### ISSUE TITLE
Add PopupPrintDialogAction to support 100% Mvvm Print dialog handling

### ISSUE THREAD

**Issue by ronin4net** [PrismLibrary/Prism#100]
Pls have a look at:

https://github.com/ronin4net/Plainion/blob/master/src/Foundation/Plainion.Prism/Interactivity/PopupPrintDialogAction.cs

It allows handling of win32 print dialog with interaction requests.

I would like to contribute this to prism if interested

**Comment by brianlagunas** [comment]
After consideration, we have decided to not include this for now.  If enough people ask for it, we will revisit this decision.
