### ISSUE TITLE
Multiple views unique connected to the same viewmodel instance

### ISSUE THREAD

**Issue by mprevot** [PrismLibrary/Prism#1003]
Hello,

I'm trying to have multiple views (in different regions) that would use the _same instance_ of a view model.
Do you recommand a way to do so ?

(for multiple view and unique viewmodel (different instances) : http://bit.ly/2nLXUaL)

Best

**Comment by brianlagunas** [comment]
In the future these types of question do not belong here, but instead should be posted on our StackOverflow tag (http://stackoverflow.com/questions/tagged/prism) or our Slack channel (https://prismslack.herokuapp.com/).

I would not recommend doing that at all. That is a code smell to me. I would re-evaluate your design.  If you absolutely had to do it, just register the ViewModel instance in the container as a singleton.  Like I said, don't do it.

**Comment by mprevot** [comment]
Thank you of the pieces of advice, I'll do what you proposed. 
I'll go on SO next time.
Many thanks.
