### ISSUE TITLE
Multiple Menu

### ISSUE THREAD

**Issue by abdulraooof** [PrismLibrary/Prism#1004]
I have different menus according to user role I put all the user and admin menus in different views and register  view with menu region. When I sign in with admin id all the menus are fine but when I sign out and sign in again with user id menu not change to user role, still show admin menu even I set KeepAlive to false.

Any suggestion what should I do?
Thanks in advance!

**Comment by brianlagunas** [comment]
This type of question should be asked on StackOverflow http://stackoverflow.com/questions/tagged/prism

Make sure you provide more information in your question when you post it to SO, because no one can help as it is unclear exactly what could be causing your issue.

**Comment by abdulraooof** [comment]
How to clear all the registrations of view with regions
if i have

**Comment by abdulraooof** [comment]
_regionManager.RegisterViewWithRegion(RegionNames.AdminMainContentRegion, typeof(Views.Customers.Customers));
            _regionManager.RegisterViewWithRegion(RegionNames.AdminMainContentRegion, typeof(Views.Employees.Employees));
            _regionManager.RegisterViewWithRegion(RegionNames.AdminMainContentRegion, typeof(Views.Vehicles.Vehicles));
            _regionManager.RegisterViewWithRegion(RegionNames.AdminMainContentRegion, typeof(Views.Vendors.Vendors));

Then how to clear all these registrations?

**Comment by abdulraooof** [comment]
I solved it with an alternate solution
