### ISSUE TITLE
(possible) bug issue: No Application.ResourceDictionary in the app.xaml (Autofac version)?

### ISSUE THREAD

**Issue by stevejbrother** [PrismLibrary/Prism#1005]
Hi guys,

I just started a new Xamarin Forms Prism project using Autofac (my favorite), and I wanted to set a style for some ContentPages. Only thing is that there's no way to add the style into the ResourceDictionary. Was that overlooked? Or am I missing a step?

**Comment by brianlagunas** [comment]
You're doing it wrong :)

Read this:  https://developer.xamarin.com/guides/xamarin-forms/xaml/resource-dictionaries/
