### ISSUE TITLE
Destroy form IDestructible not fired when navigating back from deep linking

### ISSUE THREAD

**Issue by raV720** [PrismLibrary/Prism#1006]
- Platform: UWP
- Prism version: 6.3
- Xamarin version (if applicable): 2.3.3.193
- Windows 10 SDK version (if applicable): 10.0.10586.0

Do deep link navigation, for example NavigationService.NavigateAsync("Page1/Page2/Page3");
Using back button the pages Page3 and Page2 are poped but Destroy is not fired for them. Only poping "root" page - Page1 causes Destroy to be executed.
Is it expected behavior?

**Comment by brianlagunas** [comment]
are you using a Shared project or a PCL project?

**Comment by brianlagunas** [comment]
I am unable to reproduce this issue. Please provide a sample that has the issue.

**Comment by raV720** [comment]
Here is sample:
https://bitbucket.org/equo/prismidestructibletest.git

After downloading source from repo there are errors with xaml pages (InitializeComponent() method does not exists), but it compiles anyway.
Use UWP project. Set UWP project to be deployed in solution settings. Set breakpoints on Destroy methods in viewmodels. Run application, click button to navigate and then click back button - Destroy does not fire for Page3. Click second time - Destroy fires for Page2.

There is another issue (should I report it in another thread?). When navigating like this:
```
await NavigationService.NavigateAsync("NavigationPage/Page1");
await NavigationService.NavigateAsync("Page2/Page3");
```
The second navigation causes Page1 (from first navigation) to be destroyed, but since it is relative navigation it should just navigate to new pages without destroying previous, like: NavigationPage/Page1/Page2/Page3. Am I right?
This problem can be tested using provided sample - just edit code in App.cs

**Comment by nuitsjp** [comment]
When returning from Page 3 to Page 2, no Popped event has occurred.
That is the cause. But I do not know why.
It is necessary to look around that.

**Comment by brianlagunas** [comment]
That tells me there is a bug in Xamarin.Forms.  When I get time, I will set some break points in the NavigationPage.Popped event and see if it fires.

**Comment by nuitsjp** [comment]
It works correctly with normal Navigation which is not DeepLink.
There may be reasons for making DeepLink.

**Comment by brianlagunas** [comment]
XF UWP has an open bug regarding deep linking. May be related.

**Comment by AwsomeCode** [comment]
There is no proper uwp support available in xamarin forms. They better stop doing for MacOS and keep focus on current supported versions first. UWP, Android, iOS

**Comment by raV720** [comment]
Why this issue is closed?
What Xamarin.Forms bug is it related to?
What about second part of question?

**Comment by nuitsjp** [comment]
This issue is solved in Xamarin.Forms 2.3.4.224.
In Xamarin.Forms 2.3.3.193, the behavior of Android and UWP was different.
The behavior of UWP has changed with Xamarin.Forms 2.3.4.224.

But there are problems. 
Page 3 is Modal Navigation.
In the near future I will add another Issue. After examining in detail.

**Comment by raV720** [comment]
Let me know when you add another issue according to this modal navigation.

**Comment by nuitsjp** [comment]
It is okay. I will link to here.

**Comment by nuitsjp** [comment]
@raV720 The problem of modal navigation is addressed here. Please check it.
https://github.com/PrismLibrary/Prism/issues/1046
