### ISSUE TITLE
CodePlex is shutting down

### ISSUE THREAD

**Issue by dvorn** [PrismLibrary/Prism#1011]
CodePlex site is shutting down: https://blogs.msdn.microsoft.com/bharry/2017/03/31/shutting-down-codeplex/ and hence the old Prism site http://compositewpf.codeplex.com/ will be closed.  Although Brian Harry says that the site content will be archived, he explicitly mentions only

> their source code, downloads, documentation, license, and issues 

but the project also contains Discussions sections which is a source of valuable information about Prism.

@brianlagunas What can be done about that?

**Comment by brianlagunas** [comment]
I'll email Brian and find out if anything can be done. That is for raising this issue.

**Comment by tomzorz** [comment]
If there's no way to do a server-side backup you could just point httrack on it and let it create a static html archive.

**Comment by brianlagunas** [comment]
I haven't had a reply, so I am going to assume we won't get the discussions.
