### ISSUE TITLE
Navigation fails with two views of the same type inside one region

### ISSUE THREAD

**Issue by marcOcram** [PrismLibrary/Prism#1015]
### Package info

- Platform: WPF with Unity
- Prism version: 6.3.0
- Other version info: Visual Studio 2015, Windows 7

### Repro steps

The issue occurs when you register two (or more) views of the same type with the same region.
```C#
protected override void ConfigureContainer()
{
    base.ConfigureContainer();

    
    Container.RegisterType<object, SampleView>("View1", new ContainerControlledLifetimeManager(), new InjectionFactory(c => new SampleView("View1")));
    Container.RegisterType<object, SampleView>("View2", new ContainerControlledLifetimeManager(), new InjectionFactory(c => new SampleView("View2")));
}

public override void Run(bool runWithDefaultConfiguration)
{
    base.Run(runWithDefaultConfiguration);
            
    IRegionManager regionManager = Container.Resolve<IRegionManager>();
    regionManager.Regions["ContentRegion"].Add(Container.Resolve<object>("View1"), "View1");
    regionManager.Regions["ContentRegion"].Add(Container.Resolve<object>("View2"), "View2");
}
```
When you now want to navigate to the "View2" it isn't possible because the first registered view (View1) of the same type is used.
The `UnityRegionNavigationContentLoader` finds the correct instance with the specified name and then delegates to the `RegionNavigationContentLoader` to search for the type of the found view. This results in two (or more) results because there are two (or more) instances registered with the region. The `RegionNavigationService` then uses only the first result for navigation.

Is this an expected behavior?

[PrismUnitySameViewTypeSample.zip](https://github.com/PrismLibrary/Prism/files/918692/PrismUnitySameViewTypeSample.zip)

**Comment by brianlagunas** [comment]
I don't understand what you are trying to do.  If you are manually resolving objects you don't have to register your views as objects.  If you are trying to use the navigation framework (RequestNavigate) you would not register the same view type twice. You would just pass the necessary data to the view instance.
