### ISSUE TITLE
Feature Request: Expose a mapping from ViewModel type to View type

### ISSUE THREAD

**Issue by mikegottlieb** [PrismLibrary/Prism#1020]
The url path style of navigation is super useful, but it would be even better if we were able to construct that url from ViewModel types. Here is my specific scenario as an example.

I need to be able to present a modal screen that contains a view, but that view needs to support push style navigation. So I can easily wrap my view in a navigation page and achieve my results. Right now I have an extension to INavigationService that looks like this:

```
public static Task ShowModalNavPage(this INavigationService navigationService, string contentPageType, NavigationParameters parameters = null, bool animated = true)
{
    return navigationService.NavigateAsync(string.Format("NavigationPage/{0}", contentPageType), parameters, useModalNavigation: true, animated: animated);
}
```

It would be great if rather than a `string` for `contentPageType` I could pass a ViewModel type and then look up the right view and use its name to construct the uri. Without that capability I have to either pass the name of the view as a magic string or use `typeof(View).Name` which makes my ViewModel classes aware of my View types and is less than ideal.

**Comment by brianlagunas** [comment]
This is already possible by registering your types using your ViewModel name as the key
```
Container.RegisterTypeForNavigation<View>(nameof(ViewModel));
```
or even
```
Container.RegisterTypeForNavigation<View, ViewModel>(nameof(ViewModel));
```

I personally don't reference other ViewModels because that is also creating a coupling between other VMs.
