### ISSUE TITLE
XF: Unable to "PushAsync" from within MasterDetailsPage using INavigationService

### ISSUE THREAD

**Issue by MartinRobins** [PrismLibrary/Prism#1023]
When using the INavigationService it is not possible to "PushAsync" from within a MasterDetailPage.

For example, consider the following XF flow...

Within App.cs...

`MainPage = new NavigationPage(new MasterDetailPage());

`Then, within the MasterDetailPage...

`Navigation.PushAsync(new ChildPage());`

The above flow cannot be replicated using the current INavigationService functionality.

I suspect that the same will be the case when using TabbedPage too.

See also: http://stackoverflow.com/questions/43388248

**Comment by brianlagunas** [comment]
Thanks for submitting this scenario.  This should be an easy fix.  We are already handling the modal scenario.  Just need to add the logic for this scenario.  FYI, this works fine for TabbedPage as long as you aren't nesting NavigationPages, which is not recommended anyways :)

**Comment by MartinRobins** [comment]
I am no longer sure this issue is warranted.

At the time of writing, I was issuing the navigation request from within the view model of the MasterDetailPage and as a result the page that I navigated to always replaced the "Detail". I have found that if instead I request the navigation from within the view model of the page currently displayed as the "Detail" of the MasterDetailPage it works exactly as I desire and the navigation is actioned using "PushAsync" with action bars and back buttons etc..

I will leave it to you as to whether or not you want to close this issue; it is no longer a problem to me but I do not know if you wish to allow for the original scenario anyway.

**Comment by brianlagunas** [comment]
Thanks for the update. I wasn't sure how common this scenario was, or if it was even a recommended pattern for mobile development.  I may still implement it just for fun :)

**Comment by MartinRobins** [comment]
No problem. I actually discovered the solution by accident!

**Comment by brianlagunas** [comment]
I'm just now getting this, and it is recommended that you never place a MasterDetailPage inside a NavigationPage.  The only child of a NavigationPage should be a ContentPage.  In some cases a TabbedPage is acceptable.
