### ISSUE TITLE
[XF] Xamarin has deprecated OnPlatform

### ISSUE THREAD

**Issue by brianlagunas** [PrismLibrary/Prism#1025]
Since Xamarin has marked OnPlatform obsolete, we need to update Prism to remove the deprecated methods in favor of the new APIs.

http://motzcod.es/post/159463651162/device-os-xamarin-forms-obsolete-runtime-os

http://motzcod.es/post/159684940967/important-onplatform-changes-xamarin-forms?utm_content=bufferf80db&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer

**Comment by dansiegel** [comment]
Agreed but there is another [change](https://forums.xamarin.com/discussion/comment/267484) coming with OnPlatform which is the introduction of Default like the following:

```xml
<OnPlatform x:TypeArguments="string" Default="Foo">
    <On Platform="UWP, WinPhone" Value="Bar" />
</OnPlatform>
```

**Comment by brianlagunas** [comment]
I'm not sure the Prism API's will have to change, only the implementation.

**Comment by dansiegel** [comment]
Actually we never actually use OnPlatform in the registration extensions. We do however use the `Device.OS` which was also deprecated.

**Comment by brianlagunas** [comment]
What about the IDeviceService?

**Comment by dansiegel** [comment]
forgot all about that ;)

**Comment by brianlagunas** [comment]
Since Xamarin has changed the way OnPlatform works (XAML friendly only) and added a new RuntimePlatform property of type string, this is what I am thinking.

First create an Enum that wraps the string property of RuntimePlatform.
```
	public enum RuntimePlatform
	{
		Android,
		iOS,
		Windows, //2.3.4
		WinPhone,
		//WinRT, //2.3.5
		//UWP, //2.3.5
		Unknown
	}
```

Then in the IDeviceService deprecate the OnPlatform methods and add a new property of type RuntimePlatform Enum
```
		/// <summary>
		/// Gets the Platform (OS) that Xamarin.Forms is working on.
		/// </summary>
		RuntimePlatform RuntimePlatform { get; }
```
Next deprecate the RegisterTypeForNavigationOnPlatform methods for the containers.  This means that you will now be required to manually check the Device.RuntimePlatform property value to register different views based on the result.

Thoughts?

**Comment by brianlagunas** [comment]
Please check out PR #1043 to see if this is an acceptable solution to the deprecation of the OnPlatform API.

Notable changes:

**IDeviceService**
* deprecated OnPlatform methods
* added DeviceRuntimePlatform property - this mimics the XF API and returns a string
* added RuntimePlatform property which returns an Enum of type `RuntimePlatform` and wraps the XF string-based values

**RegisterTypeForNavigationOnPlatform Extensions**
* deprecated the RegisterTypeForNavigationOnPlatform signature that requires explicit platform parameters
* added new signature that accepts new IPlatform objects
_Example:_
```
Container.RegisterTypeForNavigationOnPlatform<MainPage, MainPageViewModel>("Main",
     new Platform<MainPage_Android>(RuntimePlatform.Android),
     new Platform<MainPage_iOS>(RuntimePlatform.iOS));
```

I would like your feedback on this new API.

**Comment by mackayn** [comment]
Hi Brian,

API changes make sense to me. I take it UWP will return when running on Windows10 etc or Windows 10 on a mobile device?

**Comment by mackayn** [comment]
Just curious how this will play with Forms 2.3.4 as macOS is only supported in 2.3.5-pre?

Does it just return unknown?

**Comment by brianlagunas** [comment]
@mackayn not sure, I haven't fully tested their API.  This is mimicking Xamairn.Forms API exactly as-is.

**Comment by dansiegel** [comment]
@mackayn since this is abstracting away using the XF Device class, the result should vary based on the version of XF that you use. So with 2.3.4 you'll never get macOS or UWP.
