### ISSUE TITLE
Cannot add tabs via Navigation path and select a tab to navigate to.

### ISSUE THREAD

**Issue by mattman624** [PrismLibrary/Prism#1026]
- Platform: Android 6.0.0
- Prism version: 6.3

Prism 6.3 introduced the ability to add tabs via the navigation path, which is great. For my purposes I need to both add tabs dynamically, and navigate to the tab in the middle. Using the prism TabbedNavigation project as a sample, I would like to use the path "DynamicTabbedPage?addTab=ViewA&addTab=ViewB&addTab=ViewC" in combination with "ViewB" so that the user lands on ViewB.

One solution that I tried is setting IsActive on ViewB to true, but this did not work. Another solution I tried was "DynamicTabbedPage?addTab=ViewA&addTab=ViewB&addTab=ViewC/ViewB", however this did not show any tab headers. In desperation I also tried "DynamicTabbedPage?addTab=ViewA&addTab=ViewB&addTab=ViewC/DynamicTabbedPage/ViewB", again, this resulted in no tab headers.

Is this a bug or a feature that could be added?

Thank you

**Comment by brianlagunas** [comment]
> Prism 6.3 introduced the ability to add tabs via the navigation path

No, this was not a feature added to Prism and is not currently supported.

You can select an existing tab using NavigateAsync("TabbedPage/SelectedTab"), but the tab must exist or it will not be selected, but rather a new page will be created an navigated to instead.

**Comment by dansiegel** [comment]
Prism 6.3 did not add the ability to add tabs dynamically. The sample is how you can accomplish it on your own, but that's nothing new. That said it should hopefully be there in the next release.

If you look at the [DynamicTabbedPage](https://github.com/PrismLibrary/Prism-Samples-Forms/blob/master/TabbedNavigation/TabbedNavigation/Views/DynamicTabbedPage.xaml.cs#L21) you will notice that we are creating the tabs there.

**Comment by mattman624** [comment]
@dansiegel Thanks for pointing that out. 
@brianlagunas Thank you for the quick reply.
