### ISSUE TITLE
Support macOS

### ISSUE THREAD

**Issue by kdawg1406** [PrismLibrary/Prism#1027]
Please consider support macOS for Xamarin.Forms.

Thanks!

Karl

**Comment by dansiegel** [comment]
@kdawg1406 already ahead of you... before we can make Prism support MacOS we have to determine what containers even support it... currently none of the 4 containers offer the support we need.

- _Autofac_: Currently supports NetStandard1.1 which is compatible with MacOS, unfortunately this isn't compatible with Prism at the moment.
- _DryIoc_: I have already filed an [issue](https://bitbucket.org/dadhi/dryioc/issues/461/nuget-macos-support) with @dadhi 
- _Ninject_: I've also filed an [issue](https://github.com/onovotny/ninject/issues/10) with @onovotny
- _Unity_: Is pretty much a dead project and doesn't install on Xamarin Mac projects so I don't see this being the DI container of choice if you want to support MacOS

**Comment by kdawg1406** [comment]
@dansiegel thank you for the quick response.  Bummer about Unity, have always used it.  Sounds like it will just be awhile while products and API's can catch up to the ever changing world that is our environment.

Best,

Karl

**Comment by kdawg1406** [comment]
@dansiegel does not seem like a big deal.

From here:  https://blog.xamarin.com/preview-bringing-macos-to-xamarin-forms/?utm_medium=social&utm_campaign=blog&utm_source=twitter&utm_content=macos-for-xamarinforms-preview

Not All NuGets are Ready for macOS
In order to work in a macOS project, packages must target **xamarinmac20.** You may find that some of your beloved libraries do not yet support macOS. What can you do? Kindly send a request to the project’s maintainer to add it. Until they have support, you may need to look for alternatives.

**Comment by dansiegel** [comment]
@dadhi released a new version this morning that is compatible with macOS and the current Prism packages. This will at least give us a path for getting out an update that supports macOS while we work on NetStandard.

**Comment by djcparker** [comment]
@dansiegel might pay to file the ninject issue with the main ninject project? looks like there is activity there but not on orens?...  (I don't use ninject, was just poking around :) )

**Comment by dansiegel** [comment]
@djcparker I was actually just noticing that last night. I know Oren has usually been one of the first one to convert libraries over to NetStandard.

**Comment by djcparker** [comment]
@dansiegel very true, I don't know how Oren finds time to contribute to so many projects...and keep them updated... I imagine he will get to that issue soon enough :)

**Comment by brianlagunas** [comment]
Done!

**Comment by brianlagunas** [comment]
We'll be pushing nuget packages as soon as we get the CI details done
