### ISSUE TITLE
NavigationParameters issue

### ISSUE THREAD

**Issue by grandtiger** [PrismLibrary/Prism#103]
I tried to upgrade all Prism 5 Quickstarts examples to Prism 6, but found that the View-Switching Navigation_Desktop project no longer works. After some debugging, I found out that the change of NavigationParameters from IEnumerable<KeyValuePair<string, object>> to Dictionary<string, object> broke it. Specifically, the old version allow duplicates, but new version doesn't. It causes exception in several places, some can be changed in the example code, but others will require changes to the Prism library. For example, in NavigationContext.cs, the following constructor
```
public NavigationContext(IRegionNavigationService navigationService, Uri uri, NavigationParameters navigationParameters)
```
The arguments passed in have uri = "entry.Uri = {ContactsView?Show=Details}", and navigationParameters = "entry.Parameters[0] = {[Show, Details]}", which causes key duplication (ArgumentException) in the following method.

I am relatively new to this framework, and not sure what's the right way to move this forward. Could you kindly look into this and fix it?

Thanks a lot!

```
        private void GetNavigationParameters(NavigationParameters navigationParameters)
        {
            if (this.Parameters == null || this.NavigationService == null || this.NavigationService.Region == null)
            {
                this.Parameters = new NavigationParameters();
                return;
            }

            if (navigationParameters != null)
            { 
                foreach (KeyValuePair<string, object> navigationParameter in navigationParameters)
                {
                    this.Parameters.Add(navigationParameter.Key, navigationParameter.Value);
                }
            }
        }
```

A simple change like the following appears to work, but I am not sure about the full implication of such a change. Particularly, I don't know why Prism 5 allows duplicate.

```
                    if (!Parameters.ContainsKey(navigationParameter.Key))
                    {
                        Parameters.Add(navigationParameter.Key, navigationParameter.Value);   
                    }                    
```

**Comment by briannoyes** [comment]
Good catch, we will look into it. I think the solution in this case is just that when working with a dictionary you should never blindly try to add or access something by key, you need to do a ContainsKey check first.

**Comment by brianlagunas** [comment]
Yes, great catch.  It seems that for some reason, in the past Prism allowed you to have duplicate parameter keys.  When we changed it to Dictionary, this was no longer supported.  We believe this is a good thing.

I actually consider the old behavior a bug.  There should be no reason to have a duplicate parameter.

This has been fixed.

**Comment by grandtiger** [comment]
Thank you very much for the quick fix! I really look forward to the 6.0 RTM Release!

**Comment by brianlagunas** [comment]
We actually just converted this back to the original API. It was too large of a breaking change for no real benefit.

**Comment by timrobuck** [comment]
Attempting a first prism 6 wpf project, it demands composite views.  The only example i have found on github or the internet is one of your quickstarts, but it uses prism.composition nuget that is no longer supported. Do you have any example doing this with prism.wpf.   If so please send or point me to it. Thanks, Tim

**Comment by dvorn** [comment]
@timrobuck  I guess the prism.composition nuget package was left in View-Switching Navigation sample by mistake.  Just remove the reference to the package.  It is not used.
