### ISSUE TITLE
Regex to replace obsolete OnPropertyChanged usages?

### ISSUE THREAD

**Issue by hardcodet** [PrismLibrary/Prism#1031]
Since OnPropertyChanged(Expression) has been marked obsolete and is bound to go away at some point, does anybody have a regex to globally fix an app? Manually replacing all occurrences over all apps sounds super tedious.

So, we would have to go from

    OnPropertyChanged(() => SelectedTabIndex);

to

    RaisePropertyChanged(nameof(SelectedTabIndex));

My Regex-Fu is weak, so not having to reinvent that wheel would be great :)

**Comment by brianlagunas** [comment]
Find: `OnPropertyChanged\(\(\) => (.+)\);`
Replace: `RaisePropertyChanged(nameof($1));`

**Comment by bartlannoeye** [comment]
@brianlagunas should we put this in the release notes or the obsolete comment (or both)?

**Comment by hardcodet** [comment]
Works like a charm - thanks!

I'd second to put this in prominently, since every dev who is working with Prism currently will have to deal with that sooner or later - maybe put it in the docs, and link to the docs from the Obsolete comment?

**Comment by brianlagunas** [comment]
That's a great idea!  I put it on my TODO list :)
