### ISSUE TITLE
Getting NavigationService in static context?

### ISSUE THREAD

**Issue by hardcodet** [PrismLibrary/Prism#1032]
Maybe a dumb question, but: I would like to initiate navigation based on an incoming push message. This is handled globally, so I don't really know my currently active view model, which would have a reference to a NavigationService. What is the recommended pattern here (I want to navigate to an absolute path, so the current navigation stack doesn't matter)?

**Comment by dansiegel** [comment]
You might go about it by adding a public getter for the NavigationService within your application:

```cs
public INavigationService GetNavigationService() => 
     CreateNavigationService();
```

Then from your Push message handler you could do:

```cs
var navigationService = (Xamarin.Forms.Application.Current as App).GetNavigationService();
navigationService.NavigateAsync("Some/Path/You/Determine");
```

**Comment by hardcodet** [comment]
I didn't know about CreateNavigationService - I was mostly concerned about just getting an instance through DI (since I think Prism has different instances for each view model). Ended up with a similar implementation - thanks!

        public static INavigationService AppNavigationService => (Current as App)?.CreateNavigationService();

**Comment by karlingen** [comment]
@dansiegel any ideas on how to achieve this with the latest `7.1` version?

**Comment by dansiegel** [comment]
@karlfl Prism is open source... if you want to get an idea of how something is done, it's always a great idea to look at the [source code](
https://github.com/PrismLibrary/Prism/blob/master/Source/Xamarin/Prism.Forms/PrismApplicationBase.cs#L115).
