### ISSUE TITLE
SimpleInjector for WPF

### ISSUE THREAD

**Issue by rdrrichards** [PrismLibrary/Prism#1036]
I am interested in building a SimpleInjector bootstrapper for Prism WPF. Is there any interest in an effort toward this?

I searched the open and closed issues and pull requests, but only found SimpleInjector items related to UWP.

I don’t want to start on this if someone else has it in the works. From what I can tell, it is not.

Should I pursue this, or does Prism already have support for as many IoC containers as is needed at this point? Or, are there other plans, perhaps limitations, when it comes to SimpleInjector? Considering that Unity seems to be slipping away, SimpleInjector could be a nice replacement in the future.

**Comment by brianlagunas** [comment]
Actually SimpleInjector is not a container that has had a lot of requests.  having said that, if support was to be added, it must be added to all Prism platforms.  I am no longer going to allow a container to only support one Prism platform.

I will say that this may become a challenging task as SimpleINjector does not allow to resolve objects by name, which is core to Prism navigation:  https://simpleinjector.readthedocs.io/en/latest/howto.html#resolve-instances-by-key

You would need to build a custom implementation for this.

**Comment by rdrrichards** [comment]
Sounds a little like a no interest scenario, at least at the moment. For some reason, it surprises me that there are not many requests for SimpleInjector. Then again, there are plenty of IoC containers to choose from!

I may create a branch and get a good idea of the amount of work this would take. Thanks for pointing out some of the challenges ahead of time, I appreciate that. I didn't think about resolving by name, but that *would* add to this. SimpleInjector may be not so simple in this context.

Thanks!

**Comment by dansiegel** [comment]
@rdrrichards I started looking into this a while back for Xamarin Forms. Feel free to check out the [branch](https://github.com/dansiegel/Prism/tree/feature/SimpleInjector-XF/Source/Xamarin/Prism.SimpleInjector.Forms)

**Comment by rdrrichards** [comment]
@dansiegel Dan, Thanks! I am curious, what stopped you from moving forward with a PR on this? Lack of time, found that it wasn't worth the effort, not feasible, something else?

**Comment by dansiegel** [comment]
There were a couple of reasons why I stopped. For one we started looking at converting the library over to NetStandard which has taken precedence. Also there was some more debugging and testing I needed to do which I haven't devoted the time to yet.
