### ISSUE TITLE
Navigation stops working on a ContainerControlledLifetimeManager viewmodel

### ISSUE THREAD

**Issue by osicka** [PrismLibrary/Prism#1038]
- Platform: Xamarin Forms
- Prism version: 6.3
- Xamarin version: 2.3.4.231

From my main menu, I navigate to Page 1 which is wired up to a ContainerControlledLifetimeManager viewmodel. I then use NavigateAsync to go to a Page 2 which works fine. I can also use GoBackAsync to get back to the main menu.

I go back to the main menu and navigate to Page 1 a second time the page shows properly with the viewmodel data. However navigation stops working.

**View Model Registration**
`Container.RegisterType<PageViewModel>(new ContainerControlledLifetimeManager());
`

**View Model Constructor**
```
public PageViewModel(IUnityContainer container, INavigationService navigationService)
{
    _container = container;
    _navigationService = navigationService;
}
```

If I remove the View Model Registration so that the view model is created every time the issue goes away.

I am guessing that the issue is caused by the _navigationService no longer being valid as it was setup in the initial view model construction.

Is there a way to refresh the _navigationService on subsequent uses, maybe in OnNavigatedTo?

Thanks
Anthony

**Comment by dansiegel** [comment]
Using a singleton ViewModel is not supported, particularly the moment you want Navigation. The Navigation Service has to have the proper context of the View since Navigation occurs from the context of the page in which you are Navigating from. When you first Navigate to a View, then Pop it off the Navigation Stack you now have orphaned the View and Navigation will not work. Notice I said orphaned and not disposed.

**Comment by osicka** [comment]
Thanks for your quick reply. 

The view model fetches a lot of data from the server so I was trying to save on redundant calls. (mobile data is expensive in Australia) I will just offload this data into a singleton child class and resolve this inside my view model.

**Comment by brianlagunas** [comment]
@osicka Sorry for the late reply, just got back from MS Build.  I would suggest caching your data, not the VIewModels.

**Comment by osicka** [comment]
No problem, that is what I have done and its all working fine.

**Comment by dansiegel** [comment]
@osicka have you considered using the Azure Mobile Client or Realm to store your data locally that way you can reduce your network load?

**Comment by osicka** [comment]
It's a work roster where the data changes frequently and becomes stale quickly so I don't need to store it locally. I just didn't want it to be reloaded every time the page was entered.

 I am very happy with the way it is working now.
