### ISSUE TITLE
FYI: Latest VS 2017 update breaks Android performance with Prism

### ISSUE THREAD

**Issue by hardcodet** [PrismLibrary/Prism#1041]
This is more FYI than anything actionable: It appears that the latest Xamarin update that was rolled out with VS 2017 update 2 botched performance for Android in certain cases, and Prism apps are affected. My app's performance degraded so badly that it's basically 100% broken at this point.

https://forums.xamarin.com/discussion/94505/15-2-preview-1-performance-degradation#latest

**Comment by brianlagunas** [comment]
Thanks for the heads up.  It seems Xamarin has been made well aware of this from many other users.  Here is the bug we can use for tracking:

https://bugzilla.xamarin.com/show_bug.cgi?id=56240

This was the recommendation fro Xamarin:

> For those of you on VS2015 who would like to downgrade, you can download the previous release from the Xamarin account page as mentioned here (in the bug link). If you are using VS2017, to downgrade go to [this page](https://www.visualstudio.com/vs/older-downloads/) and sign in with your MSDN account or sign up for VS Dev Essentials in order to access the download for 15.0.

**Comment by brianlagunas** [comment]
Xamarin says this is fixed now :)

**Comment by NewBLife** [comment]
Fixed a performance dedgration sometimes occuring in Xamairn Android apps. 
https://www.visualstudio.com/en-us/news/releasenotes/vs2017-relnotes
