### ISSUE TITLE
[XF]When calling NavigateAsync with NavigationPage, old page's Destroy on the stack is not called

### ISSUE THREAD

**Issue by nuitsjp** [PrismLibrary/Prism#1045]
### Package info

- Platform: Xamarin
- Prism version: 6.3
- Xamarin version (if applicable): any
- Windows 10 SDK version (if applicable): any

### Repro steps
When NavigateAsync of the navigation object of NavigationPage is called, PopToRootAsync of NavigationStack is called.
https://github.com/PrismLibrary/Prism/blob/master/Source/Xamarin/Prism.Forms/Navigation/PageNavigationService.cs#L220
https://github.com/PrismLibrary/Prism/blob/master/Source/Xamarin/Prism.Forms/Navigation/PageNavigationService.cs#L229

At this time, Destroy of popned page is not called.

**Comment by brianlagunas** [comment]
Thanks again for another great find and fix!
