### ISSUE TITLE
[XF]When calling DeepLink from Navigation Stack, the second page becomes Modal navigation

### ISSUE THREAD

**Issue by nuitsjp** [PrismLibrary/Prism#1046]
### Package info

- Platform: Xamarin
- Prism version: 6.3.0
- Xamarin version (if applicable): any
- Windows 10 SDK version (if applicable): any
- Other version info:

### Repro steps
Please look at this code.
```cs
navigationService.NavigationAsync("NavigationPage/ContentPageA");
navigationService.NavigationAsync("ContentPageB/ContentPageC");
```
At this time, ContentPageB becomes Hierarchical Navigation.
However, ContentPageC becomes Modal Navigation.

**Comment by brianlagunas** [comment]
This is dependent on the following Xamarin.Forms bug being fixed:

https://bugzilla.xamarin.com/show_bug.cgi?id=56593

**Comment by brianlagunas** [comment]
For now the work around is to set the useModalNavigation = false.

**Comment by beylkhanovdamir** [comment]
the same problem in deep linking for me now

**Comment by brianlagunas** [comment]
Fixed!
