### ISSUE TITLE
HttpClient into constructor class not work

### ISSUE THREAD

**Issue by brux88** [PrismLibrary/Prism#1052]
### Package info

- Platform: Android(xamarin form)
- Prism version: 6.3.0
- Xamarin version 2.3.4.224

### Repro steps

Hello, I'm noticing a problem, if I call a service that makes a http client post call within the viewmodel builder, i will not work, and i will not leave any errors, i just jump it if instead i same service i put it all Inside a deleegatecommand works, what can it be?
this not work:
```
` public LoginPageViewModel(INavigationService navigationService,ILoginService loginService)
        {
            _navigationService = navigationService;
            _loginService = loginService;
             GoRootPage(); //  GoRootPage().Wait(); i try but not work, the ui freeze

        }`
```
this work:
```
`public LoginPageViewModel(INavigationService navigationService,ILoginService loginService)
{
            _navigationService = navigationService;
            _loginService = loginService;
            goRootPage = new DelegateCommand(GoRootPage);

}

private async Task 


GoRootPage()
{
            var result = await _loginService.LoginCheck(LoginModel.Email, LoginModel.Password, _hostname:LoginModel.Hostname);

}`
```

Can it be due to the lack of await? As I can solve, I need to make some calls at the beginning of the view upload

**Comment by brux88** [comment]
i try add Wait() but freeze

**Comment by brianlagunas** [comment]
I'm sorry, but this is not the correct place to ask thee types of questions.  This forum is for Prism support questions only.  I would suggest posting your question on StackOverflow instead.  You are more likely to get an answer there.

Thanks
