### ISSUE TITLE
[XF] When deep linking within NavigationPage, page order is reversed

### ISSUE THREAD

**Issue by brianlagunas** [PrismLibrary/Prism#1054]
This is a Xamarin.Forms bug and we are awaiting a fix:  https://bugzilla.xamarin.com/show_bug.cgi?id=56593

When trying to build up a navigation stack and pushing from a Page that has a NavigationPage parent, the pages are added in the incorrect order, and the middle page is broken.

Given the following example, the expectation is that the final navigation stack would be: ViewA/ViewB/ViewC

Unfortunately the result is ViewA/ViewC/ViewB. Notice that page that should be last is in the middle.  Not only that, but ViewC is completely broken and no bindings are retained.  Not to mention all the Titles are messed up and are showing the wrong values.
```
	public partial class App : Application
	{
		public App()
		{			
			MainPage = new NavigationPage(new ViewA());
		}
	}

	public class ViewA : ContentPage
	{
		public ViewA()
		{
			Title = "View A";
			Button btn = new Button() { Text = "Navigate from ViewA", HorizontalOptions = LayoutOptions.Center, VerticalOptions = LayoutOptions.Center };
			btn.Clicked += Btn_Clicked;
			Content = btn;

		}

		private async void Btn_Clicked(object sender, System.EventArgs e)
		{
			var viewB = new ViewB();
			var viewC = new ViewC();

			await viewB.Navigation.PushAsync(viewC);

			await Navigation.PushAsync(viewB);
		}
	}

	public class ViewB : ContentPage
	{
		public ViewB()
		{
			Title = "View B";
			Content = new Label() { Text = "View B" };
		}
	}

	public class ViewC : ContentPage
	{
		public ViewC()
		{
			Title = "ViewC";
			Content = new Label() { Text = "ViewC" };
		}
	}
```

**Comment by beylkhanovdamir** [comment]
currently I have temporary resolved this issue with separate navigation to the middle page, then from the middle page I'm navigating to the last page inside **OnNavigatedTo** method on the middle page

**Comment by brianlagunas** [comment]
Fixed!
