### ISSUE TITLE
Push Popup

### ISSUE THREAD

**Issue by brux88** [PrismLibrary/Prism#1055]
Hi,
I'm implementing a navigation service, I wanted to have a click alert button on a button from my viewmodel, I saw the Prism.Plugin.Popups plugin, but I do not work.
I wanted to know if there is a way to prism to show a message alert

**Comment by dansiegel** [comment]
@brux88 you should ask how to questions on StackOverflow or Slack. Your question on the Popup library was already addressed in dansiegel/Prism.Plugin.Popups#44. That said you're trying to show a simple alert you should read the [docs](http://prismlibrary.readthedocs.io/en/latest/Xamarin-Forms/4-Page-Dialog-Service/).
