### ISSUE TITLE
I am trying to navigate from login page to a prism tabbed page but getting error

### ISSUE THREAD

**Issue by ShahriatHossain** [PrismLibrary/Prism#1056]
Here is my code below:
       ```
DelegateCommand _loginCommand;
        public DelegateCommand LoginCommand => _loginCommand != null ?
            _loginCommand : (_loginCommand = new DelegateCommand(LoginAsync));

        private async void LoginAsync()
        {
            await _navigationService.NavigateAsync("ChannelsTabPage", null, false, false);
        }
```
```
public App(IPlatformInitializer initializer = null) : base(initializer) { }

        protected override void OnInitialized()
        {
            InitializeComponent();

            NavigationService.NavigateAsync("LoginPage");
        }
```
but I am getting such exception like below:

PushAsync is not supported globally on Android, please use a NavigationPage - Xamarin.Forms

has any solution for such problem?

**Comment by brianlagunas** [comment]
You are setting the useModalNavigation to false in your navigation call.  You can only do this if your pages are wrapped in a NavigationPage.  So either wrap your root page in a navigationPage, or don't set the useModalNavigation property to false.
