### ISSUE TITLE
RaisePropertyChanged: squiggly line annoyance

### ISSUE THREAD

**Issue by znakeeye** [PrismLibrary/Prism#1059]
With ReSharper you see the problem:

![raisepropertychanged-annoyance](https://cloud.githubusercontent.com/assets/958469/26402199/8ef0d5ac-4089-11e7-9a0f-822449d9f587.png)

And [here](https://stackoverflow.com/questions/31875261/resharper-highlights-use-of-nameof-with-explicit-argument-passed-to-parameter-w) they mention that the ReSharper check is indeed correct. Apparently, GalaSoft.MVVMLight had the same problem.

When I saw the newly added "RaisePropertyChanged" method I thought that you would drop the CallerMemberNameAttribute hackiness, but that's not the case.

**Comment by brianlagunas** [comment]
Resharper isn't correct.  While the CallerMemberName attribute does automatically obtain the method or property name of the caller to the method, you apply the CallerMemberName attribute to an optional parameter that has a default value. You **must** specify an explicit default value for the optional parameter. You can't apply this attribute to parameters that aren't specified as optional.

Also keep in mind that methods are used in a variety of scenarios which means that you are't always calling RaisePropertyChnaged from the corresponding property.  For example; in a FirstName and LastName properties you may call `RaisePropertChanged(nameof(FullName));`.  This is the intended design of the attribute.  Resharper is wrong.
