### ISSUE TITLE
[WPF] Create 6.0 RTM NuGet packages

### ISSUE THREAD

**Issue by brianlagunas** [PrismLibrary/Prism#106]
I need to create the RTM NuGet packages for Prism for WPF 6.0.

This will include the Prism.dll, Prism.Wpf.dll, and all supported DI Containers.

**Comment by brianlagunas** [comment]
Done.  Prism 6 is live on NuGet.

**Comment by Michael-DST** [comment]
Awesome... congratulations Team Brian and the rest of the hard-working team here!  Exciting to watch this actively develop!!

**Comment by TioLuiso** [comment]
Cannot wait to update my solution for Prism6. Awesome!!!
