### ISSUE TITLE
Suggestion: make testing easier

### ISSUE THREAD

**Issue by CarlosAdrianM** [PrismLibrary/Prism#108]
I am not sure this is the right place for a suggestion, if it is not, move it to the right place, please.

I think testing a ViewModel in Prism is really difficult, so it would be great to have a template for new modules in Prism, so you have your View, your ViewModel and your tests project.

In ASP, for example, you can create a new project and the template has a "Create test project" checkbox. I would like something similar to that for new Prism projects (new module projects above all).

Thank you, and congratulations for your great work with Prism!!!

**Comment by bartlannoeye** [comment]
Project/Item templates are on the backlog (see #13). As things were changing a lot in the code base, it was too early to create templates, but I suppose this will gain priority once Prism 6 goes RTM.

**Comment by CarlosAdrianM** [comment]
You are right, sorry. I will wait until RTM :)

Thank you
