### ISSUE TITLE
Module initialization after Shell initialization in AutofacBootstrapper

### ISSUE THREAD

**Issue by nivedano** [PrismLibrary/Prism#1080]
AutofacBootstrapper.Run implement initialization logic, so that Shell is initialized before Modules. This make impossible to resolve neigher shell's dependencies, not a shell itself with types from modules.

If there're no some specific reasons for such a harsh restriction (what?), please change the init order.

![image](https://user-images.githubusercontent.com/26411464/26979753-93256c1c-4d38-11e7-95e0-f73cc4f4e27f.png)

**Comment by brianlagunas** [comment]
The shell must exist first as the modules are initialized and the regions must exist or when the initialize method is called form the IModule, not views would be injected.  We cannot change the order.  I would challenge you why you are wanting to inject module classes as a dependency in your shell.  Something doesn't seem right there.

**Comment by nivedano** [comment]
Shell or other core components may themselves be dep-injected from modules. I want my host app to load different shells, for example. Or to allow shell some logic to construct itself. Of course, you can make a proxy, defer some initializations or do some other tricks, but the fixed order of initializations is restrictive. Regions look like exactly as such proxies to allow
I accept that there're substantial reasons for such design, but they're not the only possible ways to go. 
It would be good to have initialization of modules two-phased, pre-shell (after module catalog and container builder are configured) and post-shell (as now) inits.

**Comment by brianlagunas** [comment]
Any dependencies the Shell has must be registered in the Shell assembly.  You can have dynamic shells no problem, you just have to make sure you dependencies are registered in time so they can be used.
