### ISSUE TITLE
Sandbox UWP

### ISSUE THREAD

**Issue by rubgithub** [PrismLibrary/Prism#1084]
Can I submit simple examples `HelloWorld` ( `AutoFac` and `Simple Inject`) to Prism/Sandbox/Windows10 ?

**Comment by dansiegel** [comment]
The Sandbox is not our official Samples. There is a [sample repo](https://github.com/PrismLibrary/Prism-Samples-Windows) for each platform. That said the difference between containers should be minimal and limited to the way each container handles registrations. With only that as a difference I don't much see the value of a Hello World for each container when you simply need to look at the docs for the container you want to use (if you aren't already using that container).

**Comment by bartlannoeye** [comment]
Like @dansiegel just mentioned, sandbox is our testbed not the real sample repro. And we decided against having (read maintaining) equal samples for all supported IoC containers.

If you really want to put time into this, please do it in the format of **markdown documentation** (under /docs/UWP) showing the difference between the containers. That would be much appreciated.

This way people can read how to do and we don't have to support a multiple of the current amount of samples _(which need some effort, as I was showing the SplitView sample to a colleague just last night and noticed there's some cleaning up to do ... which will have to wait until the rewrite of some UWP fundamentals_)
