### ISSUE TITLE
IsNavigationTarget does not work as expected

### ISSUE THREAD

**Issue by aytacasan** [PrismLibrary/Prism#1088]
Hi @brianlagunas,

I'm working on a fairly complex and large financial project. Because of simplicity i'll not go into much detail but try to tell enough detail about the problem. Using prism for WPF latest stable version. Don't know am i missing so simple thing? Anyway my problem is;

I have a ViewModel base class that implements many interfaces. One of them is IConfirmNavigationRequest interface. In this class all navigation methods are virtual. Like below;
```
        private IRegionNavigationService _navigationService;

        public virtual bool IsNavigationTarget(NavigationContext navigationContext)
        {
            return true;
        }

        public virtual void OnNavigatedFrom(NavigationContext navigationContext)
        {

        }

        public virtual void OnNavigatedTo(NavigationContext navigationContext)
        {
            _navigationService = navigationContext.NavigationService;
        }

        public virtual void ConfirmNavigationRequest(NavigationContext navigationContext, Action<bool> continuationCallback)
        {
            continuationCallback(true);
        }
```
Also i have another view model which is inherited from base ViewModel and overriding all virtual methods. Even there is a criteria about "is it navigation target or not" i simple write return false value inside IsNavigationTarget method for create new tab for each navigation request.
```
        public override bool IsNavigationTarget(NavigationContext navigationContext)
        {
            return false;
            //var nameParameter = (string) navigationContext.Parameters[WellKnownParameterKeys.FileName];
            //return nameParameter == Name;
        }

        public override void OnNavigatedFrom(NavigationContext navigationContext)
        {
            base.OnNavigatedFrom(navigationContext);
        }

        public override void OnNavigatedTo(NavigationContext navigationContext)
        {
            base.OnNavigatedTo(navigationContext);

            Name = (string) navigationContext.Parameters[WellKnownParameterKeys.FileName];
            Content = (string) navigationContext.Parameters[WellKnownParameterKeys.FileContent];
        }

        public override void ConfirmNavigationRequest(NavigationContext navigationContext, Action<bool> continuationCallback)
        {
            base.ConfirmNavigationRequest(navigationContext, continuationCallback);
        }
```
When i put break points on IsNavigationTarget & OnNavigatedTo methods i see methods working correctly. I can not see any problem. But each navigation request using same tab insistently. Before i used view discovery and injection many times but i'm new extended navigation, so could you please tell me what i missing?

Update : Also my ViewModel base class implementing IRegionMemberLifetime too. Like below;

```
        public virtual bool KeepAlive
        {
            get { return false; }
        }

```

Also i'm overriding KeepAlive property and returning true value for derived view model. For not remove deactivated view/tab from region by region manager.

Regards,
Aytac Asan

**Comment by aytacasan** [comment]
@bartlannoeye,

I follow prism documentation and do all steps like it's mentioned. But i do a mistake and override KeepAlive for wrong view model. So normally it's not worked as expected. But i fix it and now it's working. Sorry about that.

Plus, I don't know can i deactivate or how can i deactivate an issue. So please deactivate this issue for me.

Regards,
Aytac Asan

**Comment by brianlagunas** [comment]
Great!  I am glad you figured it out.  I will close the issue for you.

**Comment by aytacasan** [comment]
@brianlagunas  thank you so much!
