### ISSUE TITLE
What is the best way to manage ActiveViewModel & ViewModels inside tab region?

### ISSUE THREAD

**Issue by aytacasan** [PrismLibrary/Prism#1092]
Hi @brianlagunas,

I'm trying to develop an editor. I have two View/ViewModels;

CodeEditorView/CodeEditorViewModel & CodeFileView/CodeFileViewModel

CodeEditorView has a prism's tab region and for add new tab (CodeFileEditor) to that region i'm using prism's extended navigation feature and using region manager's RequestNavigate method.

Any moment i want to access all tabs and selected tab. Sample scenarios;

1. If user try to close CodeEditor. I have to check if any CodeFile is dirty then want to ask "are you want to save content?" This is the reason of need all tabs in that region.
2. At CodeEditor Menu there is an option "Show Line Numbers". When user select it i want to show line numbers for only active/selected CodeFile.

For accomplish that i add two property in my CodeEditorViewModel;
```
        public ICodeFileViewModel SelectedCodeFileViewModel
        {
            get
            {
                var activeViews = _regionManager.Regions[WellKnownRegionNames.CodeFileRegion].ActiveViews;
                return ((CodeFileView) activeViews?.ToList()[0])?.DataContext as ICodeFileViewModel;
            }
        }

        public IEnumerable<ICodeFileViewModel> CodeFileViewModels
        {
            get
            {
                var views = _regionManager.Regions[WellKnownRegionNames.CodeFileRegion].Views;
                return views.Select(view => ((CodeFileView) view).DataContext as ICodeFileViewModel);
            }
        }
```
But i'm not sure is this an effective and/or right solution, especially in terms of MVVM pattern. I'm accessing CodeFileView.DataContext inside of CodeEditorViewModel! Could you please tell me, what is your simple/effective solution about this requirement?

PS : Using prism for WPF latest stable version. 

Regards,
Aytac Asan

**Comment by brianlagunas** [comment]
To know which ViewModel is the active tab use the IActiveAware interface.  For command to invoke against the active tab, use a CompositeCommand and set the ctor param to `true` to monitor the IsActive property.

**Comment by aytacasan** [comment]
@brianlagunas,

Thanks for your answer. Before I can not connect with each other but, after read your answer, i remember that prism documentation (Part 06 Advanced MVVM) mentioning my problem and it's solution exactly and clearly. Sorry for take your time with this stupid question.

Regards,
Aytac Asan

**Comment by brianlagunas** [comment]
No problem.  No stupid question.  The community is here to help each other learn and be successful.

**Comment by aytacasan** [comment]
You are right. Even so, thanks for your understanding @brianlagunas.
