### ISSUE TITLE
OnPropertyChanged(string.Empty); doesn't refresh the viewmodel as expected

### ISSUE THREAD

**Issue by John-Burbidge** [PrismLibrary/Prism#1095]
*Use GitHub issues for __bugs in Prism and feature requests only__. If you have a question how to implement something using Prism or a bug in your app that might be related to Prism, please post your question on [StackOverflow](http://stackoverflow.com/tags/prism) (which we monitor as well).*

Please provide as much detail as possible (and feel free to remove unused properties):

### Package info

- Platform: Xamarin.Forms PCL project but the platform is iOS
- Prism version: 6.3.0
- Xamarin version (if applicable): Xamarin.Forms.2.3.3.193

### Repro steps

OnPropertyChanged(string.Empty); doesn't refresh the viewmodel.

An example would be as below. 

I'm hoping to change the value of PhotoCount when the collection changes but it remains the same.   I can only seem to have Prism show changes if I use SetValue on a property.

Am I doing something wrong?

```
public class Example : BindableBase
{	
	private ObservableCollection<Photo> _selectedPhotos;
	public ObservableCollection<Photo> SelectedPhotos
	{
		get
		{
			return _selectedPhotos;
		}
		set
		{

			SetValue(ref _selectedPhotos, value);
			_selectedPhotos.CollectionChanged += (sender, args) =>
			{
				OnPropertyChanged(string.Empty);
			};
		}
	}
	
	private int _photoCount;
	public int PhotoCount {get{ return SelectedPhotos.Count; }}
}
```

**Comment by nuitsjp** [comment]
OnPropertyChanged argument is name of property that you want to notify for updates.
That is, string.Empty is not valid.
This is not problem of Prism.

I will write like this.
```cs
    public class Example : BindableBase
    {
        private ObservableCollection<Photo> _selectedPhotos;
        public ObservableCollection<Photo> SelectedPhotos
        {
            get =>  _selectedPhotos;
            set
            {
                var previous = _selectedPhotos;
                if (SetValue(ref _selectedPhotos, value))
                {
                    previous.CollectionChanged -= OnSelectedPhotosChanged;
                    _selectedPhotos.CollectionChanged += OnSelectedPhotosChanged;
                }
            }
        }

        public int PhotoCount => SelectedPhotos.Count;

        private void OnSelectedPhotosChanged(object sender, EventArgs e)
        {
            OnPropertyChanged(nameof(PhotoCount));
        }
    }
```

1. Delete _photoCount
2. Change string.Empty to nameof(PhotoCount)
3. Unsubscribe to event when _selectedPhotos is changed

**Comment by John-Burbidge** [comment]
In this post (but I could be mistaken in the intent) Brian mentions "Calling OnPropertChanged(String.Empty) is the best approach. It's simple, clean, does not require creating a derived class, and does not require creating a dirty API in the Prism implementation."
https://github.com/PrismLibrary/Prism/issues/817

I'll give your approach a try tomorrow.

Thanks for the help!

**Comment by nuitsjp** [comment]
I did not know that string.Empty will notify all properties for updates.
However, it is better to notify only one property this time.
Only when you update all properties, string. Empty should be used.

**Comment by brianlagunas** [comment]
Thank you to everyone for the help while I was on vacation :)
