### ISSUE TITLE
navigation service with (app:///...) not working properly in Windows 8.1

### ISSUE THREAD

**Issue by udayb99** [PrismLibrary/Prism#1096]
I'm using Xamarin.Forms 2.3.3.193 and Prism.Forms 6.3.0 My app is crashing in Windows 8.1 when navigating with Absolute URI

Pls see below my App Navigation Flow.

1 - App.xaml.cs

if (!IsUserLoggedIn)
{
    NavigationService.NavigateAsync("NavigationPage/LoginPage");
}
else
{
    NavigationService.NavigateAsync("NavigationPage/HomePage");
}

2 - LoginPageViewModel

if (response.AuthStatus)
{
    NavigationParameters navParams = new NavigationParameters();

    await _navigationService.NavigateAsync("OTPPage", navParams);
}
3 - OTPPageViewModel

if (ValidOTP)
{
    App.IsUserLoggedIn = true;
    await _navigationService.NavigateAsync("app:///NavigationPage/HomePage");
}
My App is Crashing in the OTPPageViewModel when I try to navigate to HomePage after OTP Validation.

Please note that the same Code is working in Android and UWP without any issues, but crashing only in Windows 8.1

If I use

await _navigationService.NavigateAsync("HomePage");
the app is working fine, but I am able to navigate back to OTPpage which I have to restrict.

And If I skip OTPPage and call HomePage directly from Login Page like below, it is working properly.

4 - LoginPageViewModel

if (response.AuthStatus)
{
    await _navigationService.NavigateAsync("app:///NavigationPage/HomePage");
}

**Comment by brianlagunas** [comment]
There is not enough information to diagnose your issue.  Make sure you are checking for parameters existence before trying to use them.  Chances are you are using a parameter in your OnNavigatedTo and not checking for null.

You need to provide more information about the exception.  It would be best to provide a sample app the demonstrates the issue.
