### ISSUE TITLE
pageDialogService MainPage reference is always null inside OnNavigatedTo after app is launched

### ISSUE THREAD

**Issue by Maharba** [PrismLibrary/Prism#1098]
[PrismUnityApp2.zip](https://github.com/PrismLibrary/Prism/files/1102719/PrismUnityApp2.zip)
### Package info

- Platform: iOS 10.3
- Prism version: 6.3.0.0
- Xamarin version (if applicable): 2.3.4.231
- Other version info: VS 2017 (15.2)

### Repro steps

Basically when the app is launching and the developer wants to display an alert, immediately after that, pageDialogService does not get the reference of MainPage even on the OnNavigatedTo method. Even App.Current.MainPage property is always null. This only happens in the first screen.

I could be able to reproduce it in every blank app using Prism/Unity and the versions above mentioned.
![blank](https://user-images.githubusercontent.com/319145/27547947-72a5f166-5a65-11e7-8a93-2526060f37d7.PNG)

**Comment by Maharba** [comment]
UPDATE: Sample project attached.

**Comment by jacob-maristany** [comment]
The issue seems to stem from the fact that IPageDialogService.DisplayAlertAsync(...) is invoked before AppDelegate.FinishedLaunching(...) completes.  While this does method does complete after the IPageDialogService.DisplayAlertAsync(...) invocation, the crash happens immediately after.

**Comment by brianlagunas** [comment]
As discussed on the Slack channel.  Use `Task.Yield()` in this scenario.
