### ISSUE TITLE
[XF] Introduce a Behavior factory into the navigation service

### ISSUE THREAD

**Issue by powerdude** [PrismLibrary/Prism#1099]
I'd like to try to tease apart the behavior injection inside the navigation service and introduce an IBehaviorFactory, or IPageFactory, so that it can be a bit easier to override or add additional functionality when standard XF pages are created.

**Comment by dansiegel** [comment]
@powerdude I believe the functionality that you're looking for can already be accomplished by implementing a custom `PageNavigationService` and overriding [`ApplyPageBehaviors`](https://github.com/PrismLibrary/Prism/blob/master/Source/Xamarin/Prism.Forms/Navigation/PageNavigationService.cs#L421-L435). 

```cs
protected override void ApplyPageBehaviors(Page page)
{
    base.ApplyPageBehaviors(page);
    // Add any additional behaviors
}
```

**Comment by powerdude** [comment]
@dansiegel , yes, it is possible there, but thought it would be more explicit to call out the functionality separately.  There's a lot going on in that class and it does more than navigation and should probably rely on other, more specialized services to help it do what it does.

**Comment by brianlagunas** [comment]
This is something that has been discussed in the past, but hasn't had any traction because it is not very common and can be accomplished by deriving from PageNavigationService like Dan suggested.  If you would like to talk about a design and put a preliminary PR together for what you had in mind, that would be great.

**Comment by brianlagunas** [comment]
I worked on a branch with this new abstraction, but I'm not sure if it is worth it or not.  If I pull this out into an IPageBehaviorFactory we will have to rely on reflection in order to determine if the page type is the target type or a derived type in order to properly apply the behaviors.  Reflection means performance hit.  This code would invoke for every page created.

Essentially we would have this class
```
    public class PageBehaviorFactory : IPageBehaviorFactory
    {
        List<KeyValuePair<Type, Behavior>> _pageBehaviors = new List<KeyValuePair<Type, Behavior>>();

        public PageBehaviorFactory()
        {

        }

        public void Register<T>(Behavior behavior) where T : Page
        {
            _pageBehaviors.Add(new KeyValuePair<Type, Behavior>(typeof(T), behavior));
        }

        public IEnumerable<Behavior> GetPageBehaviors(Page page)
        {
            List<Behavior> behaviors = new List<Behavior>();

            foreach (var kvp in _pageBehaviors)
            {
                if (IsSameOrSubclass(kvp.Key, page.GetType()))
                {
                    behaviors.Add(kvp.Value);
                }
            }

            return behaviors.AsEnumerable();
        }

        bool IsSameOrSubclass(Type potentialBase, Type potentialDescendant)
        {
            return potentialDescendant == potentialBase || potentialDescendant.GetTypeInfo().IsSubclassOf(potentialBase);
        }
    }
```
Then you can register your behaviors in the Prism Application:
```
        protected virtual void ConfigurePageBehaviors(IPageBehaviorFactory pageBehaviors)
        {
            if (pageBehaviors != null)
            {
                pageBehaviors.Register<NavigationPage>(new NavigationPageSystemGoBackBehavior());
                pageBehaviors.Register<TabbedPage>(new TabbedPageActiveAwareBehavior());
                pageBehaviors.Register<CarouselPage>(new CarouselPageActiveAwareBehavior());
            }
        }
```

Thoughts?

**Comment by brianlagunas** [comment]
I am closing this as there has not been a community response in a month.

**Comment by dansiegel** [comment]
After thinking about this some more I believe that this would actually be a good addition. While you could override `ApplyPageBehaviors` as I mentioned above, this would require users to properly update the registration for `INavigationService`. Considering the general importance of `INavigationService` I think it would be better to introduce a simple factory that would allow users to apply any behaviors that they want. 

```cs
public interface IPageBehaviorsFactory
{
    void ApplyPageBehaviors(Page page);
}

// this then simplifies registration

Container.Register<IPageBehaviorsFactory, PrismPageBehaviorsFactory>(Reuse.Singleton);
```

With the addition of Dynamic Tab Creation, it will also be more common to generically register a TabbedPage as well as a NavigationPage. This means that there are going to be use cases where you simply want to add a PlatformSpecific. There shouldn't be a need to add a custom TabbedPage for example just to add some platform specific property. 

```cs
public void ApplyPageBehaviors(Page page)
{
    // Apply Prism Behaviors
    base.ApplyPageBehaviors(page);
    switch(page)
    {
        case TabbedPage tabbed:
            AndroidSpecific.TabbedPage.SetIsSwipePagingEnabled(tabbed, true);
            macOSSpecific.TabbedPage.SetTabsStyle(tabbed, TabsStyle.Icons);
            break;
        case NavigationPage navPage:
            iOSSpecific.NavigationPage.SetIsNavigationBarTranslucent(navPage, true);
            macOSSpecific.NavigationPage.SetNavigationTransitionPushStyle(navPage, NavigationTransitionStyle.SlideUp);

    }
}
```
