### ISSUE TITLE
Project Structure Recommendation/Discussion

### ISSUE THREAD

**Issue by Michael-DST** [PrismLibrary/Prism#11]
The discussion on #10 inspired me to open a new issue about the naming/structure of projects and see if I am off on my own island in this regard (yet again \*smile\*).

The whole new platform thing is, well, new, so I think we're all learning along here.

I am wondering if it makes more sense to categorize assemblies/namespaces along by technology/concern then platform, resulting in the following pattern:

\<Product\>.\<Concern\>.\<Platform\>

Example: Prism.Unity.Windows

The other implied suggestion here is to use "Windows" in place of Wpf, as (I feel, personally) it is a stronger brand name, and then can also be extended in the case of Windows 10/Universal/One:

Prism.Mef.Windows.Universal or
Prism.Mef.Windows.One

(This is assuming that "Windows One" -- or "All-in-One" as I believe I have seen -- is the new API name being announced at //build.)

Part of the reasoning behind this suggestion is that I feel this is consistent with Xamarin's approach (which I personally will be adopting, as well):
Xamarin.Forms.Platform.\<Platform\>

(We would remove "Platform" to make it more succinct).

So in total:
Prism (PCL)
Prism.Windows (WPF Components)
Prism.Forms (Xamarin.Forms Components)
Prism.Unity (PCL)
Prism.Unity.Windows (Unity WPF Components)
Prism.Unity.Windows.One (Unity Windows 10 Components)
Prism.Unity.Forms (Unity Xamarin.Forms Components)
Prism.Mef (PCL)
Prism.Mef.Windows (MEF WPF components)
Prism.Mef.Windows.One (MEF Windows 10 Components)
Prism.Mef.Forms (MEF Xamarin.Forms Components)

The obvious intention/benefit for this design is that:
\<Product\>.\<Concern\> - For components with extensibility points.
\<Product\>.\<Concern\>.\<Platform\> - For implementations/extensions of extensibility points.

Just another thought that's been kicking around my head and had to get it out. :)  Thanks for any consideration as always.

**Comment by Michael-DST** [comment]
FWIW here's a mention today of a "One Core OS" (there is also a link to "One Windows" as well in the article):
http://www.zdnet.com/article/microsoft-delivers-windows-10-tools-for-building-universal-applications/

**Comment by brianlagunas** [comment]
Thanks for the suggestion.  After thinking about we agree.

We made the changes you suggested to the project structure and project names.  Minus the "Windows" part :0)

**Comment by JohnTasler** [comment]
I like *.*.Windows.OneCore for the UAP namespaces.
