### ISSUE TITLE
[XF] Introduce an IAppearingAware interface

### ISSUE THREAD

**Issue by powerdude** [PrismLibrary/Prism#1100]
Would there be any value in adding an interface like the following:

interface IAppearingAware
{
   void OnAppearing();
   void OnDisappearing();
}

This would make it easier to add async functions instead of trying to implement the property of IActiveAware.

**Comment by dansiegel** [comment]
How exactly would this make it easier to implement async functions? 

```cs
public class ViewAViewModel : BindableBase, IActiveAware
{
    private bool _isActive;
    public bool IsActive
    {
        get => _isActive;
        set => SetProperty(ref _isActive, value, () => OnIsActiveChanged);
    }

    private async void OnIsActiveChanged()
    {
         // You can do the same Async stuff as async void OnAppearing/OnDisappearing
    }
}

**Comment by brianlagunas** [comment]
I'm not sure I understand the full scenario around what you are trying to accomplish, but invoking async methods is no easier by adding On[...]ing methods.  Maybe if you provide more information about what you are trying to do.

**Comment by brianlagunas** [comment]
I am going to close this issue as this is not an interface I will be adding, but feel free to continue the conversation so we can help you with your problem.
