### ISSUE TITLE
Can i handle PopupWindowAction's wrapper window's closing event?

### ISSUE THREAD

**Issue by aytacasan** [PrismLibrary/Prism#1102]
Using prism for WPF latest stable version. I have below code inside ShellView.xaml for show my custom popup view;

```
    <i:Interaction.Triggers>
        <mvvm:InteractionRequestTrigger SourceObject="{Binding ShowCodeEditorRequest}">
            <mvvm:PopupWindowAction IsModal="True" CenterOverAssociatedObject="True">
                <mvvm:PopupWindowAction.WindowStyle>
                    <Style TargetType="Window">
                        <Setter Property="Width" Value="960"/>
                        <Setter Property="Height" Value="540"/>
                    </Style>
                </mvvm:PopupWindowAction.WindowStyle>
                <mvvm:PopupWindowAction.WindowContent>
                    <views:CodeEditorView/>
                </mvvm:PopupWindowAction.WindowContent>
            </mvvm:PopupWindowAction>
        </mvvm:InteractionRequestTrigger>
    </i:Interaction.Triggers>
```

CodeEditorView has a tab region (for CodeFileView) and a delegate command (CloseCommand) which is controlling all CodeFileViewModel's IsDirty property and asking to user want to save it or not. This command working when user click a toolbar button as expected. But also I want to trigger same command when user click to wrapper window's close button. How can i accomplish this requirement?

PS: User can be select yes (save it), no (don't save it) or cancel (cancel to close). Because of that trying to handle canceling event.

Regards,
Aytac Asan

**Comment by brianlagunas** [comment]
You can use an EventSetter, but I would just use a custom dialog service instead.

**Comment by aytacasan** [comment]
@brianlagunas, EventSetter can be use only for routed events and window closing is not a routed event. Also EventSetter handler must be on code behind which is don't like and/or prefer. Am i right?

Maybe i'll choose custom dialog solution, but i don't understand it. Could you please tell me some links from your blog (or from other source) for both solutions.

Thanks
