### ISSUE TITLE
Scoped View and View Model with Inner Region not Garbage Collected Straight Away

### ISSUE THREAD

**Issue by james1301** [PrismLibrary/Prism#1104]
I have a sample application here: https://1drv.ms/u/s!Av4A-OzchDGliEf7inb1mmjAPjzj.

I am just a little concerned that Scoped Views with Regions in are not available for garbage collection straight away. I do override a few of your core services, as advised by someone in your team a few years ago so that I can create the scoped region through navigation.

### Package info

- Platform: WPF
- Prism version: 6.3

### Repro steps

1. Put a break point on the deconstructor of the ScopedView and ScopedViewModel
2. Run Application and run "Navigate to Scoped View"
3. Click Close on the Scoped View (Which should try to call Garbage Collect)
4. Click Force GC as well, but the break points are not being hit

I know this isn't a full proof way of detecting whether they are being properly garbage collected but think it's an OK indicator. If you comment out the Tab Control Region in ScopedView, this does hit the break points straight away.

**Comment by james1301** [comment]
Same result if you did the same for View2 and added a region in there, it still doesn't get cleaned up. As well as removing all of my overriding classes.

**Comment by brianlagunas** [comment]
GC and break points are not a reliable mechanism to find memory leaks.  These types of discussions always lead to a needle in a haystack effort that results a lot of wasted time.  If you want to find memory leaks, please use a proper memory analyzer and provide the results that include what is rooting the objects.

**Comment by james1301** [comment]
Not an 100% guarantee no but has pretty good indicator I've used in the past with decent results. Here is the Memory graph. Do I need to enter a new issue now?

[View2 memory graph.pdf](https://github.com/PrismLibrary/Prism/files/1112330/View2.memory.graph.pdf)

**Comment by brianlagunas** [comment]
I'm not sure what this is supposed to be saying.  You need to provide much more information about hwat yo are testing for and what your results are.  Find what is rooting the your views to enable a more productive conversation.  Also, it looks likes you are using MEF.  Doesn't MEF makes things a singleton by default (Shared Creation Policy)?  Have you tried this with an actual DI container?

**Comment by james1301** [comment]
Some of our testers have brought up a memory issue, and I am trying to look into it, but the view and ViewModel not clearing up straight away is clouding my search as to whether there is actually a problem or not.

I've provided my sample application (slightly simpler version: https://1drv.ms/u/s!Av4A-OzchDGliEodmWzzkkuYh7qO). I took a snapshot between starting the application, launching my view with a region in, closing the view with region and taking another snapshot. This is the results of View2 still existing. Nothing is setup as a singleton. But after doing snapshot 2 the View and ViewModel are still there.

Is MEF not recommended to use? This is what our fairly large enterprise application is currently using, so would be quite an effort to change container.

**Comment by brianlagunas** [comment]
I would never recommend MEF to be used as a container, because it's not a DI container.  MEF is not even officially supported by the Prism team, but rather the MEF community only.  I haven't looked at the sample, but are you removing the View from the region?  Is your View and VM being resolved via MEF hence being created as a Shared Creation Policy (singleton)?

**Comment by james1301** [comment]
I see, I may have to review using this then.

I am deactivating the view yes. They are resolved through MEF but they are set to     [PartCreationPolicy(CreationPolicy.NonShared)]. If I navigate to the View again and close it, it will clear up the first instance of the View and View Model. If I do not have a child region in the view, it will also be cleared up find straight away.

**Comment by brianlagunas** [comment]
My only thought could be to test manually removing the region when the view is closed to see if that works.  You essentially need to figure out what is rooting the object.  Once you know that, it will be easier to figure out a solution.

Also, is it only one instance of the view that is always hanging around, or every time you navigate do you keep having multiple instances being added in memory?

**Comment by james1301** [comment]
I will mess about with that yeah, but as far as I know the region is removed, or else when I navigate to a new instance it would complain because of the duplicate region. I will look into it.

Yeah only one instance, which as I say probably isn't that bad, but is just making it more difficult when testing this kind of stuff. And the size of the view's in our actual application can get quite large, so ideally there wouldn't be one instance hanging around.

Thank you for your input.

**Comment by brianlagunas** [comment]
So, if it is only one instance at a time then this is most likely not a memory leak.

By default, Prism keeps the View alive and reuses it when navigating to the same instance.  When using a DI container you woud control this using the IRegionMemebrLifetime interface or the RegionMemberLifetime attribute on the View and set the KeepAlive property to false.  When you do this, the view is removed from the region automatically when deactivating.  You should know that deactivating is not the same as removing.  So by using the KeepAlive property you can remove the view on deactivation.

**Comment by james1301** [comment]
Yeah I do use IRegionMemberLifetime and I am setting keep alive to false, which does result in it actually being removed like just manually removing it from the region. Hence, when if I comment out the child region from the View, it is cleaned up straight away. It seems to just be just when there is a child region that makes it stay in memory.

**Comment by james1301** [comment]
Back when I started using Prism like 5 or more years ago, MEF seemed like one of the simplest implementations. Just having to configure the export on the actual View and ViewModel, seemed more relevant that having to go somewhere else to add it to the container etc.
