### ISSUE TITLE
INavigationAware Methods does not get called 

### ISSUE THREAD

**Issue by mustafasaaed** [PrismLibrary/Prism#1106]
I have a listview in a homepage and the ItemTapped event is bound to a command on the view Model which navigate to Details page passing the tapped item so far so good but on details page which implement INavigationAware the three methods (OnNavigatedFrom, OnNavigatedTo, OnNavigatingTo)
Doesn't get called at all   

### Package info

- Platform: Xamarin Forms 
- Prism version: 6.3.0
- Xamarin version :  2.3.4.247
- Windows 10 SDK version : Build 14393

**Comment by brianlagunas** [comment]
You'll need to provide a sample that reproduces the issue.

**Comment by mustafasaaed** [comment]
In the homepage listview I have this behavior:

```
<ListView.Behaviors>
                <b:EventToCommandBehavior EventName="ItemTapped"
                                          Command="{Binding ItemTappedCommand}"
                                          EventArgsParameterPath="Item"/>
</ListView.Behaviors>
```
in the home page viewmodel :

        `public DelegateCommand<Recipe> ItemTappedCommand { get; set; }`

in the Constructor :


```
 public HomeViewModel(INavigationService navigationService)
        {
            RecipesCollection = new ObservableCollection<Recipe>(new Data().GetRecipes());
            ItemTappedCommand = new DelegateCommand<Recipe>(NavigatToDetailsPage);
            this._navService = navigationService;
        }

```

```
private void NavigatToDetailsPage(Recipe recipe)
        {
            var navigationParams = new NavigationParameters();
            navigationParams.Add("Recipe", recipe);
            _navService.NavigateAsync("RecipeDetail", navigationParams);
        }
```


 in RecipeDetailViewModel which Implement INavigationAware 


```
public void OnNavigatedTo(NavigationParameters parameters)
        {
            _recipe = (Recipe)parameters["Recipe"];
        } 
```

**Comment by brianlagunas** [comment]
That is not a sample.  I need a running sample that reproduces the issue.  I have a lot of apps that have ListViews that have this functionality with no issues.

**Comment by mustafasaaed** [comment]
I found the problem, it turns out when I set the BindingContext="{Binding item}" on the Details Page it prevents the call to these methods !! is that a normal behavior ?

**Comment by brianlagunas** [comment]
I think there is more to it than that.  Without seeing the app it's hard to say.  Glad you got it figure out.

**Comment by mustafasaaed** [comment]
I have created a sample demo project to reproduce the issue 
here is the [project](https://github.com/mustafasaaed/SampleDemo)

**Comment by brianlagunas** [comment]
Yes this is expected because you changed the BindingContext of the entire page to something else.  It's not longer your ViewModel.
