### ISSUE TITLE
DisplayActionSheetAsync close after return page

### ISSUE THREAD

**Issue by brux88** [PrismLibrary/Prism#1107]
HI everyone,
I'm using the _dialogService.DisplayActionSheetAsync

To see a list of actions, if I click on a item I navigate to another page, if I go back to work I still have the DisplayActionSheetAsync open.
I when I click an item I want to close the DisplayActionSheetAsync

```
   public async void OpenDetail()
        {
            if (SelectedItem == null) return;
            var navigationParams = new NavigationParameters { { "model", SelectedItem } };
            await _navigationService.NavigateAsync("RegistroIvaDettaglioPage", navigationParams);
        }


        public async void VisualizzaAvanzate()
        {

            var result = await _dialogService.DisplayActionSheetAsync(SelectedItem?.Descrizione, AppResources.Cancel, null, AppResources.Dettaglio,
                AppResources.RegistroIvaSezionali);
            Debug.WriteLine(result);
            if (result == AppResources.Dettaglio)
            {
                OpenDetail();
            }
            else if (result == AppResources.RegistroIvaSezionali)
            {
                ApriRegistroIvaSezionali();
            }
    


        }

        public async void ApriRegistroIvaSezionali()
        {
            if (SelectedItem == null) return;
            var navigationParams = new NavigationParameters { { "registroIvaSelezionato", SelectedItem } };
            await _navigationService.NavigateAsync("RegistroIvaSezionaliPage", navigationParams);
        }
```

i added an screencast

[2017-07-01_1041.zip](https://github.com/PrismLibrary/Prism/files/1116940/2017-07-01_1041.zip)

**Comment by brianlagunas** [comment]
I can't view a swf video.  You should send as an .mp4

Also, when you select a button on an action sheet, it should closes automatically.  Prism does not control when it closes and there is no API to close one programmatically.

It would be better if you had a running sample the reproduces the issue.

**Comment by brux88** [comment]
hi,
If I click on an action, open another view, and then back with the navigation backbutton I find it open again

i added an mp4 screencast 

[2017_07_07_10_57_53.zip](https://github.com/PrismLibrary/Prism/files/1130498/2017_07_07_10_57_53.zip)

**Comment by brianlagunas** [comment]
I am unable to reproduce the issue.  Please provide a sample.
