### ISSUE TITLE
XamlCompilation for xamarin forms?

### ISSUE THREAD

**Issue by EmilAlipiev** [PrismLibrary/Prism#1108]
Does prism implement XamlCompilation for xamarin forms pages? when I try to add xamlc in app level in app.xaml.cs as below? I get Duplicate XamlCompilation attribute. It seems that there is something but I couldnt find any information about it anywhere? 

```
[assembly: XamlCompilation(XamlCompilationOptions.Compile)]
namespace myApp

```

Doing page level as below works fine

```
    [XamlCompilation(XamlCompilationOptions.Compile)]
    public partial class MainPage : ContentPage
```

if XamlC is not implemented, it would be great to extend snippets of prism contentpage that it automatically adds just like latest Xamarin Forms has when adding a new ContentPage

**Comment by dansiegel** [comment]
Prism itself has nothing to do with XamlC. That said, if you're using one of the templates, it's already added in the AssemblyInfo as it is a best practice. 

Keep in mind XamlCompilation works at either the class or assembly level, with the class level taking precedence, but it can only be added to the assembly once or a specific class once. Trying to add it multiple times is what generates the error.
