### ISSUE TITLE
App properties not available when it inherits PrismApplication

### ISSUE THREAD

**Issue by vidalkk** [PrismLibrary/Prism#1110]
Hi there,

I'm trying to write a code to authenticate users using Facebook via Xamarin.Auth. However I'm struggling to get access to properties defined in my App.cs class that inherits from PrismApplication.

I'm using following site as a reference: http://www.joesauve.com/using-xamarin-auth-with-xamarin-forms/

It does work when App class inherit from Application only.

From the code specific if I try to Access App.<MyProperty>, the property is not there. Is there anyone that has overcome this issue?

Any help will be appreciated.

**Comment by dansiegel** [comment]
Have you tried using `IApplicationStore`?

**Comment by vidalkk** [comment]
Hi Dansiegel,

Thanks for the Tip. How can I use it for this purpose?

**Comment by dansiegel** [comment]
```cs
public class ViewAViewModel : BindableBase
{
    private IApplicationStore _appStore { get; }

    public ViewAViewModel(IApplicationStore appStore)
    {
        _appStore = appStore;
    }

    private async void DoFoo()
    {
        _appStore.Properties["foo"] = "bar";
        await _appStore.SavePropertiesAsync();
    }

    private void DoBar()
    {
        var foo = _appStore.Properties["foo"];
    }
}
```

**Comment by brianlagunas** [comment]
The App property is still available in a Prism app.  Could you be more specific about what you are trying to accomplish?  Provide the actual code that isn't working or you expect to work?

**Comment by brianlagunas** [comment]
Also, I hope you did see the large test at the beginning of the article"

**"NOTE: This post is now over 3 years old. I strongly suggest you use something else, like Auth0 or some other authentication solution. I am no longer maintaining this code, so it probably won't work anymore."**

It seems this is no longer supported.
