### ISSUE TITLE
Include pdb file in nuget package?

### ISSUE THREAD

**Issue by bill2004158** [PrismLibrary/Prism#1111]
Is it possible include pdb file in nuget package? thus it will be easier for VS to debug.

**Comment by brianlagunas** [comment]
hmmmm... I'm not sure.  We ship release builds, and I would prefer not to bloat the NuGet packages as they are included in the Prism Template Pack which would really increase the sizes of them.  If you need to debug, why not just download the source code?

**Comment by dansiegel** [comment]
As I recall it is technically possible, and I know Xamarin does include the pdb file in the Xamarin.Forms NuGet... but its one of the very few, and Xamarin doesn't even consistently do that across all of their packages. Generally speaking including symbols in a NuGet isn't something you do for releases. 

If we did provide the pdb's for each build, I believe it would end up being hosted on MyGet and it would be up to the individual developer to add it as a Symbols Source in Visual Studio.

**Comment by bartlannoeye** [comment]
Going with Dan's option on this.

**Comment by sunefred** [comment]
First of all, .pbd will only help with Call Stack info and Stack traces. In order to debug into Prism you will need both .pbd and source files. The recommended way to do this for public nuget packages is to create a separate symbol package and make that available on http://www.symbolsource.org/.

Details can be found here: https://www.visualstudio.com/en-us/docs/build/steps/utility/copy-and-publish-build-artifacts

**Comment by dansiegel** [comment]
@sunefred I thought you were asking for this to be part of the NuGet that we ship on NuGet... that would never happen. 

As you mentioned .pbd's are only part of it... this is something that we can certainly look more into once we stabilize the CI/CD pipeline for all of Prism. I know there are several options for how to best do this, so it may take a while before we decide how we want to handle this.

**Comment by opcodewriter** [comment]
@dansiegel What's the usual practice as a library author if you want to give your users the PDBs?

**Comment by dansiegel** [comment]
my libraries now include symbol packages on MyGet... and it's planned to be added to Prism. I'll try to sneak it in before we do the next public preview. AFAIK VS4Mac doesn't really support custom symbol sources, but VS4Windows will allow you to add the MyGet feeds as a symbols source.

**Comment by opcodewriter** [comment]
@dansiegel symbol packages are of great help to debug easily issues. It would also encourage people to debug their issues themselves instead of opening up tens of questions on StackOverflow only to realize they forgot to do something their own.

**Comment by opcodewriter** [comment]
@dansiegel It would be fantastic to get the PDBs working with next release. Thank you

**Comment by opcodewriter** [comment]
Meanwhile, a colleague is trying to do it but no luck: https://github.com/PrismLibrary/Prism/issues/1111#issuecomment-331616933

**Comment by dansiegel** [comment]
Symbols are now being published to MyGet. 

Browse the sources in this package using Visual Studio or WinDbg by configuring the following symbol server URL: https://www.myget.org/F/prism/symbols/

**Comment by toreaurstad** [comment]
Symbol servers are nice. 
This is probably a strategy many know already about, I include it as a suggestion. 
It is possible to also obtain the pdb files by cloning the Prism source code and getting the pdb files via building Prism. For example, first off cloning Prism library: 
git clone https://github.com/PrismLibrary/Prism.git
Then we see which remote branches are available: 
git branch -a 
Hmm, in my business case there are no branches for version 6.3. Maybe a tag perhaps: 
git tag
Aha! There is a 6.3 version among the tags! Checking the tag out as a local branch: 
git checkout tags/Prism.v6.3.0 -b Prism630

Switching to VS 2015, I build the Prism.Wpf solution and especially the Prism Autofac project to obtain Prism.pdb, Prism.Wpf.pdb and Prism.Wpf.Autofac.pdb files, which I was looking after.
