### ISSUE TITLE
[XF] MasterDetailPage: Unable to explicitly navigate to MainPage from MasterDetailPage

### ISSUE THREAD

**Issue by Rhywden** [PrismLibrary/Prism#1112]
### Package info

- Platform: UWP / Android
- Prism version: 6.3.0
- Xamarin version (if applicable): 2.3.4.247
- Windows 10 SDK version (if applicable): Creator's Update
- Other version info:

### Repro steps

I basically just used the HelloWorld example (https://github.com/PrismLibrary/Prism/tree/master/Sandbox/Xamarin/HelloWorld/HelloWorld) to create my own MasterDetail page.

The code should be basically identical. Where I am running into trouble is this:

On Android, after clicking on the Hamburger menu and selecting a page to navigate to, the Hamburger Icon turns into a NavigationBack arrow which leads back to the MainPage.

On UWP, that's a little different - since the Hamburger Menu is always open (at least on default), I could in principle have a ```<Button Text="MainPage" Command="{Binding NavigateCommand}" CommandParameter="MyNavigationPage/MainPage" />``` on the MasterDetailPage (as does your own project).

However, this particular button does *nothing*. I can navigate to *any* other view without problems but this page (i.e. the landing page from App.cs) does nothing.
However, navigation from inside a page works again. It's a bit weird and counterintuitive.

**Comment by Rhywden** [comment]
Here's a short video which shows the problem in detail:

https://youtu.be/BDq5AggtF3A

**Comment by brianlagunas** [comment]
You can't use the HelloWorld sample as I use that to test various features and scenarios.   In it's current state it is set up to reproduce a Xamarin.Forms bug so that the Xamarin team can debug it.  I suggest starting from a new project and not the HelloWorld sample.

**Comment by Rhywden** [comment]
I only used the Navigation features from Prism. I'm not seeing how I could define anything *differently*.

**Comment by brianlagunas** [comment]
The only way you will get a back button when using master detail is if you are reusing the navigation page.  This is implemented in the HelloWorld, so if you copied that, that is why you are getting the back buttons and not the hamburger menu.

**Comment by Rhywden** [comment]
Please watch my video, it should make the issue clearer. It's only 2 minutes.

**Comment by brianlagunas** [comment]
I did watch it.  I am telling you what the problem is based on what I saw.  The only way you get a back button is if you are reusing the Nav page and not resetting it.

**Comment by Rhywden** [comment]
I'm not sure where I would be resetting it. The Views and ViewModels for the three pages are functionally identical. I'm not doing anything special to MainPage that I'm not also doing to CourseForm and PupilForm.

**Comment by brianlagunas** [comment]
You probably copied the MyNavigationPage ffrom the HelloWorld which implements the INavigationPageOptions interface and sets the ClearNavigationStack property to false.  Set it to true, or don't use the MyNavigationPage at all.

**Comment by Rhywden** [comment]
If I set it to true I don't get any back button. Also, if I use a simple NavigationPage instead of MyNavigationPage I still don't get the back button.

**Comment by brianlagunas** [comment]
Of course not, you get the hamburger menu instead.  That's how XF works.  The only way you get a back button is if you navigate within the navigation page.  Basic XF behavior.

**Comment by Rhywden** [comment]
That is very confusing. I honestly do not understand why the initial navigation in App.cs prevents any further navigation to that page from inside the Hamburger Menu when it *does* work for all the other pages.

**Comment by brianlagunas** [comment]
Initial navigation does not prevent anything.  Chances are it is something in your code.  Possibly from something you copied out of HelloWorld.  Navigation in Prism really isn't that difficult, but first you must understand how standard XF navigation works.  Send you sample so I can take a look.

**Comment by Rhywden** [comment]
https://1drv.ms/u/s!AnaQYQYuE_OJjcBlM_lwS1Y88I8Hpw

**Comment by brianlagunas** [comment]
I checked out the sample and everything is working perfectly.  I deleted the MyNavigationPage and just used a normal navigation page.  That was the only difference.  Maybe uninstall the app from the emulator and delete your obj and bin folders to remove anything hanging around.

Also, the reason the master stays open on UWP is because you are telling it to with the IMasterDetailPageOptions.

**Comment by Rhywden** [comment]
Yes, but if I use a normal navigation page I lose the back button for the Hamburger.

**Comment by brianlagunas** [comment]
A back button only appears if you have more than one page on a NavigationPage's navigation stack.  If you want this, then you must reuse the navigation page.  If you do that, then you loose the hamburger menu.  Right now, if you were to navigate to another page from one of the detail pages you would get a back button.  You need to decide how you want your navigation to work.  Either reuse the navigation page or don't, but you can't have it both ways.

**Comment by brianlagunas** [comment]
It would help if you describe what exactly you are trying to achieve.  What is your desired end result?  And what is the current problem preventing you from getting there?

**Comment by Rhywden** [comment]
It's easy to describe: My sample shows that upon clicking on the two options for CourseForm and PupilForm does execute a navigation to those pages while also enabling a navigation back through the button. 
`<Button Text="CourseForm" Command="{Binding NavigateCommand}" CommandParameter="NavigationPage/CourseFormPage" />`
This works.

I'd like for it to work also for this:
`<Button Text="MainPage" Command="{Binding NavigateCommand}" CommandParameter="NavigationPage/MainPage" />`

Because clicking *that* button does absolutely nothing - neither does it navigate to MainPage nor is a back button available (obviously).

**Comment by brianlagunas** [comment]
Okay, now I understand.  Thanks you for explaining it again.  That was a bug that has been fixed, but has not been released yet.  In the old code, it was always comparing the root page and checking if it was the same, and if it was it would ignore it.  That has been fixed in the latest source code.  We are still working on our automated build process and hope to have a fix out soon.

Keep in mind though, that you will not be navigating to the same instance since you are reusing the navigation page.  Instead, you will be creating another instance and adding it to the end of the navigation stack.  This will happen each time you click on a button in the Master.  The master can be shown as any time by swiping from the left regardless if there is a hamburger menu or not.  I would recommend not trying to reuse the navigation page.

**Comment by Rhywden** [comment]
Ah, I see. I suppose there isn't an easy way of adding a reference to a page to the stack instead of the page itself?

**Comment by brianlagunas** [comment]
No. You would have to remove the page from the stack and insert it at the end, then when going back you couldn't actually pop the page (unless you stored a reference to it somewhere), but rather remove it from the stack and reinsert it where it originally was, while maintaining all the state that the page had prior to it being removed the first time.

**Comment by Rhywden** [comment]
Okay, thank you for that explanation. So, if I understand that correctly, `NavigationService.NavigateAsync("MyNavigationPage/CourseFormPage");` will reuse the navigation page and create a new instance of CourseFormPage, whereas `NavigationService.NavigateAsync("CourseFormPage");` will not do that.

Is there some way to prevent the first from happening, besides not using the Hamburger Menu in that way?

**Comment by brianlagunas** [comment]
No, both will create a new instance.  There is no sharing of instances when navigating back and forth.  If you need this capability, you will need to manually manage the stack (i.e.. holding references to pages, inserting and removing from the stack in proper locations).
