### ISSUE TITLE
ViewModelLocator should support Views

### ISSUE THREAD

**Issue by dansiegel** [PrismLibrary/Prism#1116]
While the ViewModelLocator.AutoWire property can be used on either a View or Page the ViewModelLocationProvider is not currently being setup to handle the scenario when a Custom View in Xamarin Forms has it's own ViewModel. 

Because the ViewModel may require the use of `INavigationService` we should update this so that we handle the scenario where we are resolving the ViewModel for a View and not a Page. I'm thinking something like the following: 

```cs
protected override void ConfigureViewModelLocator()
{
    ViewModelLocationProvider.SetDefaultViewModelFactory((view, type) =>
    {
        switch(view)
        {
            case Page page:
                // Existing parameter with the Page
                break;
            case View customView:
                var page = GetPage(customView);
                // Existing parameter with the Page
                break;
        }

        return Container.ResolveWithParameters(...);
    });
}

private Page GetPage(View view)
{
    switch(view.ParentView)
    {
        case Page page:
            return page;
        case null:
            return null;
        default:
            return GetPage(view.ParentView)
    }
}

```

**Comment by bartlannoeye** [comment]
How difficult would it be to expand it to all controls, as not every 'user control' has to [derive from a ContentView](https://xamarinhelp.com/xamarin-forms-user-control/)? In UWP I've already used the ViewModelLocator on my user/custom controls a few times.

**Comment by dansiegel** [comment]
Well even a Button, Label, StackLayout, Grid, etc all derive from View... As I recall the Parent property actually comes from Element so we could take it up to that level.

**Comment by dansiegel** [comment]
Just thinking on this, if we add this support, we would need to be able to determine what View/ViewModel's may exist as a child of our parent View (Xamarin Forms Page). There is no good way to recursively walk the children of an Element/Page/View, not to mention that could lead to poor performance on a complex View. We could however solve this by implementing something like the following:

#### ChildViewRegistry

This new attachable property would allow us to track any Child Views that may exist for a particular page.

```cs
public static class ChildViewRegistry
{
    public static readonly BindableProperty ChildViewsProperty =
        BindableProperty.CreateAttached("ChildViews", typeof(IList<Element>), typeof(ChildViewRegistry), new List<Element>());

    public static IList<Element> GetChildViews(BindableObject bindable) =>
        (IList<Element>)bindable.GetValue(ChildViewsProperty);

    public static void AddChildView(BindableObject bindable, Element element) =>
        GetChildViews(bindable).Add(element);
}
```

#### PrismApplicationBase.cs

We could then update PrismApplicationBase to provide a new CreateNavigationService that accepts a generic object for the View allowing all containers to simply pass this in the view directly from the ViewModelLocatorProvider and get the NavigationService for either the Page or View. When the `View` is a Page, the process would continue as it currently does today. If however it is some other View Element, we would try to determine the parent Page and add the View Element to the Page's Child View Registry.

```cs
// Currently exists
protected INavigationService CreateNavigationService(Page page)
{
    var navigationService = CreateNavigationService();
    ((IPageAware)navigationService).Page = page;
    return navigationService;
}

protected INavigationService CreateNavigationService(object view)
{
    switch(view)
    {
        case Page page:
            return CreateNavigationService(page);
        case Element element:
            var parentPage = GetPageFromElement(element);
            if (parentPage == null)
            {
                Logger.Log($"No Parent Page could be found for the View: {view.GetType().Name}", Category.Debug, Priority.None);
                return null;
            }
            ChildViewRegistry.AddChildView(parentPage, element);
            return CreateNavigationService(parentPage);
        default:
            return null;
    }
}

protected Page GetPageFromElement(Element element)
{
    switch(element.Parent)
    {
        case Page page:
            return page;
        case null:
            return null;
        default:
            return GetPageFromElement(element.Parent);
    }
}
```

#### PageUtiliities

Finally we could update `InvokeViewAndViewModelAction` to ensure that when we call `OnNavigatingTo`, `Destroy` etc, we are also invoking the action on any child Views contained in the ChildViewRegistry.

```cs
public static void InvokeViewAndViewModelAction<T>(object view, Action<T> action) where T : class
{
    if(view is T viewAsT)
        action(viewAsT);

    if(view is BindableObject bindable)
    {
        if(bindable.BindingContext is T viewModelAsT)
        {
            action(viewModelAsT);
        }

        foreach(Element child in ChildViewRegistry.GetChildViews(bindable))
        {
            InvokeViewAndViewModelAction(child, action);
        }
    }
}
```

**Comment by kylewarren** [comment]
Would you need to know the order of your children so that you could handle the onNavigatingTo, destroy, etc. in a particular order if the children were stacked on top of each other or within one another. 

I would think you would work from the inner most child and work your way up.

I have a couple of views where I have embedded views where I set the binding context at each level

Does that make sense?

**Comment by dansiegel** [comment]
@kylewarren if I understand you correctly you're thinking something like:

```xml
<ContentPage>
    <CustomViewA>
        <CustomViewB />
    </CustomViewA>
</ContentPage>
```

With `OnNavigatingTo` or whatever we invoke, hitting `CustomViewB`, `CustomViewA`, and then the `ContentPage`... is that correct?

**Comment by kylewarren** [comment]
Correct. Mostly speaking to content views in particular, and just making sure that when handling all the events, attempting to do them from the inner most child and working your way up/out. 

And I suppose I would think that the in scenario you laid out above, that you would handle navigation methods TO first of the upper/outer most parent and work your way down. So from the content page, to view a, to view b. Why? Because I would assume some setup would probably need to happen in each of the parents before setting the context on the child.

But when working on methods that fire when a view is being destroyed/pushed off the stack, you would do the inverse and work from view b, to view a, to the content page.

**Comment by dansiegel** [comment]
@kylewarren what you're proposing would add a lot of complexity that I don't see a need for. Ultimately I see this as being quite similar to the problem we have with TabbedPages. For instance, say I have a TabbedPage for a user profile with tabs for User Details, User Photos, and Messaging the User. Each page uses a custom View that has the User's profile picture, name, and some basic stuff about the user.

The goal then should be to be able to reduce the XAML markup from page to page by simply having:

```xml
<ContentPage>
    <StackLayout>
        <UserDetailBar />
        <!-- Some other stuff -->
    </StackLayout>
</ContentPage>
```

What is really important for our goal is that we are initializing `UserDetailBar` in this sample with the user's id or perhaps the actual user model that we have passed in the NavigationParameters. I don't see the need to add any overhead. If some setup is required in the Parent, then I see there being something entirely wrong with the design.

**Comment by brianlagunas** [comment]
I'm closing this issue because this is related, and dependent on the region feature implementation.  What's most likely going to happen is that VM resolution will be part of a new feature specific to the regions use case.
