### ISSUE TITLE
OnActivated not handled

### ISSUE THREAD

**Issue by diego2k** [PrismLibrary/Prism#112]
Hi,
if I launch an app through a click at a toast message the OnLaunched method doesn't get called, instead the OnActivated gets executed. But this method isn't handled by PrismApplication.cs, so the app doesn't start. 
The only way to fix this is to add the following method in your main class which inherits from PrismApplication: 

        protected async override void OnActivated(IActivatedEventArgs args)
        {
            if (Window.Current.Content == null)
            {
                Frame rootFrame = await InitializeFrameAsync(args);

                Shell = CreateShell(rootFrame);

                if (Shell != null)
                    Window.Current.Content = Shell;
                else
                    Window.Current.Content = rootFrame;
            }

            Window.Current.Activate();
        }

I think this case is not considered in the current code.

**Comment by briannoyes** [comment]
Hi @diego2k, good catch. I knew there were some other kinds of launches we did not have covered. The code is a port of the Prism for Windows Runtime release, which explicitly only supported live tile and secondary live tile launches. I'll get a fix in for this within the next few days.

**Comment by briannoyes** [comment]
@diego2k Could you confirm if this is still an issue with the changes that have been made in the activation pipeline in PrismApplication?

**Comment by diego2k** [comment]
I have only done a short test (on master), but I think the issue is still in the code. 
The method "protected async override void OnActivated(IActivatedEventArgs args)" is missing in the PrismApplication, so I guess it can't work.

**Comment by diego2k** [comment]
Additionally, that everything works the following code has to be added to e.g. App.xaml.cs:

        protected async override void OnActivated(IActivatedEventArgs args)
        {
            if (Window.Current.Content == null)
            {
                Frame rootFrame = await InitializeFrameAsync(args);

                Shell = CreateShell(rootFrame);

                if (Shell != null)
                    Window.Current.Content = Shell;
                else
                    Window.Current.Content = rootFrame;
            }
            else
            {
                // If the app is already running OnInitializeAsync doesn't get called
                ToastNotificationActivatedEventArgs toastArgs = args as ToastNotificationActivatedEventArgs;
                if (toastArgs != null)
                {
                    this.NavigationService.Navigate(Pages.BLA.ToString(), toastArgs.Argument);
                }
            }

            Window.Current.Activate();
        }

**Comment by briannoyes** [comment]
Since I don't have an app all ready to go that does toast messages here, could we get you to submit a PR with the changes to PrismApplication that you think will address this issue?

**Comment by diego2k** [comment]
Sorry I overlooked this ... I will upload an example as soon as possible

**Comment by diego2k** [comment]
It's already fixed, since a few days. 
Thanks.
