### ISSUE TITLE
Prism.Autofac RegisterTypeForNavigation issue

### ISSUE THREAD

**Issue by galmond** [PrismLibrary/Prism#1120]
Navigation doesn't appear to be working correctly if I specify a 'name' when using ContainerBuilder.RegisterTypeForNavigation< TView >(name)

I can correctly navigate to the view the first time but subsequent navigation attempts do not call INavigationAware.IsNavigationTarget()

The issue is reproducable by modifying the NavigationParticipation sample solution to use Autofac with named views, e.g.:

builder.RegisterTypeForNavigation< ViewA >("ThisIsViewA");

Calling regionManager.RequestNavigate("ContentRegion", "ThisIsViewA") for the second time does not call INavigationAware.IsNavigationTarget() on the ViewA viewmodel.  I tried this with Unity and it works as expected.

**Comment by brianlagunas** [comment]
This is very strange.  Just so you know `builder.RegisterTypeForNavigation<ViewA>("MyViewA");` is the exact same as `builder.RegisterType<ViewA>().Named<object>("MyViewA");`.  RegisterTypeForNavigation is just an extension method.  I don't use Autofac and have no understanding of how it works, but this is very weird. It works with Unity, so this tells me this has something to do with the container itself.

This will work: `builder.RegisterType<ViewA>().Named<object>("ViewA");`
This won't work: `builder.RegisterType<ViewA>().Named<object>("MyViewA");`

Maybe someone more familiar with Autofac can help you out.  For now, just use the type name, because Autofac seems to prefer that.

**Comment by brianlagunas** [comment]
Actually, I dug a little deeper and found that the other containers do not properly implement the necessary classes to function properly.  What Autofac is missing is the AutofacRegionNavigationContentLoader.

You can see Unity's here: https://github.com/PrismLibrary/Prism/blob/master/Source/Wpf/Prism.Unity.Wpf/Regions/UnityRegionNavigationContentLoader.cs

If you create this class and implement the `GetCandidatesFromRegion` method, and register it with the container in the botstrapper, it will work just fine.  You can see how Unity does it here:
https://github.com/PrismLibrary/Prism/blob/master/Source/Wpf/Prism.Unity.Wpf/UnityBootstrapper.cs#L157

**Comment by brianlagunas** [comment]
It would be great if someone from the Autofac community could implement this class using the Unity class as a guide and submit a PR.

**Comment by galmond** [comment]
Thanks for investigating Brian, much appreciated.

**Comment by brianlagunas** [comment]
I'm not familiar with Autofac but I think this should work

```
	public class AutofacRegionNavigationContentLoader : RegionNavigationContentLoader
	{
		private IContainer container;

		public AutofacRegionNavigationContentLoader(IServiceLocator serviceLocator, IContainer container)
			: base(serviceLocator)
		{
			this.container = container;
		}

		/// <summary>
		/// Returns the set of candidates that may satisfiy this navigation request.
		/// </summary>
		/// <param name="region">The region containing items that may satisfy the navigation request.</param>
		/// <param name="candidateNavigationContract">The candidate navigation target.</param>
		/// <returns>An enumerable of candidate objects from the <see cref="IRegion"/></returns>
		protected override IEnumerable<object> GetCandidatesFromRegion(IRegion region, string candidateNavigationContract)
		{
			if (candidateNavigationContract == null || candidateNavigationContract.Equals(string.Empty))
				throw new ArgumentNullException(nameof(candidateNavigationContract));

			IEnumerable<object> contractCandidates = base.GetCandidatesFromRegion(region, candidateNavigationContract);

			if (!contractCandidates.Any())
			{
				//First try friendly name registration.
				var matchingRegistration = container.ComponentRegistry.Registrations.Where(r => r.Services.OfType<KeyedService>().Where(x => x.ServiceKey.ToString().Equals(candidateNavigationContract, StringComparison.Ordinal)).FirstOrDefault() != null).FirstOrDefault();

				//If not found, try type registration
				if (matchingRegistration == null)
					matchingRegistration = container.ComponentRegistry.Registrations.Where(r => candidateNavigationContract.Equals(r.Activator.LimitType.Name, StringComparison.Ordinal)).FirstOrDefault();

				if (matchingRegistration == null)
					return new object[0];

				string typeCandidateName = matchingRegistration.Activator.LimitType.FullName;

				contractCandidates = base.GetCandidatesFromRegion(region, typeCandidateName);
			}

			return contractCandidates;
		}
	}
```

Then register it in the bootstrapper:
```
	protected override void ConfigureContainerBuilder(ContainerBuilder builder)
	{
		base.ConfigureContainerBuilder(builder);
		RegisterTypeIfMissing<IRegionNavigationContentLoader, AutofacRegionNavigationContentLoader>(builder, true);
	}
```

You'll want to have someone that actually knows Autofac to double check that.

**Comment by galmond** [comment]
Thanks Brian, I attempted it myself and it's exactly the same as yours. I raised the issue with the Autofac devs but haven't had a response yet, although I suspect the reason the Autofac content loader doesn't exist is due to this stackoverflow response...

https://stackoverflow.com/a/9120836

**Comment by gitlsl** [comment]
` 
public void Initialize()
        {
            _container.RegisterTypeForNavigation<ViewA>();
            _container.RegisterTypeForNavigation<ViewB>();
         }
` 

this work in the demo  `NavigationParticipation`  which use `IUnityContainer`

if you switch to `Autofac`  you should do like next
````
                   var containerBuilder  = new ContainerBuilder();
                        containerBuilder.RegisterTypeForNavigation<ViewA>("ViewA");
                        containerBuilder.RegisterTypeForNavigation<ViewB>("ViewB");
                        
                        containerBuilder.Update(container);
`

**Comment by brianlagunas** [comment]
Unfortunately, it doesn't work unless you add the custom content loader that I provided in this thread.  Also, Autofac is switching toan immutable container.  Which means you will no longer be able to update the container using Update()

**Comment by brianlagunas** [comment]
fixed

**Comment by wowfood** [comment]
While this has been marked as fixed / closed.  I appear to be having the same issue in Prism.Ninject.

Would I be correct in assuming it's down to the same root cause?  It seems navigation called OnNavigatedTo and OnNavigatedFrom fine, but never calls any of my IsNavigationTarget.

**Comment by brianlagunas** [comment]
It is probably related to the same issue.  Whoever implemented the Ninject support, didn't provide the necessary content loader.  Just follow the same pattern discussed in this thread and see if it works for you.

**Comment by topfunet** [comment]
not just autofac, i'm using DryIoc, this issue still exist.
