### ISSUE TITLE
EventToCommandBehavior is not working in Entry textChanged

### ISSUE THREAD

**Issue by mo-kml** [PrismLibrary/Prism#1122]
Hi there
im using EventToCommandBehavior To bind Entry TextChanged to my Command in ViewModel but it wouldnt work.
`            <Entry Placeholder="search" Text="{Binding Value}" >

                <Entry.Behaviors>

                    <b:EventToCommandBehavior EventName="TextChanged"
                                              Command="{Binding TextChanging}"
                                              CommandParameter="Text"/>
                </Entry.Behaviors>
            </Entry>`
and in my viewModel im using this code for my textChanged Command

```
`public Command TextChanging { get; set; }

public SelectCityViewModel()

{
            TextChanging = new Command((parameter) =>
            {
            });
        }`

```
actually ive used this behavior in listView itemTapped and it worked perfectly but in other controls it wouldnt work at all. i also try this on stepper ValueChanged but it didnt work on it either

- Platform: Xamarin Form shared project
- Prism version: 6.3.0
- Xamarin version (if applicable): 2.3.4.247

**Comment by brianlagunas** [comment]
It works perfectly for me.  Double check your bindings.

```
		<Entry>
			<Entry.Behaviors>
				<b:EventToCommandBehavior EventName="TextChanged"
                                          Command="{Binding TextChangedCommand}"
                                          CommandParameter="Text"/>
			</Entry.Behaviors>
		</Entry>
```
```
private DelegateCommand<string> _textChangedCommand;
        public DelegateCommand<string> TextChangedCommand =>
            _textChangedCommand ?? (_textChangedCommand = new DelegateCommand<string>(TextChanged));

        private void TextChanged(string p)
        {
            
        }
```
