### ISSUE TITLE
solution for navigation from a service

### ISSUE THREAD

**Issue by mo-kml** [PrismLibrary/Prism#1128]
hi there
im using odata for my server integration and xamarin forms for my client side.i have a service that passes odata context to another view models. i wanna sign out the user when odata response be unAuthorize error. but i have a problem. i wanna navigate user to login page from my service. but i not able to do this. what solution do you suggest to make this right?
this is what i want to do but without a view model i cant do that.

> private void ServerContext_ReceivingResponse(object sender, ReceivingResponseEventArgs e)
        {
            if (!e.ResponseMessage.Headers.Any(h => h.Key == "X-CorrelationId"))
            {
                _dialogService.DisplayAlertAsync("Authentication Failed", "Authentication Failed.Please Login again", "Ok");
                _navigationService.NavigateAsync(nameof(CompanyLoginView));
            }
        }

Actually ive tries MessagingCenter of xamarin to do so but it didnt work out. 
I sent a message from my service that you have been logout
> private void ServerContext_ReceivingResponse(object sender, ReceivingResponseEventArgs e)
        {
            if (!e.ResponseMessage.Headers.Any(h => h.Key == "X-CorrelationId"))
            {
                MessagingCenter.Send(this, "Logout");
            }
        }

and in constructor of my view model i navigate to another page but navigation didn't work. also IPageDialogService also didnt work and throw an exception.

> MessagingCenter.Subscribe<ODataContextProvider>(this, "Logout",(sender) =>
            {
                _navigationService.NavigateAsync("CompanyLoginView");
                _dialogService.DisplayAlertAsync("Error", "Please select void reason", "Ok");
            });

- Platform: Xamarin forms shared project
- Prism version: 6.3.0
- Xamarin version (if applicable): 2.3.4.247

**Comment by brianlagunas** [comment]
You shouldn't try to navigate within the service.  Your service should provide you with a response and you navigate after receiving that response in your ViewModel.

**Comment by mo-kml** [comment]
actually i am doing this. i`m using MessagingCenter of Xamarin forms to send a message to my ViewModel  that my authentication has been expired. but even when i use MessageCenter and navigate from my ViewModel it wont  navigate or even not display alert with dialogService

**Comment by brianlagunas** [comment]
Then you have a different problem in your code.
