### ISSUE TITLE
A NavigationPage within a TabbedPage can't push onto the view stack if the tab is grouped into a "More" section

### ISSUE THREAD

**Issue by mikegottlieb** [PrismLibrary/Prism#1129]
Please provide as much detail as possible (and feel free to remove unused properties):

### Package info

- Platform: iOS
- Prism version: 6.3.0
- Xamarin version (if applicable): 2.3.3.193

### Repro steps

1. Use a TabbedPage as your root view. 
2. Add 6 sub pages to the TabbedPage which will cause the TabbedPage to automatically generate a "More" tab containing your 5th and 6th sub pages. Make sure your 5th or 6th page is a NavigationPage with some kind of root view and that the root view contains something that can trigger another push of a view onto the stack.
3. Select the "More" tab
4. Select the page configured in step 2 which should push it onto the stack
5. Trigger the navigation from the page described in step 2.

At this point you would expect the next view to be pushed onto the stack, but actually nothing happens.

**Comment by brianlagunas** [comment]
Can you provide a sample that reproduces the issue.

**Comment by brianlagunas** [comment]
Closing since there has been no response.

**Comment by mikegottlieb** [comment]
Yeah sorry, I've been too busy to get something together especially because my environment was seriously destabilized by trying to update to Xamarin Forms 2.3.4 and VS 4 Mac. This is definitely still and issue and is easily reproducible as soon as you have 6 or more pages as a child of a TabbedPage. Hopefully I can get an example together soon.
