### ISSUE TITLE
Prism for WPF Navigation Go Back reload datagrid header style, why?

### ISSUE THREAD

**Issue by sa13m** [PrismLibrary/Prism#1131]
Hello. Prism 6.3, Wpf 4.5.

I use navigation for editing Customer(CustomersView -> CustomerView).
CustomersView:
`        <DataGrid AutoGenerateColumns="True" ItemsSource="{Binding Customers}">
            <DataGrid.ColumnHeaderStyle>
                <Style TargetType="{x:Type DataGridColumnHeader}">
                    <Setter Property="Template">
                        <Setter.Value>
                            <ControlTemplate TargetType="{x:Type DataGridColumnHeader}">
                                <Grid x:Name="gridColumnHeader">
                                    <Grid.RowDefinitions>
                                        <RowDefinition/>
                                        <RowDefinition/>
                                    </Grid.RowDefinitions>
                                    <ContentPresenter x:Name="contentPresenterColumnHeader"/>
                                    **<TextBox x:Name="filter" Grid.Row="1" Height="30" Width="30"/>**
                                </Grid>
                            </ControlTemplate>
                        </Setter.Value>
                    </Setter>
                </Style>
            </DataGrid.ColumnHeaderStyle>
        </DataGrid>`

I set the filter in header and use navigation, after navigation filter set default value(reload ColumnHeaderStyle?). There is more GoBack() freeze for 1-2 second. How to save CustomersView as before navigation? 
Sorry, my English is bad

**Comment by brianlagunas** [comment]
Call a method to save your view before calling the navigation method.

**Comment by sa13m** [comment]
what method?

**Comment by brianlagunas** [comment]
Your method that you write.

**Comment by sa13m** [comment]
Brian, I will tell in more detail.
User works in the CustomersView and set the filter in DataGridColumnHeader Column.Name = 11:
![1](https://user-images.githubusercontent.com/30556809/28790587-60d012da-7632-11e7-82c4-f4fea7fad58f.jpg)
Then double click in first row and there is a navigation to EditCustomerView for editing. Save changes and comes back CustomersView. GoBack() method freeze for 1-2 second and the filter is clear:
![2](https://user-images.githubusercontent.com/30556809/28791077-dae0df68-7633-11e7-98df-36cde5049623.jpg)

If to put TextBox under DataGrid and edit property Text after navigation Text doesn't change, I expect such behavior from DataGridColumnHeader filter.

**Comment by brianlagunas** [comment]
I'm sorry but this is not a Prism issue.  Prism has no influence over the DataGrid control or the code you have written for it.  All Prism does is get you from one page to another.  You may have better luck posting your question on StackOverflow and be sure to provide a working example.  No one will be able to help based off this description of the problem.  They'll need a working repro of the issue to debug.
