### ISSUE TITLE
Prism Forms Modularity

### ISSUE THREAD

**Issue by dansiegel** [PrismLibrary/Prism#1132]
Modularity registration should be made a little easier.

Currently registering a Module requires something like:

```cs
ModuleCatalog.AddModule(new ModuleInfo(typeof(ModuleA.ModuleAModule)));
ModuleCatalog.AddModule(new ModuleInfo("ModuleA", typeof(ModuleA.ModuleAModule), InitializationMode.OnDemand));
```

We can make this simpler by updating the API to include a new AddModule method like:

```cs
ModuleCatalog.AddModule<ModuleAModule>();
ModuleCatalog.AddModule<ModuleAModule>(InitializationMode.OnDemand);
```

**Comment by brianlagunas** [comment]
And `ModuleCatalog.AddModule<ModuleAModule>("ModuleA", InitializationMode.OnDemand);`
