### ISSUE TITLE
Cancel Navigation in UWP Prism App

### ISSUE THREAD

**Issue by Robzilla** [PrismLibrary/Prism#1137]
Posted this to StackOverflow on Jul 29th [https://stackoverflow.com/questions/45386337/cancel-navigation-in-uwp-prism-app](url) but no solution as yet so I am hoping some of the contributors can have a look. Essentially I am using building upon the splitview hamburger UWP example. I am initiating a navigation event in the navigation menu but there is dirty data in the main view. I need to be able to cancel/pause navigation to ask the user if they would like to lose any unsaved data (pretty common requirement). But if I check `isDirty` on the model, and try to cancel the navigation event using `e.Cancel` in the `OnNavigatingFrom` override in the main view model, the navigation menu view model ignores this and the navigation menu view model and menu view model get out of sync.

**Comment by bartlannoeye** [comment]
Thanks for posting the question on StackOverflow (where it belongs). I've seen it pass by, but haven't had time yet to look into it last week as I was on vacation. I'll come back to the question on SO asap (if it isn't answered by then). If it would require a change in Prism, I'll reopen this issue.

**Comment by Robzilla** [comment]
Still no answer on SO, can one of the core devs (Brian?) please have a look? If this is scenario is not possible I will have to look at ditching Prism. I have been using Prism for years and would not be very keen on using another framework. But the ability to cancel navigation and have all navigation elements still in sync is pretty important.

**Comment by brianlagunas** [comment]
I haven't looked at any code, but my first thought is that trying to cancel navigation after the navigation process has started is the wrong approach.  You want to check to see if you are allowed to navigate first, and then proceed to navigate if you at allowed to.  Do the check first before navigating.
