### ISSUE TITLE
No event is fired when returning from non-modal navigation using native Back Button from UWP (

### ISSUE THREAD

**Issue by juninholiveira** [PrismLibrary/Prism#1138]
Currently, i don't seen to find a way to fire any event when i return from my non-modal pages in my Xamarin.Forms app in the UWP.

My hierarchy is: 
NavigationPage/MasterDetail/SomePage/SomeOtherPage

I navigate deeper into the stack using non-modal navigation, so i can have the Back Button in top of my UWP window. When i click it I return to the previou spage in the stack, but my app doesn't know it. He kind of still thinks i'm into the last page.

Will be ever implemented some way to the OnNavigatedTo/From/etc acknowledge the UWP Back Button pressing? Or probably not because there is a better way to get the same effect?

Prism: 6.3.0
Xamarin.Forms: 2.3.5.256-pre6

**Comment by brianlagunas** [comment]
First off, don't put a MasterDetailPage inside a navigation page.  That's not a recommended navigation pattern.  Instead you need to have the MasterDetail set as the root, and have the Detail wrapped in a NavigationPage.  Like "MasterDetail/NavigationPage/SomePage".  The INavigationAware methods work as expected.
