### ISSUE TITLE
XF Modularity Enhancements

### ISSUE THREAD

**Issue by dansiegel** [PrismLibrary/Prism#1139]
The following enhancements should be added to make Prism Modularity easier to work with:

1. Extension Method to determine if a Module has been added
1. Extension Method to determine if a Module has been initialized
1. Extension Methods should be made to support support for evaluating the Module by type/name similar to the current generic extensions for `AddModule`
1. The Module Catalog should use an ObservableCollection rather than a List to allow the automatic initialization of Modules added to the Module Catalog. Specifically when that Module is registered with `InitializationMode.WhenAvailable`, and AFTER `IModuleManager.Run()` has been called.
    1. This requirement would also mean that the Module Manager should be run even if no Modules were added to the Catalog as we would need to ensure that Modules could be added successfully later.

**Comment by brianlagunas** [comment]
Option 4 is not a scenario that needs to be handled.

**Comment by dansiegel** [comment]
Autofac Modules in Prism Forms should also be updated to support a more traditional Module approach

```cs
public interface IAutofacModule : IModule
{
    void Initialize(ContainerBuilder builder);
}

public abstract class AutofacModuleBase : IAutofacModule
{
    public void Initialize() => new NotImplementedException();

    public abstract void Initialize(ContainerBuilder builder);
}
```

This would allow Prism.Autofac.Forms to then provide it's own ModuleManager with the PrismApplication's ContainerBuilder so that it can pass the builder into the modules `Initialize` method before the Container is built.
