### ISSUE TITLE
How to make PopWindow(Notification\Comfirm\CustomPop) as Metro Style

### ISSUE THREAD

**Issue by bobdog1986** [PrismLibrary/Prism#1140]
Hello everyone!
     I'm learning prism framework and Prism-Sample-WPF demos.
     After install MahApps.Metro Nugets, the MainWindow show as new style, but the PopWindows(included Notification\Comfirm\CustomPop) still shown as old style, like  follow picture(button-style already changed !). 
     How can I do?

![2017-08-15_111213](https://user-images.githubusercontent.com/9330555/29301046-0d8be77c-81ac-11e7-8b31-cf800d516f19.png)

**Comment by MichaelPonti** [comment]
I didn't look in the code, but I am sure custompop doesn't use the same class as your mainwindow (MetroWindow). If I were to suggest something, I would say use the CustomDialog that is in the MahApps nuget instead. You will get the metro style popup on your main window.

If you look in the Mahapps demo app, you will see in the pulldown menus, different ways of calling dialogs, including from the viewmodel.

**Comment by brianlagunas** [comment]
If you want to use the PopUpWindowAction, the create a custom class that derives from `PopupWindowAction` and override the `CreateWindow` method and provide your own Window class.  Then use the custom action in your XAML markup.
