### ISSUE TITLE
ObservesProperty params overload

### ISSUE THREAD

**Issue by Giorgi** [PrismLibrary/Prism#1143]
It is very common for CanExecute to depend on multiple properties. I think it would be helpful to have an overload of ObservesProperty which takes an array of expressions (with params) so that it's a little bit easier to pass multiple properties.

I can send a PR if you also think that it would be useful to have such functionality.

**Comment by brianlagunas** [comment]
You can already add support for multiple ObservesProperty call by chaining them using the fluent API that is available.

`ObservesProperty(() => PropA).ObservesProperty(() => PropB)`

**Comment by Giorgi** [comment]
Yes, you can already do it but something like this looks cleaner/less verbose to me:

`ObservesProperty(() => PropA, () => PropB)`

**Comment by dansiegel** [comment]
@Giorgi you can easily add an extension method to your project to allow you to do that.

**Comment by brianlagunas** [comment]
Then that method would not called "ObservesProperty", instead it would be called "ObservesProperties" :)

**Comment by Giorgi** [comment]
Yes, I agree that it's very easy to add such extension method but why not include it in the framework itself?

**Comment by brianlagunas** [comment]
Because that syntax is not representative of the method name and that is not how I want to API to function.  This comes down to a personal preference, and since this API must support a very wide user base, I prefer to make the API as explicit as possible.

**Comment by Giorgi** [comment]
Yes, I agree ObservesProperties would have been a better name. As for making the api explicit I'm not saying that we should remove the current `ObservesProperty` method, just add a new one which makes observing multiple properties less verbose but as you said it's a personal preference.
