### ISSUE TITLE
System.IO.FileNotFoundException Prism.resources.dll

### ISSUE THREAD

**Issue by mo-kml** [PrismLibrary/Prism#1145]
hi there
im trying to navigate to an page but i get this error
System.IO.FileNotFoundException: 
File name: '/storage/emulated/0/Android/data/Tipax.Xamarin.Android/files/.__override__/en-US/Prism.resources.dll'
  at (wrapper managed-to-native) System.Reflection.Assembly:LoadFrom (string,bool)
  at System.Reflection.Assembly.LoadFrom (System.String assemblyFile) [0x00000] in <3fd174ff54b146228c505f23cf75ce71>:0 
  at System.Reflection.Assembly.InternalGetSatelliteAssembly (System.String name, System.Globalization.CultureInfo culture, System.Version version, System.Boolean throwOnFileNotFound, System.Threading.StackCrawlMark& stackMark) [0x000ad] in <3fd174ff54b146228c505f23cf75ce71>:0 }	System.IO.FileNotFoundException

before it i got this error about autofac.resources.dll but when i reinstall the autofac package it disapeared
im using xamarin forms shared

**Comment by brianlagunas** [comment]
I've never seen this and cannot reproduce it.  Make sure you have added all the necessary packages to every project in your solution.  You can try deleting all the obj and bin folders and rebuilding.

**Comment by mo-kml** [comment]
that didnt really help at all. actually when i register a navigationPage and try to pass all my pages through it i one of my pages when i try to Goback this exception happens. but when i dont use a navigationPage this will not happen at all.
how would i fix this?

**Comment by ysmoradi** [comment]
Hi @brianlagunas 

I think I managed to find something related to this issue.

Consider following code in Prism library (as an example only) =>

https://github.com/PrismLibrary/Prism/blob/master/Source/Prism/Commands/DelegateCommand%7BT%7D.cs#L67

```csharp
throw new InvalidCastException(Resources.DelegateCommandInvalidGenericPayloadType);
```

It uses "Resources" which are stored in Resx file. The Prism nuget package does not contain any Resource dll and I receive the same exception "System.IO.FileNotFoundException Prism.resources.dll" when I reach that code I mentioned before.

**Comment by dansiegel** [comment]
What version of Prism are you using?

**Comment by brianlagunas** [comment]
Resources are embedded into an assembly.  It's not a separate DLL and you do not reference it.  This is usually a sign of another problem in your project.

**Comment by ysmoradi** [comment]
@dansiegel Latest stable versions of VS 2017.4 + Xamarin.Android + Xamarin.Forms + Prism
There is no update indicator in nuget package manager & vs notification center.
@brianlagunas I'm sure that it's somehow related to our project, but I can't find out how!
I'm trying to find more info and I'll discus them here as I move forward.
Thanks in advance.
