### ISSUE TITLE
XF - How using NavigationService from Native.Android & Native.iOS project?

### ISSUE THREAD

**Issue by juanagu** [PrismLibrary/Prism#1147]
I need call INavigationService.NavigateAsync from native project, after open a notification and pass a NavigationParameter with information.

Any suggestion?

**Comment by brianlagunas** [comment]
You don't.  If you are in native code, you need to use native navigation code.

Although, a hack would be to use the event aggregator to send a message to a VM that will handle the navigation in response.

**Comment by juanagu** [comment]
Thanks, I implemented the event aggregator and works! :)
