### ISSUE TITLE
Enhance EventToCommandBehavior to send the event args object itself

### ISSUE THREAD

**Issue by smalleythedave** [PrismLibrary/Prism#1148]
Hi,

I often need to send the original event args object as the parameter for Execute(object) instead of a bound value or an extracted path. I am able to accomplish this by using an IValueConverter which simply returns the original value, but I think having to provide this class and registering it in a resource dictionary (or binding it from a view model), is a lot of trouble for something simple. It occurred to me that if CommandParameter, EventArgsParameterPath, and EventArgsConverter are all null (i.e., not specified in the XAML), the parameter could default to the original event args. Or, some magic string like "." as EventArgsParameterPath could trigger it.

This need usually arises when event args has something like a Cancel property, and it's necessary to "return" this value from handling the event.

Dave

**Comment by brianlagunas** [comment]
Thanks for the idea, but this violates the MVVM pattern as you are now passing view objects into your VM.  It is never recommended to pass event args into your VM.  For these reasons, this suggestion will not be implemented.  Thanks again.
