### ISSUE TITLE
[UWP] SplitView Navigation Sample and Dev/Sandbox Project

### ISSUE THREAD

**Issue by veccie** [PrismLibrary/Prism#115]
As mentioned in #67 /cc #102 I've been working on a SplitView Navigation sample template that works well with Prism. Basically I wanted a template where I could easily add new navigation items and it just worked without me doing anything else. At the same time it should also be fairly consistent in design when switching between Light and Dark theme. Therefore this sample only uses system theme colors.

I've created a new branch for it and the code can be found here: https://github.com/veccie/Prism/tree/sandbox-windows10/Samples/Sandbox/Windows10

Some of the code is based on [Microsoft's SplitView sample](https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/XamlNavigation/cs) which uses a ListView for navigation items. I wanted to use a ListView mainly because it's more flexible than for example ItemsControl in terms of functionality and design.

The purpose of this post is mainly to:
* Show how one implementation of SplitView navigation using Prism could look like.
* Get feedback and give others the opportunity to use and help improve it.
* Propose this as a dev/test/sandbox/source solution template for a platform, which can be used to test various scenarios while developing Prism. More test/sample projects can be added to each solution where needed. In this case it's for UWP, but the same setup could be used for all the other platforms. Once Prism 6 is released App projects in these solutions can then be copied and linked to the NuGet packages instead of the source as @brianlagunas also talks about in #73 You're welcome to use my SplitView navigation sample if it's good enough.

## Notes:
The basic idea/concept of my SplitView navigation implementation is to get a "confirmation loop" going when navigating. By that I mean that the selected navigation item should only be updated if we can confirm that a Page has actually been navigated to. In short the "confirmation loop" looks something like this:
* A navigation item is clicked
* Frame.Navigate is called
* OnNavigatedTo is called
  * PubSubEvent(OnNavigatedTo) is published (which the SplitView's ListView is subscribed to)
    * The ListView selects the right navigation item and saves the selected index internally.
* ListView.SelectionChanged event occurs (this event is always fired when clicking an item)
  * If the selected index is different from the internal index we set it back to what the selected index was before the click event.

There are several benefits of this concept:
* The navigation menu automatically reflects the Page that is currently shown.
* When using shortcuts like mouse forward/backward the menu is automatically updated through the PubSubEvent(OnNavigatedTo) which then selects the right navigation item.
* If a navigation command is canceled we can then skip the PubSubEvent(OnNavigatedTo) call and the selected navigation item is automatically reset(if started from a click event).
* Not necessarily related to Page navigation, but events for changes to SplitView.DisplayMode and IsPaneOpen can also be subscribed to.

## Todos:
* As mentioned in #67 this implementation could benefit from exposing BackStack/Depth when navigating to sub-pages. The code has been disabled for now.
* The MainPage in this sample shows a very simple way of adjusting to SplitView.DisplayMode events, but a shared PageHeader control applying the same technique might be better for many apps.
* Add swipe support

For new eyes all this might seem rather complicated and for the sake of understanding what's going on I've left a lot of Debug.Writeline() in the code. I hope the Debug info will help you in seeing the call stack/flow and better understand/give feedback on it. I will remove these later.

Any feedback is much appreciated.

**Comment by brianlagunas** [comment]
Thanks for sharing your sample.
