### ISSUE TITLE
(WPF) Loading Modules in MEF via app.config

### ISSUE THREAD

**Issue by Dirkster99** [PrismLibrary/Prism#1151]
I want to use PRISM MEF to load a module:
https://github.com/Dirkster99/Edi

but the loading fails when I start the application from a different folder than the application's folder. I am using the following app.config entry which works otherwise OK:

```<modules>
  <module assemblyFile="Plugins/MyPlugin.dll" moduleType="Plugin.Module"
          moduleName="MyPlugin" startupLoaded="true" />
</modules>
```

Is it possible to use something like this:

```<modules>
  <module assemblyFile="$(AppDir)\Plugins/MyPlugin.dll" moduleType="Plugin.Module"
          moduleName="MyPlugin" startupLoaded="true" />
</modules>
```

to always force the searchpath below the application's path?

I otherwise have trouble loading MEF modules when the current directory happens to be another one than the applications directory :-(

**Comment by brianlagunas** [comment]
This question belongs on StackOverflow where the community can support the MEF functionality.  The Prism team no longer supports MEF.  MEF is still provided as a courtesy to existing applications.

**Comment by Dirkster99** [comment]
Thats funny because I already asked the question on [Stackoverflow](https://stackoverflow.com/questions/45871319/loadin-modules-in-mef-via-app-config)
Got NO answer

Asked it on [MSDN](https://social.msdn.microsoft.com/Forums/en-US/98b9f718-bead-47c4-a672-e30f931ec07b/loading-modules-in-mef-via-appconfig?forum=netfxbcl)

and they directed me her to be directed to StackOverflow :-(

I was not aware that MEF is discontinued.
Is there a replacement for MEF?

**Comment by brianlagunas** [comment]
MEF is not an IoC container, hence you would need to move to an actual supported container.  You can find a list on the ReadMe page.

But, moving to a supported container won't solve your problem.  The syntax you are trying to use is not supported.  You would be better off using a DirectoryCatalog and specifying the relative path in code. Not in an app.config.

**Comment by brianlagunas** [comment]
By the way, if your application allows unknown 3rd parties to add plugins into your app, then you can still use MEF because that is what it is meant for.  You just won't be using a MEF bootsrapper.
