### ISSUE TITLE
How to avoid calling OnNavigatedTo when coming back from detail page to listview page

### ISSUE THREAD

**Issue by avinashramireddy-rapidd** [PrismLibrary/Prism#1153]
Hi,
I just started using Prism. It's really awesome.
Started using to show some data via calling api. 

Calling _GetDataServiceAsync_ inside _async OnNavigatedTo_ method to get listview details.
When I click particular item,it takes me to details page which is totally fine. 
Now when comeback to listview page by pressing hardware/software button, _OnNavigatedTo_ is called again making call to api again which is not what I want to have(too many calls to api everytime something is clicked).

So my question is "Is there any way to avoid triggering OnNavigatedTo or not calling api when come back from details page" which is not really making sense in my application. I would rather have a refresh button at this moment(getting familiar with Prism - Day1)

**Comment by bartlannoeye** [comment]
Please ask these questions on [StackOverflow](https://stackoverflow.com/questions/tagged/prism) in the future, GitHub issues should only be used for issues with Prism.

You can test if the navigation is back, if so don't do a new call.

You should also consider using a caching service (like [Akavache](https://github.com/akavache/Akavache)) to prevent multiple web calls in a given timespan (eg. 5 mins) no matter what your navigation is.

**Comment by avinashramireddy-rapidd** [comment]
Sure. Will keep that in mind. I just thought that it will be fast for reply if I do ask here.

**_You can test if the navigation is back, if so don't do a new call._** - Should I use eventaggregator or messaging center to remember that I am navigating back or something else?
 I am not sure with the approach in Prism for this kind of things.

Of course, I try to use _Akavache_ but I would like to also  know about the approach to follow just in case if I can't make it work.

**Comment by brianlagunas** [comment]
Check the NavigatioMode on the NavigationParameters. It will tell you if you are navigating back.

**Comment by avinashramireddy-rapidd** [comment]
Thanks. It worked.
