### ISSUE TITLE
[XF] ModalBack NavigationMethod

### ISSUE THREAD

**Issue by CMorooney** [PrismLibrary/Prism#1154]
I was thinking about putting in some work and submitting a PR for adding an enum value to NavigationMethod to signify that a modal page was dismissed as currently the NavigationMethod is always simply "Back" when popping off the stack or dismissing a modal page. Saw under the contribution guidelines that an issue should be submitted first -- is this something others would like to have?

**Comment by brianlagunas** [comment]
What is the benefit of knowing of the page was modal or not?

**Comment by CMorooney** [comment]
I have a use case in my app where a page will present a modal to select a location when filling out a form. The modal will be dismissed when a location is selected and the user will be back at the form. 

Once the form is completed the app will push a new page. In OnNavigatedTo of my view model for the form I would be checking the parameters for the selected location data, but that data would not be there when popping back from the new pushed page.

I could make an extra check on the parameters or pass the data back from the modal view model in another way. In my case, however, I thought it would be clean to check how the page was navigated to, knowing that if it came back from a modal navigation that there would be location data to consume.

**Comment by brianlagunas** [comment]
Knowing a modal vs. a non-modal back operation is not the correct approach to your problem.  You should pass the information you need to your VM.  Check to see if the location is in the parameters, and if it's not then you don't need to do anything.
