### ISSUE TITLE
Visual Studio for Mac Prism template pack creates a Prism Unity template when choosing a Prism DryIoc template

### ISSUE THREAD

**Issue by etiennestrydom** [PrismLibrary/Prism#1155]
### Package info

- Platform: Xamarin.Forms
- Xamarin.Forms 2.3.4.270
- Xamarin.Android 7.4
- Xamarin.iOS 10.12
- Xamarin.Mac 3.6
- Visual Studio for Mac 7.1.0.1297
- Prism.Forms 6.3.0
- Prism.Core 6.3.0
- Prism.DryIoc.Forms 6.3.0.1

### Repro steps

I referenced the Prism template pack in Visual Studio Mac by adding the url: https://prism.azureedge.net/main.mrep to the extensions. The templates seem to be working. The issue is when I create a new project using either a “Prism DryIoc App” or a “Prism Unity App” the project template is always the “Prism Unity App” and never a “Prism DryIoc App”, so I have to do a bit of tweaking to make the project build.

Also when using the standard template code in the App.xaml.cs:

    protected override void OnInitialized()
    {
        InitializeComponent();
        
        NavigationService.NavigateAsync("MainPage?title=Hello%20from%20Xamarin.Forms");
    }
    
The AutowireViewModel="True" does not seem to link to the viewmodel automatically. But when I change the code in the App.xaml.cs to:

    protected override void OnInitialized()
    {
        InitializeComponent();

        MainPage = new MainPage();

        //NavigationService.NavigateAsync("MainPage");
    }

    protected override void RegisterTypes()
    {
        Container.RegisterTypeForNavigation<MainPage, MainPageViewModel>();
        Container.RegisterTypeForNavigation<SpeakPage>();
    }
    
The AutowireViewModel="True" starts working for all the pages and Prism starts working as described in the docs.

**Comment by etiennestrydom** [comment]
The viewmodels not automatically linking is caused by template pack creating the MainPage.xaml with a double reference to Views in the namespace: 

    x:Class="MyApp.Views.Views.MainPage"

After fixing all the namespaces and changing my code in the App.xaml.cs to:

        protected override void OnInitialized()
        {
            InitializeComponent();

            //MainPage = new MainPage();

            NavigationService.NavigateAsync("MainPage?title=Hello%20from%20Xamarin.Forms");
        }

the MainPage's viewmodel seems to be linked and triggering the constructor but before the page renders there is an error:

### Foundation.MonoTouchException:
Objective-C exception thrown.  Name: NSInternalInconsistencyException Reason: Application windows are expected to have a root view controller at the end of application launch"

**Comment by dansiegel** [comment]
Thanks for the report. I was able to duplicate the issue, and will have a fix out as soon as I can... also note that the feed was updated to https://addin.prismlibrary.com/main.mrep

**Comment by dansiegel** [comment]
this has been fixed. please update the Template Pack in VS4Mac

**Comment by etiennestrydom** [comment]
Cool thanx! works like a charm :). Is this documented anywhere or where can I read more about the template pack for mac?

**Comment by dansiegel** [comment]
I still need to update the ReadMe, but you can read more on http://dansiegel.net/post/2017/08/30/prism-template-pack-in-visual-studio-for-mac
