### ISSUE TITLE
Navigation from Tabpage

### ISSUE THREAD

**Issue by manojtailor2k17** [PrismLibrary/Prism#1156]
When Navigating From tabpage the navigation bar is not visible.
My tab page looks like this
<TabbedPage xmlns="http://xamarin.com/schemas/2014/forms"
            xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
            xmlns:ctrl="clr-namespace:Messier16.Forms.Controls;assembly=Messier16.Forms.Controls"
            xmlns:prism="clr-namespace:Prism.Mvvm;assembly=Prism.Forms"
            prism:ViewModelLocator.AutowireViewModel="True"
             xmlns:local="clr-namespace:app.Mobile.Views"
            x:Class="app.Mobile.Views.BottomTabPage">

    <TabbedPage.Children>
        <local:ViewA  Icon="a.png" Title=""/>
        <local:ViewB Icon="b.png" Title=""/>
        <local:ViewC Icon="c.png" Title=""/>
        
    </TabbedPage.Children>
</TabbedPage>

 public partial class BottomTabPage : PlatformTabbedPage, INavigatingAware
    {
        public BottomTabPage()
        {
            InitializeComponent();
         
        }

        public void OnNavigatingTo(NavigationParameters parameters)
        {
            foreach (var child in Children)
            {
                (child as INavigatingAware)?.OnNavigatingTo(parameters);
                (child?.BindingContext as INavigatingAware)?.OnNavigatingTo(parameters);
            }
        }
    }
}

Now when navigating from ViewA content page Navigation bar is not visible.

**Comment by brianlagunas** [comment]
You've already asked this question on SO

https://stackoverflow.com/questions/46153040/navigation-from-tabpage-in-prism-in-xamarinforms
