### ISSUE TITLE
Region not fully removed with view

### ISSUE THREAD

**Issue by wowfood** [PrismLibrary/Prism#1157]
Package info

- Platform:  Windows 7
- Prism version:    6.3.0
- Other version info:  Prism.Core, Prism.Ninject, Prism.Wpf:

### Repro steps

This is likely a bit of a fringe scenario but I believe it may be a prism bug (or I'm just doing something wrong)

Shell view is set up with a content region.  
ViewA has a its own region (lets call it subRegion)
ViewA KeepAlive = false;

All views are registered using 

`Kernel.RegisterTypeForNavigation<ViewAView>( PageNames.ViewA );`

When I navigate forwards from this view to a new view it's removed from the region / memory.  In doing so subRegion also appears to be getting removed from the regionManager.

However when I navigate back to ViewA and it tries to recreate the view I get the following error.

> Prism.Regions.Behaviors.RegionCreationException: 'An exception occurred while creating a region with name 'SubRegion'. The exception was: System.ArgumentException: Region with the given name is already registered: SubRegion

The workaround I have at the moment is to put the following into my ViewModels OnNavigatedFrom

```
public override void OnNavigatedFrom(NavigationContext navigationContext)
{
    base.OnNavigatedFrom(navigationContext);

    if (_regionManager.Regions.ContainsRegionWithName(RegionNames.SubRegion))
    {
    // i cannot explain this.  But having this check here prevents a crash...
    }
}
```

The if statement never enters as the region doesn't exist after the base does its thing, so externally it doesn't look like it should fix anything (but it does, I only found this workaround by accident).

I believe what is happening is that normally when a region is removed Prism automatically calls updateRegions();

However where the region is being magically removed along with the view i don't believe updateRegion(); is getting called so something still thinks the region exists.  (best guess, I haven't had a chance to dig too deep)

Like I said it may just be user stupidity here, but it's the best explanation I can think of.

**Comment by brianlagunas** [comment]
Thanks for reporting this and the work around.  Can you by chance provide a simple repro app?

**Comment by wowfood** [comment]
I'll try and put something together when I get the chance.  Right now both work and weekends are being kept busy.

**Comment by brianlagunas** [comment]
It's been a month, so I am closing this as I think this may have been related to #1161. If you still wish to follow up on this, please feel free to continue the conversation.
