### ISSUE TITLE
Using Lazy<> with Prism.DryIoc.Forms doesn't work

### ISSUE THREAD

**Issue by JaccoDieleman** [PrismLibrary/Prism#1160]
To minimize the startup time of the app we are using the Lazy<> pattern for classes with a lot of dependencies. This works fine with Prism.Unity.Forms. However, I can't get it to work with Prism.DryIoc.Forms. When I try to use the Lazy param that is being passed into the ViewModel, I get an exception with message "_Container is no longer available (has been garbage-collected)._" .

### Package info

- Platform: all
- PrismDryIoc.Forms version: 6.3.0.1
- Is dependent on DryIoc: 2.10.1

### Repro steps
We have a page view model like this:
```
public class MySamplePageViewModel
{
    private readonly Lazy<ISomeClass> _lazySomeClass;

    public MySamplePageViewModel(Lazy<ISomeClass> lazySomeClass)
    {
        _lazySomeClass = lazySomeClass;
    }

    public void SomeMethod()
    {
        _lazySomeClass.Value.DoIt(); //throws exception
    }
}
```
We are doing the registration like this:
```
container.Register<ISomeClass, SomeClass>(Reuse.Singleton);
container.RegisterTypeForNavigation<MySamplePage, MySamplePageViewModel>("MySamplePage");
```
However, after the page view model is being instantiated, when calling _lazySomeClass.Value we get an exception with message "_Container is no longer available (has been garbage-collected)._".

I asked [the question on stackoverflow](https://stackoverflow.com/questions/46195007/using-lazy-with-prism-dryioc-forms-gives-container-is-garbage-collected-exce) and [according to the creator of DryIoc](https://stackoverflow.com/a/46213657) this can simply be solved by updating Prism.DryIoc.Forms with a reference to the 2.10.3 version of DryIoc.

**Comment by brianlagunas** [comment]
This seems like an easy fix.  I'll update the DryIoC version and you can test it out in our CI builds on MyGet.

**Comment by dansiegel** [comment]
I'm closing this as we already target a newer version of DryIoc than you are asking about.

**Comment by brianlagunas** [comment]
Connect to this feed and test it out: https://www.myget.org/gallery/prism

**Comment by JaccoDieleman** [comment]
I tested it with Prism.DryIoc.Forms 7.0.0.51-ci and it worked like a charm! Thanks guys!
