### ISSUE TITLE
Prism.Unity.Xamarin.Forms Async Method OnNavigatedTo not updating View

### ISSUE THREAD

**Issue by AbhijeetChowdhury** [PrismLibrary/Prism#1162]
@brianlagunas 
I am developing a Xamarin app using Prism Unity. I am facing problem on Refreshing the binding of view after my method is called OnNavigatedTo event in my ViewModel class. I am using Fody for property changed. PFB the code snippet:

Model:

public class Load:BindableBase
{
public string proNumber {get; set;}
...
}

ViewModel:

public Load load{get; set;}
public async void OnNavigatedTo(NavigationParameters parameters)
        {
           load = await retrieveTrip();//this service takes much amount of time
           //load = Task.Run(async()=>await retrieveTrip()).Result; //if we do this it works fine but it lacks asynchronus way
        }

The View has binding of the Load object.

```
<StackLayout Spacing="5" Padding="10">
                <Label Text="{Binding load.proNumber,Mode=TwoWay}"
                       Style="{StaticResource labelContentStyle}"></Label>
</StackLayout>
```

If we call the service method async way the label text always comes blank. But on synchronus calling it works as expected.

Any help will be appreciated.
Thanks in advance!

**Comment by brianlagunas** [comment]
I'm sorry, but this type of question belongs on [SO](https://stackoverflow.com/questions/tagged/prism).  This is not an issue or even really related to Prism, but rather a general programming question.
