### ISSUE TITLE
Custom NavigationPage is not working properly Prism 7

### ISSUE THREAD

**Issue by KalpeshChheda** [PrismLibrary/Prism#1166]
Custom NavigationPage is not working properly 

I have navigation like this
await NavigationService.NavigateAsync("app:///TestNavigationPage/MainPage", navPar);
RegistrationPageViewModel's constructor is getting called 2 times
If am changing to
await NavigationService.NavigateAsync("app:///NavigationPage/MainPage", navPar);
RegistrationPageViewModel's constructor is getting called 1 time only which is should be

### Package info

- Platform: Windows/UWP
- Prism version: Prism Form 7 Pre1
- Xamarin Forms version (if applicable): 2.4.0 Pre 3

### Repro steps

https://www.dropbox.com/s/xlt5o67by7m0vym/PrismUnityApp1.zip?dl=0

**Comment by brianlagunas** [comment]
Good find.  This is related to the new ReverseNavigation method added to the NavigationService to address two other bugs.  The work around is to add the following ctor to your custom NavigationPage:
```
        public TestNavigationPage(Page page) : base(page)
        {
            InitializeComponent();
        }
```

**Comment by brianlagunas** [comment]
This has been fixed.  You can try it out by using the latest CI build on MyGet 

https://www.myget.org/gallery/prism

You should delete that workaround code now :)

**Comment by joncortez** [comment]
@brianlagunas - It seems that I still need to have the ctor above if I have a custom NavigationPage on a TabbedPage. Otherwise, I am getting the following exception System.MissingMethodException: Constructor on type 'WellRx.Forms.Views.MyNavigationPage' not found. Is this a regression of the previous bug?

MainTabbed.xaml
```XML
<?xml version="1.0" encoding="UTF-8"?>
<TabbedPage
    xmlns="http://xamarin.com/schemas/2014/forms"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:views="clr-namespace:MyApp.Forms.Views;assembly=MyApp.Forms"
    x:Class="MyApp.Forms.Views.MainTabbedPage">
	<TabbedPage.Children>
        <views:MyNavigationPage Title="Tab1">
            <x:Arguments>
                <views:Tab1Page />
            </x:Arguments>
        </views:MyNavigationPage>
        <views:MyNavigationPage Title="Tab2">
            <x:Arguments>
                <views:Tab2Page />
            </x:Arguments>
        </views:MyNavigationPage>
	</views:TabbedPage.Children>    
</TabbedPage>
```
MyNavigationPage.cs
```csharp
public class MyNavigationPage : NavigationPage
{
   public MyNavigationPage()
   {
      BarTextColor = (Color)Application.Current.Resources["primary-color"];
      BarBackgroundColor = Color.White;
   }
}
```

## Package info
Platform: Visual Studio for Mac
Prism version: Prism Form 7.0.0.396
Xamarin Forms version (if applicable): 2.5.0.280555

**Comment by ribas1a3** [comment]
Can confirm the issue still exists and needs the workaround.

**Comment by brianlagunas** [comment]
This original issue does not exist anymore.  If you are talking about the requirement for having a ctor that accepts a page when using it in a TabbedPage, then that is correct.  That is required by the XAML parser to define a NavigationPage in XAML.

**Comment by JoeDurand3** [comment]
I think he means the default navigation page provided by Forms:

```
containerRegistry.RegisterForNavigation<CustomNavigationPage>("NavigationPage");
...
navigationService.NavigateAsync("NavigationPage/LoginPage");
```

I've also tried:

```
containerRegistry.RegisterForNavigation<CustomNavigationPage>();
...
navigationService.NavigateAsync("CustomNavigationPage/LoginPage");
```

**Comment by brianlagunas** [comment]
@JoeDurand3 I cannot duplicate. Custom navigation pages are working fine for me.
