### ISSUE TITLE
XF Compiling from source fails

### ISSUE THREAD

**Issue by opcodewriter** [PrismLibrary/Prism#1168]
I have an issue in my XF app with DI not working, so I wanted to debug Prism.

I checked out the source code for the latest stable 6.3.0 version:

![image](https://user-images.githubusercontent.com/15019084/30771300-16f89ae8-a04d-11e7-89c4-f13895859eb3.png)

then opened `PrismLibrary_Wpf.sln` in VS2017 (v15.3.5) and tried to build and it shows two errors:

```
> 1>------ Rebuild All started: Project: Prism, Configuration: Debug Any CPU ------
> 1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\NuGet\15.0\Microsoft.NuGet.targets(178,5): error : Your project is not referencing the ".NETPortable,Version=v4.5,Profile=Profile259" framework. Add a reference to ".NETPortable,Version=v4.5,Profile=Profile259" in the "frameworks" section of your project.json, and then re-run NuGet restore.
> 2>------ Rebuild All started: Project: Prism.Forms, Configuration: Debug Any CPU ------
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\NuGet\15.0\Microsoft.NuGet.targets(178,5): error : Your project is not referencing the ".NETPortable,Version=v4.5,Profile=Profile259" framework. Add a reference to ".NETPortable,Version=v4.5,Profile=Profile259" in the "frameworks" section of your project.json, and then re-run NuGet restore.
> ========== Rebuild All: 0 succeeded, 2 failed, 0 skipped ==========
> 
```

Can please someone say what's wrong?

**Comment by opcodewriter** [comment]
Ha! It works in VS2015... but why? :\

**Comment by brianlagunas** [comment]
Glad you got it figured out

**Comment by opcodewriter** [comment]
@brianlagunas If you don't mind, why does compilation fail on VS2013?

**Comment by brianlagunas** [comment]
Hard to say.  It can be anything in your environment causing an issue.

**Comment by opcodewriter** [comment]
@brianlagunas I don't think it has to do with my environment at all. The build works on VS2015 but not on VS2017. I am pretty sure it's not my setup at all.
Does it compile fine for you in VS2017?

**Comment by brianlagunas** [comment]
I am actively developing Prism in VS2017.  So yeah, its working.

**Comment by opcodewriter** [comment]
I don't understand what you mean by "It can be anything in your environment causing an issue".
I have latest VS2017 Enterprise installed, v15.3.5.
What else should I need in my "environment" to compile a C# project? Clone repo and compile, should just work.
