### ISSUE TITLE
[XF] Add Windows Phone 8.1 target to Prims.Forms

### ISSUE THREAD

**Issue by ValdimarThor** [PrismLibrary/Prism#117]
Since XF now supports WinPhone 8.1 and WinRT 8.1, Prism.Forms should work as well?
I get this error when trying to add Prism.Forms to my XF project:
"Could not install package 'Prism.Forms 5.7.0-pre3'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile259', but the package does not contain any assembly references or content files that are compatible with the framework."
I hope I'm not stuck with WinPhone 8.1 Silverlight :)

**Comment by brianlagunas** [comment]
Right now there is a bug in Xamarin.Forms which breaks navigation on Windows Phone.  We are waiting for Xamarin.Forms to fix this bug before we upgrade the Prism project.  As of now, Prism for XF is still on v1.4.0.6341 and WP 8.0

**Comment by ValdimarThor** [comment]
Alright :) 
good to know :+1:

**Comment by martingust** [comment]
@brianlagunas Which is the bug in Xamarin.Forms? Would like to keep an eye on that one since we are also waiting on WP 8.1 support.

**Comment by brianlagunas** [comment]
It is related to navigating in Windows Phone when calling PopModalAsync would throw an exception.  This is supposed to be fixed soon.

**Comment by brianlagunas** [comment]
The navigation but was fixed by xamarin.  Now in order to add the WP 8.1 profile, we would have to upgrade to NuGet 3.0.  NuGet 3.0 really sucks, so this may take some time :)

**Comment by brianlagunas** [comment]
Xamarin fixed the navigation bug, so I upgraded to the latest version of Xamarin.Forms and added WP 8.1 support.
