### ISSUE TITLE
Prism XCode 9 - iOS 11 Updated - Error: Compiling IB documents...

### ISSUE THREAD

**Issue by eliasribeiro** [PrismLibrary/Prism#1170]
Hi, I updated XCode 9 because iOS 11 arrived and my iOS project stopped working. **Error:** Compiling IB documents before iOS 7 is no longer supported. When creating a new Prism project the same error is also displayed.

Does anyone know how to solve it?

Note: There is no storyboard in the iOS project.

**Comment by brianlagunas** [comment]
You're probably better off asking this question on the Xamarin forums.

**Comment by dansiegel** [comment]
@eliasribeiro can you clarify is this the Template Pack for VS2017 or VS4Mac?

**Comment by eliasribeiro** [comment]
Hi @dansiegel and @brianlagunas i use Prism Template Pack for VS2017(Windows 10), on MacOS only have XCode and VS2017 for Mac because i run on iPhone emulator.

I create one video for you look: [https://www.youtube.com/watch?v=DTVNQ8R_5mE](https://www.youtube.com/watch?v=DTVNQ8R_5mE)

Thanks for help.

**Comment by brianlagunas** [comment]
Maybe a stupid question, but did you make sure you have your deployment target set to 8.0 in the info.plist?  Since you upgraded your Mac versions, you need to update your deployment target too.
