### ISSUE TITLE
nuget package Prism.Unity 

### ISSUE THREAD

**Issue by ENikS** [PrismLibrary/Prism#1171]
Project link on package no longer works. 

https://www.nuget.org/packages/Prism.Unity/

**Comment by brianlagunas** [comment]
Which link exactly?  Can you be more specific?

**Comment by ENikS** [comment]
One with title: ``"http://prismlibrary.com/"``

**Comment by brianlagunas** [comment]
That link works perfectly for me. I clicked on it and the page loaded right up.

**Comment by ENikS** [comment]
It points to http://prismlibrary.github.io/WKloZ/ and  shows 404 for me.

**Comment by brianlagunas** [comment]
Not for me.  Still works perfectly.
