### ISSUE TITLE
Cell's Command.CanExecute being called with incorrect objects in ListView on UWP

### ISSUE THREAD

**Issue by xxMUROxx** [PrismLibrary/Prism#1176]
I know that this issue is not Prism related but it is very annoying:

https://bugzilla.xamarin.com/show_bug.cgi?id=55928

Therefore __only__ on UWP `DelegateCommand<T>.CanExecute` is executed multiple times with changing parameters. In my case the first time the BindingContext of the Form is passed first as parameter then the correct object specified in `CommandParameter`.

If the parameter is not of the type specified for T then an exception is thrown that is swallowed and as result the `cell's item` is empty.

Is there a possibility to change the behavior of DelegateCommand.CanExecute method to something like this?

    protected override bool CanExecute(object parameter)
    {
        if (Device.RuntimePlatform == Device.UWP || Device.RuntimePlatform == Device.WinPhone)
        {
            // BUG: TEMP FIX https://bugzilla.xamarin.com/show_bug.cgi?id=55928
            if (!Equals(parameter, default(T)) && !(parameter is T))
            {
                return false;
            }
        }
        return this.CanExecute((T) parameter);
    }

---
Currently another solution is to use following code instead of `TextCell.Command`

~~~
<ListView.Behaviors>
    <behaviors:EventToCommandBehavior Command="{Binding Path=CommandOpenArticle}"
                                      EventArgsParameterPath="Item"
                                      EventName="ItemTapped" />
</ListView.Behaviors>
~~~

But this solution does not work if I want to use a `CommandParameter` in a `TextCell.ContextActions`

**Comment by brianlagunas** [comment]
No, we are not changing the DelegateCommand's implementation as that is the wrong approach.  The DelegateCommand is used on multiple platforms and not limited to Xamarin.Forms.  For now you will have to implement the workaround in your code until Xamarin can fix their bug.

**Comment by xxMUROxx** [comment]
Ok, thanks for the reply
