### ISSUE TITLE
Add the possibility to autowire a viewmodel with instance names

### ISSUE THREAD

**Issue by less0** [PrismLibrary/Prism#1177]
### Package info

- Platform: Xamarin.Forms
- Prism version: 6.3
- Xamarin version (if applicable): 2.3.4.270

### Repro steps

I've not found anything about it, hence I assume that the issue has not been addressed, yet (although I don't think that the problem is too exotic). There are occasions when I need differently configured instances of types in different viewmodels. I can register these instances/types with different names, but there is no intuitive way to use these named instances/types in an autowired viewmodel. Currently I have to register the viewmodel manually with unity

```
this.Container.RegisterType<MyPageViewModel, MyPageViewModel>(new InjectionConstructor(new ResolvedParameter(typeof(IDependency), "DependencyName")));
```

This works and is fine, but makes the initialization more complex and is - to my understanding - not quite in the sense of viewmodel autowiring. I think - e.g. - introducing an attribute for the constructor parameter would render the code more expressive

```
class MyPageViewModel
{
  public MyPageViewModel([NamedDependency("DependencyName)] IDependency dependency)
  {
    ...
  }
}
```

**Comment by brianlagunas** [comment]
You don't register the VM with the container.  You only have to register your services with the container. `Container.RegisterType<IMyService, MyService>(...)`

**Comment by less0** [comment]
Thanks for your quick reply, Brian,

either me or you did understand something wrong. Of course what you wrote is correct, *if* there is only one registration of `IDependency`. But, if I registered `IDependency` twice

```
Container.RegisterType<IDependency, DependencyImpl>(/* default config */);
Container.RegisterType<IDependency, DependencyImpl>(/* custom config */, "CustomDependencyConfiguration");
```

there is no way of telling `ViewModelLocator` which registration to use and it will always use the first - unnamed. To avoid this, I have to use the workaround presented above. Or did I get something wrong?

**Comment by brianlagunas** [comment]
Well, I can safely say you understood something wrong :).  I get the feeling you are not experienced with DI containers such as Unity. This has nothing to do with Prism, but is related to how you register your services.  If you need a custom configuration use RegisterInstaance.  I suggest reading up on the Unity container to learn how you should be registering your types properly.

**Comment by brianlagunas** [comment]
With Unity, when you specify just the type in a constructor parameter the container will return the default concrete implementation of that type as defined in the registrations within the container. To specify a named registration when using constructor injection, you can add the Dependency attribute to the parameter definition, as shown below.
```
public class MyNewObject
{
  public MyNewObject([Dependency("CustomerDB")] IDatabase customers)
  { 
    // code to use the resolved IDatabase instance here
  }
} 
```

**Comment by less0** [comment]
Dear Brian,

Thank you very much. This is exactly what I wanted. 

Why shouldn't I register a custom configuration with `RegisterType`? With `InjectionConstructor` I can perfectly build up my custom configurations with `RegisterType`, too.

**Comment by brianlagunas** [comment]
You can if you want. Depends on your needs.  You should research the features of Unity and decide what approach is best for your app.
