### ISSUE TITLE
Region definitions in version 7

### ISSUE THREAD

**Issue by Teknel** [PrismLibrary/Prism#1178]
Is there any change in the definition of regions in version 7?
Because recompiling to that version I have the following error in the Prism.Wpf module:

An exception occurred while attempting to create region objects.
- The most likely causing exception was: 'System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Prism.Regions.Behaviors.RegionCreationException: An exception occurred while creating a region with name 'RegionShellHeader'. The exception was: Prism.Regions.UpdateRegionsException:

Thanks.

**Comment by brianlagunas** [comment]
No changes were made to regions in WPF.  All tests are passing, and I cannot duplicate this.  By the way, there is no version 7 of Prism.WPF released yet, so I'm not sure what exactly you have going on.
