### ISSUE TITLE
Prism.Mef.Wpf ask for v7 assembly

### ISSUE THREAD

**Issue by Teknel** [PrismLibrary/Prism#1179]
Returning to version 6.3.0 and having deleted all reference to version 7 I get the following error in the module Prism.Mef.Wpf:

  {"Could not load file or assembly 'Prism, Version = 7.0.0.0, Culture = neutral, PublicKeyToken = 40ee6c3a2184dc59' or one of its dependencies. ":" Prism, Version = 7.0.0.0, Culture = neutral, PublicKeyToken = 40ee6c3a2184dc59 "}

Any idea what can be missing to erase?

Before this modification everything worked normally

Thank you.

**Comment by brianlagunas** [comment]
Then you didn't delete everything with Prism 7.  Do a clean, and then delete your obj and bin folders.  Make sure you don't have any of the preview stuff installed.
