### ISSUE TITLE
Xamarin.iOS: Unable to locate assembly 'Prism.resources' (culture: 'en-US')

### ISSUE THREAD

**Issue by pawanshakya** [PrismLibrary/Prism#1180]
When I try to include third party solution (Expandable List View - https://github.com/umarmohammed/XFExpandableListView) into my existing Xamarin.Froms app with prism, facing above error. 
I have updated Prism and Xamarin.Forms packages as well in app but no luck. If I don't include this , solution works fine, looks like some reference I am missing here. 

Can someone please help me in this regard, If am missing anything here.

**Comment by dansiegel** [comment]
can you please provide a sample that reproduces the issue

**Comment by pawanshakya** [comment]
Including "xmlns:local="clr-namespace:XXX;assembly=XXX"  " and below lines for resources , seems to fix the issue for me. 

<ContentPage.Resources>
        <ResourceDictionary>
            <local:InverseBooleanConverter x:Key="boolInverter"></local:InverseBooleanConverter>
        </ResourceDictionary>
    </ContentPage.Resources>
