### ISSUE TITLE
Performance issue adding multiple regions

### ISSUE THREAD

**Issue by dkofoed** [PrismLibrary/Prism#1184]
### Package info

- Platform: Windows 10
- Prism version: 6.2.0.0
- Xamarin version (if applicable):
- Windows 10 SDK version (if applicable):
- Other version info:

### Repro steps

There is a noticeable delay when adding regions (we use navigation to populate them) on load.  We are using the tab control, and each tab is a separate region.  There may be up to 100 tabs (i.e. 100 regions) and we're seeing delays of up to 3 seconds just to create the regions themselves.  Can this be optimized at all?

**Comment by brianlagunas** [comment]
WOW!  100 tabs all with scoped regions?  Fire your app architect.  There is way too many variables going on here.  Everything from the size of the view and number f elements it has, to the view that is injected into the scoped region, to any behaviors be added, to any amount of code that is running in your VM's for each view that may not be written properly, to the amount of memory and size of process your computer has.  I can easily argue that this is not a result of a issue with Prism but rather app architecture.

A region doesn't really do anything different than you manually injecting the view yourself into the hosting control.  Anytime you start creating that many tabs with view with nested views, WPF will start to get sluggish.  You should do a full and thorough review of your application code by profiling it and identifying the various areas in your own code base that can improved.  Then we can start looking into Prism framework.
