### ISSUE TITLE
IPageDialogService should invoke on Main Thread

### ISSUE THREAD

**Issue by raV720** [PrismLibrary/Prism#1185]
- Platform: Android
- Prism version: 6.3

In PageDialogService class Prism invokes Xamarin methods (DisplayActionSheet, DisplayAlert) on calling thread. It causes TargetInvocationException on Android platform. These methods should be called on Main Thread. Perhaps problem is also on different platforms.

**Comment by jbachelor** [comment]
We just ran into the same issue on iOS, actually. We're working around it using the DeviceService to BeginInvokeOnMainThread for the PageDIalogService call causing the problem... But of course, it makes me nervous about all our other calls that are not wrapped like this.

**Comment by brianlagunas** [comment]
Although I would normally argue this is the developer responsibility to know what thread you are calling your code in and to manage it, I don't necessarily see a problem adding this to the dialog service.  I will have to research if there are any performance, or other issues, prior to adding this to the service.

**Comment by raV720** [comment]
In my opinion the service is usually called from viewmodel. In viewmodel I do not want to think if I am on main or different thread when trying to display something

**Comment by brianlagunas** [comment]
> In my opinion the service is usually called from viewmodel. In viewmodel I do not want to think if I am on main or different thread when trying to display something

This is wrong.  As a developer, you should always know on what thread you are calling code in your ViewModel.

**Comment by brianlagunas** [comment]
If you look at the code, we are returning the Task that you invoke in your ViewModel.

https://github.com/PrismLibrary/Prism/blob/master/Source/Xamarin/Prism.Forms/Services/PageDialogService/PageDialogService.cs#L49

Hence, we cannot wrap this in the Device.BeginInvokeOnMainThread.  You must do this in your ViewModel.  I would recommend using the IDeviceService to keep your VM testable.
