### ISSUE TITLE
Possible memory leak with regions and listeners

### ISSUE THREAD

**Issue by dkofoed** [PrismLibrary/Prism#1188]
### Package info

- Platform: WPF
- Prism version: 6.2.0.0
- Xamarin version (if applicable):
- Windows 10 SDK version (if applicable):
- Other version info:

### Repro steps

We have a scenario in which we are using Prism at a feature level. The Prism "shell" is actually a user control that is hosted inside consuming applications. What we noticed is that when the shell control was reloaded, the load times increased gradually due to what appears to be a memory leak with the region listeners. Multiple regions are being populated during load, and each of those regions is holding onto a listener instance and they don't ever appear to be removed.

Attached is a sample app where we tried to replicate our application scenario, and the increasing load delay should hopefully be evident.  Additionally, the same sample app without Prism implementation loaded more quickly overall and didn't incur the increasing load times.  Also included are some ANTS profiler results.  There are really a couple of things we noticed in our analysis:

1) Possible memory leak as already mentioned
2) ANTS pointed to around 40% of time taken in Region.Add. 

As a test, we modified the Prism source code to remove all listeners and the issue #1 was resolved in local testing.

Any feedback welcome!

[SamplePrism6.2.0.zip](https://github.com/PrismLibrary/Prism/files/1354213/SamplePrism6.2.0.zip)

**Comment by brianlagunas** [comment]
Do not open a new duplicate issue.  Continue this discussion in the current issue you have already opened.  It may have been closed, but you can still post to it.
