### ISSUE TITLE
Add a version of IRegionNavigationJournal.GoBack that adds a NavigationResult

### ISSUE THREAD

**Issue by wldevries** [PrismLibrary/Prism#119]
It would be very useful to know what the NavigationResult is of a call to IRegionNavigationJournal.GoBack and GoForward. Unfortunately this cannot be created without listening to navigation events on INavigationService. This is why I implemented an extension method on INavigationService.

An example example can be found in the following gist:

https://gist.github.com/frogger3d/cb60ce0d516502113e45

**Comment by briannoyes** [comment]
Like it! Pull request?

**Comment by dvorn** [comment]
@briannoyes @brianlagunas @wldevries  Implemented this in as part of transition to Task-based Asynchronous Navigation in #646.
