### ISSUE TITLE
Navigation inside tabbedpage

### ISSUE THREAD

**Issue by charlygandia** [PrismLibrary/Prism#1196]
- Platform: Android
- Prism version: 6.3

I have a tabbed page with three tabs. In one of them I have a button to navigate to another page (non-modal). The problem is when I arrive at the new page, there isn't a navigation bar on it.

First, I tried to navigate with `_navigationService.NavigateAsync("DetailPage");` but like I said there is not nav bar.

After, I tried `_navigationService.NavigateAsync("NavigationPage/Detailpage");` With this option the navigation bar is shown but the back button is hide and the only option to go back is with the physical button.

¿Is there any way to navigate within a tab or something like this?

**Comment by brianlagunas** [comment]
Your tab must be a navigation page in order to navigate within a tab.
