### ISSUE TITLE
Rename IApplicationLifecycle to IApplicationLifecycleAware

### ISSUE THREAD

**Issue by mgj** [PrismLibrary/Prism#1198]
I would very much like to rename IApplicationLifecycle to IApplicationLifecycleAware in an attempt to:

1. Make it more discoverable
2. Make it consistent with the naming of INavigationAware

Implementing IApplicationLifecycle does not actually create a lifecycle, as the current name may suggest, it only lets you be aware of the current lifecycle. Please let me know what you think

### Package info

- Platform: All
- Prism version: 6.3.0

**Comment by brianlagunas** [comment]
Well, it doesn't make it more discoverable, but it does align better with our current naming convention.  Since it's not documented and has a very low usage, I think we can make this change.  I am wondering if we should also add OnStartup to it as well?

**Comment by brianlagunas** [comment]
Nah, let's leave OnStartup off.

**Comment by mgj** [comment]
I can definitely see some apps wanting to use OnStartup but honestly, after dealing with the insanity that is android activity and fragment lifecycle callbacks, im leaning towards keeping the lifecycle as simple as possible

**Comment by brianlagunas** [comment]
Done
