### ISSUE TITLE
Add an async version of InteractionRequest<T>.Raise

### ISSUE THREAD

**Issue by frogger3d** [PrismLibrary/Prism#120]
It would be nice te be able to await the result of an interaction request. I created an example implementation on the following gist.

https://gist.github.com/frogger3d/7bbdfebd8fa83cbfaad1

**Comment by briannoyes** [comment]
Good idea. Have thought same thing myself at times and just never got around to pursuing it. Probably won't make it into Prism 6.0 since we are trying to wrap things up for that right now, but I'd vote for this being a candidate for our next release.

**Comment by brianlagunas** [comment]
This has ben implemented.

**Comment by ekalchev** [comment]
@brianlagunas I see you removed RaiseAsync what was the reason for that?

**Comment by brianlagunas** [comment]
@ekalchev see https://github.com/PrismLibrary/Prism/issues/678
