### ISSUE TITLE
Crash at start if deployed over testflight

### ISSUE THREAD

**Issue by ES-2000** [PrismLibrary/Prism#1206]
### Package info

- Platform: iOS
- Prism version: 6.3.0
- Xamarin version (if applicable): 2.3.4.270
- Other version info: Prism.DryIoc.Forms @ 6.3.0.1

### Problem description

We build our app in debug mode and deploy it on a simulator or locally on a device, it works fine.
If we build it in release mode and deploy it over testflight for testing it, the app crashes on startup just after showing the launchscreen. This is a part of the stackstrace of the symbolicated crash file from the device:

Exception Type:  EXC_BAD_ACCESS (SIGABRT)
Exception Subtype: KERN_INVALID_ADDRESS at 0x0000000000000000
VM Region Info: 0 is not in any region.  Bytes before following region: 4373954560
      REGION TYPE                      START - END             [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      __TEXT                 0000000104b54000-0000000104b58000 [   16K] r-x/r-x SM=COW  .../ESMobile.iOS

Triggered by Thread:  0

Application Specific Information:
abort() called

Filtered syslog:
None found

Thread 0 name:  tid_303  Dispatch queue: com.apple.main-thread
Thread 0 Crashed:
0   libsystem_kernel.dylib        	0x0000000187311348 __pthread_kill + 8
1   libsystem_pthread.dylib       	0x0000000187425354 pthread_kill$VARIANT$mp + 396
2   libsystem_c.dylib             	0x0000000187280fd8 abort + 140
3   ESMobile.iOS                  	0x0000000105c49d38 mono_handle_native_crash + 17784120 (mini-exceptions.c:2548)
4   libsystem_platform.dylib      	0x000000018741fb44 _sigtramp + 52
5   libsystem_pthread.dylib       	0x0000000187425354 pthread_kill$VARIANT$mp + 396
6   libsystem_c.dylib             	0x0000000187280fd8 abort + 140
7   ESMobile.iOS                  	0x0000000105d490f0 xamarin_printf + 18829552 (runtime.m:2218)
8   ESMobile.iOS                  	0x0000000105c85e50 mono_invoke_unhandled_exception_hook + 18030160 (exception.c:1084)
9   ESMobile.iOS                  	0x0000000105c49990 mono_handle_exception_internal + 17783184 (mini-exceptions.c:1886)
10  ESMobile.iOS                  	0x0000000105c489c8 mono_handle_exception + 17779144 (mini-exceptions.c:2117)
11  ESMobile.iOS                  	0x0000000105c41350 mono_arm_throw_exception + 17748816 (exceptions-arm64.c:411)
12  ESMobile.iOS                  	0x0000000104e37db8 throw_exception + 168
13  ESMobile.iOS                  	0x0000000105c59140 mono_magic_trampoline + 17846592 (mini-trampolines.c:839)
14  ESMobile.iOS                  	0x0000000104e36e2c generic_trampoline_jit + 252
15  ESMobile.iOS                  	0x0000000105817d28 Prism_DryIoc_PrismApplication_CreateContainer + 13385000 (/<unknown>:1)
16  ESMobile.iOS                  	0x0000000105882578 Prism_PrismApplicationBase_1_T_REF_Initialize + 13821304 (/<unknown>:1)
17  ESMobile.iOS                  	0x0000000105882464 Prism_PrismApplicationBase_1_T_REF_InitializeInternal + 13821028 (/<unknown>:1)
18  ESMobile.iOS                  	0x0000000105882418 Prism_PrismApplicationBase_1_T_REF__ctor_Prism_IPlatformInitializer_1_T_REF + 13820952 (/<unknown>:1)
19  ESMobile.iOS                  	0x0000000105817ccc Prism_DryIoc_PrismApplication__ctor_Prism_DryIoc_IPlatformInitializer + 13384908 (/<unknown>:1)
20  ESMobile.iOS                  	0x0000000104e7550c ESMobile_App__ctor_Prism_DryIoc_IPlatformInitializer + 3282188 (/C:\Users\klaus.bleck\Documents\Sources\esmobile\1130\ESMobile\ESMobile\App.xaml.cs:54)
21  ESMobile.iOS                  	0x0000000104b805c0 ESMobile_iOS_AppDelegate_FinishedLaunching_UIKit_UIApplication_Foundation_NSDictionary + 181696 (/<unknown>:1)
22  ESMobile.iOS                  	0x0000000104e08334 wrapper_runtime_invoke_object_runtime_invoke_dynamic_intptr_intptr_intptr_intptr + 244
23  ESMobile.iOS                  	0x0000000105c57004 mono_jit_runtime_invoke + 17838084 (mini-runtime.c:2526)
24  ESMobile.iOS                  	0x0000000105cbc1bc do_runtime_invoke + 18252220 (object.c:2829)
25  ESMobile.iOS                  	0x0000000105cbc11c mono_runtime_invoke + 18252060 (object.c:2983)
26  ESMobile.iOS                  	0x0000000104b5be08 native_to_managed_trampoline_19(objc_object*, objc_selector*, _MonoMethod**, UIApplication*, NSDictionary*, unsigned int) + 32264 (registrar.m:799)
27  ESMobile.iOS                  	0x0000000104b5c3a4 -[AppDelegate application:didFinishLaunchingWithOptions:] + 33700 (registrar.m:8908)

For me, it seems that an exception is thrown while creating the container. Some other people wrote about problems in release mode related to linking, so i tried to linkskip prism assemblies or, for testing purposes, disable linking in general, but nothing helps. For this reason, i hope someone has an idea to solve this problem, because it is quite critical for us atm.

**Comment by brianlagunas** [comment]
You're going to have to reach out to TestFlight support.  Prism works on emulators, devices, and Xamarin TestCloud with no issues.  If it's problems with the container, then make sure you try link skipping DryIoC as well, and not just Prism.  Good luck and let us know what you find.
