### ISSUE TITLE
Remove stack on top of MasterDetail navigation

### ISSUE THREAD

**Issue by sky018** [PrismLibrary/Prism#1208]
*Use GitHub issues for __bugs in Prism and feature requests only__. If you have a question how to implement something using Prism or a bug in your app that might be related to Prism, please post your question on [StackOverflow](http://stackoverflow.com/tags/prism) (which we monitor as well).*

Please provide as much detail as possible (and feel free to remove unused properties):

### Package info

- Platform: Android
- Prism version: 6.3.0
- Xamarin version (if applicable): 2.4.0.282
- Windows 10 SDK version (if applicable):
- Other version info:

### Repro steps

Navigating from one content page to master detail page and pop the master detail page (remove the master detail page) to another content page.

So basically here's the scenario.

Page 1 -> Page 2 -> Page 3 -> MasterDetailPage -> Page 4 

So what I've tried was doing this.

Navigation to page 1 to 3 would be:
`_navigationService.NavigateAsync("PageX");`

Then navigating to MasterDetailPage would be:
`await _navigationService.NavigateAsync("MasterDetail/NavigationPage/MainPage");`

Then let's say I have a log out button navigating to a certain page by using absolute navigation:
`_navigationService.NavigateAsync("/Page4");`

I am getting unhandled exception when navigating to page 4

However, when I do this to App.xaml.cs:
`NavigationService.NavigateAsync("MasterDetail/NavigationPage/MainPage");
`
And navigate back to Page 4, I do not encounter the exception. Can anyone enlighten me how do I navigate using a master detail that has a stack on top of it?

**Comment by brianlagunas** [comment]
I am unable to duplicate this issue.  Chances are you have an issue in your code somewhere.  Try adding some error handling to your code to capture the exception's message. Make sure you are checking for nulls in any IDestructible method, or INavAware method.  Can you replicate this issue in a blank app? Also, please do not double post to SO.

**Comment by sky018** [comment]
@brianlagunas  Sorry about double posting. I have fixed the issue - if you may, you can close this, it seems like the code for a certain page still checks the value before destroying it.

So if I have page 1 and I have a behavior<entry> implemented on it (since I didn't have a null checking) implementing an absolute navigation before destroying the page, the method will still check the entry who implemented the behavior<entry> and gives a null ref value (which doesn't make sense) cause I didn't go back to page 1 who has it, but rather than page 4. Well, anyways, thanks!

**Comment by brianlagunas** [comment]
Great! I'm glad you got it figured out.
