### ISSUE TITLE
Setting binding properties in onNavigatedTo with Forms 2.4

### ISSUE THREAD

**Issue by zeljkoa** [PrismLibrary/Prism#1209]
There seems to be an issue with the OnNavigatedTo method after upgrading to Forms 2.4. 
For example, if you set a visibility property of a control in the onNavigatedTo method, it won't have any effect on android API levels 17 and below and the control will stay invisible. 

I attached a sample project.
[App1.zip](https://github.com/PrismLibrary/Prism/files/1382456/App1.zip)

**Comment by brianlagunas** [comment]
This has nothing to do with Prism.  The OnNavigatedTo method gets fired as expected.  The functionality of hiding/unhiding controls is not something Prism is responsible for.  You can try using OnNavigatingTo as maybe API 17 requires it to be set prior to the page being visible.  You should open a bug with Xamarin if you are still having issues..
