### ISSUE TITLE
Binding to DelegateCommand Doesn't navigate

### ISSUE THREAD

**Issue by joeizang** [PrismLibrary/Prism#1212]
Hello everyone,
 
I hope I am wrong but I think what is happening in my code is a bug in Prism's DelegateCommand or the NavigationService.
I have a Button and I do a binding in its Command Property that is supposed to call an action in my Viewmodel which will navigate to another page, but that doesn't happen. But if I use the dialogService and attempt to display dialog using the same command it works. Here are the details of my setup:

### Package info
Windows 10 Pro Creators Update (Platform)
Prism 6.3 (Prism version)
Xamarin 4.6 (Xamarin Version)(Xamarin Forms 2.4.0.280 or 2.3.4.270)
using Android API 23 and deploying to a physical phone.
using latest prism template pack

### Repro steps
To Reproduce, create a xamarin forms project with unity and prism add a button and wire up delegate command to respond to command of button and let the action that is called by the delegate command navigate to another page. You will notice that nothing happens.

**Comment by brianlagunas** [comment]
I am unable to duplicate this.  It is probably something in your code.  If you haven't figured it out yet, just provide a sample that reproduces the issue.

**Comment by joeizang** [comment]
Hi Brian,
I dunno what to say but I still have this issue and I made sure I created a new project and tried this and nothing happens. I will give my code a look over again and see but I am still having this issue. I even tried to deploy to api 22 but still the same. Thank you for taking the time to help out. And God bless you for all your work on prism.

**Comment by bartlannoeye** [comment]
If you have the issue in a new project, please push it to github so we can investigate.

**Comment by joeizang** [comment]
ok sir I will do that now. I will let you know what the repo is called.
