### ISSUE TITLE
MasterDetailPage control Visual Studio Template default code issue.

### ISSUE THREAD

**Issue by RikardoPons** [PrismLibrary/Prism#1222]
Hello. I'm using Xamarin Forms and I added the control MasterDetailPage I can find this control in Xamarin Forms section in VS.

This control add code and views automatically. 
I would like to know where is the template about this control.
Because I want to do a pull request about some improvements.

For example:
When the user selects a page if the page is already loaded in the detail page section the default code creates always a new instance of the same page. 
I think this behavior must be fixed 

The default code looks like this:

` var item = e.SelectedItem as RootPageMenuItem;
            if (item == null)
                return;

            var page = (Page)Activator.CreateInstance(item.TargetType);
            page.Title = item.Title;
            Detail = new NavigationPage(page);
            IsPresented = false;

            MasterPage.ListView.SelectedItem = null;`

My small improvement is like this:

` var item = e.SelectedItem as RootPageMenuItem;
            if (item == null)
                return;

          
         
            var navigationPage = Detail as NavigationPage;
            if (navigationPage != null)
            {
                
                if (navigationPage.CurrentPage != null)
                {
                    if(navigationPage.CurrentPage.GetType()== item.TargetType)
                    {
                        IsPresented = false;
                        MasterPage.ListView.SelectedItem = null;
                        return;
                    }
                }
            }

            var page = (Page)Activator.CreateInstance(item.TargetType);
            page.Title = item.Title;
            Detail = new NavigationPage(page);
            IsPresented = false;

            MasterPage.ListView.SelectedItem = null;`

I know is small but I had problems with my app the memory was increasing always when I opened a new view  and I found this issue.

**Comment by brianlagunas** [comment]
I'm sorry, but this is the issues page for the Prism project, not Xamarin.Forms.  You should submit this directly to Xamarin, because we do not ship that product.

**Comment by RikardoPons** [comment]
@brianlagunas  Ok Thanks!
