### ISSUE TITLE
Save and restore the user interface state.

### ISSUE THREAD

**Issue by FSharpCSharp** [PrismLibrary/Prism#1224]
I'm writing about this because I see some problems here. When I set up an application with Prism modularly, it must be possible to store the state of the user interface in the same way. If possible, the user's customizations should also be saved. Is there any approach in the Prism module that can be used? Or does someone have best practices to follow that could be followed? When saving the application state, it is mainly a question of positions within the modules, for example, user interface properties, such as sizes of certain controls or their positions. I would be very grateful for an answer here, because the subject is well known, and it would make sense to provide for an approach here, especially in the case of such applications, which consist of many modules.

**Comment by brianlagunas** [comment]
Please post these types of questions to StackOverlfow.  Saving application state is not specific to a Prism app.  As you said, the subject is well known.  If you know how to save app state in a non-prism app, you can save state in a Prism app. The only difference is you need to send a message to all modules that need to save state.
