### ISSUE TITLE
OnNavigatedTo Contains Extra Parameter

### ISSUE THREAD

**Issue by mrbiggred** [PrismLibrary/Prism#1225]
### Package info

- Platform: Windows, Visual Studio 2017
- Prism version: Dryloc Forms 7.0.0.168-pre
- Xamarin version (if applicable): Xamarin Forms 2.4.0.282
- Other version info:

### Repro steps

When OnNaviagedTo is called there is an extra parameter with a key of __NavigationMode.  The problem is the extra parameter is messing up my parameter checking.  For example, I have logic in the OnNavigatedTo that checks if a certain number of parameters are provided.

```C#
public void OnNavigatedTo(NavigationParameters parameters)
{
    // Should only be one parameter.
    if (parameters.Count != 1)
        throw new ArgumentException("Should only be one parameter", nameof(parameters));

    // Rest of method....
}
```

I propose that instead of having the __NavigationMode added to the parameters collection it is a separate property.  That way it is still available but won't mess up my parameter checking logic.  It would be nice to assume all the parameters in the collection are ones I put there and not ones that magically show up.

If you like the above idea I can try implement it and do a pull request.  If you anyone has any better idea please let me know.

Thank you.

**Comment by brianlagunas** [comment]
I think you have a valid point.  The issue is that we need a way to pass information about what is going on within the navigation service.  These should not be used directly which is why they start with "__".

Maybe we can create an internal "property bag" that we can then use extension methods to expose instead of properties.  We can't add properties to the NavigationParameters class as the long term vision is to add that class to the Prism.Core which will be shared across all platforms.

**Comment by brianlagunas** [comment]
I'd be interested in seeing your idea to implement this while keeping our long term goal in mind.

**Comment by mrbiggred** [comment]
@brianlagunas thanks for explaining the reason you can't just add a property.  I'll post any solutions I come up with in the next couple of days.

**Comment by mrbiggred** [comment]
@brianlagunas any reason we couldn't use inheritance?  For example, the long term solution might look like:

```c#
namespace Prism.Core
{
  public class NavigationParametersBase : IEnumerable<KeyValuePair<string, object>>
  {
    // Existing Prism.Forms.Navigation.NavigationParameters class
  }
}

namespace Prism.Forms
{
  public class NavigationParameters : NavigationParametersBase
  {
    NavigationMode PageNavigationMode { get; set; }
  }
}
```
Now each platform can extend the navigation parameters as needed.  Until the NavigationParameters is moved to Prism.Core we could leave everything in the Prism.Forms project and, hopefully, not break anything:

```c#
namespace Prism.Forms
{
  internal class NavigationParametersBase : IEnumerable<KeyValuePair<string, object>>
  {
    // Existing Prism.Forms.Navigation.NavigationParameters class.  Will eventually be moved
    // to Prism.Core.
  } 

  public class NavigationParameters : NavigationParametersBase
  {
    NavigationMode PageNavigationMode { get; set; }
  }
}
```

**Comment by brianlagunas** [comment]
That would break the sharing of the NavigationParameters class in the interfaces.

**Comment by mrbiggred** [comment]
Is the plan to move all or most of the navigation classes from Prism.Forms project to the Prism core?  If so is the goal to have a common navigation interfaces for each platform?  Would there be any platform specific navigation settings that need to be exposed just to that one platform?

Is there a road map or design document for the future of Prism?

Thanks.

**Comment by brianlagunas** [comment]
Yes, the long term plan is to move as many of the navigation interfaces into a shared assembly for all platforms.  This will make code sharing across various platforms with Prism much easier.

**Comment by mrbiggred** [comment]
Thank you for the information and your patience with my questions.  I'll be on vacation for the next two weeks so feel free to assign this issue to someone else.  On the plus side I have a 10+ hour flight to think about this problem.

**Comment by brianlagunas** [comment]
Vacations are the best time to work on OSS. Especially on features you want :)

**Comment by mrbiggred** [comment]
@brianlagunas I'm glad you found a solution to the issue.  I look forward to trying it out the fix later this week.  Sorry I couldn't be more help.
