### ISSUE TITLE
Unity namespace changed in version 5

### ISSUE THREAD

**Issue by khoavn** [PrismLibrary/Prism#1226]
### Package info

- Platform: Windows, VS 2017
- Prism version: 6.3
- Xamarin version (if applicable):
- Windows 10 SDK version (if applicable):
- Other version info:

### Repro steps

After upgrading to Unity 5, it doesn't understand `RegisterTypeForNavigation` in `UnityExtensions` because the namespace changed from `Microsoft.Practices.Unity` to `Unity`

**Comment by brianlagunas** [comment]
Don't upgrade. Prism isn't compiled against Unity 5.
