### ISSUE TITLE
PageNavigationService should check for MultiPage Parent

### ISSUE THREAD

**Issue by dansiegel** [PrismLibrary/Prism#1232]
## Problem

In the event that your navigation stack looks like: 
`NavigationPage/TabbedPage?createTab=ViewA&createTab=ViewB` and you navigate from either `ViewA` or `ViewB` like: `_navigationService.NavigateAsync("ViewC")`, the Navigation Service will navigate modally. It is far more likely that your intent is to navigate non-modally.

## Proposal

If `useModalNavigation` is null, the PageNavigationService will attempt to determine the correct way to navigate by determining if the parent of the Current Page is a NavigationPage. This should be updated to accommodate when the Page's parent is a `MultiPage<>` with a NavigationPage parent.

**Comment by brianlagunas** [comment]
Do you think this would work?
```
        internal static bool HasNavigationPageParent(Page page)
        {
            if (page?.Parent != null)
            {
                if (page.Parent is NavigationPage)
                {
                    return true;
                }
                else if (page.Parent is TabbedPage || page.Parent is CarouselPage)
                {
                    return page.Parent.Parent != null && page.Parent.Parent is NavigationPage;
                }
            }

            return false;
        }
```
