### ISSUE TITLE
Deep linking doesn't show correct toolbar items

### ISSUE THREAD

**Issue by mrbelk** [PrismLibrary/Prism#1234]
*Use GitHub issues for __bugs in Prism and feature requests only__. If you have a question how to implement something using Prism or a bug in your app that might be related to Prism, please post your question on [StackOverflow](http://stackoverflow.com/tags/prism) (which we monitor as well).*

Please provide as much detail as possible (and feel free to remove unused properties):

### Package info

- Platform: Xamarin.Android/Xamarin.Forms
- Prism version: 6.3 (Unity)
- Xamarin version (if applicable): VS for Mac v7.2.2, Xamarin.Android 8
- Other version info: Xamarin.Forms 2.4

### Repro steps

If I "deep link" a couple pages encapsulated within a navigation page like this:

```c#
navigationService.NavigateAsync("/NavigationPage/pageA/pageB/pageC");
```
and if pageA, pageB, and pageC each have their own set of different toolbar items; pageC still shows the toolbar items from pageA.

If I don't deep link, and go from page to page to page one at a time, as though the user were getting the app ready for his daily use (like maybe picking a truck, picking a route, etc.), the individual toolbars for each different page seem to render correctly.

**Comment by mrbelk** [comment]
it would appear the upgrading to Prism 7 pre-release might have solved this issue.

**Comment by brianlagunas** [comment]
Prism 7 introduced a workaround to a Xamarin.Forms bug when pushing multiple pages onto a navigationPage.  That is what is sounds like you are experiencing, and Prism 7 should fix it.
