### ISSUE TITLE
Programmatically switch between Tabs in a TabbedPage

### ISSUE THREAD

**Issue by mmoscati** [PrismLibrary/Prism#1235]
I'm using Prism v6.3 and XF as v2.3.3.193
After the TabbedPage is loaded (Constructor and OnNavigatingTo have been called) is it possible programmatically switch between tabs like a Tap on the tab?
Behaviour expected: only the IsActive methods must be invoked without Constructor/OnNavigatingTo.
Using  NavigateAsync("MyTabbedPage/Tab1Page") the Constructor and OnNavigatingTo will be called again.

**Comment by brianlagunas** [comment]
No, Prism does not support the selecting of tabs from within a ViewModel.  This must be done with custom code.  Also, you should upgrade to the latest Prism7 preview as we have made breaking behvairo changes to how TabbedPages work: https://github.com/PrismLibrary/Prism/releases/tag/7.0.0-pre3
