### ISSUE TITLE
Handling Prism Exceptions

### ISSUE THREAD

**Issue by leroygumede** [PrismLibrary/Prism#1241]
*Use GitHub issues for __bugs in Prism and feature requests only__. If you have a question how to implement something using Prism or a bug in your app that might be related to Prism, please post your question on [StackOverflow](http://stackoverflow.com/tags/prism) (which we monitor as well).*

Please provide as much detail as possible (and feel free to remove unused properties):

### Package info

- Platform: Android , ios
- Prism version: 6.3.0
- Xamarin version : 2.3.4 using Xamarin Forms
- Other version info:

### Repro steps

Please describe the issue/request in detail. 👍 

Handling Prism Errors Are getting hard to read which for some reason Gives me the same error every time

In this case, I had resolved a container incorrectly in app.cs but the error prism gave was too vague

<img width="965" alt="screen shot 2017-11-08 at 9 22 50 am" src="https://user-images.githubusercontent.com/20415678/32536277-7577a8d8-c466-11e7-8289-6831a7525f9e.png">

Console Log : 
```
2017-11-08 09:18:15.804 TheApp.iOS[8651:374369] *** Assertion failure in -[UIApplication _runWithMainScene:transitionContext:completion:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit_Sim/UIKit-3600.6.21/UIApplication.m:3680
2017-11-08 09:18:15.807 BrandWorx.iOS[8651:374369] Xamarin.iOS: Received unhandled ObjectiveC exception: NSInternalInconsistencyException Application windows are expected to have a root view controller at the end of application launch
```

I was forced to debug by commenting out line by line to see what was breaking prism

**Comment by dansiegel** [comment]
What you’re describing is vague, however I believe your issue has already been resolved in Prism 7. Please update to the latest preview.

**Comment by leroygumede** [comment]
My point is It always throws a `Foundation.MonoTouchException` when there is a prism error

**Comment by brianlagunas** [comment]
>  I had resolved a container incorrectly in app.cs 

Sounds like this was a container exception, not a Prism exception.  Anytime an exception occurs before the MainPage is set, this is the error that is thrown.  Prism does not control this.  You need to make sure you have proper error handling in the OnInitialized for your App.cs to catch these exceptions and get more information about them.

**Comment by devperson** [comment]
I'm too having same issue

**Comment by lhughey** [comment]
As @brianlagunas referenced, this issue is triggered when you have an error before the MainPage is set. You can get around this when debugging a hard to figure out issue by simply putting 
`MainPage = new Page();`
directly after the InitializeComponent method.  This will cause the error to be unhidden.
