### ISSUE TITLE
Xamarin forms prism OnNavigatedFrom method not fired when pressing back button in nav bar

### ISSUE THREAD

**Issue by vladimir-shirmanov** [PrismLibrary/Prism#1243]
### Package info

- Platform: XF iOS
- Prism version: 6.0.3
- Xamarin version (if applicable): 2.4.0.38779

### Repro steps

Tab page screen with this structure

```
<tabbedpage>
   <navigationpage>
      <contentpage1 />
   </navigationpage>
</tabbedpage>
```

when you navigate from content page 1 to new content page like this navigationService.NavigateAsync("ContentPage2") and then press back button in navbar, method OnNavigatedFrom of ContentPage2 is not called.
ContentPage2 is implementing INavigationAware

**Comment by brianlagunas** [comment]
I do not understand your scenario.  Can you provide a sample that demonstrates your issue?

**Comment by brianlagunas** [comment]
You should also try updating to the latest 7.0 preview.  It has a lot of improvements around TabbedPages.  

I am closing this as I was unable to duplicate this issue.  If you would like to submit a sample that can reproduce it, please do.

**Comment by brianlagunas** [comment]
Actually, I know what it didn't work for you.  You are manually defining the NavigationPage in XAML.  Prism isn't creating it for you.

Either upgrade to the latest 7.0 preview, or you have to manually add the NavigationPageSystemGoBackBehavior to the NavigationPage in XAML.

**Comment by vladimir-shirmanov** [comment]
Thanks for quick reply. In the latest 7.0 preview version all works as expected.
