### ISSUE TITLE
App created by template pack doesn't compile

### ISSUE THREAD

**Issue by opcodewriter** [PrismLibrary/Prism#1251]
Creating an app using latest template pack in VS2017 fails to compile.

```
2>Project "BlankApp3.Android.csproj" (Install target(s)):
2>Project "BlankApp3.csproj" (GetTargetFrameworkProperties target(s)):
2>Project 'D:\Projects\BlankApp3\BlankApp3\BlankApp3\BlankApp3.csproj' targets '.NETStandard,Version=v2.0'. It cannot be referenced by a project that targets 'MonoAndroid,Version=v8.0'.
```

### Package info

- Platform: Windows 10 ( I DO NOT have Creators Fall Update)
- Prism version: whatever version is used by the app created by the Prism template pack (in my case I see it's v7.0.0.168-pre)
- Prism Template Pack: 2.0.5
- Xamarin version: 4.7.10.38
- Xamarin Android version: 8.0.2.1
- Windows 10 SDK version (if applicable):
- Visual Studio:  VS2017 Enterprise, v15.4.3

### Repro steps
1. Open VS2017, go to New\Project\Prism\Xamarin.Forms and select 'Prism Blank App'
2. Select just Android as target platform and DryIoc.
3. Compile App

I tried to rebuild, clean obj bin directories, didn't work
Creating a Xamarin Forms app, without Prism, works.

I don't understand why the template is creating an application which is using the pre-release version of Prism

**Comment by brianlagunas** [comment]
Have you tried changing the version of android that your project is using to compile?  I am unable to reproduce the issue.

It is using a pre-release version because that is the version that is .NET Standard compatible.

**Comment by brianlagunas** [comment]
Also, this belongs in the extensibility repo:

https://github.com/PrismLibrary/Prism-Extensibility/issues

Please repost there.

**Comment by opcodewriter** [comment]
To answer your questions:

1. No, I haven't tried changing the Android version. Why should it make any difference? The error refers to the Xamarin Android version, not the Android SDK version.
   I still don't understand why is using the pre-release version. Only the pre-release version of template packs should use pre-release versions of Prism. The template pack is released version, so it should use only the latest release Prism version.

2. Sure, I can repost it there, but I doubt it has to do with the template pack. Are you sure this is really needed? I am sure the issue is in the pre-release version of Prism.

**Comment by brianlagunas** [comment]
The issue is not the pre-release version of Prism.  You can easily test this by creating a project using the VS cross platform templates, and adding the pre-release version of Prism to it and trying to compile.  This works as there are over a 1,000 downloads of the pre-release with no reported issues.

The templates must use the pre-release as that is the only version that supports .NET Standard and the new dotnet templating system.  The marketplace has no concept of a "pre-release" VSIX, so it must be a release version.

Do you have the DotNet Core package installed with VS?

**Comment by opcodewriter** [comment]
I didn't realize until now I need .NET Core SDK 2 installed, I thought Visual Studio updated did that!

**Comment by brianlagunas** [comment]
Yeah... the entire .NET Standard thing is going to be very confusing for the next couple of years as people adjust.  I am hoping they fix VS to automatically install that when Xamarin is installed in their upcoming 15.5 release.

Let me know if you are still having problems.

**Comment by opcodewriter** [comment]
Funny, now I am confused why did compilation of my solution worked before installing .NET Core SDK. 
Few months ago I converted my PCLs to  .NET Core library and it was compiling fine.
Maybe because I'm using `<TargetFramework>netstandard1.6</TargetFramework>`  in my .NET Core library, and not 'netstandard2.0' ? I don't remember having to installing any SDK for 'netstandard1.6'...

**Comment by brianlagunas** [comment]
Just for fun, can you remove these lines from the Android csproj file

```
    <ProductVersion>8.0.30703</ProductVersion>
    <SchemaVersion>2.0</SchemaVersion>
```

And let me know what happens

**Comment by opcodewriter** [comment]
I already installed .NET Core SDK. Now everything compiles fine. Does it still make sense to change the .csproj with those changes?

**Comment by brianlagunas** [comment]
Nah.. I was just curious.  I'm glad you're up and running.

**Comment by opcodewriter** [comment]
Hi Brian, are you getting these warnings too?

```
>D:\Projects\BlankApp7\BlankApp7\BlankApp7\BlankApp7.csproj : warning NU1701: Package 'CommonServiceLocator 1.3.0' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.
>D:\Projects\BlankApp7\BlankApp7\BlankApp7\BlankApp7.csproj : warning NU1701: Package 'Unity 4.0.1' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.
```

**Comment by brianlagunas** [comment]
If you aren't using the preview of Prism, then yes

**Comment by brianlagunas** [comment]
Correct, because Prism for WPF 6.3.0 is being referenced (which is not .NET STandard).  When we release 7.0, then you won't get the warning.  It's not a big deal.  It will work just fine.

**Comment by opcodewriter** [comment]
OK, thanks a lot.

**Comment by opcodewriter** [comment]
More issues ... 
Here are the steps:

1. Using the Prism template, I create an app. It compiles and runs fine.
2. I saw there's an update for Prism, so I updated it but it gave this error
![snip_20171116191138](https://user-images.githubusercontent.com/15019084/32905238-089d691c-cb02-11e7-9358-d32d8b23ed90.png)

3. I saw there's an update for Xamarin, so I updated it too, but now I've got this error:
![snip_20171116191336](https://user-images.githubusercontent.com/15019084/32905327-4cae44f0-cb02-11e7-9af3-a670dcf38bb3.png)

I can't get rid of it. I tried to delete all bin\obj dirs., restarted VS, recompiled, ... nothing

**Comment by brianlagunas** [comment]
This is a known issue with the latest Xamairn.Forms version.I had this happen to me when I updated Prism to use the new version of XF. I did the same things you did.  Finally after restarting VS a number of times it finally worked for me.

I have reported this to Microsoft.

**Comment by opcodewriter** [comment]
OK.
Is it normal that the only references are Xamarin.Forms and Prism.Unity.Forms and not also Unity or CommonServiceLocator packages?

Also, there's no `packages` folder in the solution folder.

![snip_20171116194236](https://user-images.githubusercontent.com/15019084/32906672-4e33553c-cb06-11e7-90a3-c3bd5649f972.png)

**Comment by opcodewriter** [comment]
After deleting bin and obj folders and restarting VS, this is what I have not:

![snip_20171116194402](https://user-images.githubusercontent.com/15019084/32906761-982ee480-cb06-11e7-89f6-0b3c8ce8c76e.png)

**Comment by brianlagunas** [comment]
This usually indicates your file path is too long. Move it to a short path like C:\Projects and see if it works then

**Comment by opcodewriter** [comment]
The path is quite small 
![snip_20171116195055](https://user-images.githubusercontent.com/15019084/32907052-7c0333fa-cb07-11e7-80fb-d35d88adeffb.png)

**Comment by brianlagunas** [comment]
Well, you also have a bad namespace you need to remove.

**Comment by dansiegel** [comment]
@opcodewriter the new SDK Style project structure that was introduced with VS 2017 / .NET Standard eliminates the packages folder in your solution directory. There's actually a number of advantages to this. 

1. It uses the NuGet cache so you don't have 100 copies of the same NuGet floating around
1. It allows non-traditional references. For example say you have `C:Repos` with `ProjectA` and `ProjectB` cloned in your Repos directory. You can then reference projects in ProjectA from ProjectB without having to first open ProjectA and restore the NuGet's
1. The new style allows you to reference a top level package and it will automatically bring in all of the dependencies. This eliminates having to manage 10000 packages (particularly with all of the System.Foo references in .NET Standard. Xamarin Forms is there as well so that you can manage that in addition to Prism.Unity.Forms... that said it's not actually needed. And CommonServiceLocator is no longer used by Unity...

**Comment by opcodewriter** [comment]
@brianlagunas  What bad namespace? This is a dummy app created by the template. I didn't add or modified any code.

@dansiegel Thanks for explanation regarding NuGet references. Very happy local packages in the solution folder is gone. But do you have any thoughts of how to solve the compilation issues?

**Comment by brianlagunas** [comment]
Your error output tells you.  It says "Practices". Unity has made breaking changes and so has common service locator. You upgraded those packages. Which means you need to fix the namespaces now.

**Comment by opcodewriter** [comment]
Thanks, I finally managed to make it work. I wasn't aware of all these changes, I got used with the app created by the template to just work, my brain was in monkey mode.

What's weird is that VS doesn't display the reference tree for the Android project like the one for the .NET Standard project:

![snip_20171116202415](https://user-images.githubusercontent.com/15019084/32908405-244e6418-cb0c-11e7-87b9-6411237fd0c5.png)

Which is extremely confusing. You basically don't see that the Android project is referencing Unity.dll.
I had to manually add `using Unity;` in the MaiNActivity.cs. It couldn't compile and hovering over the `IUnityContainer` didn't suggested adding the `using` statement.

**Comment by brianlagunas** [comment]
Because only the .Net Standard projects provide the new reference experience. The Android project is not .Net Standard.

Glad you got it figured out.  As soon as we RTM v7.0.  I will update the templates so this won't be an issue going forward.

**Comment by opcodewriter** [comment]
> Because only the .Net Standard projects provide the new reference experience. The Android project is not .Net Standard.
I see what you mean, but it's funny that the new  `<PackageReference>` exists and works for both .csproj, but the tree display in VS only works for the .NET Standard one.

Not sure what the "new reference" experience i
Both projects have `<PackageReference>` inside their .csproj. I don't understand why only for one of them VS displays the reference tree (I do understand that this is because only .NET Standard one . I hope this is just a temporary issue.
