### ISSUE TITLE
App created by template pack doesn't compile OutputPath error

### ISSUE THREAD

**Issue by lubritto** [PrismLibrary/Prism#1252]
Starting a new project on the new template's version, an error is occurring with outpath when compile the project on visual studio 15.3.3. To solve this, i puted these lines manually on the csproject

  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>bin\Debug\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <AndroidUseSharedRuntime>True</AndroidUseSharedRuntime>
    <AndroidLinkMode>None</AndroidLinkMode>
    <AotAssemblies>false</AotAssemblies>
    <EnableLLVM>false</EnableLLVM>
  </PropertyGroup>

### Package info

- Platform: Android
- Prism version: 7.0.0.168-pre
- Xamarin version (if applicable): 2.4.0.282
- Windows 10 SDK version (if applicable):
- Other version info: Visual studio version 15.3.3

### Repro steps

Severity Code Description Project File Line Suppression State Error The OutputPath property is not set for project 'DryIocAPp.Android.csproj'. Please check to make sure that you have specified a valid combination of Configuration and Platform for this project. Configuration='Debug' Platform='AnyCPU'. This error may also appear if some other project is trying to follow a project-to-project reference to this project, this project has been unloaded or is not included in the solution, and the referencing project does not build using the same or an equivalent Configuration or Platform. DryIocAPp.Android

**Comment by brianlagunas** [comment]
Can you please submit this to the correct repro?

https://github.com/PrismLibrary/Prism-Extensibility/issues

**Comment by brianlagunas** [comment]
Also, the recommended version of VS is 15.4.2.

**Comment by lubritto** [comment]
Sorry, i will put on the right place
