### ISSUE TITLE
Documentation: Namespacing/Using statements in examples?

### ISSUE THREAD

**Issue by p0lar-bear** [PrismLibrary/Prism#1256]
(I accidentally [submitted an issue](https://github.com/PrismLibrary/Prism-Documentation/issues/2) to PrismLibrary/Prism-Documentation before learning that the docs were maintained over here. Copying my issue over to here.)

I'm brand new to Prism and coming in with just enough hands-on experience with WPF to be dangerous, so that may be the root of the issue. But, the docs are confusing for me to follow on their own - in the WPF Initializing chapter alone it's entirely ambiguous to me which classes are being used in examples for return types and the like. I think that it should be clarified via namespacing, or the inclusion of `using` statements, exactly which classes are being used.

i.e. instead of this example on the WPF Initializing chapter:

    protected override DependencyObject CreateShell()
    {
        return ServiceLocator.Current.GetInstance<Shell>();
    }

I think it should read either:

    using System.Windows;
    using CommonServiceLocator;
    using YourApp.Views;

    protected override DependencyObject CreateShell()
    {
        return ServiceLocator.Current.GetInstance<Shell>();
    }

or:

    protected override System.Windows.DependencyObject CreateShell()
    {
        return CommonServiceLocator.ServiceLocator.Current.GetInstance<YourApp.Views.Shell>();
    }

**Comment by brianlagunas** [comment]
You had it right the first time.  We are migrating docs over to their own repo.
