### ISSUE TITLE
Can't override Prism.Mvvm.BindableBase.RaisePropertyChanged()

### ISSUE THREAD

**Issue by istagir** [PrismLibrary/Prism#1259]
Can't override Prism.Mvvm.BindableBase.RaisePropertyChanged(), because it is not marked virtual such as obsolete method Prism.Mvvm.BindableBase.OnPropertyChanged()

https://github.com/PrismLibrary/Prism/blob/e70cfa3df6943be8314e9ae37dcdf40484ffbba6/Source/Prism/Mvvm/BindableBase.cs#L70

Is it bug or by design?

**Comment by brianlagunas** [comment]
You need to override the method with the following signature
```
protected virtual void OnPropertyChanged(PropertyChangedEventArgs args)
```
