### ISSUE TITLE
Show extended splash screen right away

### ISSUE THREAD

**Issue by xperiandri** [PrismLibrary/Prism#126]
If ExtendedSplashScreenFactory is set we need to put extended splash screen page right away to the frame and activate window.
Only then restoring state and doing everything else.
Isn't it?

**Comment by briannoyes** [comment]
Not sure what you are saying the problem is. ExtendedSplashScreen works as designed for Prism for Windows Runtime under UWP as well. I've added a sample here that shows it in use:
https://github.com/PrismLibrary/Prism-Samples-Windows
