### ISSUE TITLE
Custom navigation bar using Xamarin forms with prism broken

### ISSUE THREAD

**Issue by dimonkomaron** [PrismLibrary/Prism#1262]
I'm using Prism Library for Xamarin.Forms.

And I'm going to create custom navigation bar via Control template. (Reason of creating custom navigation bar - I didn't find solution to make navigation bar transparent for display background image, also I will probably customize my navigation bar and add some controls on it).

      
      <ControlTemplate x:Key="NavigationPageTemplate">
                <AbsoluteLayout BackgroundColor="Transparent">

                    <Image AbsoluteLayout.LayoutBounds="0,0,1,1"
                           AbsoluteLayout.LayoutFlags="All"
                           Aspect="AspectFill"
                           Source="{TemplateBinding BackgroundImageEx}" />

                    <ContentView Padding="0,50,0,0"
                                 AbsoluteLayout.LayoutBounds="0,0,1,1"
                                 AbsoluteLayout.LayoutFlags="All">
                        <ContentPresenter />
                    </ContentView>
                    

                    <ContentView AbsoluteLayout.LayoutBounds="0,0,1,AutoSize"
                                 AbsoluteLayout.LayoutFlags="PositionProportional, WidthProportional"
                                 BackgroundColor="Transparent">
                        <ContentView.Padding>
                            <OnPlatform x:TypeArguments="Thickness"
                                        Android="10"
                                        iOS="10, 20, 10, 0" />
                        </ContentView.Padding>

                        <controls:ImageButton Command="{TemplateBinding GoBackCommand}"
                                              HeightRequest="30"
                                              HorizontalOptions="StartAndExpand"
                                              Source="ic_back.png"
                                              WidthRequest="30">
                        </controls:ImageButton>

                    </ContentView>
                </AbsoluteLayout>
            </ControlTemplate>

And my problem is to process back button press with Prism Navigation. I've tried to process click on MyApp.xaml.cs file.

       private void Button_OnClicked(object sender, EventArgs e)
        {
            NavigationService.GoBackAsync();
        }

And it seems to have different navigation stack because it shows after press my first page.

I have Navigation this way:

Navigate("FirstPage"); -> Navigate(MasterDetail/NavigationPage/ViewA) -> Navigate("ViewB") ViewB - uses Control template.

When I click custom back button on ViewB NavigationService back me to FirstPage.

Another question Should first page be saved when we change App.MainPage?

**Comment by brianlagunas** [comment]
You can't use the INavigationService in a code-behind file.  You must use the native XF APIs for navigation.  Creating custom navigation bars is outside the scope of our support.

**Comment by dimonkomaron** [comment]
Ok, And how can I use INavigationAware interface if I will use on my Base Page, for example, code like Navigation.PopAsync()?

**Comment by brianlagunas** [comment]
INavAware methods work with the built-in PopAsync methods.

**Comment by brianlagunas** [comment]
Also, please do not double post

https://stackoverflow.com/questions/47309062/custom-navigation-bar-using-xamarin-forms-with-prism-broken

**Comment by dimonkomaron** [comment]
Please correct me if I wrong, Your answer means that I can't create custom navigation bar using Prism built-in navigation?

Sorry for double post. I will remove my question on stackoverflow!

**Comment by brianlagunas** [comment]
You can create a custom navigation bar, but you can't use the Prism INavigationService in the code-behind.  You will use the built-in Xamarin.Forms navigation API.  Just like the sample in the SO post.

**Comment by dimonkomaron** [comment]
Ok, thank you for your answer. Now I have created BasePage where I realize simple pop:
`  if (Navigation != null)
            {
                await Navigation.PopAsync();
            }`

And it works fine for me!

Maybe it simple question. But if use Xamarin forms back button on navigation page - I can't set parameters for previous page. I mean NavigatedFrom is empty always when I click back button?

**Comment by brianlagunas** [comment]
Correct. Well, you can but it's more of a trick.  You will need to add the parameters in the OnNavigatedFrom and they will be available in the OnNavigatedTo of the back you are going back to.

**Comment by dimonkomaron** [comment]
Great thanks for your help and feedback!!!
