### ISSUE TITLE
Is it possible to provide a new json based module catalog?

### ISSUE THREAD

**Issue by noufionline** [PrismLibrary/Prism#1268]
It would be very convenient to register the modules using a json config file.

**Comment by brianlagunas** [comment]
I'm not sure this is something that will be included in Prism as this would require an additional dependency on Json.NET to read and parse the file.  Plus, might as well be a simple text file as I'm not sure adding modules via Json will be desirable.

**Comment by noufionline** [comment]
Yeah, I agree with you. having an additional dependancy is not a good idea. But was just wishing a better and simpler way to register modules. Text file is not at all a bad idea provided it has the merit

**Comment by brianlagunas** [comment]
You could use an App.config fie and then use the Prism Extensibility Pack to add your modules via a form.

https://marketplace.visualstudio.com/items?itemName=BrianLagunas.PrismExtensibilityPack

**Comment by brianlagunas** [comment]
or , just write your own Json module catalog.

**Comment by noufionline** [comment]
Thanks, @brianlagunas . Is PrismExtensibilityPack is compatible with Visual Studio 2017? I am not able to install!

**Comment by brianlagunas** [comment]
Not yet, I have not updated it.  I'll get to that when I have time.

**Comment by dansiegel** [comment]
You could simply reference System.Json

**Comment by brianlagunas** [comment]
Have you seen how to define a module in a file?
