### ISSUE TITLE
I can't for the life of me get Realm database to work Xamarin.Forms. I used your latest version of the templates, but as soon as i add Realm everything goes downhill. Guess Realm does not support .NET Standard yet, or there is something else i am missing. Shame, i really want to mover over to .NET Standard, but with new template pack, only thing holding me back is Realm.

### ISSUE THREAD

**Issue by Allmight** [PrismLibrary/Prism#1271]
*Use GitHub issues for __bugs in Prism and feature requests only__. If you have a question how to implement something using Prism or a bug in your app that might be related to Prism, please post your question on [StackOverflow](http://stackoverflow.com/tags/prism) (which we monitor as well).*

Please provide as much detail as possible (and feel free to remove unused properties):

### Package info

- Platform:
- Prism version:
- Xamarin version (if applicable):
- Windows 10 SDK version (if applicable):
- Other version info:

### Repro steps

Please describe the issue/request in detail.

**Comment by brianlagunas** [comment]
I'm sorry but this has nothing to do with Prism.  You should bring your concerns up with the Realm team.

**Comment by Allmight** [comment]
Yeah, sorry bout that. I was about to remove this issue when i realised my error.
