### ISSUE TITLE
StructureMap as new container for Xamarin Forms.

### ISSUE THREAD

**Issue by dazinator** [PrismLibrary/Prism#1274]
Feature request:

Ability to use `StructureMap` container for `PrismApplication` when targeting Xamarin Forms.

**Comment by brianlagunas** [comment]
We accept PR's.  Luckily for you, we already have this support in WPF so this is more likely to be accepted.  Although, there is no guarantee of when, or if, it will be accepted as it will take time to properly review and test

**Comment by brianlagunas** [comment]
StructureMap us being sun-setted so no need in adding support for it.  https://jeremydmiller.com/2018/01/29/sunsetting-structuremap/
