### ISSUE TITLE
BaseDirectory for DirectoryModuleCatalog

### ISSUE THREAD

**Issue by dvorn** [PrismLibrary/Prism#1276]
### Package info

- Platform: WPF
- Prism version: All

### Repro steps

Build the sample https://github.com/PrismLibrary/Prism-Samples-Wpf/tree/master/7-Modules%20-%20Directory

Use command line to run Modules.exe from directory other than the directory of exe file.  E.g., from the solution directory run Modules\bin\debug\Modules.exe.  

The application crashes.

The ModulePath property of DirectoryModuleCatalog may specify an absolute or relative path.  If the path is relative, the documentation does not specify to what directory the path is relative.  It turns out that it is relative to the current working directory.  The application is deployed so that the "Modules" folder is next to the application exe folder.  If the current working directory is different from the application exe folder, this does not work.

Options:

1.  Upgrade the documentation to explicitly state that ModulePath is relative to the current working directory (which is the current implementation).  Update the sample application: in the bootstrapper, save the current working directory, set it to the directory of exe, load modules, restore the current working directory.

2. Use an approach similar to MEF's DirectoryCatalog which has the BaseDirectory property which defaults to the directory of exe (AppDomain.CurrentDomain.BaseDirectory).

a) Always evaluate relative ModulePath relative to AppDomain.CurrentDomain.BaseDirectory.

or

b) Introduce BaseDirectory property for DirectoryModuleCatalog.  It may default to either current working directory or directory of exe.  It could be overridden when DirectoryModuleCatalog is created in bootstrapper.  Evaluate ModulePath relative to BaseDirectory.

**Comment by brianlagunas** [comment]
I actually like adding the BaseDirectory property and defaulting it to the current directory as to not break anyone using it.  Another great find.

Do you have time to create a PR?

**Comment by dvorn** [comment]
I still have doubts about the best way to approach this.  If BaseDirectory defaults to the current directory, the users will have to write something like

```
new DirectoryModuleCatalog() 
{ 
    ModulePath = @".\Modules",
    BaseDirectory = AppDomain.CurrentDomain.BaseDirectory
};
```
which is less clear than
```
new DirectoryModuleCatalog() 
{ 
    ModulePath = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, @".\Modules")
};
```
which does not require any modification to library and essentially means that relative paths are discouraged.

May be something like this
```
new DirectoryModuleCatalog() 
{ 
    ModulePath = @".\Modules",
    RelativeToExe = true
};
```
or there is an even better way?

**Comment by noufionline** [comment]
@dvorn 

If BaseDirectory is not specified, let it take the default (relative to Exe path) otherwise let the user specify the path.

Just a suggestion!

**Comment by brianlagunas** [comment]
Hmmm.... actually the more I think about it the more I am agreeing with your assessment.  Maybe updating the docs to describe the current behavior would be best.

I will think about this some more what I get some time.

**Comment by Dirkster99** [comment]
This issue describes exactly what I reported here:
https://github.com/PrismLibrary/Prism/issues/1151

I don't really understand why supporting a relativ from the executeable is an issue.

I really wonder what the value of the current functionality is, if I can:
1) only use a fixed path in the app.config or
2) am forced to change to an applications folder before being able to use it?

**Comment by dvorn** [comment]
Actually #1151 has nothing to do with MEF.  It is about ConfigurationCatalog which resolves relative paths in `<module assemblyFile=...` relative to the current working directory.  This is particularly nasty since a configuration file do not have naturally a process with a current directory associated with it.  It turns out the meaning of a configuration file depends on the process interpreting it.

**Comment by brianlagunas** [comment]
I think this is just one of those "leave it the way it is" issues.  Not a big deal, and not a blocker. It could just be a little more clear. Thanks again for brining it up.
