### ISSUE TITLE
Shared ViewModel From childern of tabbedpage

### ISSUE THREAD

**Issue by brux88** [PrismLibrary/Prism#1278]
*Use GitHub issues for __bugs in Prism and feature requests only__. If you have a question how to implement something using Prism or a bug in your app that might be related to Prism, please post your question on [StackOverflow](http://stackoverflow.com/tags/prism) (which we monitor as well).*

Please provide as much detail as possible (and feel free to remove unused properties):

### Package info

- Platform: Xamarin forms
- Prism version: 6.3.0
- Xamarin version (if applicable): 2.3.4

hello I'm using prism. i have a tabbedpage how can i share a single viewmodel for all daughters pages?

my xaml:

> <TabbedPage xmlns="http://xamarin.com/schemas/2014/forms"
>             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
>             xmlns:prism="clr-namespace:Prism.Mvvm;assembly=Prism.Forms"
>             xmlns:views="clr-namespace:MySednaApp.Views;assembly=MySednaApp"
>             xmlns:view="clr-namespace:MySednaApp.View;assembly=MySednaApp"
>             prism:ViewModelLocator.AutowireViewModel="True"
>             x:Class="MySednaApp.Views.PubblicaArticoliTabbedPage"
>             Title="{view:Translate PubblicaArticoli}">
>     <TabbedPage.ToolbarItems>
>         <ToolbarItem x:Name="Delete2" Icon="ico_delete.png" Text="Elimina"    Command="{Binding delete}"   >
>             <ToolbarItem.Order>
>                 <OnPlatform x:TypeArguments="ToolbarItemOrder">
>                     <On Platform="iOS">Primary</On>
>                     <On Platform="Android">Secondary</On>
>                 </OnPlatform>
>             </ToolbarItem.Order>
>         </ToolbarItem>
>         <ToolbarItem x:Name="Save" Icon="ico_save.png"  Command="{Binding save}"  Order="Primary" Priority="0" />
>     </TabbedPage.ToolbarItems>
>     <views:PubblicaArticoliDettaglioPage x:Name="pubblicaArticoliDettaglioPage"/>
>     <views:PubblicaArticoliGaugePage  x:Name="pubblicaArticoliGaugePage"/>
>     <views:PubblicaArticoliFotoPage  x:Name="pubblicaArticoliFotoPage"/>
> </TabbedPage>

**Comment by brianlagunas** [comment]
You have already posted your question here:

https://stackoverflow.com/questions/47423633/prism-shared-viewmodel

Please do not cross post.
