### ISSUE TITLE
Crash calling GoBackAsync

### ISSUE THREAD

**Issue by SirdarAPJ** [PrismLibrary/Prism#1279]
My app crashes when calling GoBackAsync twice in sequence, only on the iOS platform. It has some situations that we have to navigate through two pages until reach a third page. So we have to go back to the first one without going through the other two. As stated, this implementation worked fine until it was tested on iOS. I ve read the post ["Add ability to Remove pages from the navigation stack"](github.com/PrismLibrary/Prism/issues/921), about non-linear navigation and the new extension methods RemovePage and PopToRoot available in prism release. Do you know if it would solve my crash issue by updating prism and refactoring my app code to use these new methods, in addition to solving a navigation problem? We have already tried some alternatives without success or with some side effect. I wish I could try something more assertive this time. 

Prism version: 6.3.0.0

**Comment by brianlagunas** [comment]
You can't call GoBackAsync twice in succession. Once you call GoBackAsync, the page is removed from the navigation stack.  It no longer knows anything about your nav stack.

You would have to pass a parameter to the previous page in your GoBackAsync call to instruct it to call GoBackAsync in the OnNavigatedTo.

Or, you could try using the new features in the latest preview to see if they fit your needs.

**Comment by SirdarAPJ** [comment]
I couldnt explain my implementation right, probably 'cause of my poor English skills. I do exactly as you suggest, telling OnNavigatingTo that I need to call GoBackAsync () again. The "sequentially" was to try to explain that there is no user interaction or processing between one GoBack and another. This works fine on Android, but crashes on iOS.

**Comment by brianlagunas** [comment]
Try calling it in OnNavigatedTo not OnNavigatingTo, or just use the new features in the preview.

**Comment by SirdarAPJ** [comment]
I knew the event OnNavigatedTo but this code was already implemented before and working fine on Android. I did not even go into that detail. This will probably work without necessarily to use the new methods. But I will consider upgrading simply by considering the implementation without the multiple GoBacks more elegant. Thank you very much for your attention.

**Comment by brianlagunas** [comment]
Why do you need multiple gobacks?

The new features might help if you know that when you navigate to the third page, you want to remove the previous two.

`NavigateAsync("../../ThirdPage");`

That will automatically remove the previous pages from the stack so when you click goback it will work as expected.

**Comment by SirdarAPJ** [comment]
So good! This is the most elegant implementation. But is this feature (../../page) only available in the latest pre-release version?

**Comment by brianlagunas** [comment]
yes, it's in the latest pre-release.

**Comment by SirdarAPJ** [comment]
Ok! I will do the upgrade. Thank you one more time.
