### ISSUE TITLE
New Xamarin Forms Prism Project does not build.

### ISSUE THREAD

**Issue by rizaanlakay** [PrismLibrary/Prism#1280]
I am using Visual Studio 2017 15.3.5 and created a new project for Android and iOS. The empty project does not build and has the following error: 

Severity	Code	Description	Project	File	Line	Suppression State
Error		The OutputPath property is not set for project 'FlushBuddy.Android.csproj'.  Please check to make sure that you have specified a valid combination of Configuration and Platform for this project.  Configuration='Debug'  Platform='AnyCPU'.  This error may also appear if some other project is trying to follow a project-to-project reference to this project, this project has been unloaded or is not included in the solution, and the referencing project does not build using the same or an equivalent Configuration or Platform.	FlushBuddy.Android			

This used to work, so I'm not sure what has changed? Anybody else have this issue?

**Comment by brianlagunas** [comment]
This is a bug in VS. SImpl yopen your properties for your project, and then go to the debug tab.  delete the `\` on the Debug out put path and then re-add it.

**Comment by rizaanlakay** [comment]
Superstar!
