### ISSUE TITLE
Provide Subscribe and Unsubscribe method overloads to centralize the use of EventAggregator 

### ISSUE THREAD

**Issue by noufionline** [PrismLibrary/Prism#1282]
Hi @brianlagunas ,

How about adding a new method overload like this and have it called from OnNavitateTo(..) 

```csharp
        public virtual void SubscribeEvents()
        {
            
        }
```

and something like this and have it called from OnNavigateFrom(...)
```csharp
       public virtual void UnsubscribeEvents()
        {
            
        }
```
*Or any better way to standardise the way events are subscribed and unsubscribed.
This will help all the consumers to centralize the task of subscribing and unsubscribing events with ease.*

**Comment by brianlagunas** [comment]
You don't have to unsubscribe form IEventAggregaotr events.  Also, there is no base class in Prism. SO there would be no where to add such a virtual method.  Also, If you need to unsubscribe, implement IDestructible

**Comment by noufionline** [comment]
@brianlagunas thanks,
I never heard of IDestructible and could not find anything on google as well. Can you help me with some link where I can get more info about this interface

**Comment by noufionline** [comment]
If I am not unsubscribing subscribed events fires multiple times.

**Comment by brianlagunas** [comment]
Then you are not subscribing in the right spot. Should only subscribe once.

**Comment by brianlagunas** [comment]
IDestructible is use to clean up any resources when the page is popped off the stack. Implement it and see if it fits your needs.

**Comment by noufionline** [comment]
I am subscribing on customer views OnNavigatedTo event and when I close the customer view and open again the subscription will happen again I tried to make the keep Alive property false but still it’s firing

**Comment by brianlagunas** [comment]
Don't subscribe to events there as that can fire multiple times. Subscribe in the ctor

**Comment by noufionline** [comment]
Oh I am working on WPF and you might be talking about Xamarin forms I guess

**Comment by brianlagunas** [comment]
oh, yes. IDestructible is on XF not WPF.

**Comment by noufionline** [comment]
At the beginning I was subscribing from the constructor only but it was still firing. May be I missed something
