### ISSUE TITLE
Provide Filtering Overload in PubSubEvent without Payload

### ISSUE THREAD

**Issue by noufionline** [PrismLibrary/Prism#1284]
### Package info

- Platform: WPF
- Prism version: 7
It's always not the case that payload is part of the filtering. In my case I want the subscription to happen only if the view is Active (IsActive=true).

I would like to have two options in PubSubEvent if possible.
```csharp
 public SubscriptionToken Subscribe(Action action, ThreadOption threadOption, bool keepSubscriberReferenceAlive,
            Func<bool> filter){}

 public SubscriptionToken Subscribe(Action action,Func<bool> filter)
```

**Comment by brianlagunas** [comment]
If you aren't filtering off the payload, why not just check the value of your IsActive in the handler.

```
if (!IsActive)
    return;

//code to execute
```
