### ISSUE TITLE
OnNavigatedTo not called on MainWindowViewModel

### ISSUE THREAD

**Issue by weitzhandler** [PrismLibrary/Prism#1285]
### Package info

- Platform: WPF (.NET 4.7.1)
- Prism version: 6.3.0

### Repro steps

- Create a Prism (DryIoc) project from the Prism templates
- Have the `MainWindowViewModel` class implement `INavigationAware`, and put a breakpoint in the `OnNavigatedTo` method
- When running the program, the debugger doesn't stop at the breakpoint

**Comment by brianlagunas** [comment]
If course not. The MainWindow is not being navigated to. Its the shell.  No navigation is occurring.  Hence, non of the INavigationAware method will fire.  The only way those methods fire is if you use the IRegionMagaer.RequestNavigate method.

**Comment by weitzhandler** [comment]
So is there a way to 'navigate' to the `MainWindow`?
The reason I want to do this is because I want to call `ILoginService.EnsureLogin` (provided via IoC).
And I only want to call it when the Window was loaded. Any other things to consider?

Thanks!

**Comment by brianlagunas** [comment]
Call it in the ctor of your ViewModel. Or call it before you even show the Shell.  Use a behavior to hook into the loaded event of the window and execute a command. Lots of ways.

**Comment by weitzhandler** [comment]
Since I can only perform this action when the view is ready, the only option is the second one, which I don't like so much (because I prefer keeping the code-behind files clean).
If you have another way to intercept the Window readiness in the VM, I'd appreciate if you can tell me.

Thank you very much!

**Comment by brianlagunas** [comment]
If you use a behavior, you don't need code-behind.

**Comment by weitzhandler** [comment]
That's what I'm gonna do, thanks!
