### ISSUE TITLE
Adding modules to Prism in newest PR version

### ISSUE THREAD

**Issue by SirdarAPJ** [PrismLibrary/Prism#1286]
I recently upgraded the prism to its latest pre-release to take advantage of the newest navigation features. After the update I had to make the following changes in some namespaces:

```
\*using Microsoft.Practices.Unity; (excluded)*\
using Unity; --(added)
using Unity.Lifetime; --(added)
```

I would like to know, first of all, if this procedure is correct.

Additionally, the error "*A duplicated module with name has already been added*" has always occurred when I try to add the second module in the following code snippet:

```
        protected override void ConfigureModuleCatalog ()
        {
            base.ConfigureModuleCatalog ();

            ModuleCatalog.AddModule (new ModuleInfo (typeof (CoreModule)));
            ModuleCatalog.AddModule (new ModuleInfo (typeof (ServicServiceModule)));
            ModuleCatalog.AddModule (new ModuleInfo (typeof (SynchronizationModule));
        }
```
This code worked fine before the update.

Based on the above information, can you deduce what I am doing wrong?

Thanks!

- Platform: Android
- Prism version: 7.0.0.269-pre
- Xamarin version: 4.6.0.295
- Xamarin.Forms version: 2.5.0.91635

**Comment by brianlagunas** [comment]
Yes, you must update the namespaces because the latest preview is using Unity v5. Unity introduced a number of breaking changes which included namespace name changes.

The second issue is actually a bug.  For now use the following syntax to get around that issue:
```
ModuleCatalog.AddModule<CoreModule>();
```
