### ISSUE TITLE
Navigationbar flickering while navigating from detailpage

### ISSUE THREAD

**Issue by VinoliyaPrincy** [PrismLibrary/Prism#1291]
When clicking a button to navigation bar is flickering on the page.
I attached the image for my issue.Please help me to fix this
![error](https://user-images.githubusercontent.com/23738877/33363261-a94425b0-d505-11e7-94a6-739fe1945827.jpg)

**Comment by brianlagunas** [comment]
This has nothing to do with Prism. I suggest you post your question on StackOverflow or the Xamarin.Forms forums.  I will say that you shouldn't be wrapping your MasterDetailPage in a NavigationPage.
