### ISSUE TITLE
Can't run in Xamarin Live Player

### ISSUE THREAD

**Issue by leonmeijer** [PrismLibrary/Prism#1294]
Should I be able to run a Prism app via Xamarin Live Player?

### Package info

- Platform: Android
- Prism version: Prism.Forms 7.0.0.335-ci
- Xamarin version (if applicable): Xamarin Forms 2.5
- Windows 10 SDK version (if applicable):
- Other version info: VS 2017 15.5.0 Preview 5, .NET Core 2.0.3 SDK
- Had all the NuGets updated to the latest versions (PRISM via MyGet)

### Repro steps
A File New Project -> Cross-Platform App (Xamarin.Forms) -> Master Detail / All platforms / Xamarin Forms / .NET Standard compiles and I can run it on a Xamarin Live Player device (and in Live Player in Genymotion). This proves I can run apps in the Player.

A File New Project -> Prism -> Prism Blank App (Xamarin.Forms) -> All platforms / Dryloc compiles. I can deploy and run it. When I run this on Xamarin Live Player, I receive a Visualization Error (NullReferenceException).

A File new Project -> AppMap Project (Infragistics) -> All platforms / Dryloc compiles when the target is the Android device. When I change the target to Xamarin Live Player, I receive many build errors:

Deploying c:\users\leon_\Source\Repos\AppMapProject5\AppMapProject5\AppMapProject5.Android\AppMapProject5.Android.csproj...
Got device info: Samsung SM-A520F Player (Android) @ 192.168.3.164:37847
Synchronizing files...
Building and running...
Built with 48 messages.
c:\users\leon_\Source\Repos\AppMapProject5\AppMapProject5\AppMapProject5\App.xaml.cs(1,1): error: The type or namespace name 'DryIoc' could not be found (are you missing a using directive or an assembly reference?)
c:\users\leon_\Source\Repos\AppMapProject5\AppMapProject5\AppMapProject5\App.xaml.cs(1,1): error: The type or namespace name 'Prism' could not be found (are you missing a using directive or an assembly reference?)
c:\users\leon_\Source\Repos\AppMapProject5\AppMapProject5\AppMapProject5\Infrastructure\AppMapViewModelBase.cs(1,1): error: The type or namespace name 'Prism' could not be found (are you missing a using directive or an assembly reference?)
c:\users\leon_\Source\Repos\AppMapProject5\AppMapProject5\AppMapProject5\Infrastructure\AppMapViewModelBase.cs(1,1): error: The type or namespace name 'Prism' could not be found (are you missing a using directive or an assembly reference?)
c:\users\leon_\Source\Repos\AppMapProject5\AppMapProject5\AppMapProject5\Infrastructure\AppMapViewModelBase.cs(1,1): error: The type or namespace name 'Prism' could not be found (are you missing a using directive or an assembly reference?)
c:\users\leon_\Source\Repos\AppMapProject5\AppMapProject5\AppMapProject5\Infrastructure\AppMapViewModelBase.cs(1,1): error: The type or namespace name 'Prism' could not be found (are you missing a using directive or an assembly reference?)
c:\users\leon_\Source\Repos\AppMapProject5\AppMapProject5\AppMapProject5\ViewModels\MainPageViewModel.cs(1,1): error: The type or namespace name 'Prism' could not be found (are you missing a using directive or an assembly reference?)
c:\users\leon_\Source\Repos\AppMapProject5\AppMapProject5\AppMapProject5\ViewModels\MainPageViewModel.cs(1,1): error: The type or namespace name 'Prism' could not be found (are you missing a using directive or an assembly reference?)
c:\users\leon_\Source\Repos\AppMapProject5\AppMapProject5\AppMapProject5\ViewModels\MainPageViewModel.cs(1,1): error: The type or namespace name 'Prism' could not be found (are you missing a using directive or an assembly reference?)
c:\users\leon_\Source\Repos\AppMapProject5\AppMapProject5\AppMapProject5\ViewModels\MainPageViewModel.cs(1,1): error: The type or namespace name 'Prism' could not be found (are you missing a using directive or an assembly reference?)
c:\users\leon_\Source\Repos\AppMapProject5\AppMapProject5\AppMapProject5\App.xaml.cs(1,1): error: The type or namespace name 'PrismApplication' could not be found (are you missing a using directive or an assembly reference?)
(1,1): error: The type or namespace name 'Prism' could not be found in the global namespace (are you missing an assembly reference?)
c:\users\leon_\Source\Repos\AppMapProject5\AppMapProject5\AppMapProject5\Infrastructure\AppMapViewModelBase.cs(1,1): error: The type or namespace name 'BindableBase' could not be found (are you missing a using directive or an assembly reference?)
c:\users\leon_\Source\Repos\AppMapProject5\AppMapProject5\AppMapProject5\Infrastructure\AppMapViewModelBase.cs(1,1): error: The type or namespace name 'INavigationAware' could not be found (are you missing a using directive or an assembly reference?)
c:\users\leon_\Source\Repos\AppMapProject5\AppMapProject5\AppMapProject5\Infrastructure\AppMapViewModelBase.cs(1,1): error: The type or namespace name 'IConfirmNavigation' could not be found (are you missing a using directive or an assembly reference?)
c:\users\leon_\Source\Repos\AppMapProject5\AppMapProject5\AppMapProject5\Infrastructure\AppMapViewModelBase.cs(1,1): error: The type or namespace name 'IDestructible' could not be found (are you missing a using directive or an assembly reference?)
c:\users\leon_\Source\Repos\AppMapProject5\AppMapProject5\AppMapProject5\App.xaml.cs(1,1): error: 'App.OnInitialized()': no suitable method found to override
c:\users\leon_\Source\Repos\AppMapProject5\AppMapProject5\AppMapProject5\App.xaml.cs(1,1): error: 'App.RegisterTypes()': no suitable method found to override
c:\users\leon_\Source\Repos\AppMapProject5\AppMapProject5\AppMapProject5\App.xaml.cs(1,1): error: The type or namespace name 'IPlatformInitializer' could not be found (are you missing a using directive or an assembly reference?)
c:\users\leon_\Source\Repos\AppMapProject5\AppMapProject5\AppMapProject5\ViewModels\MainPageViewModel.cs(1,1): error: The type or namespace name 'INavigationService' could not be found (are you missing a using directive or an assembly reference?)
c:\users\leon_\Source\Repos\AppMapProject5\AppMapProject5\AppMapProject5\Infrastructure\AppMapViewModelBase.cs(1,1): error: The type or namespace name 'DelegateCommand<>' could not be found (are you missing a using directive or an assembly reference?)
c:\users\leon_\Source\Repos\AppMapProject5\AppMapProject5\AppMapProject5\Infrastructure\AppMapViewModelBase.cs(1,1): error: The type or namespace name 'DelegateCommand<>' could not be found (are you missing a using directive or an assembly reference?)
c:\users\leon_\Source\Repos\AppMapProject5\AppMapProject5\AppMapProject5\Infrastructure\AppMapViewModelBase.cs(1,1): error: The type or namespace name 'DelegateCommand<>' could not be found (are you missing a using directive or an assembly reference?)
c:\users\leon_\Source\Repos\AppMapProject5\AppMapProject5\AppMapProject5\Infrastructure\AppMapViewModelBase.cs(1,1): error: The type or namespace name 'DelegateCommand<>' could not be found (are you missing a using directive or an assembly reference?)
c:\users\leon_\Source\Repos\AppMapProject5\AppMapProject5\AppMapProject5\Infrastructure\AppMapViewModelBase.cs(1,1): error: The type or namespace name 'INavigationService' could not be found (are you missing a using directive or an assembly reference?)
c:\users\leon_\Source\Repos\AppMapProject5\AppMapProject5\AppMapProject5\Infrastructure\AppMapViewModelBase.cs(1,1): error: The type or namespace name 'NavigationParameters' could not be found (are you missing a using directive or an assembly reference?)
c:\users\leon_\Source\Repos\AppMapProject5\AppMapProject5\AppMapProject5\Infrastructure\AppMapViewModelBase.cs(1,1): error: The type or namespace name 'NavigationParameters' could not be found (are you missing a using directive or an assembly reference?)
c:\users\leon_\Source\Repos\AppMapProject5\AppMapProject5\AppMapProject5\Infrastructure\AppMapViewModelBase.cs(1,1): error: The type or namespace name 'NavigationParameters' could not be found (are you missing a using directive or an assembly reference?)
c:\users\leon_\Source\Repos\AppMapProject5\AppMapProject5\AppMapProject5\Infrastructure\AppMapViewModelBase.cs(1,1): error: The type or namespace name 'NavigationParameters' could not be found (are you missing a using directive or an assembly reference?)
c:\users\leon_\Source\Repos\AppMapProject5\AppMapProject5\AppMapProject5\Infrastructure\AppMapViewModelBase.cs(1,1): error: The type or namespace name 'DelegateCommand<>' could not be found (are you missing a using directive or an assembly reference?)
c:\users\leon_\Source\Repos\AppMapProject5\AppMapProject5\AppMapProject5\Infrastructure\AppMapViewModelBase.cs(1,1): error: The type or namespace name 'DelegateCommand<>' could not be found (are you missing a using directive or an assembly reference?)
c:\users\leon_\Source\Repos\AppMapProject5\AppMapProject5\AppMapProject5\Infrastructure\AppMapViewModelBase.cs(1,1): error: The type or namespace name 'DelegateCommand<>' could not be found (are you missing a using directive or an assembly reference?)
c:\users\leon_\Source\Repos\AppMapProject5\AppMapProject5\AppMapProject5\Infrastructure\AppMapViewModelBase.cs(1,1): error: The type or namespace name 'DelegateCommand<>' could not be found (are you missing a using directive or an assembly reference?)
c:\users\leon_\Source\Repos\AppMapProject5\AppMapProject5\AppMapProject5\Infrastructure\AppMapViewModelBase.cs(1,1): error: The type or namespace name 'INavigationService' could not be found (are you missing a using directive or an assembly reference?)
c:\users\leon_\Source\Repos\AppMapProject5\AppMapProject5\AppMapProject5\App.xaml.cs(1,1): error: 'Prism.DryIoc.PrismApplication' does not contain a constructor that takes 1 arguments
c:\users\leon_\Source\Repos\AppMapProject5\AppMapProject5\AppMapProject5\App.xaml.cs(1,1): error: The name 'NavigationService' does not exist in the current context
c:\users\leon_\Source\Repos\AppMapProject5\AppMapProject5\AppMapProject5\App.xaml.cs(1,1): error: The name 'Container' does not exist in the current context
c:\users\leon_\Source\Repos\AppMapProject5\AppMapProject5\AppMapProject5\App.xaml.cs(1,1): error: The name 'Container' does not exist in the current context
c:\users\leon_\Source\Repos\AppMapProject5\AppMapProject5\AppMapProject5\Infrastructure\AppMapViewModelBase.cs(1,1): error: The type or namespace name 'DelegateCommand<>' could not be found (are you missing a using directive or an assembly reference?)
c:\users\leon_\Source\Repos\AppMapProject5\AppMapProject5\AppMapProject5\Infrastructure\AppMapViewModelBase.cs(1,1): error: The type or namespace name 'DelegateCommand<>' could not be found (are you missing a using directive or an assembly reference?)
c:\users\leon_\Source\Repos\AppMapProject5\AppMapProject5\AppMapProject5\Infrastructure\AppMapViewModelBase.cs(1,1): error: The type or namespace name 'DelegateCommand<>' could not be found (are you missing a using directive or an assembly reference?)
c:\users\leon_\Source\Repos\AppMapProject5\AppMapProject5\AppMapProject5\Infrastructure\AppMapViewModelBase.cs(1,1): error: The type or namespace name 'DelegateCommand<>' could not be found (are you missing a using directive or an assembly reference?)
(1,1): error: Dependent project AppMapProject5.csproj failed to build, using old version.
c:\users\leon_\Source\Repos\AppMapProject5\AppMapProject5\AppMapProject5.Android\MainActivity.cs(1,1): error: The type or namespace name 'DryIoc' could not be found (are you missing a using directive or an assembly reference?)
c:\users\leon_\Source\Repos\AppMapProject5\AppMapProject5\AppMapProject5.Android\MainActivity.cs(1,1): error: The type or namespace name 'Prism' could not be found (are you missing a using directive or an assembly reference?)
c:\users\leon_\Source\Repos\AppMapProject5\AppMapProject5\AppMapProject5.Android\MainActivity.cs(1,1): error: The type or namespace name 'IPlatformInitializer' could not be found (are you missing a using directive or an assembly reference?)
c:\users\leon_\Source\Repos\AppMapProject5\AppMapProject5\AppMapProject5.Android\MainActivity.cs(1,1): error: The type or namespace name 'IContainer' could not be found (are you missing a using directive or an assembly reference?)
c:\users\leon_\Source\Repos\AppMapProject5\AppMapProject5\AppMapProject5.Android\MainActivity.cs(1,1): error: The type or namespace name 'App' could not be found (are you missing a using directive or an assembly reference?)

**Comment by brianlagunas** [comment]
The Xamarin Live Player is very limited and does not support Prism apps.  Heck it doesn't support custom renderers.  There is a full list of limitations on the Xamarin website.

**Comment by weitzhandler** [comment]
Is there any progress with XLP for Prism apps?
Please see my [comment](https://forums.xamarin.com/discussion/comment/324067/#Comment_324067) and the [bug report](https://bugzilla.xamarin.com/show_bug.cgi?id=61270) too.

**Comment by weitzhandler** [comment]
@brianlagunas 
Is there any progress with XLP for Prism apps?
Please see my [comment](https://forums.xamarin.com/discussion/comment/324067/#Comment_324067) and the [bug report](https://bugzilla.xamarin.com/show_bug.cgi?id=61270) too.
