### ISSUE TITLE
CA2214 warnings on SetProperty calls

### ISSUE THREAD

**Issue by wowfood** [PrismLibrary/Prism#1295]
- Platform:  Windows
- Prism version:  6.3
- Other version info:  .NET 4.6.2

I know this isn't so much an issue as an annoyance.  But getting a lot of compiler warnings for CA2214 where properties are being set in the constructor, which is cluttering up the warnings list.  I'd rather not supress the warning entirely (as this is advised against) but noticed that elsewhere in the prism code the following has been added

[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]

Would it be worth adding this to the SetProperty methods in BindableBase?  Or is there another method I can use to get around the compiler warnings.

**Comment by brianlagunas** [comment]
You should be setting the backing field in the ctor, not the property that invokes the INPC methods.

**Comment by wowfood** [comment]
Ok, thanks.
