### ISSUE TITLE
Support for IDestructilbe in WPF projects

### ISSUE THREAD

**Issue by weitzhandler** [PrismLibrary/Prism#1296]
### Package info

- Platform: WPF
- Prism version: 6.3

### Repro steps

Looks like the interface [`IDestructible`](https://github.com/PrismLibrary/Prism/blob/master/Source/Xamarin/Prism.Forms/Navigation/IDestructible.cs) is only available in XF.

I'm looking for a way to unsubscribe from events of objects injected to the VM before the VM needs to get collected/disposed of in WPF.

Is there a different way to achieve this?

*Some event sources aren't IoC ruled and `EventAggregator` is not always a feasible solution.

**Comment by noufionline** [comment]
Subscribe has an overload which has a predicate to control the subscription. Check IsActive on the predicate then it will not fire when view is not active.

```csharp
Subscribe(action, ThreadOption.PublisherThread, false, payload=> IsActive);
```

**Comment by weitzhandler** [comment]
Would still be nice to have `IDestructible` in WPF, to give us a hint on VM tear-down.

**Comment by brianlagunas** [comment]
You can write a custom region behavior to accomplish this in your app. This will most likely not be included in Prism as I cannot assume that when a view is removed from a region that it will not be reused again.

**Comment by brianlagunas** [comment]
I've actually decided to include this. If someone is trying to reuse VM's after they have been removed from a Region, then it is the developers responsibility not to "clean them up" or even implement this interface.

**Comment by brianlagunas** [comment]
Done!
