### ISSUE TITLE
Memory Leak in DefaultConfirmationWindow

### ISSUE THREAD

**Issue by apmorton** [PrismLibrary/Prism#1297]
When using the default implementation of `Confirmation` with `DefaultConfirmationWindow`, the instance of `Confirmation` used gets leaked.  This is due to binding on an object that does not implement INotifyPropertyChanged (or is otherwise not a dependency object).

### Package info

- Platform: Wpf
- Prism version: 6.3.0

### Repro steps

Run the attached example under a memory profiler
[PrismMemoryLeakTest.zip](https://github.com/PrismLibrary/Prism/files/1545447/PrismMemoryLeakTest.zip)

**Comment by brianlagunas** [comment]
Thanks for pointing this out. This is actually a very common issues in WPF and I can't believe I completely missed this.

**Comment by apmorton** [comment]
Yep, this is definitely "one of those things" about WPF - investigating a memory leak in my own application is what lead me to this bug. Until a few days ago I was entirely unaware of this wonderful little "gotcha" about binding to objects that don't implement INotifyPropertyChanged.

What follows is entirely unrelated to this issue, I just chose to shout into the wind about my current frustration :)

Unfortunately my memory leak isn't so simple *sigh*. Turns out there are some internal classes in PresentationCore that keep references to controls to track mouse/keyboard input states. If your .net code is running as part of a native process through hosting and you close all your .net windows the last one to close (and all associated models/viewmodels) will remain in memory until another .net window in the process gets keyboard/mouse focus.  I guess it's not a true memory leak, since it is correctly reclaimed *eventually*, but it definitely looks like one.

/rant

**Comment by brianlagunas** [comment]
There are a number of "leaks" that are caused by the automation peers holding onto objects for a really long time when the app is running on a touch screen, or a screen where the automation peers is enabled.  This is a known issue with MS, and they don't have a solution yet.

**Comment by dvorn** [comment]
There is no memory leak in Prism interactivity default windows.  For a leak to occur, the source object of the binding should have a (direct or indirect) reference to the target of the binding.  See https://support.microsoft.com/en-us/help/938416/a-memory-leak-may-occur-when-you-use-data-binding-in-windows-presentat .  

You may verify that the memory is reclaimed by running the popup window multiple times and taking snapshots.

**Comment by brianlagunas** [comment]
Actually, this is a common issue with WPF.  If a Window binds to an object that is not a DO or implements INPC, it will leak.  You can see it in this sample: 
[WpfBindingIssue.zip](https://github.com/PrismLibrary/Prism/files/1648316/WpfBindingIssue.zip)

**Comment by dvorn** [comment]
@brianlagunas This sample proves nothing.  There is no memory leak. Do the following with the sample:

1. Add a big object to Foo, e.g.
```csharp
public class Foo
{
     private byte[] buffer = new byte[1000000];
```
(this is not necessary, but simplifies finding the Foo object).

2. Start the program.

3. In Diagnostic Tools\Memory Usage take a snapshot.

4. Open and close the OtherWindow several times (e.g., 10).

5. Take another snapshot.

6. See the difference between snapshots.  To find the Foo objects, sort rows by the "size" column.

7. Repeat steps 4-6, if curious.

If there were a memory leak in the binding, we would see 10 Foo objects.  But there are just a few, usually from 1 to 3.

I did not investigate who's holding the Foo object.  May be the windowing system holds the last top-level window or something like that.  But certainly this is not a binding.

**Comment by dvorn** [comment]
The "WPF binding memory leak" occurs when the source of the binding contains a direct or indirect reference to the source.  If you want to see it in action, change the content of the OtherWindow to the following:
```XAML
<Grid>
    <StackPanel Name="MyStackPanel">
        <TextBlock Text="{Binding Name}" />
        <TextBlock Text="{Binding ElementName=MyStackPanel, Path=Children.Count}" />
    </StackPanel>
</Grid>
```
And repeat the steps described above.  You will see that the number of Foo object corresponds to how many times you pressed the "Show Window" button.

**Comment by dvorn** [comment]
Of course it does not hurt to have INPC on Notification/Confirmation but this change was pointless and, I would say, it will be misleading to other developers who may believe in the myth of "memory leak" in MVVM.

**Comment by dvorn** [comment]
Another misleading issue with the proposed fix is that Notification implements INPC, but this implementation is not functional: the PropertyChanged event is never fired.

The developer will see from metadata that Notification implements INPC and will think that it is possible to change the Title of notification window during execution of popup by changing the Title property of the Notification object.  But that won't work.

IMO, it is a bad fix for non-existent problem.

**Comment by brianlagunas** [comment]
@dvorn After sleeping on it, I actually agree with you.  This is a pretty bad, and misleading "fix". I also didn't see any difference in my snapshots.  I am going to revert this as it really is a bad approach to a non-issue.
