### ISSUE TITLE
DelegateCommand.ObservesProperty() to work with DependencyProperties?

### ISSUE THREAD

**Issue by james1301** [PrismLibrary/Prism#1298]
I am using a DelegateCommand on a Control of mine in WPF. My command relies on whether the control IsEnabled or not, so I want it's CanExecute to go off when this property changes. I know currently the ObservesProperty works on properties that implement INotifyPropertyChanged, but would it be possible to extend this to Dependency Properties also?

### Package info

- Platform: WPF
- Prism version: 6.3

### Repro steps

Please describe the issue/request in detail.

**Comment by brianlagunas** [comment]
It sounds to me like you have some design smell going on. A command controls the state of the IsEnabled of the button it is bound to, not the other way around. This not going to supported.

**Comment by james1301** [comment]
That's not really what I meant, I know how a command works... Basically there is a delegate command on my custom control, which has a CanExecute that relies on a couple of bound dependency properties. My Button within my custom control is disabled because it never updates it CanExecute when these properties change. To fix this at the moment I am calling the RaiseCanExecuteChanged on the command in the Dependency Property PropertyChangedCallback. But it would be much neater if the DelegateCommand's ObserveProperty would just work with Depedency Properties also.
