### ISSUE TITLE
Prism Xamarin.Forms using Repository + Logic Patterns

### ISSUE THREAD

**Issue by mmaneff** [PrismLibrary/Prism#1299]
Buenos días, estoy desarrollando un proyecto en el cual deseo usar las siguientes capas:
**_Capa Lógica_**: se encarga de realizar las validaciones necesarias entre los datos que ingresan y los datos que se obtienen desde la base de datos (Repository)
**_Capa Repository_**: solo devuelve los datos desde la base de datos SQLite. No tiene lógica de validaciones.

Como Prism usa DI (Dependency Injection) e IoC (Inversion of Control), para registrar las instancias. Uso el siguiente código para instanciar la Capa Lógica dentro del proyecto Portable, lo cual anda y bastante bien.

protected override void ConfigureContainer()
{
            base.ConfigureContainer();

            Container.RegisterInstance<IAccountLogic>(new AccountLogic());   
}

Dentro del ViewModel lo instancio en el constructor

public LoginViewModel(INavigationService navigationService, IPageDialogService pageDialogService, IAccountLogic accountLogic = null)
{
    this.navigationService = navigationService;
    this.pageDialogService = pageDialogService;         
    this.accountLogic = accountLogic;
}

Mi pregunta es, como debería registrar mi instancia para el Repository Pattern.? Mi repository es "IUserAccountRepository".

Quiero implementar esta forma ya que deseo tener aun más desacoplado lo que es la logica y el acceso a datos.

![image](https://user-images.githubusercontent.com/11965264/33889783-038f2644-df30-11e7-992b-4e7e86e11712.png)

Por último, la interface "**IUserAccountRepository**" se encuentra dentro del proyecto "**Domain**".

Cualquier ayuda será muy bien recibida y desde ya muchas gracias

**Comment by bartlannoeye** [comment]
You should ask these types of questions on [StackOverflow under the Prism tag](https://stackoverflow.com/questions/tagged/prism) (in English). Here we only handle bugs and feature requests.
