### ISSUE TITLE
Prism Forms Autofac register type Vms erro

### ISSUE THREAD

**Issue by muhammetsahin** [PrismLibrary/Prism#1300]
Hi, I have a problem with vm ctor pass parameter.

![image](https://user-images.githubusercontent.com/2045788/33937441-96df75c2-e014-11e7-8f6f-e1bdd4d7853d.png)

![image](https://user-images.githubusercontent.com/2045788/33937444-9e0a1dfc-e014-11e7-807c-404c1fe4a003.png)

I'm using latest prism forms nuget package 7.0.0.336-pre

![image](https://user-images.githubusercontent.com/2045788/33937453-a651c99c-e014-11e7-9161-0f7e2bcea7c2.png)

I've got this error:  MyHandler caught : An error occurred during the activation of a particular registration.
See the inner exception for details. Registration: Activator = MasterDetailContainer (ReflectionActivator),
Services = [MasterDetailContainer (System.Object)], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = OwnedByLifetimeScope --->
An exception was thrown while invoking the constructor 'Void .ctor()' on type 'MasterDetailContainer'. ---> An error occurred during the activation of a particular registration.
See the inner exception for details. Registration: Activator = MasterDetailContainerViewModel (ReflectionActivator), Services = [SafeDev.ViewModels.MasterDetailContainerViewModel],
Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = OwnedByLifetimeScope ---> An error occurred during the activation of a particular registration.
See the inner exception for details. Registration: Activator = AppDrawerViewModel (ReflectionActivator), Services = [S
afeDev.ViewModels.AppDrawerViewModel], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, 
Sharing = None, Ownership = OwnedByLifetimeScope ---> None of the constructors found with 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder'
on type 'SafeDev.ViewModels.AppDrawerViewModel' can be invoked with the available services and parameters:
Cannot resolve parameter 'Prism.Navigation.INavigationService navigationService' of constructor 'Void .ctor(INavigationService, IDialogService)'.
(See inner exception for details.) (See inner exception for details.) (See inner exception for details.) (See inner exception for details.)
12-13 10:43:55.994 I/mono-stdout( 3705): Cannot resolve parameter
'Prism.Navigation.INavigationService navigationService' of constructor 'Void .ctor(INavigationService, IDialogService)'. (See inner exception for details.) (See inner exception for details.) (See inner exception for details.) (See inner exception for details.)
12-13 10:43:56.018 E/mono-rt ( 3705): [ERROR] FATAL UNHANDLED EXCEPTION:
Autofac.Core.DependencyResolutionException: An error occurred during the activation of a particular registration.
See the inner exception for details. Registration: Activator = MasterDetailContainer (ReflectionActivator), Services
= [MasterDetailContainer (System.Object)], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = OwnedByLifetimeScope ---> An exception was thrown while invoking the constructor 'Void .ctor()' on type 'MasterDetailContainer'. ---> An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = MasterDetailContainerViewModel (ReflectionActivator), Services = [SafeDev.ViewModels.MasterDetailContainerViewModel], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = OwnedByLifetimeScope ---> An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = AppDrawerViewModel (ReflectionActivator), Services = [SafeDev.ViewModels.AppDrawerViewModel], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = OwnedByLifetimeScope ---> None of the constructors found with 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder' on type 'SafeDev.ViewModels.AppDrawerViewModel' can be invoked with the available services and parameters:
12-13 10:43:56.018 E/mono-rt ( 3705): Cannot resolve parameter 'Prism.Navigation.INavigationService navigationService' 
of constructor 'Void .ctor(INavigationService, IDialogService)'. (See inner exception for details.) (See inner exception for details.) 
(See inner exception for details.) (See inner exception for details.) ---> Autofac.Core.DependencyResolutionException: 
An exception was thrown while invoking the constructor 'Void .ctor()' on type 'MasterDetailContainer'. ---> An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = MasterDetailContainerViewModel (ReflectionActivator), Services = [SafeDev.ViewModels.MasterDetailContainerViewModel], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = OwnedByLifetimeScope ---> An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = AppDrawerViewModel (ReflectionActivator), Services = [SafeDev.ViewModels.AppDrawerViewModel], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = OwnedByLifetimeScope ---> None of the constructors found with 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder' on type 'SafeDev.ViewModels.AppDrawerViewModel' can be invoked with the available services and parameters:
12-13 10:43:56.018 E/mono-rt ( 3705): Cannot resolve parameter 'Prism.Navigation.INavigationService navigationService' of constructor 'Void .ctor(INavigationService, IDialogService)'. (See inner exception for details.) (See inner exception for details.) (See inner exception for details.) ---> Autofac.Core.DependencyResolutionException: An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = MasterDetailContainerViewModel (ReflectionActivator), Services = [SafeDev.ViewModels.MasterDetailContainerViewModel], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = OwnedByLifetimeScope ---> An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = AppDrawerViewModel (ReflectionActivator), Services = [SafeDev.ViewModels.AppDrawerViewModel], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = OwnedByLifetimeScope ---> None of the constructors found with 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder' on type 'SafeDev.ViewModels.AppDrawerViewModel' can be invoked with the available services and parameters:
12-13 10:43:56.018 E/mono-rt ( 3705): Cannot resolve parameter 'Prism.Navigation.INavigationService navigationService' of co
12-13 10:43:56.031 E/Surface ( 3705): queueBuffer: error queuing buffer to SurfaceTexture, -22

Any idea?

**Comment by bartlannoeye** [comment]
You did override the RegisterTypes without probably calling the base method as well?

The InnerException gives away your problem:

> Cannot resolve parameter
'Prism.Navigation.INavigationService navigationService' of constructor 'Void .ctor(INavigationService, IDialogService)

Questions like this should be asked on [StackOverflow under the Prism](https://stackoverflow.com/questions/tagged/prism) tag, only log bugs/feature requests here.
