### ISSUE TITLE
Weird Nuget package installation behavior after creating VS solution using Prism Template Pack 2.0

### ISSUE THREAD

**Issue by DaveNay** [PrismLibrary/Prism#1301]
After I created a new solution in VS2017 (15.5.1) I then tried to add the "NLog.Configuration" package. The installation of NLog.Configuration appeared to work properly (no errors in Nuget console), however I noted that the NLog.config and NLog.xsd files were not added to my project.

I then tested a standard WPF solution template provided by VS and adding the NLog package was successful.

Steps to reproduce:

1. Create a new project in VS2017 and select the "Prism Blank App (WPF)" template.
2. Select Unity container.
3. Open Package Manager Console
4. Install NLog.Config package (includes dependency on NLog)
5. Observe no errors reported
6. Observe NLog.xsd and NLog.config files are not present in project.
7. Files are also not present on disk
8. Also missing from the solution directory is the standard "packages" directory (although the NLog.dll reference is present, and the dll is copied from somewhere when the solution is built.)

Thanks!
Dave

**Comment by brianlagunas** [comment]
This is not a Prism issue. The Prism Template Pack project templates use the new PackageReference approach to managing NuGet.  You should reach out to NLog to determine if they will work with PackageReference.
