### ISSUE TITLE
OnNavigatedTo method getting fired twice in XF Prism 7

### ISSUE THREAD

**Issue by naweed** [PrismLibrary/Prism#1302]
Hi,
I have noticed that the OnNavigatedTo method is getting fired twice in XF.Prism 7 ViewModels when the associated page is a tabbed page. I have created a sample project replicating this issue. You will notice that the OnNavigatedTo method gets fire twice in TestPageViewModel. Code uploaded at: https://t.co/6nGO4UBv5K

### Details

- Platform: Xamarin Forms 
- Prism version: 7.0-336-pre
- Xamarin version: 2.5

[BlankApp1.zip](https://github.com/PrismLibrary/Prism/files/1561478/BlankApp1.zip)

**Comment by vishalpachori25** [comment]
Yes On Tabbed Page it gets fired twice.

**Comment by naweed** [comment]
In Prism 6.3, this was not the case. And it should only be fired once.

**Comment by dansiegel** [comment]
@naweed thanks for bringing this to our attention and for providing a sample.

**Comment by brianlagunas** [comment]
This is not a bug.  This is expected.  You are not defining a custom page as a Tab, instead you are using a standard ContentPage element within XMAL.  This also means that you are not providing a BindingContext for the ContentPage you are defining.  This forces the ContentPage to inherit the BindingContext of the TabbedPage instead.  That is why it is being called twice in your sample.

**Comment by naweed** [comment]
But this was not the issue in 6.3. 

Another observation, if I don't add any content page to the tabbed page, the method gets fired once. But if I add one or more (say 3) content pages, still the method gets fired only twice. For three content pages, it should get fired 4 times in total as per your explanation.

Let me know if you need any additional info.

**Comment by brianlagunas** [comment]
This is because in 6.3 the navigation pattern for tabbed pages was different. In 7.0 we changed how tabbed page nav works.  It doesn't matter how many content pages you add. OnNavigatedTo will be invoked on the TabbedPage AND the CurrentPage.  Since you are using the same ViewModel for both pages, it gets fired twice.  It will not fire on all ContentPages.

**Comment by vishalpachori25** [comment]
Ok Fair enough. So if we want that OnNavigatedTo will be called only One time then what approach we should follow? Should we take different ViewModel for each ContentPage and one for TabbedPage?
Suggest

**Comment by naweed** [comment]
If difficult to implement, its fine. I will handle this in my VM code itself.

Btw, great library. Keep up the good work.

Thanks

**Comment by naweed** [comment]
Nah. Tried. Couldn't get it to work.

The best it to have the OnNavigatedTo on the TabbedPage fired only once, as was the case in 6.3.

**Comment by brianlagunas** [comment]
I could probably add a check to see if the BindingContext is the same for both the TabbedPage and CurrentPage and not invoke OnNavigatedTo if they match.  This is really an edge case as it is recommended to have a separate Page for each tab and to not define the tabs inline.

**Comment by naweed** [comment]
Yes please, if you can do that.

The real use case for this is that I am showing a Movie Details screen. The VM is same for all the data, but I am segregating it into tabs for ease of viewing and categorization. See attached screenshot for reference.

Thanks

![2017-10-27_02-46-08-pm](https://user-images.githubusercontent.com/103980/34341489-916f352a-e9a9-11e7-9283-595716c1c279.jpg)

**Comment by brianlagunas** [comment]
I checked in a fix. You can try it out in the latest CI build on MyGet.

**Comment by naweed** [comment]
@brianlagunas , I can confirm that this has been fixed in the CI build. Attaching the updated app with new references for others benefit.

Thanks. Hoping to see it on Nuget very soon.


[BlankApp1.zip](https://github.com/PrismLibrary/Prism/files/1586559/BlankApp1.zip)

**Comment by naweed** [comment]
Hi, any idea when Prism 7 is going to go GA?
