### ISSUE TITLE
XF .NetStandard application, crashes using DryIoc container

### ISSUE THREAD

**Issue by toumir** [PrismLibrary/Prism#1304]
the **same** application with different container : 
- with unity container application works fine
- with DryIoc application crashes (I think when registering _NavigationPage_) 

Under : 

- Platform:Anroid,UWP, IOS???
- Prism version: 7.0.0.337-ci
- Xamarin version:2.5.0.121934
- Windows 10 SDK version:10.0.16299.0

### Repro steps
XF application generated by prism TemplatePack
update the packages : xamarin.forms and prism

**Comment by dansiegel** [comment]
@toumir thanks for reporting this. Now that you mention this I’m remembering that we had to fix this issue in 6.3. I’ll get this fixed shortly.

**Comment by dansiegel** [comment]
this has been fixed and is now in our MyGet feed

**Comment by toumir** [comment]
@dansiegel Thanks Sir 👍

**Comment by toumir** [comment]
the problem came back again :(

**Comment by TNoronha** [comment]
Yep, same issue here... :/
