### ISSUE TITLE
Prism WPF - Access all navigation history

### ISSUE THREAD

**Issue by 19er** [PrismLibrary/Prism#1306]
I am trying to implement a Breadcrumb for my project, so I need to access all navigation history data for a specific region. As i can see NavigationJournal only gives current record. How can I reach all navigation history up to current navigation?

**Comment by brianlagunas** [comment]
This is really simple, but will require custom code.  You simply add items to your own custom stack when you navigate to a view, and remove them when you navigate away from the view.

**Comment by 19er** [comment]
I want to do this centrally, inside ShellViewModel. So I can use, `this.regionManager.Regions["ContentRegion"].NavigationService.Navigated `
event to sense if any view is NavigatedTo.

But there is no; 

`this.regionManager.Regions["ContentRegion"].NavigationService.NavigatedFrom` event. So how can i sense if it is being Navigated From.

**Comment by brianlagunas** [comment]
There are many ways to do this.  The source code is available for you to study to find the appropriate approach that will work for your specific scenario.

**Comment by 19er** [comment]
Could you please, point me some direction in single one of many ways to sense NavigatedFrom centrally.
