### ISSUE TITLE
Is there a way that Prism.Forms 7 supports XF 2.4 for the lowest dependency?

### ISSUE THREAD

**Issue by 5yunus2efendi** [PrismLibrary/Prism#1310]
I have a project and I want to use Prism for MVVM pattern and XF with version 2.4, the reason I use XF 2.4 is because the APK size is still be tolerance (it's around **16 MB** with default Prism template) and it's very much stable version for my project. So is there a way Prism.Forms 7 supports XF 2.4 for the lowest dependency?

**Comment by brianlagunas** [comment]
Unfortuntaely not.  Prism 7 will continue to target the latest version of XF.
