### ISSUE TITLE
XF Android: OnSizeAllocated called twice with Prism

### ISSUE THREAD

**Issue by andreinitescu** [PrismLibrary/Prism#1313]
### Package info

- Platform: Tried on Android 5 and Android 7
- Prism version: 7.0.0.336-pre
- Xamarin version (if applicable): Xamarin Android 8, Xamarin Forms 2.5.0.121934

### Repro steps

I just created a project based on Prism template in VS (with Unity, but it doesn't matter, same issue with DryIoC), and I only added in MainPage.cs:

        protected override void OnSizeAllocated(double width, double height)
        {
            base.OnSizeAllocated(width, height);

            Debug.WriteLine("OnSizeAllocated");
        }

Running the app shows "OnSizeAllocated" written twice in the logcat.  I ran the app multiple times to make sure it's not something which happens only sometimes.
If I don't use Prism (I changed `App` to derive from `Application` and commented all the Prism stuff), the message only gets written once to logcat.

Calling `OnSizeAllocated` twice doesn't seem to have any noticeable differences with performance, but this is a very simple app. It's weird `OnSizeAllocated` to get called just because of using Prism. I wonder if there are other implications. 
Before spending any time on this, I wanted to ask your opinion first.

**Comment by brianlagunas** [comment]
Prism has no influence on how many times this gets called.  All Prism does is create the page and adds it to the navigation stack.
