### ISSUE TITLE
Different Version of Unity for Unity.WPF

### ISSUE THREAD

**Issue by Corsin91** [PrismLibrary/Prism#1314]
First of all, sry for my bad englisch.
I will try to explain the problem as good as i can.

Please provide as much detail as possible (and feel free to remove unused properties):

### Package info

- Platform: WPF
- Prism version: 7.0.0.340-ci

### Repro steps

Please describe the issue/request in detail.
When installing Prism.Unity.WPF form MyGet, then Unity-Version 5.2.0 will be installed also.
But in the packages.config-File and also in the *.csproj File there is a dependency on 5.2.1.
Therefore when you use code from Prism.Unity.WPF that just exists in 5.2.1 but not in 5.2.0 an error occured like:
Assembly 'Prism.Unity.Wpf' with identity 'Prism.Unity.Wpf, Version=7.0.0.0, Culture=neutral, PublicKeyToken=40ee6c3a2184dc59' uses 'Unity.Abstractions, Version=2.2.1.0, Culture=neutral, PublicKeyToken=6d32ff45e0ccc69f' which has a higher version than referenced assembly 'Unity.Abstractions' with identity 'Unity.Abstractions, Version=2.2.0.0, Culture=neutral, PublicKeyToken=6d32ff45e0ccc69f'

Do i something wrong or need the *.nuspec file to be upgraded to 5.2.1 or the version in packages.config downgraded?

**Comment by brianlagunas** [comment]
The current CI builds on MyGet require Unity 5.2.1. The current Preview on NuGet requires Unity 5.2.0. Make sure you are using the correct version of Unity for the version of Prism you are using.

**Comment by Corsin91** [comment]
Thanks for your quick response. 
Yes i found that out too. I was just a bit confused why i need to update to Unity 5.2.1 manually when using the MyGet version.
But if this the intended behavior, than its ok
