### ISSUE TITLE
Loaded from a different path

### ISSUE THREAD

**Issue by alemputes** [PrismLibrary/Prism#1315]
### Package info

- Platform: Xamarin.Forms v2.5.0.121934
- Prism version: Prism.Autofac.Forms v7.0.0.336-pre
- Other version info: VS 2017 v15.5.2

### Repro steps
Created new project with the Xamarin.Forms + NetStandard.
Set iOS as start project and run, this will work just fine.
Now add Prism to all your projects, i used: v7.0.0.336-pre.

When running iOS i get following warnings:
(Note: removing Prism and rerunning the iOS project then no warnings are displayed.)

Why I am getting these warnings with Prism, maybe a bug?

`Severity	Code	Description	Project	File	Line	Suppression State
Warning		The assembly 'System.Security.Cryptography.Encoding.dll' was loaded from a different path than the provided path (provided path: /Users/aviloin/Library/Caches/Xamarin/mtbs/builds/App1.iOS/ddbdd4bacfb87fea248252f9473f6011/bin/iPhoneSimulator/Debug/System.Security.Cryptography.Encoding.dll, actual path: /Library/Frameworks/Xamarin.iOS.framework/Versions/11.6.1.2/lib/mono/Xamarin.iOS/Facades/System.Security.Cryptography.Encoding.dll).	App1.iOS
	
Warning		The assembly 'System.Runtime.InteropServices.RuntimeInformation.dll' was loaded from a different path than the provided path (provided path: /Users/aviloin/Library/Caches/Xamarin/mtbs/builds/App1.iOS/ddbdd4bacfb87fea248252f9473f6011/bin/iPhoneSimulator/Debug/System.Runtime.InteropServices.RuntimeInformation.dll, actual path: /Library/Frameworks/Xamarin.iOS.framework/Versions/11.6.1.2/lib/mono/Xamarin.iOS/Facades/System.Runtime.InteropServices.RuntimeInformation.dll).	App1.iOS			

Warning		The assembly 'System.Net.Http.dll' was loaded from a different path than the provided path (provided path: /Users/aviloin/Library/Caches/Xamarin/mtbs/builds/App1.iOS/ddbdd4bacfb87fea248252f9473f6011/bin/iPhoneSimulator/Debug/System.Net.Http.dll, actual path: /Library/Frameworks/Xamarin.iOS.framework/Versions/11.6.1.2/lib/mono/Xamarin.iOS/System.Net.Http.dll).	App1.iOS			

Warning		The assembly 'System.Security.Cryptography.X509Certificates.dll' was loaded from a different path than the provided path (provided path: /Users/aviloin/Library/Caches/Xamarin/mtbs/builds/App1.iOS/ddbdd4bacfb87fea248252f9473f6011/bin/iPhoneSimulator/Debug/System.Security.Cryptography.X509Certificates.dll, actual path: /Library/Frameworks/Xamarin.iOS.framework/Versions/11.6.1.2/lib/mono/Xamarin.iOS/Facades/System.Security.Cryptography.X509Certificates.dll).	App1.iOS			

Warning		The assembly 'System.Security.Cryptography.Algorithms.dll' was loaded from a different path than the provided path (provided path: /Users/aviloin/Library/Caches/Xamarin/mtbs/builds/App1.iOS/ddbdd4bacfb87fea248252f9473f6011/bin/iPhoneSimulator/Debug/System.Security.Cryptography.Algorithms.dll, actual path: /Library/Frameworks/Xamarin.iOS.framework/Versions/11.6.1.2/lib/mono/Xamarin.iOS/Facades/System.Security.Cryptography.Algorithms.dll).	App1.iOS			

Warning		The assembly 'System.IO.Compression.dll' was loaded from a different path than the provided path (provided path: /Users/aviloin/Library/Caches/Xamarin/mtbs/builds/App1.iOS/ddbdd4bacfb87fea248252f9473f6011/bin/iPhoneSimulator/Debug/System.IO.Compression.dll, actual path: /Library/Frameworks/Xamarin.iOS.framework/Versions/11.6.1.2/lib/mono/Xamarin.iOS/System.IO.Compression.dll).	App1.iOS			
`

**Comment by brianlagunas** [comment]
This has nothing to do with Prism.  I suggest asking on the Xamarin forums or using Google to help you with your issue.

**Comment by alemputes** [comment]
Ok thank you for fast respond.
