### ISSUE TITLE
Navigation init in Xamarin.Forms application

### ISSUE THREAD

**Issue by spatialguy** [PrismLibrary/Prism#1316]
### Package info

- Platform: Android, DryIoc
- Prism version: 
    - Prism.Forms: 7.0.0.336-pre
    - Prism.DryIoc.Forms: 7.0.0.336-pre
- Xamarin version (if applicable): 2.5.0.121934
- Windows 10 SDK version (if applicable): N/A
- Other version info: Using .NET standard library for shared code

### Repro steps

I am trying to use Prism in my XF app. I have two problems in the class that inherits from PrismApplication:

1. When trying to register NavigationPage for navigation in RegisterTypes method
`containerRegistry.Register<NavigationPage>();`
I get the following exception: `DryIoc.ContainerException: Unable to select single public constructor from implementation type Xamarin.Forms.NavigationPage`
I was able to workaround it using this code:

```
            var viewType = typeof(NavigationPage);
            string name = viewType.Name;
            PageNavigationRegistry.Register(name, viewType);

            if (container is DryIoc.Container c)
            {
                c.Register<NavigationPage>(made: Made.Of(FactoryMethod.ConstructorWithResolvableArguments));
            }
```
Is there a better way to do it?

2. Problem with initial navigation in OnInitialized method. When I try to use 
`NavigationService.NavigateAsync("NavigationPage/MainPage");`
the application throws exception:

```
            12-25 22:41:47.801 I/MonoDroid(19184): UNHANDLED EXCEPTION:
            12-25 22:41:47.826 I/MonoDroid(19184): System.NullReferenceException: Object reference not set to an instance of an object.
            12-25 22:41:47.827 I/MonoDroid(19184):   at Xamarin.Forms.Platform.Android.AppCompat.Platform.LayoutRootPage (Xamarin.Forms.Page page, System.Int32 width, System.Int32 height) [0x0000c] in D:\agent\_work\1\s\Xamarin.Forms.Platform.Android\AppCompat\Platform.cs:290 
            12-25 22:41:47.827 I/MonoDroid(19184):   at Xamarin.Forms.Platform.Android.AppCompat.Platform.Xamarin.Forms.Platform.Android.IPlatformLayout.OnLayout (System.Boolean changed, System.Int32 l, System.Int32 t, System.Int32 r, System.Int32 b) [0x00003] in D:\agent\_work\1\s\Xamarin.Forms.Platform.Android\AppCompat\Platform.cs:199 
            12-25 22:41:47.827 I/MonoDroid(19184):   at Xamarin.Forms.Platform.Android.PlatformRenderer.OnLayout (System.Boolean changed, System.Int32 l, System.Int32 t, System.Int32 r, System.Int32 b) [0x0000e] in D:\agent\_work\1\s\Xamarin.Forms.Platform.Android\PlatformRenderer.cs:73 
            12-25 22:41:47.827 I/MonoDroid(19184):   at Android.Views.ViewGroup.n_OnLayout_ZIIII (System.IntPtr jnienv, System.IntPtr native__this, System.Boolean changed, System.Int32 l, System.Int32 t, System.Int32 r, System.Int32 b) [0x00008] in <b45497bae7b44aa5b84d9841d4f92a20>:0 
           12-25 22:41:47.827 I/MonoDroid(19184):   at (wrapper dynamic-method) System.Object:d35f0d44-47f7-4ef8-83a8-792a7af72dcd (intptr,intptr,bool,int,int,int,int)
```
This seems to be related to the fact that the XF App MainPage property was not set and when XF needs it, it is null. When I set the MainPage to a temp page before invoking the navigation, 
`MainPage = new LoadingPage();`
the exception goes away but the navigation does not work, the app will not navigate to the MainPage, it will stay on the temp page.

The only way to get things working is to set MainPage manually (dont use navigation)
`MainPage = new NavigationPage(new MainPage());`
If i do this, the navigation in the rest of the app works correctly. But now I have a problem that the MainPage view model is not initialized because navigation events were not triggered.
Is this a known issue?

Attached is a sample project which can be used to reproduce this behavior.
[TestApp.zip](https://github.com/PrismLibrary/Prism/files/1586212/TestApp.zip)

**Comment by brianlagunas** [comment]
This has already been fixed and is available in the latest CI build.

**Comment by spatialguy** [comment]
Great, thanks! Do you know when these fixes will be available in Nuget packages?

**Comment by brianlagunas** [comment]
When we release v7 in early Jan

**Comment by brianlagunas** [comment]
By the way, the fix is already available in Nuget packages available on MyGet.

**Comment by spatialguy** [comment]
Just tested latest CI packages from MyGet and can confirm that both issues are resolved. Good job!!! Thank you!
