### ISSUE TITLE
Plan for Xamarin.Forms .Net Standard Support

### ISSUE THREAD

**Issue by goodstudies** [PrismLibrary/Prism#1317]
With latest Visual Studio update, Xamarin.Froms **PCL** project template is replaced with **.Net Standard** project type. So I am unable to add the **Prism.Forms** NuGet for this .Net Standard project type. Want to know, is there any way to do this?

### Package info

- Xamarin version

**Comment by AwsomeCode** [comment]
You can install Pre release version. https://github.com/PrismLibrary/Prism/releases/tag/7.0.0-pre5

**Comment by dansiegel** [comment]
This is not a Prism issue, PCL has been generally deprecated. Questions like this should be asked on StackOverflow.
