### ISSUE TITLE
Join our Slack Channel 

### ISSUE THREAD

**Issue by gregkuha60** [PrismLibrary/Prism#1318]
I was looking for some support and tried to join the SlackChannel but there is a application error. 
https://prismslack.herokuapp.com/
//Greg

**Comment by bartlannoeye** [comment]
There seems to be an issue indeed, while some other heroku slack invites apps are still running. @brianlagunas will have to check the logs.

**Comment by dansiegel** [comment]
There is no problem. It is a free instance on Heroku, which limits how much traffic we can get each month. It resets at the beginning of each month.
