### ISSUE TITLE
Scope dependencies and NavigationService.cs

### ISSUE THREAD

**Issue by dazinator** [PrismLibrary/Prism#1326]
﻿### Description

When my view model is constructed, I would like to create a scoped container, have my view model injected from that, and then once the screen is closed, dispose of that scope.

Are there relevant hooks for navigation that would allow me to achieve this?

Flow would be --> NavigateAsync() --> create a scoped container.CreateScoped() --> Resolve View Model from scoped container instead of top level container and display view as normal --> On View Close() dispose of the scoped container.

Thanks

**Comment by brianlagunas** [comment]
That seems like a lot of work for little reward.  I'm not 100% sure, but you can try a few things.  You would have to have a custom navigation service in which you override the CreatePage method to resolve using your scoped container.  Then you may need to override the ConfigureViewmodelLocator in PrismApplicationBase for resolving the ViewModel and it's associated navigation service.

All the source is available for you to study and try to figure it out.

God luck.
