### ISSUE TITLE
Regions attached to DependencyObject sometimes won't register

### ISSUE THREAD

**Issue by spsrbud** [PrismLibrary/Prism#1328]
﻿### Description
Regions attached to DependencyObject sometimes won't register if the GC runs before RegionManager.UpdateRegions() is called. I've attached an example solution project that demonstrates the issue. This is similar to issue #1321 
[PrismShell.zip](https://github.com/PrismLibrary/Prism/files/1624281/PrismShell.zip)

### Steps to Reproduce

1. Read the included ReadMe.txt file for steps to reproduce.

### Expected Behavior
The expected behavior is for the tab to display in the region. If the GC collects before the region is registered, then the tab will not display.

### Actual Behavior
The tab does not display if the GC collects before RegionManager.UpdateRegions() is called.

### Basic Information

- Platform: WPF
- Prism version: 6.3.0

### Proposed Solution
Please see the DelayedRegionCreationBehavior_Diff.html found in the .zip file for a solution.

**Comment by brianlagunas** [comment]
Thanks for the sample.  It really helped me understand the potential issue.  Although rare, it would cause some difficult to debug issues.

I think this is an acceptable addition.  My only feedback would be to call Track after we first checked if the DO was an FE or an FCE.  Only if those checks failed would we add it to the list.

If you prepare a PR for review we can get this added.

**Comment by brianlagunas** [comment]
Fixed
