### ISSUE TITLE
Intellisense not showing XML documentation in NuGet package

### ISSUE THREAD

**Issue by nphmuller** [PrismLibrary/Prism#133]
Steps to reproduce in Visual Studio 2015 (tested in both C# and VB):
-Start a new WPF Application project.
 -Add the Prism.Wpf v6.0.0 package through NuGet.
-Intellisense now won't give any xml documentation information in its popups, event though it does work with other NuGet packages.

Example: 
Type Prism.Commands.DelegateCommand and the popup only show this:
![intellisense-notworking-prism](https://cloud.githubusercontent.com/assets/3781551/9786580/76218e58-57bb-11e5-8ed6-b4ea1ff6105b.png)

Event though it does work with other NuGet packages:
![intellisense-working-propertychanged](https://cloud.githubusercontent.com/assets/3781551/9786608/adfc2694-57bb-11e5-821e-0dea3f1646e6.png)

**Comment by brianlagunas** [comment]
Interesting.  I'll look into this.  Thanks for reporting it.

**Comment by bartlannoeye** [comment]
Normally this is a setting to generate documentation in the project properties that has to be enabled. Once enabled, the build output will generate xml files, which have to be included in the NuGet package as well. I'm not behind my pc though to tell you where exactly under the project properties to look. I can check for it later today if you haven't found it yet.
PS: if you check in the nuspec files, I can even test it out and submit a PR wanted (if this setting actually is the fix).

**Comment by brianlagunas** [comment]
uuuuggghhhhh!!!  I just found that the "XML documentation file" was not checked in the Build tab of the projects.  I will need to rebuild all of the assemblies, and repackage and upload the new NuGet packages.

**Comment by bartlannoeye** [comment]
That's the one.

**Comment by brianlagunas** [comment]
Alright, all NuGet packages have been updated.  Check out v6.0.1 and let me know if the XML doc still don't show.

**Comment by nphmuller** [comment]
Working over here. Thanks for the fast fix!
