### ISSUE TITLE
missing debug info

### ISSUE THREAD

**Issue by bill2004158** [PrismLibrary/Prism#1332]
in this project,
https://github.com/PrismLibrary/Prism/blob/master/Source/Prism/Prism.csproj#L7
there is `<DebugType>pdbonly</DebugType>`

however, it missing in other project, such as:
https://github.com/PrismLibrary/Prism/blob/master/Source/Xamarin/Prism.Forms/Prism.Forms.csproj
https://github.com/PrismLibrary/Prism/blob/master/Source/Xamarin/Prism.Unity.Forms/Prism.Unity.Forms.csproj

can we add it for them too? otherwise, it will fail to load debugging symbols.

**Comment by brianlagunas** [comment]
Debugging symbols are loaded just fine while debugging Prism source.  Can you explain the scenario with more detail?  Could you provide a sample to demonstrate you risse more clearly?

**Comment by bill2004158** [comment]
why those project using different DebugType? one is pdbonly, others are default?

**Comment by toumir** [comment]
@bill2004158  do you mean, you cannot debug project ?

**Comment by bill2004158** [comment]
when I try to debug my project, and and try to step into prism dll,
prism.dll -> works fine.
Prism.Forms.dll and Prism.Unity.Forms.dll  -> cannot.

I download the source code, and added config `<DebugType>pdbonly</DebugType>` to file Prism.Forms.csproj, and Prism.Unity.Forms.csproj,
compile it, and replace the dll download from nuget.
then it works.

so I guess the reason is missing those config in that two project.
why used different config?

**Comment by toumir** [comment]
@bill2004158  Right click project, go to Build tab **->** advanced...**->** change debugging information from Pdb-only to Full, check if helps ?!

**Comment by bill2004158** [comment]
yes, exactly, if no problem, can you commit that changes to repository?

**Comment by dansiegel** [comment]
Any difference between projects in the debug output is an accidental artifact from before we consolidated common properties to the `Directory.build.props`. That said be sure you have added our MyGet feed to your symbols sources in Visual Studio for debugging. Our MyGet feed has the symbols packages which includes the full source that was compiled.
