### ISSUE TITLE
Xamarin.Forms navigating from tab to another tab

### ISSUE THREAD

**Issue by Arbalets** [PrismLibrary/Prism#1333]
﻿### Description
I have converted my project from Prism 6.3. Everything is working fine except navigating from TabbedPage tab to another tab in the same page.
I have a MasterDetail page from where I can navigate to all the TabbedPage tabs. 

In 6.3 I had there following:
```
NavigationPage/MyTabbedPage/TabPageA
NavigationPage/MyTabbedPage/TabPageB
NavigationPage/MyTabbedPage/TabPageC
```
I replaced them with:
```
NavigationPage/MyTabbedPage?selectedTab=TabPageA
NavigationPage/MyTabbedPage?selectedTab=TabPageB
NavigationPage/MyTabbedPage?selectedTab=TabPageC
```

### Steps to Reproduce
When navigation from another page everything works fine, but when already in some of the tabs and trying to navigate to another tab (from MasterDetail) nothing happens.

### Expected Behavior
Go to the selected tab.
### Actual Behavior
Nothing happens.
### Basic Information

- Version with issue: 7.0.0.362
- Last known good version: 6.3
- Xamarin.Forms version: 2.5.0.122203

**Comment by brianlagunas** [comment]
Navigating from one tab to another tab within the same TabbedPage is not something that Prism ever did intentionally.  If you would like this to be an official feature a sample repro app is required is order to be considered.

Thanks.

**Comment by brianlagunas** [comment]
Oh wait... I had to re-read that.  I see that you are navigating form a MasterDetailPage, not from within the actual TabbedPage.  This is actually a very interesting scenario.  Can you please provide a sample app that sets up the scenario that I can use to test the behavior out?

**Comment by Arbalets** [comment]
Sure, here you go: [https://github.com/Arbalets/TabNavigation](url)
I've included 6.3 sample as well, just for comparison.

**Comment by brianlagunas** [comment]
Done. You can test it out in the latest CI builds on MyGet, or wait for the SR release.

**Comment by Arbalets** [comment]
Thanks

**Comment by dazinator** [comment]
I just updated from 7.0.0.362 to 7.0.0.396 and wanted to confirm that it solved my problem, which was: When navigating to a tabbed page, the default content page (tab) would be displayed. however it's viewmodel was not activated by prism and so it's UI was not data bound. After the NuGet package update to latest version it worked.

**Comment by dazinator** [comment]
Turns out I spoke to soon. I think perhaps the fix wasn't in 7.0.0.396. I'll await the next release!

**Comment by brianlagunas** [comment]
The fix is not on Nuget, it's in our CI feed.

**Comment by dazinator** [comment]
Ok great, I have grabbed the CI package, working as expected now, thanks

**Comment by rboyette** [comment]
@brianlagunas  any workarounds for this or upgrade our Prism packages?
