### ISSUE TITLE
Autofac IContainer - can this be an ILifetimeScope instead?

### ISSUE THREAD

**Issue by dazinator** [PrismLibrary/Prism#1335]
﻿### Description

I am registering EF Core DbContext into my container. However it is seemingly not designed to be used directly from the main container. It requires that a scope() is created for it to be used in first otherwise there are issues https://github.com/aspnet/EntityFrameworkCore/issues/10692

However autofac only seems to allow configuring the top level `IContainer` which it uses to set `App.Container` - it then resolves everything from that top level container, giving you no opportunity to create a scoped version first. 

What I would like to do is, once the main container is configured, I would like to create a scoped version of it, and have all dependencies resolved from that scoped version instead. This should allow EF Core to work correctly. However I cannot set `App.Container` to an ILifetimeScop. I.e:

```

        protected override void OnInitialized()
        {         
            Container = Container.BeginLifetimeScope();
            InitializeComponent();     
        }
```

If you could do this, it should allow dependencies that require a "scoped" container to function.

What do you think?

**Comment by dazinator** [comment]
Maybe I can take advantage of the new container abstraction model: https://github.com/PrismLibrary/Prism/commits/57cb55cfdd5f718d4bfc01282730e68bd06711ec/Source/Xamarin/Prism.Autofac.Forms/AutofacContainerExtension.cs

I am thinking If I derive my own ContainerExtension, that stores a LifeTimeScope() - and then override the resolve methods to resolve from that stored scope instead of the main IContainer - perhaps that would work..

**Comment by brianlagunas** [comment]
Honestly, I'm not sure I would be storing the DB context in the container, but rather a service that manages that stuff and register the service with the container.

You are more than welcome to extend Prism to meet your desired outcome.  Good luck.

**Comment by dazinator** [comment]
Thanks.

**Comment by dansiegel** [comment]
@dazinator the `App.Container` is actually a Prism ContainerExtension. You will need to call `GetContainer` to get the Autofac `IContainer` which will then allow you to call `BeginLifetimeScope`. If this doesn't work for you because you cannot reset the Container instance then you would need to implement a custom IAutofacContainerExtension, you can see how the base extension is [here](https://github.com/PrismLibrary/Prism/blob/master/Source/Xamarin/Prism.Autofac.Forms/AutofacContainerExtension.cs)

**Comment by dazinator** [comment]
> then you would need to implement a custom IAutofacContainerExtension, you can see how the base extension is here

That sounds like exactly what I have in mind at this point. I'll derive my own, and override the resolve() methods to resolve from my lifetime scope internally. Thanks for the pointer
