### ISSUE TITLE
Navigate to NavigationPage throws exception

### ISSUE THREAD

**Issue by AlonikiX** [PrismLibrary/Prism#1344]
﻿### Description
I updated Prism to 7.0.0.395-ci, and try to navigate to a navigation page as what I did in the old version.
![ce264fb8-71ef-4d9d-8d39-b5071f6857d2](https://user-images.githubusercontent.com/11833091/35204015-76d897c4-ff7f-11e7-80e2-e5180946d937.png)
But it throws an exception.
![9dd7458b-23d7-4293-8c3c-8c15aea75ba7](https://user-images.githubusercontent.com/11833091/35204055-b91c8fbe-ff7f-11e7-8bc8-c784b3430386.png)

Is any documents & tutorials for prism 7 available?

**Comment by dansiegel** [comment]
NavigationPages should work fine in DryIoc in Prism 7... I can only make guesses here as you haven't included a repo, but from your screenshots I don't see anywhere, where NavigationPage has been registered for Navigation.

**Comment by AlonikiX** [comment]
Oh...you are right, what a stupid mistake I made. Thanks
