### ISSUE TITLE
OnNavigatedTo not called in masterdetailpage

### ISSUE THREAD

**Issue by simon25608** [PrismLibrary/Prism#1345]
### Steps to Reproduce
I am using a masterpage to display a list, when I navigate in detail the INavigationAware methods are invoked and the backward arrow is displayed, but when I press the backward arrow, the OnNavigatedFrom method of detail is not invoked and neither is the OnNavigatedTo method of the main list.  Is that normal? In previous versions if invoked

### Basic Information

- Prism version: 7.0.0.362
- Xamarin.Forms version: 2.5.0.122203
- IDE: Visual studio 2017

**Comment by brianlagunas** [comment]
I do not understand your issue.  Please create a simple app that can reproduce your issue as that will help clarify any language barriers.  Also, if you could please try to be more specific. For example ( I don't know what "backward date" means.

**Comment by simon25608** [comment]
Sorry, the corrector changed the word arrow by date.

By creating the example project I have realized that it works as expected, I have to debug what happens in my app because I use several plugins that can alter behavior.
