### ISSUE TITLE
Add ContainerProvider for resolving dependencies in XAML

### ISSUE THREAD

**Issue by dansiegel** [PrismLibrary/Prism#1347]
﻿### Description

It's very common practice to declare types in XAML such as a TypeConverter which may then be added to a ResourceDictionary. By adding this type in XAML we must ensure that the type will work with a default constructor. This generally results in either making code much more sloppy or weird work arounds when we need services from the Container. By adding a ContainerProvider similar to Xamarin's `OnPlatform<T>` we can provide a type in XAML and allow the Container to resolve dependencies for us. 

### Expected Behavior

```cs
public class MyTypeConverter : IValueConverter
{
    private ILoggerFacade _logger { get; }
    public MyTypeConverter(ILoggerFacade logger)
    {
        _logger = logger;
    }
}
```

```xml
<ContentPage xmlns:prism="clr-namespace:Prism.Ioc;assembly=Prism.Forms">
    <ContentPage.Resources>
        <ResourceDictionary>
            <prism:ContainerProvider x:TypeArguments="MyTypeConverter" x:Key="myTypeConverter" />
        </ResourceDictionary>
    <ContentPage.Resources>
</ContentPage>
```

**Comment by brianlagunas** [comment]
Great addition!

**Comment by saifxx** [comment]
How can I do this in Prism.WPF?

**Comment by brianlagunas** [comment]
@saifxx This is not currently available in WPF.  However, you can take the code and adapt it for WPF.
