### ISSUE TITLE
Tag releases

### ISSUE THREAD

**Issue by frogger3d** [PrismLibrary/Prism#135]
I noticed neither the 6.0.0 and 6.0.1 release are tagged. I've not switched my projects yet, but I can imagine wanting to go back and see what the actual source is of a specific version in the repository.

**Comment by briannoyes** [comment]
Good point. Thanks for reminding us. Didn't bother for 6.0.0 since we would not have called that a release if we realized we left out the doc comments. :)
6.0.1 is now tagged a release.
