### ISSUE TITLE
NavigationFrom not called when navigate to different Hamburger Menu Page

### ISSUE THREAD

**Issue by SeRgI1982** [PrismLibrary/Prism#1353]
﻿### Description
NavigationFrom is not called when navigating to a different Page related with menu item in HamburgerMenu (MasterDetail scenario).

### Steps to Reproduce
All pages have ViewModels with INavigationAware implementation.
All ViewModels call OnNavigatedTo method when user navigates to them. 

1. Create MasterDetail Page with MenuPage as a Master.
   MenuPage has two buttons:
   - btn1 - navigates to PageA (NavigationService.NavigateAsync("Navigation/PageA")), 
   - btn2 - navigates to PageB (NavigationService.NavigateAsync("Navigation/PageB")).

2. PageA is a default page (after openning the app, user landing on PageA)

3. Open MenuPage and hit btn2

### Expected Behavior
PageAViewModel.OnNavigatedFrom  - should be executed,
PageBViewModel.OnNavigatedTo  - should be executed.

### Actual Behavior
**PageAViewModel.OnNavigatedFrom  - is not executed,**
PageBViewModel.OnNavigatedTo  - is executed.

### Basic Information

- Version with issue: 7.0.0.336-pre
- Last known good version:
- Xamarin.Forms version: 2.5.0.121934
- IDE: VS2017

**Comment by brianlagunas** [comment]
Please provide a sample that reproduces this issue.

**Comment by SeRgI1982** [comment]
Just open and update to the latest version of Prism and Xamarin Forms a HamburgerMenu Prism Sample. Attach override OnNavigatedFrom and attach debugger. When you switch between pages (A, B, C), OnNavigatedTo is called always, OnNavigatedFrom - never.

Updated sample in the attachment

[HamburgerMenu.zip](https://github.com/PrismLibrary/Prism/files/1681695/HamburgerMenu.zip)

**Comment by brianlagunas** [comment]
Verified. Thanks for submitting this.

**Comment by SeRgI1982** [comment]
Super. Big thanks for this fix.
Can you tell me in which pre-release version it will be available ?

**Comment by brianlagunas** [comment]
You can get it now in the latest CI builds on MyGet.  We have some pretty large efforts going on right now regarding aligning Prism across platforms, so I don't have a timeframe for the next preview.

**Comment by SeRgI1982** [comment]
You surprised me with this MyGet. I used to not looking into this 'Packages source'. For most cases, nuget.org is enough. I would love to work with company where they have at least in 50% organized development process like you have for Prism. Congratulations.

**Comment by IngweLand** [comment]
Still does not work. Checked with 7.1.0.123-pre (it supposed to be fixed according to it's release notes). Checked on Android only. Here is the sample project.
https://github.com/IngweLand/App1

**Comment by brianlagunas** [comment]
It works just fine. You aren't setting the useModalNavigation parameter to true.

**Comment by IngweLand** [comment]
Why should I set useModalNavigation parameter to true - I am not creating a modal page.
However, I think my mistake was different. I was changing pages with "absolute" style, like this:
initial set:
`NavigationService.NavigateAsync($"{nameof(PrismMasterDetailPage1)}/{nameof(NavigationPage)}/{nameof(ViewA)}");`
and to change a page i did:
`NavigationService.NavigateAsync($"{nameof(PrismMasterDetailPage1)}/{nameof(NavigationPage)}/{nameof(ViewB)}");`

However, when I changed second line to following, OnNavigationFrom started to be called:
`NavigationService.NavigateAsync($"{nameof(NavigationPage)}/{nameof(ViewB)}");`

**Comment by brianlagunas** [comment]
Because you can't set the Detail of a MasterDetail to another MasterDetailPage. Therefore you must push it modally.  Looks like you have it figured out.

**Comment by aneti9862** [comment]
I have similar problem with my app. When I'm on BasePage and I want to navigate from MasterDetailPage to some page (ViewA or ViewB), the OnNavigatedFrom method  from BasePage not called. I tried to set useModalNavigation to true, but still didn't work.

So, I created test app. @brianlagunas , I will be gratefull for your help.
https://github.com/aneti9862/XamarinForms

**Comment by bwenninger** [comment]
@SeRgI1982 I pulled down your HamburgerMenu.zip file and updated the Prism libraries to version 7.1.0.431 and tried it out on iOS.  If I switch from ViewA to ViewB the OnNavigatedFrom method is called on the MainPage but not on ViewA.  Is this how it should behave or should OnNavigatedFrom be called on ViewA?

**Comment by angelru** [comment]
@bwenninger @aneti9862 the same issue... `https://github.com/PrismLibrary/Prism/issues/1751`
