### ISSUE TITLE
INavigationAware methods are not called on children of a CarouselPage

### ISSUE THREAD

**Issue by fms10** [PrismLibrary/Prism#1354]
### Description

The methods OnNavigatingTo, OnNavigatedTo and OnNavigatedFrom of the Prism.Forms PageNavigationService do not call the corresponding INavigationAware method on the current child of a CarouselPage. This is only implemented for TabbedPages so far.

### Basic Information

- Version with issue: 7.0.0.396
- Last known good version: 6.3.0
- Xamarin.Forms version: 2.5.0.122203
- IDE: VS2017

**Comment by brianlagunas** [comment]
Are you expecting these methods to fire when you change pages within the CarouselPage?  Or, are these not firing when navigating away from the CarouselPage to another Page in the navigation stack?

Also, I thought CarouselPage is a dead page and Xamarin was working on a CarouselView instead :)

**Comment by fms10** [comment]
I'm expecting these methods to fire on the child page at least when navigating to a CarouselPage with an Uri like, e.g. "/LoginContainer?selectedTab=Login" where "LoginContainer" is a CarouselPage and "Login" is a ContentPage within the CarouselPage. With version 7, the methods are called on the LoginContainer but not on the Login page.

There is a lot of code in Prism.Forms' navigation service to handle CarouselPages. I therefore got the impression, that CarouselPages are explicitly supported, even if they might be obsoleted eventually.

**Comment by brianlagunas** [comment]
Thanks for the clarification. Should be an easy fix.

I don't see many people using the CarouselPage, so I was just curious :)

**Comment by brianlagunas** [comment]
fixed
