### ISSUE TITLE
Move INavigationService from Prism.Forms to Prism.Core

### ISSUE THREAD

**Issue by mfe-** [PrismLibrary/Prism#1359]
Move the platform specific INavigationService  to Prism.Core

### Steps to Reproduce

1. Create a ViewModel in a PCL or .NETStandard Project 
2. If you want use your ViewModels in your WPF and XF/UWP Project you need to create an independent NavigationService interface.
3. Otherwise your ViewModel Project dependents on Prism.Forms, which you don't want in a (for example) WPF Solution.

### Expected Behavior
No platform specific dependencies for the INavigationService interface. It should be in Prism.Core.

### Actual Behavior
Every platfrom owns there own INavigationService interface.
### Basic Information

- Version with issue: 7
- Last known good version: 6
- Xamarin.Forms version:  -
- IDE: -

### Workaround

Create your own Navigation interface and use this in your ViewModel project. On the specific Platform you can glue your  Navigation interface with the navigation service from prism. 

In Prism 6 we had the ability to override `CreateNavigation()` which made it easier to implement the workaround then in Prism 7.

**Comment by dansiegel** [comment]
@mfe- INavigationService has already been moved to Prism.Core as part of our unification efforts. At this time we are specifically excluding it from the net45 binary so it will not be available in WPF.

**Comment by brianlagunas** [comment]
Also in Prism 7, you use the container to register your custom nav service instead of overriding a method.
