### ISSUE TITLE
Indexer on NavigationParameters has changed

### ISSUE THREAD

**Issue by frogger3d** [PrismLibrary/Prism#136]
NavigationParameters["parameterName"] in Prims 5 would return null for missing parameters while in Prism 6 it throws an exception. This should probably be listed in the breaking changes along with mentioning that it now is a Dictionary instead of a List.

**Comment by brianlagunas** [comment]
This is listed in the release notes https://github.com/PrismLibrary/Prism/wiki/Release-Notes---6.0.0

**Comment by frogger3d** [comment]
Sorry, I had not noticed. On that note you may wish to remove the following item from the release notes:

> Added RequestNavigateAsync methods to region navigation

**Comment by brianlagunas** [comment]
Good catch.  We were going to do that, but didn't get it in.  I'll remove it.

**Comment by brianlagunas** [comment]
We actually just converted this back to the original API.  It was too large of a breaking change for no real benefit.
