### ISSUE TITLE
ServiceLocator usage in app is overriding Prism ServiceLocator

### ISSUE THREAD

**Issue by dkofoed** [PrismLibrary/Prism#1360]
We have a component that was developed to use the Prism framework and it contains it's own shell, bootstrapper, etc.

This component was consumed inside a separate application which happens to make use of the ServiceLocator class for it's own purposes.

What we realized is that the consuming application's use of the ServiceLocator is overriding Prism's use of the ServiceLocator in the "embedded" component. Once the ServiceLocator is accessed at least once in the consuming app, all the lifetime controlled instances in Prism are removed (such as the RegionAdapterMappings, etc) and the embedded component no longer functions correctly.

This is presumably because ServiceLocator is a singleton.

Is there any workaround for this scenario that we may be missing? It seems that the only resolutions are:

1) Remove Prism implementation from the embedded component (probably not practical) OR
2) Remove/change the ServiceLocator implementation in the consuming app (may not be feasible)
3) Other?

- Version with issue: 6.2.0.0

**Comment by brianlagunas** [comment]
You need to replace Prism's ServiceLocator with yours

https://github.com/PrismLibrary/Prism/blob/master/Source/Wpf/Prism.Wpf/Bootstrapper.cs#L203

**Comment by vamsi27** [comment]
The consuming application is already replacing PRISM's ServiceLocator.Current with its own container, that's the reason we are missing RegionAdapterMappings once we try to navigate to any view in the embedded component.

**Comment by vamsi27** [comment]
Unfortunately, it's not the same. The consuming app's container doesn't even implement IUnityContainer. They have their own implementation. We just wanted to know if there are any chances of PRISM moving away from using ServiceLocator in the future.

**Comment by brianlagunas** [comment]
Well, yes and no.  We are in the process of using an abstraction around any DI framework in our new Ioc namespace.  So the use of the actual ServiceLocator class will most likely be removed, but we will still need to use an internal class (which will be the service locator pattern) that gives us access to our abstraction API to resolve objects within the framework.

**Comment by brianlagunas** [comment]
This is what we are moving to:  https://github.com/PrismLibrary/Prism/tree/master/Source/Prism/Ioc

**Comment by vamsi27** [comment]
Which release would this be in?

**Comment by brianlagunas** [comment]
It will be in v7 for WPF, which has no release date.
