### ISSUE TITLE
OnNavigatedTo() not being triggered.

### ISSUE THREAD

**Issue by MarkConnelly94** [PrismLibrary/Prism#1361]
Hi,

My OnNavigatedTo method is not being triggered on any of my VMs. This is happening when I implement navigation to my DeviceDetailsVM. Beforehand, I was able to see that it is being triggered on my GlasgowDeviceListVM through the use of breakpoints.

### Steps to Reproduce

1. Breakpoint the OnNavigatedto() methods.
2. Navigate to DeviceDetails Page
3. Does not hit the breakpoint.

Expected Behaviour: Hits the breakpoint on Nav method.
Actual Behaviour: Does not hit the breakpoint.

- Version with issue:  Prism v7.0
- Last known good version:
- Xamarin.Forms version: Latest
- IDE: Visual Studio 2017
[RegiApp.zip](https://github.com/PrismLibrary/Prism/files/1704034/RegiApp.zip)

Thanks,

Mark

**Comment by brianlagunas** [comment]
Your first problem is that you aren't using the navigation service when the app starts. So the INavigationAware methods will never fire.  You're doing this: 

`this. MainPage = new RegiApp.Views.GlasgowDeviceList();`

When you should be doing this:

`NavigationService.NavigateAsync("GlasgowDeviceList");`

Your next problem is that you are throwing exceptions in all of the INavigationAware methods. You need to remove all the `throw new NotImplementedException();` from your implementation. As yu know, if you throw an exception, you basically halt all other processing of your code (in this case Prism's code).

**Comment by brianlagunas** [comment]
By the way, you need to remove the Prism.Unity 6.3 nuget package. That's for WPF :)
