### ISSUE TITLE
Question about unit testing View Models and setting NavigationMode

### ISSUE THREAD

**Issue by Andrew-Neale** [PrismLibrary/Prism#1363]
Hi,

In Forms.Prism V7 how do you set the navigationMode  when calling OnNavigatedTo in your unit tests?  Since now the __NavigationMode is now  in InternalParameters?  In my tests I want to be able to specify If I'm navigating back or new.

I used to be able to do:

```
// Arrange
 var navParams = new NavigationParameters();     
 navParams.Add("__NavigationMode", NavigationMode.New);

/Act
ViewModel.OnNavigatedTo(navParams);

....
```
This no longer works as prism does not set __NavigationMode to a collection I can access in myViewModel. From my view model calling GetNavigationMode() only appears to look at InternalParameters

Ideally, I don't want to add a reference to Xamarin Forms in my unit tests project as I'm testing my ViewModels only.

Cheers.

**Comment by brianlagunas** [comment]
The NavigationMode is not a property that should be set by end-users.  It is meant for internal uses only.  However, if you must do this you can just call methods off of the NavigationParameters class. They are just hidden from intellisense

https://github.com/PrismLibrary/Prism/blob/7c96c9ab89210290ac8f13686077a03a4c45dc29/Source/Xamarin/Prism.Forms/Navigation/NavigationParameters.cs#L25

By the way, this will be changing in an upcoming release, so your code will break and you will have to refactor to explicitly cast an interface.

**Comment by Andrew-Neale** [comment]
OK, Brilliant, cheers.
