### ISSUE TITLE
Is it possible to unsubscribe from event handlers in nested / sub views?

### ISSUE THREAD

**Issue by JMcLauchlanSQ** [PrismLibrary/Prism#1364]
I am unsure if this is a nieve question, but I have done a fair amount of searching and haven't been able to work it out.

Basically I have a login page that roughly looks like this, as you can see there is a subview "CredentialsView":
```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:views="Namespace.App.Views.CredentialsView"
             xmlns:prism="clr-namespace:Prism.Mvvm;assembly=Prism.Forms"
             x:Class="Namespace.App.Views.LoginPage"             
             prism:ViewModelLocator.AutowireViewModel="True">
    <ContentPage.Content>
        <StackLayout Padding="10, 40, 10, 10">
            <views:CredentialsView />
        </StackLayout>
    </ContentPage.Content>
</ContentPage>
```

and I have a separate CredentialsView for credential entry, roughly:
```
<?xml version="1.0" encoding="UTF-8"?>
<ContentView xmlns="http://xamarin.com/schemas/2014/forms" 
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:prism="clr-namespace:Prism.Mvvm;assembly=Prism.Forms"
             prism:ViewModelLocator.AutowireViewModel="True"
             x:Class="Namespace.App.Views.CredentialsView">
...
```

In my nested / sub view I want to be able to subscribe to events on the MessagingCenter when the parent view (and therefore sub view) is created, then unsubscribe when they are removed, however I am unsure how I could do this. I can easily subscribe in the CredentialsViewModel constructor, however unsubscribing could be a problem. Possibly I do not need to unsubscribe? - I have assumed this is necessary.

I have considered approaches such as the one described [here](https://github.com/PrismLibrary/Prism/issues/563) and [here](https://stackoverflow.com/questions/43494527/object-disposing-in-xamarin-forms) where they are implementing OnNavigatedFrom and OnNavigatedTo on the viewmodel, this makes sense for a parent view model, but I am unsure how to apply this to all child views and therefore child viewmodels also. The primary issue here is that these overridable methods are available in ContentPage but not ContentView.

I also looked into using OnParentSet (described [here](https://stackoverflow.com/questions/43494527/object-disposing-in-xamarin-forms)) however that also did not describe how to get this working with sub views, and I was a bit unsure as to when I should be actually subscribing to events in the child view (aka when is the BindingContext available? in the constructor, when Parent != nul, ?).

**Comment by brianlagunas** [comment]
Questions like this a better suited for SO.  However, you can do anything you want, it's just code.  My first thought would be to have your page implement IDestructible and then traverse your element tree and do what you need to there.

**Comment by brianlagunas** [comment]
Also, you don't have to unsubscribe from the IEventAggregator. It uses weak references and manages the memory allocation for your events automatically.

**Comment by JMcLauchlanSQ** [comment]
Will dig into that, then try SO, thanks Brian.

**Comment by JMcLauchlanSQ** [comment]
I am trying to unsub from a MessagingCenter subscribe, so I assume this does not use weak references?

**Comment by brianlagunas** [comment]
Oh MessagingCenter is a peace of crap.  Yeah, that's a major source of memory leaks. You should be using the IEventAggregator instead :)
