### ISSUE TITLE
Question: INavigationServiceExtensions.NavigateAsync not testable

### ISSUE THREAD

**Issue by jBijsterboschNL** [PrismLibrary/Prism#1365]
### Description
Why is there a INavigationServiceExtensions with a NavigateAsync(name, parameters, useModalNavigation, animated) method? This way I'm unable to verify it's usage in a unit test because it is an extension. Why is this not directly implemented on the PageNavigationService?

### Steps to Reproduce
1. Create a unit test.
2. Mock the INavigationService.
3. Try to Verify NavigateAsync(this INavigationService navigationService, string name, NavigationParameters parameters = null, bool? useModalNavigation = null, bool animated = true)

### Expected Behavior
Successful unit test

### Actual Behavior
Unit test failed with message: System.NotSupportedException : Invalid verify on an extension method: m => m.NavigateAsync(It.IsAny<String>(), null, (Nullable<Boolean>)False, True)

**Comment by brianlagunas** [comment]
INavigationSerrvice is being used across platforms, which is why there are extensions for platform specific scenarios.  You can mock it and you can test it.  For now you have to have your mock derive from the prism implementation and then override the methods you are testing.  This has been improved in the latest CI build to where this is no longer necessary and you can have your own POCO class implement the required interfaces.

**Comment by DavidStrickland0** [comment]
Forced implementations of the INavigationService calling into an Internal only Interface Im afraid is code stink. Its basically bypassing the one rule of Interface Extension that being that an Interface Extension can only access the interfaces properties and methods the interface exposes. Expose the internal Interface so it can be Mocked or implement a seperate Contract to use with Forms that inherits from the INavigationService.
Inheriting from the Prism implementation isnt a Mock. You dont "Mock" concretes you "Mock" Interfaces.

**Comment by brianlagunas** [comment]
We cannot remove the INavigationServiceExtensions. This is what gives us the ability to share our INavService across platforms yet still give us the ability to perform platform specific navigation.  The one thing I would be willing to do it rename INavigateInternal and make it public.

**Comment by brianlagunas** [comment]
We are in the process of aligning this implementation, which is why UWP has not been released yet.

**Comment by chrswgnr** [comment]
Great, will check it again when there is a preview nuget version of those changes. For now I changed the calls in my viewmodels to only use the signature provided by INavigationService, since those are testable.
