### ISSUE TITLE
ModuleInitializer can not be resolved

### ISSUE THREAD

**Issue by Corsin91** [PrismLibrary/Prism#1368]
﻿### Description
ModuleInitializer can not be resolved because of missing type mapping 
The interface IContainerExtension can not be constructed.

### Steps to Reproduce

1. Install Prism.Unity 7.0.0.423-ci
2. Use PrismApplication
3. Use ModuleManager (or ModuleInitializer) as constructor parameter (or simply resolve it form Container)

### Expected Behavior
Should resolve instance correctly

### Actual Behavior
Throws ResolutionFailedException while resolving IModuleInitializer

### Basic Information

- Version with issue:  Prism.Unity 7.0.0.423-ci
- Last known good version: Dont know the version, but i think issue is caused from #1339 
- IDE: Visual Studio 2015

﻿### Reproduction Link

[ExampleModuleManager.zip](https://github.com/PrismLibrary/Prism/files/1733525/ExampleModuleManager.zip)

**Comment by brianlagunas** [comment]
Yeah.... this is a known issue and WPF v7.0 is still being worked on and is not stable as this time.

If you wated to keep playing around with the latest CI build just add this to your App.xaml.cs

```
        protected override void RegisterRequiredTypes(IContainerRegistry containerRegistry)
        {
            containerRegistry.RegisterInstance((IContainerExtension)Container);
            base.RegisterRequiredTypes(containerRegistry);
        }
```

This will fix it.
