### ISSUE TITLE
Add base implementation of INotifyDataErrorInfo (BindableDataErrorNotifier)

### ISSUE THREAD

**Issue by mdelura** [PrismLibrary/Prism#1369]
In Prism.Mvvm there is a base implementation of `INotifyPropertyChanged `interface (`BindableBase `abstract class), but there is no base class for `INotifyDataErrorInfo`.
Following the steps in the [documentation](http://prismlibrary.github.io/docs/wpf/Implementing-MVVM.html#implementing-inotifydataerrorinfo) I have created a base abstract class which I called `BindableDataErrorNotifierBase`.

The implementation consists of:
- the class derives from `BindableBase`
- `private ErrorsContainer<ValidationResult> _errorsContainer` for keeping track of errors
- abstract protected method `IEnumerable<ValidationResult> GetValidationResults(string propertyName)` - this method needs to be implemented in a derived class as a mean to provide result of validation (when called) for the specified property
- additional helper methods that extend similar methods from BinbableBase: `RaisePropertyChangedAndValidate`, `SetPropertyAndValidate<T>`

I'd like to contribute that to Prism, please let me know if it's a valuable input and if I should create a pull request.

### Reproduction Link
Not applicable I believe...

**Comment by brianlagunas** [comment]
Thank you for your effort and willingness to contribute to Prism.  Unfortunately, we do not want to start including concepts such as validation into the Prism Library at this time.  The documentation is there to help guide developers on how to start implementing validation to meet their needs, but it's not something we will be including.  Thank you
