### ISSUE TITLE
Property injection in prism for xamarin forms

### ISSUE THREAD

**Issue by mo-kml** [PrismLibrary/Prism#1371]
I wanna Inject INavigationService as a property in my BaseViewModel 
I've tried AutoWired my BaseViewModel in RegisterType like so
`            builder.RegisterType<BaseViewModel>().InstancePerLifetimeScope().PropertiesAutowired();
`
but it didnt work
what should i do?

**Comment by brianlagunas** [comment]
Property injection is not supported with the INavigationService.

**Comment by georgethms10** [comment]
Can we use property injection for other classes. Is there any example of property injection using prism?

**Comment by brianlagunas** [comment]
Yes, but that is not a topic covered by prism as that has nothing to do with Prism. That is a function of your container of choice.
