### ISSUE TITLE
CarouselPage / INavigationAware inconsistencies

### ISSUE THREAD

**Issue by Dresel** [PrismLibrary/Prism#1372]
Hi, thanks for the effort you put into this library.

I'm currently playing around with CarouselPage and the INavigationAware interface with the latest CI package and think I'm experiencing some inconsistencies.

Somehow all Carousel pages trigger an initial `OnNavigatingTo` (I would expect that only for index 0), and after navigating to a different page when pressing back only the Carousel Item Page gets an `OnNavigatedTo` callback. `OnNavigatingTo` is left out and the Main page holding the Carousel items get no callback at all.

### Steps to Reproduce

1. Change MainPage to CarouselPage, add a SecondPage
2. Start
3. Navigate to Second Page
4. Navigate back
5. Check log

### Expected Behavior

What I would expect:

Start

MainPageViewModel: OnNavigatingTo
CarouselItemViewModel: OnNavigatingTo
MainPageViewModel: OnNavigatedTo
CarouselItemViewModel: OnNavigatedTo

Press on Navigate

SecondPageViewModel: OnNavigatingTo
MainPageViewModel: OnNavigatedFrom
CarouselItemViewModel: OnNavigatedFrom
SecondPageViewModel: OnNavigatedTo

Press Back

MainPageViewModel: OnNavigatingTo
CarouselItemViewModel: OnNavigatingTo
SecondPageViewModel: OnNavigatedFrom
MainPageViewModel: OnNavigatedTo
CarouselItemViewModel: OnNavigatedTo

### Actual Behavior

Start

MainPageViewModel: OnNavigatingTo
CarouselItemViewModel: OnNavigatingTo
**CarouselItemViewModel: OnNavigatingTo**
**CarouselItemViewModel: OnNavigatingTo**
MainPageViewModel: OnNavigatedTo
CarouselItemViewModel: OnNavigatedTo

Press on Navigate

SecondPageViewModel: OnNavigatingTo
MainPageViewModel: OnNavigatedFrom
CarouselItemViewModel: OnNavigatedFrom
SecondPageViewModel: OnNavigatedTo

Press Back

~~MainPageViewModel: OnNavigatingTo~~
~~CarouselItemViewModel: OnNavigatingTo~~
SecondPageViewModel: OnNavigatedFrom
~~MainPageViewModel: OnNavigatedTo~~
CarouselItemViewModel: OnNavigatedTo

### Basic Information

- Version with issue: 7.0.0.423-ci
- Last known good version: -
- Xamarin.Forms version: 2.5.0.122203
- IDE: VS 2017 Preview

### Reproduction Link

[Github Repo](https://github.com/Dresel/PrismRepo)

**Comment by brianlagunas** [comment]
This is by design. OnNavigatingTo cannot be called when the hardware/software buttons are pressed, only when calling the GoBackAsync method can we execute the OnNavigatingTo methods.

**Comment by dansiegel** [comment]
@Dresel remember that CarouselPage and TabbedPage are both MultiPage's which as the name would suggest are containers for other pages... the navigation from one to the other is outside of the context of the NavigationService. In Prism 7 we added support for calling OnNavigatingTo on all of the children of these Page types so that those children could receive the initialization context that would be passed in the NavigationParameters to the Parent.

**Comment by Dresel** [comment]
Thanks for your answers, guess you are not explaining this the first time. I was really looking for documentation, but everything I found was only touching the surface but not dealing with these kind of details. Guess the best way to gather information / documentation would be reading release notes, pull requests and issue discussions?

So back to the issue and to sum up:

- OnNavigatingTo is never called when pressing hardware/software buttons
- OnNavigatingTo is called for all children of a MultiPage type, but only for the initial creation, not when navigating back to these kind of pages (wether hardware/software or executing `GoBackAsync`), there it would only be called for the specific child page which is currently active
- OnNavigatingTo/OnNavigatedTo is called for MultiPage types only during initial creation, not when navigating back to these kind of pages, it is only called for the specific child page which is currently active
- Navigating within a MultiPage type (e.g. swiping through the CarouselPage) is outside of the context of the NavigationService, so OnNavigatingTo/OnNavigatedTo will/can never be called

Right?

So where would you put code that should always be called when navigating to a MultiPage or within a MultiPage type (like reloading data)? I was loading the data within OnNavigatedTo in the MultiPage type for all children, but this would not be called when navigating back to MultiPages. When loading directly within OnNavigatedTo in the child page, it would not be called when navigating (swiping) within the MultiPage.

I ended up loading the data within the MultiPage viewmodel and throwing an event in the OnNavigatedTo of the child page ViewModel (which the parent / MultiPage ViewModel  is attached to) so that the MultiPage ViewModel can react when navigating back to an MultiPage type.

I was also thinking of reacting to OnCurrentPageChanged for the MultiPage and manually calling INavigationAware functions to ensure almost consistent behaviour, but I don't know if that makes sense?

What do you think and how would you engage this kind of use cases?
