### ISSUE TITLE
Toolbar not available on Android

### ISSUE THREAD

**Issue by dazinator** [PrismLibrary/Prism#1373]
I have included a link to a repro below, with steps.

In a non prism, Xamarin.Forms application, on Android, you can grab the toolbar in `OnCreate` of your MainActivity, after the `LoadApplication` call:

```csharp

            TabLayoutResource = Resource.Layout.Tabbar;
            ToolbarResource = Resource.Layout.Toolbar;

            base.OnCreate(bundle);

            global::Xamarin.Forms.Forms.Init(this, bundle);
                     
            LoadApplication(new App());
           // LoadApplication(new ReproPrismApp());

            // Can grab the toolbar!
            ToolBar = FindViewById<Android.Support.V7.Widget.Toolbar>(Resource.Id.toolbar);

```

This is what the plain Xamarin.Forms application class looks like in this case:

```csharp
 public partial class App : Application
    {
        public App()
        {
            InitializeComponent();
            MainPage = new NavigationPage(new Views.MainPage());
        }

        protected override void OnStart()
        {
            // Handle when your app starts
        }

        protected override void OnSleep()
        {
            // Handle when your app sleeps
        }

        protected override void OnResume()
        {
            // Handle when your app resumes
        }
    }

```

However when using Prism, trying to find the toolbar after `LoadApplication(new ReproPrismApp());` results in `null` being returned.

Here is the Prism equivalent application used to test (latest prism CI packages)

```csharp

    public partial class ReproPrismApp : PrismApplication
    {
        public ReproPrismApp()
        {
            InitializeComponent();
            // MainPage = new NavigationPage(new Views.MainPage());
        }      

        protected override void RegisterTypes(IContainerRegistry containerRegistry)
        {
            containerRegistry.RegisterForNavigation<MainPage>();
        }

        protected override void OnInitialized()
        {
            NavigationService.NavigateAsync("MainPage").Wait();

            // throw new System.NotImplementedException();
        }
    }


```

I have noted that during the call to `LoadApplication(new ReproPrismApp())` - `OnInitialised` is triggered, and Navigation occurs. You can see I have added a `Wait()` on the navigate task, to ensure that it completes synchronously as I wanted to be sure that after the `LoadApplication` call, navigation has been run.

However, even though navigation has occurred, I still can't get the toolbar.

Any ideas?

### Expected Behavior

Can find the toolbar from the `MainActivity`

### Actual Behavior

Get null. Works on ordinary Xamarin.Forms (i.e no prism)

### Basic Information

- Version with issue: latest ci packages.
- Last known good version: n/a
- Xamarin.Forms version: 2.5.0.280555 (latest stable)
- IDE: VS2017

﻿### Reproduction Link

https://github.com/dazinator/Xamarin-Forms-Custom-Renderer-Samples/tree/toolbarissue

**make sure you are on the `toolbarissue` branch**
1. Put a breakpoint in `OnCreate()` to see that toolbar is null.
2. Exclude the `ReproPrismApp` cs and xaml file from the project, and include the `App.cs` and `App.xml`, then comment out the line that load ReproPrismApp in OnCreate, and uncomment the line that loads `App`. This time the toolbar is found.

**Comment by brianlagunas** [comment]
Glad you figure it out

**Comment by dazinator** [comment]
It's a bit of a `gotcha` in that I have to add the `Wait()` in `OnInitialised` in order to ensure that `MainPage` has been set synchronously during `OnCreate()` so that I can find my controls after `LoadApplication`:

```
        protected override void OnInitialized()
        {
            NavigationService.NavigateAsync("MainPage").Wait();

            // throw new System.NotImplementedException();
        }

```

Is this a known issue?

**Comment by brianlagunas** [comment]
Not a known issue. The MainPage is set synchronously.  No new threads are created as Prism sets the MainPage directly, and the MainPage cannot be set from a different thread. Prism always uses the built-in XF navigation APIs and does nothing special when it comes to navigation.

**Comment by brianlagunas** [comment]
Actually, the developer shouldn't care what happens under the covers.  All they need to know is that they asked to navigate somewhere, and they did.  As there are three different navigation patterns in XF, it wouldn't make sense to force the developer to know the difference between a Navigate and NavigateAsync or when to use them, especially when you start getting into modal and non-modal nav..

**Comment by dazinator** [comment]
> All they need to know is that they asked to navigate somewhere, and they did

I need to know that the `MainPage` has been set because I can't seem to get hold of the toolbar until this has occurred. Perhaps there is a better way for me to know this from my MainActivity?

**Comment by brianlagunas** [comment]
You know the mainPage is set after you make the call to navigate.  You can test this by checking the MainPage property after the navigate call.

**Comment by brianlagunas** [comment]
You can also await the navigation call, but it doesn't matter, it will behave the same

**Comment by dazinator** [comment]
You can't await in OnInitialised(). Hence the need for me to add that `Wait()` or .Result - which both turn out to be unnecessary because as you have explained the implementation of that method ensures it sets the MainPage synchronosly - but I am just saying this is not something I  would know from the API i'd have to be familiar with the internals of that method! Anyway I've said plenty - core of my issue is resolved and thanks for your response :-)

**Comment by brianlagunas** [comment]
You can await the call in OnInitialized.

**Comment by dazinator** [comment]
>  protected override void OnInitialized()
There is no async modifier?

**Comment by brianlagunas** [comment]
you ca add the async modifier

**Comment by dazinator** [comment]
Blown my mind

**Comment by chyzy** [comment]
How about Xamarin Forms 4.0> Shell?  FindViewById returns null for toolbar if page is wrapped in Shell. Any solutions?
