### ISSUE TITLE
OnNavigatedTo method getting fired twice

### ISSUE THREAD

**Issue by TBertuzzi** [PrismLibrary/Prism#1374]
Hi,
I have noticed that the OnNavigatedTo method is getting fired twice.

I have a TabbedPage that instantiates your children:

 public MainTabbedPage()
        {
            InitializeComponent();

            Children.Add(new MainPage());

            switch (Device.RuntimePlatform)
            {
                case Device.iOS:
                    Children.Add(new LancamentosMesPage());
                    break;
                case Device.Android:
                    Children.Add(new LancamentosMesAndroidPage());
                    break;
                case Device.WinPhone:
                case Device.UWP:
                default:
                    Children.Add(new LancamentosMesPage());
                    break;
            }
        }

But when it enters MainPage the OnNavigatingTo method is called twice.

in app.cs I implement navigation  NavigationService.NavigateAsync("MainTabbedPage?selectedTab=MainPage?carregar=true");

Am I using it wrong or is it a bug?

Thanks

**Comment by brianlagunas** [comment]
Which is it, OnNavigatingTo or OnNavigatedTo?  You said both.  Is it firing twice on MainPage? OnNavigatingTo is fired on all children.  Also you did not provide a reproduction app which is required when trying to have us investigate an issue.

**Comment by TBertuzzi** [comment]
sorry. in both methods the same problem occurs.

The problem occurs in my app. I have seen an old issue in which you replied 

"This is not a bug." This is expected. a BindingContext for the ContentPage you are defining.This forces the ContentPage to inherit the BindingContext of the TabbedPage instead. That is why it is being called twice in your sample. The ContentPage is using the same ViewModel instance that the TabbedPage is using as it's BindingContext . " ,

 so I wanted to know if I'm doing something wrong. Does forwarding the views or viewmodels help you to verify the problem?

**Comment by brianlagunas** [comment]
This is why the repro is required. I don't know what you are doing wrong because I don't see any of the code.  If your child tabs do not have their own ViewModels, then yes they will use the MainTabbedPage VM as their binding context and the methods will fire twice.

**Comment by TBertuzzi** [comment]
The only place I referenced the viewmodel of my view was in the app.cs: containerRegistry.RegisterForNavigation <MainPage, MainPageViewModel> ();
            containerRegistry.RegisterForNavigation <LancamentosMesPage, LaunchesMesPageViewModel> ();

I created an example project to send but could not reproduce the error. Is it possible to send my project with error privately?

 only in it is happening ... 

There is also a particularity, I upgraded from prism 6 pro 7 and I'm using PCL

**Comment by brianlagunas** [comment]
I'm glad you narrowed down your issue to your application code. Unfortunately, I do not have time to debug your app. The good news is that you have enough information to start working the problem to figure out what part of your code could be causing it.

**Comment by TBertuzzi** [comment]
I got it right. There was a viewmodel being used twice for the same view. Thanks for the help and sorry for the time wasted :)
