### ISSUE TITLE
Update Unity to 5.7.*

### ISSUE THREAD

**Issue by ENikS** [PrismLibrary/Prism#1383]
### Description

Been trying to submit a PR for the update but it would not let me. The Create button stays grayed out.

I've done some [performance optimization](https://github.com/unitycontainer/unity/releases/tag/5.7.0.476) of the container. It is now 2 - 5 times faster than version 5.5.5 ([Stats](https://github.com/unitycontainer/unity)). 

It would be nice if you could upgrade it before releasing final v7

### Bugs Fixed ###

- Fixed CLR Compliance warnings in all assemblies including CommonServiceLocator.

The updated and tested version in available in ENikS/Prism in case you might want it

**Comment by dansiegel** [comment]
@ENikS we regularly do updates prior to shipping releases...

**Comment by ENikS** [comment]
Just making sure. My office got very high hopes for the release. Any estimate on WPF 7?
