### ISSUE TITLE
"UnityBootstrapper is obsolete"

### ISSUE THREAD

**Issue by m5112638** [PrismLibrary/Prism#1384]
### Description

When using "UnityBootstrapper" in a WPF application, Prism 7 shows the following message:

**"UnityBootstrapper is obsolete. It is recommended to use the new PrismApplicaion as the app's base class. This will require updating the App.xaml and App.xaml.cs files. The Bootstrapper may be removed in a future release".**

This makes sense if an application has App.xaml and App.xaml.cs, like those created using Visual Studio "WPF App (.NET Framework)" template.

However if you want to use Prism in a plug-in (or add-in) project, like Office VSTO Add-in, there will be no App/Application class (defined in App.xaml and App.xaml.cs). This type of projects can still use WPF, and still need to run Prism bootstrapping. Seems like we need to keep Prism bootstrapping classes for these situations.

**Comment by brianlagunas** [comment]
The bootstrapper isn't going away. The only way to drive people to the new PrismApplication, is to use the attribute to make the announcement.  I can clarify the  message.
