### ISSUE TITLE
System.IO.FileNotFoundException thrown when using DelegateCommand<int>

### ISSUE THREAD

**Issue by dannypease** [PrismLibrary/Prism#1385]
I am using Prism.Core version 7.0.0.396.

When using a DelegateCommand<int>, a System.IO.FileNotFoundException is being thrown. However, when I use DelegateCommand<string>, everything works ok.

Repro steps:

I have a delegate command like so:

`private DelegateCommand<int> _getItemDetailsCommand;
        public DelegateCommand<int> GetItemDetailsCommand
        {
            get
            {
                return _getItemDetailsCommand ?? (_getItemDetailsCommand = new DelegateCommand<int>(async (itemId) =>
                {
                    await GetItemDetails(itemId);
                }));
            }
        }`

I then call the command like so:

`GetItemDetailsCommand.Execute(10);`

**Comment by dannypease** [comment]
I have also tried using Xamarin.Forms.Command<int> which is working fine.

**Comment by dansiegel** [comment]
@dannypease please provide an actual repro app

**Comment by brianlagunas** [comment]
primitive types are not supported as the generic. They must be nullabel.

`DelegateCommand<int?>`
