### ISSUE TITLE
How can I make PubSubEvent propagate to the parent event class?

### ISSUE THREAD

**Issue by wuyuanyi135** [PrismLibrary/Prism#1387]
### Description

Hello, 
I have a question about the event aggregator in Prism.
If I have two event classes:
```
    public class BaseEvent : PubSubEvent
    {
    }

    public class ChildEvent : BaseEvent
    {
    }
```
When I am calling `_eventAggregator.GetEvent<ChildEvent>.Publish()` is it possible to trigger the subscription of the parent event?

I am doing this because I have various error events defined in my project. I want to handle them in one place. Therefore, I am hoping to subscribe their base event and handle them in bulk, pretty much like try-catch exception.

### Basic Information

- Version with issue:
- Last known good version: 6.3
- Xamarin.Forms version:
- IDE: Visual Studio 2017 Community

**Comment by bartlannoeye** [comment]
Please ask this question on [StackOverflow](https://stackoverflow.com/questions/tagged/prism), which we monitor as well. Only use issues for bugs and feature requests.
