### ISSUE TITLE
Is it possible to manage multiple RegionManager to allow multiple sessions at the same time?

### ISSUE THREAD

**Issue by CrestApps** [PrismLibrary/Prism#1389]
### Description

**Story** 
First user "Mark" log in the application. "Mark" starts at the initial/landing view, then he navigate to a different section of the application using the available buttons/menu. Now, lets say "Mark" is viewing specific profiles when another user "John" needed to perform a quick task on the same application. Instead on login off Mark, "John" needs to be able to switch profile and perform the task he needs. Now, when Mark logs back is, he should be redirected back to the same profiles he was on before John interrupted him.

**Question**

How can I remember where "Mark" were so I can put him back exactly where he were.

**My solution** Here is my attempt into solving the problem. 

In theory, I should be able to use the `RegionManager` to put "Mark" where he left. But in order for me to be able to do that, somehow I need to manage multiple RegionManager so each logged in session will have an instance of the RegionManager. 

I know that the RegionManager is registered as singleton on the bootstrapper, then the default region is set using the following two methods in the `UnityBootstrapper` base class

RegionManager.SetRegionManager(shell, regionManagerInstance);
RegionManager.UpdateRegions();

I am hoping for a way to clone the region manager after the regions are registered since I am still going to be using the same MainWindow instance.

So I tried to clone the `RegionManger` using `BinaryFormatter` and `Newtonsoft.Json` but both are giving me error due to the loop reference in the Regions object.

So I tried to create a new instance of the `RegionManager` like so

```
var regionManager = RegionManager.CreateRegionManager();
var shell = (Application.Current.MainWindow as DependencyObject);
RegionManager.SetRegionManager(shell, regionManager);
RegionManager.UpdateRegions();
```
but the `UpdateRegions()` call keeps throwing this error

> An exception occurred while trying to create region objects. \r\n    - The most likely causing exception was: 'System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Prism.Regions.UpdateRegionsException.

I have a an object called `UserPassportManager` which manages all of my sessions ( a session is an instance of a `UserPassport` object) . Ideally, I would want each `UserPassport` object to manage its own singleton instance of the RegionManager so I am able to restore user's session by re-injecting each active view into it's corresponding region instead of injecting the HomeView all over again.

### Basic Information
Prism 6.3.
I am using Prism.Unity and Prism.WPF

**Comment by brianlagunas** [comment]
This question belongs on SO. GitHub issues are meant for bugs and fature requests.

My only hint to you would be not to try and manage regionManagers. That's the wrong appraoch. Instead you want to manage state. Yo will need to save off the state describing your user and where they are in the app, and then restore that state when they log back in.

**Comment by CrestApps** [comment]
@brianlagunas Thank you for your help here. Next time I'll use SO for such a question. By "Manage State" do you mean save a copy of the `IRegionCollection` for each session? Then when the user logs back in add each existing view to the RegionManager?

**Comment by brianlagunas** [comment]
My thought would be to save the user info, the view name they are on (not the instance), and any state in the view I might need. Using that you should be able to navigate to that view again and restore the state of that view.

**Comment by CrestApps** [comment]
I am going to give that approach a shot later on today. Thanks again for your help. I appreciate your time and you attention to this matter.
