### ISSUE TITLE
Race condition in unit test DelegateCommandFromAsyncHandlerExecuteShouldInvokeExecuteFunc

### ISSUE THREAD

**Issue by frogger3d** [PrismLibrary/Prism#139]
The problem is that the execute phase runs on a different task and may complete after the Assert.True statement. For testability purpose (and possibly for use in viewmodels) an ExecuteAsync method should be added.

```C#
        [Fact]
        public async Task DelegateCommandFromAsyncHandlerExecuteShouldInvokeExecuteFunc()
        {
            bool executed = false;

            var command = DelegateCommand.FromAsyncHandler(async () => await Task.Run(() => executed = true));
            await command.Execute();

            Assert.True(executed);
        }
```

**Comment by frogger3d** [comment]
Not sure why I missed it, but it's right in the quoted test. There already is an async Execute and I have no idea what is causing the race condition.

**Comment by briannoyes** [comment]
Yeah I spent some time staring at that one two, almost always get the race condition when running all tests but always runs green on its own and for the life of me I can't see why. Low priority as a result but will keep open until we figure out why.

**Comment by brianlagunas** [comment]
Yeah, this test is a real pain right now.  Sometimes it fails, and sometimes it passes.  Basically the luck of timing it seems.

**Comment by brianlagunas** [comment]
we commented this out for now until we can figure out why the test fails sometimes and passes other times.
