### ISSUE TITLE
RemovePage is not supported globally on iOS

### ISSUE THREAD

**Issue by dimonkomaron** [PrismLibrary/Prism#1390]
### Description

I have implemented Master Details Page using and pushed on Details Page Main Page.

`    await navigationService.NavigateAsync($"/{Screens.Index}/{Screens.Navigation}/{Screens.Lobby}");
`
Where Index is MasterDetailsPage.

On Lobby Page I have pushed modal page:
`  await navigationService.SafeNavigateAsync(Screens.StoryDetail, navigationParameters, useModalNavigation: true);`

From this modal page I have pushed another modal page  (actually I want to replace current page with my and i have done it like listed below): (RemoveView is an extension method that I have implemented by Brian suggestion.

`            var navigationParameters = await GetAndPrepateNavigationParameters();
                await navigationService.SafeNavigateAsync(Screens.Chat, navigationParameters, useModalNavigation: true);
                navigationService.RemoveView(Screens.StoryDetail);`

### Expected Behavior

Page must be removed from modal stack

### Actual Behavior

Exception throws with  message RemovePage is not supported globally on iOS;

### Basic Information
- Xamarin.Forms version: 2.5.0.280555
- IDE: VS 2017 for Mac

**Comment by brianlagunas** [comment]
You haven't provided enough information, nor a required reproduction app. I don't know what SafeNavigateSync is or what code you have modified. The error is helping you identify what the problem is.  Remove is not supported for modal pages, only pages within a NavigationPage

**Comment by dimonkomaron** [comment]
Sorry I forgot provide code:

```
 public static async Task SafeNavigateAsync(this INavigationService navigationService, string name,NavigationParameters parameters = null, bool? useModalNavigation = null, bool animated = true)
        {
            var formsNav = ((Prism.Common.IPageAware)navigationService).Page.Navigation;
            IReadOnlyCollection<Page> stack = formsNav.NavigationStack;
            if (useModalNavigation != null && useModalNavigation.Value)
            {
                stack = formsNav.ModalStack;
            }
            var pageType = PageNavigationRegistry.GetPageType(name);
            if (stack.LastOrDefault()?.GetType() != pageType)
            {
                await navigationService.NavigateAsync(name, parameters, useModalNavigation, animated);
            }
        }
```

> 
        public static void RemoveView(this INavigationService navigationService, string name)
        {
            var formsNav = ((Prism.Common.IPageAware)navigationService).Page.Navigation;
            var pageType = PageNavigationRegistry.GetPageType(name);
            var page = formsNav.NavigationStack.LastOrDefault(p => p.GetType() == pageType) ?? formsNav.ModalStack.LastOrDefault(p => p.GetType() == pageType);
            formsNav.RemovePage(page);
        }

**Comment by brianlagunas** [comment]
As I said, RemovePage is not supported for modal pages, only pages within a NavigationPage

**Comment by dimonkomaron** [comment]
Do we have a possibility to change modal page?
