### ISSUE TITLE
ObservesProperty does not support readonly properties

### ISSUE THREAD

**Issue by znakeeye** [PrismLibrary/Prism#1392]
### Description

myCommand.ObservesProperty(() => MyGetter);

### Steps to Reproduce

See code above.

### Expected Behavior

You can raise PropertyChanged on a readonly property. ObservesProperty() should support this type of property. Add code to handle **UnaryExpression**?

### Actual Behavior

Exception thrown.

### Basic Information

- Version with issue: 6.3.0
- Last known good version:
- Xamarin.Forms version:
- IDE:

**Comment by brianlagunas** [comment]
You cannot change values of readonly properties.

**Comment by JunkyXL86** [comment]
@brianlagunas What about computed properties, that need to be recomputed due to a property change?
Something like this:

```
public int AllItemsCount
{
   return AcceptedItems.Count + DeclinedItems.Count;
}

void AcceptItem(Item item)
{
    ...
    AcceptedItems.Add(item);
    OnPropertyChanged(nameof(AllItemsCount));
}
```

**Comment by brianlagunas** [comment]
Hmmmm... I'm not sure about this.  Have you tried modifying the Prism source to support UnaryExpressions and running the tests to see if they pass? If it's a simple as modifying our guard clause to check which expression type it is, I may be open to it. That's assuming there are no other issues that arise from trying to support it.

**Comment by znakeeye** [comment]
I'd say this is fundamental construct in any MVVM application. I will try to modify the source code as soon as I get time.
