### ISSUE TITLE
No hamburger icon iOS

### ISSUE THREAD

**Issue by PowerUzer** [PrismLibrary/Prism#1394]
### Description

I created a simple MasterDetail app with AppMap (attached), compiled and ran it. No hamburger icon. Works fine in Android. 

### Steps to Reproduce

1. File->New->Project->App Map
2. Select Master detail and nothing else
3. Compile/Run on iOS

### Expected Behavior
Show hamburger icon

### Actual Behavior
Shows title of ContentPage in MainPage.xaml

### Basic Information

- Version with issue:  7.0.0.396
- Last known good version: unknown
- Xamarin.Forms version: 2.5.0.280555
- IDE: VS 2017 for Windows 15.5.7

### Reproduction Link
[PrismXFBugProject.zip](https://github.com/PrismLibrary/Prism/files/1805868/PrismXFBugProject.zip)

**Comment by dansiegel** [comment]
This is not a bug, nor does it have anything to do with Prism but rather how Xamarin Forms works. You can see a sample for getting the HamburgerMenu in our [samples](https://github.com/PrismLibrary/Prism-Samples-Forms/tree/master/HamburgerMenu) repo.
