### ISSUE TITLE
View being moved from one region to another but not displayed.

### ISSUE THREAD

**Issue by danielkaczmarek** [PrismLibrary/Prism#1396]
### Description

Basically, I was following a course from pluralsight by Brian Lagunas, and I learned how to display multiple shells. Which is great, but I need to take it one step further than that. When I open new shell I want to move the view that is currently open, from the old shell to the new one (so the user does not lose any data).

### Steps to Reproduce

Create new shell.
Get current view from the old shell, and remove it from there, then add it to the new shell.
Something like this below is what I have done, this based on the project from that course. 

private void OpenShell()
{
        IRegionManager scopedRegion = service.ShowShell();
        IRegion currentRegion = RegionManager.Regions[KnownRegionNames.ContentRegion];
        object currentView = currentRegion.ActiveViews.FirstOrDefault();
        currentRegion.Remove(currentView);
        scopedRegion.RegisterViewWithRegion(KnownRegionNames.ContentRegion, () => currentView);
}

### Expected Behavior
The view should be removed from one region and added to another and displayed.
### Actual Behavior
The view is removed from the first region, added to the next region, but not displayed, until I navigate away from it in that new region and then come back to it.
### Basic Information

- Version with issue: 6.3
- Last known good version:
- Xamarin.Forms version:
- IDE: VS 2017

**Comment by Coder-Nut** [comment]
If you are sure currentView still holds the removed view then, if I am not mistaken, you still need a RequestNavigate in the content region or you could use RegionManager.Regions[KnownRegionNames.ContentRegion].Add(currentView) which will add and display the view if it is the only or first one added to the region.

**Comment by brianlagunas** [comment]
Why are you using RegisterViewWithRegion? You would only ever use that during initial module initializing. Just add the view to the region. Depending on what else is there you may have to activate it too. Please ask these types of questions on StackOverlfow or the slack channel. The issues page is for bugs/features.  Thanks

**Comment by danielkaczmarek** [comment]
Thank you for your replies, the problem is that if I add the view to the region and even activate it. Then the first time I try to navigate I get an exception from RegionManager, telling me tha the region name already exists. So I don't know if I'm doing something wrong, or is it a bug?

**Comment by brianlagunas** [comment]
You're doing something wrong. It's not a bug.
