### ISSUE TITLE
Update from Prism 5.x to 6.x or 7.x

### ISSUE THREAD

**Issue by PeterForstmeier** [PrismLibrary/Prism#1397]
Hi,
i'm aware that this is propably not the best place to ask......
Is the any advice how to upgrade from Prism 5.x (WPF) to 6.x or 7.x (WPF + UWP)

Thanks in advance
Peter

**Comment by bartlannoeye** [comment]
Read the release notes both under [releases](https://github.com/PrismLibrary/Prism/releases) for 7.x and on the [wiki](https://github.com/PrismLibrary/Prism/wiki) for v6.x and jump into it (fixing any issues that arise). We don't have an upgrade wizard.

Note that we don't have a finished 7.0 release for WPF/UWP yet, so might be best to stick to 6.3.
