### ISSUE TITLE
cannot convert from 'CommonServiceLocator.IServiceLocator' to 'Prism.Ioc.IContainerExtension'

### ISSUE THREAD

**Issue by vknht** [PrismLibrary/Prism#1398]
### Description

Hello,

I downloaded the source-files from the master branch and loaded the "Prism.Mef.Wpf.csproj" Project. When I want to build the Project, I am getting this Error:

Error	CS1503	Argument 1: cannot convert from 'CommonServiceLocator.IServiceLocator' to 'Prism.Ioc.IContainerExtension'	Prism.Mef.Wpf	C:\temp\Prism-master\Source\Wpf\Prism.Mef.Wpf\Modularity\MefModuleInitializer.cs	49	Active

Yes, I loaded the "PrismLibrary.sln" solution, build it and set the references.

### Steps to Reproduce

1.  Download master-branch
2.  Open the project "Prism.Mef.Wpf.csproj" under "\Source\Wpf\Prism.Mef.Wpf\"
3.  Build the Project.

### Expected Behavior

That I can build the Project after downloading it from the GitHub.

### Actual Behavior

That I cannot build the Project after downloading it from the GitHub.

### Basic Information

- Version with issue: 7.0.0.396
- Last known good version: Unknown
- Xamarin.Forms version: Unknown
- IDE: Visual Studio 2017 (Community)

### Screenshots

Not a Visual problem.

### Reproduction Link

I described it in the "Steps to reproduce"-Section, but since a Link is required...
https://github.com/PrismLibrary/Prism/blob/master/Source/Wpf/Prism.Mef.Wpf/Prism.Mef.Wpf.csproj

Also: Are the Nuget-Packages for Prism.Wpf and Prism.Mef outdated? they still seem to require the CommonServiceLocator 1.3

**Comment by brianlagunas** [comment]
MEF is no longer supported. If you want to use MEF you will have to modify the code to make it work.

**Comment by brianlagunas** [comment]
By the way, the CommonServcieLocator package is up to date https://github.com/PrismLibrary/Prism/blob/master/Source/Wpf/Prism.Wpf/packages.config#L3

**Comment by vknht** [comment]
Hello,

thanks for your response.

When I search for Prism.Mef or Prism.Wpf in the NuGet Package Manager, the CommonServiceLocator v1.3 ist listed as a dependency, when I download the package and Update to CommonServiceLocator v2.0.x I am getting the error, that Prism.Mef.Wpf could not find CommonServiceLocator v1.3.0.
I wanted to check the references within the source code, but i cannot build the project. That is why i created this issue.
That is also, why i asked if the Prism-Nuget-Packages are outdated.

But if you do not support Mef anymore, can I fork this repository and Update the dependencies myself?


Sample Project here:

[ClassLibrary3.zip](https://github.com/PrismLibrary/Prism/files/1814291/ClassLibrary3.zip)

some images:
![prism mef wpf_oldreference](https://user-images.githubusercontent.com/34534652/37448832-4a3d1f88-2828-11e8-8be6-4f0187b3e992.png)
![prism mef_dependencies](https://user-images.githubusercontent.com/34534652/37448833-4a5b5bc4-2828-11e8-99b2-92e78f896659.png)
![prism wpf_dependencies](https://user-images.githubusercontent.com/34534652/37448834-4a79377a-2828-11e8-8422-8df074deefd8.png)

**Comment by brianlagunas** [comment]
You're confusing the released version vs. the current master code base which is being developed but not released. What is released on NuGet is v6.3 (not updated to CSL 2.0.x). What is in the repo is v7.0.
