### ISSUE TITLE
Use Rg.Plugins.Popup with Prism?

### ISSUE THREAD

**Issue by ali-h2010** [PrismLibrary/Prism#1400]
You can use it without prism as:  
`var loadingPage = new LoadingPopupPage();
await Navigation.PushPopupAsync(loadingPage);
await Task.Delay(2000);
await Navigation.RemovePopupPageAsync(loadingPage);
`
```
<pages:PopupPage >
	 <StackLayout VerticalOptions="Center" HorizontalOptions="Center">
         <ActivityIndicator
            Color="White"
            IsRunning="True"
            IsEnabled="True"            
            HeightRequest="70"
            WidthRequest="70"/>
        <Label Text="Loading" TextColor="White" />
    </StackLayout>
</pages:PopupPage>
```

I tried that , but apparently , I can't access the INavigaion Navigation object to push pages as modals

so, I tried to use prism's navigation: 

`
await _navigationService.NavigateAsync("?",
useModalNavigation: true);
`
Here, the method takes the name of the page, but I can't register the "loadingPage" since it's a popup page with no viewmodel

Is there a way to push Modal pages into the same page using Prism?

**Comment by dansiegel** [comment]
@ali-h2010 I believe you're thinking of Modal in a Web context which is all wrong for Xamarin Forms. Prism cannot and will not directly support 3rd part libraries like Rg.Plugins.Popup... however it is supported with [Prism.Plugin.Popups](https://www.nuget.org/packages/Prism.Plugin.Popups/2.0.0-pre6)

**Comment by ali-h2010** [comment]
@dansiegel That looks like what i need exactly. 
Thanks but is there any documentation on  how to use it?

**Comment by dansiegel** [comment]
on [GitHub](/dansiegel/Prism.Plugin.Popups)... all you need to do is add the following to you RegisterTypes

```cs
containerRegistry.RegisterPopupNavigationService();
```

**Comment by ali-h2010** [comment]
@dansiegel  
i found the Github page.
https://github.com/dansiegel/Prism.Plugin.Popups
