### ISSUE TITLE
Workflow Foundation 4.5 conflict with Prism.DryIoc 6.3

### ISSUE THREAD

**Issue by dienvu** [PrismLibrary/Prism#1404]
### Description

When Add a Workflow Foundation 4.5 Project to Prism.DryIoc Solution. Any Custom Activity will not show on Workflow Toolbox.

### Steps to Reproduce

1. Clone project https://github.com/dienvu/WorkFlowConflictPrismDryIoc6.3.git
2. Open Solution Module -> Workflow -> Activity1.xaml
3. Open Toolbox (View -> Toolbox, or Ctrl-W,X)
4. RightClick Solution and Rebuild -> No CodeActivity1 appear on Workflow Toolbox
5. Unload Module Project (or Uninstall Nuget Prism.DryIoc from Module Project)
6. Now rebuild Solution => CodeActivity1 appear on Workflow Toolbox
7. Can add CodeActivity2, 3, 4 ... etc ... and test with/without Nuget Prism.DryIoc

### Basic Information

- Version with issue:
- Last known good version:
- Xamarin.Forms version:
- IDE:

### Reproduction Link

https://github.com/dienvu/WorkFlowConflictPrismDryIoc6.3.git

**Comment by brianlagunas** [comment]
Prism has no relation to Workflow Foundation or it's toolbox items.
