### ISSUE TITLE
Module, Initialization on demand. Wrong Example in documentation page

### ISSUE THREAD

**Issue by dust63** [PrismLibrary/Prism#1406]
Hi,

In your documentation web page (http://prismlibrary.github.io/docs/wpf/Modules.html), the example to set app.config to load module on demande is wrong. 
I can't see the parameter InitializationMode.OnDemand on the example.

> Specifying On-Demand Loading in Configuration
> You can specify the InitializationMode.OnDemand when you define your module catalog in the App.config file, as shown in the following code example.

```
<!-- App.config -->
<module assemblyFile="ModularityWithUnity.Desktop.ModuleC.dll" moduleType="ModularityWithUnity.Desktop.ModuleC, ModularityWithUnity.Desktop.ModuleC, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" moduleName="ModuleC" startupLoaded="false" />
```

**Comment by brianlagunas** [comment]
The part you're looking for is  `startupLoaded="false"`
