### ISSUE TITLE
Navigate using absolute URI returns an ArgumentException: Handle must be valid. Parameter name: instance

### ISSUE THREAD

**Issue by vhugogarcia** [PrismLibrary/Prism#1407]
### Steps to Reproduce
When trying to navigate to a new page I need to reset the stack and for instance I'm doing this:

`await _navigationService.NavigateAsync("App:///NavigationPage/MemberMasterPage");`

### Expected Behavior
Once the user is validated I need to navigate to the Master page with a clean stack, however, I'm getting  an error: ArgumentException: Handle must be valid. Parameter name: instance

### Basic Information

- Version with issue: 7.0 SR1
- Last known good version:
- Xamarin.Forms version: 2.5
- IDE:

### Screenshots

https://s17.postimg.org/um8lbrwsv/Screen_Shot_2018-03-22_at_1.11.00_PM.png

**Comment by brianlagunas** [comment]
You did not provide enough information about your issue. We will require a reproduction app in order to help.

**Comment by vhugogarcia** [comment]
This issue is happening on Android only. Let me see how I can provide the code sample, you know the privacy policy thing.

**Comment by brianlagunas** [comment]
I don't need a code sample, that won't help. You should create a simple app the can reproduce the issue outside the scope of your application logic.

**Comment by vhugogarcia** [comment]
Thanks @brianlagunas I think this is related with an issue on Android more than PRISM:

`
[MonoDroid] UNHANDLED EXCEPTION:
[art] JNI RegisterNativeMethods: attempt to register 0 native methods for md54ada4fbe4a5955f6151fa282d30cfc48.SelfDisposingBitmapDrawable
[MonoDroid] System.ArgumentException: Handle must be valid.
[MonoDroid] Parameter name: instance
[MonoDroid]   at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00009] in <dcbf64ae8f9943dcab345b6fa6378854>:0 
[MonoDroid]   at Android.Runtime.JNIEnv.CallNonvirtualVoidMethod (System.IntPtr jobject, System.IntPtr jclass, System.IntPtr jmethod, Android.Runtime.JValue* parms) [0x00000] in /Users/builder/data/lanes/5809/22d97e15/source/monodroid/external/xamarin-android/src/Mono.Android/Android.Runtime/JNIEnv.g.cs:444 
[MonoDroid]   at Android.Support.V4.Widget.DrawerLayout.RemoveDrawerListener (Android.Support.V4.Widget.DrawerLayout+IDrawerListener listener) [0x00088] in <2b37e84ec78447f09a7f666911e23ae6>:0 
[MonoDroid]   at Xamarin.Forms.Platform.Android.AppCompat.NavigationPageRenderer.Dispose (System.Boolean disposing) [0x000e4] in D:\agent_work\1\s\Xamarin.Forms.Platform.Android\AppCompat\NavigationPageRenderer.cs:162 
[MonoDroid]   at Java.Lang.Object.Dispose () [0x00000] in /Users/builder/data/lanes/5809/22d97e15/source/monodroid/external/xamarin-android/src/Mono.Android/Java.Lang/Object.cs:203 
[MonoDroid]   at Xamarin.Forms.Platform.Android.AppCompat.Platform+<>c__DisplayClass35_0.<SetPage>b__0 () [0x00015] in D:\agent_work\1\s\Xamarin.Forms.Platform.Android\AppCompat\Platform.cs:256 
[MonoDroid]   at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in /Users/builder/data/lanes/5809/22d97e15/source/monodroid/external/xamarin-android/src/Mono.Android/Java.Lang/Thread.cs:36 
[MonoDroid]   at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00008] in /Users/builder/data/lanes/5809/22d97e15/source/monodroid/external/xamarin-android/src/Mono.Android/obj/Release/android-26/mcw/Java.Lang.IRunnable.cs:81 
[MonoDroid]   at (wrapper dynamic-method) System.Object.88dadd17-2b6c-4312-9fb5-b09f357d0560(intptr,intptr)
`

What do you think?

**Comment by dansiegel** [comment]
@vhugogarcia the Prism team does this in our spare time. If you cannot provide a simple app that reproduces the error, we simply do not have the capacity to help you further with this issue.
