### ISSUE TITLE
The application called an interface that was marshalled for a different thread.

### ISSUE THREAD

**Issue by dwellna** [PrismLibrary/Prism#1408]
### Description

We have a UWP application running under Windows 10 in assigned access.
When the PC is being shut down, die application crashes with an unhandled exception:
"The application called an interface that was marshalled for a different thread." which is caused by handling the applications suspending event in PrismApplication.
I could track down the issue to two calls, one to "NavigationService.Suspending()" and the other one to
"SessionStateService.SaveAsync()" where at the first, the getter of the "Content" property of the underlying Frame control is called through the FrameFacadeAdapter and second in "SessionStateService.GetSessionStateForFrame()" calls "GetValue()" on the FrameFacadeAdapter which results in calling "GetValue()" on the frame control.

### Steps to Reproduce

1. Run a UWP application using the PrismApplication class as base type. within Assigned Access on Windows 10.
2. Make sure the application writes log files on unhandled exceptions.
3. Remote shutdown or restart the PC.

### Expected Behavior
It should just work.

### Actual Behavior
On shutdown while in Assigned Access the application tries to suspend and crashes with the above mentioned exception.

### Basic Information

- Version with issue: 6.*
- Last known good version: not known
- Xamarin.Forms version: N/A
- IDE: Visual Studio 2017

### Reproduction Link

Not sure what's expected here but this issue can only be reproduced manually.

**Comment by brianlagunas** [comment]
Thank you for the issue, but we are not accepting new issues for UWP.  UWP is being rewritten from the ground up and merged with Template10.
