### ISSUE TITLE
Navigation on master page

### ISSUE THREAD

**Issue by keyduq** [PrismLibrary/Prism#1410]
### Description

Is there a way to navigate inside the master page (not detail page) on MasterDetailPage with prism?

### Basic Information

- Prism version: 7.0
- Xamarin.Forms version: 2.5
- IDE: Visual Studio 2017

**Comment by brianlagunas** [comment]
Yes, it's that same as if you weren't using prism. Wrap your Master in a NavpAge and then each page should have it's own VM. You'll have to do some tricks to navigate the detail page when using this approach, but it's not too hard.

Good luck
