### ISSUE TITLE
XAML Intellisense?

### ISSUE THREAD

**Issue by mzhukovs** [PrismLibrary/Prism#1411]
### Description

I get zero intellisense in XAML files. Am I missing something?

### Steps to Reproduce

1. Add a PrismContentPage from the template pack
2. Add a property to the ViewModel and a Binding for it in the View
3. No intellisense, and yes VS -> Options -> XAML Designer -> General -> Enable XAML Designer is ticked

Also tried what is [HERE](https://damian.fyi/2016/04/10/getting-xamarin-xaml-intellisense-when-the-binding-context-is-set-in-code) to no avail.

### Expected Behavior
Get some basic intellisense, e.g. can use F12 to go to StaticResource definition or Bindings i.e. properties in ViewModel

### Actual Behavior
Zilch

### Basic Information

- Version with issue: Latest
- Last known good version: n/a
- Xamarin.Forms version: Latest
- IDE: VS2017 Enterprise

**Comment by dansiegel** [comment]
Intellisense comes from IDE tooling that the Prism team has no control over... To be honest the best XAML intellisense in Xamarin Forms I've seen comes from MFractor in VS Mac. If you choose to go that route I also suggest installing the Prism MFractor Config via NuGet which tailors MFractor for Prism conventions.

**Comment by mzhukovs** [comment]
Thanks Dan. Struggling to come to terms with this as it's advertised as if this would work, but yes I created a non-Prism XF project and sure enough, nothing again, so sorry for posting here but thanks for your response and since we're already here may I ask if you know of a free option (I don't want to pony up for a resharper license) for _Windows_ VS? Seems MFractor isn't available for win and that it's not at the top of their priority list. @dansiegel
