### ISSUE TITLE
Xaml NavigationBar and MasterDetailPage

### ISSUE THREAD

**Issue by idimkk** [PrismLibrary/Prism#1412]
### Description

Hello!
Thank you for your library.
I have a question. If I have my own NavigationBar on the page itself (xaml). I do not want to use the standard NavigationBar.
Question: what event should I call to open the menu (MasterDetailPage) on this page using ViewModel?

Thanks for your attention! 

### Basic Information
Prism version: Latest
Xamarin.Forms version: Latest
IDE: Visual Studio 2017

**Comment by dansiegel** [comment]
Please ask your questions on StackOverflow. GitHub issues are meant for feature requests and bug reports.
