### ISSUE TITLE
Question about dynamically adding views without activating

### ISSUE THREAD

**Issue by bzuillsmith** [PrismLibrary/Prism#1416]
I've got a docking control that I need to dynamically add views to. I sometimes want to add views without activating them. What's the best way to do this from a view model?

It would be nice to have a form of NavigationRequest that doesn't actually navigate, but just adds the view. Should I extend the navigation service with this functionality? Or should this sort of functionality be moved out to it's own service that handles navigation for the docking control? Or am I missing something obvious because it's the end of the week and my brain is fried?

**Comment by brianlagunas** [comment]
Have you tried Region.Add?  Also, going forward questions belong on SO or our slack channel. We reserve the Issues for bugs and feature requests.

**Comment by bzuillsmith** [comment]
Gotcha, sorry about that. I saw the other issues marked with the question labels and thought it was appropriate. Will Region.Add take a view URI or something other than the instantiated view object? The comments for the parameter are not clear. I'll take a deeper look at it though, thanks.
