### ISSUE TITLE
Release mode compilation of droid failing

### ISSUE THREAD

**Issue by thomashoef** [PrismLibrary/Prism#1418]
### Description

After integrating Prism7 into my app, everything works fine in Debug mode or Release mode for iOS. There is a failure though in Droid Debug.

### Error log
    Target _StripEmbeddedLibraries:
        /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(469,5): warning : Failed to read '/Users/thomashoefkens/Documents/git/SF_-_MyApp_-_TFS/Deployables/MyApp.App.Droid-Std/obj/BetaRelease/linksrc/MyApp.App.Droid-Std.dll' with debugging symbols. Retrying to load it without it. Error details are logged below.
        /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(469,5): warning : System.InvalidOperationException: Operation is not valid due to the current state of the object.
        /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(469,5): warning :   at Mono.Cecil.ModuleDefinition.ReadSymbols (Mono.Cecil.Cil.ISymbolReader reader) [0x00057] in /Users/builder/data/lanes/5809/a7829590/source/monodroid/external/xamarin-android/external/Java.Interop/external/cecil/Mono.Cecil/ModuleDefinition.cs:1097 
        /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(469,5): warning :   at Mono.Cecil.ModuleReader.ReadSymbols (Mono.Cecil.ModuleDefinition module, Mono.Cecil.ReaderParameters parameters) [0x0004a] in /Users/builder/data/lanes/5809/a7829590/source/monodroid/external/xamarin-android/external/Java.Interop/external/cecil/Mono.Cecil/AssemblyReader.cs:108 
        /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(469,5): warning :   at Mono.Cecil.ModuleReader.CreateModule (Mono.Cecil.PE.Image image, Mono.Cecil.ReaderParameters parameters) [0x00081] in /Users/builder/data/lanes/5809/a7829590/source/monodroid/external/xamarin-android/external/Java.Interop/external/cecil/Mono.Cecil/AssemblyReader.cs:83 
        /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(469,5): warning :   at Mono.Cecil.ModuleDefinition.ReadModule (Mono.Disposable`1[T] stream, System.String fileName, Mono.Cecil.ReaderParameters parameters) [0x00006] in /Users/builder/data/lanes/5809/a7829590/source/monodroid/external/xamarin-android/external/Java.Interop/external/cecil/Mono.Cecil/ModuleDefinition.cs:1149 
        /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(469,5): warning :   at Mono.Cecil.ModuleDefinition.ReadModule (System.String fileName, Mono.Cecil.ReaderParameters parameters) [0x0006c] in /Users/builder/data/lanes/5809/a7829590/source/monodroid/external/xamarin-android/external/Java.Interop/external/cecil/Mono.Cecil/ModuleDefinition.cs:1121 
        /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(469,5): warning :   at Mono.Cecil.AssemblyDefinition.ReadAssembly (System.String fileName, Mono.Cecil.ReaderParameters parameters) [0x00000] in /Users/builder/data/lanes/5809/a7829590/source/monodroid/external/xamarin-android/external/Java.Interop/external/cecil/Mono.Cecil/AssemblyDefinition.cs:134 
        /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(469,5): warning :   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.ReadAssembly (System.String file) [0x000de] in /Users/builder/data/lanes/5809/a7829590/source/monodroid/external/xamarin-android/external/Java.Interop/src/Java.Interop.Tools.Cecil/Java.Interop.Tools.Cecil/DirectoryAssemblyResolver.cs:151 
        Creating "obj/BetaRelease/strip.flag" because "AlwaysCreate" was specified.
    Done building target "_StripEmbeddedLibraries" in project "MyCompany.MyApp.App.Droid-Std.csproj".
    Target _LinkAssembliesShrink:
        Creating directory "obj/BetaRelease/proguard".
        /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(1748,5): error MSB4018: The "LinkAssemblies" task failed unexpectedly.
        /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(1748,5): error MSB4018: Mono.Linker.MarkException: Error processing method: 'System.Void MyCompany.MyApp.Navigation.Prism.Bootstrapping.PrismNavigationBootstrapper::ForViewNavigationWithAutofacContainer(MyCompany.Core.Bootstrapping.BootstrapResult,Prism.Ioc.IContainerRegistry)' in assembly: 'MyApp.App.Droid-Std.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve System.Void Prism.Ioc.IContainerRegistryExtensions::RegisterForNavigation(Prism.Ioc.IContainerRegistry,System.String)
        /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(1748,5): error MSB4018:   at Mono.Linker.Steps.MarkStep.HandleUnresolvedMethod (Mono.Cecil.MethodReference reference) [0x00013] in <bae064cadfb64dccb729d7cb7dab7861>:0 
        /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(1748,5): error MSB4018:   at Mono.Linker.Steps.MarkStep.MarkMethod (Mono.Cecil.MethodReference reference) [0x00049] in <bae064cadfb64dccb729d7cb7dab7861>:0 
        /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(1748,5): error MSB4018:   at Mono.Linker.Steps.MarkStep.MarkInstruction (Mono.Cecil.Cil.Instruction instruction) [0x00040] in <bae064cadfb64dccb729d7cb7dab7861>:0 
        /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(1748,5): error MSB4018:   at Mono.Linker.Steps.MarkStep.MarkMethodBody (Mono.Cecil.Cil.MethodBody body) [0x00098] in <bae064cadfb64dccb729d7cb7dab7861>:0 
        /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(1748,5): error MSB4018:   at Mono.Linker.Steps.MarkStep.ProcessMethod (Mono.Cecil.MethodDefinition method) [0x00161] in <bae064cadfb64dccb729d7cb7dab7861>:0 
        /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(1748,5): error MSB4018:   at Mono.Linker.Steps.MarkStep.ProcessQueue () [0x0001a] in <bae064cadfb64dccb729d7cb7dab7861>:0 
        /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(1748,5): error MSB4018:    --- End of inner exception stack trace ---
        /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(1748,5): error MSB4018:   at Mono.Linker.Steps.MarkStep.ProcessQueue () [0x00046] in <bae064cadfb64dccb729d7cb7dab7861>:0 
        /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(1748,5): error MSB4018:   at Mono.Linker.Steps.MarkStep.ProcessEntireQueue () [0x00002] in <bae064cadfb64dccb729d7cb7dab7861>:0 
        /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(1748,5): error MSB4018:   at Mono.Linker.Steps.MarkStep.Process () [0x00013] in <bae064cadfb64dccb729d7cb7dab7861>:0 
        /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(1748,5): error MSB4018:   at Mono.Linker.Steps.MarkStep.Process (Mono.Linker.LinkContext context) [0x0000d] in <bae064cadfb64dccb729d7cb7dab7861>:0 
        /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(1748,5): error MSB4018:   at Mono.Linker.Pipeline.Process (Mono.Linker.LinkContext context) [0x0001b] in <bae064cadfb64dccb729d7cb7dab7861>:0 
        /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(1748,5): error MSB4018:   at MonoDroid.Tuner.Linker.Run (Mono.Linker.Pipeline pipeline, Mono.Linker.LinkContext context) [0x00000] in <bae064cadfb64dccb729d7cb7dab7861>:0 
        /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(1748,5): error MSB4018:   at MonoDroid.Tuner.Linker.Process (MonoDroid.Tuner.LinkerOptions options, Mono.Linker.ILogger logger, Mono.Linker.LinkContext& context) [0x00071] in <bae064cadfb64dccb729d7cb7dab7861>:0 
        /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(1748,5): error MSB4018:   at Xamarin.Android.Tasks.LinkAssemblies.Execute (Java.Interop.Tools.Cecil.DirectoryAssemblyResolver res) [0x002c8] in <bae064cadfb64dccb729d7cb7dab7861>:0 
        /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(1748,5): error MSB4018:   at Xamarin.Android.Tasks.LinkAssemblies.Execute () [0x001fa] in <bae064cadfb64dccb729d7cb7dab7861>:0 
        /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(1748,5): error MSB4018:   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute () [0x00023] in /Users/builder/data/lanes/5533/mono-mac-sdk/external/bockbuild/builds/msbuild-15/src/Build/BackEnd/TaskExecutionHost/TaskExecutionHost.cs:631 
        /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(1748,5): error MSB4018:   at Microsoft.Build.BackEnd.TaskBuilder+<ExecuteInstantiatedTask>d__26.MoveNext () [0x00212] in /Users/builder/data/lanes/5533/mono-mac-sdk/external/bockbuild/builds/msbuild-15/src/Build/BackEnd/Components/RequestBuilder/TaskBuilder.cs:787 
    Done building target "_LinkAssembliesShrink" in project "MyCompany.MyApp.App.Droid-Std.csproj" -- FAILED.
Done building target "AfterBuild" in project "MyCompany.MyApp.App.Droid-Std.csproj" -- FAILED.

### Basic Information

- Version with issue: Prism.Forms latest version
- Last known good version: 6.x
- Xamarin.Forms version: 2.5.0.122233
- IDE: Visual Studio Mac 7.4.1
- Build Target: Oreo 8.1

Note: setting AndroidLinkMode to None --> build works fine. Set to SDK only --> build fails with above error.

**Comment by brianlagunas** [comment]
Can't reproduce this and no repro app has been provided.
