### ISSUE TITLE
[WPF] Align versions of Prism.Wpf with Prism.Core

### ISSUE THREAD

**Issue by pchinery** [PrismLibrary/Prism#1419]
### Description

At the moment, Prism.Core has the latest stable version 7.0.0.396. Prism.Wpf has the latest versions 7.0.0.336-pre or 7.1.0.123, but not stable version of 7.x.

What is the reason for that? We currently face some issues in aligning the versions with Paket and StrongNames and if it is planned to realign the versions, it would solve our problems.

**Comment by brianlagunas** [comment]
The reason is because Prism for Xamarin.Forms released first. We are in the process of aligning Prism, but not by version.  We are aligning features across WPF, UWP, and XF. So this is a much larger and riskier effort which is going to take time.
