### ISSUE TITLE
Prism.Forms's EventToCommandBehavior can't get 'Url' property value when used in WebView's Navigated event.

### ISSUE THREAD

**Issue by supershowwei** [PrismLibrary/Prism#1420]
### Description

WebNavigatedEventArgs inherited WebNavigationEventArgs, 'Url' property declared in WebNavigationEventArgs, it can't be got from WebNavigatedEventArgs by GetDeclaredProperty() method in line 186 of /Source/Xamarin/Prism.Forms/Behaviors/EventToCommandBehavior.cs

### Steps to Reproduce

1. 
2. 
3. 

### Basic Information

- Version with issue: 7.1.0.123-pre
- Last known good version: no
- Xamarin.Forms version: 2.5.1.444934
- IDE: Visual Studio 2017 15.6.6

### Reproduction Link

Source Code: https://github.com/supershowwei/broken-event-to-command/blob/master/EventToCommandApp/EventToCommandApp/MainPage.xaml

**Comment by dansiegel** [comment]
Your sample page doesn't seem to reference the ViewModel

**Comment by dansiegel** [comment]
Yes you are correct... sorry I missed that. I would suggest you take a look at the [docs](http://prismlibrary.github.io/docs/xamarin-forms/EventToCommandBehavior.html#eventargsconverter) for the EventToCommandBehavior. You may want to try using a converter.

**Comment by supershowwei** [comment]
Thanks. I'll try it.
