### ISSUE TITLE
Xamarin.Forms| Request: NavigateAsync(Page page) 

### ISSUE THREAD

**Issue by ahmad-crossplatform** [PrismLibrary/Prism#1422]
### Description

This is not a bug rather a a question or enhancement proposal. 

I have  what I call it a **Page Factory** that basically takes a viewModel and produces a `ContentPage` based on  some attributes  defined in the viewmodel . 
This works fine using Vanilla Xamarin.forms (i.e. with no Frameworks) .  However, I would like to use it with Prism since prism already supports cool services. There problem is that there is no implementation for `NavigateAsync` that takes a page as a parameter , saves it to the stack and navigate to that produced page . 

### Example of usage 

```
var type = typeof(TestPageViewModel);
var pageFactory = _container.Resolve<IPageFactory>();
var page = _container.Resolve<IPageFactory>().CreatePage(type);
await NavigateAsync(page);  
```

### Expected Behavior
Prism Framework would navigate to the Page instance and adds it to the pages stack.

### Contribution 

If you find that as a good idea and  you need my help in Implementing it I would love to help . The problem is that the framework is huge and overwhelming so it is hard to know where to start and i might need some guidance .

**Comment by dansiegel** [comment]
This is actually the exact opposite of how the NavigationService currently works. Remember you're registering the View for Navigation, and the ViewModel is being located for a specified View. You could certainly implement this yourself as long as you have the mappings you need. 

The PageNavigationService already has a factory method that produces the page for the segment name... i.e. `ViewA/ViewB` it would produce `ViewA` and later `ViewB`. I'm sure you could achieve what you're looking for by overriding CreatePage if you really had to, though I have a feeling there is probably a better way to accomplish your needs. Can you provide a little more information on why you feel this is needed?

```cs
navigationService.Navigate("ViewA");

// In the NavigationService
protected override Page CreatePage(string segmentName)
{
    var vmType = SomeLookup(segmentName);
    return pageFactory.CreatePage(vmType);
} 
```

**Comment by ahmad-crossplatform** [comment]
OK I need to test that and hopefully this works  :) 
Well I am working with a project that has many pages which do similar stuff (things like a survey ) , so I am trying to implement a mechanism that instead of having to create views and viewmodels , I create the viewmodel and let the pagefactory produce the a page based on that viewmodel , so with this as a developer I only focus on business and forget about making 10 pages doing similar things but for different parts of the survey. then i have to take care of each of thier view stuff like grid rows and columns, make sure of the bindings, styles, vertical and horizontal , etc...  with the page factory I would not have to think about that . All i need is to focus on the view-models and from the view models i can decide what to show and what not to show based on the attributes . It is pretty cool i promise and I will publish about it when it is ready and tested and proved to be good enough idea. 
Anyways, since we work with prism like many people and since prism has cool services that you can use in the view model (e.g. PageDialogService) Then I needed away to integrate the pagefactory with the prism framework . So the user can chose between predefined pages and factory produced pages. 
After all the navigation happens in the viewmodel . 

The problem that I got is how would I use the navigateAsync without registering the page in the first place (i.e. RegisterForNavigation)? If i tried to register the produced page type, then It will always be ContentPage and  it will always create a contentPage for me. 
 I tried to override the navigation service and when i navigate to or from a produced page , then Prism would not keep track of page stacks (Which i believe it is saved as segments) . Instead of that it destroyed all the stack and kept only the new page on top it   so I cannot go back with the back button .
  
I will try to override the create page as you suggested , but my question here how do i add that segment to the segments? is it RegisterForNavigation ?

**Comment by ahmad-crossplatform** [comment]
A second question , if I Extend PageNavigateService, how would i use the extended class as the default  default INavigationService in the view models ? 
I tried to register it in the container , but the viewmodels always get the super class and not the extended one.

**Comment by brianlagunas** [comment]
This is not something that we will be impleemnting as it goes against the core of Prism guidance.
