### ISSUE TITLE
Issue with singleton in Prism DryIoc 6.3 with DryIoc.dll 2.12.10

### ISSUE THREAD

**Issue by GioviQ** [PrismLibrary/Prism#1423]
In my bootstrapper I have

    protected override void ConfigureContainer()
        {
            Container.RegisterMany<HubGateway>(Reuse.Singleton);
            //Container.Register<IHubGateway, HubGateway>(Reuse.Singleton);
            //RegisterTypeIfMissing(typeof(IHubGateway), typeof(HubGateway), true);
            base.ConfigureContainer();
        }

The commented lines do not register HarvinHubGateway as a Singleton: in fact a new instance is created at every injection. Only the first line of code works as expected.
I need an explanation of this counterintuitive behavior.
Thanks

**Comment by brianlagunas** [comment]
We have no control over the behavior of the container API. Also, you did not provide a sample that reproduces the issue.

**Comment by GioviQ** [comment]
I discovered now that RegisterTypeIfMissing(typeof(IHubGateway), typeof(HubGateway), true); registers both IHubGateway and  HubGateway, but only Container.Resolve<IHubGateway>() returns a singleton and Container.Resolve<HubGateway>() creates new instances.
