### ISSUE TITLE
TargetInvocationException using DelegateCommand on Xamarin.iOS

### ISSUE THREAD

**Issue by yarmenteros** [PrismLibrary/Prism#1424]
### Description

There is any approach in order to use DelegateCommand implementation in a cross-platform app?

### Basic Information

- Xamarin.Forms version: 2.5.1.444934
- IDE: VS 2017

Thank you in advance,

**Comment by brianlagunas** [comment]
You provided no information on your issue, or the required reproduction app, so I am closing this issue.

Yes, DelegateCommand should work on any NetStandard compatible project.

**Comment by ChaseFlorell** [comment]
what issue are you having? Can you fill out the issue in full with reproduction steps?
