### ISSUE TITLE
Namespace that ends with .Prism breaks application in 7.1.0 - CS0234

### ISSUE THREAD

**Issue by DJKampouris** [PrismLibrary/Prism#1426]
### Description

Prism.Unity 7.1.10.129ci When a namespace in a WPF project ends with .Prism (case sensitive), the realtime compilation breaks and App.xaml.cs doesn't see the PrismApplication
Also getting error CS0234: The type or namespace name 'Unity' does not exist in the namespace

### Steps to Reproduce

1. Create a new WPF app (.NET Framework) and target frameworkd 4.7.1. 
   I named my example PrismBreak :)
2. Install Prism.Wpf and Prism.Unity from on MyGet (Include Pre-Release)
3. Modify the App.Xaml

```
<unity:PrismApplication x:Class="PrismBreak.App"
                        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
                        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
                        xmlns:local="clr-namespace:PrismBreak"
                        xmlns:unity="http://prismlibrary.com/"
                        x:ClassModifier="internal">
    <Application.Resources>
           
    </Application.Resources>
</unity:PrismApplication>
```

4. Modify the App.Xaml.cs also

```
using System.Windows;
using Prism.Ioc;

namespace PrismBreak
{
    internal partial class App  
    {
        protected override void RegisterTypes(IContainerRegistry containerRegistry)
        {
            
        }

        protected override Window CreateShell()
        {
            return Container.Resolve<MainWindow>();
        }
    }
}

```
5. Build and Run. 

6. Create a new class called Foo.cs

7. Change the NameSpace to PrismBreak.Prism

At this stage the IDE reports errors

```
namespace PrismBreak.Prism
{
    class Foo
    {
    }
}
```

8. In App.Xaml.cs add  : PrismApplication

The Errors goes away.

9. If you compile you get a build error.

```
1>------ Build started: Project: PrismBreak, Configuration: Debug Any CPU ------
1>c:\users\djkam\documents\visual studio 2017\Projects\PrismBreak\PrismBreak\obj\Debug\App.g.cs(44,40,44,45): error CS0234: The type or namespace name 'Unity' does not exist in the namespace 'PrismBreak.Prism' (are you missing an assembly reference?)
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

### Expected Behavior

The Application should compile.

### Actual Behavior

The App.xaml.cs breaks down.

### Basic Information

- Version with issue: Visual Studio 15.6.5 / Prism.Unity 7.1.10.129ci 
- Last known good version:
- Xamarin.Forms version:
- IDE:

### Reproduction Link

See PrismBreak.zip
[PrismBreak.zip](https://github.com/PrismLibrary/Prism/files/1955519/PrismBreak.zip)

**Comment by dansiegel** [comment]
@DJKampouris this is actually related to the compiler namespace rules. You can read more about how to work around this in the Microsoft docs 
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/namespaces/how-to-use-the-global-namespace-alias

**Comment by DJKampouris** [comment]
@dansiegel using 
`internal partial class App  :  global::Prism.Unity.PrismApplication`
or an alias like
```
using TopPrism = Prism.Unity;

namespace PrismBreak
{
    internal partial class App  : TopPrism.PrismApplication
```

still breaks the build with the CS0234 error.

**Comment by n00bje** [comment]
I get this error in my WPF application when trying to migrate from UnityBootstrapper to PrismApplication.
A global namespace alias or regular alias in App.cs doesn't fix this.
Are there any other workarounds I can try?

**Comment by prashanthmp7** [comment]
Hi,

Is there a fix/workaround for this issue? This is my app.xaml. 

<prism:PrismApplication x:Class="DCX.DPE.Client.App"
                        x:ClassModifier="public" 
                        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
                        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
                        xmlns:prism="http://prismlibrary.com/">
    <prism:PrismApplication.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <ResourceDictionary Source="pack://application:,,,/DCX.DPE.Client.Core;component/Assets/Styles.xaml" />
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
    </prism:PrismApplication.Resources>
</prism:PrismApplication>
