### ISSUE TITLE
Code continue execution and returns to the original flow after calling  NavigateAsync

### ISSUE THREAD

**Issue by ali-h2010** [PrismLibrary/Prism#1428]
### Description
Code continue execution and returns to the original flow after calling:
`await _navigationService.NavigateAsync(new System.Uri("/LoginPage", System.UriKind.Absolute));`

### Steps to Reproduce

1. add async method and call an async method inside it. 
2. In the nested async method call NaviageAsync to go to another page
3. 

### Expected Behavior
The flow should go to the new page and not continue execution of the current page. 
### Actual Behavior
the method is returning after the navigation and continue execution of the first method.
I guess that from the name Async , that the code will continue the execution but I don't see a method to Navigate not Asynchronously. 

### Basic Information

- Version with issue:7.0.0.362
- Last known good version: -
- Xamarin.Forms version: 2.5.0.122203
- IDE: Visual Studio For Mac

**Comment by brianlagunas** [comment]
This really has nothing to do with Prism. This is related to the async/await API and it's behavior.  Also you did not provide the required production link, so this issue will be closed.

**Comment by ali-h2010** [comment]
Hi @brianlagunas , 
I didn't know that I needed to make reproduction link for a simple behavior issue.

```
Async Father()
{
    Son()
    //Flow should move to the new page and not continue from here

}
Async Son()
{
    _naviageionService.NaviageAsync();
}

```
I just need to know if Prism support non Async Navigation. Otherwise, I will need to return a task every time and check if I need to continue execution or return;

Could you please help me with this concern?
