### ISSUE TITLE
stamp $(AssemblyName) ($(TargetFramework)) into builds 

### ISSUE THREAD

**Issue by ghuntley** [PrismLibrary/Prism#1429]
Hey folks. 

I stole this pattern from James Monty and Redth. You should totally steal it as well.

https://github.com/reactiveui/ReactiveUI/pull/1604/files

**Comment by dansiegel** [comment]
Thanks @ghuntley we’ve actually been doing that for quite a while. Also was a tip and in the sample I provided in my blog about multitargeting and converting to the SDK style projects.   https://github.com/PrismLibrary/Prism/blob/master/Source/Directory.Build.props#L6
