### ISSUE TITLE
Update Solution files for AppVeyor (and check settings)

### ISSUE THREAD

**Issue by bartlannoeye** [PrismLibrary/Prism#143]
@brianlagunas I noticed your latest checkin ranting on AppVeyor. I found [this post](http://kristian.hellang.com/building-csharp-6-code-with-appveyor/) detailing how to make AppVeyor build your C# 6 code. It comes down to
* Checking environment and path in AppVeyor settings
* Make sure the right VS version is in the solution file.

**Comment by brianlagunas** [comment]
Your PR fixed this.  Thanks.
