### ISSUE TITLE
Prioritize documentation updates

### ISSUE THREAD

**Issue by totht91** [PrismLibrary/Prism#1430]
### Description

The provided current documentation http://prismlibrary.github.io/docs/ for the Prism library is quite small and getting outdated. We need to fish information crumbs from release notes and blog posts from different locations. Please consider to prioritize documentation tasks because many people are trying to use your great library based on the docs.

Thanks

**Comment by dansiegel** [comment]
@totht91 I totally agree with you that the docs need to be updated. The good news is that they are also open source and we accept PR's. Please feel free to fish away from the release notes and send us a PR 👍 
https://github.com/PrismLibrary/Prism-Documentation

**Comment by dansiegel** [comment]
You may have noticed that I've added the `help wanted` label to this issue. There is only so much time in my day. If there is an issue you feel needs updating in our docs, please send us a PR. We do have a CI/CD pipeline setup for this so all updates in our Documentation repo are reflected within a few minutes in the docs.

**Comment by lewcianci** [comment]
@totht91 @dansiegel  What articles would you say are in the most dire need of updating, or adding? I'm making an app with Prism but I'm largely feeling my way through it so my information might not be best practice, but it would contribute to getting an app built.

I might write an article about dependency injection within the context of Prism to see if my writing style is well understood etc and submit a PR.

**Comment by brianlagunas** [comment]
I am closing this as we do not need an issue to remind us that our docs are way out of date :)

We'll get there.... eventually.
