### ISSUE TITLE
INavigationService not found

### ISSUE THREAD

**Issue by pkreker** [PrismLibrary/Prism#1433]
### Description

I am developing an example app with Xamrin.Froms for WPF (therefore the nightly version) and I wanted to start learning Prism. After installing and using some example Code, I get this error:
CS7069	Reference to type 'INavigationService' claims it is defined in 'Prism', but it could not be found

A further look at the Object Browser is showing that the Prism.Navigation namespace is missing in  Prism.dll

I tried cleaning my solution and uninstalling as well as reinstalling Prism, but nothing helped.

### Basic Information

- Version with issue: Prism.Core v7.1.0.123-pre
- Xamarin.Forms version: 3.1.0.444738-nightly
- IDE: Visual Studio Community 2017 Version 15.6.7

**Comment by dansiegel** [comment]
WPF via Xamarin Forms is not supported with Prism at this time. As part of our ongoing API Alignment efforts, INavigationService was moved from Prism.Forms to Prism.Core, but it is not something that makes sense for WPF like it does UWP and Forms. For this reason it is not available in the net45 target used for WPF apps.
