### ISSUE TITLE
LoaderException on MefBootstrapper raised.

### ISSUE THREAD

**Issue by Mer0winger** [PrismLibrary/Prism#1435]
### Description

After Update Prism to newer version with same code which worked before the Bootstrapper fails now.

Used Versions .Net 4.7.1 , NetStandard and Core v 2.0.1 

LoaderException 
-------------------------------
{"Der Typ \"Prism.Modularity.InitializationMode\" in der Assembly \"Prism.Wpf, Version=7.1.0.0, Culture=neutral, PublicKeyToken=40ee6c3a2184dc59\" konnte nicht geladen werden.":"Prism.Modularity.InitializationMode"}	System.Exception {System.TypeLoadException}

### Steps to Reproduce

1.  MefBootstrapper 

Last step was RegisterDefaultTypesIfMissing where in base implementation the exception was raised. 

### Expected Behavior

i take your code of from github and replaced in a local version 

DefaultPrismServiceRegistrar  to => MyPrismServiceRegistrar
and there the exception was raised in 

IEnumerable<ComposablePartDefinition> partsToRegister =  GetRequiredPrismPartsToRegister(aggregateCatalog);

Inside of this method "GetRequiredPrismPartsToRegister" is a for loop  

>> foreach (var part in catalogWithDefaults.Parts)

where it´s fails with the exception above on one of the Parts 

But catalogWithDefaults is created by 

GetDefaultComposablePartCatalog() and there is 

>>return new AssemblyCatalog(Assembly.GetAssembly(typeof(MefBootstrapper)));

returned so this is a "Problem" in Prism because this is the Prism assembly 

from debugger output => 
catalogWithDefaults.Parts	{AssemblyCatalog (Assembly="Prism.Mef.Wpf, Version=7.0.0.0, Culture=neutral, PublicKeyToken=40ee6c3a2184dc59")}	System.Linq.IQueryable<System.ComponentModel.Composition.Primitives.ComposablePartDefinition> {System.Linq.EnumerableQuery<System.ComponentModel.Composition.Primitives.ComposablePartDefinition>}

In the Debug Parts the last one is NULL maybe this is the reason but do not know why. I added a pic.  Maybe somewhere in the Code an Export Attribute is empty ? 

### Basic Information

- Version with issue: 7.1 
-IDE : Visual Studio 2017 

### Screenshots

![debug](https://user-images.githubusercontent.com/16628537/39622445-833d9fa6-4f92-11e8-90aa-d04aac0ec289.PNG)

br

**Comment by brianlagunas** [comment]
MEF is no longer supported.  So anything past v6.3 will not work.
