### ISSUE TITLE
Should GoBackAsync use parent navigation if page navigation fails?

### ISSUE THREAD

**Issue by AmrAlSayed0** [PrismLibrary/Prism#1436]
### Description

This not a bug but a feature request. Suppose I have the following structure:
TabbedPage1
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Tab1
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Tab2
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NavPage/Tab3 --- PushAsync ---> TabbedPage2
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NavPage/Tab4
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Tab5

Calling GoBackAsync on Tab4 would do nothing as the navigation page has only one page on the stack but wouldn't it make sense to look for "Parent Stacks" and pop the first one it finds, in this case this would be TabbedPage2 bringing you back to Tab3 on TabbedPage1.

I know this an unusual design for an app but I have used external controls to shift the tab bar position around so they are not both on the top so the design doesn't feel as weird as it would if 2 bar where just on top of each other.

**Comment by brianlagunas** [comment]
First off, you're right, this is an unusual design. Nesting navigation pages is never a good idea, and is not recommended.  Also, this is really not a scenario that we have tested against, nor are we really inclined to acually support.
