### ISSUE TITLE
How can i obtain service in ViewModel which binding a ContentView!

### ISSUE THREAD

**Issue by ouzs** [PrismLibrary/Prism#1437]
### Description

1、I create ContentView named LeftContent in views floder，and create viewmodel named LeftContentViewModel，then use “prism:ViewModelLocator.AutowireViewModel="True" bind them
2、create ITestInterface class and implement TestInterface，and register in App class
3、In LeftContentViewModel constructor，add parameter ITestInterface 
4、when runninng,error occur. code and eception as follow
thanks a lot!

![1](https://user-images.githubusercontent.com/13414342/39691982-ee986958-5211-11e8-91a8-885244c13c60.png)
![2](https://user-images.githubusercontent.com/13414342/39691984-f4bdf7da-5211-11e8-809d-023167d5fe79.png)
![3](https://user-images.githubusercontent.com/13414342/39691986-f6474840-5211-11e8-9623-24a670c92007.png)
![4](https://user-images.githubusercontent.com/13414342/39691987-f72ff176-5211-11e8-8a2c-5e95a018a22b.png)
![5](https://user-images.githubusercontent.com/13414342/39691989-f7e817a6-5211-11e8-8014-cb8cec08129e.png)

**Comment by dansiegel** [comment]
Please ask questions on StackOverflow. GitHub issues are for reporting bugs and filing feature requests.
