### ISSUE TITLE
How far away is Prism for Xamarin Forms 3.0?

### ISSUE THREAD

**Issue by wind-rider** [PrismLibrary/Prism#1438]
### Description

I see there is a Xamarin Forms 3.0 branch for Prism, but it hasn’t been active for the last 2 months. Now that Xamarin Forms 3.0 is stable, what are Prism’s plans for supporting it?

**Comment by brianlagunas** [comment]
Of course we plan on supporting it. Whenever we release 7.1, it will support XF 3.0

**Comment by dansiegel** [comment]
It works just fine with 3.0 and we’ll have support for 3.1 soon.
