### ISSUE TITLE
Access to EventAggregator in background task

### ISSUE THREAD

**Issue by taxinvoice** [PrismLibrary/Prism#1440]
Have created a background task in Xamarin Forms  which scans for BLE devices.  When it finds the device, I want to publish an event for the subscribers.  I have no idea how to get the instance of of EventAggregator

EventAggregator ea;
   ea = ((App)Application.Current).Container.Resolve<EventAggregator>(); //gives error

**Comment by dansiegel** [comment]
@taxinvoice GitHub issues are meant for bugs and enhancement requests. Please ask questions either on StackOverflow or on the Prism Community Slack.
