### ISSUE TITLE
ViewModel what registered as singleton created twice

### ISSUE THREAD

**Issue by zed220** [PrismLibrary/Prism#1444]
### Description

WPF: ViewModel what registered as singleton created twice.

### Steps to Reproduce

1. Build and run the attachment
2. Click button.
3. Click next button.

### Expected Behavior
Child2ViewModel must use existing instance of ChildViewModel.

### Actual Behavior
Building Child2ViewModel causes creating new instance of ChildViewModel.

### Basic Information

- Version with issue: 7.1.0.123
- Last known good version: 6.x
- Xamarin.Forms version: none
- IDE: Visual Studio 2017

### Reproduction Link

[PrismBug.zip](https://github.com/PrismLibrary/Prism/files/2004303/PrismBug.zip)

**Comment by brianlagunas** [comment]
You have so many probelms in that sample, the most basic features would never work. First word of advice, don't register ViewModels as singletons. Heck, you don't have to even register them.  You most definitely should never be trying to inject them into another VM.  I suggest looking at the WPF samples to see how you should be sturcturing your applicatin.
