### ISSUE TITLE
[Proposal] extend INavigationResult and add new INavigationErrorAware interface

### ISSUE THREAD

**Issue by ChaseFlorell** [PrismLibrary/Prism#1445]
### Description

I'd like to propose the following change to `INavigationResult`

```csharp
// change
namespace Prism.Navigation
{
    public interface INavigationResult
    {
        bool Success { get; }

        NavigationError NavigationError { get; }
    }

    public class NavigationResult : INavigationResult
    {
        public bool Success { get; set; }

        public NavigationError NavigationError { get; set; }
    }
}
```

```csharp
// addition
public struct NavigationError
{
	public Uri Uri { get; }
	public INavigationParameters Parameters { get; }
	public Exception Exception { get; }
}

public interface INavigationErrorAware
{
	void OnNavigationError(INavigationResult error);	
}
```

This change will allow us to call the `OnNavigationError` from either the NavigationService OR from within the new Xaml Navigation found in #1431.

From here we can attach `INavigationErrorAware` to any View or ViewModel and handle navigation errors cleanly.

```csharp
public class MyViewModel : INavigationErrorAware
{
    public void OnNavigationError(INavigationResult error)
    {
        // uh oh, an error happened when trying to navigate.
    }
}
```

**Comment by brianlagunas** [comment]
This is not a pattern that is well suited for error handling.  This would also be very difficult to actually implement as the information requested may not be available depending on where the error occurred. Not to mention, most of that info is already available to you from within the VM you are calling navigate.  I could possibly see adding an OnError event to the navigation service, but this is not really necessary now that we have the async model and the result is returned directly from the task.

I think the core of what you want to do is find a way to handle a navigation error in the new XAML markup extension, which is a separate issue that should be discussed in #1431

**Comment by ChaseFlorell** [comment]
@brianlagunas this idea came out of a discussion with @dansiegel about how we can potentially push the errors up to the user if/when the Markup Extension fails.
