### ISSUE TITLE
using generic way to determine navigation strings

### ISSUE THREAD

**Issue by bleissem** [PrismLibrary/Prism#1452]
### Description

In Prism (in my case 7) there are strings used to navigate to pages

    await NavigationService.NavigateAsync("NavigationPage/MainPage");

I'm currently using the prism template pack that generates the code above.
So instead of using strings this way, how about that template pack generates another class that solves string gereration a more generic way. 
Ok, this only work if you're using the autowire feature.
But this might also be a good reason to use the autowire feature.

### Example
(The class itself needs a better implementation. You should get the idea from it.)

    public static class PageName
    {
        public static string GetFrom<T>() where T : ViewModelBase
        {
            return $"NavigationPage/{typeof(T).Name.Replace("ViewModel", string.Empty)}";
        }
    }

would result in using the string like this:

    await NavigationService.NavigateAsync(PageName.GetFrom<MainPageViewModel>());

**Comment by brianlagunas** [comment]
Thanks for the idea, but this is not a pattern that would be recommended. There ar emany limittaions to this appraoch such as creating a coupling bewteen your VM's, removing the ability to perform a deep link, and more.  You are more than welcome to create somethign specific to your app to support this, but we will not be adding it to Prism.
