### ISSUE TITLE
DryIoc.ContainerException: <Timeout exceeded getting exception details>

### ISSUE THREAD

**Issue by adrianknight89** [PrismLibrary/Prism#1453]
When I supply a custom renderer for `NavigationPage`, I get a runtime exception. Please run the attached project. This was tested on a Galaxy S9+ with Prism 7.1.0.135.

[BlankApp3.zip](https://github.com/PrismLibrary/Prism/files/2043226/BlankApp3.zip)

**Comment by dansiegel** [comment]
this is a duplicate of #1443.
