### ISSUE TITLE
LoginPage/MasterDetailPage: MasterDetail is visible after click Log out

### ISSUE THREAD

**Issue by aneti9862** [PrismLibrary/Prism#1454]
### Description

I have app with LoginPage and MasterDetailPage. After logging, when I click "Log out" from MasterDetail the instruction is executed: _await_navigationService.NavigateAsync("NavigationPage/LoginPage");_
The OnNavigatedFrom method is called form BasePage so it' an exceptable behavior. However, MasterDetailPage is also visible on my LoginPage.

### Steps to Reproduce

1. Log in app
2. Click "Log out" from MasterDetail

### Expected Behavior
OnNavigatedFrom method is called from BasePage and MasterDetailPage **isn't shown** on LoginPage

### Actual Behavior
OnNavigatedFrom method is called from BasePage, but MasterDetailPage **is shown** on LoginPage

### Basic Information

- Version with issue: 

  Prism: Prerelease 7.1.0.123
  Xamarin.Forms: 3.0.0.446417

**Comment by brianlagunas** [comment]
There is not enough information to in this post to help us confidently pin-point your issue, and you have not provided a reduction link.  My best guess is that you want to reset the navigation stack, so you need to use an absolute URI by prefixing your nav path with a "/".  So for example; `/NavigationPage/LoginPage`/
