### ISSUE TITLE
Task<DelegateCommand>

### ISSUE THREAD

**Issue by wjkhappy14** [PrismLibrary/Prism#1455]
### Steps to Reproduce

1.  can i use  async  action   for button click  event  . eg:Task<DelegateCommand>   
 

### Basic Information

- Version with issue:
- Last known good version:
- Xamarin.Forms version:
- IDE:

**Comment by bartlannoeye** [comment]
Questions should be asked on [StackOverflow](https://stackoverflow.com/questions/tagged/prism). Only bugs and feature requests can be logged here.
