### ISSUE TITLE
Relative back navigation does not work with INavigationParameters

### ISSUE THREAD

**Issue by Dresel** [PrismLibrary/Prism#1456]
### Description

`NavigationService.NavigateAsync` in combination with relative back navigation does not work with `INavigationParameters`.

### Steps to Reproduce

1.  Call `NavigationService.NavigateAsync` with relative back navigation e.g. `../../` and some `INavigationParameters` parameter

### Expected Behavior

The `INavigationParameters` passed to `OnNavigatingTo` or `OnNavigatedTo` should contain the parameters given to `NavigationService.NavigateAsync`.

### Actual Behavior

The `INavigationParameters` passed to `OnNavigatingTo` or `OnNavigatedTo` do not contain the parameters given to `NavigationService.NavigateAsync` because `RemoveAndGoBack` does not pass `parameters` to [GoBackAsync](https://github.com/PrismLibrary/Prism/blob/47b306a172a0f9aba0876a086e3a9738903855c7/Source/Xamarin/Prism.Forms/Navigation/PageNavigationService.cs#L385).

### Basic Information

- Version with issue: 7.1.0.135-pre

**Comment by brianlagunas** [comment]
Great catch! Thanks for the fix.
