### ISSUE TITLE
ContentPage.ToolbarItems after navigationService.NavigateAsync("/Login");

### ISSUE THREAD

**Issue by mammadkoma** [PrismLibrary/Prism#1458]
Hi
This is MainPage with ToolBar:
```
<ContentPage.ToolbarItems>
    <ToolbarItem Name="MenuItem1" Order="Primary" Text="My Sos Requests" Command="{Binding GoToMySosRequests}" Priority="0" />
    <ToolbarItem Name="MenuItem2" Order="Secondary" Text="Logout" Command="{Binding Logout}" Priority="1"  />
</ContentPage.ToolbarItems>
```

MainViewModel:
```
Logout = new BitDelegateCommand(async () =>
{
await securityService.Logout();
await navigationService.NavigateAsync("/Login");
});

```
LoginViewModel:

```
await securityService.LoginWithCredentials(UserName, Password, "Owner", "secret");
await navigationService.NavigateAsync("/Main");
```

App Class:
```
public App() : base(null)
{
   MainPage = new NavigationPage(new MainView());
}
```

Also ContentPages have Title attribute.

When I click LogOut and Login again ToolbarItems disappear in MainPage.
When I remove / (slash) before "/Login" or "/Main" , problem resolves.
But I don't want user can back to before page after login or after logout.
What should I do?

**Comment by mammadkoma** [comment]
<ContentPage.ToolbarItems>
    <ToolbarItem Name="MenuItem1" Order="Primary" Text="My Sos Requests" Command="{Binding GoToMySosRequests}" Priority="0" />
    <ToolbarItem Name="MenuItem2" Order="Secondary" Text="Logout" Command="{Binding Logout}" Priority="1"  />
</ContentPage.ToolbarItems>

**Comment by mammadkoma** [comment]
<ContentPage.ToolbarItems
    <ToolbarItem Name="MenuItem1" Order="Primary" Text="My Sos Requests" Command="{Binding GoToMySosRequests}" Priority="0" />
    <ToolbarItem Name="MenuItem2" Order="Secondary" Text="Logout" Command="{Binding Logout}" Priority="1"  />
</ContentPage.ToolbarItems>

**Comment by mammadkoma** [comment]
<ContentPage.ToolbarItems
    <ToolbarItem Name="MenuItem1" Order="Primary" Text="My Sos Requests" Command="{Binding GoToMySosRequests}" Priority="0" />
    <ToolbarItem Name="MenuItem2" Order="Secondary" Text="Logout" Command="{Binding Logout}" Priority="1"  />
</ContentPage.ToolbarItems

**Comment by mammadkoma** [comment]
<ToolbarItem Name="MenuItem1" Order="Primary" Text="My Sos Requests" Command="{Binding GoToMySosRequests}" Priority="0" />
    <ToolbarItem Name="MenuItem2" Order="Secondary" Text="Logout" Command="{Binding Logout}" Priority="1"  />

**Comment by brianlagunas** [comment]
You've already posted your question on SO which is the correct place to ask this question.

https://stackoverflow.com/questions/50622646/xamarin-contentpage-toolbaritems-after-navigationservice-navigateasync-login

**Comment by mammadkoma** [comment]
nobody know Please help me

**Comment by brianlagunas** [comment]
Your question is not clear and you have not provided enough information for anyone to help.  I suggest editing your SO question to include more detail and even a running sample that demonstrates the issue.

**Comment by mammadkoma** [comment]
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:ff="clr-namespace:FFImageLoading.Svg.Forms;assembly=FFImageLoading.Svg.Forms"
             x:Class="Sanaap.App.Views.MainView" Title="Main Page" x:Name="mainPage">
    <ContentPage.ToolbarItems>
        <ToolbarItem Name="MenuItem1" Order="Primary" Text="My Sos Requests" Command="{Binding GoToMySosRequests}" Priority="0" />
        <ToolbarItem Name="MenuItem2" Order="Secondary" Text="Logout" Command="{Binding Logout}" Priority="1"  />
    </ContentPage.ToolbarItems>

    <Grid>
        <Grid.RowDefinitions>
            <RowDefinition Height="80" />
            <RowDefinition Height="*" />
            <RowDefinition Height="*" />
            <RowDefinition Height="80" />
            <RowDefinition Height="*" />
        </Grid.RowDefinitions>
        <ff:SvgCachedImage Grid.Row="0" Source="resource://Sanaap.App.Images.SosRequest.svg"/>
        <Button Grid.Row="1" BackgroundColor="#ed1c24" TextColor="White" FontSize="Medium" VerticalOptions="Center" HorizontalOptions="Center" WidthRequest="110" HeightRequest="110" BorderRadius="10" Text="Help Me" Command="{Binding SubmitSosRequest}" />
        <ff:SvgCachedImage Grid.Row="3" Source="resource://Sanaap.App.Images.Operator.svg"/>
        <Button Grid.Row="4" BackgroundColor="#ed1c24" TextColor="White" FontSize="Medium" VerticalOptions="Center" HorizontalOptions="Center" WidthRequest="110" HeightRequest="110" BorderRadius="10" Text="Help Me" Command="{Binding SubmitSosRequestByCall}" />
    </Grid>
</ContentPage>

**Comment by mammadkoma** [comment]
```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:ff="clr-namespace:FFImageLoading.Svg.Forms;assembly=FFImageLoading.Svg.Forms"
             x:Class="Sanaap.App.Views.MainView" Title="سناپ" x:Name="mainPage">
    <ContentPage.ToolbarItems>
        <ToolbarItem Name="MenuItem1" Order="Primary" Text="مشاهده درخواستهای قبلی" Command="{Binding GoToMySosRequests}" Priority="0" />
        <ToolbarItem Name="MenuItem2" Order="Secondary" Text="خروج" Command="{Binding Logout}" Priority="1"  />
    </ContentPage.ToolbarItems>

    <Grid>
        <Grid.RowDefinitions>
            <RowDefinition Height="80" />
            <RowDefinition Height="*" />
            <RowDefinition Height="*" />
            <RowDefinition Height="80" />
            <RowDefinition Height="*" />
        </Grid.RowDefinitions>
        <ff:SvgCachedImage Grid.Row="0" Source="resource://Sanaap.App.Images.SosRequest.svg"/>
        <Button Grid.Row="1" BackgroundColor="#ed1c24" TextColor="White" FontSize="Medium" VerticalOptions="Center" HorizontalOptions="Center" WidthRequest="110" HeightRequest="110" BorderRadius="10" Text="کمکم کنید" Command="{Binding SubmitSosRequest}" />
        <ff:SvgCachedImage Grid.Row="3" Source="resource://Sanaap.App.Images.Operator.svg"/>
        <Button Grid.Row="4" BackgroundColor="#ed1c24" TextColor="White" FontSize="Medium" VerticalOptions="Center" HorizontalOptions="Center" WidthRequest="110" HeightRequest="110" BorderRadius="10" Text="کمکم کنید" Command="{Binding SubmitSosRequestByCall}" />
    </Grid>
</ContentPage>
```

**Comment by dansiegel** [comment]
again questions belong on StackOverflow. Update your question there so someone can help you.
