### ISSUE TITLE
Problems with NavigateAsync

### ISSUE THREAD

**Issue by mapsouza** [PrismLibrary/Prism#1459]
Hi...

 I´m a newbie with Prism.

I used this navigation command in my app from the master of masterdetail page:

`navigationService.NavigateAsync("NavigationPage/MainDetailPage?createTab=UsuarioPage&createTab=MensagensTabPage")`

The MainDetailPage and MensagensTabPage are Tabbed Pages. 

The tabs of MensagensTabPage I´m loaded from the XAML

When I try to load a content page from a tab inside of MessagesTabPage, it loaded as ModalNavigationPage and hide Toolbar and back button.

`navigationService.NavigateAsync("MensagemDetalhes")`

To workaround with this problem I added "?useModalNavigation=false" to navigation string and this worked. 

### Basic Information

- Version with issue:7.0.0.396 and 7.1.0.135-pre

- Xamarin.Forms version: 3.0.0.482510 and 3.1.0.469394-pre1
- IDE:

**Comment by kcabral817** [comment]
Hi Mapsouza,
Questions like these should be asked in StackOverflow as this area is for bugs dealing specifically with PRISM.  In the future, if you feel the problem is with the PRISM code base, you will be asked to provide a sample of the code so the developers can replicate the problem.

**Comment by brianlagunas** [comment]
Also, I am not seeing a question here. This is exactly how it works.

**Comment by mapsouza** [comment]
I thought the command without the parameter "useModalNavigation" shoulded have opened as non-modal page.

**Comment by brianlagunas** [comment]
No, because you are navigating from a tab within a TabbedPage.  If your Tab was nested within a NavigationPage, then it would have worked as you expected.  In this case the TabbedPage is nested within a NavigationPage, and since you are not navigating from the TabbedPage, you are not adding to the NaviagtionPage's nav stack.
