### ISSUE TITLE
PopupWindowAction with even CenterOverAssociatedObject="true" resulted popup screen opened in most right bottom corner 

### ISSUE THREAD

**Issue by RahulPureSoftware** [PrismLibrary/Prism#1461]
In  my application, PopupWindowAction with CenterOverAssociatedObject = "true" does not keep DefaultNotificationWindow in center. This popup opens in most bottom right corner. This is due to **use of "AssociatedObject" to calculate wrapperWindow.Top and wrapperWindow.Left properties (in Microsoft.Practices.Prism.Interactivity.PopupWindowAction.Invoke() method implementation)as I saw in Prism source code**.

and here ,  AssociatedObject is my view(UserControl)--> having those InteractionRequestTrigger. This view is not the one, which is directly on the region of my Shell window. In my Shell region, I am assigning a view from different module(that's View1). In View1, I created 3 rows of equal sizes and in middle row, I created 2 columns and in 2nd column , I made a tabcontrol region and my this view (whose viewmodel raises InteractionRequest) is assigned to this tabControl Region.

I hope, you understand my question.

Anybody please suggest what could be the best guess to resolve Shell view as AssociatedObject  in Microsoft.Practices.Prism.Interactivity.PopupWindowAction.Invoke() method implementation (whether that shellWindow.WindowState is Maximized or Normal) rather than InteractionRequest Raiser view.

**Comment by brianlagunas** [comment]
First of all, try upgrading to the latest version and see if it works as expected. Second of all, you did not provide a sample application that reproduces you issue so this results in the automatic close of your issue.

**Comment by RahulPureSoftware** [comment]
Thanks Brianlagunas. With latest prism binaries (version [7.1.0-pre1]), Popup can be centered on screen.
