### ISSUE TITLE
Add Xamarin Integration Tests

### ISSUE THREAD

**Issue by dansiegel** [PrismLibrary/Prism#1468]
### Description

Tests for Xamarin should be updated so that we continue to run all of the tests in a cross platform manner with netcoreapp but all of our tests also need to run inside of a Device Runner for at least iOS and Android. This will better assist us in uncovering issues that may exist on one platform or another such as when we had tests passing with netcoreapp for Ninject despite the fact that Ninject was not actually working on iOS or Android.

**Comment by brianlagunas** [comment]
This is stale and a dead effort.
