### ISSUE TITLE
NavigationParameter is also a Breaking change

### ISSUE THREAD

**Issue by YehudahA** [PrismLibrary/Prism#147]
In prism 5 if I use indexer like ```parameters["meyKey"] ``` and the key not exists, I get null.
In prism 6 it's lead to an exception and we need use parameters.TryGetValue.

I suggest to add it to the breaking change list.

**Comment by brianlagunas** [comment]
This has already been documented here:  https://github.com/PrismLibrary/Prism/wiki/Release-Notes---6.0.0

**Comment by YehudahA** [comment]
OK, thanks, I saw only this list https://github.com/PrismLibrary/Prism#breaking-changes

**Comment by brianlagunas** [comment]
Just so you now, we just reverted this back to the way is was in Prism 5.  v6.1 will have this change.
