### ISSUE TITLE
The InvokeCommandAction needs better path support.

### ISSUE THREAD

**Issue by myermian** [PrismLibrary/Prism#1471]
https://github.com/PrismLibrary/Prism/blob/379c80193556a20d34eb442c73fd05258f6ec3c3/Source/Wpf/Prism.Wpf/Interactivity/InvokeCommandAction.cs#L113

The `TriggerParameterPath.Invoke(object parameter)` method needs better path support.

1. The `TriggerParameterPath` property should be of type `PropertyPath` (not string).
2. Support the standard XAML PropertyPath syntaxing.

For example, the TriggerParameterPath does not support indexing: `TriggerParameterPath="AddedItems[0]"`.

**Comment by brianlagunas** [comment]
Actually, I am leaning more towards creating a brand new EventToCommandBehvaior instead of using the interactivity features.

**Comment by CorsairRO** [comment]
Hello,

Just as a question there: 
Is there any EventToCommandBehavior for PRISM.WPF?

I saw how it works in Prism.Forms and it will be exactly what I need there, but I don't find this nice behavior in WPF version.

I wouldn't add Prism.Forms in my app ( WPF app ) just to get this behavior...

---
My usage purpose is for Drag and Drop functionality in a WPF MVVM PRISM app.

User Drags from a View Control ( The Control sets Data to DragDrop object from System.Windows )
It works ok.

But in my VM ( agnostic of WPF ) I hook up to the Drop event of a control and call a command from VM.
I use Blend Interactivity and Prism InvokeCommandAction

Now, the received object using prism:InvokeCommandAction is of type DragEventArgs ( which belongs to WPF ) 

Behavior that I saw in Xamarin it works exactly as I wish, to convert data out of the DragEvetnArgs in a format that my VM understands.

Thank you very much for your answer...

**Comment by CorsairRO** [comment]
Hello again,

thank you for your answers if they will be ....

I moved away from the issue by adding a Service to my VM project as an interface, where I pass an OBJECT ( my DelegateCommand<object> )

The prism:InvokeCOmmandAction for evetn Drop passes a DragEventArgs to the command as an object.

In implementation of the service which is in WPF project, I cast the object to DragEventArgs and pull out the data that I need and return to my VM.


Thank you again for the wonderful framework that you have put into PRISM ( that I use it around 20-30% of its potential  and it is already wonderful ... )

**Comment by brianlagunas** [comment]
@myermian  I am starting to look at this and I was just curious how using the PropertyPath type would be beneficial? PropertPath.Path is just a string, and reflection would still need to be done in order to get any nested values.

**Comment by brianlagunas** [comment]
Since I am now a project maintainer for the Microsoft WPF Behaviors, I am working on improving the MS InvokeCommandAction and then deprecating the Prism version.
