### ISSUE TITLE
Absolute redirect in OnNavigatedTo

### ISSUE THREAD

**Issue by MaximBalaganskiy** [PrismLibrary/Prism#1473]
### Description
I'm implementing a Login-Main scenario. 
When the main page is navigated to it calls a service to check login status and redirects to a login page. The redirect has to be absolute so that back action is impossible. Stepping through the code I can see that login view model and page get created on this redirect but the page does not appear on a screen.
At the same time, absolute navigating on a button click works fine, as well as navigating to a relative uri.

### Steps to Reproduce
1.  Add a login content page
2. Navigate to NavigationPage/LoginPage with an absolute URI

### Expected Behavior
Login page shows up

### Actual Behavior
Login page classes get instantiated but not shown

### Basic Information
- Version with issue: 7.0.0.396
- Last known good version: NA
- Xamarin.Forms version: 2.5.0.122203 (I've also tried 3.0.0.561731 with the same result)
- IDE: VS2017

### Reproduction Link
https://github.com/MaximBalaganskiy/XamarinPrismAbsoluteNavigation

**Comment by AmrAlSayed0** [comment]
Absolute Navigation is done by navigation to "app://www.putwhateveryouwanthere.com/NavigationPage/LoginPage" which is effectively like Application.Current.MainPage = new NavigationPage ( new LoginPage() );<br /><br />You can completely ignore the domain part and do app:///NavigationPage/LoginPage<br />But I don't think the slash before the navigation URL is a recognized syntax by PRISM

**Comment by MaximBalaganskiy** [comment]
According to several posts by Brian it is. And "app:///" does not work
either. Prefixing with slash works in a command, just not in OnNavigatedTo

**Comment by MaximBalaganskiy** [comment]
`await Task.Yield();` before navigation solves the issue

**Comment by brianlagunas** [comment]
You just need to await the navigation call. No need to add the Task.Yield.
