### ISSUE TITLE
Getting error "Could not load type 'Prism.Modularity.IModuleManager' from assembly Prism.Wpf"

### ISSUE THREAD

**Issue by dgxhubbard** [PrismLibrary/Prism#1478]
We just loaded release 7.1.0.172-pre. We recieve the error "Could not load type IModuleManager" when our app starts. We are using Prism.Core 7.1.0.172-pre also which has the definition of IModuleManager.

I don't know if this is related, but we have implemented 

protected override IContainerExtension CreateContainerExtension ()
{
    return null;
}

**Comment by dansiegel** [comment]
Please try deleting the output folders (obj/bin), restore and build. Also I am closing this as this has no sample reproducing the issue. If you are able to provide a sample I will be happy to take a look and re-evaluate further.

**Comment by dgxhubbard** [comment]
I did a clean build by deleting everything then building. Sorry you closed the issue. Our apps are to big to put into a sample. We reverted to previous version to get around issue.

**Comment by dansiegel** [comment]
@dgxhubbard as the Issue template specifies, you must provide information in an issue including a sample that reproduces the issue you are experiencing. You do not need to provide your entire app, just a sample that demonstrates the specific issue you are encountering.
