### ISSUE TITLE
Sample HelloWorld errors out of the box

### ISSUE THREAD

**Issue by isvaljek** [PrismLibrary/Prism#148]
I get this errors when I try to build HelloWorld sample on VS2015:

Severity	Code	Description	Project	File	Line
Error	CS0234	The type or namespace name 'Windows' does not exist in the namespace 'Prism' (are you missing an assembly reference?)	Prism.Unity.Windows	C:\Users\ivan\Desktop\Prism-master\Source\Windows10\Prism.Unity.Windows\PrismUnityApplication.cs	9
Error	CS0234	The type or namespace name 'Windows' does not exist in the namespace 'Prism' (are you missing an assembly reference?)	Prism.Unity.Windows	C:\Users\ivan\Desktop\Prism-master\Source\Windows10\Prism.Unity.Windows\PrismUnityApplication.cs	10
Error	CS0234	The type or namespace name 'Windows' does not exist in the namespace 'Prism' (are you missing an assembly reference?)	Prism.Unity.Windows	C:\Users\ivan\Desktop\Prism-master\Source\Windows10\Prism.Unity.Windows\PrismUnityApplication.cs	11
Error	CS0246	The type or namespace name 'PrismApplication' could not be found (are you missing a using directive or an assembly reference?)	Prism.Unity.Windows	C:\Users\ivan\Desktop\Prism-master\Source\Windows10\Prism.Unity.Windows\PrismUnityApplication.cs	22
Warning	CS0109	The member 'PrismUnityApplication.Current' does not hide an inherited member. The new keyword is not required.	Prism.Unity.Windows	C:\Users\ivan\Desktop\Prism-master\Source\Windows10\Prism.Unity.Windows\PrismUnityApplication.cs	47
Error	CS0115	'PrismUnityApplication.OnInitializeAsync(IActivatedEventArgs)': no suitable method found to override	Prism.Unity.Windows	C:\Users\ivan\Desktop\Prism-master\Source\Windows10\Prism.Unity.Windows\PrismUnityApplication.cs	66
Error	CS0115	'PrismUnityApplication.Resolve(Type)': no suitable method found to override	Prism.Unity.Windows	C:\Users\ivan\Desktop\Prism-master\Source\Windows10\Prism.Unity.Windows\PrismUnityApplication.cs	81
Error	CS0030	Cannot convert type 'Windows.UI.Xaml.Application' to 'Prism.Unity.Windows.PrismUnityApplication'	Prism.Unity.Windows	C:\Users\ivan\Desktop\Prism-master\Source\Windows10\Prism.Unity.Windows\PrismUnityApplication.cs	47
Error	CS0246	The type or namespace name 'ISessionStateService' could not be found (are you missing a using directive or an assembly reference?)	Prism.Unity.Windows	C:\Users\ivan\Desktop\Prism-master\Source\Windows10\Prism.Unity.Windows\PrismUnityApplication.cs	134
Error	CS0103	The name 'SessionStateService' does not exist in the current context	Prism.Unity.Windows	C:\Users\ivan\Desktop\Prism-master\Source\Windows10\Prism.Unity.Windows\PrismUnityApplication.cs	134
Error	CS0246	The type or namespace name 'INavigationService' could not be found (are you missing a using directive or an assembly reference?)	Prism.Unity.Windows	C:\Users\ivan\Desktop\Prism-master\Source\Windows10\Prism.Unity.Windows\PrismUnityApplication.cs	135
Error	CS0103	The name 'NavigationService' does not exist in the current context	Prism.Unity.Windows	C:\Users\ivan\Desktop\Prism-master\Source\Windows10\Prism.Unity.Windows\PrismUnityApplication.cs	135
Error	CS0246	The type or namespace name 'IDeviceGestureService' could not be found (are you missing a using directive or an assembly reference?)	Prism.Unity.Windows	C:\Users\ivan\Desktop\Prism-master\Source\Windows10\Prism.Unity.Windows\PrismUnityApplication.cs	136
Error	CS0103	The name 'DeviceGestureService' does not exist in the current context	Prism.Unity.Windows	C:\Users\ivan\Desktop\Prism-master\Source\Windows10\Prism.Unity.Windows\PrismUnityApplication.cs	136
Error		The name "PrismApplication" does not exist in the namespace "using:Prism.Windows".	HelloWorld	C:\Users\ivan\Desktop\Prism-master\Samples\Windows10\HelloWorld\HelloWorld\App.xaml	1
Error		The member "Resources" is not recognized or is not accessible.	HelloWorld	C:\Users\ivan\Desktop\Prism-master\Samples\Windows10\HelloWorld\HelloWorld\App.xaml	1
Error		The name "VisualStateAwarePage" does not exist in the namespace "using:Prism.Windows.Mvvm".	HelloWorld	C:\Users\ivan\Desktop\Prism-master\Samples\Windows10\HelloWorld\HelloWorld\Views\MainPage.xaml	1
Error		The name "ViewModelLocator" does not exist in the namespace "using:Prism.Windows.Mvvm".	HelloWorld	C:\Users\ivan\Desktop\Prism-master\Samples\Windows10\HelloWorld\HelloWorld\Views\MainPage.xaml	10
Error		The name "VisualStateAwarePage" does not exist in the namespace "using:Prism.Windows.Mvvm".	HelloWorld	C:\Users\ivan\Desktop\Prism-master\Samples\Windows10\HelloWorld\HelloWorld\Views\MainPage.xaml	11
Error		The name "BooleanToVisibilityConverter" does not exist in the namespace "using:HelloWorld.Converter".	HelloWorld	C:\Users\ivan\Desktop\Prism-master\Samples\Windows10\HelloWorld\HelloWorld\Views\MainPage.xaml	12

**Comment by bartlannoeye** [comment]
Are you using the AnyCPU build configuration? Try building the solution under x86, does that fix the errors? UWP apps are not supposed to have AnyCPU anymore.

**Comment by isvaljek** [comment]
That was it, thank you.
Can you give just one more direction, I'm trying to migrate an app from Prism 5 to 6, but can't seem to find nuget package called Prism.Windows.
Is is the only way to include the source project into mine?

**Comment by bartlannoeye** [comment]
Right now the UWP packages for Prism 6 are not on NuGet yet, so yes you'll have to add the source code for now. I'm expecting the team will push the packages soon as they are closing up the final blocking bugs for RTM.

**Comment by briannoyes** [comment]
@isvaljek If you were on Prism 5 that implies WPF. Prism.Windows is for Windows 10 UWP development. You would want Prism 6 for WPF. If you just search on Prism 6 in NuGet you will see Prism.Wpf and the associated libraries for whatever container you want (Unity, Autofac, etc).

**Comment by isvaljek** [comment]
@briannoyes But then where do i point xmlns:prism namespace to get to ViewModelLocator.AutoWireViewModel?

**Comment by briannoyes** [comment]
Its now part of the http://prismlibrary.com alias, same as everything else you would use in WPF XAML - so you just need that one xmlns:prism="http://prismlibrary.com" and you should be able to get to ViewModelLocator, RegionManager, InvokeCommandAction,, etc.

**Comment by isvaljek** [comment]
To me this didn't work but this did: xmlns:prism="http://www.codeplex.com/prism". But now I can't seem to find the replacement for SetProperty,

**Comment by isvaljek** [comment]
The SetProperty is still in BindableBase, someone told me it's not necessary any more, so i removed it.

**Comment by briannoyes** [comment]
I think you have to have a trailing / on http://prismlibrary.com/

BindableBase is still what you should be using for the base class for any ViewModel or Model objects to get the INotifyPropertyChanged implementation.

**Comment by brianlagunas** [comment]
Whoever told you that is wrong.  As Brian Noyes says, BindableBase and SetProperty are still the recommended way to provide INPC.
