### ISSUE TITLE
back button in master detail page

### ISSUE THREAD

**Issue by mammadkoma** [PrismLibrary/Prism#1481]
Im using prism with my xamarin forms application. i use master detail with the exact structure that you used but when i change detail page my back button wont work and when i click on back button in android it just close the app. and also the back button in toolbar wont show either. how can i fix this?
this picture belongs to time that i`ve changed the detail page that you can see there is no back button there
- Version with issue: 7.0.0.396
- Xamarin.Forms version: 3.0.0.482510
- IDE: 15.7.1

### Screenshots

![image](https://user-images.githubusercontent.com/17564001/41809589-359d270e-7705-11e8-8dbf-57c53fe7418c.png)

**Comment by AwsomeCode** [comment]
This is not related to prism. Use the Stackoverflow.com for this kind of question.
