### ISSUE TITLE
AutowireViewModel True required even when convention is not followed

### ISSUE THREAD

**Issue by S1r-Lanzelot** [PrismLibrary/Prism#1482]
### Description
I am not following the View/Viewmodel naming conventions however when setting `prism:ViewModelLocator.AutowireViewModel="False"` or omitting entirely, prism fails to find my VM when navigating.

I am explicitly registering the association with `RegisterForNavigation<MyView, SomeVM<Class>>()`. I worry that my use of a generic VM is causing an issue. 

Please take a look at the example solution and remove the `prism:ViewModelLocator.AutowireViewModel="True"` in the views or set it to `False`. (I tried `false` as well). Additionally, I find it odd that removing the line will break the wiring as well because doesn't it default to True if null? Per https://github.com/PrismLibrary/Prism/pull/703

I would be very surprised if this is a bug but I am confused what is wrong here. At the very least, the experienced functionality is very confusing to me as a developer.

Thanks.

### Steps to Reproduce

1. Create a generic VM and manually configure it with multiple views using `RegisterForNavigation`. These should not follow the autowire naming conventions
2. Remove the AutoWire setting in the view

### Expected Behavior
The views are wired correctly to the VM as it is configured with registerfornavigation

### Actual Behavior
When set to True, the views wire up correctly in some bizarre way... How does it autowire if the conventions are not followed? Setting autowire to false breaks the view/vm wiring. 

### Basic Information
- Tested only with Android Emulator 8.1
- Last known good version: N/A
- Xamarin.Forms version: v7.1.0.172-pre
- Xamarin.DryIoc.Forms version: v7.1.0.172-pre
- IDE: VS 2017 15.7.4

### Reproduction Link
**You will need to set autowire=false to see it not work**
[App4.zip](https://github.com/PrismLibrary/Prism/files/2130218/App4.zip)

**Comment by dansiegel** [comment]
1. Your sample doesn't even build
1. Your sample is not using a PrismApplication
1. Your sample has both Views & ViewModels in the root namespace without setting `ViewModelLocationProvider.SetDefaultViewModelFactory` which we do in PrismApplication{Base} in `ConfigureViewModelLocator` 
1. You can also bypass convention entirely when using the registration methods that take both the View and ViewModel. This means you could have `Contoso.StuffToLookAt.ViewA` with a ViewModel `Foo.BarViewModel` such as

```cs
containerRegistry.RegisterForNavigation<ViewA, BarViewModel>();
```

Also worth noting here that the ViewModelLocator is NOT an Opt-In feature, it is specifically Opt-Out.  This means that you are not required to set the attached property on any page handled by the NavigationService, as it will set it to `true` if the property was not explicitly set to `false`. You only need to explicitly set the value to `true` in the event that you are bypassing Prism Navigation altogether such as in your sample.

**Comment by S1r-Lanzelot** [comment]
@dansiegel  I initially messed up when creating the ticket and loaded the wrong sample app with the ticket... I think you opened that one (maybe you got it in a github email). If you have time, try redownloading the edited I uploaded later on Saturday, the current zip works. Sorry for the confusion.

Thanks. The corrected sample does use the `PrismApplication` base:

```
public partial class App : PrismApplication
	{
        public App(IPlatformInitializer initializer = null) : base(initializer) { }

        protected override void RegisterTypes(IContainerRegistry containerRegistry)
        {
            containerRegistry.RegisterForNavigation<DoubleByePage, TwoVM<ByeClass>>();
            containerRegistry.RegisterForNavigation<HiPage, OneVM<HeyClass>>();
            containerRegistry.RegisterForNavigation<ByePage, OneVM<ByeClass>>();
        }

		protected override void OnStart ()
		{
			// Handle when your app starts
		}

		protected override void OnSleep ()
		{
			// Handle when your app sleeps
		}

        protected override void OnInitialized()
        {
            InitializeComponent();
            NavigationService.NavigateAsync("HiPage");
        }

        protected override void OnResume ()
		{
			// Handle when your app resumes
		}
	}
```
