### ISSUE TITLE
Prism Template Studio and Developer Toolkit for Mac - Quickstart Prism Application

### ISSUE THREAD

**Issue by TNoronha** [PrismLibrary/Prism#1484]
### Description

Good afternoon,

I tried using the new Prism Template Pack for Mac and all but the Quickstart Prism Application works.
If we click on next after selection Quickstart Prism Application it doesn't do nothing
If I try selecting one of other ones after this, no template works.

### Steps to Reproduce

1. Install latest version of Prism Template Studio and Developer Toolkit
2. Select one of the template except Quickstart Prism Application one.
3. Select Quickstart Prism Application.
4. Try selecting other type of template.

### Expected Behavior
Dialog would procede.

### Actual Behavior
Nothing happens

### Basic Information

- Version with issue: 2.2.0.197
- Last known good version: N/A
- Xamarin.Forms version: N/A
- IDE: Visual Studio for Mac 7.5.3

### Reproduction Link

I uploaded a video of the bug:
https://streamable.com/g066b

**Comment by TNoronha** [comment]
I checked the logs and found this line: 
![image](https://user-images.githubusercontent.com/27889458/42124972-24c41ad6-7c65-11e8-9578-93c542492fd5.png)

**Comment by cbartonnh** [comment]
I am seeing the same issue. Once you try Quickstart, you cannot select any until exiting out of VS

**Comment by dansiegel** [comment]
This is fixed in 2.2.0.199
