### ISSUE TITLE
Set size for PopupWindowAction and show on CenterScreen

### ISSUE THREAD

**Issue by masgarifor2** [PrismLibrary/Prism#1485]
I Think there is a Bug.

I have a WPF project.

When I set size for PopupWindowAction, however, I set WindowStartupLocation="CenterScreen" but the window show out of the screen.

` <Style x:Key="WindowStyle" TargetType="Window">
                <Setter Property="Width" Value="500"/>
</Style>`

` <prism:InteractionRequestTrigger SourceObject="{Binding MyRequest}">
            <prism:PopupWindowAction IsModal="True" 
                                     CenterOverAssociatedObject="True" 
                                     WindowStartupLocation="CenterScreen"
                                     WindowStyle="{StaticResource WindowStyle}"
                                     WindowContentType="{x:Type views:MyView}"/>
        </prism:InteractionRequestTrigger>`

**Comment by dansiegel** [comment]
@masgarifor2 closing this as you haven't provided adequate information or a basic app that reproduces the issue.
