### ISSUE TITLE
QuickStart Prism Application not working 

### ISSUE THREAD

**Issue by pablogupi** [PrismLibrary/Prism#1488]
### Description
I created a new solution Visual Studio Community from Mac using Prism Template Studio and Developer Toolkit. When I run app using iOS emulator launch SplashScreen. When wait 4 segs, app stopped and return this log:

`Objective-C exception thrown.  Name: NSInternalInconsistencyException Reason: Application windows are expected to have a root view controller at the end of application launch
Native stack trace:
	0   CoreFoundation                      0x00000001192661e6 __exceptionPreprocess + 294
	1   libobjc.A.dylib                     0x0000000119f29031 objc_exception_throw + 48
	2   CoreFoundation                      0x000000011926b472 +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x000000011573e652 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 193
	4   UIKit                               0x00000001134deb36 -[UIApplication _runWithMainScene:transitionContext:completion:] + 3064
	5   UIKit                               0x00000001138a0f7e __111-[__UICanvasLifecycleMonitor_Compatability _scheduleFirstCommitForScene:transition:firstActivation:completion:]_block_invoke + 866
	6   UIKit                               0x0000000113c73a39 +[_UICanvas _enqueuePostSettingUpdateTransactionBlock:] + 153
	7   UIKit                               0x00000001138a0bba -[__UICanvasLifecycleMonitor_Compatability _scheduleFirstCommitForScene:transition:firstActivation:completion:] + 236
	8   UIKit                               0x00000001138a13db -[__UICanvasLifecycleMonitor_Compatability activateEventsOnly:withContext:completion:] + 675
	9   UIKit                               0x0000000114212614 __82-[_UIApplicationCanvas _transitionLifecycleStateWithTransitionContext:completion:]_block_invoke + 299
	10  UIKit                               0x00000001142124ae -[_UIApplicationCanvas _transitionLifecycleStateWithTransitionContext:completion:] + 433
	11  UIKit                               0x0000000113ef675d __125-[_UICanvasLifecycleSettingsDiffAction performActionsForCanvas:withUpdatedScene:settingsDiff:fromSettings:transitionContext:]_block_invoke + 221
	12  UIKit                               0x00000001140f14b7 _performActionsWithDelayForTransitionContext + 100
	13  UIKit                               0x0000000113ef6627 -[_UICanvasLifecycleSettingsDiffAction performActionsForCanvas:withUpdatedScene:settingsDiff:fromSettings:transitionContext:] + 223
	14  UIKit                               0x0000000113c730e0 -[_UICanvas scene:didUpdateWithDiff:transitionContext:completion:] + 392
	15  UIKit                               0x00000001134dceac -[UIApplication workspace:didCreateScene:withTransitionContext:completion:] + 515
	16  UIKit                               0x0000000113aafbcb -[UIApplicationSceneClientAgent scene:didInitializeWithEvent:completion:] + 361
	17  FrontBoardServices                  0x000000011fa602f3 -[FBSSceneImpl _didCreateWithTransitionContext:completion:] + 331
	18  FrontBoardServices                  0x000000011fa68cfa __56-[FBSWorkspace client:handleCreateScene:withCompletion:]_block_invoke_2 + 225
	19  libdispatch.dylib                   0x000000011b05d709 _dispatch_client_callout + 8
	20  libdispatch.dylib                   0x000000011b0628c1 _dispatch_block_invoke_direct + 317
	21  FrontBoardServices                  0x000000011fa94470 __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 24
	22  FrontBoardServices                  0x000000011fa9412e -[FBSSerialQueue _performNext] + 439
	23  FrontBoardServices                  0x000000011fa9468e -[FBSSerialQueue _performNextFromRunLoopSource] + 45
	24  CoreFoundation                      0x0000000119208bb1 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	25  CoreFoundation                      0x00000001191ed4af __CFRunLoopDoSources0 + 271
	26  CoreFoundation                      0x00000001191eca6f __CFRunLoopRun + 1263
	27  CoreFoundation                      0x00000001191ec30b CFRunLoopRunSpecific + 635
	28  GraphicsServices                    0x000000011d680a73 GSEventRunModal + 62
	29  UIKit                               0x00000001134e0057 UIApplicationMain + 159
	30  ???                                 0x00000001394c2c07 0x0 + 5256260615
	31  ???                                 0x00000001394c2963 0x0 +`

If try run in Android, when compile return this error and stop compilation:

`/Users/pgp/.nuget/packages/mobile.buildtools/1.3.0.599/build/Mobile.BuildTools.targets(5,5): Error MSB4095: The item metadata %(Filename) is being referenced without an item name.  Specify the item name by using %(itemname.Filename). (MSB4095) (AppTest.Droid)`

When I create a new solution using Blank Prism Application, the solution runs correctly in all platforms.

When 
### Steps to Reproduce

1. Create new solution using Prism Template Studio and Developer Toolkit
2. Select QuickStar Prism Application 
3. Run debug in Android or iOS. 

-Version Prism Template Studio: 2.2.0.199
- Version with issue: 7.0.0.396
- Last known good version: I don't know 
- Xamarin.Forms version: 3.1.0.583944
- IDE: Visual Studio for Mac Community 7.5.3 (build 7)

Thanks a lot

**Comment by dansiegel** [comment]
Thanks for reporting the issue. I actually just fixed this in the templates this morning and it will be in the next release. To fix the issue you can add the following to the ElementStyling XAML

```xml
<ResourceDictionary.MergedDictionaries>
  <theming:ColorPalette />
</ResourceDictionary.MergedDictionaries>
```

**Comment by pablogupi** [comment]
Thank a lot! I modify in ElementStyling.xaml like this: 
`<?xml version="1.0" encoding="UTF-8"?>
<ResourceDictionary xmlns="http://xamarin.com/schemas/2014/forms" xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" x:Class="ProjectName.Theming.ElementStyling" xmlns:theming="using:ProjectName.Theming">
    <Style TargetType="NavigationPage" ApplyToDerivedTypes="true">
        <Setter Property="BarTextColor" Value="{StaticResource NavigationText}" />
        <Setter Property="BarBackgroundColor" Value="{StaticResource PrimaryDark}" />
    </Style>
    <Style TargetType="TabbedPage" ApplyToDerivedTypes="true">
        <Setter Property="BarTextColor" Value="{StaticResource NavigationText}" />
        <Setter Property="BarBackgroundColor" Value="{StaticResource PrimaryDark}" />
    </Style>
    <ResourceDictionary.MergedDictionaries>
  <theming:ColorPalette />
</ResourceDictionary.MergedDictionaries>
</ResourceDictionary> 

and work fine on iOS. On android still does not work. Return this error: 
/Users/user/.nuget/packages/mobile.buildtools/1.3.0.599/build/Mobile.BuildTools.targets(5,5): Error MSB4095: The item metadata %(Filename) is being referenced without an item name.  Specify the item name by using %(itemname.Filename). (MSB4095) (ProjectName.Droid)

What is the problem? Thanks

**Comment by dansiegel** [comment]
@pablogupi see https://github.com/dansiegel/Mobile.BuildTools/issues/33

**Comment by pablogupi** [comment]
Perfect!Change code to: 

```
Copy SourceFiles="$(__Generated_APK)"
DestinationFiles="$(BuildToolsArtifactOutputPath)%(itemname.Filename)%(Extension)" /
```

works correctly. Thanks a lot and great job!
