### ISSUE TITLE
RegisterTypeForNavigation not working when add name

### ISSUE THREAD

**Issue by topfunet** [PrismLibrary/Prism#1490]
this issue be similar to to follow two issues.
https://github.com/PrismLibrary/Prism/issues/1161
https://github.com/PrismLibrary/Prism/issues/1120

But i'm using DryIoc,so how can i implement RegionNavigationContentLoader?

**Comment by dansiegel** [comment]
Closing as there is no sample app to demonstrate the issue.

**Comment by topfunet** [comment]
I'm sorry, my bad.
I create a project to demonstrate the issue.
https://github.com/topfunet/PrismNavigationBugDemo

I created a TestView and TestViewModel, then in Bootstrapper i use this line register it:
Container.RegisterTypeForNavigation<TestView>("test");
then when i use _regionManager.RequestNavigate("ContentRegion", "test") found that TestViewModel's IsNavigationTarget never gets called.

**Comment by brianlagunas** [comment]
@topfunet See http://prismlibrary.github.io/docs/wpf/Navigation.html#navigating-to-existing-views

"Note: For Prism to determine the type of the target view, the view's name in the navigation URI should be the same as the actual target type's short type name. For example, if your view is implemented by the MyApp.Views.EmployeeDetailsView class, the view name specified in the navigation URI should be EmployeeDetailsView. This is the default behavior provided by Prism. You can customize this behavior by implementing a custom content loader class; you can do this by implementing the IRegionNavigationContentLoader interface or by deriving from the RegionNavigationContentLoader class."

**Comment by topfunet** [comment]
thank you very much.
I already solved this.
