### ISSUE TITLE
Prism Template Pack creates iOS and UWP projects even when unchecked

### ISSUE THREAD

**Issue by reiniellematt** [PrismLibrary/Prism#1491]
The Prism Template Pack lets me choose what platforms I want to support. But when I create a new project, it still creates all projects but imports only the platform/s I chose. Sure those can be deleted but it just is a little bit of a hassle.

### Steps to Reproduce

1.  Create a new Prism Blank App(Xamarin.Forms)
2. Uncheck iOS or UWP or Android(IoC container is whatever you like)
3. Create Project

Prism Template Pack version 2.0.9

**Comment by dansiegel** [comment]
This issue has been fixed and will be in the next release.
