### ISSUE TITLE
Is the Prism.Wpf v7.1.0.172-pre NuGet package contents correct?

### ISSUE THREAD

**Issue by toras9000** [PrismLibrary/Prism#1492]
"System.Windows.Interactivity.dll" is not included in the NuGet package of Prism.Wpf v7.1.0.172-pre.
This file was included in the package of v7.1.0.123-pre.

The repository still maintains "System.Windows.Interactivity.dll", but is the intentional change of package contents?

(This depends on translation tools. I am sorry if there are strange sentences.)

**Comment by dansiegel** [comment]
It appears the recent updates to the way we pack Prism.Wpf resulted in `System.Windows.Interactivity` being stripped out. This should be getting packed. I'll look into this and we should have a fix in the CI feed soon.
