### ISSUE TITLE
Prism.Ninject 7.1.0.172-pre cannot start app

### ISSUE THREAD

**Issue by urosek** [PrismLibrary/Prism#1493]
### Description

I've created a new blank WPF project, added references to Prism.Wpf and Prism.Ninject and updated App.xaml and App.xaml.cs files accordingly. On trying to start the application, a Ninject error is thrown:

> Ninject.ActivationException: 'Error activating IRegionBehaviorFactory
> No matching bindings are available, and the type is not self-bindable.
> Activation path:
>   2) Injection of dependency IRegionBehaviorFactory into parameter regionBehaviorFactory of constructor of type SelectorRegionAdapter
>   1) Request for SelectorRegionAdapter
> 
> Suggestions:
>   1) Ensure that you have defined a binding for IRegionBehaviorFactory.
>   2) If the binding was defined in a module, ensure that the module has been loaded into the kernel.
>   3) Ensure you have not accidentally created more than one kernel.
>   4) If you are using constructor arguments, ensure that the parameter name matches the constructors parameter name.
>   5) If you are using automatic module loading, ensure the search path and filters are correct.

**App.xaml**
```
<prism:PrismApplication  x:Class="BlankApp2.App"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:prism="http://prismlibrary.com/">
    <prism:PrismApplication.Resources>
         
    </prism:PrismApplication.Resources>
</prism:PrismApplication>
```

**App.xaml.cs**
```
    public partial class App : PrismApplication
    {
        protected override Window CreateShell()
        {
            return ServiceLocator.Current.GetInstance<MainWindow>();
        }

        protected override void RegisterTypes(IContainerRegistry containerRegistry)
        {

        }
    }
```

### Steps to Reproduce

1. Create a new blank WPF application
2. Add references to Prism.Wpf and Prism.Ninject, version 7.1.0.172-pre
3. Update App.xaml and App.xaml.cs as above

### Expected Behavior
Application opens.

### Actual Behavior
Throws Ninject.ActivationException.

### Basic Information
I checked Ninject.Wpf sources and there is in fact binding for class IRegionBehaviorFactory, so I am not sure what could be wrong.

**PrismApplicationBase.cs**
```
        protected virtual void RegisterRequiredTypes(IContainerRegistry containerRegistry)
        {
            containerRegistry.RegisterInstance(_containerExtension);
            containerRegistry.RegisterInstance(_moduleCatalog);
            containerRegistry.RegisterSingleton<ILoggerFacade, TextLogger>();
            containerRegistry.RegisterSingleton<IModuleInitializer, ModuleInitializer>();
            containerRegistry.RegisterSingleton<IModuleManager, ModuleManager>();
            containerRegistry.RegisterSingleton<RegionAdapterMappings>();
            containerRegistry.RegisterSingleton<IRegionManager, RegionManager>();
            containerRegistry.RegisterSingleton<IEventAggregator, EventAggregator>();
            containerRegistry.RegisterSingleton<IRegionViewRegistry, RegionViewRegistry>();

            // Binding
            containerRegistry.RegisterSingleton<IRegionBehaviorFactory, RegionBehaviorFactory>();

            containerRegistry.Register<IRegionNavigationJournalEntry, RegionNavigationJournalEntry>();
            containerRegistry.Register<IRegionNavigationJournal, RegionNavigationJournal>();
            containerRegistry.Register<IRegionNavigationService, RegionNavigationService>();
        }
```

### Reproduction Link
[BlankApp2.zip](https://github.com/PrismLibrary/Prism/files/2179355/BlankApp2.zip)

**Comment by brianlagunas** [comment]
Fixed. You can test it out in the latest CI build.
