### ISSUE TITLE
Prism template app does't open up in LivePlayer

### ISSUE THREAD

**Issue by sturlath** [PrismLibrary/Prism#1494]
### Description
If I create a file->new -> Xamarin.Forms Prism project and try to run it in Visual Studio Live Player I get the following exception. Note that creating vanilla XF project **works just fine** so Prism must be doing something different that is causing this. 

### Steps to Reproduce

1.  Install Prism Template Pack version 2.0.9
2. File->New project -> Prism Xamarin.Form project.
3. Run Live Player on an iOS device.
4. I have tried this in VS Preview edition with same results.
5. And if I update every packet I get anothe error "Object reference not set to an instance of an object (NullReferenceException)"

### Expected Behavior
Should show the app in the LivePlayer

### Actual Behavior
The app does not show in LivePlayer but logs the following error
"Level=Error, Title=Visualization Error, Message=Constructor on type 'System.Collections.Concurrent.ConcurrentDictionary`2[[NInterpret.InterpretedValueType, NInterpret.Xamarin.iOS, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[NInterpret.InterpretedObject, NInterpret.Xamarin.iOS, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]' not found. (MissingMethodException)]"

### Basic Information

- Version with issue: Prism.Unity.Forms v7.0.0.396
- Last known good version:
- Xamarin.Forms version: 2.5.0.122203
- IDE: Visual Studio Professional

Microsoft Visual Studio Professional 2017 
Version 15.7.4
VisualStudio.15.Release/15.7.4+27703.2035
Microsoft .NET Framework
Version 4.7.03062

**Comment by sturlath** [comment]
Ok found the [reason ](https://docs.microsoft.com/en-us/xamarin/tools/live-player/limitations?tabs=android)

> Third party MVVM frameworks are not supported (ie. Prism, Mvvm Cross, Mvvm Light, etc.).

That makes the LivePlayer useless. Is there something that can be done to make it work? Is there a dialog between you and the LivePlayer team?

**Comment by dansiegel** [comment]
Nope nothing more you can do. Live Player is great for what it’s really meant for which is just learning about `Hello World` in Xamarin. The messaging was way off as a prototyping tool which it will never be useful for. I highly suggest you check out Live Reload or LiveXaml. They are both fantastic tools for prototyping and work well with Prism. I use them both personally.

**Comment by nrooban** [comment]
The only option we have is to use LiveXAML and it will only reload the XAML changes not the C#. 
If not convinced, better to switch to Flutter

**Comment by dansiegel** [comment]
@nrooban have fun it's not our job to convince you. Use what you need. That said if the fact that you get live reload is you basis for switching to Flutter you're making a pretty bad choice IMO. Flutter is far from a fully baked product and you'll find a lot of pain points. Good luck.

**Comment by nrooban** [comment]
@dansiegel I am not into promote any other products or such & I admire what you guys doing for the community. Otherwise I wont coming to this thread. So big thank you for that. At the same time, I am bit confused with 'Flutter is far from a fully baked product and you'll find a lot of pain points'. I have already done 3 projects with lesser time with no pain and most importantly enjoyed the coding comparing to any other. 

If you can describe the pain points hope it will be helpful to the community to know more.
