### ISSUE TITLE
Prism.Mef exception

### ISSUE THREAD

**Issue by lihaoef** [PrismLibrary/Prism#1495]
### Description
When I use Prism.Mef to create a project with module,I enter the follow error:
“There is currently no moduleTypeLoader in the ModuleManager that can retrieve the specified module.”

### Steps to Reproduce

1. `public class ModuleB : IModule
    {
        public void Initialize()
        {
            ServiceLocator.Current.GetInstance<IRegionManager>().RegisterViewWithRegion("RegionA", typeof(UserControl1));
        }
    }`
2. ` 
protected override DependencyObject CreateShell()
        {
            //return ServiceLocator.Current.GetInstance<Shell>();
            return this.Container.GetExportedValue<Shell>();
        }

        protected override void InitializeShell()
        {
            base.InitializeShell();
            App.Current.MainWindow = this.Shell as Window;
            App.Current.MainWindow.Show();
        }

        protected override void ConfigureModuleCatalog()
        {
            base.ConfigureModuleCatalog();
            this.ModuleCatalog.AddModule(new ModuleInfo(typeof(ModuleB).Name, typeof(ModuleB).AssemblyQualifiedName));
        }`
3. 

### Basic Information

- Version with issue:
- Last known good version:
- Xamarin.Forms version:
- IDE:

**Comment by lihaoef** [comment]
Any answer will be appreciated.Thanks.

**Comment by dansiegel** [comment]
You have provided no version information, and no reproduction. On top of those two issues is the fact that we have no intent of shipping any further MEF packages as we will no longer be supporting anything that is not a real DI container. I might add for those who like Autofac and SimpleInjector we are also very leery of continuing support for non-mutable containers as they provide very bad user experiences for our community.
