### ISSUE TITLE
NavigationParameters are not passed when using ../../

### ISSUE THREAD

**Issue by KalpeshChheda** [PrismLibrary/Prism#1497]
### Description

Hi. I am navigating back two pages using NavigationService.NavigateAsync("../../", SomeParameters);

Navigation is happening properly but at that page NavigationParameters of OnNavigatedTo method is empty.

We have tried single page back navigation. And it is working fine with parameters.

* Parameters passing >>>> NavigationService.NavigateAsync("../", SomeParameters); 
* Parameters not passing >> NavigationService.NavigateAsync("../../", SomeParameters);

### Steps to Reproduce

Do two page back navigation with parameters
 NavigationService.NavigateAsync("../../", SomeParameters);

### Expected Behavior
Navigating page should be having passed parameters.
### Actual Behavior
Empty parameters object.
### Basic Information
- Version with issue: 7.1 Pre 3
- Last known good version: N/A
- Xamarin.Forms version: 3.1
- IDE: 15.7.4

**Comment by brianlagunas** [comment]
This has already been fixed. Try the latest CI build on MyGet

https://github.com/PrismLibrary/Prism/pull/1457
