### ISSUE TITLE
Add support for other DI containers

### ISSUE THREAD

**Issue by brianlagunas** [PrismLibrary/Prism#15]
Right now, Prism supports Unity and MEF out of the box, but we would love to add support for other containers.

Some containers we should consider adding support for:
- Autofac
- Ninject
- StructureMap
- others?

If you would like to submit support for a container, use the Prism.Mef.Wpf, Prism.Unity.Wpf and Prism.Unity.Forms projects as a guideline.  As you can see the naming convention is Prism.<Container>.<Platform>.  The namespace should follow the Prism.<Container> convention and not include the platform.  For example, if using Autofac, the namespace should be Prism.Autofac.

**Comment by omares** [comment]
Would like to add https://simpleinjector.org to the list.

**Comment by brianlagunas** [comment]
These have been separated into individual issues.
