### ISSUE TITLE
Binding MouseDoubleClick to Command

### ISSUE THREAD

**Issue by isvaljek** [PrismLibrary/Prism#150]
How do we bind the doubleclick to a command in ViewModel?

**Comment by briannoyes** [comment]
Use InvokeCommandAction behavior with an EventTrigger hooked up to mouse double click event and the Command property of the behavior bound to your ViewModel command property.

**Comment by isvaljek** [comment]
Thanks, I was missing the xmlns:i="clr-namespace:System.Windows.Interactivity;assembly=System.Windows.Interactivity"
