### ISSUE TITLE
GetValue  not recognised on DataTemplateSelector

### ISSUE THREAD

**Issue by taxinvoice** [PrismLibrary/Prism#1500]
I'm using a listview with a DataTemplateSelector, and need to be able to subscribe to events(or bind to property in the DataTemplateSelector).   I have tried many methods with no avail...i have subscribed as  patreon hoping for some support also.  Main issue is that .GetValue  not recognised..
  <sync:SfListView.ItemTemplate>
            <local:MyDataTemplateSelector MyProperty="{Binding .}" ></local:MyDataTemplateSelector> 
        </sync:SfListView.ItemTemplate>

------------------------------------------------
    class MyDataTemplateSelector : Xamarin.Forms.DataTemplateSelector
    {

        public static BindableProperty MyPropertyContextProperty =
               BindableProperty.Create(nameof(MyProperty), typeof(string),            typeof(MyDataTemplateSelector), null);

        private string _Data;

        public object ParentBindingContext
        {
    get { return (string)GetValue (MyProperty); } //**GET ERROR doesn't recognise Getvalue**
            set {
                SetValue(MyProperty, value);
            }
        }
--------------------------------------------------------------------

**Comment by brianlagunas** [comment]
Thank you for becoming a patron. Unfortunately, this is not Prism related and is not the correct forum for this type of question. It appears you are using a Syncfusion control, so I suggest reaching out to them for help with their controls.

**Comment by taxinvoice** [comment]
ok thanks, though it would also be an issue for listview as well..but thanks anyway
