### ISSUE TITLE
Improve ViewModel testing support

### ISSUE THREAD

**Issue by chrisagzh** [PrismLibrary/Prism#1503]
### Description
In the original Prism 5 implementation there was support for the IView interface which allowed users to replace the View in integration test scenarios by a mockup. This no longer works because MvvmHelpers.ViewAndViewModelAction<T> requires that the View is a FrameworkElement in order to access the ViewModel via DataContext property, which is unfortunately very limiting:

1. Creating a FrameworkElement and setting its DataContext requires calls from an STA Thread whereas the unit test thread is usually MTA.

2. Creating FrameworkElement in tests requires access from the Dispatcher which makes the test setup considerably more difficult.

Optionally having an IView (or something similar) to navigate between View and ViewModel would greatly improve testing support for Prism by allowing pure ViewModel-based test scenarios. These are much more common than testing WPF Views.

### Basic Information

- Version with issue: 7.1.0
- IDE: Visual Studio 2017

**Comment by brianlagunas** [comment]
We will not be adding the IView interface back in. It should have never been added and is not required to test mock views in integration tests.

**Comment by chrisagzh** [comment]
It doesn't need to be IView if there is another approach to mock Views for navigation without having to use a Dispatcher and FrameworkElements.

**Comment by brianlagunas** [comment]
You are doing integration testing with a UI. You should use objects that represent actual UI elements. Otherwise, your tests will not represent the actual running environment and return invalid results.

**Comment by chrisagzh** [comment]
This is not always the case, actually almost never in my experience. I've developing WPF application for 10+ years and the usual practice is to do automated testing based on ViewModels only plus do manual testing for the Views (because you can't reach 100% View testing coverage anyway and those would be expensive to maintain plus UI tests are generally slow).
As a side note: Prism has always supported the View-first approach much better than the ViewModel-first approach. That's why people moved away from it, which is unfortunate because it is a good Framework.

**Comment by chrisagzh** [comment]
I am well aware of what the difference is between a unit test and an integration test. I used the term "automated testing". Integration tests can cover whole applications but they don't have to. Martin fowler explains it well here: https://martinfowler.com/bliki/IntegrationTest.html

How you deal with your test pyramid is up to you. On the other hand I know how I deal with mine and that involves writing some integration tests against my viewmodels.

A good framework doesn't impose a specific way how to write tests for code that uses the framework.

Microsoft knew that: In the old P&P Prism 5 implementatiin there was even a sample that showed this very scenario: PrismLibrary/Prism.Mvvm.Tests/Mocks/Mock.cs has an IView that is not a FrameworkElement. 

You could have just made IView optional instead of removing it and then pattern match it in MvvmHelpers. All relevant usages of the View DataContext use MvvmHelpers already.

**Comment by brianlagunas** [comment]
I was on the P&P team when we added the IView and it wasn't for view testability reasons.  It actualy had nothing to do with that.  It was specifically for the ViewModeLocator. Once that was introduced, it caused major design time crashes inside VS and it was also not compatible with Xamarin.  It also created a barrier to productivity and feature usage.  After tons of complaints and issues, a new approach was created and IView was removed.

**Comment by chrisagzh** [comment]
Great, now we're getting to the core of this!

In the Prism 5 sourcecode, there was a single relevant place in the code where the `IView` was actually used (see code below). Back then you could have used `FrameworkElement` instead of IView there, just like you do today. 

That would break your own code samples though! The only implementor of the `IView` in Prism 5 was a automated test that had a Mock View which **did implement the `IView` interface but at the same time didn't derive from FrameworkElement**.

This is exactly the sort of test I would like to write too. Your own code does the very thing you've just told me in length I shouldn't do. 

That said, I do not ask you to bring back `IView` the way it was. Bring it back, but make it optional. This does not break the designer but at the same time allows the type of automated tests again that you had in your sample code back in Prism 5.

```cs
public static void AutoWireViewModelChanged(IView view)
        {
            // Try mappings first
            object viewModel = GetViewModelForView(view);
            // Fallback to convention based
            if (viewModel == null)
            {
                var viewModelType = defaultViewTypeToViewModelTypeResolver(view.GetType());
                if (viewModelType == null) return;

                // Really need Container or Factories here to deal with injecting dependencies on construction
                viewModel = defaultViewModelFactory(viewModelType);
            }
            
            **view.DataContext = viewModel;**
        }
```

**Comment by brianlagunas** [comment]
Correct, as I mentioned, the only use of IView was the ViewModelLocator that you just highlighted. The intent of the test you are pointing out was meant to test the ViewModelLocator, not a UI. To introduce IView again would require changing every piece of code in Prism that checks for FrameworkElement.  Since this is the first time it has been requested, I do not consider it a candidate for implementation at this time.
