### ISSUE TITLE
INavigatedAware not in net45 lib folder

### ISSUE THREAD

**Issue by WebDucer** [PrismLibrary/Prism#1506]
### Description

We use Prism in our Xamarin applications and use havilly unit testing of our view models. Our unit test project is running with .Net 4.6.2. It works fine. Now we wanted to try the current preview version (especially of XAML navigation and DI in converters). Now all our tests fails, if the view model implements `INavigatedAware`.

The reason is: Version 7.0 and below has the class `NavigationParameter` and the interface `INavigatedAware` in the Prism.Forms package (.Net standard 2.0). With 7.1 it moves to Core library, that has `net45` version, that has no navigation implementation.

### Steps to Reproduce

1. Create Xamarin.Forms project with a view model that implements `INavigatedAware`
2. Create a .Net 4.6.2 test project (e.g. NUnit) and try to test the view model

```
System.TypeLoadException : Der Typ "Prism.Navigation.INavigatedAware" in der Assembly "Prism, Version=7.1.0.172, Culture=neutral, PublicKeyToken=40ee6c3a2184dc59" konnte nicht geladen werden.
   bei Xamarin.Common.Tests.ViewModels.ViewModelTests.SomeTest()
```

### Expected Behavior

The interface (and parameter type) should be implemented in all variations of Core library.

### Actual Behavior

The interface (and parameter type) not implemented for .Net 4.5

### Basic Information

- Version with issue: 7.1.0.172
- Last known good version: 7.0
- Xamarin.Forms version: 3.1
- IDE: VS 2017 (15.7)

**Comment by brianlagunas** [comment]
There are many interfaces that are not available in the net 4.5 folder due to incomatibility with WPF. I suggest making your test projects a .NET Core project instead.
