### ISSUE TITLE
[UWP] Absolute Navigation is not working 

### ISSUE THREAD

**Issue by jitendrajadav** [PrismLibrary/Prism#1510]
### Description
`                        await _navigationService.NavigateAsync(new Uri("/MainPage", UriKind.Absolute), animated: false);
`
not working in UWP it is working on Android fine!

### Steps to Reproduce

1. 
2. 
3. 

### Basic Information

- Version with issue:
- Last known good version:
- Xamarin.Forms version:
- IDE:

**Comment by brianlagunas** [comment]
Closed for not providing the required information.
