### ISSUE TITLE
after adding new prism Content page Error CS0103: The name 'InitializeComponent' does not exist in the current context (CS0103) 

### ISSUE THREAD

**Issue by HirenVyasSimform** [PrismLibrary/Prism#1512]
### Description
after adding new prism Content page Error CS0103: The name 'InitializeComponent' does not exist in the current context (CS0103) 

### Steps to Reproduce

1. Create new Prims Quick start template solution
2. adding new Page page
3. Try to rebuild and got error

### Basic Information

- Version with issue: 
- Last known good version:
- Xamarin.Forms version:XF 3.1
- IDE: VS 2017 mac 
![screen shot 2018-07-24 at 11 47 02 am](https://user-images.githubusercontent.com/39689111/43120295-51dca396-8f37-11e8-933c-48f423369d58.png)

**Comment by giopellizzoni** [comment]
I've got the same behaviour here

**Comment by dansiegel** [comment]
Check your csproj... VSMac has been adding references that screw up XAML pages. If you see ANY references to your pages and you're using a SDK style project (like the core project from the QuickStart template), remove them and it should start working. This is really on the VS Mac team to fix.
