### ISSUE TITLE
Have the CompositeCommand supports async DelegateCommands

### ISSUE THREAD

**Issue by jgrossrieder** [PrismLibrary/Prism#1515]
### Steps to Reproduce

1. Create a composite command
2. Create a DelegateCommand that have the Execute method "Async"
3. Register the delegate command as part of the composite command
4. Call the Composite command

### Expected Behavior
The caller should returns only when all the DelegateCommands are executed

### Actual Behavior
It returns directly at the first async

### Basic Information

- Version with issue: 6.3.0
- IDE: VS 2017 Pro

### Reproduction Link

```
	public static class GlobalCommands
	{
		public static CompositeCommand MyGlobalCommand = new CompositeCommand();
	}
	
	
	public class SomeViewModel
	{
		public DelegateCommand SomeSpecificCommand { get; set; }
		public SomeViewModel(){
			SomeSpecificCommand = new DelegateCommand(DoSomeWorkAsync);
			GlobalCommands.MyGlobalCommand.RegisterCommand(SomeSpecificCommand);
		}
		
		private async void DoSomeWorkAsync()
		{
			await DoSomeLongRunningJob();
		}
	}
	
	//By binding or just for the test in anyfile:
	GlobalCommands.MyGlobalCommand.Execute(null);
```

**Comment by brianlagunas** [comment]
There is no such thing as an async command. DelegateCommands are invoked synchronously and act more as a "fire and forget".  The CompositeCommand will not await the result of a DelegateCommand that is marked as async.

**Comment by jgrossrieder** [comment]
@brianlagunas Yeah, I read that in the meantime. But what is then the correct way of executing long tasks that should update the GUI at the end?

**Comment by brianlagunas** [comment]
You update the UI when the task returns. That's how async works. You don't pause the execution of the CompositeCommand until it finishes.  Invoke the command, whenever the task finishes, it will update the UI.

**Comment by jgrossrieder** [comment]
But it means that you have to `Wait` on the Task, right?

Like

```
		private async void DoSomeWorkAsync()
		{
			Task.Run(()=> DoSomeLongRunningJob()).Wait();
			UpdateTheGui();
		}
```

**Comment by brianlagunas** [comment]
No. Like I said, you update the UI when the task returns.

**Comment by jgrossrieder** [comment]
What do you mean? Because you will returns directly from Task.Run, so the Update would be too soon.

**Comment by jgrossrieder** [comment]
@brianlagunas I would really appreciate one very small example, that would unlock me and the team. I can't really find any example on what is the best practice on this.

**Comment by dvorn** [comment]
@jgrossrieder 
```csharp
private async void DoSomeWorkAsync()
{
    await Task.Run(() => DoSomeLongRunningJob());
    UpdateTheGui();
}
```
Note that UpdateTheGui will be executed at an unknown moment, and you need to do some extra work to properly synchronize it with the main execution thread.

**Comment by jgrossrieder** [comment]
@dvorn I see, but that doesn't seems possible when I use CompositeCommand then? 
I'm not sure how I can UnitTests my code without having any callback(and worse that the CompositeCommand will not wait on their children for the execution.

**Comment by dvorn** [comment]
The approach I used in my projects is the following: every async action used in a command ends with some _observable_ change in some object - an event or property change.  In a test I start the command and then wait for that event/property change to occur.  After that, assert the desired state.  For instance, your UpdateTheGui will set some property in a view model and that property is INPC.  Then wait for that INPC.

**Comment by noufionline** [comment]
@jgrossrieder I use prism library extensively in my application and I also use DevExpress MVVM which has an excellent implementation of AsyncCommand.

Please have a look at this library

https://github.com/DevExpress/DevExpress.Mvvm.Free/blob/master/DevExpress.Mvvm/Commands/DelegateCommand.cs

**Comment by jgrossrieder** [comment]
@dvorn Ok, so you end up by waiting for a given amount of time on some event? Just to be sure.  
@noufionline I will check it out, but I tends to stay independant from UI library code.

**Comment by dvorn** [comment]
@jgrossrieder Yes, wait for event or several events - for "good" and "bad" case scenarios.  And yes, wait should be limited in time for the case where none of good and bad events occur - usually when an exception happens in a place where nobody thought it is even possible :-)
