### ISSUE TITLE
Prism Navigation keep MasterPageDetail menu after navigating to other page

### ISSUE THREAD

**Issue by viniciusmaia** [PrismLibrary/Prism#1516]
I'm using prism and had a MasterDetailPage with some pages that is accessible from that. But, in some of this pages, I can navigate to other pages that is not accessible from the MasterPageDetail Menu, but menu is still accessible with sliding action. I'll post some prints to try explain.

That's is a page that is accessible from MasterPageDetailMenu 
![screenshot_20180727-100950](https://user-images.githubusercontent.com/5260850/43327601-38a0d714-9192-11e8-9fda-e3f35aa45507.png)

When the user is accessing this page, he can access the MasterPageDetail Menu. But if the user select an item of the list or click in "Plus" Floating Button, the app navigate to other Page where MasterPageDetail Menu shouldn't be accessible.
![screenshot_20180727-101018](https://user-images.githubusercontent.com/5260850/43327637-4f46cbc2-9192-11e8-9148-cbe0df667efd.png)

But, as you can see on the next image, if the user slide the page from the left to right, the MasterPageDetail Menu is still accessible
![screenshot_20180727-101047](https://user-images.githubusercontent.com/5260850/43327646-55a5cb9e-9192-11e8-920e-b222657074ad.png)

How can I avoid this behaviour? In the App class, my code for navigate to MasterPageDetail is:

`await NavigationService.NavigateAsync("Menu/Navigation/TipoItensCardapio")`

In this case, menu is my MasterPagelDetail. The code for navigate from TipoItensCardapio page to the second page is:

`NavigationService.NavigateAsync("TipoItemCardapioEdit");`

**Comment by brianlagunas** [comment]
This is how a MasterDetailPage works.  If you don't want the MasterDetailPage to be the root of your app, simply force a modal navigation using the useModalNavigation parmeter.

**Comment by brianlagunas** [comment]
If you wish to keep the master detail page, then just set `IsGestureEnabled = false` s you cant swipe the Master menu.
