### ISSUE TITLE
How to register a named view multiple times with custom view models

### ISSUE THREAD

**Issue by JunkyXL86** [PrismLibrary/Prism#1517]
### Description

see [https://github.com/PrismLibrary/Prism/pull/1514](https://github.com/PrismLibrary/Prism/pull/1514)
I want to be able to register a view twice using different view models. The view models simply provide a different items source for the view (just a ListView).
```
containerRegistry.RegisterForNavigation<ItemsView, OpenItemsViewModel>("OpenItemsView");
containerRegistry.RegisterForNavigation<ItemsView, CompletedItemsViewModel>("CompletedItemsView");
```

and then navigating like this: 
`NavigationService.NavigateAsync("OpenItemsView");`
which resolves the ItemsView using OpenItemsViewModel.

the same goes for navigating to "CompletedItemsView" using CompletedItemsViewModel.

I think this is a common scenario to use the same view with different view models. As you mentioned @brianlagunas, this would be a design smell. As far as I know, the usual Prism way would be to pass a navigation parameter to know what data to load in the view model. But that would end up in some if/else code I usually want to avoid. 
I think it's a bad idea to put the decision which data to load into the view model as it's more an implementation detail of each view model which data it loads.
So I don't really get why my approach would be a design smell. How can I achieve this in an elegant way without duplicating anything or doing some if/else?
I could get it working if I duplicated the view. Then I could connect it with a different view model ->
`containerRegistry.RegisterForNavigation<CompletedItemsView, CompletedItemsViewModel>("CompletedItemsView");`
This would be a normal approach - but why would I duplicate the view? 

### Reproduction Link
Below is the sample app demonstrating the desired behavior.
[SampleApp.zip](https://github.com/PrismLibrary/Prism/files/2241019/SampleApp.zip)

**Comment by brianlagunas** [comment]
As I said in my reply to your PR, this is not something we will support in Prism. You have a few options, two of which we have already discussed; create a unique view, or have a single VM and load the relevant data.

**Comment by UnreachableCode** [comment]
Does anyone know a good article that nails the single ViewModel with different state code on the head? I have a few ideas myself involving dependency injection of services for each state but I wanted to see if anyone has a good take on it.
