### ISSUE TITLE
Process.Start not working with PrismApplication

### ISSUE THREAD

**Issue by vinosd08** [PrismLibrary/Prism#1518]
### Description

Im trying to implement NUnit for Prism. For which we need to open the exe through Process.Start(prismapp.exe) and get processID for further use. We can see the  process running in task manager but UI not displayed.

### Steps to Reproduce

1.  call Process.Start("PrismApp.exe");

### Expected Behavior
1. Application main screen should be appeared.
### Actual Behavior
1. look into taskManager, we can see process running, but ui will not render. 
### Basic Information
im trying with prism 7.1.0.144

7.1.0.144 - Version with issue:
- Last known good version:
- Xamarin.Forms version:
visual studio - IDE:

**Comment by brianlagunas** [comment]
I'm sorry, but this not related to Prism.  Prism has no control over Process.Sart or it's behavior. As long as your app is properly compiled and runs it should work.  Does it work when you double click the exe in file explorer? If not, you have an issue with your app.
