### ISSUE TITLE
MasterDetail on Mac crashes when navigation from a subview to a different view from master

### ISSUE THREAD

**Issue by baywolf-studios** [PrismLibrary/Prism#1520]
### Description
When navigating with a MasterDetail view in a Xamarin.Forms macOS project. You can navigate between the main pages fine. But if you navigate to a child page of one of the main pages and attempt to go from there directly to a different main page, an exception is thrown. I created a repo with a sample project that reproduces this issue.

pseudo code (actual repo link at bottom):
_navigationService.NavigateAsync("/MainPage/NavigationPage/ViewA");
_navigationService.NavigateAsync("SubViewA");
_navigationService.NavigateAsync("NavigationPage/ViewB");

### Steps to Reproduce

1. Run project
2. Click on SubViewA label to navigate to the subviewA page.
3. Now click on the ViewB label to navigate to ViewB page.
4. You should see an exception here.

### Expected Behavior
No exception

### Actual Behavior
Exception

### Basic Information

- Version with issue: 7.0.0.396
- Last known good version: na
- Xamarin.Forms version: 3.1.0.637273
- IDE: VisualStudio Mac

### Reproduction Link

[https://github.com/baywolf-studios/TestMasterDetail](https://github.com/baywolf-studios/TestMasterDetail)

**Comment by baywolf-studios** [comment]
Any other information needed to determine if this is a Prism issue or a deeper issue with Xamarin.Forms?

**Comment by dansiegel** [comment]
@baywolf-studios Sorry for the delay. Any platform specific issue is absolutely a Xamarin Forms issue not Prism.

**Comment by baywolf-studios** [comment]
No problem, thanks! I’ve gone ahead and opened an issue on Xamarin.Forms repo.
