### ISSUE TITLE
Wrong SynchronizationContext in DelegateCommandBase

### ISSUE THREAD

**Issue by fonMaringer** [PrismLibrary/Prism#1521]
Hi! We've found that if command is created in non-UI thread it stores wrong SynchronizationContext:
https://github.com/PrismLibrary/Prism/blob/bd496273bf68ac515474cc7b6ebbce69cff57ca6/Source/Prism/Commands/DelegateCommandBase.cs#L25-L28
Then we call RaiseCanExecuteChanged method from another thread (UI or non-UI) and program crashes after executing this, because contexts are not equals:
https://github.com/PrismLibrary/Prism/blob/bd496273bf68ac515474cc7b6ebbce69cff57ca6/Source/Prism/Commands/DelegateCommandBase.cs#L44-L45
For our project we recompiled prism with hardcoded context and the problem was solved (we use only WPF):
`private static SynchronizationContext _synchronizationContext = Application.Current.Dispatcher.Invoke<SynchronizationContext>(() => SynchronizationContext.Current);`
Maybe it's possible to add some conditional compilation symbols for all targets or another solution to resolve this issue?

**Comment by dvorn** [comment]
The commands should be created on UI thread, since 6.2: https://github.com/PrismLibrary/Prism/pull/641

**Comment by brianlagunas** [comment]
Thanks @dvorn for the quick reply.

We will not be changing how the DegelateCommand works with the sync context, as it is implemened as designed. plus, creating a UI based command on a background thread doen't make a lot of sense to me anyways as you will have to marshal that command back to the UI thread in ordr for the UI to bind to it.

**Comment by znakeeye** [comment]
> Hi! We've found that if command is created in non-UI thread it stores wrong SynchronizationContext:
> https://github.com/PrismLibrary/Prism/blob/bd496273bf68ac515474cc7b6ebbce69cff57ca6/Source/Prism/Commands/DelegateCommandBase.cs#L25-L28
> 
> 
> Then we call RaiseCanExecuteChanged method from another thread (UI or non-UI) and program crashes after executing this, because contexts are not equals:
> https://github.com/PrismLibrary/Prism/blob/bd496273bf68ac515474cc7b6ebbce69cff57ca6/Source/Prism/Commands/DelegateCommandBase.cs#L44-L45
> 
> 
> For our project we recompiled prism with hardcoded context and the problem was solved (we use only WPF):
> `private static SynchronizationContext _synchronizationContext = Application.Current.Dispatcher.Invoke<SynchronizationContext>(() => SynchronizationContext.Current);`
> Maybe it's possible to add some conditional compilation symbols for all targets or another solution to resolve this issue?

Beware! Your `Invoke()` call could deadlock.
