### ISSUE TITLE
Unable to locate repository containing directory (Prism UWP)

### ISSUE THREAD

**Issue by vinhdh** [PrismLibrary/Prism#1523]
I encountered this error during process of building source code (prism 7 UWP)
Is there anyone had the same problem?

The complete error message as following:

> 1>C:\Users\vinhd\.nuget\packages\microsoft.build.tasks.git\1.0.0-beta-62925-02\build\Microsoft.Build.Tasks.Git.targets(20,5): error : Unable to locate repository containing directory 'C:\Users\vinhd\Desktop\Prism-master\Source\Prism'.

https://i.imgur.com/8nDw0TT.png

**Comment by brianlagunas** [comment]
Don't bother with UWP at this time. We are rewriting it.
