### ISSUE TITLE
Projects generated with Prism Developer Pack for macOS VS don't work on Windows VS

### ISSUE THREAD

**Issue by lewcianci** [PrismLibrary/Prism#1525]
### Description

Projects generated with Prism Developer Pack for macOS VS don't work on Windows VS

### Steps to Reproduce

1.  Make a project on macOS using Prism Developer Toolkit
2. Copy to Windows machine
3. Try to build for Android. Build fails for various reasons:
3a: Wrong version of Fody Weaver - resolved by updating Realm in project
3b: This cryptic error: "The item metadata %(Filename) is being referenced without an item name.  Specify the item name by using %(itemname.Filename)."

This seems to be caused by line 133-134 of Mobile.BuildTools.Targets.  This is what it says:

```   <Copy SourceFiles="$(__Generated_APK)" 
          DestinationFiles="$(BuildToolsArtifactOutputPath)\%(Filename)%(Extension)" />
```

### Expected Behavior
Works
### Actual Behavior
Doesn't
### Basic Information

MacOS VS - Latest (7.5.4)
Windows VS - 15.7.6

### Screenshots
[Archive.zip](https://github.com/PrismLibrary/Prism/files/2279711/Archive.zip)

### Reproduction Link

Reproducing solution attached

**Comment by lewcianci** [comment]
Another issue is that hovering over variables in VS for Windows in a created project doesn't display that variables properties which makes debugging very difficult.  Trying to fix that now.

**Comment by dansiegel** [comment]
As noted this is not a Prism issue.

**Comment by lewcianci** [comment]
@dansiegel Sorry, what I meant was, the variable hovering issue was a MS issue which was patched.  I still had the original issue of projects on VS4MAC not working on Windows visual studio.

**Comment by dansiegel** [comment]
@lewcianci your issue is dependency/tooling related not Prism

**Comment by lewcianci** [comment]
Okay, but the prism developer toolkit generated the project - is that really unrelated?

If so I'll take note for next time

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
