### ISSUE TITLE
Cant resolve page System.ArgumentException: 'The page name MainPage does not have an associated type in namespace PrismTest.Views' [UWP] 

### ISSUE THREAD

**Issue by Joebu** [PrismLibrary/Prism#1527]
### Description

Getting this error when trying load the main page from app.xaml.cs
`System.ArgumentException: 'The page name MainPage does not have an associated type in namespace PrismTest.Views'`
 my view is in the views folder as the default convention 
└───Views
        MainPage.xaml
        MainPage.xaml.cs

### Steps to Reproduce

1. Create a new UWP App. Target version 1803 (10.0; build 17134) 
    min version Windows10 Creators update (10.0; build 15063)
2. Prism.Unity.Windows -Version 7.0.0.336-pre
3. ` protected override Task OnLaunchApplicationAsync(LaunchActivatedEventArgs args)
        {
            NavigationService.Navigate("MainPage", null);
            return Task.FromResult<object>(null);
        }`

### Expected Behavior
   Load the page 
### Actual Behavior
```
    Throwing an error System.ArgumentException
  HResult=0x80070057
  Message=The page name MainPage does not have an associated type in namespace PrismTest.Views
  Source=Prism.Windows
  StackTrace:
   at Prism.Windows.PrismApplication.GetPageType(String pageToken)
   at Prism.Windows.Navigation.FrameNavigationService.Navigate(String pageToken, Object parameter)
   at PrismTest.App.OnLaunchApplicationAsync(LaunchActivatedEventArgs args) in c:\users\xxx\source\repos\temp\PrismTest\PrismTest\App.xaml.cs:line 38
   at Prism.Windows.PrismApplication.<OnLaunched>d__54.MoveNext()
```

- IDE: VS 2017 Professional 15.17.6

**Comment by brianlagunas** [comment]
Closing this as you did not provide the required reproduction link.  Keep in mind, the namespaces have to be correct, the file just can't be moved into a folder. Also, we are in the process of completely rewriting our UWP guidance, so stat tuned for that effort.

**Comment by Joebu** [comment]
@brianlagunas I've updated the issue with a link

**Comment by brianlagunas** [comment]
Don't navigate to `nameof(MainPage)`. Instead try navigating to "Main"

**Comment by Joebu** [comment]
Got Thanks.
