### ISSUE TITLE
Tabbed Page switching Tabs

### ISSUE THREAD

**Issue by snowppy** [PrismLibrary/Prism#1528]
I have been trying to find within the existing issue discussions a example of the following scenario but I haven't been able to locate a reference example. I also thought that it could be mentioned [here](https://prismlibrary.github.io/docs/xamarin-forms/Working-With-TabbedPages.html).

I have have navigated to a Tabbed Page
NavigateAsync("/LwdMasterDetailPage/LwdNavigationPage/LwdTabbedPage?createTab=HomePage&createTab=ProjectsListPage");

As expected HomePage is the selected page. I am looking for a way after I click a button to make ProjectsListPage the selected page. I am assuming there is a better way than recreating the navigation stack like this:
NavigateAsync("/LwdMasterDetailPage/LwdNavigationPage/LwdTabbedPage?createTab=HomePage&createTab=ProjectsListPage&selectedTab=ProjectsListPage");

**Comment by brianlagunas** [comment]
Tab selection is not navigation. You will have to code this up yourself as Prism doesn't do anything for you in this scenario.
