### ISSUE TITLE
Prism.DependencyInjection.Forms

### ISSUE THREAD

**Issue by smalleythedave** [PrismLibrary/Prism#1529]
Of course the above assembly does not exist. In #1352 you stated Microsoft's DI was not an option for two reasons: The container is immutable and named resolution is not supported. However, the Autofac Forms integration got around immutability by adding SupportsModules => false and FinalizeExtension() to IContainerExtension and GetBuilder() to PrismIocExtensions. As for named resolution, I have written a < 100 line set of extension methods which implements just enough named resolution to support IContainerExtension with AddTransient(serviceType, implementationType, name) and GetService(serviceType, name). The integration treats IServiceProvider and IServiceCollection like Autofac's IContainer and Builder respectively.  It passes a modified version of Prism.Autofac.Forms.Test and I've used it in a simple sample Xamarin app.

I admit it's not much to look at, and I much prefer DryIoc as a container myself, but one of the reasons I have used Unity was because it was an easy sell to some customers to be using "Microsoft's container" rather than something else (_some_ customers). Crippled though it may be, I think there is value in providing an integration for Micrsoft.Extensions.DependencyInjection, even if better options exist.

Would you be willing to reconsider your objections to Microsoft's DI for use in Prism (at least for Xamarin)?

Dave

**Comment by bartlannoeye** [comment]
You're always free to fork Prism and implement this yourself. Autofac has been supported for years and it was either this 'fix' or being dropped completely. The time of the team is very limited (we all have full time jobs and more, plus family), so our focus is on other work than supporting extra containers. Because after the initial PR, the work typically is for us, even if we don't know the container.

**Comment by brianlagunas** [comment]
We are not going to support Microsoft DI at this time, and we are considering dropping support for Autofac due to it being immutable. The thought being that if a container cannot support all features of Prism, we should not support it.
