### ISSUE TITLE
XF: Linking fails for iOS app

### ISSUE THREAD

**Issue by Sankra** [PrismLibrary/Prism#153]
Build error when linking SDK assemblies only:

Error MT2001: Could not link assemblies. Reason: Can't not find the nested type '<System.Windows.Input.ICommand.Execute>d__4' in 'Prism.Commands.DelegateCommandBase (MT2001)

Pris: 5.7.0-pre3
Xamarin.iOS: Version: 9.0.1.18

**Comment by droyiii** [comment]
I'm seeing this issue as well.  
error MT2001: Could not link assemblies. Reason: Can't not find the nested type '&lt;System.Windows.Input.ICommand.Execute&gt;d__4' in 'Prism.Commands.DelegateCommandBase

Works in the simulator but not when compiling for the device.

**Comment by droyiii** [comment]
This is related to the latest stable release from Xamarin for iOS 9.  See link here
http://forums.xamarin.com/discussion/50971/stable-release-xamarin-ios-9-0-ios-9-0-upstream-release/p1
under known issues 33124.  It can affect linking to any library compiled using vs2013 and async.

**Comment by brianlagunas** [comment]
Great find!  Thanks for checking this out.  Any idea on when a fix for this will be released from Xamarin?

**Comment by droyiii** [comment]
They say by the end of the week.  You can request access to it sooner if needed.

**Comment by droyiii** [comment]
The release is now available as a stable update.  I've tested it and it seems to resolve the issue.  I can now compile and deploy to an iOS device without issue

**Comment by brianlagunas** [comment]
Thanks for the update.
