### ISSUE TITLE
ItemTapped of SFListView doesn't work and Selected Item binding to null

### ISSUE THREAD

**Issue by muocpp** [PrismLibrary/Prism#1531]
Hello
I'm trying to figure out how to bind ItemTapped of **SFListView** with NavigationCommand the DelegateCommand Property worked correctly and send me to The Execution function , but nothing happened, and also I'm tying to bind SelectedItem to pass it as value parameter but the property value is binding to null.
**Note** the code working correctly if I'm using **ListView** 
**View:**

                    <syncfusion:SfListView
                        ItemSize="200"
                        Orientation="Horizontal"
                        ItemsSource="{Binding Products}"
                        SelectedItem="{Binding SelectedPhone}">
                        <syncfusion:SfListView.ItemTemplate>
                            <DataTemplate>
                                <ViewCell>
                                    <ViewCell.View>
                                        <Frame Margin="5">
                                            <Grid>
                                                <Grid.RowDefinitions>
                                                    <RowDefinition Height=".6*" />
                                                    <RowDefinition Height=".2*" />
                                                    <RowDefinition Height=".1*" />
                                                    <RowDefinition Height=".1*" />
                                                </Grid.RowDefinitions>
                                                <Grid.ColumnDefinitions>
                                                    <ColumnDefinition Width="*" />
                                                    <ColumnDefinition Width="*" />
                                                </Grid.ColumnDefinitions>
                                                <Image Source="{Binding ImgUrl}"
                                                       HorizontalOptions="CenterAndExpand"
                                                       Aspect="AspectFit"
                                                       Grid.Row="0"
                                                       Grid.ColumnSpan="2"/>
                                                <Label Text="{Binding Name}"
                                                       TextColor="Black"
                                                       FontAttributes="Bold"
                                                       HorizontalOptions="Center"
                                                       Grid.Row="1"
                                                       Grid.ColumnSpan="2"/>
                                                <Label Text="{Binding Price, StringFormat='{0} EGP'}"
                                                       HorizontalOptions="Center"
                                                       Grid.Row="2"
                                                       Grid.ColumnSpan="2"/>
                                                <Label Text="{Binding Rating}"
                                                       HorizontalOptions="End"
                                                       Grid.Row="3" Grid.Column="0"/>
                                                <Image Source="ic_star_rate"
                                                       HorizontalOptions="Start"
                                                       Grid.Row="3" Grid.Column="1"/>
                                            </Grid>
                                        </Frame>
                                    </ViewCell.View>
                                </ViewCell>
                            </DataTemplate>
                        </syncfusion:SfListView.ItemTemplate>
                        <syncfusion:SfListView.Behaviors>
                            <b:EventToCommandBehavior EventName="ItemTapped" 
                                              Command="{Binding NavigateCommand}" />
                        </syncfusion:SfListView.Behaviors>
                    </syncfusion:SfListView>
`

**Comment by bartlannoeye** [comment]
If code works correctly using a ListView, then this is a problem with the SfListView from SyncFusion and not Prism. Please try on Synfusion forums or StackOverflow (where you can add the tag prism)
