### ISSUE TITLE
Could not load assembly 'Microsoft.Practices.Unity when updated to latest version

### ISSUE THREAD

**Issue by shashikant0423** [PrismLibrary/Prism#1532]
### Description
@brianlagunas  and @dansiegel  I have got following error
 
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2,2): Error: Exception while loading assemblies: System.IO.FileNotFoundException: Could not load assembly 'Microsoft.Practices.Unity, Version=4.0.0.0, Culture=neutral, PublicKeyToken=6d32ff45e0ccc69f'. Perhaps it doesn't exist in the Mono for Android profile? File name: 'Microsoft.Practices.Unity.dll' at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve (Mono.Cecil.AssemblyNameReference reference, Mono.Cecil.ReaderParameters parameters) [0x0009a] in /Users/builder/data/lanes/5945/dffc5912/source/monodroid/external/xamarin-android/external/Java.Interop/src/Java.Interop.Tools.Cecil/Java.Interop.Tools.Cecil/DirectoryAssemblyResolver.cs:229 at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve (Mono.Cecil.AssemblyNameReference reference) [0x00000] in /Users/builder/data/lanes/5945/dffc5912/source/monodroid/external/xamarin-android/external/Java.Interop/src/Java.Interop.Tools.Cecil/Java.Interop.Tools.Cecil/DirectoryAssemblyResolver.cs:179 at Xamarin.Android.Tasks.ResolveAssemblies.AddAssemblyReferences (Java.Interop.Tools.Cecil.DirectoryAssemblyResolver resolver, System.Collections.Generic.ICollection`1[T] assemblies, Mono.Cecil.AssemblyDefinition assembly, System.Boolean topLevel) [0x0014a] in <96027da06dd5411688a31011072e256f>:0 at Xamarin.Android.Tasks.ResolveAssemblies.Execute (Java.Interop.Tools.Cecil.DirectoryAssemblyResolver resolver) [0x00237] in <96027da06dd5411688a31011072e256f>:0  

### Steps to Reproduce

1.  Updated latest Prism.Unity.Forms 7.0.0.396 from 6.3
2. And updated Unity 4.1 from Unit 5.8.6
3. Then got an error for android 

### Expected Behavior
Bug-free 
### Actual Behavior
Got error
### Basic Information

- Version with issue:
- Last known good version:
- Xamarin.Forms version: 3.1.0.697729
- IDE: Visual Studio

**Comment by brianlagunas** [comment]
You can't update Unity to 5.8.6. Prism.Unity.Forms has a dependency on Unity 5.5.5.
