### ISSUE TITLE
Can't register multiple viewmodels with the same view

### ISSUE THREAD

**Issue by veljko-msft** [PrismLibrary/Prism#1533]
Hello,

I'm trying to use a single view that represents the list with few features that I need throughout the application. I would like to reuse this view. In the view I use DataTemplateSelector to choose the right template for the items in the list. I have created two ViewModels and want to register them both with the view I created previously. I used the following code to register:

Container.RegisterTypeForNavigation<ASharedView, AViewModel>("One");
Container.RegisterTypeForNavigation<ASharedView, BViewModel>("Two");

It builds and deploys correctly. However, when I navigate to "Two" wrong ViewModel is provided to the view. If I navigate to "One" all works as expected. If I reverse the order of registration and register the BViewModel first, then no matter if I navigate to "One" or "Two" the BViewModel is used.

### Steps to Reproduce
1. Create a view: ASharedView
2. Create two ViewModels: AViewModel, BViewModel
3. Register in navigation ASharedView with AViewModel and ASharedView with BViewModel

### Expected Behavior
Navigation leads to the specific combination of the view and view model based on the name of the registration.

### Actual Behavior
Navigation always uses the ViewModel that was first to register for a certain view.

### Basic Information

- Xamarin.Forms version: 3.1.0.697729
- IDE: Visual Studio 2017

**Comment by bartlannoeye** [comment]
Closed as duplicate indeed. This is a scenario we don't support, more details see linked issue and PR.

**Comment by veljko-msft** [comment]
Duplicate indeed. Searched for it, but didn't find it. Sorry for spam. Thanks for a quick reply!
