### ISSUE TITLE
Nested Tabbed Page Issue

### ISSUE THREAD

**Issue by rredoh** [PrismLibrary/Prism#1539]
### Description

Add TabbedPage2 as a child of other TabbedPage1
Child of TabbedPage2 become blank page and the title is TabbedPage2

### Steps to Reproduce

1. Add TabbedPage1
2. Add TabbedPage2 as a child of TabbedPage1
3. Add some children page to TabbedPage2

### Expected Behavior
children of TabbedPage2 displayed normally

### Basic Information

- Version with issue: 7.0.0.396
- Xamarin.Forms version: 3.1.0.697729
- IDE: Visual Studio 2017 15.8.2

### Screenshots
https://drive.google.com/file/d/1b7HhwfKN8Q2bBNYbkDguYJ66nS-cbck7/view?usp=sharing

### Reproduction Link
https://github.com/rredoh/Prism-Nested-TabbedPage-Problem

**Comment by dansiegel** [comment]
Closing as this is not a Prism issue but rather a Xamarin.Forms issue.

**Comment by rredoh** [comment]
Well, the problem started when I'm using prism.. You can clearly see the difference on the project I shared [here](https://github.com/rredoh/Prism-Nested-TabbedPage-Problem)

**Comment by rredoh** [comment]
Have u check it?

**Comment by dansiegel** [comment]
@rredoh Prism has literally 0 code that would affect appearances. I do not have the time to create a repo for you that will show you the issue comes from Xamarin.Forms. I have a feeling you'll find that a nested Tabbed Pages break virtualization and just aren't supported, but your best bet is to open an issue with the Xamarin.Forms team.

**Comment by rredoh** [comment]
Ok then. I'll try. Thank you very much @dansiegel

**Comment by rredoh** [comment]
Adding this code after InitializeComponent() solve the problem. But there's a problem, navigateasync isn't working
`BindingContext = App.Current.Container.Resolve<PageViewModel>();`

**Comment by dansiegel** [comment]
@rredoh you absolutely should not be doing that and it actually will not give you a valid instance of the NavigationService. Remember if you're navigating to "SomeTabbedPage", then the NavigationService knows it needs to check to see if SomeTabbedPage should autowire the ViewModel... the individual pages you're adding as tabs though will need to specifically set the Autowire property...

**Comment by rredoh** [comment]
Can you suggest how to force the page in nested tabs to wire to correct viewmodel? It seems that the only thing working is the binding.. Event like OnNavigated to, OnAppearing, etc aren't working
