### ISSUE TITLE
Prism.Core can not load INavigationAware when using .NET Standard 2.0

### ISSUE THREAD

**Issue by moci** [PrismLibrary/Prism#1540]
### Description
Using INavigationAware, in a .NET Standard 2.0 project with a dependency to Prism.Core throws error

### Steps to Reproduce

1. Create .NET Standard (2.0) project
2. Add Prism.Core (7.1.0.255-ci) as nuget dependency
3. Create view model (A) class using the INavigationAware interface
4. Load view using view model A

### Expected Behavior
View/application is displayed

### Actual Behavior
Unhandled exception of type System.TypeLoadException

### Basic Information
- Working with build 7.1.0.255-ci
- Visual Studio Community 2017 (15.8.2)

### Screenshots
![can_not_load_type](https://user-images.githubusercontent.com/464954/45154981-afc8eb80-b1d9-11e8-8653-0536082edff9.png)

### Reproduction Link
[PrismVMsInOtherAssembly.zip](https://github.com/PrismLibrary/Prism/files/2356810/PrismVMsInOtherAssembly.zip)

**Comment by dansiegel** [comment]
The Navigation namespace in Prism.Core is specifically excluded at this time from Full Framework targets i.e. WPF/GTK#. We do not currently have any plans of making this available for WPF.
