### ISSUE TITLE
[WPF] Calling ToString() on NavigationParameters causes NullReferenceException when parameter is null.

### ISSUE THREAD

**Issue by n00bje** [PrismLibrary/Prism#1543]
### Description

Calling ToString() on an instance of NavigationParameters where a value is null results in a NullReferenceException. This is because kvp.Value is called in [NavigationParameters.cs](https://github.com/PrismLibrary/Prism/blob/master/Source/Wpf/Prism.Wpf/Regions/NavigationParameters.cs) at line 265, regardless of the value being null or not.

### Steps to Reproduce

```
var parameters = new NavigationParameters
{
    {"FirstKey", "SomeValue"},
    {"SecondKey", null}
};
Console.WriteLine(parameters);
```

### Expected Behavior

`?FirstKey=SomeValue` or `?FirstKey=SomeValue&SecondKey=` after calling ToString().

### Actual Behavior

NullReferenceException

### Basic Information

- Version with issue: Prism.Wpf 6.3.0

**Comment by brianlagunas** [comment]
Thanks for reporting this
