### ISSUE TITLE
MasterDetailPage navigation on iOS is unexcepted

### ISSUE THREAD

**Issue by yanshouwang** [PrismLibrary/Prism#1546]
### Description

The master page of Xamarin.Forms MasterDetailPage on iOS disappeared with the detail page navigation at the same time, but on prism the master disappeared after the detail page slip form screen's right side to the master's right.
This is not good-looking...
Is there any chance to solve this?

### Steps to Reproduce

1. MasterDetailPage Navigation Beahvior

### Expected Behavior
Just like the original Xamarin.Forms's MasterDetailPage, the master disappeared with the detail appeared at the same time.

### Actual Behavior
On prism the master disappeared after the detail page slip form screen's right side to the master's right.

### Basic Information

- Version with issue:Latest
- Last known good version:none
- Xamarin.Forms version:Latest
- IDE:VS2017

### Screenshots
![20180919003410](https://user-images.githubusercontent.com/24455689/45703202-2be20c80-bba6-11e8-8005-ccbac041d59f.gif)
![20180919003718](https://user-images.githubusercontent.com/24455689/45703205-2f759380-bba6-11e8-8e5f-8a5cb82172dd.gif)

**Comment by brianlagunas** [comment]
Prism uses the built-in Xamarin.Forms navigation behavior.  Your issues is not clear to us and you did not provide a sample the reproduces the issue.  You could even supply a gif of what the expected result is and another gif of the actual result to help us see the issue.  Therefore I must close this issue as not enough information was provided.

**Comment by yanshouwang** [comment]
> Prism uses the built-in Xamarin.Forms navigation behavior. Your issues is not clear to us and you did not provide a sample the reproduces the issue. You could even supply a gif of what the expected result is and another gif of the actual result to help us see the issue. Therefore I must close this issue as not enough information was provided.

Sorry for that (='x'=) , I just used the [HamburgerMenu Demo](https://github.com/PrismLibrary/Prism-Samples-Forms/tree/master/HamburgerMenu/HamburgerMenu) to build this issue, and upload the gifs below, the first gif is the default effect which I used the detail property, and the second gif is the demo's effect which is a mvvm pattern, it's really not good-looking with the default one used the Detail property.
And I tried to set binding to the Detail but it built to an error...I finally have to use a behavior to do this

![20180919003410](https://user-images.githubusercontent.com/24455689/45702495-8ed2a400-bba4-11e8-8972-629532ed3872.gif)
![20180919003718](https://user-images.githubusercontent.com/24455689/45702500-909c6780-bba4-11e8-9205-cf6ce1fd166b.gif)

**Comment by brianlagunas** [comment]
Thank you for clarifying the issue. I'll have to look into this and see if there is anything we can do. We are using the Xamarin.Forms API to close the master when the detail is set, so I'm not sure if there is anything we can really do.

**Comment by yanshouwang** [comment]
I think the best Pattern to do this is like the TabbedPage which can use the CreateTab params. 
Now I use a behavior which bind a Detail Property in the vm to control the MasterDetailPage’s Detail Property，It’s ok to me temporarily，but really hope Prism to be better and better☺️

**Comment by yanshouwang** [comment]
@brianlagunas I just write a demo, see [MasterDetailTest](https://github.com/yanshouwang/MasterDetailTest)
I don't know if it will be helpful, but it's a solution at least.

**Comment by brianlagunas** [comment]
Thank you, but I was asking for a plain XF demo that shows it working properly. Not a Prism app that has the delay yo are having an issue with.

**Comment by yanshouwang** [comment]
Oh~I updated my [Test.Forms](https://github.com/yanshouwang/Test.Forms) Project right now, and it works as expected.

**Comment by brianlagunas** [comment]
Great, let me look into this and see if there is anything I can do to improve this behavior.

**Comment by brianlagunas** [comment]
I think we figured it out. Give our latest CI on MyGet a try and see if you are still experiencing issues.

**Comment by yanshouwang** [comment]
@brianlagunas I tried it just now and it is really what I want~ thank you!

**Comment by brianlagunas** [comment]
Thanks for reporting it. I can't believe we didn't notice it before. You have a great eye for detail :)
