### ISSUE TITLE
Prism Template Studio and Developer Toolkit for Mac - Quickstart Prism Application

### ISSUE THREAD

**Issue by ngvanmy** [PrismLibrary/Prism#1547]
### Description

Hi,
I created my app with Quickstart Prism Application, it build successful. But, when build with my iphone failed. 
### Steps to Reproduce

1. Install latest version of Prism Template Studio and Developer Toolkit
2. Select one of the template except Quickstart Prism Application one.
3. Select Quickstart Prism Application.
4. Build app with emulator.
5. Build app with real iphone.
### Expected Behavior
Build and run app on real iphone
### Actual Behavior
Build error: 
_Error MT2101: Can't resolve the reference 'System.Threading.Tasks.Task`1<System.Boolean> Prism.Navigation.INavigationService::GoBackAsync(Prism.Navigation.NavigationParameters,System.Nullable`1<System.Boolean>,System.Boolean)', referenced from the method 'System.Threading.Tasks.Task Prism.Navigation.INavigationServiceExtensions::GoBackAsync(Prism.Navigation.INavigationService,System.String,System.Object,System.Nullable`1<System.Boolean>,System.Boolean)' in 'Prism.Forms, Version=7.0.0.124, Culture=neutral, PublicKeyToken=null'. (MT2101) (itqn.UrbanMap.iOS)_
### Basic Information

- Version with issue: 2.2.0.203
- Last known good version: N/A
- Xamarin.Forms version: 3.1.0.583944
- IDE: Visual Studio for Mac 7.7 Preview

**Comment by dvanblokland** [comment]
I had the same problems when I updated Prism.Forms to 7.1.0.279-pre and had Prism.Plugin.Popups version 2.0.0-pre6.
When I updated Prism.Plugin.Popups to version 2.1.0.182-pre the error disappeared.

**Comment by MarisB** [comment]
I still have the same problem if I build for Generic device. For simulator everything is ok.

**Comment by ngvanmy** [comment]
I updated Prism.Plugin.Popups to 2.1.0.182-pre the error disappeared, but have error:
Error MT2002: Failed to resolve "Prism.Navigation.INavigationService" reference from "Prism.Forms, Version=7.0.0.124, Culture=neutral, PublicKeyToken=null" (MT2002).

**Comment by dansiegel** [comment]
@ngvanmy you have references that do not work together. Prism.Plugin.Popups 2.1 and the last 2.0 preview are targeting Prism 7.1. The

**Comment by blombas** [comment]
I figured it out. Prism.extensions created the error. It is still referencing prism 7.0
Remove package will solve the problem
