### ISSUE TITLE
Xamarin.Forms Adding DependencyService attribute to each of the services classes in the respective platforms doesn't register the service

### ISSUE THREAD

**Issue by titolim** [PrismLibrary/Prism#1548]
### Description

I followed the documentation on Dependency Service to create a dependency service with prism. I wanted to use the DependencyService attribute on each on my platform specific implementation of the service but it's not working. If I register my service to the container in the "RegisterTypes" method of "UwpInitializer", it works. Looks like the DependencyService attribute doesn't register types automatically.

See Step 4 in Prism Xamarin.Forms docs: Attribute the DependencyService
"http://prismlibrary.github.io/docs/xamarin-forms/Dependency-Service.html"

### Steps to Reproduce

1. I created a simple application to reproduce the error. Just run it and it will throw an error when it tries to instanciate the MainPage view.

### Expected Behavior

By putting the DependencyService attribute on my implemented service class, the service will be registered in the container and available when injected into the MainPageViewModel class.

### Actual Behavior

The application was not able to create the MainPage view. Null exception is raised on "LoadApplication(new LearnPrismXamarin.App(new UwpInitializer()));"

### Basic Information

- Version with issue: Prism.Unity.Forms v7.0.0.396
- Last known good version: n/a
- Xamarin.Forms version: v.3.2.0.839982
- IDE: Visual Studio 2017 pro

### Screenshots

n/a

### Reproduction Link

Attached example here:
[LearnPrismXamarin.zip](https://github.com/PrismLibrary/Prism/files/2390442/LearnPrismXamarin.zip)

**Comment by brianlagunas** [comment]
I'm sorry, but that feature was removed in version 7.0.

https://github.com/PrismLibrary/Prism/releases/tag/7.0.0-Forms

All platform registrations should be against the container directly via the IPlatformInitializer.  We just need to remove the documentation topic.

**Comment by brianlagunas** [comment]
Resolved: https://github.com/PrismLibrary/Prism-Documentation/pull/12
