### ISSUE TITLE
Equate Prism.Autofac.Windows version

### ISSUE THREAD

**Issue by paulovila** [PrismLibrary/Prism#1559]
Hey guys, great job with the latest Prism.Windows drop. Keep up the good work 👍 
Would it be possible to have Prism.Autofac.Windows updated to the latest version? .

**Comment by dansiegel** [comment]
We currently have no plan of shipping Autofac for Prism.Windows, and are considering dropping support for it altogether. It really does have a terrible API, it's not very performant, and their decision to become an immutable container makes it incompatible with Prism Modularity.

**Comment by paulovila** [comment]
Then why you published Prism.Autofac for WPF?, Probably Prism Modularity shouldn't be part of Core, There are too many responsibilities grouped in the same library. Would you consider in your making Prism.Core compatible with platform Uno? It would be grate to use Prism in WASM.

**Comment by brianlagunas** [comment]
Prism.Autofac for WPF will be going away. Modularity is core to Prism guidance, and there is no need for it to go into a separate project. We are not currently looking at trying to another platform such as Uno at this time. Prism is open source so if someone would like tot take on that effort, that would be great.

**Comment by dansiegel** [comment]
> Then why you published Prism.Autofac for WPF?

As you'll see from the [Package Notices](https://github.com/PrismLibrary/Prism#package-notices) in the ReadMe, we have planned to drop support for Autofac following the 7.1 release. Should the maintainers of Autofac decide that they want to migrate back towards being a mutable container we will happily bring it back as a supported container.

> Probably Prism Modularity shouldn't be part of Core

Actually we feel that Prism's ability to help developers build Modular apps is a Core compentency. It is one of the reasons why developers love Prism, and why we've decided to unify the API, giving Xamarin.Forms developers the same rich features WPF developers have enjoyed, and why we've brought Modularity to the upcoming UWP preview.

> Would you consider in your making Prism.Core compatible with platform Uno

Prism.Core is shipped with net45, uwp, netstandard1.0 and netstandard2.0 binaries. I haven't dealt with Uno, but I can't imagine why you would be prevented from using Prism.Core
