### ISSUE TITLE
Suggestion: Expand the available Samples to include WPF examples and other DI containers

### ISSUE THREAD

**Issue by karlfl** [PrismLibrary/Prism#156]
I've created several versions of a simple WPF sample app to assist my understanding of Prism 6 and experiment with some of it's features, including other DI containers.  I'm willing to contribute them to this project to allow the community to enhance them further.  For now it's a very simple WPF app implemented using Prism and a few supporting modules.  You can take a look at the start of them in my [Prism Samples](https://github.com/karlfl/PrismSamples) repository.  Let me know if this helps.  Alternatively, if you create a GitHub repository for "Prism-Samples-WPF" and I'll create a pull request to contribute these. to the PrismLibrary.  Enjoy!

**Comment by brianlagunas** [comment]
Yes, we are definitely in need of samples.  We just haven't had time to create them yet.  I took a look at some of your samples and they are a great starting point.  I think there could be some improvements made, but overall very good.  We will discuss our format for samples and then give you guidance for your samples.

**Comment by brianlagunas** [comment]
I have created a new repo for the WPF samples.  You should look at the HelloWorld sample and simplify your samples to meet it's structure and code.

**Comment by karlfl** [comment]
Thanks Brian!
