### ISSUE TITLE
Xamarin.Forms MasterDetails navigation issue

### ISSUE THREAD

**Issue by markosavchuk** [PrismLibrary/Prism#1562]
Hi!

Navigation from master details has visual issue on navigation bar. It makes back arrow with old title for a second. I made sure it's Prism issue by checking Xamarin Forms and here is simple Xamarin.Forms sample with expected behavior https://github.com/xamarin/xamarin-forms-samples/tree/master/Navigation/MasterDetailPage

Also I investigated that this issue come after 6.3 update, as on Prism 6.3 it's also working as expected, here is sample with expected behavior from your repository https://github.com/PrismLibrary/Prism-Samples-Forms/tree/6cba8a651b52971ab7a7b748faf70a0b1e751eb6

- Version with issue: 7.0.0
- Last known good version: 6.3
- Xamarin.Forms version: 3.2.0
- IDE: VS for MAC

### Recorded video

[navigation issue.zip](https://github.com/PrismLibrary/Prism/files/2433742/navigation.issue.zip)

### Reproduction Link

Here is sample with actual behavior https://github.com/CrossGeeks/PrismV7Sample when your can reproduce that bug. Just navigate between pages by burger menu.

**Comment by brianlagunas** [comment]
This has already been fixed. You can test it with the latest CI build on our MyGet feed.
