### ISSUE TITLE
Primitive types are not supported as the generic. They must be nullable.

### ISSUE THREAD

**Issue by SkinnySackboy** [PrismLibrary/Prism#1566]
`DelegateCommand<int?>`

_Originally posted by @brianlagunas in https://github.com/PrismLibrary/Prism/issues/1385#issuecomment-370238388_

Hi Brian,

We have just started migrating our project to use Prism and have come across this issue. Do you know delegates intentionally exclude primitive types?

Cheers!

EDIT: Thinking about it, I presume this is because if someone binds to a command without a command parameter, the parameter for a primitive type will default to something that would almost certainly be incorrect/unwanted. Is this the case? If so, please feel free to simply close this question. Thanks!

**Comment by brianlagunas** [comment]
https://github.com/PrismLibrary/Prism/blob/master/Source/Prism/Commands/DelegateCommand%7BT%7D.cs#L14
