### ISSUE TITLE
Application.Resources not loaded in App

### ISSUE THREAD

**Issue by alex-dev** [PrismLibrary/Prism#1575]
### Description
Resources defined in Application.Resources in App.xaml are not loaded in App at runtime.

### Steps to Reproduce
```
<prism:PrismApplication x:Class="Hymperia.Facade.App" xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml" xmlns:prism="http://prismlibrary.com/">
  <Application.Resources>
    <Style x:Key="ListBox" TargetType="{x:Type ListBoxItem}" BasedOn="{StaticResource {x:Type ListBoxItem}}">
      <Style.Resources>
        <SolidColorBrush x:Key="{x:Static SystemColors.HighlightBrushKey}" Color="Red" />
        <SolidColorBrush x:Key="{x:Static SystemColors.ControlBrushKey}" Color="Red" />
      </Style.Resources>
    </Style>
  </Application.Resources>
</prism:PrismApplication>
``` 
### Expected Behavior
A defined Application.Resources should be loaded by the Application
### Actual Behavior
The application crashes loading any view containing a StaticReference to the resources. Application.Resource is also empty.
### Basic Information
- WPF, .NET Framework 4.6.1
- Prism 7.1.279-pre
- Ninject 3.3.4

### Reproduction Link
[PrismTest.zip](https://github.com/PrismLibrary/Prism/files/2464884/PrismTest.zip)

**Comment by brianlagunas** [comment]
This is actually one of those weird issues that happens in WPF. It is completely random and can happen when not using Prism. A simple web search will show tons of examples of it not working for people for various reasons.  It has to do with the complex nature of how resources are loaded and the order in which they are loaded.  You can fix this my either using a Merged dictionary
```
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <ResourceDictionary>
                    <Style x:Key="MyListBox" TargetType="{x:Type ListBoxItem}" BasedOn="{StaticResource {x:Type ListBoxItem}}">
                        <Style.Resources>
                            <SolidColorBrush x:Key="{x:Static SystemColors.HighlightBrushKey}" Color="Red" />
                            <SolidColorBrush x:Key="{x:Static SystemColors.ControlBrushKey}" Color="Red" />
                        </Style.Resources>
                    </Style>
                </ResourceDictionary>
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
```
Or just by adding another resource such as a background color
```
    <Application.Resources>

        <Style x:Key="MyListBox" TargetType="{x:Type ListBoxItem}" BasedOn="{StaticResource {x:Type ListBoxItem}}">
            <Style.Resources>
                <SolidColorBrush x:Key="{x:Static SystemColors.HighlightBrushKey}" Color="Red" />
                <SolidColorBrush x:Key="{x:Static SystemColors.ControlBrushKey}" Color="Red" />
            </Style.Resources>
        </Style>

        <SolidColorBrush x:Key="MyBackground" Color="Blue" />

    </Application.Resources>
```

**Comment by IoTFier** [comment]
Hi Brian, Happy New Year ! 

Thank you for helping us with this API.

I am in the process of moving my Xamarin Form based UI changes (made with the help of Gorilla) in a separate Xamarin App (Framework) project where I am using PrismLib to set up Navigation and MVVM.
 
I am experiencing similar issue in my Xamarin Forms App project [Prism Lib DryIoc.Forms v7.1.0.431 + Xamarin Forms v3.4.0.10009999] even when I have ResourceDictionary defined with the mergedwith attribute.

        
        <ResourceDictionary MergedWith="themes:myTheme">

…..</<ResourceDictionary>

Does this have to match exactly like the syntax in your response above ?

Thanks
