### ISSUE TITLE
Using the 'cmd' snippet in Visual Studio for Mac creates a non-functional ICommand

### ISSUE THREAD

**Issue by lewcianci** [PrismLibrary/Prism#1576]
### Description

Using the latest VS 4 Mac and Prism Extension Pack, writing "cmd" and then hitting tab twice creates this code:

        public DelegateCommand CommandName { get; } = new DelegateCommand(OnCommandNameExecuted);

        private void OnCommandNameExecuted()
        {
        }

![image](https://user-images.githubusercontent.com/9065229/46864741-9eb96d00-ce5e-11e8-8752-ea005653c542.png)

### Steps to Reproduce

1. Install Prism Template Pack and Developer Toolkit for VS 4 Mac
2. Use the 'cmd' snipper in a view model

### Expected Behavior

Working ICommand is produced

### Actual Behavior

Non-functional ICommand is produced

### Basic Information

- Version with issue: VS 7.6.9, latest prism template pack for VS4Mac
- Last known good version: N/A
- Xamarin.Forms version: 3.1
- IDE: VS4MAC

**Comment by lewcianci** [comment]
Using MFractor to produce a view model command yields other code, but it is still non-functional

```
public DelegateCommand TestCommand { get; }
        private void OnTestCommandExecuted()
        {

        }
```

**Comment by brianlagunas** [comment]
@dansiegel It appears the code snippet is not correct and would not function properly. It needs to be updated to match what we provide in the Windows version.

**Comment by dansiegel** [comment]
will be fixed in the next release

**Comment by lewcianci** [comment]
@dansiegel Thanks for that. Just so I can keep coding, is there any way to get it to work?  I noticed that the Prism QuickStart has the MFractor configuration - is there anything I can do to get the MFractor command creation working to generate working ICommands? Thank you so much.

**Comment by dansiegel** [comment]
initialize it in the ctor

**Comment by lewcianci** [comment]
@dansiegel It's still not working correctly and I've updated the toolkit for visual studio... Any other tips?

Also congrats on the amazing 7.1.0 release! @brianlagunas @dansiegel You guys are the best.
