### ISSUE TITLE
Prerelease NuGet package for Prism.Windows

### ISSUE THREAD

**Issue by tomzorz** [PrismLibrary/Prism#158]
I just saw the merged pull request for the UWP demo project, but it's referencing the Prism.Windows stuff directly, not via a NuGet package.

Could you create a prerelease NuGet package for Prism.Windows so we can begin testing as well?

**Comment by bartlannoeye** [comment]
The sample projects under this repository are for development purposes. Stable samples based on NuGet packages will be posted under the [Prism-Sample-Windows](https://github.com/PrismLibrary/Prism-Samples-Windows) repository once the packages are released.

We're closing up the last few issues for an UWP release and hope to have RTM NuGet packages available soon. But you're right, nothing (except time :)) keeps us from creating a pre-release package and it has been on my mind the last few days as well. I'll try to have a look at creating them this weekend and ask @brianlagunas to drop them on NuGet asap.

**Comment by tomzorz** [comment]
Thank you! Until then I think I'll try to look at https://github.com/PrismLibrary/Prism/issues/146 myself if I get a little time, as that was one of the issues we were experiencing as well with our project.

**Comment by brianlagunas** [comment]
Yes, it's just a time thing at this point.  We are want to get a preview out as soon as we can.  Also keep in mind, that for UWP, we have to use the new NuGet JSON format to create the package which honestly is a major pain in the ass.  NuGet is a hot mess right now.

**Comment by tomzorz** [comment]
Oh yes I'm aware - saw exactly that with the Newtonsoft.Json package here https://gist.github.com/JamesNK/56b1c3b90b2a8d21c73d :)

**Comment by bartlannoeye** [comment]
Trying to get @onovotny's [tool](https://github.com/onovotny/ReferenceGenerator) to generate us the dependency part of the nuspec files. Trying to find out how to deal with multiple packages generated in the same solution and solving the dependencies between them.

**Comment by onovotny** [comment]
Are the current nuspec files checked in anywhere? I took a quick look but didn't see any - might have missed them though.

You mentioned two packages with some overlap of what's in them - that's the part that's confusing me right now. What are the packages, what's in them and what's the potential overlap?

**Comment by bartlannoeye** [comment]
I've pushed them to https://github.com/bartlannoeye/Prism/tree/Prism-NuSpec.
When you open the Win10 solution, you have following projects:
* Prism (already a [package on NuGet](https://www.nuget.org/packages/Prism.Core/), but nuspec isn't checked in)
* Prism.Windows
* Prism.Unity.Windows

Each of those 3 projects are a single package with dependencies following the project references: Prism.Unity.Windows > Prism.Windows > Prism.
Because of the project references, Prism.Unity.Windows get all 3 assemblies in the project output, but I can filter that out. It would be awesome though if the dependencies would get added automatically to the nuspec, but I know that probably won't be an easy one.

**Comment by onovotny** [comment]
Okay, starting to make sense now. It sounds like those should be independent packages with their own nuspecs - and you're right, you'd want to filter out the others from your packaging.

As to having the reference generator adding Prism.Windows to Prism.Unity.Windows, it can't currently do that. It has no way to know/detect what package that reference will ultimately reside in. It should pick up the Unity and Common Service Locator packages correctly though.

The nuspecs in your fork seem ok. As to the files, you probably need something like this in your nuspec:
https://github.com/xunit/devices.xunit/blob/master/src/xunit.runner.devices.nuspec#L78-L82

**Comment by bartlannoeye** [comment]
Thanks for confirming my thoughts. The files part I got (pretty similar to 8.1), just need to add the AnyCPU configuration for the libraries again first.
