### ISSUE TITLE
7.1.0 Documentation

### ISSUE THREAD

**Issue by steji113** [PrismLibrary/Prism#1580]
I checked out the documentation links and repo referenced in the project's README but it seemed to be about version 6. Are there plans to release documentation updates for the newly released 7.1.0? If so, would you happen to know a time frame?

Thanks so much for the new release!

**Comment by brianlagunas** [comment]
Docs are on our extremely long list of things to do. If you feel like you can contribute, here is the repo:

https://github.com/PrismLibrary/Prism-Documentation
