### ISSUE TITLE
Unable to build source code with examples on Mac OSX

### ISSUE THREAD

**Issue by alexshikov** [PrismLibrary/Prism#1581]
### Steps to Reproduce

1. Check out the repo (using master branch) version 7.1.x on Mac OSX
2. Run sample `HelloWorld.iOS`

### Expected Behavior

Successful compilation. Sample runs.

### Actual Behavior

Build failed with an error:

```
error MSB4018: The "Microsoft.Build.Tasks.Git.LocateRepository" task failed unexpectedly.
error MSB4018: System.TypeInitializationException: The type initializer for 'Microsoft.Build.Tasks.Git.TaskImplementation' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Build.Tasks.Git.Operations' or one of its dependencies
error MSB4018:   at System.AppDomain.Load (System.Reflection.AssemblyName assemblyRef, System.Security.Policy.Evidence assemblySecurity) [0x001a9] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-02/external/bockbuild/builds/mono-x64/mcs/class/corlib/System/AppDomain.cs:777 
error MSB4018:   at (wrapper remoting-invoke-with-check) System.AppDomain.Load(System.Reflection.AssemblyName,System.Security.Policy.Evidence)
error MSB4018:   at System.AppDomain.Load (System.Reflection.AssemblyName assemblyRef) [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-02/external/bockbuild/builds/mono-x64/mcs/class/corlib/System/AppDomain.cs:714 
error MSB4018:   at (wrapper remoting-invoke-with-check) System.AppDomain.Load(System.Reflection.AssemblyName)
error MSB4018:   at System.Reflection.Assembly.Load (System.Reflection.AssemblyName assemblyRef) [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-02/external/bockbuild/builds/mono-x64/mcs/class/corlib/System.Reflection/Assembly.cs:600 
error MSB4018:   at Microsoft.Build.Tasks.Git.TaskImplementation..cctor () [0x0006b] in /_/src/Microsoft.Build.Tasks.Git/TaskImplementation.cs:32 
error MSB4018:    --- End of inner exception stack trace ---
error MSB4018:   at Microsoft.Build.Tasks.Git.LocateRepository.Execute () [0x0000f] in /_/src/Microsoft.Build.Tasks.Git/LocateRepository.cs:27 
error MSB4018:   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute () [0x00023] in /_/src/Build/BackEnd/TaskExecutionHost/TaskExecutionHost.cs:631 
error MSB4018:   at Microsoft.Build.BackEnd.TaskBuilder+<ExecuteInstantiatedTask>d__26.MoveNext () [0x00212] in /_/src/Build/BackEnd/Components/RequestBuilder/TaskBuilder.cs:787 
```

### Basic Information

- Version with issue: master branch of v7.1.0.431, commit hash 9d05095de2275898711b12c73ec157a4038649db
- Last known good version:
- Xamarin.Forms version:
- IDE: **Visual Studio for Mac** version 7.6.9 (build 22)

### Additional

Looks like related to https://github.com/dotnet/sourcelink/issues/155 but would be great to know if there is a temporary workaround.

**Comment by brianlagunas** [comment]
Since you are using source code, I would guess the workaround would be to uninstall the Microsoft.SourceLink.GitHub package from Prism.

**Comment by alexshikov** [comment]
That helped, thanks!

Though removing reference was not obvious. It's specified in `Directory.Build.props` https://github.com/PrismLibrary/Prism/blob/9d05095de2275898711b12c73ec157a4038649db/Source/Directory.Build.props#L62-L64

**Comment by dansiegel** [comment]
Building on Mac is plain NOT Supported. While I love VS Mac there are simply too many limitations for us to support building from source. There are a variety of reasons for this including that we are multi-targeting which the IDE does not support though building from the cli does. Also because we have UWP targets that do not exist. 

As for the not obvious comment. This is a preferred MSBuild way of handling these issues though most developers are not used to working with these advanced concepts. 

Closing as this works as expected.

**Comment by alexshikov** [comment]
@dansiegel indeed, VS Mac has limitation and sometimes the project simply can't be built at all. Though it worth to try in some cases to find a workaround and this one actually works! :)

As for the not obvious comment. Just decided to mention a solution if other struggle with that too.

Thanks for the support. Hope one day VS Mac be same usable as VS Win.
