### ISSUE TITLE
UWP Unity extension has a dependency to Prism.Wpf?

### ISSUE THREAD

**Issue by Seikilos** [PrismLibrary/Prism#1586]
When looking on the required nuget packages for **UWP** from this [site](https://prismlibrary.github.io/docs/getting-started/NuGet-Packages.html), the Prism.Unity.Windows page links to this [Prism.Unity package](https://www.nuget.org/packages/Prism.Unity/).

Now when expanding the dependencies, this package seems to depend on 
>  Prism.Wpf (>= 7.1.0.431) 

Is this intentional? I did not expect a WPF dependency in a UWP context.

**Comment by brianlagunas** [comment]
The links on the readme should be correct.  https://github.com/PrismLibrary/Prism/blob/master/README.md

**Comment by Seikilos** [comment]
@brianlagunas  Thanks for the hint. Do you have a definitive commitment to Unity as a Prism DI Container? Because the Prism.Unity.Windows on nuget is a 10 _months_ old pre-release (myget is a black box for me because I cannot even see meta-data of packets there without signing in o_0).

This might be a risk using Unity at the moment, the same way Autofac would be a risk because it appears to be phased out for prism due to its design decisions.

**Comment by brianlagunas** [comment]
Unity works great and is up to date on MyGet.  I can browse it just fine without logging in:

https://www.myget.org/feed/prism/package/nuget/Prism.Unity.Windows

**Comment by Seikilos** [comment]
@bartlannoeye See my pull request #1587 , typos in the README.md caused issues.

**Comment by bartlannoeye** [comment]
UWP clearly says https://www.nuget.org/packages/Prism.Unity.Windows/ as
dependency, not Prism.Unity

>

**Comment by brianlagunas** [comment]
@bartlannoeye right, but @Seikilos was talking about the links in the docs pointing to the wrong location which will need t be fixed.

**Comment by bartlannoeye** [comment]
Guess GitHub issues and reply by mail made my reply arrive out of sync :) But at least it's solved now 👍
