### ISSUE TITLE
[XF] RegisterRequiredTypes for INavigationService doesn't work (infinite loop !)

### ISSUE THREAD

**Issue by draudrau** [PrismLibrary/Prism#1588]
### Description

I have a Xamarin Forms project using prism v7.0
I use the RegisterRequiredTypes method to override the behavior of INavigationService.
It work fine with v7.0
I have upgraded to v7.1 and it doesn't work any more.
I have an inifinte recursive call on NavigateAsync method.

### Steps to Reproduce

1. Open project gived in the google drive url below
2. put a breakpoint in the MyNavigationService.cs file at line 22
3. Run in debug mode

### Expected Behavior
HomePage is displayed

### Actual Behavior
Inifinte recursive call on NavigateAsync method.

### Basic Information

- Version with issue: 7.1.0.431
- Last known good version: 7.0.0.396
- Xamarin.Forms version: 3.3.0.912540
- IDE: VS2017 v15.8.7

### Reproduction Link

https://drive.google.com/open?id=1tJ28nIkNbsxrYne10oZD_Br8HFw_1Un5

**Comment by brianlagunas** [comment]
You're making a recursive call, which would explain your infinite loop. You need to pass your parameters in order to call the base of the you are overriding.

```
return await base.NavigateAsync(pagePath, myParameters);
```

**Comment by draudrau** [comment]
it's a shame that it works like this.
When the override method call the base method, it should be the real base method and not the one which is overridden. So I can execute some specific code and then call the base method.

**Comment by draudrau** [comment]
Sorry for my code. I've done quickly this project to do an example. I've omitted to pass the parameter.
Use the RegisterRequiredTypes fonctionality doesn't offer much flexibility. I can't override NavigateAsync method with one with additional parameters as this signature doesn't exists in the interface. So this overriden method can't be used. I can't redifine the method (with new) as I can't call base method.
So if I need to do some stuff in the NavigateAsync method (add some controls for example) and the call the NavigateAsync base method, it's not possible.

I have to search another solution :-(.

Thanks for your explanation.
