### ISSUE TITLE
Question: Documenation, HowTo

### ISSUE THREAD

**Issue by Blackjack92** [PrismLibrary/Prism#159]
Hello guys,

great Framework!
is there any documentation or a how to especially for Prism 6?
Because there exist so many features of prism and i dont want to miss any of them.

Regards,
Kevin

**Comment by brianlagunas** [comment]
You can read the documentation for Prism 5 on MSDN:  https://msdn.microsoft.com/en-us/library/gg406140.aspx?f=255&MSPPError=-2147217396

Not a lot has changed functionality wise.  The main changes were in assembly references and namespaces.  We did add some new functionality to Prism 6 that I will cover in a blog post soon.

**Comment by brianlagunas** [comment]
I also have a number of PluralSight courses that cover Prism:  http://www.pluralsight.com/author/brian-lagunas

I will be updating the intro course to Prim 6 soon.

**Comment by Blackjack92** [comment]
thx

**Comment by ChSchmidt81** [comment]
Hi Brian,

will you make a Pluralsight course for Prism 6? Maybe with UWP content?

Thanks
Christian

**Comment by bartlannoeye** [comment]
I think UWP content is more something for @briannoyes instead, not sure if he has anything planned.

I've got a series of posts for UWP planned myself, but I don't expect them before end of spring (swamped with work right now).

**Comment by brianlagunas** [comment]
@briannoyes already has a course for Prism and WinRT here:
