### ISSUE TITLE
No Possible to load module(ASP.NET Core 2+) using Prism

### ISSUE THREAD

**Issue by Ghislain1** [PrismLibrary/Prism#1590]
### Description
A Module is not loaded when a project is target to .NET Core 2+.

### Steps to Reproduce

1. Clone a project [07-Modules - AppConfig](https://github.com/PrismLibrary/Prism-Samples-Wpf/tree/master/07-Modules%20-%20AppConfig)
2. Add a new project with Target .NET Core 2+
3. Install Prism.Core package
4. Create new class  e.g. HomeModule to implement IModule
5. Xcopy command in Build event
6. Registry module in app.Config
7. Build all and run the solution

### Expected Behavior
The desired HomeModule should load like ModuleAModule 

### Actual Behavior
**Prism.Modularity.ModuleTypeLoadingException:** 'Failed to load type for module HomeModule. 
Error was: Unable to retrieve the module type StockTraderRI.Modules.Home.HomeModule, StockTraderRI.Modules.Home, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null from the loaded assemblies.  You may need to specify a more fully-qualified type name..'

### Basic Information

- Version with issue: Prism: 7.1.0.431
- Last known good version:

- IDE: VS2017

### Screenshots

![image](https://user-images.githubusercontent.com/13945825/47372048-3e8dbb00-d6e9-11e8-8da0-9849e8afba30.png)

What do i do wrong?

**Comment by brianlagunas** [comment]
Closed as there is no reproduction app provided.  Also, it really doesn't make sense to have a module as a .NET core 2.0 assembly as you cannot use WPF in a .NET Core 2.0 assembly.
