### ISSUE TITLE
AutoWiring ViewModel for partial views not working in separate assemblies

### ISSUE THREAD

**Issue by Jaguel** [PrismLibrary/Prism#1591]
Hi,
From my understanding we can register a partial view in a page using:
 

    ViewModelLocator.AutowirePartialView="{x:Reference currentPageName}" 

 and also registering our partial view in container like:

    containerRegister.Registry<MyPartialView>();
    containerRegister.Registry<MyPartialViewModel>();
But it seems to work and OnNavigatedTo gets called for MyPartialViewModel only when MyPartialView and MyPartialViewModel are located in same assembly.
I can't find a proper Register method for registering MyPartialView and MyPartialViewModel together (without using reflection behind the scene) and tell Prism that they are pair even if they are in different assemblies as we do in registering pages like:

    containerRegistry.RegisterForNavigation<MyView, MyViewModel>("MyView");
Thanks in advance.

**Comment by brianlagunas** [comment]
Technically, you don't need to register the View/VM with the container. You just need to tell the VML how to associate your VM with the View.  To do this use
```
ViewModelLocationProvider.Register<View, ViewModel>();
```
This is definitely a documentation issue.
