### ISSUE TITLE
EventToCommandBehavior does not call Command with EventArgs unless converter is used

### ISSUE THREAD

**Issue by charristti** [PrismLibrary/Prism#1593]
### Steps to Reproduce

1. Add EventToCommandBehavior to Syncfusion SfListView

```
<xListView:SfListView.Behaviors>
       <behaviors:EventToCommandBehavior
                  EventName="SwipeStarted" 
                  Command="{Binding ContentViewModel.SwipeStartedCommand}"/>
</xListView:SfListView.Behaviors>
```
2.  Add command and methods to view model.

```
        SwipeStartedCommand = new DelegateCommand<object>(OnSwipeStarted);
        private void OnSwipeStarted(object obj)
        {
        }

```

3. Run application and swipe on list view

### Expected Behavior
Expect to see OnSwipeStarted called with SwipeStartedEventArgs object
### Actual Behavior
Actual behavior is OnSwipeStarted is called with null object
### Basic Information
Adding a converter which simply passes thru the object gives the expected result.

```
 public class SwipeStartedEventArgsConverter : IValueConverter
    {
        public object Convert(object value, Type targetType, object parameter, CultureInfo culture)
        {
            var swipeStartedEventArgs = value as SwipeStartedEventArgs;
            if (swipeStartedEventArgs == null)
            {
                throw new ArgumentException("Expected value to be of type SwipeStartedEventArgs", nameof(value));
            }

            return swipeStartedEventArgs;
        }

        public object ConvertBack(object value, Type targetType, object parameter, CultureInfo culture)
        {
            throw new NotImplementedException();
        }
    }

```

- Version with issue: 7.1.0.431
- Last known good version: ?
- Xamarin.Forms version: 3.2.0.871581
- IDE: Visual Studio 2017 15.8.7

### Reproduction Link

Recommended fix to EventCommandBehavior.cs is attached (starting a line 205)
[EventToCommandBehavior.zip](https://github.com/PrismLibrary/Prism/files/2507973/EventToCommandBehavior.zip)

**Comment by brianlagunas** [comment]
This is by design.  You should never pass event arg objects to a VM. You should always get the data you need off of the event args instead by setting the EventArgsParameterPath or EventArgsConverter. I will make a note in the documentation
