### ISSUE TITLE
NavigationParameter should have a constructor with string key, object value

### ISSUE THREAD

**Issue by Nk54** [PrismLibrary/Prism#1595]
Hello,

First, I love Prism. I often use the NavigationParameter. Most of the time, I add complex object.
I need to do :
```
var param = new NavigationParameters();
param.Add("a key", anObject);
```          

I've made an extension method which allows me to write : 
`var param = new NavigationParameters().With("a key", anObject).With("another key", anotherObject);
`

Here is the code :
```
public static NavigationParameters With(this NavigationParameters navigationParameters, string key, object value)
{
    if (navigationParameters == null)
        navigationParameters = new NavigationParameters();

    navigationParameters.Add(key, value);
    return navigationParameters;
}
```

But it would have been nicer to be able to do

`var param = new NavigationParameters("a key", anObject);
`

What do you think about that ?

**Comment by powerdude** [comment]
what's wrong with doing this:

`var param = new NavigationParameters{{"a key", anObject}};`

**Comment by brianlagunas** [comment]
We will not be providing a ctor that accepts only a single parameter. I would use @powerdude suggestion instead. It's the same thing, except it supports multiple parameters

**Comment by Nk54** [comment]
Yeah you guys are right and I thought about it too. But that's two useless bracket when 90% of the time you'll end up with only one parameter :D but I'm ok with your answer.
It's just I have the bad habit of writing stuff like that
`new NavigationParameter() {{"a key", "an object");`
Maybe I should correct this habit instead and trying to change a framework :)

Keep up the good work. Thanks for your fast answer both of you.
Have a good weekend !
