### ISSUE TITLE
Prism Template Pack: Snippets

### ISSUE THREAD

**Issue by horseyhorsey** [PrismLibrary/Prism#1596]
It's been a while since used Prism but today I've gone to use "propp" and it's not there?

I tried reinstalling the extension with latest version but no snippets appear. Templating is fine, just the snippets.

Any idea?

VS 15.8.7

**Comment by brianlagunas** [comment]
Yeah, VS is horrible at updating/installing snippets. open up your snippet manager and I bet you will see a yellow warning triangle on the Prism snippets. Use the link to find the real location of the snipet and update the location.  Let me know if you are still having issues.
