### ISSUE TITLE
Add support for AutoFac

### ISSUE THREAD

**Issue by brianlagunas** [PrismLibrary/Prism#16]
This is being split from Issue #15 

Right now, Prism supports Unity and MEF out of the box, but we would love to add support for other containers.

If you would like to submit support for a container, use the Prism.Mef.Wpf, Prism.Unity.Wpf and Prism.Unity.Forms projects as a guideline. As you can see the naming convention is Prism... The namespace should follow the Prism. convention and not include the platform. For example, if using Autofac, the namespace should be Prism.Autofac.

**Comment by bartlannoeye** [comment]
In case somebody else is looking into adding support for Autofac, I'm having a go at it on [my fork](https://github.com/bartlannoeye/Prism) and I wouldn't want us to do double work. But don't hesitate to stop by for review or helping a hand, so we can group everything in a single pull request for Autofac.
