### ISSUE TITLE
Prism.Wpf: InitializeModules() should be called even if there's no shell

### ISSUE THREAD

**Issue by dro123** [PrismLibrary/Prism#1601]
### Description

PrismApplicationBase.cs has this code right now:

```c#
            var shell = CreateShell();
            if (shell != null)
            {
                RegionManager.SetRegionManager(shell, _containerExtension.Resolve<IRegionManager>());
                RegionManager.UpdateRegions();
                InitializeShell(shell);
                InitializeModules();
            }
```

My application can also run as a consol application and in that case I want the modules even though there's no shell.

My current workaround is to call InitializeModules() myself in CreateShell() but this seems fragile.
Is there a reason InitializeModules() is only called if there's a shell?

Another point is that OnInitialized() crashes if there's no shell because MainWindow is null. So right now if there's no shell the application crashes if OnInitialized() is not overwritten and the base method not called.

**Comment by brianlagunas** [comment]
What value are you getting out of Prism for WPF if you have no views/regions? Also, how do you prevent your modules from crashing since no regions exist in the app to inject any views?

**Comment by dro123** [comment]
More or less only that it will load my modules.
The application is when run without command line parameters a normal WPF GUI application with regions and views. But I can specify command line parameters and in that case I don't need the UI part, just the module loading.

**Comment by brianlagunas** [comment]
Normally, I would say this isn't something I would allow. However, I do see that the old bootstrapper did allow for this, and the code changes are very minimal to support it.  So I will merge your PR.  Thanks for that by the way :)

**Comment by brianlagunas** [comment]
This has been fixed. You can test out the changes in the latest CI build on our MyGet feeed when the build has completed in about 20 minutes.

**Comment by dro123** [comment]
Just checked 7.1.0.559-ci and it works fine. 
Thank you!
