### ISSUE TITLE
[XF] Master page stay open after navigation

### ISSUE THREAD

**Issue by draudrau** [PrismLibrary/Prism#1603]
### Description

When using **NavigateTo** in Xaml and **SourcePage** in a MasterDetailPage, the master page stays open.

I need to use this facility described in documentation :
[Defining your Source Page](https://prismlibrary.github.io/docs/xamarin-forms/navigation/xaml-navigation.html#defining-your-source-page)

But after navigation, the master page stays open.

My MasterDetailPage looks like this one :

```xaml
<MasterDetailPage xmlns="http://xamarin.com/schemas/2014/forms"
                  xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
                  xmlns:prism="clr-namespace:Prism.Mvvm;assembly=Prism.Forms"
                  xmlns:navigation="clr-namespace:Prism.Navigation.Xaml;assembly=Prism.Forms"
                  xmlns:cc="clr-namespace:MyApp.CustomControls;assembly=MyApp"
                  xmlns:views="clr-namespace:MyApp.Views;assembly=MyApp"
                  prism:ViewModelLocator.AutowireViewModel="True"
                  x:Class="MyApp.Views.MasterDetailMenuPage">
    <MasterDetailPage.Master>
        <ContentPage>
            <StackLayout>
                <cc:MenuItem Text="First Page" ImageSource="FirstPage.png"
                             Command="{navigation:NavigateTo 'FirstPage', SourcePage={x:Reference HomePage}}"/>

                <cc:MenuItem Text="Second Page" ImageSource="SecondPage.png"
                             Command="{navigation:NavigateTo 'SecondPage', SourcePage={x:Reference HomePage}}"/>

                <cc:MenuItem Text="Third Page" ImageSource="ThirdPage.png"
                             Command="{navigation:NavigateTo 'ThirdPage', SourcePage={x:Reference HomePage}}"/>
            </FlexLayout>
        </ContentPage>
    </MasterDetailPage.Master>
    <MasterDetailPage.Detail>
        <NavigationPage>
            <x:Arguments>
                <views:HomePage x:Name="HomePage"/>
            </x:Arguments>
        </NavigationPage>
    </MasterDetailPage.Detail>
</MasterDetailPage>
```
**MenuItem** is a custom control.
The purpose of this is to stack the pages on the **HomePage**, like this :

/MasterDetailPage/NavigationPage/HomePage/FirstPage

- Version with issue: 7.1.0.431
- Xamarin.Forms version: 3.3.0.912540
- IDE: VS 2017 version 15.8.8

**Comment by brianlagunas** [comment]
Of course the Master won't close since you aren't navigating using the MasterDetailPage.  You are navigating directly from the DetailPage which has no knowledge of the MDP.

Also, you just have to create a custom NavigationPage and have it implement INavigationPageOptions and set ClearNavigationStackOnNavigation to false. Then each page will be added to the stack.

**Comment by brianlagunas** [comment]
If you want to continue to use your approach, you should edit your custom control to get the master and close it on Click.

**Comment by draudrau** [comment]
Thanks for these advices.
I'll test it.
