### ISSUE TITLE
When update prism nuget for UWP, breaking changes all the time

### ISSUE THREAD

**Issue by StanleyBroo** [PrismLibrary/Prism#1605]
### Description

Why do prism constantly change namespaces and such causing breaking Changes when updating the nuget. Isn't there any back compability. As it is now ..one for sure doesn't update the prism nuget until next Project unless you have a time to read up on all the breaking Changes.
### Steps to Reproduce

1. 
2. 
3. 

### Basic Information

- Version with issue:
- Last known good version:
- Xamarin.Forms version:
- IDE:

**Comment by bartlannoeye** [comment]
UWP does not have an official v7 release yet. Once that is released, we'll offer a guide how to upgrade. The deal about [semver](https://semver.org/) is that major releases can have breaking changes. We only make them to streamline platforms, not for fun.
