### ISSUE TITLE
DelegateCommand ObserveCanExecute not waiting on animation

### ISSUE THREAD

**Issue by rredoh** [PrismLibrary/Prism#1608]
### Description

When I navigate to modal page, opening camera, or anything that do some animation, it likely bypass ObserveCanExecute. A simple `if(!can_click) return;` fix this.

### Steps to Reproduce

1.  Add a button
2.  Bind to DelegateCommand with ObserveCanExecute
3.  Add some method to navigate to modal page with animation, or open camera, or open gallery
3.  Click the button twice before the modal page completely shown

### Expected Behavior
Should protect from more than 1 click
### Actual Behavior
Opening modal page as much as the number of clicks
### Basic Information

- Version with issue: 7.1.0.544-ci
- Xamarin.Forms version: 3.3.0.967583
- IDE: VS 15.8.9

### Reproduction Link

[Reproduction](https://github.com/rredoh/ObserveCanExecuteRepro)

**Comment by brianlagunas** [comment]
The DelegateCommand does not know when you want to click the button or not. It is your responsibility to control the state of your UI elements.

**Comment by rredoh** [comment]
May I ask then when to use ObserveCanExecute ?

**Comment by brianlagunas** [comment]
ObservesCanExecute simply uses the property you provided as the return for the CanExecute delegate and notifies the UI of state changes to that property by calling RaiseCanExecuteChanged.  If CanExecute is false, the command cannot be invoked. You must make sure you are properly controlling that logic.

**Comment by rredoh** [comment]
Ok. Thanks for the explanation :)
