### ISSUE TITLE
Understand prism dependencies with XF

### ISSUE THREAD

**Issue by Umar3x** [PrismLibrary/Prism#1610]
### Description

Hello all,

I'm new to prism and I wanted to understand which package is needed and why when creating a xamarin forms prism application using unity container.

When I create a new Prism Project using Unity container from Prism Template Pack, I can see in Nuget that all my projects have Prism.Unity.Forms v7.1.0.431 being installed. Right for now its clear for me.

When adding a Prism Module, I can see that the module has Prism.Forms v7.1.0.431 but not Prism.Unity.Forms.

**Prism.Unity.Forms** : "Use these extensions to build Xamarin.Forms applications with Prism and Unity".

**Prism.Forms** : "Prism provides an implementation [...]"

Perhaps this is a newb question, Ive been looking in each repos to get clews but this is still not clear in my mind. 

**_Note_** : I don't have any probs, I can build and deploy my solution, everything's perfect. I just wanted a simple clarification w/o diving into prism core functionnality for now. 

- Prism 7.1.0.431
- Xamarin.Forms version: 3.3
- IDE: VS 2017

**Comment by totht91** [comment]
If you look at the Forms.Unity.Forms nuget's dependencies at https://www.nuget.org/packages/Prism.Unity.Forms/ you can see that it also transitively references the Prism.Forms package.

**Comment by dansiegel** [comment]
@Umar3x as was noted in the issue template, questions should be asked on StackOverflow. That said @totht91 has answered your question, if you require further clarification please ask it on StackOverflow.
