### ISSUE TITLE
Navigation with '../TargetPage' doesn't work from TabbedPage

### ISSUE THREAD

**Issue by explorer566** [PrismLibrary/Prism#1611]
### Description

Using a navigation like '../TargetPage' within a content page works as expected, but doing the same thing within a content page that is part of a tabbed page doesn't work.

### Basic Information

Prism version: Autofac for Prism 7.1.0.431
Xamarin.Forms version: 3.3.0.967583
IDE: Visual Studio for Mac: 7.6.11 (build 9) on Mac OS X 10.14.1

### Example

I'm trying to upload a sample project if I can persuade my admin to configure our firewall accordingly

**Comment by brianlagunas** [comment]
Relative Back `../` navigation **only** works when you are within a NavigationPage.

**Comment by explorer566** [comment]
Hi Brian,

please have a look at my project sample where navigation takes place within a NavigationPage.
The "Navigate"-Button works in the "Normal Page" but not in the "Tabbed Page".

Regards
Ralf

[PrismNavigation.zip](https://github.com/PrismLibrary/Prism/files/2562584/PrismNavigation.zip)
