### ISSUE TITLE
[Question] How to switch tabs

### ISSUE THREAD

**Issue by stesvis** [PrismLibrary/Prism#1612]
I have a TabbedPage with Tab1, Tab2, Tab3, and i want to programmatically switch from Tab1 to Tab2 and pass a parameter.

I tried this: 
`await NavigationService.NavigateAsync("Navigation/MainTabbedPage?selectedTab=Tab2", navigationParams);`
and this:
`await NavigationService.NavigateAsync("/Navigation/MainTabbedPage?selectedTab=Tab2", navigationParams);`

but it both cases this happens chronologically:

Tab2--->OnNavigatedTo
and then
Tab2--->Constructor

Is there a way to just switch the tabs and pass a parameter without reloading the Tab2 page and not call its constructor?

**Comment by brianlagunas** [comment]
There is no built-in mechanism to switch tabs programmatically.

**Comment by brianlagunas** [comment]
I have created an issue to implement this behavior follow #1615

**Comment by stesvis** [comment]
That would be awesomeee!
Thanks Brian
