### ISSUE TITLE
[XF] Add the ability to switch tabs

### ISSUE THREAD

**Issue by brianlagunas** [PrismLibrary/Prism#1615]
### Description

When you are within a TabbedPage, it is sometimes necessary to change tabs, but not actually navigate to another page. Simply select a different tab in the same TabbedPage. It would be helpful to pass parameters and respect the INavigationAware and IConfirmaNavigation interfaces so I can control if I am allows to switch tabs, and have access to various parameters as I change tabs.

### API Spec
I am thinking of adding a new extension method for the INavigationSevice called `SelectTab`. In order to access this method, you would add a new namespace to your ViewModel.

`using Prism.Navigation.TabbedPages`

with the namespace added you wil be abls to select a new tab with

`navigationService.SelectTab("tabName", parameters)`

**Comment by brianlagunas** [comment]
This has ben implemented and is available in the latest CI build on our MyGet feed.

**Comment by stesvis** [comment]
When will this be available in the stable NuGet package?

**Comment by brianlagunas** [comment]
We do not have or piblish any release dates.

Read how to add CI builds here:  http://prismlibrary.github.io/docs/getting-started/NuGet-Packages.html

**Comment by stesvis** [comment]
Thanks, if i am not mistaken, does the latest version require the pre-release of Xamarin.Forms?
