### ISSUE TITLE
Suggestion: Move from classical mvc to "RazorPages-like" project structure

### ISSUE THREAD

**Issue by wocar** [PrismLibrary/Prism#1618]
Hello my suggestion is instead of using the classical MVC approach for the project structure, move to the "razorpages-like" structure, I think it makes thinks cleaner. 

I'm aware that by convention that this already can be done by using the PageName + ViewModel, however my concrete suggestion is that the template by default, creates the files in this manner example:

```
  <ItemGroup>
    <Compile Update="Views\Attachmens\AttachPageViewModel.cs">
      <DependentUpon>AttachPage.xaml</DependentUpon>
    </Compile>
  </ItemGroup>
```

to have something like this:
![image](https://user-images.githubusercontent.com/9215073/48374398-5a520480-e68a-11e8-85d3-b01f1a7b0d0c.png)
and a much cleaner project structure instead of having to mantain two big folder trees.

What do you think?

**Comment by brianlagunas** [comment]
Actually, in large WPF production app this is exactly how I do it.  However, having the templates use the distinct folder really helps with the learning curve and helps to discover the patterns being used.  I am considering adding an "Options" item in the VS Options dialog to control how these are created, but that is a very low priority.

**Comment by wocar** [comment]
Ok got you. Do you simply do it by editing the csproj or do you have a shorthand way of doing it?

**Comment by brianlagunas** [comment]
I use a VS extension to do it. Right click and done.

**Comment by AwsomeCode** [comment]
I use my view models on multiple pages.

**Comment by powerdude** [comment]
@brianlagunas which VS extension?
