### ISSUE TITLE
DelegateCommand Execute Handlers getting released randomly in unit testing

### ISSUE THREAD

**Issue by zein-makki** [PrismLibrary/Prism#1620]
### Description

We're stuck with Prism 4 for the next weeks until we upgrade to Prism 6 and we're about done upgrading from Xunit 1.9 to Xunit 2.4. We're facing a weird behavior that is blocking our builds which is in the test cases targeting `RaiseCanExecuteChanged` behavior. We have already read both issues reported in Xunit([#883](https://github.com/xunit/xunit/issues/883)) and Prism(#641) that are related to this but are targeting a newer version of Prism (that uses static `SynchronizationContext`) and we have already tried using that `SynchronizationContext `in combination with `WaitForCompletionAsync `with not luck.

### Steps to Reproduce

1. Checkout the Repo found [here](https://github.com/zein-makki/XunitPrismDelegateCommand)
2.  Run the tests (Preferably in parallel)

### Expected Behavior
Consistent test results.

### Actual Behavior
Flaky tests as shown in these 2 sample screenshots below
![flaky1](https://user-images.githubusercontent.com/25294002/48433720-8354c100-e780-11e8-81ee-16f35308f283.PNG)
![flaky2](https://user-images.githubusercontent.com/25294002/48433732-8d76bf80-e780-11e8-82b0-40dde90922c1.PNG)
### Basic Information
It is worth noting that if we remove the `SomeLongRunningCode` that is being called before the `RaiseCanExecuteChanged` in the method under test shown below, then we can't reproduce this issue and the tests pass consistently. 

`public void RaiseCanExecuteChanged()`
`{`
           `SomeLongRunningCode();`
           `delegateCommand1.RaiseCanExecuteChanged();`
`}`

Another crucial note is that while debugging this, we could clearly see that the weak reference for the execute method that is being subscribed in the test class is being released (`IsAlive` is false) before `RaiseCanExecuteChanged` is called (shown in the screenshot below).

![image](https://user-images.githubusercontent.com/25294002/48434633-ecd5cf00-e782-11e8-9ce9-a1d2c818b934.png)

- Version with issue: 4.0
- Last known good version: Unknown
- Xamarin.Forms version: None
- IDE: Microsoft Visual Studio Community 2017  Version 15.8.3

### Reproduction Link

[Repo](https://github.com/zein-makki/XunitPrismDelegateCommand)

We understand that Prism 4 might not be supported anymore, but this is blocking issue for us in the upgrade process and we're not also sure this behavior is fixed in newer versions. We would like to know if that is a known issue that was fixed in later minor releases that we can reference without having breaking changes in our code. Otherwise, we would like to know if there is any workaround for this.

(Note: We haven't posted that on StackOverflow because we're not yet sure this is not an actual issue in the latest release).

**Comment by brianlagunas** [comment]
You would be correct in that Prism 4 is not supported. No issues have been reported regarding the DelegateCommand and all of our tests for DelegateCommand have no issues with the latest version of Prism. I would suggest you try upgrading your repro project to the latest version and try your tests.

**Comment by brianlagunas** [comment]
At first glance, its the way you are writing your tests.  I bet if you wrote your tests like this:
```
        [Fact]
        public void DelegateCommand1Test()
        {
            bool delegateCommand1CanExecuteChangedFired = false;
            var sut = new ClassWithDelegateCommand();

            sut.delegateCommand1.CanExecuteChanged += (o, e) => { delegateCommand1CanExecuteChangedFired = true; };

            sut.RaiseCanExecuteChanged();

            Assert.True(delegateCommand1CanExecuteChangedFired);
        }
```
They would work.

**Comment by zein-makki** [comment]
@brianlagunas I can't see why moving the class members into local variables would affect this. Anyway, I have just updated and pushed code to the repo to use this approach and we're still seeing the same behavior.. The interesting point mentioned in the issue is that if we remove the call to the long running method which executed before calling the Command's `RaiseCanExecuteChanged` inside the SUT code, then tests pass consistently.
I can't get my head around why the handlers are being released, and we've been trying to figure that out since more than a week before posting this.

**Comment by brianlagunas** [comment]
You didn't upgrade Prism. It works for me.

![image](https://user-images.githubusercontent.com/835562/48440626-9cd91700-e746-11e8-877a-8d84f5432e3c.png)

**Comment by brianlagunas** [comment]
I ran your tests as you has them written. Prism 4 is not supported.

**Comment by zein-makki** [comment]
@brianlagunas Tests being ran in parallel or not has nothing to do with the way the tests are written. There is an option in the Visual Studio test runner that configures that option and I though it would be on by default. Anyway, I have added and pushed the `xunit.runner.json` configuration file that would force the Visual Studio test runner to run the tests in parallel. This should be the only thing that would make you see different results (since we're both referencing the same Prism and Xunit assemblies).

**Comment by brianlagunas** [comment]
It still works for me.

**Comment by zein-makki** [comment]
This makes sense now! I have been scratching my head trying to think why we're getting different results.

Since you've experience issues in the past testing `RaiseCanExecuteChanged`, do you have any idea why this might be happening ? Why the handlers are being set to `IsAlive` false while the SUT is still running? Maybe you can suggest some workaround, if any, on how to resolve it until we upgrade in the near future to Prism 6 or 7. 

This is a real blocker for us and any help to resolve it would be much appreciated.

**Comment by zein-makki** [comment]
I've just upgraded that sample project locally to Prism 6.0 and I can confirm that I am not seeing that issue anymore.
