### ISSUE TITLE
IContainerProvider needs to be registered in App.xaml.cs RegisterTypes

### ISSUE THREAD

**Issue by quicoli** [PrismLibrary/Prism#1623]
Hello

Before version 7.1 in my ShellViewModel I had a dependency to the existing container. This dependency was resolved automatically. 

Now, after moving to 7.1 I changed this dependency type to be IContainerProvider container. Prism tries to resolve this but it raises an exception saying there's no implementation for IContainerProvider. The solution was to include that in my App.xaml.cs RegisterTypes:

 containerRegistry.RegisterInstance<IContainerProvider>(Container);

I'd like to know if this is right or if I'm wrongly using it...

**Comment by brianlagunas** [comment]
It is highly discouraged to pass the container around your application. Therefore, Prism does not register the IContainerProvider with the container.  If you wish to break this DI rule then you must do exactly as you did.
