### ISSUE TITLE
Should throw circular dependency error

### ISSUE THREAD

**Issue by jmichas** [PrismLibrary/Prism#1629]
### Description
I accidentally added a circular dependency via constructor injection while refactoring my Xamarin Forms app. The result was iOS simulator would just crash "The app has been terminated." with no error. Even try catching the registration or first use of the service containing the faulty dependencies did not get caught. Took me a while to figure it out.

I would think it should be possible for Prism to throw a circular dependency error when it encounters one. It would have save a ton of time in tracking my mystery crashes.

Thanks.

### Steps to Reproduce

1. Create two services ServiceA and ServiceB.
2. In the constructor of each, add the other service as a dependency i.e. ServiceA(IServiceB serviceB) etc.
3. It should crash. (I didn't try this on my own, but its a simplified version of what I did by accident)

### Expected Behavior
Throw an error.

### Actual Behavior
App in iOS simulator crashes silently.

**Comment by brianlagunas** [comment]
Protecting you from yourself falls outside the scope of the responsibilities of Prism.  Prism does not control the how objects are resolved, that is handled by the container you chose to use.
