### ISSUE TITLE
How about Adding a behavior key propery right in to the RegionBehavior class as an override?

### ISSUE THREAD

**Issue by noufionline** [PrismLibrary/Prism#163]
Since every region behavior requires a behavior key how about adding a property right in to the Region Behavior class and provide a overload for adding the behavior without a key

**Comment by brianlagunas** [comment]
Not a bad idea, and it could be done without breaking anyone.  We will discuss this.  Thanks for the idea.

**Comment by brianlagunas** [comment]
Actually, to implement this properly would require a new property on the IRegionBehavior interface, which would be a breaking change.  Because of this, we will not be introducing this feature right now.
