### ISSUE TITLE
Problem Module Registration by XAML: ModuleCatalog not found in Prism.Modularity

### ISSUE THREAD

**Issue by Supai93** [PrismLibrary/Prism#1631]
### Description
Tried to register new module by XAML. The type ModuleCatalog in namespace Prism.Modularity cannot be found from .xaml file. But, the type ModuleCatalog can be found from code-behind (.cs file) using Prism.Modularity namespace.

### Steps to Reproduce

1. Create new ResourceDictionary
2. Add modularity namespace xmlns:Modularity="clr-namespace:Prism.Modularity;assembly=Prism"
3. Now the tag &lt;Modularity:ModuleCatalog&gt; does not exist in the namespace.

### Actual Behavior
From App class (PrismApplication) using Prism.Modularity, i can find the ModuleCatalog type. But not from ResourceDictionary.xaml

### Basic Information

- Version with issue: Prism.Core 7.1.0.431
- WPF
- IDE: VS 2015 14.0.25422.01

**Comment by brianlagunas** [comment]
Closing as you did not provide a repro link.  Also, this is most likely due to an error in your implementation. For example, you are using the wrong namespace. The module catalog is not in Prism, it's in Prism.WPF.
