### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by MaelVe** [PrismLibrary/Prism#1632]
Hello,

Is it possible to have a full documentation for Prism 7.0 ? Maybe it already exists but I can't find it, i've only found thi one : https://prismlibrary.github.io/docs/wpf/Implementing-MVVM.html but not for 7.0 :)

Cordially

**Comment by brianlagunas** [comment]
Anything is possible, especially if the community helps. We do accept PRs.  There really isn't much of a difference between v6 and v7, so the current topics still apply.
