### ISSUE TITLE
[UWP] Request for OS support of version 14393

### ISSUE THREAD

**Issue by rainman-63** [PrismLibrary/Prism#1633]
### Description

Request for support of Windows OS version 14393.  Currently Prism is supporting Win10 15063+

### Required Changes

1. Include uap10.0.14393 in the TargetFrameworks for Prism, Prism.Windows, and Prism.Unity.Windows. 
2. Change the following code in StartArgs.cs:

```C#
                    case IContactPanelActivatedEventArgs c: return StartCauses.ContactPanel;
                    
                    // https://blogs.windows.com/buildingapps/2017/07/28/restart-app-programmatically/#1sGJmiirzC2MtROE.97
#if !UAP10_0_15063 
                    case ICommandLineActivatedEventArgs c: return StartCauses.CommandLine;
#endif
```

To:

```C#
#if !UAP10_0_14393
                    case IContactPanelActivatedEventArgs c: return StartCauses.ContactPanel;
#endif
                    // https://blogs.windows.com/buildingapps/2017/07/28/restart-app-programmatically/#1sGJmiirzC2MtROE.97
#if !UAP10_0_15063 && !UAP10_0_14393
                    case ICommandLineActivatedEventArgs c: return StartCauses.CommandLine;
#endif
```

### Basic Information
Prism Version : 7.2.0.690-ci

**Comment by dansiegel** [comment]
We've made the deliberate decision to only target back to 15063. While I appreciate this may not work for some people, there is only so much that a small team can commit itself to support for free, particularly when there is little to no demand. Unless/until there is a change in which we see that the community truly needs specific support for versions prior to 15063 we won't be making this change at this time.
