### ISSUE TITLE
IContainerRegistry and factories

### ISSUE THREAD

**Issue by bdominguez** [PrismLibrary/Prism#1634]
### Description

Hi,

I'm used to Microsoft's "Microsoft.Extensions.DependencyInjection" implementation of IOC that has a really useful extension method that add a implementationFactory:

https://github.com/aspnet/DependencyInjection/blob/master/src/DI.Abstractions/ServiceCollectionServiceExtensions.cs#L542

Now with Prism abstraction it's not possible to do this.

I would like to register a dependency more than one time.

For example, having this:

```csharp
public interface ITestA { }

public interface ITestB { }

public class Test : ITestA, ITestB { }
```

With Microsoft's "Microsoft.Extensions.DependencyInjection" implementation I would do this:

```csharp
services.AddSingleton<Test>();
services.AddSingleton<ITestA>(provider => provider.GetRequiredService<Test>());
services.AddSingleton<ITestB>(provider => provider.GetRequiredService<Test>());
```

With current "IContainerRegistry" API it's not possible to do this. I know I can:

```csharp
Test test = new Test();

containerRegistry.RegisterSingleton<Test>(test);
containerRegistry.RegisterSingleton<ITestA>(test);
containerRegistry.RegisterSingleton<ITestB>(test);
```

The real problem is that when "Test" class has a constructor with multiple dependencies and this dependencies can only be resolved with IOC.

**Comment by dansiegel** [comment]
the container abstractions is purposely kept simple. You can call `GetContainer()` to get the specific container you are using to perform more complex registrations such as when you need some sort of factory.
