### ISSUE TITLE
NavigationService: Relative navigation throws InvalidOperationException: Queue Empty

### ISSUE THREAD

**Issue by arghlolrofl** [PrismLibrary/Prism#1636]
### Description

In a MasterDetail-View (e.g. "/menu/nav/items") we are no longer able to do relative navigation since upgrading to XF 3.4. When calling **await Navigator.NavigateAsync("detail?id=[itemId]");** (realtive navigation by default) the NavigationService (PageNavigationService) throws an exception:

Exception: System.InvalidOperationException: Queue empty

### Steps to Reproduce

1. Create App with MasterDetail Page
2. Start app and do absolute navigation to any detail page
3. Do a relative navigation to another detail page

### Expected Behavior
App is navigating to the other detail page and the user can navigate back to the previous page.

### Actual Behavior
PageNavigationService returns an Exception: System.InvalidOperationException: Queue empty

### Basic Information

- Version with issue: 7.1.0
- Last known good version: 7.1.0
- Xamarin.Forms version: 3.4
- IDE: VS 2017 Enterprise

### Sidenotes

The exception is being thrown inside the following method:
    `PageNavigationService#ProcessNavigationForMasterDetailPage`
The parameters were:
    `nextSegment` = "detail"
    `seqments` = *empty* Queue instance
    
Then in this line
    `var nextPageType = PageNavigationRegistry.GetPageType(UriParsingHelper.GetSegmentName(segments.Peek()));`
    
the code peeks into the queue, but it is empty and the exception is being thrown.

### Screenshots

None

**Comment by brianlagunas** [comment]
This has been fixed in the latest CI build on MyGet. Also, you didn't provide a reproduction link.
