### ISSUE TITLE
[XF3+Prism7] GoBackAsync() and NavigateAsync("../") aren't working as expected

### ISSUE THREAD

**Issue by iskabin** [PrismLibrary/Prism#1637]
### Description

Can't go back to previous page in the Navigation Stack, neither using GoBackAsync() nor NavigateAsync("../").

### Steps to Reproduce

1. Added Register Types in App.xaml.cs
`containerRegistry.RegisterForNavigation<HomeTutor, HomeTutorViewModel>();
 containerRegistry.RegisterForNavigation<Store, StoreViewModel>();`
2. After InitializeComponent(); in OnInitialized() in App.xaml.cs:
`await NavigationService.NavigateAsync("NavigationPage/HomeTutor");`
(This part works fine, app starts at HomeTutor as expected)
3. Add button to Navigate to Store in HomeTutor:
`<Button {...} Command="{Binding OnStoreTappedCommand}"/>`
HomeTutorViewModel:
```
public class HomeTutorViewModel
    {
        INavigationService _navigationService;

        public DelegateCommand OnStoreTappedCommand { get; set; }

        public HomeTutorViewModel(INavigationService navigationService)
        {
            _navigationService = navigationService;

            OnStoreTappedCommand = new DelegateCommand(OnStoreTapped);
        }

        async void OnStoreTapped()
        {
            await _navigationService.NavigateAsync("Store", useModalNavigation: false);
        }
    }
```
(This also works fine)

4. Add Back Button to Store.xaml:
`<Button Command="{Binding OnBackTappedCommand}" {...}/>`

StoreViewModel:

```
namespace Aule.ViewModels
{
    class StoreViewModel
    {
        INavigationService _navigationService;

        IPageDialogService _pageDialogService;

        public DelegateCommand OnBackTappedCommand { get; set; }

        public StoreViewModel(INavigationService navigationService, IPageDialogService pageDialogService)
        {
            _navigationService = navigationService;

            _pageDialogService = pageDialogService;

            OnBackTappedCommand = new DelegateCommand(OnBackTapped);
        }

        async void OnBackTapped()
        {
            await _pageDialogService.DisplayAlertAsync("Back Tapped", _navigationService.GetNavigationUriPath() ,"Ok");
            await _navigationService.NavigateAsync("../");
        }
    }
}
```

I added the Alert so I could see de UriPath, and I get:

`/NavigationPage/HomeTutor/Store`

as expected. The OnBackTappedCommand gets fired and the alert is displayed, but the page isn't popped from the stack.

### Expected Behavior

Go back to previous page in the Navigation Stack (HomeTutor is a MasterDetailPage, I don't know if that matters...).

### Actual Behavior

Nothing happens.

### Basic Information

- Version with issue: Prism.Unity.Forms 7.1.0.431
- Last known good version: First time I'm using Prism
- Xamarin.Forms version: 3.3.0.912540
- IDE: Visual Studio Community 2017 15.8.8

**Comment by brianlagunas** [comment]
Yes, the MasterDetailPage is the issue. Never put a MDP in a NavigationPage. That's a bug "no-no". Also, you didn't provide the required repro app.

**Comment by iskabin** [comment]
Thanks for the quick reply!

I took out the NavigationPage, but the problem persists.

Here is the repro: https://github.com/iskabin/PrismRepro
