### ISSUE TITLE
IModuleCatalog could not be resolved in UWP

### ISSUE THREAD

**Issue by MikelThief** [PrismLibrary/Prism#1638]
### Description
I cannot initalize a module because I receive an error: IModuleManager could not be resolved. This is strange as prior to resolving phase it is registered in `PrismApplication.RegisterRequiredTypes()`.

Originally, the error rises in `PrismApplication.InitializeModules()` in line 195. If you try to resolve it before this method kicks in (but after instance was registered) same thing happens.

### Steps to Reproduce

1.  Create a new simple module
2.  Add it by overriding `ConfigureModuleCatalog()`
3. Turn on debugging (you may need to turn mixed mode debugging to see the issue in ouput window)

### Expected Behavior

Initialization of modules is possible.

### Actual Behavior
An error is rised:
`Exception thrown at 0x00007FFC31EA5299 (KernelBase.dll) in ElkaUWP.Core.exe: WinRT originate error - 0x80131500 : 'Unity.Exceptions.ResolutionFailedException: Resolution of the dependency failed, type = 'Prism.Modularity.IModuleManager', name = '(none)'.
Exception occurred while: while resolving.
Exception is: InvalidOperationException - The current type, Prism.Ioc.IContainerExtension, is an interface and cannot be constructed. Are you missing a type mapping?`

### Basic Information

- Version with issue: 7.2.0.690-ci (Prism.Windows.Unity)
- Last known good version: Unknown
- IDE: VS2017 Enterprise

### Reproduction Link

[Example.7z](https://www81.zippyshare.com/v/9pIfrFj3/file.html)

**Comment by MikelThief** [comment]
I made a further investigation on this issue.
It seems that `IModuleManager` could not be resolved because `IModuleCatalog` could not be solved in the first place.

Workaround:
By overriding `RegisterRequiredTypes()` i managed to find out that if one replaces `RegisterSingleton<>()` by `Register<>()` for `IModuleCatalog`, the module will get loaded.

Because I need wo work with IModuleCatalog only once (and I am not going to use its powerful features from WPF, just for cosmeting project structure splitting) this is okay, as it won't cause memory leak...

I am still trying to understand where the bug lies, but for now I think am missing something essential while browsing code.

**Comment by totht91** [comment]
Yes UWP cannot load dinamically DLLs so the ModuleManager functionality can be only for project structure purposes.

**Comment by MikelThief** [comment]
@totht91 could you elaborate on that?

**Comment by brianlagunas** [comment]
The problem is that the IContainerExtension is not being registered with the container. So the IModuleManager can't be created. Just add `containerRegistry.RegisterInstance(Container)` and it should work. Let me know if that works.

**Comment by MikelThief** [comment]
@brianlagunas Unfortunately, registering the container in the registry at the beginning of `RegisterRequiredTypes()` didn't fix the issue.

**Comment by brianlagunas** [comment]
Yeah.... sorry, you need to provide the interface `containerRegistry.RegisterInstance<IContainerExtension>(Container)`

**Comment by MikelThief** [comment]
@brianlagunas this does not work as 

> IContainerExtension is not assignable to IContainerExtension

which is kinda interesting since `Container` property points to `_containerExtension` field and `IContainerExtension` implements `IContainerExtension`

**Comment by brianlagunas** [comment]
it will work when I do it :)

**Comment by brianlagunas** [comment]
fixed
