### ISSUE TITLE
OnNavigatedFrom() is only trigerred following an explicit call to NavigateAsync("Page X")

### ISSUE THREAD

**Issue by HelenMamalaki** [PrismLibrary/Prism#1641]
### Steps to Reproduce

1.  Navigate from Page A -> Page B using this.navigationService.NavigateAsync("Page B") 
2. Page A OnNavigatedFrom() is triggered and so is Page B OnNavigatedTo() 
3. On Page B, Press the hardware or soft nav bar back button or suspend the app, OnNavigatedFrom() is not triggered. 

### Expected Behavior
OnNavigatedFrom should be triggered no matter how you leave the page.
### Actual Behavior
It's only triggered following a navigation event using Prism navigation service

### Basic Information

- Version with issue: Prism.Forms 7.1.0.431
- Last known good version:
- Xamarin.Forms version: 3.4.0.1008975
- IDE: Visual Studio 2017

**Comment by brianlagunas** [comment]
You did not provide a the required reproduction app.

**Comment by HelenMamalaki** [comment]
Hi Brian, I'm not comfortable sharing my app code publicly, would I be able to send it to you privately somehow? I could share it through the form on your website if that's ok? http://brianlagunas.com/contact/

**Comment by brianlagunas** [comment]
Create a simple app the reproduces the issue and provide the link here. I am not accepting samples that are emailed to me personally. I get 1,000s of emails in a day.  It will get lost and/or ignored. I am also not the only person that supports Prism. It's better to add it directly to the issue.

**Comment by HelenMamalaki** [comment]
As requested, I have updated the issue with a link to a simple app that replicates the issues, I have updated the reproduction steps too.  Appreciate your comments above so I hope that helps. Thanks so much for your time and effort.

**Comment by HelenMamalaki** [comment]
@brianlagunas I don't see a way of re-opening this issue now that I have provided a sample app. (See comment above). Just worried it will be over-looked otherwise.

**Comment by brianlagunas** [comment]
This is because you are manually setting up the master detail page, and not relying on Prism to build it up for you using deep links.  Therefore you need to manually apply the NavigationPageSystemGoBackBehavior to your MDP's navigation page.  Also, INavigationAware methods do not fire when suspending. That is not a navigation operation. You need to utilize the IApplicationLifecycle interface instead.
