### ISSUE TITLE
VS link broken

### ISSUE THREAD

**Issue by DickBaker** [PrismLibrary/Prism#1645]
my Dell Inspiron laptop runs
W10Home (v1803 10.0.17134.407)
VS2017 Community Ed. 15.9.3, .NET FW 4.7.03056
Prism Template Pack v2.1.4 (17/11/2018)

In the "Extensions and Updates" window, clicking the "More information" hyperlink gives a 404 to
https://github.com/PrismLibrary/Prism-Extensibility

**Comment by brianlagunas** [comment]
fixed. It will be available in the next release.
