### ISSUE TITLE
Updating samples and documentation for Prism 7

### ISSUE THREAD

**Issue by BigBallard** [PrismLibrary/Prism#1648]
It has been near impossible to find any information for starting up Prism 7 applications, at least in a complete sense from start to functional finish. The current official Prism [documentation](http://prismlibrary.github.io/docs/) is becoming outdated and doesn't discuss the new architecture and concepts at all. The amount of information is great but the lack of extended examples is not.

Is there any intention on documentation being updated in the near future considering Prism 7 is not that new?

**Comment by brianlagunas** [comment]
Yes the docs are out dated, so feel free to jump in and help us out.  I can't wait to see a PR.

I didn't realize 35 WPF samples was considered being a "lack"

https://github.com/PrismLibrary/Prism-Samples-Wpf

**Comment by brianlagunas** [comment]
Also, you should consider beomcing a patron and help support the project. This will actually help us hire people to write docs.

Looking forward to your support: https://www.patreon.com/prismlibrary

**Comment by brianlagunas** [comment]
There are plenty of samples that show how to register modules in various ways.  Registering services is also covered in great detail in the docs: http://prismlibrary.github.io/docs/wpf/Managing-Dependencies.html. Keep in mind, registering and resolving services is an IoC concept that Prism uses, but didn't invent. So the docs link to resources to help you become more familiar with how to utilize IoC with varius DI containers.

You could also look at the other platform samples that do show how to register and use services: For example XF: https://github.com/PrismLibrary/Prism-Samples-Forms

Like I said, if you feel the sample are lacking, feel free to submit your PR.

**Comment by DallasP9124** [comment]
Understood @brianlagunas , I know the small team dev life, always stuff on the backlog 👍
