### ISSUE TITLE
How to unit test after modifying project to use PrismApplication or PrismUnityApplication?

### ISSUE THREAD

**Issue by MarkDHarris** [PrismLibrary/Prism#165]
As soon as I modify my project to inherit from PrismUnityApplication, the associated unit test project (which was just added but working ok before I added Prism) immediately starts failing with:

- "Cannot deserialize XBF metadata type list as 'PrismUnityApplication' was not found in namespace 'Prism.Unity.Windows'. [Line: 0 Position: 0]".

I've repro'd this several times:
1) New Universal project.  
2) New Universal Unit test project with 1 sample test.  
3) Test runs fine.  
4) Modify the app class to inherit from PrismUnityApplication.  
5) Test requires references to Unity then fails with the above exception.  

Seems like I need to modify the unit test project in some way but its not clear to me what the issue is.  

What extra step am I missing?

**Comment by briannoyes** [comment]
See issue #140 - this is a limitation currently of the UWP platform, not specific to Prism. You'll need to put your testable assets (ViewModels, services) in a UWP class library to be able to unit test them.
