### ISSUE TITLE
Prism.Wpf.csproj fails to load in Visual Studio

### ISSUE THREAD

**Issue by Jinjinov** [PrismLibrary/Prism#1652]
### Description

Prism.Wpf.csproj, Prism.Unity.Wpf.csproj, Prism.Ninject.Wpf.csproj, Prism.StructureMap.Wpf.csproj, Prism.DryIoc.Wpf.csproj fail to load in Visual Studio 2017 15.9.4 and in Visual Studio 2019 preview 1.0 in Windows 7 and in Windows 10

Visual Studio error:

Expected "$(IS_PREVIEW)" to evaluate to a boolean instead of "", in condition " '$(PRISM_RELEASE)' == '' And '$(PRISM_WPF_VERSION)' == '' And '$(IS_PREVIEW)' ".

### Steps to Reproduce

1. install Visual Studio 2017 or 2019 (in installer choose ".NET desktop development")
2. pull Prism from GitHub
3. open PrismLibrary.sln or PrismLibrary_Wpf.sln

### Expected Behavior

PrismLibrary.sln loads all projects successfully.

### Actual Behavior

PrismLibrary.sln fails to load some projects.

**Comment by brianlagunas** [comment]
If you are trying to build from source, you'll need to install the latest .NET Core 3 SDK and runtime. The repo builds successfully as proven by our automated builds.

**Comment by Jinjinov** [comment]
Ok, even though I am not trying to build from source - I am just trying to open the solution - I did go and install the latest .NET Core 3 SDK and runtime. The situaltion did not change. Visual Studio fails to open the project:

![vs](https://user-images.githubusercontent.com/20396198/50032959-e55e4b80-fff6-11e8-8066-3f8ad4bc7388.png)

**Comment by Jinjinov** [comment]
line 21 in Prism.Wpf.csproj

<VersionSuffix Condition=" '$(PRISM_RELEASE)' == '' And '$(PRISM_WPF_VERSION)' == '' And '$(IS_PREVIEW)' ">pre</VersionSuffix>

is causing the error:

Expected "$(IS_PREVIEW)" to evaluate to a boolean instead of "", in condition " '$(PRISM_RELEASE)' == '' And '$(PRISM_WPF_VERSION)' == '' And '$(IS_PREVIEW)' ".

I just opened a freshly created WPF *.csproj file and it looks vastly different from Prism.Wpf.csproj

**Comment by dansiegel** [comment]
the only way that could happen is if you've somehow tried loading in a way that dismisses the Directory.build.props in the Source directory right next to all of the solution files... like if you clicked on Prism.Wpf directly (which would cause VS to generate a new solution file in the project folder)

**Comment by dansiegel** [comment]
If you’re trying to do something custom like that you can just add your own Directory.build.props that defines `IS_PREVIEW` and `IS_RELEASE` properties..

**Comment by brianlagunas** [comment]
You also have to have .NET Core 3 installed and ENABLED

https://youtu.be/gIlfHtqgKk8

You also ned more thn just the .NEt desktop development. You need .net core and mobile development installed.

I just tested this in a new virtual machine and had no issues.

**Comment by horseyhorsey** [comment]
> This is the first time in my 18 year programming career that I decided I would contribute to an open source project to give something back to the community and now I am stuck at the very beginning...

:1st_place_medal: 

I had the same issue and ended up here. You can use the extension templates and create, which just disappears immediatley after.  I hadn't updated 3.0 for a while but soon as update it's fine.

Cheers
