### ISSUE TITLE
NavigatedTo is triggered after the View is rendered

### ISSUE THREAD

**Issue by SdeWitAH** [PrismLibrary/Prism#1655]
Hello,

I have a issue.
I have implemented my controls in code behind(C#) and i try to pass a parameter from page to page. The method OnNavigatedTo is triggerd after the IntializeComponent function, so my controls are  rendered without my data. Is is possible to trigger the OnNavigatedTo function before the IntializeComponent function of the View?

Thanks for reading,

Stefan

**Comment by fileman** [comment]
Use OnNavigatingTo http://prismlibrary.github.io/docs/xamarin-forms/navigation/passing-parameters.html#sidetoggle
