### ISSUE TITLE
Prism Template Studio and Developer Toolkit- Quickstart Prism Application

### ISSUE THREAD

**Issue by HobDev** [PrismLibrary/Prism#1657]
### Description

The new project for prism QuickStart application doesnot allow to select Container, Min. Android SDK Version and Data Provider
### Steps to Reproduce

1. New Project
2. Select QuickStartPrism Application
3. Try to change the Container, Min. Android SDK Version and Data Provider

### Expected Behavior
The developer can choose the container, Min. Android SDK Version and Data Provider of his choice

### Actual Behavior
The Dialog does not allow to change the aforementioned options

### Basic Information

- Version with issue: 2.2.0.434
- Last known good version: Don't know
- Xamarin.Forms version: Does not apply
- IDE:Visual studio for Mac 7.7.2(build 21)

### Screenshots

![image](https://user-images.githubusercontent.com/9531864/50563575-fa9bdf80-0d43-11e9-9b67-c696101cdb3c.png)

### Reproduction Link
Try to create new project with the Quickstart prism application and try to change the Container , Min. Android SDK Version and Data Provider

**Comment by HobDev** [comment]
Please see this screenshot too.
![image](https://user-images.githubusercontent.com/9531864/50570471-ef33cd00-0db2-11e9-992a-97e2f24e7c08.png)

**Comment by dansiegel** [comment]
I'm unable to reproduce the problem you said you were having... all of the drop down boxes work just fine. as for the second screenshot you'll need to configure your environment with your access tokens as it says.
