### ISSUE TITLE
ModuleCatalog in Xamarin.Forms

### ISSUE THREAD

**Issue by cytoph** [PrismLibrary/Prism#1659]
I've read that with version 7 (or 7.1) the modularization part has been reworked. For example there is no CreateModuleCatalog method to override in the App class anymore. In the Prism-Samples-Forms repository I found the sample project UsingModules which brought a little more light in the dark, but one question is still exists: How can I use other types of ModuleCatalogs (e.g. ConfigurationModuleCatalog)? I saw this working with Prism.Wpf, but this requires .NET Framework and newly created Xamarin projects will use .NET Standard instead.

So is there anyway to get this to work or is it just not possible in Xamarin.Forms at this time?

**Comment by brianlagunas** [comment]
This is not possible in Xamarin.Forms. Only hard-coded module references work in XF. You cannot load modules dynamically in a XF application.
