### ISSUE TITLE
Modules in separate solutions

### ISSUE THREAD

**Issue by cytoph** [PrismLibrary/Prism#1661]
In issue #1659 it has been explained to me, that it's not possible to load modules dynamically (e.g. from directory) in Xamarin.Forms. Know I thought about another approach but do not know if this is possible in any way and if yes how a sample approach could look.
My idea (which would eliminate the need to load modules dynamically) is to have a solution for core functionality, loading the modules and building/running the app (contains logic, Xamarin.Forms PCL, android and iOS project) and than have various solutions (in different repositories) that would have references to this core project, add themselves to it and run the core app, so it is run with the module.

Can something like this be done in anyway or maybe even have this been done already? Or rather no luck?

**Comment by brianlagunas** [comment]
Questions like this should be asked on the Prism Slack channel or on StackOverflow.
