### ISSUE TITLE
Should we bring INavigationService and other interfaces to WPF?

### ISSUE THREAD

**Issue by brianlagunas** [PrismLibrary/Prism#1664]
Currently, all of the [common navigation interfaces](https://github.com/PrismLibrary/Prism/tree/master/Source/Prism/Navigation) are hidden from .NET45 (WPF) applications.  This is because WPF has a completely different way of navigating via Regions and has many duplicate interface names, but with different signatures.

For example, here is INavigationAware for WPF
```
public interface INavigationAware
{
    void OnNavigatedTo(NavigationContext navigationContext);
    bool IsNavigationTarget(NavigationContext navigationContext);
    void OnNavigatedFrom(NavigationContext navigationContext);
}
```

And here it is for Xamarin.Forms and UWP (simplified)
```
    void OnNavigatedFrom(INavigationParameters parameters);
    void OnNavigatedTo(INavigationParameters parameters);
    void OnNavigatingTo(INavigationParameters parameters);
```
As you can see, the interface names are the same except the signatures are completely different.

We can support both.  However, I am concerned this would cause a ton of confusion.  Prism for WPF is already the most complicated form of Prism, and if we were to add support for these common interfaces on top of the existing Region navigation interfaces, it would lead to tons of confusion.

It would however make sharing ViewModels much easier when developing cross platform apps that target WPF, UWP, and XF.

Right now, these interfaces are hidden from any app using WPF. This means if you are trying to build an XF application and want to target WPF, you can't because they are hidden form this target.  Today we just don't support WPF with XF, and sharing any VM from UWP with WPF would be difficult (but possible)

Thoughts?

**Comment by AKruimink** [comment]
For the last week i have been trying to figure out how to have my view models shared between XF and WPF clearly without any result, as soon as a view model contains any kind of navigation its off the table and get duplicate inside its own project with it's own navigation (still trying to find a way, so if anyone knows how to please let me know, i am getting deperate, maybe an event aggregator that gets handled inside the wpf and xamarin project and deal with the navigation?)

With that being said, and to adress the question, i think it is of somewhat important that slowly but surely WPF will be worked into the Prism.Core project as well, WPF is not dead, and with WPF comming in .net core 3.0 there are more reasons then ever to have shared view models cross platforms. 

With UWP being limited to windows 10 systems, Windows Forms mainly being around from older projects, and not every company jumping on the web based ui we still see a lot of WPF around (and new projects written with them) and allot of these projects get mobile ports, which would benefit hugely from being able to share these viewModels.

I do understand that this will bring certain issues with it and make stuff more complicated, but i do think that in return it will offer even more flexibility, and far outweight any of the negative downsides.

Also nothing a decent example project would not fix?

But hey, that's my take on it.

**Comment by AwsomeCode** [comment]
+1

**Comment by brianlagunas** [comment]
@DamianSuess Actually XF is not the primary reason for thinking about this effort. I would never recommend using XF to write a WPF app. EVER!  However, you can still target XF and have a WPF app by sharing your core VM logic.  The purpose of this question is how much should be sharable.

The problem is, there may not be much value to WPF developers if these interfaces were brought over.  They are so vastly different and very limiting as they are missing APIs that WPF would require, I'm not sure it makes sense to try and bring them over as it will just cause a ton of confusion.

**Comment by dansiegel** [comment]
Ultimately for those brave enough to "Share" their ViewModel logic between a Xamarin.Forms and a real WPF application I think they'll need to follow one of two approaches:

1. Cross Compile net45/netstandard2.0 where you make use of conditional compilation to change the logic around what your Navigation dependencies are and how your implement some of that Navigation logic.
2. Implement a bunch of abstract base view models that then have an implementing ViewModel in your WPF or Forms projects. 

that said I'm in favor of removing the conditional compile, it may not work for real WPF applications, but it would make it available if someone needs to use full framework Unit tests instead of .NET Core, as well as the previously stated Forms WPF target (which is a terrible idea) and GTK#.

**Comment by brianlagunas** [comment]
You will **always** need a base VM with a platform specific implementation.

**Comment by DamianSuess** [comment]
@brianlagunas , thank you for taking your time to provide a detailed and useful explanation.  Since we're doing a lightweight front-end, I was hoping we'd get away with using XF.WPF w/ minimal effort. Honestly, I'd rather use your project - prism - over our previous custom efforts with TinyIoC.

**Comment by Martinn2** [comment]
WPF support for XF would be great for me as well.

**Comment by MikelThief** [comment]
I think the only way is not to bring the new interfaces to WPF or replace existing ones. Besides new names and slightly easier learning curve (for instance - ppl coming from other versions of Prism) it will also make tutorial videos more legacy (like "Introduction to Prism 5" which is still pretty actual). I am agaist this change personally (and I use both UWP and WPF versions).

**Comment by brianlagunas** [comment]
I think for now, I will not implement this.
