### ISSUE TITLE
Using ViewModels in ObservableCollections

### ISSUE THREAD

**Issue by cytoph** [PrismLibrary/Prism#1667]
As far as I know, the default way to use ObservableCollections that are bound to a listview is with model classes. So when a listview element is selected, we use NavigateAsync and pass the model, which then can be used by the ViewModel to "fill itself".
The problem with this approach is, that it's not possible to use ViewModel properties for binding in the listview.

For example:
I have a View, ViewModel and Model "PickList", which contains a collection of "PickLine" objects - each having a View, ViewModel and Model themselves. The PickLine object contains a property "PickedQuantity" and a property "OpenQuantity". Now in my PickList view, I don't want to bind these two to separate items (e.g. two labels), but I want to have one label to display both I a format like for example "PickedQuantity / OpenQuantity". I know this example can be solved by using multi binding or something like this. But that's not the meaning of it all.
My PickLine ViewModel already has a property "QuantityString", that I want to bind to the label of a listview element via DataTemplate. But how can I do this. Is it even possible?

**Comment by brianlagunas** [comment]
Please ask questions like this on StackOverflow or the Prism Slack channel.

**Comment by cytoph** [comment]
Oh sorry.

The question I now asked at StackOverflow can be found [here](https://stackoverflow.com/questions/54262530/using-viewmodels-in-observablecollections-in-prism).
