### ISSUE TITLE
ObservesProperty does not work when arguments indicate ALL properties changed.

### ISSUE THREAD

**Issue by jmoleary** [PrismLibrary/Prism#1670]
### Steps to Reproduce

1.  Create a DelegateCommand that that depends upon and observes a boolean property ("Foo")
2.  In the setter of Property "Foo", when it changes, only raise the PropertyChanged event with an argument of null or string.empty, indicating that all properties changed.  (i.e.   for BindableBase,              `RaisePropertyChanged(null);` OR `RaisePropertyChanged("");`
  Do not supply the name of the property "Foo" itself.   

### Expected Behavior

I would expect the DelegateCommand to raise CanExecuteChanged when null or string.empty is supplied.  I realize the user can just call RaisePropertyChanged with the name of the given property, but to me that seems immaterial.  Whatever property it is observing is a part of "All" properties.  

### Actual Behavior

The DelegateCommand does not raise CanExecuteChanged unless you supply the exact property name.

### Basic Information

- Version with issue:  Prism.Unity 7.1.0.431
- Last known good version:  I suspect it has always been this way
- Xamarin.Forms version:  Not using Xamarin forms.  Using WPF and .NET Framework on Windows 10
- IDE: Visual Studio 2017 15.9.5

### Reproduction Link
[PrismTestApp.zip](https://github.com/PrismLibrary/Prism/files/2784461/PrismTestApp.zip)

This simple prism app shows a button and a checkbox.  The button's Delegate command observes a boolean property controlled by the checkbox.  When you check the box, the property setter uses "null" as the name of the property that changed.  The button does not become enabled.  But if you make the setter actually use the name of the property, the button does become enabled.

**Comment by brianlagunas** [comment]
This is not the intention of this feature. You register a specific property for monitoring. We do not automatically hook into the INPC event of the VM and monitor all properties for changes or a empty string.

**Comment by jmoleary** [comment]
I am not sure I understand the objection.  

You don't have to hook into  anything you don't hook into already.  Under the hood, DelegateCommand uses PropertyObserver, does it not?  .  Well PropertyObserver already hooks into the INPC event.  All I am saying is that it should be a tiny bit smarter about what it is monitoring and do a check for null or "" and consider that as also being the property changed.  

Since (according to the docs) null or "" actually **_means_** that the specific property you are observing has changed.  If you do not react to it (in addition to the property name itself) then you are not truly observing the property.

I use my own version of PropertyObserver in my own projects and the change to make this work was trivial.  If the string is null or empty, instead of invoking one handler, it invokes  the handlers for everything it monitors.

**Comment by brianlagunas** [comment]
Sorry, it appears I completely missed the point you were trying to make in your original issue.  I re-read it, and now I understand what you were trying to say.

Actually, this does already work when passing `null`. Your sample works for me.  We do not handle String.Empty though.

https://github.com/PrismLibrary/Prism/blob/master/Source/Prism/Commands/PropertyObserverNode.cs#L64

**Comment by totht91** [comment]
This property is a string, you should write the condition with `IsNullOrEmpty`

**Comment by brianlagunas** [comment]
Just waiting on the PR :)
