### ISSUE TITLE
Is there a way to reference VM in xaml while using AutoWireViewModel = "True"

### ISSUE THREAD

**Issue by GreatFireWall** [PrismLibrary/Prism#1673]
As you see, I'm trying a new way to show custom dialog with MahApp.Metro in MVVM.

I can't reference `MahApps.Metro.Controls.Dialogs` in VM directly for using
`dialogCoordinator.ShowMetroDialogAsync(..., BaseMetroDialog dialog, ...)`,
because `BaseMetroDialog` is an UI element.

So I'm trying define my custom dialog in xaml, then calling `ShowMetroDialogAsync` via `ObjectDataProvider`. But I don't know how to get reference of DataContext(the VM) for passing to `ObjectDataProvider.MethodParameters` as the first param.

![image](https://user-images.githubusercontent.com/4510984/52005186-0f66c100-2504-11e9-8245-7d8e3721245f.png)

button for trigger `ObjectDataProvider`:

![image](https://user-images.githubusercontent.com/4510984/52005668-370a5900-2505-11e9-8f80-e9d9f5878b92.png)

**Comment by brianlagunas** [comment]
Please ask questions on the Prism Slack channel or StackOverflow
