### ISSUE TITLE
Could not load file or assembly - Prism.Unity v7.1.0.431 and UnityContainer v5.9.3

### ISSUE THREAD

**Issue by rgiosa** [PrismLibrary/Prism#1674]
### Description

Could not load file or assembly 'Unity.Abstractions, Version=3.3.1.0, Culture=neutral, PublicKeyToken=6d32ff45e0ccc69f'

### Steps to Reproduce
1. Create a new WPF application
2. Install Prism.Unity v7.1.0.431 and UnityContainer v5.9.3 (01/30/2019) _(are they compatible?)_
3. Configure simple modules ([sample link](https://github.com/PrismLibrary/Prism-Samples-Wpf/tree/master/07-Modules%20-%20LoadManual))
4. Run

### Basic Information

- Version with issue: Prism.Unity v7.1.0.431 and UnityContainer v5.9.3
- Last known good version: Prism.Unity v7.1.0.431 and UnityContainer **v5.8.13**

**Comment by brianlagunas** [comment]
Do not upgrade the container dependencies separate from Prism.  Only use the version of the container that Prism depends on.
