### ISSUE TITLE
Prism.Unity.Wpf and Unity.Abstractions

### ISSUE THREAD

**Issue by margussikk** [PrismLibrary/Prism#1675]
It seems to me that Prism.Unity.Wpf references dependencies Unity.Abstractions v3.3.1.0 and Unity.Container v5.8.12.0. Unity.Container itself references dependency Unity.Abstractions v4.0.2.0. That causes a conflict because you can't have two versions of the same file. I think Prism.Unity.Wpf's Unity.Abstractions dependency needs to be updated.

How to reproduce:
I tried to create Prism WPF application using tutorial from http://donovanbrown.com/post/Getting-started-with-Prism-70 page. Basically just make a blank prism application using Unity IOC and Unity.Abstractions v3.3.1.0. Once everything works, upgrade all the nugets and especially Unity.Abstractions to 4.0.2 and you'll get an error complaining that the application cannot load Unity.Abstractions v3.3.1.0 file. ILSpy showed that Prism.Unity.Wpf references that file.

**Comment by brianlagunas** [comment]
In WPF, you can' just update dependencies of an assembly.  You must use the version of the container that Prism is referencing or you will break binary compatibility. Do not upgrade the container separately from the Prism nugets.  ONLY upgrade Prism.Unity, and the other dependent NuGets will automatically update to the version of the container that has binary compatibility.

We are not ready to push any updates to WPF as we still have work in progress.  We will release updated Nugets when that work has been completed.
