### ISSUE TITLE
Ambiguous match found when ObserveProperty

### ISSUE THREAD

**Issue by omerfarukz** [PrismLibrary/Prism#1676]
ObserveProperty api is not working when we try to observe inner complex property is shadowed. 

### Steps to Reproduce
1. Create a class with a complex property
2. Create an another class and inherit from first. Declare a property as first and shadow.
3. Declare a DelegateCommand and observe complex property's property.
4. And get "Ambiguous match found." exception

Example codes and test are below.

    public class BaseVm : BindableBase
    {
        private Demo _parent;
        public Demo Parent
        {
            get { return _parent; }
            set { SetProperty(ref _parent, value); }
        }
    }

    public class BaseVm<T> : BaseVm
    {
        private GenericDemo<T> _parent;
        public new GenericDemo<T> Parent
        {
            get { return _parent; }
            set { SetProperty(ref _parent, value); }
        }
    }

    public class Demo : BindableBase
    {
        private int _value;
        public int Value { get => _value; set => SetProperty(ref _value, value); }
    }

    public class GenericDemo<T> : Demo
    {
        private T _value;
        public new T Value { get => _value; set => SetProperty(ref _value, value); }
    }

And test is

    bool canExecuteChangedRaise = false;

    Buggy = new BaseVm<int>(); // Buggy is declared in a class which is inherited from BindableBase
    Buggy.Parent = new GenericDemo<int>();

    var command = new DelegateCommand<BaseVm<int>>((o) => { })
        .ObservesProperty(() => Buggy.Parent.Value);

    command.CanExecuteChanged += delegate
    {
        canExecuteChangedRaise = true;
    };

    Buggy.Parent.Value = 1;

    Assert.True(canExecuteChangedRaise);

### Basic Information
Exception is thrown from PropertyObserverNode's GenerateNextNode method. In declaration of method attemps to get property info with "_inpcObject.GetType().GetRuntimeProperty(PropertyName);".

- Version with issue: 7.1.0.431

**Comment by brianlagunas** [comment]
I'm not sure we want to introduce support for this. I am not sure what the performance impact would be to check every property to see if it is a shadow property or not.

**Comment by brianlagunas** [comment]
Another aspect of this is that you can change the return type of a shadowed proeprty, so this would be another complexity to consider.

**Comment by omerfarukz** [comment]
We have a member info(given from property expression) on property observer. So, why we not use the property info(over expresssion.Member[type=PropertyInfo]) instead of property name. Is that cause a performance problem? Using property name instead of property info enforces us to make reflection twice. (GetRuntimeProperty(name)) but we have a property info already in property observer.

I made a small changes on property observer and property observer node classes to use property info. So, there is no need to have property info on the PropertyObserverNode and as a result there is no need to GetRuntimeProperty(again) call for resolution to get property and check for is it shadow or not.

What do you think about that?

**Comment by brianlagunas** [comment]
I am having a hard time understanding the proposed changes. Please provide your code snippets, or submit a PR, so I can read your code.

**Comment by brianlagunas** [comment]
fixed with #1680
