### ISSUE TITLE
Fluent API for IContainerRegistryExtensions

### ISSUE THREAD

**Issue by aracurd** [PrismLibrary/Prism#1677]
I propose that IContainerRegistryExtensions methods should return IContainerRegistry. Then we will have ability to write like this:
container.RegisterType<T>()
                .RegisterType<T>()
                .RegisterType<T>()
                .RegisterSingleton<T, To>();
What do you think guys?

**Comment by totht91** [comment]
Is it a breaking change?

**Comment by brianlagunas** [comment]
Yes, you would have to change the interface method definitions

**Comment by aracurd** [comment]
I still don't understand why just not use IUnityContainer instead of IContainerRegistry and IContainerProvider like it's was before.

**Comment by dansiegel** [comment]
@aracurd you still can if that’s what you want to do by simply calling GetContainer(). The fact is that this created variations that were very difficult for people to understand between containers and documentation. Simply put most devs are extremely unfamiliar with the DI containers they are using and report issues as Prism issues that are really they haven’t invested the time to learn the container issues. Also by introducing a common API this allowed us to greatly simply what it takes to “support” a new container meaning that you have the ability to use a container with very little effort even when we may not officially support that container.
