### ISSUE TITLE
[XF] Navigating from MasterDetail Detail page's subpage back to Detail page

### ISSUE THREAD

**Issue by Arbalets** [PrismLibrary/Prism#1678]
### Description

When navigating from the MasterDetail Detail page to the subpage and then from the subpage back to the Detail page using MasterDetail page (pulling out Master page or any other way), Detail page gets recreated. 
Prior to version 7.1 it would simply go back to the Detail page without recreating it.

### Steps to Reproduce

1. Go to the subpage (MasterDetailPage/NavigationPage/DetailPage/SubPage)
2. Go back to the DetailPage from MasterDetail (NavigationPage/DetailPage)

### Expected Behavior
Go back to the Detail page without recreating it.
### Actual Behavior
Detail page gets recreated.
### Basic Information

- Version with issue: 7.1.0.431
- Last known good version: 7.0.0.396
- Xamarin.Forms version: 3.4.0.1029999
- IDE: Visual Studio

### Reproduction Link

[Sample](https://github.com/Arbalets/MasterDetailNavigation)

**Comment by brianlagunas** [comment]
This is by design. We must create a new NavigationPage when navigating between detail pages in a MDP because of issues around this navigation pattern.

**Comment by brianlagunas** [comment]
I would like to add, in this case just call GoBackAync.

**Comment by brianlagunas** [comment]
I would like to mention that you could create your own Navigation service that derived from the Prism PageNavigationService and override the [ProcessNavigationForMasterDetailPage](https://github.com/PrismLibrary/Prism/blob/master/Source/Xamarin/Prism.Forms/Navigation/PageNavigationService.cs#L540) and modify line (589)[https://github.com/PrismLibrary/Prism/blob/master/Source/Xamarin/Prism.Forms/Navigation/PageNavigationService.cs#L589] to fit you needs.

**Comment by brianlagunas** [comment]
another option is to have your MDP code behind listen for the event and just call PopToRoot on the Detail as a NavigationPage. Probably easier

**Comment by Arbalets** [comment]
Option two works for me. Thanks again.
