### ISSUE TITLE
Prism.Windows 7.2 status?

### ISSUE THREAD

**Issue by pmatrasc** [PrismLibrary/Prism#1679]
### Description

I'm sorry in advance if this is not the right place where to ask this question.
If I wanted to start a new UWP application using Prism.Windows (aka Prism 7) what's the suggested path?

In Nuget I can only find version 7.0.0.336-pre which I believe is not the one "based" on Template10.
Is it safe to start using the continuous integration version found on myget instead?
Or should I wait for an official "pre-release" of version 7.2? Or even just simply use Template10.1?

Thanks,
Paolo.

**Comment by brianlagunas** [comment]
Use the previews on MyGet.  Unfort7uately, we have not had time to finalize the UWP API, but the Myget is the current working version.
