### ISSUE TITLE
Possible to add a Module from a project in a separate solution?

### ISSUE THREAD

**Issue by HansKrJensrud** [PrismLibrary/Prism#168]
Playing around with Prism, I have managed to add a module from a separate solution/project to the ModuleCatalog in the main solution, but get an error while initiating the same module. This is probably due to that the two solutions/projects operate with two different Unity-containers, and I haven't found a way to inject the "main" container (including the RegionManager) into the separate solution/project while initializing that module (registering view-types and view with region). Am I trying to do something Prism do not support, or is there solution to this scenario (or should this be straight forward, so that I have probably missed something else)? Just wondering, so that I do not spend time on something impossible or much too complicated. Apologize if this is not the correct place to address this kind of issues. Please advice me if not...

**Comment by brianlagunas** [comment]
What is the error?  I doubt this issue has anything to do with the Unity container, because Unity is registered as a singleton in the Shell project so when the module is loaded the IUnityContainer will be properly injected through the interface.

**Comment by briannoyes** [comment]
Solutions and projects don't really matter at runtime, all that matters is that the right assemblies are found, which means they have to be in the exe directory or the GAC. The module loader support DirectoryCatalogs and can load any assemblies it finds in the exe folder or a subfolder, regardless of what project or solution they came from. You can also use configuration to tell the module loader to load modules that were not part of the same solution, as long as those assemblies are getting copied into the exe folder.

**Comment by HansKrJensrud** [comment]
Thanks for great comments and support, and confirmation that this should work. It was a "null" error, and I'm no sure it is caused by something else. Back to debugging!

**Comment by brianlagunas** [comment]
I am closing this issues, as this I snot a limitation of Prism, but most likely an issue with application code.
