### ISSUE TITLE
Problem with references in upgrading to Prism 7.1 doesn't work

### ISSUE THREAD

**Issue by SubasishMohapatra** [PrismLibrary/Prism#1686]
### Description
I have upgraded my WPF app from prism 6 to prism 7.1.
I am still not able to resolve the reference error while accessing the Container property.
IUnity container is defined in an assembly not references. You must add a reference to the assembly Unity.Abstractions 3.1.1.0

I have wiped off all previous Unity references and added Prism.Core Here is the screenshot of the Nuget packages installed.
![image](https://user-images.githubusercontent.com/16698158/52538423-7142e880-2d98-11e9-9989-59408eb7f2ca.png)

### App.xaml
<prism:PrismApplication x:Class="WPFPrismDemoApp.App"
                x:ClassModifier="internal" 
                xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
                xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
	            xmlns:prism="http://prismlibrary.com/">
    <Application.Resources>
    </Application.Resources>
</prism:PrismApplication>

### App.xaml.cs -not complete

using Prism.Ioc;
using Prism.Unity;
using System.Windows;

namespace WPFPrismDemoApp
{
    /// <summary>
    /// Interaction logic for App.xaml
    /// </summary>
    public partial class App : PrismApplication
    {
        protected override Window CreateShell()
        {
            return null;
        }

        protected override void InitializeShell(Window shell)
        {
            base.InitializeShell(shell);
            Application.Current.MainWindow = shell;
            var container= Container.GetContainer();
        }

### Error screenshot
![image](https://user-images.githubusercontent.com/16698158/52538458-d1d22580-2d98-11e9-8ea7-43f7fc07b575.png)

Where am I going wrong?

**Comment by brianlagunas** [comment]
This is most likely happening because you upgraded the Unity container separate from Prism, which you cannot do.  Only use the version of Unity that Prism depends on. Otherwise you break binary compatibility.
