### ISSUE TITLE
System.InvalidOperationException with multi back navigation and compiled bindings

### ISSUE THREAD

**Issue by sebastianfilke** [PrismLibrary/Prism#1688]
### Description

We have an application where we skip a pages and navigate back two times or more. After navigation the app crashes with the following exception. We use syncfusion listview. We can not say yet if the problem is with syncfusion or prism and destroy. The exception is too general. But the exception doesn't happen if we remove the logic in destory method or remove the compiled bindings.

### Steps to Reproduce

1. Implemement IDestructible on your viewmodel
2. Add compiled bindings with x:DataType in your xaml files
3. Navigate back with NavigateAsync("../../")
4. in Destroy method reset some elements and bindings
```
public override void Destroy() {
            var functionalAreaOverviewTileVms = FunctionalAreas.Source.Cast<FunctionalAreaOverviewTileVm>().ToList();
            functionalAreaOverviewTileVms.ForEach(x => x.Image = null);
            FunctionalAreas.Dispose();

            FunctionalAreaTypeFilter = null;
            SelectedFunctionalArea = null;
            SelectedFunctionalAreaTypeFilter = null;
            Title = null;

            base.Destroy();
        }

```
### Expected Behavior
Should normally navigate back
### Actual Behavior
Exception: 
```
System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at Xamarin.Forms.Internals.TypedBinding`2.Apply(Boolean) + 0xd4
   at Xamarin.Forms.Internals.TypedBinding`2.PropertyChangedProxy.<OnPropertyChanged>b__16_0() + 0xc
   at System.Action.Invoke() + 0x11
   at Internal.WinRT.Interop.WinRTCallbacks.ActionInvoker.Invoke() + 0xe
   at Windows.UI.Core.DispatchedHandler.Invoke() + 0x1d
   at Qkiss.UWP!<BaseAddress>+0x43279da
   at Xamarin.Forms.Platform.UWP.TaskExtensions.<>c.<WatchForError>b__2_1(Object) + 0x18
   at System.Threading.SendOrPostCallback.Invoke(Object) + 0x15
   at System.Threading.WinRTSynchronizationContext.Invoker.InvokeCore() + 0x45
```

### Basic Information

- Version with issue: 7.1.0.431
- Last known good version: ?
- Xamarin.Forms version: 3.4.0.1029999
- IDE: Visual Studio 15.9.6

**Comment by dansiegel** [comment]
While I have seen some exceptions on Navigation which seem to indicate that the error occurred as a result of IDestructible the cause has always been due to a bug within my codebase. I'm sure if you create a simplified repro app you'll be able to more easily find the error.

**Comment by mfeingol** [comment]
@sebastianfilke: were you able to create a small repro app that could reproduce the problem?
