### ISSUE TITLE
WindowStyle on PopupWindowAction for third party window is not working as expected

### ISSUE THREAD

**Issue by noufionline** [PrismLibrary/Prism#169]
I have created a custom WindowPopupAction and by overriding CreateWindow I am passing a DevExpress DXWindow as my PopupWindow. When I try to set the style it's not working as expected. Am I missing anything?

  <i:Interaction.Triggers>
        <prism:InteractionRequestTrigger SourceObject="{Binding NotificationRequest}">
            <inf:AbsPopupWindowAction IsModal="True" CenterOverAssociatedObject="True">
                <inf:AbsPopupWindowAction.WindowStyle>
                    <Style TargetType="dx:DXWindow">
                        <Setter Property="SizeToContent" Value="WidthAndHeight"/>
                        <Setter Property="ResizeMode" Value="NoResize"/>
                    </Style>
                </inf:AbsPopupWindowAction.WindowStyle>
                <inf:AbsPopupWindowAction.WindowContent>
                    <views:CriteriaView/>
                </inf:AbsPopupWindowAction.WindowContent>
            </inf:AbsPopupWindowAction>
        </prism:InteractionRequestTrigger>
    </i:Interaction.Triggers>

**Comment by brianlagunas** [comment]
Are you setting the TargetType to be a Window?

**Comment by noufionline** [comment]
Hi Brian. Thanks for the quick response. When I am setting the target type as window it's working. But to set a propery in style which is specific to a third party control I was setting the target as DXWindow


                    <Style TargetType="dx:DXWindow">
                        <Setter Property="SizeToContent" Value="WidthAndHeight"/>
                        <Setter Property="ResizeMode" Value="NoResize"/>
                    </Style>

**Comment by brianlagunas** [comment]
Alright, I found the issue.  When the WindowStyle feature was added, there is a check for the type of style that is being applied  IN this case, the code is checking for a style of type Window, which means that unless the style is targeting a Window, it would not be applied.  This should be an easy fix.  For now you can override GetWindow method and copy/paste everything except the line of code which is checking for the type of Style.

**Comment by brianlagunas** [comment]
Fixed

**Comment by noufionline** [comment]
thanks a Ton Brian 👍
