### ISSUE TITLE
Bug With MasterDetail using SplitOnLandscape[Tablet]

### ISSUE THREAD

**Issue by arturgromek** [PrismLibrary/Prism#1691]
### Bug with Master-Detail using SplitOnLandscape(Tablet)

When using prism navigation with Master-Detail while the master behaviour is set to SplitOnLandscape, the layout breaks on tablets while in landscape, and crashes on startup if started in landscape mode. If started in portrait, works (laggily) but breaks whenever put into landscape mode.

Works normally on phones, as master behaviour doesn't do anything on phones.

### Steps to Reproduce

1. Master-Detail layout with multiple details, and behaviour set to SplitOnLandscape.
2. Put tablet in landscape. (before or after startup)

### Expected Behavior
layout to be normal, and for it to not crash

### Actual Behavior
Crashes on startup if in landscape, non-responsive if put into landscape after start.

### Basic Information

- Version with issue: 7.1.0.431
- Last known good version: Unknown
- Xamarin.Forms version: 3.5.0.129452
- IDE: Visual Studio 2017

### Screenshots

![screenshot_1550121092](https://user-images.githubusercontent.com/38743338/52764252-5a8be280-3073-11e9-9b96-aa1cf93822cb.png)
![screenshot_1550121099](https://user-images.githubusercontent.com/38743338/52764253-5a8be280-3073-11e9-9c4a-c585c878c673.png)
![screenshot_1550121101](https://user-images.githubusercontent.com/38743338/52764254-5b247900-3073-11e9-9eb2-63435291e57b.png)
![screenshot_1550121112](https://user-images.githubusercontent.com/38743338/52764255-5b247900-3073-11e9-921e-449c1b657619.png)

### Reproduction Link

https://github.com/arturgromek/PrismMasterDetailTabletRepro/tree/master

**Comment by brianlagunas** [comment]
The first thing that stands out to me is that your navigation path is wrong. In your master, you do not need to prefix the MasterDetailPage again, and you should not have a prceeding `/` as that inidcates an absolute navigation which rests the navigation stack. Just use `CommandParameter="NavigationPage/DetailOne"`

Regarding the changing of layout direction, Prism has no control over that logic.  All Prism does is create your pages and adds them to the navigation stack. Any issues related to rotating the device to landscape would not be a Prism issue.  Mak sure you are checking for any erros or exceptions.

**Comment by brianlagunas** [comment]
YOu should check out this video for more information on relative vs absolute navigation https://youtu.be/33hYzo5cFcE
