### ISSUE TITLE
ServiceLocator.GetInstance<T>("name"); for all resolved constructor injection

### ISSUE THREAD

**Issue by Rogardo** [PrismLibrary/Prism#1692]
Is there a possibility to get from the Servicelocator a special kind of Instance?
For a direct Interface you can resolve a special kind with the name, but if the interface a used as parameter in the constructor of a other class you can't get a defined Interface.

Is it possible to check if needed parameter objects are defined with the same name (like FirstOrDefault(x => x == name) )?

class definition
```
    public class MaskingCreation : IMaskingCreation
    {
        public string Header { get; set; }

        public MaskingCreation(ITabContent tabContent)
        {
            Header = tabContent.Header;
        }
     }
```
Type registation in App.xaml.cs
```
        protected override void RegisterTypes(IContainerRegistry containerRegistry)
        {
            containerRegistry.Register<ITabContent, TabContentA>("TabContentA");
            containerRegistry.Register<ITabContent, TabContentB>("TabContentB");
        }
```
Get Instance from ServiceLocator
```
ServiceLocator.Current.GetInstance<MaskingCreation>("TabContentA")
```

**Comment by brianlagunas** [comment]
You should ask questions like these on StackOverflow. Be sure to provide as much information as possible such as which container you are using as that could change the behavior of what you are trying to achieve.
