### ISSUE TITLE
Prism 7 just doesn't work.

### ISSUE THREAD

**Issue by Oleksandr-Tokmakov** [PrismLibrary/Prism#1693]
### Description

I have created new wpf project, installed Prism.Wpf and Prism.Unity.
Also I changed base class for App to PrismApplicationBase:

```
public partial class App : PrismApplicationBase
{
        protected override Window CreateShell()
        {
            return new MainWindow();
        }

        protected override IContainerExtension CreateContainerExtension()
        {
            return new UnityContainerExtension();
        }

        protected override void RegisterTypes(IContainerRegistry containerRegistry)
        {
        }
}
```

And in App.xaml:

```
<prism:PrismApplicationBase x:Class="WpfApp1.App"
              xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
              xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
              xmlns:local="clr-namespace:WpfApp1"
              xmlns:prism="clr-namespace:Prism;assembly=Prism.Wpf"
              StartupUri="MainWindow.xaml">
     <prism:PrismApplicationBase.Resources>          
     </prism:PrismApplicationBase.Resources>
</prism:PrismApplicationBase>
```
And when I try to start app it crashes with exceptions like:
----
> Unity.Exceptions.ResolutionFailedException
>   HResult=0x80131500
>   Message=Resolution of the dependency failed, type = 'Prism.Regions.SelectorRegionAdapter', name = '(none)'.
> Exception occurred while: while resolving.
> Exception is: InvalidOperationException - The current type, CommonServiceLocator.IServiceLocator, is an interface and cannot be constructed. Are you missing a type mapping?
> -----------------------------------------------
> At the time of the exception, the container was: 
>   Resolving Prism.Regions.SelectorRegionAdapter,(none)
>   Resolving parameter 'regionBehaviorFactory' of constructor Prism.Regions.SelectorRegionAdapter(Prism.Regions.IRegionBehaviorFactory regionBehaviorFactory)
>     Resolving Prism.Regions.RegionBehaviorFactory,(none) (mapped from Prism.Regions.IRegionBehaviorFactory, (none))
>     Resolving parameter 'serviceLocator' of constructor Prism.Regions.RegionBehaviorFactory(CommonServiceLocator.IServiceLocator serviceLocator)
>       Resolving CommonServiceLocator.IServiceLocator,(none)
> 
>   Source=Unity.Container
>   StackTrace:
>    at Unity.UnityContainer.ThrowingBuildUp(IBuilderContext context)
>    at Unity.UnityContainer.Resolve(Type typeToBuild, String nameToBuild, ResolverOverride[] resolverOverrides)
>    at Unity.UnityContainerExtensions.Resolve(IUnityContainer container, Type t, ResolverOverride[] overrides)
>    at Prism.Unity.Ioc.UnityContainerExtension.Resolve(Type type)
>    at Prism.Ioc.IContainerProviderExtensions.Resolve[T](IContainerProvider provider)
>    at Prism.PrismApplicationBase.ConfigureRegionAdapterMappings(RegionAdapterMappings regionAdapterMappings)
>    at Prism.PrismApplicationBase.Initialize()
>    at Prism.PrismApplicationBase.InitializeInternal()
>    at Prism.PrismApplicationBase.OnStartup(StartupEventArgs e)
>    at System.Windows.Application.<.ctor>b__1_0(Object unused)
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
>    at System.Windows.Threading.DispatcherOperation.InvokeImpl()
>    at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
>    at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>    at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
>    at System.Windows.Threading.DispatcherOperation.Invoke()
>    at System.Windows.Threading.Dispatcher.ProcessQueue()
>    at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
>    at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
>    at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
>    at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
>    at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
>    at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
>    at System.Windows.Application.RunDispatcher(Object ignore)
>    at System.Windows.Application.RunInternal(Window window)
>    at System.Windows.Application.Run(Window window)
>    at System.Windows.Application.Run()
>    at WpfApp1.App.Main()
> 
> Inner Exception 1:
> InvalidOperationException: The current type, CommonServiceLocator.IServiceLocator, is an interface and cannot be constructed. Are you missing a type mapping?
> 

### Steps to Reproduce

0. Create new Wpf project
1. Install Prism.Wpf
2. Install Prism.Unity
3. Change base class for App class in code behind and xaml
4. Implement abstract members
5. Start the app

### Expected Behavior
App starts and works

### Actual Behavior
App crashes on start up

### Basic Information

VS Pro 15.9.7, .NET Framework 4.7.2.
Prism:
CommonServiceLocator - v2.0.4
Prism.Core - v7.1.0.431
Prism.Unity - v7.1.0.431
Prism.Wpf - v7.1.0.431
UnityAbstractions - v3.3.1 (also I tried 4.0.3)
Unity.Container - 5.8.1.1 (also I tried 5.9.4)

### Reproduction Link
https://blackthornvision-my.sharepoint.com/:u:/g/personal/oleksandr_tokmakov_blackthorn-vision_com/EcYscdPrBe1Ioo4ZpHLGlPIBBBxAcNN4XfMXnIk-zGnw-A?e=ATSXKd

**Comment by wowfood** [comment]
You should be inheriting from PrismApplication, not PrismApplicationBase.

**Comment by Oleksandr-Tokmakov** [comment]
> You should be inheriting from PrismApplication, not PrismApplicationBase.

))))) Thanks! That solved my issue.

**Comment by brianlagunas** [comment]
Thanks @wowfood!
