### ISSUE TITLE
ExtendedBindableBase with attributes for related properties and autoproperty

### ISSUE THREAD

**Issue by KSemenenko** [PrismLibrary/Prism#1695]
### Description
I propose to expand the base class with useful functions.
### AutoProperty Description
```cs
public int FirstProperty
{
	get => GetValue<int>();
	set => SetValue(value);
}
```
I think that this method of implementation to simplify the work with properties.

### Attributes Description
``` NotifyProperty```
``` DependsOnProperty```
that allow you to keep track of property updates and call PropertyChange for related properties

``` cs
public class MockExtendedViewModel : ExtendedBindableBase
{

	[NotifyProperty(nameof(ThirdProperty))]
	public int FirstProperty
	{
		get => GetValue<int>();
		set => SetValue(value);
	}

	[DependsOnProperty(nameof(FirstProperty))]
	public int SecondProperty
	{
		get => GetValue<int>();
		set => SetValue(value);
	}

	public int ThirdProperty
	{
		get => GetValue<int>();
		set => SetValue(value);
	}
}
```
If you assign a new value to FristProperty, you will also be instantiated by the OnPropertyChanged event for ThirdProperty.

Also trigger events for SecondProperty because it depends on FirstProperty.

**Comment by brianlagunas** [comment]
Thanks for the idea, but this is not a responsibility that Prism wants to take on.  There are many ways to handle INPC, and there are many projects available that already implement them.
