### ISSUE TITLE
[XF] Feature Request: OnNavigatingToAsync, OnNavigatedToAsync and OnNavigatedFromAsync

### ISSUE THREAD

**Issue by DavidStrickland0** [PrismLibrary/Prism#1697]
### Description

Current implementation of INavigateAware has 3 overrides. This is requesting three additional versions of these methods that return Task. There is currently no way to call an Async Method and await its execution before the page is popped onto the stack or the UI is released to the user. One of the advantages of ViewModelBased Navigation is the ability to let the ViewModel decide if the page should load. Currently we can do this provided everything is sync no async methods can be used prior to page load. Or Prior to the page being released to the User for interaction.

### Steps to Reproduce

1. Place an async method in OnNavigatingTo 
2. place a Break Point in OnNavigatedTo
### Expected Behavior
OnNavigatingTo finishes before OnNavigatingTo Completes.

### Actual Behavior
OnNavigatedTo fires before OnNavigatingTo Completes.
or
OnNavigatingTo DeadLocks
or 
OnNavigatingTo Blocks the UI thread.

Depending on how the async method is called

### Reproduction Link

https://github.com/DavidStrickland0/ONavigatingTo

**Comment by brianlagunas** [comment]
This has already been discussed and is not currently planned for implementation. There are a number of issues that could arise from providing async versions of those methods and result in perceived performance problems as the navigation would not occur until those methods have completed.  See #704 as an example.
