### ISSUE TITLE
OnNavigatedTo is not fired on clicking hardware back button on android device

### ISSUE THREAD

**Issue by henryyue2010** [PrismLibrary/Prism#1698]
### Description

Click the back button on Android device, the OnNavigatedTo method is not fired.
Anyone met same issue?

### Expected Behavior
should fire OnNavigatedTo when clicking the back button on the device

### Actual Behavior

not fired

### Basic Information

- Version with issue: 7.1.0.431
- Last known good version:
- Xamarin.Forms version: 3.5.0.129452
- IDE:

**Comment by brianlagunas** [comment]
Closed due to no repo link provided.
