### ISSUE TITLE
When will Prism supports Xamarin.WPF AGAIN?

### ISSUE THREAD

**Issue by lekia** [PrismLibrary/Prism#1699]
### Description

I know there are some arguments between the supporting of WPF, and I really understand at this point WPF over Xamarin is not supported, the INavigationService for WPF will not be implemented and probably never. WPF is dying and is not suitable for mobile UI.

**If Prism has never supported Xamarin.WPF, I would not post this issue.**

**But I can actually run WPF over Xamarin.Forms with Prism 7.0.0.396** and register and navigate like what the other platforms do, sharing the same VM and UI layout and codes without any platform-based file. however after 7.1 the WPF project always complains "could not load type ... INavigationService."

Would you please leave some compatibility to Xamarin.WPF? Platform-based Xamarin is great but we now have Xamarin.Form.

### Steps to Reproduce

1. Upgrade Prsim from 7.0.0 to one of the later versions.
2. Run WPF project.

### Expected Behavior

Run without error like what it does in Prism 7.0.

### Actual Behavior
Type load error for INavigationService.

### Basic Information

- Version with issue: Versions > 7.0.0.396
- Last known good version: 7.0.0.396
- Xamarin.Forms version: 4.0.0.135214
- IDE: VS2017 15.9.2

### Reproduction Link

Sample: We all know Prism.Forms does not support Xamarin.WPF now.

**Comment by brianlagunas** [comment]
Prism.Forms will not support WPF any time soon. You are welcome to fork Prism and remove this constraint for your specific requirements.
