### ISSUE TITLE
Please provide one more extention method for UnityContainer to register type for navigation without a key

### ISSUE THREAD

**Issue by noufionline** [PrismLibrary/Prism#170]
Dear Brian,
Since most of the time users are registering view for navigation with its default view name,it would be fantastic if you can provide one more extension method to register like mentioned below. 

```
  public static void RegisterTypeForNavigation<T>(this IUnityContainer container)
  {
       container.RegisterType(typeof(Object), typeof(T), typeof(T).FullName);
  }
```

**Comment by briannoyes** [comment]
Great suggestion @noufionline, I've actually had my own helper method on several projects that did the same thing because it is such a common thing. I wish the common ServiceLocator used by the framework to resolve types had a container agnostic way to register types so that we could put it down in core, but I think we would have to do it against the container interfaces as you say because each container is a little different on the way you register and what parameters are needed.

We will look into it.

**Comment by brianlagunas** [comment]
Actually, it would be easier to just make the current RegisterTypeForNavigation have an optional name parameter.  Which honestly, I thought it did, because that is the snippet I use in all my apps.  I must have gotten confused when adding this extension method.  Oversight on my part.

**Comment by brianlagunas** [comment]
I also wanted to mention that I wouldn't use the FullName for the registration by default because that would force you to type in the fully qualified name of the view in your ViewModel.  Which is most likely not desired.  Instead, I would just use the name of the view itself.

**Comment by noufionline** [comment]
Yes Brian. You are right👍

**Comment by brianlagunas** [comment]
So something like this:
```
        public static void RegisterTypeForNavigation<T>(this IUnityContainer container, string name = null)
        {
            Type type = typeof(T);
            string viewName = String.IsNullOrWhiteSpace(name) ? type.Name : name;
            container.RegisterType(typeof(object), typeof(T), viewName);
        }
```

**Comment by noufionline** [comment]
Looks perfect👌😊

**Comment by brianlagunas** [comment]
This has been fixed for Unity, Autofac, and SturctureMap

**Comment by noufionline** [comment]
Hi Brian,
Don't you think FullName will give uniqueness than the name property as one or more different module can have a similar view name?

**Comment by brianlagunas** [comment]
The problem with that is if you use FullName, then in your VM, when you navigate you will be required to provide the entire fully qualified name of the View.  So something like RequestNavigate("MyApplication.Modules.Customers..Views.CustomerView").  This is not only a major pain in the ass, but it also creates a dependency of knowledge which will require you to know the exact location of the View as it relates to your module dependencies.

**Comment by noufionline** [comment]
Hmmm. Yes Brian that makes perfect sense.

**Comment by noufionline** [comment]
As I was passing type name as command parameter
CommandParameter="{x:Type salesOrders:SalesOrderCollectionView}"  
I never thought about your point

**Comment by brianlagunas** [comment]
The good thing about this is that if you prefer the FullName, simply create your own extension method to support it.
