### ISSUE TITLE
RegisterForNavigationOnPlatform not Registers Default View instead of Platform View

### ISSUE THREAD

**Issue by erikh111** [PrismLibrary/Prism#1700]
### Description
I'm attempting to implement the common ViewModel platform or idiom specific View use case and am having trouble with the platform specific View rendering as it should according to the documentation.

### Steps to Reproduce

1. Create ViewAPage.xaml, ViewBPage.xaml view using add new item in IDE, ViewAPageViewModel & ViewBPageViewModel generated
2. Create  ViewAPageTablet.xaml and ViewBPageAndroid.xaml
3. Register Views/ViewModels in the containerRegistry
`containerRegistry.RegisterForNavigationOnIdiom<ViewAPage, ViewAPageViewModel>(tabletView: typeof(ViewAPageTablet));`
`containerRegistry.RegisterForNavigationOnPlatform<ViewBPage, ViewBPageViewModel>(new Platform<ViewBPageAndroid>(RuntimePlatform.Android));`

### Expected Behavior
Expected the ViewBPage.xaml would render when running on an android simulator just as the ViewPageTablet.xaml rendered when running an iOS Tablet simulator

### Actual Behavior
The default ViewBPage.xaml renders regardless of simulator OS.

### Basic Information

- Version with issue: 7.1.0.431
- Last known good version: 7.1.0.431
- Xamarin.Forms version: 3.2.0.871581
- IDE: Visual Studio Community (for Mac)

### Screenshots
![screen shot 2019-02-18 at 1 59 05 pm](https://user-images.githubusercontent.com/262699/52971499-a8f7f480-3385-11e9-9da2-b8f4ddb0902d.png)
![screen shot 2019-02-18 at 1 57 27 pm](https://user-images.githubusercontent.com/262699/52971500-a8f7f480-3385-11e9-8345-d1879535a013.png)
![screen shot 2019-02-18 at 1 57 01 pm](https://user-images.githubusercontent.com/262699/52971501-a8f7f480-3385-11e9-88ff-fa4d8d43fa9d.png)
![screen shot 2019-02-18 at 1 56 53 pm](https://user-images.githubusercontent.com/262699/52971502-a8f7f480-3385-11e9-8da9-d8867c95ba67.png)

### Reproduction Link
[Archive.zip](https://github.com/PrismLibrary/Prism/files/2877080/Archive.zip)

**Comment by dansiegel** [comment]
This is confirmed. It appears that the current registration logic ends up registering the View twice resulting in the original default View type taking precedence.

**Comment by dansiegel** [comment]
@erikh111 thanks for the bug report and repo app! this has been fixed and will be available shortly in the CI feed.

**Comment by erikh111** [comment]
@dansiegel thanks for reviewing this issue and providing a fix so quickly!
