### ISSUE TITLE
Prism.Structuremap not updated in MyGet

### ISSUE THREAD

**Issue by noufionline** [PrismLibrary/Prism#1701]
When is the update on Structuremap is expected? My production project is based on Structuremap and would like to integrate the new DialogService.

Please help!

**Comment by brianlagunas** [comment]
We update containers every now and then as we work on new featuresor before a release.  However, StrutureMap is not even part of the WPF solution anymore. If I remember correctly, this container has been abandoned by its author. So we are not providing updates for that container.

**Comment by dansiegel** [comment]
@noufionline as was mentioned StructureMap has been ["Sunsetted"](https://github.com/structuremap/structuremap#structuremap-has-been-sunsetted) by its maintainers. As a result of this the Prism team will no longer be shipping updates for StructureMap moving forward.

**Comment by noufionline** [comment]
I understand. Actually structure map was replaced by new container Lamar
and I was expecting that would be integrated in place of Structure map.

Anyways now I will move back to Unity.

Thanks a lot for your excellent support.

**Comment by dansiegel** [comment]
@noufionline it has indeed... however Lamar is a new container with only around 35,000 downloads. It would really need to mature and have a much larger user adoption before we could consider official support. In the mean time the IoC abstractions that we use for Prism 7 are intentionally designed to reduce the heavy lifting that are needed at the container level. You should be able to very easily add your own implementation for Lamar if that's what you prefer to do.
