### ISSUE TITLE
Support for Aspect Oriented Programming missing from new IModule interface

### ISSUE THREAD

**Issue by SubasishMohapatra** [PrismLibrary/Prism#1707]
## Question
How do I set virtual method interceptors while registering the ViewModels in the RegisterTypes(IContainerRegistry containerRegistry)

I would like to do something like this, but I cant do it with the "containerRegistry"

```
 Container.Configure<Interception>()
.SetInterceptorFor<SomeViewModel>(new VirtualMethodInterceptor());
```

**Comment by dansiegel** [comment]
As indicated in the Issue Templates, Questions should be asked on StackOverflow
