### ISSUE TITLE
[Question] ConfigureDefaultRegionBehaviors is not possible anymore

### ISSUE THREAD

**Issue by Blackjack92** [PrismLibrary/Prism#171]
When using the StockTrader example with prism6 it is not possible to do the following Code:

```
        protected override Microsoft.Practices.Prism.Regions.IRegionBehaviorFactory ConfigureDefaultRegionBehaviors()
        {
            var factory = base.ConfigureDefaultRegionBehaviors();

            factory.AddIfMissing("AutoPopulateExportedViewsBehavior", typeof(AutoPopulateExportedViewsBehavior));

            return factory;
        }
```

I tried to do it this way:

```
        protected override Prism.Regions.IRegionBehaviorFactory ConfigureDefaultRegionBehaviors()
        {
            var factory = base.ConfigureDefaultRegionBehaviors();

            factory.AddIfMissing("AutoPopulateExportedViewsBehavior", typeof(AutoPopulateExportedViewsBehavior));

            return factory;
        }
```

and Implemented the Prism.Regions.RegionBehavior in the AutoPopulateExportedViewsBehavior but my Application crashes, when calling run of the bootstrapper. Maybe you can help me?

**Comment by Blackjack92** [comment]
As ioc container mef is used and the problem is, that the mefExtensions are obsolete

**Comment by brianlagunas** [comment]
If you want to use MEF for Prism 6 you must use the Prism.Mef NuGet package.  Just so you know, MEF is not an IOC container :)

**Comment by Blackjack92** [comment]
I already used the MEF package and removed the Unity package but it is still crashing.

**Comment by brianlagunas** [comment]
Nothing changed except the namespaces.  What is your exception?

**Comment by brianlagunas** [comment]
Also, please confirm that you are using the Prism.Mef package and NOT then Prism.MefExtentions package (deprecated).

**Comment by Blackjack92** [comment]
At the moment I did some changes, so that I don't get any error. But the binding of the different Views does not work, so all regions are empty.
What I did:
1) I removed all deprecated packages + Installed new packages
2) I fixed all usings to the right namespaces
3) Tests were not fixed but uncommented
4) In the Bootstrapper and the  AutoPopulateExportedViewsBehavior were the following changes done:
```
  protected override Prism.Regions.IRegionBehaviorFactory ConfigureDefaultRegionBehaviors()
        {
            var factory = base.ConfigureDefaultRegionBehaviors();

            factory.AddIfMissing("AutoPopulateExportedViewsBehavior", typeof(AutoPopulateExportedViewsBehavior));

            return factory;
        }
```
Used the Prism.Regions.RegionBehavior in the AutoPopulateExportedViewsBehavior instead of the Microsoft.Practices.

**Comment by brianlagunas** [comment]
Were you using Unity before you switch to MEF?  You said you removed the Unity package in an earlier statement, which implies you were using Unity.  If you did, then there are other steps that you must take when switching to use MEF.

**Comment by Blackjack92** [comment]
No sry that was another Project. 
I took the stock example, which used the depricated MEF package with MEFExtensions. Then I removed the depricated packages and added the prism 6 packages.

**Comment by brianlagunas** [comment]
Which stock example?

**Comment by Blackjack92** [comment]
https://msdn.microsoft.com/en-us/library/gg430879(v=pandp.40).aspx 
The Stock Trader Reference Implementation.

**Comment by brianlagunas** [comment]
Worked for me.

**Comment by Blackjack92** [comment]
Have you also replaced the old packages with the new one? :)

**Comment by brianlagunas** [comment]
All I did was download the ZIP.  Unblock the zip file before extracting.  Removed all old Prism packages, added new Prism 6 packages. Find Replace fix on namespaces.   Then it worked.

**Comment by Blackjack92** [comment]
Okay thank you very much, I will try it!
