### ISSUE TITLE
Multiple frames within a window and associated NavigationServices

### ISSUE THREAD

**Issue by MikelThief** [PrismLibrary/Prism#1710]
### Description

I have a following situation:

In my initial Window I create a NavigationService (since 7.2-pre2 it is created automatically in PrismApplicationBase). This NavigationService takes care of navigation within the core frame and instantly navigates to shell view (or login view if user is not logged in).

Now, I put a NavigationView control inside the shell view. This control has its own internal frame for displaying other pages next to the menu panel. This internal frame has to have its own NavigationService as well.

Currently there is no clear way of how to place two NavigationServices within one ViewModel, because asking for NavigationService in ViewModel's constructor will always return NavigationService which belongs the frame bound to the corresponding view.

Thus, Shell's ViewModel has no way to obtain internal NavigationService to govern changing items inside NavigationView's frame.

### Expected Behavior

Maybe registering a Frame inside Container with some GUID taken from ViewModel (to provide unique pairing) could be created. Then in some arbitrary ViewModel one can ask for a specified NavigationService, which is being created internally in the framework, so no reference to a frame is being passed to ViewModel. 

### Actual Behavior

Cannot create a NavigationView manually.

### Basic Information

- Version with issue: 7.2.-pre2
- Last known good version: 7.2.0.853 (allowed for manual NavigationService creation)
- IDE: VS2017

### Reproduction Link

I can create a sample if it is needed to start tinkering with the way of providing some access to two NavigationServices

**Comment by bartlannoeye** [comment]
As mentioned on Slack by @dansiegel, multi window/frame is something we're not supporting yet, but it's certainly something that's needed as UWP added it. If you can give us a sample project, it saves us some time to create one, that would be helpful indeed.

**Comment by MikelThief** [comment]
@bartlannoeye thanks for the reponse. Unfortunately I am currently ill and will be seeing a doctor in a couple of days. After I get better I should be able to create what you need.

**Comment by bartlannoeye** [comment]
There's no rush, we got several points to tackle. That's why the UWP version is still beta.

**Comment by dansiegel** [comment]
Obviously let's have some discussion around any proposed API changes.. but I would encourage you to join in the effort and submit PR's to help us get to something we can release.

**Comment by MikelThief** [comment]
What actually came to my mind so far i what I have already written. Hovewer this would add a requirement to call for IContainerExtension every time one needs more than the default NavigationService (to resolve other instances which are being registered in View's code-behind - is this even sane?)

**Comment by totht91** [comment]
@dansiegel You encourage the discussion but closing the issue? Do you even opensource?

**Comment by son2499** [comment]
styp1118@gmail.com
