### ISSUE TITLE
Remove Navigation extensions that take NavigationTransitionInfo 

### ISSUE THREAD

**Issue by dansiegel** [PrismLibrary/Prism#1711]
### Description

Currently Prism for UWP has the IPlatformNavigation with extensions for INavigationService which expose NavigationTransitionInfo as a parameter. This is a major violation of the MVVM pattern. We likely need some new Service that can act as a factory to create the NavigationTransitionInfo based on some Known query parameter. 

### Current API

As mentioned above the current API violates MVVM design by directly exposing a View centric object inside of the ViewModel.

```cs
await NavigationService.NavigateAsync("ViewA", new DrillInNavigationTransitionInfo())
```

### Proposed API

Following a more proper MVVM design this really should be handled via a Uri query parameter like shown here:

```cs
await NavigationService.NavigateAsync("ViewA?transition=drillin")
```

This would then be handled by a service that could be customized by developers who may have custom Navigation Transitions with a service like:

```cs
public interface INavigationTransitionFactory
{
    NavigationTransitionInfo CreateTransitionInfo(string name);
}

public class NavigationTransitionFactory : INavigationTransitionFactory
{
    public NavigationTransitionInfo CreateTransitionInfo(string name)
    {
        switch(name)
        {
            case "drillin": return new DrillInNavigationTransitionInfo();
            case "slide": return new SlideNavigationTransitionInfo();
            case "entrance": return new EntranceNavigationTransitionInfo();
            default: throw new NotImplementedException($"No transition has been defined for {name}");
        }
    }
}
```

This would further need to be supported for the default implementation with a set of constants like:

```cs
public static class KnownNavigationParameters
{
    public const string TransitionInfoKey = "transition";
    public const string DrillInNavigation = "drillin";
    public const string SlideNavigation = "slide";
    public const string EntranceNavigation = "entrance"
}
```

**Comment by MikelThief** [comment]
@dansiegel 
Do you plan to add a possibility to provide custom implementation of `NavigationTransitionFactory`?
I believe it would be good to allow users to register their own implementation as any new TransitionInfos that may appear, won't be supported by Prism until somebody adds them (becuase matching parameter with the actual TransistionInfo is done internally in Prism).

**Comment by MikelThief** [comment]
This is a good idea. How about adding a tiny base class to make things a little easier to mess with:

```
public class NavigationTransitionFactoryBase : INavigationTransitionFactory
{
    protected Dictionary<string, NavigationTransitionInfo> TransitionInfoDictionary

    public NavigationTransitionFactoryBase()
    {
        TransitionInfoDictionary = new Dictionary<string, NavigationTransitionInfo>();
    }

    // user adds their own pairs like {drillin, new DrillInNavigationTransitionInfo()}
    // can be overridable if we want to provide default implementation
    public void virtual ProvideNavigationTransitionInfo() 

    public NavigationTransitionInfo GetTransitionInfo(string name)
    {
        return TransitionInfoDictionary[name];
    }
}
```

**Comment by dansiegel** [comment]
@MikelThief there's not really a point in a "BaseClass". We can do this like the [`IPageBehaviorFactory`](https://github.com/PrismLibrary/Prism/blob/master/Source/Xamarin/Prism.Forms/Behaviors/PageBehaviorFactory.cs) where we simply implement GetTransitionInfo virtually so you can simply inherit from Prism's implementation and handle anything custom or that wouldn't be handled OOB... and call the base implementation for everything else...

**Comment by JerryNixon** [comment]
Remember that MANY transitions have properties.

**Comment by dansiegel** [comment]
@JerryNixon having this as part of the Navigation call from the ViewModel completely breaks MVVM.

**Comment by JerryNixon** [comment]
Difficult problems. I know.
