### ISSUE TITLE
Prism 7.1.0431 not working with any version of Unity.Wcf

### ISSUE THREAD

**Issue by aracurd** [PrismLibrary/Prism#1713]
I'm trying to use Prism with Unity.Wcf. Problem that latest version of Unity.Wcf (5.9.0) needs UnityContainer >= 5.9.0. UnityContainer depends on Unity.Abstractions >= 4.0.0.
 Latest version of Prism need UnityContainer  5.8.1 + Unity.Abstractions >= 3.3.1.

I try to use previous version Unity.Wcf (4.0) depends on Unity.Abstractions >= 2.0.0 but this is didn't work for me. Someone know any solution?

**Comment by MikelThief** [comment]
Obviously the newer version won't work as Prism is built against the older version i.e. 3.X

**Comment by aracurd** [comment]
> Obviously the newer version won't work as Prism is built against the older version i.e. 3.X

There is why i tried to use old version. But old didn't works too. So looks like only Prism 6 works with Unity.Wcf

**Comment by aracurd** [comment]
I find solution. Just need to do redirect reference from old version to new 
` <dependentAssembly>
        <assemblyIdentity name="Unity.Abstractions" publicKeyToken="6d32ff45e0ccc69f" culture="neutral" />
        <bindingRedirect oldVersion="2.0.0.0" newVersion="3.3.1.0" />
      </dependentAssembly>`
