### ISSUE TITLE
Swallowing Exceptions

### ISSUE THREAD

**Issue by tstivers1990** [PrismLibrary/Prism#1715]
### Description

```cs
protected override async void OnInitialized()
{
    InitializeComponent();

    await NavigationService.NavigateAsync($"{nameof(NavigationPage)}/{nameof(LoginView)}");
}
```

Because `OnInitialized` is marked `void`, any exception that gets thrown gets eaten. Visual Studio won't break on the line that threw the exception. It just goes into a pause state and shows you the name of the exception. Surely this isn't intended behavior?

It may also be caused by `OnNavigatedTo` also returning `void`. I'm not sure which. There are a lot of methods that return `void` where it would be desirable to return `Task` or provide an alternate option, such as `INavigationAwareAsync`, `IActiveAwareAsync`, etc.

### Steps to Reproduce

1. Create new app
2. Throw exception from a view
3. ???
4. Cry
### Basic Information

- Version with issue: latest
- Last known good version: N/A
- Xamarin.Forms version: 3.4.latest
- IDE: VS Latest

### Screenshots

![image](https://user-images.githubusercontent.com/14251176/53335570-d71b8e00-38c9-11e9-819c-6941047e4ec2.png)

**Comment by dansiegel** [comment]
The NavigationService isn't "swallowing" the Exceptions. If you look at the Navigation Result you'll see if your navigation was successful and what the Exception was.

```cs
var result = await NavigationService.NavigateAsync("ViewWithException");
if(!result.Success)
{
    Console.WriteLine(result.Exception);
}
```

Also worth noting that it's actually a bad practice to be using nameof(SomePage) since this would directly expose the Page class within your ViewModel. It would be a far better practice to abstract that into a Keys class that exposes it as a constant string like:

```cs
public static class NavigationKeys
{
    public const string FooPage = nameof(FooPage);
    public const string BarPage = nameof(BarPage);
}
```

**Comment by tstivers1990** [comment]
>The NavigationService isn't "swallowing" the Exceptions. If you look at the Navigation Result you'll see if your navigation was successful and what the Exception was.
>
>```cs
>var result = await NavigationService.NavigateAsync("ViewWithException");
>if(!result.Success)
>{
>    Console.WriteLine(result.Exception);
>}
>```

It's still swallowing the exception, though. Visual Studio doesn't properly break on the line. And many times, Visual Studio fails to show any information about the exception (such as a message), instead stating that a timeout occurred while getting exception details. This makes debugging about as annoying as it could be. The fact the result shows you exception details is great and all. But that doesn't do anything to resolve the point I'm bringing up.

Is there a reason why my proposal can't be done? I don't think it's that unreasonable to have `OnInitialized` return `Task`, considering you're always going to have to call a navigation method from it, and those are only `async`. And I don't think it's unreasonable to add `INavigationAwareAsync`, `IActiveAwareAsync`, etc.

> Also worth noting that it's actually a bad practice to be using nameof(SomePage) since this would directly expose the Page class within your ViewModel. It would be a far better practice to abstract that into a Keys class that exposes it as a constant string like:
> 
> ```cs
> public static class NavigationKeys
> {
>     public const string FooPage = nameof(FooPage);
>     public const string BarPage = nameof(BarPage);
> }
> ```

I actually wrote this for my `ViewModelBase`. The code that uses `nameof` is in `App.xaml.cs` where this isn't available.

```cs
public class ViewModelBase : BindableBase
{
	...

	protected async Task<INavigationResult> NavigateAbsolute<TViewModel>(bool useNavigationPage = false)
		where TViewModel : ViewModelBase
	{
		return await NavigateAbsolute<TViewModel>(null, useNavigationPage);
	}

	protected async Task<INavigationResult> NavigateAbsolute<TViewModel>(INavigationParameters parameters,
		bool useNavigationPage = false) where TViewModel : ViewModelBase
	{
		var key = useNavigationPage ? "/NavigationPage" : "";

		key += $"/{GetViewName(typeof(TViewModel).Name)}";

		return await _navigationService.NavigateAsync(key, parameters);
	}

	protected async Task<INavigationResult> NavigateRelative<TViewModel>() where TViewModel : ViewModelBase
	{
		return await NavigateRelative<TViewModel>(null);
	}

	protected async Task<INavigationResult> NavigateRelative<TViewModel>(INavigationParameters parameters)
		where TViewModel : ViewModelBase
	{
		return await _navigationService.NavigateAsync(GetViewName(typeof(TViewModel).Name), parameters);
	}
	
	private static string GetViewName(string viewModelName)
	{
		if (!viewModelName.EndsWith("ViewModel"))
		{
			throw new ArgumentException($"Parameter `{nameof(viewModelName)}` must end with 'ViewModel'.",
				nameof(viewModelName));
		}

		var result =  viewModelName.Substring(0, viewModelName.Length - "Model".Length);
		return result;
	}
	
	...
}
```

**Comment by dansiegel** [comment]
@tstivers1990 the NavigationService used to allow most exceptions to bubble up and while also handling a few. This forced developers to wrap every navigation call in a try/catch and generally led to a bad experience. That behavior was intentionally changed to make it easier for developers to handle situations where Navigation has failed in a graceful manner with INavigationResult.

**Comment by tstivers1990** [comment]
> @tstivers1990 the NavigationService used to allow most exceptions to bubble up and while also handling a few. This forced developers to wrap every navigation call in a try/catch and generally led to a bad experience. That behavior was intentionally changed to make it easier for developers to handle situations where Navigation has failed in a graceful manner with INavigationResult.

I'm not understanding. Based on what you stated, I'd say it's user error because they haven't caught the exception in the first place. Wrapping every navigation call in a try/catch seems like exactly the sort of thing you shouldn't do. It's akin to:

```cs
public class Program
{
	static void Main(string[] args)
	{
		try
		{
			// do something
		}
		catch { }
	}
}
```

**Comment by tstivers1990** [comment]
@dansiegel 

My problem also isn't with the navigation service itself. Prism could still return `INavigationResult` while fixing the issue. The problem is that `OnInitialized` has to return void, and as such will swallow every exception that gets thrown down that chain. This makes no sense, because you're supposed to call the navigation service in `OnInitialized` and that guarantees you're going to call a method that returns `Task`. There's no reason *not* to have `OnInitialized` return `Task`. Along with that, `INavigationAware`, `IActiveAware`, etc must return void, and so those also swallow exception information. Making `OnInitialized` return `Task` and `await`ing it in any code that calls it within Prism would resolve half of it. And then making `INavigationAwareAsync`, etc interfaces would resolve the other half. It wouldn't require any changes to what the navigation service returns from what I can see. You could still return `INavigationResult` and users wouldn't have to wrap their navigation calls in a try/catch block. But exceptions would bubble up correctly, and Visual Studio etc would break on the line that threw the exception like it's supposed to.

**Comment by dansiegel** [comment]
@tstivers1990 

OnInitialized is called from the Constructor and therefore cannot return a task. You should simply do an async void and get the result. If you haven't done something that basic then swallowing the exception is on you.

As to your other complaints about INavigationAware what you're asking would lock up the UI Thread and actually lead to poor performance.

**Comment by tstivers1990** [comment]
> @tstivers1990
> 
> OnInitialized is called from the Constructor and therefore cannot return a task. You should simply do an async void and get the result. If you haven't done something that basic then swallowing the exception is on you.

I can understand that returning `Task` isn't viable for `OnInitialized`. I'm not following how "simply do an async void and get the result" will resolve my problem. I know an exception happened. Visual Studio tells me an exception happened. The problem is it just gives me the standard "application paused" screen with an exception dialog, rather than breaking on the line in my code that threw the exception.

For example: I make a call to `HttpClient.GetAsync()`. `GetAsync()` throws a `HttpRequestException`. Under normal circumstances, Visual Studio would break on the call to `HttpClient.GetAsync()` with exception details. But with my Xamarin Forms project using Prism, it gives me the pause screen with a dialog that tells me an `HttpRequestException` was unhandled. Obviously, I should be handling this exception and it's my fault for not handling it. But that's what debugging is for, and why it's useful having the debugger break on the line that caused the exception, so you know what needs to be fixed. How can I go about getting the desired behavior here? I've done pretty extensive googling on this topic and have come up with 0 solutions. I'm not sure if it's a Xamarin Forms thing, or if it's something to do with the way Prism works.

> As to your other complaints about INavigationAware what you're asking would lock up the UI Thread and actually lead to poor performance.

I'm not understanding how that would lock up the UI thread? I'm aware of the caveats of `async/await` and the need to use `ConfigureAwait(false)` in many scenarios. But I don't understand how making an alternative `INavigationAwareAsync` would inherently lock up the UI thread?

**Comment by tstivers1990** [comment]
These aren't necessarily complaints, either. They're suggestions for solutions to an issue I'm having. If the suggestions aren't possible, then so be it. But I'm not one to just complain and demand someone fix the problem. I'm willing to submit a pull request myself if it's something that can be done.
