### ISSUE TITLE
IDialogParameter inheritance

### ISSUE THREAD

**Issue by noufionline** [PrismLibrary/Prism#1716]
Hi @brianlagunas 

Please inherit IDialogParameters from INavigationParameters as you are already inheriting DialogParameters from NavigationParameters. It will be a great help.

**Comment by dansiegel** [comment]
@noufionline can you provide some context on how you feel this would be a "great help". Thanks

**Comment by noufionline** [comment]
In my ViewModelBase class which supports both IDialogService and my custom implemented RegionAwareDialog Service. If IDialogParameters is derived from INavigationParameters then I can reuse my method. Now I am forced to create two separate methods.

see the code below.

```csharp
 public override void OnDialogOpened(IDialogParameters parameters)
        {
            SetLookupItems();

            var action=parameters.GetValue<string>("action");
            switch (action)
            {
               
            }
        }


 public override void OnNavigatedTo(NavigationContext navigationContext)
         {
            base.OnNavigatedTo(navigationContext);

            SetLookupItems();

            var parameters=navigationContext.Parameters;
            var action=parameters.GetValue<string>("action");
            switch (action)
            {
               
            }
        }
```

**Comment by brianlagunas** [comment]
No you can't, because INavigationParameters is not included in WPF. This also means that NavigationParameters does not implement the INavigationParametrs interface.

You can however cast the IDialogParameters (which is actually an instance of DialogParameters) to NavigationParameters.
