### ISSUE TITLE
[XF]Navigation broken after switching Detail of MasterDetailPage

### ISSUE THREAD

**Issue by hongyue** [PrismLibrary/Prism#1719]
### Description

I have a MasterDetailPage with Detail switch between NavigationPage and TabbedPage. TabbedPage also has its Children wrapped into NavigationPages. The navigation hierarchy looks like this:
MasterDetailPage:
	navigationpage -> PageA -> PageB
	tabbedpage -> Tab1(navigation page) -> PageC -> PageD
After switching between navigationpage and tabbedpage, I can't navigate from PageA to PageB or PageC to PageD. The first time switched to tabbedpage, it does work correctly. 

### Steps to Reproduce

1. Create MasterDetailPage
2. Create TabbedPage
3. Create ContentPage wrapped in NavigationPage
4. Create menu items to switch Detail
5. Switch Detail between TabbedPage and NavigationPage
6. Navigate in tab page or content page to next page

### Expected Behavior
Navigate successfully.

### Actual Behavior
Navigation not happened, and NavigateAsync result.success returned true!

### Basic Information

- Version with issue: 7.2.0.1038-pre
- Last known good version: 
- Xamarin.Forms version: 3.5.0.169047
- IDE: Visual Studio 2017 15.9.7

### Screenshots

N/A

### Reproduction Link

https://github.com/hongyue/bug-prsim-xf-masterdetail-nav

**Comment by hongyue** [comment]
seems the issue has already been fixed after the 7.2.0.1038-pre released. I just compiled the source code and adding the assemblies to my project, the problem has gone.

**Comment by dansiegel** [comment]
@hongyue remember we do have a much easier way for you to get the latest bits... just add the CI feed as a package source in Visual Studio and you can install the CI packages as we make changes.

**Comment by hongyue** [comment]
@dansiegel Thank you for reminding me, next time I'll try it first.
