### ISSUE TITLE
White page when I use NavigationPage in URI

### ISSUE THREAD

**Issue by patricksegantine** [PrismLibrary/Prism#1723]
### Description

when I use the NavigateService.NavigateAsync() with "NavigationPage" on the URI, the app do not show view

### Steps to Reproduce

1. uncomment navigation startup code on OnInitialized in app.xaml.cs that not work
2. run the app

### Expected Behavior
show navbar

### Actual Behavior
do not show page content and launch exception: System.NullReferenceException: Object reference not set to an instance of an object.

### Basic Information

- Version with issue: 7.1.0.431
- Last known good version: --
- Xamarin.Forms version: 3.5.0.169047
- IDE: Visual Studio 2017 15.9.7

### Screenshots

https://github.com/patricksegantine/prism7-NavigationPage-Issue/tree/master/screenshots

### Reproduction Link

[GitHub](https://github.com/patricksegantine/prism7-NavigationPage-Issue)

**Comment by dansiegel** [comment]
@patricksegantine your repo does not seem to exist or you've created it as a private repo. I'm not sure what exactly you're doing I can say using a NavigationPage is pretty well vetted. Unless you're doing some total one off I can't see a reason why you would be having trouble. 

```cs
protected override void OnInitialized()
{
    NavigationService.NavigateAsync("NavigationPage/ViewA");
}

protected override void RegisterTypes(IContainerRegistry containerRegistry)
{
    containerRegistry.RegisterForNavigation<NavigationPage>();
    containerRegistry.RegisterForNavigation<ViewA>();
}
```

Closing for now as I cannot see your repo. If you're still having trouble feel free to update the thread and we can re-evaluate.
