### ISSUE TITLE
UWP Memory Leak

### ISSUE THREAD

**Issue by FrogsLegs** [PrismLibrary/Prism#1725]
### Description
Bug: Memory leak in a Prism.Unity UWP App when navigating to a page and back again.
When navigating between pages inside a very basic app memory consumption always increases, it would appear memory is not released from the current page when navigating back using `GoBackAsync`.

### Steps to Reproduce

1. Create new UWP app, Add Prism.Windows and Prism.Unity.Windows NuGet Packages
2. Add two Views / ViewModels
3. Use `INavigationService.NavigateAsync` in Page1, use `INavigationService.GoBackAsync` in Page2
4. Cycle between the pages 

### Expected Behavior
Memory from page2 is released and collected by the GC when using `GoBacyAsync` to Page1

### Actual Behavior
Memory consumption increases with each cycle of Page1 -> Page 2 and Page2 <- Page1

### Basic Information
Attached a repro demonstrating the issue, sample code taken from the HelloWorld application.

- Version with issue: 7.2.0.1038-pre
- IDE: VisualStudio Pro 2017

### Screenshots

![image](https://user-images.githubusercontent.com/5354915/53690160-2136c080-3d5d-11e9-9794-fde9b7d16a6f.png)

### Reproduction Link
[App2.zip](https://github.com/PrismLibrary/Prism/files/2922699/App2.zip)

**Comment by FrogsLegs** [comment]
Some further testing on this issue, if we set each pages `NavigationCacheMode` to `Required`, is appears to be resolved. Memory is correctly freed up by the GC. I would suggest this issue is therefore not a bug of the Prism library but within the UWP Framework itself.

**Comment by bartlannoeye** [comment]
Thanks for the repro, we'll take this up with the Windows team.
