### ISSUE TITLE
There is not a project template for Xamarin.Forms Shared Project

### ISSUE THREAD

**Issue by yanshouwang** [PrismLibrary/Prism#1727]
Hi, why there is not a project template for Xamarin.Forms when use a shared project? Recently I found that maybe the shared project is better for me but Prism has no template for it so I have to add views and viewmodels and register them into container myself, will Prism teams provide it in the future?
Thank you!

**Comment by dansiegel** [comment]
@yanshouwang you are correct we do not provide a template that uses a Shared Project. This leads developers to make bad design decisions and write hard to maintain apps... something we have no intention of encouraging.
