### ISSUE TITLE
Do not understand how to save view state

### ISSUE THREAD

**Issue by CuteGridView** [PrismLibrary/Prism#173]
Hello. I am trying to port my Windows 8.1 prism app to UWP(using prerelease Prism 6 packages). I do not understand how to save view state(stuff like scrollviewer position). In WinRT Prism I used SaveState and LoadState methods, but Prism 6 does not have VisualStateAwarePage which contains these methods.

**Comment by tomzorz** [comment]
Check the breaking changes in the readme :) >> "Visual State management parts of VisualStateAwarePage were removed and it is now renamed to SessionStateAwarePage."

**Comment by CuteGridView** [comment]
I tried to save ScrollViewer’s scroll position using code from this blog post http://www.davidbritch.com/2014/03/capturing-and-setting-scrollviewers.html . The problem is that it does not restore correctly, after restoring scroll position is around 160 effective pixels higher than it should be. Is there a recommended prism way of saving scroll position?

**Comment by brianlagunas** [comment]
Please post your question here:  http://stackoverflow.com/questions/tagged/prism
