### ISSUE TITLE
.net core 3.0, "ReflectionOnly loading is not supported on this platform."

### ISSUE THREAD

**Issue by jherby2k** [PrismLibrary/Prism#1732]
### Description

You're probably well aware of this limitation, but I thought i'd log an issue since I can't find one.

I'm unable to dynamically load modules using a DirectoryModuleCatalog under .NET Core 3.0. It throws the exception `System.PlatformNotSupportedException: 'ReflectionOnly loading is not supported on this platform.'`

### Steps to Reproduce

1. Create a new .NET Core 3.0 WPF application
2. override the CreateModuleCatalog method in App.xaml.cs
3. Return a new DirectoryModuleCatalog.

### Expected Behavior

1. Load the modules without issue. .NET Core apps need to use System.Runtime.Loader to resolve assemblies, but all the same stuff should be doable.

### Actual Behavior

Said exception

### Basic Information

- Version with issue: 7.2.0.1038-pre
- Last known good version: N/A
- IDE: Visual Studio 2019 RC1

### Reproduction Link

If you really need a repro i'll supply one, but this is pretty trivial to reproduce.

**Comment by jherby2k** [comment]
Just saw your post about stepping back from OSS. That's cool! Thanks for all your hard work. Hopefully you'll take a PR for this.

**Comment by dansiegel** [comment]
@jherby2k I'm sure that it is trivial to reproduce... if you could please provide a repro that would be helpful though. Our time is really quite limited so having something that demonstrates the reported issue helps us to both validate and prioritize issues.

**Comment by Grompot77** [comment]
I just ran into the exact same issue, when looking at the code on github, it is using the AppDomain.  If there is a different branch, it might be different.  But AppDomain has been deprecated and Microsoft is no longer developing it.  

PS: Producing it with the latest ci build from myget

**Comment by Grompot77** [comment]
sorry, it is a bit ugly, could not spend more time analysing the MetadataLoadContext, but this is a quick hack that works, this to watch out for is the this.GetType().Assembly.  I was doing it in the running context.  And there is a bit of hardcoding for the directory, all this are modified excerpts from the existing code base.

`
AssemblyLoadContext ctx = AssemblyLoadContext.GetLoadContext(this.GetType().Assembly);
DirectoryInfo directory = new DirectoryInfo(".\\Modules");
var alreadyLoadedAssemblies = ctx.Assemblies;
var fileInfos = directory.GetFiles("*.dll")
        .Where(file => alreadyLoadedAssemblies
                            .FirstOrDefault(
                            assembly =>
                            String.Compare(Path.GetFileName(assembly.Location), file.Name,
                                            StringComparison.OrdinalIgnoreCase) == 0) == null);
List<Assembly> validAssemblies = new List<Assembly>();
foreach (FileInfo fileInfo in fileInfos)
{
    try
    {
        var assembly = ctx.LoadFromAssemblyPath(fileInfo.FullName);
        validAssemblies.Add(assembly);
    }
    catch (BadImageFormatException)
    {
        // skip non-.NET Dlls
    }
}

var vasf = validAssemblies.SelectMany(f => f.GetTypes())
    .Where(v => {
        var b = typeof(IModule).IsAssignableFrom(v);
        return false;
        }).ToList();

var vasft = validAssemblies
    .Where(t => t.GetType() != typeof(IModule) && !t.GetType().IsAbstract);

var vss = validAssemblies.SelectMany(a => a.GetTypes())
    .Where(v => typeof(IModule).IsAssignableFrom(v))
    .Where(t => t != typeof(IModule) && !t.IsAbstract)
    .Select(type => CreateModuleInfo(type)).ToList();


var moduleCatalog = base.CreateModuleCatalog();
vss.ForEach(c => moduleCatalog.AddModule(c));
return moduleCatalog;
`

**Comment by Grompot77** [comment]
The DirectoryModuleCatalog just need these changes, for testing I just added it in-line with the override IModuleCatalog CreateModuleCatalog(), bit easier to step through

**Comment by apwwn** [comment]
So, there is a way to do it. Fell free to comment this approach.

**Comment by Grompot77** [comment]
I have reworked the DirectoryModuleCatalog, sorry, did not pull a branch and the test cases are out of date as well, added comments to the changes:

    /// <summary>
    /// Represets a catalog created from a directory on disk.
    /// </summary>
    /// <remarks>
    /// The directory catalog will scan the contents of a directory, locating classes that implement
    /// <see cref="IModule"/> and add them to the catalog based on contents in their associated <see cref="ModuleAttribute"/>.
    /// Assemblies are loaded into a new application domain with ReflectionOnlyLoad.  The application domain is destroyed
    /// once the assemblies have been discovered.
    ///
    /// The diretory catalog does not continue to monitor the directory after it has created the initialze catalog.
    /// </remarks>
    public class DirectoryModuleCatalog : ModuleCatalog
    {
        /// <summary>
        /// Directory containing modules to search for.
        /// </summary>
        public string ModulePath { get; set; }

        /// <summary>
        /// Drives the main logic of building the child domain and searching for the assemblies.
        /// </summary>
        protected override void InnerLoad()
        {
            //if (string.IsNullOrEmpty(this.ModulePath))
            //    throw new InvalidOperationException(Resources.ModulePathCannotBeNullOrEmpty);

            //if (!Directory.Exists(this.ModulePath))
            //    throw new InvalidOperationException(
            //        string.Format(CultureInfo.CurrentCulture, Resources.DirectoryNotFound, this.ModulePath));
#if NETCOREAPP3_0
            AppDomain childDomain = AppDomain.CurrentDomain;
#else
            AppDomain childDomain = this.BuildChildDomain(AppDomain.CurrentDomain);
#endif

            try
            {
                List<string> loadedAssemblies = new List<string>();

                var assemblies = (
                                     from Assembly assembly in AppDomain.CurrentDomain.GetAssemblies()
                                     where !(assembly is System.Reflection.Emit.AssemblyBuilder)
                                        && assembly.GetType().FullName != "System.Reflection.Emit.InternalAssemblyBuilder"
                                        && !String.IsNullOrEmpty(assembly.Location)
                                     select assembly.Location
                                 );

                loadedAssemblies.AddRange(assemblies);

                Type loaderType = typeof(InnerModuleInfoLoader);

                if (loaderType.Assembly != null)
                {
                    var loader =
                        (InnerModuleInfoLoader)
                        childDomain.CreateInstanceFrom(loaderType.Assembly.Location, loaderType.FullName).Unwrap();
#if NET45 //ajb: no need to load the assemblies if in netcore, since we are using the AppDomain.CurrentDomain and ReflectionOnlyLoadFrom is not platform implemented
                    loader.LoadAssemblies(loadedAssemblies);
#endif
                    this.Items.AddRange(loader.GetModuleInfos(this.ModulePath));
                }
            }
            finally
            {
#if NET45
                AppDomain.Unload(childDomain);
#endif
            }
        }

#if NET45
        /// <summary>
        /// Creates a new child domain and copies the evidence from a parent domain.
        /// </summary>
        /// <param name="parentDomain">The parent domain.</param>
        /// <returns>The new child domain.</returns>
        /// <remarks>
        /// Grabs the <paramref name="parentDomain"/> evidence and uses it to construct the new
        /// <see cref="AppDomain"/> because in a ClickOnce execution environment, creating an
        /// <see cref="AppDomain"/> will by default pick up the partial trust environment of
        /// the AppLaunch.exe, which was the root executable. The AppLaunch.exe does a
        /// create domain and applies the evidence from the ClickOnce manifests to
        /// create the domain that the application is actually executing in. This will
        /// need to be Full Trust for Prism applications.
        /// </remarks>
        /// <exception cref="ArgumentNullException">An <see cref="ArgumentNullException"/> is thrown if <paramref name="parentDomain"/> is null.</exception>
        protected virtual AppDomain BuildChildDomain(AppDomain parentDomain)
        {
            if (parentDomain == null)
                throw new ArgumentNullException(nameof(parentDomain));

            Evidence evidence = new Evidence(parentDomain.Evidence);
            AppDomainSetup setup = parentDomain.SetupInformation;
            return AppDomain.CreateDomain("DiscoveryRegion", evidence, setup);
        }
#endif

        private class InnerModuleInfoLoader : MarshalByRefObject
        {
            [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic")]
            internal ModuleInfo[] GetModuleInfos(string path)
            {
                DirectoryInfo directory = new DirectoryInfo(path);

                ResolveEventHandler resolveEventHandler =
                    delegate (object sender, ResolveEventArgs args) { return OnReflectionOnlyResolve(args, directory); };

                AppDomain.CurrentDomain.ReflectionOnlyAssemblyResolve += resolveEventHandler;

                //ajb: again, we work with the GetAssemblies for the loaded appdomain context
                Assembly moduleReflectionOnlyAssembly =
                    AppDomain.CurrentDomain
#if NETCOREAPP3_0
                    .GetAssemblies()
#else
                    .ReflectionOnlyGetAssemblies()
#endif
                    .First(asm => asm.FullName == typeof(IModule).Assembly.FullName);
                Type IModuleType = moduleReflectionOnlyAssembly.GetType(typeof(IModule).FullName);

                IEnumerable<ModuleInfo> modules = GetNotAllreadyLoadedModuleInfos(directory, IModuleType);

                var array = modules.ToArray();
                AppDomain.CurrentDomain.ReflectionOnlyAssemblyResolve -= resolveEventHandler;
                return array;
            }

            private static IEnumerable<ModuleInfo> GetNotAllreadyLoadedModuleInfos(DirectoryInfo directory, Type IModuleType)
            {
                //ajb: had to change the temp list to assembly type, it is required for the return select
                //List<FileInfo> validAssemblies = new List<FileInfo>();
                List<Assembly> validAssemblies = new List<Assembly>();
                //ajb: changed to use GetAssemblies with conditional build, exclude where assemblies are IsDynamic for fileInfos will fail
                Assembly[] alreadyLoadedAssemblies = AppDomain.CurrentDomain
#if NETCOREAPP3_0
                    .GetAssemblies().Where(p => !p.IsDynamic).ToArray();
#else
                    .ReflectionOnlyGetAssemblies();
#endif

                var fileInfos = directory.GetFiles("*.dll")
                    .Where(file => alreadyLoadedAssemblies
                                       .FirstOrDefault(
                                       assembly =>
                                       String.Compare(Path.GetFileName(assembly.Location), file.Name,
                                                      StringComparison.OrdinalIgnoreCase) == 0) == null).ToList();

                foreach (FileInfo fileInfo in fileInfos)
                {
                    try
                    {
                        //ajb: add to new collection inline
                        //Assembly.ReflectionOnlyLoadFrom(fileInfo.FullName);
                        validAssemblies.Add(
#if NETCOREAPP3_0
                        Assembly.LoadFrom(fileInfo.FullName)
#else
                        Assembly.ReflectionOnlyLoadFrom(fileInfo.FullName)
#endif
                            );
                        //validAssemblies.Add(fileInfo);
                    }
                    catch (BadImageFormatException)
                    {
                        // skip non-.NET Dlls
                    }
                }

                //ajb: changed to use the new temp collection
                return validAssemblies.SelectMany(assembly => assembly
                            .GetExportedTypes()
                            .Where(IModuleType.IsAssignableFrom)
                            .Where(t => t != IModuleType)
                            .Where(t => !t.IsAbstract)
                            .Select(type => CreateModuleInfo(type)));

                //return validAssemblies.SelectMany(file => Assembly
                //                            .ReflectionOnlyLoadFrom(file.FullName)
                //                            .GetExportedTypes()
                //                            .Where(IModuleType.IsAssignableFrom)
                //                            .Where(t => t != IModuleType)
                //                            .Where(t => !t.IsAbstract)
                //                            .Select(type => CreateModuleInfo(type)));
            }

            private static Assembly OnReflectionOnlyResolve(ResolveEventArgs args, DirectoryInfo directory)
            {
                Assembly loadedAssembly = AppDomain.CurrentDomain.ReflectionOnlyGetAssemblies().FirstOrDefault(
                    asm => string.Equals(asm.FullName, args.Name, StringComparison.OrdinalIgnoreCase));
                if (loadedAssembly != null)
                {
                    return loadedAssembly;
                }
                AssemblyName assemblyName = new AssemblyName(args.Name);
                string dependentAssemblyFilename = Path.Combine(directory.FullName, assemblyName.Name + ".dll");
                if (File.Exists(dependentAssemblyFilename))
                {
                    return Assembly.ReflectionOnlyLoadFrom(dependentAssemblyFilename);
                }
                return Assembly.ReflectionOnlyLoad(args.Name);
            }

            [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic")]
            internal void LoadAssemblies(IEnumerable<string> assemblies)
            {
                foreach (string assemblyPath in assemblies)
                {
                    try
                    {
                        Assembly.ReflectionOnlyLoadFrom(assemblyPath);
                    }
                    catch (FileNotFoundException)
                    {
                        // Continue loading assemblies even if an assembly can not be loaded in the new AppDomain
                    }
                }
            }

            private static ModuleInfo CreateModuleInfo(Type type)
            {
                string moduleName = type.Name;
                List<string> dependsOn = new List<string>();
                bool onDemand = false;
                var moduleAttribute =
                    CustomAttributeData.GetCustomAttributes(type).FirstOrDefault(
                        cad => cad.Constructor.DeclaringType.FullName == typeof(ModuleAttribute).FullName);

                if (moduleAttribute != null)
                {
                    foreach (CustomAttributeNamedArgument argument in moduleAttribute.NamedArguments)
                    {
                        string argumentName = argument.MemberInfo.Name;
                        switch (argumentName)
                        {
                            case "ModuleName":
                                moduleName = (string)argument.TypedValue.Value;
                                break;

                            case "OnDemand":
                                onDemand = (bool)argument.TypedValue.Value;
                                break;

                            case "StartupLoaded":
                                onDemand = !((bool)argument.TypedValue.Value);
                                break;
                        }
                    }
                }

                var moduleDependencyAttributes =
                    CustomAttributeData.GetCustomAttributes(type).Where(
                        cad => cad.Constructor.DeclaringType.FullName == typeof(ModuleDependencyAttribute).FullName);

                foreach (CustomAttributeData cad in moduleDependencyAttributes)
                {
                    dependsOn.Add((string)cad.ConstructorArguments[0].Value);
                }

                ModuleInfo moduleInfo = new ModuleInfo(moduleName, type.AssemblyQualifiedName)
                {
                    InitializationMode =
                                                    onDemand
                                                        ? InitializationMode.OnDemand
                                                        : InitializationMode.WhenAvailable,
                    Ref = type.Assembly.EscapedCodeBase,
                };
                moduleInfo.DependsOn.AddRange(dependsOn);
                return moduleInfo;
            }
        }
    }

**Comment by Grompot77** [comment]
Do not think TypeLoading is the way to go now, the AppDomain.CurrentDomain.ReflectionOnlyGetAssemblies is still not supported.  Also reviewed the github code, it is always and empty array, so no luck using it.

**Comment by Grompot77** [comment]
/// <summary>
    /// Represets a catalog created from a directory on disk.
    /// </summary>
    /// <remarks>
    /// The directory catalog will scan the contents of a directory, locating classes that implement
    /// <see cref="IModule"/> and add them to the catalog based on contents in their associated <see cref="ModuleAttribute"/>.
    /// Assemblies are loaded into a new application domain with ReflectionOnlyLoad.  The application domain is destroyed
    /// once the assemblies have been discovered.
    ///
    /// The diretory catalog does not continue to monitor the directory after it has created the initialze catalog.
    /// </remarks>
    public class DirectoryModuleCatalog : ModuleCatalog
    {
        /// <summary>
        /// Directory containing modules to search for.
        /// </summary>
        public string ModulePath { get; set; }

        /// <summary>
        /// Drives the main logic of building the child domain and searching for the assemblies.
        /// </summary>
        protected override void InnerLoad()
        {
            //if (string.IsNullOrEmpty(this.ModulePath))
            //    throw new InvalidOperationException(Resources.ModulePathCannotBeNullOrEmpty);

            //if (!Directory.Exists(this.ModulePath))
            //    throw new InvalidOperationException(
            //        string.Format(CultureInfo.CurrentCulture, Resources.DirectoryNotFound, this.ModulePath));
#if NETCOREAPP3_0
            AppDomain childDomain = AppDomain.CurrentDomain;
#else
            AppDomain childDomain = this.BuildChildDomain(AppDomain.CurrentDomain);
#endif

            try
            {
                List<string> loadedAssemblies = new List<string>();

                var assemblies = (
                                     from Assembly assembly in AppDomain.CurrentDomain.GetAssemblies()
                                     where !(assembly is System.Reflection.Emit.AssemblyBuilder)
                                        && assembly.GetType().FullName != "System.Reflection.Emit.InternalAssemblyBuilder"
                                        && !String.IsNullOrEmpty(assembly.Location)
                                     select assembly.Location
                                 );

                loadedAssemblies.AddRange(assemblies);

                Type loaderType = typeof(InnerModuleInfoLoader);

                if (loaderType.Assembly != null)
                {
                    var loader =
                        (InnerModuleInfoLoader)
                        childDomain.CreateInstanceFrom(loaderType.Assembly.Location, loaderType.FullName).Unwrap();
#if NET45 //ajb: no need to load the assemblies if in netcore, since we are using the AppDomain.CurrentDomain and ReflectionOnlyLoadFrom is not platform implemented
                    loader.LoadAssemblies(loadedAssemblies);
#endif
                    this.Items.AddRange(loader.GetModuleInfos(this.ModulePath));
                }
            }
            finally
            {
#if NET45
                AppDomain.Unload(childDomain);
#endif
            }
        }

#if NET45
        /// <summary>
        /// Creates a new child domain and copies the evidence from a parent domain.
        /// </summary>
        /// <param name="parentDomain">The parent domain.</param>
        /// <returns>The new child domain.</returns>
        /// <remarks>
        /// Grabs the <paramref name="parentDomain"/> evidence and uses it to construct the new
        /// <see cref="AppDomain"/> because in a ClickOnce execution environment, creating an
        /// <see cref="AppDomain"/> will by default pick up the partial trust environment of
        /// the AppLaunch.exe, which was the root executable. The AppLaunch.exe does a
        /// create domain and applies the evidence from the ClickOnce manifests to
        /// create the domain that the application is actually executing in. This will
        /// need to be Full Trust for Prism applications.
        /// </remarks>
        /// <exception cref="ArgumentNullException">An <see cref="ArgumentNullException"/> is thrown if <paramref name="parentDomain"/> is null.</exception>
        protected virtual AppDomain BuildChildDomain(AppDomain parentDomain)
        {
            if (parentDomain == null)
                throw new ArgumentNullException(nameof(parentDomain));

            Evidence evidence = new Evidence(parentDomain.Evidence);
            AppDomainSetup setup = parentDomain.SetupInformation;
            return AppDomain.CreateDomain("DiscoveryRegion", evidence, setup);
        }
#endif

        private class InnerModuleInfoLoader : MarshalByRefObject
        {
            [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic")]
            internal ModuleInfo[] GetModuleInfos(string path)
            {
                DirectoryInfo directory = new DirectoryInfo(path);

                ResolveEventHandler resolveEventHandler =
                    delegate (object sender, ResolveEventArgs args) { return OnReflectionOnlyResolve(args, directory); };

                AppDomain.CurrentDomain.ReflectionOnlyAssemblyResolve += resolveEventHandler;

                //ajb: again, we work with the GetAssemblies for the loaded appdomain context
                Assembly moduleReflectionOnlyAssembly =
                    AppDomain.CurrentDomain
#if NETCOREAPP3_0
                    .GetAssemblies()
#else
                    .ReflectionOnlyGetAssemblies()
#endif
                    .First(asm => asm.FullName == typeof(IModule).Assembly.FullName);
                Type IModuleType = moduleReflectionOnlyAssembly.GetType(typeof(IModule).FullName);

                IEnumerable<ModuleInfo> modules = GetNotAllreadyLoadedModuleInfos(directory, IModuleType);

                var array = modules.ToArray();
                AppDomain.CurrentDomain.ReflectionOnlyAssemblyResolve -= resolveEventHandler;
                return array;
            }

            private static IEnumerable<ModuleInfo> GetNotAllreadyLoadedModuleInfos(DirectoryInfo directory, Type IModuleType)
            {
                //ajb: had to change the temp list to assembly type, it is required for the return select
                //List<FileInfo> validAssemblies = new List<FileInfo>();
                List<Assembly> validAssemblies = new List<Assembly>();
                //ajb: changed to use GetAssemblies with conditional build, exclude where assemblies are IsDynamic for fileInfos will fail
                Assembly[] alreadyLoadedAssemblies = AppDomain.CurrentDomain
#if NETCOREAPP3_0
                    .GetAssemblies().Where(p => !p.IsDynamic).ToArray();
#else
                    .ReflectionOnlyGetAssemblies();
#endif

                var fileInfos = directory.GetFiles("*.dll")
                    .Where(file => alreadyLoadedAssemblies
                                       .FirstOrDefault(
                                       assembly =>
                                       String.Compare(Path.GetFileName(assembly.Location), file.Name,
                                                      StringComparison.OrdinalIgnoreCase) == 0) == null).ToList();

                foreach (FileInfo fileInfo in fileInfos)
                {
                    try
                    {
                        //ajb: add to new collection inline
                        //Assembly.ReflectionOnlyLoadFrom(fileInfo.FullName);
                        validAssemblies.Add(
#if NETCOREAPP3_0
                        Assembly.LoadFrom(fileInfo.FullName)
#else
                        Assembly.ReflectionOnlyLoadFrom(fileInfo.FullName)
#endif
                            );
                        //validAssemblies.Add(fileInfo);
                    }
                    catch (BadImageFormatException)
                    {
                        // skip non-.NET Dlls
                    }
                }

                //ajb: changed to use the new temp collection
                return validAssemblies.SelectMany(assembly => assembly
                            .GetExportedTypes()
                            .Where(IModuleType.IsAssignableFrom)
                            .Where(t => t != IModuleType)
                            .Where(t => !t.IsAbstract)
                            .Select(type => CreateModuleInfo(type)));

                //return validAssemblies.SelectMany(file => Assembly
                //                            .ReflectionOnlyLoadFrom(file.FullName)
                //                            .GetExportedTypes()
                //                            .Where(IModuleType.IsAssignableFrom)
                //                            .Where(t => t != IModuleType)
                //                            .Where(t => !t.IsAbstract)
                //                            .Select(type => CreateModuleInfo(type)));
            }

            private static Assembly OnReflectionOnlyResolve(ResolveEventArgs args, DirectoryInfo directory)
            {
                Assembly loadedAssembly = AppDomain.CurrentDomain.ReflectionOnlyGetAssemblies().FirstOrDefault(
                    asm => string.Equals(asm.FullName, args.Name, StringComparison.OrdinalIgnoreCase));
                if (loadedAssembly != null)
                {
                    return loadedAssembly;
                }
                AssemblyName assemblyName = new AssemblyName(args.Name);
                string dependentAssemblyFilename = Path.Combine(directory.FullName, assemblyName.Name + ".dll");
                if (File.Exists(dependentAssemblyFilename))
                {
                    return Assembly.ReflectionOnlyLoadFrom(dependentAssemblyFilename);
                }
                return Assembly.ReflectionOnlyLoad(args.Name);
            }

            [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic")]
            internal void LoadAssemblies(IEnumerable<string> assemblies)
            {
                foreach (string assemblyPath in assemblies)
                {
                    try
                    {
                        Assembly.ReflectionOnlyLoadFrom(assemblyPath);
                    }
                    catch (FileNotFoundException)
                    {
                        // Continue loading assemblies even if an assembly can not be loaded in the new AppDomain
                    }
                }
            }

            private static ModuleInfo CreateModuleInfo(Type type)
            {
                string moduleName = type.Name;
                List<string> dependsOn = new List<string>();
                bool onDemand = false;
                var moduleAttribute =
                    CustomAttributeData.GetCustomAttributes(type).FirstOrDefault(
                        cad => cad.Constructor.DeclaringType.FullName == typeof(ModuleAttribute).FullName);

                if (moduleAttribute != null)
                {
                    foreach (CustomAttributeNamedArgument argument in moduleAttribute.NamedArguments)
                    {
                        string argumentName = argument.MemberInfo.Name;
                        switch (argumentName)
                        {
                            case "ModuleName":
                                moduleName = (string)argument.TypedValue.Value;
                                break;

                            case "OnDemand":
                                onDemand = (bool)argument.TypedValue.Value;
                                break;

                            case "StartupLoaded":
                                onDemand = !((bool)argument.TypedValue.Value);
                                break;
                        }
                    }
                }

                var moduleDependencyAttributes =
                    CustomAttributeData.GetCustomAttributes(type).Where(
                        cad => cad.Constructor.DeclaringType.FullName == typeof(ModuleDependencyAttribute).FullName);

                foreach (CustomAttributeData cad in moduleDependencyAttributes)
                {
                    dependsOn.Add((string)cad.ConstructorArguments[0].Value);
                }

                ModuleInfo moduleInfo = new ModuleInfo(moduleName, type.AssemblyQualifiedName)
                {
                    InitializationMode =
                                                    onDemand
                                                        ? InitializationMode.OnDemand
                                                        : InitializationMode.WhenAvailable,
                    Ref = type.Assembly.EscapedCodeBase,
                };
                moduleInfo.DependsOn.AddRange(dependsOn);
                return moduleInfo;
            }
        }
    }

**Comment by Grompot77** [comment]
@brianlagunas the above does not look pretty, just how the posting works, but this is working

**Comment by Grompot77** [comment]
pushed it, https://github.com/Grompot77/Prism/blob/master/Source/Wpf/Prism.Wpf/Modularity/DirectoryModuleCatalog.Desktop.cs

**Comment by brianlagunas** [comment]
Thanks, I'll check it out.

**Comment by Grompot77** [comment]
Cool, I got my old PrioritizedWatchDirectoryModuleCatalog working as well, it has a filewatcher with a priority loading construct 👍

**Comment by jherby2k** [comment]
I haven't had time to investigate this - thanks for working on it! I get the impression https://docs.microsoft.com/en-us/dotnet/core/whats-new/dotnet-core-3-0#type-metadataloadcontext is the new way of doing things without loading into an appdomain.

**Comment by Grompot77** [comment]
Thanks for all the work, remember that the changes being made has to "fit" both full and core stack, just doing it for core is not good enough IMHO.  Might need to incorporate the change to have a conditional build switch and build 2x packages.  Another way is to run a PrismCore project that has linked files for common work and only make new files where the core does not support the old full stack work.

**Comment by apwwn** [comment]
I think, and it's only my opinion, it will be a mandatory to update to netstandard2.0 at least to be able to maintain a full framework and a netcore version without to much work.

for the work I've done, it's only to unblock guys on netcore who have the same problem than me with the module directory loader and I totally understand that will not be merge on prism now (or never), I'm fine with that :)

**Comment by brianlagunas** [comment]
The approach to take here is to have two different implementations. One for .NET and one for .NET Core.

**Comment by brianlagunas** [comment]
I used @Grompot77 code in a .NET Core 3 version of the DirectoryModuleCatalog with PR #1828.  Please test it out in the latest nightly build on MyGet in about 30 minutes.

**Comment by Grompot77** [comment]
Thanks @brianlagunas , I will test it out as soon as I can.  On a personal note, I think we should create a branch for the .net core work.  I will try and see how much I can port for the MS DI work through some middleware registration in the ServicesCollection.  My feeling is to have it registered, eg services.AddPrism which will wire up Prism modules.  Let me know what you think.
