### ISSUE TITLE
Nakitta

### ISSUE THREAD

**Issue by Nakitta** [PrismLibrary/Prism#1734]
### Steps to Reproduce

1. 
2. 
3. 

### Basic Information

- Version with issue:
- Last known good version:
- Xamarin.Forms version:
- IDE:

**Comment by bartlannoeye** [comment]
I don't spot a question in here.

**Comment by thinzarhtet** [comment]
Nakita@gmail.com

**Comment by Nakitta** [comment]
https://github.com/PrismLibrary/Prism/issues/1734#issuecomment-471896021
