### ISSUE TITLE
[XF] Issue with navigation service after navigating back

### ISSUE THREAD

**Issue by ddomengeaux** [PrismLibrary/Prism#1738]
### Description

Have an app with a nested navigation stack. On first run everything works correctly. Once you navigate back (via navigation bar back button) you are unable to navigate forward again. Navigation service returns a success result but navigation never actually occurs. Reverting back to 7.1.0.431 works correctly.

### Steps to Reproduce

1. Create blank prism application.
2. Add two pages
3. Have them navigate MainPage > ViewA > ViewB
4. Navigate Back from ViewB > ViewA and you can no longer navigate to ViewB

### Expected Behavior
ViewB should load as expected

### Actual Behavior
After first back navigation back navigation stack fails to work.

### Basic Information

- Version with issue: 7.2.0.1038-pre
- Last known good version: 7.1.0.431 
- Xamarin.Forms version: 3.6.0.220655
- IDE: Visual Studio for Mac 7.8.3 (build 2)

### Reproduction Link

https://github.com/ddomengeaux/NavigationBug

**Comment by brianlagunas** [comment]
Unable to verify. Works on my machine :)

![works-for-me](https://user-images.githubusercontent.com/835562/55364353-918c4b00-549d-11e9-823c-aec149a999b1.gif)
