### ISSUE TITLE
Error: No property, bindable property, or event found for 'UseModalNavigation'

### ISSUE THREAD

**Issue by patricksegantine** [PrismLibrary/Prism#1739]
### Description

Error: No property, bindable property, or event found for 'UseModalNavigation', or mismatching type between value and property.

### Steps to Reproduce

1. add in source code:  xmlns:nav="clr-namespace:Prism.Navigation.Xaml;assembly=Prism.Forms"
2. start the compile
3. view error list window

### Expected Behavior
Run app with UseModalNavigation parameter in Xaml prism navigation

### Actual Behavior
Error when start the compile

### Basic Information

- Version with issue: Prism.DryIoc.Forms 7.1.0.431
- Last known good version: NA
- Xamarin.Forms version: 3.6.0.220655
- IDE: VS 2017 15.9.7

### Screenshots
https://github.com/patricksegantine/issues/blob/master/PrismLibrary/UseModalNavigation/01.png
https://github.com/patricksegantine/issues/blob/master/PrismLibrary/UseModalNavigation/02.png
https://github.com/patricksegantine/issues/blob/master/PrismLibrary/UseModalNavigation/03.png

**Comment by dansiegel** [comment]
This feature was added more recently. Please update to the latest preview of 7.2
