### ISSUE TITLE
Question: Xamarin.Forms : Shell with modularity  

### ISSUE THREAD

**Issue by ahmad-crossplatform** [PrismLibrary/Prism#1741]
I have a question regarding  Shell App with Modularity . 
in the recent Prism Template Pack for VSMac , I found the option of **Prism Forms Module + Shell App** 
[Click to view ](https://postimg.cc/TLk82TXB)
However when  proceed with that I get an error regarding app icon missing , my question is that what should this do ? and do you guys have an exmaple of using the modularity with shell ?

**Comment by scharada** [comment]
is that the link ???? why would you post such a thing ?

**Comment by ahmad-crossplatform** [comment]
Hello , I have updated my question , I did not know how to post an image with markdown .
