### ISSUE TITLE
Prism Template Pack missing WPF ItemTemplates

### ISSUE THREAD

**Issue by fileman** [PrismLibrary/Prism#1742]
### Description
In .net core 3 WPF window and usercontrol ItemTemplates are missed.

### Steps to Reproduce

1. Create VS 2019 RC WPF .net core 3 proj
2. Add -> New item -> Prism

### Expected Behavior
Find WPF window and usercontrol with viewmodel, as mentioned [here](https://marketplace.visualstudio.com/items?itemName=BrianLagunas.PrismTemplatePack#overview)

### Actual Behavior
Empty WPF folder

### Basic Information

- Version with issue: 2.1.4
- Last known good version: .net framework 
- IDE: Visual Studio 2019 RC

### Screenshots

![image](https://user-images.githubusercontent.com/17230763/54562836-140a0a80-49c8-11e9-81fb-24d723c0df5f.png)

**Comment by fileman** [comment]
I wanted to try to solve this problem, but I can't find the extension source code, is it available somewhere?

**Comment by brianlagunas** [comment]
The extension code is not open surce.

**Comment by brianlagunas** [comment]
fixed. the marketplace will be updated shortly
