### ISSUE TITLE
Question: How do I resolve errors after Prism.Unity NuGet update to 7.1.0.431 from 6.3.0?

### ISSUE THREAD

**Issue by myokeeh** [PrismLibrary/Prism#1743]
Is there any guidance available about addressing errors after updating Prism.Unity NuGet to 7.1.0.431? I have searched around to understand some of the history and how to resolve this, but can't figure this out. This is in context to using it with an app generated using Windows Template Studio.

Originally posted below, but redirected to ask here instead: 
https://github.com/Microsoft/WindowsTemplateStudio/issues/3022

**Comment by bartlannoeye** [comment]
Windows Template Studio uses Prism.Windows 6.3 and Prism.Unity 6.3. We don't have a stable 7.x release yet for Prism.Windows, so you have to stick with Prism.Unity 6.3 for now. The 7.1 version is not compatible with Prism.Windows 6.3.

You could try the prerelease packages for Prism.Windows, but since we're still changing that library, you might have to update your app twice.

**Comment by myokeeh** [comment]
@bartlannoeye I've tried updating to Prism.Unity to 7.2.0.1038-pre and installed Prism.Windows 7.2.0.1038-pre, too. Not Prism.Unity.Windows? You seem to imply that I should be able to get to a an app that builds even with the pre-release versions above. Is that right? I'm still getting a bunch of "does not exist in current context/namespace" errors that I can't seem to point in the right library/namespace. Is that expected?

**Comment by bartlannoeye** [comment]
As I mentioned, there are **breaking** changes. You could get an app working with the preview builds, but you will have to change parts of your codebase (cfr the 'does not exist'). We can't promise there won't be more breaking changes between now and the final 7.x release.

**Comment by myokeeh** [comment]
@bartlannoeye. I understand there are breaking changes, and okay with that. I'm new to this and trying to understand current state and where this is heading. Thanks.
