### ISSUE TITLE
Getting an error when selecting Prism Forms Module + Shell App from VS Mac 2017

### ISSUE THREAD

**Issue by ahmad-crossplatform** [PrismLibrary/Prism#1744]
### Description

I have a question regarding  Shell App with Modularity . 
in the recent Prism Template Pack for VSMac , I found the option of **Prism Forms Module + Shell App** 

![image](https://i.postimg.cc/nrxnkLSV/Screenshot-2019-03-18-at-14-15-56.png)

However when  proceed with that I get an error regarding missing mandatory params  

![image](https://i.postimg.cc/nhNNgDMz/Screenshot-2019-03-19-at-11-07-55.png)

What should this do ? and do you guys have an example of using the modularity with shell ? 

### Steps to Reproduce
Having visual studio for mac 2017 with Prism Template Pack installed
1.  Select Add new project
2.  Choose Modular tab
3.  Select Prism Forms Module + Shell App 
4. Fill the missing fields 
5. Click finish. 

### Expected Behavior
To get an solution based on Shell App  and has modularity in it . 
### Actual Behavior
receiving an error regarding missing mandatory params  

### Basic Information
- IDE: VS MAC 2017

### Screenshots

![image](https://i.postimg.cc/nhNNgDMz/Screenshot-2019-03-19-at-11-07-55.png)

**Comment by dansiegel** [comment]
this will be looked at as part of #1755
