### ISSUE TITLE
Change Request for DialogViewModelBase

### ISSUE THREAD

**Issue by AlexejLiebenthal** [PrismLibrary/Prism#1747]
First of all, thanks @brianlagunas for this new feature :+1: !!!

But as I came along with the `DialogViewModelBase`, I would have implemented the `IDialogAware` interface slightly different.
 
1. Make the class/command generic or accept `object`:
Like this objects and not only strings could be injected through the view for the closing action. This could be useful, if the command parameter has a binding to a selected item. This can then be added to the `IDialogResult.Parameters` and send back to the dialog caller.
2. Have a possibility to bind the `Title` property via convention through `IDialogParameters`.
3. Provide an abstract/virtual method, which has a return type of `IDialogResult`:
In all of the use cases I could imagine the last statement of `CloseDialog` would be `RaiseRequestClose(IDialogResult)`. So rather than let the user overwrite `CloseDialog` directly, it could be better to have a method like `protected virtual/abstract DialogResult OnClosing(T commandParameter)`, which is called in the than private `CloseDialog` method. Such a method  would also provide for me, a more natural way of dealing with dialogs, as I expect as a user to return some result in the end, rather than invoking an event.

I think understanding my concerns will be easier with some code :wink: :

```cs
   public /*abstract*/ class DialogViewModelBase<T> : BindableBase, IDialogAware
    {
        private DelegateCommand<T> _closeDialogCommand;
        public DelegateCommand<T> CloseDialogCommand =>
            _closeDialogCommand ?? (_closeDialogCommand = new DelegateCommand<T>(CloseDialog));

        private string _title;
        public string Title
        {
            get { return _title; }
            set { SetProperty(ref _title, value); }
        }

        public event Action<IDialogResult> RequestClose;

        private void CloseDialog(T commandParameter)
        {
            RaiseRequestClose(OnClosing(commandParameter));
        }

        protected virtual/*abstract*/ IDialogResult OnClosing(T commandParameter)
        {
            return new DialogResult(true);
        }

        public virtual void RaiseRequestClose(IDialogResult dialogResult)
        {
            RequestClose?.Invoke(dialogResult);
        }

        public virtual bool CanCloseDialog()
        {
            return true;
        }

        public virtual void OnDialogClosed()
        {

        }

        public virtual void OnDialogOpened(IDialogParameters parameters)
        {
            if (parameters.TryGetValue("title", out string title))
              Title = title;
        }
    }
```

**Comment by brianlagunas** [comment]
I think there are some good ideas in here. I am slammed right now with other priorities,, but give me some time to come back to this.

**Comment by brianlagunas** [comment]
My first thought is what if the command parameter type is not the same as the type to be checked for the result? I think it will be very common not to use the same parameter type, and in fact, pass a number of different parameters back in the result.  I also remember when writing this base VM that I need to keep it simple and not try to support/solve all the possibilities that could occur in a base VM. This is actually the very reason why I try not to support any type of base VM, because it can be done is so many different ways.

**Comment by AlexejLiebenthal** [comment]
> I think it will be very common not to use the same parameter type, and in fact, pass a number of different parameters back in the result.

Yes, indeed. But this should (or if abstract must) be done all in the `protected virtual/*abstract*/ IDialogResult OnClosing(T commandParameter)` method. So the user can create an `IDialogResult` by using/adding V/VM binded properties or the injected command parameter from the view or both or none of them to the `IDialogParamters`. This would also be the method, where I would implement some validator calls if needed.

> because it can be done is so many different ways.

With this statement you're damn right! I already struggling with the "right / best" implementation of two paths (Accept/Cancel), with the base model. For this you have already so many options: 
- Control it, like in your implementation, via the command parameter ("True", "False").
- Implement a second simple delegate command for the abort, which accepts no parameter and as action has `RaiseRequestClose(new DialogResult(false))`.
- ...

There is also a problem of the generic implementation, if you need more than one close command, I think it is usual, that on different close actions you may need different command parameter types. That's the reason why I also thinking in a more general way of using `object` instead of `T`. With this you can choose the closing path in the `OnClosing(object)` method and delegate to some methods the user needs to implement themselves. E.g. OnAcceptClosing(...) or OnCancelClosing(...).

I also really don't think, that this problem should be already solved in a BaseVM. It should only be open for all possible solutions.
And maybe a best practice/guidance/example should be provided as well.

**Comment by brianlagunas** [comment]
Hmmmm… maybe a base VM shouldn't even ship with Prism. This is why Prism never had a base VM to begin with. All that matters is the interface. That's what Prism looks for.

**Comment by AlexejLiebenthal** [comment]
> All that matters is the interface. That's what Prism looks for.

That's true 😉:

> I also really don't think, that this problem should be already solved in a BaseVM. It should only be open for all possible solutions.
> And maybe a best practice/guidance/example should be provided as well.

And what is more open in OO than an interface 😄. 
So I would agree, that the `DialogVMBase` really shouldn't be part of the next stable Prism release, as it can have so many different ways of implementing it, depending on the business needs, rather than `BindableBase` which is quite straightforward everytime. 

A good xmldoc for the interface plus comprehensive examples in [Prism-Samples-Wpf](https://github.com/PrismLibrary/Prism-Samples-Wpf), which will replace the old `INotification` and `InteractionRequest` stuff (25-28) should do the job in my opinion.

**Comment by brianlagunas** [comment]
done!
