### ISSUE TITLE
[Enhancement] Implement IInitialize (BREAKING)

### ISSUE THREAD

**Issue by dansiegel** [PrismLibrary/Prism#1748]
### Description

Following the poll results in #1724 and on Patreon, it appears that the community prefers a breaking change for an API that remains clearer in intent. 

- Twitter Results: 61% in favor of a breaking change
- Patreon Results: 80% in favor of a breaking change

The community has long requested an API that will allow both synchronous and asynchronous initialization of the ViewModel prior to the View being pushed onto the Navigation Stack. The intent of INavigatingAware.OnNavigatingTo was to fill this need, however was not clear that this was the intent and lead to the API getting called in other scenarios resulting in buggy behavior.

### Deprecated API

INavigatingAware will be marked as Obsolete and treated as an error in 7.2 and removed from INavigationAware in order to avoid forcing new apps to implement a deprecated API. This will likely be raised an a build error when used directly as INavigatingAware to force updates when explicitly used. When this has been used from INavigationAware the method will simply not be called.

### New API's

When you are able to initialize synchronously 

```cs
public interface IInitialize
{
    void OnInitialized(INavigationParameters parameters);
}
```

When you need to initialize asynchronously

```cs
public interface IInitializeAsync
{
    Task OnInitializedAsync(INavigationParameters parameters);
}
```

When you want to initialize by convention from the Navigation Parameters: issue #1746 

```cs
public interface IAutoInitialize
{
}

public class NavigationParameterAttribute : Attribute
{
    public string Name { get; }
    public bool IsRequired { get; }
}

public class SampleViewModel : IAutoInitialize
{
    // Will throw an ArgumentNullException for the Title Property 
    // if not passed in the NavigationParameters
    [NavigationParameter(true)]
    public string Title { get; set; }

    // Will be set by a Navigation Parameter named `ByConvention`
    // ignoring case, if it exists
    public string ByConvention { get; set; }

    // Will be set by a Navigation Parameter named `bar` ignoring case
    [NavigationParameter("bar")]
    public string Foo { get; set; }
}
```

**Comment by andreinitescu** [comment]
My feedback:

1. The naming `OnInitialized()` doesn't sound good to me. 

`OnInitialized` makes me think the target **was** initialized, not that it **should** initialize.  I think the purpose of the new interface `IInitialize`/`IInitializeAsync` is to tell target **it's time** to initialize itself, not that it **was** initialized. I suggest instead `Initialize`/`InitializeAsync`. Also, according to [this](https://docs.microsoft.com/en-us/dotnet/csharp/event-pattern) the `On` prefix is usually for virtual methods.

2, What's going to happen with INavigatedAware? Will it continue to have same OnNavigated? Why not also have Initialize too? Instead of having separate interfaces (INavigating/INavigated) why not have a single interface (IInitialize) with one method (Initialize) which has navigation parameters allowing to differentiate the navigation time it's called (navigating/navigated)

**Comment by djcparker** [comment]
I agree, the naming OnInitialized() doesn't sound right.   If this is "to perform the initialisation then naming it "Initialize()" would be better.

**Comment by brianlagunas** [comment]
I'm okay with `Initialize()`

**Comment by dansiegel** [comment]
@andreinitescu 

> the On prefix is usually for virtual methods.

Prism uses state of being verbs such as Is and On by convention. Since I cannot find one single use of the word virtual or even prefix on your link I'm not really sure how you feel that says .NET conventions would reserve the On state prefix for virtual methods. While I understand the argument for Initialize this would actually be contrary to our conventions.

That said I can understand that use of the 'ed' tense suggests that the initialization already occurred. What I think may instead be a better suited name would be `OnInitializing` as this conveys a current state of initialization and actually fits within our existing conventions.

> What's going to happen with INavigatedAware?

Nothing is going to happen with INavigatedAware… there will have to be a breaking change with INavigationAware as we would have to either drop INavigatingAware from INavigationAware or force people to implement an obsolete method. After a lot of conversation on this @brianlagunas and I have decided that we will be dropping from INavigationAware. INavigatedAware however remains untouched.

**Comment by djcparker** [comment]
OnInitialising works. Plenty of examples of it in base .net 👍

**Comment by kronic** [comment]
Maybe 
```cs
public interface IInitialize
{
    bool TryOnInitialized(INavigationParameters parameters);
}
 ```
 
 ```cs
public interface IInitializeAsync
 {
     Task<bool> TryOnInitializedAsync(INavigationParameters parameters);
 }
 ```

**Comment by UnreachableCode** [comment]
The documents still talk about [INavigatingAware](https://prismlibrary.github.io/docs/xamarin-forms/navigation/passing-parameters.html). But Dan, in this enhancement you say it's now obsolete. Can I update the docs? And would it be possible to show the version of Prism a document refers to, like the framework version which shows on Microsoft docs for example?

**Comment by dansiegel** [comment]
@UnreachableCode it would be best to open an issue for this on the docs repo. I do appreciate your bringing this to my attention though :)
