### ISSUE TITLE
please provide a StartupLocation Property for PopupWindowAction

### ISSUE THREAD

**Issue by noufionline** [PrismLibrary/Prism#175]
Current CenterOverAssociatedObject is sometime not sufficient enough. If we have a startup location property we can easily set to center screen for example

**Comment by abdullahbamusa** [comment]
Yes please add this property. CenterOverAssociatedObject doesn't work as expected, at least in my case, where controls flow direction is from right to left. Beside that StartupLocation is how Windows handle its windows and dialogs, so let is stop reinventing the wheel.

**Comment by brianlagunas** [comment]
I believe CenterOverAssociateObject isn't meant to replace StartUpLocation.  I think it was provided for cases where the notification window is not to be centered around a parent Window, but instead an element in a view.  @briannoyes do you know the history behind this?

**Comment by briannoyes** [comment]
Do not know, sorry.

**Comment by znakeeye** [comment]
In my opinion, `CenterOverAssociateObject` is pretty worthless in its present form. The centering algorithm fails in many cases. E.g. The associated view is 100 points wide, near the desktop edge and the interaction request then shows a view of 300 points. You're lucky if you can see the popup at all.

**Comment by brianlagunas** [comment]
fixed with #231
