### ISSUE TITLE
[WPF] PopupWindowAction with custom WindowContent does not re-evaluate size on second show

### ISSUE THREAD

**Issue by Jinjinov** [PrismLibrary/Prism#1752]
### Description

Raising a second notification with different content does not re-evaluate the size of the modal window.

### Steps to Reproduce

1. open Prism-Samples-Wpf/27-CustomContent/

2. change MainWindowViewModel.cs line 39, replace
`NotificationRequest.Raise(new Notification { Content = "Notification Message", Title = "Notification" }, r => Title = "Notified");`
with
`CustomPopupRequest.Raise(new Notification { Title = "Custom Popup", Content = "Custom Popup Message \n Custom Popup Message \n Custom Popup Message \n " }, r => Title = "Good to go");`
**This has \n in the text to create new lines!**

3. change MainWindowViewModel.cs line 44, replace
`ConfirmationRequest.Raise(new Confirmation { Title = "Confirmation", Content = "Confirmation Message" }, r => Title = r.Confirmed ? "Confirmed" : "Not Confirmed");`
with
`CustomPopupRequest.Raise(new Notification { Title = "Custom Popup", Content = "Custom Popup Message Custom Popup Message Custom Popup Message " }, r => Title = "Good to go");`
**This does not have \n in the text!**

4. run the application, click the **first** button, then click the **second** button

5. run the application again, click the **second** button, then click the **first** button

### Expected Behavior

The modal window should resize to fit the content every time.

### Actual Behavior

The modal window resizes itself to fit the content only on the first show.

### Basic Information

- Version with issue: 7.1.0.431
- Last known good version: N/A
- Xamarin.Forms version: I am using Prism.Wpf
- IDE: Visual Studio 2017 ver. 15.9.10

**Comment by brianlagunas** [comment]
Closed as will not verify or fix. We have a new IDialogService which will be replacing the PopupWindowAction

**Comment by Jinjinov** [comment]
I have to fix this asap. If you could give me some pointers on what my options are, I would be very grateful. Is there any sample on how to use IDialogService?

**Comment by brianlagunas** [comment]
All the source code is available for you to debug to see what is causing your issue. Just start stepping thorough it. Simple sample can be found in PR #1666, though the base class has been removed.
