### ISSUE TITLE
RegionAdapter

### ISSUE THREAD

**Issue by PeterForstmeier** [PrismLibrary/Prism#1753]
Hi,
i would like to use Fluent.Ribbon 6.1  togehter with Prism 7.1
Register RegionAdapter:
protected override void ConfigureRegionAdapterMappings(RegionAdapterMappings regionAdapterMappings)
        {
            base.ConfigureRegionAdapterMappings(regionAdapterMappings);
            regionAdapterMappings.RegisterMapping(typeof(Ribbon), (RibbonRegionAdapter)Container.Resolve(typeof(RibbonRegionAdapter)));
            regionAdapterMappings.RegisterMapping(typeof(RibbonTabItem), (RibbonTabItemRegionAdapter) Container.Resolve(typeof(RibbonTabItemRegionAdapter)));
 }
RegionAdapter:
 public class RibbonRegionAdapter : RegionAdapterBase<Ribbon>
    {
        public RibbonRegionAdapter(IRegionBehaviorFactory behaviorFactory)
            : base(behaviorFactory)
        {
        }
        protected override void Adapt(IRegion region, Ribbon regionTarget)
        {
            if (region == null) throw new ArgumentNullException("Region");
            if (regionTarget == null) throw new ArgumentNullException("RegionTarget");

            region.ActiveViews.CollectionChanged += (s, args) =>
            {
                switch (args.Action)
                {
                    case NotifyCollectionChangedAction.Add:
                        {
                            foreach (Object view in args.NewItems)
                            {
                                AddViewToRegion(view, regionTarget);
                            }
                            break;
                        }
                    case NotifyCollectionChangedAction.Remove:
                        {
                            foreach (Object view in args.OldItems)
                            {
                                RemoveViewFromRegion(view, regionTarget);
                            }
                            break;
                        }
                    default:
                        {
                            // Do nothing.
                            break;
                        }
                }
            };
        }
        protected override IRegion CreateRegion()
        {
            return new AllActiveRegion();
        }

        static void AddViewToRegion(Object view, Ribbon wpfRibbon)
        {
            var ribbonTab = view as RibbonTabItem;
            if (ribbonTab != null)
                wpfRibbon.Tabs.Add(ribbonTab);
        }

        static void RemoveViewFromRegion(Object view, Ribbon wpfRibbon)
        {
            var ribbonTab = view as RibbonTabItem;
            if (ribbonTab != null)
                wpfRibbon.Tabs.Remove(ribbonTab);
        }
    }

    public class RibbonTabItemRegionAdapter : RegionAdapterBase<RibbonTabItem>
    { 
        public RibbonTabItemRegionAdapter(IRegionBehaviorFactory regionBehaviorFactory) : base(regionBehaviorFactory)
        {
        }

        protected override void Adapt(IRegion region, RibbonTabItem regionTarget)
        {
            region.Views.CollectionChanged += (sender, args) => ViewsOnCollectionChanged(regionTarget, args);
        }

        private static void ViewsOnCollectionChanged(RibbonTabItem regionTarget, NotifyCollectionChangedEventArgs e)
        {
            switch (e.Action)
            {
                case NotifyCollectionChangedAction.Add:
                    foreach (var newItem in e.NewItems)
                    {
                        regionTarget.Groups.Add((RibbonGroupBox)newItem);
                    }
                    regionTarget.BringIntoView();
                    break;
                case NotifyCollectionChangedAction.Remove:
                    foreach (var oldItem in e.OldItems)
                    {
                        regionTarget.Groups.Remove((RibbonGroupBox)oldItem);
                    }
                    break;
            }
        }

        protected override IRegion CreateRegion()
        {
            //  return new AllActiveRegion();
            return new Region();
        }
    }

Declaration:
     Title="{Binding Title}" Height="350" Width="525">
    <Grid>
        <Fluent:Ribbon Grid.Row="0" prism:RegionManager.RegionName="RibbonRegion" >

            <Fluent:RibbonTabItem Header="Test" prism:RegionManager.RegionName="TabRegion">
            </Fluent:RibbonTabItem>

            <Fluent:RibbonTabItem Header="Home">
                <Fluent:RibbonGroupBox Header="Group" ></Fluent:RibbonGroupBox>
            </Fluent:RibbonTabItem>
        </Fluent:Ribbon>
        
        <ContentControl Grid.Row="1" Background="LightBlue" prism:RegionManager.RegionName="ContentRegion"></ContentControl>
    </Grid>

'RibbonRegion' and 'ContentRegion' works as expected, 'TabRegion' is initialized but not added to the Regions Property in RegionManager.
Any idea????
Thanks
Peter

**Comment by brianlagunas** [comment]
I'm sorry, but questions like these should be asked on forums like StackOverflow.

**Comment by PeterForstmeier** [comment]
Ok, sorgt


Peter




Outlook für Android herunterladen







On Fri, Mar 29, 2019 at 9:37 PM +0100, "Brian Lagunas" <notifications@github.com> wrote:












I'm sorry, but questions like these should be asked on forums like StackOverflow.



—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.







I'm sorry, but questions like these should be asked on forums like StackOverflow.

**Comment by isalo** [comment]
were you able to solve your issue?

**Comment by PeterForstmeier** [comment]
Hi,
no
Thanks
Peter
