### ISSUE TITLE
Xaml NavigationParameters not setting BindingContext on Parameter

### ISSUE THREAD

**Issue by jhermsen** [PrismLibrary/Prism#1754]
### Description
The Xaml NavigationParameters extension is not setting the BindingContext on its parameters.
Because of this binding of Parameter values is not working

### Steps to Reproduce

1. Create project using "Prism Blank App (Xamarin Forms)" project template

2. Add a Page using "Prism ContentPage (Xamarin.Forms)" E.g. TestPage
3. Update TestPageViewModel class to extend from  : ViewModelBase
4. Override the OnNavigatedTo and put your breakpoint in here

5. In the MainPage add the "Prism.Navigation.Xaml" namespace: 
`xmlns:prismNav="clr-namespace:Prism.Navigation.Xaml;assembly=Prism.Forms"`
6. Add a Button E.g:
```
<Button Text="TEST" Command="{prismNav:NavigateTo 'TestPage'}">
    <Button.CommandParameter>
        <prismNav:NavigationParameters BindingContext="{Binding .}">
            <prismNav:NavigationParameter 
                Key="modelParm"
                Value="{Binding .}" />
        </prismNav:NavigationParameters>
    </Button.CommandParameter>
</Button>
```

7. Run the app and press the button and see that at the breakpoint the parameters argument contains the modelParm, but its value is null.

### Expected Behavior
Bound value of the modelParm parameter is passed on at navigation

### Actual Behavior
Bound value of the modelParm parameter is null

### Basic Information
- Version with issue: 7.1.0.431
- Last known good version: Unkown

- Xamarin.Forms version: 3.2.0.839982 also 3.6.0.264807
- IDE: Visual Studio 2017

### Reproduction Link
Attached a sample project
Also added a second button with PropertyChanged eventhandler to set parameters based on changed Parent of the NavigationParameters.
So this event handler handles what should mimics the code in the NavigationParmaters: https://github.com/PrismLibrary/Prism/blob/2507daf9e30df838d0d6d3443f1ac47befc529e8/Source/Xamarin/Prism.Forms/Navigation/Xaml/NavigationParameters.cs#L83-L88
[PrismNavTest.zip](https://github.com/PrismLibrary/Prism/files/3035307/PrismNavTest.zip)

**Comment by brianlagunas** [comment]
Please reformat your issue to adhere to the issue template and provide a sample to reproduce the issue, or I will have close this issue.

**Comment by jhermsen** [comment]
I think the following should be updated:
https://github.com/PrismLibrary/Prism/blob/2507daf9e30df838d0d6d3443f1ac47befc529e8/Source/Xamarin/Prism.Forms/Navigation/Xaml/NavigationParameters.cs#L78-L79
To something like so:
```csharp
if (newvalue is BindableObject newParent) 
{
     newParent.BindingContextChanged += BindingContextChanged; 
     BindingContextChanged(newParent, EventArgs.Empty);
}
```

**Comment by dansiegel** [comment]
@jhermsen it's going to be a while before I can look at this. if you want to take the issue submit a PR we'd love to see it. Just please make sure we get some tests in there so we can be sure that bindings are working as expected.

**Comment by brianlagunas** [comment]
And that there no memory leaks. You're hooking into an event which is always a common source for memory leaks.

**Comment by dansiegel** [comment]
well there is that... I really do not think you should have to hook into the event btw. and BindableBase which NavigationExtensionBase inherits from does have a virtual OnBindingContextChanged as I recall.

**Comment by jhermsen** [comment]
@dansiegel I'll work around it for now.
I have little experience writing unit tests and for tests for xaml I haven't done at all.
