### ISSUE TITLE
unable to install prism developer toolokit 

### ISSUE THREAD

**Issue by mohammedmsadiq** [PrismLibrary/Prism#1755]
### Description

i was unable to install prism developer toolkit on visualstudio 2019 for mac see picture below;
with vs you get monodevelope v8 as standard but prism requires v7.6.6. cant find any solution for this?
 
<img width="1523" alt="Screenshot 2019-04-03 at 10 20 44" src="https://user-images.githubusercontent.com/48685203/55468443-46884a00-55fb-11e9-950c-158de43c4d28.png">

### Steps to Reproduce

1. 
2. 
3. 

### Basic Information

- Version with issue:
- Last known good version:
- Xamarin.Forms version:
- IDE:

**Comment by zultralord** [comment]
and so it begins...

**Comment by dansiegel** [comment]
I'm aware of the issue... I haven't had the time to update the extension for VS Mac 2019. I'll try to get to this when I get some time.

**Comment by Pepsi1x1** [comment]
Is the source for the extension available?

**Comment by bartlannoeye** [comment]
It is not publicly available.

**Comment by gumeralvarado25** [comment]
Hi, is this quick start template for VS 2019 for Windows?

**Comment by dansiegel** [comment]
It hasn't been brought over to Windows yet

**Comment by bomanry** [comment]
Hi Daniel.  Any further development on this issue?  Would love to see prism for VS 2019 Mac.  Thanks.

**Comment by fuegosoft** [comment]
Hi Daniel. any updates for the prism template pack?  Thanks.

**Comment by WarBorg** [comment]
also waiting for the update so I can do some Prism magic in VS for Mac 2019 :D

**Comment by Pepsi1x1** [comment]
As a workaround, the VS 2019 for Mac install keeps a copy of VS 2017 as “Visual Studio (old)”, just right click and Show Package Contents on the application. 

You can launch 2017, generate the project in there using the quick start template, then open the solution in VS 2019 for Mac

**Comment by KevinHu-au** [comment]
Waiting for the extension for VS4mac 8 (2019). Thanks.

**Comment by john-dalsgaard** [comment]
Any news on this?

"Hand creating" new pages doesn't seem right.... 😃

**Comment by adeel-appmaisters** [comment]
Any update here, I am also stuck in the same issue!

**Comment by ArsalRaza** [comment]
Any update here, I am also stuck into the same issue!

**Comment by Pepsi1x1** [comment]
I pulled out the file templates into a separate addin, repo is here https://github.com/Pepsi1x1/VSMacPrismTemplates

**Comment by brianlagunas** [comment]
@Pepsi1x1 FYI... the templates are not open source. So if you took the templates that the extension installed locally and extracted them to place on GitHub, this would technically be considered stealing.

**Comment by Pepsi1x1** [comment]
@brianlagunas I've considered multiple responses to this message. I think an email might have been more appropriate. 

I took the time to understand what was going on with these templates and published a small subsection of the file templates alone because it was hurting my productivity and hoped this would help others bridge the gap to having the full extension without taking away from the great work that Dan is doing. This is following giving support to others on this thread with a workaround so that they could use the other parts of the extension that haven't been updated yet.

I found a couple of bugs in there too, I'm not sure if this was a reflection issue or a bug proper, I'll gladly share those to improve the extension.

We explore.  We seek after knowledge. We exist without skin color, without nationality, without religious bias... My crime is that of curiosity.

If you would like me to take the repo down, I will do that.

**Comment by Pepsi1x1** [comment]
I'll take the repo down. Out of curiosity why isn't this code open source?

**Comment by brianlagunas** [comment]
We're just not giving everything away. We are keeping some stuff for ourselves. We my want to productize some of the things we are creating in the future so we must keep that closed source in order to do that. We do eventually want to get pad for all our work :)

**Comment by dansiegel** [comment]
I have to say given the immense amount of work that has gone into it, stealing it and trying to rebrand it as your own really does NOT make me want to prioritize this.

**Comment by Pepsi1x1** [comment]
Fair enough, do let me know when you monetise it so that I can open source that ;)

In all seriousness, where should I report these bugs, is there a private tracker for the template pack?

**Comment by Pepsi1x1** [comment]
@dansiegel This wasn't branded as my own, seriously.

**Comment by brianlagunas** [comment]
@Pepsi1x1 if you find any issues with the template packs, feel free to submit your issues here. We have a "Template Pack" tag that we use t track them.  Thanks again.

**Comment by dansiegel** [comment]
@Pepsi1x1 you need to understand that's IP Theft... seriously not cool. The fact that you found this thread indicates that you clearly understand that issues regarding the template pack are being tracked here.

**Comment by Pepsi1x1** [comment]
@dansiegel I think I've been quite reasonable, upon request I immediately removed the repository. I will be contributing bug reports based on what I've found. My intention was to help the community and bridge a gap whilst other issues were taking priority. 

The work you have done is fantastic and I'm grateful for how much your work has improved both my productivity and the quality of my code, I'm sure many others share the same gratitude. 

I have nor ever had any intention to pass off this code as my own or rebrand it, the repository that I put up contained the name of the addin as part of it in order that it was clear it came from another source.

**Comment by Pepsi1x1** [comment]
@dansiegel I think I've been quite reasonable, once this was explained I offered to and I immediately removed the repository. I will be contributing bug reports based on what I've found. My intention was to help the community and bridge a gap whilst other issues were taking priority.

The work you have done is fantastic and I'm grateful for how much your work has improved both my productivity and the quality of my code, I'm sure many others share the same gratitude.

I have nor ever had any intention to pass off this code as my own or rebrand it, the repository that I put up contained the name of the addin as part of it in order that it was clear it came from another source.

**Comment by Pepsi1x1** [comment]
I have reported the issues I came across, I'd be happy to help out with getting this template pack up and running with the new version of VS for Mac if bandwidth is an issue prioritising this.

**Comment by dansiegel** [comment]
@Pepsi1x1 feel free to ping me on Twitter and we can continue this discussion via DM, or if you're on Prism/Xamarin Slack you can reach me there as well.

**Comment by mharrisonbit** [comment]
Where could I find a walkthrough of how to get started with prism because everything I have found so far talks about needing this template pack?

**Comment by TreasureTS** [comment]
https://www.youtube.com/watch?v=DYRLcqG2BAY&t=1455s

**Comment by TreasureTS** [comment]
Can you guys please help with the Template pack for VS 2019 Mac. Please

**Comment by rajkumarvishnu** [comment]
Any update on the prism pack for VS mac?

**Comment by TreasureTS** [comment]
@dansiegel Is there anything we can do to help with this, please man?

**Comment by rajkumarvishnu** [comment]
@TreasureTS  Use this in the meantime -> Implement Prism in existing Xamarin.Forms Shared Application - https://stackoverflow.com/questions/45280105/implement-prism-in-existing-xamarin-forms-shared-application

**Comment by leroygumede** [comment]
@dansiegel and @brianlagunas , any update, timeline on this ? are you planning to cut out mac support so we are all on the same page ?

**Comment by brianlagunas** [comment]
@leroygumede there is no timeline. We do this work in our spare time. We will get to it when we can. Just because it takes us a while to get to something doesn't mean it's dead.

**Comment by mojazu** [comment]
Hello @brianlagunas @dansiegel , any updates on this issue. Thank you guys.

**Comment by brianlagunas** [comment]
Due to the complexity and time requirements for IDE extensions and tooling, we are closing this issue as "will not fix".  However, for those of you that really need this, you can sponsor @dansiegel to implement this feature on his time.

https://github.com/sponsors/dansiegel

**Comment by jbachelor** [comment]
> Due to the complexity and time requirements for IDE extensions and tooling, we are closing this issue as "will not fix". However, for those of you that really need this, you can sponsor @dansiegel to implement this feature on his time.
> 
> https://github.com/sponsors/dansiegel

Thank you, @dansiegel, for developing it for as long as you did. It was a great tool, and made it easy to introduce developers to Prism based apps with Xamarin.Forms. I personally Loved it. The class I taught at UC San Marcos on Prism.Forms would not have been possible without it.

**Comment by stephenhauck** [comment]
Just got back to this as I have been stuck on a Windows box for some time now.
Thanks for the templates when they were available.
Thanks for the work you guys do on Prism!

Seems like someone at Microsoft should take note that making templates and extending Visual Studio is overly complicated and needs to be revisited.

**Comment by nosmirck** [comment]
@dansiegel @brianlagunas  If you're not going to upgrade the templates and don't have time/intention/motivation to do it, then simply open source the template pack code so people with the right motivation and time, like @Pepsi1x1 can fix it for all of us! That's what a community is all about, isn't it? We understand that you guys provide a nice package and all for free, but if you can't keep it up, either make it a paid service so you guys can work full time on it or open source it and leave the community help. The in-between doesn't really make any sense.

**Comment by dansiegel** [comment]
@nosmirck actually I am updating the entire developer studio and will have something out in the next few weeks, however it will only be available to those who are sponsoring me.

**Comment by stephenhauck** [comment]
Uhhhh.... ok ?

I don’t mind supporting a project but .... Prism will definitely not be my defacto choice moving forward 

THANK you for all the years of an excellent product!!!!!!

**Comment by dansiegel** [comment]
@stephenhauck it takes hundreds of hours to build and maintain products like the IDE tooling not to mention everything that we've done for Prism. If you or your company can't be bothered to help sponsor @brianlagunas or myself then you obviously do mind supporting a project, and you're looking for us to work for you for free.

Frankly the IDE tooling I built for VS4Mac last year saved people hundreds of hours of development time when trying to create new projects. If people want it then they will need to help make Prism sustainable long term by sponsoring me for all of the work they are benefiting from.

**Comment by stephenhauck** [comment]
@dansiegel @brianlagunas I AGREE and I THANK YOU!
I am a single developer and getting squeezed by ...
- JetBrains for Resharper,
- MFractor for Resharper like features for VSMac

**Comment by Coder-Nut** [comment]
@dansiegle @brianlagunas and anyone else maintaining prism and keeping it alive. Thank You. You guys are doing a fantastic job. Keep up the good work and I will continue to sponsor. Have a great day!

________________________________
