### ISSUE TITLE
[Proposal] Automatic View Registration

### ISSUE THREAD

**Issue by dansiegel** [PrismLibrary/Prism#1757]
### Description

Since it can be assumed that any page within a Xamarin Forms Project will be used for Navigation we can dramatically simplify View Registration by introducing an Opt-In API that would allow Prism to reflect on the main assembly (where App.xaml.cs is located), and any modules that are loaded)

### Proposal

Core support for this feature would come from the use of two new Attributes `RegisterByConventionAttribute` and `RegisterForNavigationAttribute`.

```cs
public class RegisterByConventionAttribute : Attribute
{
    public bool Automatic { get; set; }
}

public class RegisterForNavigationAttribute : Attribute
{
    public Type ViewType { get; }
    public Type ViewModelType { get; }
    public string Name { get; }
}
```

To Opt-In you will need to decorate your App class with the `RegisterByConvention` attribute like so:

```cs
[RegisterByConvention]
public partial class App : PrismApplication
{
}
```

When set like this Prism would then reflect over the assembly:

1. First it would look for attributes set at an assembly level like:

```cs
[assembly: RegisterForNavigation(typeof(ViewA))]
[assembly: RegisterForNavigation(typeof(ViewB), typeof(ViewBViewModel))]
[assembly: RegisterForNavigation(typeof(ViewC), "viewC")]
[assembly: RegisterForNavigation(typeof(ViewD), typeof(ViewDViewModel), "viewD")]
```

In this example we would get 4 automatically registered Views

2. In the event that we have opted for this sort of automatic registration, but no registrations are found at an assembly level, PrismApplication would then reflect over the exported types and evaluate any types that inherit from Page. This would occur for the assembly that the implementing App class is located in as well as for any loaded Modules. For this the Page type must declare the `RegisterForNavigation` attribute

```cs
[RegisterForNavigation]
public class ViewA : ContentPage
{
}

[RegisterForNavigation("viewB")
public class ViewB : ContentPage
{
}

[RegisterForNavigation { ViewModelType = typeof(ViewCViewModel) }]
public class ViewC : ContentPage
{
}
```

3. As shown above the `RegisterByConventionAttribute` has an Automatic property. In the event that Automatic is set, any assembly level attributes will be handled, and all Exported types will be evaluated. In the event that a given Page type is not handled by either an assembly or type level RegisterForNavigationAttribute, the type will be automatically registered by convention with the type name as the navigation key.

**Comment by brianlagunas** [comment]
implementd with PR #1780

**Comment by Im-PJ** [comment]
```
 [AutoRegisterForNavigation]
public class App : PrismApplication
{
}
```
It can't recognize Automatic property. I have update to prism 7.2
