### ISSUE TITLE
Unity Exceptions Resolution Failed

### ISSUE THREAD

**Issue by joshwl2003** [PrismLibrary/Prism#1758]
### Description

I have a Xamarin forms application and it is throwing the following error when I try to run the ios version of my application  It is being thrown in the constructor. It seems to be thrown in the initialize function after my injected items are registered.

It is stated that at the time of the exception the container was trying to resolve Prism Modularity Module Catelog Mapped from I module catelog

### Steps to Reproduce

1. I try to run my app in the iOS configuration
2. 
3. 

### Basic Information

- Version with issue: 7.1.0.431
- Xamarin.Forms version: 3.6.0.293080
- IDE: Visual Studio Mac 2019

### Screenshots

![Screen Shot 2019-04-05 at 2 17 05 PM](https://user-images.githubusercontent.com/7062049/55648136-7f682080-57ad-11e9-830f-7c7668f697c3.png)
>

### Reproduction Link

`App.Xaml.CS Code  protected override void RegisterTypes(IContainerRegistry containerRegistry)
        {
            this.RegisterLocal(containerRegistry);
            this.RegisterServices(containerRegistry);  
            this.RegisterPagesForNavigation(containerRegistry);
        }

        private void RegisterLocal(IContainerRegistry containerRegistry)
        {
            containerRegistry.Register<IUserInfoProvider, UserService>();
        }

        private void RegisterServices(IContainerRegistry containerRegistry)
        {
            //TODO: Need to figure out how to work with configurable options
            containerRegistry.Register<IAuthorizationContext, AuthorizationManager>();
            containerRegistry.GetContainer()
                .RegisterType<IAuthenticationService, AuthenticationService>(new ContainerControlledLifetimeManager());
        }

        private void RegisterPagesForNavigation(IContainerRegistry containerRegistry)
        {
            containerRegistry.RegisterForNavigation<NavigationPage>();
            containerRegistry.RegisterForNavigation<LoginPage, LoginPageViewModel>();
            containerRegistry.RegisterForNavigation<MenuPage>();
        }
`

Here is the IOS App Code
`{
        public override bool FinishedLaunching(UIApplication app, NSDictionary options)
        {
            global::Xamarin.Forms.Forms.Init();
         
            LoadApplication(new App(new IosInitializer()));

            return base.FinishedLaunching(app, options);
        }

        public class IosInitializer : IPlatformInitializer
        {
            public void RegisterTypes(IContainerRegistry containerRegistry)
            {
                containerRegistry.Register<IUAirshipUpdate, UAirshipUpdate>();
            }
        }
    }`

I would expect that the iOS version would work the same way that the android version works but it is always crashing.

From looking through the source code in PrismApplicaitonBase I do not understand why the module is not resolved because one is created in Required Dependencies section

**Comment by dansiegel** [comment]
I have multiple projects using Prism Modules... You've also not include a sample app that shows the issue.
