### ISSUE TITLE
Xamarin IOS Linker Settings

### ISSUE THREAD

**Issue by joshwl2003** [PrismLibrary/Prism#1760]
### Description

If you create a Xamarin IOS project and set the linker behavior to link all. The application will crash with the following exception
![Screen Shot 2019-04-08 at 3 01 04 PM](https://user-images.githubusercontent.com/7062049/55749536-24cdff00-5a0f-11e9-8acd-4a92eceb8565.png)

If you set linker options to any other mode the software works as expected.

### Basic Information

- Version with issue: Prism Unity Forms 7.1.0.431
- Last known good version: Unknown
- Xamarin.Forms version: 3.6.0.29308
- IDE: Visual Studio For Mac

### Reproduction Link

https://github.com/joshwl2003/XamarinPrisimSample

**Comment by dansiegel** [comment]
This is not a bug or problem with Prism. Before you use the Linker please read the documentation for how it works.
