### ISSUE TITLE
Unable to use relative navigation in Xamarin.Forms

### ISSUE THREAD

**Issue by ronray88** [PrismLibrary/Prism#1762]
I'm did a tiny Xamarin.Forms program to test navigation in Prism.
I did not use Xaml in creating the views, I use c# code only.
When I use absolute navigation path then the it navigated as expected.
However, if I use relative path then it did not work.

Here is what I have:
1) PgMain - First view to be displayed, contains a button to navigation to PgA
2) VmMain - the matching viewmodel of PgMain containing the navigation method
            to be called by PgMain
3) PgA - a  simple XF page which display a label saying "PgA"			

### Expected Behavior
When I use absolute navigation then everything works fine:
```		
		await _navServ.NavigateAsync("/NavigationPage/PgMain/PgA");
```

### Actual Behavior
when I use relative navigation in VmMain:
```                
		await _navServ.NavigateAsync("PgA");
```
	
It did not navigate. I put a break point at this line and found that the same line is executed twice.

- Version with issue: Prism 7.1.0
- Last known good version:
- Xamarin.Forms version: 3.6.0
- IDE: VS 2017

### Code

In App.xaml.cs:
```
        protected override async void OnInitialized()
        {
            InitializeComponent();

            await NavigationService.NavigateAsync("NavigationPage/PgMain");
        }

        protected override void RegisterTypes(IContainerRegistry containerRegistry)
        {
            containerRegistry.RegisterForNavigation<NavigationPage>();
            containerRegistry.RegisterForNavigation<PgMain, VmMain>();
            containerRegistry.RegisterForNavigation<PgA, VmA>();
        }
```

In PgMain.cs:
```
    class PgMain : ContentPage
    {

        public PgMain(VmMain vm)
        {
            Title = vm.titleText;
            var btn = new Button()
            {
                Text = vm.btnText,
            };
            btn.Clicked += async (sender, args) =>
            {
                await vm.Nav2ViewA();
            };

            Content = new StackLayout()
            {
                Children = { btn}
            };
        }
    }
```

In VmMain.cs:
```
    public class VmMain : VmBase
    {
        public string titleText = "Page Title";
        public string btnText = "Nav to PgA";

        private readonly INavigationService _navServ;
        public VmMain(INavigationService navServ) : base(navServ)
        {
            _navServ = navServ;
        }

        public async Task Nav2ViewA()
        {
                await _navServ.NavigateAsync("PgA");
        }
    }
```

**Comment by dansiegel** [comment]
Closing for no repo app
