### ISSUE TITLE
Unable to create a new Prism project after I updated today (4/9/2019)

### ISSUE THREAD

**Issue by visionarycoder** [PrismLibrary/Prism#1763]
### Steps to Reproduce
1. Update to latest Prism Template Pack (v2.1.15)
2. Add new Module.

### Expected Behavior
The module loads into the solution.

### Actual Behavior
The module does not appear in the solution.  No error shown.  
Manually adding the project throws an error.

### Basic Information
Visual Studio Enterprise 2017
Version 15.9.11

Prism Template Pack 
Version 2.1.5

### Screenshots
![Capture](https://user-images.githubusercontent.com/8689814/55825691-58fef980-5abb-11e9-8823-91ccbead877a.PNG)

### Reproduction Link
Not applicable.  Template failure.

**Comment by brianlagunas** [comment]
Whatplatform? WPF or XF?

**Comment by brianlagunas** [comment]
Fixed. The update should be available shortly.
