### ISSUE TITLE
Can't create new project at Prism Template Pack

### ISSUE THREAD

**Issue by DroppedCakes** [PrismLibrary/Prism#1764]
### Description

Can't create new project(PrismBlankAppWpf) in VS2019 and VS2017.

till few days ago,I had no problems creating Prism Project. 

### Steps to Reproduce

1. VS2019 or VS2017
2. Create a new project on the Prism Blank App(WPF) using .Net framework4.7.2
3. Push Create Button

### Expected Behavior
Create new project and Show selected view for IOC Container
### Actual Behavior
Show this error dialog.

---------------------------
Microsoft Visual Studio
---------------------------
Requested value 'Autofac' was not found.
---------------------------
OK   
---------------------------

### Basic Information

- Version with issue:2.1.6
- Last known good version: sorry,Idon't know
- Xamarin.Forms version:
- IDE:VS2019 community 16.0.1
- IDE:VS2017 community 15.9.11
### Screenshots
![SnapCrab_NoName_2019-4-10_12-42-25_No-00](https://user-images.githubusercontent.com/43688962/55850156-34c01d00-5b8e-11e9-92c2-bff6ee7f4251.png)

**Comment by DroppedCakes** [comment]
Solved removing registry key "SelectedContainer" in HKEY_CURRENT_USER\Software\Prism

**Comment by brianlagunas** [comment]
See for more info: https://forums.xamarin.com/discussion/comment/370943#Comment_370943

**Comment by DanielCauser** [comment]
I was having the same issue, and looking following the steps in this issue resolved it.
