### ISSUE TITLE
Custom View Template binding with static property

### ISSUE THREAD

**Issue by Andufer** [PrismLibrary/Prism#1766]
Hi,
I'm using Prism for Xamarin in an App which is an interface from a BLE tool and my server on Azure.
I need to have a footer with the status of the connection from the app to the tool.
In the app I have a service that checks the connection and update a properties of a static class called IsConnected.
I thought to use a custom view template to add the footer with an image representing the connection status.
How I can bind the IsConnected property of the static class to the image of the footer in the view template?

Thanks a lot for any help.
Have a nice day,
Andrea

**Comment by dansiegel** [comment]
As indicated by our issue template. All questions should be asked on StackOverflow or our Slack channels for our Patrons.
