### ISSUE TITLE
No way to auto-set Views to ViewModelLocator.AutoWireViewModel to true for all Views

### ISSUE THREAD

**Issue by james1301** [PrismLibrary/Prism#1767]
### Description
No way to auto-set Views to ViewModelLocator.AutoWireViewModel="true" for all Views. I have specifically registered my views for navigation, so I don't know why I have to say to AutoWire them up each time. I have tried to do this through styles, but still gets a bit messy as I have different types and it still requires you to set the style in all Views.

### Steps to Reproduce

1. Setup WPF application for prism
2. In PrismApplication class, register views for navigation
3. Navigate to View, and the ViewModel is not automatically set with out setting AutoWireViewModel to true

### Expected Behavior
ViewModel is automatically set. Or someway to specify that this happens by default. Or it is an inherited dependency property.
### Actual Behavior
ViewModel is not set.
### Basic Information

- Version with issue: 7.1 Prism.WPF
- Last known good version: N/A
- Xamarin.Forms version: N/A
- IDE: Visual Studio 2019

### Screenshots
N/A

### Reproduction Link
N/A

**Comment by brianlagunas** [comment]
Not everyone uses the VML, and views must be registered for navigation rgardless of if you are using VML or not.
