### ISSUE TITLE
IDestructible is actually missing.

### ISSUE THREAD

**Issue by karak** [PrismLibrary/Prism#1772]
### Description

`IDestructible` causes a runtime error in a WPF project with the reference to a net-standard project.

### Steps to Reproduce

1. Check it out and build the following repository.
2. Execute its unit tests of Net472Test.

### Expected Behavior

All the tests success.

### Actual Behavior

Build has succeeded, and it throws TypeLoadException, however.

### Basic Information

- Version with issue: 7.1.0.431
- IDE: VS2019 for Mac and Rider

### Screenshots

None.

### Reproduction Link

<https://github.com/karak/PrismNavigationBug>

**Comment by brianlagunas** [comment]
IDestructible is not part of Prism for WPF.

**Comment by brianlagunas** [comment]
I'll add, that while it's not part of the 7.1, it is part of WPF in the latest CI build on MyGet.

**Comment by brianlagunas** [comment]
Like I said, it's not in v7.1. If you want to use IDestrucible, you need ot use the latest Preview, or the latest CI build.

**Comment by karak** [comment]
I have just tested with 7.2.0.1038-pre to get same result.

Exactly saying, the test project of <https://github.com/karak/PrismNavigationBug> doesn't use Prism.WPF, but just uses Prism.Core on the target platform `net452`.

**Comment by brianlagunas** [comment]
It's not Prism, it's an issue with your project.

**Comment by karak** [comment]
Hmm...in short, Prism.Core does provide `IDestructible` or not?

As you know, I believe bait-and-switch is so common and sometimes the only way to build cross-platform applications.
