### ISSUE TITLE
IDialogService for WPF 

### ISSUE THREAD

**Issue by juliogamasso** [PrismLibrary/Prism#1775]
@brianlagunas 
Please, I need some help. I'm trying to implement the new IDialogService for WPF but when I try to set modal properties using <prism: Dialog.WindowStyle> is not being found in the namespace http://prismlibrary.com/ I'm running version 7.2.0.1038-pre. Some help? Thank you!

**Comment by brianlagunas** [comment]
That is not in the Preview, you have to use the CI builds for that feature
