### ISSUE TITLE
RegisterSingleton(name) does not found in version 7.1.0431 

### ISSUE THREAD

**Issue by huyjack178** [PrismLibrary/Prism#1776]
I want to register instance singleton with key but I don't find the method like this in the latest package. Refer to https://github.com/PrismLibrary/Prism/blob/master/Source/Xamarin/Prism.DryIoc.Forms/DryIocContainerExtension.cs

**Comment by dansiegel** [comment]
That’s because it was added after that. It should be in the latest preview

**Comment by huyjack178** [comment]
Hi @dansiegel, I found that in version preview but after installing, I got this issue

Method not found: Prism.Ioc.IContainerRegistry Prism.Ioc.IContainerRegistryExtensions.RegisterInstance

Can you help me?
