### ISSUE TITLE
Refit - thoughts on proper usage?

### ISSUE THREAD

**Issue by mzhukovs** [PrismLibrary/Prism#1778]
Just a question on if you agree with [this article](https://nicksnettravels.builttoroam.com/post/2019/04/16/Lazy-Dependencies-and-Interfacing-Refit-with-MvvmCross-and-Prism.aspx) regarding setting up Refit for use as an injectable service with Prism - would this be the recommended approach or something simpler would do just fine?

**Comment by bartlannoeye** [comment]
Questions like this should be asked on StackOverflow. Also, the time of instantiation (startup vs first time needed for injection) of your Refit service depends on the IoC container, not on Prism.
