### ISSUE TITLE
[Feature] Observes any Expression<Fun<T>> type expression

### ISSUE THREAD

**Issue by DingpingZhang** [PrismLibrary/Prism#1782]
Let us first assume that there is a static method with the following signature:

```csharp
ExpressionObserver.Observes<T>(Expression<Func<T>> expression, Action<T, Exception> onChanged): void
```

It differs from the current `DelegateCommand.ObservesPropety` function: the expression is not limited to a property or a property chain, but any expression that returns `T` type.

I think we can use it to implement the following two features:

1. Enhance `DelegateCommand.ObservesCanExecute()`:

```csharp
// Replace it
SignInCommand = new DelegateCommand(() => {  }, () => !string.IsNullOrEmpty(Username) && !string.IsNullOrEmpty(Password))
    .ObservesProperty(() => Username)
    .ObservesProperty(() => Password);

// with
SignInCommand = new DelegateCommand(() => {  })
    .ObservesCanExecute(() => !string.IsNullOrEmpty(Username) && !string.IsNullOrEmpty(Password));
```

2. Add "Computed Property" feature to the `BindableBase` class: 
- `BindableBase.GetProperty<T>(Expression<Func<T>> expression, T fallback = default, [CallerMemberName] string propertyName = null): T`

e.g.
```csharp
public class ViewModel: BindableBase
{
    public double RectangularArea => GetProperty(() => Width * Height);
}
```

**I have tried to implement the static method mentioned at the beginning** (please see this repo [DataBinding](https://github.com/DingpingZhang/DataBinding)), and I am supplementing its test cases. If it has no bugs, I will be happy to send a pull request to Prism Library :)

**Comment by brianlagunas** [comment]
Thanks for the idea, but this isn't something that Prism should handle.

**Comment by DingpingZhang** [comment]
@brianlagunas The "Computed Property" probably should not be handled by Prism, but I think a enhanced version of `DelegateCommand.CanExecute()` is still in demand.

**Comment by brianlagunas** [comment]
I'm not sure I want to complicate the code base to support any expression, which may or may not use properties from the VM. That goes against the intent of the ObservesCanExecute and can already be accomplished with the normal CanExcute delegate.  Remember, another funciton of the ObservesCanExecute is to raise the RaiseCanExecuteChanged method whenever the value of the property in the expression is change. It isn't used for just a boolean return value.
