### ISSUE TITLE
Xamarin Forms navigation broken with code inside OnNavigatingTo

### ISSUE THREAD

**Issue by BradleyDHobbs** [PrismLibrary/Prism#1783]
### Description

When I have any code inside of the OnNavigatingTo method, the app will not change pages. If I comment the code inside that method, it will change pages as expected.

### Steps to Reproduce

1. Open App
2. Click Login
3. Page doesn't change
4. Comment out code in OnNavigatingTo
5 Open app, click login, page changes

### Expected Behavior

Open app, click login, page changes

### Actual Behavior

Open app, click login, page doesn't change

### Basic Information

- Version with issue: 7.1.0.431
- Xamarin.Forms version: 3.6.0.344457
- IDE: Visual Studio 2019

### Reproduction Link

This is a sample that has the navigation broken by default. Comment out the code in the OnNavigatingTo method and it will work.

https://github.com/BradleyDHobbs/BlankPrismApp

**Comment by brianlagunas** [comment]
I'm pretty sure 9999999999 is outside the valid range of values for the int data type. You shoud test that first.

**Comment by BradleyDHobbs** [comment]
Just saw that. How to handle exceptions in the navigation methods?

**Comment by brianlagunas** [comment]
how do you handle exceptions anywhere else in your app?

**Comment by BradleyDHobbs** [comment]
Well really I'd like to know how to make them not fail silently in VS. I could wrap them with a logging service.

Are those methods supposed to fail silently if there's an exception?

**Comment by brianlagunas** [comment]
check the result of the navigation service call for an exception.

**Comment by BradleyDHobbs** [comment]
Will do thanks
