### ISSUE TITLE
Xamarin.Unity.Forms update Unity dlls

### ISSUE THREAD

**Issue by attilaszabo2** [PrismLibrary/Prism#1785]
### Description
Error caused in App.xaml.cs by constructor:
```
public App(IPlatformInitializer initializer) : base(initializer)
{
}
```
Unhandled Exception:
System.TypeLoadException: Could not resolve type with token 01000026 from typeref (expected class 'Unity.Registration.InjectionMember' in assembly 'Unity.Abstractions, Version=3.3.1.0, Culture=neutral, PublicKeyToken=6d32ff45e0ccc69f')

### Steps to Reproduce

1. Update Microsoft Unity.Container to the latest version (v5.10.3)
2. Start Android application

### Basic Information

- Version with issue: 7.2.0.1038-pre
- Last known good version: Unity.Contaner v5.8.13
- Xamarin.Forms version: 3.6.0.344457
- IDE:

### Reproduction Link
Just update please Unity.Container to the latest version.

**Comment by dansiegel** [comment]
We cannot guarantee that Unity will work when you upgrade beyond the version that Prism is built against. The problem is not Prism but breaking changes from Unity.

**Comment by maxal1917** [comment]
This is interesting. I look at Prism.Unity.Forms and it traces dependency to UnityContainer  5.8.11, which actually depends on Unity.Abstractions 4.1.3. So, the question remains open, where Unity.Abstractions, Version=3.3.1.0 is coming from?
I can reproduce the error.
