### ISSUE TITLE
Region navigation not working in new window

### ISSUE THREAD

**Issue by raV720** [PrismLibrary/Prism#1786]
I have main window (MainWindow) and new window (NewWindow) to be displayed from MainWindow. I am trying to display some view in region which is defined in NewWindow. When I use IRegionManager.RegisterViewWithRegion it works as expected. But when I display NewWndow and then call IRegionManager.RequestNavigate nothing happens. The method IRegionManager.RequestNavigate works as expected when region is in MainWindow. Is it my mistake or Prism cannot do navigation in separate window?

Here is an example: https://bitbucket.org/equo/prismregionnavigationtest.git
It is modified example 17-BasicRegionNavigation. After opening new window there nothing happens when clicking on any button, but ViewA or ViewB should be displayed below. After uncommenting MainWindow1 in App.CreateShell method the window works as expected.

- Version with issue: 7.1.0.431

**Comment by brianlagunas** [comment]
This is not a bug, and is fully supported. I even have a course on how to properly handle mutliple instances of those Windows.

https://www.pluralsight.com/courses/prism-showing-multiple-shells
