### ISSUE TITLE
Enhancements Request Generic abstract BindableBase<TModel> and Implementation of the IDisposable 

### ISSUE THREAD

**Issue by mindprober** [PrismLibrary/Prism#1787]
### Description

Enhancements Request Generic abstract BindableBase<TModel> and Implementation of the IDisposable 

Although, I Implemented at my own, the Generic abstract BindableBase<TModel> where TModel acts as associated Model with the ViewModel and Also I felt handy capped, where I need a common way of Implementing IDisposable pattern for view models. Attached file has a class model where have extended it.

![MvvmModel](https://user-images.githubusercontent.com/7477293/57155221-e37c0580-6da8-11e9-9ffc-fc4051192336.png)

 

### Steps to Reproduce

1. 
2. 
3. 

### Basic Information

- Version with issue:
- Last known good version:
- Xamarin.Forms version:
- IDE:

**Comment by brianlagunas** [comment]
Thanks for the idea, but this is not something we will be adding to Prism. The good news is that you can use it in your app with no problems.
