### ISSUE TITLE
Is ViewModel is correctly disposed if it has implemented IDisposable interface

### ISSUE THREAD

**Issue by noufionline** [PrismLibrary/Prism#179]
Hi Brians,

Suppose I have a view model with some unmanaged resources and this viewmodel has correctly implemented IDisposable. When the view is removed from the region will the viewmodel be disposed correctly?. Since I am using a TabControl as my RegionManager I cannot implement IRegionManagerMemberLifeTime interface as it will dispose the view the moment the view is deactivated.

Any thoughts on this?

**Comment by briannoyes** [comment]
It will not, but all you need is a simple custom RegionBehavior to make it happen. See https://github.com/PrismLibrary/Prism/issues/7
