### ISSUE TITLE
[7.2.0.1038-pre] switch to child tab page with parameters

### ISSUE THREAD

**Issue by henryyue2010** [PrismLibrary/Prism#1790]
### Description
I updated Prism to the current version 7.2.0.1038-pre and use
await _navigationService.SelectTabAsync("ChildPage", navigationParams);
to do the navigation. I want to pass parameters to the child tab page, but OnNavigatedTo method in the child tab page didn't get fired during the navigation.
Not sure if it's a bug or not. Any one got same issue?

**Comment by dansiegel** [comment]
closing for no repo app
