### ISSUE TITLE
IPageLifecycleAware firing OnAppearing event for tabbed pages that aren't appearing yet

### ISSUE THREAD

**Issue by cmpalmer66** [PrismLibrary/Prism#1791]
### Description

We have a tabbed page with five children. Each of the child pages except for the first implements IPageLifecycleAware. When the second page is clicked on, the OnAppearing event for it AND the next (third) page in the list is firing. Then when the third page is clicked, it doesn't get a new OnAppearing event, but the OnAppearing even for the FOURTH page fires, etc. Only after all of the pages have been visited once does the behavior match expectations.

### Steps to Reproduce

1. Create a TabbedPage with multiple children
2. Have all (or all but the first) implement IPageLifecycleAware
3. Put logging statements in the OnAppearing and OnDisappearing events for the child pages
4. Load the application and click each tab, observing which OnAppearing and OnDisappearing events fire.

### Expected Behavior

It is expected that when a tab is click, only that child page's OnAppearing even will fire and the OnDisappearing event from the previous page will fire. One OnAppearing per tab/child page.

### Actual Behavior

On the first visit to the tab, the OnAppearing event for that tab AND the next tab seem to be firing. Only after each tab has been visited does each page exhibit the predicted behavior.

### Basic Information

- Version with issue: v.7.1.0.431
- Last known good version: Unknown - about to go back to last stable version for testing
- Xamarin.Forms version: v4.0.0.394984-pre10
- IDE: Visual Studio 2017

- Only observed on UWP. Android appears to work as expected.

**Comment by dansiegel** [comment]
Thank you for the report. We are closing this for not having a sample duplicating the issue. If you'd like to add a sample we will reopen.
