### ISSUE TITLE
Request for refactoring DelegateCommand

### ISSUE THREAD

**Issue by sa-he** [PrismLibrary/Prism#1794]
The current DelegateCommand has nice features like, .ObservesProperty(..), but still lacks some important stuff (IMHO).

1. The documented usage of async/await (https://prismlibrary.github.io/docs/commanding.html#implementing-a-task-based-delegatecommand) is not well unit testable (https://stackoverflow.com/questions/15727515/how-to-unit-test-delegatecommand-that-calls-async-methods-in-mvvm). In the same way you cannot await a DelegateCommand when you want to call it inside of your own ViewModel.

2. Inheriting and overwriting Execute(object parameter) has only impact when called via the ICommand.Execute(object) overload, not via the generic version that is part of DelegateCommand<T>. A overwritten, custom overload should be used in both scenarios.

I'd be happy to contribute, but first want to check on your opinion.

**Comment by brianlagunas** [comment]
What exactly do you believe is lacking and how do you plan to fix it?

**Comment by sa-he** [comment]
1. I'd create AsyncDelegateCommand's that can be used something like that: 

``` C#
var ac = new AsyncDelegateCommand(()=> Task.Delay(500));
await ac.Execute();

var acGeneric = new AsyncDelegateCommand<int>(i=> Task.Delay(i));
await acGeneric.Execute(88);
```

2. Make sure that the protected virtual method is called in every scenario. I'd suggest the call stack of: Execute<T>(T param) -> ICommand.Execute(object param) -> protected virtual Execute() -> hosted delegate

**Comment by brianlagunas** [comment]
1. We will not add an async command because there is no such thing.  The UI does not invoke commands async.  There has already been a number of discussions around this.
2. this is already handled as you can see here: https://github.com/PrismLibrary/Prism/blob/master/Source/Prism/Commands/DelegateCommand%7BT%7D.cs#L101

**Comment by sa-he** [comment]
1. The UI does not invoke generic or parameleless Commands either - and still Prism has both. Without the not-existing AsyncCommand, I see no way of properly calling 'Execute' in the following code sample.

``` C#
public async Task Test()
{
    ICommand target = new DelegateCommand(Execute);

    // Both of the following calls cannot be awaited and therefore are asynchronous fire&forget calls.
    target.Execute(null);
    Execute();
    // Should be: await Execute();
}

// Should be: private async **Task** Execute()
private async void Execute()
{
    await Task.Delay(500);
    //..
}
```

2. Am I suggesting to change nothing? No. I am suggesting this little change (which has the previously mentioned advantage).
``` C#
public void Execute(T parameter)
{
    Execute(parameter as object);
}

protected override void Execute(object parameter)
{
    _executeMethod((T)parameter);
}
```

**Comment by brianlagunas** [comment]
1. Yes it does. If you invoke `ICommand.Execute(myParam) or `ICommand.Execute(null), it will work exactly as expected.  The code you have will not work. You cannot await `ICommand.Execute`, because `ICommand.Execute` is not a Task. It will always be fire and forget because the UI does not await commands. Prism will not be adding an AsyncCommand because ICommand is not async.
2. Can you provide a more detailed explanation on why you feel this change is necessary? Essentially you are requiring the typed parameter to be casted to an object and then back to it's generic type. Why take that performance hit?

**Comment by sa-he** [comment]
1. Sure, WPF Binding does fire & forget. I'm talking about the scenario where I want to call the executeMethod from my own code. It would be good if I could await the method.

2. 

``` C#
public class MyCommand : DelegateCommand
{
    public MyCommand(Action executeMethod) : base(executeMethod) { }

    protected override void Execute(object parameter)
    {
        Debug.WriteLine("Execute was called");
        base.Execute(parameter);
    }
}

var mc = new MyCommand(() => { });
mc.Execute(); // This line leads to NO debug output
(mc as ICommand).Execute(null); // This line leads to a debug output
```

**Comment by brianlagunas** [comment]
1. Just call the Task method directly in your code
2. You're overriding the wrong Execute method if you want to extend the Prism DelegateCommand. The comments above this method signature even indicate its for the internal invocation.

**Comment by multinerd** [comment]
> We will not add an async command because there is no such thing. The UI does not invoke commands async. There has already been a number of discussions around this.

@brianlagunas I hate to bother a professional but that line above was news to me. In addition to Prism, i was also using a modified version of Stephen Cleary's `AsyncCommand ` found [here](https://github.com/StephenCleary/Mvvm.Async/blob/master/src/Nito.Mvvm.Async/AsyncCommand.cs)

The following command binds to a button.
The important part for me in the ability to await `BusyIndicator.SetBusyAsync(LoadingMessageString, Login)` which presents a xaml loading message binded to a property on my ViewModel

I couldn't for the life of me get this to work using the `DelegateCommand`. It would always block my UI thread.

If theres no benefits to async commands, how would i write this properly with a `DelegateCommand`? Or maybe i misunderstood what you meant?

```csharp
		public IAsyncCommand LoginCommand
			=> new AsyncCommand(
					() => BusyIndicator.SetBusyAsync(LoadingMessageString, Login),
					() => !AuthenticateModel.UserNameOrEmailAddress.IsNullOrEmpty() &&
					      !AuthenticateModel.Password.IsNullOrEmpty(), false);

		private async Task Login()
		{
			if (LoginCommand.IsCancellationRequested) return;

			try
			{
				var response = await _accessTokenManager.LoginAsync();

				if (AuthenticateModel.RememberClient)
					_applicationSettingsManager.SetCredentials(AuthenticateModel);
				else
					_applicationSettingsManager.ClearCredentials();

				EventAggregator.GetEvent<UserLoginEvent>().Publish(response);
			}
			catch (UserFriendlyException e)
			{
				MessageBox.Show(e.Message, e.Message);
			}
			catch (Exception e)
			{
				MessageBox.Show(e.Message, e.Message);
			}
		}
.....
    public class BusyIndicatorModel : BindableObject
    {
        private string _busyMessage = "Loading...";
        private bool _isBusy;

        public bool IsBusy
        {
            get => _isBusy;
            set => SetProperty(ref _isBusy, value);
        }

        public string BusyMessage
        {
            get => _busyMessage;
            set => SetProperty(ref _busyMessage, value);
        }

        public async Task SetBusyAsync(string loadingMessage, Func<Task> function)
        {
            if (string.IsNullOrEmpty(loadingMessage))
                loadingMessage = "Loading...";

            try
            {
                ShowActivityIndicator(loadingMessage);

                await function();
            }
            finally
            {
                HideActivityIndicator();
            }
        }

        public void ShowActivityIndicator(string message)
        {
            IsBusy = true;
            BusyMessage = message;
        }

        public void HideActivityIndicator()
        {
            IsBusy = false;
            BusyMessage = string.Empty;
        }
    }
```
