### ISSUE TITLE
WeakDelegatesManager::RemoveListener takes 3 seconds when injecting view with 1000 subviews

### ISSUE THREAD

**Issue by hermestobias** [PrismLibrary/Prism#1796]
### Description

See provided HelloWorld application

### Steps to Reproduce

1. Drop in replace provided HelloWorld in latest Prism
2. Build in release
3. Start with Analyze -> Performance profiler.. -> CPU Usage
4. Click the "InjectViews" button in the app
Notice the lag, and in the profiler call tree you will see that Prism.Events.WeakDelegatesManager::RemoveListener takes a long time (2979 ms on my machine).

### Expected Behavior

Prism.Events.WeakDelegatesManager::RemoveListener should only take max 100 ms on my machine

### Actual Behavior

It takes 2979 ms.

### Basic Information

- Version with issue: Latest
- Last known good version: None
- IDE: Visual studio 2019

### Reproduction Link

Hello World attached as zip (drop in replace over Prisms WPF Sandbox)

[HelloWorld.zip](https://github.com/PrismLibrary/Prism/files/3182554/HelloWorld.zip)

**Comment by hermestobias** [comment]
Profile excerpt for HEAD version:

Function Name	Total CPU [unit, %]	Self CPU [unit, %]	Module
||| + [External Call] System.Windows.Application.Run(System.Windows.Window)$##6000277	4841 (88,44 %)	805 (14,71 %)	Multiple modules
|||| + Prism.Regions.Behaviors.DelayedRegionCreationBehavior::ElementLoaded	3670 (67,04 %)	0 (0,00 %)	Prism.Wpf.dll
||||| + Prism.Regions.Behaviors.DelayedRegionCreationBehavior::TryCreateRegion	3624 (66,20 %)	0 (0,00 %)	Prism.Wpf.dll
|||||| + Prism.Regions.DefaultRegionManagerAccessor::remove_UpdatingRegions	2979 (54,42 %)	0 (0,00 %)	Prism.Wpf.dll
||||||| + [External Code] Prism.Events.WeakDelegatesManager::RemoveListener	2979 (54,42 %)	23 (0,42 %)	Multiple modules
|||||||| + Prism.Events.WeakDelegatesManager+<>c__DisplayClass2_0::<RemoveListener>b__0	2956 (54,00 %)	115 (2,10 %)	Prism.Wpf.dll
||||||||| + [External Call] System.Reflection.RuntimeMethodInfo.CreateDelegate(System.Type, System.Object)$##6004642	2784 (50,86 %)	2784 (50,86 %)	Multiple modules
||||||||| + [External Code]	25 (0,46 %)	25 (0,46 %)	Multiple modules
||||||||| + [External Call] System.MulticastDelegate.Equals(System.Object)$##6000708	19 (0,35 %)	19 (0,35 %)	Multiple modules
||||||||| + Prism.Events.DelegateReference::TryGetDelegate	10 (0,18 %)	10 (0,18 %)	Prism.dll
||||||||| + [External Call] System.Reflection.RuntimeMethodInfo.get_Attributes()$##6004634	3 (0,05 %)	3 (0,05 %)	mscorlib.ni.dll
|||||| - Prism.Regions.Behaviors.DelayedRegionCreationBehavior::CreateRegion	641 (11,71 %)	0 (0,00 %)	Prism.Wpf.dll
|||||| - Prism.Regions.Behaviors.DelayedRegionCreationBehavior::Detach	2 (0,04 %)	0 (0,00 %)	Prism.Wpf.dll
|||||| - Prism.Regions.DefaultRegionManagerAccessor::GetRegionName	2 (0,04 %)	0 (0,00 %)	Prism.Wpf.dll
||||| - Prism.Regions.Behaviors.DelayedRegionCreationBehavior::UnWireTargetElement	45 (0,82 %)	0 (0,00 %)	Prism.Wpf.dll
||||| + Prism.Regions.Behaviors.DelayedRegionCreationBehavior::Detach	1 (0,02 %)	1 (0,02 %)	Prism.Wpf.dll

**Comment by hermestobias** [comment]
Profile excerpt from after applying PR #1793:

Function Name	Total CPU [unit, %]	Self CPU [unit, %]	Module
||| + [External Call] System.Windows.Application.Run(System.Windows.Window)$##6000277	1634 (76,75 %)	703 (33,02 %)	Multiple modules
|||| + Prism.Regions.Behaviors.DelayedRegionCreationBehavior::ElementLoaded	624 (29,31 %)	0 (0,00 %)	Prism.Wpf.dll
||||| + Prism.Regions.Behaviors.DelayedRegionCreationBehavior::TryCreateRegion	609 (28,60 %)	0 (0,00 %)	Prism.Wpf.dll
|||||| - Prism.Regions.Behaviors.DelayedRegionCreationBehavior::CreateRegion	549 (25,79 %)	0 (0,00 %)	Prism.Wpf.dll
|||||| + Prism.Regions.DefaultRegionManagerAccessor::remove_UpdatingRegions	58 (2,72 %)	0 (0,00 %)	Prism.Wpf.dll
||||||| + [External Code] Prism.Events.WeakDelegatesManager::RemoveListener	58 (2,72 %)	3 (0,14 %)	Prism.Wpf.dll
|||||||| + Prism.Events.WeakDelegatesManager+<>c__DisplayClass2_0::<RemoveListener>b__0	55 (2,58 %)	30 (1,41 %)	Prism.Wpf.dll
||||||||| - Prism.Events.DelegateReference::TargetEquals	15 (0,70 %)	11 (0,52 %)	Prism.dll
||||||||| + [System Call] clr.dll	5 (0,23 %)	5 (0,23 %)	clr.dll
||||||||| + [External Call] System.Reflection.RuntimeMethodInfo.get_Attributes()$##6004634	5 (0,23 %)	5 (0,23 %)	mscorlib.ni.dll
|||||| - Prism.Regions.Behaviors.DelayedRegionCreationBehavior::Detach	1 (0,05 %)	0 (0,00 %)	Prism.Wpf.dll
|||||| - Prism.Regions.DefaultRegionManagerAccessor::GetRegionName	1 (0,05 %)	0 (0,00 %)	Prism.Wpf.dll
||||| - Prism.Regions.Behaviors.DelayedRegionCreationBehavior::UnWireTargetElement	15 (0,70 %)	0 (0,00 %)	Prism.Wpf.dll

**Comment by hermestobias** [comment]
Notice how Prism.Events.WeakDelegatesManager::RemoveListener now only takes 58 ms instead of 2979 ms.

**Comment by brianlagunas** [comment]
Thank you for the sample. It made the issue very obvious 😃
