### ISSUE TITLE
Unable to mock the INavigateInternal interface because it's internal rather than public

### ISSUE THREAD

**Issue by Project4MobileDev** [PrismLibrary/Prism#1797]
### Description
Unable to mock the INavigateInternal interface because it's internal rather than public. Could this interface be made public please? I realise that it's possible to mock the navigation service by stubbing it but it'd be really useful to be able to use Moq and to mock the interface. 

I see that this was considered in the past but hasn't been implemented yet so I thought I'd request it.
https://github.com/PrismLibrary/Prism/issues/1312#issuecomment-435155550
https://github.com/PrismLibrary/Prism/issues/1365#issuecomment-442489586

Cheers,
Stephen

**Comment by brianlagunas** [comment]
This has been implemented and is available in the latest preview.

**Comment by Project4MobileDev** [comment]
Ah great, thanks for the quick reply
