### ISSUE TITLE
InteractionRequest not firing in OnNavigatedTo (tested with Prism 5.0)

### ISSUE THREAD

**Issue by znakeeye** [PrismLibrary/Prism#180]
Since I cannot upgrade to Prism 6.0 at the time, I can only confirm this behavior in Prism 5.0. When raising an interaction request inside *OnNavigatedTo* nothing happens. I can understand that this occurs if the view has not been completely loaded yet (workaround?), but shouldn't I get an error message of some kind?

```C#
public void OnNavigatedTo(NavigationContext navigationContext)
{
    MyInteractionRequest.Raise(...);
}
```

```XAML
</UserControl.Resources>
<i:Interaction.Triggers>
	<prism:InteractionRequestTrigger SourceObject="{Binding MyInteractionRequest, Mode=OneWay}">
		<local:PopupWindowAction IsModal="True" />
	</prism:InteractionRequestTrigger>
</i:Interaction.Triggers>
```

**Comment by brianlagunas** [comment]
Are you expecting this to fire when changing tabs, or just when you initially navigate to a tab?

**Comment by znakeeye** [comment]
I'm expecting an exception. Or, it would be nice for it to show before the navigation is completed.

I solved this using a navigation callback where I call "GoBack()" on error. However, I still think that the framework should warn when the interaction request cannot be found or executed. Invalid bindings show a "nice" warning in the output window, but an invalid interaction request shows nothing...

**Comment by brianlagunas** [comment]
I'm still a little confused.  Do you have a sample that can demonstrate your issue?  Are you saying that the Notification isn't shown yet because the View hasn't been loaded?  You mentioned an error. Where does this error occur?  Is it an exception, or an output error.  What does the error say?

**Comment by znakeeye** [comment]
**Problematic implementation:** The Notification isn't shown because the View hasn't loaded (I guess...) when *OnNavigatedTo* is being called. **The problem is that there is NO error**. I would expect at least a warning message in the Output window.

**Alternative implementation:** The error I'm referring to comes from a *non-handled* custom exception in the *OnNavigatedTo* method, which is then propageted to the callback defined in *RequestNavigate*. Thus, to successfully show an interaction request when navigation fails, I do the following.

**THIS works:**
```C#
public void OnNavigatedTo(NavigationContext navigationContext)
{
     throw new Exception("Booya!");
}

// Caller:
regionManager.RequestNavigate(..., OnNavigationCallback);

private void OnNavigationCallback(NavigationResult navigationResult)
{
    if (navigationResult.Result == false)
    {
        ConfirmationRequest.Raise(...);
    }
}
```

So, my first implementation is obviously wrong. Prism does not allow me to show my interaction request in *OnNavigatedTo*, but... I had to realize this by myself. **No error! :)**

**Comment by brianlagunas** [comment]
I would probably use an event trigger for the loaded event of the view and then invoke a command which would raise the notification.  You don't want to go throwing exceptions around just to show a dialog.

**Comment by znakeeye** [comment]
I just realized there is an interface for this. *IConfirmNavigationRequest*

Anyway, why not throw an error if the interaction request cannot be raised?

**Comment by brianlagunas** [comment]
Because we cannot detect if the request is not received by the Interaction request trigger.  The InteractionRequestTrigger is bound to a SourceObject.  It uses reflection to listen for the Raised event off of the bound request object.  The framework handles this, and we have no way of knowing if the trigger received the event or not.
