### ISSUE TITLE
NavigationService.GetNavigationUriPath reports wrong path just after initial deep-link nav

### ISSUE THREAD

**Issue by jmegner** [PrismLibrary/Prism#1800]
### Steps to Reproduce

1.  Launch [PrismNavUriBug](https://github.com/jmegner/PrismNavUriBug) app.
2.  Notice that ViewA reports wrong path (see the [README.md](https://github.com/jmegner/PrismNavUriBug#steps-to-reproduce-bug) for more info)

Perhaps more generally: 1) Do an initial deep-linking nav. 2) Before any other nav, look at NavigationService.GetNavigationUriPath. 

### Expected Behavior
NavigationService.GetNavigationUriPath should have returned "/Navigation/MainPage/ViewA".

### Actual Behavior
NavigationService.GetNavigationUriPath returned "/Navigation/ViewA".

### Basic Information
- Prism.DryIoc.Forms 7.1.0.431
- Xamarin.Forms 3.2.0.839982
- Visual Studio

### Reproduction Link

[PrismNavUriBug](https://github.com/jmegner/PrismNavUriBug) repo.  README.md has steps and screenshots.

**Comment by brianlagunas** [comment]
You shouldn't call that method in the OnNavAware methods because Xamarin hasn't finished processing. If you add a button to ViewA and then get the nav path on the button click it works just fine.  Remember, navigation is async, and Prism is just calling a method when we programatically add a view to the XF nav stack. It doesn't mean that the nav process is finished until the "await" returns from the nav call.

**Comment by jmegner** [comment]
Thanks, @brianlagunas, I've added a "Update Below" button to my PrismNaviUriBug project, and acknowledged your resolution of the bug report.  Since OnNavigatedTo executes concurrently with the navigation, I'm wondering what is the easiest thing to hook into so you execute something once navigation is complete, rather than this button approach? (I'm hoping for something I can put in the destination page, not the source page.)

**Comment by brianlagunas** [comment]
You could try the IPageLifecycleAware in the OnAppearing.  That's supposed to fire when the page is actually appearing on glass.

**Comment by jmegner** [comment]
Awesome, thanks.

**Comment by brianlagunas** [comment]
Let me know if that works. I'm curious too :)

**Comment by dansiegel** [comment]
It should theoretically work on account of OnAppearing is triggered by Xamarin.Forms and outside of the actual NavigationService so the NavigationService should be complete as I recall.
