### ISSUE TITLE
Defined Bindable property(say ListView's Selecteditem's)value is not reflected to PCL element when changed programmatically in OnNavigatingTo method

### ISSUE THREAD

**Issue by GnanaPriyaNamasivayam** [PrismLibrary/Prism#1802]
### Description

SelectedItem value is not reflected in UI when changed in OnNavigatingTo method.

### Steps to Reproduce

1.Run the sample. 
2. Check in OnNavigatingTo method, SelctedItem value is defined.
3. But in UI selection background color is not appeared for the programmatically SelectedItem

### Expected Behavior
BackgroundColor should appear for the Programmatically SelectedItem.

### Actual Behavior
BackgroundColor does not appear for the Programmatically SelectedItem.

### Basic Information

- Version with issue: 3.6
- Last known good version:
- Xamarin.Forms version:
- IDE:

### Reproduction Link

http://www.syncfusion.com/downloads/support/directtrac/general/ze/ListViewPrism-219641795

**Comment by brianlagunas** [comment]
Prism has no control over the binding system or how the syncfusion control behaves to data changes.
