### ISSUE TITLE
Replace System.Windows.Interactivity.dll with Microsoft.Xaml.Behaviors

### ISSUE THREAD

**Issue by hillin** [PrismLibrary/Prism#1804]
### Description

Since the world is merging in to .NET Core 3.0, I think the .NET Framework 4.5 assembly `System.Windows.Interactivity.dll` should be replaced by [Microsoft.Xaml.Behaviors](https://github.com/microsoft/XamlBehaviorsWpf), which not only supports .NET Framework, but also will [have.NET Core 3.0 support soon enough](https://github.com/microsoft/XamlBehaviorsWpf/pull/20).

**Comment by wzswzd** [comment]
so how should i do to binding a control`s event not using `System.Windows.Interactivity.dll` in .Net Core 3.0......at present......

**Comment by brianlagunas** [comment]
I'm actually on the WPF Behaviors team. We have been unable to get MS to actually participate in the project so it is moving extremely slow.  I even had a PR for Prism to add support, but MS has been dragging their feet.  Until this project is moved froward, we aren't supporting it just yet.
