### ISSUE TITLE
Prism WPF 7.2.0.1233-pre: RequestNavigation is not working

### ISSUE THREAD

**Issue by yingyyliu** [PrismLibrary/Prism#1805]
### Description
 I'm trying to navigate to different views based on the selection in the combobox for a pop-up user control. Unable to load the views.

### Steps to Reproduce
1.  Please open my demo project  [NavigationUsingRegionsDemo](https://github.com/yingyyliu/NavigationUsingRegionsDemo)
 
2. In the ViewModels\Settings\SettingViewModel class, this is where I put in the navigation to different views depending on the combobox selection.

The views are already registered for navigation in App.xaml.cs RegisterTypes() method.
 
3. When I try to debug, I found that the _regionManager doesn't contain the ViewInjectionRegion. This is the region defined in the Setting view.

### Expected Behavior
Able to navigate to different view based on combobox selected item.

### Actual Behavior
No view is displayed.

### Basic Information

- Version with issue: Prism WPF 7.2.0.1233-pre, Prism DryIoC 7.2.0.1233-pre, .NET Framework v4.8                            
- IDE: Visual Studio 2019 v16.1

### Reproduction Link
[NavigationUsingRegionsDemo](https://github.com/yingyyliu/NavigationUsingRegionsDemo)

**Comment by brianlagunas** [comment]
This is just the nature of how the RegionManager works in prism. Since a new window is being opened, it has lost it's region manager that was assigned during the app initialization process.  All you have to do is assign the region manager like this:

```
        public SettingsMainWindow(IRegionManager regionManager)
        {
            InitializeComponent();
            RegionManager.SetRegionManager(this, regionManager);
            regionManager.RegisterViewWithRegion("SettingRegion", typeof(Setting));
        }
```

This is a very common mistake that is made, and something I should probably build directly into the dialog service.

**Comment by brianlagunas** [comment]
This will be fixed in the next release. Thanks for reporting it.

**Comment by noufionline** [comment]
Hi @brianlagunas ,
Can please extend this implementation to support ScopedRegion as well. either make CreateDialogWindow as protected so that we can grab the window in an inherited dialogservice and set the scoped region or give a better option consistent with the prism api

**Comment by yingyyliu** [comment]
Thanks. I've have tried solution provided, it worked for the first click but on the second click, it throw up the above error. May I ask when can I get the new Prism WPF package.

Thank You

**Comment by brianlagunas** [comment]
You will need to implement scoped regions ot support showing multiple instances of a dilaog that has a region in it.  This course shows you how https://www.pluralsight.com/courses/prism-showing-multiple-shells

**Comment by noufionline** [comment]
Hi @brianlagunas 
Can I Suggest something?

If you can make CreateDialogWindow as protected virtual any one needs to use Scoped region manager behavior can override it and attach the scoped region manager to the window.

Suppose I am using IRegionManagerAware interface as you suggested in your course which contains the Scoped RegionManager property.

so we will required 2 changes.

1. protected virtual CreateDialogWindow.
2. A way to set Scoped RegionManager property of IRegionManagerAware interface



````
//if you can wrap this code in protected virtual method which returns the content then we can assign the RegionManager here
var content = _containerExtension.Resolve<object>(dialogName);

//provide us something like
protected virtual IDialogWindow  CreateDialogWindow()
{
   return _containerExtension.Resolve<IDialogWindow>();
}
protected virtual object CreateDialogContent()
{
    return _containerExtension.Resolve<object>(dialogName);
}

//the we can override the method and set the scoped region manager 

protected override IDialogWindow  CreateDialogWindow()
{
    var dialogWindow = base.CreateDialogWindow();
     var scopedRegionManager = _regionManager.CreateRegionManager();
     RegionManager.SetRegionManager((DependencyObject)dialogWindow, scopedRegionManager);
}

protected override object CreateContent()
{
   var content=base.CreateContent();
  if (content IRegionManagerAware rma)
  {
       rma.RegionManager = scopedRegionManager;
  }
}
````
What do you think?

If you allow me I will submit a pull request.

**Comment by brianlagunas** [comment]
@noufionline please create an issue before submitting a PR 😃 

You do not need to go through all this work for scoped regions. Just add the scoped region in the code-behind of the dialog, or create a custom Window host and do it there.

**Comment by noufionline** [comment]
@brianlagunas 😃. Trying to contribute which ever way I can. I will take of it next time. Thanks.

**Comment by fuine6** [comment]
> This is just the nature of how the RegionManager works in prism. Since a new window is being opened, it has lost it's region manager that was assigned during the app initialization process. All you have to do is assign the region manager like this:
> 
> ```
>         public SettingsMainWindow(IRegionManager regionManager)
>         {
>             InitializeComponent();
>             RegionManager.SetRegionManager(this, regionManager);
>             regionManager.RegisterViewWithRegion("SettingRegion", typeof(Setting));
>         }
> ```
> 
> This is a very common mistake that is made, and something I should probably build directly into the dialog service.

I tried this code, it works fine the first time when I open the SettingsMainWindow.
If I close the SettingsMainWindow and open it again, it will cause an exception.

```
An exception occurred while creating a region with name 'ViewInjectionRegion'. The exception was: System.ArgumentException: Region with the given name is already registered: ViewInjectionRegion
```

How can I solve it?
