### ISSUE TITLE
DryIoc throws exception on iOS

### ISSUE THREAD

**Issue by dansiegel** [PrismLibrary/Prism#1806]
### Description

DryIoc 4.0 adds support for the FastExpressionCompiler which makes it even faster, however this requires support for JIT which is not supported on iOS. The rules for the container need to be updated to remove the FastExpressionCompiler when running on iOS.

#### WORK AROUND

For those experiencing the issue you can resolve it by adding the following to your PrismApplication

```cs
protected override Rules CreateContainerRules()
{
    return base.CreateContainerRules()
        .WithoutFastExpressionCompiler();
}
```

### Steps to Reproduce

1. Use latest 7.2 preview for Prism.DryIoc.Forms
1. Run on iOS

### Expected Behavior

No Exception

### Actual Behavior

```
Attempting to JIT compile method 
'FastExpressionCompiler.LightExpression.ExpressionCompiler:TryCompile (FastExpressionCompiler.LightExpression.ExpressionCompiler/ClosureInfo&,
    System.Type,System.Type[],
    System.Type,FastExpressionCompiler.LightExpression.Expression,
    System.Collections.Generic.IReadOnlyList`1<FastExpressionCompiler.LightExpression.ParameterExpression>,bool)' 
while running in aot-only mode. 
See https://docs.microsoft.com/xamarin/ios/internals/limitations for more information.
```

### Basic Information

- Version with issue: 7.2.0.1233-pre 
- Last known good version: 7.2.0.1038-pre 
- Xamarin.Forms version: n/a
- IDE: n/a

**Comment by YZahringer** [comment]
Shouldn't it be disabled only on the iOS platform?

**Comment by dansiegel** [comment]
No. The FastExpressionCompiler will not work anytime you use AOT which would include Android.
