### ISSUE TITLE
[Bug] Prism WPF 7.1 & AvalonDock

### ISSUE THREAD

**Issue by ChristianPerner** [PrismLibrary/Prism#1816]
### Description

Using AvalonDock from XCeed Extended WPF Toolkit can not find DockingManager defined region.
With Prism 6.3 there are no issues.
Using a ContenControl instead of DockingManager (see comment in Views\MainWindow.xaml) has no issue.

The DockingManager definition in MainWindow is only a shrinked example, the DockingManagerRegionAdapter is equal to our project.

### Steps to Reproduce

1. clone https://github.com/ChristianPerner/AvalonDockTest.git
2. Build
3. Run

### Expected Behavior

No KeyNotFoundException

### Actual Behavior
Exception thrown: 'System.Collections.Generic.KeyNotFoundException' in Prism.Wpf.dll

### Basic Information

- Version with issue: 7.1.0.431
- Last known good version: 6.3
- IDE: Visual Studio 2019 16.1.1

### Reproduction Link

https://github.com/ChristianPerner/AvalonDockTest.git

**Comment by brianlagunas** [comment]
Not a bug, its your code.

Use this
```
regionAdapterMappings.RegisterMapping(typeof(DockingManager), Container.Resolve<DockingManagerRegionAdapter>());
```

**Comment by ChristianPerner** [comment]
Thank you very much!
Maybe a change in Prism? Because my line was fine in Prism 6.3.

**Comment by brianlagunas** [comment]
Not a change in Prism, most likely a change in the container. That line was a bad implementation anyways.
