### ISSUE TITLE
No longer able to compile after upgrading to XF 4.0.0 Service Release 1

### ISSUE THREAD

**Issue by pasteusernamehere** [PrismLibrary/Prism#1818]
After upgrading to XF 4.0.0 SR1 I can no longer compile my solution.

Error |   | Position 5:14. Missing a public static GetAutowireViewModel or a public instance property getter for the attached property "Prism.Mvvm.ViewModelLocator.AutowireViewModelProperty" | TestCase | C:\Users\Administrator\Documents\Code\TestCase\TestCase\TestCase\Views\TestPage.xaml   

### Steps to Reproduce

1. Using VS2019 create a new XF app.
2. Update XF to latest service release.
3. Add Prism.DryIoc.Forms to projects.
4. Add a new Prism ContentPage using the template pack.
5. Compile the solution.

### Expected Behavior
Clean compile

### Actual Behavior
Compile failure

Error |   | Position 5:14. Missing a public static GetAutowireViewModel or a public instance property getter for the attached property "Prism.Mvvm.ViewModelLocator.AutowireViewModelProperty" | TestCase | C:\Users\Administrator\Documents\Code\TestCase\TestCase\TestCase\Views\TestPage.xaml  

### Basic Information

- Version with issue: XF 4.0.0.471375 Prism.DryIoc.Forms 7.1.0.431
- Last known good version: XF 4.0.0.425677 Prism.DryIoc.Forms 7.1.0.431
- IDE: VS2019

**Comment by dansiegel** [comment]
@pasteusernamehere please include a sample to reproduce this.

**Comment by pasteusernamehere** [comment]
I have a sample but it appears that the Xamarin Forms team has found the issue. I have fix is pending. Sorry to bother...

BTW thanks for all the hard work on Prism!  Love it.
