### ISSUE TITLE
[Enhancement] Abstractions in Prism.Core

### ISSUE THREAD

**Issue by weitzhandler** [PrismLibrary/Prism#1819]
## Summary

Please bring abstractions (e.g. `IPageDialogService`) in Prism.Core or in one of the lower level cross plat projects.

## API Changes

No API change, just the interfaces such as `IPageDialogService`, `IDeviceTimer` etc. should go in a more general project, to make it easier for framework authors (such as [Uno Platform](https://github.com/nventive/Uno.Prism) to write xplat implementations of those interfaces.
I'm aware to the fact that these interfaces were made to address XF, but in fact even in a WPF it might be worth accessing dialogs using the Prism interfaces rather than statically with the system, so we could potentially wrap the WPF modals and have them accessed with `IPageDialogService`, hence making the VMs portable between the various frameworks.

## Intended Use Case

Make it more accessible to adapt the prism library in xplat apps.

**Comment by brianlagunas** [comment]
An abstraction will only go into Core if it will apply to all supported platforms. Those interfaces do not belong in Core.

**Comment by weitzhandler** [comment]
Thanks for your response!
