### ISSUE TITLE
[Enhancement] Preffered dialog size

### ISSUE THREAD

**Issue by kalatchev** [PrismLibrary/Prism#1820]
## Summary

I would like to have View (UserControl) with some MinWidth and MinHeight, but when I show it as dialog trough newlly added IDialogService, I would like to set some (lager) default values. My idea is to put other styles in snippet 
```xaml
<prism:Dialog.WindowStyle>
        <Style TargetType="Window">
            <Setter Property="ResizeMode" Value="CanResizeWithGrip"/>
            <Setter Property="ShowInTaskbar" Value="True"/>
            <!-- SEE HERE -->
            <Setter Property="Width" Value="880"/>
            <Setter Property="Height" Value="700"/>
        </Style>
    </prism:Dialog.WindowStyle>
```
It seem will work with two lines of change (see bellow)

## API Changes

I think this will be possabe if we change couple of code lines. Idea is first to set `window.Content` (wich will set Window's size to minimum size of ocntrol), **and after that** to invoke `window.Style = windowStyle` which will resize the window **and** control to desired size.

```c#
   var windowStyle = Dialog.GetWindowStyle(dialogContent);
   if (windowStyle != null)
         window.Style = windowStyle;

   //Just change sequence - first set content, and afetr that set styles.

   window.Content = dialogContent;
   window.DataContext = viewModel; //we want the host window and the dialog to share the same data contex
```

## Intended Use Case

IMHO many users will be happy to have bit more control over dialogs.

P.S. It will be too dificult for me to make PR, as I have not requirements on my computer, such as .NET Core 3.

**Comment by brianlagunas** [comment]
Usually setting SizeToContent is recommended, but this is an easy change.  Thank for reporting it.

**Comment by brianlagunas** [comment]
I just tested this and it works perfectly for me as-is. You will need to provide a sample that reproduces this issue and i will reopen it.

**Comment by kalatchev** [comment]
Yes, it works. The problem was in my custom dialog window. Thanks for your attention.
