### ISSUE TITLE
Possible NullReferenceException in EventBase

### ISSUE THREAD

**Issue by Stoeoef** [PrismLibrary/Prism#1821]
**Note: This Defect is likely fixed on master. Only 7.1 should be affected.**
I'm posting this just in case anybody else stumbles onto this defect. Downgrading to 7.0 solved the issue for me. The symptom is the following stacktrace:

> System.NullReferenceException: Object reference not set to an instance of an object.
   at Prism.Events.EventBase.InternalPublish(Object[] arguments) in D:\a\1\s\Source\Prism\Events\EventBase.cs:line 64
   at Prism.Events.PubSubEvent`1.Publish(TPayload payload) in D:\a\1\s\Source\Prism\Events\PubSubEvent.cs:line 259

### Description
I'm getting infrequent NullReference exceptions with **Prism 7.1.0.431**.
After browsing the source code I believe I have an idea where this error may originate (See [EventBase, Tag 7.1.0](https://github.com/PrismLibrary/Prism/blob/9d05095de2275898711b12c73ec157a4038649db/Source/Prism/Events/EventBase.cs#L114)):

```c#
private List<Action<object[]>> PruneAndReturnStrategies()
{
  lock (Subscriptions)
  {
    Prune();
   // GC may run here
    return _subscriptions.Select(x => x.GetExecutionStrategy()).ToList();
  }
}
```
If the gc runs at the inserted comment, `GetExecutionStrategy` may return `null`, which leads to a null reference exception when it is is being invoked in `EventBase::InternalPublish`.

This was introduced by #1507 and (likely unintentionally) fixed by 57ad662f693cb9877d55046b7552291458bcdd02 .

As mentioned at the beginning, please do close this issue as it is already fixed. Also, it is a rare occurrence of a "race condition" with the GC. I believe this is interesting from an educational standpoint, showing some subtleties that WeakReferences can introduce.

### Steps to Reproduce
This happens infrequently, inserting a `System.GC.Collect()`at the above marked position is likely enough to make this reproducible.

### Basic Information

- Version with issue: Prism 7.1.0.431
- Last known good version: 7.0

**Comment by brianlagunas** [comment]
Thank you for reporting this. I will see if there is an easy fix. Unless you have already found one you can share :)

**Comment by brianlagunas** [comment]
Actually, can you test this against the latest builds on MyGet and see if you can still get the error?
