### ISSUE TITLE
Prism Template Pack: Reflected code for MemberDeclarationSyntaxWalker indicates infinite recursion in Visit implementation

### ISSUE THREAD

**Issue by Pepsi1x1** [PrismLibrary/Prism#1823]
Using ILSpy to inspect MemberDeclarationSyntaxWalker.cs in DeveloperToolkit.RoslynSDK produces reflected code that exhibits a StackOverflowException. As the first syntax node is almost never a Member Declaration and the base method is never called this method simply recurses without executing any other methods or any way to break out of the recursion.

`public override void Visit(SyntaxNode node)
	{
		if (node is MemberDeclarationSyntax)
		{
			Members.Add(node as MemberDeclarationSyntax);
		}
		else
		{
			this.Visit(node);
		}
	}`

### Steps to Reproduce

1. Load DeveloperToolkit.RoslynSDK in ILSpy
2. Navigate to MemberDeclarationSyntaxWalker
3. Observe the implementation of the Visit method 

### Expected Behavior

Implementation as follows

`public override void Visit(SyntaxNode node)
        {
            if (node is MemberDeclarationSyntax)
            {
                Members.Add(node as MemberDeclarationSyntax);
            }

            base.Visit(node);
        }`

### Actual Behavior

StackOverflowException

### Basic Information

- Version with issue: Prism Template Pack 2.2.0.434 (Stable) for MonoDevelop 7.6.9

**Comment by dansiegel** [comment]
@Pepsi1x1 Please provide some context here. Is this Mac/Windows... what template specifically are you using.. etc.

**Comment by Pepsi1x1** [comment]
@dansiegel this is Mac, the issue affects generating the base class constructor for the View Model (MVVMFile) when creating any of the XF Pages templates

**Comment by dansiegel** [comment]
@Pepsi1x1 what version of VSfM are you using?

**Comment by Pepsi1x1** [comment]
2019, however this is the mpack file hosted on the mono addins repo for VS for Mac 2017

**Comment by Pepsi1x1** [comment]
@dansiegel 2.2.0.434 (Stable) for MonoDevelop 7.6.9

**Comment by dansiegel** [comment]
sorry but we are not supporting VSfM 2019 at this time. Please see the open issue on the matter. We hope to resolve some issues soon. See issue #1755
