### ISSUE TITLE
Prism Template Pack: Reflected code returns null for configuration if no settings JSON exists

### ISSUE THREAD

**Issue by Pepsi1x1** [PrismLibrary/Prism#1824]
### Description

When inspecting the code reflected with ILSpy for the load configuration method in DeveloperToolkit.VisualStudio.Mac.Helpers.ConfigurationLoader, if no configuration file exists then the method returns a null configuration object before the finally block can execute.

### Expected Behavior

`public static DeveloperToolkitConfiguration LoadConfiguration(DotNetProject project)
        {
            DeveloperToolkitConfiguration developerToolkitConfiguration = null;
            try
            {
                developerToolkitConfiguration = JsonConvert.DeserializeObject<DeveloperToolkitConfiguration>(File.ReadAllText(Path.Combine(project.BaseDirectory, "toolkit.config.json")));
                if (developerToolkitConfiguration.ViewModelBase != null && !string.IsNullOrWhiteSpace(developerToolkitConfiguration.ViewModelBase.Name))
                {
                    return developerToolkitConfiguration;
                }
            }
            catch
            {

            }
            finally
            {
                if (developerToolkitConfiguration == null)
                {
                    developerToolkitConfiguration = new DeveloperToolkitConfiguration
                    {
                        ViewModelBase = GetDefaultViewModelBase(project)
                    };
                }
            }
            return developerToolkitConfiguration;
        }`

### Actual Behavior

`public static DeveloperToolkitConfiguration LoadConfiguration(DotNetProject project)
{
	//IL_0003: Unknown result type (might be due to invalid IL or missing references)
	//IL_001f: Unknown result type (might be due to invalid IL or missing references)
	DeveloperToolkitConfiguration developerToolkitConfiguration = null;
	try
	{
		if (!File.Exists(Path.Combine(FilePath.op_Implicit(project.get_BaseDirectory()), "quickstart.config.json")))
		{
			return developerToolkitConfiguration;
		}
		developerToolkitConfiguration = JsonConvert.DeserializeObject<DeveloperToolkitConfiguration>(File.ReadAllText(Path.Combine(FilePath.op_Implicit(project.get_BaseDirectory()), "toolkit.config.json")));
		if (developerToolkitConfiguration.ViewModelBase != null && !string.IsNullOrWhiteSpace(developerToolkitConfiguration.ViewModelBase.Name))
		{
			return developerToolkitConfiguration;
		}
		developerToolkitConfiguration.ViewModelBase = GetDefaultViewModelBase(project);
		return developerToolkitConfiguration;
	}
	finally
	{
		if (developerToolkitConfiguration == null)
		{
			developerToolkitConfiguration = new DeveloperToolkitConfiguration
			{
				ViewModelBase = GetDefaultViewModelBase(project)
			};
		}
	}
}`

### Basic Information

- Version with issue: Prism Template Pack 2.2.0.434 (Stable) for MonoDevelop 7.6.9

**Comment by dansiegel** [comment]
@Pepsi1x1 Please provide some context here. Is this Mac/Windows... what template specifically are you using.. etc.

**Comment by Pepsi1x1** [comment]
@dansiegel This is Mac, it applies to all templates that use an MVVM file as LoadConfiguration is called by MVVMFileDescriptionTemplate in the Templating assembly

**Comment by dansiegel** [comment]
VSfM 2019 is not currently supported. See issue #1755

**Comment by Pepsi1x1** [comment]
@dansiegel I'm really not sure why this issues has been closed, they relate to the package for VSfM 2017. Support for VSfM 2019 is inconsequential to this issue.
