### ISSUE TITLE
Please Provide an AsyncCommand which will accept Task as method

### ISSUE THREAD

**Issue by noufionline** [PrismLibrary/Prism#183]
Hi Brians,

DevExpress MVVM Framework has a nice little Async Delegate command which will encapsulates all the required behaviors including CancellationToken. It would be nice to have it in Prism built in.

Please have a look at this link for more information

https://documentation.devexpress.com/#WPF/CustomDocument17354

The source code for Async Command can be found on this link

https://github.com/DevExpress/DevExpress.Mvvm.Free/blob/master/DevExpress.Mvvm/DelegateCommand.cs

**Comment by brianlagunas** [comment]
Prism already provides an async command.  Granted there is no cancellation token support.

**Comment by noufionline** [comment]
Any possibilities of adding cancellation support?

**Comment by brianlagunas** [comment]
There is always a possibility.  Especially if someone wants to submit a PR for it.

**Comment by brianlagunas** [comment]
We aren't going to be adding this at this time.
