### ISSUE TITLE
Best practice to load modules from different sources?

### ISSUE THREAD

**Issue by hillin** [PrismLibrary/Prism#1830]
### Description

In Prism 7, what's the best practice to load modules from different sources (e.g. different directories)?

There was a `AggregateModuleCatalog` in the [samples repository](https://github.com/PrismLibrary/Prism-Samples-Wpf) once upon a time, but not anymore. When I was trying to write my own one in Prism 7, I found it difficult to implement cross-catalog module dependency. For example:
- I have two directories, say `Modules` and `Plugins`, which are loaded by two `DirectoryModuleCatalog`s respectively;
- `PluginA` in the `Plugins` folder declares to be dependent on `ModuleA` in the `Modules` folder;
- The two `DirectoryModuleCatalog` are aggregated by an `AggregateModuleCatalog`, which implements its `Initialize` method as follows:
```
public void Initialize()
{
    foreach (var catalog in this.Catalogs)
    {
        catalog.Initialize();
    }
}
```
This however causes a `ModularityException` when the `Initialize` method is called on the second catalog (for the `Plugins` directory). It seems in `ModuleCatalogBase.Validation`, it tries to resolve dependencies for `PluginA` within the catalog, but the dependency `ModuleA` is in another catalog.

I realized it may be possible to write a, say, `MultiDirectoryModuleCatalog` which accepts multiple directories, but I'd like to see if there is a better approach first.

**Comment by dansiegel** [comment]
All questions should be posted on StackOverflow.
