### ISSUE TITLE
IModuleInitializer + CancellationToken

### ISSUE THREAD

**Issue by znakeeye** [PrismLibrary/Prism#1832]
When you have multiple modules with heavy code in `IModule.OnInitialized(IContainerProvider)` it would be nice to have the ability to terminate the module initialization. E.g. when closing a splash screen waiting for modules to load.

```c#
protected override void InitializeModules()
{
    // TODO: Would be nice if we could use CancellationToken when loading modules...
    var manager = Container.GetExportedValue<IModuleManager>();
    manager.Run();
}
```

**Comment by brianlagunas** [comment]
This is not something that can be canceled.

**Comment by znakeeye** [comment]
> This is not something that can be canceled.

Yes it can. Sort of. When you have N modules, you can cancel the initialization of the remaining modules when a module in the list has been loaded.
