### ISSUE TITLE
[Bug] Prism.DryIoc incompatible with later DryIoc

### ISSUE THREAD

**Issue by richbryant** [PrismLibrary/Prism#1833]
### Steps to Reproduce

1. Start a Prism application (I used WPF) with DryIoc as the Ioc Container
2. Use GetContainer to register factory types
3. Install DryIoc 4.x from nuget

### Expected Behavior

Compatibility

### Actual Behavior

Error	CS0012	
The type 'IContainer' is defined in an assembly that is not referenced. You must add a reference to assembly 'DryIoc, Version=3.0.2.0, Culture=neutral, PublicKeyToken=null'.

**Comment by bartlannoeye** [comment]
The Prism libraries are compiled against specific versions of the IoC containers, Xamarin.Forms etc. If you use the latest previews, you can use DryIoC 4.0.4 (see [code](https://github.com/PrismLibrary/Prism/blob/master/Source/Wpf/Prism.DryIoc.Wpf/Prism.DryIoc.Wpf.csproj#L17))

**Comment by dansiegel** [comment]
@richbryant a couple of things to note here...

- Which NuGet for DryIoc did you install? They have a funky naming pattern where if you install the `DryIoc` NuGet you get source code which wouldn't work with Prism. We use the `DryIoc.dll` NuGet package.
- The latest Prism 7.2 preview is compiled against DryIoc 4

**Comment by richbryant** [comment]
I was using the DryIoc.dll package but I guess I'll have to look forward to the preview going to full release, since this is work stuff.
