### ISSUE TITLE
android crash when changing splashscreen image on axml file.

### ISSUE THREAD

**Issue by mohammedmsadiq** [PrismLibrary/Prism#1834]
get this error when trying to change image on splashscreen.axml file see the screenshot bellow;
<img width="1103" alt="Screenshot 2019-06-15 at 01 12 36" src="https://user-images.githubusercontent.com/48685203/59544643-70b78b80-8f0b-11e9-8595-bf8d7d8bdaf1.png">

below is my code on the splashscreen page.
<img width="1261" alt="Screenshot 2019-06-15 at 01 12 52" src="https://user-images.githubusercontent.com/48685203/59544649-7b722080-8f0b-11e9-881c-5ddc5cc76fe8.png">

    [Activity(Label = "@string/ApplicationName",
              Icon = "@mipmap/ic_launcher",
              Theme = "@style/SplashTheme",
              MainLauncher = true)]
    public class SplashActivity : AppCompatActivity
    {
        protected override void OnCreate(Bundle savedInstanceState)
        {
            base.OnCreate(savedInstanceState);
            var intent = new Intent(Application.Context, typeof(MainActivity));
            if (Intent.Extras != null)
                intent.PutExtras(Intent.Extras);
            StartActivity(intent);
            Finish();
        }
    }

**Comment by brianlagunas** [comment]
I'm sorry, but this is not related to Prism. You should ask this question on a more appropriate forum such as the Xamarin forums or StackOverflow.
