### ISSUE TITLE
[Enhancement] Bring back concept of separate Bootstrapper from Application

### ISSUE THREAD

**Issue by aesalazarln** [PrismLibrary/Prism#1836]
## Summary

Instead of sub-classing `PrismApplicationBase` from `Application`, go back to the decoupling pattern with a separate Bootstrapper class.  This will allow for Multiple UI threads.  I relaize this is not a trivial request and would be willing to contribute in any way I an.

## API Changes

Instead of 

    public abstract class PrismApplicationBase : Application

we could have 

    public abstract class PrismBootstrapperBase

This class would be something like 95% the same, code-wise (I have done it on a project).  There are only a few lines of code we would need to modify:

        protected override void OnStartup(StartupEventArgs e)
        {
            base.OnStartup(e);
            InitializeInternal();
        }

would become something like

        protected PrismApplicationBase()
        {
            InitializeInternal();
        }

And 

        protected virtual void InitializeShell(Window shell)
        {
            MainWindow = shell;
        }

        protected virtual void OnInitialized()
        {
            MainWindow.Show();
        }

would need to have a `MainWindow` property created.  

Another possibility is to keep the inheritance from `Application` but separate the code from `PrismApplicationBase` in to another public class that is then used as a "Backer".  That would maintain the current API and still allow direct use of that backer class in situations like ours.

## Intended Use Case

In our case, we wanted to create modules on separate UI Threads.  With the old `Bootstrapper` class we could do this with since it was not coupled with `Application`.  Creating another instance was fairly straight forward.

Now, after upgrading to from Prism 6 to 7, this will no longer work since creating a second instance of `PrismApplicationBase `/`Application`  is not possible without using AppDomains.   Eventually, we will move to .NET Core which no longer support AppDomains.

Like I said, I understand this is not a small change so I understand if it is a "no" but thought I would suggest it.

**Comment by brianlagunas** [comment]
The bootstrapper that exists now is not going to ever be removed. You can continue to use that if you like, but PrismApplication is the recommended class to use for 95% of apps.
