### ISSUE TITLE
Register Service in module

### ISSUE THREAD

**Issue by PeterForstmeier** [PrismLibrary/Prism#1837]
Hi, 
in my Module i have:
 public class ProjectsModule : IModule
    {
        public void OnInitialized(IContainerProvider containerProvider)
        {
            // This lines works
            var regionManager = containerProvider.Resolve<IRegionManager>();
            regionManager.Regions["Tabs"].Add(new ProjectTab());     
        }

        public void RegisterTypes(IContainerRegistry containerRegistry)
        {
            // This line works
            containerRegistry.RegisterForNavigation<ProjectNavigation>();
            //This line throws
            containerRegistry.RegisterSingleton<IProjectService, ProjectService>();
        }
    }

As you can see in RegisterTypes the second line throws:
Prism.Modularity.ModuleInitializeException
  HResult=0x80131500
  Nachricht = An exception occurred while initializing module 'ProjectsModule'. 
    - The exception message was: Methode nicht gefunden: "Void Prism.Ioc.IContainerRegistryExtensions.RegisterSingleton(Prism.Ioc.IContainerRegistry)".
    - The Assembly that the module was trying to be loaded from was:ErpDach.Modules.Projects, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
    Check the InnerException property of the exception for more information. If the exception occurred while creating an object in a DI container, you can exception.GetRootException() to help locate the root cause of the problem.
  Quelle = Prism.Wpf
  Stapelüberwachung:
   bei Prism.Modularity.ModuleInitializer.HandleModuleInitializationError(IModuleInfo moduleInfo, String assemblyName, Exception exception)
   bei Prism.Modularity.ModuleInitializer.Initialize(IModuleInfo moduleInfo)
   bei Prism.Modularity.ModuleManager.LoadModulesThatAreReadyForLoad()
   bei Prism.Modularity.ModuleManager.LoadModuleTypes(IEnumerable`1 moduleInfos)
   bei Prism.Modularity.ModuleManager.LoadModulesWhenAvailable()
   bei Prism.Modularity.ModuleManager.Run()
   bei Prism.PrismApplicationBase.InitializeModules()
   bei Erp_Dach.App.InitializeModules() in D:\Development\ErpDach_2\ErpDach_2\App.xaml.cs: Zeile103
   bei Prism.PrismApplicationBase.Initialize()
   bei Prism.PrismApplicationBase.InitializeInternal()
   bei Prism.PrismApplicationBase.OnStartup(StartupEventArgs e)
   bei System.Windows.Application.<.ctor>b__1_0(Object unused)
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   bei System.Windows.Threading.DispatcherOperation.InvokeImpl()
   bei System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   bei MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   bei MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   bei System.Windows.Threading.DispatcherOperation.Invoke()
   bei System.Windows.Threading.Dispatcher.ProcessQueue()
   bei System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   bei MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   bei MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   bei System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   bei MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   bei MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   bei System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   bei System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   bei System.Windows.Application.RunDispatcher(Object ignore)
   bei System.Windows.Application.RunInternal(Window window)
   bei System.Windows.Application.Run(Window window)
   bei System.Windows.Application.Run()
   bei Erp_Dach.App.Main() in D:\Development\ErpDach_2\ErpDach_2\obj\Debug\App.g.cs: Zeile58

Innere Ausnahme 1:
MissingMethodException: Methode nicht gefunden: "Void Prism.Ioc.IContainerRegistryExtensions.RegisterSingleton(Prism.Ioc.IContainerRegistry)".

I have definitly no idea how to solve this Problem or is there anx other way to Register globaly variable Services.
Thanks
Peter

**Comment by brianlagunas** [comment]
Closing as there is no sample app to reproduce the issue provided.

**Comment by PeterForstmeier** [comment]
Hi and sorry for the inconvinenace.

 

I can't provide a sample, all what i have

in App.xaml.cs:

  protected override void InitializeModules()

        {

            _logger.Log("App.Xaml - InitializeModules", Category.Info, Priority.Low);         

            base.InitializeModules();

        }     

 

In my ProjectModule i have 

public class ProjectsModule : IModule

    {

        public void OnInitialized(IContainerProvider containerProvider)

        {

            // works

            var regionManager = containerProvider.Resolve<IRegionManager>();

            regionManager.Regions["Tabs"].Add(new ProjectTab());     

        }

 

        public void RegisterTypes(IContainerRegistry containerRegistry)

        {

            // This line works

            containerRegistry.RegisterForNavigation<ProjectNavigation>();

            //This line throws

           // containerRegistry.RegisterSingleton<IProjectService, ProjectService>();

        }

    }

 

I just look for a way to register globaly available services in the ModuleInitialize.

 

Thanks again

Peter

 

Von: Brian Lagunas <notifications@github.com> 
Gesendet: Freitag, 21. Juni 2019 20:15
An: PrismLibrary/Prism <Prism@noreply.github.com>
Cc: Peter Forstmeier <peter.forstmeier@t-online.de>; Author <author@noreply.github.com>
Betreff: Re: [PrismLibrary/Prism] Register Service in module (#1837)

 

Closing as there is no sample app to reproduce the issue provided.

**Comment by brianlagunas** [comment]
That doesn't help. There is no actionable information in this issue. Saying "this throws" is not helpful. We need a sample app to reproduce the issue in order to be of assistance.

**Comment by PeterForstmeier** [comment]
Ok,

i hope i can build one.

Thanks

 

Von: Brian Lagunas <notifications@github.com> 
Gesendet: Freitag, 21. Juni 2019 20:30
An: PrismLibrary/Prism <Prism@noreply.github.com>
Cc: Peter Forstmeier <peter.forstmeier@t-online.de>; Author <author@noreply.github.com>
Betreff: Re: [PrismLibrary/Prism] Register Service in module (#1837)

 

That doesn't help. There is no actionable information in this issue. Saying "this throws" is not helpful. We need a sample app to reproduce the issue in order to be of assistance.

**Comment by PeterForstmeier** [comment]
Hi,

i found the problem. I have different versions of prism in my solution.

Anyway Thanks

peter

 

Von: Brian Lagunas <notifications@github.com> 
Gesendet: Freitag, 21. Juni 2019 20:30
An: PrismLibrary/Prism <Prism@noreply.github.com>
Cc: Peter Forstmeier <peter.forstmeier@t-online.de>; Author <author@noreply.github.com>
Betreff: Re: [PrismLibrary/Prism] Register Service in module (#1837)

 

That doesn't help. There is no actionable information in this issue. Saying "this throws" is not helpful. We need a sample app to reproduce the issue in order to be of assistance.
