### ISSUE TITLE
Unable to open solution VS2017/VS2019/VS2019 Preview

### ISSUE THREAD

**Issue by parkeradam** [PrismLibrary/Prism#1838]
Downloaded solution clean from github, tried to open in all 3 editors listed 

- Visual Studio Community 2017 (15.9.13)
- Visual Studio Community 2019 (16.1.3)
- Visual Studio Community 2019 Preview (16.2 Preview 2.0)

In all versions, and with all solutions, only the test projects would load and not the other projects. 
Error given when trying to load projects : 
![image](https://user-images.githubusercontent.com/30392071/60184658-5a210680-9820-11e9-857e-ba83dc4d681a.png)

I have installed the .Net Core 2.0 sdk/tools etc installed from within visual studio. Is there anything else required?

I have also tried this with the .NET Core 1.0/1.1 tooling installed with no avail either.

**Comment by dansiegel** [comment]
this is not an issue with Prism

**Comment by parkeradam** [comment]
Where would you suggest I ask this question then? I am trying to open the solution and so thought the Prism team may be able to help get this working.

**Comment by dansiegel** [comment]
First of all if you look at the error it tells you the error. Second of all we do not allow questions here... only bug reports and feature requests.

The best place to ask question is on StackOverflow, but even there you haven't provided enough information for anyone to help you.
