### ISSUE TITLE
[Question]: Retrieve Prism Navigation Stack with data 

### ISSUE THREAD

**Issue by sarathfrancis90** [PrismLibrary/Prism#1839]
I am implementing a Xamarin Forms Mobile application using Prism for Navigation.

Is there a way to retrieve the complete Navigation Stack along the data from Prism?

The requirement is, if the user is in the middle of a workflow and the app is closed, the user should be able to continue the workflow when a new session is started.

So I am trying to periodically save the entire navigation stack in the Local Storage.

**Comment by dansiegel** [comment]
Questions belong on StackOverflow
