### ISSUE TITLE
OnDialogClosing Method

### ISSUE THREAD

**Issue by noufionline** [PrismLibrary/Prism#1845]
## Summary

Provide a way to pass DialogParameters if a user closes the window natively.

## API Changes

option 1 : Provide an OnDialogClosing(DialogResult result) method.

option 2: Add DialogResult as a parameter in CanCloseDialog method

## Intended Use Case

Users can close the window just using the native close button and different users will have different requirements and need to get different DialogResult based on their use case scenario. This extension point will help to manipulate the DialogResult before closing the window.

**Comment by brianlagunas** [comment]
Can you provide more detail around the scenario you are trying to achieve? Maybe with some sample code. Also clarify what you mean by closing the dialog "natively".  Also, specify which platform you are talking about.

**Comment by noufionline** [comment]
@brianlagunas Hi, I am referring WPF platform. Natively means closing the window using the close button of the window itself. Suppose I want to pass some values back to the calling view irrespective of the way the user closes the window. If this much information is not enough then I will make a sample app tomorrow and post it here. Thanks for your consideration

**Comment by brianlagunas** [comment]
Please make a sample because I cannot visualize your requirement.

**Comment by noufionline** [comment]
Hi @brianlagunas 
please find the sample app link below.
[Sample App](https://github.com/noufionline/dialogresulttest.git).

If Closed using Button the message is displayed. But when closing using the windows close button then there is no way to pass the parameters.

**Comment by brianlagunas** [comment]
There is no need for a cancelable closing method. The CanCloseDialog method is used to determine if the dialog can close. If that returns false, it will not close even if you hit the "x" button.

Also, I'm not sure sending parameters back from a dialog that was closed via the "x" really make a lot of sense. You can use the DialogResult.Result to check to see how it was closed (ButtonResult.None means it was closed via the "x" button). I'll have to think about this one.  I'm not sold on it just yet.

**Comment by brianlagunas** [comment]
I can't convince myself to add this API at this time. I will wait for more feedback once the feature has more widespread usage.
