### ISSUE TITLE
Xamarin Forms iOS: Voice Over locks up UI when using navigation with selectedTab query string

### ISSUE THREAD

**Issue by IcemarkUK** [PrismLibrary/Prism#1847]
### Description
Using iOS device in Accessibility mode with Voice over.

When navigating to a tab page after two other page navigations, Voice Over will lock up unable to read anything from the screen other than the status bar and stop the user interacting with any UI element on screen. Essentially locking up the app.

The problem appears to be with using NavigateAsync with both "tabPage?selectedPage=tab1" and "root:///tabPage" format paths.

A work around is to Navigate to "tabPage" and internal navigate to tabs using SelectTabAsync however this doesn't make the Tab page the correct rootViewController and leads to problems elsewhere.

### Steps to Reproduce

Demo app included for iOS

1. Turn on Accessibility
2. Launch App - Shows Initial Load Page
3. Press 'Move to welcome screen'
4. Press 'Move to login screen'
5. Press 'Move to Member Dashboard Tab Navigation (broken)'

### Expected Behavior
Member dashboard page should be shown, voice over should announce the page, and the user should be able to interact with the ui on the page.

### Actual Behavior
Member dashboard page is shown, voice over does not announce the page, the user cannot interact with any ui elements on screen other than the status bar.

### Basic Information

- Version with issue: 7.1.0.431 ( Also tested on 7.2.0.1347-pre )
- Last known good version: N/A
- Xamarin.Forms version: 3.6.0.264807 ( Also tested on 4.0.0.425677 )
- IDE: Visual Studio 2019

### Screenshots

NONE

### Reproduction Link

https://github.com/IcemarkUK/PrismAccessibilityTestIOS

**Comment by dansiegel** [comment]
We'll try to look at this when we get a chance but there's basically a 99% chance this is either a Xamarin.Forms bug or you just didn't set something that Xamarin.Forms needs.

**Comment by IcemarkUK** [comment]
Thanks @dansiegel 
Only thing I would add is that without Prism in the equation it all works fine, otherwise I would have raised the issue directly with Xamarin.

Chris

**Comment by dansiegel** [comment]
@IcemarkUK do you have a sample without Prism of it working? It’d be much easier for me to diagnose if I can compare what you’re expecting with what you’re getting in the sample you shared.

**Comment by IcemarkUK** [comment]
@dansiegel I've have updated the repo do add a xamarin only solution. It's a quick hack back from the original code and so pretty straight forward.

**Comment by dansiegel** [comment]
@IcemarkUK sorry this has taken me so long to get to. I was running this sample. I am unable to duplicate an issue of any Voice Over lock up. While there were some minor differences in Accessibility that I noticed between your normal navigation and your "work around" these wouldn't really be on Prism since we don't touch anything having to do with Accessibility. If you think I've missed something by all means let me know and we can try taking another look.
