### ISSUE TITLE
[Enhancement] Update the samples and VS templates to Xamarin Forms 4

### ISSUE THREAD

**Issue by Gimly** [PrismLibrary/Prism#1848]
## Summary

Since Xamarin Forms 4 is now officially released and has some rather big improvements, it would be nice to have the Prism templates and samples get updated to use it.

## API Changes

The main change is the use of the `Shell` which greatly simplifies the navigation system of Xamarin.

**Comment by bartlannoeye** [comment]
I thinks this should be split up in 2 issues: one for templates (here) and one for samples (https://github.com/PrismLibrary/Prism-Samples-Forms).

**Comment by dansiegel** [comment]
For Prism 7.2 there is no reason for us to update to 4.0 as there is nothing we are using that specifically requires us to target it. You can certainly feel free to update to 4.X. When we add Shell support we will be updating to 4.TBD which will give us what we need to integrate Shell support. That is already being tracked via #1809
