### ISSUE TITLE
Journal still stores current entry even if PersistInHistory returns false

### ISSUE THREAD

**Issue by nvonada** [PrismLibrary/Prism#1850]
### Description
Navigating to a target that implements IJournalAware and returns false for PersistInHistory still sets the CurrentEntry in the RegionNavigationJournal

### Steps to Reproduce
1.  In a Prism WPF application create a view that implements IJournalAware and returns false for PersistInHistory().  It should also implement INavigationAware and return false for IsNavigationTarget()
2. Navigate to the view twice
3. PersistInHistory() will only be called once
4. The CurrentEntry of the journal will be the last view navigated to

### Expected Behavior
It seems to me that if you don't want the target in the journal it should honor that.   I spotted this as a memory leak because the journal was holding  objects passed as NavigationParameters.  It is not a big deal, I just Clear() the journal to remove the CurrentEntry.  But it seemed inconsistent.

### Actual Behavior
The code currently always sets the CurrentEntry.  It will only check PersistInHistory() to decide if the CurrentEntry should be pushed on the journal stack.

### Basic Information
- Version with issue: 7.1.431
- IDE: VS2019

### Reproduction Link
[PersistInHistoryTest.zip](https://github.com/PrismLibrary/Prism/files/3382791/PersistInHistoryTest.zip)

**Comment by brianlagunas** [comment]
I'll have to look into this. I'm not sure what role the CurrentEntry plays and if not setting it would cause issues with the current functionality. For example, if you navigated from ViewA to ViewB, except ViewB is not persisted in the journal, what happens if I call GoBack. Will it still work if the CurrentEntry is not updated to ViewB or is null?

**Comment by nvonada** [comment]
I wondered the same thing.  But calling Clear() does wipe out the CurrentEntry.  So if clearing the CurrentEntry is bad then that just became a new bug…

**Comment by brianlagunas** [comment]
Finally got around to addressing this. Consider it fixed!
