### ISSUE TITLE
[Enhancement] Raise error other than XamlParseException when AutoWireViewModel="True"

### ISSUE THREAD

**Issue by janschreier** [PrismLibrary/Prism#1852]
## Summary

I just noticed that when there is an exception raised in the ViewModel-constructor when AutoWireViewModel="True" the exception is raised as XamlParseException which typically is burried in a logfile and is not raised any further. The good thing is, the program doesn't crash, the downside is, that at least for me this was quite an unexpected behavior and took some time to find the issue.

So my suggestion would be to wrap the viewmodel creation in a try catch block in ViewModelLocationProvider.AutoWireViewModelChanged and raise another error here. 
I am not sure if this would be sufficient as I am not experienced enough with XAML-exception handling.

**Comment by dansiegel** [comment]
Closing for no repro. You haven't provided any contextual information here. If you add a reproduction and provide information as to what version and platform you're using we can reopen this issue.
