### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by bradws** [PrismLibrary/Prism#1853]
### Cannot get Prism 7.1.0.431 working in a dotnetcore version 3.0.0-preview6-27804-01
Does Prism support dotnet core 3 (I thought it does ?!?)

### Steps to Reproduce

1. Install Visual Studio Community 2019. Install the dotnet core v3 Preview 6 SDK and runtime
2. Launch Visual Studio Community 2019 and create a new dotnetcore v3 WPF application.
3. Build and run to make sure it works
4. In the Nuget Package manager, browse for Prism.Wpf
5. Install it

### Expected Behavior
It should install as per normal

### Actual Behavior
It does seem to install, however it looks like it's not supported in dotnet core 3?
Please refer to screenshot ErrorList:
![image](https://user-images.githubusercontent.com/9676439/61538467-0941ae00-aa6c-11e9-8002-11a16fb3f7ec.png)

### Basic Information

- Version with issue: Visual Studio Community 2019 with dotnet core v3
- Last known good version: Visual Studio Community 2019 with .NET Framework (it works!)
- Prism.Wpf version: 7.1.0.431
- IDE: Visual Studio Community 2019

**Comment by brianlagunas** [comment]
First off, not supporting a framework that is under development and not released is not a bug. LOL

Secondly, .NET Core 3 support is in version 7.2, not 7.1.
