### ISSUE TITLE
[Request] Update Template Pack to target latest XF

### ISSUE THREAD

**Issue by hnabbasi** [PrismLibrary/Prism#1855]
## Summary

Current template pack (2.1.6) targets XF 3.2 It will be helpful to release a new version that points to XF 4.1 (stable).

PS: happy to help test and valid any pre-release.

**Comment by adamhill** [comment]
Will to help test as well. 4.2 is now the latest stable :-)

**Comment by brianlagunas** [comment]
I updated the Template Pack to the latest version of Prism
