### ISSUE TITLE
Multiple Command parameters

### ISSUE THREAD

**Issue by arcuri** [PrismLibrary/Prism#1856]
### Description

Hi,
I'm developing my first application in Prism. I've worked for more time with caliburn micro. 
Caliburn provides Message.Attach function, where you can put the event and method (with multiples parameters). Follow and example:

cal:Message.Attach="[Event GotKeyboardFocus] = [Action GotKeyboardFocus(Description.Text,$this.ToolTip)]

Is it possible to implement something like this in prism? Because if you want to pass more parameter the xaml code will be more extended (more rows).

Otherwise, do you have a compact solution?
Thanks

**Comment by brianlagunas** [comment]
This does not exist and Prism and we will not add this type of behavior. If you wish to add multiple command parameters for a command, you would use normal XAML syntax to do that with the use of a MultiBinding.

**Comment by arcuri** [comment]
Hi brian,

How I can pass EventArgs to multiple command parameters?

<Setter Property="Command" Value="{Binding Data.rpOpenDocument, Source={StaticResource ResourceKey=Proxy}}"/>

            <Setter Property="CommandParameter">
              <Setter.Value>
                <MultiBinding Converter="{StaticResource CommandParameterConverter}">
                  <Binding Path="" /> 
                  <Binding Path="."/> 
                </MultiBinding>
              </Setter.Value>
            </Setter>
