### ISSUE TITLE
[Bug] MasterDetail Navigation: OnNavigatedTo parameters is null

### ISSUE THREAD

**Issue by michaelmairegger** [PrismLibrary/Prism#1857]
### Description

If I navigate on a MasterDetailPage without specifying any NavigationParameters then the parameters method parameter passed to `OnNavigatedFrom(INavigationParameters parameters)` is null rather than empty.

In the other case if I explicitly call `_navigationService.NavigateAsync("viewname, null)`
the parameters method parameter passed to `OnNavigatedTo(INavigationParameters parameters)` is not null but empty.

### Expected Behavior

The value of `parameters` is a empty collection 

### Actual Behavior

The value of `parameters` is null

related #1589

**Comment by brianlagunas** [comment]
The quick fix is to not pass null 😄

**Comment by brianlagunas** [comment]
BY=y the way, you're missing a repo app the duplicates the problem. If not provided, this issue will be closed.

**Comment by brianlagunas** [comment]
This was fixed. The update will be on MyGet shortly.
