### ISSUE TITLE
[Bug] 7.2.0.1367 System.PlatformNotSupportedException: Operation is not supported on this platform.

### ISSUE THREAD

**Issue by ChrisJAult** [PrismLibrary/Prism#1859]
### Description

After upgrading to 7.2.0.1376 from 7.1.0.431 my DryIoc registrations fail on iOS with System.PlatformNotSupportedException: Operation is not supported on this platform.

This works on Android but not iOS.

container.RegisterMany(new[] { typeof(CoreRegistry).GetTypeInfo().Assembly },
                type => type.IsAssignableTo< IMenuProvider >(),
                ifAlreadyRegistered: IfAlreadyRegistered.AppendNewImplementation);

### Steps to Reproduce

1. 
2. 
3. 

### Expected Behavior

The registration should work as it did with the previous version of Prism.

### Actual Behavior

An exception is thrown on startup
System.PlatformNotSupportedException: Operation is not supported on this platform.

### Basic Information

- Version with issue:  7.2.0.1367.
- Last known good version: 7.1.0.431
- Xamarin.Forms version: 3.6.0.344457
- IDE: Visual Studio 2019 Enterprise

**Comment by dansiegel** [comment]
1. There is no reproduction
1. Prism has no direct support for RegisterMany. Based on the code sample you've added I'd suggest opening an issue under the [DryIoc repo](https://github.com/dadhi/DryIoc/issues/new)

**Comment by ChrisJAult** [comment]
Hi, I reported the but in the DryIoc repo and they have confirmed there will be a fix very soon.

**Comment by dansiegel** [comment]
once that update is available you should be able to simply take the updated dependency on DryIoc it should work.
