### ISSUE TITLE
[Bug] GoBackAsync(useModalNavigation:true) to a MasterDetailPage is not working on UWP

### ISSUE THREAD

**Issue by Schinwinkwinsky** [PrismLibrary/Prism#1860]
### Description

Hello, everybody! I'm Schinwinkwinsky and I'm creating a Xamarin Forms app that uses Prism. I've been working with Prism for some time. My new solution has three projects: Android, iOS and UWP. But I'm facing a problem on UWP project that it's not happening on the others. 
The app starts with a MasterDetailPage(MainPage), and its Master has two children pages: Promotions and Account. When the user goes to Account, the app verifies if he is logged. If not, the SignInPage is shown on a modal page.

        ...
        private async void ItemTapped(MasterItem masterItem)
        {
            if (masterItem.Title.Equals("Account"))
            {
                if (_isLogged)
                {
                    await _navigationService.NavigateAsync("NavigationPage/AccountPage");
                }
                else
                {
                    await _navigationService.NavigateAsync("NavigationPage/SignInPage", useModalNavigation:true);
                }
            }
            else
            {
                await _navigationService.NavigateAsync("NavigationPage/" + masterItem.Path);
            }
        }
        ...

But if the user cancel the sign, the app goes back to the MainPage. On Android and iOS projects, the menu opens normally. But on UWP, it do not respond.

### Steps to Reproduce

1. Clone the solution on: https://github.com/Schinwinkwinsky/XamarinForms_Prism_MasterDetail_ListView/tree/modalNavigation.
2. Run the UWP project.
3. On menu, click on Account.
4. On SignInPage, click on Cancel.
5. Try to go to SignInPage again.

### Expected Behavior

When the app comes back from SignInPage, the menu on MainPage should be able to be opened.

### Actual Behavior

On UWP, when the app comes back from SignInPage, the user can't open the menu.

### Basic Information

- Version with issue: Prism.DryIoc.Forms (7.2.0.1367)
- Last known good version: -
- Xamarin.Forms version: 4.1.0.618606
- IDE: Visual Studio 2019 v16.2.0

### Reproduction Link

https://github.com/Schinwinkwinsky/XamarinForms_Prism_MasterDetail_ListView/tree/modalNavigation

### More Observations

StackOverflow discussion: https://stackoverflow.com/questions/57201173/gobackasyncusemodalnavigationtrue-to-a-masterdetailpage-is-not-working-on-uwp

**Comment by dansiegel** [comment]
@Schinwinkwinsky your reproduction doesn't seem to follow your steps to reproduce. It only has a Page A and Page B.

**Comment by Schinwinkwinsky** [comment]
Please, verify on modalNavigation branch.

**Comment by brianlagunas** [comment]
I haven't looked at this, however, I would like to mention it is highly unlikely this is a Prism issue. Prism uses XF's navigation API.  Have you tried this in a non Prism app?

**Comment by Schinwinkwinsky** [comment]
It worked properly!
https://github.com/Schinwinkwinsky/XF_UWP_Test

**Comment by brianlagunas** [comment]
I looked into this and was able to duplicate issue. However, this is not an issue with Prism. Prism has absolutely zero control or influence over the rendering of the UI.  Prism also calls the exact same PopModalAsync method that you are calling.  I even went as far as modifying the GoBackAsync code to hard code to just:
```
await page.Navigation.PopModalAsync();
```
And it still froze.

Also, if you set the MasterBehavior to Split, it will work.  If you keep the MasterBehavior set to Popover, you can implement the IMasterDetailPageOptions to set the IsPresented to true and it will work.
```
    public partial class MyMasterDetail : IMasterDetailPageOptions
    {
        public MyMasterDetail()
        {
            InitializeComponent();
        }

        public bool IsPresentedAfterNavigation => Device.Idiom != TargetIdiom.Phone;
    }
```
This boils down to something in XF that is not working properly. Keep in mind that UWP is the bastard step child of XF, and even the XF team is not focusing on it at this time.
