### ISSUE TITLE
[Bug] OnNavigatingTo not fires after update.

### ISSUE THREAD

**Issue by andreybutko** [PrismLibrary/Prism#1861]
### Description

After updating to the latest version of  OnNavigatingTo not firing. Why it could be? Xamarin.Forms 

### Steps to Reproduce

1. Create base app, using package versions provided above;
2. Create view model; 
3. Try to fire OnNavigatingTo.

### Expected Behavior
OnNavigatingTo fires
### Actual Behavior
OnNavigatingTo not fired.

### Basic Information

- Version with issue: Prism.Core and Forms( 7.2.0.1367)
- Last known good version: 7.1.0.431
- Xamarin.Forms version: 4.1.0.581479 
- IDE: Visual Studio for Mac (latest stable)

**Comment by brianlagunas** [comment]
This is by design. Please read the release notes: https://github.com/PrismLibrary/Prism/releases/tag/v7.2.0.1367
