### ISSUE TITLE
[Enhancement] Back Button Behavior for DialogService

### ISSUE THREAD

**Issue by WebDucer** [PrismLibrary/Prism#1862]
## Summary

The current implementation does not respect the Android back button, if the dialog is shown. The complete page is closed (go back), instead of closing only the diolog.

## Intended Use Case

User should be able to close / cancel the dialog with the back button.

**Comment by dansiegel** [comment]
This is not currently possible however there is an outstanding proposal for Xamarin.Forms that should make this possible. See Xamarin/Xamarin.Forms#6971

**Comment by AmrAlSayed0** [comment]
Since ```DialogService``` now uses a ```ContentPage``` (```DialogPage```), can this issue be fixed by overriding the ```OnBackButtonPressed```?

**Comment by Tum4ik** [comment]
Do you think [this](https://github.com/PrismLibrary/Prism/discussions/2380#discussioncomment-591133) could be used as workaround inside Prism?

**Comment by brianlagunas** [comment]
@Tum4ik That's not actually a workaround. That's just preventing a double click when it's not allowed. The responsibility for preventing multiple clicks of a button that invokes a command is on the developer. Prism will never try to control or manipulate the end-user experience or interactions of the UI.

**Comment by dansiegel** [comment]
fixed by #2391
