### ISSUE TITLE
[Enhancement] Ability to reuse view with parameters on tab page

### ISSUE THREAD

**Issue by ScarlettCode** [PrismLibrary/Prism#1864]
## Summary

I'd like to have a dynamically generated list of tabs re use the same view and be able to pass parameters to the different instances.

## Intended Use Case

`_navigationService.NavigateAsync("createTab=ViewA?id=1&createTab=ViewA?id=2")
`

At the moment if I do this it correctly creates 2 tabs and both are rendered however if I use

```
if (parameters.ContainsKey("id"))
{
    Id = parameters.GetValue<int>("id");
}
```

from within ViewA then both views get an Id of 1. Would like the views to get the parameters that are related to there instance.

**Comment by brianlagunas** [comment]
Passing parameters in the createTab will not be supported. The creation of tabs occurs at the very beginning of the navigation process. There is no way to reliably persist and read those in the navigation stack to where they are correctly associated.

Your best option would be to pass your parameters view the INavigationParameters parameter in the NavigateAsync method, and associate a unique ID for each param/View combination.
