### ISSUE TITLE
Unable to launch the dialog box, when using Shell page

### ISSUE THREAD

**Issue by vk-makam** [PrismLibrary/Prism#1865]
### Description
I am using AppShell along with Prism.DryIoC.Forms in one of our projects. We are unable to use the DialogService in AppShell pages (Tabs). We are using `dialogService.ShowDialog("DemoDialog");`

The same code is working fine in the normal ContentPage

### Steps to Reproduce

1. Launching the AppShell using `MainPage = new AppShell();`
2. Created a `DialogDemo.xaml` and `DialogDemo.xaml.cs` (as mentioned in the [Prism Issue 1825](https://github.com/PrismLibrary/Prism/pull/1825))
3. Trying to launch the `DialogDemo` using `DialogService` in ViewModel

### Expected Behavior
The DialogDemo should appear

### Actual Behavior
Nothing happens

### Basic Information

- Version with issue: v7.2.0.1367
- Last known good version:
- Xamarin.Forms version: v4.1.0.618606
- IDE: Visual Studio Mac 2019 (v8.2.1 build 19)

**Comment by brianlagunas** [comment]
Prism does not support Shell.  See #1809

**Comment by dansiegel** [comment]
This is something that will need to be done in a separate effort from general "Shell Support". While #1809 is in fact labeled "Shell Support" what we're really talking about there is the Navigation Service. Also this should be fairly straight forward to handle where Shell Navigation is still pending fixes from the Xamarin.Forms team. @vk-makam please provide a simple reproduction app and we can reopen the issue.

**Comment by vk-makam** [comment]
Hi Dan,

Thanks for the reply. Please find the attached Xamarin.Forms project.

[DialogDemo.zip](https://github.com/PrismLibrary/Prism/files/3461389/DialogDemo.zip)

**Comment by vk-makam** [comment]
Hi Brain,

Thanks for the quick reply, I don't know about this. I will try to change them using TabbedPage/ MasterDetailPage.
