### ISSUE TITLE
Inconsistent behavior when navigating with/without navigationpage [Bug] [XF]

### ISSUE THREAD

**Issue by JesperBaltzersen** [PrismLibrary/Prism#1866]
### Description

I'm new to Prism and testing out how the navigation works and the ordering of calls made to `Initialize`, `OnNavigatedTo` and `OnAppearing`. 
I'm noticing different order of methods called. The ordering changes when navigating to a new page with and without wrapping it in a navigationpage. 

Specifically I see this difference: 

With navigationpage: `await navigationService.NavigateAsync("NavigationPage/SecondPage");`
1. Initialize
2. OnNavigatedTo
3. OnAppearing

Without navigationpage: `await navigationService.NavigateAsync("SecondPage");`
1. Initialize
2. OnAppearing
3. OnNavigatedTo

### Steps to Reproduce
Navigate to page with and without wrapping it in a NavigationPage
`await navigationService.NavigateAsync("NavigationPage/SecondPage");`
`await navigationService.NavigateAsync("SecondPage");`

I made a repo that shows the difference in behavior. Just download and run: https://github.com/JesperBaltzersen/TestPrism 

### Expected Behavior
Not sure. 
Documentation says TBD for `PageLifeCycle`. 

### Actual Behavior
Different for each way of calling. 

### Basic Information

- Version with issue: 7.2
- Last known good version: 
- Xamarin.Forms version: 4.1
- IDE: Visual Studio Mac

### Reproduction Link

https://github.com/JesperBaltzersen/TestPrism

**Comment by brianlagunas** [comment]
Due to the nature of navigation in XF, you cannot rely on the order/timing of the INavigationAware methods.  Besides navigation being async, the process of adding a page to the nav strack, vs the page actually being rendered is not related. Also, when dealing with navigation pages, the nav stack is built in reverse order.

**Comment by JesperBaltzersen** [comment]
Thank you for taking time to respond to this:-)
