### ISSUE TITLE
Prism and Telerik Docking

### ISSUE THREAD

**Issue by arcuri** [PrismLibrary/Prism#1867]
Hi,
I've create an application with prism and RadDocking. My problem is that the controls in the rad panes don't lose the focus when I clicked in another rad pane.
This happen only after the first loading of layout. In my case, I resolve the instance of the module in base of the serialization tag (to have only an instance of the module) and add to the region the view (to have the list of the view present in the regions, but in the DockingPanesFactory I skip the add of the pane, because it's already present in the docking).

I've also tried to use Region.Activate and Deactivate when the IsActive property changed.

Do you have any suggestions?

![Untitled](https://user-images.githubusercontent.com/10706727/62360823-f6be7e80-b519-11e9-98b5-ab2324d6ed44.png)

```
foreach (var rPane in rDocking.Panes)
{
   var tag = RadDocking.GetSerializationTag(rPane);
   if (tag.Contains("SPEA.Semi"))
   {
      IToolModule rModule = rmContainer.Resolve<IToolModule>(tag);            
      rPane.Content = rModule;
      rPane.DataContext = (rPane.Content as FrameworkElement).DataContext;
      rModule.rpBase.rpAlreadyLoaded = true;

      rmRegionManager.AddToRegion(TkRegions.kDocumentsRegion, rModule);
   }
}
```

**Comment by brianlagunas** [comment]
Sorry, you'll have to ask Telerik about that one.
