### ISSUE TITLE
[Question] Prism Navigation with MasterDetailPage

### ISSUE THREAD

**Issue by hudaIT** [PrismLibrary/Prism#1869]
### Description
I have some problems fully understanding the Prism Navigation with a MasterDetailPage.

### MY GOAL IS
To navigate normally between my pages and always show the hamburger Icon, **without a white page between navigating**

### MY TRIES

1. First Try
First => **NavigationService.NavigateAsync("MasterDetailPage/NavigationPage/Page1")**
Second => **navigationService.NavigateAsync("Page2")**
When I call **string path= _navigationService.GetNavigationUriPath();** i get => **path = "/MainPage"**
However my Hamburger Icon is gone + my Title bar is gone

2. Second Try
First => **NavigationService.NavigateAsync("MasterDetailPage/NavigationPage/Page1")**
Second => **navigationService.NavigateAsync("MasterDetailPage/NavigationPage/Page2")**  => My Hamburger Icon is still there but the constructor of my MasterDetailPage is called which i assume i completely reconstruct my MasterDetailPage

3. Third Try
First => **NavigationService.NavigateAsync("MasterDetailPage/NavigationPage/Page1")**
Second => **navigationService.NavigateAsync("NavigationPage/Page2")**  => My Hamburger Icon is still there and the constructor of my MasterDetailPage is **not** called anymore so far so good
However my page completely dissapears between navigating for about 1 second and shows a white page **which is not the case with Try Number 2**.

### THREE FINAL QUESTIONS

- Is there any way to avoid this white screen between navigating?
- Is the Third Try the right way to work with the NavigationService when i have a masterdetailpage?
- Is NavigationService.NavigateAsync("MasterDetailPage/NavigationPage/Page1") the right way to be called in app.xaml.cs to Initialize my Masterdetailpage for the first time?

Thank you very much for your time.

**Comment by dansiegel** [comment]
As was indicated in the issue template we do not answer questions here. Please ask your questions on StackOverflow
