### ISSUE TITLE
RibbonRegionAdapter inherits from Microsoft.Practices.Prism.Regions

### ISSUE THREAD

**Issue by Blackjack92** [PrismLibrary/Prism#187]
Can it be that the RegionRibbonAdapter does not implement the moved IRegionAdapter from the Prism.Regions ?
I got the newest nuget packages and when i check the namespaces of the implemented interface (IRegionAdapter) from the RegionRibbonAdapter it is still in Microsoft.Practices.Prism.Regions.

**Comment by brianlagunas** [comment]
What RibbonRegionAdapter?  Prism doesn't ship one of those.

**Comment by Blackjack92** [comment]
This one, http://prismribbonregionadapter.codeplex.com/
In the bootstrapper the RegionAdapterMappings should be changed like this
 ```
	protected override RegionAdapterMappings ConfigureRegionAdapterMappings()
		{
			var mappings = base.ConfigureRegionAdapterMappings();

			mappings.RegisterMapping(typeof(Ribbon), ServiceLocator.Current.GetInstance<RibbonRegionAdapter>());
			return mappings;
		}
```
but it does not work because the RegisterMapping expects a Prism.Regions.IRegionAdapter and the RibbonRegionAdapter does implement the old one Microsoft.Practices.Prism.Regions.IRegionAdapter.
