### ISSUE TITLE
[Proposal] Automatic Injection of Named Views

### ISSUE THREAD

**Issue by SMutschler** [PrismLibrary/Prism#1872]
## Summary

[EDITED FOR CLARITY AND TO ELIMINATE MISSTATEMENT]

Past issues #1120, #1161, and #1490 all had to do with failure to discover existing named Views within a region.  Brian Lagunas correctly pointed out in each case that a custom content loader (derived from RegionNavigationContentLoader) is the chosen solution and that Prism.Unity.Wpf in fact includes UnityRegionNavigationContentLoader for the Unity container.

My proposal is to augment automatic View injection (within UnityRegionNavigationContentLoader) to use a named Add ("Region.Add(view, viewName, ...") when an alias URI is provided.  The default implementation of LoadContent(...) in base class RegionNavigationContentLoader always performs a generic Add() when injecting a new View into a Region, even when the provided URI is based on an alias name for the View rather than its type.

## API Changes

An override of LoadContent(...) is the correct approach here, but that method is not defined as virtual.  My first request would be to define it as such so that derived classes can override it.  I have done as much by using a "new" directive and re-declaring the interface in my derived class, but a plain override would be MUCH more elegant.

Better yet, I would argue that the base implementation of RegionNavigationContentLoader.LoadContent(...) should actually be modified to make my override unnecessary:  when injecting a new instance of a View, it should perform a "named" Add() if the provided URI is NOT based on the View's type (thus indicating that an alias registration key is being used to refer to the View).  As currently exists, the injection always performs an "unnamed" Add for a new View (without a name key) and thus the View cannot be retrieved using Region.GetView(name).  Being able to reference and retrieve the View by key is almost always the intent of using a URI that is not the type name (and most programmers follow a pattern of using the same key for the navigation URI as the key used to register the View in the dependency container).

I argue that the injection could and should be more consistent with the candidate search method.  UnityRegionNavigationContentLoader specifically returns matching Views from within the region by matching both alias names and plain old View type names.   I argue that the base LoadContent() method would be more consistent if it also used the alias name to inject a new (not found) View, if an alias is apparent in the navigational URI.

## Intended Use Case

I guess I'd like some folks to weigh in before I submit code.  Is the override (of UnityRegionNavigationContentLoader) the preferred approach or should this change be implemented directly in the base class implementation of LoadContent()?

There is little chance of this breaking old code as the view discovery code in UnityRegionNavigationContentLoader.GetCandidatesFromRegion(...) finds both named and unnamed views.  Adding a new view with its name key does not change that.  But it does have the desirable side effect of making the View reference-able and retrievable by its key within the region.  

I believe altering UnityRegionNavigationContentLoader honors the main intent of using named Views -- the ability to later refer to that View instance using Region.GetView(aliasName).  To summarize: the proposal is to change LoadContent() to perform "named/keyed Add" of a new View when that View is not found in Region and an alias name was provided in the URI.  Otherwise, an unnamed Add would be performed as is currently.

**Comment by SMutschler** [comment]
Okay, here is the modified code for LoadContent (plus additional method) with highlighted changes in **bold**:

`
public object LoadContent( IRegion region, NavigationContext navigationContext )
        {
            if (region == null)
                throw new ArgumentNullException(nameof(region));

            if (navigationContext == null)
                throw new ArgumentNullException(nameof(navigationContext));

            string candidateTargetContract = this.GetContractFromNavigationContext(navigationContext);

            var candidates = this.GetCandidatesFromRegion(region, candidateTargetContract);

            var acceptingCandidates =
                candidates.Where(
                    v =>
                    {
                        var navigationAware = v as INavigationAware;
                        if (navigationAware != null && !navigationAware.IsNavigationTarget(navigationContext))
                        {
                            return false;
                        }

                        var frameworkElement = v as FrameworkElement;
                        if (frameworkElement == null)
                        {
                            return true;
                        }

                        navigationAware = frameworkElement.DataContext as INavigationAware;
                        return navigationAware == null || navigationAware.IsNavigationTarget(navigationContext);
                    });


            var view = acceptingCandidates.FirstOrDefault();

            // If we found the View already in the Region, use it
            if (view != null)
            {
                return view;
            }

            </b>
            // If not already in the Region, create and add a new view instance to the region
            view = this.CreateAndInjectNewViewInstance( region, candidateTargetContract );
            return view;
        }

        private object CreateAndInjectNewViewInstance( IRegion region, string candidateTargetContract )
        { 
            var view = this.CreateNewRegionItem(candidateTargetContract);

            // If the URI ("contract") is not based on the View's type name, then the View is being referenced
            // by an alias name, i.e., a "friendly name" key.  If an alias name is detected, this is used to
            // perform a named (keyed) View injection.  As with an explicit named injection, this View will match
            // the contract and be discovered when searched for in <see cref="GetCandidatesFromRegion()"/>.
            // Conversely, if the contract IS based on the View's type name, we perform a generic, non-keyed Add.
            // A view injected this way will not be discovered using an alias key contract, i.e., the key used
            // when the View was originally registered into the DI container.
            if ( !string.Equals(view.GetType().Name, candidateTargetContract, StringComparison.Ordinal) 
                && !string.Equals(view.GetType().FullName, candidateTargetContract, StringComparison.Ordinal) )
            {
                region.Add(view, candidateTargetContract);      // perform Named (keyed) Add
            }
            else
            {
                region.Add(view);                               // perform unnamed (non-keyed) Add
            }

            return view;
        }
        </b>
`

**Comment by SMutschler** [comment]
Okay, here is the modified code for LoadContent (plus additional method) with highlighted changes in **bold**:

`
public object LoadContent( IRegion region, NavigationContext navigationContext )
        {
            if (region == null)
                throw new ArgumentNullException(nameof(region));

            if (navigationContext == null)
                throw new ArgumentNullException(nameof(navigationContext));

            string candidateTargetContract = this.GetContractFromNavigationContext(navigationContext);

            var candidates = this.GetCandidatesFromRegion(region, candidateTargetContract);

            var acceptingCandidates =
                candidates.Where(
                    v =>
                    {
                        var navigationAware = v as INavigationAware;
                        if (navigationAware != null && !navigationAware.IsNavigationTarget(navigationContext))
                        {
                            return false;
                        }

                        var frameworkElement = v as FrameworkElement;
                        if (frameworkElement == null)
                        {
                            return true;
                        }

                        navigationAware = frameworkElement.DataContext as INavigationAware;
                        return navigationAware == null || navigationAware.IsNavigationTarget(navigationContext);
                    });


            var view = acceptingCandidates.FirstOrDefault();

            // If we found the View already in the Region, use it
            if (view != null)
            {
                return view;
            }

**            // If not already in the Region, create and add a new view instance to the region
            view = this.CreateAndInjectNewViewInstance( region, candidateTargetContract );
            return view;
        }

        private object CreateAndInjectNewViewInstance( IRegion region, string candidateTargetContract )
        { 
            var view = this.CreateNewRegionItem(candidateTargetContract);

            // If the URI ("contract") is not based on the View's type name, then the View is being referenced
            // by an alias name, i.e., a "friendly name" key.  If an alias name is detected, this is used to
            // perform a named (keyed) View injection.  As with an explicit named injection, this View will match
            // the contract and be discovered when searched for in <see cref="GetCandidatesFromRegion()"/>.
            // Conversely, if the contract IS based on the View's type name, we perform a generic, non-keyed Add.
            // A view injected this way will not be discovered using an alias key contract, i.e., the key used
            // when the View was originally registered into the DI container.
            if ( !string.Equals(view.GetType().Name, candidateTargetContract, StringComparison.Ordinal) 
                && !string.Equals(view.GetType().FullName, candidateTargetContract, StringComparison.Ordinal) )
            {
                region.Add(view, candidateTargetContract);      // perform Named (keyed) Add
            }
            else
            {
                region.Add(view);                               // perform unnamed (non-keyed) Add
            }

            return view;
        }
**
``

**Comment by SMutschler** [comment]
Okay, here is the modified code for LoadContent (plus additional method) with highlighted changes in bold:

`
public object LoadContent( IRegion region, NavigationContext navigationContext )
{
if (region == null)
throw new ArgumentNullException(nameof(region));

        if (navigationContext == null)
            throw new ArgumentNullException(nameof(navigationContext));

        string candidateTargetContract = this.GetContractFromNavigationContext(navigationContext);

        var candidates = this.GetCandidatesFromRegion(region, candidateTargetContract);

        var acceptingCandidates =
            candidates.Where(
                v =>
                {
                    var navigationAware = v as INavigationAware;
                    if (navigationAware != null && !navigationAware.IsNavigationTarget(navigationContext))
                    {
                        return false;
                    }

                    var frameworkElement = v as FrameworkElement;
                    if (frameworkElement == null)
                    {
                        return true;
                    }

                    navigationAware = frameworkElement.DataContext as INavigationAware;
                    return navigationAware == null || navigationAware.IsNavigationTarget(navigationContext);
                });


        var view = acceptingCandidates.FirstOrDefault();

        // If we found the View already in the Region, use it
        if (view != null)
        {
            return view;
        }

        // If not already in the Region, create and add a new view instance to the region
        view = this.CreateAndInjectNewViewInstance( region, candidateTargetContract );
        return view;
}

private object CreateAndInjectNewViewInstance( IRegion region, string candidateTargetContract )
    { 
        var view = this.CreateNewRegionItem(candidateTargetContract);

        // If the URI ("contract") is not based on the View's type name, then the View is being referenced
        // by an alias name, i.e., a "friendly name" key.  If an alias name is detected, this is used to
        // perform a named (keyed) View injection.  As with an explicit named injection, this View will match
        // the contract and be discovered when searched for in <see cref="GetCandidatesFromRegion()"/>.
        // Conversely, if the contract IS based on the View's type name, we perform a generic, non-keyed Add.
        // A view injected this way will not be discovered using an alias key contract, i.e., the key used
        // when the View was originally registered into the DI container.
        if ( !string.Equals(view.GetType().Name, candidateTargetContract, StringComparison.Ordinal) 
            && !string.Equals(view.GetType().FullName, candidateTargetContract, StringComparison.Ordinal) )
        {
            region.Add(view, candidateTargetContract);      // perform Named (keyed) Add
        }
        else
        {
            region.Add(view);                               // perform unnamed (non-keyed) Add
        }

        return view;
    }
``

**Comment by SMutschler** [comment]
On second thought, here is the code.  Modifications are at the bottom of LoadContent and the method which follows:

```
public object LoadContent( IRegion region, NavigationContext navigationContext )
{
        if (region == null)
             throw new ArgumentNullException(nameof(region));

        if (navigationContext == null)
            throw new ArgumentNullException(nameof(navigationContext));

        string candidateTargetContract = this.GetContractFromNavigationContext(navigationContext);

        var candidates = this.GetCandidatesFromRegion(region, candidateTargetContract);

        var acceptingCandidates =
            candidates.Where(
                v =>
                {
                    var navigationAware = v as INavigationAware;
                    if (navigationAware != null && !navigationAware.IsNavigationTarget(navigationContext))
                    {
                        return false;
                    }

                    var frameworkElement = v as FrameworkElement;
                    if (frameworkElement == null)
                    {
                        return true;
                    }

                    navigationAware = frameworkElement.DataContext as INavigationAware;
                    return navigationAware == null || navigationAware.IsNavigationTarget(navigationContext);
                });


        var view = acceptingCandidates.FirstOrDefault();

        // If we found the View already in the Region, use it
        if (view != null)
        {
            return view;
        }

        // If not already in the Region, create and add a new view instance to the region
        view = this.CreateAndInjectNewViewInstance( region, candidateTargetContract );
        return view;
}

private object CreateAndInjectNewViewInstance( IRegion region, string candidateTargetContract )
{ 
        var view = this.CreateNewRegionItem(candidateTargetContract);

        // If the URI ("contract") is not based on the View's type name, then the View is being referenced
        // by an alias name, i.e., a "friendly name" key.  If an alias name is detected, this is used to
        // perform a named (keyed) View injection.  As with an explicit named injection, this View will match
        // the contract and be discovered when searched for in <see cref="GetCandidatesFromRegion()"/>.
        // Conversely, if the contract IS based on the View's type name, we perform a generic, non-keyed Add.
        // A view injected this way will not be discovered using an alias key contract, i.e., the key used
        // when the View was originally registered into the DI container.
        if ( !string.Equals(view.GetType().Name, candidateTargetContract, StringComparison.Ordinal) 
            && !string.Equals(view.GetType().FullName, candidateTargetContract, StringComparison.Ordinal) )
        {
            region.Add(view, candidateTargetContract);      // perform Named (keyed) Add
        }
        else
        {
            region.Add(view);                               // perform unnamed (non-keyed) Add
        }

        return view;
}

**Comment by brianlagunas** [comment]
I have been looking into this, and we can;t take the appraoch you have suggested. The reason being is when you use a named add, you can't have another view with the same name. So if you had a items control (like a TabControl) and you try to inject the same view multiple times, it would fail with an exception.

I can think of two other appraoches we can try:
1. We can create content loaders for each DI container and hope each containers provides and API that will allow us to do so.
2. We could follow the pattern we used in Prism.Forms where we have a [PageNavigationRegistry](https://github.com/PrismLibrary/Prism/blob/master/Source/Xamarin/Prism.Forms/Navigation/PageNavigationRegistry.cs) class that is used in the `RegistierForNavigation` method to register the custom name with it's associated type. When we go to get the candidates from the region, we check to see if the type is already in the registertry and grabs it's type, then follow the existing logic.

Both options have their pros and cons. What do you think we should try first?

**Comment by brianlagunas** [comment]
I've made the decision to use approach 1.  This is the mechanism that Prism relies on to provide support for named view registrations. We just have to make sure that all supported containers ship with a proper RegionNaviationContentLoader.  I just added one for DryIoC. I think all officially support containers now have a content loader.
