### ISSUE TITLE
[Bug] IsActive can become true for more than one tab

### ISSUE THREAD

**Issue by Tragetaschen** [PrismLibrary/Prism#1874]
### Description

I have a Xamarin.Forms application with a Tabbed page and child pages and do "silent" navigation on an inactive tab. This can result in the inactive tab being `IsActive==true`.

### Steps to Reproduce

My TabbedPage contains two children.
Each child is a NavigationPage containing Page1 and Page2 respectively.
Depending on an external state, I want to navigate into Page3 from Page2 and back.
This can happen while the second tab is not active.
When the user activates the second tab, there's either NavigationPage/Page2 or NavigationPage/Page2/Page3 shown.

I have simulated the external state with a Task that requests the navigation on the Main thread after a small timeout.
Page1, Page2, and Page3 have view models that implement `INavigatedAware` and `IActiveAware`. For the debugger, there are break points in IsActive.set and OnNavigatedTo/From on all three page view models.

### Actual Behavior

I don't change the tabs, so Page2 is always in the "background"
The sequence of events starting at App startup currently is
- Page1VM.OnNavigatedTo
- Page1VM.IsActive=true

Page2ViewModel task runs NavigateAsync("./Page3")
- Page2VM.IsActive=false
- Page3VM.IsActive=true
- Page2VM.OnNavigatedFrom
- Page3VM.OnNavigatedTo

By that time, both Page1ViewModel and Page3ViewModel have `IsActive==true`.

Page3ViewModel task runs GoBackAsync()
- Page3VM.IsActive=false
- Page2VM.IsActive=true
- Page3VM.OnNavigatedFrom
- Page2VM.OnNavigatedTo

By that time, both Page1ViewModel and Page2ViewModel have `IsActive==true`.

### Expected Behavior

<s>There are inconsistencies in the order of IsActive=true and OnNavigatedTo between the initial navigation and later navigations. It might be worth harmonizing those.</s>

It should not be possible to have `IsActive==true` for more than one tab.

Ultimately, I would like to know in my view models whether things happen in the background or in the foreground in order to change behavior based on that. For example, I don't want to `GoBackAsync` in the above example when the tab is in the foreground.

### Basic Information

- Version with issue: Prism.DryIoc.Forms 7.2.0.1367
- Last known good version: n/a
- Xamarin.Forms version: 4.1.0.618606
- IDE: Visual Studio 16.2.0

### Reproduction Link
Will provide if deemed necessary :)
Edit: https://github.com/Tragetaschen/prism-forms-issue-1874

**Comment by dansiegel** [comment]
@Tragetaschen please provide a reproduction.

**Comment by Tragetaschen** [comment]
Sure: https://github.com/Tragetaschen/prism-forms-issue-1874

**Comment by brianlagunas** [comment]
@Tragetaschen 

> There are inconsistencies in the order of IsActive=true and OnNavigatedTo between the initial navigation and later navigations. It might be worth harmonizing those.

This is not something we will change. The order of these events are dependent on many factors including the parent pages, the current nav stack, and more. Do not try to rely on the order of these events firing to execute you code.

**Comment by brianlagunas** [comment]
There is some very unorthadox coding practices in this sample that is not supported in Prism. For example, you cannot navigate in the ctor of a VM. The page hasn't even been added to the navigation stack yet, and nav will not function properly.  The scenario you are describing of silently navigating to tabs that are not select is not a scenario that is supported. I would actaully question that approach altogether. You may want to rely on the IPageLifecycle instead. This way you know if a page has appeared/disappeared. IActiveAware it not the use case for this scenario. It is meant to be used when your end-users are switching tabs.
