### ISSUE TITLE
[Bug] Cannot correctly replace child page

### ISSUE THREAD

**Issue by Tragetaschen** [PrismLibrary/Prism#1876]
### Description

I'm currently trying to programmatically control the page stack in a NavigationPage.
From `/NavigationPage/Page1`, the Page1ViewModel is pushing Page2, so I'm at `/NavigationPage/Page1/Page2`. Now, Page1ViewModel needs to replace Page2 with Page3, so the page stack becomes `/NavigationPage/Page1/Page3`

### Steps to Reproduce and Actual Behavior

In Page1ViewModel:
1. When I do `NavigateAsync("Page3")`, I end up with `/NavigationPage/Page1/Page2/Page3`, and have to navigate back twice.
2. When I do `NavigateAsync("../Page3")`, I end up with `/NavigationPage/Page2/Page3`, so the `..` yanks out the Page1 and Page3 is pushed in front of Page2.
3. I can do `GoBackAsync()` and then `NavigateAsync("Page3")` to end up with `/NavigationPage/Page1/Page3`, but this results in two animations—Page2 goes away, Page1 shows briefly, Page3 appears.

### Expected Behavior

In Page1ViewModel, I want the behavior I can get from Page*2*ViewModel when I do `NavigateAsync("../Page3")`, which is: replace Page2 with Page3 without any flash.

I have downloaded the source and modified the PageNavigationService:
https://github.com/PrismLibrary/Prism/blob/ef3d80362cf5baf5a0de3ce975f61ab7a05e162a/Source/Xamarin/Prism.Forms/Navigation/PageNavigationService.cs#L424-L429

Instead of having `currentPage` in the `pagesToRemove`, I put in `currentPage.Navigation.NavigationStack.Last()` and that did what I was expecting from case 2 above.

### Basic Information

- Version with issue: 7.2.0.1367
- Last known good version: n/a
- Xamarin.Forms version: 4.1.0.618606
- IDE: Visual Studio 16.2.0

### Reproduction Link

https://github.com/Tragetaschen/prism-forms-issue-1876

**Comment by brianlagunas** [comment]
Reproductions are always necessary. That's why we require it in the issue template. Closing until one is provided

**Comment by Tragetaschen** [comment]
What do you want in the reproduction?

I have provided three methods that don't work well and one where I hacked Prism's source code.

I would suggest case 2 as this is the one that I thought should work (and that I hacked to work). Do you agree?

**Comment by brianlagunas** [comment]
An app that reproduces the issue you are submitting. Your hack is just that, a hack. We can't add that to the code base. We need to properly analyze your code and approach to make sure we understand what's going on. Most of the time it's user error.

**Comment by Tragetaschen** [comment]
Here you go: https://github.com/Tragetaschen/prism-forms-issue-1876

**Comment by brianlagunas** [comment]
This is exactly why we need a sample. What exactly are you trying to do?  Code like this should never be needed:

```
        private async void navigateOne()
        {
            await navigationService.NavigateAsync("Page2"); // /Page1/Page2
            await Task.Delay(2_000);
            await navigationService.NavigateAsync("Page3"); // /Page1/Page2/Page3
        }
``
You would use deep linking instead: `await navigationService.NavigateAsync("Page2/Page3")`

I have no idea what you are trying to accomplish with code like this:
```
        private async void navigateThree()
        {
            await navigationService.NavigateAsync("Page2"); // /Page1/Page2
            await Task.Delay(2_000);
            await navigationService.GoBackAsync();
            await navigationService.NavigateAsync("Page3");// /Page1/Page3 with flicker

        }
```
You should be able to use a combination of GoBackToRootAsync and deep linking, or even relative navigation like `../../View`

**Comment by Tragetaschen** [comment]
Please read the OP.
I want to get from /Page1/Page2 to /Page1/Page3 from within Page1ViewModel

**Comment by brianlagunas** [comment]
So the active page is Page2, but you want to navigate from Page1? That doesn't make a lot of sense. How would you do this in normal XF? You can take the same approach in Prism.

**Comment by brianlagunas** [comment]
You have to know, that the NavigationService instance belongs to the page, it is not global. So Page1 has its nav service, Page2 has its own nav service, and so on. Nav is relative to the page you are calling it from. This is how nav in XF works. Each page has it's own nav stack, actually 2 of its own nav stacks. If you want to nav from View1, then in XF you'll call PopToRoot to get to View1, and then navigate to Page3. You can do the same in Prism.

**Comment by Tragetaschen** [comment]
I have an app-external process that I want to synchronize the GUI with (exposed via Bluetooth LE). A central navigation page to start/stop the process and children for each step while running seemed like a good fit. However, the Prism navigation infrastructure did weird stuff when I tried it: at least the behavior for "../Page3" doesn't really make sense from a domain-specific language perspective.

I could might be able to do the child-to-child navigation from each child (with `../Page3` from Page2), but when I started to think about synchronization with the service and race conditions, a central child management from Page1 seemed way easier.

The problem with Pop + Nav is the double animation

**Comment by brianlagunas** [comment]
You have a couple of options. Navigate to Page 3 and create an extension method to INavigationService to actually remove the page from the stack. Or try using animated: false in the NavigateAsync method.

**Comment by Tragetaschen** [comment]
I will do some experiments tomorrow and see if I can navigate through the API (pun intended). As you mentioned, I should be able to navigate to Page3 and then remove Page2 "behind the scenes".

> You have to know, that the NavigationService instance belongs to the page, it is not global

Part of the confusion is that Prism's navigation DSL partly works on the full, active-to-root stack and partly locally to the page calling navigation APIs: GoBackAsync will pop the top-most page (Page2 even when called from Page1) while ".." operates on the current page's layer ("Page1") and "/Page3" again works with the tip of the navigation entire stack. So "../Page3" mixes different concepts which is why i still think that it should do something different than it currently does.

**Comment by Tragetaschen** [comment]
I have been able to do this by manipulating the native navigation stack and using PageUtilities manually.

Just as a last note: When in /NavigationPage/Page1/Page2 and doing navigation in Page1ViewController, I haven't found a single API call that drives the INavigationAware interface correctly. For example, you'll get multiple, consecutive OnNavigatedFrom in Page1 and no OnNavigatedFrom in Page2. My impression is that this part of the navigation infrastructure is callable, but actually quite broken. I simple fix would be to block navigation when not at the tip of the stack or even better fix it. EOT for me.
