### ISSUE TITLE
[Bug] Container.Resolve<INavigationService> diff Constructor Resolve

### ISSUE THREAD

**Issue by rudacs** [PrismLibrary/Prism#1877]
### Description
When attempting to resolve INavigationService using Container resolve, but returned object is different
```
public ViewModelBase (INavigationService nav1)
{
    var nav2 = Prism.PrismApplicationBase.Current.Container.Resolve<INavigationService>();

    // the navigation is not in the constructor, I am exemplifying.
    // nav1 works if I try to navigate
    // nav2 doesn't work if I try to navigate
    // nav1.Page <> nav2.Page
}
```

From what I understand the Page property is not set.

### Steps to Reproduce

1. Create ViewModel
2. Create the constructor as mentioned above.
3. Verify that nav1 is different from nav2.

### Expected Behavior
nav2 is set the current Page to be able to work the navigation.

### Actual Behavior
nav2 does not come set the current Page.

### Basic Information

- Version with issue: 7.2 (DryIoc)
- Last known good version:
- Xamarin.Forms version: 4.1
- IDE: Visual Studio for Mac

### Screenshots
![Captura de Tela 2019-08-08 às 14 50 01](https://user-images.githubusercontent.com/2153223/62725672-f9bee080-b9eb-11e9-9b84-cd58c3943e7e.png)
![Captura de Tela 2019-08-08 às 14 50 09](https://user-images.githubusercontent.com/2153223/62725675-f9bee080-b9eb-11e9-8731-7e5fe7ebb7e1.png)
![Captura de Tela 2019-08-08 às 14 50 15](https://user-images.githubusercontent.com/2153223/62725677-fa577700-b9eb-11e9-9c43-e9e8b4b7cf59.png)

**Comment by brianlagunas** [comment]
This is by design. There is no global navigation service in XF. Each Page get's its own INavService instance. That's why the one you inject works, and the one you try to access statically that does not belong to the current page doesn't.

**Comment by rudacs** [comment]
Prism should take the last page to reflect and give the user the option to manipulate. In case you have to access elsewhere in the code other than ViewModel.
According to what you said. I will only be able to navigate within the ViewModels.

Wonderful :(

**Comment by brianlagunas** [comment]
@rudacs we can't do that. Navigation in XF is complex. You can always navigation from the View by calling a method in your VM, or use the PrismApplications INavService instance if you want the root page.
