### ISSUE TITLE
[Enhancement] ModuleParameters for IModuleInfo

### ISSUE THREAD

**Issue by hnabbasi** [PrismLibrary/Prism#1878]
## Summary

While loading modules, it might be helpful to receive parameters from the module.

### Introduce: IModuleParameters
Nothing fancy, just like `INavigationParameters` and `IDialogParameters`, it will be `IEnumerable<KeyValuePair<string, object>>`

```csharp
public interface IModuleParameters : IEnumerable<KeyValuePair<string, object>>, IEnumerable
{
    . . .
}
```
### Update: IModuleInfo
Update `IModuleInfo` to have `IModuleParameters` as a property.
```csharp
public interface IModuleInfo : IModuleCatalogItem
{
    . . .
    IModuleParameters Parameters { get; set; }
}
```
### Update: IModule
Not sure what the best way to do this may be. But maybe we can do something like this,

```csharp
public interface IModule
{
    . . .
    void RegisterParameters(IModuleParameters parameters);
}
```
### Update: IModuleManager

```csharp
public interface IModuleManager
{
    . . .
    IModuleInfo LoadModule(string moduleName);
}
```
## Intended Use Case
With `IModuleParameters` in place, we can load a module and receive any parameters the module may send. 

### Scenario:
Say we have an application that shows functions/menu items based on user role. We want to load each module and add the icon to the main MasterDetailPage in the main application.
When I load a module, I want the module to provide me some information, e.g. what icon it wants to use, what text it wants to use on the menu item, and any other info we might need from it.

### Usage:
Register,
```csharp
public class FooModule : IModule
{
    . . .
    public void RegisterParameters(IModuleParameters parameters)
    {
        parameters.Add("menu_title", "Feature A");
    }
}
```
Receive,
```csharp
public class App : PrismApplication
{
    . . .
    protected override void ConfigureModuleCatalog(IModuleCatalog moduleCatalog)
    {
        var m = moduleCatalog.AddModule<FooModule>();
        if(m.Parameters.ContainsKey("menu_title"))
        {
            var title = (string) m.Parameters["menu_title"];
            MenuItems.Add(title);
        }
    }
}
```
also,
```csharp
public class BarViewModel
{
    . . .
    public class BarViewModel(IModuleManager moduleManager)
    {
        var m = moduleManager.LoadModule("FooModule");
        if(m.Parameters.ContainsKey("menu_title"))
        {
            var title = (string) m.Parameters["menu_title"];
            MenuItems.Add(title);
        }
    }
}
```

Maybe also pass parameters to the module. I can investigate more if this is something that makes sense. 

Thoughts? 🤓

**Comment by brianlagunas** [comment]
This would not be the correct approach for what you want. Instead, just use a simple menu service.

**Comment by hnabbasi** [comment]
Agreed. Not the best example. I was thinking in terms of modules being able to communicate back to the app.

**Comment by dansiegel** [comment]
that's not really something you should need to do as a global Prism thing. It would really be the wrong placement for such a feature. It's the sort of thing that if you're using a module you should provide your own service to handle what you need to pass back such as the afore mentioned MenuService which is something I commonly add (and commonly do differently on each app).

**Comment by hnabbasi** [comment]
Ah. Makes sense. I was thinking too much into it I guess. Thanks guys 👍
