### ISSUE TITLE
[Enhancement] AutowireViewModelChanged resolution validation

### ISSUE THREAD

**Issue by bdovaz** [PrismLibrary/Prism#1879]
## Summary

I'm integrating Prism Core in Unity3D for our codebase.

Doing that I encountered a problem with this specific method. The problem is that when it's not possible to return a ViewModel.

If you inspect the code you will see a "return;". The problem is that we can't check of handle that case:

https://github.com/PrismLibrary/Prism/blob/master/Source/Prism/Mvvm/ViewModelLocationProvider.cs#L105

It would be nice to at least return a bool with the result.

## API Changes

public static void AutoWireViewModelChanged(object view, Action<object, object> setDataContextCallback);

To

public static bool AutoWireViewModelChanged(object view, Action<object, object> setDataContextCallback);

## Intended Use Case

Autowire validation.

**Comment by dansiegel** [comment]
@bdovaz can you expand on your proposal a bit more? How you would see this for the normal use case and how this helps you for yours?

**Comment by brianlagunas** [comment]
Closing as requested information was not provided.
