### ISSUE TITLE
View Model features in portable class library

### ISSUE THREAD

**Issue by hameedfs** [PrismLibrary/Prism#188]
For the UWP version, can you split the view model related features into a separate portable class library? I ask this mainly because of the inadequate support for testing universal windows components in Visual Studio 2015 - you cannot have code coverage, VSO has some issues executing tests in appx package, etc. It also makes sense to not keep view model in UWP project from design perspective as it can be platform agnostic.

**Comment by bartlannoeye** [comment]
You're right that testability for UWP apps is inadequate and we certainly encourage you to place your view models in a separate library to be able to test them. What prevents you from adding Prism.Windows to that library?

**Comment by hameedfs** [comment]
I do have my view models in a separate class library. The problem is this - Prism's ViewModelBase base is defined in Prism.Windows project, a Universal Windows class library. The class library containing my view models should also be Universal Windows class library for referring to Prism.Windows (this is a restriction by VS2015). Unit tests for my view models need to be created in Universal Windows unit test app project - it cannot be a regular unit test project. Universal Windows unit test app projects have limitations like we cannot use regular mocking frameworks like Microsoft Fakes or Moq, we cannot get code coverage, etc.

The problem can be resolved if ViewModelBase and the related components are moved out of Prism.Windows project to a portable class library targeting .Net & Windows (similar to Prism.csproj). If that is done, my project containing the view models can be a portable class library and the unit tests can be in a regular unit test project that does not have the mocking and code coverage restrictions.

**Comment by bartlannoeye** [comment]
I've quickly checked the feasability and one of the types I'm running into is [Windows.UI.Xaml.Navigation.NavigatingCancelEventArgs ](https://msdn.microsoft.com/library/windows/apps/br243278) which is a WinRT type, while .NET/Silverlight (WP) has [System.Windows.Navigation.NavigatingCancelEventArgs](https://msdn.microsoft.com/en-us/library/system.windows.navigation.navigatingcanceleventargs(v=vs.110).aspx). Rewriting the UWP codebase to make these 2 types (with different properties) interchangeable through compile directives just to support better testability would bring us too far in my opinion.

**Comment by brianlagunas** [comment]
Agreed.  Let's hope VS2015 is improved to better support these testing scenarios.
