### ISSUE TITLE
Broken Link for detailed view of each prism assembly

### ISSUE THREAD

**Issue by IoTFier** [PrismLibrary/Prism#1881]
### Description
Detailed view of each assembly per Prism package is inaccessible due to broken link

### Steps to Reproduce

1.  Go to https://github.com/PrismLibrary/Prism/tree/v7.2.0.1367 and click on the link as pointed by the picture below
![image](https://user-images.githubusercontent.com/26844611/63240844-0ecf1700-c217-11e9-9d87-de430deb6701.png)

### Expected Behavior
Show the working link

### Actual Behavior
Getting 404

### Screenshots
![image](https://user-images.githubusercontent.com/26844611/63240916-64a3bf00-c217-11e9-8594-8940009f97cd.png)

**Comment by brianlagunas** [comment]
How about a PR? The link should be here: http://prismlibrary.github.io/docs/getting-started/NuGet-Packages.html

**Comment by bartlannoeye** [comment]
Can't update the documentation of a release, but master is updated (and so future releases will show the new link).
