### ISSUE TITLE
[Enhancement] WPF - Navigation in Dialogs

### ISSUE THREAD

**Issue by murphyjstevens** [PrismLibrary/Prism#1882]
## Summary

Add new regions to DialogWindows to allow navigation after the dialog is opened. 

## API Changes

The current implementation of DialogService could use regions instead of loading it in through the DialogService.cs as it is now. This would allow for navigation in the dialog which currently appears to be impossible. I currently have a custom dialog service that is using the region "Dialog" in the DialogWindow to allow for navigation. An issue I ran into was the region was sticking around on close, so I added _regionManager.Regions["Dialog"].RemoveAll() to prevent multiple navigations after multiple dialogs have been open. 

This would make navigation as simple as other forms of navigation...

RegionManager.RequestNavigate("Dialog", "SecondView", parameters);

My implementation of it only works if there's only one dialog opened. That works for me so far but to be put in the framework it will need to work in cases of multiple dialogs, so it would require unique dialog region names and a way to get which dialog you desire to navigate on. 

## Intended Use Case

I currently have a custom dialog that opens an informational screen and then allows you to navigate to an Add screen so you can add one of the types in the first screen. Since navigation doesn't exist in current Prism Dialog Service, I have to stick with the custom approach. Allowing navigation in dialogs will help support the use cases where it's needed and/or optimal.

**Comment by brianlagunas** [comment]
You can do this yourself in your dialogs. This is not something that should be hard-coded in the DialogService.  For multiple instances you must use ScopedRegions
