### ISSUE TITLE
[Bug] Repeating Initialization of Controls loaded through View Discovery

### ISSUE THREAD

**Issue by DinkWerks** [PrismLibrary/Prism#1885]
### Description
During some debugging for a WPF application that I am creating, I noticed that a child user control loaded into its region using view discovery was being initialized multiple times in a row. It initializes once when navigating to the parent region for the first time, but the on successive navigations to the parent control the child initializes multiple times. The amount of times it initializes usually grows by two each visit to the parent. In this scenario, the parent control is implementing IRegionMemberLifetime and the KeepAlive property is set to false. I don't understand how repeating the creation of the Parent view would cause this.

I've attached a link to a repo for a simple app that can recreate the problem. If you put a breakpoint in the ChildViewModel's constructor swap between the views, you should see it.

Thanks!

### Steps to Reproduce
1.  Create two top-level controls and place them in the content region. One will be the parent container to a child and the other is just to reset the test.
2.  Have the parent implement IRegionMemberLifetime and set the KeepAlive property to false. Make sure it has a region for the child control.
3.  Create a child control with an and place it into the region with view discovery.
4.  Put a breakpoint in the constructor of the child.
5.  Swap between the top-level controls and observe the breaking point.

### Expected Behavior
The child user control would initialize once every time the parent control is navigated to

### Actual Behavior
The child control initializes once when loading when switching to the parent for the first time, then initializes three times successively when switching to the parent for the second time. This pattern continues, with the number of times the child initializes usually increasing by two every time, but the increase isn't completely consistent.

### Basic Information

- Version with issue: v7.2.0.1367 (initial encountered in v7.1.0431)
- Last known good version: Unknown
- Xamarin.Forms version: N/A
- WPF .NET 4.7.2
- IDE: VS2019 Community

### Reproduction Link
https://github.com/DinkWerks/RepInitBug

**Comment by brianlagunas** [comment]
This is to be expected. You are registering a child view with a region called ChildRegion in the ctor of a parent VM. Then you are creating multiple instance of that parent VM causing multiple registrations of your child with the ChildRegion. Just because the parent has KeepAlive set to true, doesn't mean that erases the registration of the child view.  You need to either change keepAlive to false (so multiple instances aren't created), or move your RegisterViewWithRegion code somewhere else so its not being called multiple times.
