### ISSUE TITLE
[Enhancement] Select tab by index

### ISSUE THREAD

**Issue by sanyandreichuk** [PrismLibrary/Prism#1886]
## Summary

When for some reason we need to use the same page for different tabs in TabbedPage, `SelectTabAsync` will always select the first available page with the name, without the ability to select another page with the same name. In this case, it will be convenient to have the ability to select tab by TabbedPage child index.

Here is the repro project with my attempt to implement `SelectTabAsync` by a child index method
https://github.com/sanyandreichuk/PrismSelectTabByIndex

## API Changes

The new extension method could be added to INavigationServiceExtensions

`Task<INavigationResult> SelectTabAsync(this INavigationService navigationService, int index, INavigationParameters parameters = null)`

## Intended Use Case

Select tab in TabbedPage by child index.

**Comment by brianlagunas** [comment]
This is not something Prism will add. It would be easy for you to add yourself though. It's just an extension method.
