### ISSUE TITLE
[Bug] Bad exception for invalid ObservesProperty expression

### ISSUE THREAD

**Issue by WalkerCodeRanger** [PrismLibrary/Prism#1893]
### Description

Calling `DelegateCommand.ObservesProperty()` with an expression that isn't a property chain but rather is just a value throws an exception that doesn't indicate what is wrong.

### Steps to Reproduce

In a class that implements `INotifyPropertyChanged` add the line `new DelegateCommand(() => { }, () => true).ObservesProperty(() => this);` and run it.

### Expected Behavior

Throw an exception indicating that the expression is invalid because it doesn't refer to any property.

### Actual Behavior

Throws `System.InvalidOperationException 'Stack empty'`.

### Basic Information

- Version with issue: 7.2.0.1367

**Comment by brianlagunas** [comment]
Not a bug, this is by design. Yo must specify a property to observe, not just a value

**Comment by WalkerCodeRanger** [comment]
I disagree, this is a bug. Yes, you must specify a property to observe. I clearly stated the expected behavior was to throw an exception. The bug is the confusing exception that fails to convey to the developer what is going on.

**Comment by brianlagunas** [comment]
It's not a bug. It's an enhancement. If you would like to submit a PR to implement this request, I'll reopen this issue.
