### ISSUE TITLE
[Bug] DialogService sets width when RelativeHeightRequest was set

### ISSUE THREAD

**Issue by Denrage** [PrismLibrary/Prism#1894]
### Description

When the RelativeHeightRequest was set through DialogLayout.RelativeHeightRequest then the DialogService overwrites the width of the popup and set it to the desired height.

https://github.com/PrismLibrary/Prism/blob/master/Source/Xamarin/Prism.Forms/Services/Dialogs/DialogService.cs#L290

### Steps to Reproduce

1. Set RelativeWidthRequest and RelativeHeightRequest in XAML
2. Open Popup in App
3. The popup is now bigger than the visible area

### Expected Behavior
RelativeHeightRequest would set the Popup height to a percentage of the available screen

### Actual Behavior
The popup is bigger than the available screen

### Basic Information

- Version with issue: v7.2.0.1367
- Last known good version: -
- Xamarin.Forms version: 4.1.0.673156
- IDE: VS 2017 15.9.13

### Screenshots

![image](https://user-images.githubusercontent.com/22132579/64406968-6f69ab00-d083-11e9-8678-d8dd5111f7cc.png)

### Reproduction Link

[DialogReproduction.zip](https://github.com/PrismLibrary/Prism/files/3582504/DialogReproduction.zip)

**Comment by nschoenberg** [comment]
I think this line is also wrong, should be using relativeHeight. Seems like copy paste Issue
https://github.com/PrismLibrary/Prism/blob/b302ae78774c0c4edd7bb9754965fb5149bc0212/Source/Xamarin/Prism.Forms/Services/Dialogs/DialogService.cs#L293

**Comment by dansiegel** [comment]
@nschoenberg great catch!
