### ISSUE TITLE
[Bug] Checkbox's in CollectionView EventToCommandBehavior not firing

### ISSUE THREAD

**Issue by ScarlettCode** [PrismLibrary/Prism#1895]
### Description

If I create a checkbox and add the eventToCommandBehavior everything works, the event is fired, and the command gets called.

`<CheckBox>
<CheckBox.Behaviors>
<behaviors:EventToCommandBehavior EventName="CheckedChanged" Command="{Binding OrderSelectedCommand}"  EventArgsConverter="{StaticResource SelectionChangedEventArgsConverter}"/>
</CheckBox.Behaviors>
</CheckBox>`

If however I then put this code within a collectionView so there are multiple checkboxes then the eventToCommandBehaviour stops working. If I add an event and add a handler on the xaml code behind that gets hit so the event is firing in the collectionView, the command however isn't.

It doesn't matter if I bind to an isSelected from the collectionView or not so it's just got to do with creating multiple checkboxes

### Expected Behavior

Clicking on any of the checkboxes in the collection view should fire the same command

### Actual Behavior

Nothing happens, the command isn't fired

### Basic Information

- Version with issue: 7.2.0.1367
- Last known good version: None
- Xamarin.Forms version: 4.2.0.709249
- IDE: Visual Studio 2019 - 16.3 Preview 2

I'm not sure if this is an underlying Forms issue or a Prism issue. Because it works with an Event in the collectionView I thought it might be a Prism issue with the eventToCommand behavior in Prism

**Comment by brianlagunas** [comment]
Closing as no reproduction app was provided. Also, this is 99.99% an issue with your code. Prism does not have any control over data binding behavior or binding contexts. You'll have to make sure you have your binding context, XAML, and bindings created properly.

**Comment by ScarlettCode** [comment]
Link to repro - https://github.com/ScarlettCode/CheckBoxBug

**Comment by ScarlettCode** [comment]
@brianlagunas Can we reopen this with reproduction app attached?

**Comment by eincioch** [comment]
good afternoon, I need help with this too please

I need to select the check and get the selected item, the checkbox is inside my collectionview

<CheckBox 
                                                IsChecked="{Binding IsSelected, Mode=TwoWay}">
                                                <CheckBox.Behaviors>
                                                    <behaviors:EventHandlerBehavior EventName="CheckedChanged">
                                                        <behaviors:InvokeCommandAction 
                                                            Command="{Binding Path=BindingContext.CommandCheck, Source={x:Reference collectionView}}"
                                                            CommandParameter="{Binding .}" />
                                                    </behaviors:EventHandlerBehavior>
                                                </CheckBox.Behaviors>
                                            </CheckBox>

**Comment by dzebas** [comment]
I've the same issue as Scarlett, if checkbox is inside ListView then EventHandlerBehavior doesn't work.

**Comment by ScarlettCode** [comment]
I've been using this https://github.com/enisn/Xamarin.Forms.InputKit with pretty good success to achieve what I needed
