### ISSUE TITLE
[Enhancement] Little confusing code in BindableBase

### ISSUE THREAD

**Issue by MikhailLavrenov** [PrismLibrary/Prism#1900]
Prism/Source/Prism/Mvvm/BindableBase.cs 

It seems to me, code little confusing:

SetProperty<T>(...)   notifies listeners by calling method  RaisePropertyChanged(...), it is clear.
RaisePropertyChanged(...) In summary said "Raises this object's PropertyChanged event.", but it is not raises event. 
RaisePropertyChanged(...) have sole doubtful duty - call another method OnPropertyChanged() and nothing else. 
OnPropertyChanged()  method finally raise event. 
So we have method which call another method which call event - it is confusing.

I think, RaisePropertyChanged () must raise event itself.

2 methods of SetProperty duplicating code, so SetProperty without Action can be realized by calling SetProperty with Action onChanged =null.

protected override bool SetProperty(ref T storage, T value, [CallerMemberName] string propertyName = null) => SetProperty(ref storage, value, null, propertyName);

**Comment by MikhailLavrenov** [comment]
SetProperty<T> without Action can be realized by calling SetProperty<T> with Action onChanged =null, it is prevent code duplicating:
protected override bool SetProperty<T>(ref T storage, T value, [CallerMemberName] string propertyName = null) => SetProperty(ref storage, value,  null,  propertyName);

**Comment by brianlagunas** [comment]
If you read the comments in the code, you will see what's going on there. If you look at the code, you will see the Obsolete attributes as well.
