### ISSUE TITLE
[Enhancement] ErrorsContainer add property errors separate one at a time

### ISSUE THREAD

**Issue by MikhailLavrenov** [PrismLibrary/Prism#1901]
Now we must add all errors at a time  for one property, in some cases this is not suitable, so we must itselt get collection of  existen errors, add new uniq to collection and set back to errorContainer.

So I suggest add method that add property error one at a time:
public void SetError(string propertyName, T newValidationResult).

Also in ErrorsContainer used Expression<Func<TProperty>> propertyExpression instead of [CallerMemberName]string propertyName = ""

**Comment by brianlagunas** [comment]
We accept PRs 😃

**Comment by MikhailLavrenov** [comment]
I forgot to say, if it will be possible to add errors separately, it should be possible to delete them as well.
Naturally, SetError (...) should take care of the uniqueness of the added errors.
