### ISSUE TITLE
[Enhancement] Multiple dialog windows

### ISSUE THREAD

**Issue by Pretasoc** [PrismLibrary/Prism#1903]
## Summary

While watching your todays stream @brianlagunas i noticed some possible further extension point for the `IDialogService`. It would be nice to register multiple named `IDIalogWindow`s for different purposes. So you could have a `IDialogWindow` for message boxes and an other for more specialized dialogs, such as a `RibbonWindow` or a wrapper for the native file windows.

## API Changes

Add an overload to register a name with an `IDialogWindow` such as

    void RegisterDialogWindow<TWindow>(this IContainerRegistry containerRegistry, string name)

This would simply register a maping from `IDialogWindow` to `TWindow` with the name `name` to the container. 

I have multiple ideas, how to declare, which dialog goes into which window, but i'm not fully satisfied with them:

There could be an additional optional string parameter for `RegisterDialog` that defaults to `null`. This would require a named parameter if most cases, to prevent breaking current code.

```
void RegisterDialog<TView>(this IContainerRegistry containerRegistry, string name = null, string WindowName = null)

void RegisterDialog<TView, TViewModel>(this IContainerRegistry containerRegistry, string name = null, string WindowName = null)
```

A second option would be to allow an additional generic parameter to specify the type of the `IDIalogWindow`.

    void RegisterDialog<TView, TViewModel, TWindow>(this IContainerRegistry containerRegistry, string name = null) where TWindow : IDialogWindow

This wouldn't also do it for all cases, since you had to specify the ViewModel each time.

A third option would be a new Attribute on the dialog control, that would specify name of the `IDialogWindow`. Like `[DialogWindowName("MyDialogWindow")]`.

## Intended Use Case

As described above, there may be applications, that need different types of `IDialogWindow`. Also in the meantime of writing this @brianlagunas had mentioned the idead by himself.

If this is something you want to do, i am willing to submit a PR, but that might clash with the changes you plan.

**Comment by qtbui159** [comment]
good idea

**Comment by wyshmily** [comment]
Is there any workaround, before this feature is shipped?
Need as special window to show Android like Toast message.

**Comment by brianlagunas** [comment]
@wyshmily Yes, the workaround is to write your own toast dialog service.

**Comment by brianlagunas** [comment]
DONE!
