### ISSUE TITLE
Make Subscribe methods all virtual for PubSubEvent

### ISSUE THREAD

**Issue by kayhustle** [PrismLibrary/Prism#1904]
## Summary

I can't mock the PubSubEvent in a unit test because the PubSubEvent Subscribe methods are not virtual.  

## API Changes

Please just make all methods virtual for the generic and non generic version of PubSubEvent or make PubSubEvent implement an interface.

## Intended Use Case

Unit testing with Prism when I need to replicate event publishing.

**Comment by brianlagunas** [comment]
You create a PubSubEvent to use in your tests. You don't need to mock it.

**Comment by kayhustle** [comment]
Yeah, but what if I want to do something like 
eventAggregator.GetEvent<MyEvent>().Subscribe(MyEventHandler, ThreadOption.UIThread);
This will fail in a unit test with a real event because there is no UI Thread.
It will throw the exception:
System.InvalidOperationException: 'To use the UIThread option for subscribing, the EventAggregator must be constructed on the UI thread.'

**Comment by brianlagunas** [comment]
You need to set your sync context to meet your testing requirements in your tests. ALso, the Subscribe is virtual

https://github.com/PrismLibrary/Prism/blob/master/Source/Prism/Events/PubSubEvent.cs#L71

**Comment by kayhustle** [comment]
Thanks for the update.  Yeah, only one overload is virtual while the others are not.  I mean from a testing perspective, I'm not really testing my code in isolation as it is calling through to yours in order to test mine.  This would make my tests look more like integration tests than pure unit tests.  Shouldn't I be able to test my view models without knowing anything about SynchronizationContexts specific to your implementation? The event is more like a service for publishing/subscribing than a data structure.  Should it not be mockable or implement some kind of interface then?  If you change some implementation detail or introduce a defect in your implementation my unit test will fail even though my logic is correct.  Thoughts?

**Comment by brianlagunas** [comment]
All other subscribe methods call that one virtual method. There is no need for the others to be virtual. The core subscribe method is. No, you're not testing Prism code to test your. The sync context is not specific to Prism's implementation, its specific to what you are trying to test/mock.  This has nothing to do with testing Prism. This has to do with how you are testing your code.  For one, if we introduced a defect in PubSubEvent, the Prism unit tests would fail. If somehow the detect didn't break Prism's test, then actually want your tests to fail. That's the point.

**Comment by kayhustle** [comment]
I hear what you're saying.  Just consider the following scenario.  My view models make no reference to SynchronizationContext but my unit tests do. I create an empty SynchronizationContext for the sake of testing.  Let's say you make an implementation detail change regarding the SynchronizationContext.  This could potentially fail my test, even though my code would work in production.  My tests have to know about supplying this value even though my code does not.
If you introduced a bug that broke my code, I would want that bug to be detected in my own integration tests, not necessarily in my unit tests.

**Comment by brianlagunas** [comment]
No, your VMs don't, because the sync context is provided by the framework your app is running on.  Just like your unit tests do. If your test is trying to test a UI process, you need to set your test up to do that, regardless of if you are using Prism or not. If a change was made to the sync context logic, your production app would also most likely fail, not just your tests. Which by the way, will never happen because we are not modifying this class. Hence the closed issues because Subscribe is already virtual.

**Comment by kayhustle** [comment]
So how would I test something like this:
eventAggregator.GetEvent().Subscribe(MyEventHandler, ThreadOption.BackgroundThread);

**Comment by brianlagunas** [comment]
If your code is multi-threaded, then you need to setup and write your tests that can support that. This is no different with any other mutli-threaded scenario. This is also way off topic of the issue which has been closed as "already in product".

**Comment by kayhustle** [comment]
My code has no way of knowing when the subscribed delagate will be invoked on the background thread.  It's very different as in a normal scenario I can mock a wrapper to the Task Factory or at the very least wait for the task to finish. You use Task.StartNew in the implementation.  I have to put a sleep in my test to wait for it to invoke which can produce unexpected results and affect test performance.  This reiterates the need to mock the events directly, hence making subscribe methods virtual.

**Comment by kayhustle** [comment]
Another scenario to consider is this.  
Let's say I subscribe to an Event and return a SubscriptionToken.  
If I want to test that a subscriptionToken was Diposed by my code, since it's Disposable, I have no way to test that because I can't mock the SubscriptionToken returned by the Event.  Unsubscribe is virtual so I can therefore test that Unsubscribe is called on my SubscriptionToken, but I can't test the other way around if I want to dispose of the SubscriptionToken directly.  
This again reiterates the need for PubSubEvent to implement an interface.  You should reopen this case.
