### ISSUE TITLE
[Enhancement] Add ContentView to Prism Template Pack

### ISSUE THREAD

**Issue by ScarlettCode** [PrismLibrary/Prism#1906]
## Summary

For Xamarin projects add the ability to create a ContentView by using the template pack.

## Intended Use Case

When using partial view's with a ContentView you have to either manually create the ContentView or create a ContentPage and then change a few things. Would be great to have a ContentView option which also add the correct ViewModelLocationProvider.

**Comment by dansiegel** [comment]
There is already a ContentView template from Xamarin. You shouldn’t need anything from Prism. If it’s the ViewModelLocator you’re worried about you just need to register the View/ViewModel types with the ViewModelLocationProvider.

**Comment by ScarlettCode** [comment]
@dansiegel there is, the Prism template pack just creates the view and the viewmodel in one go where as the Xamarin one only creates the view
