### ISSUE TITLE
Skip the requirement of ViewModelLocator for dialogs

### ISSUE THREAD

**Issue by EuroEager2008** [PrismLibrary/Prism#1907]
RN has some samples of dialogs where both a ViewModelLocator is used and the RegisterDialog<TView, TViewModel> are used.
I think this is redundant (and it works fine if i use RegsisterDialog<TView> as long as ViewModelLocator is utilized.
However, it should not be necessary to setup ViewModelLocator as long as the RegisterDialog<TView, TViewModel> is used.

**Comment by brianlagunas** [comment]
Keeping it consistent with the rest of Prism. Making this one different would just cause confusion.
