### ISSUE TITLE
PRISM Xamarin.Forms INavigationService understanding

### ISSUE THREAD

**Issue by poseydonfba** [PrismLibrary/Prism#1908]
I wonder if the option discussed in the link below can already be made using Prism.
https://stackoverflow.com/questions/43388248/prism-xamarin-forms-inavigationservice-understanding

Project using MasterDetail.

In XF without Prism, using PushAsync, a Page opens without replacing MainPage, with NavigationBar and back button.

_- App.css_
MainPage = new NavigationPage(new MyMasterPage()); 

_- Call SecondPage from MyMasterPageViewModel.cs_
await _navigation.PushAsync(new SecondPage());

The SecondPage page opens as modal and with NavigationBar and back button.

I could not reproduce this same behavior using Prism.

Thanks

**Comment by dansiegel** [comment]
All questions should be asked on StackOverflow
