### ISSUE TITLE
Prism Documentation

### ISSUE THREAD

**Issue by brianlagunas** [PrismLibrary/Prism#191]
We need to find a home for our docs.  We have a ton of docs from our Prism 5 release.  These need to be updated, but when we do update them where should they live?  Right now they are in word docs (.docx).

We could try to convert them to markup and put them on GitHub, but I am worried that would make them difficult to find/search.

Any ideas or thoughts on the matter?

**Comment by tomzorz** [comment]
I think markup + putting them on GitHub is the way, but https://pages.github.com/ could come in handy for accessibility. There are surely plenty of things that can take markup files and render static html pages from them.

**Comment by bartlannoeye** [comment]
Tough call. If you want to move to GitHub, pages might be better than the Wiki indeed as you can't make decent PRs yet for wiki pages afaik.

**Comment by brianlagunas** [comment]
Well, we will be building a website to help aggregate our content in one place under the PrismLibrary.com domain.  Do we can use GitHub pages and just use a redirect for the domain name.

**Comment by tomzorz** [comment]
@brianlagunas plenty of projects do that.

**Comment by brianlagunas** [comment]
Step one complete:  http://prismlibrary.github.io

**Comment by tomzorz** [comment]
I stumbled upon this solution - opinions?

1) Get docs up in repo: https://github.com/reactiveui/ReactiveUI/tree/master/docs
2) Use the service: https://readthedocs.org/
3) ..?
4) Profit: https://reactiveui.readthedocs.org/en/latest/dependency-injection/splat/

**Comment by brianlagunas** [comment]
@tomzorz This looks very promising!  Thanks.  I will check it out.  Looks like either way we need to convert our word doc into markup.

**Comment by bzuillsmith** [comment]
There are also options to use markdown in your own website. [markdown-js](https://github.com/evilstreak/markdown-js) is one of them. There are more. So you can start in GitHub and transfer files to your own site down the road. However, GitHub is an excellent place to host documentation and has the added benefit of being easy for the community to contribute.

**Comment by bartlannoeye** [comment]
Another option: http://www.toptensoftware.com/markdowndeep/, used by messagehandler.net for their [documentation](https://github.com/MessageHandler/MessageHandler.Documentation/).

**Comment by brianlagunas** [comment]
Okay so step one is definitely convert current docs into markdown. I have created issue #198 for this.
