### ISSUE TITLE
[XF] CanNavigate never returns Success = false for NavigateAsync

### ISSUE THREAD

**Issue by akamud** [PrismLibrary/Prism#1912]
### Description

Whenever you have a `IConfirmNavigation` or `IConfirmNavigationAsync` and you call `NavigateAsync`, you can't tell if the confirmation was `true` or `false`.

### Steps to Reproduce

1. Clone the repro repo provided [here](https://github.com/akamud/PrismConfirmNavigation)
2. Run the app and click on `Navigate` button on the bottom
3. Click "No" on the "CanNavigate?" confirmation
4. You should see an alert with the `Success` property of `NavigationResult`.

### Expected Behavior
`NavigationResult.Success` should be `false` with a `NavigationException`, just like the [back](https://github.com/PrismLibrary/Prism/blob/master/Source/Xamarin/Prism.Forms/Navigation/PageNavigationService.cs#L91) behavior.

### Actual Behavior
`NavigationResult.Success` is still `true`.

### Basic Information

- Version with issue: 7.2.0.1367
- Last known good version: None that I know of
- Xamarin.Forms version: 4.0.0.425677+
- IDE: Visual Studio for Mac 2019.1

### Reproduction Link

https://github.com/akamud/PrismConfirmNavigation

-----

The problem with the actual behavior is that I cannot act on a refusal to navigate. I have a use case that needs this information: I need to know which item in the menu is selected, so I log the last selected item. Since `NavigateAsync` always returns `.Success = true`, even when the confirmation is `false`, my app is changing the selected page even when the user refuses to navigate.

Is there any reason why the `Navigation` doesn't [fill](https://github.com/PrismLibrary/Prism/blob/master/Source/Xamarin/Prism.Forms/Navigation/PageNavigationService.cs#L696) the `NavigationException`?

I can easily send a PR fixing this if you agree that is something you want changed.

**Comment by brianlagunas** [comment]
This is actually a scenario I never considered. I think you're onto something here. Submit your PR so I can see what you're thinking in code.

**Comment by akamud** [comment]
I opened #1919 fixing this.

**Comment by brianlagunas** [comment]
We are having an issue with our build server. As soon as that is resolved we will move forward with your PR. Thanks for the help on this one.
