### ISSUE TITLE
[Bug] Method OnNavigatedTo not executed 

### ISSUE THREAD

**Issue by ArthurConceicao** [PrismLibrary/Prism#1913]
I have a viewmodel with a listview that are filled with items from API, clicking an item navigates to a detail page of the item. The problem is that OnNavigatedTo is not executed, the code doesn't break, but the fields are not updated because I can't fetch the data from API.

After some hours of investigation, I noticed that my list viewmodel implemented INavigatedAware and IActiveAware, and when I removed it, it worked as expected.

### Steps to Reproduce

1. Tab inside a NestedTabbedPage inside a RootTabbedPage that implements both IActiveAware and INavigatedAware, each tab has his own navigationpage
2. Try to Navigate to Content Page that implements INavigatedAware
3. OnNavigatedTo is not executed but the page is loaded without error

- Version with issue: 7.2.0.1367
- Xamarin.Forms version: 3.6.0.709228

**Comment by dansiegel** [comment]
no reproduction provided
