### ISSUE TITLE
[Enhancement] [UWP] Prism.UWP with Regions! anyone intersted?!

### ISSUE THREAD

**Issue by HesamKashefi** [PrismLibrary/Prism#1914]
## Summary

I needed a good MVVM library on UWP. 
I ask for it, you removed Prism.Uwp (without explanation of why) ! also template10 was abandoned.
I forked Prism. 
Added Uwp to it. 
Ported regions support. 
Borrowed a little from template10.
I published it as [UniversalPrism ](https://github.com/HesamKashefi/UniversalPrism).
I want to make a pull request! if anyone is interested or I can continue alone...

Here is the project: [Prism with Uwp](https://github.com/HesamKashefi/Prism/tree/prism_uwp_returns)

## API Changes
Two new libraries added, Prism.Uwp and Prism.Uwp.Unity.
Nothing is touched on the other projects but that's the point of this issue. 
We need to move regions to a new project to share it between Uwp and Wpf.
Obviously there is a need for Unit Tests. but  I don't want to do a massive change in Prism on my own and make it impossible for a pull request.

## Intended Use Case
Creating Uwp applications with Prism! 
I just published an application - [EZDictionary](https://www.microsoft.com/en-us/p/ezdictionary/9nblggh4qb3m) - for UWP last night with [UniversalPrism ](https://github.com/HesamKashefi/UniversalPrism) (a clone of [Prism with Uwp)](https://github.com/HesamKashefi/Prism/tree/prism_uwp_returns) and I think it works but it needs improvements. 
(e.g When I register my views to regions and then call navigate on that region to a view it does not work because I think AutoPopulateRegionBehavior loads registered views into the region immediately and takes precedence so my workaround was to add a delay before calling navigate on that region and then it works)

**Comment by dansiegel** [comment]
Actually we explained why in #1745 
We understand some people have some interest in UWP support, and we are beginning to work on getting commitments from companies who would be willing to officially help support this. Until then this is a non-issue.

**Comment by HesamKashefi** [comment]
OH PLEASE stop promising on UWP! 
I mean you even closed that issue with no explanation many MONTHS AGO!
I'm not new to Prism! It's been years that Prism team says this and I'm tired of hearing it!
I wish you good lucks.
