### ISSUE TITLE
[Bug] Possible OnNavigatedTo bug

### ISSUE THREAD

**Issue by stesvis** [PrismLibrary/Prism#1915]
### Description

I created a simple blank Prism app for xamarin forms and installed the package **Acr.UserDialogs**.
When I try to use it on iOS, it works fine if I call it from the code behind **OnAppearing()**, and also from the ViewModel **constructor** and the Prism **OnAppearing()**.

However, when I call it from Prism **OnNavigatedTo**, it throws an exception on iOS but it works on Android..
Are there any conflicts between Prism and the latest iOS version, or could you investigate this issue?

I already started an issue with the package repo, but it's been marked as a non issue:
https://github.com/aritchie/userdialogs/issues/672

I cannot move my code (in my real app) from OnNavigatedTo to OnAppearing because i would lose the parameters.

### Steps to Reproduce

1. Clone [this sample repo](https://github.com/stesvis/AcrTest) and run it
2. Call `UserDialogs.Instance.Loading()` from various methods (Constructor, OnAppearing, OnNavigatedTo)
3. Run on iPhones/iPads (in my case, iOS 13.0)
4. Exception is thrown

### Expected Behavior
Loading overlay should work

### Actual Behavior
Acr.UserDialogs throws an exception:

> System.NullReferenceException: Object reference not set to an instance of an object

### Basic Information

- Version with issue: Latest (7.2.0.1367) but I also tried previous ones
- Last known good version: Not sure, maybe it was with an older iOS version (current 13.0)
- Xamarin.Forms version: 4.2.0.815419 (also older ones)
- IDE: VS for Mac (latest version)

### Screenshots

[AcrTest.mov.zip](https://github.com/PrismLibrary/Prism/files/3668167/AcrTest.mov.zip)

### Reproduction Link

https://github.com/stesvis/AcrTest

**Comment by brianlagunas** [comment]
I'm sorry, but this is not a bug with Prism. OnNavigatedTo does not guarantee that the view is done rendering yet. It just means that navigation process is complete.

**Comment by dansiegel** [comment]
it's worth noting that if you implement IPageLifecycleAware you can execute whatever you need to when the View is actually visible as this hooks into the Page's Appearing/Disappearing events.

**Comment by stesvis** [comment]
Is Prism gonna work with Shell and Shell tabs etc? Just wondering if it's worth to give it a try if they are compatible. Maybe it could solve some problems.

**Comment by dansiegel** [comment]
No they do not work together yet. Last I heard @PureWeen was still working on getting his PR merged that would give us the plugin points we need. Once it's part of a stable release we can look at adding support for Shell.
