### ISSUE TITLE
[Bug] Xaml Parameter not updating Binding

### ISSUE THREAD

**Issue by jhermsen** [PrismLibrary/Prism#1917]
### Description

I run into this issue using a Syncfusion Listview with sorting.
When updating an Item and then refreshing the listview which causes the list to reorder.
All item template display data is updated, but the command parameter using the prism parameter extension or xaml on a button doesn't update.

### Steps to Reproduce

1. Unpack included sample and run it
2. Click on the Update button on Test1
3. Second Page opens, shows Test1 data and updates the bound model,
    Click on the Go back button
4. Main page opens and refreshes list view and shows the correct data,
    Click on the Test2 Update button 
5. Second Page opens, shows **Test1** data instead of Test2

### Expected Behavior
On Step 5. I expect to get the Test2 data

### Actual Behavior
It show Test1 data

### Basic Information

- Version with issue: 7.2.0.1367
- Last known good version: -
- Xamarin.Forms version: 3.6.0.344457 / 4.2.0.815419
- Syncfusion.Xamarin.SfListView version: 17.2.0.51
- IDE: Visual Studio 2019, 16.2.5

### Screenshots

Step 2.
![vlc_HfGOlJ3Hvl](https://user-images.githubusercontent.com/1192950/65887258-ef8ee200-e39d-11e9-9e04-965ae371d4b9.png)

Step 3. 
![vlc_ADhKPvyrtA](https://user-images.githubusercontent.com/1192950/65887992-1bf72e00-e39f-11e9-86e9-85af0ff58005.png)

Step 4.
![vlc_cYMNgpNiEn](https://user-images.githubusercontent.com/1192950/65887529-5c09e100-e39e-11e9-898f-a01dd03a304f.png)

Step 5.
![vlc_GoCACD0I5h](https://user-images.githubusercontent.com/1192950/65887548-65934900-e39e-11e9-8248-61d54fd7fa6b.png)

### Reproduction Link
Zip also includes video of the issue
[SfListViewRefresh.zip](https://github.com/PrismLibrary/Prism/files/3671662/SfListViewRefresh.zip)

**Comment by jhermsen** [comment]
Forgot to mention if I just bind the CommandParameter to the item {Binding .} and retrieve it using TryGetValue KnownNavigationParameters.XamlParam in OnNavigatedTo it does get the correct data.

**Comment by dansiegel** [comment]
I ran this sample and was unable to reproduce the issue that you've described. The sample seems to run as expected where you have the Key `MyData` defined in the XAML Parameter and it's available as `MyData` in the NavigationParameters in `UpdatePageViewModel.OnNavigatedTo`

**Comment by jhermsen** [comment]
Hi Dan thanks for testing I’m not able to try again right now, but just to verify.
If you update test 1 it shows it’s updated to 11 and if you then update 2 it shows that updated to 12 right?

**Comment by dansiegel** [comment]
I got the value I expected. If you still encounter an issue I would suggest referencing the Prism code directly and stepping into the code for the ParameterExtension. If you find a bug feel free to reopen the issue and perhaps submit a PR

**Comment by jhermsen** [comment]
Oké thanks will do
