### ISSUE TITLE
[Bug] Can't set property on ViewModel in InitializeAsync if corresponding View is first one upon App starting

### ISSUE THREAD

**Issue by mzhukovs** [PrismLibrary/Prism#1918]
### Description

When using IInitializeAsync to set a property on my ViewModel, it results in no exceptions being thrown but a native error and a blank page being rendered instead of the actual view. All details below.

### Steps to Reproduce

1. Add and implement IInitializeAsync to ViewModel, using an injected service to set a property on the ViewModel class. Set up App.xaml.cs OnInitialized() method to navigate to the corresponding View right away.
2. Run the app on Android device (although same thing on iOS simulator).
3. Native error gets thrown (no errors in Visual Studio) and blank page shows up instead of the actual View that that ViewModel corresponds to.

### Expected Behavior
View renders without issue.

### Actual Behavior
Native error thrown and view does not render (blank page instead).

### Basic Information

- Version with issue: Prism.DryIoc.Forms v7.2.0.1367
- Last known good version: n/a
- Xamarin.Forms version: v4.2.0.815419
- IDE: VS2019 Enterprise v16.3.1 on Windows 10
-Issue is seen in both iOS Simulator (iPhone 13.0) and physical Android Device (OnePlus 7)

### Android Device Manager Logged Error

> java.lang.NullPointerException
> 	at org.eclipse.core.runtime.URIUtil.toURI(URIUtil.java:280)
> 	at org.eclipse.e4.ui.internal.workbench.ResourceHandler.loadMostRecentModel(ResourceHandler.java:127)
> 	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.loadApplicationModel(E4Application.java:370)
> 	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.createE4Workbench(E4Application.java:220)
> 	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:557)
> 	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
> 	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:543)
> 	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:149)
> 	at com.android.ide.eclipse.monitor.MonitorApplication.start(MonitorApplication.java:63)
> 	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
> 	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
> 	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
> 	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:353)
> 	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:180)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:629)
> 	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:584)
> 	at org.eclipse.equinox.launcher.Main.run(Main.java:1438)

### Reproduction Link

This is some sample code (note that I am using Fody.PropertyChanged), if full example is required let me know and I will set it up but I don't think that the "cheshirerService" code is relevant:
```

    public class HomePageViewModel : ViewModelBase, IInitializeAsync
    {
        private readonly IMessageCheshirerService _cheshirerService;
        public HomePageViewModel(INavigationService navigationService, IMessageCheshirerService cheshirerService)
            : base(navigationService)
        {
            _cheshirerService = cheshirerService;
            Title = "Home";

            ExampleMessage = "Nice 2 $ee u! #jk";
        }

        public string ExampleMessage { get; set; }
        public string ExampleMessageCheshired { get; set; }

        public async Task InitializeAsync(INavigationParameters parameters)
        {
            ExampleMessageCheshired = await _cheshirerService.Cheshire(ExampleMessage, AppConfig.LiteDb.MaxId, false);
        }
    }
```

The above does not work and generates the error mentioned and results in a blank view:

If I get rid of InitializeAsync however and just use this, it DOES work:
```
        private async void OnExampleMessageChanged()
        {
            ExampleMessageCheshired = await _cheshirerService.Cheshire(ExampleMessage, AppConfig.LiteDb.MaxId, false);
        }

```

**Comment by brianlagunas** [comment]
A reproduction app is required. This i will be closed until one is provided.

**Comment by mzhukovs** [comment]
@brianlagunas hey Brian, sure thing. Please see attached (and disregard the name and everything else except the HomePageViewModel really, I had piggy-backed off of a different sample that I already had).

[IInitializeAsyncIssueRepro.zip](https://github.com/PrismLibrary/Prism/files/3685139/IInitializeAsyncIssueRepro.zip)

The code with InitializeAsync works on UWP, but not on Android (results on blank page as described) or iOS (crashes completely).

Please let me know if you need any further info from me.

Thanks for all that you and the Prism team do.

**Comment by brianlagunas** [comment]
This is not a bug. This is your startup code.  When you use IInitializeAsync, you must understand this is not multi-threading.  If you call an async method, you app will pause until that method has returned it's result (which your service has a Task.Delay(1000)).  Now, if I'm not mistaken, if an app doesn't compete startup by a certain number of seconds, the app will be shutdown or won't render properly.

If you simply change your code to use `IInitialize`:
```
        public async void Initialize(INavigationParameters parameters)
        {
            TestProp = await _fakeService.ReturnStringAsync(TestProp2);
        }
```

It will work as you are not pausing the startup of your application.

**Comment by mzhukovs** [comment]
@brianlagunas thanks for the clarification, I guess it was more the naming than anything else that had thrown me off. If Initialize can be made async then why have InitializeAsync?

**Comment by dansiegel** [comment]
@mzhukovs you need to understand the difference between what async void and async Task do. When you use async void your code is not awaited meaning your initialization could complete after the page is pushed and realized visually. When using async Task we are actually waiting for your code to complete before we continue with pushing your page thus there are no visual UI updates after the page is realized visually.

**Comment by mzhukovs** [comment]
@dansiegel thank you
