### ISSUE TITLE
Where are MVVM classes?

### ISSUE THREAD

**Issue by trickyvail** [PrismLibrary/Prism#192]
I'm trying to use the BindableBase class to create ViewModels.

When I look in the the source code repository ...

https://github.com/PrismLibrary/Prism/tree/master/Source/Prism/Mvvm

I can see four classes ...

BindableBase.cs
ErrorsContainer.cs
PropertySupport.cs
ViewModelLocationProvider.cs

But when I add the Prism.Core (6.0.1) Nuget package to a project only the ViewModelLocator seems to be part of the Prism.Core dll; the other 3 classes are missing. I'm attempting to reference them in the Prism.Mvvm namespace.

Currently I'm loading the Prism.Mvvm 1.1.1.1 package to retain access to this class.

Are these classes deprecated? What is the correct way to reference/load BindableBase in Prism 6?

**Comment by brianlagunas** [comment]
These classes are not deprecated, and are in the Prism.Core.dll under the Prism.Mvvm namespace.  Make sure you don't have any old packages installed that could be causing your issues.  Remove all old prism assemblies.

**Comment by trickyvail** [comment]
Thank you very much for your help. I have created a new solution and things are working as expected.
