### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by mennamagdy182-m** [PrismLibrary/Prism#1920]
![image](https://user-images.githubusercontent.com/56035906/65972295-e9fece00-e469-11e9-8a79-1c7a951637a5.png)
I receive this error everytime I try to download Prism Template Pack on VS 2019

**Comment by brianlagunas** [comment]
This looks like an issue with your Visual Studio. The icons aren't even showing up. Try downloading it from the website and installing it manually.

https://marketplace.visualstudio.com/items?itemName=BrianLagunas.PrismTemplatePack
