### ISSUE TITLE
[Enhancement] Unable to mock SelectTabAsync because it is an extension method

### ISSUE THREAD

**Issue by dconlisk** [PrismLibrary/Prism#1921]
## Summary

It would be great to be able to mock and test the SelectTabAsync method the same way that you can for other navigation methods such as NavigateAsync or GoBackAsync. It is not possible to do this at the moment due to the fact that SelectTabAsync is an extension method.

## Intended Use Case

I'd like to write a unit test using Moq that verifies that a call was made to SelectTabAsync. Just now if I try the following:

```
// Assert
var mockNavigationService = new Mock<INavigationService>();
mockNavigationService.Verify(service => service.SelectTabAsync("SelectedTabName", null));
```

I get the following exception:

> System.NotSupportedException : Unsupported expression: service => service.SelectTabAsync("SelectedTabName", null)
>     Extension methods (here: INavigationServiceExtensions.SelectTabAsync) may not be used in setup / verification expressions.

**Comment by brianlagunas** [comment]
This will not be added to the INavigationService interface at this time. Selecting a tab is not navigation. For now, the extension method is what is being provided.  I actually wasn't even going to add the extension method to Prism, but rather provide it as a snippet to bring into your own apps.

**Comment by brianlagunas** [comment]
See if this article will help you mock the extension method

http://adventuresdotnet.blogspot.com/2011/03/mocking-static-methods-for-unit-testing.html

**Comment by brianlagunas** [comment]
or this:

https://codethug.com/2017/09/09/Mocking-Extension-Methods/

**Comment by ernestoyaquello** [comment]
Whilst selecting a tab is not strictly a navigation action, being able to do so is still a feature of the whole navigation system, so I don't really see why the tab selection method wouldn't fit in the navigation service. Maybe we could try using the testing techniques suggested above, but to me, it just feels like we should be able to mock the method in a normal fashion instead of going through such hassle.

Is there any other alternative or potential change we could make to be able to mock the method? @brianlagunas

**Comment by brianlagunas** [comment]
If you're just trying to determine if a tab is selected when you call that method, have your VM under test implement IActiveAware, mock the navservice, call SelectTabAsync, and check IActiveAware.IsActive to see if it's true.

**Comment by ernestoyaquello** [comment]
I was hoping to be able to verify whether or not the method was called with the right values directly, but I guess we will have to implement some mocks and verify it indirectly by checking their state. Thanks for your help.
