### ISSUE TITLE
[Bug] Resizing dialog does not resize content.

### ISSUE THREAD

**Issue by DarqueWarrior** [PrismLibrary/Prism#1923]
### Description

Resizing dialog does not resize content.

### Steps to Reproduce

1. Load Helloworld solution from Sandbox
2. Uncomment lines 32-42 in MainWindowViewModel.cs
3. Comment out lines 57-67
4. Run the app and click "Show Dialog"
5. Grab the edge of the dialog and resize it.

### Expected Behavior

The content of the dialog would resize.

### Actual Behavior

The content stays centered and original size. It does not move to fill the larger dialog.

### Basic Information

- Version with issue: Latest version 
- Last known good version:
- Xamarin.Forms version:
- IDE: VS 2019

### Screenshots

I expected OK button to still be in lower right hand corner.

![image](https://user-images.githubusercontent.com/3853405/66286048-2cbf0c80-e895-11e9-8ce8-e291951327ba.png)

**Comment by brianlagunas** [comment]
This is not a bug. The dialog has a hard coded height and width set in it's XAML. Either remove this code or change to a minheight/minwidth and it will resize.

**Comment by DarqueWarrior** [comment]
I set all to 
Width="300" Height="150" MinHeight="150" MinWidth="300" MaxWidth="300" MaxHeight="150"
And I could still drag the corner of the window and it looks jacked up. How do I either create a fixed size Window that I can't resize or have the contents flow inside the dialog when you drag a corner to resize it?

**Comment by DarqueWarrior** [comment]
OK when I removed all Width and Height the contents flowed as expected. However, even with a min width and height they are not respected. I can resize the window to sizes less than mins and all the controls are hidden. Can you make it a fixed size. I tried setting min, max to the same values but I can still resize the window beyond all set values.

**Comment by brianlagunas** [comment]
Yes, you're dealing with two different components.; the dialog user control and the window. When you set a min width and min height on the user control it will be respected by the user control. However you must set a min width and min height on the window too if you want to restrict the window dimensions.  Just use the prism:Dialog.WindowStyle attached property on the dialog to set the window properties from the dialog.
