### ISSUE TITLE
[Bug] After updating prism 6 to prism 7 when i try to start my project i got this error

### ISSUE THREAD

**Issue by AmirAoT** [PrismLibrary/Prism#1924]
### Steps to Reproduce

1.  update prism 6.0 to prism 7.0 
2. in Bootstrapper class 
3. 

### Basic Information

- Version with issue:
- Last known good version:
- Xamarin.Forms version:
- IDE:

### Screenshots
![Bootstrapper](https://user-images.githubusercontent.com/38525216/66468951-47f16e00-ea87-11e9-98f6-e3fd7ec72379.PNG)

**Comment by dansiegel** [comment]
You most likely have something referencing Prism 6. Sometimes Visual Studio gets confused after an update and still references old dependencies in which case a clean and build should help.

**Comment by AmirAoT** [comment]
Dear sir

Thanks for your reply, I using MefBootstrapper in my application according to new prism documentation Prism.Mef will not supported.

I am sending Bootstrapper class 

Thanks:
