### ISSUE TITLE
[Bug] Prism.Forms targets errors

### ISSUE THREAD

**Issue by daniprog** [PrismLibrary/Prism#1926]
### Description

I opened the Project "...\Prism-master\Sandbox\Xamarin\HelloWorld\HelloWorld.sln".
First i got the Problem with .Net Core 3.0. That i solved with updating Visual Studio 2019 to Version 16.3.3. After re-unzipping and Opening the sln file, i got the 2 Errors. And thats why i couldnt compile the Project for Android (/Maybe also not in iOS).

### Steps to Reproduce

1. Update Visual Studio 2019 to Version 16.3.3
2. Unzip the downloaded Git Project
3. Open the Solution: "...\Prism-master\Sandbox\Xamarin\HelloWorld\HelloWorld.sln"

### Basic Information

- Version with issue: 16.3.3
- Last known good version: (Fresh tester so not good version)
- Xamarin.Forms version: 16.3.0.275 (d16-3@35ef585)
- IDE: Visual Studio 2019

### Screenshots

![image](https://user-images.githubusercontent.com/22686327/66511278-f5d83900-ead6-11e9-9358-ec3d1f5e0da1.png)

**Comment by dansiegel** [comment]
Thanks for opening the issue... we are aware the issue as it has broken the builds... this seems to be from a change in the tooling
