### ISSUE TITLE
[Bug] Prism.wpf.dll missing prism.bootstrapper.createModuleCatalog(); 

### ISSUE THREAD

**Issue by AmirAoT** [PrismLibrary/Prism#1928]
### Description
i have update prism v6.3 to v7... after updating when i build project and try to run it i got this error, then i clean build and again rebuild it but same error is there

### Steps to Reproduce

1. Updating prism v6.3 to v7
2. 
3. 

### Expected Behavior
prism v7 it should be work as it work before for v6.3

 
### Basic Information

- Version with issue: prism 7
- Last known good version: v6.3
- Xamarin.Forms version:
- IDE:

### Screenshots

![bootstrappererror](https://user-images.githubusercontent.com/38525216/66642621-64271380-ec1d-11e9-9d53-6bc8a990f10c.PNG)

**Comment by brianlagunas** [comment]
MEF is no longer supported.
