### ISSUE TITLE
[Bug] Navigation is not working from Rg.Plugin.Popups

### ISSUE THREAD

**Issue by jitendrajadav** [PrismLibrary/Prism#1929]
### Description
Earlier I have old version of Prism and it was working fine with Navigation from Popup(Rg.Plugin.Popups) Page now I am doing with updated version with prism it is not working navigation no error nothing is happen?

sample code : await _navigationService.NavigateAsync("AboutAppView", animated: false);

Doing Push...
10-11 17:36:25.487 I/mono-stdout( 4589): Doing Push...Doing default Prism Push with Xamarin.Forms

10-11 17:36:25.487 I/mono-stdout( 4589): Doing default Prism Push with Xamarin.Forms

### Expected Behavior
It should work and navigate to next page
### Actual Behavior
Nothing is happen no navigation only what I get from build log is here
10-11 17:36:25.487 I/mono-stdout( 4589): Doing Push...Doing default Prism Push with Xamarin.Forms

10-11 17:36:25.487 I/mono-stdout( 4589): Doing default Prism Push with Xamarin.Forms

Microsoft Visual Studio Professional 2019
Version 16.3.4
VisualStudio.16.Release/16.3.4+29409.12
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Professional

Visual C++ 2019   00435-60000-00000-AA694
Microsoft Visual C++ 2019

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASP.NET and Web Tools 2019   16.3.285.24939
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   16.3.285.24939
For additional information, visit https://www.asp.net/

Xamarin   16.3.0.277 (d16-3@c0fcab7)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.3.0.246 (remotes/origin/d16-3@bd2f86892)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.3.565 (27e9746)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   10.0.3.0 (d16-3/4d45b41)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: mono/mono/2019-06@5608fe0abb3
    Java.Interop: xamarin/java.interop/d16-3@5836f58
    LibZipSharp: grendello/LibZipSharp/d16-3@71f4a94
    LibZip: nih-at/libzip/rel-1-5-1@b95cf3fd
    ProGuard: xamarin/proguard/master@905836d
    SQLite: xamarin/sqlite/3.27.1@8212a2d
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-3@cb41333

Xamarin.iOS and Xamarin.Mac SDK   13.4.0.2 (e37549b)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by dansiegel** [comment]
This is the wrong repository to be reporting any issues regarding Rg.Plugins.Popup support. That said it sounds like you most likely forgot to register the Popup Navigation Service with the registration extension in Prism.Plugin.Popups

**Comment by jitendrajadav** [comment]
this is actual issue with Prism I have checked with old version it is working fine with Prism 7.1 but not working with 7.2

**Comment by brianlagunas** [comment]
Prism does not officially support any 3rd party software such as Rg.Plugins.Popups. You are more than welcome to fork the Prism repo and debug your issue to see if you can find the issue. You can even submit a PR with the fix as long a sit doesn't impact existing Prism behavior.

**Comment by jitendrajadav** [comment]
> Prism does not officially support any 3rd party software such as Rg.Plugins.Popups. You are more than welcome to fork the Prism repo and debug your issue to see if you can find the cause. You can even submit a PR with the fix as long as it doesn't impact existing Prism behavior.
> 
> Also, for future issue submissions, no issue will be looked at unless a repro app is provided.

Thank you @brianlagunas here I am attaching Repository for actual problem please have a look 
actually if you decrease one level all of 3 packages listed below it will work! 
![image](https://user-images.githubusercontent.com/1029026/66700999-7b94f800-ed14-11e9-8c51-5bf6fa484fa2.png)


Note : so the problem is prism last updated version

Repository [https://github.com/jitendrajadav/XamarinRealm.git](url)

**Comment by jitendrajadav** [comment]
let me know if you want new issue for that or you can manage

**Comment by dansiegel** [comment]
@jitendrajadav we won’t be looking into this as both @brianlagunas and I have both said Prism does not directly support Rg.Plugins.Popup. The support comes from Prism.Plugin.Popups.
