### ISSUE TITLE
Unity Version Related Issue 

### ISSUE THREAD

**Issue by bcopmt143** [PrismLibrary/Prism#193]
When I use Prism 6.0.1, and when I use Unity 4.0 ... it show me the following error even if I upgrade all dependencies 

	CS0012	The type 'IUnityContainer' is defined in an assembly that is not referenced. You must add a reference to assembly 'Microsoft.Practices.Unity, Version=3.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.

on UnityBootstrap

**Comment by bartlannoeye** [comment]
Duplicate #176

In short: the Unity team had to resign their assemblies with a new key, introducing a breaking change and thus upping the version to 4.0. As it doesn't bring any new functionality except for the new signing key, we're not pushing a new version of Prism right away. You should continue to use the previous version of Unity (which is the same as 4.0) until we do.
