### ISSUE TITLE
Wpf Applicatin Won't Run after installation But There is no Problem when runing in visual studio 2019 (debug/release)

### ISSUE THREAD

**Issue by PhantomParadox** [PrismLibrary/Prism#1933]
### Description
after installing WPF app [(Link to PR)](https://github.com/PhantomParadox/TestWpfApp) I get the following error 
----------
 Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Reference assemblies should not be loaded for execution.  They can only be loaded in the Reflection-only loader context. (Exception from HRESULT: 0x80131058)
_____________________________________________________
Exception occurred while:

 for parameter:  'regionBehaviorFactory'
 on constructor:  SelectorRegionAdapter(IRegionBehaviorFactory regionBehaviorFactory)
  ·resolving type:  'SelectorRegionAdapter'
----------------------

### Steps to Reproduce

1. add (prism blank app (WPF) ) to the solution (.net framework 4.7.2)
2. Select unity as the container
3. add a setup project (and Configure it) 
4. in the App.xaml.cs file override the onStartUp method and add a try\catch 
5. build the setup project and install it 

### Expected Behavior
well it should run and show the main window 
### Actual Behavior
throws mentioned above exception 
### Basic Information

- Version with issue: 7.2.0.1367
- Last known good version: -- 
- Xamarin.Forms version:--
- IDE: Visual Studio 2019

### Reproduction Link

[(Link to PR)](https://github.com/PhantomParadox/TestWpfApp) 

thank you in advance for any help with this issue

**Comment by brianlagunas** [comment]
I'm sorry, but this is not a Prism issue. When you build your app for an installer, it's up to you to ensure all your dependencies are packaged properly.

**Comment by PhantomParadox** [comment]
> 
> 
> I'm sorry, but this is not a Prism issue. When you build your app for an installer, it's up to you to ensure all your dependencies are packaged properly.

I am sorry if I am taking to much of your time But if it's possible for you to take a look at this Assembly Binder Log from Fusion++ that tells me that Prism.Wpf & Prism.Unity.Wpf & Prism are successfully Binding I put one of the logs here and be grateful if you take a look at it and if there is something that I am misunderstanding guide me in the right direction 

Thanks for considering my request.
[Log File](https://github.com/PrismLibrary/Prism/files/3730459/Prism.txt)
