### ISSUE TITLE
[Bug] IContainerRegistryExtensions Prism.dll and Prism.Wpf.dll have same namespace

### ISSUE THREAD

**Issue by Jonas-Marty** [PrismLibrary/Prism#1935]
### Description

I want to register my dialogs automatically without statically typing them every time I add a new one. So I use reflection to find all dialog views and the corresponding view models and register them to the container registry. Because there is only a generic overload of `IContainerRegistryExtensions.RegisterDialog<TView, TViewModle>()` available, I tried it using reflection with `MakeGenericMethod()` like this:

```csharp
foreach (var assembly in GetAllLoadedAssemblies()) {

    ...

    foreach (var dialogType in assembly.GetTypes().Where(x => x.Name.EndsWith("Dialog") && x.IsClass && typeof(UserControl).IsAssignableFrom(x)))
    {
        var dialogViewModelType = assembly.GetTypes().FirstOrDefault(t => t.Name == $"{dialogType.Name}ViewModel" && typeof(IDialogAware).IsAssignableFrom(t));
        typeof(IContainerRegistryExtensions).GetMethod(nameof(IContainerRegistryExtensions.RegisterDialog)).MakeGenericMethod(dialogType, dialogViewModelType)
        .Invoke(null, new[] { containerRegistry, null });
    }
}
```

The problem is that Prism.dll and Prism.Wpf.dll contain a class `IContainerRegistryExtensions` in the namespace `Prism.Ioc` and the compiler can't decide which one to use (see screenshot).

### Steps to Reproduce

1. Reference both Prism and Prism.Wpf
2. In code use: `typeof(IContainerRegistryExtensions)`

### Expected Behavior

These two `IContainerRegistryExtension` classes should be placed into different namespaces or either of them should be removed.

### Actual Behavior

```
CS0433 The type 'IContainerRegistryExtensions' exists in both 'Prism.Wpf, Version=7.2.0.1367, Culture=neutral, PublicKeyToken=40ee6c3a2184dc59' and 'Prism, Version=7.2.0.1367, Culture=neutral, PublicKeyToken=40ee6c3a2184dc59'
```

### Basic Information

- Version with issue: Prism 7.2 and Prism.Wpf 7.2 with Prism.DryIoc 7.2
- Last known good version: Don't know, switched ioc from MEF to DryIoc when changing to Prism 7.2 from 6.x
- Xamarin.Forms version: not using
- IDE: Visual Studio 2019 (16.3.2)

### Screenshots

![image](https://user-images.githubusercontent.com/10078507/67084666-aa402200-f19d-11e9-9636-b6bb1bbaf498.png)

### Reproduction Link

[PrismIssue.zip](https://github.com/PrismLibrary/Prism/files/3743657/PrismIssue.zip)

**Comment by brianlagunas** [comment]
This is by design, and was not structured to support what you are trying to do.  If you want to dynamically register your dialogs, then you'll have to create your own wrapper class/method that calls the Prism.Ioc extension methods.  Maybe something like:

```
    public static class MyDynamicIocExtension
    {
        public static void RegisterDynamicDialog<T, VM>(this IContainerRegistry registry) where VM : IDialogAware
        {
            registry.RegisterDialog<T, VM>();
        }
    }
```
