### ISSUE TITLE
[Enhancement] Allow interrupt, cancel or prevent navigation within a region scope.

### ISSUE THREAD

**Issue by Lukkian** [PrismLibrary/Prism#1937]
## Summary

Allow interrupt, cancel or prevent navigation within a region scope.

## API Changes

Consider this event:
https://github.com/PrismLibrary/Prism/blob/05972600e0baebbd4aa9733c809b3f2bcd39ec43/Source/Wpf/Prism.Wpf/Regions/RegionNavigationService.cs#L81

I expected it to be possible to prevent or cancel navigation in the event above, but I didn't find a reasonable way to do that. Well, I actually managed to interrupt the navigation by throwing an exception, but it seems very wrong, besides I had some unwanted side effects.

So I would like to propose adding a "CancelNavigation" property in the navigationContext passed in the line below:

https://github.com/PrismLibrary/Prism/blob/05972600e0baebbd4aa9733c809b3f2bcd39ec43/Source/Wpf/Prism.Wpf/Regions/RegionNavigationService.cs#L255

And after that line checks if "CancelNavigation" has been marked true and cancels or continues the navigation.

e.g.

    //Line 256 in RegionNavigationService.cs
    if(navigationContext.CancelNavigation) {
        //Call other events and / or perform necessary actions
    }

## Intended Use Case

The proposed idea would be very useful for controlling access to a given region, or rather to views of that region. For example, I could make a decision to restrict access to a particular view based on the claims or roles of a particular user. I know that there are other ways to achieve this, one of them is through the INavegationAware interface, but the proposed idea makes the process simpler and more practical.

Here is a complete example:

Somewhere you subscribe to the event:

    var region = _regionManager.Regions[RegionName.MainContentRegion];
    region.NavigationService.Navigating += NavigationServiceOnNavigating;

.

    private void NavigationServiceOnNavigating(object sender, RegionNavigationEventArgs e)
    {
        if (e.Uri.OriginalString == nameof(WelcomeView))
        {
            // WelcomeView does not need authorization checks 
            return;
        }

        var principal = _currentPrincipalHolder.GetCurrentPrincipal();

        if (principal.IsInRole(Role.Administrator))
        {
            // Administrators does not need authorization checks
            return;
        }
        
        var hasClaim = principal.HasClaim(CustomClaimTypes.AuthorizeView, e.Uri.OriginalString);

        if (hasClaim == false)
        {
            // ShowNotification is an extension method
            _dialogService.ShowNotification("Attention", "You are not allowed to access this!");
            
            e.NavigationContext.CancelNavigation = true;
            //or maybe: e.CancelNavigation = true;
        }
    }

At this point I expect the application to keep the current active view and present the dialog informing the user that he has no permission to access wherever he was trying to go.

**Comment by Lukkian** [comment]
As a complement, here is what I do today:

    private void NavigationServiceOnNavigating(object sender, RegionNavigationEventArgs e)
    {
        if (e.Uri.OriginalString == nameof(WelcomeView))
        {
            // WelcomeView does not need authorization checks 
            return;
        }

        var principal = _currentPrincipalHolder.GetCurrentPrincipal();

        if (principal.IsInRole(Role.Administrator))
        {
            // Administrators does not need authorization checks
            return;
        }
        
        var hasClaim = principal.HasClaim(CustomClaimTypes.AuthorizeView, e.Uri.OriginalString);

        if (hasClaim == false)
        {
            _dialogService.ShowNotification("Attention", "You are not allowed to access this!");
            
            throw new UnauthorizedNavigationException($"User: '{principal.Identity.Name}' | Target: '{e.Uri.OriginalString}'");
        }
    }

This works, but imagine the active view implements INavigationAware, it turns out that the OnNavigatedFrom method will be called even if navigation has been interrupted by throwing UnauthorizedNavigationException and this may not be as desired because you, I mean I, put some cleanup code there.

**Comment by brianlagunas** [comment]
This is not going to be added. This would not be the recommended way to handle "cancelling" navigation. Since navigation is synchronous, there is no concept of cancelling, but instead preventing. This means your logic need to be invoked before navigation ever occurs. There is already a mechanism for this in the IConfirmNavigation interface.

**Comment by brianlagunas** [comment]
I'd add that you should be able to add to the parameters collection when you throw an exception so that you can check that parameter in the OnNavigatedFrom to prevent any cleanup from occurring.

**Comment by Lukkian** [comment]
It would be almost perfect...
The problem is INavigationAware.OnNavigatedFrom runs before NavigationService.Navigating event.

https://github.com/PrismLibrary/Prism/blob/05972600e0baebbd4aa9733c809b3f2bcd39ec43/Source/Wpf/Prism.Wpf/Regions/RegionNavigationService.cs#L250-L255

**Comment by brianlagunas** [comment]
Well, can't change that. 😄

**Comment by Lukkian** [comment]
No problem, I'll try something else.
Cheers.
