### ISSUE TITLE
[Bug] Can't relative navigate from within a partial view

### ISSUE THREAD

**Issue by ScarlettCode** [PrismLibrary/Prism#1938]
### Description

If you have a partial view and you try use navigationService from within the partial view with a relative path the navigation never occurs. 

### Steps to Reproduce

1. Place a button within a partial view. 
2. On clicking the button try navigate to another view

### Expected Behavior

There are three expected behaviors I see.

- When you navigate from within a partial view, find the parent view and navigate as if the parent is doing the navigation. 

- When navigating from within a partial view (to another partial view) then the partial view gets swapped out. This is probably a dynamic partial view / regions discussion. It's not actually a use case I need but just wanted to mention it as it could be useful to keep in mind.

- Using https://github.com/dansiegel/Prism.Plugin.Popups have the ability to launch a popup from a partial view and then when closing the popup the parent is the highest on the stack so that the parent get's re on navigated to and not just the partial. This is what I was trying to achieve when I ran into the issue. My hope is that fixing point 1 will fix this too.

Extra Note.

Absolute navigation works however if you a few layers down and dealing with popups absolute navigation is a pain so ideally relative should work too.

### Actual Behavior

Nothing happens.

### Basic Information

- Version with issue: 7.2
- Xamarin.Forms version: 4.3.0.9
- IDE: VS 2019 (16.3.5)

### Reproduction Link

[PopupNavigationFromPartialView.zip](https://github.com/PrismLibrary/Prism/files/3762479/PopupNavigationFromPartialView.zip)

**Comment by dansiegel** [comment]
I'm not sure what your issue is as I can't find my Android phone, but I've tested and confirmed this works as expected
