### ISSUE TITLE
[Bug] MainPage is never set

### ISSUE THREAD

**Issue by Softtinn** [PrismLibrary/Prism#1939]
### Description

In our scenario we have to present the MasterDetailPage from a button click inside a ContentPage.
e're using the following code to get a reference to the MasterDetailPage:
```
 (Prism.PrismApplicationBase.Current.MainPage as MainMasterDetailPage).IsPresentedChanged += (sender, args) =>
            {
                (Prism.PrismApplicationBase.Current.MainPage as MasterDetailPage).IsPresented = !_isPresented;
            };
```

(We have also tried this: **App.Current.MainPage**)

### Steps to Reproduce

1. Install the latest version of Prism.DryIoC.Forms.
2. Register the MainPage and the NavigationPage inside the App.xaml.cs file.
3. Use the navigationService to set and navigate to the MainPage: `NavigationService.NavigateAsync("NavigationPage/MainPage");`

### Expected Behavior

Being able to reference the application current "MainPage" in order to toggle the presentation of our MasterDetailPage.

### Actual Behavior

The **MainPage** is always null

### Basic Information

- Version with issue: Xamarin.Forms.DryIoC v7.2.0.136
- Last known good version: N/A
- Xamarin.Forms version: 4.3.0.908675
- IDE: Visual Studio 2019 v16.3.5

### Screenshots

![image](https://user-images.githubusercontent.com/7129814/67510465-4c2ba700-f695-11e9-93b6-28a47b167e08.png)

**Comment by dansiegel** [comment]
- No Reproduction
- You are using a MasterDetailPage in the wrong order with a NavigationPage which tells me any potential bug is in your code and you're not looking at the Navigation Result to understand the error that is occurring (in your code) and why your MainPage is not being set...
