### ISSUE TITLE
[Enhancement] Use new C# 8.0 operator ??= for cmd-snippets

### ISSUE THREAD

**Issue by vortex852456** [PrismLibrary/Prism#1940]
## Summary

You could use the new C# 8.0 operator `??=` for your cmd-snippets.

## About the operator

![image](https://user-images.githubusercontent.com/4114781/67870995-f7be7680-fb2f-11e9-8004-2c9be9ec8528.png)
(Source: https://docs.microsoft.com/de-de/dotnet/csharp/whats-new/csharp-8#null-coalescing-assignment)

## About the cmd-snippet

Currently if you use the snippet you get following code:
```
private DelegateCommand _fieldName;
public DelegateCommand CommandName =>
    _fieldName ?? (_fieldName = new DelegateCommand(ExecuteCommandName));

void ExecuteCommandName()
{

}
```

With the new `??=` operator it could be simplified to this:
```
private DelegateCommand _fieldName;
public DelegateCommand CommandName => 
    _fieldName ??= new DelegateCommand(ExecuteCommandName);

void ExecuteCommandName()
{

}
```

**Comment by brianlagunas** [comment]
Thanks for the suggestion. Unfortunately, this is not something that will be changed at this time. Not everyone is using C# 8 and this would not be compatible with their existing code.
