### ISSUE TITLE
[Bug] Destroy of IDestructible does not fire when pressed back button

### ISSUE THREAD

**Issue by huyjack178** [PrismLibrary/Prism#1942]
After upgrade to Prism 7.2.x, Destroy() method is not being fired anymore when I pressed back button. Please check

**Comment by dansiegel** [comment]
@huyjack178 we have issue templates for a reason. This is not helpful. Most issues developers face are from their own code and this is typically discovered when you try to reproduce the issue which is part of the reason we require a sample reproducing any bug which you think you have found.
