### ISSUE TITLE
ErrorsContainer should raise error events on UI thread 

### ISSUE THREAD

**Issue by znakeeye** [PrismLibrary/Prism#1946]
See [ErrorsContainer.cs(143)](https://github.com/PrismLibrary/Prism/blob/master/Source/Prism/Mvvm/ErrorsContainer.cs#L143). Here you propagate the error to the parent viewmodel. The call should be dispatched to the UI thread or WPF will throw `InvalidOperationException`.

You could argue that the viewmodel should take care of this. But considering the fact that you have a dedicated class for error handling, it makes sense to let it do this itself. Some important notes below:

- The `ErrorsChanged` event will ultimately add an item to the `Validation.Errors` collection which is an `ObservableCollection`. Thus, WPF requires this event to be fired on the UI thread.
- The `PropertyChanged` event does not have this limitation. Hence, you get the expected behavior for your `SetProperty()` method. The same is not true for `SetErrors()`.

Do you see my point? As a developer I trust both `SetProperty()` and `SetErrors()` to work in all cases, but that's not the case.

**Comment by brianlagunas** [comment]
These base classes are merely helpers. They are not meant to solve all the possible use-cases you may use them in. Especially in a mutli-threading scenario.  You're on your own there. I am actually considering removing the ErrorsContainer class as I do not believe it should be something Prism even tries to handle.
