### ISSUE TITLE
[Enhancement] Allow IDialogAware to control WindowStyle property

### ISSUE THREAD

**Issue by SamirKharchi** [PrismLibrary/Prism#1949]
## Summary

Using IDialogAware is much more comfortable but the unstyled title bar of the dialog might be undesired as it most probably collides with the styled content visually. It would be correspondingly advantageous to be able to hide the title bar, i.e. WindowStyle property of the (WPF) window.

## API Changes

To make this work IDialogAware must be updated with a WindowStyle auto property

        WindowStyle WindowStyle { get; }

And accordingly the DialogWindow.xaml should be bound:

        WindowStyle="{Binding WindowStyle, FallbackValue=SingleBorderWindow}"

## Intended Use Case

When using it in conjunction with MaterialDesignInXaml for example, the title bar falls out of line instantly and breaks the look and feel. Especially when it comes to notifications, where moving the dialog is of no interest most of the time, it would help improving the applied style experience for the end-user if it was possible to hide the Title bar.

**Comment by brianlagunas** [comment]
Adding a Style property to a VM breaks the MVVM pattern and will not be something prism will do. However, setting the window style is already supported.  Just read the release notes: https://github.com/PrismLibrary/Prism/releases/tag/v7.2.0.1367
