### ISSUE TITLE
[Bug] 'B' page in 'B/C' navigation scenario isn't put in the navigation stack until its `InitializeAsync` method has completed

### ISSUE THREAD

**Issue by Pavel-Sulimau** [PrismLibrary/Prism#1950]
### Description

If you have 'A', 'B', 'C' view models with asynchronous initialization and navigate from 'A' to 'C' with 'B/C' approach, then you may end up having ambiguous backward navigation when the actual previous page depends on how much time the interim view models need for their initialization and how much time the user has spent on the last page before starting backward navigation.

### Steps to Reproduce

1. Get the app from the reproduction link and run it.

2. Press "Navigate to 'FirstPage/SecondPage'" to navigate from "MainPage" to "SecondPage" and then immediately press "Back button".
Please note that the user is navigated back to "Main Page".
<img src="https://user-images.githubusercontent.com/8143332/68890098-4cb4dc00-072f-11ea-8f28-d32d6e50548d.gif" width="300" height="600">

3. Press "Navigate to 'FirstPage/SecondPage'" again, wait for at least 4 seconds after "Second Page" is opened, press "Back button".
Please note that in this case the user is navigated back to "First Page".
<img src="https://user-images.githubusercontent.com/8143332/68886982-3ad03a80-0729-11ea-99e7-aec8cb3ad791.gif" width="300" height="600">

### Expected Behavior
Out team forked Prism v7.1 back in the day and implemented `OnNavigatingToAsync` method with the same semantic as `InitializeAsync` has now. We get around the described issue by introducing a navigation parameter which (when it's present) indicates that asynchronous initialization should be skipped for all but the target view model in 'A/B/C' navigation case. With this flag in place, we can be sure that backward navigation will always lead from 'C' to 'B' in the described circumstances.

### Basic Information

- Version with issue: 7.2.0.1367
- Xamarin.Forms version: 4.3.0.9912
- IDE: Visual Studio 16.3.9

### Reproduction Link
https://github.com/Pavel-Sulimau/Prism.Xamarin.AbsoluteUriNavigationIssue

**Comment by brianlagunas** [comment]
This is not a bug, but working exactly like you are coding it to work. Your code in InitializeAsync does not run on a separate thread, it is all part of the same thread so your delay is doing exactly what it is supposed to do. Any code you put in that method will pause navigation operations for that page until the result has been returned.
