### ISSUE TITLE
Prism.DryIoc.Forms: Undefined Method '"GetDefault"' when compiling with Link All

### ISSUE THREAD

**Issue by Pepsi1x1** [PrismLibrary/Prism#1954]
### Description

Undefined Method '"GetDefault"' in Type DryIoc.ReflectionTools (including non-public=True) at runtime when building Prism with Link All set

This method was removed from DryIoc in version 4.0.0

### Steps to Reproduce

1. Create a project with Prism.DryIoc.Forms
2. Set linker behavior to Link All
3. Run on an iOS device

### Expected Behaviour

App boots

### Actual Behaviour

App crashes at startup with the message Undefined Method '"GetDefault"' in Type DryIoc.ReflectionTools (including non-public=True)

### Basic Information

- Version with issue: 7.2.0.1442, 1367
- Last known good version: 7.1.0.431
- Xamarin.Forms version: 4.3.0.991211
- IDE: Visual Studio Mac 2019

**Comment by dansiegel** [comment]
This is not a Prism issue. You likely have some dependency that is messing this up for you or you need to update your linker config. You've also not provided a sample.

**Comment by Pepsi1x1** [comment]
Hi @dansiegel, this occurs in a fresh prism project when Xamarin.Forms is updated to 4.3.0.991211, I'm getting a repro ready for you

**Comment by Pepsi1x1** [comment]
@dansiegel see repro here

https://github.com/Pepsi1x1/PrismLinkAllBug

**Comment by Pepsi1x1** [comment]
Also breaks the Unity Container, with instead an InvalidOperationException

**Comment by brianlagunas** [comment]
This is not a bug in prism. This is an issue with how you are using the linker. You must fully understand what you are doing when you set the linker to LinkAll.  The Xamarin team themselves suggest using Link SDK Only and not Link All.  If you want to go down the path of Link All it becomes imperative that you understand its going to be on you to spend a lot of time looking up code on GitHub if you want a customized Linker Configuration.

**Comment by Pepsi1x1** [comment]
So the default behaviour when you build for App Store submission is Link All and expected, I discovered this issue submitting a binary to TestFlight when the app crashes on boot at the splash screen, fast forward and I've set this option on a Debug build to repro and work out what was the cause.

**Comment by dansiegel** [comment]
As @brianlagunas mentioned this is issue of having to understand exactly what you are and are not using when you use the Linker. I've had a number of discussions with the Xamarin team around this. Ultimately the Linker is a bit too magical in that you don't have any clue what on earth it's going to strip out. I know DryIoc pretty well and gave up after about 2 hours of Linker hell and made it my policy if I want to really use the Linker I exempt the DryIoc dll from linking and my problems went away... I would suggest you try the same.

This isn't actually an issue with Prism so there is nothing more that I can really do to help you from an out of the box perspective. If you use the Linker for Link All it's going to cause problems for you.
