### ISSUE TITLE
[Enhancement] Deactivate should call OnNavigatedFrom

### ISSUE THREAD

**Issue by gojanpaolo** [PrismLibrary/Prism#1957]
## Summary

Deactivating an active view should call its `INavigationAware.OnNavigatedFrom`.

## API Changes

There will be no API Changes.

## Intended Use Case

```c#
class ParentViewModel
{
    IRegionManager _regionManager;

    void DeactivateAllViews()
    {
        var region = _regionManager.Regions["MyRegion"];
        foreach (var view in region.ActiveViews)
           region.Deactivate(view); // this should call INavigationAware.OnNavigatedFrom
    }
}
```

We have a scenario where we just want to clear the region and not navigate to a new view. And we need to execute `OnNavigatedFrom` of the deactivated view.

Also tried `IRegion.RemoveAll` but it also doesn't not call `OnNavigatedFrom`

P.S.
Thank you for developing and maintaining this library. I'm sorry for creating a new issue if there is already a discussion regarding this, I tried to find one but was not successful.

**Comment by brianlagunas** [comment]
Activating and deactivating views is not part of the navigation framework.

**Comment by gojanpaolo** [comment]
Thanks for the immediate response Brian! I realized from your response that I could use `IActiveAware` (part of View activation framework) instead to execute the code when the view gets deactivated. Thank you!
