### ISSUE TITLE
[UWP] Validate dependent properties

### ISSUE THREAD

**Issue by bartlannoeye** [PrismLibrary/Prism#196]
While porting one of our existing Win8.1 apps with Prism for Windows Runtime to the latest version for UWP last night, I noticed we had our own implementation of ValidatableBindableBase to be able to trigger validation on dependent properties. While not used often, this is sometimes necessary. We added following overload to the base class:

    public void ValidateProperty(string propertyName)
    {
        if (_bindableValidator.IsValidationEnabled)
            _bindableValidator.ValidateProperty(propertyName);
    }

Which enabled us to do this:

    [CustomValidation(typeof(ModifierGroup), "ValidateMaxNumberChoices")]
    [CustomValidation(typeof(ModifierGroup), "ValidateMaximumNotSmallerThanMinimum")]
    public int MaxNumberChoices
    {      
        get { return _maxNumberChoices; }
        set
        {
            SetProperty(ref _maxNumberChoices, value );
            ValidateProperty("MinNumberChoices");
        }
    }

Now in C# 6 you would be able to use nameof().

Do we want to support this scenario in Prism for UWP? And is this simple overload 'good enough' or do we want another approach (like data annotations)?

**Comment by briannoyes** [comment]
Yeah, I think we should add this. I had something like this and a few other enhancements planned but haven't had the time to integrate them. Not sure what you mean about another approach like data annotations - ValidateProperty on BindableValidator does evaluate DataAnnotations.

**Comment by bartlannoeye** [comment]
Maybe something like a [AlsoValidate(...)] attribute, but to be honest I think the simple method overload is more than enough. I'll make some time to add it later today.

**Comment by bartlannoeye** [comment]
Looking into this, I see that all other Validate methods return a boolean, so maybe this one should as well?

        public bool ValidateProperty(string propertyName)
        {
            return !_bindableValidator.IsValidationEnabled // don't fail if validation is disabled
                || _bindableValidator.ValidateProperty(propertyName);
        }
