### ISSUE TITLE
mscorlib issue since version 7.2

### ISSUE THREAD

**Issue by kenw2121** [PrismLibrary/Prism#1961]
Having the following exception when running on Android emulator using Prism.DryIoc.Forms 7.2.0.1422 and 7.2.0.1367. Works fine on 7.1.0.431.

System.TypeLoadException: Could not resolve type with token 01000069 from typeref (expected class 'System.Collections.Generic.Queue`1' in assembly 'mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e')

I'm using Visual Studio 2017. I think was because Queue has been moved from System.dll to mscorlib.dll (https://github.com/mono/mono/pull/11511)

**Comment by dansiegel** [comment]
I really can't answer this, but it is apparent that this is not an issue with Prism. There are lots of apps running Prism 7.2.0.1367 & 7.2.0.1422 just fine. I might suggest you try using Visual Studio 2019.

**Comment by kenw2121** [comment]
Thanks for your quick response.  I guess if I need to use the newer version of Prism, I have to go with Visual Studio 2019.
