### ISSUE TITLE
Prism incorrectly depends on System.ValueTuple

### ISSUE THREAD

**Issue by znakeeye** [PrismLibrary/Prism#1964]
Targeting .NET Framework **4.7.2**. Saw an unwanted dependency on `ValueTuple` so I tried uninstalling it.

> Unable to uninstall 'System.ValueTuple.4.5.0' because 'Prism.Core.7.2.0.1422' depends on it.

**Comment by dansiegel** [comment]
Your not wanting something does not mean Prism is doing anything incorrectly. Prism.Core relies on System.ValueTuple for certain API's including the IContainerProvider which allows Prism to do what it needs.

**Comment by dansiegel** [comment]
The CI feed should address your issue. After some additional discussions we've decided to go ahead and add an explicit net47 target which does not require the System.ValueTuple reference
