### ISSUE TITLE
Remove Obsolete classes

### ISSUE THREAD

**Issue by brianlagunas** [PrismLibrary/Prism#1968]
## Summary

As we rev for v8, we need to remove all classes markd obsolete.

**Comment by sylvesp** [comment]
Maybe you want to add:
… except the different bootstrapper classes that are marked obsolete.

**Comment by brianlagunas** [comment]
We are discussing plans for bootstrapper.  We may align the API with the PrismApplication class and then remove the obsolete attribute.

**Comment by brianlagunas** [comment]
initial removals have been completed.
