### ISSUE TITLE
Prism for Xamarin conflict with Unity 4.0.0

### ISSUE THREAD

**Issue by tangkhaiphuong** [PrismLibrary/Prism#197]
error CS0012: The type ‘IUnityContainer’ is defined in an assembly that is not referenced. You must add a reference to assembly ‘Microsoft.Practices.Unity, Version=3.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35’.

Reference issue: https://compositewpf.codeplex.com/discussions/443219

**Comment by bartlannoeye** [comment]
Duplicate #193 #176 

Unity added a breaking change by changing the signing key.

Please continue to use the previous version of Unity until we push a new release referencing Unity 4.0.
An alternative is to compile and use the latest source code, as the dependency on Unity is upgraded to v4.0 in PR #194.

**Comment by brianlagunas** [comment]
This has been fixed with the latest preview of Prism for Xamarin.Forms.
