### ISSUE TITLE
[Bug] declaring PrismApplication in xaml break the application property tab

### ISSUE THREAD

**Issue by GianlucaLocri** [PrismLibrary/Prism#1973]
### Description
Using PrismApplication class in Application.xaml (and relative code behind) breaks the project application tab reporting the error [...]
Could not find the expected root element "Application" in the application definition file.

Tested on **VS2019** community edition, **prism/unity v7.2.0.1422**, **VB.net**

### Steps to Reproduce

1. Make a simple vb.net WPF project with the prism packets installed as should be
2. Edit Application.xaml like
<prism:PrismApplication x:Class="App"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:prism="http://prismlibrary.com/"
    >
    <Application.Resources>
    </Application.Resources>
</prism:PrismApplication>
3. Edit code behind like
`Class App
    Inherits PrismApplication

    Protected Overrides Sub RegisterTypes(containerRegistry As IContainerRegistry)
        containerRegistry.Register(GetType(ApplicationService))
    End Sub

    Protected Overrides Function CreateShell() As Window
        Return Container.Resolve(Of Views.MainWindowView)
    End Function
End Class`
4. Right click on the project node -> properties -> Application Tab

### Expected Behavior
The application information and settings such as Assembly name, Root namespace, target framework should be displayed

### Actual Behavior
An error is reported on the application tab:

> An error occurred trying to load the application definition file for this project.  The file '[path name]\Application.xaml' could not be parsed.  Please edit the file in the XAML editor to fix the error.
Could not find the expected root element "Application" in the application definition file.

I've omitted the [path name] part as not important for the explanation

### Basic Information

- Version with issue:  prism-unity v7.2.0.1422
- Last known good version: unknown
- IDE: VS2019 / vb.net

### Reproduction Link
sample zipped project available here:
https://github.com/GianlucaLocri/WpfAppTest191217

**Comment by brianlagunas** [comment]
This is not a bug in Prism. This is a bug in Visual Studio. This can easily be proven by creating your own base application class and deriving from that instead.  You should report this to MS.
