### ISSUE TITLE
[Enhancement] Boilerplate code

### ISSUE THREAD

**Issue by stesvis** [PrismLibrary/Prism#1975]
## Summary

When declaring properties, would it be possible to eliminate a bunch of boilerplate code with the use of annotations, like the other MVVM framework **ReactiveUI** does here?
https://reactiveui.net/docs/handbook/view-models/boilerplate-code

## API Changes

e.g.

Before:
```
        private string _firstName;

        public string FirstName
        {
            get { return _firstName; }
            set { SetProperty(ref _firstName, value); }
        }
```

After:
```
        [Prism] public string FirstName { get; set; }
```

## Intended Use Case

General use case, i find a lot of repeated code that could be reduced.
Please forgive me if a feature like this already exists, in that case how to use it?

**Comment by dansiegel** [comment]
Already is possible... just use PropertyChanged.Fody... the reason we don't have to ship a specific package like ReactiveUI is we aren't doing something that requires a custom implementation... PropertyChanged.Fody already works OOB with Prism.
