### ISSUE TITLE
[Bug] [UWP] In MasterDetail if DetailPage is NavigationPage TabbedPage the NavigationBar/Menu DISAPPEAR

### ISSUE THREAD

**Issue by mzhukovs** [PrismLibrary/Prism#1977]
### Description

I have an app wherein there is a MasterDetail page, and one of the Detail Pages is a Tabbed Page (wrapped in a Navigation Page). On iOS and Android, when I navigate to this Tabbed page, the NavigationBar and the Master hamburger menu are visible and accessible as expected. However, only on UWP, when I navigate to this TabbedPage, the NavigationBar and Master Menu disappear, and user is stuck there no longer able to access that menu to navigate to other pages. This only happens when using Prism, not with vanilla Xamarin Forms. See working XF repro here: https://github.com/xamarin/Xamarin.Forms/issues/7341
[NavBarTabbedPagePrismUWPissue.zip](https://github.com/PrismLibrary/Prism/files/3987875/NavBarTabbedPagePrismUWPissue.zip)

### Steps to Reproduce

1. Create a MasterDetail Page and add to it a normal NavigationPage as well as a TabbedPage NavigationPage
2. Navigate to the TabbedPage when running on UWP
3. Observe the NavigationBar and Master Menu icon disappear

### Expected Behavior

NavigationBar and Master Menu hamburger icon in UWP are still visible when viewing the TabbedPage as a Detail page.

### Actual Behavior

NavigationBar and Master Menu hamburger icon in UWP disappear when viewing the TabbedPage as a Detail page.

### Basic Information

- Version with issue: latest Prism (7.2.0.1422) and latest Xamarin.Forms (4.4.0.991265)
- Last known good version: unsure
- IDE: VS2019 Enterprise latest
- Platform Target Frameworks: 
  - iOS:  works on all
  - Android: works on all
  - UWP:  does NOT work on 1809 nor 1903

- Nuget Packages: Xamarin.Forms and Prism
- Affected Devices: UWP desktop

###  Repro:
[NavBarTabbedPagePrismUWPissue.zip](https://github.com/PrismLibrary/Prism/files/3987876/NavBarTabbedPagePrismUWPissue.zip)

**Comment by brianlagunas** [comment]
This is not a Prism issue. Prism does nothing special when it comes to navigation. Prism relies solely on the XF navigation APIs.  The unique thing Prism does is build up the navigation stack before it is added to the applications navigation stack. There is already one bug related to that process that has not been fixed by the XF team (https://github.com/xamarin/Xamarin.Forms/issues/2562).

**Comment by brianlagunas** [comment]
Also, your sample is too complicated for us to use as a reproduction app. In the future, please create a new blank Prism app and reproduce the issue using only the required code. This helps you weed out any issues that may exist in your code base, and makes it easier for us to debug your app as well. We do not have the time to try and learn a new code base and dissect how various extension methods are being used to understand how the code is supposed to work before even getting to the issue.  Just something to keep in mind in the future.
