### ISSUE TITLE
[Bug] System.ExecutionEngineException: Attempting to JIT compile method '(wrapper managed-to-native) YourClass/YourDelegate:wrapper_aot_native(object,intptr,intptr)' while running in aot-only mode.

### ISSUE THREAD

**Issue by mfranc28** [PrismLibrary/Prism#1979]
### Steps to Reproduce

1.  On App.xaml.cs
public partial class App : PrismApplication
    {
        public App(IPlatformInitializer initializer = null) : base(initializer) { }
2. On AppDelegate iOS
public class iOSInitializer : IPlatformInitializer
    {

        public void RegisterTypes(IContainerRegistry containerRegistry)
        {

        }
    }
3.  Start in debug mode your App

### Expected Behavior
App run normally
### Actual Behavior
App don't Run and debug is stopped with message error :"Attempting to JIT compile method 'void YourApp.App:RegisterTypes (Prism.Ioc.IContainerRegistry)' while running in aot-only mode. See https://docs.microsoft.com/xamarin/ios/internals/limitations for more information.

### Basic Information

- Version with issue:7.2.0.1422
- Last known good version:
- Xamarin.Forms version:4.2.0.709249
- IDE: VS MAC Last version

**Comment by dansiegel** [comment]
While I'd love to help you here, you've opened an issue which I have never had an issue with previously and you've provided no reproduction as is required for all bug reports making it impossible for me to assist you.
