### ISSUE TITLE
Convert Prism 5 docs into Markdown

### ISSUE THREAD

**Issue by brianlagunas** [PrismLibrary/Prism#198]
We need to convert the current Prism 5 doc that are available as .docx files into Markdown so that we can host the docs on GitHub.

Here is the location of the current docs:  http://compositewpf.codeplex.com/releases/view/614456

Here is the docs hosted on MSDN:  https://msdn.microsoft.com/en-us/library/gg406140.aspx

**Comment by bartlannoeye** [comment]
Don't forget to keep the breaking changes in mind while going through the conversion.

**Comment by brianlagunas** [comment]
Phase one will be to convert.  Then we can go through and edit :)

**Comment by brianlagunas** [comment]
Okay, WPF docs have been converted to MD.  Next phase, fix all the formatting, insert the images, and update the content one file at a time.
