### ISSUE TITLE
merge dialog view and normal view some same function

### ISSUE THREAD

**Issue by lirenzhi** [PrismLibrary/Prism#1980]
## Summary

merge dialog view and normal view some same function,like INavigationAware(IDialogAware) ,NavigationParameters(DialogParameters)

## API Changes

INavigationAware (IDialogAware) ,
NavigationParameters(DialogParameters)

e.g.

we frequently use  a view in  normal way ,and also use  in a dialog.that we need create two view and viewmodel inherited diffrent interface. merge them and use property or method to indentify them

**Comment by dansiegel** [comment]
This is not something that we're going to do. Dialogs are not meant to be drop in replacements for a View you might normally Navigate to. They are different by design to keep you from confusing the two.

**Comment by brianlagunas** [comment]
I'll add, the same view can implement both interfaces to achieve your goals.
