### ISSUE TITLE
[Enhancement] Dialog support for plugin environment

### ISSUE THREAD

**Issue by sylvesp** [PrismLibrary/Prism#1982]
## Summary

A plugin module built with Prism - running inside a host application - will crash when trying to show a dialog using IDialogService.Show().

This happens because in such a scenario the Application object of the hosting environment is Null Invoking IDialogService.Show() in such an environment causes a System.NullReferenceException: 'Object reference not set to an instance of an object.'

The actual cause of the exception is that DialogService.ConfigureDialogWindowProperties() is trying to access the null Application object.

if (window.Owner == null)
     window.Owner = Application.Current.Windows.OfType<Window>().FirstOrDefault(x => x.IsActive);

Suggestion:
In a "plugin environment" usually it is possible to get at least an IntPtr with the handle of the Main Window of the host application.
It would be nice to have the possibility to inject this into the DialogService() and have the dialog service set the owner of the dialog based on this IntPtr.

## API Changes

Add a new interface, that will be implemented and registered with the IoC container by the plugin Prism application.

public interface IWindowOwnerProvider
{
      IntPtr? Owner { get; }
}

Inject this interface into the DialogService constructor OR use the IoC container to resolve it.
 _windowOwnerProvider  => assign it from constructor injection or Container.Resolve<IWindowOwnerProvider>();

Update DialogService.ConfigureDialogWindowProperties() to use this provider.

void ConfigureDialogWindowProperties(IDialogWindow window, FrameworkElement dialogContent, IDialogAware viewModel)
{
….
if (window.Owner == null)
{
    if (_windowOwnerProvider.Owner != null)
    {
        var windowInterop = new WindowInteropHelper(window as Window);
        windowInterop.Owner = _windowOwnerProvider.Owner.Value;
    }
    else if (Application != null) // try other way
    {
        window.Owner = Application.Current.Windows.OfType<Window>().FirstOrDefault(x => x.IsActive);
    }
    else
      throw new NullReferenceException("blah blah");
}
….
}

## Intended Use Case

A solution like this will allow to use Prism for plugin applications that do not have access to the host Application class.

The current workaround would be to use containerRegistry.RegisterDialogWindow<> and register your own dialog window that does something similar.

Maybe somebody has a better idea?

**Comment by sylvesp** [comment]
Well... another solution could be for the IDialogService.ShowDialog() to have another, optional IntPtr parameter to pass in the Owner.

The conversion from IntPtr to Window is not through the WindowInteropHelper I've suggested earlier but:

    var hwndOwner = HwndSource.FromHwnd(...IntPtr of the Owner window Hwnd...);
    this.Owner = hwndOwner?.RootVisual as Window;

**Comment by brianlagunas** [comment]
I have submitted PR #1992 to make the methods virtual. This will allow you to modify the implementation to provide your own IntPrt logic.
