### ISSUE TITLE
[Enhancement] Best Practices - Async / Await

### ISSUE THREAD

**Issue by GioviQ** [PrismLibrary/Prism#1984]
Looking at 
https://www.youtube.com/watch?v=-LY4ATA8Bgw 
and https://johnthiriet.com/mvvm-going-async-with-async-command/

I found very useful tips especially preventing concurrent execution of a command.

Is it possibile to have this enhancement?

**Comment by brianlagunas** [comment]
This has already been discussed in other threads. Prism has no plans to add an async command.  There are already a number of Async Command implementations available freely on GitHub and NuGet. @dansiegel has actually already created an async command you can use as well in his Prism.Forms.Extended package on NuGet.
