### ISSUE TITLE
[Bug] Gesture inside collectionview or LIstview not working

### ISSUE THREAD

**Issue by viveknegi51288** [PrismLibrary/Prism#1985]
### Description

I Have created a collectionview and Listiview on differnt pages for testing.
Each Collectionview and listview has same design that includes 1 label , 1 image inside frame.

I want to perform some action if user click on image so i have added gesture on image but its not calling the function. I want to perform some action whenever user click on label or image. 

### Steps to Reproduce

1. Create a listview or collectionview in xamarin forms
2. Set Itemsource from viewmodel using prims to listview or collectionview
3. Add 1 label and 1 image on listview cell or collectionview data template
4. Add gestrure to lable and image as command={Binding someCommand}
5. Initiate someCommand  in viewmodel and call method ABC() for label and XYZ() from Image.
6. Debug the application.
7. You will find method is not calling from any one of them.

### Expected Behavior
Should call respective method while clicking on image or label.
### Actual Behavior
None method called while click on image or label.
### Basic Information

- Version with issue:7.2.0.1422
- Last known good version:
- Xamarin.Forms version:4.4.0.991265
- IDE:

**Comment by bartlannoeye** [comment]
Hey @viveknegi51288 

Have you tried without Prism and verified the bug is in Prism? Also we need a reproduction project (either zip or link to source code we can clone/build.

**Comment by viveknegi51288** [comment]
[Example.zip](https://github.com/PrismLibrary/Prism/files/4007986/Example.zip)

I was facing problem using Prism but after your comment I have tried without prism and same issue has been found. If you can help why gesture inside listiview and collectionview is not working it would be a great help @bartlannoeye

**Comment by dansiegel** [comment]
this is not an issue in with Prism but rather Xamarin.Forms. It looks like you've already opened the issue there as well, which is where the issue needs to be.
