### ISSUE TITLE
[Bug] Android: Master Detail Hamburger Menu button breaks after opening camera/gallery

### ISSUE THREAD

**Issue by ledragon101** [PrismLibrary/Prism#1994]
### Steps to Reproduce

1. Navigate to Master/Detail Detail Page with buttons to open Media Plugin Camera/Gallery
2. Open Camera or Gallery
3. Close Camera/Gallery or take a picture

### Expected Behavior
Android (not iOS) Hamburger menu should open slide out MasterDetail Menu
### Actual Behavior
Button is disabled. No menu appears although menu can still be reached via swipe from left
### Basic Information
So the situation is in my app the Hamburger Menu button doesn't work after opening the camera. I produced a simplfied repo which shows the Hamburger Menu to be working fine after opening Camera/Gallery so of course the problem is specific to my app...but I'm not sure what steps to take to diagnose. 

I can't provide my app of course but would appreciate any guidance on how to figure out the cause...even just a nudge in the right direction as I'm at a bit of a loss ATM!

Thanks in advance.

- Version with issue: 7.1
- Last known good version: n/a
- Xamarin.Forms version: 4.3
- IDE:Visual Studio 2019

### Screenshots

[MasterDetailCamera.zip](https://github.com/PrismLibrary/Prism/files/4040859/MasterDetailCamera.zip)

**Comment by dansiegel** [comment]
@ledragon101 we can't begin to look at this issue if your sample doesn't reproduce the issue.

**Comment by ledragon101** [comment]
@dansiegel Hi there, yes I understand that...I was just hoping for a suggestion on how I could investigate the cause...I don't even know where to begin to add the various functionalities in my app that may have caused it into the sample....there are so many!

If there's anything that you could suggest to help me dig in a little it would be gratefully received

**Comment by ledragon101** [comment]
[MasterDetailCamera.zip](https://github.com/PrismLibrary/Prism/files/4099715/MasterDetailCamera.zip)

Figured the reason!

Added the following into MainActivity.cs in Droid Project and it causes the issue. See attached sample solution.

protected override void OnResume()
        {
            Android.Support.V7.Widget.Toolbar toolbar = this.FindViewById<Android.Support.V7.Widget.Toolbar>(Resource.Id.toolbar);
            SetSupportActionBar(toolbar);

            base.OnResume();
        }
