### ISSUE TITLE
[Bug] [UWP] Template Disappears when Command Parameter Binding Set

### ISSUE THREAD

**Issue by djrpascu** [PrismLibrary/Prism#1995]
### Description
I have a Listview with simple DataTemplate selector which presents one of either two templates. Once the CommandParameter Binding is defined to the current object ({Binding} or {Binding .}), the entire view for that template goes blank on UWP. Therefore, I'm not allowed to call the command with the current object. This works as expected when deploying out to iOS.

Note: I originally submitted this issue in the XF Github [#8918](https://github.com/xamarin/Xamarin.Forms/issues/8918). @Pureween discovered that it works as expected when using Xamarin.Forms.Command. So, perhaps issue is specific to Prism DelegateCommand?

### Steps to Reproduce

Sample project here https://github.com/djrpascu/XFGithub

### Expected Behavior
Listview template displays contents properly and I'm able to pass the object into my command via CommandParameter.
### Actual Behavior
Listview template goes blank.
### Basic Information

- Version with issue: 4.4.0.991265
- Last known good version: N/A
- IDE: VS Enterprise 2019 16.4.1
- Platform Target Frameworks: 
  - iOS:  13
  - Android: N/A 
  - UWP: 16299  
- Android Support Library Version: N/A 
- Nuget Packages: 
XF 4.4.0.991265
Prims.Unity.Forms 7.2.0.1422
NETStandard.Library 2.0.3

- Affected Devices:
Windows 10 Desktop

### Reproduction Link
https://github.com/djrpascu/XFGithub

**Comment by dansiegel** [comment]
The InvalidCastException is by design. You are getting the wrong value into the CommandParameter. As I mentioned on your original issue this has to be a bug in Xamarin.Forms.
