### ISSUE TITLE
ObservesCanExecute throws System.ArgumentNullException

### ISSUE THREAD

**Issue by lebtho1878** [PrismLibrary/Prism#1997]
Since upgraded to newest version 7.2.0.1422

the following line of code produces a System.argumentNullException with the detail information, that value has to be not null for parameter name propertyInfo.

new DelegateCommand<object>(EditRouteNamePressed).ObservesCanExecute(() => CanDoEditRouteName);

**Comment by brianlagunas** [comment]
Closing as you did not provide a reproduction app.
