### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by lebtho1878** [PrismLibrary/Prism#1998]
Since upgraded to newest version 7.2.0.1422

the following line of code produces a System.argumentNullException with the detail information, that value has to be not null for parameter name propertyInfo.

new DelegateCommand(EditRouteNamePressed).ObservesCanExecute(() => CanDoEditRouteName);

If you change the version in the sample project to 7.1.0.431 everything works fine
[PRISM_TEST.zip](https://github.com/PrismLibrary/Prism/files/4058877/PRISM_TEST.zip)

**Comment by brianlagunas** [comment]
This i snot a bug. ObservesCanExecute only works with properties, not variables.  Also, I don't know what you are trying to do, but you have more problems than just that in this app.  Please do not take this approach in your real app. You are asking for trouble.
