### ISSUE TITLE
[Bug] XAML Hot reload stops working when using PrismApplication

### ISSUE THREAD

**Issue by SneWs** [PrismLibrary/Prism#2002]
### Description
When creating a new Xamarin Forms application and using PrismApplication, XAML hot reload stops working. 

### Steps to Reproduce

1. Create a new Xamarin Forms application
2. Switch from using Application to using PrismApplication and wire up your App.xaml.cs in accordance to Prism docs.
3. Register your start page
4. Start the application in the Android emulator, make sure that it navigates properly to the page you set as start page
5. Change styles on a Label for example in VS, press save, see the Output window, it will tell you that hot reloading failed or succeeded, at random
6. The page you where looking at in the emulator now reloads, and the change it not updated, OR the page stops rendering completely.

### Expected Behavior
Hot reloading should work just as it does when not using PrismApplication

### Actual Behavior
Hot reload does not work

### Basic Information

- Version with issue: Prism 7.2.0
- Last known good version: None
- Xamarin.Forms version: 4.4.0
- IDE: VS 2019

### Output messages
[HotReload] (2020-01-20 22:20:30.4): INFO: Reloaded: 'ReloadChange in App.xaml', ignoring 1 unsupported edits:
[HotReload] (2020-01-20 22:20:30.4): INFO: 	 In App.xaml:

**Comment by dansiegel** [comment]
This wouldn't really be a Prism issue... That said @SneWs can you please provide a sample app where you are experiencing the issue and provide more details on what build of VS 2019 that you're using. @maddyleger1 @pierceboggan do you have any insight on this?

**Comment by SneWs** [comment]
Ofc, Will assemble a minimum required repro. As a side note, this seems to only be a problem when I poke at stuff hosted in App.xaml, not if I change or poke at stuff in a ContentPage. 

Will get the sample repro done in a few hours.

**Comment by SneWs** [comment]
OK, here you can find a minimal repro https://github.com/SneWs/PrismMvvmBug/tree/master 

In the App.xaml I've left a comment inside the Style element named BigText. If you change the text on that style Hot reload will error out and render the view without any styles at all. 

**My exact VS version:**
Microsoft Visual Studio Professional 2019
Version 16.4.2

Let me know if I can provide anything else that might help here.

**Comment by maddyleger1** [comment]
@SneWs thanks for filing!! Can you also file this under Help > Send Feedback > Report a Problem in the IDE? We have an idea of what could be happening but if you file through the VS system it makes it easier to share logs etc. confidentially!

**Comment by dansiegel** [comment]
now that the team is involved I'm going to close this issue. Thanks @maddyleger1

**Comment by drasticactions** [comment]
@SneWs Currently, when we reload changes in root `App.xaml`, we send the new XAML over to the device, and have Xamarin.Forms run it's `XamlLoader.LoadResources` on it. While it's getting the new XAML, and the root `Application`, it's failing to load the resources, which then causes _all_ resources to be unloaded. 

It's hard to diagnose exactly where the failure is happening (It's failing inside of Xamarin.Forms, based on a call made by Hot Reload, while a third party library is being used as the base application). So we're going to diagnose it further on our side. 

As a workaround, you should be able to load your Application Resources inside a ResourceDictionary (in a seperate file), and reference that in the `app.xaml`.

**Comment by SneWs** [comment]
> @SneWs thanks for filing!! Can you also file this under Help > Send Feedback > Report a Problem in the IDE? We have an idea of what could be happening but if you file through the VS system it makes it easier to share logs etc. confidentially!

Sure I can do that.

**Comment by drasticactions** [comment]
@SneWs @dansiegel 

I've got good news and bad news

- Good news: This is 100% not a Prism bug. I can replicate these conditions in my own program by using an inherited Xamarin.Forms `Application` type. 
- Bad news: It's an issue in Xamarin.Forms and its [`XamlLoader.LoadResources`](https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Xaml/XamlLoader.cs#L175-L180
)

The TL;DR is that using an inherited base class for the `app.xaml` results in the node properties being `Application.Resources`, rather than `Resources`, which is what it's expecting. We're going to talk to the Forms team about the next steps for this. For now, using the ResourceDictionary in a separate file will get around that issue.

**Comment by SneWs** [comment]
> 
> 
> @SneWs @dansiegel
> 
> I've got good news and bad news
> 
>     * Good news: This is 100% not a Prism bug. I can replicate these conditions in my own program by using an inherited Xamarin.Forms `Application` type.
> 
>     * Bad news: It's an issue in Xamarin.Forms and its [`XamlLoader.LoadResources`](https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Xaml/XamlLoader.cs#L175-L180)
> 
> 
> The TL;DR is that using an inherited base class for the `app.xaml` results in the node properties being `Application.Resources`, rather than `Resources`, which is what it's expecting. We're going to talk to the Forms team about the next steps for this. For now, using the ResourceDictionary in a separate file will get around that issue.

@drasticactions I'd say that it's good news all around, issue identified and reproducible, thus easier to understand and fix. 

Good job! And thanks for the swift responses.
