### ISSUE TITLE
Stuck on page after absolute navigation

### ISSUE THREAD

**Issue by JsCalahan** [PrismLibrary/Prism#2003]
### Description
On Android, when doing absolute navigation, if the app is moved to the background or the phone's screen is turned off, the app will continue executing, but gets stuck on the original page.

### Steps to Reproduce

1. Begin absolute navigation
2. Leave the app (hit home button on phone or lock phone to turn off screen)
3. Return to the page you were navigating from

### Expected Behavior
The app should navigate to the target page.
### Actual Behavior
The app gets stuck on the original page; the navigation stack and all bindings are cleared. 
### Basic Information

- Version with issue: 7.2.0.1422
- Last known good version: N/A
- Xamarin.Forms version: 4.4.0.991477
- IDE: Visual Studio 2019

### Reproduction Link

https://github.com/JsCalahan/AbsoluteNavRepro

**Comment by dansiegel** [comment]
This is not an issue with Prism. Place a breakpoint on your Navigation in OnInitialized...
