### ISSUE TITLE
[Bug] Cancelling "add project" wizard deleted EVERYTHING in the solution folder

### ISSUE THREAD

**Issue by LoghamLogan** [PrismLibrary/Prism#2004]
### Description

Using "Prism Template Pack".
Cancelling the add new project wizard early (via 'x' button) caused the wizard to become non-responsive, it then proceeded to delete my *entire* solutions folder. This even included all of the files (that were not in use) in the hidden /.vs and /.git folders.
I killed the window, and have no idea if it would have carried on up the folder hierarchy...
This **really** f'd up my day.

### Steps to Reproduce

Reproduce this at your own risk. I'm not trying it again...
1. "Add a new project".
2. Selected "Prism Blank App (Xamarin.Forms)"
3. Choose Dryioc
4. Clicked next (pretty sure)
5. Clicked back (pretty sure)
4. Click the 'x' in the top right.
5. The plugins window crashes (not responding) 
6. Starts deleting everything in the solution... this included hidden /.vs and /.git folders.
7. Cry.

### Expected Behaviour
DON'T delete the entire solution.

### Actual Behaviour
DOES delete the entire solution.

### Basic Information

- Version with issue: 2.1.7
- Last known good version: n/a
- Xamarin.Forms version: 4.4
- IDE: Visual Studio 2019

### Screenshots

n/a

### Reproduction Link

n/a

**Comment by brianlagunas** [comment]
Thanks for letting me know. This is has been fixed. You can get it in a few minutes via v2.1.8
