### ISSUE TITLE
DelegateCommandBase should have a second constructor

### ISSUE THREAD

**Issue by znakeeye** [PrismLibrary/Prism#2005]
In a huge project with lots of DelegateCommands we realized that many of our crashes and hangs come from this [line of code](https://github.com/PrismLibrary/Prism/blob/master/Source/Prism/Commands/DelegateCommandBase.cs#L25) in `DelegateCommandBase`:

```c#
 protected DelegateCommandBase()
 {
     _synchronizationContext = SynchronizationContext.Current;
 }
```

It took us 3,5 years to identify this well hidden threading issue. Yes, some of our DelegaetCommands are created on non-UI threads. Boom!

I read all about this change, and I understand that you believe this is correct. I call it a bug, since WPF will call `CanExecute` and expect it to run on the UI thread.

Anyway, I suggest that you add another constructor, allowing you to circumvent this **locked-in behavior**.

**The fix**

```c#
protected DelegateCommandBase(synchronizationContext synchronizationContext)
{
     _synchronizationContext = synchronizationContext;
}

protected DelegateCommandBase()
 : this(SynchronizationContext.Current)
{
}
```

Also, `DelegateCommand` should only call the first constructor. You can specify `SynchronizationContext.Current` if you'd like, avoiding breaking existing code. Even though I would prefer the developer to explicitly set this parameter.

That way, we can patch this without using reflection or re-writing `DelegateCommand` from scratch.

**Comment by brianlagunas** [comment]
How would you expect the public API to be changed to allow setting this syncContext in the very rare case that it needs to be manually set?  Would using a property be an option as well?

**Comment by znakeeye** [comment]
A property would be fine.
