### ISSUE TITLE
[Bug][NRE] Using TabbedPage with ItemSource and late population of source

### ISSUE THREAD

**Issue by dersia** [PrismLibrary/Prism#2006]
### Description

When Navigating to a TabbedPage which is using a binding on ItemSource and the ItemSource is fetched delayed (loading from IO) then CurrentPage of TabbedPage is null.

NavigationService is throwing a NRE, because CurrentPage is null. From Forms perspective that state is fine, and Tabs are populated, once the ObservableCollection is filled.

I created a sample Repo to show it of.

### Steps to Reproduce

1. Create Xamarin.Forms App
2. Add TabbedPage
3. Set ItemSource and ItemTemplate of TabbedPage
4. Set Items to empty ObservableCollection() in VM.cotr
5. Implement INavigationAware on VM
6. Override OnNavigatedTo as async method
7. Make call to IO in OnNavigatedTo
8. Populate Items with actual Items
9. Navigate to TabbedPage

### Expected Behavior

Navigate to TabbedPage with no Tabs

### Actual Behavior

NRE

### Basic Information

- Version with issue: 7.2.0.1422
- Last known good version: -
- Xamarin.Forms version: 4.5.0.187-pre2
- IDE: VS2019 16.5 P2

### Reproduction Link

1. git clone https://github.com/dersia/TabbedPageBindingPrismException.git

**Comment by dersia** [comment]
Fix is easy though:
https://github.com/PrismLibrary/Prism/blob/74b5ef614d98027d3f86e85aba2129b161d81d74/Source/Xamarin/Prism.Forms/Navigation/PageNavigationService.cs#L750

```csharp
else if (tabbedPage.CurrentPage != null && tabbedPage.BindingContext != tabbedPage.CurrentPage.BindingContext) 
```

**Comment by dansiegel** [comment]
@dersia Is there a reason you can't use IInitializeAsync? tried your sample on my live stream this morning and if you put a loading page before your start page with the async LoadData in InitializeAsync it all works just fine.
