### ISSUE TITLE
[Enhancement] Close dialog from the caller

### ISSUE THREAD

**Issue by Haukinger** [PrismLibrary/Prism#2007]
## Summary

Currently, there's no direct way for code that opened a dialog through `IDialogService` to close it (see [this question at stackoverflow](https://stackoverflow.com/questions/58291547/prism-closing-a-dialog-created-with-idialogservice) for example). `IDialogService.Show` could return an `IDisposable` (like `PubSubEvent.Subscribe` returning the `SubscriptionToken`) that's used to close the dialog from the outside.

## API Changes

`IDialogService` becomes

    public interface IDialogService
    {
        IDisposable Show(string name, IDialogParameters parameters, Action<IDialogResult> callback);

        IDisposable Show(string name, IDialogParameters parameters, Action<IDialogResult> callback, string windowName);

        void ShowDialog(string name, IDialogParameters parameters, Action<IDialogResult> callback);

        void ShowDialog(string name, IDialogParameters parameters, Action<IDialogResult> callback, string windowName);
    }

Disposing the returned object should close the dialog, similar to clicking the x-button or calling `Close`.

## Intended Use Case

Currently, if you have code that needs to open and close a dialog, e.g. a task that shows a progress dialog, it needs to be split into a portion that prepares and opens the dialog, and another portion _inside_ the dialog that does the work and closes the dialog when it's done. If the dialog supported closing it from the _outside_, that code can be kept together.

**Comment by Pretasoc** [comment]
The `ShowDialog` methods shouldn't change. Since they are blocking, the caller could close the dialog only after it already has been closed.

**Comment by Haukinger** [comment]
True, I've adapted the proposal.

**Comment by dansiegel** [comment]
@Haukinger I'm familiar with the StackOverflow issue where this was brought up. I'll say it again. Not gonna happen. It's very easy to write your own extension to do what they were looking to do. That said I am willing to provide some examples of how you could do this when I get a chance.

**Comment by Haukinger** [comment]
@dansiegel I'm sorry to say this, but I fear my memory fails me. Can you give me a hint about the "say it again" part? Doesn't the `DialogService` have to manage the dialogs and isn't he thus the go-to for closing a dialog (for those that aren't the to-be-closed dialog, of course)?

I'm interested in your approach to closing a dialog "from the outside".
