### ISSUE TITLE
[Bug] GoBack ToRoot fails when a Page is pushed as a Modal

### ISSUE THREAD

**Issue by luismts** [PrismLibrary/Prism#2008]
### Description
When trying to navigate back to the root of a NavigationPage from a modal page fails with the  error message "GoBackExtension threw an exception".

### Steps to Reproduce

1. From an existing navigation stack say NavigationPage/ViewA, modally push a new modal Page like:
`await this.NavigationService.NavigateAsync(ViewB, useModalNavigation: true);`
2. Now from ViewB.xaml call `Command="{prism:GoBack ToRoot}"`. The NavigationResult will contain an exception from line 200 in the PageNavigationService:
> [0:] Warning: GoBackExtension threw an exception
> [0:] Exception: System.InvalidOperationException: Sequence contains no elements at System.Linq.Enumerable.Last[TSource] (System.Collections.Generic.IEnumerable`1[T] source) 
> [0x0000b] in /Users/builder/jenkins/workspace/archive-mono/2019-08/android/release/external/corefx/src/System.Linq/src/System/Linq/Last.cs:16 
>  at Prism.Navigation.PageNavigationService.GoBackToRootInternal (Prism.Navigation.INavigationParameters parameters) [0x00121] in d:\a\1\s\Source\Xamarin\Prism.Forms\Navigation\PageNavigationService.cs:200 

### Expected Behavior
The navigation succeeds and returns you to the Root Page behind your Modal.

### Actual Behavior
The navigation fails

### Basic Information

- Version with issue: 7.2
- Last known good version: n/a
- Xamarin.Forms version: 4.4
- IDE: VS 16.4.2

### Screenshots
n/a

### Reproduction Link
n/a

**Comment by brianlagunas** [comment]
First, you didn't provide a sample to reproduce the issue. Second, GoBackToRoot only works when you are in the context of a NavigationPage. It is the same as calling XF's PopToRootAsync method. So it is working exactly how it should. In this case, you would just cal a normal GoBack and force it to be modal.
