### ISSUE TITLE
.NET Core project templates

### ISSUE THREAD

**Issue by seesharprun** [PrismLibrary/Prism#2009]
I was looking for a **template.json** file to indicate that you have .NET Core project templates that can be spun-up using ``dotnet new``.

If you don't have any, can I contribute? It would be great for me to say ``dotnet new wpfprism`` and spin up a .NET Core 3.1 WPF application with a basic Prism setup similar to the Visual Studio project templates.

Please close if they are located somwhere else and I missed them. In the past, I used templates from here <https://github.com/dansiegel/Prism-Templates/>.

**Comment by seesharprun** [comment]
https://github.com/seesharprun/Prism-Templates-Wpf-NetCore

Here's an example of how I would implement two templates:
- The first template (ran using ``dotnet new wpfprism``) creates a very basic WPF application that has a bootstrapped Shell view and a single Home view
- The second template (ran using ``dotnet new wpfprismfull``) creates a WPF application that implements a simple service, multiple regions in the Shell, a DelegateCommand, and the EventAggregator

**Comment by dansiegel** [comment]
the templates are back on GitHub, currently in a private repository. We will look to open this up in the near future.

**Comment by dansiegel** [comment]
Templates are now public. Be sure to open any future issues on the Templates in the [Templates Repo](https://github.com/PrismLibrary/Prism.Templates)

![PrismTemplates](https://user-images.githubusercontent.com/3860573/79388371-0e138f80-7f22-11ea-9356-ff762b3fa7ed.gif)
