### ISSUE TITLE
Fix documentation formatting

### ISSUE THREAD

**Issue by brianlagunas** [PrismLibrary/Prism#201]
Now that the Prism 5 docs have been converted form .docx to markdown, we have to painstakingly update each file individually to fix the formatting, insert the images, and update the content for each file.

Here is the location of the original docs and images:

http://compositewpf.codeplex.com/releases/view/614456

Use MSDN as a guide when updating the formatting and images as content may have been lost during the conversion.  Please compare and make sure the content is the same.

https://msdn.microsoft.com/en-us/library/gg406140.aspx

Please, pick a file and fix it.

Use Livewire to edit the markup locally.  This app gives an awesome client side editing experience with real time preview.

https://github.com/Infragistics/livewire

**Comment by Mykezero** [comment]
I'll be working on formatting [chapter 4](https://github.com/PrismLibrary/Prism/blob/master/Documentation/WPF/30-ModularApplicationDevelopment.md) next.

**Comment by bartlannoeye** [comment]
Started on [navigation](https://github.com/PrismLibrary/Prism/blob/master/Documentation/WPF/60-Navigation.md) in my lunch break.

**Comment by brianlagunas** [comment]
I'm starting Modular Application Development now.

**Comment by tomzorz** [comment]
Working on https://github.com/PrismLibrary/Prism/blob/master/Documentation/WPF/AppendixC-PrismLibrary.md and https://github.com/PrismLibrary/Prism/blob/master/Documentation/WPF/AppendixE1-ExtendingPrism.md

**Comment by overrorflow** [comment]
I'm started [70-CommunicatingBetweenLooselyCoupledComponents.md
] (https://github.com/PrismLibrary/Prism/blob/master/Documentation/WPF/70-CommunicatingBetweenLooselyCoupledComponents.md)

**Comment by bartlannoeye** [comment]
I think only the [HOL page](AppendixI-PrismWPFClickOnceDeploymentHOL.md) is left to do, the [What's new page](WhatsNewInPrism.md) should be either removed or completed with Prism 6 changelog.

**Comment by brianlagunas** [comment]
Awesome. Let remove the what's new page.  I'm about to board a flight to Germany, so I'll check in when I land in 10 hours :)

**Comment by brianlagunas** [comment]
Looks like we completed the WPF doc conversion.  Thank you everyone for your efforts.
