### ISSUE TITLE
[Enhancement] Observe INotifyCollectionChanged

### ISSUE THREAD

**Issue by paulovila** [PrismLibrary/Prism#2010]
## Summary
When using the ```ObservesProperty``` method, it only listens to property changes. But if the property implements ```INotifyCollectionChanged```, there should be  a way to listen to those changes to evaluate the command can execute.

## API Changes
Add a method like ```ObservesCollectionProperty``` in delegate command :
```csharp
addCommand.ObservesCollectionProperty(() => Collection1)
```
## Intended Use Case
when adding or removing items in a collection the ```CanExecute``` of a command can evaluated again
```csharp
new DelegateCommand(doSomething, () => Collection1.Count() <12)
.ObservesCollectionProperty(() => Collection1)
```

**Comment by brianlagunas** [comment]
Thank you for you suggestion, but this is not something I want to add to Prism. It is easier to hook into your collection changed event and call the `DelegateCommand.RaieCanExeciteChanged()` method.

**Comment by paulovila** [comment]
Just wanted to comment that it is easier to use that method in the DelegateCommand because the life cycle of the DC is related to that notification. It's more tidy to avoid the clutter of adding and removing an event handler, the same way we don't do it with OnPropertyChanged.
