### ISSUE TITLE
[Bug] Incompatibility with FireBaseCloudMessaging (prism.Unity)

### ISSUE THREAD

**Issue by JerTrud** [PrismLibrary/Prism#2011]
### Description
I started a new app and I wanted to send push notification to my user , I search for service to do it easily and found two solutions, azure notification hub and app center push

AppCenter push was easy to set up and work good with prism, but appCenter are retiring so they redirect you to azure notification center, 

But when I start Following the guide thy provide (https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/azure-services/azure-notification-hub#configure-android-manifest) i got an error. The nugget NETStandart.Libraryv2.0 is in conflict if you want to use Xamarin.Firebase.Messaging. 

So i tried looking for another solution, Pushy was the only none FireBase push notification service, so i tried implanting it , but the same error occurred. The NETStandart.Library is in conflict. 

### Steps to Reproduce

1. start a app with prism
2. try install Xamarin.Firebase.Messaging. 
3. you should see the error

### Expected Behavior
install
### Actual Behavior
error
### Basic Information

- Version with issue: lastest prism.unity 7.2.0.1422
- Last known good version:don't know
- Xamarin.Forms version: 4.4.0.991640+471-sha.c1bdf538e-azdo.3443599
- IDE: visual studio

### Reproduction Link
![image](https://user-images.githubusercontent.com/39913355/74370849-d19ea880-4da5-11ea-8c57-b94da5d20715.png)

**Comment by brianlagunas** [comment]
Closing as the required repro app was not provided
