### ISSUE TITLE
[Bug] Xamarin Forms Prism DialogService show behind ModalNavigation

### ISSUE THREAD

**Issue by qzwzqty** [PrismLibrary/Prism#2012]
### Description
I am using a custom DialogService, the problem I have is that I first show a page as a modal and when sending to display the DialogPage it is apparently not shown but it really is behind the model page

### Steps to Reproduce

1. create a new Page and custom DialogPage
2. navigate to Page use modal navigation
3. open DialogPage, and back to mainPage you should see the DialogPage

### Basic Information

- Version with issue:7.2.0.1422
- Last known good version:
- Xamarin.Forms version:
- IDE:vs2019

**Comment by brianlagunas** [comment]
Closing as the required repro app was not provided
