### ISSUE TITLE
Prism Template Pack - Visual Studio 2019 Mac

### ISSUE THREAD

**Issue by juliangm996** [PrismLibrary/Prism#2013]
### Description

With the update to Visual Studio 2019 for Mac, our Prism Template Pack won't appear in the list of extensions anymore however, it does work as normal on Visual Studio 2019 on Windows..

Steps to Reproduce

Screenshots

### Steps to Reproduce

Visual Studio -> Extensions -> Gallery
Version with issue: Visual Studio 2019 Mac
Last known good version: Visual Studio 2017 Mac
Xamarin.Forms version: 3.6.0.293080

### Basic Information

- Version with issue:
- Last known good version:
- Xamarin.Forms version:
- IDE:

### Screenshots

![Captura de Pantalla 2020-02-17 a la(s) 12 49 59 a  m](https://user-images.githubusercontent.com/48926745/74627314-77dd0c00-5120-11ea-91f3-5c483fccdaab.png)

**Comment by dansiegel** [comment]
The template pack is currently not available for Visual Studio for Mac. This is something I am looking at re-releasing but will only be available to my GitHub Sponsors. 

Duplicate #1755
