### ISSUE TITLE
[Bug] Prism.Wpf.DryIoc not signed/strong named

### ISSUE THREAD

**Issue by walli545** [PrismLibrary/Prism#2014]
### Description

Prism.Wpf.DryIoc.dll is not signed/strong named when downloaded from [https://www.nuget.org/packages/Prism.DryIoc/](https://www.nuget.org/packages/Prism.DryIoc/). This leads to an error when trying to build a signed assembly.

### Steps to Reproduce

1. Include Prism.Wpf into a signed project
2. Build

### Expected Behavior

.dll files on nuget should be signed

### Actual Behavior

.dll is not signed which leads to a build error:

> Error	CS8002	Referenced assembly 'Prism.DryIoc.Wpf, Version=7.2.0.1422, Culture=neutral, PublicKeyToken=null' does not have a strong name.

**Comment by dansiegel** [comment]
Thank you for the report. This is correct. When DryIoc was first added DryIoc did not have a strong name. This should be resolved in v4 to the best of my knowledge.

**Comment by dansiegel** [comment]
@walli545 this is fixed and will be available in the CI feed from build 1533.
