### ISSUE TITLE
UWP App with ShareTarget throws exception when closing the share window

### ISSUE THREAD

**Issue by sibille** [PrismLibrary/Prism#2016]
### Description

We're facing a problem with a UWP app with Prism 6.3 that is configured as share target.
The app opens correctly and shows the shared content, but when closing the window an exception is thrown:

The application called an interface that was marshalled for a different thread. (Exception from HRESULT: 0x8001010E (RPC_E_WRONG_THREAD))

I've attached a basic repro project that allows to receive an url shared for example by Edge. 

Are we missing something?

The original issue was reported in Windows Template Studio (https://github.com/microsoft/WindowsTemplateStudio/issues/3431)

### Steps to Reproduce

1. Configure the project to debug but not start
2. Go to Edge and share an url with the app
3. See the shared content
4. Close the app

### Expected Behavior
Should close without exception.

### Actual Behavior
Exception is thrown.
### Basic Information

- Version with issue: Prism.Unity 6.3

### Reproduction Link

[PrismShareTargetApp.zip](https://github.com/PrismLibrary/Prism/files/4224552/PrismShareTargetApp.zip)

**Comment by brianlagunas** [comment]
Prism no longer supports UWP. I would recommend removing it fro Windows Template Studio.
