### ISSUE TITLE
[Bug] Issue fixed in #928 has been introduced again in latest prism

### ISSUE THREAD

**Issue by srinims** [PrismLibrary/Prism#2019]
### Description

Issue fixed in #928 has been introduced again in latest prism

### Steps to Reproduce

1. Add a space in any of the parent directory
2. Run the application
3. It will crash

### Basic Information

- Version with issue: 7.2.0.1422
- Last known good version:
- Xamarin.Forms version:
- IDE:

**Comment by dansiegel** [comment]
No reproduction provided

**Comment by srinims** [comment]
Steps are in #928 & #926

**Comment by brianlagunas** [comment]
This code hasn't changed since this fix was introduced. Also the links you provided do not have a repro app.

**Comment by srinims** [comment]
Apologies, my bad. We have overridden the function "IEnumerable<IModuleInfo> Sort(IEnumerable<IModuleInfo> modules);"  from ModuleCatalogBase. Where the modules.Ref are still having the path string without Escape character, which is causing the issue in our application. We have fixed the issue locally. However it is ideal to have all overriddable functions exposed to have the correct path with escape characters.
