### ISSUE TITLE
[Bug] Open Dialog from item in CollectionView throws System.NotSupportedException

### ISSUE THREAD

**Issue by Softtinn** [PrismLibrary/Prism#2020]
### Description

We've created an image carousel by using a horizontal CollectionView. The images are shown as thumbnails, but if you click on them we show the image in a fullscreen mode, using a prism dialog.

However, when we click on it now, we get the following error thrown:
System.NotSupportedException: 'Unable to activate instance of type Xamarin.Forms.Platform.Android.ScrollViewRenderer from native handle 0x7fe6097324 (key_handle 0x8d911d2).'

If we bind the Show Dialog Command from another button, not included in the CollectionView, it's working fine (we just select the first best option).

Code snippet:
```
...
<CollectionView.ItemTemplate>
                                <DataTemplate>
                                        <Image
                                            WidthRequest="160"
                                            Aspect="AspectFill"
                                            Source="{Binding Image.Source}">
                                            <Image.GestureRecognizers>
                                                <TapGestureRecognizer
                                                    NumberOfTapsRequired="2"
                                                    Command="{Binding BindingContext.EnlargeImageCommand,  Source={x:Reference ParentView}}" 
                                                    CommandParameter="{Binding .}" />
                                            </Image.GestureRecognizers>
                                        </Image>

...
```
**ParentView** = x:Name of the current ContentPage.

### Steps to Reproduce

1. Create a Page containing a CollectionView. 
2. Each item in the CollectionView is clickable.
3. When an item is clicked, the command should trigger a prism dialog to be shown

### Expected Behavior

Display a prism dialog by clicking on an item inside a CollectionView.

### Actual Behavior

When the item is clicked, the following error is thrown:
System.NotSupportedException: 'Unable to activate instance of type Xamarin.Forms.Platform.Android.ScrollViewRenderer from native handle 0x7fe6097324 (key_handle 0x8d911d2).'

No dialog is shown.

### Basic Information

- Version with issue: Prism.DryIoc.Forms V. 7.2.0.1422
- Xamarin.Forms version: 4.4.0.991640
- IDE: Visual Studio 2019 Pro V. 16.4.3

**Comment by brianlagunas** [comment]
No reproduction app provided
