### ISSUE TITLE
[Bug] Xamarin.Forms iOS - Master/Detail - no detail content rendered on iPad in landscape mode 

### ISSUE THREAD

**Issue by jan-rucka** [PrismLibrary/Prism#2021]
### Description

Xamarin.Forms iOS application does not render content of detail in Master/Detail page on iPad in lanscape orientation. I have to rotate the iPad to portait and back to lanscape to see the content.

### Steps to Reproduce

1. Start the app on iPad/Simulator in landscape orientation
2. Tap on navigation link on left side
3. No detail content rendered
4. Rotate the iPad to portrait and back
5. Detail content is rendered

### Reproduction Link
[LandscapeOnIos](https://github.com/jan-rucka/LandscapeOnIos)

**Comment by brianlagunas** [comment]
Prism does not control what is, or what is not, rendered in XF. It only creates pages and adds them to the navigation stack. Rendering rotated content is not an area that Prism is involved in.
