### ISSUE TITLE
[Bug] IDestructible not working with back button

### ISSUE THREAD

**Issue by StefanStsc** [PrismLibrary/Prism#2023]
### Description

IDestructible not called when pressing back button in the last page.

### Steps to Reproduce

1. Implement an empty page and view model. The page should implement IDestructible interface
2. Set a breakpoint in the Destroy method
3. Launch debugger and press the back button

### Expected Behavior

Destroy is called

### Actual Behavior

Destroy is not called

### Basic Information

- Version with issue: 7.2.0.1422
- Last known good version: unknown
- Xamarin.Forms version: 4.4.0.991265
- IDE: VS 2019 16.4.1

**Comment by brianlagunas** [comment]
No reproduction app provided

**Comment by StefanStsc** [comment]
@brianlagunas this is already the third time that a report regarding this issue is just closed.
It seems that no one here cares about this problem, so I also don't mind to send a pull request for its fix.

**Comment by brianlagunas** [comment]
@StefanStsc it seems more like people submitting issues don't want to follow directions and provide the required sample app that reproduces the issue. While we love PR's, the problem must be verified first, and a sample app is required for that process to occur.
