### ISSUE TITLE
Use NameOf instead of strings in navigation

### ISSUE THREAD

**Issue by BillyMartin1964** [PrismLibrary/Prism#2024]
Can you use NameOf() instead of strings for navigation and registering navigation? I just spent 2 hours chasing down a misspelled string! Thanks.

**Comment by bartlannoeye** [comment]
Best practice is to keep the strings in a constants file and use those constants both for registering navigation and the actual navigation. So even if you have typos, since you're using the same constant, everything will work. However, nothing keeps you from using nameof to fill these constants.

    internal static class NavigationUrls
    {
        public static string FormsNavigation = nameof(NavigationPage);
        public static string Main = nameof(MainPage);
        public static string Settings = $"{nameof(SettingsNavigationPage)}/{nameof(SettingsPage)}";
        public static string Walkthrough = nameof(WalkthroughPage);
        public static string AccountCreated = nameof(AccountCreatedPage);
        public static string ForgotPassword = nameof(ForgotPasswordPage);
    }

**Comment by dansiegel** [comment]
@BillyMartin1964 please do not open issues for a question. If you have a question they belong on StackOverflow
