### ISSUE TITLE
[Enhancement] ResolveAll the instances of a registered type in the IContainerProvider

### ISSUE THREAD

**Issue by krafty** [PrismLibrary/Prism#2032]
## Summary

IContainerProvider is a great way to abstract the actual container implementation from the consumers. This allows us to swap a container in future without changing the code much. The IContainerProvider does not have the ResolveAll method. As of now the consumer will need to get hold of the Container to use this method.

## API Changes

IContainerProvider should have following method:
`public System.Collections.Generic.IEnumerable<T> ResolveAll<T>();`

and can be consumed like below:
`var allPlugins = myContainerProvider.ResolveAll<ICustomPlugin>();`

## Intended Use Case

In the IUnityContainer class there is a method like:
`var myModules = Container.ResolveAll<ICustomModule>();`

This is quite useful in scenarios where there is a need to deal with multiple implementations of the same type. 

Lets say, if there is a need to support plugins (addins) in an application. The plugin can be developed after the application has been built and deployed on Target PC. Now the application loads all the instances of the type plugin and shows a way to invoke the plugin in the application dyanamically - there is no need to recompile the application. For this to work, there has to be a method which can resolve all types in IContainerProvider.

**Comment by brianlagunas** [comment]
The IContainerExtension interfaces are purposely kept as simple as possible to help support the majority of container being used by developers. With every new method we add, we impose another restriction on the container being used. Therefore we stick to the minimum required methods for Prism to function. That is why we expose the actual container so you are not limited to the API surface that containers provide. At this time we will not be adding this additional method.  You can however create your own extension method to accomplish this.

**Comment by dansiegel** [comment]
I should add here, if you're looking for a lot more flexibility with Prism's Container abstractions you can incorporate the [Prism.Container.Extensions](/dansiegel/Prism.Container.Extensions). The specific extension you're looking for however, would be on you, as Prism defaults to replacing registrations so I'm not sure that you would get all instances but rather only the last one.

**Comment by krafty** [comment]
Thanks @brianlagunas and @dansiegel. I was of the opinion that it was a basic method to resolveall instances. However, if all containers do not support it, your decision seems to be fine.

Cheers.
