### ISSUE TITLE
Prism 7.2: DeepLink Navigation into subPages of TabbarItem (Xamarin.Forms)

### ISSUE THREAD

**Issue by MaxFmi** [PrismLibrary/Prism#2033]
I try to DeepLink into a subPage of one TabbarItem. See the following navigation call:
_navigationService.NavigateAsync($"/NavigationPage/TabbedPage?{KnownNavigationParameters.SelectedTab}=Tab2ContentPage/ViewA_Page/ViewB_Page");

### Steps to Reproduce

1. Start yout App
2. Navigate by an absolute path -> /NavigationPage/TabbedPage/Tab1/ViewA_Page/ViewB_Page

### Expected Behavior
ViewB_Page should be show as content of Tab1

### Actual Behavior
ViewB_Page is shown without TabbedPage

### Basic Information

- Version with issue: 7.2.0.1422
- Last known good version: - 
- Xamarin.Forms version: 4.4.0.991640
- IDE: Visual Studio for Mac 8.4.4

### Reproduction Link
- Start the app from the repository https://github.com/MaxFmi/IssuePrismDeepLinkIntoTabbedPage/
- Click the button "DeepLink ViewModel Navigation to ViewB"
- You should see ViewB_Page inside a TabbedPage. But instead we see a plane ViewB_Page without Tabs.

**Comment by brianlagunas** [comment]
This is not a bug. This is not a supported feature. You will need to handle this nesting yourself.

**Comment by MaxFmi** [comment]
Is it possible to implement this handling using Prism? Do you have a suggestion?

**Comment by MaxFmi** [comment]
> This is not a bug. **This is not a supported feature.** You will need to handle this nesting yourself.

Do you mean I should have created a feature request?

**Comment by brianlagunas** [comment]
You may submit a feature request. However, it may be awhile before Dan or myself has time to look into it.  This would be a very complex feature to implement, and we make no guarantees it will be implemented.

**Comment by brianlagunas** [comment]
You can try passing your nested pages as a parameter to your tabbed page, then handle the INavAware/IPageLifecycle, or other page events to process the nesting.

**Comment by MaxFmi** [comment]
It seems that I'm missing something. When I'm on a TabbedPage and navigate using a relative path , I'm already navigating inside a tab.

For example (scenario from https://github.com/MaxFmi/IssuePrismDeepLinkIntoTabbedPage/): 
1) We're on the page /NavigationPage/TabbedPage // TabX selected
2) And navigate using `_navigationService.NavigateAsync("ViewA_Page");`
  - Press the button under Tab 1 -> "Relative ViewModel Navigation to ViewA"
3) The result is /NavigationPage/TabbedPage?selectedTab=TabX/ViewA_Page // ViewA_Page is under TabX and shows the TabbedPage.
4) Switching the to TabY shows the content of TabY.
  - If we press the BackButton here, the app will be closed.
5) Switching back to TabX shows /NavigationPage/TabbedPage?selectedTab=TabX/ViewA_Page
6) Press BackButton -> /NavigationPage/TabbedPage?selectedTab=TabX

My suggestion is to have this behavior of relative navigation from step 2 in the absolute navigation of 
`_navigationService.NavigateAsync($"/NavigationPage/TabbedPage?{KnownNavigationParameters.SelectedTab}=Tab2ContentPage/ViewA_Page/ViewB_Page");`

**Comment by brianlagunas** [comment]
It only seems like a simple task because Prism does such a good job of making navigation easy for you. You are more than welcome to jump into the source code and implement this feature in a PR. We would greatly appreciate it.
