### ISSUE TITLE
[Bug] WPF.DialogService Release 4.2.0.1422 missing ShowDialog function

### ISSUE THREAD

**Issue by utech626** [PrismLibrary/Prism#2034]
### Description

Version 4.3.0.1422, latest version on nuget is missing the DialogService
public void ShowDialog(string name, IDialogParameters parameters, Action<IDialogResult> callback, string windowName)
and 
public void Show(string name, IDialogParameters parameters, Action<IDialogResult> callback, string windowName)

Methods.

### Steps to Reproduce

1. Create function to show custom dialog and try to add ShowDialog function with 4 paramenters

### Basic Information

- Version with issue: 4.3.0.1422
- Last known good version: Guthub source shows function
- WPF
- IDE: Visual Studio

It would also help to have an example of Register a Custom Dialog Window

**Comment by brianlagunas** [comment]
You're on a VERY old version of Prism. The latest version is 7.2.

**Comment by utech626** [comment]
Sorry Typo, version is 7.2.0.1422
![prismwpf](https://user-images.githubusercontent.com/11544372/76181120-14c61e80-618e-11ea-8a76-ef5c19bcab63.png)
