### ISSUE TITLE
[Bug] LoadModules raise exception in Xamarin.Forms

### ISSUE THREAD

**Issue by urodolf** [PrismLibrary/Prism#2037]
### Description

To avoid having a function in the main application that registers all modules, we have made each module add to the catalog the list of modules it uses. This in WPF worked correctly, but in Xamarin.Forms an exception occurs because the list used by a foreach is modified. Reviewing the differences in the ModuleManager between the versions of WPF and XF we have found that the LoadModulesWhenAvailable function of the ModuleManager in WPF makes a ToList of the module list of the ModuleCatalog while the Xamarin.Forms does not make this ToList and uses a iterator returned by LinQ that produces the exception when a module is added to the catalog during the load proces.

### Steps to Reproduce

1. Create a IModule that do AddModule to ModuleCatalog.

### Basic Information

- Version with issue: 7.2.0.1422
- Xamarin.Forms version: 4.3.0.991250
- IDE: Visual Studio 16.4.4

**Comment by dansiegel** [comment]
A sample reproducing the issue is required for all bug reports
