### ISSUE TITLE
[UWP] PrismUnityApplication.OnInitializeAsync not sealed

### ISSUE THREAD

**Issue by bartlannoeye** [PrismLibrary/Prism#204]
@briannoyes I noticed in the [PrismUnityApplication](https://github.com/PrismLibrary/Prism/blob/master/Source/Windows10/Prism.Unity.Windows/PrismUnityApplication.cs#L63-L66) that the comment says OnIntializeAsync override should be sealed, but the code doesn't reflect this. Since this is the piece of code where everything is set up, I think it should be sealed indeed. Could you confirm?

**Comment by briannoyes** [comment]
Yup, makes sense to me. Make it so. :)
