### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by tmay57** [PrismLibrary/Prism#2040]
### Description
Navigation broken when NavigateAsync() called from a class referenced in a ViewModel. 
The sample provided is a simple 3 page application.
MainPage -> PrismContentPage1 -> PrismContentPage2

Each page is instrumented to navigate using:
XAML markup  -- works
MainPage navigates to PrismContentPage1 with absolute
    Command="{prism:NavigateTo /NavigationPage/PrismContentPage1}"
PrismContentPage1 navigates to PrismContentPage2 with relative
    Command="{prism:NavigateTo PrismContentPage2}"

ViewModel Command -- works
  -- just put DelegateCommands in the ViewModels

MyNav Command -- partially works
 -- IMyNav interface and MyNav instance registered as a singleton
 -- DelegateCommands similar to those in the ViewModels
  - Fails on navigation to PrismContentPage2

Code Behind Event handler -- partially works
  -- same behavior as MyNav 

### Steps to Reproduce
1.  Test Direct Navigation among the pages
- On MainPage. Click "PrismContentPage1 direct" button. PrismContentPage1 appears.
- On PrismContentPage1. Click "PrismContentPage2 direct" button. PrismContentPage2 appears.

2.  Test Command Navigation among the pages

3.  Test MyNav Command Navigation among the pages
- On MainPage. Click "PrismContentPage1 mynav command". PrismContentPage1 appears.
- On PrismContentPage1. Click "PrismContentPage2 mynav command". !No navigation!

### Expected Behavior
calling the _navigationService.NavigateAsync() should work in any class

### Actual Behavior
calling the _navigationService.NavigateAsync() only works in ViewModel

### Basic Information

- Version with issue: 7.2.0.1422
- Last known good version: None
- Xamarin.Forms version: 4.4.0.00991757
- IDE: Visual Studio 2019 Windows

I have tested on both Android and iOS -- same behavior.

### Reproduction Link
[PrismNavBug.zip](https://github.com/PrismLibrary/Prism/files/4350609/PrismNavBug.zip)

**Comment by brianlagunas** [comment]
Navigation in Xamarin.Form cannot be a singleton.  Please read the XF docs to better understand how navigation in XF works.  In Prism, navigation must occur within a ViewModel using the INavigationService that was injected.

**Comment by tmay57** [comment]
Thanks for the quick response!

I am familiar with XF and how navigation in XF works. In addition, I have traced through the Prism code quite a bit and have some glimmer as to what is going on in the lib. The context of my project is separating the ViewModels entirely from the underlying presentation engine (Xamarin) so more code reuse is possible with a different presentation engine (Blazor) and working with the upcoming .NET 5 easier. I know this wasn't apparent in the simple sample project I sent you. The MyNav class would live in the View project and reference Xamarin etc.

FWIW, my current project is similar to MvvmCross in that the ViewModels are in a  different project than the Views. I have nothing but standard .NET in the ViewModels and Prism.Core in the ViewModel project to leverage DelegateCommand and the Ioc libs. Works like a charm. Only my Forms project and deploy projects reference Xamarin.

 I can hand roll the navigation myself or fork Prism. I've been using Prism for a year or so and appreciated the feature set it provides and still use the non-UI elements of the library in my ViewModel project as they don't rely on anything that isn't portable. Thanks for taking a quick look at my issue. I'll let you know if I decide to hack Prism and end up with a usable generic feature.

**Comment by dansiegel** [comment]
if you're trying to do something nuts like use Prism and Blazor together talk to @RLittlesII
