### ISSUE TITLE
[Enhancement] Add ContainerProvider for XAML in WPF

### ISSUE THREAD

**Issue by gayaK** [PrismLibrary/Prism#2041]
## Summary

It enables the same function as #1347 in WPF.

## API Changes

Add only one class.

```cs
public class ContainerProviderExtension : System.Windows.Markup.MarkupExtension 
{
  public ContainerProviderExtension(Type t) => Type = t;

  private static readonly IContainerProvider _containerProvider
    => (Application.Current as PrismApplicationBase)?.Container;

  public Type Type { get; set; }
  public String Name { get; set; }

  public override object ProvideValue(IServiceProvider _)
    => _containerProvider.Resolve(Type, Name);
}
```

e.g.

```xml
<Window.DataContext>
  <prism:ContainerProvider Type="local:MyVM" />
</Window.DataContext>
<TextBlock Text="{Binding Path=Foo,
                          Converter={prism:ContainerProvider {x:Type local:MyConverter}}}" />
```

**Comment by dansiegel** [comment]
I agree this would be a good addition for WPF, actually thought @brianlagunas had already added it for parity. In any case Brian thoughts on this as we have the issue in WPF where some applications may need to use the Bootstrapper while most will use the PrismApplication?

**Comment by brianlagunas** [comment]
Yes, the reason this hasn't been added is because of the bootstrapper. There are 2 ways to create a Prism for WPF app, PrismApplication, and the Bootstrapper.  Both have their use cases.  However, you could use the ServiceLocator, but I was really hoping we could remove that thing altogether. So I don't think I want to keep adding code that uses it.

**Comment by gayaK** [comment]
I didn't consider about Bootstrapper.
So I've understood this problem is difficult.

**Comment by dansiegel** [comment]
With #2056 merged, this issue is now unblocked and welcome for a community PR.
