### ISSUE TITLE
[Bug] Issue loading modules from module catalog when older framework dll is included

### ISSUE THREAD

**Issue by stekkedoos** [PrismLibrary/Prism#2045]
### Description

Issue when starting a .net4.5.2 application with older dll's
While initializing the modules, from the module folder, prism crashes.
This only happens when there is a referencing dll for the module inside the module folder that is depending on runtime V2.0.... of .NET

### Steps to Reproduce

1. Create shell
2. create module
3. add reference to module that references .net runtime v2.0...
4. copy the dll to the module folder (as the module needs it to work)
5. Build and run
6. OnInitializing the module you get an exception

### Expected Behavior
only get dll's that are of type IModule

### Actual Behavior
takes every file in the modulefolder

### Basic Information

- Version with issue: 7.2.0.1422
- IDE: Visual Studio 2019

### Screenshots

![image](https://user-images.githubusercontent.com/1382453/77426132-318c6400-6dd4-11ea-97fb-33cd50a67cb4.png)

### Reproduction Link
can't release company code

added a dll the throws the error
[DMXLiteClient.zip](https://github.com/PrismLibrary/Prism/files/4375264/DMXLiteClient.zip)

**Comment by brianlagunas** [comment]
This is not a bug, and is not supported in a .NET application. If your module relies on a specific assembly to function, such as the "SystemWindows.Forms" assembly in your screenshot, your app must also have that assembly loaded into the AppDomain. You also can't mix different versions of an assembly that has been referenced unless you have a number of steps in place to support redirecting your assemblies or ensuring those assemblies are compatible with your app.
