### ISSUE TITLE
[Enhancement] Add overload to IEventAggregator to provide delegate and filter only

### ISSUE THREAD

**Issue by brianlagunas** [PrismLibrary/Prism#2046]
## Summary

We want to provide an API to the IEventAggregator that allows a developer to provide a filter without having to specify a thread and the keepSubscriberAlive options.

## API Changes

Add new overload
```
eventAggregator.GetEvent<MyEvent>().Subscribe(Method, filter => filter.Value == value);

```

**Comment by dansiegel** [comment]
fixed
