### ISSUE TITLE
[Bug] PageNavigationService doesnt throw exception for failed ViewModel dependency

### ISSUE THREAD

**Issue by SilverioMiranda** [PrismLibrary/Prism#2047]
### Description
PageNavigationService::NavigateInternal doesnt throw exception if ViewModel DI fails to load some dependency and doesnt throw any exception, just logging it

Can we change that to throw exceptions related only to DryIoc? or do more less generic than catch(Exception)?

### Steps to Reproduce

1. Create Interface but dont Register it
2. Create your ViewModel and add reference to it in constructor
3. Navigate to your view

### Expected Behavior
The code throws this exception:
Throw DryIoc.ContainerException: Unable to resolve DryIoc.ContainerException: Unable to resolve Miranda.Mobile.Vendas.ViewModels.LoginPageViewModel with passed arguments [value(Prism.Navigation.PageNavigationService)] IsResolutionCall\n  from Container without Scope\n with Rules with {AutoConcreteTypeResolution} and without {UseFastExpressionCompilerIfPlatformSupported}\n with Made={FactoryMethod=ConstructorWithResolvableArguments}\nWhere no service registrations found\n  and no dynamic registrations found in 0 of Rules.DynamicServiceProviders\n  and nothing found in 1 of Rules.UnknownServiceResolvers\n  at DryIoc.Interpreter.TryInterpretAndUnwrapContainerException (DryIoc.IResolverContext r, FastExpressionCompiler.LightExpression.Expression expr, System.Boolean useFec, System.Object& result) [0x00020] in <92da8401330947909899e4f36c32e769>:0 \n  at DryIoc.Container.DryIoc.IResolver.Resolve (System.Type serviceType, System.Object serviceKey, DryIoc.IfUnresolved ifUnresolved, System.Type requiredServiceType, DryIoc.Request preResolveParent, System.Object[] args) [0x0023b] in <92da8401330947909899e4f36c32e769>:0 \n  at DryIoc.Resolver.Resolve (DryIoc.IResolver resolver, System.Type serviceType, System.Object serviceKey, DryIoc.IfUnresolved ifUnresolved, System.Type requiredServiceType, System.Object[] args)

### Actual Behavior

No exception is shown, navigation page still blank and no warnings are made. The exception generated by DryIoc are handled inside PageNavigationService:NavigateInternal and doesnt thrown back

### Basic Information
The problem is here https://github.com/PrismLibrary/Prism/blob/master/Source/Xamarin/Prism.Forms/Navigation/PageNavigationService.cs#L328-L333
in this catch block :
```
catch (Exception ex)
            {
                _logger.Log(ex.ToString(), Category.Exception, Priority.High);
                result.Exception = ex;
                return result;
            }
```

I dont know if this is the expected behaviour, but we can change that to more less generic Exception or add other catch block to catch DryIoc.ContainerException?

Like : 
```
catch(DryIoc.ContainerException ex)
        {
            throw ex;
        }
catch (Exception ex)
            {
                _logger.Log(ex.ToString(), Category.Exception, Priority.High);
                result.Exception = ex;
                return result;
            }
```

**Comment by dansiegel** [comment]
This is not a bug, this is by design. The Navigation Service specifically catches any exceptions. We typically wrap any exception caught as an inner exception to a NavigationException which contains a message to help you understand the probable cause of the Navigation Error.

As I said all exceptions are caught. If you look at the NavigationService's method signature you'll notice that it returns a `Task<INavigationResult>`. If you check the result it will tell you if the navigation was successful or not and will contain any exception that was thrown allowing you to log it or do what ever you need to do.
