### ISSUE TITLE
[Bug] UI is stuck when using HttpClient

### ISSUE THREAD

**Issue by VlaTo** [PrismLibrary/Prism#2049]
### Description
The UI of the sample application is stuck (feeze) when using HttpClient to retrieve data and targeting Android Simulator.

### Steps to Reproduce

1.  Creating sapmple project from template 'Prism Blank App (Xamarin.Forms)'
2.  Adding code to get data over HttpClient 
3. Target Andriod Simulator or real device

### Expected Behavior
The UI should be updated (binded)

### Actual Behavior
The UI is stuck (feeze)

### Basic Information
- Version with issue: v7.2.0.1367
- Last known good version: --
- Xamarin.Forms version: v3.6.0.344457
- IDE: Microsoft Vusial Studio 2019 16.6.0 Preview 2

### Reproduction Link
https://github.com/VlaTo/BlankApp3 to produce problem.

**Comment by dansiegel** [comment]
this is not a bug with Prism or Xamarin.Forms but with your code. There are two issues you're facing here...
1) http://example.com is not secured which throws an exception on Android
2) You cannot use InitializeAsync on the root view.

**Comment by dansiegel** [comment]
I'm adding the revised sample to assist for anyone who is trying to better understand this issue.

[BlankApp3.zip](https://github.com/PrismLibrary/Prism/files/4439342/BlankApp3.zip)
