### ISSUE TITLE
RequestNavigate returns System.Object as DataContext for view

### ISSUE THREAD

**Issue by bzuillsmith** [PrismLibrary/Prism#205]
I can't get the region manager to resolve my class properly. I am calling ```_regionManager.RequestNavigate("MainRegion", "HelloWorldView")``` in one of my ViewModels and it creates a new view bound to ```System.Object```. No ```HelloWorldViewModel``` class appears to be instantiated. If I call ```_regionManager.RegisterViewWithRegion("MainRegion", typeof(Views.HelloWorldView));``` it creates and binds to an instance of ```HelloWorldViewModel```, but obviously I don't get the navigation and activation. I can also use view injection, but that also doesn't give me navigation/activation.

Also, I'm using ```UnityBootstrapper``` which may be relevant.

Is there a step I'm missing to link the ```HelloWorldView``` target to the ```HelloWorldViewModel``` type?

**Comment by bzuillsmith** [comment]
Of course I find it on the very next search I make... Unity apparently needs the module to register the view like so ```_container.RegisterType<object, HelloWorldView>("HelloWorldView");```.

**Comment by brianlagunas** [comment]
If you are using Prism 6, there is a new extension method called Conatiner.RegisterTypeForNavigation<HelloWorldView> which uses the view name by default.

**Comment by bzuillsmith** [comment]
Interesting, what container class/interface is that? I've been using ```IUnityContainer```.

**Comment by brianlagunas** [comment]
It's there for all the containers :)

**Comment by bzuillsmith** [comment]
Doh, right. Just needed the proper namespace. Found it. Looks like the default value was recently fixed and not in the published version though. Thanks!
