### ISSUE TITLE
IActiveAware not working when TabbedPage is inside a MasterDetailPage (as Detail)

### ISSUE THREAD

**Issue by HelenMamalaki** [PrismLibrary/Prism#2051]
### Description
`IActiveAware` not working when `TabbedPage `is set as the Detail Page inside a `MasterDetailPage`.

I implement IActiveAware on the Viewmodel of my individual tab pages following the Prism documentation [here](https://github.com/PrismLibrary/Prism-Documentation/blob/master/docs/xamarin-forms/navigation/working-with-tabbedpages.md/#L1) and it works fine when my `TabbedPage `is the root page. But when that same tabbed page is inside a `MasterDetailPage `it doesn't work anymore.

### Reproduction steps:
Set the root page to be a `MasterDetailPage `with a `TabbedPage `as the Detail Page, then the IActiveAware on the tab page viewmodel doesn't work any more.

### Expected Behavior
`IActiveAware.IsActive` to be set when switching between tabs even when a `TabbedPage `is inside a `MasterDetailPage`.

### Actual Behavior
`IActiveAware.IsActive` is not set

### Basic Information

- Version with issue: v7.2.0.1422 (Prism.Forms, Prism.Core, Prism.Unity.Forms)
- Last known good version: Not known
- Xamarin.Forms version: v4.5.0.356
- IDE: VS2019 Win10

### Reproduction Link
Please see sample solution which replicates issue [here ](https://drive.google.com/file/d/1qqTx1wDi2ssZOuECRpLRwg-e69DQEwwD/view?usp=sharing)

MainPage.cs is a `MasterDetailPage` with TabbedTestPage.cs set as Detail Page.
The second tab called 'AboutPage.cs' has IActiveAware implemented in the AboutPageViewModel.cs I breakpoint the IsActive property and it's not hit. If you comment out MasterDetailPage and navigate directly to TabbedTestPage.cs and switch to 2nd tab (AboutPage), the breakpoint is hit.

**Comment by brianlagunas** [comment]
This is because you are not using Prism to build your Detail page, but instead you are hard coding the DetailPage. If you want to hard code the Detail page like you are doing, you will have to add the IActiveAware behavior youself.

**Comment by HelenMamalaki** [comment]
@brianlagunas Thank you for your quick response. It works now. :) I didn't realise I wasn't meant to set the Detail page in the xaml when using Prism. There was nothing in the official Prism [docs]https://prismlibrary.com/docs/xamarin-forms/navigation/working-with-masterdetailpages.html) for MasterDetailPage but I have since found many blogs and sample projects with examples which cover what I needed. Thanks again.

**Comment by dansiegel** [comment]
@HelenMamalaki if there are docs you feel we're missing you're always welcome open an issue on the [docs repo](https://github.com/PrismLibrary/Prism-Documentation/issues/new) and tell us what you feel is missing and why it would help. If we agree it would beneficial you are also welcome to submit a PR with some docs to help the next person ;)
