### ISSUE TITLE
[Enhancement] Create New Bootstrapper for Prism.WPF

### ISSUE THREAD

**Issue by dansiegel** [PrismLibrary/Prism#2061]
## Summary

The Bootstrapper for WPF is based on an older API and not really aligned with how PrismApplication makes creating an application very easy. The existing Bootstrapper should be moved to a Legacy namespace to make way for a new Bootstrapper that follows the more simplified and consistent approach that we use in PrismApplication

**Comment by d3fkn1ght** [comment]
Would this just involve changing the Bootstrapper.cs file's namespace in the Prism.Wpf project?

**Comment by brianlagunas** [comment]
@d3fkn1ght No, this will require creating a brand new bootstrapper class with an updated API.

**Comment by d3fkn1ght** [comment]
@brianlagunas Ok, thought would be fun to try to implement this but if that is the case then I'll wait to see what you come up with

Thanks for explaining

**Comment by dansiegel** [comment]
hence why it got assigned to @brianlagunas and didn't get the `Good First Issue` label ;)

**Comment by d3fkn1ght** [comment]
true, guess i got a little ahead of myself ;)
