### ISSUE TITLE
Replace IDialogParameters with INavigationParameters

### ISSUE THREAD

**Issue by Jesus805** [PrismLibrary/Prism#2064]
## Summary

I noticed in the source code that there is a TODO: to replace IDialogParameters with INavigationParameters. I am writing this issue because I did not see it as an existing issue and in-case we want to add this to the Prism 8.0 roadmap

## API Changes

- Move INavigationParameters to Prism.Core
- Currently there are two classes of Navigation Parameters, one defined in Prism.Wpf and Prism.Forms, perhaps they should be merged and moved to Prism.Core
- Replace all references of IDialogParameters with INavigationParameters

**Comment by dansiegel** [comment]
@brianlagunas comment is from you... we probably do want to take a look at how we want to deal with Parameters long term. We've already introduced a ParametersBase. This probably does need some refactoring... we may... emphasis on may... want to think about introducing a common IParameters that IDialogParameters and INavigationParameters can inherit from....

https://github.com/PrismLibrary/Prism/blob/07997a6097ddc4edea725047453e030ef272b0a9/src/Wpf/Prism.Wpf/Services/Dialogs/IDialogParameters.cs#L3-L9

**Comment by brianlagunas** [comment]
It was decided to keep the IDialogParameters for the sake of API ease of use. For example, it doesn't make sense to pass NavigationParameters to a Dialog. We can't move the NavigationParameters to Core becuase the namespaces would not align with the platforms. For example; RegionNaviagtion exists in the Regions namespace. It would not make sense to have parameters for region navigation in one namespace and the actual region navigation framework in another namespace.

**Comment by brianlagunas** [comment]
I will add this during stream on 4/23/2020

https://www.twitch.tv/brianlagunas

**Comment by d3fkn1ght** [comment]
Great, looking forward to it ;)
