### ISSUE TITLE
[Bug] View "view" named can't auto inject the viewmodel

### ISSUE THREAD

**Issue by johnMinelli** [PrismLibrary/Prism#2066]
### Description
If i create a view named like "FileTreeView" but the corresponding viewmodel it's not autoinjected with the line `prism:ViewModelLocator.AutoWireViewModel="True"`.
I both tried with a vm named FileTreeViewViewModel and FileTreeViewModel.
### Expected Behavior
Having a simple button that call a command in the viewmodel. i would expect that it builds and starts normally.
### Actual Behavior
Executing i've got an error in the xaml that can't make the binding since it doesn't find the method, that is in the viewmodel.
### Basic Information
- JetBrains Rider 2020.1.0 Build #RD-201.6668.197
- Prism 7.2.0..1422

**Comment by madfisht3** [comment]
Did you check the namespace of both files? This appeared when I didn't change the namespace of a XAML file or a ViewModel file. You must ensure that your XAML file is located to Views folder and ViewModel file is located to ViewModels folder. Of course, you must change namespaces to Project.Views and Project.ViewsModels.

**Comment by johnMinelli** [comment]
I've done it so. the only difference is that the vm is in Project.ViewModels. and not ViewsModel.
Are you able to reproduce it or the problem is somewhere else?

**Comment by dansiegel** [comment]
This is not a but with Prism... we intentionally guard against scenarios where your View ends with View... your ViewModel should be FileTreeViewModel not FileTreeViewViewModel. Also keep in mind that you can break with our conventions any time you want by simply registering them together.

```cs
containerRegistry.RegisterForNavigation<FileTreeViewModel, NotGonnaTryToMatchViewModel>();
```
