### ISSUE TITLE
[Enhancement] Add a build time code gen for AutoRegisterForNavigation

### ISSUE THREAD

**Issue by dansiegel** [PrismLibrary/Prism#2071]
## Summary

Autoregistration is pretty expensive generally, if done through reflection (it iterates on all types). It's generally better to generate the code for that instead.

## API Changes

None

## Intended Use Case

When someone is using AutoRegisterForNavigation we want to generate the code at build rather than waiting for runtime reflection to improve perf.

**Comment by d3fkn1ght** [comment]
If I can be of any assistance, let me know.  This might be outside the scope of my abilities but would love to help.

**Comment by d3fkn1ght** [comment]
I would like to assist with this if I can.  Would be a good learning opportunity but maybe too advanced for me.  If I can help, please let me know.

**Comment by dansiegel** [comment]
This is a pretty advanced issue

**Comment by d3fkn1ght** [comment]
Fair enough.  Thought I'd offer in case I could help.  Good luck with it.

**Comment by brianlagunas** [comment]
This may work in XF, but this will not be a good feature for WPF.

**Comment by brianlagunas** [comment]
The more I think about this, the more I think this should not be part of Prism and should be a stand-alone tool as some's side project. I am closing this issue because this "tool" belongs somewhere else.
