### ISSUE TITLE
[Proposal] Add ContainerResolutionException

### ISSUE THREAD

**Issue by dansiegel** [PrismLibrary/Prism#2078]
## Summary

Prism currently utilizes the ExceptionExtensions to collect a list of known framework exceptions which currently only track the Container Specific exceptions (the `ContainerException` for DryIoc and `ResolutionFailedException`). We should add a specific exception that the Extensions can throw when a service is not resolved. 

This solves an issue in which it can be difficult to determine what Service Type / Key was used when attempting to resolve a service. This is currently works very well in the Prism.Container.Extensions and is an easy win when debugging.

## API Changes

https://github.com/dansiegel/Prism.Container.Extensions/blob/40b77f34a006b4ca661a356ec455690dc460e0cf/src/Prism.Container.Extensions/ContainerResolutionException.cs#L5-L31

## Intended Use Case

```cs
public class ViewAViewModel
{
    public ViewAViewModel(IServiceIForgotToRegister badService)
    {
        // Do stuff
    }
}

public partial class App
{
    protected override void OnInitialized()
    {
        var result = await NavigationService.NavigateAsync("ViewA");
        if(!result.Success)
        {
            // I can now see the result.Exception is a ContainerResolutionException
            // and that it was the ViewModel not the View that had the issue...
            // thus telling me where to focus my energy... 
        }
    }
}
```

A possible enhancement over simply catching any exception and wrapping it in a ContainerResolutionException would be that we could spend the extra time to evaluate the ctor of the type and check for any unregistered services. This would then go into the exception making the debugging process easier and faster to iterate.

**Comment by dansiegel** [comment]
In talking with @brianlagunas we've come to some agreement on this...
As part of the issue #2076 we'll be adding the ContainerResolutionException as well.

We'll also add a method off of the ContainerException that will give you a helper to try to diagnose the actual issue. For the example ViewModel above you might end up with:

```cs
protected override async void OnInitialized()
{
    INavigationResult result = await NavigationService.NavigateAsync("ViewA");
    if (!result.Success)
    {
        switch(result.Exception)
        {
            case NavigationException ne when ne.InnerException is ContainerResolutionException cre:
                HandleContainerException(cre);
                break;
            case NavigationException ne:
                HandleNavigationException(ne);
                break;
            default:
                // Report a bug to the Prism Team
                break;
        }
                
    }
}

private void HandleContainerException(ContainerResolutionException cre)
{
// NOTE: This is not a cheap function to execute... This will recurse dependencies...
// Multiple exceptions may be thrown and caught
#if DEBUG
    // returns IDictionary<Type, Exception>
    var errors = cre.GetErrors();
    foreach ((var type, var ex) in errors)
    {
        Console.WriteLine($"Could not resolve {type.Name}.");
        Console.WriteLine($"{ex.GetType()} - {ex.Message}");
        // Writes the following to the console:
        // Could not resolve IServiceIForgotToRegister. 
        // ContainerResolutionException - No Registration was found in the container for the specified type
    }
#endif
}
```

The goal here is to have an opt-in helper that can evaluate a ContainerResolutionException. The ContainerResolutionException for instance may help you to determine that your error was with the Page or with a ViewModel. The `GetErrors()` method will attempt to locate the errors such as hey you forgot to register a service or there is a TypeInitializationException here... etc..

## Implementation Notes

Just like with the NavigationException in Prism.Forms I'll be adding some constant strings for some scenarios where GetErrors will produce a ContainerResolutionException for certain known issues to be listed in the GetErrors. Keep in mind that GetErrors will catch any exceptions to give you them in a consolidated Dictionary to make it easier to diagnose what the issue(s) are and which types they may be associated with.

**Comment by mackayn** [comment]
This will make debugging A LOT easier!

**Comment by Im-PJ** [comment]
I'm getting below error after updating to Prism 8-pre without making any changes. 
Prism.Ioc.ContainerResolutionException: An unexpected error occurred while resolving 'Prism.Navigation.INavigationService' ---> System.MissingMethodException: Method not found: void Prism.Navigation.PageNavigationService..ctor
