### ISSUE TITLE
[Enhancement] Move IDialogAware from Prism.WPF to Prism.core

### ISSUE THREAD

**Issue by luckymark** [PrismLibrary/Prism#2079]
## Summary

Make DialogViewModel to cross platform(windows、MacOs。。。)

## API Changes
Move IDialogAware from Prism.WPF（only for windows）to Prism.core

**Comment by dansiegel** [comment]
Thanks for the suggestion. This isn't something that we're going to do though as there are subtle differences between the API for WPF and Xamarin.Forms

**Comment by luckymark** [comment]
Thanks!
I've readed Prism's code. IDialogAware just depends on  IDialogResult & IDialogParameters & ButtonResult .There isn't any dependency with WPF or Xamarin.Forms.  Does I miss something?

**Comment by dansiegel** [comment]
correct there isn't a dependency on either platform but the API's themselves are slightly different as you noted WPF includes a ButtonResult where it doesn't make sense on Xamarin.Forms.

**Comment by luckymark** [comment]
Thanks！
I agree with that the APIs are slightly different.If I want define some DialogModel:IDialogAware in a core project(just depends on DotNetCore),How can I do this? Any suggestion?
