### ISSUE TITLE
Fix the DevOps Pipeline to publish the Test Results for Core/Forms

### ISSUE THREAD

**Issue by dansiegel** [PrismLibrary/Prism#2080]
## Summary

The Test Results are not getting published for Prism.Core or Prism.Forms. And they are duplicated for Prism.WPF. We need to fix this so they are published once, and published by all..

**Comment by EdwardBlair** [comment]
#2081, tests now publish as follows:

![image](https://user-images.githubusercontent.com/239672/80011057-36236580-84c3-11ea-9f7e-1985c88b3d52.png)

I publish the test results as early in the pipelines as possible, this gives greater possibility that if subsequent tasks fail, results are still published at least partly.
I've parametised the yml in such a way that you can easily modify this to publish at the end of the "Full Prism Library" task if you so desire i.e. just move the ```publishTestResults: true``` directives to the ```prism-lib.yml```

As an FYI: I replaced VSTest task with a powershell task running dotnet cli test commands for Prism.Wpf.*.Tests.

**Comment by dansiegel** [comment]
fixed by #2081
