### ISSUE TITLE
[Enhancement] Support Tasks in DelegateCommand

### ISSUE THREAD

**Issue by brianlagunas** [PrismLibrary/Prism#2082]
## Summary

`Async Void` has been a major pain in the ass when working with DelegateCommands since async/await was introduced.

It has been decided that there will never be an AsyncDelegateCommand, however, we still need away to call Task based code from within a DelegateCommand Execute handler while maintaining the ability to properly handle the task such as exceptions being thrown.

## API Changes

Add an extension method that allows you to await a Task inside of a void method.

I am envisioning something like this:  `TaskMethod().Await();`

## Intended Use Case

```
void ExecuteCommand()
{
    UpdateText().Await(HandleError);
}

private void HandleError(Exception ex)
{
    //handle exception
}
```

**Comment by brianlagunas** [comment]
I will add this during stream on 4/23/2020

https://www.twitch.tv/brianlagunas

**Comment by dansiegel** [comment]
added in #2084
