### ISSUE TITLE
[Enhancement] Support NavigateAsync in void methods

### ISSUE THREAD

**Issue by brianlagunas** [PrismLibrary/Prism#2083]
## Summary

Similar to #2082, calling `navigationService.NavigateAsync("path")` in a DelegateCommand execute handler which is void, requires the use of an `async void`. We want to make this experience easier to use in the `async void` scenario.

## API Changes

I am looking for an API similar to:

`navigationService.NavigateAsync("path").Await()`

## Intended Use Case

```
void ExecuteCommand()
{
    _navigationService.NavigateAsync("path").Await(OnNavigationComplete);
}

private void OnNavigationComplete(INavigationResult result)
{
    //handle result
}
```

**Comment by brianlagunas** [comment]
I will add this during stream on 4/23/2020

https://www.twitch.tv/brianlagunas

**Comment by dansiegel** [comment]
added in #2084
