### ISSUE TITLE
[Bug] UI Tests failing for iOS on iPad

### ISSUE THREAD

**Issue by dansiegel** [PrismLibrary/Prism#2087]
### Description

Our UI Tests for Prism.Forms are currently failing when running on iPad. We need to investigate what is different in the E2E app from iPhone to iPad and evaluate what changes we need to make.

This issue is open and welcome for Community Involvement.

**Comment by adamhill** [comment]
I have an iPad and would like to work on this.

**Comment by dansiegel** [comment]
@adamhill just realized your comment was never responded to... to be honest I haven't tried it on a Simulator. The issue was noticed with the device cloud tests in App Center

**Comment by dansiegel** [comment]
Not sure what we "fixed" but all UI tests have been passing since build 1803
