### ISSUE TITLE
Should animate parameter on NavigationService.Navigate method signature be removed?

### ISSUE THREAD

**Issue by brianlagunas** [PrismLibrary/Prism#21]
After talking to a number of Xamarin.Forms developers, I am finding that controlling the animation during navigation is very rare.

Is this correct?  And if so, should we remove the animate parameter from the Navigate method signature?

If we do keep it, should we at least move it to the end of the method signature?  Make it the last parameter?

**Comment by Michael-DST** [comment]
I would vote for that. :+1:  Animation should be a concern of the view, ideally.  With that said, my Xamarin.Forms navigation experience is very minimal (but, that parameter has always bugged me).  It would be great to hear from someone with a good deal of experience around this parameter to get their take on why it's being passed around like it is and not being handled by the view.

**Comment by powerdude** [comment]
I would suggest leaving it has i've seen quite a number of people on forums want something like this.  It becomes necessary when you want to push/pop a number of forms on/off the stack but not make it obvious you are doing so.  I haven't run into the scenario myself, but I see it is possible.

**Comment by omares** [comment]
@brianlagunas could you please link the current implementation?

In general, please keep the option to control the animation, controlling it is an important part of handling the navigation stack "behind the scene".

**Comment by brianlagunas** [comment]
@omares here is the interface definition:
Prism/Source/Xamarin/Prism.Forms/Navigation/INavigationService.cs

I am thinking that the animated parameter should at least go last since it is probably not used as the useModalNavigation would be.

**Comment by brianlagunas** [comment]
What about passing the "animated" option as a NavigationParameter, instead of placing it on the Navigate method signature?

**Comment by Michael-DST** [comment]
That is definitely better.  I myself would prefer a clever use of an attached property somewhere, in the most ideal of situations. Again, that's just my input without me sticking my nose into it too much yet.

**Comment by brianlagunas** [comment]
For now, I just moved the animated parameter to the end of the method signature.  I will re-evaluate if the community is completely against it.
