### ISSUE TITLE
[Bug]IRegionManager#RequestNavigate doesn't work when OnInitialized method of IModule

### ISSUE THREAD

**Issue by runceel** [PrismLibrary/Prism#2102]
### Description

I have tried Prism.Unity.Uno 8.0.0.1717-ci.
`RequestNavigate` method of `IRegionManager` doesn't work when `OnInitialized` method of `IModule`.

After Shell is displayed, then `RequestNavigate` method becomes work.

### Steps to Reproduce

1. Create an UWP project
2. Add Prism.Unity.Uno 8.0.0.1717-ci package
3. Change App class and create a Shell that has ContentRegion.
4. Create a Class Library as Prism module.
5. Add Prism.Unity.Uno 8.0.0.1717-ci package to the library project.
6. Create a View and create a module class.
7. Implements the module class:
```csharp
using Prism.Ioc;
using Prism.Modularity;
using Prism.Regions;
using PrismHelloWorld.Main.ViewModels;
using PrismHelloWorld.Main.Views;

namespace PrismHelloWorld.Main
{
    public class MainModule : IModule
    {
        public void OnInitialized(IContainerProvider containerProvider)
        {
            // it doesn't work.
            var regionManager = containerProvider.Resolve<IRegionManager>();
            regionManager.RequestNavigate("ContentRegion", nameof(MainView));
        }

        public void RegisterTypes(IContainerRegistry containerRegistry)
        {
            containerRegistry.RegisterForNavigation<MainView, MainViewModel>();
        }
    }
}
```
8. Add below code to load the module to App.xaml.cs
```csharp
protected override void ConfigureModuleCatalog(IModuleCatalog moduleCatalog)
{
    moduleCatalog.AddModule<MainModule>();
}
```

### Expected Behavior

MainView will be displayed to 'ContentRegion' on the Shell.

### Actual Behavior

MainView isn't displayed.

### Basic Information

- Version with issue: Prism.Unity.Uno 8.0.0.1717-ci
- Last known good version: None
- Xamarin.Forms version: None
- IDE: Visual Studio 2019 16.5.4

### Screenshots

There is a blank area. MainView has a TextBlock(`Hello from MainViewModel'). But there is not displayed.

![image](https://user-images.githubusercontent.com/79868/80271864-72dba080-86ff-11ea-9417-7dd416ff06cc.png)

A button of bottom one that is attached below event handler was clicked, MainView is displayed correctly. 
```csharp
private void NavigateRequestButton_Click(object sender, RoutedEventArgs e)
{
    RegionManager.RequestNavigate("ContentRegion", "MainView");
}
```

![image](https://user-images.githubusercontent.com/79868/80271867-7bcc7200-86ff-11ea-89c2-7f4d73e89c1a.png)

### Reproduction Link

It needs Prism.Unity.Uno 8.0.0.1717-ci package.

https://github.com/runceel/PrismHelloWorld

**Comment by dansiegel** [comment]
cc: @jeromelaban

**Comment by brianlagunas** [comment]
@runceel Does RegisterViewWithRegion work?

**Comment by jeromelaban** [comment]
This happens because the `OnInitialize` is called before the region has had the chance for the visual tree to be created. This makes the RegionManagerRegistrationBehavior fail to find the region manager:

https://github.com/PrismLibrary/Prism/blob/1d4a9620cc6940dca4149f6fb1933eee7456bbe7/src/Wpf/Prism.Wpf/Regions/Behaviors/RegionManagerRegistrationBehavior.cs#L146

Because VisualTreeHelper returns a parent only when the control is Loaded.

@brianlagunas Is this a common scenario when using Prism WPF (navigating in OnInitialize during startup) ?

An immediate workaround for this is to navigate once the window is activated:

```csharp
void Navigate(object sender, object args)
{
    regionManager.RequestNavigate("ContentRegion", nameof(MainView));

    Windows.UI.Xaml.Window.Current.Activated -= Navigate;
}

Windows.UI.Xaml.Window.Current.Activated += Navigate;
```

But it may be interesting to load the modules only once the Loaded event on the shell has been invoked. I've validated quickly that doing something like this in `PrismApplicationBase` will allow this scenario to work:

```csharp
var shell = CreateShell();
if (shell != null)
{
    _containerExtension.Resolve<IRegionNavigationService>().NavigationFailed += (s, e) => Console.WriteLine($"Region navigation failed {e.Error}");
    InitializeShell(shell);

    void FinalizeInialization(object sender, object args)
    {
        RegionManager.SetRegionManager(shell, _containerExtension.Resolve<IRegionManager>());
        RegionManager.UpdateRegions();

        InitializeModules();
        OnInitialized();

        (shell as FrameworkElement).Loaded -= FinalizeInialization;
    }

    (shell as FrameworkElement).Loaded += FinalizeInialization;
}
```

**Comment by runceel** [comment]
@brianlagunas It works.

RequestNavigate on OnInitizlized works on Prism.WPF.
I had found the issue when I tried Prism.Uno, so I just reported it.

If it is by design, then because I think it is not serious issue this issue can be closed.

**Comment by brianlagunas** [comment]
@jeromelaban This scenario does work in WPF. However, I'm not sure what the effects would be for Uno apps if your proposed change was made. It would be hard to say without some testing.

**Comment by runceel** [comment]
@jeromelaban 
Doesn't the following work to get a parent of the logical tree at `RegionManagerRegistrationBehavior.cs`?

```csharp
// parent = VisualTreeHelper.GetParent(dependencyObject); 
parent = (dependencyObject as FrameworkElement)?.Parent;
```

WPF gets a parent from the logical tree, so I think UWP should also do that.
How dou you think?

**Comment by jeromelaban** [comment]
@runceel unfortunately, even then, the parent is null. I'll be making a PR that updates the initialization and validates that scenario in the UI Tests.
