### ISSUE TITLE
[Bug] OnResume Navigation sets navigation back to root

### ISSUE THREAD

**Issue by ske66** [PrismLibrary/Prism#2104]
### Description

I have an app that requires a "User Login" modal to show on app start and resume. I wanted to show this as a modal when the app resumes but for some reason the view is still shown inside a NavigationPage.

### Steps to Reproduce

1. In the OnInitialize() method set the navigation route to just the Login Page
`
NavigationService.NavigateAsync("LoginPage");
`

2. On the login page, reset the navigation stack when the user logins in
`
NavigationService.NavigateAsync("/NavigationPage/MainPage");
`

3. Add an OnResume override to your app.xaml.cs and navigate to the login page as a modal
`
NavigationService.NavigateAsync("LoginPage", useModalNavigation: true);
`

4. Launch the app and login. When you get to the main page close and re-open the app. The OnResume Login Page will now be nested inside a NavigationPage

### Expected Behavior
The login page should appear as a modal when the app is resumed

### Actual Behavior
The login page is shown inside a NavigationPage

### Basic Information

- Version with issue: Prism.Dryloc.Forms (7.2.0.1422)
- Last known good version: Unkown
- Xamarin.Forms version: 4.5.0.657
- IDE: Visual Studio 2019
- Device: Zebra TC77 (Android 8.1)

### Screenshots

![NoModalNavigation](https://user-images.githubusercontent.com/26600892/80462217-49ed2280-892e-11ea-934e-1da162d2e1c4.gif)

### Reproduction Link

https://github.com/ske66/NoModalNavigationOnResume.git

**EDIT**

I made a slight modification to this to see if the modal is the issue. I believe it may actually be an issue with the OnResume method possibly setting navigation back to root

To check my theory I made the following changes to the code

App.xaml.cs
```
        protected override async void OnInitialized()
        {
            InitializeComponent();
            await NavigationService.NavigateAsync("NavigationPage/MainPage/LoginPage");
        }

      protected override async void OnResume()
        {
            base.OnResume();

            var path = NavigationService.GetNavigationUriPath();  //THIS CAUSES A NULL REFERENCE EXCEPTION
            Console.WriteLine(path);

            await NavigationService.NavigateAsync("LoginPage");
        }

```

LoginPageViewModel.cs
```
                var loginPath = NavigationService.GetNavigationUriPath();
                Console.WriteLine(loginPath);  //WATCH THIS

                await NavigationService.GoBackAsync(); //go back to the previous page in the stack. 
                                                                                Should be MainPage when the user first logs in, 
                                                                                another page when the user logs in after app resume
```

Interestingly enough, the loginPath in the LoginPageViewModel returns NavigationPage/MainPage/LoginPage when the user logs in for the first time, but shows NavigationPage/LoginPage when the user logs in after resuming the application. 

What i would expect to see is when I log in the LoginPage is popped, leaving the URI as NavigationPage/MainPage. When I resume the app the LoginPage should be pushed to the stack (depending on where you left the navigation stack) and displayed as Navigation/MainPage/..another_page.../..another_page../LoginPage.

Is NavigateBackToRootAsync() being called when the app is resumed?

**Comment by ske66** [comment]
I made a slight modification to this to see if the modal is the issue. I believe it may actually be an issue with the OnResume method and the NavigationContainer not being resolved properly.

To check my theory I made the following changes to the code

App.xaml.cs
```
        protected override async void OnInitialized()
        {
            InitializeComponent();
            await NavigationService.NavigateAsync("NavigationPage/MainPage/LoginPage");
        }

      protected override async void OnResume()
        {
            base.OnResume();

            var path = NavigationService.GetNavigationUriPath();  //THIS CAUSES A NULL REFERENCE EXCEPTION
            Console.WriteLine(path);

            await NavigationService.NavigateAsync("LoginPage");
        }

```

LoginPageViewModel.cs
```
                var loginPath = NavigationService.GetNavigationUriPath();
                Console.WriteLine(loginPath);  //WATCH THIS

                await NavigationService.GoBackAsync(); //go back to the previous page in the stack. 
                                                                                Should be MainPage when the user first logs in, 
                                                                                another page when the user logs in after app resume
```

Interestingly enough, the loginPath in the LoginPageViewModel returns NavigationPage/MainPage/LoginPage when the user logs in for the first time, but shows NavigationPage/LoginPage when the user logs in after resuming the application

**Comment by xerx** [comment]
Could be somewhat related to this Xamarin.Forms issue https://github.com/xamarin/Xamarin.Forms/issues/5813

**Comment by brianlagunas** [comment]
This is not a bug, but rather an issue in your logic and a misunderstanding of where you are navigating from.

First off, in the OnResume, you need to perform an absolute navigation for your login screen, not a modal.

```
protected override async void OnResume()
{
    await NavigationService.NavigateAsync("/LoginPage");
}
```

This will reset the navigation stack to just the LoginPage.

The reason you are getting the behavior you are now is becuase you are actually navigating from the root NavigationPage itself, not the MainPage you think you are. Since you are navigating from a NaviagtionPage, you cannot perform a modal as Prism forces a non-modal from a navigationPage.  If you wanted to keep the "NavigationPage/MainPage" on the stack, you would have to make sure you are navigating form the correct page, in this case the MainPageViewModel in order to maintain your current stack.

If you would like to keep the stack in place, but navigate modally from MainPageViewModel, then you need to implement `IApplicationLifecycleAware` and handle the OnResue in your MainPageViewModel instead.
