### ISSUE TITLE
[Bug] Container.Resolve<T> get wrong value

### ISSUE THREAD

**Issue by qtbui159** [PrismLibrary/Prism#2109]
### Description

new Number can get the correct result,
but Container.Resolve\<Number\> get the the incorrect result. 

### Steps to Reproduce

1.  Run the project

### Expected Behavior

result is 1234

### Actual Behavior

result is 4444

### Basic Information

- Version with issue: .NetFramework4.8， Prism.Unity 7.2.0.1422
- IDE: VS2019

### Screenshots

https://github.com/qtbui159/ResolveTest/blob/master/screenshot.png

### Reproduction Link

https://github.com/qtbui159/ResolveTest

**Comment by brianlagunas** [comment]
This is not a bug. You are passing your parameters as a type to the Resolve method. This means that Unity will try to match based only on type, and not on the order in which they are passed. SO it takes the last type of `int` that you passed in, which was 4. What you need is to pass your params based on name. Prism does not provide an API for named based params injection for ctor parameters. You will have to use the Unity container API directly for this functionality.
