### ISSUE TITLE
[Bug] Cant Load Module Assembly in .Net Core 3.0

### ISSUE THREAD

**Issue by ghost1372** [PrismLibrary/Prism#2115]
### Description
Assembly cant load on .NET Core and The problem can be solve by replacing some characters
### Steps to Reproduce

1. override ConfigureModuleCatalog 
2. Load Assembly with this code : `Assembly asm = Assembly.LoadFrom(mi.Ref);`

### Expected Behavior
The assembly must be loaded without any problems

### Actual Behavior
The program encounters an error `Could not load file or assembly`

### Basic Information
The problem is solved with the following code
`Assembly asm = Assembly.LoadFrom(mi.Ref.Replace(@"file:///", ""));`

- Version with issue: 7.2.1422
- IDE: VS2019

### Reproduction Link
[HandyControlProject13.zip](https://github.com/PrismLibrary/Prism/files/4601261/HandyControlProject13.zip)

**Comment by brianlagunas** [comment]
Thanks for the sample. This is related to #2031

**Comment by brianlagunas** [comment]
Actually, this is not a bug at all. First off, your post build can be clean up. It needs to look like this:
```
  <PropertyGroup>
    <PostBuildEvent>xcopy "$(TargetDir)$(TargetName)*$(TargetExt)" "$(SolutionDir)$(SolutionName)\bin\Debug\netcoreapp3.1\modules\" /Y /S</PostBuildEvent>
  </PropertyGroup>
```
Also, you can simplify your module path to this:
```
return new DirectoryModuleCatalog() { ModulePath = @".\modules" };
```
All that code you have in the override of ConfigureModuelCatalog is your custom code. It has nothing to do with Prism. That is the code that is failing.

The Module loads fine if you remove your override code.
