### ISSUE TITLE
[Enhancement] Multi-platform App UI (MAUI) Support

### ISSUE THREAD

**Issue by dansiegel** [PrismLibrary/Prism#2118]
## Summary

Xamarin.Forms is evolving to the Multi-platform App UI (MAUI). This includes some major breaking changes in namespaces. This will require the port of Prism.Forms to Prism.Maui

- https://github.com/dotnet/maui
- https://devblogs.microsoft.com/dotnet/introducing-net-multi-platform-app-ui/

**Comment by qtbui159** [comment]
coooool

**Comment by mackayn** [comment]
Sweet

**Comment by giuseppenovielli** [comment]
Nice :)

**Comment by romagny13** [comment]
😮

**Comment by almirvuk** [comment]
Is there are strategy ready on how to do this. Are we going to create a new project or with some branches strategy to stay up to date with Prism.Forms code and future changes?

**Comment by dansiegel** [comment]
@almirvuk it's really too early to say since we don't even have a CI build to use. I anticipate we may use a strategy like Prism.Uno has with Prism.WPF. But again it's a bit too early to say anything concrete.

**Comment by rajeshjha96** [comment]
Can't imagine using **MAUI** without **Prism**.

**Comment by LeoJHarris** [comment]
Exciting! 🥇

**Comment by NengSyle007** [comment]
I'm waiting Prism.Maui.

**Comment by Coder-Nut** [comment]
They accept PRs. Just saying.
________________________________

**Comment by dansiegel** [comment]
We do accept PRs but it's a moot point. There is no .NET MAUI package for us to work with.

**Comment by shmoe01** [comment]
Any thing new on prism supporting MAUI?

**Comment by dansiegel** [comment]
nope

**Comment by dansiegel** [comment]
Prism for Maui is now generally available as an alpha build on NuGet.org

**Comment by DamianSuess** [comment]
https://github.com/dansiegel/Prism.Maui

Link for future viewers until it gets moved into the PrismLibrary account

**Comment by OuterSpaceOrg** [comment]
Is there a timeline for Maui support?  

We are looking to migrate a Xamarin.Forms application that uses Prism extensively and want to start determining timelines into mid 2023.

**Comment by dansiegel** [comment]
We do not publicly discuss or adhere to specific timelines as Brian and I work on Prism in our spare time and all work on Prism is ultimately dependent on us having the time to work on it, or companies who are willing to fund initiatives. That said it is being worked on and I am hoping to try to have an updated preview out this month.
