### ISSUE TITLE
[Bug] [iOS] Application crashed with "System.Exception cannot destroy" exception when navigating back from page using Navigationbar

### ISSUE THREAD

**Issue by LakshmiNatarajan21** [PrismLibrary/Prism#2120]
### Description
Application crashed with "**System.Exception cannot destroy**" exception when navigating back from page using Navigation bar. The page has SfListView with ViewModel property bounded SfListView.DataSource bindable property. The reported issue occurs in the iOS platform. The crash occurs from _DestroyPage_ method.

**Note**:  In another bigger project also on Android and also with the navigation bar back button.

- The application will not crash if we set the DataSource property in code behind rather binding.

- Manual navigation works fine. This occurs when navigating using Page navigation.

- The Xamarin.Forms navigation works fine without the crash.

### Steps to Reproduce

1. Run the Sample on iOS.
2. Click the navigation back arrow.
3. The application will crash with "System.Exception cannot destroy" exception.

### Expected Behavior
Application should not crash.

### Actual Behavior
"System.Exception cannot destroy" exception occurs.

### Basic Information

- Version with issue: 7.2.0.1422
- Last known good version: -
- Xamarin.Forms version: 4.6.0.800
- IDE: 

### Reproduction Link
[IssueSample](https://www.syncfusion.com/downloads/support/directtrac/general/ze/13195-854545868)

**Comment by ninaada** [comment]
We had this problem for a very long time, but on Android though. This is caused by SyncFusion ListView not being disposed correctly. Here is how we fixed it.

Give a x:Name for your listview in XAML

`<sync:SfListView x:Name="sflist" SelectionMode="None" >`

Implement IDestructible interface on the views/page in the code behind.
In the destroy method there, dispose of the syncfusion listview.

`public void Destroy()
        {
            try
            {
                sflist.Dispose();
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.ToString());
            }
        }
`

**Comment by brianlagunas** [comment]
Thanks for sharing @ninaada. This is the correct answer. This is not an issue with Prism, it's an issue with syncfusion. I've heard another solution is to set the `DataSource = null`.

**Comment by ninaada** [comment]
@brianlagunas My pleasure. That `DataSource = null` never worked for us. Eventually we figured out that the control itself was the culprit. 
If it helps anyone, it used to happen when we were resetting the navigation stack (via absolute navigation) or going back from the page which had that syncfusion listview control.
