### ISSUE TITLE
[Enhancement] Use the recommended DryIoc extension method for configuration

### ISSUE THREAD

**Issue by bmarinov** [PrismLibrary/Prism#2121]
## Summary

Currently the default Rules for the DryIoc container use a method that is going to be eventually deprecated. According a [comment on bitbucket](https://bitbucket.org/dadhi/dryioc/issues/480/dryiocmicrosoftdependencyinjection#comment-37305577) the method was supposed to be removed one major version ago. My guess is that the author forgot about that.

(1) The method in question: `WithAutoConcreteTypeResolution`
(2) Should be replaced with: `WithConcreteTypeDynamicRegistrations`
A [comment](https://github.com/dadhi/DryIoc/blob/master/src/DryIoc/Container.cs#L5502) on (1) also indicates that (2) is supposed to replace it.

## Changes

The `DefaultRules` would look like that after the change:

```c#
// DryIocContainerExtension.cs
public static Rules DefaultRules => Rules.Default.WithConcreteTypeDynamicRegistrations()
                                                    .With(Made.Of(FactoryMethod.ConstructorWithResolvableArguments))
                                                    .WithFuncAndLazyWithoutRegistration()
                                                    .WithTrackingDisposableTransients()
                                                    .WithoutFastExpressionCompiler()
                                                    .WithDefaultIfAlreadyRegistered(IfAlreadyRegistered.Replace);
```

All Prism tests are green after the change. I also tried the rules in our application and changing one method with the other did not have any (visible) side effects. 

## PR

I was going to submit a tiny PR, but in your contributing guidelines you have explicitly stated that I should start with an issue. Also im not sure if we need some integration tests that check if prism services can get resolved. I've added such tests for our application so I could do the same for Prism, but I would need a bit of guidance (where / what should I test and where does the test belong).

Regards!

**Comment by dansiegel** [comment]
Thanks for opening an issue @bmarinov... generally speaking I'm not opposed to updating to use non-obsolete methods. We don't currently get an obsolete warning on this and that comment seems to be from a few years ago.

@dadhi can you shed any light on this?

**Comment by dadhi** [comment]
Hi, regarding the `WithAutoConcreteTypeResolution`, yes it is  deprecated but I was rather conservative to remove it completely. I suggest to switch to `WithConcreteTypeDynamicRegistrations` so I would have more reasons to drop it in V5.

Also regarding the `WithoutFastExpressionCompiler`, it is not obsolete yet, but it will be in V5.

**Comment by dansiegel** [comment]
@bmarinov feel free to submit a PR to update from the deprecated API's

**Comment by bmarinov** [comment]
Closing the issue since #2122 got merged. :)
