### ISSUE TITLE
How can the Autofac module of ABP vNext be injected into the Di of prism?

### ISSUE THREAD

**Issue by LostAsk** [PrismLibrary/Prism#2126]
How can the Autofac module of ABP vNext be injected into the Di of prism?

**Comment by dansiegel** [comment]
@LostAsk as was indicated in our issue templates we do not answer questions in GitHub issues, they belong on StackOverflow.

Also note Autofac is NOT supported by the Prism team as we require a mutable container for Modularity and the Autofac team made the decision to change the container to be immutable.
