### ISSUE TITLE
[Bug] Xamarin.Forms:[UWP] "OnNavigatedTo" method is not called when switching pages inside TabbedPage

### ISSUE THREAD

**Issue by vardansargsyan92** [PrismLibrary/Prism#2128]
### Description

Hi folks. 

I have an issue regarding the Prism library. I have created a sample which you can see [here](https://github.com/vardansargsyan92/PrismSample).I have a tabbed page (RootTabbedPage) that has 4 pages(MyMasterPage, Page1, Page2, Page3), one of them is master details page(MyMasterPage: Master -> MyMasterPageMaster, Detail -> MainPage ). Each of the child pages of the tabbed page has its view model which implements INavigationAware interface. During creating the sample I have faced up two bugs and would be happy if they will be fixed. I have created an infinite loop inside the Tabbed page (RootTabbedPage) and change the current page every second. 

This issue found on UWP/IOS.

1. The OnNavigatedTo method is not called when I change the current page of the Tabbed page.
2. OnNavigatedTo method is not called for detail page inside the master details page.

### Steps to Reproduce

1. Open the app.
2. Put breakpoints on OnNavigatedTo methods inside view models.
3. Debug the app 

### Expected Behavior

**Scenario: Switching current page inside a tabbed page**
**Given:** I have run the app
**And:** The app is running and I have navigated to a tabbed page
**And:** I have set the current page to one of its children pages
**And:** The corresponding OnNavigated method is called
**When:** I change the current page again
**Then:** The OnNavigatedTo method for the current page should be invoked

### Actual Behavior

**Scenario: Switching current page inside a tabbed page**
**Given:** I have run the app
**And:** The app is running and I have navigated to a tabbed page
**And:** I have set the current page to one of its children pages
**And:** The corresponding OnNavigated method is called
**When:** I change the current page again
**Then:** The OnNavigatedTo method for the current page **is not**  invoked

### Basic Information

- Version with issue:
- Prism: 7.2.0.1422
- Xamarin.Forms version: 4.6.0.800
- IDE: Microsoft Visual Studio

### Screenshots

N/A

### Reproduction Link

[Sample](https://github.com/vardansargsyan92/PrismSample)

**Comment by dansiegel** [comment]
This is not a bug, and is working as designed. Changing tabs is not considered Navigation.

**Comment by vardansargsyan92** [comment]
So when I set the current page in the tabbed page for the first time the OnNavigatedTo method (for the current page) is called but when I change the current page again it is not called anymore. And it's working as designed?  It's strange to me.

**Comment by brianlagunas** [comment]
@vardansargsyan92 you are initially navigating to the TabbedPage, which has an initial tab selected, that is the target of a navigation operation. In this case you did indeed navigate to the TabbedPage and it's current selected tab. Selecting a tab is not navigation. Not even in a normal XF application.

**Comment by vardansargsyan92** [comment]
@brianlagunas thank you for your response.
