### ISSUE TITLE
[Bug] Link to Prism.Uno Nuget package points to Prism.Forms

### ISSUE THREAD

**Issue by MikelThief** [PrismLibrary/Prism#2130]
### Description

As in the title, under 'Core packages' we have a table with links to Nuget packages. Prism.Uno is point to Prism.Forms, but it should not.

### Steps to Reproduce

1. Enter Prism.Uno link to Nuget

### Expected Behavior

Points to https://www.nuget.org/packages/Prism.Uno/

### Actual Behavior

Points to https://www.nuget.org/packages/Prism.Forms/

**Comment by dansiegel** [comment]
@MikelThief feel free to submit a PR to fix broken links in the ReadMe :)
