### ISSUE TITLE
[Bug] iOS soft keyboard shows when using DialogService to display a dialog

### ISSUE THREAD

**Issue by sam-piper** [PrismLibrary/Prism#2131]
### Description
I'm using the DialogService to display a custom dialog from a login page that has multiple Entry fields. If an Entry has been used at least once, then on iOS only, displaying the dialog causes the soft keyboard to popup again (this doesn't occur on Android). 

### Steps to Reproduce

1. Pull and run the code using an iOS simulator or device
2. Tap Show Dialog, note that a dialog displays, no keyboard issues
3. Enter some text in the Entry, then dismiss the keyboard
4. Tap the Show Dialog button again

### Expected Behavior
I can edit text in the Entry, and show dialog without keyboard showing up again.

### Actual Behavior
After entering text in the Entry control, showing the dialog also shows the keyboard again after it has been dismissed, which is not desired.

### Basic Information

- Version with issue: 7.2.0.1422
- Last known good version: N/A
- Xamarin.Forms version: 4.6.0.800
- IDE: Visual Studio 2019 (16.5.4)

### Reproduction Link
https://github.com/sam-piper/prism-dialog-keyboard-issue

**Comment by dansiegel** [comment]
Prism has no control over the platform. Your issue is with Xamarin.Forms
