### ISSUE TITLE
Naming convention violated with 

### ISSUE THREAD

**Issue by janschreier** [PrismLibrary/Prism#2134]
Hi Brian, hi Dan
I just had a look into https://github.com/PrismLibrary/Prism/blob/master/src/Wpf/Prism.Wpf/Regions/Behaviors/IDestructibleRegionBehavior.cs and think it might be good to rename it to DestructibleRegionBehavior as it is a class and not an interface. Of course I understand that this behavior is here to execute that interface's method but still it breaks with expectations. take for example https://github.com/PrismLibrary/Prism/blob/master/src/Wpf/Prism.Wpf/Regions/Behaviors/IHostAwareRegionBehavior.cs which is an interface. 

### Expected Behavior
Rename IDestructibleRegionBehavior to DestructibleRegionBehavior

**Comment by brianlagunas** [comment]
Although this is not a bug, that's a good catch. Luckily an easy fix.
