### ISSUE TITLE
[Bug] XamarinForms - NavigationService.GoBackToRootAsync not firing OnNavigatedTo()

### ISSUE THREAD

**Issue by Berdsen** [PrismLibrary/Prism#2135]
### Description
When having a XamarinForms app which has a MasterDetailPage with at least three Navigation Views and using GoBackToRootAsync with NavigationParameters, OnNavigatedTo is not fired in the MainPage. The navigation is done with NavigateAsync(nameof(View1)). The root page is navigated with: NavigateAsync(nameof(MenuPage) + "/" + nameof(NavigationPage) + "/" + nameof(View1));

OnNavigatedTo is neither called in the main root page and also not in the main base view. 

### Steps to Reproduce

1. Create XF MasterDetailPage with prism navigation and three views
2. OnIntitalized route to View1 - (NavigateAsync(nameof(MenuPage) + "/" + nameof(NavigationPage) + "/" + nameof(View1)))
2. Navigate from view 1 to view 2 - (NavigateAsync(nameof(View2))
3. Navigate from view 2 to view 3 - (NavigateAsync(nameof(View3))
4. Navigate from view 3 to view 1 using GoBackToRootAsync()

### Expected Behavior
OnNavigatedTo(INavigationParameters parameters) should have been called

### Actual Behavior
OnNavigatedTo is not called

### Basic Information
- Version with issue: 7.2.0.1422
- Last known good version: unknown
- Xamarin.Forms version: 4.5.0.657
- IDE: Visual Studio 2019

### Reproduction Link
[OnNavigated.zip](https://github.com/PrismLibrary/Prism/files/4752132/OnNavigated.zip)

### Additional Information
Seems to be a problem with the inheritance of a typed base view.
If the views don't inherit from the BaseView<T> then it seems to work.
Add a breakpoint in class BaseViewModel OnNavigatedTo. When GoBackToRootAsync is called, it should also break.

**Comment by brianlagunas** [comment]
This works as expected.  I ran the aspp, navigated to View3, hit the GoBackToRoot button, and my breakpoint on View1ViewModel was hit.

![image](https://user-images.githubusercontent.com/835562/84161400-79fb0b80-aa2c-11ea-9777-9f7df7a1ee6e.png)

Then, if you want to test it firing on your BaseViewModel, simply comment out your overrides and put your breakpoint on the base class. It hits too:

![image](https://user-images.githubusercontent.com/835562/84162079-35bc3b00-aa2d-11ea-8de2-9c21a47dd408.png)

**Comment by Berdsen** [comment]
Hi Brian,
thanks for the fast check and answer. I was a bit in a hurry before, so I unfortunately didn't check the solution correct and missed the base call in the viewmodel, so I set the wrong breakpoint.

I rechecked with my actual code and updated the attached solution, where the breakpoint don't get hit. Can you please check this solution again? I promise, if it works I won't give it another try :)

[OnNavigated.zip](https://github.com/PrismLibrary/Prism/files/4753566/OnNavigated.zip)

**Comment by brianlagunas** [comment]
To find your problem, you just have to check the result of the navigation call.
```
NextCommand = new DelegateCommand(async () =>
{
    var result = await this.navService.GoBackToRootAsync();
    if (!result.Success)
    {
        var ex = result.Exception;
    }
});
```
You'll see you are throwing a NullReferenceExcption in View3. Which will then lead you to this line of code:
```
        protected override void OnBindingContextChanged()
        {
            base.OnBindingContextChanged();

            this.Title = this.ViewModel.Title;
        }
```
See the problem?

**Comment by Berdsen** [comment]
@brianlagunas 
I'm sorry for bothering you with such a stupid mistake. I didn't checked the result, because the navigation succeeded and didn't thought of the possibility to get this result. Thanks for pointing me to the error. 

Keep up the good work with and thanks again.
