### ISSUE TITLE
[Bug] Failed to emit module when do not include Interface in Prism.Ioc Resolve

### ISSUE THREAD

**Issue by OzBob** [PrismLibrary/Prism#2137]
### Steps to Reproduce

```
    public interface IRegistrator
    {
        bool GetImpl();
    }

    public class Registrator : IRegistrator
    {
        private IContainerProvider _containerProvider;

        public Registrator(IContainerProvider containerProvider)
        {
            _containerProvider = containerProvider;

        }
        public bool GetImpl()
        {
            //oops missed out the interface
            return _containerProvider.Resolve<>();

        }
    }
```

1. New Blank Prism netcoreapp3.0 app
2. using the Prism.IOC Reslove generic function
3. when forget to specify an Interface in container.Resolve<>();
4. the VS build system reports "error CS7038: Failed to emit module... : Unable to determine specific cause of the failure."

### Expected Behavior

Build Error added to the VS Error List, line numbers included in error.

Unity has a related error which is also only identified at run time, but this one resolves to the correct class and line number when double clicking on the error in the VS output window:

```
    Unity.IUnityContainer container = new Unity.UnityContainer();
    var r = container.Resolve<>();
```

App.xaml.cs(22,17,22,42): error CS7003: Unexpected use of an unbound generic name

### Actual Behavior

CSC : error CS7038: Failed to emit module 'FailedToEmit': Unable to determine specific cause of the failure. 

### Basic Information

- Version with issue: Prism.Unity 7.2.0.1422
- Last known good version: unknown
- Xamarin.Forms version:na
- IDE:VS2019 v16.6.2

### Reproduction Link
Zip attached

[FailedToEmit.zip](https://github.com/PrismLibrary/Prism/files/4762529/FailedToEmit.zip)

**Comment by brianlagunas** [comment]
Actually, Unity and the Prism.IoC abstraction behave the exact same way. You are comparing different code snippets.

```
    Unity.IUnityContainer container = new Unity.UnityContainer();
    var r = container.Resolve<>();
```
behaves the exact way as 
```
var r =  _containerProvider.Resolve<>();
```

Plus, Prism has no control over the error list and its interactions
