### ISSUE TITLE
Raising InteractionRequests when CompositeCommand fired

### ISSUE THREAD

**Issue by WillEllis** [PrismLibrary/Prism#214]
This is a question potentially not an issue as such so I don't know if this is the place for it. I also posted it here:
http://compositewpf.codeplex.com/discussions/646111

-----------------
Hi, 

I have a scenario where I have multiple views registered in a window with one view active at a time. 

I am using a CompositeCommand when the window is closing to validate the close can occur, with each view registering a command with that composite command. 

The composite command works as expected, but my problem is that some of the views need to raise an interaction request to allow the user to confirm they want the window to close without fixing validation issues on those views. 

To do this some of the views have interaction requests which they trigger when their command fires and then need user confirmation. 

The issue that I'm having is that if the view isn't the currently active view then the interactionrequest cannot fire as either the Raised event becomes null or an exception of "This Visual is not connected to a PresentationSource" is thrown. 

I have tried to implement an activation of the view that wants to raise an interaction request but because the composite command is executing synchronously the view cannot be activated before the interaction request needs to fire. 

Am I going about implementing this wrong? Or getting the interaction request to not throw? 

Thanks!

**Comment by brianlagunas** [comment]
You're right, this isn't an issue, but you're really looking for advice on how to approach this scenario.  Please post this question here:

http://stackoverflow.com/questions/tagged/prism

**Comment by WillEllis** [comment]
Thanks, raised it here 
http://stackoverflow.com/questions/33084401/raising-interactionrequests-when-compositecommand-fired-wpf-prism
