### ISSUE TITLE
[Bug] Inconsistent behavior without AutowireViewModel 

### ISSUE THREAD

**Issue by AwsomeCode** [PrismLibrary/Prism#2140]
### Description

I have create new project where MainPage.xaml does not have AutowireViewModel.
Xaml to ViewModel Bindings working fine. But If i try to access ViewModel in ctor of xaml.cs its not accessible.

If I explicitly define AutowireViewModel to true in MainPage.xaml. ViewModel is accessible at ctor of xaml.cs

![image](https://user-images.githubusercontent.com/11809653/84566075-f757b080-ad8b-11ea-8022-e1365a45149b.png)

### Basic Information

- Version with issue: 7.2.0.1422
- Last known good version:
- Xamarin.Forms version: 4.6.0.847
- IDE: VS2019 16.7 p2

**Comment by dansiegel** [comment]
This is not a bug, this has to do with order of operations. If you do not explicitly set the ViewModelLocator and then the Navigation Service will AFTER the ctor has finished. If it is explicitly set in XAML then the Binding Context would be set after InitializeComponent has been called.
