### ISSUE TITLE
[Bug] TabControl with region, modal dialog and IActiveAware selects previous tab

### ISSUE THREAD

**Issue by erikbarke** [PrismLibrary/Prism#2141]
### Description

A `TabControl` with tabs rendered using a Prism region selects the previously selected tab if a modal dialog is shown when the `IActiveAware.IsActiveChanged` event handler is triggered.

The selected tab stays selected until the modal dialog is closed and then the TabControl immediately selects the previously selected tab.

This happens with the built-in Prism `IDialogService` and the [Material Design In Xaml DialogHost](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/wiki/Dialogs).

### Steps to Reproduce

1: Unzip and run either repro example using Visual Studio 2019
2. Click tab "B"
3. Click tab "A"
4. Close the dialog
5. The TabControl switches back to tab "B"

### Expected Behavior
The TabControl should stay on the selected tab

### Actual Behavior
The TabControl switches back to the previously selected tab

### Basic Information
- Version with issue: Prism 7.2.0.1422
- IDE: Visual Studio 2019

### Reproduction Link
Repro using the Material Design In Xaml dialog host:
[PrismVsMdix.zip](https://github.com/PrismLibrary/Prism/files/4819033/PrismVsMdix.zip)

Repro using the Prism dialog service:
[PrismVsPrism.zip](https://github.com/PrismLibrary/Prism/files/4819034/PrismVsPrism.zip)

**Comment by brianlagunas** [comment]
This is not a bug in Prism. This is an issue with the TabControl. The TabControl is selecting TabB automatically after showing a window. Prism simply responds to this selection change.

You can test this by using a basic TabControl and handling the SelectionChanged event:

```
        <TabControl SelectionChanged="TabControl_SelectionChanged">
            <TabItem Header="Tab A" >
                <TextBlock Text="A" HorizontalAlignment="Center" VerticalAlignment="Center" />
            </TabItem>
            <TabItem Header="Tab B" >
                <TextBlock Text="B" HorizontalAlignment="Center" VerticalAlignment="Center" />
            </TabItem>
            <TabItem Header="Tab C" >
                <TextBlock Text="C" HorizontalAlignment="Center" VerticalAlignment="Center" />
            </TabItem>
        </TabControl>
```

```
        private void TabControl_SelectionChanged(object sender, SelectionChangedEventArgs e)
        {
            var tc = sender as TabControl;
            if (tc.SelectedIndex == 0)
            {
                Window win = new Window() { Height = 250, Width = 450 };
                win.Show();
            }
        }
```

**Comment by erikbarke** [comment]
Of course, the TabControl itself is broken... Back to the drawing board, thanks for the fast reply ☺️
