### ISSUE TITLE
[Bug] Ambiguity between 'Resource.Layout.Tabbar(Toolbar) and Resource.Layout.Tabbar(Toolbar)'

### ISSUE THREAD

**Issue by wsigel** [PrismLibrary/Prism#2142]
### Description
Even when creating an empty Prism project I get the error message mentioned above in MainActivity.cs.
For comparison I've created a blank xamarin.forms app and here the problem with the Tabbar/Toolbar doesn't
show up.

### Steps to Reproduce

1.  create new prism blank app with the vs template
2.  set android as the starting project
3.  run the app

### Expected Behavior
- display 'Welcome to Xamarin Forms and Prism!'

### Actual Behavior
- Android.Views.InflationException: 'Binary XML file line #1: Binary XML file line #1: Error inflating class androidx.appcompat.widget.Toolbar' is thrown (see image)

### Basic Information

- Version with issue: Prism Template Pack Version 2.2.1
- Last known good version: -
- Xamarin.Forms version: 4.7.0.968
- IDE: Microsoft Visual Studio Community 2019 Version 16.6.2

### Screenshots

![image](https://user-images.githubusercontent.com/10357745/85723589-acc32600-b6f3-11ea-85a5-e584f482c695.png)

### Reproduction Link

The sample can be found here: [https://github.com/wsigel/PrismError](https://github.com/wsigel/PrismError)

**Comment by brianlagunas** [comment]
Try adding this to the csproj and let me know if it works
```
<AndroidUseManagedDesignTimeResourceGenerator>False</AndroidUseManagedDesignTimeResourceGenerator>
```

**Comment by wsigel** [comment]
After adding your suggestion to the csproj file the red squiggles went away but the same exception is thrown (see image):

![PrismException2](https://user-images.githubusercontent.com/10357745/85831707-fa40a100-b78e-11ea-892a-e9e152e6a227.PNG)

**Comment by wsigel** [comment]
By accident I came across another machine today - same OS, IDE, ... and there was no error. There were still the red squiggles but this could be removed the way you had pointed out above. So I suspect the issue is related to my machine and I'll close this.

**Comment by BaseCrusher** [comment]
Encountering the exect same Issue.
I got the same exception wsigel got too. 
The strange thing is, the "InflateException" die only throw after I've added some Unit Test Projects. Before that I could compile the project eventhough the ambiguity was there.

**Comment by brianlagunas** [comment]
@BaseCrusher thanks for the info. There's no telling what the Xamarin team changed tat is causing the issue. I'll take another look when I get a chance

**Comment by dansiegel** [comment]
Note that the Prism Templates are Open Source. Issues with the templates should be filed [there](https://github.com/PrismLibrary/Prism.Templates/issues/new?assignees=&labels=&template=template_issue.md&title=YOUR+IDEA%21).

Even better news is that if there are issues with the Templates, we accept Pull Requests!

**Comment by BaseCrusher** [comment]
> Note that the Prism Templates are Open Source. Issues with the templates should be filed [there](https://github.com/PrismLibrary/Prism.Templates/issues/new?assignees=&labels=&template=template_issue.md&title=YOUR+IDEA%21).
> 
> Even better news is that if there are issues with the Templates, we accept Pull Requests!

Thats good to know, I've made a pull request there. Still I dont believe that the "InflateException" has something to do with the template. I could be wrond though. I'll try to look into it a little.
