### ISSUE TITLE
[Enhancement] Switching between scopes on Prism WPF

### ISSUE THREAD

**Issue by Jesus805** [PrismLibrary/Prism#2148]
I've been playing around with scoping and using multiple shells. From my understanding the only way to set `_currentScope` is to create a new scope. It would be nice to be able to set the scope if a window becomes active.

Example:
Suppose you have 2 shells and you create a child container.
Shell 1 becomes active, set the main `IScopedProvider`.
Shell 2 activates, set the child `IScopedProvider`.
Shell 1 becomes active again, set the main `IScopedProvider`.

**Comment by brianlagunas** [comment]
This is not something that Prism will be responsible for. If you need this behavior, you must implement it yourself.

**Comment by Jesus805** [comment]
@brianlagunas This is not something I can implement since `IContainerExtension.CreateScope()` sets `_currentScope` with the newly created scope and it cannot be changed by any other means

**Comment by brianlagunas** [comment]
@dansiegel will have to comment on this since this was his idea to add 😄

**Comment by Jesus805** [comment]
@brianlagunas do you mind re-opening this issue? I'm afraid that it wont be responded to since it's closed

**Comment by brianlagunas** [comment]
@dansiegel will respond when he gets time. I don't want t reopen because I'm 99% sure this isn't something Prism will provide. The only reason scopes were added is to support the functionality of Prism in Xamarin.Forms. Prism isn't trying to create, or recreate, every container feature. Maybe, just maybe we might provide some mechanism to se the _currentScope variable, but that may have unintended consequences in the functionality of Prism.

**Comment by Jesus805** [comment]
Honestly, the bane of my existence using Prism with multiple shells was not being able to scope my services per child window. Which is why I am really excited that scoping was introduced in Prism 8. I hope Prism WPF can get some love too.

**Comment by brianlagunas** [comment]
If you were to use this feature. What do you think the API would look like? How do you expect to use it?

**Comment by Jesus805** [comment]
I was thinking something along the lines of this:
API:
`IContainerExtension.SetActiveScope(IScopedProvider)`

Use:
When I create a new shell, I call `IContainerExtension.CreateScope()` which returns a `IScopedProvider`, which I will then attach to the newly created shell.

When any shell fires of an `Window.Activated` event, I get the attached IScopeProvider and call `IContainerExtension.SetActiveScope(IScopedProvider)`.

**Comment by dansiegel** [comment]
While I'm not fundamentally opposed to making this topic easier for people to work with, we do want to be careful about what we will and will not do. As @brianlagunas mentioned:

> This is not something that Prism will be responsible for. If you need this behavior, you must implement it yourself.

At the end of the day this just isn't an area that we are really looking to spend any real energy or effort. If this is a business critical issue then I would suggest we talk offline about what paid options may be available for you.

**Comment by Jesus805** [comment]
Again, I have no problem implementing a solution myself since this is a pretty niche problem but I believe I'm blocked by the library. When you call `IContainerExtension.CreateScope()` there is a hidden side effect where `IContainerExtension.CreateScope()` will set `IContainerExtension._currentScope`, so when you resolve anything on any `IContainerExtension` the resolved item will _always_ come from the child scope. 

I am not representing a company, this is a personal project of mine demonstrating how to use Prism with MaterialDesign in XAML
https://github.com/Jesus805/PrismAndMaterialDesign
