### ISSUE TITLE
[Enhancement] ParametersBase.AddOrUpdate

### ISSUE THREAD

**Issue by PieterjanDeClippel** [PrismLibrary/Prism#2149]
## Summary

Provide an `AddOrUpdate` method in the NavigationParameters.

## API Changes

https://github.com/PrismLibrary/Prism/blob/master/src/Prism.Core/Common/ParametersBase.cs

    public abstract class ParametersBase : IEnumerable<KeyValuePair<string, object>>
    {
        public void AddOrUpdate(string key, object newValue)
        {
            if (this.ContainsKey(key))
                this.Remove(key);
            this.Add(key, newValue);
        }
    }

## Intended Use Case

At my work we created a custom class just to implement this.

**Comment by brianlagunas** [comment]
This is not something that we will be adding to Prism.  That doesn't have to be a class, that could have been an extension method.
