### ISSUE TITLE
Wpf Behaviors  Prism add support isn't supporting it just yet.

### ISSUE THREAD

**Issue by alvarogt** [PrismLibrary/Prism#2151]
I'm actually on the WPF Behaviors team. We have been unable to get MS to actually participate in the project so it is moving extremely slow.  I even had a PR for Prism to add support, but MS has been dragging their feet.  Until this project is moved froward, we aren't supporting it just yet.

_Originally posted by @brianlagunas in https://github.com/PrismLibrary/Prism/issues/1804#issuecomment-495239682_

**Comment by brianlagunas** [comment]
Not enough information to understand what the issue is.
