### ISSUE TITLE
IPageDialogService.DisplayAlertAsync does not show alert [Bug] 

### ISSUE THREAD

**Issue by rmgalante** [PrismLibrary/Prism#2152]
### Description
I am trying to upgrade my solution to the latest version of Xamarin Forms. I am using the Prism.Unity.Forms version 7.2.0.1422. The PageDialogService stopped working with Xamarin.Forms version 4.5+. I checked every version of Xamarin.Forms from v 4.7.0.1142 to 4.4.0.981664.

Version 4.4.0.981664 is the last version that shows an alert with this service.

### Steps to Reproduce

1. Load the demo application provided. Install version 4.4.0.981664 of Xamarin Forms. 
2. Run the demo. Click the button, Show Alert.
3. You will see a modal alert with the message, "Increase Xamarin.Forms version past 4.4.0.981664, and this alert will not appear."
4. Stop the demo.
5. Install any version of Xamarin Forms v 4.5+.
6. Run the demo. Click the button, Show Alert.
7. The page goes modal, but the alert does not appear.

### Expected Behavior
The alert should appear.

### Actual Behavior
The alert does not appear.

### Basic Information

- Version with issue: Every Xamarin.Forms version after v 4.4.0.981664
- Last known good version: Xamarin.Forms v 4.4.0.981664
- Xamarin.Unity.Forms version: 7.2.0.1422
[DemoPageDialogServiceBug.zip](https://github.com/PrismLibrary/Prism/files/4948486/DemoPageDialogServiceBug.zip)

- IDE: VS 2019

**Comment by rmgalante** [comment]
It's the UWP app that has the problem.

**Comment by brianlagunas** [comment]
If the IPageDialogService works on Android and iOS, but not UWP, then this is not a Prism issue. Prism uses the XF DisplayAlert method. There is no custom code on Prism's side. It is a simple wrapper around the XF implementation.

Can you confirm is this works on other platforms, just not UWP?

**Comment by rmgalante** [comment]
Yes, this works in iOS and Android. I'll report the issue to the Xamarin.Forms team.
