### ISSUE TITLE
XF - Destroy not called when back button pressed

### ISSUE THREAD

**Issue by being-yash-t** [PrismLibrary/Prism#2153]
@brianlagunas this is already the third time that a report regarding this issue is just closed.
It seems that no one here cares about this problem, so I also don't mind to send a pull request for its fix.

_Originally posted by @StefanStsc in https://github.com/PrismLibrary/Prism/issues/2023#issuecomment-593314078_

This issue is repeating & I have a clean project to prove this bug, I just created a project added a log message in the Destroy method for the viewModel & when I run the app and press back button, the Destroy method is not called.

Note that, when there is a page pushed above the root page, this method is called, but it is not called when the page is the only page open in the app & when the back button is pressed the app will exit, but the destroy function will not be called.

Here is the link for the project: https://drive.google.com/file/d/1D3wlDk1GNrsjIfpn05DeF1IdNduahnYz/view?usp=sharing

**Comment by dansiegel** [comment]
@being-yash-t it would seem that you're trying to use IDestructible in a way that it's purposely not meant to work with. Your sample has a single page, so I can only assume that when you say that:

> when I run the app and press back button, the Destroy method is not called.

What you are referring to here is that you are trying to handle the scenario where your app is being backgrounded and App.OnSleep is being called. IDestructible is not meant to cover this scenario and you should look at IApplicationLifecycleAware.

**Comment by being-yash-t** [comment]
@dansiegel  Thanks for clearing my doubt, I wanted a way to stop the database updated listeners (snapshotListener) when the root page is popped, I also tried NavigationPage.Popped but it is also not executed when root page is popped (When application exits)

I will now use the IApplicationLifecycleAware for root pages, as you understand I am not much experienced, but you are. If you know a "Best Practice" to close data stream/listeners when a root page is popped, please share it. :)

**Comment by thomasgalliker** [comment]
@dansiegel I was running into this problem too. I believed IDestructible can be used to unsubscribe from event handler consistently, so matter if it is used on the root viewmodel. Do you have a best practice approach on how to unsubscribe from events in viewmodels? Would you handle unsubscribes in the root viewmodel differently (e.g. with IApplicationLifecycleAware) than in other viewmodels? Thanks for your thoughts.
