### ISSUE TITLE
DialogService OnDialogOpened invoke time

### ISSUE THREAD

**Issue by kardinalios** [PrismLibrary/Prism#2155]
As title says, with current implementation OnDialogOpened will be invoked before show/showdialog will be called.

I believe that whoever uses DialogService, expects that OnDialogOpened will be processed after DialogWindow will be loaded.

I am not sure if this is a bug or it is the expected behavior, but i think that at least the naming is confusing.

I would like to hear your opinion and if you agree I can make a pr.

Platform: WPF
Version: Latest

**Comment by brianlagunas** [comment]
The OnDialogOpened method is to meant to signify when a dialog has been loaded or rendered on glass. The fact that the technical invocation of the OnDialogOpened method happens before the Show/ShowDialog method is executed is irrelevant. To the developer, all they know is they called Show/ShowDialog, they have the ability to pass parameters before the dialog is rendered to prevent unnecessary binding refreshes, and the dialog opens.

Thank for asking.
