### ISSUE TITLE
[Enhancement] Add tabs to tabbed page using its ViewModel

### ISSUE THREAD

**Issue by BaseCrusher** [PrismLibrary/Prism#2156]
## Summary

It would be nice to have the option to add tabs to the tabbed page in its corresponding ViewModel. In my opinion it's a litle bin more clear when reading the code. Many apps use tabbed pages as their initial view and I find it unintuitive that you have to add them in your App.cs.

## API Changes

There is already the namespace Prism.Navigation.TabbedPages, that adds functionality to the NavigationService. So the method could be added there.

// Only the tab
_navigationService.AddTabAsync("MyTab");

// Or with navigation page
_navigationService.AddTabAsync("NavigationPage|MyTab"); 

## Intended Use Case

Instead of adding tabs in the initial navigation, you could do this in the the TabbedPageViewModel. This would also enable to add Pages when already displaying the TabbedPage.

**Comment by brianlagunas** [comment]
Thank you for the the suggestion. However, this is not something we will be adding to Prism as there are rendering issues in XF when dealing with dynamically creating and adding a NavigationPage to the TabbedPage.Children collection.  For now, you can use this extension method to achieve your request.

```
    public static class INavigationServiceExtensions
    {
        public async static Task AddTabAsync(this INavigationService navigationService, string name,
            INavigationParameters parameters = null)
        {
            TabbedPage tabbedPage = null;
            var currentPage = ((IPageAware)navigationService).Page;

            if (currentPage is TabbedPage tPage)
            {
                tabbedPage = tPage;
            }
            else if (currentPage.Parent is TabbedPage parent)
            {
                tabbedPage = parent;
            }
            else if (currentPage.Parent is NavigationPage navPage)
            {
                if (navPage.Parent != null && navPage.Parent is TabbedPage parent2)
                {
                    tabbedPage = parent2;
                }
            }

            ContainerLocator.Container.CreateScope();

            var newTab = ContainerLocator.Container.Resolve<object>(name) as Page;

            var autowire = ViewModelLocator.GetAutowireViewModel(newTab);
            if (!autowire.Value)
                ViewModelLocator.SetAutowireViewModel(newTab, true);

            await PageUtilities.OnInitializedAsync(newTab, parameters);

            tabbedPage.Children.Add(newTab);
            tabbedPage.CurrentPage = newTab;
        }
    }
```

note: make sure you upgrade to Prism v8 in order to use the `ContainerLocator`. Otherwise you'll have to expose it yourself.

**Comment by BaseCrusher** [comment]
Thank you very much for your reaply. I'll try it out.
