### ISSUE TITLE
[Bug] NavigateAsync broken the binding properties on the previous page

### ISSUE THREAD

**Issue by enephiel** [PrismLibrary/Prism#2157]
### Description
Execute NavigateAsync, the display of the previous page will be broken for a moment.
Occurs when using "/Navigationpage/hogePage" to reset the navigation stack.
Only controls that use binding properties are broken.
It happens on Android, but works fine on iOS.

### Steps to Reproduce

1. Binding Page1ViewModel property to Page1 control
`<Button Text="{Binding HogeText.Value}" BackgroundColor="{Binding HogeColor.Value}" />`

2. Reset the navigation stack
`await navigationService.NavigateAsync("/NavigationPage/Page2");`

### Expected Behavior
The Button on Page1 will be broken for a moment.

### Actual Behavior
The Button on Page1 is displayed fine.

### Basic Information
- Version with issue: 7.2.0.1422
- Last known good version: Unkown
- Xamarin.Forms version: 4.7.0.1260
- IDE: Visual Studio 2019

### Screenshots
![sample_prism_001](https://user-images.githubusercontent.com/69282723/89519000-ace83280-d816-11ea-82ce-a4387ecbcf0d.gif)

### Reproduction Link
https://github.com/enephiel/sample-prism-001.git

**Comment by dansiegel** [comment]
I'm not sure what you mean by "Broken". If you're looking for the button to be disabled then you need to set the CanExecute on your command so that it will be false while the command is executing.

**Comment by enephiel** [comment]
The text on the "!!! BINDED !!!" button in the image disappears when NavigationAsync is executed.
The background color is also gone.
It does not disable the button.
Since the above button that does not use "Binding" has no problem, I suspect that the BindingContext has been deleted.
