### ISSUE TITLE
Assembly Xamrinform.Android.Support.Annotations is using a deprecated attribute

### ISSUE THREAD

**Issue by batongprodt** [PrismLibrary/Prism#2160]
Assembly Xamrinform.Android.Support.Annotations is using a deprecated attribute

i use visual studio 2019 xamarinform 4.8

Link Image
https://ibb.co/gv31GS2

**Comment by dansiegel** [comment]
This is not an issue with Prism. We don't have any explicit Android support references, they all come from Xamarin.Forms
