### ISSUE TITLE
[Bug] Navigation with the same view name as other Modules

### ISSUE THREAD

**Issue by BradJeong** [PrismLibrary/Prism#2161]
### Steps to Reproduce
I modified the BasicRegionNavigation Project of Prism Sample. 
1. ContentRegion was separated as ContentRegionLeft and ContentRegionRight in MainWIndow.xml.
2. Button for ModuleA and ModuleB was added in MainWIndow.xml.
3. ViewC and ViewD added in ModuleA.
4. ModuleB was added.
5. ViewA and ViewB added in ModuleB.

### Expected Behavior
if ViewB Button of ModuleA is pushed, It is expected that ViewB of ModuleA is displayed. 

### Actual Behavior
ViewB of ModuleB is displayed. 

### Basic Information
if ModuleA has the same view name as ModuleB, View of ModuleB is displayed.
In OnInitialized of ModuleA, I added like this:
        public void OnInitialized(IContainerProvider containerProvider)
        {
            //View will be displaed as Default. 
            var regionManager = containerProvider.Resolve<IRegionManager>();
            regionManager.RequestNavigate("ContentRegionLeft", "ViewB");
            regionManager.RequestNavigate("ContentRegionLeft", "ViewA");
        }
And then, Even if View Name of ModuleA is the same as the one of ModuleB,
it is navigated correctly. 

- Version with issue: Prism.Wpf 7.2.0.1367
- Last known good version:
- Xamarin.Forms version:
- IDE: Visual Studio 2019

### Screenshots
![image](https://user-images.githubusercontent.com/13713012/90082100-eacee480-dd49-11ea-89d8-2bc95c2dd4b9.png)
![image](https://user-images.githubusercontent.com/13713012/90082683-69785180-dd4b-11ea-9ac8-e73f923ebe78.png)

**Comment by brianlagunas** [comment]
This is not a bug. YOu are trying to register views with the same name. The name of the view must be unique. You can't register a view using the key "ViewB" in both ModuleA and ModuleB. Provide a unique key during registration.

Also, I usually immediately close issues with no reproduction app.

**Comment by BradJeong** [comment]
OK. the name of views must be UNIQUE. That is the specification.
But, It would be nice to have an exception handling(?) to avoid malfunctioning.

**Comment by brianlagunas** [comment]
there can be no exceptions thrown during view registration, because sometime you do that on purpose. You just have to know that navigation keys must be unique
