### ISSUE TITLE
[Breaking] Remove Legacy Bootstrapper

### ISSUE THREAD

**Issue by brianlagunas** [PrismLibrary/Prism#2177]
## Summary

Remove the legacy UnityBootsrapper and DryIocBootstrapper classes from Prism for WPF.

## API Changes

Anyone using the legacy bootstrapper will need to modify their code to use the new PrismBootstrapper class that is available for both Unity and DryIoC.

The new bootstrapper API aligns with the PrismApplication class and takes advantage of the new features that have been added to Prism over the last year.

**Comment by dansiegel** [comment]
closed via #2178
