### ISSUE TITLE
[Enhancement] Add Module list as property of IModuleManager

### ISSUE THREAD

**Issue by dansiegel** [PrismLibrary/Prism#2179]
## Summary

Prism previously introduced a number of great extensions off of the IModuleCatalog to check if a Module exists, or is initialized, however in order to validate the current state of a module you must inject both the IModuleManager and IModuleCatalog, since it is likely that in this scenario you want to load a module if it hasn't been initialized.

## API Changes

We would be updating the IModuleManager to include a new property:

```cs
public interface IModuleManager
{
    IEnumerable<IModuleInfo> Modules { get; }
}

public class ModuleManager : IModuleManager
{
    // Existing
    protected IModuleCatalog ModuleCatalog { get; }

    // New
    public IEnumerable<IModuleInfo> Modules => ModuleCatalog.Modules;
}
```

This then allows us to bring some of the extensions we have on the IModuleCatalog over to the IModuleManager to make it easier to work with as we only need to work with a single dependency directly.

Add Extensions for the IModuleManager:

- bool ModuleExists<TModule>()
- bool ModuleExists(string name)
- ModuleState GetModuleState<TModule>()
- ModuleState GetModuleState(string name)
- bool IsModuleInitialized<TModule>()
- bool IsModuleInitialized(string name)
- void LoadModule<TModule>()

Add Extensions for IModuleCatalog

- ModuleState GetModuleState<TModule>()
- ModuleState GetModuleState(string name)

## Intended Use Case

```cs
public void Current()
{
    if(_managerCatalog.Exists<SomeModule>() && !_managerCatalog.IsInitialized<SomeModule>())
    {
        _manager.LoadModule("SomeModule");
    }
}

public void Proposed()
{
    if(_manager.ModuleExists<SomeModule>() && !_manager.IsModuleInitialized<SomeModule>())
    {
        _manager.LoadModule<SomeModule>();
    }
}
```

**Comment by brianlagunas** [comment]
I like it. Ideally, you only care about the IModuleManager and would never need to inject the IModuleCatalog
