### ISSUE TITLE
[Enhancement] Register the same dialog view with multiple iterations of a Generic view model

### ISSUE THREAD

**Issue by narrsam** [PrismLibrary/Prism#2186]
## Summary

In an attempt to make a reusable dialog that shows a list of items I tried to make a generic view model that takes a class of <T> as an identifier and registered 2 dialogs  with custom names and different T types for the view models, but  it seems that the dialog is being registered only once and the 2nd registration always wins.
It would be nice if I could have these registrations both work say for a dialog showing a list of strings and another showing a list of persons without having to create separate user controls for each.
Not sure if there is another way of doing this in Prism, if not, this could be a nice feature to have.

e.g.

see the attached project for the suggested implementation.
[BlankApp1.zip](https://github.com/PrismLibrary/Prism/files/5157676/BlankApp1.zip)

**Comment by brianlagunas** [comment]
This is not something that will be, or can be, supported. You need to rethink the design of your VM for a single Dialog to represent many different list types.
