### ISSUE TITLE
[Bug] BindableBase.SetProperty: Date property doesn't change when specifying different DateTimeKind

### ISSUE THREAD

**Issue by InquisitorJax** [PrismLibrary/Prism#2187]
### Description

not sure if this is a bug or not, but the equality comparer will return false for the use case of changing the DateTimKind of a DateTime property, but retaining the original ticks value.

eg. where Model inherits from BindableBase, and uses SetProperty in the setter of the Date property:
Model.Date = DateTime.Now;
Model.Date = DateTime.SpecifyKind(Model.Date, DateTimeKind.Utc); //Model.Date is still local kind - the change was not assigned.

**Comment by brianlagunas** [comment]
This has nothing to do with Prism. As long as the value of the property changes, then BindableBase will invoke INPC. If the value doesn't change it won't. You'll need to find out why the value isn't changing.

**Comment by Pretasoc** [comment]
@InquisitorJax The `DateTime` implementation does only compare the internal ticks, not the kind as you can see [here](https://referencesource.microsoft.com/#mscorlib/system/datetime.cs,df6b1eba7461813b).

You could solve the issue, by overwriting `SetProperty<T>` in `BindableBase` to use an other `IEqualityComparer<DateTime>`.
