### ISSUE TITLE
Prism 7.2 vs Prism-7.2.0.1422  - src\Wpf\Prism.Wpf complete folders and files missing

### ISSUE THREAD

**Issue by stevensrf11** [PrismLibrary/Prism#2188]
I cloned from GutHub Prism-7.2.0.1422.
 When comparing that source code to a previous version of 7.2 in the src\Wpf\Prism.Wpf folder, Prism-7.2.0.142 is missing complete folders, and files from folder that version 7.2 had. 
This does make any sense. I can expect complete changes say from version 7 to version 8, but complete changes in the same hive?
The logging folder that was present in version 7.2 is completely gone from version -7.2.0.142. 
The registering of logging was also removed  from RegisterRequiredTypes method in version version -7.2.0.142. 
In the Extensions folder ExceptionExtensions.cs was removed in version -7.2.0.142.
The Events directory was also removed in version -7.2.0.142.
The containerRegistry.RegisterSingleton<ILoggerFacade, TextLogger>(); was removed from regesitering..
I search all of version -7.2.0.142. and did not find ILoggerFacade anywhere.
So does this mean everytime a change in the same version is accomplished, and checked in I can expect complete changes in directory structures with breakage in common objects used?
This is the first time since Prism 4.0 I have seen ILoggerFacade removed along with the two classes derived from it.
And image is attach showing come folder changes.
 internal static void RegisterRequiredTypes(this IContainerRegistry containerRegistry, IModuleCatalog moduleCatalog)
        {
            containerRegistry.RegisterInstance(moduleCatalog);
            containerRegistry.RegisterSingleton<IDialogService, DialogService>();
            containerRegistry.RegisterSingleton<IModuleInitializer, ModuleInitializer>();
            containerRegistry.RegisterSingleton<IModuleManager, ModuleManager>();
            containerRegistry.RegisterSingleton<RegionAdapterMappings>();
            containerRegistry.RegisterSingleton<IRegionManager, RegionManager>();
            containerRegistry.RegisterSingleton<IRegionNavigationContentLoader, RegionNavigationContentLoader>();
            containerRegistry.RegisterSingleton<IEventAggregator, EventAggregator>();
            containerRegistry.RegisterSingleton<IRegionViewRegistry, RegionViewRegistry>();
            containerRegistry.RegisterSingleton<IRegionBehaviorFactory, RegionBehaviorFactory>();
            containerRegistry.Register<IRegionNavigationJournalEntry, RegionNavigationJournalEntry>();
            containerRegistry.Register<IRegionNavigationJournal, RegionNavigationJournal>();
            containerRegistry.Register<IRegionNavigationService, RegionNavigationService>();
            containerRegistry.Register<IDialogWindow, DialogWindow>(); //default dialog host
        }

The two version are shown in the attached image.
![aa](https://user-images.githubusercontent.com/22349374/91930915-a6c76380-eca7-11ea-8dbb-498f84abca2f.png)

**Comment by stevensrf11** [comment]
Below is the progression of the file structure changes as I found on git hub.
11 days ago the Event folder is not longer present.
8 days agp the Logging folder is not longer present.
Looks like the Bootstrapper.cs folder was removed 8 days ago and 11 days ago PrismInitializtionExtension.cs file shows up in the root directory.
![aa](https://user-images.githubusercontent.com/22349374/91932150-f2c7d780-ecaa-11ea-9689-4bdc8bf71ff0.png)

**Comment by stevensrf11** [comment]
The source available on Github for  version -7.2.0.142 , and the source code shown in the version obtain via a nuget package do not match.
In the attached image the source code obtain via a nuget package does contain the logging and event folders which was obtain via reflector.
In the attached image also is shown version -7.2.0.142 source code available on GitHub in the master some 8 days old.
![aa](https://user-images.githubusercontent.com/22349374/91933028-8d291a80-ecad-11ea-9e01-01e4b0a82037.png)

**Comment by stevensrf11** [comment]
One more thing I have to use CommonServiceLocator 2.0.5 when creating Prism applications and modules when coding against the Prism source code off GitHub. For some reason if I use 2.0.4 version I get some error saying the ServiceLocator is not set. When I use version 2.0.5 the error does not appear, and the service locator works fine. I saw version 2.0.4 is used when using nuget to obtain the Prism packages,

**Comment by dansiegel** [comment]
There is no bug here. Prism 8 has a lot of changes which you can see in the release notes. Some things like the ILoggerFacade were removed in the latest preview. Other things like some of the event helpers were consolidated to the Prism.Core. If you have questions like this they belong on StackOverflow, Prism Slack or the Sponsor Discord.

**Comment by stevensrf11** [comment]
Oh I was in error on version. Master is Prism 8
Ok thanks
