### ISSUE TITLE
[Enhancement] add a `Task PageClosed` property to `INavigationResult` 

### ISSUE THREAD

**Issue by roubachof** [PrismLibrary/Prism#2190]
## Summary

Add a Task PageClosed property to `INavigationResult` for awaiting a page to be closed. 

## API Changes

    public interface INavigationResult
    {
        bool Success { get; }

        Exception Exception { get; }

        Task PageClosed { get; }
    }

## Intended Use Case

Doing so we could create page controllers to manage some specific workflow.
For example when initializing our app:

```csharp
protected override async void OnInitialized()
{
    InitializeComponent();

    var userService = ServiceLocator.GetInstance<IUserService>();
    if (!userService.IsLoggedIn)
    {
        await NavigationService.NavigateAsync("LoginPage").PageClosed;
    }

    var referentialService = ServiceLocator.GetInstance<IReferentialService>();
    if (!referentialService.IsInitialized)
    {
        await NavigationService.NavigateAsync("FirstLaunchPage").PageClosed;
    }

    await NavigationService.NavigateAsync("NavigationPage/MainPage");
}
```

**Comment by brianlagunas** [comment]
Thank you for your feature request. Unfortunately, this is not something we will be adding to Prism.
