### ISSUE TITLE
[Bug] [Xamarin.Forms UWP] dismissing IDialogService dialog causes debug console output that suggests something bad

### ISSUE THREAD

**Issue by jmegner** [PrismLibrary/Prism#2193]
### Description

Dismissing a dialog created from IDialogService.ShowDialog causes debug console output that suggests something not-quite-right is being done.  Here's an example of the debug console output:

`Element: Xamarin.Forms.StackLayout is already a child of Prism.Services.Dialogs.DialogContainer. Remove Xamarin.Forms.StackLayout from Prism.Services.Dialogs.DialogContainer before adding to PrismSample.Views.PassingParametersPage.`

### Steps to Reproduce

1. Launch the UWP project of the Prism-Samples-Forms's [07-DialogService](https://github.com/PrismLibrary/Prism-Samples-Forms/tree/master/07-DialogService) sample solution 
2. Launch and dismiss all 5 sample dialogs in order.
3. Look at the debug console output.  You'll find the lines below, one per dialog dismissal.

```
Element: Xamarin.Forms.StackLayout is already a child of Prism.Services.Dialogs.DialogContainer. Remove Xamarin.Forms.StackLayout from Prism.Services.Dialogs.DialogContainer before adding to PrismSample.Views.PassingParametersPage.
Element: Xamarin.Forms.TableView is already a child of Prism.Services.Dialogs.DialogContainer. Remove Xamarin.Forms.TableView from Prism.Services.Dialogs.DialogContainer before adding to PrismSample.Views.MainPage.
Element: Xamarin.Forms.TableView is already a child of Prism.Services.Dialogs.DialogContainer. Remove Xamarin.Forms.TableView from Prism.Services.Dialogs.DialogContainer before adding to PrismSample.Views.MainPage.
Element: Xamarin.Forms.StackLayout is already a child of Prism.Services.Dialogs.DialogContainer. Remove Xamarin.Forms.StackLayout from Prism.Services.Dialogs.DialogContainer before adding to PrismSample.Views.DialogExtensionPage.
Element: Xamarin.Forms.StackLayout is already a child of Prism.Services.Dialogs.DialogContainer. Remove Xamarin.Forms.StackLayout from Prism.Services.Dialogs.DialogContainer before adding to PrismSample.Views.SelectorPage.

```
### Expected Behavior

No debug console output that suggests something not-quite-right is happening.  Alternatively, some documentation that points out that this debug console output doesn't mean the user is using IDialogService incorrectly.

### Actual Behavior

Debug console output that suggests something not-quite-right is happening, and junking up our debug console output.

### Basic Information

- Version with issue: 8.0.0.1740-pre
- Last known good version: I don't know
- Xamarin.Forms version: happens in at least 4.8.0.1269 and 4.7.0.968
- IDE: Visual Studio 2019 Professional 16.7.2

### Screenshots

none needed

### Reproduction Link

Prism-Samples-Forms's [07-DialogService](https://github.com/PrismLibrary/Prism-Samples-Forms/tree/master/07-DialogService)

**Comment by dansiegel** [comment]
please update to the latest preview as we've updated and no longer manipulate the visual tree. if the problem persists let me know and we can reopen the issue.

**Comment by jmegner** [comment]
Confirmed: updating Prism.DryIoc.Forms to 8.0.0.1850-pre from 8.0.0.1740-pre made the messages go away.

I'll work on remembering to always try to reproduce the issue in the latest preview version.
