### ISSUE TITLE
OberservesProperty should support PropertyChanged with string.empty

### ISSUE THREAD

**Issue by tzehetner** [PrismLibrary/Prism#2196]
The property name check in Prism.Commands.PropertyObserverNode.OnPropertyChanged(object sender, PropertyChangedEventArgs e) is incorrect.

Currently it is

`if (e?.PropertyName == PropertyInfo.Name || e?.PropertyName == null)`

but it should be

`if (e?.PropertyName == PropertyInfo.Name || e?.PropertyName == null || e?.PropertyName == string.Empty)`

See https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.propertychangedeventargs.propertyname:

> An **Empty value(!)** or null for the propertyName parameter indicates that all of the properties have changed.

**Comment by brianlagunas** [comment]
fixed with PR #2202
