### ISSUE TITLE
ModuleDownloadProgressChanged missing in core but available in framework

### ISSUE THREAD

**Issue by stevensrf11** [PrismLibrary/Prism#2198]
Is there any reason why the ModuleDownloadProgressChanged  event is not included in .Net Core but included in .Net Framework,
In Prism 7.2.0.2422 source code IModuleManager.cs file shows event is coded out for use in .Net Core as shown below:

#if NET45
        /// <summary>
        /// Raised repeatedly to provide progress as modules are downloaded.
        /// </summary>
        event EventHandler<ModuleDownloadProgressChangedEventArgs> ModuleDownloadProgressChanged;
#endif
![image](https://user-images.githubusercontent.com/22349374/94267380-1c1e0100-ff01-11ea-913f-ca3453165f57.png)

### Steps to Reproduce

1. 
2. 
3. 

### Basic Information

- Version with issue:
- Last known good version:
- Xamarin.Forms version:
- IDE:

**Comment by brianlagunas** [comment]
Good catch. This is an oversight on our part when .NET Core 3 was released.  This was added because of Xamarin, but when .NET Core was added, we never updated it. We'll have to make sure we think this through as I'm not sure if this could be supported in Uno. So this may be a WPF only feature.

**Comment by dansiegel** [comment]
This was already addressed in Prism 8 when we added support for Uno.

**Comment by brianlagunas** [comment]
@dansiegel SWEET! Thanks for the update

**Comment by stevensrf11** [comment]
Oh no big deal.

Thanks

 
 

Sent: Friday, September 25, 2020 at 9:14 AM

**Comment by stevensrf11** [comment]
Is there a stable release of PRISM 8 yet?

 
 

Sent: Friday, September 25, 2020 at 9:15 AM

**Comment by brianlagunas** [comment]
@stevensrf11 No, but there is a preview on NuGet which is the v8 RC.

**Comment by dansiegel** [comment]
pre2 is essentially what we'll be shipping as stable with some minor tweaks like updating the version of DryIoc / Unity

**Comment by stevensrf11** [comment]
Ok. Any projected date for a stable release of PRISM 8?

I am starting to get allot of calls for new development of WPF application, and would like to use a stable release of PRISM 8.

I did not know that companies still had VC++ / MFC applications in existence.


 
 

Sent: Friday, September 25, 2020 at 9:23 AM

**Comment by stevensrf11** [comment]
Sounds great.

Would pre2 be stable enough to run in a production environment in critical applications?

 
 

Sent: Friday, September 25, 2020 at 9:24 AM

**Comment by dansiegel** [comment]
We'll release when we get to it... @brianlagunas and I have a lot of other things going on. Pre2 is absolutely stable enough to run in a production environment

**Comment by stevensrf11** [comment]
Sounds like a good plan

 
 

Sent: Friday, September 25, 2020 at 9:30 AM
