### ISSUE TITLE
[Bug][uno] I get an error when outputting multiple DialogWindow.

### ISSUE THREAD

**Issue by kaki104** [PrismLibrary/Prism#2199]
### Description

Hi

These days, I am developing a test app using the Uno-prism template.
If I try to show the DialogWindow again while the DialogWindow is shown, an error occurs.

```
System.Exception: An async operation was not properly started.

Only a single ContentDialog can be open at any time.
   at Windows.UI.Xaml.Controls.ContentDialog.ShowAsync()
   at Prism.Services.Dialogs.DialogService.ShowDialogInternal(String name, IDialogParameters parameters, Action`1 callback, String windowName)
   at Prism.Services.Dialogs.DialogService.ShowDialog(String name, IDialogParameters parameters, Action`1 callback)
   at UnoPrism200.Commons.Utility.ShowConfirm(String message, IDialogPara
```

As far as I know, ContentDialog can only output one at a time. If so, can Prism only display one DialogWindow at a time? On other platforms, it is possible to display multiple DialogWindow, but there seems to be a problem to have to display only one in Uno Platform.

If it is not possible to implement multiple DialogWindow, it would be helpful if there is even a property (display or not) that can know the current state value.

### Steps to Reproduce

1. Display one DialogWindow using DialogService.
2. When the OK button is pressed, _dialogService.ShowDialog is called again.
3. 

### Expected Behavior
Another DialogWindow is displayed.

### Actual Behavior
I get an error.

### Basic Information

- Version with issue: Prism.DryIoc.Uno 8.0.0.1850-pre
- Last known good version:
- Xamarin.Forms version:
- IDE: Visual Studio 2019 version 16.7.4

### Reproduction Link

https://github.com/kaki104/UnoPrism410

**Comment by brianlagunas** [comment]
As the error says `Only a single ContentDialog can be open at any time`. You requirements for "state value" is unknown and vague. You can easily tack this yourself. Check your state before opening it, save your state when the dialog closes.
