### ISSUE TITLE
Double registrations (UnityExtension)

### ISSUE THREAD

**Issue by EuroEager2008** [PrismLibrary/Prism#2203]
Every call to e.g. containerRegistry.Register<TFrom, Tto>();
creates 2 registrations, one as expected and other with name, version etc.

Calling containerRegistry.Register<TFrom, Tto>("SomeName)";
seems to register correct, but crashes at resolve later.

Is this the expected behaviour? Why?

**Comment by dansiegel** [comment]
this is a duplicate issue.

**Comment by EuroEager2008** [comment]
Thanks.
Would you care to link to the other one?
