### ISSUE TITLE
Difference between v7.2.0.1422 and v8

### ISSUE THREAD

**Issue by OmidID** [PrismLibrary/Prism#2209]
I working on Prism for Avalonia https://github.com/AvaloniaCommunity/Prism.Avalonia and it is a ported version from WPF.
It is complicated to find out what is the differece in latest version to make the same changes there. 
I would ask like to community to help me to find what is the different that I can do the changes there as well.

**Comment by AmrAlSayed0** [comment]
You could compare different tags https://github.com/PrismLibrary/Prism/compare/v7.2.0.1422...v8.0.0.1850-pre in Github

**Comment by OmidID** [comment]
@AmrAlSayed0 Thanks for your answer. The problem is 1672 files are modified contains all the libraries.
As I mention it is so complicate to find the difference. The project is active for 3 years and it was re ported once by me to update it with latest version.
It is not easy to do it again, that why asking for help from community to find a better solution.

**Comment by AmrAlSayed0** [comment]
There is this website that can diff between different versions of nuget packages but that's just the exposed APIs and only nuget packages hosted on nuget.org, Hope it helps

**Comment by dansiegel** [comment]
If you're looking for API by API differences fuget is probably your best bet since you can diff API's between two NuGet package versions... for more explanatory information please refer to the releases. If you have further questions please ping me on Twitter.
