### ISSUE TITLE
[Bug] When Android creates a new MainActivity, the app shows a white screen

### ISSUE THREAD

**Issue by pravincar** [PrismLibrary/Prism#2211]
### Description
In a certain sequence of navigation events, it seems like Android creates a new instance of MainActivity. This creates a new instance of App.cs 
In this scenario, although Prism appears to set the MainPage to MenuPage, a white screen is displayed. 

### Steps to Reproduce
Run the project PopupPluginSample.Droid on Android emulator
1. Click NavigationPage
2. Click Launch Popup
3. Click the system back button (Goes out of the app)
4. Use the recent apps button to get back to the app

### Expected Behavior
App should show the MainPage

### Actual Behavior
App shows a white screen

### Basic Information

- Version with issue: 7.4.0.122+
- Last known good version: unknown
- Xamarin.Forms version: 4.8.0.1269
- IDE: Visual Studio for Mac 8.7.8

### Screenshots
A video has been attached showing how to reproduce the problem
[Prism navigation issue.mov.zip](https://github.com/PrismLibrary/Prism/files/5365433/Prism.navigation.issue.mov.zip)

### Reproduction Link
[prism navigation issue.zip](https://github.com/PrismLibrary/Prism/files/5365497/prism.navigation.issue.zip)

**Comment by pravincar** [comment]
Could this be related to https://github.com/xamarin/Xamarin.Forms/issues/2562

**Comment by dansiegel** [comment]
@pravincar whatever the issue is, what you're describing would be out of the context of anything that Prism would be handling.

**Comment by pravincar** [comment]
@dansiegel I tested this further and found that the issue is within the Prism library. If I use Application.Current.MainPage to set MainPage the problem is not seen.

Please see the new sample project attached here.

If you comment out the line `UseXFNavigation = true`, you will be able to reproduce the problem.

On further investigation, I found that adding a 'Task.Delay(1000)' before 'Application.Current.MainPage = new MenuPage();' causes the same issue. I believe that MainPage should be set synchronously whereas Prism is setting it asynchronously here which is causing the white screen to appear.

````
        static bool UseXFNavigation = false;

        protected override async void OnInitialized()
        {
            InitializeComponent();
            SetupLoggingListeners();
            if (UseXFNavigation)
            {
                Application.Current.MainPage = new MenuPage();
            }
            else
            {
                await NavigationService.NavigateAsync("/MenuPage");
                //Comment the line below and try the steps to reproduce the issue
                UseXFNavigation = true;
            }
        }
````


[navigation_issue_repro.zip](https://github.com/PrismLibrary/Prism/files/5370380/navigation_issue_repro.zip)

**Comment by Tuytje** [comment]
@pravincar were you able to solve the issue? I think I'm running into the same issue and have no solution at this time. 

Setting the MainPage directly (with new Page()) is not an option since I'm losing all ViewModel creation then :(

**Comment by Subha1787** [comment]
Any update on this Issue? Facing the same blank white screen only in android when try to set the MainPage using Navigation Service. Thanks in advance.

**Comment by pmatrasc** [comment]
I confirm I still this the issue

**Comment by hutterm** [comment]
@dansiegel please consider reopening this
can also confirm I get this issue
