### ISSUE TITLE
WindowStartupLocation and custom dialog window

### ISSUE THREAD

**Issue by brinko99** [PrismLibrary/Prism#2216]
Regarding Prism for WPF: 7.2.0.1422

When using `WindowStartupLocation` with a custom dialog window, `CenterOwner` does not work without modification to the custom dialog window.

Because `Dialog.WindowStartupLocation` was implemented with `CenterOwner` as the default value (below), a custom window must set the property to `CenterOwner` to match (as Prism does with its `DialogWindow`).

```// Prism implementation
public static readonly DependencyProperty WindowStartupLocationProperty =
    DependencyProperty.RegisterAttached(
        "WindowStartupLocation",
        typeof(WindowStartupLocation),
        typeof(Dialog),
        new UIPropertyMetadata(WindowStartupLocation.CenterOwner, OnWindowStartupLocationChanged));
```
`Window's` default `WindowStartupLocation` is `Manual`. If the dependency property is used with such a window and is set to `CenterOwner`, the property changed callback is never invoked and `WindowStartupLocation` is never set.

I suggest that `WindowStartupLocationPropert` be implemented with no default (below). This ensures that the desired property is set regardless of the Window's default.

```// Suggested
public static readonly DependencyProperty WindowStartupLocationProperty =
    DependencyProperty.RegisterAttached(
        "WindowStartupLocation",
        typeof(WindowStartupLocation),
        typeof(Dialog),
        new UIPropertyMetadata(OnWindowStartupLocationChanged));
```

The attached project demonstrates the issue.

Note the window style:
```<prism:Dialog.WindowStyle>
    <Style TargetType="Window">
        <Setter Property="prism:Dialog.WindowStartupLocation" Value="CenterOwner" />
        <!--<Setter Property="local:Dialog.WindowStartupLocation" Value="CenterOwner" />-->
```
When Prism's implementation is used, the dialog is not centered in the owner. When the local implementation is used, it works as expected.

[DialogRepo.zip](https://github.com/PrismLibrary/Prism/files/5405388/DialogRepo.zip)

**Comment by brianlagunas** [comment]
Fixed! Thanks for reporting the issue.
