### ISSUE TITLE
[Bug] Navigation when in Tabbed Pages doesn't change currently selected tab

### ISSUE THREAD

**Issue by DevonHansen** [PrismLibrary/Prism#2218]
### Description
When using Tabbed page as main page, with  as described within Microsoft's [documentation](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/navigation/tabbed-page#populate-a-tabbedpage-with-a-page-collection) and attempting to do a navigation action on the selected tab, it changes the last tab item in the list to requested page rather than the currently selected. I have reproduced using Prism template generator, updated to Prism 8.0.0.1909 and entering 3 tabbed pages and a singluar sub page. (See attached).

### Steps to Reproduce

1. Create Prism app
2. Create tab page with multiple tabs as pages - have some functionality in there to allow navigation
3. Attempt navigation on page that isn't the last tab in the list

### Expected Behavior
Currently selected tab navigates the relevant screen.

### Actual Behavior
Last tab navigates to requested location

### Basic Information

- Version with issue: 8.0.0.1909
- Last known good version: 7.2.x
- Xamarin.Forms version: 4.8.0.1560
- IDE: Visual Studio 2019

#### Notes
Only tested this on Android, as this is the only device I currently have access to. It was running on Android Simulator with Android 10 installed.

### Reproduction Link
[SampleApp.zip](https://github.com/PrismLibrary/Prism/files/5422413/SampleApp.zip)

**Comment by dansiegel** [comment]
This indeed is some very strange behavior. Thanks for the bug report and reproduction.

**Comment by brianlagunas** [comment]
We have identified the issue and will work on a fix. Thanks again for reporting this.

**Comment by DevonHansen** [comment]
Thank you for the update. What task/bug can I keep an eye on for updates on this as I noticed this and duplicate are both marked as closed?

**Comment by brianlagunas** [comment]
What do you mean? This issue is not closed
 
![image](https://user-images.githubusercontent.com/835562/102636534-03914180-4112-11eb-94b2-717557390989.png)

**Comment by DevonHansen** [comment]
Oh sorry, misread the thread! Ill remove previous comment

**Comment by brianlagunas** [comment]
This should be fixed now. It will be publicly available in our next update.
