### ISSUE TITLE
[Bug] Dialog's AutowireViewModel

### ISSUE THREAD

**Issue by qtbui159** [PrismLibrary/Prism#2219]
### Description

See the Prism 8.0.0.1909 changelog, there is 

BEHAVIOR CHANGE: ViewModelLocator is now Opt-Out not Opt-In. The ViewModelLocator.AutowireViewModel will automatically be set to true if the DataContext is null and the property has not been set.

### Steps to Reproduce

1. Run Project
2. Click ViewA and ViewB
3. Compare

### Expected Behavior
TextBlock Show Success
### Actual Behavior
ViewA Show Success
ViewB Not
### Basic Information

- Version with issue: Prism 8.0.0.1909 ,  .net framework 4.8
- IDE: VS2019

### Reproduction Link
https://github.com/qtbui159/PrismAutowireViewModel.git

**Comment by dansiegel** [comment]
it would seem that the DialogService is not calling the correct API's. Thanks for the report

**Comment by brianlagunas** [comment]
This is not a bug in Prism, this is a bug in your sample. You are not setting ViewBViewModel.Value property, so it's null when the VM loads. Set the Value property in the ctor and it will show in the UI.

**Comment by qtbui159** [comment]
@brianlagunas  It's not question about ViewBViewModel.Value . I mean ViewBViewModel.LoadedCommand not call correctly without AutoWireViewModel=True

**Comment by brianlagunas** [comment]
This is not a bug. This is about order of operations in WPF. When you don't set the autowire attached property, the view is created first by Prism, everything is initialized and loaded, and then the autowire is added to the view after the fact by Prism if it has not been set. If you define the VML attached property on the view, it becomes part of the initialization process of the view when it's created and gets set before the view is loaded. If you need the LoadedCommand to fire on load, then you must manually set the VML.

**Comment by qtbui159** [comment]
> This is not a bug. This is about order of operations in WPF. When you don't set the autowire attached property, the view is created first by Prism, everything is initialized and loaded, and then the autowire is added to the view after the fact by Prism if it has not been set. If you define the VML attached property on the view, it becomes part of the initialization process of the view when it's created and gets set before the view is loaded. If you need the LoadedCommand to fire on load, then you must manually set the VML.

clearly.thx
