### ISSUE TITLE
[Bug] .net 4.7.2 cannot add Prism reference by nuget

### ISSUE THREAD

**Issue by qtbui159** [PrismLibrary/Prism#2220]
### Description

I try .net framework 4.8 and 4.6.1. It works well, but version 4.7.2 is incorrect.

### Steps to Reproduce

1. Create a new wpf project use .net framework 4.7.2
2. Use nuget install Prism.Unity
3. There is not Prism.Unity in Reference

### Expected Behavior
Prism.Unity is added to Reference
### Actual Behavior
Prism.Unity is not added to Reference
### Basic Information

- Version with issue: Prism 8.0.0.1909，.Net Framework 4.7.2
- IDE: vs2019 community 16.7.6

### Reproduction Link
none

**Comment by dansiegel** [comment]
closing for no reproduction
