### ISSUE TITLE
[Bug] Xamarin forms Hierarchical Navigation with Page title,MasterDetailsPage,TabbedPage

### ISSUE THREAD

**Issue by ghotekarduryo** [PrismLibrary/Prism#2221]
I m Using Below code working fine same page as Like 

`   NavigationParameters navigationParameters = new NavigationParameters();
                navigationParameters.Add("ItemId", products.Item_Id);
              //  navigationParameters.Add("Mode", "ProductDetils");
                await NavigationService.NavigateAsync("NavigationPage/ProductDtlsPage", navigationParameters);
            `

same showing double backbutton and toolitems why?

**Comment by dansiegel** [comment]
@ghotekarduryo as was indicated by the issue template which you didn't follow, bug reports require a reproduction app of the issue you are reporting.
