### ISSUE TITLE
Simplify passing parameters between dialogs

### ISSUE THREAD

**Issue by Ashymonth** [PrismLibrary/Prism#2224]
## Summary

Now, to get the parameter, after closing the dialog, you need to write `callback.Patameters.GetValue` or `TryGetValue`. For simple situations, you can simplify this and use the generic extension method, where to get the key will be used `typeof(TValue).Name`
and to add a parameter, use `nameof(ClassName)`

## API Changes

To maintain backward compatibility and simplify usage, you can add extension methods that will return parameters from the dialog

## Intended Use Case

        public Example(IDialogService dialogService)
        {
            _dialogService = dialogService;
        }

        public void Test()
        {
            _dialogService.ShowDialog("DialogView",new DialogParameters(), result =>
            {
                var actual = result.GetDialogParameter<TestClass>();
            });
        }

**Comment by brianlagunas** [comment]
Thank you for the suggestion, but this is not a feature we will be adding to Prism.
