### ISSUE TITLE
PTA, Digital Clocks, Negation

### ISSUE THREAD

**Issue by proteusGIT** [PrismLibrary/Prism#2226]
I understand that strict clock comparisons of the form `x<2` are prohibited for the digital clocks engine.
But apparently, negation is not and, hence, `x<2` can be encoded using `!(x>=2)`.
Then I also recognized that PRISM rewrote the condition `Pmax=? [ F !(x>=2) ]` into `Pmax=? [ F !(x*2>=2) ]`.
While `x*2` may be an internal name for a fresh variable, I was wondering if there may be a bug here.

Basically, I just wanted to get a full grammar of what PRISM supports for each of the three PTA engines.

```
Model checking: Pmax=? [ F !(x>=2) ]

Performing digital clocks translation...
Computed clock maximums: {x=2, y=10}
Computed GCD: 2

Type:        MDP
Modules:     M 
Variables:   s x y 

Model checking: Pmax=? [ F !(x*2>=2) ]

Building model...
```

model:

```
pta

module M

	s : [0..3] init 0;
	x : clock;
	y : clock;

	[]
		s=0
		-> 
		0.5: (s'=1)&(x'=0)
		+
		0.5: (s'=2);
	[]
		s=1 & x=0 & y=10
		-> 
		1: (s'=3) & (y'=0);
	[]
		s=2 & x=0 & y=0
		-> 
		1: (s'=3);

endmodule

label "success" = (s=3);
```

**Comment by brianlagunas** [comment]
I believe you have the wrong repo. This is the repo for the Prism Library. A library for building .NET applications

**Comment by proteusGIT** [comment]
You are right. Sorry.
