### ISSUE TITLE
Register the same view to use a different view model, The corresponding instance cannot be obtained by key

### ISSUE THREAD

**Issue by Exception-King** [PrismLibrary/Prism#2228]
Register the same view to use a different view model,
The corresponding instance cannot be obtained by key。

          containerRegistry.RegisterForNavigation<StepView, AViewModel>("A");
          containerRegistry.RegisterForNavigation<StepView, BViewModel>("B");

**Comment by Exception-King** [comment]
Set A to get B

**Comment by brianlagunas** [comment]
This is not support. The ViewModelLocator uses type mappings for VMs. The key is only used with the container to resolve the type, not the VM.

If you need this behavior, then you need to handle this yourself.
