### ISSUE TITLE
AutoWireViewModel where constructor uses MEF service

### ISSUE THREAD

**Issue by znakeeye** [PrismLibrary/Prism#223]
Consider this viewmodel constructor:

```C#
[ImportingConstructor]
public MyViewModel(IMyService service)
```

This works in my Prism app, except when I use `AutoWireViewModel="True"`. In that case, I get a `XamlParseException`. If I remove the constructor parameter, it works.

How can I make it work with this constructor?

**Comment by znakeeye** [comment]
I believe I need to use `SetDefaultViewModelFactory`, but I still cannot get the container to instantiate my viewmodel unless I have it in region. Ideas?

```C#
protected override void ConfigureContainer()
{
	base.ConfigureContainer();

	ViewModelLocationProvider.SetDefaultViewModelFactory(viewModelType =>
       Container.GetExports(viewModelType, null, null).First());
}
```

**Comment by briannoyes** [comment]
Are you saying you need access to the container in your ViewModel or you just need to have your ViewModel constructed by the container so that it can DI your IMyService reference? For the latter, what you are showing in your second comment is all that should be required.

**Comment by znakeeye** [comment]
The latter. Thanks for pointing that out. Now I see the error... `GetExports` returns a `Lazy<>` so we need to add `.Value`. That did the trick!

(A good thing this code is now documented here. It was quite hard to find it on the internet.)

**Comment by brianlagunas** [comment]
Well, I am curious why this wouldn't work by default.  In Bootstrapper.cs we are setting the ViewModelLocationProvider like this:
```
        protected virtual void ConfigureViewModelLocator()
        {
            ViewModelLocationProvider.SetDefaultViewModelFactory((type) => ServiceLocator.Current.GetInstance(type));
        }
```

Should we override this in the MefBootstrapper and call it like in @znakeeye comment?

**Comment by znakeeye** [comment]
If you ask me, that makes perfect sense.
