### ISSUE TITLE
[Enhancement] Apply AutowireViewModel automatically when using RegisterViewWithRegion 

### ISSUE THREAD

**Issue by hansoli68** [PrismLibrary/Prism#2236]
### Description

AutoWireViewModel opt-out doesn't work. I don't know why it causes exactly, it may be related with region manager.

### Steps to Reproduce

1. Clone repo.
2. Remove `prism:ViewModelLocator.AutoWireViewModel="True"` from `/Modules/MainModule/Views/MainRegionView.xaml`
3. Run `Shell` project.
4. Click `Open Window` button.

### Expected Behavior

New window (a dialog of `WindowTestView`) pop-up.

### Actual Behavior

Nothing happen.

* It works fine if I didn't remove `prism:ViewModelLocator.AutoWireViewModel="True"`.

### Basic Information

- Version with issue: 8.0.0.1909

### Reproduction Link

https://github.com/HakamFostok/prism-boilerplate

**Comment by qtbui159** [comment]
same #2219

**Comment by vhugogarcia** [comment]
I am also facing the same exact issue. 

When registering for navigation on the App.xaml.cs file:
`containerRegistry.RegisterForNavigation<NavigationPage>();
            containerRegistry.RegisterForNavigation<SignInPage, SignInViewModel>();
            containerRegistry.RegisterForNavigation<MainView, MainViewModel>();
            containerRegistry.RegisterForNavigation<MainAdminView, MainAdminViewModel>();

            containerRegistry.RegisterForNavigation<VisitorsPage, VisitorsViewModel>();
            if (containerRegistry.IsRegistered<VisitorsPage>())
            {
                Debug.WriteLine("Registered VisitorsPage");
            }
            else
            {
                Debug.WriteLine("NOT registered VisitorsPage");
            }
`

It always triggers "NOT registered VisitorsPage" message.

**Comment by brianlagunas** [comment]
Technically, this is not a bug. The automatics application of the VML was only designed for use with RegionNavigation and the dialog service.

RegisterViewWithRegion is not part of the auto-VML feature. If you change your code to this:

`regionManager.RequestNavigate(RegionNames.MainRegion, "MainRegionView");`

It would work. (don't forget to register the view for navigation).  Basically to enable this we would need to modify this line of code to apply the VML automatcially:

https://github.com/PrismLibrary/Prism/blob/1046aee5cca5b40e073f1dbc06c09ed7a5506dc7/src/Wpf/Prism.Wpf/Regions/RegionViewRegistry.cs#L81-L84
