### ISSUE TITLE
[Enhancement] DisplayPromptAsync for IPageDialogService

### ISSUE THREAD

**Issue by OliverFlecke** [PrismLibrary/Prism#2241]
## Summary

Add `DisplayPromptAsync` to the `IPageDialogService` interface, alongside similar methods.

## API Changes

`IPageDialogService` provide methods to display native pop-up alerts and action sheets. [Xamarin.Forms.Page](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.page.displaypromptasync?view=xamarin-forms#Xamarin_Forms_Page_DisplayPromptAsync_System_String_System_String_System_String_System_String_System_String_System_Int32_Xamarin_Forms_Keyboard_System_String_) already provide a method to display a simple, native prompt to receive a text input from a user. I suggest adding this method to the `IPageDialogService` to match this.

```csharp
Task<string> DisplayPromptAsync(string title, string message, string accept = "OK", string cancel = "Cancel", string placeholder = default, int maxLength = -1, Xamarin.Forms.Keyboard keyboard = default, string initialValue = "");
```

I have made the proposed changes in [my fork here](https://github.com/OliverFlecke/Prism/tree/display_prompt).
(This also includes a usage of the method when loading the `HelloPageDialogModule` sample to test it, but you might not want that permanently in the samples)

Are there any issues regarding this?

## Intended Use Case

Request a simple text input from the user.

**Comment by brianlagunas** [comment]
I think is a reasonable addition and fits well with the existing PageDialogService. Submit your PR and Dan and myself will check it out.

**Comment by OliverFlecke** [comment]
Created PR #2246
