### ISSUE TITLE
[Bug] setFormsDependencyResolver doesn't work

### ISSUE THREAD

**Issue by stivenbr** [PrismLibrary/Prism#2244]
### Description

setFormsDependencyResolver doesn't work in Prism.Unity.Forms 8.0.0.1909, update my project to the latest version of nuget and does not recognize "DependencyService.Resolve" returns null

I have several child Models that use “DependencyService.Resolve<InterfaceService>" to perform their respective actions.

### Steps to Reproduce

1. Update Prism.Unity.Forms 7.2.0.1422 to 8.0.0.1909
2. return null all DependencyService.Resolve
3. setFormsDependencyResolver: true

### Expected Behavior

return requested service

### Actual Behavior

return null

### Basic Information

- Version with issue: 8.0.0.1909
- Last known good version: 7.2.0.1422
- Xamarin.Forms version: 4.8.0.1560
- IDE: Visual Studio Mac

### Screenshots

![Captura de Pantalla 2020-11-08 a la(s) 11 19 45 p  m](https://user-images.githubusercontent.com/17907993/98500009-427dce80-2219-11eb-9627-2c4bafda6b4b.png)

![Captura de Pantalla 2020-11-08 a la(s) 11 20 18 p  m](https://user-images.githubusercontent.com/17907993/98500020-4873af80-2219-11eb-9645-9ea9e2601cbc.png)

Thanks !

**Comment by dansiegel** [comment]
@stivenbr you may notice that the constructor in question has been marked Obsolete. This was also mentioned in the Release Notes. https://github.com/PrismLibrary/Prism/releases/tag/v8.0.0.1909

The Forms team has made some changes that made this feature unstable to begin with. As we start looking to the future of Xamarin.Forms / .NET MAUI this is likely an area that will change anyway. 

Lastly the fact that you were directly using the DependencyService to try to get something from Prism's container tells me you've got some major code smell.
