### ISSUE TITLE
[Bug] UWP AppThemeBindings doesn't work in a Prism based XF project

### ISSUE THREAD

**Issue by chowarth** [PrismLibrary/Prism#2248]
### Description
Trying to use an [AppThemeBinding](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/theming/system-theme-changes) in a Xamarin.Forms.UWP project that has been created through the Prism Template Pack does not appear to work (see attached project: **Prism-AppThemeBindingUWP**). I do not see the same issue with iOS and Android, the binding works as expected.

At first I thought this would absolutely be a XF issue but I've been unable to reproduce this behaviour using the standard Xamarin.Forms blank project template within Visual Studio (see attached project: **XF-AppThemeBindingUWP**).

### Steps to Reproduce

1. Create a blank page app using the Prism Template Pack that has iOS, Android and UWP platforms, and `DryIoc` as the container.
2. Open the `App.xaml.cs` for the UWP project and add the experimental flag for AppThemeBinding
3. Open `MainPage.xaml` within the Xamarin.Forms project
4. Add an `AppThemeBinding` for the `BackgroundColor` of the `ContentPage`
    e.g. `BackgroundColor="{AppThemeBinding Light=CornflowerBlue, Dark=Purple}"`
5. Run the application
6. Open Windows Light Theme Settings from the Start menu
7. Change the colour between **Light** and **Dark**
8. Observe no changes in the background colour of the displayed content page

### Expected Behavior
The background colour of the content page should change based on the Windows setting:
- In **Light** mode the background colour should be `CornFlowerBlue`
- In **Dark** mode the background colour should be `Purple`

### Actual Behavior
- The colour of the background is always set to the **Light** mode colour of `CornflowerBlue` regardless of Windows setting

### Basic Information

- Prism.DryIoc.Forms version: 7.2.0.1422
- Xamarin.Forms version: 4.7.0.1239
- IDE: Visual Studio 2019 version: 16.7.7
   - Prism Template Pack version: 2.2.2

Although the issue is visible using the above versions of XF and Prism it is also reproducible using:
- Prism.DryIoc.Forms version: 8.0.0.1909
- Xamarin.Forms version: 4.8.0.1560
- IDE: Visual Studio 2019 version: 16.7.7
   - Prism Template Pack version: 2.2.2

**Note:** You do not need to do Step 2. above if using XF 4.8.0 or greater

### Screenshots
![windows_light_mode](https://user-images.githubusercontent.com/10574476/98697081-6d2c6c00-236c-11eb-9de8-a82be2543e2d.png)
![windows_dark_mode](https://user-images.githubusercontent.com/10574476/98696992-538b2480-236c-11eb-9d38-cd6d574d0122.png)

### Reproduction Link
[XF-AppThemeBindingUWP.zip](https://github.com/PrismLibrary/Prism/files/5518498/XF-AppThemeBindingUWP.zip)
[Prism-AppThemeBindingUWP.zip](https://github.com/PrismLibrary/Prism/files/5518502/Prism-AppThemeBindingUWP.zip)

**Comment by dansiegel** [comment]
@chowarth this has to be an issue either with your code or Xamarin.Forms. Prism has ZERO understanding of anything other than the base netstandard contracts from Xamarin.Forms. We also don't touch theming or anything else that would impact this.

https://github.com/PrismLibrary/Prism/blob/59f712d3bb7ef2d92c17ad19a626738837b23794/src/Forms/Prism.Forms/Prism.Forms.csproj#L5

It is worth noting that Prism 7.2 was built against Xamarin.Forms 3.6 which didn't understand Light Theme/Dark Theme.. while Prism 8 is built against Xamarin.Forms 4.8 which should theoretically handle it just fine.

**Comment by chowarth** [comment]
That's exactly what I assumed, but I have no explanation for it as a standard non-Prism blank project works as expected 🙁

**Comment by dansiegel** [comment]
if you install Prism in the Xamarin app btw it all works fine...

**Comment by chowarth** [comment]
Could it be something with Prism Template Pack when the project is created? I'll have a look at comparing the two projects in more depth tonight.

**Comment by chowarth** [comment]
@dansiegel I found the culprit. In the UWP `App.xaml` that is generated with the Prism Template Pack it includes the line `RequestedTheme="Light"` this appears to prevent XF `AppThemeBinding` from working, removing this line and rebuilding, UWP now correctly recognises system settings and changes binding values accordingly.
