### ISSUE TITLE
containerRegistry.RegisterForNavigation fails in  Prism-Samples-Wpf-master 17-BasicRegionNavigation solution structure made more defined in structure

### ISSUE THREAD

**Issue by stevensrf11** [PrismLibrary/Prism#2253]
If the  the Prism-Samples-Wpf-master 17-BasicRegionNavigation solution code is broken up into a structure similar  as the Plural's Prism Introduction BasicRegionNavigation source code from back when Prism 5 was used, the 
containerRegistry.RegisterForNavigation<ViewA>() and containerRegistry.RegisterForNavigation<ViewB>(); fails to register the views for navigation.

To get those two views to register properly for navigation  I had to use that Plural's old source code trick.
Below is that code for registering View A successfully. ViewB would be registered the same way.

My question is why does the containerRegistry.RegisterForNavigation method fail to register the views, but the old plural code work? 

During Navigation I placed a breakpoint in the UnityContainerExtension's Resolve method and the value of the name input parameter was the same no matter which method is used to register the view.
But if the containerRegistry.RegisterForNavigation is used to register a view the KeyNotFoundException is thrown,
If the old plural way is used to register the exception is not thrown.

I have a sample project where the Prism-Samples-Wpf-master 17-BasicRegionNavigation was broken down into the similar structure of the old plural structure. The latest Prism 8 source code was used.
I can post the solution on GitHub for download if anyone is interested in it.

On a side note if a NavigationComplete is used, and the  KeyNotFoundException, the NavigationResult indicates the navigation was successful. 

// Code where during navigation containerRegistry.RegisterForNavigation  causes exception to be thrown
namespace Prism.Unity
{

    class UnityContainerExtension : IContainerExtension<IUnityContainer>, IContainerInfo
{..........................
        public object Resolve(Type type, string name, params (Type Type, object Instance)[] parameters)
        {
            try
            {
                var c = _currentScope?.Container ?? Instance;

                // Unity will simply return a new object() for unregistered Views
                if (!c.IsRegistered(type, name))
                    throw new KeyNotFoundException($"No registered type {type.Name} with the key {name}.");

                var overrides = parameters.Select(p => new DependencyOverride(p.Type, p.Instance)).ToArray();
                return c.Resolve(type, name, overrides);
            }
            catch (Exception ex)
            {
                throw new ContainerResolutionException(type, name, ex);
            }
        }

// Old plural prism 5 code
   public class ModuleAModule : IModule
    {

        IUnityContainer _container;

        public ModuleAModule(IUnityContainer container)
        {
            _container = container;
        }
        public void OnInitialized(IContainerProvider containerProvider)
        {

            var regionManager = containerProvider.Resolve<IRegionManager>();
            regionManager.RegisterViewWithRegion(RegionNames.ToolbarRegion, typeof(ViewAButton));

        }

        public void RegisterTypes(IContainerRegistry containerRegistry)
        {
            _container.RegisterTypeForNavigation<ViewA>();
        }
    }

   public static class UnityExtensions
    {
        public static void RegisterTypeForNavigation<T>(this IUnityContainer container)
        {
            container.RegisterType(typeof(Object), typeof(T), typeof(T).FullName);
        }
    }

### Steps to Reproduce

1. 
2. 
3. 

### Basic Information

- Version with issue:
- Last known good version:
- Xamarin.Forms version:
- IDE:

**Comment by brianlagunas** [comment]
We're going to need a sample in order to help answer this question.

**Comment by brianlagunas** [comment]
Closing because of no sample
