### ISSUE TITLE
[Bug] .net core 3.1 app (load modules in directory) throws an exception "Could not load .....  *.resources.dll"

### ISSUE THREAD

**Issue by joezhang-sh** [PrismLibrary/Prism#2255]
### Description

I used a demo from https://github.com/PrismLibrary/Prism/issues/2115 and updated the code by Brian's suggest, but there was an exception when starting up, and then the app worked well.

### Steps to Reproduce

1. Download the zip file and open with VS 2019
2. Build the solution
3. Run project HandyControlProject13

### Basic Information

- Version with issue: 8.0.0.1909
- Last known good version: NA
- Xamarin.Forms version: NA
- IDE: VS 2019

### Screenshots
![59F05589-8E7D-45ae-BDF3-1C8B9A004C34](https://user-images.githubusercontent.com/4892632/99612923-96768780-2a51-11eb-96e8-112238bbffbc.png)

### Reproduction Link

[HandyControlProject13.zip](https://github.com/PrismLibrary/Prism/files/5563975/HandyControlProject13.zip)

**Comment by brianlagunas** [comment]
There is no bug. The app works fine.
