### ISSUE TITLE
[Bug] NavigateAsync with stack reset modifies binding context of previous page 

### ISSUE THREAD

**Issue by BerndStoltefuss** [PrismLibrary/Prism#2258]
As already described in #2157 using await navigationService.NavigateAsync("/NavigationPage/Page2") seems to reset/modify binding context on the previous page, which for me results in some hard crashes in UiKit (which is tyring to remove GestureRecognizers while some of my code running in OnBindingContextChanged seems to do modifications while the page is already in destruction)
See fix in #2157 for a possible workaround?
I was able to workaround by doing some checks in my OnBindingContextChanged handlers.

Basic Information
Version with issue: 7.0.0.1909
Last known good version: Unkown
Xamarin.Forms version: 4.8.0.1687
IDE: Visual Studio 2019 Mac

**Comment by BerndStoltefuss** [comment]
I did some further testing and although there seems to be some modification to the binding context, my error seems to be related to using a NavigateAsync("NavigationPage/PreviousPage/NextPage") call while inside a Popup Page. There seems to some problem around this in 8.0. I replaced my call with _navigationService.ClearPopupStack();...NavigateAsync("NextPage") which seems to work.

**Comment by brianlagunas** [comment]
No sample provided. It also seems you fixed your problem.

**Comment by dansiegel** [comment]
based on the code you provided you are using the Popup plugin... Issues with the Popup Navigation Service should be reported at https://github.com/dansiegel/Prism.Plugin.Popups/issues
