### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by mprevot** [PrismLibrary/Prism#2264]
### Description

With Prism.{Core, DryIoc, Unity, Wpf} 8.0.0.1919 in a WPF .net 4.8 application, with `Container.RegisterTypeForNavigation<IntroView>();` was working until recent update: `RegisterTypeForNavigation` does not exists:

> Error	CS1061	'IUnityContainer' does not contain a definition for 'RegisterTypeForNavigation' and no accessible extension method 'RegisterTypeForNavigation' accepting a first argument of type 'IUnityContainer' could be found (are you missing a using directive or an assembly reference?)

It was reported here: https://github.com/PrismLibrary/Prism/issues/681

But the link provided by @brianlagunas is now dead.

**Comment by dansiegel** [comment]
Closing... no reproduction provided.

Also as the issue you referenced, and from what you've posted. This is simply no longer supported by Prism. You should be using the Prism IContainerRegistry NOT the IUnityContainer. If you would like to continue doing it with the Unity container it will be on you to write your own extension methods.

**Comment by mprevot** [comment]
@dansiegel It was implemented until update. Can you point to an example of such implementation ?

**Comment by dansiegel** [comment]
https://github.com/PrismLibrary/Prism/blob/v7.2.0.1422/Source/Wpf/Prism.Unity.Wpf/Legacy/UnityExtensions.cs
