### ISSUE TITLE
[Improvement] Performance can be marginally improved by using optimal Dictionary methods

### ISSUE THREAD

**Issue by VitalyKnyazev** [PrismLibrary/Prism#2274]
### Description
Current code uses ContainsKey + Get approach when working with dictionaries which is basically two lookups.
It is better to use existing TryGetValue method to have just one lookup and thus marginally improve performance.

Count() > 0 also can be replaced with Any() which has better performance by avoiding full collection scan.

### Steps to Reproduce
N/A

### Expected Behavior
Marginally better perfromance, hardly can be measured, just better coding practice

### Actual Behavior
Redundant dictionary lookups

### Basic Information
N/A

### Screenshots
N/A

### Reproduction Link
N/A

**Comment by brianlagunas** [comment]
Thank you for the suggestion, but this is not something we are concerned about at this time.
