### ISSUE TITLE
[Bug] Navigating Back twice, the parameters are missed

### ISSUE THREAD

**Issue by Galle94** [PrismLibrary/Prism#2276]
### Description

When GoBack twice, using this approach [link](https://github.com/PrismLibrary/Prism/issues/591#issuecomment-221151153), the parameters passed in are not being received on the destination page. I tried it using version 7.2.0.1422 and 8.0.0.1909, both have the same behavior. The navigation and animation are working well.

### Steps to Reproduce

1. Create my own Navigation Service derive from PageNavigationService.
2. Override the method "Task<INavigationResult> GoBackAsync(INavigationParameters parameters)" 

```
public override Task<INavigationResult> GoBackAsync(INavigationParameters parameters)
{
    if (parameters != null && parameters.TryGetValue("NumberOfPages", out int numberOfPages))
    {
        if (numberOfPages > 0)
        {
            for (int i = 0; i < numberOfPages; i++)
            {
                base.GoBackAsync(parameters, false, false);
            }
        }
    }

    return base.GoBackAsync(parameters);
}
```

3. Register the service with the container.
        
```
protected override void RegisterTypes(IContainerRegistry containerRegistry)
{	    
    containerRegistry.Register<INavigationService, PageNavigationServiceWrapper>();
    ...
}
```

4. Call GoBackAsync with the parameter "NumberOfPages" ("NumberOfPages" indicate the quantity extra's GoBack I need)

```
NavigationParameters parameters = new NavigationParameters
{
    { "NumberOfPages", 1 },
    { "PaymentAdded", true }
};

await NavigationService.GoBackAsync(parameters);
```

### Expected Behavior

Receive in the method OnNavigatedTo(INavigationParameters parameters) the parameters passed in.

### Actual Behavior

The parameters received in OnNavigatedTo(INavigationParameters parameters) are empty.

### Basic Information

- Version with issue: 7.2.0.1422 & 8.0.0.1909
- Last known good version: -
- Xamarin.Forms version: 4.8.0.1364
- IDE: Visual Studio 2019 for mac

### Reproduction Link

[SampleApp.zip](https://github.com/PrismLibrary/Prism/files/5680996/SampleApp.zip)

**Comment by brianlagunas** [comment]
We do not support custom code. If you wish to implement the ability to go back twice using the approach you are taking now, you would be responsible for making that work.

However, if you are within a NavigationPage, you could use the relative navigation pattern and just use `NavigateAsync("../../")` to go back twice.
