### ISSUE TITLE
PopupWindowAction should be able to set the Window's Owner

### ISSUE THREAD

**Issue by chuseman** [PrismLibrary/Prism#228]
When showing a window as a dialog, if the owner isn't set it is possible for the parent window to steal the focus away from the child. The application could appear hung to users in this case.

The ```PopupWindowAction``` should be able to setup the child ```Window```'s ```Owner``` property to avoid this.

**Comment by brianlagunas** [comment]
I noticed your PR #227 that you have a custom method for getting the owner.  Will Window.GetWindow not work?  Also, I am curious if we can always set the parent window, and remove the need for the property in general.

I am also not sure about adding the WindowStartupLocation.  Maybe we just need to improve on the CenterOverAsscoiatedObject logic?

**Comment by chuseman** [comment]
Let's pretend #227 didn't happen :)

I wasn't aware of ```Window.GetWindow()```, so I've updated to use that in #230. I didn't want to change behavior on people so that's why I added the property to enable this behavior of setting the ```Owner```. I can't imagine where you wouldn't want to do this though so maybe it is safe to always do it?

I think setting ```WindowStartupLocation``` is valuable because you may want to center to the owner window or screen instead of the view of the associated object. I'd use ```WindowStyle``` to accomplish this, if it were possible.

**Comment by brianlagunas** [comment]
Is it not possible to use the WindowStyle property to do this?

**Comment by chuseman** [comment]
The ```WindowStartupLocation``` property isn't a dependency property. There's a warning from ReSharper and and I get an exception at runtime when I've got it set.

**Comment by brianlagunas** [comment]
Ahhhh... yeah that would be a problem.
