### ISSUE TITLE
[Bug] Navigation from tab in TabbedPage populated in XAML ignores NavigationPage

### ISSUE THREAD

**Issue by kobbok** [PrismLibrary/Prism#2282]
### Description

When creating a new TabbedPage statically through XAML, if a tab is embedded in a NavigationPage, the navigation service ignores the navigation page and navigates to new pages modally. Forcing non-modal navigation throws an exception.

This problem does not occur if the tabbed page is created dynamically (ex. `NavigationService.NavigateAsync("/TabbedPage?createTab=NavigationPage|NavigationWrappedTab");`).

The problem occurs on Android. I sadly cannot check if the problem also occurs on iOS.

### Steps to Reproduce

1. Create a new TabbedPage
2. In the TabbedPage's XAML add a tab wrapped in a NavigationPage:
```xaml
<TabbedPage.Children>
  <NavigationPage>
    <x:Arguments>
      <views:NavigationWrappedTab />
    </x:Arguments>
  </NavigationPage>
  ...
</TabbedPage.Children>
```
3. In `App.xaml.cs` set the initial page to the newly created TabbedPage
4. Navigate from the NavigationWrappedTab to a new page, the navigation will be Modal, or if forced to not be modal, an exception is thrown.

### Expected Behavior
Navigation should not be modal, and should use the embedded navigation page.

### Actual Behavior
The navigation is either modal or if forced to not be modal, no navigation occurs (exception is thrown complaining about PushAsync not being avaliable globally on Android).

### Basic Information

- Version with issue: v8.0.0.1909
- Last known good version: 
- Xamarin.Forms version: v4.8.0.1821
- IDE: Microsoft Visual Studio Community 2019 16.8.3

### Reproduction Link

https://github.com/kobbok/AppPrismTabbedNavBug

**Comment by brianlagunas** [comment]
Thank you, this is related to #2218 and we will work on a fix. Closing as duplicate
