### ISSUE TITLE
[Bug] Call Command via BindingContext DelegatCommand not raised (XF)

### ISSUE THREAD

**Issue by isarzhan** [PrismLibrary/Prism#2296]
### Description
When  use XAML context for command type of   DelegateCommand :
** TapGestureRecognizer Command="{Binding Source={x:Reference _ProductPage}, Path=BindingContext.RemoveLocation }" CommandParameter="{Binding .}" **
No effect.
if change RemoveLocation command in  a viewmodel  from  DelegateCommand<T> to Command<T> the command raise as well 
 w/o problem.

Prism 8.0.0.1909
XF 4.8

**Comment by brianlagunas** [comment]
Closed as no repo app was provided. Also, this would not be a Prism issue. Prism does not have any control over gestures or their ability to invoke ICommands.
