### ISSUE TITLE
[Bug] Pressing back button on an async dialog, results in ShowDialogAsync task hanging

### ISSUE THREAD

**Issue by zeib** [PrismLibrary/Prism#2297]
### Description

When pressing the (Android) back button while an awaitable dialog (with ShowDialogAsync) is open, the task never returns a dialog result, essentially hanging the calling function as well. As a result OnDialogClosed of IDialogAware interface is not called as well.

### Steps to Reproduce

1. Open a dialog with ShowDialogAsync and await it
2. Press back button

### Expected Behavior

The task should return a dialog result..

### Actual Behavior

The task never returns.

### Basic Information

- Version with issue: Prism 8.0.0.1909
- Last known good version: Dialogs were different before Prism 8, probably not comparable.
- Xamarin.Forms version: 4.8.0.1560
- IDE: Visual Studio 2019 16.8.3

### Reproduction Link

[PrismDialogExampleApp.zip](https://github.com/PrismLibrary/Prism/files/5772297/PrismDialogExampleApp.zip)

**Comment by brianlagunas** [comment]
The back button is not currently support with dialogs. We are tracking this with #1862
