### ISSUE TITLE
PrismContentPage Wizard failed to run

### ISSUE THREAD

**Issue by dpuckett** [PrismLibrary/Prism#2303]
Trying to create a new ContentPage from the Prism templates. I'd had them installed for a while, went to create a new page yesterday and received this error.
I Uninstalled the template pack, and reinstalled from my visual studio, but still receive the same error.

- Version with issue:
- Last known good version:
- Xamarin.Forms version: 5.0.0.1874
- IDE: Visual Studio 2019 Enterprise 

![image](https://user-images.githubusercontent.com/5477570/104297746-1ef62f00-54bb-11eb-9d21-708328f91a05.png)

**Comment by brianlagunas** [comment]
This was a breaking change in Visual Studio. Update to the latest version of VS and it will work.
