### ISSUE TITLE
[Bug] Wrong text alignment of IPageDialogService.DisplayAlertAsync popup

### ISSUE THREAD

**Issue by Alex-Dobrynin** [PrismLibrary/Prism#2309]
RTL - right to left, LTR - left to right
I need to show MasterDetailPage with RTL behavior, when flyout comes from right. But everything else I need to show with LTR. 

To acheive this I did next:

![image](https://user-images.githubusercontent.com/23138430/105215186-a0079300-5b59-11eb-9f5c-815223d3ac66.png)

the stack of navigation is next (I'm sure you dont need such complex navigation to reproduce the issue):

await NavigationService.NavigateAsync($"{nameof(BaseMDPage)}/{nameof(TabbedPage)}" +
                    $"?{KnownNavigationParameters.CreateTab}={nameof(NavigationPage)}|{nameof(FirstTabPage)}" +
                    $"&{KnownNavigationParameters.CreateTab}={nameof(NavigationPage)}|{nameof(SecondTabPage)}" +
                    $"&{KnownNavigationParameters.CreateTab}={nameof(NavigationPage)}|{nameof(ThirdTabPage)}" +
                    $"&{KnownNavigationParameters.CreateTab}={nameof(NavigationPage)}|{nameof(FourthTabPage)}" +
                    $"&{KnownNavigationParameters.CreateTab}={nameof(NavigationPage)}|{nameof(FifthTabPage)}" +
                    $"&{KnownNavigationParameters.SelectedTab}={nameof(FirstTabPage)}");
              
and when I trying to show some alert popup using IPageDialogService.DisplayAlertAsync, it shows popup like arabian style RTL.
I suppose its somehow relates to latest changes in prism 8x, because when prism was 7.2.x I didnt notice such behavior of popups.

**Comment by dansiegel** [comment]
Prism does not control UI features such as RTL, also you have not provided a reproduction app as is our policy.

**Comment by Alex-Dobrynin** [comment]
created new ticket, where I attached repro project
