### ISSUE TITLE
[Bug] Navigating within NavigationPage not possible after going back from modal page

### ISSUE THREAD

**Issue by cytoph** [PrismLibrary/Prism#2313]
### Description

We have the following pages (MainPage, ViewA, ViewB and ViewM).
The navigation URI after each navigation should be as follows:
1. /NavigationPage/MainPage
2. /NavigationPage/MainPage/ViewA
3. /NavigationPage/MainPage/ViewA/ViewM?useModalNavigation=true
4. /NavigationPage/MainPage/ViewA/ViewB

All navigations except from 3. to 4. work. That navigation is done by using
`await navigationService.GoBackAsync(null, true, true);`
`await navigationService.NavigateAsync("ViewB");`
which does not seem to work, because after doing so my navigation stack is back on 2.

### Steps to Reproduce

1. Navigate to a page modally
2. GoBack modally from this page
3. Right after that navigate to another page (non-modally)

### Expected Behavior

The page to which was navigated lastly is shown.

### Actual Behavior

The page previous to the modally opened page is shown.

### Basic Information

- Version with issue: 8.0.0.1909
- Last known good version: n/a
- Xamarin.Forms version: 4.8.0.1364 and 5.0.0.1905
- IDE: Visual Studio 2019 (Version 16.8.4)

### Reproduction Link

I created a sample project with which the issue can be reproduced easily.
It can be found [here](https://github.com/cytoph/PrismNavigationBugSample).

**Comment by brianlagunas** [comment]
You can't do this
```
await navigationService.GoBackAsync(null, true, true);
await navigationService.NavigateAsync("ViewB");
```
You are removing the current page form the navigation stack and then trying to navigate from it again. Navigation is relative, and is always invoked from the caller. You must navigate from your ViewA VM after going back to it.

**Comment by cytoph** [comment]
But if that's not how I should do this, is there a way to replace the current modal page with a non-modal page?
Like `navigationService.NavigateAsync(“../ViewB", null, false, true)`?
