### ISSUE TITLE
Duplication in Prism "Release Notes".

### ISSUE THREAD

**Issue by pressacco** [PrismLibrary/Prism#2315]
### Description

As part of a IEC-62304 review, I noticed that the Prism [Release  Notes](https://github.com/PrismLibrary/Prism/releases), have duplicate entries.  Clearly this is a low priority bug... just thought you should know.

### Steps to Reproduce

1. expand the list of changes by clicking `See more` on the versions: 8.0.0.1909, 8.0.0.1850, 8.0.0.1740
2. search for: `using the ContainerLocator as the VML resolver`
3. this commit is included in:
   - 8.0.0.1850
   - 8.0.0.1740

### Expected Behavior

- A software change should only be associated with one version.

### Actual Behavior

- Software changes are being associated with multiple versions of Prism.

### Basic Information

- Version with issue: n/a
- Last known good version: n/a
- Xamarin.Forms version: n/a
- IDE: Visual Studio 2019

### Screenshots

n/a

### Reproduction Link

[This](https://github.com/PrismLibrary/Prism/releases) is where the problem was observed.

**Comment by dansiegel** [comment]
Thanks for the report. We do not really consider it a bug to "duplicate" the mentioning of a bug or feature between preview versions and the stable release as most developers do not participate in previews and only update for stable releases.

**Comment by BlueDotBrigadeFounder** [comment]
No worries. 

I filed this as a bug because I was under the impression you were using a script to generate the release notes.

**Comment by pressacco** [comment]
No worries.

I filed this as a bug because I was under the impression you were using a script to generate the release notes.
