### ISSUE TITLE
Upgrade from 5 to 6

### ISSUE THREAD

**Issue by boodoolak** [PrismLibrary/Prism#232]
Hello!
I make WP for 8.1 application UWP. It uses the library of Prism.MVVM, Prism.StoreApps and Unity.
What library the new version should I download from Nuget (or compile from source) make everything work with minimal changes?
You can make a list of what methods/classes are named differently in the new version?
Sorry for my English (Bing Translate :-))

**Comment by overrorflow** [comment]
I can help. Please send me email
