### ISSUE TITLE
[Enhancement]Make Behavior Key mandatory as an abstract property in RegionBehavior class

### ISSUE THREAD

**Issue by noufionline** [PrismLibrary/Prism#2320]
As every region behavior must have a key it would be a good idea to add an abstract property BehaviorKey to the base class.

**Comment by dansiegel** [comment]
This sounds great in theory however it would have to be an instance property which wouldn't be useful. Also there is no actual requirement that the key even be a property in the Behavior class although it makes more sense for it to be.
