### ISSUE TITLE
[Bug] Dependency hell with  EnterpriseLibrary.Commom.NetCore

### ISSUE THREAD

**Issue by RVPryimak** [PrismLibrary/Prism#2321]
Hi. I'm developing application on .NET Core WPF.
Using Prism.Unity version 8 and EnterpriseLibrary.Commom.NetCore 6.3.0. Application works fine when i use just Prism.Unity without Common library. After adding nuget package i receive following error:
TypeLoadException: Could not load type 'Unity.Policy.IConstructorSelectorPolicy' from assembly 'Unity.Abstractions, Version=5.11.6.0, Culture=neutral, PublicKeyToken=489b6accfaf20ef0'.

Do you have any idea how to fix this issue? I prepare small project where error is reproduce
[https://github.com/EnterpriseLibrary/common-infrastructure/files/5882485/PrismTestModularity.zip](url)

**Comment by brianlagunas** [comment]
This is not a bug. Prism uses v5.11.8 of Unity. Which means the EnterpriseLibrary.Commom.NetCore 6.3.0 must be trying to use use a different version. These packages are not compatible at this time. They will need to upgrade their dependencies.
