### ISSUE TITLE
[Bug] Use Modeal Navigation always true

### ISSUE THREAD

**Issue by joshwl2003** [PrismLibrary/Prism#2324]
### Steps to Reproduce

1. I have a login page which navigates to a master detail page using the following code await `this.NavigationService.NavigateAsync($"app:///MasterPage/NavigationPage/{NavigationPageKeys.DashBoardPage}" `
   In the view model. This works as expected
2. Click on an item in a collection view and navigate to another page using the following code. `await navigationService.NavigateAsync($"{NavigationPageKeys.ActionIndicatorDetailsPage}",navigationParameters,false,false); `
Navigation works as expected. Get the following output from  navigationService.GetNavigationUriPath(),  Navgation Uri Path after navigation /MasterPage/NavigationPage/DashBoardPage/ActionIndicatorDetailsPage
3. Click back button on the new  content page to return to master detail page. The following path is output by calling navigationService.GetNavigationUriPath() Navgation Uri Path after navigation /MasterPage/NavigationPage/DashBoardPage/ActionIndicatorDetailsPage?useModalNavigation=true
4. Tap on an item in the collection view again using the same exact code in step 2 and I get the following output in from navigationService.GetNavigationUriPath(),  Navgation Uri Path after navigation /MasterPage/NavigationPage/DashBoardPage/ActionIndicatorDetailsPage?useModalNavigation=true" The navigation never occurs, and useModalNavigation is set to true despite setting it being set to false.

### Expected Behavior
For navigation to occur with useModalNavigation set to false.
### Actual Behavior
Navigation does not occur due to useModalNavigation being set to true.
### Basic Information
I suspect that the following block of code in the page navigation service is causing the issue:
```
  var pageParameters = UriParsingHelper.GetSegmentParameters(nextSegment);
            if (pageParameters.ContainsKey(KnownNavigationParameters.UseModalNavigation))
                useModalNavigation = pageParameters.GetValue<bool>(KnownNavigationParameters.UseModalNavigation);
```
This is located in the function Process navigation at line 389 and does not take into account if useModalNavigation is set to true or false.

- Version with issue: 8.0.0.1909
- Last known good version: None
- Xamarin.Forms version: 4.8.0.1687
- IDE: VS for Mac

**Comment by brianlagunas** [comment]
Close because the required reproduction ink was not provided

**Comment by alextorres50** [comment]
Same issue here , I navigated to `NavigationService.NavigateAsync("NavigationPage/ViewA")`, next I used `.NavigateAsync("ViewB")` to navigate to ViewB, next `.navigateAsync("../../ViewC") `to remove ViewA and ViewB, next `.navigateAsync("ViewD")`,  that's ok 
the URI is "NavigationPage/ViewC/ViewD".

But in ViewD, I used  `.navigateAsync("../../ViewA")`, next I used `.NavigateAsync("ViewB")` , I used again `.NavigateAsync("../../ViewC")` to remove  again ViewA and ViewB, but when I try used .navigateAsync("ViewD") in ViewC, the URI path appear "/NavigationPage/ViewC/ViewC?useModalNavigation=true". the use modal parameter added automatically and not navigate to ViewD

the first time work fine, but the second time doesn't work

ViewA = LoginPage
ViewD = Has a Logout Button that execute NavigationService.NavigateAsync("../../ViewA")

Xamarin Forms Version: 5.0.2337
Prism: 8.1.197
