### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by joshwl2003** [PrismLibrary/Prism#2328]
Description

Steps to Reproduce

I have a login page which navigates to a master detail page using the following code await this.NavigationService.NavigateAsync($"app:///MasterPage/NavigationPage/{NavigationPageKeys.DashBoardPage}" 
In the view model. This works as expected
Click on an item in a collection view and navigate to another page using the following code. await navigationService.NavigateAsync($"{NavigationPageKeys.DetailsPage}",navigationParameters,false,false); 
Navigation works as expected. Get the following output from navigationService.GetNavigationUriPath(), Navgation Uri Path after navigation /MasterPage/NavigationPage/DashBoardPage/DetailsPage
Click back button on the new content page to return to master detail page. The following path is output by calling navigationService.GetNavigationUriPath() Navgation Uri Path after navigation /MasterPage/NavigationPage/DashBoardPage/DetailsPage?useModalNavigation=true
Tap on an item in the collection view again using the same exact code in step 2 and I get the following output in from navigationService.GetNavigationUriPath(), Navgation Uri Path after navigation /MasterPage/NavigationPage/DashBoardPage/DetailsPage?useModalNavigation=true" The navigation never occurs, and useModalNavigation is set to true despite setting it being set to false.

Expected Behavior

For navigation to occur with useModalNavigation set to false.

Actual Behavior

Navigation does not occur due to useModalNavigation being set to true.

Basic Information

I suspect that the following block of code in the page navigation service is causing the issue:

  var pageParameters = UriParsingHelper.GetSegmentParameters(nextSegment);
            if (pageParameters.ContainsKey(KnownNavigationParameters.UseModalNavigation))
                useModalNavigation = pageParameters.GetValue<bool>(KnownNavigationParameters.UseModalNavigation);
This is located in the function Process navigation at line 389 and does not take into account if useModalNavigation is set to true or false.

Version with issue: 8.0.0.1909
Last known good version: None
Xamarin.Forms version: 4.8.0.1687
IDE: VS for Mac
Screenshots

Reproduction Link
### Reproduction Link
https://github.com/joshwl2003/PrismCollectionViewBug

**Comment by brianlagunas** [comment]
Your app works as expected and navigation does indeed occur for each item clicked in the collection view.

![xf-app-working](https://user-images.githubusercontent.com/835562/106515807-6efd5b80-6493-11eb-8a50-748d6d9c72a4.gif)

`useModalNavigation` does not impact the ability to perform navigation. It simply controls the type of navigation you want to occur. The use of the property in the `GetNavigationUri` is meant to get a snapshot of the NavigationPath of the current View/VM and has no influence of the navigation process itself.
