### ISSUE TITLE
[UWP]Please remove sealed from PrismUnityApplication OnInitializeAsync method

### ISSUE THREAD

**Issue by runceel** [PrismLibrary/Prism#233]
I want to write initializing logic in App class(this logic is async method).
PrismApplication class can override OnInitializeAsync. But PrismUnityApplication can't override OnInitializeAsync.

I hope this.

```cs
protected override async Task OnInitializeAsync(IActivatedEventArgs args)
{
    await base.OnInitializeAsync(args);
    await MyInitializeLogic();
}
```

otherwise

```cs
// PrismUnityApplication.cs
protected virtual Task OnInitializeAsync() { return Task.FromResult<object>(null); }

protected override sealed async Task OnInitializeAsync(IActivatedEventArgs args)
{
    ConfigureContainer();
    ConfigureViewModelLocator();
    await OnInitializeAsync();
}
```

Thank you.

**Comment by bartlannoeye** [comment]
This method is sealed because it implements important logic about the ViewModelLocator and the IoC container. I wouldn't open it up again, but providing a new virtual Task might be a possibility. The question is, do you still want access to the IActivatedEventArgs?

**Comment by runceel** [comment]
@bartlannoeye. Thank you for reply.

I don't want access to the IActivatedEventArgs. Because I want to initialize application model class(ex: connect twitter stream).

**Comment by bartlannoeye** [comment]
Is it an option to do that in OnLaunchApplicationAsync ?

**Comment by runceel** [comment]
OnLaunchApplicationAsync doesn't call restore case.
