### ISSUE TITLE
[Enhancement] New attribute to reduce boiler plate code

### ISSUE THREAD

**Issue by stesvis** [PrismLibrary/Prism#2338]
## Summary

Create a new `[Prism]` attribute that we can use on properties to reduce boiler plate code.

## API Changes

Right now when we create a Prism property we have this code:
```
    private string _name;
    public string Name
    {
        get { return _name; }
        set { SetProperty(ref _name, value); }
    }
```
And what would be awesome is to have an attribute to do this instead:
```
    [Prism]
    public string Name { get; set; }
```

## Intended Use Case

Save a lot of lines of code by not having to create a private field for each Prism property.
I also use ReactiveUI, and they have this great feature to go from:
```
private string name;
public string Name 
{
    get => name;
    set => this.RaiseAndSetIfChanged(ref name, value);
}
```
to:
```
[Reactive]
public string Name { get; set; }
```

I would love to have it in Prism too:
https://www.reactiveui.net/docs/handbook/view-models/boilerplate-code#read-write-properties

Please tell me that you will think about it! :)

**Comment by Codelisk** [comment]
@stesvis its called Prism.Magician :)

**Comment by brianlagunas** [comment]
Thank you for your suggestion, but this is not something that will be added to Prism. As @Codelisk pointed out, this is where Prism.Magician comes in as it provides features like that.
