### ISSUE TITLE
[Bug] Views not displayed in a StackPanel Region >>this is not a question<<

### ISSUE THREAD

**Issue by toumir** [PrismLibrary/Prism#2346]
### Steps to Reproduce

1. RequestNavigate to a region in a StackPanel Region (knowing that we have implemented a StackPanelRegionAdapter)

### Expected Behavior
View is displayed if the Region is ContentControl

### Actual Behavior
- View not displayed
- Region not found when inspecting region Manager Regions collection

### Basic Information

- Version with issue: Prism.Wpf 8.0.0.1909
- IDE: VS 2019 Version 16.8.5

### Reproduction Link
https://github.com/toumir/RegionIssueDemo

**Comment by brianlagunas** [comment]
Not a bug. You have an issue with your custom region adapter. Look very closely and see if you can find your error 😄

**Comment by toumir** [comment]
Thanks a lot Brian, this error took me a day of debugging :)
it is so simple to fix this problem, it can help other people:
**replace this Constructor :** 
`public StackPanelRegionAdapter(RegionBehaviorFactory regionBehaviorFactory) : base(regionBehaviorFactory)` 
*by this Constructor : *
`public StackPanelRegionAdapter(IRegionBehaviorFactory regionBehaviorFactory) : base(regionBehaviorFactory)` 
use Interface instead,
Thanks again Brian 👍

**Comment by brianlagunas** [comment]
Great! So glad you found it.
