### ISSUE TITLE
Dialog Serive [Bug] 

### ISSUE THREAD

**Issue by luisfernandor16** [PrismLibrary/Prism#2351]
### Steps to Reproduce

1. implement ShowDialog Async exemptions and use the ones that version 8 brings
2. when I close the dialog it sends me to page 1 of the shell
3. 

### Basic Information

- Version with issue:8.0.0.1909
- Last known good version:7.2.0.1422
- Xamarin.Forms version: 5.0.0.12
- IDE: Visual studio mac

**Comment by brianlagunas** [comment]
Closing as there is no reprodution app link provided
