### ISSUE TITLE
Typos in docs.

### ISSUE THREAD

**Issue by multinerd** [PrismLibrary/Prism#2355]
### Description

https://github.com/PrismLibrary/Prism/blob/be743c2bf7236ea7f0274efdf0567743f1c84d2b/src/Prism.Core/Properties/Resources.resx#L167

`InvalidDelegateRerefenceTypeException` should be `InvalidDelegateReferenceTypeException`. (`Reference` is spelt incorrectly)

**Comment by multinerd** [comment]
Another: 

https://github.com/PrismLibrary/Prism/blob/master/src/Prism.Core/Events/EventAggregator.cs#L16

`agnositc` should be `agnostic`

**Comment by multinerd** [comment]
Another: https://github.com/PrismLibrary/Prism/blob/master/src/Prism.Core/Events/SubscriptionToken.cs#L8

`Dispole(bool)`  should be `Dispose(bool)`

**Comment by dansiegel** [comment]
we take PRs :)

**Comment by multinerd** [comment]
I am mobile, just looking over the code. Ill submit one when I can.

**Comment by multinerd** [comment]
PR #2356
