### ISSUE TITLE
Suggestion: BindableBase should be made Serializable

### ISSUE THREAD

**Issue by furqansafdar** [PrismLibrary/Prism#236]
This is much needed because due to lack of *Serialization*, *Models* requires implementation of `INotifyPropertyChanged` to make them serialize whereas *ViewModel* can directly use `BindableBase`. This should be standardized to be used for both.

**Comment by brianlagunas** [comment]
There is nothing to serialize in the BindableBase class.  You can create your own base class that derives from BindableBase and mark that as serializable, if you require serialization.  This has been discussed in issue #57
