### ISSUE TITLE
[Bug] Navigation Fails on path with French word and accent marks

### ISSUE THREAD

**Issue by jmo-gelsight** [PrismLibrary/Prism#2360]
### Steps to Reproduce

1.  Use the Visual Studio Project Template provided by the Prism Template Pack to create a "Full WPF App" project.  (.NET Core) using Unity as the Container
2.  Change the generated ModuleNameModule.RegisterTypes and OnInitialized functions to register with (and navigate with a string "Settings".  So they should look like this:  
```
public void RegisterTypes(IContainerRegistry containerRegistry)
{
    containerRegistry.RegisterForNavigation<ViewA>("Settings");
}

public void OnInitialized(IContainerProvider containerProvider)
{
    regionManager.RequestNavigate(RegionNames.ContentRegion, "Settings");  // THIS WORKS
}
```

3.  Run the application.  It works and navigates just fine
4. Now go back to those two functions and change the string "Configure" in those two calls to the French Translation of it which is "Réglages"  So they should now look like this:

```
public void RegisterTypes(IContainerRegistry containerRegistry)
{
    containerRegistry.RegisterForNavigation<ViewA>("Réglages");
}
public void OnInitialized(IContainerProvider containerProvider)
{
    _regionManager.RequestNavigate(RegionNames.ContentRegion, "Réglages");  // FAILS
}
```

5. Run the app again.  

### Expected Behavior

Navigation should still succeed as it did when the string was "Settings"

### Actual Behavior

Navigation fails with an exception in Prism.Unity.Shared/UnityContainerExtension.cs

It would appear that the accent mark kills navigation.

### Basic Information

- Version with issue:   Prism.WPF and Prism.Unity version 8.0.0.1909
- IDE: Visual Studio 2019 version 16.9.0

### Reproduction Link

[TestPrismFullApp.zip](https://github.com/PrismLibrary/Prism/files/6087615/TestPrismFullApp.zip)

**Comment by brianlagunas** [comment]
This is by design. Prism uses URI based navigation. This means your navigation keys must be contain valid URI characters. Permitted characters within a URI are the ASCII characters for the lowercase and uppercase letters of the modern English alphabet, the Arabic numerals, hyphen, period, and underscore.
