### ISSUE TITLE
[Bug] OnNavigatedTo not called on parent page with BackAsync() navigation

### ISSUE THREAD

**Issue by WebDucer** [PrismLibrary/Prism#2363]
### Description

On Android, the OnNavigatedTo is not called on parent page, if I return to this over navigation service with BackAsync().

### Steps to Reproduce

1. Create a sample app with two pages
2. First page implement `INavigatedAware` inteface
3. Start the first page with `NavigationService.NavigateAsync($"{nameof(NavigationPage)}/{nameof(FirstPage)}");`
4. Navigate to second page with `NavigationService.NavigateAsync($"{nameof(SecondPage)}");`
5. Navigate back from second page with `NavigationService.GoBackAsync();`
6. The `OnNavigatedTo` is not called

### Expected Behavior

OnNavigatedTo should be called by back navigation.

### Actual Behavior

1. If navigating back over the "NavigationBar", the OnNavigatedTo is called
2. If navigating back over navigation service, the OnNavigatedTo is not called
3. If navigating back over "Back" button, the OnNavigatedTo is called

### Basic Information

- Version with issue: 8.0.0.1909
- Last known good version: x
- Xamarin.Forms version: 5.0.0.2012
- IDE: Rider (macOS)

**Comment by brianlagunas** [comment]
Closing for no reproduction link. Also, we have unit test covering this behavior and those tests are passing.
