### ISSUE TITLE
[Bug] Build error: SourceRoot paths are required to end with a slash or backslash.

### ISSUE THREAD

**Issue by quanljh** [PrismLibrary/Prism#2369]
### Description
When I trying to build the solution or any project, the visual studio outputs the following errors: 

`C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Roslyn\Microsoft.Managed.Core.targets(194,5): error : SourceRoot paths are required to end with a slash or backslash: 'D:\Cache\Nuget\packages'
Done building project "Prism.Core.csproj" -- FAILED.
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Roslyn\Microsoft.Managed.Core.targets(194,5): error : SourceRoot paths are required to end with a slash or backslash: 'D:\Cache\Nuget\packages'
Done building project "Prism.Core.csproj" -- FAILED.
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Roslyn\Microsoft.Managed.Core.targets(194,5): error : SourceRoot paths are required to end with a slash or backslash: 'D:\Cache\Nuget\packages'
Done building project "Prism.Core.csproj" -- FAILED.
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Roslyn\Microsoft.Managed.Core.targets(194,5): error : SourceRoot paths are required to end with a slash or backslash: 'D:\Cache\Nuget\packages'
Done building project "Prism.Core.csproj" -- FAILED.`

I found the reason is that I manually set the NuGet global-packages folder path to a folder in the D driver by overriding the NUGET_PACKAGES environment variable.
But other solutions don't have this problem, I guess may something wrong in the Packages.props file or other build settings file.
When I remove the NUGET_PACKAGES environment variable, everything turns fine. 
I need to change the NuGet global-packages folder path because my C drive space is very limited.
I am not familiar with MSBuild, can you help me to solve this problem? Thx.

### Steps to Reproduce

1. Add a NUGET_PACKAGES environment variable to change the global-packages folder path.
2. Open the solution and build.

### Expected Behavior

Build successful.

### Actual Behavior

Cannot build.

### Basic Information

- Version with issue:   Commit: 342689b
- Last known good version: ?
- IDE:  VS 2019  version: 16.8.4

**Comment by quanljh** [comment]
I found the same issues [here ](https://github.com/NuGet/Home/issues/9431), looks like the problem is the xunit package reference?

Solution: Open the Direction.Build.props file and change the

`    <SourceRoot Include="$(NuGetPackageRoot)"
                Condition="'$(NuGetPackageRoot)' != ''" />`

to

`    <SourceRoot Include="$([MSBuild]::EnsureTrailingSlash($(NuGetPackageRoot)))"
                Condition="'$(NuGetPackageRoot)' != ''" />`

**Comment by brianlagunas** [comment]
This is not a bug. The Prism source code builds on my machine, @dansiegel machine, and on our builder server. Anything you do to customize, or modify the build is your responsibility

**Comment by ronan-burke-civ** [comment]
To resolve this error: make sure your NUGET_PACKAGES system environment variable has a trailing slash at the end e.g. "C:\nuget\". You may need to do the same thing in the PATH variable if you also have your NuGet folder in the error.
