### ISSUE TITLE
Prism.AppModels.AutoInitializeAttribute is missing in 8.0

### ISSUE THREAD

**Issue by marufbd** [PrismLibrary/Prism#2376]
### Upgraded my projects nuget package from 7.2 to 8.0.0.1909

This broke all view models using autoinitializeattribute.
I did a quick search in your source code and seems Prism.AppModels.AutoInitializeAttribute is missing.

But the doc is still saying its there.
[https://prismlibrary.com/docs/xamarin-forms/auto-initialization.html](https://prismlibrary.com/docs/xamarin-forms/auto-initialization.html)

**Comment by dansiegel** [comment]
Please read the Release notes when updating... particularly to a a new Major version

**Comment by marufbd** [comment]
Thanks @dansiegel for the quick pointer.
I searched the code but i missed the release notes, my bad.
