### ISSUE TITLE
MTOUCH : error MT2101: Can't resolve the reference 'System.Threading.Tasks.Task`1<Prism.Navigation.INavigationResult> 

### ISSUE THREAD

**Issue by johng1492** [PrismLibrary/Prism#2377]
I'm Xamarin Mac, everything updated (Xcode, VS Mac, NuGet...). Everything works fine in dev to both phone and simulator.

I'm trying to ARCHIVE for iOS TestFlight and I'm getting this error:

MTOUCH : error MT2101: Can't resolve the reference 'System.Threading.Tasks.Task`1<Prism.Navigation.INavigationResult> Prism.Navigation.INavigationServiceExtensions::GoBackAsync(Prism.Navigation.INavigationService,Prism.Navigation.INavigationParameters,System.Nullable`1<System.Boolean>,System.Boolean)', referenced from the method 'System.Void Prism.Navigation.PopupExtensions/<ClearPopupStackAsync>d__7::MoveNext()' in 'Prism.Forms, Version=7.2.0.1422, Culture=neutral, PublicKeyToken=null'.

I have tried everything. ANY help would be greatly appreciated.

**Comment by dansiegel** [comment]
Issues are not a support forum and this is not a bug with Prism.

**Comment by johng1492** [comment]
Sorry. Have been working on this for 3 days to no avail. Not sure where else to turn

John Gynn

On Apr 1, 2021, at 2:37 PM, Dan Siegel ***@***.***> wrote:

﻿

Issues are not a support forum and this is not a bug with Prism.

**Comment by dansiegel** [comment]
@johng1492 for community support you can try StackOverflow or the GH Discussions... if you require actual support then you can submit a request [here](https://avantipoint.com/contact?utm_source=github.com&utm_medium=issues) for paid enterprise support.

**Comment by softlion** [comment]
@johng1492 avoid Prism for Xamarin. Having the same issue. Downgrading.

**Comment by softlion** [comment]
@johng1492 Add Prism.Forms nuget to your Android and iOS projet in addition to everywhere else. Don't rely only on Prism.DryIoc.Forms alone.

This fix the issue.

Prism.DryIoc.Forms  uses an "old" buggy version of Prism.Forms which triggers this error.
