### ISSUE TITLE
[Enhancement] Allow Execute() and CanExecute() to be overridable in DelegateCommand.cs

### ISSUE THREAD

**Issue by david-au** [PrismLibrary/Prism#2378]
## Summary

In DelegateCommand.cs, the following 2 methods are exposed but cannot be overridden by its subclass.

```
public void Execute()
       
public bool CanExecute()
```

Can they be made virtual to allow subclasses of DelegateCommand to put in specialized logic in them?

## API Changes

1. From
```
public void Execute()
```
to
```
public virtual void Execute()
```

2. From
```
public bool CanExecute()
```
to
```
public virtual bool CanExecute()
```

## Intended Use Case

If Execute() and CanExecute() can be overridden, then specialized logic, like audit logging, can be placed inside.

**Comment by brianlagunas** [comment]
This already exists and it comes from the DelegateCommandBase

**Comment by david-au** [comment]
Hi Brian,

The implementation in DelegateCommand is as below and both cannot be overridden. Can use the 'new' modifier to hide them but not the ideal approach.

```
        ///<summary>
        /// Executes the command.
        ///</summary>
        public void Execute()
        {
            _executeMethod();
        }
```

```
        /// <summary>
        /// Determines if the command can be executed.
        /// </summary>
        /// <returns>Returns <see langword="true"/> if the command can execute,otherwise returns <see langword="false"/>.</returns>
        public bool CanExecute()
        {
            return _canExecuteMethod();
        }
```

Cheers,
David

**Comment by brianlagunas** [comment]
The guidance has always been to derive from `DelegateCommandBase` if you want to add custom implementations. I'm not sure how I feel about making `Execute` and `CanExecute` virtual.
