### ISSUE TITLE
Lightinject for Prism

### ISSUE THREAD

**Issue by mojtabakaviani** [PrismLibrary/Prism#238]
[Lightinject](http://www.lightinject.net) is fastest Ioc. please make Lightinject for Prism

**Comment by tomzorz** [comment]
It's easy to integrate your IoC solution of choice with PRISM, just look at the Prism.Unity sample :)

**Comment by brianlagunas** [comment]
And then submit a PR :)

**Comment by brianlagunas** [comment]
There hasn't been any further interest in this and no PR has been received, so I'm closing it.
