### ISSUE TITLE
Sample Regions Demo throws exception when Content is added to ContentControl. Complains about ContentControl region adapter not there

### ISSUE THREAD

**Issue by stevensrf11** [PrismLibrary/Prism#2386]
### Description
Not much to say.
Add Content to the Sample Regions download application.
Run  the Regions application i

n Visual Studio 2019 and an exception is thrown complaining the ContentControl needs a region adapter created,

ContentControl prism:RegionManager.RegionName="ContentRegion" Content="Shell Content"  

[02-Regions.zip](https://github.com/PrismLibrary/Prism/files/6297012/02-Regions.zip)
![Untitled](https://user-images.githubusercontent.com/22349374/114400686-d60c5000-9b67-11eb-9b17-315943bd4a70.png)

### Steps to Reproduce

1. 
2. 
3. 

### Basic Information

- Version with issue:
- Last known good version:
- Xamarin.Forms version:
- IDE:

**Comment by dansiegel** [comment]
If there is an issue with the samples repo you should report the issue there appropriately.

**Comment by stevensrf11** [comment]
HEY DAN  create a new WPF Application just like the sample regions application.
Add a content to the content control and watch the exception happen

**Comment by brianlagunas** [comment]
See #2389

**Comment by stevensrf11** [comment]
It no big deal

Probably my fault

 
 

Sent: Monday, April 12, 2021 at 8:57 AM
