### ISSUE TITLE
ROFL Choose Latest PRISM Dryioc to wpf application and error The package reference 'Prism.DryIoc' should not specify a version

### ISSUE THREAD

**Issue by stevensrf11** [PrismLibrary/Prism#2388]
### Description
This is getting ridiculous or I am just not doing something right.
I create a Net Core 3.1 application.
I added the last version of Prism.DryIoc to the application and after installation this error was shown 

Error		The package reference 'Prism.DryIoc' should not specify a version.  Please specify the version in 'G:\prism folders\prism8net5\samples\Prism-Samples-Wpf-master - Copy\Packages.props' or set VersionOverride to override the centrally defined version.	Regionsa	G:\prism folders\prism8net5\samples\Prism-Samples-Wpf-master - Copy\Regionsa\Regionsa.csproj	1	

### Steps to Reproduce

1. 
2. 
3. 

### Basic Information

- Version with issue:
- Last known good version:
- Xamarin.Forms version:
- IDE:

**Comment by dansiegel** [comment]
@stevensrf11 this is not a bug with Prism, nor is your issue even related to the main Prism repo.
