### ISSUE TITLE
ContentControl region adapter exception when Content set directly

### ISSUE THREAD

**Issue by stevensrf11** [PrismLibrary/Prism#2389]
### Description
Not much to say.
Create a WPF net core 3.1 application.
Add the latest Prism DryIoc package.
Put a ContentControl with the Content set directly and give that ContentControl a region name.

Run the Regions application in Visual Studio 2019 and an exception is thrown complaining the ContentControl needs a region adapter created,

ContentControl prism:RegionManager.RegionName="ContentRegion" Content="Shell Content"
 
Same exception occurs if Prism Unity is used instead of Prism.DryIoc

[WpfApp1.zip](https://github.com/PrismLibrary/Prism/files/6297346/WpfApp1.zip)

![Untitled](https://user-images.githubusercontent.com/22349374/114408948-8df12b80-9b6f-11eb-8674-e0816f2914fc.png)

### Steps to Reproduce

1. 
2. 
3. 

### Basic Information

- Version with issue:
- Last known good version:
- Xamarin.Forms version:
- IDE:

**Comment by brianlagunas** [comment]
Did you read the exception?

```
---> Prism.Regions.Behaviors.RegionCreationException: An exception occurred while creating a region with name 'ContentRegion'. The exception was: System.InvalidOperationException: ContentControl's Content property is not empty. 
    This control is being associated with a region, but the control is already bound to something else. 
```

You cannot set the `Content` property of the ContentControl you are using as a region

**Comment by stevensrf11** [comment]
Oh Ok.

**Comment by stevensrf11** [comment]
I took the content out and the exception still happens

**Comment by brianlagunas** [comment]
No it doesn't.

**Comment by brianlagunas** [comment]
Also, you need to remove `StartupUri="MainWindow.xaml"` from your app.xaml.

**Comment by stevensrf11** [comment]
Yea I was coding so many new trial applications that I was overlooking the obvious.

 
 

Sent: Monday, April 12, 2021 at 12:42 PM

**Comment by stevensrf11** [comment]
Well i read the first couple words of the exception

 
 

Sent: Monday, April 12, 2021 at 9:22 AM
