### ISSUE TITLE
ModuleDependencyAttribute does it work when all modules are DirectoryLoading?

### ISSUE THREAD

**Issue by stevensrf11** [PrismLibrary/Prism#2394]
### Description
In a Prism application I load modules via directory loading
All the modules are in the same directory .
One of the module classes uses the  ModuleDependencyAttribute.
When running the application the following exception is thrown:

A module declared a dependency on another module which is not declared to be loaded. Missing module(s): ServicesModule

Dpeas ModuleDependencyAttribute does it work when all modules are DirectoryLoading?

### Steps to Reproduce

1. 
2. 
3. 

### Basic Information

- Version with issue:
- Last known good version:
- Xamarin.Forms version:
- IDE:

**Comment by brianlagunas** [comment]
Closed for no repo
