### ISSUE TITLE
[Bug] XAML navigation forces button to take the default text color

### ISSUE THREAD

**Issue by Tum4ik** [PrismLibrary/Prism#2399]
### Description

The Prism XAML navigation forces button to take the default text color before the navigated page is shown. However the navigation via binded command works as expected without changing the color (see gif animation below).

### Steps to Reproduce

1. Set Android default text color
**styles.xml**
```xml
<style name="MainTheme" parent="MainTheme.Base">
    <item name="android:textColor">#FFFF0000</item>
</style>
```
2. Create two button to navigate
**MainPage.xaml**
```xaml
<Button Text="ExpectedNavigationBehavior"
        FontAttributes="Bold"
        TextColor="Gray"
        BackgroundColor="Black"
        Command="{Binding ExpectedNavigationBehaviorCommand}" />
<Button Text="ProblemNavigationBehavior"
        FontAttributes="Bold"
        TextColor="Gray"
        BackgroundColor="Black"
        Command="{prism:NavigateTo Name=PageToNavigate}" />
```
**MainPageViewModel.cs**
```csharp
private DelegateCommand _expectedNavigationBehaviorCommand;
public DelegateCommand ExpectedNavigationBehaviorCommand =>
    _expectedNavigationBehaviorCommand ?? (_expectedNavigationBehaviorCommand = new DelegateCommand(ExpectedNavigationBehavior));

private async void ExpectedNavigationBehavior()
{
    await NavigationService.NavigateAsync("PageToNavigate");
}
```
3. Click those buttons and notice visual behavior.

### Expected Behavior
The "ProblemNavigationBehavior" button **MUST NOT** change its text color to default (currently red) right before navigation happens.

### Actual Behavior
The "ProblemNavigationBehavior" button changes its text color.

### Basic Information

- Version with issue: 8.0.0.1909
- Last known good version: -
- Xamarin.Forms version: 5.0.0.2012
- IDE: Visual Studio Community 2019 (Version 16.9.4)

### Screenshots

![2021-04-17_14-05-54](https://user-images.githubusercontent.com/21317790/115111051-1401dd80-9f87-11eb-84ee-49ad8909fe18.gif)

On the gif animation you could see that "ProblemNavigationBehavior" button text becomes red for a moment before navigation.

### Reproduction Link

https://github.com/Tum4ik/prism-xaml-navigation-problem

**Comment by dansiegel** [comment]
This is certainly interesting, by design Prism doesn't do anything to set colors/styles or really ever touch the native platform... The Navigation XAML Extension simply returns itself as an ICommand. @PureWeen any thoughts what might be causing this?

**Comment by dansiegel** [comment]
Looking at this a little closer, this is by design. While Prism does not change the Text color, we do Raise CanExecuteChanged telling the button that we cannot execute a second time while the Command is currently executing. Because CanExecute changes from `true` to `false`, the button becomes disabled while the command is executing thus changing the color of your button text. From your code snippet you have no such logic, thus CanExecute never changes on your command and the user could double tap the button.

**Comment by Tum4ik** [comment]
ah.. I understand.. Thank you, @dansiegel !
