### ISSUE TITLE
[Win10 UAP] Unable to inject own INavigationService

### ISSUE THREAD

**Issue by bartlannoeye** [PrismLibrary/Prism#24]
_This is an issue on the current Prism for store (Win8/8.1 RT) implementation. Logged considering we're taking it forward to Win10 (after \\\\Build?) and keep it in the current lightweight form. API changes in Win10 might have impact on the logged issue._

The current implementation of Prism for Windows Runtime creates its own INavigationService object in MvvmAppBase.InitializeFrameAsync(). This creation is private and hard-wired to FrameNavigationService. Using your own implementation of INavigationService requires some dirty coding.

```cs
private INavigationService CreateNavigationService(IFrameFacade rootFrame, ISessionStateService sessionStateService)
{
    var navigationService = new FrameNavigationService(rootFrame, GetPageType, sessionStateService);
    return navigationService;
}
```

**Comment by brianlagunas** [comment]
As you eluded to, Prism for WinRT is not support in this version, and is likely to be deprecated in favor of new guidance for the Windows UAP platform.  When we start looking at Prism for UAP, we will be looking at improvements to the navigation service altogether.

**Comment by briannoyes** [comment]
Bart could you confirm this is solved now?

**Comment by briannoyes** [comment]
@bartlannoeye Ping - this one still an issue?

**Comment by bartlannoeye** [comment]
I've checked the code for PrismApplication and the method mentioned above is still private, but some deeper research opens up an alternative solution.

The NavigationService property is editable, so you're able to set it to your own implementation after the base class completed InitializeFrameAsync. The only thing missing if you would set the NavigationService property is restoring state (PrismApplication line 222) which could be done by the implementer of the new service. If someone would want to set his own NavigationService, it should be done by overloading OnLaunched and setting the property after calling base.OnLaunched.

Knowing how rare it is for someone to have to implement his own NavigationService, I think above scenario is flexible enough. Making the CreateNavigationService overridable (or provide another hook) would maybe make it too complex, making regular Prism users wonder why this is possible to override.
