### ISSUE TITLE
[Enhancement] Mark Prism.Mvvm.BindableBase as Serializable 

### ISSUE THREAD

**Issue by YounesCheikh** [PrismLibrary/Prism#2402]
## Summary

In a WPF application, I have some objects inheriting from Prism.Mvvm.BindableBase class, 
The request is to be able to Set these objects in the Clipboard to do some copy paste operations from WPF Control.
It seems that it's not possible to set an object as data in the clipboard if it's not marked as serializable, because I get the following error: 

`System.Runtime.Serialization.SerializationException: 'Type 'Prism.Mvvm.BindableBase' in Assembly 'Prism, Version=8.0.0.1909, Culture=neutral, PublicKeyToken=40ee6c3a2184dc59' is not marked as serializable.'
`

The error above is happening when trying to set the object directly in the clipboard, I tried to convert the object to Json but this step requires also to have the object serializable. 

Is it possible to add the attribute [Serializable] for the object Prism.Mvvm.BindableBase ? Is there any cost in term of performance marking this object as serializable? 

Thanks in advance,

**Comment by brianlagunas** [comment]
Thanks for the suggestion, but this is not something we will be adding to Prism. BindableBase is just a helper class for INotifyPropertyChanged. You should use your own base class if you need it to be marked serializable.
