### ISSUE TITLE
[Bug]  Error during dynamic loading MOdule

### ISSUE THREAD

**Issue by kyooi93** [PrismLibrary/Prism#2408]
### Steps to Reproduce

1. Using Entity Framework Core 3.1.14
2. 
3. 

### Expected Behavior
Auto loading dynamic module.
### Actual Behavior
Error during loading module

### Basic Information

- Version with issue:
- Last known good version:
- Xamarin.Forms version: WPF 
- IDE: Visual Studio

### Screenshots
![image](https://user-images.githubusercontent.com/71051053/115513202-61e35200-a2b5-11eb-85f1-3dbfe8ce41d3.png)

**Comment by dansiegel** [comment]
Closing. You have not followed the issue template or provided a reproduction.

**Comment by brianlagunas** [comment]
You're also using a custom module loader, which will not be supported.
