### ISSUE TITLE
[Bug] Prism.Forms.Regions can't be used with Jetbrains Rider

### ISSUE THREAD

**Issue by albilaga** [PrismLibrary/Prism#2413]
### Description

Not sure if this should be reported it here or to Rider. I am using Jetbrains Rider on mac and can't use region in Xamarin.Forms. Same project working on VS for mac

### Steps to Reproduce

1. Use this sample https://github.com/CrossGeeks/PrismRegionsXFSample/
2. Run in Rider.

### Expected Behavior
App working like in Visual studio for mac

### Actual Behavior
App not working with when navigating get error message `The region manager does not contain the HomeRegion region.`

### Basic Information

- Version with issue: 8.0.0.1909
- Last known good version: -
- Xamarin.Forms version: 5.0.0.2012
- IDE: JetBrains Rider 2021.1.2

### Reproduction Link
https://github.com/CrossGeeks/PrismRegionsXFSample/

**Comment by brianlagunas** [comment]
IDE support is not within the scope of Prism. If you are having issues with Rider, you need to reach out to the Rider team.

**Comment by jameslavery** [comment]
@albilaga - did you find a solution to this? I've got the same problem. Works with VS for Mac, but not with Rider.

**Comment by jameslavery** [comment]
There's a bug raised against Rider for this. Apparently it only manifests if Hot Reload is enabled. Turning Hot Reload off fixes it. Although then you lose the advantages of Hot Reload!
