### ISSUE TITLE
[Bug] [XF] Flyout page menu item navigation does not work

### ISSUE THREAD

**Issue by vardansargsyan92** [PrismLibrary/Prism#2435]
### Description

I have updated the Prism library, and I have changed the master details page to the flyout page. The problem is that I am not able to use menu item navigation inside the flyout page's view model. I am trying to use the following:
` await NavigationService.NavigateAsync($"NavigationPage/{menuItem.Page}");`
but it does not work. So the question is, how can I use menu item navigation inside the view model?

I also noticed that the **PageNavigationService** does not handle a case for **flyout page** inside **ProcessNavigation** method

### Steps to Reproduce

1. Open the sample 
2. Run the application
3. Tap on menu item and try to navigate to the menu item page.

### Expected Behavior

When I tap on menu item I should be navigated to the corresponding menu item page. 

### Actual Behavior

The navigation does not happen. 

### Basic Information

- Version with issue: 8.0.0.1909
- Last known good version: --
- Xamarin.Forms version: 5.0.0.2012
- IDE: Visual Studio

### Screenshots

_N/A_

### Reproduction Link

[FlyoutPageSample.zip](https://github.com/PrismLibrary/Prism/files/6435052/FlyoutPageSample.zip)

**Comment by dansiegel** [comment]
FlyouPage is only supported in Prism 8.1.

**Comment by LucasCordova** [comment]
Hello! I have been trying to get FlyoutPage to work with Prism 8.1.97 and ViewModels with no success for days. Is this supported?  Is there an example somewhere?   If it's helpful, I can post an example of what I'm doing, but I also tried the sample posted on this issue and after upgrading it to Prism 8.1.97, have been unable to get it to work either.   Many thanks!
