### ISSUE TITLE
[UWP]Prism.Unity throw NullReferenceException at release build.

### ISSUE THREAD

**Issue by runceel** [PrismLibrary/Prism#244]
I use Prism.Unity. I build release mode. I run application.  Application is crush, throw NullReferenceException at DebugLogger line 25.

stack trace is here(sorry. this stack trace is japanese):

```
   場所 Prism.Logging.DebugLogger.Log(String message, Category category, Priority priority) (C:\Users\Kazuki\Source\Repos\Prism\Source\Prism\Logging\DebugLogger.cs):行 25
   場所 Prism.Unity.Windows.PrismUnityApplication..ctor() (C:\Users\Kazuki\Source\Repos\Prism\Source\Windows10\Prism.Unity.Windows\PrismUnityApplication.cs):行 33
   場所 App1.Program.<>c.<Main>b__0_0(ApplicationInitializationCallbackParams p) (C:\Users\Kazuki\Source\Repos\Prism\Source\App1\obj\x86\Release\App.g.i.cs):行 24
   場所 Windows.UI.Xaml.ApplicationInitializationCallback__Impl.Vtbl.Invoke__STUB(IntPtr pComThis, Vtbl** unsafe_p) (c:\Users\Kazuki\Source\Repos\Prism\Source\App1\obj\x86\Release\ilc\intermediate\App1.Interop\ImplTypes.g.cs):行 64279
```

I debug application. But I don't understand this behavior.
Are you sure you want to reproduce the direction of the other?

**Comment by runceel** [comment]
Additional Info.

Maybe, this error has occurred in a non-English environment.

- open Package.appxmanifest
- edit Language ja-JP
- change release
- build application
- run application
- crush application

**Comment by briannoyes** [comment]
That sounds possible. The logging statements that were in there from Prism for Windows Runtime used a localizable template string and it is probably looking for using a ResourceLoader. It may be looking for a satellite assembly for ja-JP and not finding it and not falling back properly. I just checked in updates to the PrismApplication, PrismUnityApplication, and PrismAutofacApplication classes to get rid of the sealed on a couple of the methods. I also added some logging down at the base class level. If you could try with that latest code and see where it is throwing exactly, that would be very helpful in tracking it down. Hope to get nugets updated with a new release within a day or two.

**Comment by runceel** [comment]
Hi.
I tested other japanese people environment.
This error hasn't occurred in other people environment.

My environment is broken. Sorry.
