### ISSUE TITLE
Question about potentially scalability issues with MVVM and popup windows

### ISSUE THREAD

**Issue by ConstantinPatak** [PrismLibrary/Prism#246]
Hello,

I am currently working on a project and I am using the Prism framework with the MVVM pattern. I followed the ViewModel first approach for the project. I noticed, and please correct me if I am wrong, that when you use the InteractionRequest pattern to show popup windows, the UserControl that is the content of the popup window and the ViewModel of that UserControl instantiates only once, when the program start, and every time the popup opens and closes it uses the same instances.

I want to ask if there are any potential scalability issues with this? An application with many popup windows can be scaled? Because as I understand all the popup windows contents and the popup windows ViewModels are being loaded in the memory when the program starts.

Thanks in advanced,
Constantin Patak

**Comment by brianlagunas** [comment]
For this scenario, I would recommend using a dialog service instead of the InteractionRequest.

**Comment by ConstantinPatak** [comment]
Hi Brian,

Thank you for your response.
