### ISSUE TITLE
[Bug] Prism 8.1.97 Xamarin.Forms 5.0.0.2012 Flyout Page Detail NavigateAsync open always modal page

### ISSUE THREAD

**Issue by giuseppenovielli** [PrismLibrary/Prism#2468]
### Description

After open Flyout Page into Xamarin Forms's app when push a detail page with Prism NavigationService, open always modal page.

`navResult = await NavigationService.NavigateAsync(nameof(NavigationPage) + "/" +nameof(Page1Page));` -->Open Modal Page, instead, Push page into Flyout Detail's navigation.

Clone also 
https://github.com/giuseppenovielli/XF-Prism-Full-Navigation-Example/releases/tag/8.0.0.1909
With prism 8.0.0.1909 work as expected!

I'm missed something, when push page?

PS I'm using .NET Core, not .NET 5

Thanks!!

### Steps to Reproduce

1. Clone repository https://github.com/giuseppenovielli/XF-Prism-Full-Navigation-Example
2. Run App into iOS simulator
3. Click button -> 'PushMasterDetailPage'
4. Open Left Menu
5. Select 'PageParameters' or 'TabbedPage'

### Expected Behavior
Page pushed as Flyout detail

### Actual Behavior
Page pushed as modal page

### Basic Information
- Version with issue: 8.1.97
- Last known good version: 8.0.0.1909
- Xamarin.Forms version: 5.0.0.2012
- IDE: Visual Studio For Mac

### Reproduction Link
https://github.com/giuseppenovielli/XF-Prism-Full-Navigation-Example

**Comment by DaviBittencourt** [comment]
Any predictions for this solution? I'm having the same problem, having to go back to version 8.0.0.1909 unfortunately

**Comment by giuseppenovielli** [comment]
@dansiegel when you will analyze this bug? Thanks!!

**Comment by brianlagunas** [comment]
This is not a bug. The sample provided uses a different VM for the [FlyoutPage.Flyout](https://github.com/giuseppenovielli/XF-Prism-Full-Navigation-Example/blob/master/PrismFullNavigation/PrismFullNavigation/Views/MenuPage.xaml#L10). This is not allowed. The Flyout must use the same VM as the FlyoutPage in order to function properly.

**Comment by giuseppenovielli** [comment]
Thanks you so much @brianlagunas !!

@DaviBittencourt i update my repository and fix this issue.

FlyoutPage.Flyout Page must use the same ViewModel of FlyoutPage.

https://github.com/giuseppenovielli/XF-Prism-Full-Navigation-Example/blob/514871a2cb2b903fd7836ad64c43415a34daea33/PrismFullNavigation/PrismFullNavigation/Views/MenuPage.xaml#L8

**Comment by davibittencourtome** [comment]
Thanks you so much @brianlagunas ! 

Thanks for the code @giuseppenovielli , we arrived at the same solution.
