### ISSUE TITLE
[Bug] RegionManagerRegistrationBehavior adds a region twice when detects that a different region manager was previously attached

### ISSUE THREAD

**Issue by codingdna2** [PrismLibrary/Prism#2471]
### Description

RegionManagerRegistrationBehavior adds a region twice when detects that a different region manager was previously attached to a view. This happens when using scoped regions while re-using an existing control attached to another region manager.

### Steps to Reproduce

```cs
using System;
using System.Windows.Controls;
using DryIoc;
using Prism.DryIoc;
using Prism.Ioc;
using Prism.Regions;
using Prism.Regions.Behaviors;

namespace Issue
{
    class Program
    {
        [STAThread]
        static void Main(string[] args)
        {
            // Initialize infrastructure
            ContainerLocator.SetContainerExtension(() => new DryIocContainerExtension(new Container(DryIocContainerExtension.DefaultRules)));
            var container = ContainerLocator.Current;
            var regionBehaviorFactory = new RegionBehaviorFactory(container);
            var regionManager = new RegionManager();

            var regionAdapterMappings = container.Resolve<RegionAdapterMappings>();
            IRegionAdapter adapter = new ContentControlRegionAdapter(regionBehaviorFactory);
            regionAdapterMappings.RegisterMapping(typeof(ContentControl), adapter);
            container.Register<DelayedRegionCreationBehavior>(() => new DelayedRegionCreationBehavior(regionAdapterMappings));

            // Initialize controls            
            var childControl = new ContentControl();
            var child = new UserControl() { Content = childControl };
            
            var parentControl = new ContentControl();
            var parent = new UserControl() { Content = parentControl };

            // Create parent region
            SingleActiveRegion parentRegion = (SingleActiveRegion)adapter.Initialize(parentControl, "Region1");            
            var behavior = new RegionManagerRegistrationBehavior()
            {
                HostControl = parentControl,
                Region = parentRegion
            };
            behavior.Attach();
            RegionManager.SetRegionManager(parent, regionManager);

            // Create child region
            SingleActiveRegion childRegion = (SingleActiveRegion)adapter.Initialize(childControl, "Region2");
            var behavior1 = new RegionManagerRegistrationBehavior()
            {
                HostControl = childControl,
                Region = childRegion
            };
            behavior1.Attach();
            RegionManager.SetRegionManager(child, regionManager);

            // Add control to region
            regionManager.AddToRegion("Region1", child);            

            // Remove it
            parentRegion.Remove(child);

            // Create scoped region
            var scopedRegion = regionManager.CreateRegionManager();
            RegionManager.SetRegionManager(parent, scopedRegion);
            scopedRegion.AddToRegion("Region1", child);
        }
    }
}
```

### Expected Behavior

The expected behavior is to have the inner region added once.

### Actual Behavior

The inner region is added twice as the `UpdateRegions` is called in `RegionCollection.Remove`. The issue arise in `RegionManagerRegistrationBehavior.TryRegisterRegion()` when the call `attachedRegionManager.Regions.Remove(this.Region.Name);` is made.

### Basic Information

- Version with issue: 8.1.97

### Reproduction Link
[PrismIssue.zip](https://github.com/PrismLibrary/Prism/files/6568798/PrismIssue.zip)

**Comment by codingdna2** [comment]
### Possible solutions

I think there's many ways to fix this issue while respecting the authors concerns of breaking things as noted in #953. 
Let's see some (I would do a PR but I would like authors how they prefer to proceed):

1. The shortest solution would be to change the `if` at line an `else if`. While it's functional, it relies on the knownledge of `RegionManagerRegistrationBehaviorFixture` that a re-entrant call would happen, breaking the SoC pattern. **BAD DESIGN**

```cs
private void TryRegisterRegion()
{
    DependencyObject targetElement = this.HostControl;
    if (targetElement.CheckAccess())
    {
        IRegionManager regionManager = this.FindRegionManager(targetElement);

        IRegionManager attachedRegionManager = this.GetAttachedRegionManager();

        if (regionManager != attachedRegionManager)
        {
            if (attachedRegionManager != null)
            {
                this.attachedRegionManagerWeakReference = null;
                attachedRegionManager.Regions.Remove(this.Region.Name);
            }
            else if (regionManager != null)     // <= HERE
            {
                this.attachedRegionManagerWeakReference = new WeakReference(regionManager);
                regionManager.Regions.Add(this.Region);
            }
        }
    }
}
```

2. The highest risk modification is to implement an update flag. As stated in #953 the effects are unknown. **RISKY**

3. The safest solution would be to read again the state of the region managers between operations.

```cs
private void TryRegisterRegion()
{
    DependencyObject targetElement = this.HostControl;
    if (targetElement.CheckAccess())
    {
        IRegionManager regionManager = this.FindRegionManager(targetElement);

        IRegionManager attachedRegionManager = this.GetAttachedRegionManager();

        if (attachedRegionManager != null && regionManager != attachedRegionManager)
        {
            this.attachedRegionManagerWeakReference = null;
            attachedRegionManager.Regions.Remove(this.Region.Name);

            attachedRegionManager = this.GetAttachedRegionManager();
            regionManager = this.FindRegionManager(targetElement);
        }

        if (regionManager != null && regionManager != attachedRegionManager)
        {
            this.attachedRegionManagerWeakReference = new WeakReference(regionManager);
            regionManager.Regions.Add(this.Region);
        }
    }
}
```

5. The IRegionCollection can be modified to allow some kind of mechanism to do both operations transactionally. Call UpdateRegions() can be made when both operation complete. **COMPLEX**

### Final consideration

The `attachedRegionManager` check seems intended for scoped region handling and I think it should be fixed. All in all I don't see it too risky if approached as in (3). It's not elegant and that's why I'm inclined for (1). The reasoning here is that scoped regions are supported but they would probably require a refactor to improve and (1) is a compromise.

### Workaround (as suggested in #953) not applicable

The workaround suggested in #953 (`view.ClearValue(RegionManager.RegionManagerProperty);`) seems not applicable to me as it requires the knowledge of the inner view.

**Comment by brianlagunas** [comment]
I'm not sure what you're doing, but I'm pretty sure it isn't the right way. This is not a bug, as Prism is not designed to handle situations were region managers are changed for a view instance at runtime. That should not be happening.  Once a region manager is set for a view, it should stay set to that region manager instance.

I don't know why you want to do this, but have you tried just clearing the region manager before setting it again?

**Comment by codingdna2** [comment]
I wrote an adapter for DevExpress TabControl and the scenario I'm trying to handle is a tab tear-off to a new window. The view of course is already created and I create a scoped region for the new window and tabcontrol. But I guess a drag-n-drop scenario is really similar.

I disagree it's not a bug, the function suggests that a different region manager can be attached and removed before attaching the new one. But you are the owner so I'm left with no much choice. I wasted so much time detailing the bug, I hoped you would a least asked before closing the issue.

**Comment by codingdna2** [comment]
Clearing the region manager doesn't work either.. the inner control is added twice in the new region manager (which is empty)..

**Comment by brianlagunas** [comment]
You should not be creating multiple region managers for a single view instance. Your approach is wrong.

**Comment by codingdna2** [comment]
It's like a browser. There's a TabControl for every shell. When you tear-off a tab, you can move it to an existing shell or to a new shell. But most important, when you shift-click a link in tab a new tab is created in the current shell and not in the main shell. Your pluralsight courses indicate a regionmanager per shell is the way to go (and I agree with that). But then a tab can have a sub-region and that is added twice when moved to a new region manager (and it's something I cannot change as I use a DevExpress control which use the same TabItem instance).

Despite the scenario, Prism seems to expect that a view can change region manager (why the RegionManagerRegistrationBehavior.TryRegisterRegion() checks it in first place?) 
But that same check, ends up adding the sub-region twice. I cannot avoid this issue as the check is based on an internal weak reference.

**Comment by brianlagunas** [comment]
I am telling you, your approach is wrong. The shell doesn't matter. Only using the correct region manager instance matters. I have implemented this many times in other customer apps for every control vendor, not just DevEx.

**Comment by codingdna2** [comment]
You stated two thing:
1. You should not be creating multiple region managers for a single view instance
2. Only using the correct region manager instance matters

Which implies that multiple region manager are the way to go, but not with the same view instance. But I told you that is Dx that inject the view in the control. I just add the corrisponding view in my custom behavior. And I do add it to the right region manager.

Beside my approach, I don't understand why you don't see a bug in Prism adding the region twice. Have you at least run the minimal repro? 

PS: of course my app is not a browser but a complex LOB app.
