### ISSUE TITLE
[Bug] WinUI 3 Desktop -->Dialog Service errors out when resolved from the View Model

### ISSUE THREAD

**Issue by MarkBQE** [PrismLibrary/Prism#2472]
### Steps to Reproduce

Just add few views and view models and trigger the dialog service from the view model. Built in Content Dialog seems to work fine after setting the XamLRoot. Not sure where you are setting the XAM root for the user control used in Prism dialog service. I have set the XAMRoot in the App.Xaml.cs , not sure why  dialog service seems to ignore it. Other than that I was able to port RegionAdapters, Event Aggregators, Region Behaviors and everything Prism related from an old WPF app to WinUi3 desktop app without any issues. For now I am using built in Content Dialog with event aggregators to show the notifications and it seems to be working well. @jeromelaban  when you have a some time you may want to look into this. This port has been seamless for me, thanks for all the hard work bringing Prism to WinUI 3 Desktop. It seems in the dialog service we need to set the set the XAML root for the content dialog, please see the remarks section here in the docs https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.contentdialog?view=winrt-20348#remarks

![image](https://user-images.githubusercontent.com/23547957/120247306-db148400-c227-11eb-9b46-575cf94fb77a.png)

### Expected Behavior
Should be able to resolve dialog service for any view model tied to a view injected in any region.
### Actual Behavior
Unable to resolve the dialog services from the view model
### Basic Information

- Version with issue: 8.1
- Last known good version: none
- IDE: Visual Studio 2019

### Screenshots
![image](https://user-images.githubusercontent.com/23547957/120247102-3eea7d00-c227-11eb-958b-b0b461784d2d.png)

![image](https://user-images.githubusercontent.com/23547957/120247560-c389cb00-c228-11eb-8454-dc8b512f3414.png)

**Comment by jeromelaban** [comment]
Thanks for your kind words, and I'm glad this is working well for you.

This particular piece of code is indeed needed to get dialogs working. It is implemented this way in the e2e sample application here:
https://github.com/PrismLibrary/Prism/blob/15140a61976d0a224cd6ebb9ee1f7ca63db02b47/e2e/Uno/HelloUnoWorld.Shared/App.xaml.cs#L151
and here:
https://github.com/PrismLibrary/Prism/blob/15140a61976d0a224cd6ebb9ee1f7ca63db02b47/e2e/Uno/HelloUnoWorld.Shared/Dialogs/CustomContentDialog.xaml.cs#L27

I did not take a service configuration API design decision on purpose, trying to see if the community would find a best way to handle this situation.

**Comment by MarkBQE** [comment]
In-fact you have implemented that in the e2e code. However current approach  of  setting XAML root  will always set the XAML Root to null. Please see the snippet below how I was able to set the XAML Root, however looking at the Prism UNO dialog service code we are not setting the XAML Root for the Content Dialog anywhere, perhaps I will write my own implementation of Dialog Service where I can set the Xaml Root before I show the Dialog 

![image](https://user-images.githubusercontent.com/23547957/120387552-e971a700-c2de-11eb-8141-dce904cb3c82.png)

**Comment by MarkBQE** [comment]
FYI I was able to implement the "Custom Dialog" with your guidance in WinUi3. Thank you for all your help.
