### ISSUE TITLE
[Bug] [WPF] The Inavigationaware Interface  Problem, Why Just exec OnNavigatedFrom.

### ISSUE THREAD

**Issue by sanshiliuxiao** [PrismLibrary/Prism#2480]
### Description

I'm trying to use [Prism](https://github.com/PrismLibrary/Prism) and [HandyControl](https://github.com/HandyOrg/HandyControl) to create a project, **but now I have a very strange problem.**

I have three views (A, B, CWithParameters) whose ViewModel inherits Inavigationaware. 

If I click  the button (`ViewA` or `ViewB`), It can execute three functions in turn (`OnNavigatedFrom`、`IsNavigationTarget`、`OnNavigatedTo`).

But, if I click the button (`ViewC`), it just execute the `OnNavigatedFrom`.

All three views perform the same operation. Why do they have different results **It's so strange!!**

### Basic Information
- Version with issue: Prism.Unity 8.1.97 [WPF]
- IDE: Visual Studio 2019

### Screenshots
![2.gif](https://i.stack.imgur.com/bY7tu.gif)

![3.gif](https://i.stack.imgur.com/ACbyx.gif)

### Reproduction Link

This is My Github repo:  [https://github.com/sanshiliuxiao/PrismRegionWithHcTabControl](https://github.com/sanshiliuxiao/PrismRegionWithHcTabControl)

(If you know Chinese, you can see the principle of my implementation) 
My Blog: [http://sanshiliuxiao.top/notebook/CSharp/20210611-PrismWithTabControl/](http://sanshiliuxiao.top/notebook/CSharp/20210611-PrismWithTabControl/)

**Comment by sanshiliuxiao** [comment]
After testing, it is found that when  `IRegionManager.RequestNavigate` 's `navigationParameters` parameter is not null, only l will be triggered  `OnNavigatedFrom` ;

**Comment by sanshiliuxiao** [comment]
Ohhhh!!! I know why there is such a bug.

I Have two views， one is ViewA( ` ViewName = ViewA`, the url source is `ViewA`), one is ViewA (But `ViewName =ViewAA`, the url source is `ViewAA`).  

The key is here： `Prism.Wpf.RegionNavigationContentLoader.cs`

```csharp

private bool ViewIsMatch(object v, string navigationSegment)
{

  var names = new[] { v.GetType().Name, v.GetType().FullName, (v as IViewName).ViewName };
  return names.Any(x => x.Equals(navigationSegment, StringComparison.Ordinal));
}
private static bool ViewIsMatch(Type viewType, string navigationSegment)
{
    var names = new[] { viewType.Name, viewType.FullName };
    return names.Any(x => x.Equals(navigationSegment, StringComparison.Ordinal));
}
```
the `navigationSegment` is `ViewAA`,  So, Can't to match.

**Comment by brianlagunas** [comment]
There are a lot of issues with your code. You are implementing a lot of poor coding choices that are not recommended by the Prism team.   Also, there is no need to have the same view registered with different names. Only register a specific view type once.

**Comment by sanshiliuxiao** [comment]
> There are a lot of issues with your code. You are implementing a lot of poor coding choices that are not recommended by the Prism team. Also, there is no need to have the same view registered with different names. Only register a specific view type once.

Thinks, you are right, I'm just trying this function, Because someone asked me if I could have the same view registered with different names.
