### ISSUE TITLE
[Bug]  Parameters are not passed to all pages when using deep linking and query strings

### ISSUE THREAD

**Issue by Huaba93** [PrismLibrary/Prism#2483]
### Description
When adding multiple pages to the navigation stack at once (deep linking) and using HTML query strings to pass parameters, not all pages receive the navigation parameters.

### Steps to Reproduce

1.  Push multiple pages at once to the navigation stack eg. `NavigateAsync("Page1/Page2")`
2.  Use query string to pass parameters eg. `NavigateAsync("Page1/Page2?Test=true")`

### Expected Behavior
`Page1` and `Page2` should receive the same parameters.  

### Actual Behavior
`Page1` receives empty parameters. 

### Basic Information

- Version with issue: tested with 7.2.0.1422 & 8.1.97
- Last known good version: -
- Xamarin.Forms version: 5.0.0.2012
- IDE: Rider

### Workaround
Don't use query string. This is working as expected:
`NavigateAsync(NavigationPath, new NavigationParameters(){{"Test", true}});`

### Reproduction Link

```
        private const string NavigationPath = "Page1/Page2";
        private const string QueryString = "Test=true";
        private static readonly NavigationParameters NavigationParams = new NavigationParameters(QueryString);
        
        private void ButtonUri_OnClicked(object sender, EventArgs e)
        {
            //NOT working
            _navigationService.NavigateAsync(NavigationPath + NavigationParams);
        }

        private void ButtonQuery_OnClicked(object sender, EventArgs e)
        {
            //NOT working
            _navigationService.NavigateAsync($"{NavigationPath}?{QueryString}");
        }

        private void ButtonNavigationParameters_OnClicked(object sender, EventArgs e)
        {
            //working as expected
            _navigationService.NavigateAsync(NavigationPath, NavigationParams);
        }
```

Full Repo [here](https://github.com/Huaba93/XamarinIssues/tree/master/PrismUriNavigationIssue).

**Comment by brianlagunas** [comment]
This is not a bug, it's by design. When deep linking, the query parameters in the navigation string belong only to the specific navigation segment. You need to use the NavigationParemeters object f you wish to pass the same parameters to all pages in the deep link.
