### ISSUE TITLE
[Enhancement] WPF RegionNavigationJournal stacks protected or public?

### ISSUE THREAD

**Issue by mythjuha** [PrismLibrary/Prism#2489]
## Summary

In my project I need to be able to manipulate the navigation parameters of the last entry in the backstack (adding an ID value to the parameters because the ID was not yet known at the previous view). For this I just need to add 1 method to the RegionNavigationJournal to return the backstack.Peek() entry. To do this currently I need to create an entire new RegionNavigationJournal, copying the code available on github, and add an extra method. This means extra maintenance to make sure my copy stays up to date with the prism package version installed through nuget. 

Ideally the stacks would be public, meaning I could just create an extension method to do this. Alternatively if the stacks would be 'protected' i could override the original class and just add an extra method.

**Comment by brianlagunas** [comment]
I'm not sure I understand your scenario completely, but this is not something we will be adding to Prism. I am confident there is another way to achieve what you want without even messing with the navigation stack.
