### ISSUE TITLE
[XF] How can I access the INavigationService through either unity or the ServiceLocator....or someother DI way

### ISSUE THREAD

**Issue by ValdimarThor** [PrismLibrary/Prism#249]
Hi
I have a usercontrol that need's to get a hold the navigation service but it's not registered in the UnityContainer nor accessible through the ServiceLocator. Is my only option to get it though the BindinContext of the page that the control resides in or is there another way?
I also need to be able to get a handle on it in the OnResume/OnStart method in the app class. Is that possible?

Best Regards Valdimar Thor

**Comment by brianlagunas** [comment]
You could simply register the PageNaviationService with the container in your bootstrapper, like this:

`Container.RegisterType<INavigationService, PageNavigationService>(new ContainerControlledLifetimeManager());`

Then use the ServiceLocator to get your service.  Just keep in mind, when you do this, you will always be navigating off the Application.Current.MainPage object.

**Comment by ValdimarThor** [comment]
Brilliant, thanks Brian
