### ISSUE TITLE
[Win10 UAP] Unable to cancel navigation

### ISSUE THREAD

**Issue by bartlannoeye** [PrismLibrary/Prism#25]
_This is an issue on the current Prism for store (Win8/8.1 RT) implementation. Logged considering we're taking it forward to Win10 (after \\\\Build?) and keep it in the current lightweight form. API changes in Win10 might have impact on the logged issue._

The current implementation of Prism for Windows Runtime doesn't allow you to cleanly cancel navigation, while it is supported by the OS. The FrameNavigationService implementation hooks onto the Frame.Navigating event:

```cs
_frame.Navigating += frame_Navigating;
```

The full eventhandler has NavigatingCancelEventArgs as parameter, which enables cancelling the navigation. However, this is not forwarded to the viewmodel.

```cs
departingViewModel.OnNavigatedFrom(viewModelState, suspending);
```

As an extra: OnNavigatedFrom should be named OnNavigatingFrom, as cancellation can still happen.

**Comment by briannoyes** [comment]
Hi Bart,
Is this one still an issue?
Thanks, BrianN

**Comment by bartlannoeye** [comment]
Checked with the current implementation and the result is as desired.
