### ISSUE TITLE
Global style not visible [Bug] 

### ISSUE THREAD

**Issue by alex-relov** [PrismLibrary/Prism#2500]
### Description

Style from App.xaml not visible for content page on Visual Studio 2019

### Steps to Reproduce

1.  Define style on App.xaml
```
<?xml version="1.0" encoding="utf-8" ?>
<prism:PrismApplication
    x:Class="PrismXF.App"
    xmlns="http://xamarin.com/schemas/2014/forms"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:prism="http://prismlibrary.com">
    <Application.Resources>

        <ResourceDictionary>
            <Style x:Key="Title" TargetType="Label">
                <Setter Property="FontSize" Value="26" />
            </Style>
        </ResourceDictionary>

    </Application.Resources>
</prism:PrismApplication>
```
2.  Use style on any page 
![image](https://user-images.githubusercontent.com/26199529/123987588-fcf05a80-d9cf-11eb-947e-ee3e2ecddfc5.png)
intellisense on visual studio 2019 not see style for label

Visual studio 2019 Version 16.10.3
Prism.Forms 8.1.97
Xamarin.Forms  5.0.0.2012

**Comment by dansiegel** [comment]
First off... This is not a bug with Prism but with the Xamarin tooling. Second we do not allow issues that do not follow our template and do not have a sample reproducing the issue.
