### ISSUE TITLE
[Bug] "Cannot Resolve Type "PrismApplication"" stopping XamlHotReload from compiling.

### ISSUE THREAD

**Issue by markrobert194** [PrismLibrary/Prism#2501]
### Description

Whenever I try use the XamlHotReload feature the PrismApplication cannot be resolved error is stopping the xaml from being updated on the simulator. 

### Steps to Reproduce

1. Create a new project.
2. Make sure Xamarin and Prism are both on the latest versions.
3. Run your application.
4. Make a small change and save the xaml file.

### Expected Behavior

Screen is updated with the change made in the xaml file.

### Actual Behavior

No update is made and an error is produced on the application output. 

### Basic Information

- Version with issue: 
 Prism.Core - v8.1.97 

- Last known good version:
- Whatever I had before, which I can't quite remember but I need the latest version of Xamarin to run the XCT.
- Xamarin.Forms version:
v5.0.0.2012
- IDE: Visual Studio for Mac v8.10.4

### Screenshots

![Screenshot 2021-07-01 at 10 59 02](https://user-images.githubusercontent.com/78956172/124106430-1b9c3300-da5c-11eb-80ef-441232dd1377.png)

![Screenshot 2021-07-01 at 10 50 46](https://user-images.githubusercontent.com/78956172/124106459-21921400-da5c-11eb-8200-d306ded62f99.png)

### Reproduction Link

Create a new project and try make changes, can't add my project here for some reason.

**Comment by dansiegel** [comment]
This is not a Prism bug. Please file a ticket in Visual Studio. 
cc: @maddyleger1
