### ISSUE TITLE
Region from custom RegionAdapter not in list of regions

### ISSUE THREAD

**Issue by bzuillsmith** [PrismLibrary/Prism#251]
I haven't been able to navigate to regions created by a custom ```RegionAdapter``` I made. I noticed the ```RegionManager.Regions``` collection does not contain the ```Region instance``` created by the custom ```RegionAdapter```. I cannot call ```regionManager.RequestNavigate``` to it - it seems to be a noop. But I *can* call ```regionManager.registerViewWithRegion``` and it works fine even though the view is not in the list of regions of that region manager. [This SO question](http://stackoverflow.com/questions/33249284/prism-regions-from-custom-regionadapter-not-showing-in-regionmanager-list) has more details. Am I missing something?

**Comment by noufionline** [comment]
most probably your code below is causing you the issue.
```
protected override IRegion CreateRegion()
    {
        return new Region();
    }
```

Try changing to return a region which can host multiple active views

```
protected override IRegion CreateRegion()
{
    return new AllActiveRegion();
}
```

**Comment by bzuillsmith** [comment]
This has no effect. Further, I don't want all regions to be active like they would be in an ```ItemsControl```. ```Region``` has the ability to activate only some regions whereas ```AllActiveRegion``` assumes they will be active all the time.

**Comment by briannoyes** [comment]
Probably stating the obvious here, but have you compared your implementation of your custom RegionAdapter carefully against the ContentControlRegionAdapter, ItemsControlRegionAdapter, and SelectorRegionAdapters that are included with Prism? You could also look at the source for some of the component library ones like Infragistics and Telerik have for their docking containers. 

What kind of container is the adapter for?

**Comment by bzuillsmith** [comment]
The Adapter is for AvalonDock. Both my ```CreateRegion``` implementation and my ```Adapt``` implementation are called. Wouldn't that mean they should appear in the RegionManager.Regions list regardless of the rest of the implementation?

**Comment by bzuillsmith** [comment]
Well, I can write a custom ```StackPanel``` adapter without problem so my only guess is that AvalonDock is doing something on initialization that causes problems with putting regions on some of its layout elements. It looks like I have some alternatives to the way I am doing things though. I'll close this for now and reopen if I find anything new that leads me to believe it's a Prism issue.

**Comment by mkb137** [comment]
I have the same issue.  If I use `RegisterViewWithRegion`, my view will be displayed but the region will never appear in the `RegionManager`'s list of regions and can't be navigated to with `RequestNavigate`.

I traced why the region wasn't registered to `RegionManagerRegistrationBehavior.TryRegisterRegion`.  On my adapted region, `FindRegionManager` returns nothing as the RegionManagerProperty is not set on the control.  I haven't figured out how it gets set on other controls and why it's not set on mine.

I was able to work around it by setting the property myself in my `RegionAdapter`'s `Adapt` method:

```csharp
private readonly IRegionManager _regionManager;

public MyRegionAdapter( IRegionBehaviorFactory regionBehaviorFactory, IRegionManager regionManager ) : base( regionBehaviorFactory ) {
    this._regionManager = regionManager;
}

protected override void Adapt( IRegion region, MyControl target ) {
    RegionManager.SetRegionManager( target, this._regionManager );
    // continue with Adapt
}
```

With this, the target control properly ends up in the list of regions and can be navigated to.

**Comment by brianlagunas** [comment]
This happens because you are trying to navigate to a region that hasn't been created yet.  This is why you use RegisterViewWithRegion.  This will let the region handle injecting the view when it has been created.  This is also known as "view discovery".

**Comment by mkb137** [comment]
Let's say I have a Region X.  View A is registered with the region in its module's Initialize.  When the application is launched, View A is correctly shown.  

Now when the application is up and running, on the click of a button in a different region I call `RequestNavigate( "X", "ViewB" )`.  At this point, even though the region is created and has a view in it, the region manager will not have "X" in its list of regions and the request will fail.

**Comment by brianlagunas** [comment]
I am not able to reproduce your issue.  Can you provide a sample the reproduces your issue?

Are you are not registering your ViewB with the container for use with navigation?  If not then navigation will not work.

```
_container.RegisterTypeForNavigation<ViewB>();
```

If the RegionManager didn't have the region in it, then ViewA wouldn't show at all.  If ViewA shows, it has the region.  How are you getting the RegionManager to navigate to your ViewB?

**Comment by mkb137** [comment]
See https://github.com/mkb137/PrismRegionIssue

**Comment by brianlagunas** [comment]
Ahhh... I see what's going on.  You are using MahApps Metro Window and trying to create a region on a command object that is not part of the visual tree.  Since the `metro:WindowsCommand` is not part of the visual tree, the RegionManager will not find the WindowCommand region at runtime.  So you just need to set the RegionManager on your `metro:WindowCommands` object manually.

XAML:
```
	<metro:MetroWindow.RightWindowCommands>
		<metro:WindowCommands x:Name="_windowsCommand" />
	</metro:MetroWindow.RightWindowCommands>
```
Code-Behind:
```
        public Shell(IRegionManager regionManager)
        {
            InitializeComponent();

            RegionManager.SetRegionName(_windowsCommand, RegionNames.WindowCommands);
            RegionManager.SetRegionManager(_windowsCommand, regionManager);
        }
```

Now it will work as expected.  Just remember, the RegionManager can only find regions that are part of the visual tree.

**Comment by mkb137** [comment]
It's odd, then, that `RegisterViewWithRegion` works OK.  It seems to become part of the visual tree eventually, perhaps after templates are loaded.  But it's good to have a workaround.

**Comment by brianlagunas** [comment]
Actually it doesn't. You can look at the code to see why it works initially, and not when calling RequestNavigate if you want to understand the inner workings.
