### ISSUE TITLE
[Bug] iOS Navigation Bar Double Height

### ISSUE THREAD

**Issue by memis1970** [PrismLibrary/Prism#2511]
### Steps to Reproduce

1. Create new Project with MasterDetailPage and Detail Page
2. Navigate to Detail Page
3. Observe height of Navigation Bar

### Expected Behavior

Navigation Bar should be normal height

### Actual Behavior

Navigation bar appears to be double height

### Basic Information

- Version with issue: 8
- Last known good version: Unknown
- Xamarin.Forms version: 5
- IDE: Visual Studio 2019 Mac & iOS Simulator 14.5

### Screenshots

![Nav Bar Height](https://user-images.githubusercontent.com/86732322/124723805-4fb3a000-df03-11eb-952e-647ece611ed6.png)

### Reproduction Link

[BlankPrism copy.zip](https://github.com/PrismLibrary/Prism/files/6775479/BlankPrism.copy.zip)

**Comment by dansiegel** [comment]
@memis1970 Prism does not control any UI Styling, or native renderers... With the exception of the Android Back Button, everything in Prism.Forms is just a netstandard library. So particularly if your issue exists on a single platform, this tells me the issue you're having is with Xamarin.Forms.

**Comment by memis1970** [comment]
Hi Dan, Thanks for your swift reply!

I've just tried amending the solution to navigate to the MasterDetailPage without using Prism Navigation (standard Xamarin Forms navigation) and it seem to work as expected; i.e. the navigation bar is the correct height.

I've reattached the solution with the Xamarin Forms navigation added to App.xaml.cs so you can easily switch between the 2 methods of navigating if you wanted to take a look?

As an aside, I've noticed previously that if I'd made a mistake with the navigation path then the same thing would happen; I.e. Navigation bar would be double height. I can't remember the specifics of what would cause it though now but it was when the Path wasn't created to spec.

Anyway, if you cared to take a look at the attached that would be much appreciated!

Thanks in advance.

[BlankPrism copy.zip](https://github.com/PrismLibrary/Prism/files/6777877/BlankPrism.copy.zip)

**Comment by memis1970** [comment]
@dansiegel 

Hi Dan,

As it seems to be working using Xamarin Forms navigation, I'm wondering if it's an option to use this instead of Prism Navigation just for navigating to the Detail Pages? Would this be an option? If so is there anything to consider?

Thanks in advance.

**Comment by dansiegel** [comment]
looking at your sample, you've really opened the issue in the wrong repo... also what you're observing is that Prism.Forms.Extended sets the iOS Specific property PrefersLargeTitles.

https://github.com/dansiegel/Prism.Container.Extensions/blob/c3bedad89fc04c53cc3841f52542067a08d5db63/src/Prism.Forms.Extended/Behaviors/ExtendedPageBehaviorFactory.cs#L54-L57

**Comment by memis1970** [comment]
Well that's a new one on me!

Thanks so much for the guidance. Managed to fix with the following property set on the Detail (Content) Pages:

ios:Page.LargeTitleDisplay="Never"

Appreciate you taking the time to respond.
