### ISSUE TITLE
[Bug] NavigationService GoBackAsync alway navigating with useModalNavigation=true

### ISSUE THREAD

**Issue by Yagon2395** [PrismLibrary/Prism#2514]
### Description

After calling `GoBackAsync()` or `GoBackAsync(INavigationParameters parameters, bool? useModalNavigation, bool animated)` the result of `GetNavigationUriPath()` has always the flag `useModalNavigation=true` even if i set it to be false.

I've got into this bug when i saw this log on my published app on AppCenter:
`Prism.Navigation.NavigationException: An unknown error occurred. You may need to specify whether to Use Modal Navigation or not.`

When I saw the current navigation path that I saved in the log's customProperties, I debugged and came to this conclusion.

### Steps to Reproduce

1. Clone repository https://github.com/Yagon2395/SamplePrismNavigationIssue;
2. Run the sample app in Android or iOS device or simulator;
3. Click button -> Navigate to ViewA;
4. Click button -> GoBackAsync() or button -> GoBackAsync(INavigationParameters parameters, bool? useModalNavigation, bool animated);
5. See the output log messages _stackBeforeGoBack_ and _stackAfterGoBack_ or put a breakpoint in **ViewAViewModel** on methods `GoBackAsync` or `GoBackAsyncWithOptions`

### Expected Behavior
The navigation path should have the flag `useModalNavigation=true` only when we set it to true.
### Actual Behavior
The navigation path after a `GoBackAsync`, alway set the flag `useModalNavigation=true`.

### Basic Information

- Version with issue: 8.1.97.5141
- Last known good version: 8.0.0.1909
- Xamarin.Forms version: 5.0.0.2012
- IDE: Microsoft Visual Studio Professional 2019 - Version 16.9.4

### Reproduction Link
https://github.com/Yagon2395/SamplePrismNavigationIssue

**Comment by brianlagunas** [comment]
This is not a bug. You cannot call `GetNavigationUriPath()` after you have removed the page from the navigation stack. Since the page is no longer part of the stack, the generated UriPath will not be accurate. Instead, you need to call it on the Page you went back too. Also, the `GetNavigationUriPath()` method does not persist any options you pass into a navigation call like GoBack. It is generated based on the navigation stack.

**Comment by AnimaOleg** [comment]
Broken repository "Clone repository https://github.com/Yagon2395/SamplePrismNavigationIssue;"
