### ISSUE TITLE
Documentation for Prism.Forms

### ISSUE THREAD

**Issue by Mardaneus86** [PrismLibrary/Prism#252]
I'm very interested to start using Prism.Forms for Xamarin. However, it looks like documentation on this subject is missing. I've used Prism for WPF briefly a few years ago so my knowledge of the subject is rather low.

Is there any work in progress or plans to start documenting it? I'd love to help if it is wanted.

**Comment by brianlagunas** [comment]
Well, I have documentation on the [dependency service](https://github.com/PrismLibrary/Prism/blob/master/Documentation/Xamarin.Forms/DependencyService.md).  I am still working on the docs for XF.  There are more docs coming.  Would definitely appreciate any help on documentation I can get.  For now, if you need something to get you started, check out my blog post.  It's a little outdated, but still relevant.

http://brianlagunas.com/first-look-at-the-prism-for-xamarin-forms-preview/

Some major topics I still need to add:
* getting started
* navigation

**Comment by Mardaneus86** [comment]
I've seen and read the blog post, which is indeed a good starter but fairly limited to really get going. Documentation will help a lot to grow the community around Prism.Forms. I'm liking the concepts that I've already discovered.

The example of the dependency is working properly. Right now I'm trying to combine it with the navigation example and trying to show dialogs through the INavigationService and IDialogService. I can't seem to get the DialogService working though. I am unsure if this is an issue with the DialogService or that I'm missing some core concept here. This is what I currently have in my ViewModel:

```C#
public TestPageViewModel (IPageDialogService pageDialogService)
{
	_pageDialogService = pageDialogService;

	ShowDialogCommand = new DelegateCommand (ShowDialog);
}

private async void ShowDialog() {
	_pageDialogService.DisplayAlert ("test", "test", "test"); //not working
}
```

The ShowDialog command has been properly bound in the View (it hits the breakpoint). The alert is not shown in this case, without an error. If I make it an async/await call it throws a NullReferenceException on something within the DialogService (the Page variable is set though).

Any idea what I'm doing wrong?

**Comment by Mardaneus86** [comment]
I've been looking into the issue a bit further. It seems that the Page property getter returns a proper object, but the class itself uses a private variable that can be null if Page isn't explicitly set. Since the IPageDialogService is injected just like the INavigationService it has to be aware of the current page it's on.

I have created a fix in my local copy of Prism.Forms at the UnityBootstrapper class in the ConfigureViewModelLocator method, with the same drawbacks as the INavigationService regarding naming convention.

Should I open a new issue and create a pull request for this?

**Comment by brianlagunas** [comment]
Yes, please.
