### ISSUE TITLE
[Enhancement] Prism.Regions.RegionManager.RequestNavigate implement INavigationAware

### ISSUE THREAD

**Issue by djunod** [PrismLibrary/Prism#2521]
## Summary

When using Xamarin.Forms Prism, the Prism.Regions.RegionManager,RequestNavigate API should implement INavigationAware just like Prism.Navigation.PageNavigationService.DoNavigateAction does.

## API Changes

Prism.Regions.RegionManager,RequestNavigate should implement INavigationAware just like Prism.Navigation.PageNavigationService.DoNavigateAction does since they are doing the same thing.

## Intended Use Case

Even though you choose to do Region navigation instead of Page navigation, you should still get the same navigation tools.

**Comment by brianlagunas** [comment]
For region navigation you must use `IRegionAware`. These are two completely different navigation models and have completely different object types passed into it's methods. This was designed this way on purpose. The same interface could not be used for both.
