### ISSUE TITLE
Getting error when handling NavigationService

### ISSUE THREAD

**Issue by kerberosargos** [PrismLibrary/Prism#2527]
Hello, after update Xamarin Form then when I handling navigation like **../SomePage**  I am getting issue as `System.InvalidOperationException: 'Collection was modified; enumeration operation may not execute.'` 

I think that is about `foreach` in [this line ](https://github.com/PrismLibrary/Prism/blob/5b5c54ae2af12144736d88c6a2fa2fdc7faf8a7f/src/Forms/Prism.Forms/Navigation/PageNavigationService.cs#L492) 

Thank you in advance.

**Comment by brianlagunas** [comment]
Did not follow the issue template
