### ISSUE TITLE
[XF] PageDialogService is not setting Page property correctly

### ISSUE THREAD

**Issue by Mardaneus86** [PrismLibrary/Prism#254]
The PageDialogService is using the Page property, like the NavigationService does. However it uses the internal field to display alerts and action sheets which can cause NullReferenceExceptions. When using constructor injection the Page property does not get set.

The fix for this is to assign the Page property in the UnityBootstrapper class in the ConfigureViewModelLocator method.

This does however rely on the same solution as the NavigationService does, which means there is another fixed name constructor parameter (which in my opinion is a little bit fragile). I've seen another issue about this topic so I guess we shouldn't repeat that here.

Will add a PR soon.

**Comment by brianlagunas** [comment]
Yeah, I really hate how we have to do the service injection.  I requested Unity to add support for type based parameter override so that we can remove this limitation.  Also, I think that if we just use the Page property, it should work.  I'm not 100% sure if the dialogs must be shown from it's specific page.

**Comment by Mardaneus86** [comment]
I'm testing if it causes any issues when using this Page property. Hopefully Unity can add the support that you requested.

I was thinking that it would be beneficial to have some platform specific Xamarin Forms test projects. This could have 2 benefits. One would be to be able to test everything in the platforms themselves, the other would be to have a showcase for every feature that's added. Because right now I have to create these test projects myself and include the Prism libraries to make sure my solution works properly.

**Comment by brianlagunas** [comment]
Yeah, that is definitely something we need to do.  I have something locally that I use as a playground.  I'll try to think of a somewhat decent sample that we cam start with for this purpose.

**Comment by Mardaneus86** [comment]
Great, I have something locally as well right now (but very limited). I'd be happy to help where possible.
