### ISSUE TITLE
[Bug] App freeze after multiple dialogs in a modal page on iOS

### ISSUE THREAD

**Issue by pierre-galaup** [PrismLibrary/Prism#2541]
### Description

Hello,

I found a bug on iOS on Xamarin Forms.
It is with the DialogService.
The project works on Android without problem.

I am in a page in modal. I open a suite of Dialog. After 3, when I close the Dialogs, the application is freezing, I can't click on anything at all.

I made a reproduction project.

For information, the purpose is to have a succession of Dialogs, with choices and at the end we go back to the view model that called the Dialogs to know the choices made by the user.

### Steps to Reproduce

1. Start the reproduction project on iOS
2. Press 1 time on "Launch Modal".
3. Press 1 time on "Launch Dialog (after modal)".
4. Press 2 times on "Open new dialog (open 3 dialogs then close)".
5. Press 1 time on "Close all dialogs".

### Expected Behavior

The application will close all the dialogs and we can continue to use app.

### Actual Behavior

The application will close all the dialogs but you will not be able to press any of the buttons.

### Basic Information

- Version with issue: 8.1.97
- Last known good version: /
- Xamarin.Forms version: 5.0.0.2083
- IDE: Rider/Visual

### Reproduction Link

[samples.zip](https://github.com/PrismLibrary/Prism/files/7044978/samples.zip)

**Comment by nick5454** [comment]
@pierre-galaup I didn't test your app(not connected to a mac), however you shouldn't be opening a dialog. Not sure if this fixes your issue. but you could put the call in the OnNavigatedTo method. Can you try putting that in and see if it works? I don't think it's the Dialog Service issue

**Comment by brianlagunas** [comment]
I'm having a hard time trying to follow your approach. It seems overly complicated. Trying to close dialogs within a dialog, right after opening the dialog is not going to work well and is not something we are even interested in trying to support.
