### ISSUE TITLE
[Bug] Not possible to create Regions using WinUI enabled Uno Platform With Project Reunion 0.8

### ISSUE THREAD

**Issue by roland-hediger** [PrismLibrary/Prism#2545]
### Description

It is not possible to use Prism Regions when adding Prism.Uno.WinUI to a Uno WinUI project, and running the Windows Desktop version of it with WinUI. Note that all other project types (WASM,mobile,etc) remain unaffected. 

I am very aware that this is possible in general given what is available in the `e2e` folder of the Prism Library itsself.

Currently the version of Project Reunion included in the `Windows.Desktop.Package`project of the `Uno WinUI` template is `0.8.1` as opposed to the 0.5x used in the e2e samples. 

This version includes some namespace changes that prevent the `RegionManager.SetRegionName` from working when attached to controls. The error below occurs leading to a crash when running on WinUI.

### Steps to Reproduce

1. Create a WinUI Uno Project ``` dotnet new unoapp-winui -o MyExample```
2. Add `Prism.Uno.WinUI` and `Prism.Uno.DryIoc.WinUI` dependencies to the various project types.
3. Modify App.xaml.cs as it is in the WinUI sample under e2e of the Prism Library
4. Rename MainPage.xaml to Shell.xaml
5. Add a ContentControl named "MainView" to the Page.
6. Add a property to this: ```prismRegions:RegionManager.RegionName="MainRegion"```

Note all this has been done in the linked repository below. 

### Root Cause Analysis
It seems that the new version of Project Reunion - 0.8 does not include `Microsoft.UI.Xaml.DependencyObject.get_DispatcherQueue()` this is due to a namespace change. The class can now be found here: https://docs.microsoft.com/en-us/uwp/api/windows.system.dispatcherqueue?view=winrt-20348, and no longer under the XAML namespace. 

### Expected Behavior
Running the Application does not cause a crash

### Actual Behavior
```
at 0x00007FF98B914ED9 (KernelBase.dll) in Stutor.Admin.Windows.Desktop.exe: WinRT originate error - 0x80131513 : 'Method not found: 'Microsoft.System.DispatcherQueue Microsoft.UI.Xaml.DependencyObject.get_DispatcherQueue()'.'.
````

### Basic Information

- Version with issue: 8.197
- Last known good version: ?
- IDE: Visual Studio 2022 Preview,but also reproduced on Visual Studio 2019

### Reproduction Link

https://github.com/roland-hediger/prism-uno-platform-issues, download and run the Windows.Package (x64) project to reproduce.

**Comment by sigmarsson** [comment]
https://github.com/PrismLibrary/Prism/discussions/2523

**Comment by roland-hediger** [comment]
> #2523

Thanks, I see your PR actually got merged, so it is in master. @sigmarsson. I am just not sure how to build what is on master in such a way that I could integrate it into the example project, to check if it works. Seems like I will have to dig in the Github action and sln a bit to see how I could build the nuget packages.

**Comment by sigmarsson** [comment]
either. or you can have 8.2 on sponsor channel now.

**Comment by roland-hediger** [comment]
> either. or you can have 8.2 on sponsor channel now.

 Unfortunately I am not a sponsor, so  I do not think I will get access to that channel immediately but I will definitely take a look 👍🏻 thanks for such a speedy response.
