### ISSUE TITLE
Any samples for Prism.Windows.Validation?

### ISSUE THREAD

**Issue by JohnTasler** [PrismLibrary/Prism#256]
The UWP HelloWorld sample lists several features that it demonstrates, but the code does not seem to back that up.

I'd like to use the Prism.Windows.Validation classes, but it would be nice to get up to speed without having to assume how to use it based on the code. It's not entirely clear.

**Comment by briannoyes** [comment]
The validation functionality is a straight port of what we implemented in the Prism for Windows Runtime release. Have not had time to port over all the QuickStarts or the Reference Implementation App (AdventureWorks Shopper) yet, where that code is exercised, but hope to do that sometime soon. 

I'd recommend a couple things:
1. Check out my course on Pluralsight: http://www.pluralsight.com/courses/building-windows-store-business-applications-prism - I have a whole module covering the validation functionality in there. If you don't have a Pluralsight subscription, email me at brian.noyes AT gmail.com and I can get you a one month trial.
2. Download the Validation QuickStart from http://prismwindowsruntime.codeplex.com/ as another sample that shows how to use it.
3. Download the AdventureWorks Shopper from https://code.msdn.microsoft.com/windowsapps/Prism-for-the-Windows-86b8fb72 and look at the BillingAddress and ShippingAddress views and viewmodels - which use the validation functionality.
