### ISSUE TITLE
[Bug] i:Interaction.Triggers, KeyDown event not working in dialog

### ISSUE THREAD

**Issue by hengway** [PrismLibrary/Prism#2561]
### Description
i:Interaction.Triggers, KeyDown event not working in dialog, the same code if implement in view, work no problem, but when implement in the dialog, then no key stroke been capture.

### Steps to Reproduce

1. Implement i:Interaction.Triggers, KeyDown in dialog

### Expected Behavior

Should be able to capture the keyboard keydown key stroke

### Actual Behavior

No key stroke been capture in dialog

### Basic Information

- Version with issue: 8.1.97
- Last known good version: 
- WPF version: 4.8
- IDE: Visual studio 2019

### Screenshots

![2021-09-14 23_15_08-PrismIssue - Microsoft Visual Studio](https://user-images.githubusercontent.com/6492598/133284979-bfdfeed1-402a-450e-8651-f682bc30fb26.png)

### Reproduction Link
Sample code: 
[PrismIssue.zip](https://github.com/PrismLibrary/Prism/files/7163099/PrismIssue.zip)

**Comment by brianlagunas** [comment]
This has nothing to do with Prism, and you already asked this in the discussion which make this a double post.

**Comment by hengway** [comment]
Thank you for the reply, so mean in WPF, i:Interaction.Triggers, KeyDown event not working in dialog service?

**Comment by brianlagunas** [comment]
it has nothing to do with the dialog service, it has to o with where you are defining your triggers (Window vs UserControl).
