### ISSUE TITLE
Update Unit Tests to Use Fluent Assertions

### ISSUE THREAD

**Issue by Christian-Oleson** [PrismLibrary/Prism#2562]
## Summary
Fluent Assertions can help make unit tests much more readable. 
https://fluentassertions.com/

## API Changes
No API Changes will occur, but the changes will be made to the unit tests

Here's an example:
```
        [Fact]
        public void OnPropertyChangedShouldExtractPropertyNameCorrectly()
        {
            bool invoked = false;
            MockViewModel mockViewModel = new MockViewModel();

            mockViewModel.PropertyChanged += (o, e) => { if (e.PropertyName.Equals("MockProperty")) invoked = true; };
            mockViewModel.InvokeOnPropertyChanged();

            Assert.True(invoked);
        }
```

The Assertion would read:
`invoked.Should().BeTrue();`

## Intended Use Case
To add clarity around the unit tests for ease of readability.

**Comment by brianlagunas** [comment]
Thanks for the suggestion, but this is not something we need to spend any time on. Our unit tests are still readable.

`Assert.True(invoked)` is just as readable as `invoked.Should().BeTrue();`, and it's actually few characters to type 😄
