### ISSUE TITLE
prism versions!

### ISSUE THREAD

**Issue by 3wwebdev** [PrismLibrary/Prism#257]
Hi
I am just starting out with prism and WPF and using Actipro Software WPF Studio widgets/controls and they support prism v5.
I am getting lost to if the prism on this site is V5 and OK to use or if I have to use the one at MS's site?

p.s. is there any way you can keep up naming prism download with the version included in the name as some of us am or will get lost as to which version we need (i.e other 3rd partys that do not keep up with your new versions. Like when you go to V6 and users need V5 only).

I am taking it that the version here is V5 at time of posting?

Simon

**Comment by bartlannoeye** [comment]
Hey Simon
The code on this GitHub repository is for **Prism 6**, you can find the link to the different packages on the readme, e.g. the one for WPF is https://www.nuget.org/packages/Prism.Wpf/ (which clearly states it's V6). 

If you want to continue using Prism 5 (created by Microsoft P&P team), this is the package you're looking for: https://www.nuget.org/packages/Prism/. Note that we do not longer support that version, so any bugs you find in v5 will not get fixed.

As Actipro Software WPF Studio provides controls, I don't think there's an issue in either using v5 or v6, but I haven't tried it myself. Maybe @brianlagunas or @briannoyes can confirm this?

**Comment by brianlagunas** [comment]
You can also see the versions by viewing the current release on the releases page located here: https://github.com/PrismLibrary/Prism/releases

The region adapters that Actipro has available for Prism will work regardless of it being v5 or v6.  Simply take the code and bring it into your project and it will work.
