### ISSUE TITLE
[Bug] The MainPage is possible to be null and causes issues in displaying an alert

### ISSUE THREAD

**Issue by AlfonChitoSalano** [PrismLibrary/Prism#2570]
### Description
The MainPage is possible to be null and causes issues in displaying an alert. We saw this crash in our prod logs many times. Please see the attached simple reproducible project.

### Steps to Reproduce

1. Just display and alert using PageDialogService.DisplayAlert
2. Some logs in our production occurred NRE

### Expected Behavior
Should be no NullReference Exception Occur

### Actual Behavior
Some NullReferenceException occur

### Basic Information

- Version with issue: 8.1.97
- Last known good version: NA
- Xamarin.Forms version: 5.0.0.2125
- IDE: Microsoft Visual Studio Community 2019
     Version 16.11.3

### Screenshots

![image](https://user-images.githubusercontent.com/20876086/134872747-a6faa054-cc77-461e-b6b8-7d0c70480077.png)
[PrismDialogBug.zip](https://github.com/PrismLibrary/Prism/files/7234627/PrismDialogBug.zip)

### Reproduction Link

Please see attached.
[PrismDialogBug.zip](https://github.com/PrismLibrary/Prism/files/7234627/PrismDialogBug.zip)

**Comment by dansiegel** [comment]
@AlfonChitoSalano while the issue that you raise is a legitimate issue, your proposal would introduce a major breaking change in behavior that we do not want. A better way to solve this is to update the IPageDialogService to have a `bool CanShowDialog()` which returns true when the MainPage is not null.

**Comment by AlfonChitoSalano** [comment]
> @AlfonChitoSalano while the issue that you raise is a legitimate issue, your proposal would introduce a major breaking change in behavior that we do not want. A better way to solve this is to update the IPageDialogService to have a `bool CanShowDialog()` which returns true when the MainPage is not null.

will do. thanks for your quick response
