### ISSUE TITLE
FileNotFoundException on RequestNavigate() from module

### ISSUE THREAD

**Issue by znakeeye** [PrismLibrary/Prism#2572]
### Description

See attached `WPF` sample project, targeting `.NET 5`. Basically, the following implies a seemingly costly exception on startup:

1. Register view using `RegisterForNavigation<TView>()`.
2. Use a `DirectoryModuleCatalog`.
3. Use `RequestNavigate("SomeRegion", "ViewName")`.

It seems `Prism` or possibly `.NET Core` causes a `FileNotFoundException` when performing these steps. Also see #2255 and [.NET Core issue 36053](https://github.com/dotnet/runtime/issues/36053). Why does it try to load some `...resources.dll`? Is this a `Prism` or `.NET Core` issue? Please advise.

[PrismTest.zip](https://github.com/PrismLibrary/Prism/files/7237322/PrismTest.zip)

### Steps to Reproduce

1. Break on all exceptions.
2. Clean solution. Rebuild.
3. Run the sample app.

**Comment by brianlagunas** [comment]
I get no exceptions. App works as excepted.

**Comment by znakeeye** [comment]
Maybe locale dependent issue then. But the exception is there, for sure.

Even though this issue was closed in world record speed, I'll take the time to spread the knowledge of how this exception is fixed in `.NET Core` enabled `Prism` projects. Simply add this to the `.csproj` file:

```c#
<NeutralLanguage>en-US</NeutralLanguage>
```
