### ISSUE TITLE
[Bug] [TabbedPage] NavigateAsync Page inside TabbedPage 

### ISSUE THREAD

**Issue by beisienlin** [PrismLibrary/Prism#2575]
＿＿＿＿＿＿＿＿＿＿＿＿＿
|　　ＨｏｍｅＰａｇｅ　　｜     
| 　　　　　　　　　　　 　|
| 　　　　　　　　　　　 　| 
＿＿＿＿＿＿＿＿＿＿＿＿
| 　Test1Page　|　Test2Page|
＿＿＿＿＿＿＿＿＿＿＿＿

`<TabbedPage xmlns="http://xamarin.com/schemas/2014/forms" 
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" 
             x:Class="PrismUnitySample.Views.CustomTabbedPage"
             xmlns:local="clr-namespace:PrismUnitySample.Views"
             Title="My App">
	<TabbedPage.Children>   
        <local:Test1Page />
        <local:Test2Page />
    </TabbedPage.Children>
</TabbedPage>`

`<ContentPage xmlns="http://xamarin.com/schemas/2014/forms" 
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" 
             x:Class="PrismUnitySample.Views.Test1Page"
             Title="Test1" BackgroundColor="Red"
             xmlns:mvvm="clr-namespace:Prism.Mvvm;assembly=Prism.Forms"
             mvvm:ViewModelLocator.AutowireViewModel="True">
	<Button Command="{Binding OnLoginCommand}" Text="GO"/>
</ContentPage>`

`public Test1PageViewModel(INavigationService navigationService)
        {
            _navigationService = navigationService;
            OnLoginCommand = new DelegateCommand(GoHome);
        }
		async void GoHome()
		{
            await _navigationService.NavigateAsync("/NavigationPage/HomePage", null);
		}`

**Comment by brianlagunas** [comment]
Sorry, but I can't make sense of this.
