### ISSUE TITLE
Is it possible to get access to the container inside a custom region adapter

### ISSUE THREAD

**Issue by noufionline** [PrismLibrary/Prism#258]
Hi Brians,

I have created a Custom Region Adapter in which I would like to get the Container to get the View registered for Navigation. Is it possible to get access to the container through RegionAdapter Base or some Trick to achieve this?

**Comment by brianlagunas** [comment]
Of course, just ask for it in the constructor.

```
public StackPanelRegionAdapter(IRegionBehaviorFactory factory, IUnityContainer container)
         : base(factory)
     {

    }
```

**Comment by noufionline** [comment]
Thanks Brian :)
