### ISSUE TITLE
[Bug] Incorrect behavior INavigationAware methods on Dialog open and close

### ISSUE THREAD

**Issue by amaneshi** [PrismLibrary/Prism#2588]
### Description

When worked with Dialog service noticed strange behavior. When I open Dialog with DialogService on page method `OnNavigatedFrom` not triggered, but when I close this dialog - page method `OnNavigatedTo` triggered (I was forced to add protection as I subscribe on events in it, so to avoid multiple duplicate subscriptions).

### Steps to Reproduce

1. Open app and on page click "Open Dialog" button
2. When dialog show up any message in debug console.
3. When dialog is closed (either on dedicated button tap or outside of dialog) in debug console appear message from `OnNavigatedTo` method.

### Expected Behavior
Not sure how it should be, but guess both navigation methods should be triggered (or none at least)
### Actual Behavior
Triggered only `OnNavigatedTo` page method on dialog close
### Basic Information

**Platform**: UWP
**Prism**: 8.1.97
**XF**: 5.0.0.2125

### Reproduction Link

[Sample App](https://github.com/amaneshi/PrismSampleApp2)

**Comment by brianlagunas** [comment]
Fixed

**Comment by memis1970** [comment]
Hi, Not sure if this is the best place to post this but I'm seeing the same behaviour on Xamarin.Forms. Is this expected behaviour?

Sample repo attached.

[OnNavigatedTo-PrismDialog.zip](https://github.com/PrismLibrary/Prism/files/13318745/OnNavigatedTo-PrismDialog.zip)

**Comment by dansiegel** [comment]
@memis1970 this issue has been closed for 2 years. If you have an issue rather than digging please open a new issue. Also remember that we will not consider looking at issues with samples that are not on the latest version of Prism which is currently the Prism 9 preview.
