### ISSUE TITLE
[Win10 UAP] INavigationService should provide method to remove items from backstack

### ISSUE THREAD

**Issue by bartlannoeye** [PrismLibrary/Prism#26]
_This is an issue on the current Prism for store (Win8/8.1 RT) implementation. Logged considering we're taking it forward to Win10 (after \\\\Build?) and keep it in the current lightweight form. API changes in Win10 might have impact on the logged issue._

In Windows 8.1 API  the BackStack property was added to the Frame control. The current implementation of Prism for Windows Runtime doesn't expose any way to remove pages from the backstack.

**Comment by brianlagunas** [comment]
How would you envision removing pages from the back stack from within a view model, where you have no reference to the pages?

Would you do it based on page index?  Something like Remove(int pageIndex)?

I have to answer this same question for Xamarin.Forms.

**Comment by briannoyes** [comment]
Since you navigate to a page based on a logical name associated with that page (done so that view models can request navigation without being coupled to the view), I would expect that we would be able to remove them by logical name as well. Logical name maps to type name based on convention that is overridable. I don't think that should be hard to add.

**Comment by brianlagunas** [comment]
What if you have multiple instances of that view on the stack?  How do you choose which instance to remove?

**Comment by brianlagunas** [comment]
Or should we not allow multiple instances to be created and instead always navigate to an existing instance?

**Comment by bartlannoeye** [comment]
In our case it was mostly popping the current page off the stack after navigating away from it (as only then it's on the Backstack). As @briannoyes says, navigation happens based on tokens (logical names), so that can be used to remove pages. But as multiple instances can be added to the stack, we'd probably need an extra parameter (e.g. in the idea of 'first', 'last', 'all' with given token).
