### ISSUE TITLE
Prism Template Pack: VS 2022 support

### ISSUE THREAD

**Issue by glautrou** [PrismLibrary/Prism#2618]
Make "_Prism Template Pack_" extension compatible with **64 bit** (and thus Visual Studio 2022).

### Discussed in https://github.com/PrismLibrary/Prism/discussions/2612

<div type='discussions-op-text'>

<sup>Originally posted by **glautrou** November  9, 2021</sup>
Is there a way to install the "_Prism Template Pack_" for _Visual Studio **2022**_?

I can import snippets manually, but unfortunately not the PRISM "Add new item" templates.
"Prism UserControl (WPF)" is needed for me, I didn't find any hack.</div>

**Comment by glautrou** [comment]
@dansiegel Why closing?

**Comment by brianlagunas** [comment]
Wrong repo and this already exists:

https://github.com/PrismLibrary/Prism.Templates/issues/39

**Comment by 1125028049** [comment]
Why am I only create the .NET template WPF project? I want to create .Net Frame Work 4.8 Prism WPF project.
How can I do?

**Comment by coolfarmer** [comment]
> Wrong repo and this is a duplicate request:
> 
> [PrismLibrary/Prism.Templates/issues/39](https://github.com/PrismLibrary/Prism.Templates/issues/39)

Is your project still accessible?

**Comment by dansiegel** [comment]
> Is your project still accessible?

The templates have been moved to a private repo and are currently only available to those with a Commercial Plus license.
