### ISSUE TITLE
Suggestion: Add tag "up-for-grabs" on issues to make easier to send contributions

### ISSUE THREAD

**Issue by caioproiete** [PrismLibrary/Prism#262]
Would be great to see some issues tagged as "up-for-grabs" or similar to make it easier to send contributions.

**Comment by brianlagunas** [comment]
Yes, we have use the "help wanted" tag in the past.  Right now, I'm not sure we have gone through and identified anything that the tag can be associated with.  Thanks for reminding us to utilize the tags more.
