### ISSUE TITLE
Avoid unnecessary Assembly loading

### ISSUE THREAD

**Issue by EuroEager2008** [PrismLibrary/Prism#2621]
Using DirectoryModuleCatalog (at least for net core) seems to load all the assemblies found in the ModulePath unconditionally even if not needed. I.e. Assume I add one or more assemblies hosting one or more IModule types and then I "mistakenly" add a totally unreferenced assembly to the directory, then this unrelated assembly stays loaded.

I guess this is due to the fact that AppDomains cannot be created in net core and thus an assembly cannot be loaded, inspected, found to be not relevant, but cannot be unloaded.

However net core defines AssemblyLoadContext which could be used just for inspecting Assemblies making a list of relevant Assemblies, unload the (temporary) context and finally load the relevant Assemblies into the AppDomain or even into a non-temporary context (obtaining a bit of isolation).

**Comment by brianlagunas** [comment]
You as the developer are responsible for making sure only the assemblies you want loaded are in your executable directories. Prism has no way of knowing what assemblies are needed and which ones aren't. The only thing Prism does when loading assemblies from a directory is to check to make sure they aren't already loaded.  Other than that, if you have unneeded assemblies in your output, you need to make sure you are cleaning them up.

**Comment by EuroEager2008** [comment]
Ok, thanks
(Actually I thought assemblies were opened for inspecting if any type in it implements IModule and thereby using this assembly and all dependency assemblies from there)
