### ISSUE TITLE
[Bug] CanExecute is called with a type other than T, which was specified in DelegateCommand<T>

### ISSUE THREAD

**Issue by marbel82** [PrismLibrary/Prism#2626]
### Description

When I have DelegateCommand<> with a parameter, an exception is thrown because CanExecute is called with a different parameter type. This happens when the DataContext is switching and probably CommandParameter has an old value when CanExecute is called.

### Steps to Reproduce

1. Create 2 classes with ObservableCollection<> with different item type.
2. Add to each class DelegateCommand<> with an item type and add CanExecute methods.
2. Create DataGrid and add a custom column with a button.
3. Bind button Command to DelegateCommand<> and parameter to a row (parameter will be item type).
4. Switch DataGrid DataContext from one class to another. You may need to add/remove some rows.

### Basic Information

- Application type: Windows Desktop WPF
- Version with issue: Prism.Core 8.1.97 
- .NET 5.0.9
- IDE: Visual Studio 2019
- OS: Microsoft Windows NT 10.0.19043.0

### Reproduction Link

https://github.com/marbel82/DataGridRowCanExecuteParamTypeBugRepro

I have prepared 2 examples (2 windows). Both examples are "fixed". You can see what I changed in commits.

There are buttons:
- [Switch] - switches DataContext from DogsCatalog to CowsCatalog and vice versa
- [Add] - adds row
- [Remove] - remove first row
- [GC] - garbage collector

#### 1) DelayedDataContextSwitching.xaml + DelayedDataContextSwitching.xaml.cs

I fixed this example by changed botch `DelegateCommand<Dog>` and `DelegateCommand<Cow>` to `DelegateCommand<object>` so you can add breakpoint in

```c#
        private bool CanRemoveExecute(object item)
```
and look at type of `this` and `item`.

For example, after switch, the type of `this` is `CowsCatalog` and the type of `item` is `Dog`.

Interestingly, after deleting rows, CanExecute is still called. And this is exactly what I had a problem with in my program.

#### 2) CanExecureBugFix.xaml.cs + CanExecureBugFix.xaml.cs

This example is more like my program. I have a DataTemplateSelector that sometimes returns the same resource.

The DataGrid control then stays the same (same object) and only the DataContext changes.

When I remove a row and switch `DataContext`, `CanExecute` is invoked for the removed row (not sure why, maby GC), but `this` is equal to another collection. For example, when I remove `Dog` and switch DataContext to `CowsCatalog`, `CanExecute` is called for `CowsCatalog` and `item` is of type `Dog`.

This causes an exception.

I was able to fix this error by adding the parameter `x:Shared="False"` to resource, containing  the DataGrid.

Change `x:Shared` to `True` to see the exception.

**Comment by brianlagunas** [comment]
This is not a bug in Prism.  This is related to how you are implementing your application code.

**Comment by marbel82** [comment]
@brianlagunas  Could you explain to me, why doesn't Prism check types when calling CanExecute, if there could be a situation that CommandParameter Binding can come later than CanExecute call?

Maybe this is a bug in DataGrid's implementation?

**Comment by marbel82** [comment]
@brianlagunas OK, I back to my application, and I looked at the error again.

After I delete a row in the DataGrid, and change the DataContext I got exception in WindowsBase.dll:

_"Unable to cast object of type 'KDictionaries.ViewModels.EntityVM.UniversalEditableVM\`1[KDictionaries.Database.KDictionariesDataSet+dict_branchRow]' to type 'KDictionaries.ViewModels.EntityVM.EditableEntityVM\`1[KDictionaries.Database.KDictionariesDataSet+dict_document_statusRow]'."_

and call stack is:

```txt
   at System.Runtime.CompilerServices.CastHelpers.ChkCastAny(Void* toTypeHnd, Object obj)
   at Prism.Commands.DelegateCommand`1.CanExecute(Object parameter)
   at MS.Internal.Commands.CommandHelpers.CanExecuteCommandSource(ICommandSource commandSource)
   at System.Windows.Controls.Primitives.ButtonBase.UpdateCanExecute()
   at System.Windows.Controls.Primitives.ButtonBase.UnhookCommand(ICommand command)
   at System.Windows.Controls.Primitives.ButtonBase.OnCommandChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
```


I think I got too far from the original problem when trying to find the cause, write description and prepare examples.
