### ISSUE TITLE
[Bug] WINUI 3 (VS 2019) and PRISM (Prism.Uno -Version 8.1.97 )  - Same class exists in both assemblies

### ISSUE THREAD

**Issue by annmanvel** [PrismLibrary/Prism#2632]
### Steps to Reproduce

As an R&D I tried to create MVVM using WinUI 3 + PRISM.
I have done below steps and created a WinUI 3 project by installing:

1. Visual Studio 2019 Professional with all required components for WinUI3 
2. Windows App SDK From Visual Studio, click on menu Extensions > Manage Extensions
3. After installing, create a new project by selecting "Blank App, Packaged (WinUI 3 in Desktop)" template.
4. Install Prism.Uno 8.1.97 from Visual Studio, click on menu Tools > NuGet Package Manager > Package Manager Console and type command "Install-Package Prism.Uno -Version 8.1.97"

Now after building the solution I am getting build error.

> Error CS0433 The type 'DefaultOverloadAttribute' exists in both 'Microsoft.Windows.SDK.NET, Version=10.0.19041.21, Culture=neutral, PublicKeyToken=31bf3856ad364e35' and 'Uno.Foundation, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null'

### Expected Behavior
No errors expected and How to resolve this error? 

### Actual Behavior
Now after building the solution I am getting build error.

> Error CS0433 The type 'DefaultOverloadAttribute' exists in both 'Microsoft.Windows.SDK.NET, Version=10.0.19041.21, Culture=neutral, PublicKeyToken=31bf3856ad364e35' and 'Uno.Foundation, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null'

### Basic Information

- Version with issue: 8.1.97
- Last known good version: N/A
- Xamarin.Forms version: N/A
- IDE: Visual Studio 2019 Professional 16.11.7

### Screenshots

![image](https://user-images.githubusercontent.com/71872211/144984445-0286e9b3-f88a-4f29-b69a-2e5342f5edf1.png)

### Reproduction Link

     
[WinUI3Prism.zip](https://github.com/PrismLibrary/Prism/files/7666327/WinUI3Prism.zip)

**Comment by brianlagunas** [comment]
The version of Prism for Uno you are using is not built against the new Windows.Sdk package.

However, this issue was resolved with a recent PR #2628. There is no current timeline for when a public build will be available.

**Comment by annmanvel** [comment]
> 

Hi, 
Is there any Prism Library support for WinUI 3 other than using Prism. Uno?

**Comment by brianlagunas** [comment]
@annmanvel Not at this time.

**Comment by annmanvel** [comment]
> @annmanvel Not at this time.

@brianlagunas Thank you for your time

**Comment by annmanvel** [comment]
Hi @brianlagunas, 
Any new release planned (public) for the issue reported?

**Comment by ahass** [comment]
We are still waiting for Prism to include in our WinUi3 Application. Are there any other options?

**Comment by brianlagunas** [comment]
@ahass Build from source if you need it now.
