### ISSUE TITLE
Prism 8.1 not compatible with .Net 6.0

### ISSUE THREAD

**Issue by kergee** [PrismLibrary/Prism#2648]
when  run the following code
``` C#
var roleBusiness = ContainerLocator.Current.Resolve<IBase_RoleBusiness>();
```
throw Prism.Ioc.ContainerResolutionException, more details:
An unexpected error occurred while resolving 'IBase_RoleBusiness'

StackTrace:
   Prism.Unity.UnityContainerExtension.Resolve(Type type, ValueTuple`2[] parameters)
   Prism.Unity.UnityContainerExtension.Resolve(Type type)
   Prism.Ioc.IContainerProviderExtensions.Resolve[T](IContainerProvider provider)
   var roleBusiness = ContainerLocator.Current.Resolve<IBase_RoleBusiness>()
   
   App.xaml.cs:
   Prism.PrismApplicationBase.Initialize()
   Prism.PrismApplicationBase.InitializeInternal()
   Prism.PrismApplicationBase.OnStartup(StartupEventArgs e)
   
   System.Windows.Application.<.ctor>b__1_0(Object unused)
   System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

Inner Exception 1:
TypeInitializationException: The type initializer for 'Unity.Interception.Interceptors.InstanceInterceptors.InterfaceInterception.InterfaceInterceptorClassGenerator' threw an exception.

Inner Exception 2:
PlatformNotSupportedException: Strong-name signing is not supported on this platform.

**Comment by brianlagunas** [comment]
Not a bug as explained in the discussion you posted.
