### ISSUE TITLE
[Bug] Prism.DryIoc.Forms and Prism.DryIoc.Extensions

### ISSUE THREAD

**Issue by softlion** [PrismLibrary/Prism#2656]
### Description

When both nugets are present in a project, the same methods are defined twice in the same namespace.

I've read in the previous issues that Prism.DryIoc and Prism.DryIoc.Extensions are not meant to be used in the same project.  
But i don't understand why there would be a collision. Is there an issue with the Prism.DryIoc.Forms nuget which does reference Prism.DryIoc.Extensions and instead redefine the same classes/methods ?

Anyway i need Prism.DryIoc.Forms as it's a Xam forms project, and also Extensions  to be able to use the RegisterServices extension method.

### Steps to Reproduce

1.  Create a xamarin forms project
2.  Add Prism.DryIoc and Prism.DryIoc.Extensions
3. Modify the base class of App with PrismApplication
4. 
In ```protected override void RegisterTypes(IContainerRegistry containerRegistry)```   
Use ```containerRegistry.RegisterService(services => {})```

### Expected Behavior
Compiles ok.

### Actual Behavior
Fails with "RegisterService" is ambigous between 2 classes residing in the same namespace but in different assemblies.

### Basic Information

- Version with issue: 8.0.62 of extensions, 8.1.97 of forms
- Last known good version: the versions from may 2021 were OK
- Xamarin.Forms version: 5.0.0.2291
- IDE: Rider latest stable

**Comment by softlion** [comment]
It seems a non issue. Closing.

**Comment by softlion** [comment]
It seems a non issue. Closing.

**Comment by AmrAlSayed0** [comment]
If you want to use 2 nuget packages that have classes with the same name you can do this in your csproj file:
```xml
<PackageReference Include="Prism.DryIoc.Forms" Version="8.1.97" />
<PackageReference Include="Prism.DryIoc.Extensions" Version="8.0.62" Aliases="PrismDryIocExt" />
<PackageReference Include="Prism.Forms.Extended" Version="8.0.62" Aliases="PrismFormsExt" />
```
and in your App.xaml.cs file you can do this:
```csharp
extern alias PrismFormsExt;
using Prism.Ioc;
public sealed partial class App : PrismFormsExt::Prism.PrismApplication
{
    protected override void RegisterTypes(IContainerRegistry containerRegistry)
    {}
}
```
And in you App.xaml you can do this:
```xaml
<prismFromsExt:PrismApplication xmlns="http://xamarin.com/schemas/2014/forms"
                                xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
                                xmlns:prismFromsExt="clr-namespace:Prism;assembly=Prism.Forms.Extended"
                                x:Class="Text.App" />
```
Here is the [documentation](https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#packagereference-aliases) about it.
