### ISSUE TITLE
[Bug] Android await NavigationService.NavigateAsync useModalNavigation: true does not work

### ISSUE THREAD

**Issue by johng1492** [PrismLibrary/Prism#2658]
### Description
I have been trying for days for the code below to work on Android (it works perfectly on iOS). When I set useModalNavigation: null, it will push the page and load the parameters. However, for Android, when I set useModalNavigation: true, I cannot, doing anything I try, get it to load modally and have OnNavigatedTo fire off. I call the SENDING code below from App.cs (it's data from a push notification). 

THE BELOW DOES NOT FIRE OFF OnNavigatedTo on the RECEIVING PAGE running on Android.
SENDING PAGE:
var x = new NavigationParameters
 {
    {"SAMPLE_PARAMS", "123" }

 };
 await NavigationService.NavigateAsync("SamplePopUpPage", x, true, true);

RECEIVING PAGE:
public override async void OnNavigatedTo(INavigationParameters parameters)
{
     
          string result = (string)parameters["SAMPLE_PARAMS"];
}

### Steps to Reproduce

1. Create a new app from Prism.Template (Unity)
2. Add CrossPushNotification on App.cs
3. Pass data from Firebase (I use the above dummy data once the ACTION even is received in App.cs).
4. Have App.cs fire off the SENDING PAGE code above, once the push notice has been received.
5. Place RECEIVING CODE above in a second page
6. For Android, when set to useModalNavigation=true, it will not get to OnNavigatedTo

### Expected Behavior
I expect, as it works on iOS (and the other parts of the app when I'm not sending modally), the data to be send on the NavigateAsync event to the OnNavigatedTo function.

### Actual Behavior
For Android, with useModalNavigation=true, OnNavigatedTo is not fired

### Basic Information

- Version with issue: Xamarin.Forms 5.0.0.2012, Prism.Unity.Forms 8.1.97, PlugIn.PushNotification 3.6.9
- Last known good version: N/A
- Xamarin.Forms version: 5.0.0..2012
- IDE: VS Mac 8.10.9

### Reproduction Link

The EXACT code that does not work on Android is above and again here.
SENDING PAGE:
var x = new NavigationParameters
 {
    {"SAMPLE_PARAMS", "123" }

 };
 await NavigationService.NavigateAsync("SamplePopUpPage", x, true, true);

RECEIVING PAGE:
public override async void OnNavigatedTo(INavigationParameters parameters)
{
     
          string result = (string)parameters["SAMPLE_PARAMS"];
}

**Comment by brianlagunas** [comment]
Closing as you did not provide the require reproduction link.
