### ISSUE TITLE
[XF] Document the ViewModelLocator

### ISSUE THREAD

**Issue by brianlagunas** [PrismLibrary/Prism#266]

**Comment by YipingRuan** [comment]
I am happy to do this

**Comment by brianlagunas** [comment]
Great!

**Comment by YipingRuan** [comment]
Which chapter do you prefer?

Documentation/WPF/100-ViewModelLocator.md

?

**Comment by bartlannoeye** [comment]
@YipingRuan this issue is for Xamarin Forms documentation, so that would be: [Documentation/Xamarin.Forms/2-ViewModelLocator.md](https://github.com/PrismLibrary/Prism/blob/master/Documentation/Xamarin.Forms/2-ViewModelLocator.md)

**Comment by tomcrusader** [comment]
The page currently states "maybe link to primary ViewModelLocator topic".

But this is the primary topic? :smiley:

**Comment by brianlagunas** [comment]
Well, it might be :)

The majority of the VML applies to all platforms, so this topic may be move up a level in the docs.

**Comment by brianlagunas** [comment]
I have so much documentation to write, having one open issue on one topic is kind of pointless. Closing this :)
