### ISSUE TITLE
Navigation Extensions in Prism.Forms

### ISSUE THREAD

**Issue by HenJigg** [PrismLibrary/Prism#2663]
## Summary

In the process of using navigation, can you add a callback function? When the navigation returns, you can do some specific logic for the return, such as the callback in IDialogService in WPF.

## Demo:
````
navigationService.NavigateAsync("ViewA",back=>{
var param=back.Parameter;
//...
})
````

**Comment by brianlagunas** [comment]
No callback is necessary,  just await the navigation call.
