### ISSUE TITLE
[XF] Document Getting Started with Prism for XF

### ISSUE THREAD

**Issue by brianlagunas** [PrismLibrary/Prism#267]

**Comment by Mardaneus86** [comment]
I'd like to help with this. What's the format you're looking for? Markdown?

And where to place it?

**Comment by bartlannoeye** [comment]
There's already an [empty markdown](https://github.com/PrismLibrary/Prism/blob/master/Documentation/Xamarin.Forms/1-GettingStarted.md) file ready for that chapter.

For content structure, you can have a look at [this XF documentation page](https://github.com/PrismLibrary/Prism/blob/master/Documentation/Xamarin.Forms/4-PageDialogService.md) or the [WPF documentation](https://github.com/PrismLibrary/Prism/tree/master/Documentation/WPF).

**Comment by Mardaneus86** [comment]
Oh, didn't notice that. I'll take a look at where I can contribute.

**Comment by Adam--** [comment]
I started working on this. For content I was thinking:
 - Overview
 - Prerequisites
 - Background
	 - Xamarin.Forms
	 - MVVM
 - Creating a new solution
	 - Installing and using the Prism Template Pack
	 - Running the app
	 - Views overview
	 - View Models overview
 - Adding a new Page (View) and ViewModel
 - Navigating to your new Page
 - IoC and dependency injection with Unity
 - Displaying a dialog
 - Using the dependency service

**Comment by brianlagunas** [comment]
Sweet!  This will be extremely helpful.  Just a few notes:
* There is a new NuGet package for Unity for XF called Prism.Unity.Forms.  This had to be added because of XF's support for UWP.  So that will be the new NuGet to use going forward.  Although, currently it is still in preview.
* I love starting with the Prism Template Pack, but we should also have a section on how to manually set up your project just incase you don't have the Template Pack because you are on an older version of VS.
* Be sure to point to the Navigation documentation for more detailed information when you show how to navigate to a new page.
* You can drop the "Displaying a dialog" and "Using the Dependency Service" from the Getting started.  These are well documented independently.

**Comment by Adam--** [comment]
> I love starting with the Prism Template Pack, but we should also have a section on how to manually set up your project just incase you don't have the Template Pack because you are on an older version of VS.

Initially I was thinking that it would be best to show how to do it the "hard way", creating a project then adding Prism, then showing the easy way with the templates. But then I realized that the "hard way" was relying on templates from Xamarin to create the initial solution and figured we might as well use the Prism templates. It looks like the Prism templates support VS2013 and VS2015 and Xamarin supports VS2010 and up, so the VS2010 users would be missing out with this approach.

>Be sure to point to the Navigation documentation for more detailed information when you show how to navigate to a new page.
You can drop the "Displaying a dialog" and "Using the Dependency Service" from the Getting started. These are well documented independently.

I've been writing it in a walkthough style and planned on showing just enough to get started and linking to the other documentation for more information.

https://github.com/Adam--/Prism/blob/XF-Documentation/Documentation/Xamarin.Forms/1-GettingStarted.md

**Comment by brianlagunas** [comment]
Well, since I added the new Module Editor to the template pack, I have run into an issue with VS2013.  It looks like it may now be a VS2015 only thing now.  I will have to see if I can get VS2013 to play nice or not.

Your doc is looking great.  I may be weird, but I am actually quite excited about this :)

**Comment by brianlagunas** [comment]
Fixed with PR #491
