### ISSUE TITLE
[Bug] Navigation issues with plugin system

### ISSUE THREAD

**Issue by EMostafaAli** [PrismLibrary/Prism#2671]
### Description
When we develop a plugin for a host application that we don't control (e.g. Visual Studio), we should use `PrismBootstrapper` rather than `PrismApplication`. I found that the navigation service will fail to navigate if two plugins are referencing Prism Library. I believe this happens because the host application will load the prism library once for the two plugins and as `RegionManager` is static one plugin will override the other.

The following picture illustrates that
![prism1](https://user-images.githubusercontent.com/11354102/160957242-b1b8958c-7b77-4fae-80ab-271050eade1c.png)

I've created a minimal example to illustrate the issue. I created a host application that loads two plugins (Plugin-A & Plugin-B). The host app doesn't reference prism library. Each plugin is a class library that define a WPF window and a view. Each WPF window has a prism region **with different names**. For example this is the code for plugin-A
```
<Window x:Class="PrismNav.PluginA.Views.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:prism="http://prismlibrary.com/"
        xmlns:local="clr-namespace:PrismNav.PluginA.Views"
        mc:Ignorable="d"
        Title="MainWindow" Height="450" Width="800" Closing="Window_Closing">
    <Grid>
        <ContentControl prism:RegionManager.RegionName="RegionPluginA"/>
    </Grid>
</Window>
```
Each plugin defines an `Execute` Method that requests to navigate as follows:
```
public void Execute()
{
    var regionManager = ContainerLocator.Container.Resolve<IRegionManager>();
    regionManager.RequestNavigate("RegionPluginA", nameof(ViewA));
    ((MainWindow)_bs.Main).ShowDialog();
}
```
The issue is one of the plugin will navigate successfully while the other will not

### Steps to Reproduce
1.  Download the source code from [PrismNav.zip](https://github.com/PrismLibrary/Prism/files/8385227/PrismNav.zip)
2. Build Plugin-A & Plugin-B (this will copy the Dlls into host App)
3. Run the host app, it will show a window with two buttons
4. Click button A, the plugin-A main window will open but the view A will not be shown. Button B will work successfully
5. Go the host main window (code-behind) and switch the code to load plugin-B before plugin-A
6. Now button A will work but button B will fail

### Expected Behavior
Both plugins navigation should work
### Actual Behavior
Only one works

### Basic Information

- Version with issue: 8.1.97
- Last known good version: NA
- Xamarin.Forms version: NA
- IDE: Visual Studio 2022

### Screenshots
NA

### Reproduction Link
The link can be found under Steps to Reproduce

### Note
I tried to assign a different `RegionManager` to each plugin but it didn't make a difference (_Disclaimer: I am not very familiar with this approach so I might be missing something_)

**Comment by brianlagunas** [comment]
This is not a bug. RegionManager is not static. What is static is the ContainerLocator. When developing plugins its very important to understand how the host application loads the plugins. Meaning does each plugin run in the same app-domain/proc or separate? This will change the way you develop multiple plugins using Prism.

However, in this specific example your navigation logic is wrong. Just by changing where the navigation occurs, it works fine

![image](https://user-images.githubusercontent.com/835562/161304543-4009cc0c-8b04-486c-adff-393c6a41ca39.png)

**Comment by EMostafaAli** [comment]
@brianlagunas, Can you give more details about the changes you made to code? thanks.
