### ISSUE TITLE
[Bug] PrismBootStrapper Container changes if multiple plugins are loaded

### ISSUE THREAD

**Issue by EMostafaAli** [PrismLibrary/Prism#2673]
### Description

This is related to issue #2671. By no means I  try to abuse the system or waste your time but I found a new insight that might be a bug (so please give this few minutes of your time before closing it).

In the attached sample, the host will load plugin-A & B. Each plugin contains an implementation for an interface `INamed`. If I try to resolve INamed from plugin B using `PrismBootStrapper.Container.Resolve<INamed>();` _before loading PluginA_ it returns the correct implementation. However, if I call the same line after loading PluginA, PluginB will return the wrong implementation as per pictures below.

![image](https://user-images.githubusercontent.com/11354102/161625553-fda21a67-ee90-4f6f-a985-435ce5282fb4.png)

![image](https://user-images.githubusercontent.com/11354102/161625459-bfedbae6-09a2-4771-ae94-5ba04e973533.png)

### Steps to Reproduce

1. Download sample from here
[PrismPlugin.zip](https://github.com/PrismLibrary/Prism/files/8413036/PrismPlugin.zip)

2. In the class `InitB`, Put debug point in line 26 and line 32
3. Investigate variable `n` in both functions (they will give different implementations of `INamed`); Not sure why for `PluginB.PrismBootStrapper.Container` somehow changes to be `PluginA.PrismBootStrapper.Container`

### Expected Behavior
Each plugin `PrismBootStrapper.Container` should be different.

### Actual Behavior
Each Plugin `PrismBootStrapper.Container` refers to the same container instance

### Basic Information

- Version with issue: 8.1.97
- Last known good version: NA
- Xamarin.Forms version: NA
- IDE: VS 2022

### Screenshots
See above

### Reproduction Link
The link can be found under Steps to Reproduce

**Comment by brianlagunas** [comment]
As stated in the issue you referenced, the container locator is static. Meaning there can be only one. Once a new bootstapper runs the container is overwritten with the new container which looses all previous registrations.

**Comment by RexRen2021** [comment]
@EMostafaAli , have you found the solution for your question? I got a same scenerio.

I want to register all the device controller instance to a interface, too. And then I can get the exact instance when using it.

**Comment by dansiegel** [comment]
If you need to ensure that you have a single container you can do something like the following:

```cs
public class MyBootstrapper : PrismBootstrapper
{
    protected override IContainerExtension CreateContainerExtension()
    {
        // Prism 8.1 (ContainerLocator.Container is null)
        // Prism 9.0 (!ContainerLocator.IsInitialized)
        if (logic from above)
            return base.CreateContainerExtension();
        return ContainerLocator.Current;
    }
}
```

Otherwise as @brianlagunas mentioned you should manage your own reference for your Bootstapper so that you can access it's Container

**Comment by EMostafaAli** [comment]
@RexRen2021, take a look at the discussion in the link below, it describes more details about the problem I faced. I didn't find a satisfactory solution. However, when I tested with .NET core I didn't face the problem (it looks like .NET core separates app domain for different projects/plugins).
https://github.com/PrismLibrary/Prism/discussions/2674
