### ISSUE TITLE
[Bug] DryIoc 5.0.0 — Method not found: WithoutFastExpressionCompiler()

### ISSUE THREAD

**Issue by msubrosa** [PrismLibrary/Prism#2677]
### Description

While looking into switching over from Unity to DryIoc after seeing Unity has been deprecated, I noticed an error on startup when using DryIoc 5.0.0: "Method not found: 'DryIoc.Rules DryIoc.Rules.WithoutFastExpressionCompiler()"

From what I could find, it's being called here: https://github.com/PrismLibrary/Prism/blob/342689ba9a10e511418943438d0f5c57534ca623/src/Containers/Prism.DryIoc.Shared/DryIocContainerExtension.cs for the default rules.

It looks like the `FastExpressionCompiler` was moved to another library according to their github page (https://github.com/dadhi/DryIoc/tree/43638a71315d6be326df7e211649d436594aff48) which may be related. In documentation, it was also stated that this method may be removed.

"Two original parts of the DryIoc are now the separate projects: [FastExpressionCompiler](https://github.com/dadhi/FastExpressionCompiler) and [ImTools](https://github.com/dadhi/ImTools)"

Prism still works when using DryIoc 4.8.8 (previous version).

### Steps to Reproduce

1. Install NuGet package "Prism.DryIoc" & "DryIoc"
2. Update DryIoc package to latest (5.0.0)

### Expected Behavior

PrismApplication does not throw an exception when OnStartup() is called.

### Actual Behavior

An exception is thrown.

### Basic Information

- Version with issue: 8.1.97
- Last known good version:
- Xamarin.Forms version:
- IDE:

### Reproduction Link
https://github.com/msubrosa/prism-dryioc5-issue

**Comment by brianlagunas** [comment]
You can't update the DryIoC version that Prism depends on and expect it to work. Prism relies on DryIoC v4.7.7. If you upgrade DryIoC separately, you take the risk of incompatibility issues.

**Comment by msubrosa** [comment]
Ah, okay. Sorry about that.

Thank you for the fast response and clarification!

**Comment by GioviQ** [comment]
If you install the current version of DryIoc.Microsoft.DependencyInjection you didn't notice that DryIoc is updated too. Downgrade to 5.1.0.
