### ISSUE TITLE
[Bug] After Navigation stack is reset, the tapGesture in CollectionView is not working (iOS)

### ISSUE THREAD

**Issue by OscarHMG** [PrismLibrary/Prism#2682]
Description
This bug, only happens in iOS.

I have this stack navigation on my app:
/MainPage/Nav/BottomNavigationBar

My BottomNavigationBar is a TabbedPage: 3 children

TAB1: Has CollectionView.
TAB2
TAB3
TAB1, is the firstTab. This TAB, has a CollectionView with 2 TapGesture Commands per item

Steps to Reproduce
.

When the app opens, you have to click on the item (ID or Name) of the CollectionView. At first the gestures on the items. works fine.
This, send you to the DEMO PAGE. In this page, at the bottom there is a button. The command of this button RESET the navigation stack LIKE THIS /MainPage/Nav/BottomNavigationBar?selectedTab=TAB3
Expected Behavior
After the navigation is reset, the TapGestures, in the CollectionView should work.

Actual Behavior
TapGestures in my collectionView doesnt work after the nvaigation is reset. This only happen in iOS. Android is working fine as expected

Basic Information
Version with issue: Prism.Dryloc.Forms 7.2.0.1422 | Prism.Plugin.PopUps 7.2.0.1046
Xamarin.Forms version: 5.0.0.2012
IDE: Microsoft Visual Studio Community 2019 Version 16.4.4
Screenshots
Reproduction Link
Here is a link with a issue case.
https://github.com/OscarHMG/SampleBug2680-Prism/

**Comment by brianlagunas** [comment]
Prism has no control over the function of behaviors. All it does is add and remove pages to the navigation stack.
