### ISSUE TITLE
Prism is leaving the .NET Foundation

### ISSUE THREAD

**Issue by brianlagunas** [PrismLibrary/Prism#2683]
Prism joined the .NET Foundation in July of 2015 in hopes that we could build a sustainable OSS model with the backing of the various benefits the foundation would provide. Unfortunately, we have not seen any meaningful benefits being part of the .NET Foundation.

The two primary benefits Prism uses are the CLA bot and a signing certificate for the NuGet packages. Everything else is provided, and paid for, by the project maintainers personal pockets. This is done with the help of GitHub sponsors for both [Dan](https://github.com/sponsors/dansiegel) and [myself](https://github.com/sponsors/brianlagunas). Prism could not exist without the generosity of our sponsors.

As you may have heard, there were a series of unfortunate events that occurred regarding the .NET Foundation which prompted Prism to rethink its membership. After much deliberation, @dansiegel and I have decided to remove the Prism Library from the .NET Foundation.

The Prism Library has submitted an "Intent to Leave" with the .NET Foundation, and the process to leave has begun.

The Prism Library will no longer be part of the .NET Foundation by May 31, 2022.

Please, do not worry. This has no impact on the project itself. Dan and I will continue to support and maintain the Prism Library as we have been doing since Prism was handed over to the us in 2015.

**Comment by saint4eva** [comment]
Congrats.

**Comment by mzy666888** [comment]
Congrats

**Comment by nschoenberg** [comment]
Thanks for being so transparent

**Comment by wuchang** [comment]
nuget package 了不更新了？
