### ISSUE TITLE
[Enhancement] BindableBase for record type.

### ISSUE THREAD

**Issue by sawankumarbundelkhandi** [PrismLibrary/Prism#2703]
## Summary

BindableBase is a class and can't be inherited on record type. I am currently using record type for the Model and DTO on my Xamarin app. For now, I have created a record that implements I INotifyPropertyChanged and literally copied all the code from the Prism BindableBase and just changed the type to record.

## API Changes

There are no API changes. My thought is to have a BindableBase of record type as well.

e.g.

public abstract record BindableBase : INotifyPropertyChanged {
...
...
}

## Intended Use Case
This will help in NotifyPropertyChanged on the record types.

**Comment by brianlagunas** [comment]
Thank you for the suggestion, but this is not something Prism will provide. Records are primarily intended for supporting immutable data models (it's their default behavior). The entire concept of INPC goes against this.
