### ISSUE TITLE
 WithoutFastExpressionCompiler is not in the lastest DryIoc. It has been removed but is still referenced

### ISSUE THREAD

**Issue by gmarbury** [PrismLibrary/Prism#2705]
### Description

 Rules.WithoutFastExpressionCompiler is not in lastest DryIoc. It has been removed but it is referenced in the Default Rules

### Steps to Reproduce

1.  Add a nuget reference to DryIoc.dll 5.1.1 to a project with Prism.DryIoc.Forms already in it
2.  Compile
3.  Run

Also, see this link for another example of the problem.
https://stackoverflow.com/questions/72257891/system-missingmethodexception-message-method-not-found-dryioc-rules-dryioc-rule

### Expected Behavior

Works as expected 

### Actual Behavior

Method not found exception

### Basic Information

See this link for when WithoutFastExpressionCompiler  was removed
https://github.com/dadhi/DryIoc/issues/386

- Version with issue:
- Last known good version:
- Xamarin.Forms version:
- IDE:

**Comment by dansiegel** [comment]
You should not be updating DryIoc on your own. We are well aware of the changes. Prism.Maui is currently built against the latest version of DryIoc, and the next release of Prism will include those updates.If this is that much of a blocker for you I suggest you do not reference the official Prism.DryIoc.Forms package and provide your own implementation.

**Comment by gmarbury** [comment]
Thank you for the quick response.  I increased the version because I  needed to use Rules.WithoutTrackingDisposableTransients which is not in 4.7.7. Maybe you guys should consider changing the NUGET dependencies from DryIoc.dll >= 4.7.7  to DryIoc.dll <= 5.0.0 to make it clear that you are aware of the non-breaking change. By the way, 4.8 so far seems to work fine.

Have a nice day.
