### ISSUE TITLE
[Enhancement] Cancel `IRegion.Remove` from within view

### ISSUE THREAD

**Issue by Pretasoc** [PrismLibrary/Prism#2717]
## Summary

I'm currently devloping an app, that has hosts a tabcontrol, which hosts some document like views. When i close a view, i currently remove it with `IRegion.Remove(view)` from the region. But there is no buildin way (afaik) to cancel the removal from within the view to display a warnin about unsaved changed for example.

What i need is something like `IConfirmNavigation`, that is called prior removing a view from a region, and allows it to cancel the removal.

## API Changes

Add a new interface, that may be implemented by the view or the region.

```
public interface IConfirmRemoval
{
    void ConfirmRemoval(Action<bool> continuationCallback);
}
``` 
If a view or viewmodel implements this interface and a view is removed from a region. The `ConfirmRemoval` method would be called and the removal would be suspended until the callback was called from within the view either confirming or cancelling the removal.

A second change could be helpful, but it might be bit to much, since it would be a breaking change to the `IRegion` interface, thus requirering all clients to implement it as well.

``` 
public interface IRegion
{
    Remove(object view, Action<bool> removalCompleted);

    RemoveAll(Action<bool> removalCompleted)
}
``` 

This method would behave like the existing `Remove` and `RemoveAll` methods, but call the the delegate, once the callback was called from inside the view.

In the case of `RemoveAll` the callback would be invoked once all views have responded to the removal request. The parameter would be only true, whenn all views confirmed the removal.

If neither the view nor the viewmodel implements `IConfirmRemoval` the view is removed and the delegate is called straight away.

If you attempt to remove a view from a region, that has an pending confirmation (`ConfirmRemoval` was called, but the delegate has not been invoked yet), `ConfirmRemoval` is called again with the same callback, so that any of the two method can close the view or keep it open. This should be also true for the delegates passed to `Remove(object, Action<bool>)`. If one of the `continationCallbacks` are invoked all `removalCompleted` delegates will be invoked with the same result. 

## Intended Use Case

Prism already has a mechanism to coorporate with a view, when it`s deavtiaved or navigated away from. But in some scenarios its okay to leave a view in a dirty state, when the user might switch to an other view and then return to finish his work, as long as the state ist correctly stored, before the view ist closed (removed from the region). Although it is possible to provent this in current prism, it feels a little bit hacky to do so, as it is not directly supported by the infrastructure.

So the way this works is, whenever a view is about to be removed from a region, the view can intercept this request and confirm or cancel that operation.

## Additional extension points

There are some other features, that could be added to this idea as well, but they seem to unneccessay open the scope of this issue, so i just list them here without really going into details:

### Force Removal
A drawback of the proposed solution is, that a bad implemented view, can completly block the removal by accidend, when it never calls the callback. In the solutin i proposed the is currently no way to force the removal of the view. So there might be need to allow bypassing the `IConfirmRemoval`.

### Parameters
As proposed there are no parameters in the close request. One possibility so reduce the impact of the issue above could be the introduction of parameters in the removal request. That way you could set a `forceRemoval` parameter and react to it in the implementaton of `ConfirmRemoval`

**Comment by brianlagunas** [comment]
Since you are using the region APIs to manage the region, you are responsible for all aspects of removing the view. This includes canceling the remove.

You're over thinking this. Just show your dialog before you call region.Remove.
