### ISSUE TITLE
[BUG] EventAggregator system bug

### ISSUE THREAD

**Issue by ai2soft** [PrismLibrary/Prism#2735]
### Description

there is a hidden bug with  EventAggregator.
the EventAggregator method  **EventSubscription.GetExecutionStrategy** should check the **Action.Target** 's state before invoke the method.

i did a test , code bellow

`
public partial class MainWindow : Window
    {
        private ActTestCls _actTestCls;
        private IEventAggregator _eventAggregator;

        public MainWindow()
        {
            InitializeComponent();

            _eventAggregator = EventsService.GetSystemWideEventAggregator();

            Test();
        }

        private void Act1(string msg)
        {
            System.Diagnostics.Debug.WriteLine(msg);
        }

        private void Act2(string msg)
        {
            System.Diagnostics.Debug.WriteLine(msg);
        }

        private void Test()
        {
            _eventAggregator.GetEvent<TestEventMessage>().Subscribe(Act1);
            _eventAggregator.GetEvent<TestEventMessage>().Subscribe(Act2);

            Task.Run(() =>
            {
                Thread.Sleep(2000);

                System.Diagnostics.Debug.WriteLine("test output  act -------------------------------------1");
                _eventAggregator.GetEvent<TestEventMessage>().Publish("I am the text message");

                Thread.Sleep(2000);
                System.Diagnostics.Debug.WriteLine("unregister Act2");
                _eventAggregator.GetEvent<TestEventMessage>().Unsubscribe(Act2);

                Thread.Sleep(2000);
                System.Diagnostics.Debug.WriteLine("test output  act -------------------------------------2");
                _eventAggregator.GetEvent<TestEventMessage>().Publish("I am the text message");

                Thread.Sleep(2000);
                System.Diagnostics.Debug.WriteLine("new register ActTestCls.Test");
                _actTestCls = new ActTestCls();

                Thread.Sleep(2000);
                System.Diagnostics.Debug.WriteLine("test output  act -------------------------------------3");
                _eventAggregator.GetEvent<TestEventMessage>().Publish("I am the text message");

                System.Diagnostics.Debug.WriteLine("unregister Act1, left ActTestCls.Test only");
                _eventAggregator.GetEvent<TestEventMessage>().Unsubscribe(Act1);

                System.Diagnostics.Debug.WriteLine("set ActTestCls = null , but, not unregister ActTestCls.Test.\t what will expect is output nothing , but ..");
                _actTestCls = null;

                Thread.Sleep(1);
                System.Diagnostics.Debug.WriteLine("test output  act -------------------------------------4");
                _eventAggregator.GetEvent<TestEventMessage>().Publish("I am the text message");

            });
        }
    }

    class ActTestCls
    {
        public ActTestCls()
        {
            EventsService.GetSystemWideEventAggregator().GetEvent<TestEventMessage>().Subscribe(Test);
        }

        public void Test(string msg)
        {
            System.Diagnostics.Debug.WriteLine("this is Test");
        }
    
    }

`

the output is 

> 
> test output  act -------------------------------------1
> 
> I am the text message
> 
> I am the text message
> 
> unregister Act2
> 
> test output  act -------------------------------------2
> 
> I am the text message
> 
> new register ActTestCls.Test
> 
> test output  act -------------------------------------3
> 
> this is Test
> 
> I am the text message
> 
> unregister Act1, left ActTestCls.Test only
> 
> test output  act -------------------------------------4
>
> this is Test   //<----------------it is wrong, here

as you can see, most of the time , we forgot to unregister a subscribe,  the EventAggregator system even doesn't check the **Target** state before invoke . so a unusable objcts's method will be invoked. it's not right.

### Steps to Reproduce

1.create a new app
2.reference Prism
3. define a message object
```
    internal class TestEventMessage : PubSubEvent<string>
    {
    }
```
4. copy and past follow code
```
public partial class MainWindow : Window
    {
        private ActTestCls _actTestCls;

        private IEventAggregator _eventAggregator;

        public MainWindow()
        {
            InitializeComponent();


            _eventAggregator = EventsService.GetSystemWideEventAggregator();


            Test();
        }

        private void Act1(string msg)
        {
            System.Diagnostics.Debug.WriteLine(msg);
        }

        private void Act2(string msg)
        {
            System.Diagnostics.Debug.WriteLine(msg);
        }

        private void Test()
        {
            _eventAggregator.GetEvent<TestEventMessage>().Subscribe(Act1);
            _eventAggregator.GetEvent<TestEventMessage>().Subscribe(Act2);

            Task.Run(() =>
            {
                Thread.Sleep(2000);

                System.Diagnostics.Debug.WriteLine("test output  act -------------------------------------1");
                _eventAggregator.GetEvent<TestEventMessage>().Publish("I am the text message");

                Thread.Sleep(2000);
                System.Diagnostics.Debug.WriteLine("unregister Act2");
                _eventAggregator.GetEvent<TestEventMessage>().Unsubscribe(Act2);

                Thread.Sleep(2000);
                System.Diagnostics.Debug.WriteLine("test output  act -------------------------------------2");
                _eventAggregator.GetEvent<TestEventMessage>().Publish("I am the text message");


                Thread.Sleep(2000);
                System.Diagnostics.Debug.WriteLine("new register ActTestCls.Test");
                _actTestCls = new ActTestCls();

                Thread.Sleep(2000);
                System.Diagnostics.Debug.WriteLine("test output  act -------------------------------------3");
                _eventAggregator.GetEvent<TestEventMessage>().Publish("I am the text message");

                System.Diagnostics.Debug.WriteLine("unregister Act1, left ActTestCls.Test only");
                _eventAggregator.GetEvent<TestEventMessage>().Unsubscribe(Act1); //删除 Act1， 只保留 ActTestCls.Test

                System.Diagnostics.Debug.WriteLine("set ActTestCls = null , but, not unregister ActTestCls.Test.\t what will expect is output nothing , but ..");
                _actTestCls = null;

                Thread.Sleep(1);
                System.Diagnostics.Debug.WriteLine("test output  act -------------------------------------4");
                _eventAggregator.GetEvent<TestEventMessage>().Publish("I am the text message");

            });
        }
    }

    class ActTestCls
    {
        public ActTestCls()
        {
            EventsService.GetSystemWideEventAggregator().GetEvent<TestEventMessage>().Subscribe(Test);
        }

        public void Test(string msg)
        {
            System.Diagnostics.Debug.WriteLine("this is Test");
        }
    
    }

```
5. run debug

### Platform with bug

Prism Core

### Affected platforms

Windows, I was *not* able test on other platforms

### Did you find any workaround?

        public virtual Action<object[]> GetExecutionStrategy()
        {
            Action<TPayload> action = this.Action;
            Predicate<TPayload> filter = this.Filter;                               
            if (action != null && filter != null) // Check this.Action.Target is being disposed of not at the same time
            {
                return arguments =>
                {
                    TPayload argument = default(TPayload);
                    if (arguments != null && arguments.Length > 0 && arguments[0] != null)
                    {
                        argument = (TPayload)arguments[0];
                    }
                    if (filter(argument))
                    {
                        InvokeAction(action, argument);
                    }
                };
            }
            return null;
        }

### Relevant log output

```shell
test output  act -------------------------------------1
I am the text message
I am the text message
unregister Act2
test output  act -------------------------------------2
I am the text message
new register ActTestCls.Test
test output  act -------------------------------------3
this is Test
I am the text message
unregister Act1, left ActTestCls.Test only
set ActTestCls = null , but, not unregister ActTestCls.Test.	 what will expect is output nothing , but ..
test output  act -------------------------------------4
this is Test
```

**Comment by brianlagunas** [comment]
This is not a bug. This is an issue with your code. EventsService is a static class and you are registering a method with a static class. The event aggregator cannot check the “state” of a “target”. That’s not how it works. You are simply registering delegates to invoke when the event is executed. It uses weak event to make sure once an object is garbage collection the registered events are released. Objects can stay in memory for some time before being garbage collected

**Comment by ai2soft** [comment]
actully you are wrong . 

       static EventsService is a system wide class , a singleton object .

the problem is  ActTestCls = null , and ActTestCls.Test still is can be invoked.

that's the problem . 

i know objects will stay in memory after set to null or  dispose.  but , 
Prism dosen't check target's state (is disposed or not ) will cause bugs , right ?

**Comment by brianlagunas** [comment]
You didn’t provide all the sample code so I had to make assumptions. Doesn’t matter, the fact still remains that Prism can’t check a “state”. Setting something to null doesn’t remove it from memory. The object has to be garbage collected first. It works as expected.

**Comment by ai2soft** [comment]
Thanks. i just did another test , and made _eventAggregator as a private variable, and the result was what i expected.

`_eventAggregator = new EventAggregator();`

**Comment by ai2soft** [comment]
and i'm not sure about my code.


    public static class EventsService
    {
        public static IEventAggregator GetSystemWideEventAggregator()
        {
            return InternalEventAggregator.Instance.EventAggregator;
        }
    }

    internal class InternalEventAggregator
    {
        private InternalEventAggregator()
        {
            EventAggregator = new EventAggregator();
        }

        public static InternalEventAggregator Instance { get; } = new InternalEventAggregator();

        public IEventAggregator EventAggregator { get; private set; }
    }


as you can see , i want a system wide singleton object to hold EventAggregator.  for now i'm puzzled.
