### ISSUE TITLE
question: Where is RegisterFrameworkExceptionType?

### ISSUE THREAD

**Issue by odalet** [PrismLibrary/Prism#274]
Hi, I've just tried to port my Prism 4.1 based application to Prism 6.1; once I've tweaked the namespaces everything went fine except for the line below:

```csharp
ExceptionExtensions.RegisterFrameworkExceptionType(
    typeof(Microsoft.Practices.ServiceLocation.ActivationException));
```

Is this still supported in v6.1? Is it required (I've commented the code, and my app seems to run just fine, but I think I resolve all the services I need...).

PS: this used to be located in Microsoft.Practices.Prism.dll as of v4.1 (and it exists in v5: https://msdn.microsoft.com/en-us/library/microsoft.practices.prism.exceptionextensions.registerframeworkexceptiontype(v=pandp.50).aspx).

Thanks!

**Comment by brianlagunas** [comment]
This exists in Prism.Wpf.dll now.

https://github.com/PrismLibrary/Prism/blob/master/Source/Wpf/Prism.Wpf/Extensions/ExceptionExtensions.cs

**Comment by odalet** [comment]
Thanks!

**Comment by weitzhandler** [comment]
Any documentation or example on how to use `RegisterFrameworkExceptionType` and `ExceptionExtensions`?
Is this some sort of global exception catcher?
I tried unsuccessfully to [look it up](https://readthedocs.org/search/?q=registerframeworkexceptiontypes&check_keywords=yes&area=default&project=prismlibrary&version=latest&type=file) in the docs.
