### ISSUE TITLE
Bootstrapping an App with Prism 6

### ISSUE THREAD

**Issue by PaybackMan** [PrismLibrary/Prism#275]
I'm familiar with Prism.Forms but can't seem to find the UnityBootstrapper for Prism 6. Are we required to configure our Unity container in the PrismApplication.CreateAndConfigureContainer()??? If so does anyone have some sample code to get started?

Thanks,
  Travis

**Comment by PaybackMan** [comment]
Looks like I was derriving my App class from PrismApplication instead of PrismUnityApplication...
I guess this is our new Bootstrap area??

**Comment by brianlagunas** [comment]
No just add Prism.Unity to your Xamarin.Forms solution.

Check out these samples: https://github.com/PrismLibrary/Prism-Samples-Forms

**Comment by brianlagunas** [comment]
Prism.Forms does not have a PrismApplication, or PrismUnityApplication
