### ISSUE TITLE
Reuse Prism.Forms ViewModels with Prism 6 UWP app??

### ISSUE THREAD

**Issue by PaybackMan** [PrismLibrary/Prism#276]
Are there any plans to consolidate the BindableBase found in Prism.Forms with something I can use within my UWP Prism 6 based app? I noticed XF is moving towards UWP support but I'm a little concerned about the story with Prism and how these two worlds will coincide...

Thanks,
  Travis

**Comment by brianlagunas** [comment]
BindableBase is already supported in UWP.  It's in the core Prism PCL.  Xamarin.Forms is working on UWP support, so when that is released, you will be using Prism.Forms with Xamarin.Forms to create iOS, Android, and UWP apps.
