### ISSUE TITLE
[BUG] <Possible bug with IDialogService.ShowDialog callback parameter>

### ISSUE THREAD

**Issue by GrandStrateguerre** [PrismLibrary/Prism#2762]
### Description

I create a simple dialog :
![image](https://user-images.githubusercontent.com/86523070/187040128-e64795ac-c412-4a33-a6ca-89d48dc574b1.png)
![image](https://user-images.githubusercontent.com/86523070/187040548-3dd4f64c-1814-422d-8e01-97e03c6a6e3f.png)

The code for the callBack is :
![image](https://user-images.githubusercontent.com/86523070/187040202-637a0eaa-1a8b-4cf5-aecc-4352a57d363d.png)
![image](https://user-images.githubusercontent.com/86523070/187040285-ce4ac8f7-0380-4a65-be8e-60a8c2ade4da.png)

The code for  CloseDialogCommand  :
![image](https://user-images.githubusercontent.com/86523070/187040606-b1a16a29-5c0d-4ab8-a377-8585ce709e53.png)
![image](https://user-images.githubusercontent.com/86523070/187040693-0b312ad8-f8b8-4b54-b0e9-b946737cbece.png)

When I click on button OK everything works fine.
![image](https://user-images.githubusercontent.com/86523070/187040799-f4df7676-a6e5-42ca-aead-2a021f0e5d39.png)
When I not click on the button OK (Red cross)  works not as expected ;
I expect to get the parameter with key param2 but the collection result.PArameters is empty
![image](https://user-images.githubusercontent.com/86523070/187040871-234ba00a-65a1-4af9-8d2a-dd7585bba4b1.png)

### Steps to Reproduce

Use Prism 8.1.97 with  .net Framework 4.8

source code :

1. MessageDialogViewModel.cs  

using PowerTools.Core;
using Prism.Commands;
using Prism.Services.Dialogs;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace PowerTools.Dialogs.ViewModels
{
    public class MessageDialogViewModel : ViewModelDialogBase
    {
        private string _message;

        public string Message
        {
            get => _message;
            set => _ = SetProperty(ref _message, value);
        }

        public DelegateCommand CloseDialogCommand { get; }

        public MessageDialogViewModel()
        {
            CloseDialogCommand = new DelegateCommand(CloseDialog);
        }

        //public override event Action<IDialogResult> RequestClose;

        public override void OnDialogOpened(IDialogParameters parameters)
        {
            Message = parameters.GetValue<string>("message");
        }
    }
}

2. MessageDialog.xaml
<UserControl x:Class="PowerTools.Dialogs.Views.MessageDialog"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
             xmlns:local="clr-namespace:PowerTools.Dialogs.Views"
             xmlns:prism="http://prismlibrary.com/"
             xmlns:viewmodels="clr-namespace:PowerTools.Dialogs.ViewModels"
             d:DataContext="{d:DesignInstance Type=viewmodels:MessageDialogViewModel}"
             prism:ViewModelLocator.AutoWireViewModel="True"
             mc:Ignorable="d"
             d:DesignHeight="450" d:DesignWidth="800">
    <Grid x:Name="LayoutRoot" Margin="25">
        <Grid.RowDefinitions>
            <RowDefinition Height="Auto" />
            <RowDefinition Height="*" />
        </Grid.RowDefinitions>

        <TextBlock HorizontalAlignment="Stretch"
                   VerticalAlignment="Stretch"
                   Grid.Row="0"
                   Text="{Binding Message}"
                   Margin="10" />
        <Button Content="OK"
                Width="75"
                Height="25"
                HorizontalAlignment="Right"
                Command="{Binding CloseDialogCommand}"
                Margin="10"
                Grid.Row="1" />
    </Grid>
</UserControl>

3. ViewModelDialogBase.cs
using Prism.Mvvm;
using Prism.Services.Dialogs;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace PowerTools.Core
{
    /// <summary>
    /// Base class for constructing dialog view model
    /// <para>Inherits of <see cref="BindableBase"/> and <see cref="IDialogAware"/></para>
    /// </summary>
    public class ViewModelDialogBase : BindableBase, IDialogAware
    {
        #region Implements IDialogAware

        public event Action<IDialogResult> RequestClose;

        public virtual string Title => "My Message dialog";

        public virtual bool CanCloseDialog()
        {
            return true;
        }

        public virtual void OnDialogClosed()
        {
        }

        public virtual void OnDialogOpened(IDialogParameters parameters)
        {
        }

        #endregion Implements IDialogAware

        private string messageReceived;

        public string MessageReceived
        {
            get => messageReceived;
            set => SetProperty(ref messageReceived, value);
        }

        public void CloseDialog()
        {
            ButtonResult result = ButtonResult.OK;

            DialogParameters p = new();
            p.Add("param1", "Ok button clicked");
            p.Add("param2", "Ok button not clicked");

            RequestClose?.Invoke(new DialogResult(result, p));
        }

        public enum DialogParametersKey
        { OkClicked = 0, OkNotClicked = 1 }
    }
}

4. Showing Dialog from  a view (ViewModel)
  public DelegateCommand ShowDialogCommand { get; } => declare
 ShowDialogCommand = new DelegateCommand(ShowDialog); => in ctor

        private void ShowDialog()
        {
            var p = new DialogParameters();
            p.Add("message", "this a test message.");
            //p.Add("","");

            My.DialogService.ShowDialog("MessageDialog", p, result =>
            {
                if (result.Result == ButtonResult.OK)
                {
                    MessageReceived = result.Parameters.GetValue<string>("param1");
                }
                else
                {
                    MessageReceived = result.Parameters.GetValue<string>("param2");
                }
            });
        }

### Platform with bug

WPF

### Affected platforms

Windows

### Did you find any workaround?

no

### Relevant log output

```shell
no log
```

**Comment by brianlagunas** [comment]
Why would you expect the window's X button to invoke your custom command? The answer to that question will lead you to your answer.

**Comment by GrandStrateguerre** [comment]
yes right :)
