### ISSUE TITLE
Register Views going to wrong region

### ISSUE THREAD

**Issue by stevensrf11** [PrismLibrary/Prism#2763]
### Description

I have two views each with a different region name.
These two views are contained in a user control that is navigated to which has its own region name.
In the Loaded event handler the region names for each of the two views has to be set in the region manager.
An instance of each view is created by using resolve method off the container provider.
Each region is obtained for of the view models.
Each instance of each view is added to to each corresponding region.
The problem is the second view which is suppose to show up in region two is showing up in region one.
The first view will show up in region one is the second view is added to the region two. 
A sample project is located on git hub at the following link
or in the attach project zip file locates in steps to reproduce section
The Super.User.Render.Catheter.Module project is where the two views are contained.
The setting of the regions for the two view is done in the RenderCatheterUserControl_Loaded loaded event handle in the RenderCatheterUserControl.xaml.cs file. This loaded event hander is called first.
Next the loaded event handle in the view model for the user control is called to resolve the views and add the views to the corresponding region names. Look at the NavigationToRenderCatheterControl() method in the RenderCatheterUserControlViewModel_Commands.cs

https://github.com/stevensrf11/superuser

### Steps to Reproduce

Run the application on git hub or in the attach zip project
Click on the Render button
The second view will appear where the first view is suppose to be
This is seen where a text block appear with a green background.
That second view should appear on the right side of the grid splitter no the left side of the grid splitter where it appears now.
The Super.User.Render.Catheter.Module project is where the two views are contained.
The setting of the regions for the two view is done in the RenderCatheterUserControl_Loaded loaded event handle in the RenderCatheterUserControl.xaml.cs file. This loaded event hander is called first.
Next the loaded event handle in the view model for the user control is called to resolve the views and add the views to the corresponding region names. Look at the NavigationToRenderCatheterControl() method in the RenderCatheterUserControlViewModel_Commands.cs

[SuperUser.zip](https://github.com/PrismLibrary/Prism/files/9438718/SuperUser.zip)
 

### Platform with bug

Prism Core

### Affected platforms

Windows

### Did you find any workaround?

no

### Relevant log output

```shell
no log
```

**Comment by stevensrf11** [comment]
Found correction just delete this issue

**Comment by brianlagunas** [comment]
The chances of you finding a bug in Prism for WPF is very slim. If you run into an issue, chances are extremely high it's a problem with your code 😄

**Comment by stevensrf11** [comment]
Yea that is usually what it is.

 
 

Sent: Saturday, August 27, 2022 at 6:38 PM
