### ISSUE TITLE
[BUG] Unknown method "WithoutFastExpressionCompiler" in DryIocContainerExtension.DefaultRules

### ISSUE THREAD

**Issue by alansingfield** [PrismLibrary/Prism#2770]
### Description

https://github.com/PrismLibrary/Prism/blob/master/src/Containers/Prism.DryIoc.Shared/DryIocContainerExtension.cs

I've updated DryIoc to verion 5.2.2, and now receive the following error when calling DryIocContainerExtension.DefaultRules:

```
System.MissingMethodException: Method not found: 'DryIoc.Rules DryIoc.Rules.WithoutFastExpressionCompiler()'.
```

### Steps to Reproduce

Create Prism Application using DryIoc.dll v5.2.2, Prism.Wpf 8.1.97, Prism.DryIoc 8.1.97

Run application; error occurs on startup.

### Platform with bug

WPF

### Affected platforms

Windows

### Did you find any workaround?

Workaround is to create my own version of DefaultRules and override CreateContainerRules() to use this.

```
public partial class MyPrismApplication : PrismApplication
{
        public static Rules DefaultRules => Rules.Default.WithConcreteTypeDynamicRegistrations(reuse: Reuse.Transient)
                                                         .With(Made.Of(FactoryMethod.ConstructorWithResolvableArguments))
                                                         .WithFuncAndLazyWithoutRegistration()
                                                         .WithTrackingDisposableTransients()
                                                         //.WithoutFastExpressionCompiler()
                                                         .WithFactorySelector(Rules.SelectLastRegisteredFactory());

        protected override Rules CreateContainerRules()
        {
            return DefaultRules;
        }

```

**Comment by dansiegel** [comment]
Please be sure to check for duplicate issues before opening this. This is not a bug.
see: #2677 #2679 #2705

**Comment by alansingfield** [comment]
Just wondering if the workaround I've put in here is all that is needed to get it working again - have you noticed any other problems upgrading DryIoc on the MAUI platform?

**Comment by lwlivy** [comment]
Thanks
