### ISSUE TITLE
[BUG] containerRegistry.RegisterViewForNavigation doesnt work with generic viewmodels

### ISSUE THREAD

**Issue by jamestays** [PrismLibrary/Prism#2772]
### Description

I have a View called `SimpleListView `that has a `viewModel `of type `SimpleListViewModel<TModel>` when I register multiple views for navigation such as:

        ```
containerRegistry.RegisterForNavigation<SimpleListView, SimpleListViewModel<Expense>>(UserModuleViewNames.ExpensesView);
        containerRegistry.RegisterForNavigation<SimpleListView, SimpleListViewModel<Trip>>(UserModuleViewNames.TripsView);
```

The container always returns the last instance of `TModel`

### Steps to Reproduce

1. Create WPF App
2. Add Prim.DryLoc
3. Create View
4. Create Generic ViewModel
5. Register view 2 times with 2 different generic types
6. navigate to first type and try to cast type of T to first type
 
it will crash

[Download Example](https://github.com/jamestays/PRISM_GENERIC_EXAMPLE)

you can download this and be able to reproduce it

### Platform with bug

WPF

### Affected platforms

Windows, I was *not* able test on other platforms

### Did you find any workaround?

no

**Comment by brianlagunas** [comment]
This is not a bug. Please research how dependency injection works and what the expectations are for the container you are using.
