### ISSUE TITLE
[BUG] Android Physical back button issue

### ISSUE THREAD

**Issue by KurasovAnton** [PrismLibrary/Prism#2774]
### Description

- OnDialogClosed of IDialogAware is not called on the Android physical back button.
- ShowDialog callback not called on the Android physical back button

How could I detect that the dialog was closed on the Android physical back button?

### Steps to Reproduce

1. Display dialog
2. Press android physical back button

### Platform with bug

Xamarin.Forms

### Affected platforms

Android

### Did you find any workaround?

No

**Comment by brianlagunas** [comment]
No repo
