### ISSUE TITLE
App is crashing when using Prism with Shiny

### ISSUE THREAD

**Issue by alamzaib-farooq** [PrismLibrary/Prism#2777]
### Description

I am using the latest Shiny with Prism. I am using:

Prism.ContainerExtenstions 8.0.62
Prism.DryIoc.Forms 8.1.97
Prism.Forms.Extended 8.0.62

The is working fine but when I use Shiny Startup class it just crashes.

Here are the error details:
![Screenshot 2022-10-09 005813](https://user-images.githubusercontent.com/25901497/194725756-eced5282-5fa8-43e9-a63a-e5abcf6cf4b1.png)

Here is the Startup class:
`public class Startup : ShinyStartup
    {

        public override void ConfigureServices(IServiceCollection services, IPlatform platform)
        {
            services.UseGeofencing<GeofenceDelegate>();
            services.UseNotifications();
            services.UseGps();
            Console.WriteLine("Shiny Added");
        }
        
        
        public override IServiceProvider CreateServiceProvider(IServiceCollection services)
        {
            ContainerLocator.SetContainerExtension(() => new DryIocContainerExtension());
            var container = Prism.Ioc.ContainerLocator.Container.GetContainer();
            DryIocAdapter.Populate(container, services);
            return container.GetServiceProvider();
        }
   } `

Here is file where you can see my all packages.
[ProjectPackages.txt](https://github.com/PrismLibrary/Prism/files/9740185/ProjectPackages.txt)

### Steps to Reproduce

1. Add Prism to your app
2. Try to integrate Shiny in your app

### Platform with bug

Xamarin.Forms

### Affected platforms

Android

### Did you find any workaround?

No

**Comment by brianlagunas** [comment]
No reproduction
