### ISSUE TITLE
[BUG] DryIoc new version don't container functions: WithoutFastExpressionCompiler()

### ISSUE THREAD

**Issue by mzy666888** [PrismLibrary/Prism#2789]
### Description

Use DryIoc new version, not container the function: `WithoutFastExpressionCompiler` ,  
so the file : `DryIocContainerExtension.cs`  should remove the function `WithoutFastExpressionCompiler `

### Steps to Reproduce

on nuget page ,update dryioc package to lastest version.

### Platform with bug

WPF

### Affected platforms

Windows

### Did you find any workaround?

remove the function: `WithoutFastExpressionCompiler`

### Relevant log output

```shell
not
```

**Comment by brianlagunas** [comment]
Please be sure to check for duplicate issues before opening this. This is not a bug.
see: #2667 #2679 #2705 and #2770
