### ISSUE TITLE
[XF] Add Prism.Ninject.Forms

### ISSUE THREAD

**Issue by rprouse** [PrismLibrary/Prism#279]
Oren Novotny released the Portable.NInject NuGet that supports Xamarin.

- Add a Prism.Ninject.Forms project and test project.
- Add to the Prism.Ninject nuget and adjust the dependencies accordingly.

I am giving this a try. Interested in a pull request if it works out?

**Comment by bartlannoeye** [comment]
Go for it ! :+1:
