### ISSUE TITLE
[BUG] Uno.WinUI with Prism windows project not building

### ISSUE THREAD

**Issue by michelebonomelli** [PrismLibrary/Prism#2795]
### Description

Build fails after adding Prism.Uno.WinUI to a Uno WinUI Windows project with this error:
`Improper project configuration: WindowsPackageType is set to None, but AppxPackage is set to true.`

Project created with standard Uno Template "Uno Platform App".
Prism nuget version is 8.1.97.

### Steps to Reproduce

-> Create a new project with template "Uno Platform App", include "Windows" target
-> Add nuget package "Prism.Uno.WinUI" to all solution projects
-> Build

### Platform with bug

Uno Platform - WinUI

### Affected platforms

Windows

### Relevant log output

```shell
Improper project configuration: WindowsPackageType is set to None, but AppxPackage is set to true.
```

**Comment by brianlagunas** [comment]
You did not provide the required reproduction app, in addition you didn't provide any version information either. My guess is you are trying to use Prism in the latest version of Uno which isn't currently supported.
