### ISSUE TITLE
Calling base.ConfigureRegionAdapterMappings() throws when adding a custom adapter

### ISSUE THREAD

**Issue by znakeeye** [PrismLibrary/Prism#2798]
### Description

Trying to add a custom `Selector` adapter as shown below. The problem is that when calling the base method, it throws an error:

> System.InvalidOperationException: 'Mapping with the given type is already registered: Selector.'

```c#
protected override void ConfigureRegionAdapterMappings(RegionAdapterMappings regionAdapterMappings)
{
    regionAdapterMappings.RegisterMapping<Selector, MySelectorRegionAdapter>();
    base.ConfigureRegionAdapterMappings(regionAdapterMappings);
}
```

You would expect the base implementation to gracefully handled any custom registrations, similar to the `AddIfMissing()` method used in `ConfigureDefaultRegionBehaviors()`.

### Steps to Reproduce

1. Create a `Prism.DryIoc.PrismApplication` app.
2. Override `ConfigureRegionAdapterMappings()`.
3. Add a custom adapter for a known type, e.g. `Selector`.
4. Run the app.

### Platform with bug

WPF

### Affected platforms

Windows, I was *not* able test on other platforms

### Did you find any workaround?

Instead of calling `base.ConfigureRegionAdapterMappings()` you can manually add its registrations manually:

```c#
protected override void ConfigureRegionAdapterMappings(RegionAdapterMappings regionAdapterMappings)
{
    regionAdapterMappings.RegisterMapping<Selector, MySelectorRegionAdapter>();

    // WORKAROUND: Do not call base! Instead, add its registrations here.
    // Let's hope the base implementation never changes or things will break!
    regionAdapterMappings.RegisterMapping<ItemsControl, ItemsControlRegionAdapter>();
    regionAdapterMappings.RegisterMapping<ContentControl, ContentControlRegionAdapter>();
}
```

**Comment by brianlagunas** [comment]
Not a bug. This is by design. It worked exactly as it was intended.
