### ISSUE TITLE
[BUG] Using registered View with ViewModel as UserControl in a collection results doubling the ViewModel

### ISSUE THREAD

**Issue by Speedy044** [PrismLibrary/Prism#2800]
### Description

Hi,
I notice when I have registered View (UserControl) with ViewModel in e.g. module and trying to use this UserControl e.g. as a List item in parent View the object in the list (ViewModel) is diffrent then acctual ViewModel of UserControl I see on my screen. When I deregister it from module - everything works fine.

### Steps to Reproduce

Create Prism Module project.
Create some UserControl and ViewModel for it.
Register UserControl with ViewModel using ViewModelLocator in module starting point file (ViewModelLocationProvider.Register<View, ViewModel>();)
Create a ObservableCollection<ViewModels> and add some objects to it.

Bind ObservableCollection to e.g. ListBox in MainWindow. 

Check if objects are the same objects as you see on the screen, best way is to make any public property in ViewModel and give it a value while adding to a list (not in constructor). UserControls on the screen will not have those values.

### Platform with bug

WPF

### Affected platforms

I was *not* able test on other platforms

**Comment by brianlagunas** [comment]
Did not provide required repro app. Even without it, I can tell you this is an issue in your code and not Prism.
