### ISSUE TITLE
[BUG] Registration of factory method in DryIoC uses default Reuse instead of transient

### ISSUE THREAD

**Issue by azabluda** [PrismLibrary/Prism#2802]
### Description

**Reproduction project**: https://github.com/azabluda/Prism
**Branch**: 8.1.97-TransientDelegateRegistration
**Path**: tests\Wpf\Prism.DryIoc.Wpf.Tests\PrismBugRepro.cs

As per documentation `DryIocContainerExtension.Register` is supposed to register a **Transient** service. It is working as expected only for simple type-based registrations (see attached picture). However, registration via factoryMethod is using the **default** Reuse policy instead of **Transient**. Thus if your DryIoC container overrides the default Reuse (e.g. [MefAttributedModel](https://github.com/dadhi/DryIoc/blob/master/docs/DryIoc.Docs/Extensions/MefAttributedModel.md) configures Reuse.Singleton for delegate based registrations), then there is no way to register a factoryMethod as a Transient service.

![image](https://user-images.githubusercontent.com/7567733/214319463-efc38ca6-12ce-4ba5-8eda-d4ec51e084f1.png)

### Steps to Reproduce

1. Create Prism WPF application project with DryIoc
2. Override default Reuse policy with Reuse.Singleton for DryIoC container
3. Register a service via delegate using IContainerRegistry.Register 

EXPECTED: the service registers as Transient

ACTUAL: the service registers as Singleton

### Platform with bug

WPF

### Affected platforms

Windows, I was *not* able test on other platforms

### Did you find any workaround?

Temporarily using our own extension method which explicitly passes Reuse.Transient to DryIoC:
```cs
    public static class PrismBugWorkaround
    {
        public static IContainerRegistry RegisterTransient<T>(this IContainerRegistry containerRegistry, Func<IContainerProvider, object> factoryMethod)
        {
            var dryIoc = ((IContainerProvider)containerRegistry).Resolve<IContainer>();
            dryIoc.RegisterDelegate(typeof(T), factoryMethod, Reuse.Transient);
            return containerRegistry;
        }
    }
```

**Comment by dansiegel** [comment]
Thanks for the bug report @azabluda this will be fixed in Prism 9
