### ISSUE TITLE
DryIoc.Rules DryIoc.Rules.WithoutFastExpressionCompiler()

### ISSUE THREAD

**Issue by gsgoodluck** [PrismLibrary/Prism#2806]
Prism.Unity Change Prism.DryIoc 

  Error: 引发的异常:“System.MissingMethodException”(位于 mscorlib.dll 中)
找不到方法:“DryIoc.Rules DryIoc.Rules.WithoutFastExpressionCompiler()”。

**Comment by brianlagunas** [comment]
This issue is not clear
