### ISSUE TITLE
[BUG] NavigateAsync("../../../ViewE") not working

### ISSUE THREAD

**Issue by hugotruffe79** [PrismLibrary/Prism#2807]
### Description

I have => "NavigationPage/ViewA/ViewB/ViewC/ViewD"

I want to delete ViewB, ViewC and ViewD. 

So 

._navigationService.NavigateAsync("../ViewE"); 

but is not delete the vies b, c and d

### Steps to Reproduce

I have => "NavigationPage/ViewA/ViewB/ViewC/ViewD"

### Platform with bug

Xamarin.Forms

### Affected platforms

iOS

**Comment by brianlagunas** [comment]
Require reproduction app not provided
