### ISSUE TITLE
Prism.Windows should provide a hook for the application to prevent restoring app state

### ISSUE THREAD

**Issue by ali-hk** [PrismLibrary/Prism#281]
Prism.Windows should provide some means for the application developer to determine whether or not they actually want to restore application state.
An example of when this is necessary is when the app has been updated and one of the pages has been removed or renamed. In this scenario, if the user was on that page or had that page in their navigation history when the app was suspended, then the app was updated, it would attempt to resume to that page and crash.
Another example is if the user state of the application has changed since the app was last launched (ex. if the app uses Facebook login and the logged in Facebook user has changed or the account has been deleted, etc.).
My suggestion is to provide an override in PrismApplication that determines whether or not the RestoreSessionStateAsync, RestoreFrameState and RestoreSavedNavigation occur.

**Comment by briannoyes** [comment]
Good idea. With Windows 8 Store Apps there was rigid guidance that you were always supposed to restore state when launching from termination, but I checked with the platform team a while back and they said for Windows 10 that guidance has been relaxed and it is up to the app (developer/requirements) to decide whether the state should be restored or not. 

Will look into this when I have time, or if you want to submit a PR with the way you think it should look that might let us get that support in there quicker.

**Comment by ali-hk** [comment]
Submitted a PR (#539) that addresses this issue.
