### ISSUE TITLE
Android back button override closes app

### ISSUE THREAD

**Issue by neilt6** [PrismLibrary/Prism#2815]
The Android back button override from PrismLibrary/Prism.Maui#88 isn't working properly on my end.

### Steps to Reproduce

1. Build and launch _PrismMauiDemo_ on an Android 10.0 emulator.
2. Click _Flyout Page_.
3. Click the _Back_ button on the emulator.

### Expected Behavior

- Navigation from _ViewD_ to _ViewC_:

```
[DOTNET] ViewD - View Disappearing
[DOTNET] ViewC - View Appearing
[DOTNET] ViewD - ViewModel NavigatedFrom
[DOTNET] ViewC - ViewModel NavigatedTo
[DOTNET] Navigation: GoBack
[DOTNET] Result: Success
```

### Observed Behavior

- The app closes, and all manner of badness ensues:

```
[DOTNET] ViewD - View Disappearing
[DOTNET] ViewC - View Appearing
[DOTNET] ViewC - View Disappearing
[DOTNET] ViewD - ViewModel NavigatedFrom
[DOTNET] ViewC - ViewModel NavigatedTo
[DOTNET] Navigation: GoBack
[DOTNET] Result: Success
[DOTNET] ViewC - ViewModel NavigatedFrom
[DOTNET] ViewB - ViewModel NavigatedTo
[DOTNET] Navigation: GoBack
[DOTNET] Result: Success
```

- Reopening the app from recent apps reveals _ViewB_ with no navigation bar:

`[DOTNET] ViewB - View Appearing`

- Reopening the app from the launcher throws an exception and crashes:

```
[mono-rt] [ERROR] FATAL UNHANDLED EXCEPTION: System.NotImplementedException: Either set MainPage or override CreateWindow.
[mono-rt]    at Microsoft.Maui.Controls.Application.CreateWindow(IActivationState activationState) in D:\a\_work\1\s\src\Controls\src\Core\HandlerImpl\Application\Application.Impl.cs:line 126
[mono-rt]    at Microsoft.Maui.Controls.Application.Microsoft.Maui.IApplication.CreateWindow(IActivationState activationState) in D:\a\_work\1\s\src\Controls\src\Core\HandlerImpl\Application\Application.Impl.cs:line 40
[mono-rt]    at Microsoft.Maui.Platform.ApplicationExtensions.CreatePlatformWindow(Activity activity, IApplication application, Bundle savedInstanceState) in D:\a\_work\1\s\src\Core\src\Platform\Android\ApplicationExtensions.cs:line 44
[mono-rt]    at Microsoft.Maui.MauiAppCompatActivity.OnCreate(Bundle savedInstanceState) in D:\a\_work\1\s\src\Core\src\Platform\Android\MauiAppCompatActivity.cs:line 32
[mono-rt]    at PrismMauiDemo.MainActivity.OnCreate(Bundle savedInstanceState) in C:\Users\NeilThiessen\Downloads\Prism.Maui-master\sample\PrismMauiDemo\Platforms\Android\MainActivity.cs:line 12
[mono-rt]    at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_(IntPtr jnienv, IntPtr native__this, IntPtr native_savedInstanceState) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net6.0/android-31/mcw/Android.App.Activity.cs:line 2781
[mono-rt]    at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPL_V(_JniMarshal_PPL_V callback, IntPtr jnienv, IntPtr klazz, IntPtr p0) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:line 121
```

**Comment by MardorZ** [comment]
Is there a workaround? For now i cannot use prism because of this bug. :(

**Comment by mtopolewski** [comment]
Thanks @maxchu92 for sharing your workaround but it doesn't work for me for some reason. But I found better one. In Prism repo go to PrismNavigationPage.cs file (https://github.com/PrismLibrary/Prism/blob/master/src/Maui/Prism.Maui/Controls/PrismNavigationPage.cs) and change boolean value returned by OnBackButtonPressed from false to true. Works like a charm for me:
```
protected override bool OnBackButtonPressed()
{
    BackButtonPressed.Invoke(this, EventArgs.Empty);
    return true;
}
```
The only downside of this workaround is that you need to compile Prism by yourself :)

**Comment by shahbaaz90** [comment]
@dansiegel i have tried the workaround mentioned by @maxchu92 above, but it's pretty hacky. This issue seems to point that the NavigatonService is broken for android. would love a patch for this, as Android app is unusable with this.

happens with even the sample e2e app when used with the 8.1.273-pre nuget (instead of the embedded prism Project).

**Comment by soroshsabz** [comment]
Any update?

**Comment by dansiegel** [comment]
It's being looked at... and while this exact problem I could fix right now there is another another issue with the back button which isn't so easy to address. It will be fixed when it is fixed. If someone from the community wants to spend the time getting things to work for this we do take PRs, otherwise you will need to wait until I have the time to come up with a fix.

**Comment by rthanga1** [comment]
@maxchu92 I tried your workaround. Now, the hardware back button is working as expected. But if I press the back button in my navigation bar, it is not working
