### ISSUE TITLE
KnownNavigationParameters.UseModalNavigation only works when used as PageParameter

### ISSUE THREAD

**Issue by BerndStoltefuss** [PrismLibrary/Prism#2819]
Judging from the name of the parameter i would have guessed that it can be added to the navigationParameters of a NavigateAsync call. But due to this code in PageNavigationService:341 it seems only to be parsed from url/segment parameters:
```
     var pageParameters = UriParsingHelper.GetSegmentParameters(nextSegment);

        useModalNavigation = pageParameters.ContainsKey(KnownNavigationParameters.UseModalNavigation) ? pageParameters.GetValue<bool>(KnownNavigationParameters.UseModalNavigation) : false;
       
```
Not sure if this is intended, as for the the KnownNavigationParameters.Animated it is implemented differently (checks both, pageParams and navigationParams)

The good thing is: when used correctly modal pages work fine including background transparency :-)

**Comment by mnxamdev** [comment]
Not sure if this is relevant but I found this issue as well when trying to find a work around for my issue.

https://github.com/PrismLibrary/Prism.Maui/issues/106

What is the proper code work around for getting a view to show as a modal and also closing that modal? I've tried passing in page parameters but the view still shows in my flyout detail page and not as a modal.

**Comment by dansiegel** [comment]
I am going to be closing this as no reproduction app was ever provided. To answer the general question yes it should be a view specific parameter. If this has a bug when using the NavigationBuilder let me know and be sure to include a reproduction of the issue.

**Comment by mnxamdev** [comment]
Hi @dansiegel, I'm using the NavigationBuilder and I'll try to provide a sample app soon. I'm using a flyoutpage and the modal always ends up in the flyoutpage detail. Can you confirm the code below as correct usage please? Thanks.

```
//Registration
containerRegistry.RegisterForNavigation<SignInPage, SignInPageViewModel>();

//Modal navigation
await _navigationService
	  .CreateBuilder()
          .AddSegment<SignInPage>()
          .AddParameter(KnownNavigationParameters.UseModalNavigation, true)
          .NavigateAsync();

//Also tried
_navigationService
	  .CreateBuilder()
          .AddSegment("SignInPage")
          .AddParameter(KnownNavigationParameters.UseModalNavigation, true)
          .NavigateAsync();

//Also tried
await _navigationService
	   .CreateBuilder()
           .AddNavigationPage()
          .AddSegment<SignInPage>()
          .AddParameter(KnownNavigationParameters.UseModalNavigation, true)
          .NavigateAsync();
```

**Comment by giuseppenovielli** [comment]
@dansiegel check this discussion -> https://github.com/PrismLibrary/Prism/discussions/2828
I have developed a repository with Prism's example.

Thanks!
