### ISSUE TITLE
Flyout navigation not working properly[MAUI.Prism] Android

### ISSUE THREAD

**Issue by SarthakB26** [PrismLibrary/Prism#2820]
Doing  _navigationService.NavigateAsync("NavigationPage/ViewB") From Flyout Page will result in opening ViewB as a push modal  also no hamburger icon will be visible on ViewB page.

Steps To Reproduce

1. Open Prism.Maui app
2. Go to flyout page
3. Click on hambergur icon and select ViewB Button from Flyout
4. You will see instead of setting ViewB as detail page of Flyout page, ViewB will open as a PushModal page and no back or hamburger button will be visible on ViewB page

Testing on Latest Maui and Prism version
Maui Flyout works fine

Video attached of Sample Prism app

https://user-images.githubusercontent.com/125443207/219013945-d98b2d5a-a330-45b1-aa59-bda86e19b5ff.mp4

Please let me know if there is any workaround to fix this. Really important for migration

**Comment by berhir** [comment]
hi @SarthakB26, did you find a workaround for this issue?

**Comment by SarthakB26** [comment]
For now you can get FlyoutPage from Application.MainPage as FlyoutPage and then sets its detail page by yourself rather then through prism navigation service.
It's dirty I know but works for me

**Comment by berhir** [comment]
The solution was even simpler. I created a PR with the fix. And I added a new test that fails without my changes and succeeds with my changes.
