### ISSUE TITLE
Prism.WFP/Services/Dialogs/DialogService.cs -- ConfigureDialogWindowEvents() fails to return correct dialog result

### ISSUE THREAD

**Issue by McSaverInvestments** [PrismLibrary/Prism#2827]
### Description

This line is missed placed:   dialogWindow.GetDialogViewModel().RequestClose -= requestCloseHandler;   

It is called before dialogWindow.GetDialogViewModel().OnDialogClosed(); with results in the dialog results being null.

Then incorrectly an empty dialog result is returned to the callback.

Move the missed placed line down below the dialogWindow.GetDialogViewModel().OnDialogClosed();

### Steps to Reproduce

1.   Use the example from your PluralSight training course.
2.  Try returning a dialog result of OK, with or without a parameter.
3.  CallBack will have a dialog result of None and a null value for the parameter

### Platform with bug

WPF

### Affected platforms

I was *not* able test on other platforms

### Did you find any workaround?

            EventHandler closedHandler = null;
            closedHandler = (o, e) =>
                {
                    dialogWindow.Closed -= closedHandler;
                    dialogWindow.Closing -= closingHandler;
                    // ****  Old location of the missed placed line.     *******

                    dialogWindow.GetDialogViewModel().OnDialogClosed();

                    if (dialogWindow.Result == null)
                        dialogWindow.Result = new DialogResult();

                    callback?.Invoke(dialogWindow.Result);

                    // ****  New location of the missed placed line.     This fixes the bug!   *******
                    dialogWindow.GetDialogViewModel().RequestClose -= requestCloseHandler;

                    dialogWindow.DataContext = null;
                    dialogWindow.Content = null;
                };
            dialogWindow.Closed += closedHandler;

**Comment by brianlagunas** [comment]
Please provide a simple app that can reproduce the issue or this will be closed. Thanks.

**Comment by McSaverInvestments** [comment]
[PrismBug.zip](https://github.com/PrismLibrary/Prism/files/10834850/PrismBug.zip)

Here is a simple sample app

**Comment by brianlagunas** [comment]
This sample demonstrates using the `IDialogAware` in a way in which it was not designed. `OnDialogClosed()` is called after the dialog has been closed. You should not be calling `RequestClose` in `OnDialogClosed()` as the dialog has already been closed. `RequestClose` is called to close the dialog.

What exactly are you trying to do in which you need to try to call `RequestClose` in a dialog that is already closed?

**Comment by McSaverInvestments** [comment]
I'm bad.    I see what you're saying.

I trying to find a way for my ViewModel to return my DialogResult with Params when the user clicks the close box in the dialog window.   

CanCloseDialog() is also too late to call RequestClose.

It would be nice if IDialogAware has some additional interface to support this.

Any ideas would be greatly appreciated.
