### ISSUE TITLE
[BUG] DryIoc dependency

### ISSUE THREAD

**Issue by lkroliko** [PrismLibrary/Prism#2829]
### Description

Hello

Nuget package Prism.DryIoc have dependency to DryIoc.dll (>= 4.7.7) but it shoud be 4.7.7 <= x < 5.0.0.

When I try use 5.x.x version of DryIoc I get System.MissingMethodException: 'Method not found: 'DryIoc.Rules DryIoc.Rules.WithoutFastExpressionCompiler()'.'

Maybe is it possible to move this dependency to version 5? 

Thanks in advance.

### Steps to Reproduce

1. Use project with Prism.DryIoc 
2. Update DryIoc to version 5.0.0

in
```
public partial class App : PrismApplication
{
    protected override void OnStartup(StartupEventArgs e)
    {
        base.OnStartup(e); //<- Exception will be throwned
    }
```

### Platform with bug

WPF

### Affected platforms

Windows, I was *not* able test on other platforms

**Comment by brianlagunas** [comment]
Please be sure to check for duplicate issues before opening this. This is not a bug.
see: https://github.com/PrismLibrary/Prism/issues/2789 https://github.com/PrismLibrary/Prism/discussions/2667 https://github.com/PrismLibrary/Prism/issues/2679 https://github.com/PrismLibrary/Prism/issues/2705 and https://github.com/PrismLibrary/Prism/issues/2770

Prism 9 will have the updated dependencies.
