### ISSUE TITLE
Improve discoverability of the core packages

### ISSUE THREAD

**Issue by bartlannoeye** [PrismLibrary/Prism#283]
As the amount of packages go up (with supporting multiple IoC containers), I was wondering if we should highlight which package is the core package per platform. Or do we go with the assumption that people will (nearly) always use one of the IoC containers anyway?

I had a go at it with placing the core package in bold on my [Documentation branch](https://github.com/bartlannoeye/Prism/blob/Documentation/README.md).

Another option could be to add a description column. But then I would only add a description for the core package, otherwise it will go up in the clutter.

![image](https://cloud.githubusercontent.com/assets/5115577/10857451/79905884-7f4e-11e5-9de3-024c4eb02a80.png)

What's your opinion? Is this an improvement or can we do without?

**Comment by brianlagunas** [comment]
I think that we could improve the NuGet package layout/descriptions.  Maybe separating out the containers form the library would be a good start.

**Comment by bartlannoeye** [comment]
Do we really need (want) to show the assembly names? If we separate the IoC packages, we could do something like this:

| Package | WPF | Win10 UWP | Xamarin.Forms |
|--------------|:--------:|:-----------------:|:---------------------:|
| [Prism.Unity](link) | X | X | X |
| [Prism.Autofac](link) | X | | |

**Comment by brianlagunas** [comment]
I think it may be useful to document which assemblies are in the various packages.  Maybe we don't have to use the same tables for this, but I think full disclosure is good regarding what will actually be added to the customers projects when a package is added.  Think about how we cam restructure this.

**Comment by brianlagunas** [comment]
By the way, I do like the new format of the container support matrix

**Comment by bartlannoeye** [comment]
Too bad GitHub doesn't support including sections of markdown into another file (like pandoc does), so we got some duplicate documentation. But I'm quite pleased with what I got now. I kept the detailed assembly matrix on the installing page.
