### ISSUE TITLE
[BUG] NavigationPage Navigation Is Not Animated on iOS [Prism.Maui]

### ISSUE THREAD

**Issue by Axemasta** [PrismLibrary/Prism#2842]
### Description

I have noticed when using navigation within a `NavigationPage` on iOS that forwards navigation is not animated and the page will pop onto the navigation stack without an animation. Here is a gif demonstrating the issue, you first see an app navigating using Shell (the purple tab bar) and the second app with the list of esports teams which is using prism navigation:

<img src="https://user-images.githubusercontent.com/33064621/225603042-b1d991e4-ca7e-48a7-9b75-2f6952434175.gif" height="500" />

I noticed this after porting a sample app over from XF to Maui & reproduced it in the esports sample app which is shown in the above gif.

This behaviour is the same when using the navigation builder or the uri based approach:
```csharp
var result = await navigationService.CreateBuilder()
    .AddSegment<TeamViewModel>()
    .AddParameter("SelectedTeam", lecTeam)
    .NavigateAsync();

// OR

var result = await navigationService.NavigateAsync("TeamPage", navParams);
```

I have tried adding the `KnownNavigationParameters.Animated` into the nav params with the value `true` and this does not appear to affect the behaviour.

### Steps to Reproduce

- Create a prism app & set the main page to be wrapped in a navigation page
- Navigate to a new page
- Run on iOS

Expected:
Page is pushed onto nav stack from right to left

Actual:
Page appears on nav stack, going back does animate

### Platform with bug

.NET MAUI

### Affected platforms

iOS

Prism version:
Prism.DryIoc.Maui 8.1.285-pre

### Did you find any workaround?

Not yet

### Relevant log output

The only logs in my console are:
```shell
Microsoft.Maui.Controls.BindableObject: Warning: Cannot convert True to type 'Prism.Mvvm.ViewModelLocatorBehavior'
```

**Comment by brianlagunas** [comment]
Please provide the required reproduction app or this issue will be closed.

**Comment by Axemasta** [comment]
Hi Brian, the reproduction of this issue is [here](https://github.com/Axemasta/PrismMauiTesting)
