### ISSUE TITLE
[BUG] Can't update DryIoc

### ISSUE THREAD

**Issue by bdovaz** [PrismLibrary/Prism#2845]
### Description

Related: https://github.com/PrismLibrary/Prism/issues/2770 https://github.com/PrismLibrary/Prism/discussions/2715

I see that in this commit (https://github.com/PrismLibrary/Prism/commit/4a021d8a309c4563844a7c8764171c0e87c4eff1) you have updated DryIoc but I see that you haven't released a new version of the NuGet packages yet.

Do you know when you are going to do it @dansiegel @brianlagunas? Thanks.

### Steps to Reproduce

Update DryIoc to 5.x

### Platform with bug

WPF

### Affected platforms

Windows

### Did you find any workaround?

https://github.com/PrismLibrary/Prism/issues/2770

**Comment by bdovaz** [comment]
@brianlagunas can you give an explanation why you closed it as not planned? If the commit is already merged. What's the problem? Thanks.

**Comment by brianlagunas** [comment]
You submitted a bug knowing it was a duplicate and even linked to the commit in which its fixed. Please do not open bugs to ask questions of existing issues.

**Comment by bdovaz** [comment]
@brianlagunas I have opened it anyway because the other 2 are old and have been closed for a long time. There was no active issue at the time I opened this issue that was related.

@dansiegel and what are the "appropriate channels"?

I have the feeling that you are being a bit rude, I think I have been polite in my messages and have not demanded anything, they are simply questions. If you look at my profile you will see that I am an active contributor in other projects so I am also on that side.

**Comment by dansiegel** [comment]
@bdovaz you've started this by ignoring the options you have when creating an issue which includes the option for asking a question. We are quite clear we do not appreciate people asking questions with Bug Reports. If you look at the other issues you would get the same information you are going to get here. If you require an updated build more quickly you can always become a sponsor to access the Sponsor Connect CI feed or become an Enterprise Support Client. 

The issue has already been fixed and will be available in the next release whenever that happens to be.
