### ISSUE TITLE
How to Pass Parameters to an Custom interaction Request

### ISSUE THREAD

**Issue by noufionline** [PrismLibrary/Prism#285]
Hi Brians,

I would like to pass a parameter while calling Raise method of Interaction Request which could be data bound to the view in the interaction request.

How to achieve this behavior?

Thanks in advance.

Noufal

**Comment by bartlannoeye** [comment]
Hey @noufionline, could you please post this question on [StackOverflow under the Prism tag](http://stackoverflow.com/questions/tagged/prism?sort=newest&pageSize=50)? We're using SO for questions and try to keep GitHub issues for issues and features requests only.

**Comment by noufionline** [comment]
OK . Sorry :)
