### ISSUE TITLE
[BUG] Getting "Warning: Cannot convert True to type 'Prism.Mvvm.ViewModelLocatorBehavior'" on MAUI

### ISSUE THREAD

**Issue by shahbaaz90** [PrismLibrary/Prism#2855]
### Description

i keep getting these logs in the application output window.

`Microsoft.Maui.Controls.BindableObject: Warning: Cannot convert True to type 'Prism.Mvvm.ViewModelLocatorBehavior'`
As per my understanding, in Prism MAUI the AutowireToViewModel property got changed from boolean to the enum ViewModelLocatorBehavior. But i am not setting either the bool nor the enum anywhere in my project, as i assumed this is now handled automatically. 

### Steps to Reproduce

I have registered all my views for navigation in my IContainerRegistry.
is there a way to fix this?
![Screenshot 2023-03-30 at 23 45 00](https://user-images.githubusercontent.com/9108018/228934960-ebc35038-4657-4d8e-afb0-39876dfed93c.png)

### Platform with bug

.NET MAUI

### Affected platforms

iOS, Android

**Comment by brianlagunas** [comment]
Did not follow bug template instructions.

**Comment by dansiegel** [comment]
This is not a bug btw. You need to read the [migration docs for Maui](https://prismlibrary.com/docs/maui/migrating.html#viewmodellocator-autowire-property). This was a breaking change in Prism.Maui when migrating from Xamarin.Forms as we have changed this from a bool to an Enum. If you had `ViewModelLocator.Autowire="True"` you can just remove it as we do it automatically for you and it has a new behavior that delays the autowire. You only need to specify the property when you are explicitly disabling the Autowire for some reason.

**Comment by shahbaaz90** [comment]
@dansiegel thanks for the response. I don't believe im setting that property in my app anymore, but it still shows. Another thing that i have come across is that i am unable to inherit from the PrismApplication class (for the App.xaml/cs class). Could this be one of the reasons? the app does run with the stock MAUI Application class too, so i'm not sure how important this class is. I

I am however, facing issues with navigation (animated, modal navigation not working). not sure if its related.

I am using the latest pre nuget of Prism.Maui (8.1.273-pre)

![Screenshot 2023-03-31 at 17 16 02](https://user-images.githubusercontent.com/9108018/229117646-b96f91d2-bcd3-4fae-9e8d-f9b315338187.png)

**Comment by Pantheas** [comment]
@DamianSuess did you find a solution for your issue?
