### ISSUE TITLE
[BUG] System.MissingMethodException: 'Method not found'

### ISSUE THREAD

**Issue by souravanand001** [PrismLibrary/Prism#2858]
### Description

After following example in Prism MAUI template i came to this exception on MAUIProgram.cs

System.MissingMethodException: 'Method not found: Microsoft.Maui.Hosting.MauiAppBuilder Prism.PrismAppBuilderExtensions.UsePrismApp<!0>(Microsoft.Maui.Hosting.MauiAppBuilder,Prism.Ioc.IContainerExtension,System.Action`1<Prism.PrismAppBuilder>)'

### Steps to Reproduce

Create new MAUI application.
Add Prism.DryIoc.MAUI
Register dependencies in MAUIProgram.cs with UsePrismApp<App>
During launch application gets crash with this exception.

### Platform with bug

.NET MAUI

### Affected platforms

iOS, Android, I was *not* able test on other platforms

### Did you find any workaround?

No

### Relevant log output

```shell
System.MissingMethodException: 'Method not found: Microsoft.Maui.Hosting.MauiAppBuilder Prism.PrismAppBuilderExtensions.UsePrismApp<!0>(Microsoft.Maui.Hosting.MauiAppBuilder,Prism.Ioc.IContainerExtension,System.Action`1<Prism.PrismAppBuilder>)'
```

**Comment by SarthakB26** [comment]
Please share sample for replication. I am Playing with Prism.MAUI from a while, haven't got exception on the startup atleast yet.

**Comment by dansiegel** [comment]
This is not a bug. The Prism API has been in flux for .NET MAUI.

**Comment by maxxentropy** [comment]
Hey Dan, Why is this not a bug? I get this error too, although it did not happen when I first started with the Maui project template.

**Comment by Pantheas** [comment]
@souravanand001 did you find a way to fix this?
I'm facing the same issue.
I am completely new to Prism and used the VS Template to create a project.
