### ISSUE TITLE
NotificationRequest focus on OK Button

### ISSUE THREAD

**Issue by CarlosAdrianM** [PrismLibrary/Prism#286]
The default notification request window should have the focus on the OK Button, so the user can skip the notification pressing enter key.
http://stackoverflow.com/questions/33483533/prism-notificationrequest-focus-on-ok-button

**Comment by brianlagunas** [comment]
Thanks for reporting this.  We will simply set the Button.IsDefault property to true to fix this.

**Comment by brianlagunas** [comment]
fixed
