### ISSUE TITLE
[BUG] InvalidCastException when resolving an IEnumerable-implementing generic interface through UnityContainerExtension

### ISSUE THREAD

**Issue by workingparrot** [PrismLibrary/Prism#2871]
### Description

When a generic interface is derived from IEnumerable<T> and regsitered with the container, attempting to resolve an instance through that interface results in an InvalidCastException, and the type is not resolved. See reproduction for details.

This does not appear to be an issue with the UnityContainer. Prism's UnityContainerExtension.Resolve(Type type, params (Type Type, object Instance)[] parameters) does some special handling if the requested type is an enumerable and has a generic parameter.

```
public object Resolve(Type type, params (Type Type, object Instance)[] parameters)
{
    try
    {
        var c = _currentScope?.Container ?? Instance;
        var overrides = parameters.Select(p => new DependencyOverride(p.Type, p.Instance)).ToArray();

        if (typeof(IEnumerable).IsAssignableFrom(type) && type.GetGenericArguments().Length > 0)
        {
            type = type.GetGenericArguments()[0];
            return c.ResolveAll(type, overrides);
        }

        return c.Resolve(type, overrides);
    }
    catch (Exception ex)
    {
        throw new ContainerResolutionException(type, ex);
    }
}
```

 

Unless the requested type is only an IEnumerable, this call will never return the expected type, causing casting issues either for the caller, or by IContainerProviderExtensions.Resolve().

 

There may be no need for this conditional to intercept whether the type is an enumerable - UnityContainer has built-in support for using Enumerables to resolve all instances of T in the container (see http://unitycontainer.org/tutorials/resolution/collections.html).

### Steps to Reproduce

1. Build and run the project at https://github.com/workingparrot/fictional-octo-doodle

### Expected Behaviour
The program should run to completion, with the correct type being resolved in the main method.

### Actual Behaviour
The following exception is thrown:
System.InvalidCastException
  HResult=0x80004002
  Message=Unable to cast object of type '<CastIterator>d__97`1[System.Object]' to type 'ConsoleApp1.IExtendedEnumerable`1[System.Int32]'.
  Source=Prism
  StackTrace:
   at Prism.Ioc.IContainerProviderExtensions.Resolve[T](IContainerProvider provider)
   at ConsoleApp1.Program.Main(String[] args) in E:\Dev\fictional-octo-doodle\Program.cs:line 38

### Platform with bug

Prism Core

### Affected platforms

I was *not* able test on other platforms

### Did you find any workaround?

Bypass IContainerProvider using GetContainer() and use the IUnityContainer directly.

**Comment by dansiegel** [comment]
Closing this issue as resolved. @workingparrot please let me know if the following test does not match your issue. You should be able to validate this with the [Prism.Container.Unity](https://www.nuget.org/packages/Prism.Container.Unity/9.0.61-pre) package.

![image](https://github.com/PrismLibrary/Prism/assets/3860573/ef09043a-e0c8-4cb1-ac3e-55320c9ae53c)

![image](https://github.com/PrismLibrary/Prism/assets/3860573/46f72c5c-1568-4cc9-9c78-29ad67d993ef)
