### ISSUE TITLE
[BUG] OnNavigatedTo is not called when using region navigation

### ISSUE THREAD

**Issue by Nobody84** [PrismLibrary/Prism#2878]
### Description

Hello,

I created a **Prism Maui App** using the **Prism.Templates 8.1.97** and updated the Frameworks to net7.0. The Prism Package used is **Prism.Dryloc.Maui 8.1.191-beta**.

I'm using the **RegionManager** to navigate a view (**ViewA**) into a region named **ContentRegion**. ViewA has view model named **ViewAViewModel** that implements the **INavigatedAware** interface.  The navigation itself works fine and the View is displayed, but the **OnNavigatedTo/From** methods are not called.

Am I doing something wrong?

### Steps to Reproduce

I created a minimal code sample to reproduce the Issue.
[https://github.com/Nobody84/Issues_PrismMaui_RegionNavigation](https://github.com/Nobody84/Issues_PrismMaui_RegionNavigation)

### Platform with bug

.NET MAUI

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Did you find any workaround?

No

**Comment by dansiegel** [comment]
This is by design. https://github.com/PrismLibrary/Prism/blob/ed889223da8fa83a1215205ef605745a39942c85/e2e/Maui/MauiRegionsModule/ViewModels/RegionViewModelBase.cs

**Comment by Nobody84** [comment]
I'm afraid I didn't stumble over the IRegionAware interface yet.
Thank your for the hint. Works as intended.

**Comment by dansiegel** [comment]
Do keep in mind we are looking at a breaking change that will consolidate the Region Abstractions in Prism.Core this means names of interfaces for Maui will be changing.
