### ISSUE TITLE
[BUG] Navigating between two view models with the same page type does not work

### ISSUE THREAD

**Issue by berhir** [PrismLibrary/Prism#2880]
### Description

We have two view models registered using the same page. When we navigate from one view model to the other, the page gets not updated correctly.

I created a failing test in [this branch](https://github.com/berhir/Prism/tree/FlyoutRelativeNavigationWithSharedPage_RemovesPage_AndNavigates) to show the problem.

I guess the problem is in `NavigationService.cs` in the block starting in line 624:
```cs
//if we weren't forced to reuse the NavPage, then let's check the NavPage.CurrentPage against the next segment type as we don't want to recreate the entire nav stack
//just in case the user is trying to navigate to the same page which may be nested in a NavPage
var nextPageType = Registry.GetViewType(UriParsingHelper.GetSegmentName(segments.Peek()));
var currentPageType = navPage.CurrentPage.GetType();
if (nextPageType == currentPageType)
{
    reuseNavPage = true;
}
```
The `nextPageType` is the same as the `currentPageType` because both view models are using the same page type. But I am not sure if the page should be reused in this case, because the `BindingContext` (view model) should be different.

This additional check solves the issue:
```cs
//if we weren't forced to reuse the NavPage, then let's check the NavPage.CurrentPage against the next segment type as we don't want to recreate the entire nav stack
//just in case the user is trying to navigate to the same page which may be nested in a NavPage
var nextPageRegistration = Registry.Registrations.LastOrDefault(x => x.Name == UriParsingHelper.GetSegmentName(segments.Peek()));
var currentPageType = navPage.CurrentPage.GetType();
var currentPageViewModelType = navPage.CurrentPage.BindingContext.GetType();
if (nextPageRegistration != null && nextPageRegistration.View == currentPageType && nextPageRegistration.ViewModel == currentPageViewModelType)
{
    reuseNavPage = true;
}
```

If you agree, I will create a PR. If you want to solve it in a different way let me know and I will try to implement it.

### Steps to Reproduce

Register two view models using the same page type:
```cs
container.RegisterForNavigation<MockHome, MockHomeViewModel>()
    .RegisterForNavigation<MockViewShared, MockViewShared1ViewModel>("Shared1")
    .RegisterForNavigation<MockViewShared, MockViewShared2ViewModel>("Shared2");
```

```cs
[Fact]
public async Task FlyoutRelativeNavigationWithSharedPage_RemovesPage_AndNavigates()
{
    var mauiApp = CreateBuilder(prism => prism.OnAppStart("MockHome/NavigationPage/Shared1"))
        .Build();
    var window = GetWindow(mauiApp);

    var rootPage = window.Page as MockHome;
    Assert.NotNull(rootPage);
    TestPage(rootPage);
    Assert.NotNull(rootPage.Detail);
    var detailPage = rootPage.Detail as NavigationPage;
    Assert.NotNull(detailPage);
    TestPage(detailPage);
    var firstPage = detailPage.CurrentPage;
    Assert.IsType<MockViewShared>(firstPage);
    TestPage(firstPage);
    Assert.IsType<MockViewShared1ViewModel>(firstPage.BindingContext);
    var navService = Prism.Navigation.Xaml.Navigation.GetNavigationService(rootPage);
    var result = await navService.NavigateAsync("./NavigationPage/Shared2");
    Assert.True(result.Success);
    Assert.NotNull(rootPage.Detail);
    detailPage = rootPage.Detail as NavigationPage;
    Assert.NotNull(detailPage);
    TestPage(detailPage);
    var secondPage = detailPage.CurrentPage;
    Assert.IsType<MockViewShared>(secondPage);
    TestPage(secondPage);

    // this fails: expected type is MockViewShared2ViewModel, but actual type is MockViewShared1ViewModel
    Assert.IsType<MockViewShared2ViewModel>(secondPage.BindingContext);

    // this fails too. not sure if the page should be reused in this case. at least the BindingContext must be updated.
    Assert.NotSame(secondPage, firstPage);
}
```

We are having this issue using a flyout page, but I guess it happens also in other cases.

### Platform with bug

.NET MAUI

### Affected platforms

iOS, Android, Windows, macOS, I was *not* able test on other platforms

**Comment by brianlagunas** [comment]
Registering the same view with different view models is not support and I would argue points to a code smell in your app architecture.

**Comment by berhir** [comment]
Thanks for the reply. Interesting, I was sure I read somewhere that this is supported. But I can't find it anymore.
Anyway, I found many other requests for this feature.
Is there a reason why it's not supported?

Probably it's an edge case, but we are having a base view model for one use case with two different implementations, but the view is exactly the same.
Our workaround is to have also a base view and two derived views without any changes. This way we can register both and share the view.
It would be nice to register them as described above. And it works also in some cases, but not in all.

**Comment by berhir** [comment]
> The VML only allows registering a VM with a specific view Type. If you register the same view again but using a different VM, then the VML will use the new VM you provided overwriting the previous.

I thought that's the reason why the overload with the parameter for a custom name exists. What is the use case for this if it's not to register the same thing with different names?

> I would argue your current approach needs to be reconsidered for a more favorable approach.

As always, there are different ways to achieve the same thing. Using inheritance was just the first thing that came into my mind. Our use case is to load some data from different locations. Once from a local DB and, if the data was archived, from a remote API. Except of the title, the view is exactly the same in both cases. So only the methods to load the data have different implementations in the derived view models. I prefer this over a parameter and a lot of if-else statements.

> This is not something that we will be adding to Prism.

Actually, you already added 99% of the feature 😉 It's just the one check I mentioned above that's missing.
But I understand if you don't want to officially support this, even if it would not be much effort to implement it.

**Comment by brianlagunas** [comment]
> I thought that's the reason why the overload with the parameter for a custom name exists. What is the use case for this if it's not to register the same thing with different names?

The custom name exists for the container to resolve the objects (views) you are navigating to. The VML does not use this name in its functionality.

> As always, there are different ways to achieve the same thing. Using inheritance was just the first thing that came into my mind. Our use case is to load some data from different locations. Once from a local DB and, if the data was archived, from a remote API. Except of the title, the view is exactly the same in both cases. So only the methods to load the data have different implementations in the derived view models. I prefer this over a parameter and a lot of if-else statements.

This can be handled in a service.

> Actually, you already added 99% of the feature 😉 It's just the one check I mentioned above that's missing.
But I understand if you don't want to officially support this, even if it would not be much effort to implement it.

Actually its more than that. Regardless, this is not something Prism will be adding.

**Comment by berhir** [comment]
I had some time to take a closer look and now it's clear where the confusion comes from.

> The custom name exists for the container to resolve the objects (views) you are navigating to. The VML does not use this name in its functionality.

I was looking only at the _MAUI_ implementation, and it works differently from other implementations. In MAUI, the static registration is _NOT_ used. Instead, a `ViewRegistration` object gets registered. 

```cs
container.RegisterInstance(new ViewRegistration
            {
                Type = ViewType.Page,
                Name = name,
                View = view,
                ViewModel = viewModel
            })
            .Register(view);
```

This `ViewRegistration` is also used to resolve the view and the related view model by the name of the registration. That's why it's working in Prism MAUI to add multiple pages for the same view model.

There is only this small bug I mentioned above that happens in this specific case and stops the feature from working fully.

Can I add a small draft PR with a fix and a few tests to show that it's really just a very small change to make it work? You can still decline it if you don't like it.
