### ISSUE TITLE
[Enhancement] AsyncDelegateCommand

### ISSUE THREAD

**Issue by dansiegel** [PrismLibrary/Prism#2885]
## Summary

We previously removed the direct support for creating a DelegateCommand with a Task. In effect this directly executed with the use of `async void`. While you can still technically create a DelegateCommand in this fashion we need a better solution for the many times where you may need to execute some async code block. In particular this will be helpful for the addition of catching errors on the Execution of the delegate as we need to catch it within the async context.

## Proposal

```cs
public class AsyncDelegateCommand : DelegateCommandBase
{
    private readonly Func<Task> _delegate;
    private readonly Func<bool> _canExecute;
    private bool _multipleExecution;

    public AsyncDelegateCommand(Func<Task> func, Func<bool> canExecute)
    {
        _delegate = func;
        _canExecute = canExecute;
    }

    public bool IsExecuting { get; private set; }

    public bool CanExecute => (_multipleExecution || !IsExecuting) && _canExecute();

    public async Task Execute()
    {
        try
        {
            IsExecuting = true;
            RaiseCanExecuteChanged();
            await _delegate();
        }
        catch(Exception ex)
        {
           // Process or rethrow exception issue #2873
        }
        finally
        {
           IsExecuting = false;
           RaiseCanExecuteChanged();
        }
    }

    public AsyncDelegateCommand AllowMultipleExecute()
    {
        _multipleExecution = true;
        return this;
    }

    async void ICommand.Execute(object obj) => await Execute(); 
}
```

**Comment by thomasgalliker** [comment]
This would be a highly appreciated enhancement @dansiegel. Meanwhile we switched all Xamarin.Forms.Command instances with the [AsyncRelayCommand](https://github.com/CommunityToolkit/dotnet/blob/main/src/CommunityToolkit.Mvvm/Input/AsyncRelayCommand.cs) from CommunityToolkit.Mvvm. It is a good source of inspiration, if you ask me.
They have an `ExecuteAsync(object)` method which I can perfectly use in viewmodel unit tests to run async command handlers. Their `IsRunning` property can be used to bind to button.IsEnabled states or ActivityIndicators, if needed.
