### ISSUE TITLE
[BUG] Native Exception when using SecureStorage in OnAppStart

### ISSUE THREAD

**Issue by tibuprophen** [PrismLibrary/Prism#2901]
### Description

I get a Native Exception when I use the SecureStorage from the Maui Community Toolkit in the Prism OnAppStart function on Android. 
It works **fine on iOS** and **even on Android on a later state** (e.g. on page appearing).

```
System.NotImplementedException: Either set MainPage or override CreateWindow.
   at Microsoft.Maui.Controls.Application.CreateWindow(IActivationState activationState) in D:\a\_work\1\s\src\Controls\src\Core\HandlerImpl\Application\Application.Impl.cs:line 129
   at Microsoft.Maui.Controls.Application.Microsoft.Maui.IApplication.CreateWindow(IActivationState activationState) in D:\a\_work\1\s\src\Controls\src\Core\HandlerImpl\Application\Application.Impl.cs:line 47
   at Microsoft.Maui.Platform.ApplicationExtensions.CreatePlatformWindow(Activity activity, IApplication application, Bundle savedInstanceState) in D:\a\_work\1\s\src\Core\src\Platform\Android\ApplicationExtensions.cs:line 44
   at Microsoft.Maui.MauiAppCompatActivity.OnCreate(Bundle savedInstanceState) in D:\a\_work\1\s\src\Core\src\Platform\Android\MauiAppCompatActivity.cs:line 32
   at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_(IntPtr jnienv, IntPtr native__this, IntPtr native_savedInstanceState) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net7.0/android-33/mcw/Android.App.Activity.cs:line 2816
   at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPL_V(_JniMarshal_PPL_V callback, IntPtr jnienv, IntPtr klazz, IntPtr p0) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:line 121
```

### Steps to Reproduce

1. Create a new Maui App
2. Add Prism (nuget package and init. code)
3. Add Maui Community Toolkit (nuget package and init. code)
4. Try SecureStorage.GetAsync in OnAppStart function of prism

### Platform with bug

.NET MAUI

### Affected platforms

Android

### Did you find any workaround?

Create a pseudo first page (which may look like the splash screen), navigate to that and initialize the REAL first navigation there as you can access the SecureStorage then. 
This creates a performance and efficency issue. As this affects only Android, you may implement the workaround only for android with compiler conditions (`#if ANDROID`)

**Comment by SarthakB26** [comment]
Might be related to this
https://learn.microsoft.com/en-us/answers/questions/1001662/suddenly-getting-securestorage-issues-in-maui
In any case if prism is not able to set MaiPpage of App. The MAUI will throw System.NotImplementedException: Either set MainPage or override CreateWindow.
So it might nothing to with Prism your page is crashing

**Comment by dansiegel** [comment]
You have provided no reproduction app which is required for all bug reports. That said it seems like @SarthakB26 is probably pointing you in the right direction.

**Comment by tibuprophen** [comment]
Hello,
thank you for your help. Sadly, it does not work when setting `android:allowBackup="false"` as suggested in @SarthakB26 answer. 
I have attached a repro. Please take a look at PrismStartup.cs . 
[prism-maui.zip](https://github.com/PrismLibrary/Prism/files/11995247/prism-maui.zip)

**Comment by Sarthak261995** [comment]
@tibuprophen I checked your shared sample the issue is with the line
```var a = await SecureStorage.GetAsync("asd");```
So as soon any awaitable methods call before setting MainPage you will see Either set MainPage....... exception 

for a workaround you can use
```var a =  SecureStorage.GetAsync("asd").GetAwaiter().GetResult();```
instead, which will freeze UI and keep user at splash screen till this returns.

Or You can first navigate to your custom splash screen content page and there you can do all your awaitable operations and go forward accordingly. An example of this is already implemented on e2e prism maui sample you can refer that.

https://github.com/PrismLibrary/Prism/blob/master/e2e/Maui/PrismMauiDemo/MauiProgram.cs

https://github.com/PrismLibrary/Prism/blob/master/e2e/Maui/PrismMauiDemo/ViewModels/SplashPageViewModel.cs

**Comment by tibuprophen** [comment]
@Sarthak261995 thank you. Your first suggestion works and is much easier 👍🏻

**Comment by dansiegel** [comment]
@tibuprophen ultimately you're suffering from bad design.

```cs
private static async void OnAppStarted(IContainerProvider container, INavigationService navigation)
{
    // THIS WORKS ON IOS, BUT NOT ON ANDROID.
    // SecureStorage works in a later state in android
    var a = await SecureStorage.GetAsync("asd");
    var isLoggedIn = true;
    var targetUri = isLoggedIn
        ? $"/{nameof(MasterPage)}/{nameof(NavigationPage)}/{nameof(MainPage)}"
        : $"/{nameof(LoginPage)}";
    await navigation.NavigateAsync(targetUri);
}
```

A much better practice is to have a "SplashPage" or a "LoadingPage" that you can navigate to quickly. It's from here that you can do any sort of real async tasks that you need like evaluating the state of the user's authentication.

**Comment by tibuprophen** [comment]
@dansiegel I don't want to open a new discussion here, but why it is bad design by me to check e.g. credentials on the OnAppStart which handles to navigate to the first page (with async and di context) while a platform-specific splash screen is already available and shown to the user. 
Why is it much better practice to additonal add another loading screen beside the "original" splash screen. Can't find any ressource for that.
Thanks you very much for your advise!

**Comment by dansiegel** [comment]
In short your goal should be to get the app to load a Maui Page as quick as possible. 

Longer version: The native Splash Screen is really just a static image. By having something like a Loading Page you can now mimic this but add some text that changes as you do different tasks and/or add an activity indicator (or you can get as creative as you want). This approach helps to ensure that the user will see that the app is in fact responsive and loading. The alternative results in scenarios where the app may be unresponsive. Depending on what sort of async tasks you have (i.e. web requests with poor connections) you could inadvertently have your app killed by the OS.

**Comment by SarthakB26** [comment]
> @dansiegel I don't want to open a new discussion here, but why it is bad design by me to check e.g. credentials on the OnAppStart which handles to navigate to the first page (with async and di context) while a platform-specific splash screen is already available and shown to the user. Why is it much better practice to additonal add another loading screen beside the "original" splash screen. Can't find any ressource for that. Thanks you very much for your advise!

From MAUI team perspective it's all about being crossplatform so what you want might be achievable on android platform somehow on below android 13 platform(Above 13 there should be splash icon to be set which will be seen before any first activity to reach) using custom splash activity though on iOS MAUI default splashscreen uses LaunchScreenStoryBoard that iOS OS wants to return to any UIViewController in 7 seconds or low otherwise app will crash I am not sure how it works on Windows but that may be the reason behind exception after taking too much time to set MainPage I guess
