### ISSUE TITLE
[BUG] Prism.MAUI v9 AutoWire not working

### ISSUE THREAD

**Issue by albilaga** [PrismLibrary/Prism#2904]
### Description

We use `Prism.DryIoc.Maui` version `9.0.169-pre` and then when we want to autowire our view to their own viewmodel but not succeeded. We already register the view and viewmodel with
`ViewModelLocationProvider.Register<MainContentView, MainContentViewModel>();`
and we do also set `mvvm:ViewModelLocator.AutowireViewModel="Automatic"` explicitly in the Page and also in the `ContentView` itself. `MainContentViewModel` is also looks like never instantiated.

### Steps to Reproduce

1. Run https://github.com/albilaga/MAUIPlayground/tree/test-prismautowire
2. It should create list in the center of the page but no list created and `MainContentViewModel` is not triggered

### Platform with bug

.NET MAUI

### Affected platforms

iOS, Android

### Did you find any workaround?

Not yet.

**Comment by dansiegel** [comment]
This is not a bug. Please read the release notes. The way that Prism's Autowire property functions has been changed for MAUI. For the given UI that you're looking for you should use a Region which you can register the default View for.
