### ISSUE TITLE
[BUG] Android multiple instances of the app when navigating

### ISSUE THREAD

**Issue by GUOLDEV** [PrismLibrary/Prism#2905]
### Description

Android multiple instances of the app when navigating.

Sample used:
[MauiFest2022](https://github.com/dansiegel/MauiFest2022)

![image](https://github.com/PrismLibrary/Prism/assets/22019245/cdc9d576-69cb-46a3-91f3-4f56053fed52)

### Steps to Reproduce

Run the sample app MauiFest2022 on Android Device.
Tap any button in the Login Page.
The .Net Maui Developers Page will be displayed.
Tap the Device Navigation Bar Recents.
You can see multiple instances of app running.

### Platform with bug

Prism Core

### Affected platforms

Android

**Comment by SarthakB26** [comment]
duplicate https://github.com/PrismLibrary/Prism/issues/2833
