### ISSUE TITLE
[Enhancement] Support Microsoft DI (added in .NET 8)

### ISSUE THREAD

**Issue by bdovaz** [PrismLibrary/Prism#2922]
## Summary

Finally keyed services!

https://devblogs.microsoft.com/dotnet/announcing-dotnet-8-preview-7/#keyed-services-support-in-microsoft-extensions-dependencyinjection

**Comment by brianlagunas** [comment]
That's a good start, but the container is still immutable which is a problem for Prism.

**Comment by dansiegel** [comment]
Actually keyed services don't really help. Prism.Maui doesn't even use keyed services. But it does rely on container mutability.

**Comment by dansiegel** [comment]
Support for Microsoft DI will be available in Prism 9.0 for Commercial Plus License holders.

Everyone can thank @aritchie for getting me to look more into this.
