### ISSUE TITLE
[BUG] Exception thrown: 'System.IO.FileNotFoundException' in System.Private.CoreLib.dll

### ISSUE THREAD

**Issue by xiaoxstz** [PrismLibrary/Prism#2933]
### Description

If `ConfigurationModuleCatalog` or `DirectoryModuleCatalog` is used to load modules. Visual Studio will throw this error in the Output window. I found that the errors increase two more every time we add one module.

The official demo [Prism-Samples-Wpf /07-Modules - AppConfig](https://github.com/PrismLibrary/Prism-Samples-Wpf/tree/master/07-Modules%20-%20AppConfig) also shows it.

I have not found any issues caused by these errors, but I feel uneasy with them.

### Steps to Reproduce

1. Download the official sample `Prism-Samples-Wpf /07-Modules - AppConfig`
2. Run it with Visual Studio

My environment:
* WIndows 10
* Microsoft Visual Studio Community 2022 (64-bit) ,Version 17.5.4

### Platform with bug

WPF

### Affected platforms

Windows, I was *not* able test on other platforms

**Comment by brianlagunas** [comment]
Could not duplicate. The sample you linked to works. No exceptions thrown.

![image](https://github.com/PrismLibrary/Prism/assets/835562/e2a78ce8-f0e1-414d-a261-8f40aa7784ea)

I am closing this since I could not duplicate it. If you have an app that can duplicate the issue, please attached it.

**Comment by xiaoxstz** [comment]
I use Visual Studio 17.9.1 now, and I cannot duplicate this, as well
