### ISSUE TITLE
[BUG] NavigationPage Title Overridden by TabbedPage Segment Titles 

### ISSUE THREAD

**Issue by Adam--** [PrismLibrary/Prism#2937]
### Description

Presently, when a navigation page is created and a tabbed page is added to it with segments, the navigation page uses the tabbed page's segment titles as its title. This behavior is unexpected when using standard tabs (tabs on the top) in a navigation page on Android.

Without a custom tabbed page, this behavior makes sense, especially for bottom tabs; however, when a custom tabbed page is defined, it seems that the title should not be overridden.

Screenshot:
![Prism Issue 2937 Screenshot](https://github.com/PrismLibrary/Prism/assets/2179171/de80fe17-19b7-4f8b-a5c4-ccbf91adc112)

### Steps to Reproduce

Reproduced at https://github.com/Adam--/Prism/tree/tabbedpage-navpage-title in PrismMauiDemo.

1. Create a new TabbedPage called MyTabbedPage and set the Title to "MyTabbedPage"
2. Create two new ContentPages called ViewA and ViewB set their Titles to "ViewA" and "ViewB", respectively.
3. Register all pages for navigation.
4. Navigate to NavigationPage/MyTabbedPage?createTab=ViewA&createTab=ViewB on startup.
5. Tap the tabs "ViewA" and "ViewB"

Observed behavior:
The title displayed in the NavigationPage's toolbar is "ViewA" or "ViewB".

Expected behavior:
The title displayed in the NavigationPage's toolbar is "MyTabbedPage".

### Platform with bug

.NET MAUI

### Affected platforms

Android

### Did you find any workaround?

No

**Comment by dansiegel** [comment]
This is by design however I can see the issue where you may have already set the title and you would like to have that respected. Would you like to submit a PR to fix it?

**Comment by Adam--** [comment]
This is a bug in MAUI, not Prism see https://github.com/dotnet/maui/issues/8577.
