### ISSUE TITLE
[BUG] .Maui Framework Prism Navigation is not working

### ISSUE THREAD

**Issue by Elayaraj222** [PrismLibrary/Prism#2951]
### Description

We are trying to use the Prism shell navigation in .Net Maui framework I couldn't able to do the navigation as expected the page is not getting reloaded when i switch one page to another page. Same instance is persisting while to navigating to the same page. Right now I create custom code to load and unload the page and controls properties.

### Steps to Reproduce

We are trying to use the Prism shell navigation in .Net Maui framework I couldn't able to do the navigation as expected the page is not getting reloaded when i switch one page to another page. Same instance is persisting while to navigating to the same page. Right now I create custom code to load and unload the page and controls properties.

### Platform with bug

.NET MAUI

### Affected platforms

iOS, Android

### Did you find any workaround?

To write explict code in OnAppearing and OnDisappering method to control the properties manually for the all the page. So this will make too workaround for me for all the pages[currently we have 40 pages].

**Comment by dansiegel** [comment]
First of all Prism does not support Shell. Second it is mandatory to submit a sample that reproduces your issue.
