### ISSUE TITLE
NavigationService.NavigateAsync("../../") Throwing error in iOS 

### ISSUE THREAD

**Issue by letscodewithkalyan** [PrismLibrary/Prism#2952]
### Description

When I try to remove two pages from navigation stack in iOS 16.4. it is showing below error in NavigationResult

Value has to be >= 0.
Parameter name: destinationIndex

### Steps to Reproduce

Create a navigation hierarchy similar to above
Try to navigate two pages back without pushing another page

### Platform with bug

Xamarin.Forms

### Affected platforms

iOS

**Comment by letscodewithkalyan** [comment]
<img width="1120" alt="Screenshot 2023-09-09 at 4 19 32 PM" src="https://github.com/PrismLibrary/Prism/assets/36136595/3beab3ea-9a7e-4b3b-97f7-c6f63139fe87">

**Comment by dansiegel** [comment]
It is required to provide a sample reproducing the error.
