### ISSUE TITLE
[BUG] Modal page is not being closed when absolute navigation happens [Current repo version]

### ISSUE THREAD

**Issue by Alex-Dobrynin** [PrismLibrary/Prism#2953]
### Description

The modal page is not closed when absolute navigation was done. What is interesting, the modal stack is cleared. I tested it on android, but i suppose on ios the same.

I'm using the current cloned repo project as dependency instead of actual nuget, because it is outdated.

add as a reference Prism.DryIoc.Maui to the project  to be able to build the project

repro:
[PrismModalPage.zip](https://github.com/PrismLibrary/Prism/files/12609292/PrismModalPage.zip)

btw, this is not an issue in actual nuget, BUT actual nuget does not open modal page if it has NavigationPage as root page of modal navigation. this is why i'm using cloned repo as dependency.

### Steps to Reproduce

1. navigate to tabbed page:
2. Open modal page from tab:
3. do absolute navigation from modal page:
4. see that modal page is not closed, modal stack is empty

### Platform with bug

.NET MAUI

### Affected platforms

iOS, Android

### Did you find any workaround?

nope

### Relevant log output

```shell
no logs from prism
```

**Comment by dansiegel** [comment]
@Alex-Dobrynin @LarsHennig please submit an actual reproduction from the Prism 9 preview. If you want to wait on me to fix your sample it's going to take a long time to get fixed

**Comment by Alex-Dobrynin** [comment]
@dansiegel will do in few days

**Comment by Alex-Dobrynin** [comment]
this is fixed in the latest nuget version
