### ISSUE TITLE
[BUG] KnownNavigationParameters.SelectedTab does not actually select a tab [Current repo version]

### ISSUE THREAD

**Issue by Alex-Dobrynin** [PrismLibrary/Prism#2954]
### Description

When navigating to a tabbed page and in same time select a desired tab, the navigation happens, but the tab is not selected. I tested it on android, but i suppose on ios the same.

I'm using the current cloned repo project as dependency instead of actual nuget, because it is outdated.

add as a reference Prism.DryIoc.Maui to the project to be able to build the project

repro:
[PrismTabbedPage.zip](https://github.com/PrismLibrary/Prism/files/12602108/PrismTabbedPage.zip)

### Steps to Reproduce

1. navigate to a tabbed page with some tabs
2. in same time select tab in url
3. tab is not selected

### Platform with bug

.NET MAUI

### Affected platforms

iOS, Android

### Did you find any workaround?

nope

### Relevant log output

```shell
no logs from prism
```

**Comment by dansiegel** [comment]
Your issue is that you did not properly select the tab. You should have `NavigationPage|TabPage2` not just `TabPage2`

**Comment by Alex-Dobrynin** [comment]
@dansiegel in xamarin.forms it works without navigation page like this
<img width="391" alt="image" src="https://github.com/PrismLibrary/Prism/assets/23138430/95baabfa-caf5-46dc-8391-f2b92504f59c">
