### ISSUE TITLE
[BUG] Default navigation happens when trying to navigate modally [Current repo version]

### ISSUE THREAD

**Issue by Alex-Dobrynin** [PrismLibrary/Prism#2956]
### Description

When i try to navigate modally, my, supposed to be modal, page opens as default. I tested it on android, but i suppose on ios the same.

I'm using the current cloned repo project as dependency instead of actual nuget, because it is outdated.

add as a reference Prism.DryIoc.Maui to the project to be able to build the project

repro:
[PrismModalPage.zip](https://github.com/PrismLibrary/Prism/files/12609735/PrismModalPage.zip)

### Steps to Reproduce

1. navigate to start page
2. do modal navigation
3. see that page is not opened modally
4. uncomment this line in PrismStartup file 
![image](https://github.com/PrismLibrary/Prism/assets/23138430/3c6bde0f-d856-43ca-912c-9fff1a674d8b)
5. repeat step 1,2
6. the modal navigation happend

### Platform with bug

.NET MAUI

### Affected platforms

iOS, Android

### Did you find any workaround?

yes, in the repro project there is CustomPageNavigationService

### Relevant log output

```shell
no logs from prism
```

**Comment by Alex-Dobrynin** [comment]
@dansiegel here is the repo with added latest nuget package 9.0.271-pre. the bug is not fixed

[PrismModalPage.zip](https://github.com/PrismLibrary/Prism/files/13366095/PrismModalPage.zip)

**Comment by phillippschmedt** [comment]
@brianlagunas Any chance you can pay attention to this issue? It should be impacting everyone who is using modals.

**Comment by Alex-Dobrynin** [comment]
@phillippschmedt @tbaggett you can try this library, in which this can be done without any workarounds
[MPowerKit](https://github.com/MPowerKit/Navigation)
also you can try other libs of MPowerKit

**Comment by phillippschmedt** [comment]
Commenting here to make it clear that the issue is not fixed and still exists even after https://github.com/PrismLibrary/Prism/pull/3055

**Comment by phillippschmedt** [comment]
@dansiegel Maybe this issue should be reopened to make it clear that https://github.com/PrismLibrary/Prism/pull/3055 did not fix it?
