### ISSUE TITLE
NavigationService.GoBack() doesn't trigger OnGoBackRequested

### ISSUE THREAD

**Issue by senkia** [PrismLibrary/Prism#296]
If I perform a back navigation by pressing the hardware back button or the title bar back button the OnGoBackRequested method in App.cs gets called alright. But if I try to navigate backward by calling GoBack() on the NavigationService OnGoBackRequested doesn't get called.

Is that normal behavior? If so, then how can I handle back navigation initiated by the NavigationService on the application level?

**Comment by bartlannoeye** [comment]
The OnGoBackRequested event handler is to couple the DeviceGestureService with the NavigationService. If you look at [the implementation](https://github.com/PrismLibrary/Prism/blob/ff93f11245bbde7b44755e2abb40c8c177bdc3a5/Source/Windows10/Prism.Windows/PrismApplication.cs#L377-L381), it doesn't do much more than call NavigationService.GoBack(). So if you call GoBack yourself, you're actually using a shortcut and doing the backward navigation correctly.
