### ISSUE TITLE
Add data-binding friendly Task

### ISSUE THREAD

**Issue by arbsmith** [PrismLibrary/Prism#297]
Look at Stephen Cleary's NotifyTaskCompletion. Would also like an easy way to handle Progress, Cancel and Pause.

**Comment by brianlagunas** [comment]
Since there is a NuGet that already has this, what would the benefit be to adding it to Prism?  Where in Prism do you see this being used?

**Comment by brianlagunas** [comment]
After reviewing Stephen's project, this is not something I believe should be brought into Prism.  Actually it seems you can use Stephen's code with Prism.
