### ISSUE TITLE
[BUG] Prism.DryIoc.Uno.WinUI 9.0.264-pre

### ISSUE THREAD

**Issue by sigmarsson** [PrismLibrary/Prism#2973]
### Description

The package cannot be installed due to ;

`Unable to find package Prism.Events.`

<img width="678" alt="image" src="https://github.com/PrismLibrary/Prism/assets/43340959/ba9d018a-9749-4565-b86d-0f0e70d19201">

### Steps to Reproduce

Try to install the package. 

### Platform with bug

Uno Platform - WinUI

### Affected platforms

Windows

**Comment by dansiegel** [comment]
Thanks for bringing this to our attention. It seems there were some issues in the CI release that need to get fixed. We'll have an updated package out some time this weekend.

**Comment by sigmarsson** [comment]
Thanks for making it happen MR !

**Comment by dansiegel** [comment]
this is resolved with 9.0.271-pre
