### ISSUE TITLE
[BUG] ViewModel of Controls not being wired when setting ViewModelLocator.AutowireViewModel="Automatic" and manually registering them with ViewModelLocationProvider.Register 

### ISSUE THREAD

**Issue by mlxyz** [PrismLibrary/Prism#2994]
### Description

When setting `ViewModelLocator.AutowireViewModel="Automatic"` on a custom XAML control (e.g. ContentView) and registering the viewmodel for that view using the `ViewModelLocationProvider.Register` method, the viewmodel is not being wired.

This used to work on Xamarin, not sure why its not working anymore. I need this feature as i have lots of custom controls with their own view models pulling in their dependencies through DI.

<details>

CustomControl:
```xaml
<?xml version="1.0" encoding="utf-8" ?>
<ContentView xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:prism="http://prismlibrary.com"
             xmlns:vm="clr-namespace:PrismApp.ViewModels"
             x:Class="PrismApp.Controls.CustomControl"
             prism:ViewModelLocator.AutowireViewModel="Automatic">
  <VerticalStackLayout>
    <Label Text="This is the content:" VerticalOptions="Center" 
           HorizontalOptions="Center"></Label>
    <Label Text="{Binding CustomText}"
           VerticalOptions="Center" 
           HorizontalOptions="Center" />
  </VerticalStackLayout>
</ContentView>
```

CustomControlViewModel:
```csharp
namespace PrismApp.ViewModels
{
    internal class CustomControlViewModel
    {
        public string CustomText => "This is a custom control";
    }
}
```

PrismStartup:
```csharp
namespace PrismApp;

internal static class PrismStartup
{
    public static void Configure(PrismAppBuilder builder)
    {
        ViewModelLocationProvider.Register<CustomControl, CustomControlViewModel>();
        ViewModelLocationProvider2.Register<CustomControl, CustomControlViewModel>();
        builder.RegisterTypes(RegisterTypes)
                .OnAppStart("NavigationPage/MainPage");
    }

    private static void RegisterTypes(IContainerRegistry containerRegistry)
    {
        containerRegistry.RegisterForNavigation<MainPage>()
                     .RegisterInstance(SemanticScreenReader.Default);
    }
}
```

MainPage:
```xaml
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:controls="clr-namespace:PrismApp.Controls"
             Title="{Binding Title}"
             x:Class="PrismApp.Views.MainPage">

  <ScrollView>
    <VerticalStackLayout
            Spacing="25"
            Padding="30,0"
            VerticalOptions="Center">
      <controls:CustomControl></controls:CustomControl>
    </VerticalStackLayout>
  </ScrollView>

</ContentPage>
```
</details>

### Steps to Reproduce

1. Create new Prism MAUI project (.NET 7)
2. Create a ContentView XAML file
3. Create a viewmodel for the ContentView control
4. Set `ViewModelLocator.AutowireViewModel="Automatic"` on the ContentView
5. In `PrismStartup`, register the contentview with the viewmodel using `ViewModelLocationProvider.Register<CustomControl, CustomControlViewModel>();`
6. Use the ContentView in the MainPage

Repro repo: https://github.com/mlxyz/prism-maui-repro.git

### Platform with bug

.NET MAUI

### Affected platforms

iOS, I was *not* able test on other platforms

**Comment by dansiegel** [comment]
What you are doing is not supported. Please update your code to use Region Navigation. You can register your Control to automatically load in the when the region is created.
