### ISSUE TITLE
NavigateAsync, KnownNavigationParameters.UseModalNavigation & GoBackAsync

### ISSUE THREAD

**Issue by MartinRobins** [PrismLibrary/Prism#2995]
### Description

I am trying to show a modal page using the following...

            INavigationBuilder builder = NavigationService.CreateBuilder();
            await builder
                .UseRelativeNavigation()
                .AddSegment(nameof(SynchronisationPopupPage), segmentBuilder =>
                {
                    segmentBuilder.AddParameter(KnownNavigationParameters.UseModalNavigation, true);
                })
                .NavigateAsync();

This displays correctly, but when I then try to close the page and return to the caller...

            INavigationResult result = await NavigationService.GoBackAsync();

I get an exception in the result "Cannot Pop Application MainPage".

I suspect that I am using the INavigationBuilder incorrectly?

### Steps to Reproduce

Create a MAUI application.

Add the Mopups nuget package.

Add a Flyout Page ("HomePage") along with the necessary content pages ("HomePageFlyoutContentPage" and "HomePageDetailContentPage") and matching view-models "HomePageFlyoutContentPageViewModel" and "HomePageDetailContentPageViewModel") for the content pages.

Add another page "SynchronisationPopupPage" along with an associated view-model ("SynchronisationPopupPageViewModel")
Register the pages for navigation (I used the overload that takes both page type and view-model type). This page is derived from PopupPage (within Mopups).

Within the "HomePageFlyoutContentPageViewModel", add a command...

```

        private Command _syncAllDataCommand;
        public Command SyncAllDataCommand
        {
            get { return _syncAllDataCommand ?? (_syncAllDataCommand = new Command(async () => await ExecuteSyncAllDataCommand())); }
        }

        private async Task ExecuteSyncAllDataCommand()
        {

            INavigationBuilder builder = NavigationService.CreateBuilder();
            await builder
                .UseRelativeNavigation()
                .AddSegment(nameof(SynchronisationPopupPage), segmentBuilder =>
                {
                    segmentBuilder.AddParameter(KnownNavigationParameters.UseModalNavigation, true);
                })
                .NavigateAsync();
        }


```
Within the "HomePageFlyoutContentPage", add a button and bind it to the command above

Within the "SynchronisationPopupPageViewModel", add a command...

```

        private Command _closeCommand;
        public Command CloseCommand
        {
            get { return _closeCommand ?? (_closeCommand = new Command(async () => await ExecuteCloseCommand())); }
        }

        private async Task ExecuteCloseCommand()
        {
            INavigationResult result = await NavigationService.GoBackAsync();
        }

```

Place a breakpoint on the closing bracket under the GoBackAsync line.

Within the "SynchronisationPopupPage", create a button and bind it to the command above.

Within the CreateMauiApp/UsePrism method...

```
                    .OnAppStart(async navigationService =>
                    {
                        await navigationService.CreateBuilder()
                            .AddSegment(nameof(HomePage))
                            .AddNavigationPage()
                            .AddSegment(nameof(HomePageDetailContent))
                            .NavigateAsync();
                    });

```

Run the application. Click the button on the flyout page ("HomePageFlyoutContentPage") to open ""SynchronisationPopupPage"". When you then click the button on "SynchronisationPopupPage" to close it, you should stop on the breakpoint you can see the error.

### Platform with bug

.NET MAUI

### Affected platforms

Android, I was *not* able test on other platforms

### Did you find any workaround?

Not yet.

### Relevant log output

```shell
[DOTNET] Navigation: GoBack
[DOTNET] Result: Failed
[DOTNET] Cannot Pop Application MainPage
```

**Comment by MartinRobins** [comment]
Just to add, I have included ...

```
UsePrism(prismAppBuilder=> {
  ...
  prismAppBuilder.ConfigureMopups();
  ...
{); 
```

I have based "SynchronisationPopupPage" on PopupPage as it is being ported from a Prism.Forms application. The documentation says it should be a drop in replacement so I have merely changed namespaces.

I am not using DialogService as the documentation says it is not supported in Prism 8.x

		<TargetFrameworks>net7.0-android;net7.0-ios</TargetFrameworks>
		<PackageReference Include="CommunityToolkit.Maui" Version="6.0.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="7.0.13" />
		<PackageReference Include="Mopups" Version="1.2.0" />
		<PackageReference Include="Prism.Maui.Rx" Version="8.1.273-pre" />
                <PackageReference Include="Prism.DryIoc.Maui" Version="8.1.273-pre" />

**Comment by MartinRobins** [comment]
I have tried changing PopupPage to ContentPage (just to rule out Mopups); no difference. I still get the error and the modal page stays open.

**Comment by dansiegel** [comment]
@MartinRobins while I appreciate the lots of code you've provided here, we do require that you provide a sample that can reproduce the issue. I do not have time to create samples for everyone's issues.

**Comment by MartinRobins** [comment]
@dansiegel Please find attached a minimal VS2022 solution that demonstrates the issue.
When you run the application, follow the instructions on screen and you will see what to do in order to reproduce it.

[PrismIssue.zip](https://github.com/PrismLibrary/Prism/files/13297365/PrismIssue.zip)

**Comment by dansiegel** [comment]
I am unable to reproduce your issue using net8 and Prism 9. Please be sure you are using the latest bits.

**Comment by MartinRobins** [comment]
@dansiegel Were you able to verify the problem in net7 and Prism 8 (as originally provided)?
If this is the case, then I can be confident that simply moving to net8/Prism9 (when they are released) will resolve the problem.

**Comment by dansiegel** [comment]
I do not bother with net7. We don't support net7 and this isn't paid support. If you require Paid support please feel free to reach out to us at support@prismlibrary.com and we can discuss your options.

**Comment by MartinRobins** [comment]
Sorry, did not realise .NET7 was unsupported. I do not yet have .NET8 (or the VS preview) so had not tested with this.
Thank you for your help; I will look into the available support options as I have always preferred using Prism with Xamarin in the past as, if nothing else, the navigation is so much easier.
