### ISSUE TITLE
[BUG] Navigating away from a page with Regions to a named page and back again doesn't work. 

### ISSUE THREAD

**Issue by HelenMamalaki** [PrismLibrary/Prism#2996]
### Description

In the attached Repo sample: 

We start off with a _MainPage_, that can navigate to a _SecondPage_ which contains two Regions. From there if I do
`	await _navigationService.GoBackAsync();`
back to the _MainPage_ and then navigate to the  _SecondPage_ again, it navigates fine.

BUT if I do
 `       await _navigationService.NavigateAsync("MainPage");`
to get back to the _MainPage_ and then navigate to  _SecondPage_, nothing happens. 

I tried implementing a NavigationService error call back and I didn't garner any more information beyond the fact that some generic navigation exception is being thrown.

Repo: https://drive.google.com/file/d/14ICHKd3Zhre83gLoSRuL43icdbPpX8TN/view?usp=sharing

Testing in net7-Windows-10.0.19041

Any help would be much appreciated. Without Regions I don't have any way of implementing Tabs backed by ViewModels (outside of a TabbedPage which is not suitable) unless anyone can recommend something. 

### Steps to Reproduce

I have attached a Repo solution.

### Platform with bug

.NET MAUI

### Affected platforms

Windows, I was *not* able test on other platforms

### Did you find any workaround?

GoBackAsync() works but that doesn't work for all navigation scenarios so this is not a workaround I can use.

**Comment by dansiegel** [comment]
@HelenMamalaki please provide your sample directly to GitHub and remove the bin/obj before zipping it up. Thanks

**Comment by HelenMamalaki** [comment]
[Repo-Navigation-Region-bug-no-binobj.zip](https://github.com/PrismLibrary/Prism/files/13259429/Repo-Navigation-Region-bug-no-binobj.zip)

@dansiegel Thanks for your reply. Done. :)

**Comment by HelenMamalaki** [comment]
I can see this has been added as a milestone for Prism 9 which is great. Thank you.😊 

Just as a rough timeline, is Prims 9 intended to be released by the end of this year/ early next year or is the time frame much longer?

**Comment by dansiegel** [comment]
really depends on the time I have.... if I can get it out next week that would be my preference... but it may wait until next month when I'm back from vacation.

**Comment by dansiegel** [comment]
After looking more at your issue, the API is working as designed.

The scenario where you go:

- Page1 -> Page2... then call GoBack()

This works because Page2 is popped off of the Navigation Stack and the Regions are removed.

When you do:
- Page1 -> Page2 then call `NavigateAsync("Page1")` you really have the NavigationStack `Page1 -> Page2 -> Page1`.. which mean that when you attempt to go to Page2 from the 2nd instance of Page1 you get a Navigation Exception because the Regions in Page2 already exist within the application.

You can fix this by using Absolute Navigation like `NavigateAsync("/Page1")`

**Comment by HelenMamalaki** [comment]
@dansiegel Thanks, that makes sense. However if you use Absolute Navigation there is a different bug, in the same sample above if you update it to use Absolute navigation (either: NavigateAsync("/MainPage") or NavigateAsync("app:///MainPage") everything looks normal* the first time, but the second time you do it, the Window duplicates! For every 2nd, 3rd, 4rth time the app windows replicates itself. 0_0 It's bizarre. 

Do you want me to raise a new bug for that or use this one?

*With absolute nav, rather then the normal slide in transition animation, the screen flashes white or black (depending on the devices' theme, and not the app's theme) - it looks like the app is glitching. I can see there is a bug fix for switching off animation completely so can try that in the future.

**Comment by dansiegel** [comment]
key word.. `different bug`... Please be sure to provide a sample that reproduces the issue in your new issue.
