### ISSUE TITLE
[BUG] Navigation auto reset

### ISSUE THREAD

**Issue by LaBoss** [PrismLibrary/Prism#2997]
### Description

When I minimize the application, the program returns to the OnStart page, but only the first time, after returning to the login page, it works correctly.

In my application the problem is that I use printManager and when I do back, exactly the same thing happens, after logging in again, it no longer happens.

### Steps to Reproduce

https://github.com/PrismLibrary/Prism/assets/5363187/ce7591ae-f18a-44e1-8ab8-412957f002c9

Demo project
[Prism.zip](https://github.com/PrismLibrary/Prism/files/13252996/Prism.zip)

### Platform with bug

.NET MAUI

### Affected platforms

Android

### Did you find any workaround?

No

**Comment by dansiegel** [comment]
This shouldn't happen from Prism unless something has happened to your application window. As you'll notice we have not one, but 2 sanity checks to ensure that if a Window already exists we return the one that exists. The OnStart delegate in your Startup is only invoked if no Window is found.

https://github.com/PrismLibrary/Prism/blob/9ae685d6c2ce486c6d32268010ef773c921eb042/src/Maui/Prism.Maui/Navigation/PrismWindowManager.cs#L16-L26

**Comment by LaBoss** [comment]
If i change nav to Startup - > Login - > nav/Main the app works great but i need nav/Login because off settings page

I will try debug prims with demo project o monday, the problem is i dont have permissions too install .Net 8 o dev machine need to ask to IT dep to install

**Comment by LaBoss** [comment]
I try update to .NET 8 and use prism source on project, and problem disappeared, i will try on real project and report back (My problem is collectionview bug on .NET 8 version but i try to change code to work without it)

**Comment by LaBoss** [comment]
On last version if fixed, thanks
