### ISSUE TITLE
[BUG] Navigation using "../../" Does Not Work Correctly When Last Page in Stack Is a Popup from Prism.Plugin.Popup

### ISSUE THREAD

**Issue by vppetrov** [PrismLibrary/Prism#3003]
### Description

**Desired Functionality**

From MainPage, navigate to Page1. From Page1 navigate to Popup2. From Popup2 navigate back to the MainPage using navigation "../../".

**Expected Behavior**

When navigating "../.." from inside Popup2, the app returns **two levels** back to **MainPage**.

**Actual Behavior**

When navigating "../.." from inside Popup2, the app returns **one level** back to **Page2**.

**Additional Notes**

The same navigation, when executed from a Page2 (instead of Popup2) works as expected.

**Reproduction Project**

Available at [GitHub](https://github.com/vppetrov/Prism.Xamarin.Forms.Bug.NavigationWithLastPageInStackIsPopup).

### Steps to Reproduce

Reproduction project with MainPage, Page1, Page2 and Popup2 provided as GitHub repository. Behavior as described in the description.

### Platform with bug

Xamarin.Forms

### Affected platforms

Android

### Did you find any workaround?

No.

### Relevant log output

None.

**Comment by dansiegel** [comment]
Popup Pages are not supported as part of the Navigation Stack. You should be using Popup Pages with the DialogService.
