### ISSUE TITLE
Xamarin - Navigate(string, useModalNavigation:false) crashed on android, and not working on wp8.1

### ISSUE THREAD

**Issue by pardont** [PrismLibrary/Prism#301]
Bug 1:
MainPageViewModel.cs:
 _navigationService.Navigate("ViewA", useModalNavigation:false);

Crashed on android;

Bug2:
MainPageViewModel.cs:
 _navigationService.Navigate("ViewA")
ViewAViewModel.cs:
  _navigationService.Navigate("ViewB", useModalNavigation:false);

Can not navigate to ViewB on wp8.1, and crashed on android.

**Comment by brianlagunas** [comment]
What version are you using?  What is the exception?

**Comment by pardont** [comment]
Prism                       - 6.1
Prism.Forms            - 6.0
Prism.Unity.Forms   - 6.0

I just "downoad zip" at 2015/11/11. and test the "Prism-master\Samples\Xamarin\HelloWorld" sample, I modified few rows to test the navigation feature. It seems 
_navigationService.Navigate(string, useModalNavigation:false);
has bug.

Excpetion:
On Android:  "An unhandled exception occured."
On WP8.1:    No Response.

**Comment by pardont** [comment]
BTW, I have a version(download zip at 2015/11/09),  it works fine.

**Comment by brianlagunas** [comment]
If you are downloading the Zip of the current source code, be careful because it s being actively developed on.  You also have to make sure you are using the correct Xamarin.Forms version.  The current table version is v6.0.1:

https://github.com/PrismLibrary/Prism/releases/tag/Prism.Formsv6.0.1

**Comment by bartlannoeye** [comment]
An addition to @brianlagunas's remark:
As mentioned on the [samples readme](https://github.com/PrismLibrary/Prism/blob/master/Samples/README.md), use the stable samples under [this repository](https://github.com/PrismLibrary/Prism-Samples-Forms), which are using stable NuGet packages (while the ones you mentioned use the changing code base).

**Comment by pardont** [comment]
Hi, brianlagunas,

Sorry for my stupid mistake, I download v6.0.1, it works fine.

Thank you
