### ISSUE TITLE
[BUG] Cannot bind correct ViewModel to TabbedPage children with ViewModelLocator

### ISSUE THREAD

**Issue by caz162** [PrismLibrary/Prism#3017]
### Description

I am trying to dynamically add pages from a TabbedPages ViewModel at runtime. Each page has its own ViewModel, which  will have its own custom logic within it. However the ViewModelLocator is always assigning the parent's ViewModel to the child pages. I would assume since we have defined the navigation route it would bind to its own ViewModel rather than the parents one. I know the functionality of ViewModelLocator has changed since we implemented it in our app to be automatic, rather than opt in.

Previously (in 7.2) we would have created the page, set the AutowireViewModel then added it to the TabbedPage. We used this extensively in our app so we are trying to find a replacement.

I have tried to implement this but no avail. I found the below enhancement request with sample code to do this (https://github.com/PrismLibrary/Prism/issues/2156). I have found that this doesn't work and it still binds the parent's ViewModel to the child page.

I implemented it into the sample app listed below to highlight the potential issue.

Repo: [Test Repo](https://github.com/caz162/MAUI/archive/refs/heads/main.zip)

Within this app there is a TabbedPage and ViewModel called MainTabPage and MainTabPageViewModel. On navigated to, it will try and add child pages at runtime. These pages are InnerPageA, InnerPageB, InnerPageC, InnerPageD, InnerPageE.

In order to debug I have setup all these pages differently in order to try and get the ViewModelLocator to bind the pages correctly. 

InnerPageA : This one sets the prism:ViewModelLocator.AutowireViewModel="Automatic" in its XAML
InnerPageB : This one explicitly sets its DataType x:DataType="viewmodels:InnerTabBViewModel"
InnerPageC : This one uses the constructor to get the VM and set its binding there. While this works I had hoped the ViewModelLocator could be used.
InnerPageD : This one does nothing, just uses default ViewModelLocator
InnerPageE : This one sets the prism:ViewModelLocator.AutowireViewModel="Disabled". I would assume that wouldn't bind to anything.

### Steps to Reproduce

Download and open the test project supplied.
Run project, it should open 5 Tabs (InnerTabA, InnerTabB, InnerTabC, etc)

Each of these tabs have a binding to their ViewModel. It will print out the ViewModels class name as well as its ID.
Notice that every tab (except InnerTabC) is bound to the MainTabPageViewModel, rather than its own ViewModel.

I would expect them to bind to their own ViewModels.

### Platform with bug

.NET MAUI

### Affected platforms

Android

**Comment by brianlagunas** [comment]
Good news is this is not a bug. Instead, you need to change the way you are creating the views. Prism moved to an IViewRegistry. So, for MAUI, if you want to use Prism to create the views your extension method will look like this:

```cs
public static async Task AddTabAsync(Page currentPage, string name, INavigationParameters parameters = null)
{
    TabbedPage tabbedPage = null;

    if (currentPage is TabbedPage tPage)
    {
        tabbedPage = tPage;
    }
    else if (currentPage.Parent is TabbedPage parent)
    {
        tabbedPage = parent;
    }
    else if (currentPage.Parent is NavigationPage navPage)
    {
        if (navPage.Parent != null && navPage.Parent is TabbedPage parent2)
        {
            tabbedPage = parent2;
        }
    }
    
    var scopeProvider = ContainerLocator.Container.CreateScope();
    var registry = ContainerLocator.Container.Resolve<INavigationRegistry>();
    var newTab = registry.CreateView(scopeProvider, name) as Page;

    ViewModelLocator.SetAutowireViewModel(newTab, ViewModelLocatorBehavior.Automatic);
        
    await MvvmHelpers.OnInitializedAsync(newTab, parameters);

    tabbedPage.Children.Add(newTab);
    tabbedPage.CurrentPage = newTab;
}
```
