### ISSUE TITLE
[BUG] IDialogService does not display dialog when using RelativeHeightRequest and/or RelativeWidthRequest [MAUI/9.0.271-pre]

### ISSUE THREAD

**Issue by MartinRobins** [PrismLibrary/Prism#3019]
### Description

When trying to display a dialog using IDialogService and the XAML for the dialog uses the RelativeHeightRequest and/or RelativeWidthRequest attached properties the content of the dialog is never rendered.

Repo: 
[PrismIssue.zip](https://github.com/PrismLibrary/Prism/files/13518092/PrismIssue.zip)

### Steps to Reproduce

Unzip the attached repo.
Open in Visual Studio 2022 (I am using 17.8.2)
Build and deploy to an Android device.
Click the button on the first screen to open the dialog.
The existing page is masked as if the dialog should be there, but there is no dialog content.

If you then edit the SynchronisationDialog.xaml and remove the following lines...

```
       prism:DialogLayout.RelativeHeightRequest="0.9"
       prism:DialogLayout.RelativeWidthRequest="0.9"

```
... re-running the repo then displays the dialog content correctly (albeit not formatted very well as it is not sized to the screen as would have been expected had the now removed properties been set).

### Platform with bug

.NET MAUI

### Affected platforms

Android, I was *not* able test on other platforms

### Did you find any workaround?

The only workaround I have found to date is to remove the problematic properties and then manually size the dialog. This is not ideal as it becomes restrictive when deployed to different devices with different form factors.

### Relevant log output

```shell
I see no log output that appears to be related to this issue.
```

**Comment by abaslam** [comment]
I am able to reproduce this issue, following are the screenshot which was reproduced in prism MAUI demo application.

iOS

![ios-2](https://github.com/PrismLibrary/Prism/assets/1916748/a80e327c-0d59-4b62-8220-42b14cebf3ed)

Android

![android-2](https://github.com/PrismLibrary/Prism/assets/1916748/c4b0850f-d964-4772-9e46-7e7c45e6447d)
