### ISSUE TITLE
async/await in InteractionRequest is unneeded

### ISSUE THREAD

**Issue by tiesmaster** [PrismLibrary/Prism#303]
The [`RaiseAsync`](https://github.com/PrismLibrary/Prism/blob/305276db0a83f0b21cdb1318b4ff9d4edb8211ec/Source/Wpf/Prism.Wpf/Interactivity/InteractionRequest/InteractionRequest.cs#L51) in InteractionRequest is an [unnecessary async/await method](http://www.learnasync.net/misuse-unnecessaryasync.html), and can be simplified, like [this commit](https://github.com/tiesmaster/Prism/commit/2273dcd8f0ecd2ed49f048168c33f5eb69b21dc5) shows.

Is it ok if I put this in a PR?

**Comment by bartlannoeye** [comment]
Guess those went through the mazes of the net. You're 200% correct, bring it in!

**Comment by tiesmaster** [comment]
Done. I've found a couple more, I've also taken the liberty to touch that code, I hope that's ok ;)

**Comment by briannoyes** [comment]
Thanks and good catch!

**Comment by tiesmaster** [comment]
Btw PR #124, and #127 will add a lot of these unneeded async methods. Just a heads-up ;)
