### ISSUE TITLE
[BUG] DynamicResource no longer works in .Net 8 MAUI

### ISSUE THREAD

**Issue by jamesv-7** [PrismLibrary/Prism#3033]
### Description

Using DynamicResource in xaml is no longer working in .Net 8 MAUI with Prism Maui. The only way to get it to work is use StaticResource which defeates the purpose of DynamicResource.

### Steps to Reproduce

1. Create new .Net 8 MAUI Project.
2. Add ResourceDictionary with a color to App.xaml
    <Application.Resources>
        <ResourceDictionary>
            <Color x:Key="main-color">#5ACCCC</Color>
        </ResourceDictionary>
    </Application.Resources>
3. Set BackgroundColor="{StaticResource main-color}" of xaml
4. Change color with button click or another way
      Resources["main-color"] = Colors.Red;
5. Initial xaml background color is white and color never changes on button click

### Platform with bug

.NET MAUI

### Affected platforms

iOS, Android

### Did you find any workaround?

No

**Comment by Alex-Dobrynin** [comment]
1. DynamicResource does work in .net8 maui
2. This has nothing to Prism library

**Comment by jamesv-007** [comment]
It works if I don't have Prism installed. As soon as I link prism it quits working. I can send you a test project if you like. 
As soon as I add this dynamic resources quit working .UsePrism
Also you documentation for MAUI is wrong says to use .UsePrism<app> but get error.

**Comment by jamesv-007** [comment]
DynamicResources do work in .Net Maui until you install Prism Maui then it no longer does. I have a test project if you would like it. Give it a try.

**Comment by dansiegel** [comment]
@jamesv-007 a sample reproduction is required for us to look into the issue. I'm not sure how Prism would be breaking this for you as Prism does nothing with regards to resources... Prism 9 doesn't even provide a base application type anymore so it's 100% MAUI

cc: @pureween @redth

**Comment by jamesv-007** [comment]
You are correct! I got it working.

Glad to know you are here if needed.

**Comment by dansiegel** [comment]
We had originally planned on releasing a stable version last month however due to sudden increase of issues for MAUI the last couple of months we have temporarily decided to delay that. There are a couple of small issues I am planning on getting some PRs for and once those are in we'll do another preview and re-evaluate from there.
