### ISSUE TITLE
[BUG] Tabbed Page doesn't show icons and title when using NavigationPage

### ISSUE THREAD

**Issue by sact1909** [PrismLibrary/Prism#3035]
### Description

Tabbed Page doesn't show Icons and Title when adding AddNavigationPage().AddSegment() to CreateTab() method.

I try to use the following code on the pages that I'm using to create the tabs but it's still happen
`prism:TabbedPage.IconImageSource="setting.png"`
`prism:TabbedPage.Title="Page Three"`

Current Behavior

https://github.com/PrismLibrary/Prism/assets/23615129/da85c31b-7a3b-442a-aa7f-c342e7a43774

Expected Behavior
![Screenshot_1703669492](https://github.com/PrismLibrary/Prism/assets/23615129/9693b68c-1ff1-405c-b5c2-219ebef46631)

### Steps to Reproduce

1. Create a MAUI App using Prism Template
2. Create MAUI TabbedPage (it doesn't matter if you avoid this step and create the tabbed page with the extension method)
3. Add the Tabs to TabbedPage using ExtensionQueryMethod in the PrismStartup.cs
![image](https://github.com/PrismLibrary/Prism/assets/23615129/6d62f419-ab1d-4466-a6bd-8d4dbade4413)
4. Add IconImageSource to the Tabs Pages
5. Run the app.

(It still happen using a MAUI App Template and adding the corresponding libraries to use Prism).

Sample Project
[TestPrismMaui.zip](https://github.com/PrismLibrary/Prism/files/13814000/TestPrismMaui.zip)

### Platform with bug

.NET MAUI

### Affected platforms

Android

### Did you find any workaround?

The only way this works is adding the pages manually to the TabbedPage with its NavigationPage

`<NavigationPage Title="PageOne"
             IconImageSource="bowlricesolid.svg">
  <x:Arguments>
    <locals:PageOne />
  </x:Arguments>
</NavigationPage>`

but, the prism documentation specifies that you don't recommend doing this, but it is the only way that the application has the expected behavior using the TabbedPage, the app looks working properly, using for a while and no crashing any time, but if you warning us about it, is because there is something you know that we don't, but in other ways, it doesn't work and its better if I do as you recommend it.
![image](https://github.com/PrismLibrary/Prism/assets/23615129/02912bc9-97bb-4e70-9d52-8709c897590b)

**Comment by dansiegel** [comment]
@sact1909 a sample reproduction is required

**Comment by sact1909** [comment]
@dansiegel Nice, here the same I used to take the video and the image

[TestPrismMaui.zip](https://github.com/PrismLibrary/Prism/files/13814008/TestPrismMaui.zip)

**Comment by dansiegel** [comment]
@sact1909 thanks for the sample... I see what your issue is... it should be fixed in the next release.

**Comment by sact1909** [comment]
NICE @dansiegel , glad to hear this will be fixed in the next release, sorry If I bother you, I know you are someone very busy and I don't wanana sound annoying doing dumbs questions to you, but I would like to know when we shall have this new release (dont have to say the exactly date), I'm asking because my customer need information about the state of her application development and I need to let her know whats happening

**Comment by dansiegel** [comment]
Looking at doing the next public preview in the next week or two. But you can get access to the latest builds with the Commercial Plus license.

**Comment by AnthonyLatty** [comment]
@dansiegel, was this release make public to non Commercial Plus license users?
