### ISSUE TITLE
[BUG] No destination with ID 2 is on the NavController's back stack

### ISSUE THREAD

**Issue by AwsomeCode** [PrismLibrary/Prism#3052]
### Description

<img width="675" alt="image" src="https://github.com/PrismLibrary/Prism/assets/11809653/a19d31c8-874c-40c2-8efa-870ad24014d8">

### Steps to Reproduce

1. The app starts with MainPage
2. Navigate to FirstPage
3. Navigate back to MainPage (Exception!)

[Repo](https://github.com/AwsomeCode/MauiTabbedPageBug)

### Platform with bug

.NET MAUI

### Affected platforms

Android

### Did you find any workaround?

NO

**Comment by dansiegel** [comment]
@AwsomeCode 

- Do not register the Maui NavigationPage. Prism automatically provides a registration for both the TabbedPage and NavigationPage. In the specific case of the NavigationPage Prism uses the PrismNavigationPage which provides some better handling for BackButton scenarios with the Navigation Service. If you absolutely need to provide your own NavigationPage then you should inherit from the PrismNavigationPage.
- Second I'm unable to reproduce the issue with the attached sample.

**Comment by AwsomeCode** [comment]
> * Second I'm unable to reproduce the issue with the attached sample.

Interesting.
Because it's a blank project, with prism only I have created a new blank project, the same as the old one, and it's working fine. Will try clearing the Bin and Obj folder. Let see.

**Comment by AwsomeCode** [comment]
@dansiegel Deleting the .vs folder worked. I don't get a relation with it but it worked.
Thanks for your time.

**Comment by dharamhbtik** [comment]
`Java.Lang.IllegalArgumentException: 'No destination with ID 11 is on the NavController's back stack. The current destination is Destination(0x5) class=crc6452ffdc5b34af3a0f.NavigationViewFragment'`

I am also getting almost same exception when closing the modal which was open using 
NavigationService.NavigateAsync and passing navigation parameter as ModalPopup
and closing using 
`NavigationService.GoBackAsync();`

this is breaking when I turn on the commaon language runtime exception in debug mode. 

We are not registering NavigationPage but have customnavigation page which is inherting navigation page and this customnavigation page we are using to navigate something like this

`NavigationService.NavigateAsync("CustomNavigationPage/HomePage");`

**Comment by brianlagunas** [comment]
@dharamhbtik your custom navigation page MUST derive from the `PrismNavigationPage` or it will never work.
