### ISSUE TITLE
[BUG] Prism.Navigation getParameters failed (empty parameters)

### ISSUE THREAD

**Issue by brdacon1** [PrismLibrary/Prism#3054]
### Description

Using navigation, I'm getting the error getParameters failed (empty parameters) which refers to app navigation using the Prism lib, has anyone ever gotten this error?

### Steps to Reproduce

Using navigation, I'm getting the error getParameters failed (empty parameters) which refers to app navigation using the Prism lib, has anyone ever gotten this error?

### Platform with bug

Xamarin.Forms

### Affected platforms

Android

### Did you find any workaround?

Using navigation, I'm getting the error getParameters failed (empty parameters) which refers to app navigation using the Prism lib, has anyone ever gotten this error?

### Relevant log output

```shell
Using navigation, I'm getting the error getParameters failed (empty parameters) which refers to app navigation using the Prism lib, has anyone ever gotten this error?
```

**Comment by dansiegel** [comment]
Bug reports must be accompanied by a sample that reproduces your issue.
