### ISSUE TITLE
[uwp] rootSplitView doesnt close on menuitemviewmodel

### ISSUE THREAD

**Issue by asiddique** [PrismLibrary/Prism#306]
is there a way to set rootSplitView.IsPaneOpen to false if already open when Command is called on menu item? as it stands, user has to manually close. new to prism so unsure how to wire it up correctly.

**Comment by billSpaulding** [comment]
Hello There!

I'm fairly new to XF so I apologize if I have misunderstood your question. However if by "SplitView" you mean Xamarin.Forms.MasterDetailPage and what you are trying to accomplish is to have the slide out menu close on selection of a menu item and bring the content page into full view then you might try this.


1)  handle the selected event in the code behind of the menu page 
2) set isPresented to false 
3)  publish a message to the ViewModel requesting a Navigation command 


private void Menu_ItemSelected(object sender, SelectedItemChangedEventArgs e)
        {
            NavigateTo(e.SelectedItem as MenuItem);
        }


 private void NavigateTo(MenuItem menuItem)
        {
            if (menuItem == null)
                return;
            try
            {
                //
                if (this.Detail.BindingContext != null)
                    this.Detail.BindingContext = null;
                //
                if(this.Detail.ToolbarItems != null)
                    this.Detail.ToolbarItems.Clear();
                //
                if (this.Detail.BackgroundImage != null)
                    this.Detail.BackgroundImage = null;
               
                //
                MessagingCenter.Send(menuItem.TargetView, "MasterDetailNavigationEvent");
                //
                IsPresented = false;
                //
              

            }
            catch (Exception ex)
            {
                Insights.Report(ex);
            }

        }

**Comment by brianlagunas** [comment]
Sorry for the late response.  Prism doesn't do anything special with the split view so you will have to manually close the pane.
