### ISSUE TITLE
Interaction Request : Custom Confirmation Possible Issue

### ISSUE THREAD

**Issue by toumir** [PrismLibrary/Prism#307]
Hi!
I'm trying to use a custom confirmation popup Window, But I use Confirmation Class provided by PRISM, and my own XAML. My issue is related to the Confirmed Property which is always false, (see attached Code)

1. from MainViewModel, the request is raised by
  private void RaiseConfirmation()
        {
            StatusConfirmation = string.Empty;
            // USING THE CLASS PROVIDED BY PRISM : Confirmation 
            ConfirmationRequest?.Raise(new Confirmation
            {
                Title = "My Title",
                Content = "My Content"
            },
            confirmation =>
            {
                if (confirmation.Confirmed) // <=====   HERE ??? always false ???
                {
                    StatusConfirmation = "Confirmed";
                }
                else
                {
                    StatusConfirmation = "Canceled";
                }
            });
        }

2. Behind Code of my View (which contains OK, and Cancel buttons)
 public partial class CustomConfirmation : IConfirmation, IInteractionRequestAware
    {
        public CustomConfirmation()
        {
            InitializeComponent();
        }

        public string Title { get; set; }
        public bool Confirmed { get; set; }
        public INotification Notification { get; set; }
        public Action FinishInteraction { get; set; }

        private void OnOk_Click(object sender, RoutedEventArgs e)
        {
            Close(true);
        }
        private void OnCancel_Click(object sender, RoutedEventArgs e)
        {
            Close(false);
        }
        private void Close(bool confirmation)
        {
            if (FinishInteraction != null)
            {
                this.Confirmed = confirmation;// <== When I  push the OK button it's true here (VERIFIED)
                FinishInteraction.Invoke();
            }
        }

    }

Thanks

Attached files below
[CustomConfirmation.xaml.cs.txt](https://github.com/PrismLibrary/Prism/files/36868/CustomConfirmation.xaml.cs.txt)
[CustomConfirmation.xaml.txt](https://github.com/PrismLibrary/Prism/files/36870/CustomConfirmation.xaml.txt)
[MainViewModel.cs.txt](https://github.com/PrismLibrary/Prism/files/36869/MainViewModel.cs.txt)
[MainWindow.xaml.txt](https://github.com/PrismLibrary/Prism/files/36871/MainWindow.xaml.txt)

**Comment by brianlagunas** [comment]
Please look at how the default confirmation window is done:

https://github.com/PrismLibrary/Prism/blob/master/Source/Wpf/Prism.Wpf/Interactivity/DefaultPopupWindows/DefaultConfirmationWindow.xaml.cs

As you can see, your implementation isn't quite right.  Your Window should not implement IConfirmation, but rather have a property that is the data context of the window.

**Comment by toumir** [comment]
thank you very much, it works!

**Comment by Timhilly** [comment]
Thanks, Brianlagunas! 
But waht if use MVVM? datacontext could not be set.

**Comment by brianlagunas** [comment]
If you are using MVVM, there will be a DataContext. That's how MVVM works.
