### ISSUE TITLE
[Feature Request] Add support Keyed Service for IServiceCollection

### ISSUE THREAD

**Issue by wangkewei111** [PrismLibrary/Prism#3088]
### Description

Microsoft.Extension.DependencyInjection has new  feature: Keyed Service from 8.0.0.
But  it is not supported in IServiceProviderExtensions.RegisterTypesWithPrismContainer .
Then it throw exception :" Your service provider may not support keyed services "
I suggest add some code  if "service.IsKeyedService".

### Steps to Reproduce

  

   containerRegistry.RegisterServices(collection => collection.AddKeyedSingleton())

### Platform with bug

WPF

### Affected platforms

Windows

**Comment by berhir** [comment]
I ran into the same issue today. We updated the package `Microsoft.Extensions.Http.Resilience` from v8.1.0 to v8.2.0 and suddenly the application crashed as startup with `'This service descriptor is keyed. Your service provider may not support keyed services.'`

**Comment by dansiegel** [comment]
If you are a Commercial Plus user this is now available starting with Prism.Container.DryIoc 9.0.92 or later.
Prism.Container.Microsoft already supports this.
