### ISSUE TITLE
Resolving with Unity works, not with DryIoc 

### ISSUE THREAD

**Issue by EuroEager2008** [PrismLibrary/Prism#3089]
### Description

I have an application using Prism with DryIoc.
(I have "privatized" a few identifiers and a file path)
One line in OnInitialized in a module looks like:
IMyService myService = containerProvider.Resolve<IMyService>()

Using DryIoc, this call throws an Prism.Ioc.ContainerResolutionException with the details shown in attachment.
[ExceptionDetails.txt](https://github.com/PrismLibrary/Prism/files/14403090/ExceptionDetails.txt)

By replacing DryIoc with Unity the call works just fine with the exact same code except the changed package reference.

I thought Prism is supposed to be 100% agnostic on the choice of Unity vs DryIoc (I chose DryIoc because Unity is perhaps no longer being maintained and it seems like Prism people recommands DryIoc over Unity).

### Steps to Reproduce

Currently I cannot describe repro steps.
I can send my solution privately if that is possible

### Platform with bug

WPF

### Affected platforms

Windows

### Did you find any workaround?

Using Unity instead of DryIoc seems to fix it (haven't tested many other aspects though)

**Comment by EuroEager2008** [comment]
By some strange reason (markdown?) my post did not include the type of service in angled-brackets (should be IMyService) describing the call that throws.

**Comment by dansiegel** [comment]
Bug reports must contain a reproduction.

**Comment by EuroEager2008** [comment]
Ok, I will try to make a repro (and attach files probably).
Do I have to make a new issue?
