### ISSUE TITLE
Hide the dialog box from the Windows Taskbar

### ISSUE THREAD

**Issue by frankwwu** [PrismLibrary/Prism#310]
I need a way to hide the dialog box from the Windows Taskbar. Functionally, it is like Window.ShowInTaskbar property.

**Comment by brianlagunas** [comment]
Have you tried using the WindowStyle property to set it?

**Comment by toumir** [comment]
I try to explain, after setting the property *ShowInTaskBar=false* to the window, i think there a issue of **blocking** (the case of the popup window when using interactions):
suppose we have more than one application running at the same time (ms word, visual studio,...) and our application with the popup window **showed**, when navigate to other application (such ms word) and try to come back to our application via click mouse in the **Task Bar icon**, then main window  (or the shell) will be showed but not the popup window until we press (alt+tab) to know there is popup window that block the application, i think you must set the owner of the popup window to the main window of the application(the shell).

**Comment by brianlagunas** [comment]
Yes, as I explained in our last conversation, the fix for setting the owner is in the current code base.  So, if you use the current code base and then set the ShowInTaskbar property using the WindowStyle does it work as expected?

**Comment by toumir** [comment]
thanks Brain, i will try this :+1:

**Comment by brianlagunas** [comment]
I tested this and it worked for me
