### ISSUE TITLE
Forms Navigation Samples

### ISSUE THREAD

**Issue by dhaligas** [PrismLibrary/Prism#311]
I would like to see some real world navigation samples using master detail and tabs with navigation pages.

**Comment by brianlagunas** [comment]
I am still working on the navigation service.  The current code base supports what you want.  You just have to call navigate from the MasterDetail ViewModel, and it will automatically update the MasterDetail.Detail property as expected.  The same goes for NavigationPage.  If you have a view that is a child of a NavigationPage, it will automatically call PushAsync.

This is the sample I am using to test various navigation scenarios as I work on it:  https://github.com/PrismLibrary/Prism/tree/master/Samples/Xamarin/HelloWorld

This is only available in the current repo, not in the public NuGet packages yet.

**Comment by dhaligas** [comment]
@brianlagunas does your sample allow setting the Detail of the MasterDetail to a NavigationPage?

I always set the root Detail Page as a navpage

**Comment by brianlagunas** [comment]
Yes.  Didn't you try it?

**Comment by dhaligas** [comment]
@brianlagunas i haven't had a chance yet .. was just reading the code in github to figure out how it works.  I want to use this lib b/c of the url navigation support for deep linking

**Comment by dhaligas** [comment]
@brianlagunas the example is not clear on how it sets the Detail to a NavigationPage since no nav bar is shown

**Comment by brianlagunas** [comment]
You need to play around with the sample and the various navigation scenarios you want.
