### ISSUE TITLE
[BUG] Popup Dialogs are hidden/covered by calling Page when called after returning from MAUI FilePicker

### ISSUE THREAD

**Issue by askariya** [PrismLibrary/Prism#3126]
### Description

If you are on Page A and call and await the FilePicker PickAsync function, and then open a Popup dialog, the Popup dialog will be covered by Page A.
This does not seem to occur with the MAUI Community Toolkit Popups, so I think this must be an issue within Mopups or the Prism Dialog Popups. 

### Steps to Reproduce

1. In a ViewModel, add a call to PickAsync() and follow it with a call to open a Popup Dialog:
`var fileData = await FilePicker.PickAsync();
result = await _dialogService.ShowDialogAsync(nameof(PopupNotificationDialog));`
2. Trigger the above call (ex: with a button press).
3. Select a file or back out such that the File Picker closes.
4. You will see that the popup does not appear and instead the Page you called from does.
5. If you repeat this in debug mode with breakpoints for each step you can see that the Popup does appear but is covered by the calling Page immediately.

### Platform with bug

.NET MAUI

### Affected platforms

Android

### Did you find any workaround?

No workaround, only solution I could find for this is to use Maui Community Toolkit popups instead.

**Comment by dansiegel** [comment]
a reproduction app is required for bug reports

**Comment by askariya** [comment]
Created a new bug with a reproduction app linked: https://github.com/PrismLibrary/Prism/issues/3164
