### ISSUE TITLE
[BUG] Link to Prism License T&C is wrong

### ISSUE THREAD

**Issue by munkii** [PrismLibrary/Prism#3129]
### Description

In the readme.md found here https://github.com/PrismLibrary/Prism/tree/master/src there is a link to the Terms and Conditions of the PRISM license

> How to Purchase Your License:
> 
> 1. Determine if you qualify for the Prism Community License by reviewing the criteria above.
> 2. If you qualify, make sure to read, understand, and agree to Prism's terms and conditions found in the [Prism License](https://prismlibrary.com/downloads/prism_license.pdf).
> 3. If you do not qualify for the Community License, visit the [Prism Library website](https://prismlibrary.com/) for commercial licensing options and further instructions.

The link to [Prism License] results in a 404

### Steps to Reproduce

1. Go To https://github.com/PrismLibrary/Prism/tree/master/src
2. Click the [Prism License] link

### Platform with bug

.NET MAUI

### Affected platforms

I was *not* able test on other platforms

**Comment by brianlagunas** [comment]
Fixed. Thanks for letting us know.
