### ISSUE TITLE
Prism for XF - Namespace issue when associating ViewModel to View

### ISSUE THREAD

**Issue by rdelrosario** [PrismLibrary/Prism#314]
Doesn't associate ViewModel to View if the namespace of View doesn't end with Views. 

Example:

Application.Views.Pages - Won't work.
Application.Views.XXX

If ends with Views such as:

Application.Views - Works just fine.

**Comment by brianlagunas** [comment]
Yes, this is the convention.  Don't worry, you can change the convention.  Check out this article.

http://brianlagunas.com/getting-started-prisms-new-viewmodellocator/

It's a little outdated, but most of it still applies.  Especially the part about changing the conventions.
