### ISSUE TITLE
[BUG] Region is not working on Maui when Rider Debugger is attached

### ISSUE THREAD

**Issue by albilaga** [PrismLibrary/Prism#3156]
### Description

Prism region is not working on MAUI. Even prism sample is not working when rider debugger is attached

### Steps to Reproduce

1. Open this project https://github.com/PrismLibrary/Prism/tree/master/e2e/Maui
2. Run in iOS and also android. It doesn't do anything when navigate to region

https://github.com/PrismLibrary/Prism/assets/2399099/cbfd626a-9bad-4040-af24-ecb229044792

1. I also tried in new project. Run this project https://github.com/albilaga/TestMauiMultiProject/tree/main in android or iOS
2. It should directly shown label with text `TestFromViewModel` but it doesn't show anything

### Platform with bug

.NET MAUI

### Affected platforms

iOS, Android

### Did you find any workaround?

Nope

**Comment by thisisthekap** [comment]
Experiencing the same thing.

**Comment by ramtechjoe** [comment]
I am having no issues with regions.  I even setup the test project (just iOS) and it seemed to work.
I do see that you call regionManager.RequestNavigate in the constructor.  This won't work because I believe the region is not fully constructed yet

**Comment by albilaga** [comment]
@ramtechjoe any reason then why the sample from prism also not working? and also what version do you use? I also change my project to run `RequestNavigate` in `OnAppearing` but still not working

**Comment by thisisthekap** [comment]
@ramtechjoe @albilaga @dansiegel I just found out that this is related to Rider Debugger. Works flawlessly without debugge attached.

**Comment by thisisthekap** [comment]
XAML Hot Reload is causing the issue in combination with Rider Debugger: https://youtrack.jetbrains.com/issue/RIDER-68161/Rider-Xamarin-MAUI-Debug-Regions-are-not-displayed-by-Application

So to my point of view, this is nothing the Prism team needs to worry about :)

**Comment by albilaga** [comment]
Looks like we can close this as this is rider issue instead of prism issue

**Comment by thisisthekap** [comment]
I filed a bug in the MAUI repository: https://github.com/dotnet/maui/issues/22900

**Comment by Axemasta** [comment]
I'm using Rider 2024.3.6 and regions are working with the debugger attached so this looks like it's been fixed!
