### ISSUE TITLE
[BUG] In some cases, my Dedug will suddenly get stuck

### ISSUE THREAD

**Issue by maonaoda** [PrismLibrary/Prism#3163]
### Description

It that a test code ?

https://github.com/PrismLibrary/Prism/blob/fbee72601ba4f3c2ba677cb255a9bcf76e3d7976/src/Maui/Prism.Maui/Navigation/NavigationRegistry.cs#L55-L58

### Steps to Reproduce

None

### Platform with bug

.NET MAUI

### Affected platforms

I was *not* able test on other platforms

**Comment by dansiegel** [comment]
Prism is not responsible for the .NET Tooling including the Debug experience. Please file an issue with Microsoft / the Visual Studio team if you are having issues.
