### ISSUE TITLE
[BUG] Wiring view models for pages in tabbed page are done by name 

### ISSUE THREAD

**Issue by bodeg** [PrismLibrary/Prism#3167]
### Description

I have view named `CompassPage` and its view model: `CompassViewModel`
and they are registered:

`containerRegistry.RegisterForNavigation<CompassPage, CompassViewModel>();`

When I `NavigateAsync` directly to the page - it works fine

`await NavigationService.NavigateAsync(nameof(CompassPage))`

When I navigate to a `TabbedPage` that hosts that view, the view is not wired with its view model.

Once I renamed the view model to `CompassPageViewModel ` (Page was added) - it works fine at the `TabbedPage`.

With regards. alon

### Steps to Reproduce

Please check the description above

### Platform with bug

.NET MAUI

### Affected platforms

Android

**Comment by dansiegel** [comment]
No reproduction
