### ISSUE TITLE
Prism 6.0 Supports Windows 10 Mobile?

### ISSUE THREAD

**Issue by suresh-s** [PrismLibrary/Prism#319]
We want to know if Prism 6.0 can be used in Windows 10 Mobile development.

Can you suggest how to use it? any Sample code available for Windows 10 Mobile ?

Is there any document available for Prism 6.0 (for Windows phone 10 development )?

regards,
S. Suresh

**Comment by bartlannoeye** [comment]
Windows 10 Mobile is the same platform as Windows 10, also known as Windows 10 Universal Windows Platform. This is supported by the [Prism.Windows](https://www.nuget.org/packages/Prism.Windows/) package, and currently has Unity and Autofac as supported IoC containers.

Code samples are available at https://github.com/PrismLibrary/Prism-Samples-Windows

We didn't have the time yet to write full documentation for Windows 10, but it's a port of [Prism for Windows Runtime](https://msdn.microsoft.com/en-us/library/windows/apps/xx130643.aspx), so you can read that documentation if wanted. It's best to keep the list of [breaking changes](https://msdn.microsoft.com/en-us/library/windows/apps/xx130643.aspx) in mind.

**Comment by suresh-s** [comment]
We want to migrate Windows phone 8 project to **Windows 10 Mobile**.  We are currently having Single project with MVVM architecture.    The project consist of 7 different features.   We want to segregate as 7 different modules while migration.

I can't find out **ModuleCatalog**, **Region**, **RegionManager**, **Shell** classes in Prism.Windows library.  

1. Why are these classes been removed?  

2. Is the Shell, Region and ModuleCatalog based Architecture not suitable for Windows 10 mobile projects?

3. Why should i use Prism 6.0 since "**Composite application from loosely coupled components**" is not supported? How can i create Composite application with different modules and components using Prism 6.0?

4. Should i create Infrastructure libraries "Module Catalog", "Module Loader", "Region Manager", "Logging", "Region Manager", "Region" and "Shell"  to create Composite application?

**Comment by briannoyes** [comment]
See my response to your other issue.
