### ISSUE TITLE
[BUG] CS8012 on publish net8.0-ios  

### ISSUE THREAD

**Issue by tibuprophen** [PrismLibrary/Prism#3190]
### Description

Recently, we upgraded our iOS and Android Maui App from Prism 8 to 9. After clearing out some changes, we've noticed that our ci pipeline for publishing is failing. After a short investigation, our pipeline failed due to a CS8012 thrown at `Prism.Maui`.
`CSC : warning CS8012: Die Assembly "Prism.Maui, Version=9.0.401.20976, Culture=neutral, PublicKeyToken=null", auf die verwiesen wird, hat einen anderen Zielprozessor. [/Users/tibo/temp/PrismTest/PrismTest.csproj::TargetFramework=net8.0-ios]`
_Sorry for german localization, but the issue should be clear._

I have also found the discussion topic here: https://github.com/PrismLibrary/Prism/discussions/3102 where other people recently discovered the same bug. 

The bug is not affecting android and debug buiilds are working e.g. on simulator. The build does not fail as long as no `TreatWarningsAsErrors` is set.

### Steps to Reproduce

1. `dotnet new maui -n PrismTest`
2. `cd PrismTest`
3. `dotnet add package Prism.DryIoc.Maui --version 9.0.401-pre`
4. For dotnet publish on ios, you may need a valid profile for an app identifier. So I changed the `ApplicationId` in `PrismTest.csproj` to an application I have a profile for installed.
5. Add prism usage in app e.g. by adding `.UsePrism(x => x.CreateWindow(y => y.CreateBuilder().AddSegment<MainPage>()))` at the end of the MauiAppBuilder in `MauiProgram.cs`
6. `dotnet publish --framework net8.0-ios`

### Platform with bug

.NET MAUI

### Affected platforms

iOS

### Did you find any workaround?

Because this is a warning, no workaround is required, unless you are using `TreatWarningsAsErrors`. Then add `<NoWarn>$(NoWarn);CS8012</NoWarn>` to the csproj. 

### Relevant log output

```shell
Determining projects to restore...
  "/Users/xxx/temp/PrismTest/PrismTest.csproj" wiederhergestellt (in 1,24 Sek.).
  Detected signing identity:
          
    Code Signing Key: "Apple Development: XXXX" (XXX)
    Provisioning Profile: "match Development xxxxx" (XXX)
    Bundle Id: xxx
    App Id: xxx
CSC : warning CS8012: Die Assembly "Prism.Maui, Version=9.0.401.20976, Culture=neutral, PublicKeyToken=null", auf die verwiesen wird, hat einen anderen Zielprozessor. [/Users/xxx/temp/PrismTest/PrismTest.csproj::TargetFramework=net8.0-ios]
  PrismTest -> /Users/xxx/temp/PrismTest/bin/Release/net8.0-ios/ios-arm64/PrismTest.dll
  Das Optimieren der Assembly für die Größe kann das Verhalten der App ändern. Stellen Sie sicher, dass nach der Veröffentlichung Tests durchgeführt werden. Informationen finden Sie unter https://aka.ms/dotnet-illink.
  Assemblys werden für die Größe optimiert. Dieser Vorgang kann eine Weile dauern.
  Created the package: bin/Release/net8.0-ios/ios-arm64/publish//PrismTest.ipa
```

**Comment by dansiegel** [comment]
This was fixed a long time ago

**Comment by DonkeyKongJr** [comment]
How was it fixed @dansiegel?

**Comment by DonkeyKongJr** [comment]
@dansiegel when was this fixed?

**Comment by dansiegel** [comment]
if I remembered that I wouldn't have just said a long time ago

**Comment by DonkeyKongJr** [comment]
Ok. I was just wondering since the error occurred with version “9.0.401” and AFAIK there wasn't a new version since.

**Comment by dansiegel** [comment]
Those with a Commercial Plus license had access to this quite a while ago. I believe it was shortly after 401 shipped. Keep in mind any bug fixes we do only get back ported for Commercial Plus users. Everyone else has to wait until we do a 9.1 preview publicly.

**Comment by DonkeyKongJr** [comment]
Thanks for clarification, I wasn't aware of that to be honest.

**Comment by dansiegel** [comment]
@DonkeyKongJr I would say that most companies are opting to go with the Commercial Plus license not only for all of the extras that you get but also because of the more frequent access to bug fixes. Public channels will be infrequently updated where the private channels are updated as soon as the CI finishes building as we merge fixes and features.
