### ISSUE TITLE
Create new XmlnsDefinition standard

### ISSUE THREAD

**Issue by brianlagunas** [PrismLibrary/Prism#32]
When Prism was in Microsoft's hands they used two XmlnsDefinitions:

XmlnsDefinition("http://www.codeplex.com/CompositeWPF", "namespace") -- original
XmlnsDefinition("http://www.codeplex.com/prism", "namespace") - this was meant to replace the original

Now, we should come up with a new schema that is not tied to the codeplex name.

We do have a domain "http://PrismLibrary.com", that has yet to have a site created.  So should we use this now?

XmlnsDefinition("http://prismlibrary.com/", "namespace")
XmlnsDefinition("http://www.prismlibrary.com/", "namespace") -- notice the addition of "www"

Other ideas?

**Comment by Michael-DST** [comment]
I like it.  My vote/preference would be without the www (seems sort of old skool and not as concise).  I also like the domain in general, as it leads towards a (wicked-short) suggested candidate "pl" prefix. :)

**Comment by brianlagunas** [comment]
Well since we don't have any components in the VS toolbox, we don't have to specify a default prefix.  If we did have a default prefix, say in our project and item templates I'll be creating, I would probably go with "prism".

**Comment by briannoyes** [comment]
Why not use its actual new home at github.com/prismlibrary?

**Comment by brianlagunas** [comment]
Well, do we want to tie the name to a source control vendor?  Even if we didn't own the actual domain name, http://prismlibrary.com/ would be specific to prism and not imply a method of source control.  What happens when the next great source control solution CleanSource is released?

**Comment by bartlannoeye** [comment]
I'm up for using the domain name as the new definition.

**Comment by briannoyes** [comment]
Fair point, since we own the domain and since it would make intellisense selection quicker, I vote for http://prismlibrary.com

**Comment by frogger3d** [comment]
Why not .net or .org, Prism is not commercial right?

**Comment by brianlagunas** [comment]
This has been complete.  I left the XmlnsDefinition("http://www.codeplex.com/prism", "namespace") definition in there for backwards compatibility.

**Comment by brianlagunas** [comment]
Having a .com doesn't mean it's a commercial product.  Lots of open source projects the use the .com domain alias (GitHub) since it is the most widely used and it's usually the first thing someone types when looking for a website.
