### ISSUE TITLE
[BUG] Different Navigation Result between NavigateAsync(String) or NavigateAsync(Uri) when using RelativeBack() or ".." as Segment

### ISSUE THREAD

**Issue by td-s3** [PrismLibrary/Prism#3214]
### Description

When u try to use a NavigationBuilder and use the function RelativeBack() followed by a Page. There is a difference in the NavigationStack if u use NavigateAsync() or convert the Builder Uri to string and NavigateAsync(navigationstring).

By Navigate via Uri the current Page is not popped off.
By Navigating via Navigation String is current Page is popped off.

I think the difference in those calls is, that PageNavigationService.RemovePageRelativePath ("../") is not replaced by PageNavigationService.RemovePageInstruction("__RemovePage/"), when calling NavigateAsync(Uri uri).

see INavigationServiceExtensions:
NavigateAsync(this INavigationService navigationService, string name, INavigationParameters parameters)

I hope this helps :)

### Steps to Reproduce

Create a Navigation Stack PageA > PageB

```
await NavigationService
                  .CreateBuilder()
                  .RelativeBack()
                  .AddSegment<PageC>()
                  .NavigateAsync();
```

Expected:

Navigation Stack PageA > PageC

Observed:

Navigation Stack PageA > PageB > PageC

### Platform with bug

.NET MAUI

### Affected platforms

Android, I was *not* able test on other platforms

### Did you find any workaround?

Use navigationBuilder.Uri.ToString() and use NavigateAsync(string)

**Comment by dansiegel** [comment]
You need to provide a working sample that reproduces the issue
