### ISSUE TITLE
[BUG] Pages remain in memory after absolute navigation and garbage collection

### ISSUE THREAD

**Issue by stevefriesen** [PrismLibrary/Prism#3218]
### Description

We are seeing used memory continue to increase and we are seeing old contentpage objects being held onto by the app after absolute navigation and garbage collection. We used the dotnet-gcdump tool to track memory usage and have created a simple app to verify the behavior. We created one app using Prism, a second app using the .Net Maui App Shell navigation, and a third app using .Net Maui NavigationPage. The Prism app does not release the contentpage objects.

The prism app that we created is located here: https://github.com/FamousSoftware/MauiPrismApp-MemLeak

Here is a summary of the logic:

![PrismAppMainPage](https://github.com/user-attachments/assets/545a738b-88b2-49fa-8aa5-dcec4598f0c6)
MainPageViewModel navigates to Page2: navigationService.NavigateAsync(nameof(Page2))
![PrismAppPage2](https://github.com/user-attachments/assets/95eb443b-f373-4153-ba2f-af8de68dbdab)
Page2ViewModel performs absolute navigation to MainPage: navigationService.NavigateAsync($"/{nameof(MainPage)}")
MainPageViewModel performs garbage collection: GC.Collect()
A memory dump is created using dotnet-gcdump. MainPage has multiple instances still in memory. MainPageViewModel has only a single instance in memory (because we have just navigated to this page). Page2 has instances still in memory. Page2ViewModel does not exist in memory.

Running similar apps using AppShell and NavigationPage result in only a single Page1 object and a single Page1ViewModel in memory. There are no Page2 objects left in memory.

### Steps to Reproduce

1. Set up the dotnet-gcdump tool for memory profiling for Android as described here: https://github.com/dotnet/maui/wiki/Memory-Leaks. The app I created, MauiPrismApp-MemLeak (in the GitHub repo mentioned above) is ready to go, but dotnet-gcdump also requires a few other steps as noted in their documentation.
2. Build the app in release mode and deploy to your device.
3. Start the dotnet-dsrouter for listening to local Android devices--run these commands from a command line:

- adb reverse tcp:9000 tcp:9001
- adb shell setprop debug.mono.profile '127.0.0.1:9000,nosuspend,connect'
- dotnet-dsrouter android
![Run-dotnet-dsrouter-android](https://github.com/user-attachments/assets/da1c1da9-baa2-4631-97ac-f097fcc96a21)

4. Start the app (with no other apps running on the tablet). 
5. When the app has opened on the Main Page (label at top says "Page 1"), take a baseline memory dump by calling from the command line "dotnet-gcdump collect -p [pid]" where pid is specified in the output text of the dotnet-dsrouter call.
6. Go back and forth a few times from MainPage to Page2, finally from Page2 click the button with text "Go To Page1 Clear Stack" which will do absolute navigation to Page1.
7. In Page1 (MainPage) click on the Collect Garbage button and wait a minute or so (or run Collect Garbage a couple times).
8. Do another memory dump by calling "dotnet-gcdump collect -p [pid]". 
9. Compare the two memory dump files in Visual Studio. Drop the last .gcdump file in Visual Studio and in the "compare with baseline" drop-down select the baseline .gcdump file. In the search at the top of the compare, you can search on Page2, and see that there are still instances of it in memory. 
![PrismAppMemoryDumpCompare-1](https://github.com/user-attachments/assets/e163a196-cb31-4251-8520-2973fd9ba8f0)

### Platform with bug

.NET MAUI

### Affected platforms

Android

### Did you find any workaround?

No

**Comment by dansiegel** [comment]
you're using an 8.1 version of Prism.Maui.
