### ISSUE TITLE
DelegateCommandBase - ObservesProperty raised from background thread throws InvalidOperationException

### ISSUE THREAD

**Issue by matthewethomas** [PrismLibrary/Prism#322]
When a DelegateCommand is explicitly subscribed to a property's INPC notification via the ObservesProperty method, updating the property on the background thread causes the command to invoke DelegateCommandBase's OnCanExecuteChanged() on a background thread as well.

This yeilds the InvalidOperationException with a message of "The calling thread cannot access this object because a different thread owns it."

I suggest wrapping the implementation of OnCanExecuteChanged in a call to Dispatcher.Invoke or Dispatcher.BeginInvoke

**Comment by brianlagunas** [comment]
Dispatcher is XAML specific and doesn't exist in other platforms like Xamarin.Forms.

**Comment by matthewethomas** [comment]
I see that the OnCanExecuteChanged method in DelegateCommandBase is virtual, it looks like I can just override it and get the functionality there?

**Comment by brianlagunas** [comment]
You can try.  This is an interesting scenario for sure.  I'm not sure how I would get around this in the DelegateCommandBase.

**Comment by matthewethomas** [comment]
What about grabbing a reference to SynchronizationContext.Current in the constructor and then Post'ing the event?

**Comment by brianlagunas** [comment]
A PR would be great :)

**Comment by tinyplasticgreyknight** [comment]
I've got a fix for this, just need to twiddle things to satisfy the unit tests a bit.  Looks like maybe xUnit sets up its `SynchronizationContext`s a bit differently from the old framework?  Anyway I'll get it sorted out.

**Comment by brianlagunas** [comment]
That would be awesome!

**Comment by brianlagunas** [comment]
Fixed!

**Comment by tinyplasticgreyknight** [comment]
Ah, perfect timing, things finally settled down over here and I was about to start looking at getting those tests finished for this!

I guess now I can have a relax instead B-)
