### ISSUE TITLE
Question: Native way to log binding Failures

### ISSUE THREAD

**Issue by devscott** [PrismLibrary/Prism#323]
I know I have spent countless hours tracking down data binding issues only to find it is the property name was spelt incorrectly.  Within Prism, is there a native way to log binding failures?

**Comment by zleao** [comment]
I know a way to log it to the VisualStudio output.In the XAML page declare the following namespace: `xmlns:diag="clr-namespace:System.Diagnostics;assembly=WindowsBase"`
after that, you can define the trace level of each binding you have:
`<Binding Path="YourProp" diag:PresentationTraceSources.TraceLevel="High" />`
Is this what you need?

**Comment by devscott** [comment]
@zleao Thanks, but doing this for every control seems like a nightmare and I really don't want diagnositcs stuff going into release

I know there are multiple ways to do this gloabally. 

In the past I have used the way Josh Smith [presented](https://msdn.microsoft.com/en-us/magazine/dd419663.aspx?tduid=%28ce2c35b987ffb699bedbe554bc7342db%29%28256380%29%282459594%29%28TnL5HPStwNw-dFvyqW8zJUleG4iG3rtxvQ%29%28%29) back in the day

```
// In ViewModelBase.cs 
[Conditional("DEBUG")] [DebuggerStepThrough] 
public void VerifyPropertyName(string propertyName) 
{ 
	// Verify that the property name matches a real, 
	// public, instance property on this object. 
	if (TypeDescriptor.GetProperties(this)[propertyName] == null) { 
		string msg = "Invalid property name: " + propertyName; 
		if (this.ThrowOnInvalidPropertyName) 
			throw new Exception(msg); 
		else Debug.Fail(msg); 
	} 
}

```

Recently I have moved to application wide chcecking by using System.Window.Diagnostics.PresentationTraceSources 

```
using System.Windows;
using System.Diagnostics;

namespace Foobar
{
    /// <summary>
    /// Interaction logic for App.xaml
    /// </summary>
    public partial class App : Application
    {
        protected override void OnStartup(StartupEventArgs e)
        {
#if DEBUG
            PresentationTraceSources.Refresh();
            PresentationTraceSources.DataBindingSource.Listeners.Add(new DebugTraceListener());
            PresentationTraceSources.DataBindingSource.Switch.Level = SourceLevels.Warning | SourceLevels.Error;
#endif
            FoobarBootstrapper bootstrapper = new FoobarBootstrapper();
            bootstrapper.Run();
        }
    }

    public class DebugTraceListener : TraceListener
    {
        public override void Write(string message)
        {
        }

        public override void WriteLine(string message)
        {
            Debugger.Break();
        }
    }
}
```

I was just wondering if Prism had something already built in.

**Comment by brianlagunas** [comment]
No, this is not a problem Prism tries to solve as this issue is related to the tooling around app development.

**Comment by briannoyes** [comment]
Any binding failure already logs to the output window in VS - look for the System.Data.Error messages - they tell you source and target object and property type that the binding is trying to resolve. The level that these are triggered is also customizable through Tools > Options > Debugging > Output Window >WPF Trace Settings.

So beyond that, as @brianlagunas said, not a problem Prism would try to solve. We try to make a framework to help people structure their code in a more maintainable, extensible, flexible way. We don't focus on writing development tooling for basic platform capabilities.

**Comment by devscott** [comment]
@briannoyes Thanks for pointing me to the Trace settings under Tools.
