### ISSUE TITLE
[BUG] Nuget error "Part URI cannot start with two forward slashes" when install Prism.Container.Abstractions 9.0.106.9543

### ISSUE THREAD

**Issue by nagneo** [PrismLibrary/Prism#3253]
### Description

In Visual Studio 2015, 
Error is occurred in nuget package manager when I installed Prism.Container.Abstractions. 
I can not see the installed nuget package list in my project like below captured images.

https://github.com/NuGet/NuGetGallery/issues/8950

![스크린샷 2024-09-12 121159](https://github.com/user-attachments/assets/26d7cee7-9786-479b-9253-bb74a5725837)
![스크린샷 2024-09-12 121133](https://github.com/user-attachments/assets/87b96988-6dd5-4d29-ac1d-5f0ef698b32e)

### Steps to Reproduce

1. Create WPF Project in Visual Studio 2015.
2. Install Prism.Core latest version 9.0.537
3. Check the list of nuget package manger
4. Click Show errors in output. "Part URI cannot start with two forward slashes."

### Platform with bug

WPF

### Affected platforms

Windows

**Comment by brianlagunas** [comment]
Does your project build? The output window seems to indicate that it does.

Does it happen if you switch to using PackageReferences instead of the old packages.config?

**Comment by nagneo** [comment]
Yes, the build succeeded for this project, but the code isn’t actually using Prism.Container.Abstractions—it's just imported. Do I need to do anything additional to ensure that it’s been imported correctly?

I’m unable to install Prism.Unity because of the following error: “An error occurred while retrieving package metadata for 'Prism.Container.Abstractions.9.0.107' from source 'D:*\TestApplication\packages'.”

Visual Studio 2015 doesn’t support the PackageReferences option, which is only supported in VS2017 and later. In Visual Studio 2022, however, there are no build or NuGet package errors; everything works fine.

In my real project, where I’m testing the migration to Prism 9 in VS2015, I’m encountering a build error similar to the one in [GitHub Issue #3235.](https://github.com/PrismLibrary/Prism/issues/3235.)

Should I consider upgrading to Visual Studio 2022 to successfully migrate to Prism 9?

**Comment by dansiegel** [comment]
Personally I would suggest that you use VS2022 out of good practice. There is no way that we can or will test older versions of Visual Studio. If you have some weird hard requirements that force you to use an older version I would suggest opening a ticket with Microsoft.
