### ISSUE TITLE
IRegion's ItemMetadataCollection items names are always null

### ISSUE THREAD

**Issue by rotacioskapa** [PrismLibrary/Prism#3254]
### Description

Using the IRegion.GetView(name) will always return null

### Steps to Reproduce

use _regionManager.RegisterViewWithRegion, then check the ItemMetadataCollection 

### Platform with bug

WPF

### Affected platforms

Windows, I was *not* able test on other platforms

**Comment by brianlagunas** [comment]
Closing until a reproduction app is provided.
