### ISSUE TITLE
[BUG] <title> Tabs doesn't bind ViewModels

### ISSUE THREAD

**Issue by Vunda** [PrismLibrary/Prism#3269]
### Description

When I navigate to CustomTabsPage (without builder). Prism didn't bing viewModels to Tabs.

Attach the sample: 
[MauiPrismTabs.zip](https://github.com/user-attachments/files/17557408/MauiPrismTabs.zip)

### Steps to Reproduce

1. Crate project
2. Create Tabs page with pages
5. Create ViewModels for pages.
6. Add Prism.DryIoc.Maui package (version: 9.0.537)
7. Configure Prism
8. Register pages and view models for navigation
9. Set MainPage as TabsPage

### Platform with bug

.NET MAUI

### Affected platforms

Android, I was *not* able test on other platforms

**Comment by dansiegel** [comment]
This is not a bug. There has been a change in behavior from Xamarin.Forms to .NET MAUI. You either need to set the VML to Force on the tabs or you can drop a TabbedPage that you actually don't need in your code and simply do:

```cs
navigationService.NavigateAsync("TabbedPage?createTab?NavigationPage%2FViewA&createTab=NavigationPage%2FViewB");
```

Or you can use the Navigation Builder which also lets you use ViewModel first Navigation

```cs
navigationService.CreateBuilder()
  .AddTabbedSegment(tp => tp
    .CreateTab(tab => tab.AddNavigationPage().AddSegment<ViewAViewModel>())
    .CreateTab(tab => tab.AddNavigationPage().AddSegment("ViewB")))
  .NavigateAsync()
```

**Comment by Vunda** [comment]
I saw and tested it works. But with your API I cannot customize Tabs or use handlers.

**Comment by dansiegel** [comment]
Also I almost forgot you could also this without Prism APIs by just applying it globally in a style:
```xml
<Setter Property="android:TabbedPage.ToolbarPlacement" Value="Bottom" />
```
