### ISSUE TITLE
Add support in PRISM for setting header of TabControl

### ISSUE THREAD

**Issue by tiesmaster** [PrismLibrary/Prism#327]
When you host a region in a `TabControl`, the views and view models that are in the region don't have control over the header text. I would like PRISM to have support for this out of the box.

I know @brianlagunas discussed in his excellent Pluralsight Course ("Prism Problems & Solutions: Mastering TabControl"), that you can easily set the header text of a TabControl using a style. Even though, that is a very simple solution to the problem, I do think it has some downsides: (1) you always need to customize all the `TabControl`s that you use with a custom style, which leads to code duplication, and (2) it is "untyped", there is nothing in the view or view model stating that it's participating in being hosted in a TabControl.

We have a [behavior](https://gist.github.com/tiesmaster/cf9e808e744e8f0cc2f4#file-regionhostedintabcontrolawarebehavior-cs) that enables a view model to be ["region hosted in TabControl"-aware](https://gist.github.com/tiesmaster/cf9e808e744e8f0cc2f4#file-iregionhostedintabcontrolaware-cs)
so you can implement that, and give the view model that information back to PRISM, similar to how IActiveAware works, and all of its friends. 

Could this be part of PRISM?

**Comment by brianlagunas** [comment]
Thanks for the idea, but this is not something we will be adding to Prism.  You don't need to customize all the TabControls you use.  Only the TabCOntrols being used as a region.  Also, there really isn't any code duplication, you can create one style and use it for every TabControl that is a region, thus reusing that style across your application.  Yes, it is untyped, by that is the nature of binding in WPF in general.

I think your behavior is a great approach to simplifying things for you, but the interface members are too limiting for mass usage.  For one, TabItem.Header is of type object, so not just text can go in there.  This implementation would limit that and would actually reduce functionality which is not something we want to do.

I think leaving it as-is would be the best option as it leaves it wide open for the developer to choose how they want to implement it to fit their application requirements.

**Comment by weitzhandler** [comment]
Hi guys, could you please share an example?

I'm using a `TabControl` as a named region, when the views are navigated to, the title isn't loaded. Here's what I've tried:

<TabControl 
  ...
  prism:RegionManager.RegionName="{x:Static common:Constants.AdminRegion}">
  <TabControl.Resources>
    <Style TargetType="{x:Type TabItem}">
      <Setter Property="Header" Value="{Binding DataContext.Title, Source={RelativeSource Self}}"/>
      
      <Setter Property="Header" Value="{Binding Title}"/>
    </Style>
  </TabControl.Resources>
</TabControl>

**Comment by tiesmaster** [comment]
@weitzhandler The style that Brian Lagunas uses in his Pluralsight course can be found in the excercise files of his course. If you have that, you can check the complete example out there, but basically, it's this:

````xaml
<Style TargetType="TabItem">
    <Setter Property="Header" Value="{Binding DataContext.Title}" />
</Style>
````

So you were almost there ;)

I've also pasted the source for `ViewModelFromViewExtractor` into [the gist](https://gist.github.com/tiesmaster/cf9e808e744e8f0cc2f4#gistcomment-2279624), so that should be sufficient to reproduce the solution as I use it in my app (still today ;)). If you don't get it working, I can create an example for you, but probably the style should be sufficient to get it working for you. And is also simpler anyhow ;)

**Comment by weitzhandler** [comment]
@tiesmaster thanks for sharing, that worked!
Maybe you can help me with [this issue](https://prismlibrary.slack.com/archives/C2R4418HY/p1512712859000194?thread_ts=1512696182.000087&cid=C2R4418HY) too.

**Comment by weitzhandler** [comment]
And BTW, maybe there is a way to include some title data in the navigation service journal, so we can show the breadcrumbs etc.
I'll look into it, but currently tab header is enough for me now.

**Comment by tiesmaster** [comment]
Sorry, I don't have an account on that Slack workspace, and don't want one. We're moving away from WPF, in favor of a web frontend written in React. So there is no value for me to get involved more than I am now.

Having that said, I'm happy to answer a stackoverflow question, if you have one ;)

**Comment by Kumar2Harsh** [comment]
i want to open child window from MainWindow where child window having region where we can navigate
how to do that using Prism in WPF?

**Comment by weitzhandler** [comment]
@Kumar2Harsh use page not window. and learn about region navigation [here](http://prismlibrary.github.io/docs/wpf/legacy/Navigation.html#prism-region-overview).

**Comment by Kumar2Harsh** [comment]
@weitzhandler thank's  i will have a look at this
