### ISSUE TITLE
[BUG] Changing CultureInfo in the maui app is ignored.

### ISSUE THREAD

**Issue by fbsyntactix** [PrismLibrary/Prism#3270]
### Description

In our MAUI app, you have the option of changing the language within the app.
When changing the language, a new CultureInfo is generated and set as follows:

```cs
_culture = Localize.GetCurrentCultureInfo(); // returns a CultureInfo based on the user-selected language.

CultureInfo.DefaultThreadCurrentCulture = _culture;
CultureInfo.DefaultThreadCurrentUICulture = _culture;
Thread.CurrentThread.CurrentCulture = _culture;
Thread.CurrentThread.CurrentUICulture = _culture;
CultureInfo.CurrentCulture = _culture;
CultureInfo.CurrentUICulture = _culture;
TextResources.Culture = _culture; // used for text translations in the app
Languages.Culture = _culture; // used for text translations in the app
```

Immediately after setting the CultureInfo, I log this: (In this example, the language was set from German to English)
`I DOTNET  : Updated Culture to ->                        en (TwoLetterISOLanguageName: en)`
`I DOTNET  : CultureInfo.CurrentCulture:                  en (TwoLetterISOLanguageName: en)`
`I DOTNET  : CultureInfo.CurrentUICulture:                en (TwoLetterISOLanguageName: en)`
`I DOTNET  : Thread.CurrentThread.CurrentCulture:         en (TwoLetterISOLanguageName: en)`
`I DOTNET  : Thread.CurrentThread.CurrentUICulture:       en (TwoLetterISOLanguageName: en)`

If the user then calls up another page of the app where texts are translated using the CultureInfo, the texts were still displayed in the previous language. (i.e. in English and not in German, although the language was set to German)
I therefore also extended the log at this point and saw the following:
`I DOTNET  : CultureInfos for displaying filter values:`
`I DOTNET  : Localize.GetCurrentCultureInfo()             de (TwoLetterISOLanguageName: de)`
`I DOTNET  : CultureInfo.CurrentCulture:                  en (TwoLetterISOLanguageName: en)`
`I DOTNET  : CultureInfo.CurrentUICulture:                en (TwoLetterISOLanguageName: en)`
`I DOTNET  : Thread.CurrentThread.CurrentCulture:         en (TwoLetterISOLanguageName: en)`
`I DOTNET  : Thread.CurrentThread.CurrentUICulture:       en (TwoLetterISOLanguageName: en)`

Only our own service returns the correct CultureInfo, because the service stores the selected language and then generates a CultureInfo (**_Localize.GetCurrentCultureInfo();_**)
The direct queries of the CurrentCulture/CurrentUICulture return the previous CultureInfo and the texts are therefore not displayed in the selected language.

I have already executed the entire code of setting the CultureInfo also additionally on the MainThread (**_MainThread.BeginInvokeOnMainThread_**), but this has not changed anything.

In the following StackOverflow article, it is recommended to reinitialize the application after setting the CultureInfo:
(Unfortunately, I have not found a way to implement this with Prism.)
[https://stackoverflow.com/a/76668182](https://stackoverflow.com/a/76668182)

Is there such a possibility with Prism?

Or is there another way to ensure that the manually set CultureInfo is kept?

### Steps to Reproduce

1. Setting the CultureInfo to a different language at one point
2. Check the CultureInfo at another point (i.e. in another navigated site)

### Platform with bug

.NET MAUI

### Affected platforms

iOS, Android

### Did you find any workaround?

I could pass the CultureInfo from my own service for all translation calls, which would be correct in any case.
However, this would only help for the translations, all other places or other controls that access the CultureInfo would not work correctly. (formatting dates and times, formatting numbers and currencies, etc.)

**Comment by dansiegel** [comment]
Prism has no direct impact on CultureInfo/Localizations. Please open this with the .NET MAUI team
