### ISSUE TITLE
[BUG] <title>

### ISSUE THREAD

**Issue by BruceLeeCorner** [PrismLibrary/Prism#3277]
### Description

Hi, dear guys,

I try to do this : ` _eventAggregator.GetEvent<AppConfigChangedEvent>().Publish();` 
But `appConfigSource.GetConfig();` doesn't  execute  if my ViewModel like the following :

```C#
public MainWindowViewModel( IEventAggregator eventAggregator, AppConfigSource appConfigSource)
{
    _eventAggregator = eventAggregator;
    _appConfigSource = appConfigSource;
    _eventAggregator.GetEvent<AppConfigChangedEvent>().Subscribe(() =>
    {
           appConfigSource.GetConfig();
    });
}
```

modify little to like this, It can work.

```C#
public MainWindowViewModel( IEventAggregator eventAggregator, AppConfigSource appConfigSource)
{
    _eventAggregator = eventAggregator;
    _appConfigSource = appConfigSource;
    _eventAggregator.GetEvent<AppConfigChangedEvent>().Subscribe(() =>
    {
           _appConfigSource.GetConfig();
    });
}
```

**Lambda Can't use  method parameter `appConfigSource`,  and have to use field `_appConfigSource`**.

I try debug prism source code ,find this :

![image](https://github.com/user-attachments/assets/51c63654-869a-4068-87e4-da4da6e25f4e)

is this a bug, please ? thank you.

### Steps to Reproduce

none

### Platform with bug

WPF

### Affected platforms

Windows

**Comment by BruceLeeCorner** [comment]
I use Prism.DryIoc 8.1.97

**Comment by dansiegel** [comment]
1) You need to be on Prism 9, we do not support older releases than the current release without an Enterprise Support Contract
2) It is required to provide a working sample that reproduces your issue. While we are happy to help, we do not have time to recreate apps to attempt to reproduce the errors you experience. Also it is very common that when creating a simplified sample to reproduce the issue you will often discover the answer to what you are doing wrong.
