### ISSUE TITLE
DryIOC support (Xamarin)

### ISSUE THREAD

**Issue by robertbaker** [PrismLibrary/Prism#328]
DryIOC is the fastest IOC for .Net, it should be supported!

**Comment by bartlannoeye** [comment]
It's easy to implement the IoC container of your choice with Prism, you can look at the Unity implementation as a guidance. Feel free to submit a PR.

**Comment by brianlagunas** [comment]
This isn't something I plan on doing anytime soon.  I suggest submitting a PR of just adding support into your specific project.

**Comment by joacar** [comment]
I am working on this and currently Brian is looking into how to test custom Xamarin application (subclassibg Xamarin.Forms.Application) without introducing compiler directives.

There is one thing I am trying to resolve with the creator of DryIoc and that is how to resolve a base class, when registered as derived using named service, with constructor arguments. I will inform you once it is ready
