### ISSUE TITLE
Prism.Windows - OnGoBackRequested handler should honor e.Handled

### ISSUE THREAD

**Issue by briandunnington** [PrismLibrary/Prism#329]
If I have a custom handler that handles the back navigation, the handler in PrismApplication.cs should honor that value and not try to process the event. Since the method is private, it is not easy to override.

**Comment by bartlannoeye** [comment]
So you got an extra custom handler attached to the DeviceGestureService as well? This means both handlers will trigger, and are executed in the order they are registered (if this didn't change in UWP). This means that the Prism handler will be executed before yours and that e.Handled will always be false. Am I correct?

Can you share some more info on what you're trying to achieve, so we can see how to solve this?

**Comment by brianlagunas** [comment]
Since there has been no reply, I am closing this issue.
