### ISSUE TITLE
[BUG] ViewModel AutoWire Problem

### ISSUE THREAD

**Issue by AhmedAdelGadElkareeem** [PrismLibrary/Prism#3291]
### Description

 .NET MAUI Project >> .NET 9.0

**Steps to Reproduce**
**1- create .NET Maui app
2- then install Prism.Maui nuget
3- register view for navigation
4- try to auto wire view with view model**

**I used Prism.Maui version 9.0.537**

**I am facing an issue where the Initialize method in the ViewModel is not being called.**

```
public class HomePageViewModel : ViewModelBase, IInitialize
{
      async public void Initialize(INavigationParameters parameters)
      {
          try
          {
              await LoadMessage();
          }
          catch { }
      }
}
```

in my xaml

```
xmlns:prism="http://prismlibrary.com"
prism:ViewModelLocator.AutowireViewModel="Forced"
```

or 

```
xmlns:prism="http://prismlibrary.com"
prism:ViewModelLocator.AutowireViewModel="Automatic"
```

and if i don't auto wire view model , still the same problem

```
 public App()
    {
            InitializeComponent();
    }
    protected override Window CreateWindow(IActivationState? activationState)
    {
        return new Window(new HomePage());
    }
}
```

and in maui program 

 ```
    public static MauiApp CreateMauiApp()
        {
            var builder = MauiApp.CreateBuilder();
            builder
                .UseMauiApp<App>()
                .UseMauiCommunityToolkit(options =>
                {
                    options.SetShouldEnableSnackbarOnWindows(true);
                })
                .UseSegmentedControl()
                .UseCardsView()
                .ConfigureMopups()
                .UseFFImageLoading()
                .ConfigureFonts(fonts =>
                {
                 
                })
                .UsePrism(prism =>
                       prism.ConfigureModuleCatalog(moduleCatalog =>
                       {
                       })
                       .RegisterTypes(containerRegistry =>
                       {

                        containerRegistry.RegisterForNavigation<HomePage, HomePageViewModel>();

                       }).OnInitialized(container =>
                       {
                           System.Globalization.CultureInfo.CurrentCulture = new System.Globalization.CultureInfo("ar-SA");
                           AppResources.Culture = System.Globalization.CultureInfo.CurrentCulture;
                       })
                   );

#if DEBUG
            builder.Logging.AddDebug();
#endif
            return builder.Build();
        }
```

### Steps to Reproduce

1- create .NET Maui app 
2- then install Prism.Maui nuget 
3- register view for navigation
4- try to auto wire view with view model

### Platform with bug

.NET MAUI

### Affected platforms

iOS, Android, Windows

**Comment by AhmedAdelGadElkareeem** [comment]
@dansiegel i already wrote a sample reproducing the issue
![sample](https://github.com/user-attachments/assets/d3e7a26e-aee8-45cb-b871-db5fb015d86a)

**Comment by brianlagunas** [comment]
@AhmedAdelGadElkareeem That's not a sample. Those are code snippets. We require a sample that we can run and debug.

**Comment by AhmedAdelGadElkareeem** [comment]
@brianlagunas @dansiegel here you are code sample
[PrismDemo.zip](https://github.com/user-attachments/files/18090228/PrismDemo.zip)

**Comment by brianlagunas** [comment]
You're not using Prism navigation so none of those interfaces will be invoked.

**Comment by brianlagunas** [comment]
I would start here: https://docs.prismlibrary.com/docs/platforms/maui/index.html

**Comment by dansiegel** [comment]
more specifically you might look here:
https://docs.prismlibrary.com/docs/platforms/maui/appbuilder.html#createwindow

**Comment by AhmedAdelGadElkareeem** [comment]
@brianlagunas @dansiegel thanks for your support , the problem solved by using PrismAppBuilder 
from here

https://docs.prismlibrary.com/docs/platforms/maui/appbuilder.html#createwindow
