### ISSUE TITLE
Trigger right (or all) build on submitting a PR

### ISSUE THREAD

**Issue by bartlannoeye** [PrismLibrary/Prism#336]
I noticed on the readme page that we now have 4 builds running for Prism. However when a PR is submitted, only the WPF solution is built, which can give false positives/negatives when e.g. XF code is checked in.

I'm not sure if AppVeyor is smart enough to trigger the correct build(s) depending on which folder has changes committed (like TFS can do)? Otherwise we should maybe just trigger all 4?

**Comment by brianlagunas** [comment]
This is not 100% correct. There is a build for each of the four solution files (not including the PrismLibrary.sln) that occur anytime a PR is submitted, regardless of what file changed.  So any time something is checked in, all four projects get rebuilt.

**Comment by bartlannoeye** [comment]
For some reason I only see the WPF project in the output:
https://ci.appveyor.com/project/brianlagunas/prism-jy368/build/1.0.401

**Comment by brianlagunas** [comment]
I don't know why AppVeyor only shows the WPF project, but there is also a build for the UWP project here:

https://ci.appveyor.com/project/brianlagunas/prism-gv1t3/build/1.0.15
