### ISSUE TITLE
Restore Silverlight support

### ISSUE THREAD

**Issue by iskiselev** [PrismLibrary/Prism#34]
Prism 4 had Silverlight support that was dropped with Prism 5.
It will be not very hard to restore its support. We need for it:
- Enable Silverlight 5 on Prism (Portable) project settings.
- Add reference to Microsoft Async nuget package.
- Resolve little api difference in working with Type/TypeInfo and some other types (there will be total 6 files with few changed lines)
- Add new project - something like Prism.TypeForwarder, that will define System.Windows.Input.ICommand type. We will need prepare three different implementations of this project - one for design time and two for Silverlight/NonSilverlight which will have TypeForwardedToAttribute with redirection to proper assembly.

If there is any chance that it will be accepted, I'll prepare PR for review.

**Comment by bartlannoeye** [comment]
If I remember correctly, the Async nuget package changes the msbuild files. Personally I'd like to keep that out of the general Prism PCL used by all environments (and limit only to SL). Some of our team members have had issues with it in the past.

Are there any alternative approaches we could consider?

**Comment by brianlagunas** [comment]
The effort to do this and support SL may not be worth it.  Besides getting the code ported, and all the tests in place we would also have to answer support questions regarding SL.  I'm not sure this is something worth the time and effort considering the fate of SL.

If this was to be done, most likely we would use linked files.  We would definitely not put in a number of dependencies and new projects just to support SL.

**Comment by Michael-DST** [comment]
As an aside here, (and from what I understand) linked files are being replaced with Shared Projects (.shproj) going forward.  This is something that should be considered for the main Prism solution if possible/needed/encountered.  Their support in VS2013 is a little lacking ([but accounted for](https://visualstudiogallery.msdn.microsoft.com/315c13a7-2787-4f57-bdf7-adae6ed54450)).   However, they are getting [1st-class support in VS2015](http://www.c-sharpcorner.com/UploadFile/7ca517/shared-project-an-impressive-features-of-visual-studio-201/).

As for SL, I personally think it would be cool to see it supported in some fashion, maybe in an unofficial fork somewhere?  If there is enough support/energy around it to bring it into the official repo, that would be cool, too.  Personally, I have said my goodbyes to SL but a part of me would like to see it continue however possible (I still think SL5 is the best tech MSFT has ever released to date!).

**Comment by iskiselev** [comment]
I'm not sure what will be better to use - file links or Universal projects. Universal projects is not yet used in Prism - but possible it is a good time to start usage of them.
I've started my fork with example how it may looks - https://github.com/iskiselev/Prism/tree/Silverlight.

**Comment by davidezordan** [comment]
I agree with Brian about Silverlight support. I don't think it's worth the time and effort for supporting it at this stage.
Silverlight projects should continue to use Prism version 4 imo.

**Comment by CaioProiete** [comment]
+1 agree with @brianlagunas. Not worth the effort.

**Comment by tomcrusader** [comment]
We're using Prism 4 with SL5 without issues

**Comment by brianlagunas** [comment]
Frankly, this isn't going to happen.  As other members have commented, you will have to either create your own port to take advantage of the new Prism 6 features, or continue to use Prism 4.1 for Silverlight projects.
