### ISSUE TITLE
Xamarin.Forms navigate reset main page

### ISSUE THREAD

**Issue by dhaligas** [PrismLibrary/Prism#343]
@brianlagunas how do we reset the main page using the navigation service? 

for example logging out and resetting the main page to the login page.

or the ability to PopToRoot

**Comment by dhaligas** [comment]
@brianlagunas 

The NavigationService needs on NavigateTo the option to PopToRoot 
and 
NavigateToRoot() which will reset the MainPage

**Comment by brianlagunas** [comment]
In the current preview there is no support for this.  In the current code base, you would use an absolute URI to replace the MainPage and essentially remove and replace the current modal/navigation stack.  I will be pushing another preview with this update in it soon.

I will think more about the PopToRoot scenario.  Can you add another issue specifically for PopToRoot?

**Comment by dhaligas** [comment]
@brianlagunas so we have many cases where we navigate deep in the stack and give the users a home button to get back to the root were they started from

**Comment by brianlagunas** [comment]
What is where they started from?  Is it the App.MainPage?

**Comment by dhaligas** [comment]
depends .. in our current case we have a MasterDetailPage where the Detail is set to a new NavigationPage when picking a menu item from the Master Page.  Then the user can nav deep and we PopToRoot on the navigation page that the Detail is set to

**Comment by dhaligas** [comment]
@brianlagunas as I understand it from the samples this is how I get a Nav page setup

NavigationService.Navigate ("MainNavigationPage/DashboardPage");

But how to I set a new Nav Page to the Detail on MasterDetailPage?

**Comment by brianlagunas** [comment]
Navigate("MasteDetail/Detail")

For example; if you wanted to have a MasterDetailPage as your App.MainPage followed by a default NavPage as the detail that navigated async to another ContentPage it would be like this:

Navigate("MasterDetail/NavigationPage/ViewA");

**Comment by dhaligas** [comment]
ok .. how would I represent that if I wanted to deep link to that path using app links?

**Comment by brianlagunas** [comment]
What do you mean "app links"?  Do you mean you are launching the app via a website using a URI?

If so, you would navigate to an absolute URI like this:

Explicit
Navigate(new Uri("android-app://MyAppName/MasterDetail/NavigationPage/ViewA", UriKind.Absolute));

Implicit
Navigate("android-app://MyAppName/MasterDetail/NavigationPage/ViewA");

**Comment by dhaligas** [comment]
I am referring to deep linking from emails or sms into the app 

https://dev.branch.io/recipes/branch_universal_links/#configure-developerapplecom

**Comment by brianlagunas** [comment]
Yup, in that case just navigate to your URI on Startup.  I'm about to publish a new Preview that has the absolute uri support in it right now.  Check for an update in about 5 minutes

**Comment by dhaligas** [comment]
sweet thanks .. the uri nav is a game changer .. keep up the good work

**Comment by brianlagunas** [comment]
New packages have been published.  Check out this sample for how to setup your app now.  I will update the official samples soon.

**Comment by dhaligas** [comment]
Link to the sample?

**Comment by brianlagunas** [comment]
It's in my comment above :)

**Comment by dhaligas** [comment]
Thanks it didn't show up in my email

**Comment by hetzlefetz** [comment]
Try navigating using "../YourDashboard". This way the login page should be
removed from the stack if I understood the feature correctly
