### ISSUE TITLE
AutoWireViewModel throws ImportCardinalityMismatchException?

### ISSUE THREAD

**Issue by znakeeye** [PrismLibrary/Prism#346]
What am I missing if I get this error at startup? It's a MEF application with auto-wiring of the viewmodel...

```
xmlns:prism="http://prismlibrary.com/"
prism:ViewModelLocator.AutoWireViewModel="True"
```

**Exception thrown:** 'System.ComponentModel.Composition.ImportCardinalityMismatchException' in System.ComponentModel.Composition.dll
An unhandled exception of type 'System.ComponentModel.Composition.ImportCardinalityMismatchException' occurred in System.ComponentModel.Composition.dll
Additional information: No exports were found that match the constraint: 
	ContractName	Microsoft.Practices.ServiceLocation.IServiceLocator
	RequiredTypeIdentity	Microsoft.Practices.ServiceLocation.IServiceLocator

**Comment by brianlagunas** [comment]
Try making this change:

```
protected override void ConfigureContainer()
{
    base.ConfigureContainer();

    ViewModelLocationProvider.SetDefaultViewModelFactory(viewModelType =>
       Container.GetExports(viewModelType, null, null).Value);
}
```

**Comment by znakeeye** [comment]
I have that, except that I call `First()`:

```
protected override void ConfigureContainer()
{
	ViewModelLocationProvider.SetDefaultViewModelFactory(viewModelType =>
		Container.GetExports(viewModelType, null, null).First().Value);
}
```

**Comment by brianlagunas** [comment]
Honestly, I don't know anything about MEF.  I never use it because it isn't a container, and I don't need the plugin support that MEF provides.  You're not the only one that runs into this regardless of using ViewModelLocator or not.

http://stackoverflow.com/questions/18890651/mef-throws-exception-importcardinalitymismatchexception

I would recommend just googling the MEF exception and see what you find.

**Comment by brianlagunas** [comment]
Do you have a simple sample that will reproduce your issue to share?

I'm closing this because it's not an issue, but I still want to help you figure it out so feel free to post a link to your sample for me to look at.
