### ISSUE TITLE
New WindowRegionAdapter

### ISSUE THREAD

**Issue by Qwin** [PrismLibrary/Prism#348]
Hi all,

Just wanted to let you guys know that I have been using this : http://southworks.com/blog/2008/09/26/windowregionadapter-for-compositewpf-prism/
for a while.

Can we add this to the wpf prism framework ? 

Thanks,
Robert

**Comment by brianlagunas** [comment]
Thanks for that.  I have seen that before, but I vaguely remember issues with it when trying to show multiple instances.  Have yo run into that?  We would probably have to think how we would introduce automatically scoping that type of region.

**Comment by Qwin** [comment]
Yeah so what I did, I customized it to create a new Region Manager for each window. (I actually just copied there code and customized it instead of using it as is) I created an extension for the root RegionManager with a static list that has all regionmanagers with unique guid to identify it. Also I added a property where I can check (after loaded event has been fired) if I am in a popout view. Because sometimes the same view can be in the main window as well as in a popout. The differentiation seems to be very important when creating complex applications. Other then that it seems easy to customize this class to your liking's.

**Comment by brianlagunas** [comment]
Yeah, the need for those type of customizations for production apps do not make it a good candidate to include in the source code, but we are eventually going to start a "How To" section in our docs where we can start documenting these types of things.  We haven't really figured out exactly how we want to do this, but it is something we are thinking about.
