### ISSUE TITLE
PubSub Events

### ISSUE THREAD

**Issue by drcarver** [PrismLibrary/Prism#35]
I would really like to see the PubSubEvent maintained as it's own library rather then rolling it into a common Prism library.  There are times when this component is very useful on its own with out anything else.  My current project is a good example.  They are very sold on the Prism event model but have no need for the rest of Prism.  This is definitely the case in services

**Comment by brianlagunas** [comment]
The current PubSubEvents will exist as it's own NuGet as it does now.  The code is solid and will most likely not have to be modified, so it should just work.  Meaning you should be able to continue to use it as is.  Prism is being repositioned as a product.  Going forward you would just add the Prism nugget package for PubSubEvents.  Yes there will be a couple of classes for MVVM, but that shouldn't be a big deal.  PubSubEvents is not used enough as a stand-alone solution to create more dependencies for Prism as well as maintain a separate project and NuGet packages.  PubSubEvents is core to the guidance of Prism, and has been brought under the same project and brand to reflect that.

**Comment by bartlannoeye** [comment]
For future reference, the current (pre-Prism 6) Prism.PubSubEvents NuGet package is [version 1.1.2](https://www.nuget.org/packages/Prism.PubSubEvents/).
