### ISSUE TITLE
[XF] Navigation Service Page Not Found Handling

### ISSUE THREAD

**Issue by dansiegel** [PrismLibrary/Prism#352]
The Navigation Service needs to better handle pages it cannot resolve. Currently if a page is not found no action is taken which can result in exceptions which do not actually help the developer discover the actual problem.

If no page can be found this needs to either be logged to the debugger or some sort of PrismPageNotFound exception needs to be thrown. I would be in favor of the later as it would allow you to better handle the problem in code by catching a known page not found exception and possibly alerting the user that their requested resource couldn't be found and/or logging that at an application level.

**Comment by brianlagunas** [comment]
I will throw an exception is a type cannot be created.  This exception will give instructions on where to start looking for the cause of the issue, such as registering your type for navigation.

**Comment by dansiegel** [comment]
That sounds great.
