### ISSUE TITLE
where's phone's backbuttonEvent

### ISSUE THREAD

**Issue by jingliancui** [PrismLibrary/Prism#357]
so sad that i can not find the override void OnHardwareButtonsBackPressed,
now i have an app write for windowsphone,but!!! I can not control the backbutton on app,because i know you write a private function to it,i can not find where i can overrider it,.
it is important for me,please,
please,Giving me to override the OnHardwareButtonsBackPressed......
thankyou

**Comment by bartlannoeye** [comment]
We moved this functionality to the [DeviceGestureService](https://github.com/PrismLibrary/Prism/blob/master/Source/Windows10/Prism.Windows/AppModel/DeviceGestureService.cs#L174) class, you can override this class and implement your version of the OnHardwareButtonsBackPressed handler.

Don't forget to also override the [ConfigureContainer](https://github.com/PrismLibrary/Prism/blob/master/Source/Windows10/Prism.Unity.Windows/PrismUnityApplication.cs#L92) method to register your own implementation. I've linked to the Unity implementation, but same counts for other IoC containers.

**Comment by jingliancui** [comment]
hello,i am the person requested boback event yesterday.
 after i seen email that you tell me to overrider something here:
#357

and then i go to see your source:
https://github.com/PrismLibrary/Prism/blob/master/Source/Windows10/Prism.Windows/PrismApplication.cs

found that in this function:InitializeFrameAsync(IActivatedEventArgs args),
 DeviceGestureService.GoBackRequested += OnGoBackRequested;
 the OnGoBackRequested is private and so the result is what ever what i do for my backevent,
 system will excute my backevent and always excuting your private OnGoBackRequested function.

so,I just didn't what to excute your private function that will let my app Exit.....
 please do something for me to remove the handler DeviceGestureService.GoBackRequested in your InitializeFrameAsync funtion.

thankyou

**Comment by bartlannoeye** [comment]
Could you show us a sample of what you have tried? Preferably a working application on github so we can clone and test.

**Comment by jingliancui** [comment]
hello,i solve this problem，but i know this is still a bug in your PrismLibrary,i just use e.Cancel = true; to cancel your private function on your library.
so ,hope you will let the prismlibrary more and more perfect.
thank you bye

Solve Problem Code:
    /// <summary>
    /// Provides application-specific behavior to supplement the default Application class.
    /// </summary>
    sealed partial class App : PrismUnityApplication
    {        
        /// <summary>
        /// Initializes the singleton application object.  This is the first line of authored code
        /// executed, and as such is the logical equivalent of main() or WinMain().
        /// </summary>
        public App()
        {
            this.InitializeComponent();
            
        }

        private void DeviceGestureService_GoBackRequested(object sender, Prism.Windows.AppModel.DeviceGestureEventArgs e)
        { 
            e.Cancel = true;// I think that will cancel your private funcion which in your 
                            //InitializeFrameAsync(IActivatedEventArgs args)
                            //DeviceGestureService.GoBackRequested += OnGoBackRequested;

            e.Handled = false;//false to suspend


            //await new MessageDialog("Press back").ShowAsync();

            //at last,success to cancel your function's executing by e.Cancel = true;.
            //And,what i see is if you didn't use arm platform,you can't see this bug,if you deploy this app to phone,an delete e.Cancel = true; you will see this bug.
            //you can't see this bug on pc because i know pc can not execute Exit() which in your private function OnGoBackRequested.
            //thank you
        }

        protected override Task OnLaunchApplicationAsync(LaunchActivatedEventArgs args)
        {
            NavigationService.Navigate("Main", null);
            SystemNavigationManager.GetForCurrentView().AppViewBackButtonVisibility = AppViewBackButtonVisibility.Visible;
            DeviceGestureService.GoBackRequested += DeviceGestureService_GoBackRequested;
            return Task.FromResult<object>(null);
        }

        protected override void ConfigureContainer()
        {
            base.ConfigureContainer();
            
        }
    }

**Comment by brianlagunas** [comment]
Phone is dead, and so is this issue :)
