### ISSUE TITLE
it's diferent goback for what i want

### ISSUE THREAD

**Issue by jingliancui** [PrismLibrary/Prism#359]
you tell me that:
We moved this functionality to the DeviceGestureService class, you can override this class and implement your version of the OnHardwareButtonsBackPressed handler.
Don't forget to also override the ConfigureContainer method to register your own implementation. I've linked to the Unity implementation, but same counts for other IoC containers.

and i do it:
1:create a new class to inherit the DeviceGestureService(and still keep nothint to the new class,all from the parent class)
2:in app class to override the ConfigureContainer ,register IDeviceGustureService with my class that inherit from DeviceGestureService
3:in app's constructor to "+=" the ongoback event

result is: my logic and your logic will together execute,and at last, the application will close......

and i think that  you should give me the detail of the tutorial in this chapter......
thankyou

**Comment by brianlagunas** [comment]
Please provide your sample so that we can make sure you have properly implemented the necessary steps.

**Comment by brianlagunas** [comment]
You should reply to the same thread instead of opening new ones.  Continue discussion on issue #357
