### ISSUE TITLE
I Found Your DeviceGestureService.GoBackRequested  Issues

### ISSUE THREAD

**Issue by jingliancui** [PrismLibrary/Prism#362]
hello,i am the person requested boback event yesterday.
after i seen email that you tell me to overrider something here:
https://github.com/PrismLibrary/Prism/issues/357

and then i go to see your source:
https://github.com/PrismLibrary/Prism/blob/master/Source/Windows10/Prism.Windows/PrismApplication.cs

found that in this function:InitializeFrameAsync(IActivatedEventArgs args),
DeviceGestureService.GoBackRequested += OnGoBackRequested;
the OnGoBackRequested is private and so the result is what ever what i do for my backevent,
system will excute my backevent and always excuting your private OnGoBackRequested function.

so,I just didn't what to excute your private function that will let my app Exit.....
please do something for me to remove the handler DeviceGestureService.GoBackRequested  in your InitializeFrameAsync funtion.

thankyou

**Comment by brianlagunas** [comment]
You should reply to the same thread instead of opening new ones. Continue discussion on issue #357
