### ISSUE TITLE
Page Dialog Service - Dialog With Timeout or Dismiss?

### ISSUE THREAD

**Issue by billSpaulding** [PrismLibrary/Prism#363]
Hello,

   Is it possible to use the dialog service to display a notification that has a light dismiss feature or a timeout? For example if a user navigates to a list of contacts and I want to display a message that says "refreshing your contacts" or any other dialog that doesn't require an action by the user. Another scenario might be to simply show a success message. 

I would like to use the Page Dialog Service to replace the ACR Dialogs that I am using now. They have a similar implementation that mimics the behavior I have explained above.

as an example:
   UserDialogs.Instance.ShowLoading(title: "Searching members for that phone number!");

In this example I am simply letting the User know that I am looking for a matching phone number. If a match is found I can then display another message that has a timeout that controls how long the notice will be visible for
//
UserDialogs.Instance.ShowSuccess("The Contact Request has been sent!.", 3000);

Thank You,
Bill

**Comment by brianlagunas** [comment]
No, there is no such behavior in the IPageDialogService.  It is built on top of the Page.DisplayAlert, and Page.DiplayActionSheet functionality, so there is no automatically dismissing the dialogs.
