### ISSUE TITLE
Page Dialog Service - Best Practices for Resource Cleanup?

### ISSUE THREAD

**Issue by billSpaulding** [PrismLibrary/Prism#364]
Are there any suggested steps / best practices for working with the Page Dialog Service? For example please consider this notice from the XF documentation.
<I>
"When using the ProgressDialog class (or any Dialog or Alert), instead of calling the Hide method when you're done with the dialog, you must call Dismiss. Otherwise, the dialog will still be alive and will leak the Activity by holding a reference to it."</I>

If I am using the service from the View Model and it is getting the service injected from the container I am assuming the container takes care of cleaning up the resource. However looking at the examples I see they are all or mostly executed from the code behind. With the understanding that its just an example I have to assume that there might be some code left out of the picture like cleaning up the event handlers, etc. What I would like to know is if there are any methods like Dismiss that is mentioned above that I need to implement to manually break any references between the view and the dialog service.

Thank You,
Bill Spaulding

**Comment by brianlagunas** [comment]
You don't have to worry about resource clean up.  The docs you are referring to aren't the XF docs.  Here is the XF docs regarding DisplayAlert an DisplayActionsheet

http://developer.xamarin.com/guides/cross-platform/xamarin-forms/user-interface/navigation/pop-ups/

**Comment by billSpaulding** [comment]
Thank you for that clarification.
