### ISSUE TITLE
Cross platform support

### ISSUE THREAD

**Issue by InquisitorJax** [PrismLibrary/Prism#369]
Not sure if I'm missing something here - but it seems prism falls a bit short in supporting the cross platform usage scenario. Is it intended to only be used on a per-platform basis

Typically in such a scenario, one would host ViewModel classes in a shared portable library - yet Prism's ViewModelBase seems to be hosted in platform specific library references?

So I guess the question is whether Prism is designed for cross-platform implementations?

**Comment by bartlannoeye** [comment]
I think you got a valid point about being able to share viewmodels. One of the major reasons about this split functionality right now is that there's quite some support for navigation in these base classes and navigation is different on each platform (see #355 ).

Nevertheless it's something we should think about, certainly when it comes down to sharing code between UWP and XF (I see WPF as a distinct target from the other two).

**Comment by InquisitorJax** [comment]
That's exactly it. I started a new XP project covering UWP & XF - but immediately hit the wall of not being able to host my view models in a shared portable library - which is what I think most XPlat implementation would do.

**Comment by InquisitorJax** [comment]
my 2 cents on the topic: baking in navigation into the view models is a fundamentally flawed design - because of the point stated that different platforms handle navigation so differently.
In the XPlat implementations I have done thus far, view models only know how to load and save state - platform navigation implementations then call into these methods - and view models can access navigation behind a INavigationService interface.
It would be great if prism could support this kind of scenario.

Can I also just add as an aside a word of thanks to the contributors - even though I can't use the full power of prism yet - the other core implementations like commands and Event Aggregators are immensely helpful.

**Comment by brianlagunas** [comment]
We do as much cross plat as we can.  One thing to keep in mind is that Prism has always been about providing guidance for building maintainable, scalable, and testable applications for XAML platforms, and not so much trying to be a true cross platform framework.  Even an INavigationService interface cannot be standardized across all platforms, which is why Prism doesn't have such an interface in it's core.

Navigation is not baked into ViewModels.  The UWP ViewModelBase simply implements the INavigationAware interface to automatically handle state management while using the navigation service.  Since navigation is so vastly different on all the other platforms, we can't standardize on single INavigationAware interface either to add to the core Prism PCL.  This is really the only limitation preventing you from sharing your ViewModels 100%.

**Comment by InquisitorJax** [comment]
Hi Brian,

" Even an INavigationService interface cannot be standardized across all platforms," - in a cross platform mvvm framework I helped build - we standardized the INavigationService to something like:
Navigate(string destination, Dictionary<string, string> parameters); The platform-specific implementations would then resolve the logical destination to the actual platform-specific implementation. Each view is treated as a type of addressable url resource - therefore only string parameters are allowed for navigation - the ViewModels are responsible for loading their state given the string key/value context.

I realize I'm probably over-simplifying things ito the prism framework - but it would really be super-cool if the ViewModels could be shared - I hope you will re-consider this enhancement in the future.

**Comment by brianlagunas** [comment]
Well, I have had the same thought, but there are some issues with that. First, that would be a major functional change to UWP.  I'm not opposed to it, but we would have to make sure all functionality is kept.  Then we have XF which has additional parameters that do mot apply to any other platform.  Granted, they are optional parameters that don't have to be used, but the API just seems weird having parameters in a nav service that are used only for a particular platform.

I haven't been involved in the UWP support.  When our XF support stabilizes, I am going to reevaluate the UWP navigation service and INavigationAware signatures to see if they can be consolidated.  For example, the NavigationParameters class should be used for UWP and brought into core.  It will be a major break for UWP, but might be worth it.

Like I said, we are always looking at cross pls where we can make it happen.
