### ISSUE TITLE
Suggestion for creating the root Frame

### ISSUE THREAD

**Issue by JohnTasler** [PrismLibrary/Prism#37]
I'd like to create an overlay on top of the root Frame. Typically, I would do this by creating a UserControl with a Grid, inside of which I could overlay a control on top of the Frame. The following chunk of Prism for Windows Store application code, in MvvmAppBase makes this a difficult task:

``` csharp
protected async Task<Frame> InitializeFrameAsync(IActivatedEventArgs args)
{
    var rootFrame = Window.Current.Content as Frame;
    // Do not repeat app initialization when the Window already has content,
    // just ensure that the window is active
    if (rootFrame == null)
    {
        // Create a Frame to act as the navigation context and navigate to the first page
        rootFrame = new Frame();
```

What I would rather see is something like this:
``` csharp
protected virtual Frame GetFrame()
{
    var rootFrame = Window.Current.Content as Frame;
    // Do not repeat app initialization when the Window already has content,
    // just ensure that the window is active
    if (rootFrame == null)
    {
        // Create a Frame to act as the navigation context and navigate to the first page
        rootFrame = new Frame();
    }
    
    return rootFrame;
}

protected async Task<Frame> InitializeFrameAsync(IActivatedEventArgs args)
{
    var rootFrame = this.GetFrame(IActivatedEventArgs args);
```

This way, I could still get the base implementation of the Frame logic of InitializeFrameAsync, but I'm able to override the creation of the Frame. While we're at it, let's make InitializeFrameAsync virtual.

**Comment by briannoyes** [comment]
Sounds like a very reasonable ask, and in line with some of the changes we are making on the WPF side to add extensibility points. We are not planning on coming up with the full plan for a new release of the Prism for Windows Runtime until after Build, but will keep this open and make sure we do something along those lines in that release.

**Comment by briannoyes** [comment]
@JohnTasler Could you confirm whether the changes we made to add CreateShell in https://github.com/PrismLibrary/Prism/issues/102 make it so you can address the problem you were having here for UWP?

**Comment by JohnTasler** [comment]
Sure! I'll take a look later this evening.

-----Original Message-----

**Comment by brianlagunas** [comment]
We are assuming this issue has been resolved.  We can reopen if this is not the case.
