### ISSUE TITLE
Ability to clear all views from a region

### ISSUE THREAD

**Issue by mglodack** [PrismLibrary/Prism#371]
I have a region that needs to be cleared when certain events happen.
My current implementation is below, but I was wondering if there is a better way to clear all views from a region.
```
foreach(var view in _regionManager.Region["RegionName"].Views)
{
    _regionManager.Region["RegionName"].Remove(view);
}
```

**Comment by brianlagunas** [comment]
That would be it.  Though, I would probably make that into an extension method or something for code reuse and maintainability.

**Comment by mglodack** [comment]
@brianlagunas What do you think about providing a method called `Clear`?
https://github.com/PrismLibrary/Prism/compare/master...mglodack:clear_all_views_in_region

**Comment by brianlagunas** [comment]
We might be able to add something.  I'll discuss it with the team.

**Comment by brianlagunas** [comment]
Would you expect to have the removed views available to you in the collectionchanged event args (e.OldItems)?

**Comment by brianlagunas** [comment]
We are going to call it RemoveAll which will then iterate the Views and remove them one at a time which will give you access to the removed view in the collection changed events handler.

**Comment by mglodack** [comment]
Much better name than 'Clear'. And yes I would expect to be able access the old view if needed. Thanks @brianlagunas 👍
