### ISSUE TITLE
[XF] adding Prism.Unity.Forms to UWP project

### ISSUE THREAD

**Issue by ValdimarThor** [PrismLibrary/Prism#376]
I just added a UWP project to me XF solution and when adding Prism.Forms and Prism.Unity I get this error: Type universe cannot resolve assebly: Prism.Unity.Forms, version=6.2.0.0.......
is there no way to let nuget resolve this, or do I have to reference it manually?

Regards Valdimar Thor

**Comment by bartlannoeye** [comment]
@brianlagunas time to update the XF packages ! :)

**Comment by ValdimarThor** [comment]
Isn't it rather that nuget doesn't know or inspects that the UWP project has a Prism.Forms reference (indirectly)?

**Comment by brianlagunas** [comment]
@ValdimarThor you are correct. Nuget cannot detect you are in an XF solution, so it is adding the wrong Prism Unity reference.  For now you have to manually reference Prism.Unity.Forms.  We will have to create a separate NuGet package for XF containers to accommodate the newly supported UWP projects in an XF solution.

**Comment by ValdimarThor** [comment]
Thanks for clarifying Brian, I've done that and everything builds now.

btw. I know this might not be the most appropriate place to ask but.....any news on your next PRISM pluralsight course :) ?

Regards
Valdimar Thor

**Comment by brianlagunas** [comment]
My newest Prism Problems and Solutions Loading Modules Based on User Roles course should be published soon.  Then I have more in the works after the holidays.

**Comment by ValdimarThor** [comment]
Brilliant, thanks Brian. Looking forward to it :)

**Comment by WarBorg** [comment]
hello. is there a sample app that includes XF and UWP ? because I have followed the directions from the xamarin blog to add a UWP to to my XF project but I keep getting errors like 

Reference to type 'PrismApplicationBase' claims it is defined in 'Prism.Forms', but it could not be found

and I am not sure what I files I need to change to make everything work toghter

thank you in advance

**Comment by brianlagunas** [comment]
As I mentioned in this thread, you can't use NuGet to add the correct assemblies to a UWP project.  For example, PrismApplicationBase does not even exist in PrismForms because that is in the Prism.Windows assembly.  For now, you have to manually add the references to your UWP XF applications.

**Comment by WarBorg** [comment]
yes I already did that, seems I also needed to add the Microsoft Unity nuGet package and after a few clean and build commands it seems to work.

thank you

**Comment by brianlagunas** [comment]
Okay, I created a new NuGet package to support UWP in XF apps now.  Can you guys try it out and let me know if you run into any issues:

https://www.nuget.org/packages/Prism.Unity.Forms/6.2.0-pre3
