### ISSUE TITLE
Make it Easier to Register Commands in CompositeCommand 

### ISSUE THREAD

**Issue by Shayon** [PrismLibrary/Prism#377]
Right now I'm a little peeved that registering commands to `CompositeCommand` is a little clunky.  At the moment you cannot pass in any commands to the constructor, and the `RegisterCommand` function returns a `void` so you can't even chain registering commands.  I propose that we have 2 new `CompositeCommand` constructors.  `public CompositeCommand(params ICommand[] list)` and `public CompositeCommand(bool monitorCommandActivity, params ICommand[] list)`.  It would also be awesome if `RegisterCommand` returned the CompositeCommand so we could chain registering commands, i.e. `compCommand.RegisterCommand(delCommand1).RegisterCommand(delCommand2)`.  I'd be content with one or both of these solutions.  I'm happy to write a PR for this myself if you guys like this.

**Comment by brianlagunas** [comment]
I don't think the ctor should be added, but I don't see any issue with the fluent API improvement on RegisterCommand.

@briannoyes do you have any feelings about this?

**Comment by brianlagunas** [comment]
Per discussion in #380 we will not be implementing this.
