### ISSUE TITLE
How to detect missing InteractionRequest view?

### ISSUE THREAD

**Issue by znakeeye** [PrismLibrary/Prism#379]
The problem below has bothered me for quite some time now. In my viewmodel, I have an interaction request:

```C#
MyViewModel()
{
    ConfirmationRequest = new InteractionRequest<IConfirmation>();
}
```

That allows me to easily show a nice message box:

```C#
ConfirmationRequest.Raise(
    new MessageBoxConfirmation()
    {
        Title = title,
        Content = message,
        Button = MessageBoxButton.OK,
        Icon = MessageBoxImage.Error
    });
```

**The problem** is that this construct will not work unless you didn't forget (and you will) to add the corresponding `XAML`:

```XAML
<i:Interaction.Triggers>
	<prism:InteractionRequestTrigger SourceObject="{Binding ConfirmationRequest, Mode=OneWay}">
		<prism:PopupWindowAction IsModal="True" CenterOverAssociatedObject="True">
			<prism:PopupWindowAction.WindowContent>
				<views:MessageView />
			</prism:PopupWindowAction.WindowContent>
		</prism:PopupWindowAction>
	</prism:InteractionRequestTrigger>
</i:Interaction.Triggers>
```

**How can you make this construct testable? How can you detect in compile-time (or at least in runtime) that the interaction request does not have an associated view?** Some kind of dependency injection?

In my opinion, interaction requests allows you to write nice code in your viewmodels, but if it cannot easily be tested... well, that sucks. Are interaction requests indeed good for popup windows?

**Comment by brianlagunas** [comment]
You can't.  This is a side effect of using MVVM to write loosely coupled code.  All you are doing is raising a notification and anything in the view listening for that can respond.  When using interaction requests, just don't forget to have your view respond to them.
