### ISSUE TITLE
Exception thrown when removing views from AllActiveRegion when view/viewModel has KeepAlive = false

### ISSUE THREAD

**Issue by hvaring** [PrismLibrary/Prism#382]
I have a WPF C# application where I use an ItemsControl as a Region. I add and remove views from this region. The problem occurs when I want to remove a view that is an IRegionMemberLifetime with KeepAlive set to false; an ArgumentException is thrown with the "Resources.ViewNotInRegionException". However, the view does get removed from the Region. The solution has been to use a try catch clause that catches ArgumentException and does nothing.

I believe the problem stems from the OnActiveViewsChanged() method in RegionMemberLifetimeBehavior; the collection changes when I call Region.Remove(), triggering the OnActiveViewsChanged(), which tries to remove the view a second time.

This problem is not present in SingleActiveRegion since there you have to call Deactivate on views with KeepAlive = false. It is not possible to Deactivate views in AllActiveRegion.

If needed, I can provide code examples.

**Comment by brianlagunas** [comment]
Sorry for the delay.  I have been swamped with my day job.  Would you mind throwing together a simple example for me?  That would really help me get to this sooner rather than later.

**Comment by hvaring** [comment]
Sure thing. The main parts are the view and viewModel.
 
```XML
<Window x:Class="PrismTestClient.Views.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:PrismTestClient"
        xmlns:prism="http://prismlibrary.com/"
        prism:ViewModelLocator.AutoWireViewModel="True"
        mc:Ignorable="d"
        Title="MainWindow" Height="350" Width="525" >
    <Grid>
        <StackPanel>
            <Button Content="Add new item" Command="{Binding AddNewItemCommand}"></Button>
            <Button Content="Remove last item" Command="{Binding RemoveItemCommand}"></Button>
            <ItemsControl prism:RegionManager.RegionName="{x:Static local:Regions.ItemsControlRegion}" />    
        </StackPanel>   
    </Grid>
</Window>
```

The AddNewItemCommand adds a view into the ItemsControl, and the RemoveItemCommand removes the latest view. Here's the ViewModel:

```C#
public class MainWindowViewModel : BindableBase
{
	public MainWindowViewModel(IRegionManager regionManager)
	{
		AddNewItemCommand = new DelegateCommand(() =>
		{
			regionManager.RequestNavigate(Regions.ItemsControlRegion, Navigations.Test);
		});
		RemoveItemCommand = new DelegateCommand(() =>
		{
			var region = regionManager.Regions[Regions.ItemsControlRegion];
			var lastView = region.Views?.LastOrDefault();
			if (lastView != null) region.Remove(lastView);
		});
	}

	public DelegateCommand RemoveItemCommand { get; set; }
	public DelegateCommand AddNewItemCommand { get; set; }
}
```

The issue occurs at the line `if (lastView != null) region.Remove(lastView);` if the View/ViewModel associated with `Navigations.Test` is KeepAlive = false, and will throw an `ArgumentException`. The View/ViewModel is also set up as `INavigationAware` with `IsNavigationTarget()` returning false. You can also catch the exception to verify that after adding and removing a single view from the region, the region contains 0 views but still throws.

Here's the ViewModel of the navigation target:
```C#
public class TestViewModel : BindableBase, IRegionMemberLifetime, INavigationAware
{
	public bool KeepAlive => false;
	public void OnNavigatedTo(NavigationContext navigationContext) { }
	public bool IsNavigationTarget(NavigationContext navigationContext) 
	{
		return false;
	}
	public void OnNavigatedFrom(NavigationContext navigationContext) { }
}
```

If you change `KeepAlive` to true, or remove the `IRegionMemberLifetime` interface, it won't throw an exception.

**Comment by hvaring** [comment]
[PrismTestClient.zip](https://github.com/PrismLibrary/Prism/files/83583/PrismTestClient.zip)

Here's the complete solution. It includes Autofac as the IoC-container.

**Comment by brianlagunas** [comment]
So I have been looking into this and I can see the exception, but I am confused on your use-case of IRegionMemberLifetime.  The IRegionMemberLifetime interface is primarily intended to allow you to manage the lifetime of views within regions during activation and deactivation, the KeepAlive property is also considered during navigation after the new view is activated in the target region.  When calling Region.Remove you are completely bypassing the IRegionMemberLifetime functionality because you are explicitly removing the view, so matter what the IRegionMemberLifetime  value is, you will always be removing the view.  This is where the exception comes in.  Since you are explicitly removing the view from the region, when the IRegionMemberLifetimeBehavior kicks in it also tries to remove the view again, since it thinks you are trying to have the IRegionMemberLifetime manage the lifetime of the view.

So what exactly are you trying to accomplish?

**Comment by hvaring** [comment]
Hey Brian, thank you for looking into this. 

We are multiple developers working on this project, so we have created several base classes to make development easier. One of these is a ViewModelBase, which inherits the IRegionMemberLifetime-interface with KeepAlive set to false by default. We are handling large image data and are reliant on views being disposed of when navigating away from them to free up the used memory.

For the above scenario, we are displaying views as dialogs on top of the current view in an AllActiveRegion, and closing a dialog should display the previous dialog until there are no more dialogs left. Some of these dialogs are also used in a SingleActiveRegion; in this case it is important that the dialog is disposed of when navigating away from it. 

Do you have any suggestions on how to approach this problem (apart from catching and ignoring the exception)?

From what I understand, the only way to remove a view from an AllActiveRegion is to explicitly remove it with Remove(). A view in an AllActiveRegion cannot be deactivated (throws exception), and it cannot be navigated away from. Is there a specific reason why the IRegionMemberLifetime value is considered in this region-type, or have I misunderstood something? 

Thanks in advance, Brian!

**Comment by brianlagunas** [comment]
So you have a scenario where you are using a view in both navigation scenarios and scenarios where you have to manually remove the view.  That seems acceptable to me.  I think we can add a simple check in the RegionMemberLifetimeBehavior to do a simple check like:

```
if (Region.Views.Contains(inactiveView)
     Region.Remove(inactiveView);
```
This should protect against exceptions in your scenario and not break the current functionality.

What do you think?

**Comment by hvaring** [comment]
I think that is a reasonable solution that allows for more flexibility.
Thanks for all your help!

**Comment by brianlagunas** [comment]
Actually, after thinking about it, you may be on to something.  It may be best to only apply the RegionMemberLifetimeBehavior to SingleActive region adpaters only, so the ContentControlRegionAdapter and the SelectorRegionAdapter only.

**Comment by brianlagunas** [comment]
But... if someone created a custom region adapter that uses a SingleActiveRegion, then they would be broken.  So maybe this isn't the best choice after all.  Hmm..... Still thinking

**Comment by brianlagunas** [comment]
I went with the simplest fix which was the conditional check.
