### ISSUE TITLE
Remove single view from Journal

### ISSUE THREAD

**Issue by mglodack** [PrismLibrary/Prism#384]
If I remove a view from my Regions Views does that also remove that instance from the Region's NavigationService Journal?

**Comment by brianlagunas** [comment]
The navigation journal does not track view instances, rather URI's.  So no, if you remove a view from your region by calling Region.Remove, this does not impact the journal.  The journal will maintain the IRegionNavigationJournalEntry and use it's URI to navigate to it when calling GoBack/GoForward.

**Comment by mglodack** [comment]
@brianlagunas I don't think this issue has been fully resolved yet.

So would I be able to remove individual items from the forward or back stack on the `IRegionNavigationJournalEntry` ? Or would you recommend calling `Clear()` if I removed a view from my region?

**Comment by brianlagunas** [comment]
Currently there is no ability to remove items directly from the back/forward stack of the navigation journal.  We have issue #30 to track this feature.  Manually removing views from a region should have no impact on the navigation journal.  Now, calling Clear on the navigation journal would completely clear out both the back and forward navigation stacks.  If that would meet your need, then you could use that approach.

**Comment by brianlagunas** [comment]
Out of curiosity, are you wanting to remove a view that is in the middle of the journal?

**Comment by mglodack** [comment]
I want to call `GoBack()` but not record the stack change.

**Comment by brianlagunas** [comment]
So if you had a nav like this:

ViewA -> ViewB -> ViewC

and then called GoBack from ViewC, you want to be on ViewB, but essentially remove ViewC from the Forward stack?

**Comment by mglodack** [comment]
Yes that is what I would expect to see

**Comment by brianlagunas** [comment]
So I have been thinking about this and right now Prism uses Stack objects for both the Back and Front nav stacks.  This means there is no way to remove items in the middle of the stack for example.  But what if we exposed a RemoveLast method that would remove the last entry in the journal.  So on the you can call RemoveLast to remove the current view from the journal and then call your navigation method.  Well something like that.

**Comment by brianlagunas** [comment]
Actually, I'll have to double check on the timing of these events.  If I navigate from ViewA to ViewB, is ViewB in the forward stack already?  I know ViewA is on the back stack.  When I go to ViewC, at what point is ViewB on the back stack.

We may have to use a different data type for the stacks to allow iterating them to remove items which I would be a little hesitant to do.

**Comment by mglodack** [comment]
Currently, the `GoBack()` and `GoForward()` methods for the `RegionNavigationJournal` put the old entry onto either stack. 

What I propose is to ignore putting that old entry on the stack and that would not conflict with the current implementations of the stack.

**Comment by brianlagunas** [comment]
What happens if I navigate to ViewA -> ViewB -> ViewC, but when I GoBack() I want to go to ViewA.  So we need to think of a cohesive stack management feature.

**Comment by mglodack** [comment]
Here is why I'm facing this problem.

If I navigate to ViewA -> ViewB -> ViewC. I then call delete on ViewC, and navigate back to ViewB using Region.NavigationService.Journal.GoBack.

However, the `RegionNavigationJournal` keeps ViewC in the stack whereas I want to navigate back and ignore the save to the stack.

**Comment by brianlagunas** [comment]
I understand your scenario, but we have to consider the other issue of not allowing a view being adding to the back stack which occurs during navigation discussed in issue #30.  So we need a cohesive approach for controlling the stack for both back and forward scenarios which makes this more complicated.

**Comment by brianlagunas** [comment]
Give this navigation stack (bold is active view):

ViewA -> ViewB -> ViewC -> **ViewD**

Then call GoBack()

ViewA -> ViewB -> **ViewC** -> ViewD

Then call GoBack() bt remove only ViewC from the nav stack

ViewA -> **ViewB** -> ViewD

Would this ever be needed?
