### ISSUE TITLE
Snippets feedback needed - Community please respond

### ISSUE THREAD

**Issue by brianlagunas** [PrismLibrary/Prism#389]
As you may or may not know, we have shipped our first version of our Prism Template Pack to the Visual Studio gallery.

https://visualstudiogallery.msdn.microsoft.com/e7b6bde2-ba59-43dd-9d14-58409940ffa0

Currently we have 3 snippets:
* prismprop - Property, with a backing field, that depends on BindableBase 
* prismpropcmd - Creates a DelegateCommand property with private setter 
* prismpropcmdgeneric - Creates a generic DelegateCommand<T> property with a private setter

I am thinking of renaming these in the next update.  I want to shorten the snippet shortcut, but keep them understandable when you see them in your intellisense.  I was thinking something like this:

* prismprop - no change
* prismcmd - drop the "prop" from the name
* prismcmdg - drop the "prop" from the name and cut off the "eneric" from the end of the name.

What do you think?  Should I leave them as-is, or shorten them?

**Comment by mustaphakd** [comment]
great pack!

shortening the names is always beneficial.
documentation would also be welcomed for newcomers to PRISM.

**Comment by brianlagunas** [comment]
@mustaphakd thanks for your vote :)

We do have docs for WPF, but our docs on UWP and XF need to be done.  Docs are definitely on our todo list.  As our feature work slows down, I am sure our docs will start to improve :)

**Comment by Qwin** [comment]
Shorten definitely is better.

**Comment by galakt** [comment]
Vote for shorten

**Comment by tomzorz** [comment]
Shorten, definitely. 

I'd go even shorter - eg. mvvmlight has propinpc, but I always do propi[tab][tab]. Also I'd suggest keeping 'prop' or 'cmd' in front, because of the conventions (prop, propa, propdp, propinpc...). 

We could have *propps*, *cmdps* and *cmdgps*?

**Comment by bartlannoeye** [comment]
Personally I've been using propp for Prism's property snippet for 2 years now. So I can follow @tomzorz reasoning to have prop and cmd in front.

**Comment by brianlagunas** [comment]
So how do we feel about something like:
* propp
* cmd
* cmdg

**Comment by bartlannoeye** [comment]
Good for me.

**Comment by brianlagunas** [comment]
snippet shortcuts have been shortened.  This has been addressed with PR #393
