### ISSUE TITLE
Regarding AutoWireViewModel

### ISSUE THREAD

**Issue by znakeeye** [PrismLibrary/Prism#394]
I have two views called MyView and MyOtherView. MyView is auto-wired to MyViewModel. Now I need to auto-wire MyOtherView so that it uses the same viewmodel. Can that be done? I.e. I want to tell MyOtherView to auto-wire MyViewModel (and not MyOtherViewModel).

(A bit awkard, I know, but I need to get this working before refactoring this viewmodel misuse.)

**Comment by brianlagunas** [comment]
Yes, you just have to manually register the ViewModel with your View using the `ViewModelLocationProvider.Register` method.

**Comment by znakeeye** [comment]
Lifesaver! Thanks Brian! :)
