### ISSUE TITLE
Client-Specific Library?

### ISSUE THREAD

**Issue by Michael-DST** [PrismLibrary/Prism#4]
I know in this issue we talked about organization:
https://github.com/PrismLibrary/Prism.Wpf/issues/1

Things look really good right now with how the solution is organized.  My only concern now is that the core Prism library has client/presentation components in it.  That is, the Commands and Mvvm namespace, as well as IActiveAware.

The original ask/intention for this separation ([found here](https://compositewpf.codeplex.com/workitem/9118)) was meant to be designed so that Prism can be used in *any* application boundary, not just for applications dealing with presentation.  

For instance, one can (and I, for one, am intending to) use Prism for server-side applications.  That is, eventing, logging, and yes even modularity are all ubiquitous and can be utilized in any application, regardless of where it exists.

My ask here is that the Prism team (at the very least) consider making a Prism.Client (or Prism.Presentation or...?) assembly with client-specific components within it.  That way, when we're using the core Prism in another non-presentation application, we're not scratching our heads wondering what a DelegateCommand is doing there (like we did in 4.1, which is why that issue was created in the first place. :) ).

If this makes sense, my ask would also be that the team considers flattening out the namespaces so that all of the components lie at the root level of this assembly (since there would only be about 9 classes in total).  Unless of course there are going to be many more classes added to those namespaces, then disregard.

All of this is open to discussion, of course.  Just wanting to get it out there so it doesn't fester in my head. :)

**Comment by brianlagunas** [comment]
Prism has always been about providing guidance for developer composite XAML applications.  This will not change.  The guidance provided by Prism doesn't necessarily translate well to other application types, and there are n-number of application types that we would then have to start testing for and supporting.  Sure, there may be a very limited number of concepts that can be used, but there implementation may be, and probably should be, different.

**Comment by Michael-DST** [comment]
Alright.  Well, I tried. :P  It's definitely better than what I was, so I'll take 90% there over 0%.  Thanks for the explanation, Brian.
