### ISSUE TITLE
Suggestion: Roadmap, Backlog and tasks 

### ISSUE THREAD

**Issue by juanfranblanco** [PrismLibrary/Prism#40]
So everyone can contribute, it will be great if we could have a roadmap, backlog and tasks (probably after build). We could use https://trello.com/ for visibility.

**Comment by bartlannoeye** [comment]
Partially discussed in #5 and #10.
Trello could be a great tool to see what features/issues people are working on, as I don't think we can self-assign as non-owners.

**Comment by juanfranblanco** [comment]
People can pick tasks from the backlog and self assign themselves, if there is an issue (cannot complete) the task can freed up and other person can pick up the work.

**Comment by juanfranblanco** [comment]
Or we could talk to Microsoft and see how visual studio online could be used for an OS project with potentially unlimeted users

**Comment by omares** [comment]
Any news on the progress front? :) Eagerly waiting to use prism in our xamarin.forms project.

**Comment by brianlagunas** [comment]
The community has been completely silent about Prism for Xamarin.Forms.  I have some small items to tighten up, then I will probably release what we have and just wait for feedback.

**Comment by keozx** [comment]
I'm eager to help with the Xamarin.Forms port, hopefully next week I will have time for this! :D

**Comment by brianlagunas** [comment]
We will begin to use a combination of labels and Milestones to communicate our roadmaps and PR needs.
