### ISSUE TITLE
XF: Need to initialize PrismApplication with Dependency Container

### ISSUE THREAD

**Issue by dersia** [PrismLibrary/Prism#401]
Hello Community,

I am working on an Xamarin-CorssPlattform-App and I decided to go with Prism.Forms pre Version since the new Navigation-Implementation is amazing.

Before I get to the Issue, I'd like to tell you what my Application-Design Looks like:

There are a few PCL-Libraries to share common Service/ViewModels/Views between the Android, iOS and UWP App:

SharedViews (PCL, referencing: Prism, Prism.Forms, Xamarin.Forms)
SharedViewModels (PCL, referencing: Prism, Prism.Forms)
SharedServices (PCL)
SharedApplication (PCL, referencing: Prism, Prism.Forms, Prism.Unity, Xamarin.Froms, Unity)

And there are the Apps:
MyApp.Andoird (Xamarin.Droid, referencing: Prism, Prism.Forms, Prism.Unity, Xamarin.Forms, Unity, <SharedProjects>)
MyApp.iOS (Xamarin.iOS, referencing: Prism, Prism.Forms, Prism.Unity, Xamarin.Forms, Unity, <SharedProjects>)
MyApp.UWP (UWP, referencing: Prism, Prism.Forms, Prism.Unity, Xamarin.Forms, Unity, <SharedProjects>)

SharedServices contains a bunch of Interfaces and common implementation for some Interfaces, but for some other Services the Implementation Needs to be done within the App, because those are Plattform specific.
So the MyApp.Android eg has an implementation for ICredentialStore and creates upon start an UnityContainer and registeres the Interface with the implementation. Now I would like to put the Container into the PrismApplication (which is in the SharedApplication-Lib) and there it should be use as default Container which is used for all dependency resolutions.

First I tried this:
```csharp
public class App : PrismApplication 
{
    public App(IUnityContainer outerContainer) : base() 
    {
        Container = outerContainer;
    }

    protected override void OnInitialized() 
    {
        NavigationService.Navigate("MainPage");
    }
}
```

Well this didn't work. After debugging through Prism.Forms.Source I figured out, that OnInitialized() is called within the base constructor (well in the Initialize-Method, which is called by the PrismApplicationBase-Constructor) and that this is way to late to set the Container.

Longstory-short: I thing espacally for CrossPlattform-Apps there must be a way to add Dependencies from within the outside of the app.

I'll create a pull request for my solution. Please have a look and tell me what you think.

Kind Regards,

Siavash Ghassemi

**Comment by brianlagunas** [comment]
You're better off just exposing a public property for your container off of the applciatin class, o rjust use XF's built-in DependencyService registration:

docs:  https://github.com/PrismLibrary/Prism/blob/master/Documentation/Xamarin.Forms/5-DependencyService.md

sample:  https://github.com/PrismLibrary/Prism-Samples-Forms/tree/master/UsingDependencyService

**Comment by dersia** [comment]
Well Exposing a public property wouldn't wokr, because the page is loaded in OnInitialize and the viewmodel has dependencies which are set in the droid app.
I'll have a look into the dependencyservice.

**Comment by weitzhandler** [comment]
The issue I'm facing is I need to access a class that's registered in the portable app from the iOS/Android/UWP apps.
If I register the class with Container.RegisterType/Instance - it's not added to Xamarin's container.
Note that I need to access it in the UWP's App class, meaning no constructor resolving available.

**Comment by NewBLife** [comment]
I think the plugin funtion for prism's Container need to be add.  If a package(like textspeech) has itself container and register the types in it.(not use the dependencyservice and xamarin.forms package) Then this contaniner's information i want to  set to prism's Container,there is no way now? I do not want to register it once again in every platform. Maybe we can take a look at mvvmcross's plugin architecture.[https://github.com/MvvmCross/MvvmCross/blob/develop/MvvmCross/Platform/Platform/Plugins/MvxLoaderPluginRegistry.cs](url)

**Comment by weitzhandler** [comment]
Perhaps it's against the rules, but meanwhile that's what I got:

I'm calling this in the `RegisterTypes` in the portable:

          ServiceLocator.SetLocatorProvider(() => new UnityServiceLocator(Container));


The in the UWP.App:

    public IUnityContainer Container => ServiceLocator.Current.GetInstance<IUnityContainer>();

Note sine UWP.App is initialized before Portable.App, one has to ensure he doen't try to resolve the container before it's set.

**Comment by brianlagunas** [comment]
@NewBLife you can use the IPlatformInitializer to register your platform types directly with Prim container.

Look at this example: https://github.com/PrismLibrary/Prism/blob/master/Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld.Droid/MainActivity.cs

**Comment by weitzhandler** [comment]
@brianlagunas Can you please confirm, what's the optimal way of doing [this](https://github.com/PrismLibrary/Prism/issues/401#issuecomment-282194446), like the above, or this:

    public IUnityContainer Container => ((MyProject.App)Xamarin.Forms.Application.Current).Container;

Or doesn't matter.

**Comment by weitzhandler** [comment]
Gotcha, found your answer [here](https://forums.xamarin.com/discussion/comment/215964/#Comment_215964), pasting in for the reference, thank you! 
You're all over the net @brianlagunas...

**Comment by brianlagunas** [comment]
I'm not sure I understand.  You get the container in the IPlatformInitializer.  What you have works, but not sure why it's needed.

**Comment by weitzhandler** [comment]
My question was how do I **resolve** types in the platform-specific app after they've been registered in the PCL, not how I register them.
What should be the proper way to resolve the `IEventAggregator` for example, in the UWP app?

**Comment by brianlagunas** [comment]
Well, you already have the application in the platform specific app. So just use the Container property off of it:

var application = new MyApp(new UwpInitialer());  
var ea = application.Container.Resolve<IEventAggregator>();

**Comment by weitzhandler** [comment]
Thank you.
Since this happens in the local `MainPage`, how do I set it in the local `App` (`MyProject.UWP.App`)?
