### ISSUE TITLE
Make interface Prism.Interactivity.InteractionRequest.IInteractionRequestAware generic.

### ISSUE THREAD

**Issue by baterja** [PrismLibrary/Prism#405]
I propose making IInteractionRequestAware interface generic for convenience with binding to xaml. Now I have something like:

```C#
public abstract class BasePopupWindowViewModel<T> : IInteractionRequestAware
        where T : INotification  {

        protected T Confirmation;

        public Action FinishInteraction { get; set; }

        public INotification Notification
        {
            get { return Confirmation; }
            set { Confirmation = (T)value; }
        }
    }
```
to handle with custom confirmation popups. Bindings looks like:

```xaml
<TextBox Text="{Binding Notification.SomePropertyExistingInMyCustomConfirmation}" />
```
but xaml cannot resolve property in desing-time, because only INotification properties are visible. I want to write code like:

```C#
public abstract class BasePopupWindowViewModel<T> : IInteractionRequestAware<T>
        where T : INotification  {
        public Action FinishInteraction { get; set; }

        public T Notification { get; set; }
    }
```
and make my custom properties visible for binding.

Only change needed is from this:
```C#
public interface IInteractionRequestAware
    {
        /// <summary>
        /// The <see cref="INotification"/> passed when the interaction request was raised.
        /// </summary>
        INotification Notification { get; set; }

        /// <summary>
        /// An <see cref="Action"/> that can be invoked to finish the interaction.
        /// </summary>
        Action FinishInteraction { get; set; }
    }
```
to this:
```C#
public interface IInteractionRequestAware<T> where T : INotification
    {
        /// <summary>
        /// Type implementing <see cref="INotification"/> passed when the interaction request was raised.
        /// </summary>
        T Notification { get; set; }

        /// <summary>
        /// An <see cref="Action"/> that can be invoked to finish the interaction.
        /// </summary>
        Action FinishInteraction { get; set; }
    }
```
and then fix all (2-3) usages of interface.

I cloned source and did it, it doesn't make any test failed.

What do You think about that?

**Comment by appsyc** [comment]
+1 
I like it in this way, instead of casting the notification each time.

**Comment by cyounes** [comment]
+1 
I like it in this way, instead of casting the notification each time.

**Comment by brianlagunas** [comment]
Well, we can't change the interface definition because it would break every single Prism app out there for no real benefit.  It's a good API suggestion, but it needs to be done so that it will not break anyone.  Think about it a let me know if you come up with anything.

**Comment by baterja** [comment]
I don't think it is possible because of interface limitations in language. It will be easier to explicitly implement interface:
```C#
public abstract class BasePopupWindowViewModel : IInteractionRequestAware {
        public Action FinishInteraction { get; set; }

        public INotificationImplementer IInteractionRequestAware.Notification { get; set; }
}
```
but it is forbidden by language.

Maybe the other day, when some really good-but-breaking changes accumulate there will be new version of Prism incompatible with previous?

Or maybe enabling implementing interface member as I wrote will be easier and more valuable for C# developers? I will check later.

**Comment by baterja** [comment]
So I've checked [C# 7 work list of features](https://github.com/dotnet/roslyn/issues/2136) and something I wrote one comment earlier *might* be possible in the future (Covariant return types: Proposal [#357](https://github.com/dotnet/roslyn/issues/357)).

For now I have a workaround (not clean, but working nice with bindings):
```C#
public abstract class BasePopupWindowViewModel<T> : IInteractionRequestAware 
    where T : INotification {
    private T _customConfirmation;

    public T CustomConfirmation {
        get { return _customConfirmation; }
        set { _customConfirmation = value; }
    }
    
    public Action FinishInteraction { get; set; }
    
    public INotification Notification {
        get { return _customConfirmation; }
        set { _customConfirmation = (T)value; }
    }
}
```
