### ISSUE TITLE
[TemplatePack] Create item wizard for View/ViewModel

### ISSUE THREAD

**Issue by brianlagunas** [PrismLibrary/Prism#407]
Right now the template pack allows you to create View and ViewModel items separately.  It would be great if we had an item template wizard that would allow you to add both a View AND ViewModel with a single item template.

Since projects can have different conventions for the ViewModelLocator, it's important that the wizard allow devs to change the target folders these items are added to, and quite possibly choose a custom base class for the Views/ViewModels from their existing project.

Not sure if this could be used for WPF, UWP, and XF, or if we would need to build one for each platform independently.

**Comment by tomcrusader** [comment]
With Xamarin.Forms for Visual Studio ReSharper is almost a must (and very cheap by the way). So the template I made for creating View/ViewModels for R# could work, at least as a starting point.

Target folders can be changed by editing the template. However, most people use their own base class for ViewModels and/or Views, which then would have to be changed as well.

**Comment by brianlagunas** [comment]
Yeah, Resharper is a good tool, but we can't rely on a third-party in order to provide our VS tooling/templates.

**Comment by tomcrusader** [comment]
Oki doki. Only problem then is I don't think the user can edit the template easilly, once it's imported?

**Comment by brianlagunas** [comment]
Do you mean edit the template that we would be building, or edit the file that is created by the template?  Depends on how complicated we make the template.  Ideally, the template wizard will handle everything.

**Comment by brianlagunas** [comment]
After thinking about this a little more.  I'm not sure this is worth the time and effort required.  The current templates, while a little more manual, still allows you to accomplish the same goal.
