### ISSUE TITLE
[XF] Modal navigation while wrapping target pages in NavigationPage does not animate

### ISSUE THREAD

**Issue by therealjohn** [PrismLibrary/Prism#408]
- Register some Page types for navigation
- Register a NavigationPage subclass for navigation, `MyNavigationPage`. 

Call `navigationService.Navigate("MyNavigationPage/MyPage", null, true);`

Result:

The target page is wrapped in a NavigationPage, and it is Modal, except it does not animate. 

I am not sure what is the best practice with the latest on how to wrap target pages in a NavigationPage. Please clarify on how this should be implemented. Every time I want to show a new modal page wrapped in a NavigationPage, should I reuse this code? e.g.

`navigationService.Navigate("MyNavigationPage/MyPage", null, true);`
`navigationService.Navigate("MyNavigationPage/MyOtherPage", null, true);`
`navigationService.Navigate("MyNavigationPage/MyOtherOtherPage", null, true);`

Thanks!

**Comment by brianlagunas** [comment]
Yes, when navigating with a NavigationPage, you always provide the NavigationPage followed by the page you want added to the navigation stack.  Now, I am not sure I understand what you mean by "modal page wrapped in a NavigationPage".

**Comment by brianlagunas** [comment]
Oh wait.. is everything working navigation wise, it's just the animation that's not working as expected?

**Comment by brianlagunas** [comment]
So, I just found the issue:

https://github.com/PrismLibrary/Prism/blob/master/Source/Xamarin/Prism.Forms/Navigation/PageNavigationService.cs#L85

The navigation service tries to be smart about deep linking navigation and checks to see if there are more than 1 navigation segment.  If there is then is turns off animation by default.  It seems I need to rethink this.  Good thing you found this now.  I was about to release a Preview 3 to NuGet :)

Maybe a deep link should be considered 3 or more navigation segments?

**Comment by therealjohn** [comment]
@brianlagunas Sorry for the confusion. I never know how to explain this scenario very well...

> I am not sure I understand what you mean by "modal page wrapped in a NavigationPage"

I basically want this:

`Navigation.PushModalAsync(new NavigationPage(new MyTargetPage))`

> is everything working navigation wise, it's just the animation that's not working as expected?

Yes, it appears so. And it looks like you might have found the reason. 

> Maybe a deep link should be considered 3 or more navigation segments?
Or, maybe it's not smart about it at all, and if you are deep linking then you have to set the animated param manually?

For me, I don't see how you could assume any arbitrary level of deep link segments. I think somebody is always going to hit some edge case where they don't get the behavior they want. Personally, I'm OK with manually saying don't animate when I know I am deep link navigating. If you do end up with an automatic solution, I think there needs to be a way to override/customize it because 1,3,X won't work for everyone.

Doh, I am excited for Preview 3. :)

**Comment by brianlagunas** [comment]
just released preview 3.  Let me now if our fix works.
