### ISSUE TITLE
AutoWireViewModel does not work for some region injected views

### ISSUE THREAD

**Issue by znakeeye** [PrismLibrary/Prism#409]
I cannot reproduce this issue in my stripped down sample project. I'm hoping that you can come up with some ideas why this error occurs.

* Using MEF.
* Using Regions.
* Using MEF for constructing auto-wired viewmodels, as described [here](https://github.com/PrismLibrary/Prism/issues/223).
* Using ExportAttrubute + IViewRegionRegistration to allow for auto-populating views in my regions. Something like [this](https://github.com/empeg/nemplode/blob/master/Src/NEmplode/Behaviors/AutoPopulateExportedViewsBehavior.cs).

Now, when I set AutoWireViewModel="True" in views with this special ExportAttribute, the auto-wiring does not work. What are possible reasons for this? It only happens in views that are added to regions (using the technique mentioned above). And it only happens in my huge project with dozens of complicated views... :(

Ideas?

**Comment by cyounes** [comment]
I am using all the techniques you mentioned and it works correctly, are you sure that your view models are respecting the default convention of viewmodel locator ? 
I had a similar issue because i had the view models in a separated assembly and different namespace than the views.

**Comment by znakeeye** [comment]
The views and the viewmodels are in the same assembly, with correct namespaces. I guess I have to download the sources and try to debug the auto-wire code...

**Comment by brianlagunas** [comment]
I am closing this as this is not an issue with Prism, but please feel free to continue the conversation.  I would be interested to know what you find.  Honestly, if I could, I would just deprecate Prism's support for MEF, because it's not a DI container.  So when you try to use it like one, you'll always hit issues and limitations.

Be sure to let us know what you find just in case another member from the community runs into the same thing.

**Comment by znakeeye** [comment]
@brianlagunas Can you please explain the term `container`? You've mentioned several times that `MEF` is not a DI container. In what way does it's DI functionality differ from e.g. Unity? What are the benefits of a "container"?

**Comment by znakeeye** [comment]
Lol... I'm able to reproduce the problem in my sample now. Didn't change anything... strange! For "MyView" the auto-wiring does not work; "MyViewModel" is never instantiated.

**Comment by cyounes** [comment]
@znakeeye Could you share your sample with us please?

**Comment by brianlagunas** [comment]
@znakeeye it was your application code causing the issue.  I was able to get your sample to run by moving the location of the assemblies.

Also, there are a ton of article about MEF vs a true DI container.  Here is a pretty short explaination:

http://blogs.msmvps.com/peterritchie/2010/02/24/mef-is-not-an-ioc-container-but-mef-uses-ioc/

Basically my recommendation is you should use MEF to manage your unknown dependencies and an IoC container to manage your known dependencies.
