### ISSUE TITLE
Automate build and release process

### ISSUE THREAD

**Issue by brianlagunas** [PrismLibrary/Prism#412]
We need to automate the building of the various Prism projects and creating of the nugget packages to reduce the time commitment to perform a release.
- Build projects in Release configuration
- Run all tests
- Zip up assemblies for manual referenced projects
- Package nugets
- Build Release-Sign configuration for signed containers and Release configuration for unsigned conatiners (StructureMap)

**Comment by joacar** [comment]
I could help with this!

One alternative could be to include a nuget-folder in every project that is eligable for packaging which contain the .nuspecs and the configuration details for successfully building, running tests and package it.

In the Source folder we could include a Tools folder which would host the generic powershell file that takes the configuration details and then

1. Check that nuget.exe is in reachable
2. Restore project(s) dependencies
3. Build project(s)
4. Run unit tests
5. Update .nuspec file
6. Create nugpkg
7. Upload nupkg (the api-key could be resolved by either looking in %user% path for nuget/api.txt, checking it exists in machine config or prompt for credentials if previos attempts failed)

To build e.g. Prism.Unity.Forms one would execute Prism.Unity.Forms\nuget\build.cmd.

Anther option would be to create powershell modules and use those when creating build.ps1. E.g. including a powershell module PrismCore to build and run tests and upon success returns the assembly path if copying of any files that is required for Prism.Unity.Forms.

Thoughts?

**Comment by joacar** [comment]
Quick sketch of how it could look like (not yet implemented uploading of nuget nor decided upon how to include release notes)

````powershell

[CmdletBinding()]
Param(
[Parameter(Mandatory=$True, Position=1)]
[string]$root,

[Parameter(Mandatory=$True, Position=2)]
[string]$projectName

)
# Build variables
$msbuild = 'C:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe'
$projectFile = "$projectName.cssproj"
$testFolder = "$projectName.Tests"
#$configPath = Join-Path $root $projectName 'nuget'
$projectFolder = Join-Path $root $projectName
$testProjectPath = Join-Path $root $testFolder
$packages = 'packages'

$nugetFileName = 'nuget.exe'
if(!(Test-Path $nugetFileName)) 
{
	Write-Host 'Downloading nuget.exe ...'
	Invoke-WebRequest 'http://nuget.org/nuget.exe' -OutFile $nugetFileName
}

# Restore packages
Invoke-Expression ".\$nugetFileName restore -PackagesDirectory $packages $(Join-Path $testProjectPath 'packages.config')"

# Build Prism.DryIoc.Forms

# Run tests
$xunit = Join-Path $packages 'xunit.runner.console.2.1.0\tools\xunit.console.exe'
$res = Invoke-Expression ".\$xunit $(Join-Path $testProjectPath "bin\Test\$projectName.Tests.dll")"
if(0) # TODO How to se that test fails. Starting from xunit2.2.0 we can check $res -gt 0
{
	Write-Host "Tests failed"
	exit 1
}

# Package nuget
$assemblyPath = Join-Path $projectFolder "\bin\Release\$($projectName).dll"
if(!(Test-Path $assemblyPath)) 
{
	# Build
}
$releaseNotesUri = 'https://github.com/PrismLibrary/Prism/wiki/DryIoc/'
$fileInfo = Get-Item $assemblyPath
$productVersion = $fileInfo.VersionInfo.ProductVersion
Invoke-Expression ".\$($nugetFileName) pack $(Join-path $projectFolder "nuget\$projectname.nuspec") -Prop version=$($productVersion) -Prop releaseNotes=$($releaseNotesUri)" 

Read-Host 'Press any key to exit'

````

**Comment by brianlagunas** [comment]
Good start.

Ideally, we would modify the project files to copy the assemblies to a "Binaries" folder and then pull form there.  Then we would need to zip up the folder at the end of the process too.

**Comment by adamtoakley** [comment]
Is this progressing? We heavily utilize nuget packages and we would like some of the enhancements/updates that have been made in the past 8-9 months. I can help out if needed!

**Comment by brianlagunas** [comment]
Not yet. Too many other efforts going on right now.

**Comment by joacar** [comment]
@adamtoakley There is an open pull-request that I started. Unfortunately I don't have much time at the moment the finalize it. What I can recall the main thing left is to properly zip binaries for those who haven't moved to nuget-package.
