### ISSUE TITLE
Problem with adding Prism.Forms project

### ISSUE THREAD

**Issue by powerdude** [PrismLibrary/Prism#415]
Hello,

When I add a new Prism Unity App (Forms), i get the following:

![prism forms bug](https://cloud.githubusercontent.com/assets/780882/12469933/aa16af6a-bfb5-11e5-9634-fb156ea05a57.png)

Any ideas?

cliff

**Comment by brianlagunas** [comment]
Do you have Xamarin installed?

**Comment by powerdude** [comment]
yes

Microsoft Visual Studio Enterprise 2015
Version 14.0.24720.00 Update 1
Microsoft .NET Framework
Version 4.6.01038

Installed Version: Enterprise

Architecture and Modeling Tools   00322-80000-00000-AA035
Microsoft Architecture and Modeling Tools
    
UML® and Unified Modeling Language™ are trademarks or registered trademarks of the Object Management Group, Inc. in the United States and other countries.

LightSwitch for Visual Studio 2015   00322-80000-00000-AA035
Microsoft LightSwitch for Visual Studio 2015

Visual Basic 2015   00322-80000-00000-AA035
Microsoft Visual Basic 2015

Visual C# 2015   00322-80000-00000-AA035
Microsoft Visual C# 2015

Visual C++ 2015   00322-80000-00000-AA035
Microsoft Visual C++ 2015

Visual F# 2015   00322-80000-00000-AA035
Microsoft Visual F# 2015

Windows Phone SDK 8.0 - ENU   00322-80000-00000-AA035
Windows Phone SDK 8.0 - ENU

Application Insights Tools for Visual Studio Package   1.0
Application Insights Tools for Visual Studio

Arduino for Visual Studio   1.0
Arduino extension for Visual Studio. For more information please see docs, faq and forum at http://www.visualmicro.com

ASP.NET and Web Tools 2015 (RC1 Update 1)   14.1.11120.0
ASP.NET and Web Tools 2015 (RC1 Update 1)

ASP.NET Web Frameworks and Tools 2012.2   4.1.41102.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

ASP.NET Web Frameworks and Tools 2013   5.2.30624.0
For additional information, visit http://www.asp.net/

Automatic Versions   1.4.2
Provides tools for managing assembly versions.

Azure App Service Tools v2.8.1   14.0.11123.0
Azure App Service Tools v2.8.1

Common Azure Tools   1.7
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

DataFactoryProject   1.0
Microsoft Data Factory Package

GitHub.VisualStudio   1.0
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

JetBrains ReSharper Ultimate 10.0.1   Build 104.0.20151114.160203
JetBrains ReSharper Ultimate package for Microsoft Visual Studio. For more information about ReSharper Ultimate, visit http://www.jetbrains.com/resharper. Copyright © 2016 JetBrains, Inc.

KofePackagePackage Extension   1.0
KofePackagePackage Visual Studio Extension Detailed Info

Microsoft Azure Data Factory Node Node   1.0
Azure Data Factory extension for Visual Studio Server Explorer.

Microsoft Azure HDInsight HQL Service   2.0.2900.0
Language service for Hive query

Microsoft Azure HDInsight Tools for Visual Studio   2.0.2900.0
An integrated development environment for HDInsight application development.

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

Microsoft Azure Tools   2.8
Microsoft Azure Tools for Microsoft Visual Studio 2015 - v2.8.31121.1

Microsoft Azure Tools   2.7
Microsoft Azure Tools for Microsoft Visual Studio 2015 - v2.7.30818.1601

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

NCrunch   
Continuous Testing Tool for .NET
Copyright © 2010-2015 Remco Software Ltd

NinjaCoder.MvvmCross.VSPackage   1.0
NinjaCoder for MvvmCross and Xamarin Forms

NuGet Package Manager   3.3.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

Office Developer Tools for Visual Studio 2015 ENU   14.0.23025
Microsoft Office Developer Tools for Visual Studio 2015 ENU

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

Python Tools for Visual Studio   2.2.31105.00
Python Tools for Visual Studio provides IntelliSense, projects, templates, Interactive windows, and other support for Python developers.

Python Tools for Visual Studio - Django Integration   2.2.31105.00
Provides templates and integration for the Django web framework.

Python Tools for Visual Studio - Profiling Support   2.2.31105.00
Profiling support for Python projects.

SQL Server Data Tools   14.0.50730.0
Microsoft SQL Server Data Tools

Visual C++ for Cross Platform Mobile Development   1.0
Visual C++ for Cross Platform Mobile Development

Visual C++ for Cross Platform Mobile Development   1.0
Visual C++ for Cross Platform Mobile Development

Visual Studio Tools for Universal Windows Apps   14.0.24720.00
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

vsFunnel   1.5.19
Decrease solution loading and re-compilation times dramatically by filtering projects not relevant for the current task. 
For more information about Funnel, see the website at http://www.vsfunnel.com
Copyright © 2013-2016. All rights reserved.

Workflow Manager Tools 1.0   1.0
This package contains the necessary Visual Studio integration components for Workflow Manager.

Xamarin   3.11.1589.0 (f119127)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin.Android   5.1.7.12 (53fce3730830417896a42f365a5ba35f1ee58d9d)
Visual Studio plugin to enable development for Xamarin.Android.

Xamarin.Forms Intellisense   1.0
Provides intellisense for Xamarin.Forms in the XML editor.

Xamarin.iOS   9.1.0.0 (a49a79c0e30fc5f9acf323008a9e44be2f0c1bd2)
Visual Studio extension to enable development for Xamarin.iOS.

Xamarin.iOS Unified Migration   1.0
Automated migration for Xamarin iOS Classic projects to Unified

Xamarin.TestCloud.Integration   1.0
Early preview of Xamarin Test Cloud integration

XamlStylerVSPackage   1.0
Xaml Styler.

**Comment by brianlagunas** [comment]
Unzip:

C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Xamarin\Xamarin\4.0.0.1689\T\PT\Cross-Platform\Xamarin.Forms.PCL.zip

Then open up FormsTemplate\FormsTempate.vstemplate and see what version of the wizard it is asking for.

**Comment by powerdude** [comment]
I don't have Xamarin 4 installed

**Comment by brianlagunas** [comment]
Ahhh. well, that may be it.  Try upgrading and see if you have an issues.

**Comment by brianlagunas** [comment]
I'll be sure to update the Prism Template Pack page to indicate the support version of Xamarin for the templates.

**Comment by powerdude** [comment]
Arghh!!! that's very unfortunate as i can't upgrade my license.  Oh well.

**Comment by brianlagunas** [comment]
Just for fun, check out the v3 templte and see if it has any template wizard info in there.  I don't think it does.  I think they changed they way their templates worked with v4.

**Comment by brianlagunas** [comment]
I just updated the Prism Template Package page with the Xamarin 4 requirement.  Thanks for finding this issue.

**Comment by powerdude** [comment]
[Xamarin.Forms.PCL.zip.zip](https://github.com/PrismLibrary/Prism/files/98590/Xamarin.Forms.PCL.zip.zip)

there is template info there

**Comment by brianlagunas** [comment]
Yup, they completely change their assemblies and namespaces for their template wizard from 3 to 4.

v3:  Xamarin.Forms.VSTemplate -> Xamarin.Forms.FormsWizard
v4: Xamarin.VisualStudio.TemplateWizards -> Xamarin.VisualStudio.TemplateWizards.FormsWizard

That's the issue.

**Comment by powerdude** [comment]
any way to support both or install a v3 version of templates?

**Comment by brianlagunas** [comment]
Unfortunately not.  You'll just have to manually add Prism to your project, which isn't that difficult.
