### ISSUE TITLE
Does navigation service handle nav within a modal?

### ISSUE THREAD

**Issue by dhaligas** [PrismLibrary/Prism#416]
@brianlagunas does the navigation service handle nav within a modal?  

For example launch a modal in a navigation page and then push new pages on that nav page till you are done with the modal

**Comment by brianlagunas** [comment]
Well, your terminology is off a little, you don't navigate a modal in a NavigationPage.  You can navigate to a NaviagtionPage modally, and then push pages onto the NavigationPage's navigationstack (PushAsync).

Yes, this is fully supported.

**Comment by dhaligas** [comment]
@brianlagunas correct my issue is that it is not pushing inside the modals stack.  It appears to be pushing to the MainPage stack

Do you have an example of this?

**Comment by brianlagunas** [comment]
If you are navigating from within a NavigationPage and then want to push a new modal page you must use the useModalNavigation parameter in the Navigate method call.

**Comment by dhaligas** [comment]
right i do that and within there I want to pushAsync to a new page.  that pushAsync is pushing to the MainPage stack not the Model Page Nav Stack .. I will put together a small sample outside of my app to reproduce.  most likely it is an issue with the way I am using it

**Comment by brianlagunas** [comment]
You don't PushAsync to another page unless it is inside a NavigationPage.  PushAsync only works inside a NavigationPage.

**Comment by brianlagunas** [comment]
Keep in mind that navigation is relative to where you are calling Navigate from.  So if you have something like this: where your main page is a NavigationPage with 2 pages that were pushed sync.

MainNavigationPage -> ViewA -> ViewB

Now if you want to push modal to another navigationpage, from **ViewBViewModel** you would call

Navigate("SomeNavigationPage", useModalNavigation:true)

Then from your SomeNavigationPage root page, you would call Navigate("nextView") and it will push async to SomeNavigationPage

**Comment by marcvitbr** [comment]
@brianlagunas  I want to accomplish the same thing, and have the exact same setup, but I am getting the "no root page" error when I call ```NavigateAsync``` from within ```OnNavigatedTo``` method of ```SomeNavigationPage```.

I'm doing something similar with my Main page (a ```NavigationPage``` that then immediately navigates to another page when navigated to), and didn't have to set the root page.

What am I missing here?

**Comment by brianlagunas** [comment]
With no code, I can't tell you what you are missing.

**Comment by marcvitbr** [comment]
Thanks a lot for the quick response!

The following code is taken from the scenario that works, when the app launches:

**App.cs**:

```
protected override void OnInitialized()
{
    NavigationService.NavigateAsync(
                          nameof(MainNavigationPage),
                          useModalNavigation: false);
}
```

Hit the **MainNavigationPageViewModel.cs**, that just navigates forward:

```
public void OnNavigatedTo(NavigationParameters parameters)
{
    this.navigationService.NavigateAsync(
                                 GUIConstants.LoginPageNavigationId,
                                 useModalNavigation: false);
}
```
I stick with this NavigationPage until a certain point in the workflow, then I want to open another NavigationPage, modally:

**MealCompositionPageViewModel.cs**:
```
public async Task OnFoodSearchEntryFocused()
{
    await this.navigationService.NavigateAsync(
                                       name: GUIConstants.FoodSearchNavigationPageNavigationId,
                                       parameters: null,
                                       useModalNavigation: true,
                                       animated: true);
}
```
I hit the new NavigationPage's view model, and immediately navigates to another page:

**FoodSearchNavigationPageViewModel.cs**
```
public void OnNavigatedTo(NavigationParameters parameters)
{
    this.navigationService.NavigateAsync(
                             name: GUIConstants.FoodSearchPageNavigationId,
                             parameters: null,
                             useModalNavigation: false);
}
```

When this last ```NavigateAsync``` is executed, it crashes:
```
NavigationPage must have a root Page before being used. Either call PushAsync with a valid Page, or pass a Page to the constructor before usage.
```

**Comment by brianlagunas** [comment]
You can't navigate to an empty NavigationPage.  Since your NavigationPage is empty it crashes because this isn't allowed in XF.  You have to navigate using a deep link

NavigateAsync("MyNavigationPage/MyPage");

This navigates to a navigationPage, but sets the initial page before the navigation is completed so that it complies with the rules of the XF framework.

**Comment by marcvitbr** [comment]
It worked! and it makes total sense. I forget that the framework is just running on top of XF, so it has to play by its rules. :)

Thanks again and congrats on the work with Prism. I'm enjoying it a lot!

**Comment by Kumar2Harsh** [comment]
Hello @brianlagunas
i want to open a window just like  dialog from main window in WPF that should have navigate functionality for that i created one window where we have a region where i want to navigate many Views but only the view registered like   **region.RegisterViewWithRegion(regionName, ViewA);** is visible 
but i register many view for navigation like 
**containerRegistry.RegisterForNavigation<ViewB>()
containerRegistry.RegisterForNavigation<ViewC>()**
but i am not able to navigate how to do that?

**Comment by Kumar2Harsh** [comment]
finally i got solution from some where else.
