### ISSUE TITLE
Navigation that would reset the entire stack does not call OnInitialize

### ISSUE THREAD

**Issue by therealjohn** [PrismLibrary/Prism#417]
After testing with Preview 3, navigation that would "reset the stack" does not seem to call OnInitialize again. 

This causes an issue when you have App.xaml.cs. The InitializeComponent() won't get called (it's placed in OnInitialize) and Prism throws an exception for resources not existing. 

Im assuming that this needs to be called again - please correct me if that is wrong and how to handle that scenario. It's probably not as simple as OnInitialize again since that would have all the app launch logic in it which you wouldn't want to happen again.

**Comment by brianlagunas** [comment]
What are you doing to "reset" the stack?  Why would OnInitialized in the App.cs need to be called?  That is only called for the initialize app startup and all resources are loaded then.

**Comment by therealjohn** [comment]
I am probably confused. Consider this:

`NavigationService.Navigate("Root/MyPage", null, false, false)`

In an attempt to achieve something like:

`MainPage = new NavigationPage(new MyPage()); // NavigationPage is "Root"`

There is a crash with something like:

```
Unhandled Exception:
Microsoft.Practices.Unity.ResolutionFailedException: Resolution of the dependency failed, type = "System.Object", name = "MyPage".
Exception occurred while: Calling constructor CaseProject.MyPage().
Exception is: XamlParseException - Position 8:2. StaticResource not found for key MyPageColor
```

When first launching the app, navigating to the same "Root/MyPage" works fine.

**Comment by brianlagunas** [comment]
In order to "reset" the entire navigation stack of the app use an absolute URI.  Essentially to reset the App.MainPage you would do this:

Navigate(new Uri("Root/MyPage", UriKind.Absolute));

**Comment by therealjohn** [comment]
Something like this produces the same issue:

`NavigationService.Navigate(new Uri("http://mydomain.com/Root/MyPage", UriKind.Absolute), null, false, false)`

**Comment by brianlagunas** [comment]
Can you provide a sample?  Prism isn't doing anything special when it comes to creating pages, except that it is using a container instead.  Have you tried doing this without using the navigation framework to see if the same thing happens?  One a resource is loaded, you would think that it would always be loaded.

**Comment by brianlagunas** [comment]
I just threw together a simple example and could not reproduce the error.

**Comment by brianlagunas** [comment]
Here is what I have:

```
  <prism:PrismApplication.Resources>
    <ResourceDictionary>
      <Color x:Key="MyPageColor">Red</Color>
    </ResourceDictionary>
  </prism:PrismApplication.Resources>
```
```
    public partial class App : PrismApplication
    {
        protected override void OnInitialized()
        {
            InitializeComponent();

            NavigationService.Navigate("Root/MainPage?title=Hello%20from%20Xamarin.Forms");
        }

        protected override void RegisterTypes()
        {
            Container.RegisterTypeForNavigation<MainPage>();
            Container.RegisterTypeForNavigation<Root>();
        }
    }
```

```
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:prism="clr-namespace:Prism.Mvvm;assembly=Prism.Forms"
             prism:ViewModelLocator.AutowireViewModel="True"
             x:Class="PrismUnityApp1.Views.MainPage"
             Title="MainPage" BackgroundColor="{StaticResource MyPageColor}">
  <StackLayout HorizontalOptions="Center" VerticalOptions="Center">
    <Label Text="{Binding Title}" />
    <Button Command="{Binding Navigate}" Text="Navigate" />
  </StackLayout>
</ContentPage>
```

```
    public class MainPageViewModel : BindableBase, INavigationAware
    {
        INavigationService _navigationService;

        private string _title;
        public string Title
        {
            get { return _title; }
            set { SetProperty(ref _title, value); }
        }

        public DelegateCommand Navigate { get; private set; } 

        public MainPageViewModel(INavigationService navigationService)
        {
            _navigationService = navigationService;
            Navigate = new DelegateCommand(Nav);
        }

        private void Nav()
        {
            _navigationService.Navigate(new Uri("http://brianlagunas.com/Root/MainPage"));
        }

        public void OnNavigatedFrom(NavigationParameters parameters)
        {

        }

        public void OnNavigatedTo(NavigationParameters parameters)
        {
            if (parameters.ContainsKey("title"))
                Title = (string)parameters["title"] + " and Prism";
        }
    }
```

Works as expected.

**Comment by therealjohn** [comment]
@brianlagunas You're right. In this test project I have a specific use case with a library. I am not sure why it's causing an issue with navigation though. 

The app does not crash because I changed them to DynamicResources. However, it simple does not navigate. Could you take a look at see why this scenario does not work in Prism? https://www.dropbox.com/s/lvcfzvn6ijr6ipt/CaseProjectTest.zip?dl=0

If you comment out lines 16-28 of MyPage.xaml, it will work fine.

**Comment by brianlagunas** [comment]
It seems you are using a custom renderer.  I would suggest removing Prism navigation from this and then test your scenario.  I am doubtful this is a Prism issue.

**Comment by therealjohn** [comment]
Ok, thanks Brian.

**Comment by brianlagunas** [comment]
No it doesn't work without Prism.  Modify initialize to this:

```
        protected override void OnInitialized()
        {
            InitializeComponent();

            MainPage = new MyPage();
        }
```

Then your MyPageViewModel.Navigate method like this:
```
        async Task Navigate()
        {
            // Reset the stack
            App.Current.MainPage = new NavigationPage(new MyPageTwo());
        }
```

It still doesn't work.  There is a problem with the logic in the PageViewContainerRenderer.ChangePage method.  If you were to comment out all the logic in this method, it will navigate as expected, with or without Prism.

**Comment by therealjohn** [comment]
You're exactly right. I have no idea how this is working in my project. I can reproduce what you see with this test project. I'll investigate more. Thanks for looking at this.

**Comment by beylkhanovdamir** [comment]
@brianlagunas 

please tell me, why MainPage object is not reinitialized after the resetting nav stack by this way:

`await _navigationService.NavigateAsync($"/{nameof(LoginPage)}");`

And in output window I see this message:
> Cannot destroy MasterDetailPage. System.ArgumentException: Value was an invalid value for ItemTemplate

I thought that slash before the url address allows me to clear nav stack and creates a new page, no?

_Xamarin.Forms 2.5
Prism 6.3_

**Comment by brianlagunas** [comment]
Yes, an absolute navigation will reset the MainPage of the app.  As you can see in your output window, you have an issue in your code that is throwing an exception which will not allow the navigation to continue.  Fix your error and try again.

**Comment by beylkhanovdamir** [comment]
@brianlagunas 
what error I should fix? I posted my code for resetting nav stack above, nothing more

And my app is works fine with this trick:

`Application.Current.MainPage = new LoginPage();`

I think that problem in not my app

**Comment by brianlagunas** [comment]
> Cannot destroy MasterDetailPage. System.ArgumentException: Value was an invalid value for ItemTemplate

There is an error in your MasterDetailPage.

**Comment by beylkhanovdamir** [comment]
page has listview with itemtemplate, perhaps, it becomes null after resetting nav stack
I'm not sure that I should redesign a page structure to fix this error, cuz, it's not core issue 
and as I said earlier, I can reset nav stack by creating a new instance of MainPage

**Comment by brianlagunas** [comment]
Correct, because XF isn't cleaning up your previous view like Prism does.  You should provide a simple sample that can reproduce the issue.
