### ISSUE TITLE
InteractionRequest.Raised is null after viewmodel change

### ISSUE THREAD

**Issue by Haukinger** [PrismLibrary/Prism#42]
I've got a view that's navigated to and each time it is assigned a new viewmodel as datacontext.
The view contains an InteractionRequestTrigger with its SourceObject bound to a property on the viewmodel. Problem is, the binding is not updated when a new DataContext is assigned, resulting in the SourceObject pointing to an old and probably disposed viewmodel and most importantly, the InteractionRequest.Raised property is null, so nothing happens when I want to trigger the InteractionRequest from the current viewmodel.

**Comment by brianlagunas** [comment]
Can you provide a link to a sample that reproduces this issue?

**Comment by briannoyes** [comment]
Not sure if this is from the same person, have been having discussion about this here: http://compositewpf.codeplex.com/discussions/627396#post1418779

And just asked them to post as an issue here this morning.

**Comment by Haukinger** [comment]
Not the same person, but probably the same issue.
I'll post a sample, but not before the weekend I'm afraid.

**Comment by Haukinger** [comment]
Any news on this one? Does the sample work for you?

**Comment by briannoyes** [comment]
Thanks for the repro, I can run and see the problem there. This issue is in our backlog and will try to get a fix in with our next release.

**Comment by brianlagunas** [comment]
I am looking into this.  For now, you can get around this issue by using the RegionMemberLifetime attribute on the view.

[RegionMemberLifetime(KeepAlive = false)]
public partial class FirstView : INavigationAware

This will fix the issue by creating a new instance of the view each time you navigate to it.

**Comment by brianlagunas** [comment]
Alright this had been fixed.  I would also like to point out that we have decided to make the InteractionRequestTrigger Obsolete since it really isn't needed.  You can use the built-in EventTrigger like this:

<EventTrigger EventName=“Raised” SourceObject="{Binding ConfirmationRequest, Mode=OneWay}">

**Comment by tkthatikonda** [comment]
Hello Brian,

We have a similar issue but the resolution [RegionMemberLifetime(KeepAlive = false)] is not helping here.

We have a view that opens a UserControl (UC1) as a popup using InteractionRequest<INotification>. 

            UC1ViewRequest.Raise(new UC1ViewModel
            {
                Title = "User Control 1"
                
            });

UC1 has a button that opens another UserControl (UC2) as a popup using InteractionRequest<INotification>. 

            UC2ViewRequest.Raise(new UC2ViewModel
            {
                Title = "User Control 2"
                
            });

Opening UC2 again and again from UC1 works fine as long as UC1 is not closed. 

But after closing UC1, UC2 cannot be shown/opened from UC1 but UC1 cannot be opened again from the main view. 

The Raised event on the UC2ViewRequest is null.

Please advise. I can send you a sample to reproduce.

**Comment by brianlagunas** [comment]
This issue has been fixed and was closed.  If you need the fix right away, you can use the latest source code.

**Comment by tkthatikonda** [comment]
Hello Brian,

Could we know the fix for Prism 5? We can rebuild the source code with the fix.  Or is the fix only available in latest version Prism 6?

Thanks

**Comment by brianlagunas** [comment]
The fix is only available for Prims 6.  If you are using Prism 5, just use the built in EventTrigger and set the EventName="Raised"

**Comment by tkthatikonda** [comment]
Thanks Brian for your prompt response. That worked!!
