### ISSUE TITLE
Exception when loading modules

### ISSUE THREAD

**Issue by EuroEager2008** [PrismLibrary/Prism#420]
Sorry for using Issues as a forum, but I do not see any better way (Something coming ?)

Using Prism.Wpf 6.1.0 and DirectoryModuleCatalog
I had one occasion when the directory contained an old module which failed at load because it referred to an older Prism.Wpf than currently in my app's bin folders.
The exception info gives very little clue of which module/file is the stale one.
This seems to be difficult to find, imagine that the user added something wild in the folder !
Any hint ?

**Comment by brianlagunas** [comment]
Can you provide the detail that the exception does give?

**Comment by EuroEager2008** [comment]
Sure, first a little more explanation:
I have one application "exe project" which performs the bootstrapping, contains the shell etc.
The solution also contains 3 modules (dll's) with classes implementing IModule.
All the 4 module projects compile and copy the project dll's to the shell project's modules folder (but not the referenced assemblies like prism.wpf) which is discovered by DirectoryModule.
The copy happens as a post-build-event.

All is well and working.
Later I decided to remove one of the 4 modules from the solution, but forgot to remove from the modules folder so it stayed there and silently loaded without doing anything.

Later I upgraded some nuget packages (e.g. prism.wpf, prism.core etc.) to the latest 6.1 version, but because the stale/removed module was no longer in the solution it was consequently not upgraded and kept old references.
The old prism.wpf which was referred to from the stale module project was thereby gone (the shell project loads all the assemblies to keep fileset low and small) and since it was not removed it was attempted loaded by the bootstrapper, but not working.
Exception was thrown which didn't give me much hint of which file could not be loaded and the root cause of the loading, exception details below.

This is a small project and I found the problem after some thinking and tracing, but I can imagine that in a big project this could possibly be a bigger problem.
As far as I know there is no smart automatic solution to cleanup such kind of files, perhaps I am not doing what should be done when I just copy the project assemblies without their dependencies ?

Anyway, a better hint when starting up the app would be welcome, exception:

Type: System.IO.FileLoadException
Message: Could not load file or assembly 'Prism.Wpf, Version=6.0.1.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
FileName: Prism.Wpf, Version=6.0.1.0, Culture=neutral, PublicKeyToken=null (Note the version, only 6.1 existed in the app at this time)

InnerException's FusionLog had some info, but nothing really useful (at least not for a newbie like me)
