### ISSUE TITLE
UWP Prism with Unity doesn't work in release mode

### ISSUE THREAD

**Issue by Hartdrooz** [PrismLibrary/Prism#422]
I'm using Prism.Unity for my UWP application, when I run the code in debug mode everything is fine but when I run in release I have a problem and this is related to the Unity container.  From what I understood running in release is different than debug the compilation is not the same.

So I wonder what is the workaround I should use to fix this problem ? 

Here I should the erorr I got : 

![error](https://cloud.githubusercontent.com/assets/6731324/12586948/5900793e-c420-11e5-9ae6-8adcd0696e42.png)

**Comment by Hartdrooz** [comment]
Seems the problem is not related to Prism but some code that was working in Windows 8.1 that doesn't work now after I did the conversion to Windows 10.  I will close this issue.

**Comment by brianlagunas** [comment]
Sweet!  Thanks for letting us know :)

**Comment by bartlannoeye** [comment]
Sad to see there are so many issues with .NET Native, I hope you can fix the problem fast.

**Comment by Hartdrooz** [comment]
Is really frustrating, the application was running like a charm in Windows 8.1 now you need when you do the conversion change a lot of UI issues, fix some adaptive layout and top of it some code now is broken....

**Comment by tomcrusader** [comment]
My UWP works for Relase, not just x64, @Hartdrooz 

UWP is still "preview" though, and I know Telerik and others are waiting for a formal release.

**Comment by Hartdrooz** [comment]
Thanks Tom, like I said the problem was not Prism ;) so I closed this ticket but it was some control I used in Windows 8.1 that was not okay in release in UWP :)
