### ISSUE TITLE
Inheritance of DelegateCommand async methods.

### ISSUE THREAD

**Issue by malylemire1** [PrismLibrary/Prism#423]
The is a problem with async method inheritance for DelegateCommand.

Since there is a static factory for async delegate command, those methods cannot return the parent type.

If the private constructors where defined as protected, one could derive the class and call those constructors with a parent factory.

protected DelegateCommand(Func<Task> executeMethod)
            : this(executeMethod, () => true)

protected DelegateCommand(Func<Task> executeMethod, Func<bool> canExecuteMethod)
            : base((o) => executeMethod(), (o) => canExecuteMethod())

**Comment by brianlagunas** [comment]
Want it?  Submit a PR :)

**Comment by malylemire1** [comment]
PR Submitted.

**Comment by brianlagunas** [comment]
Thanks for the PR
