### ISSUE TITLE
Suggestion: Merge extension methods into interfaces

### ISSUE THREAD

**Issue by HerrLoesch** [PrismLibrary/Prism#43]
Prism for WPF has a big issue when it comes to unit testing. Various important methods like RegisterViewWithRegion and RequestNavigate are provided as extension methods. That makes it unnecessarily hard to create fake objects. At least the navigation is something you might want to test within your view models to see if the correct target is selected.

**Comment by brianlagunas** [comment]
This has been implemented with PR #101
