### ISSUE TITLE
Error in PrismTemplates 1.3 when creating Forms Unity App

### ISSUE THREAD

**Issue by bokmadsen** [PrismLibrary/Prism#440]
When creating a Prism Unity Forms app using the new template 1.3 I get the following error in VS2015:
"An error was encountered creating the sub project 'PrismUnityApp1.WinPhone'. The vstemplate references the wizard class 'Xamarin.VisualStudio.TemplateWizards.WindowsPhoneChildWizard', which does not exist in the assembly 'Xamarin.VisualStudio.TemplateWizards, Version=1.0.0.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756'.

Quite correct, that class does not exist in any of my Xamarin.VisualStudio.TemplateWizards dll's, and the WP project is not created

**Comment by brianlagunas** [comment]
The Xamarin.Forms templates require Xamarin 4 to be installed.

**Comment by bokmadsen** [comment]
I've just updated today and I have v4.0.1.89

**Comment by brianlagunas** [comment]
Ahhh... Yeah, these templates haven't been updated to the latest version.  So it looks like Xamarin broke their templates again!  They did the same thing with the last update.  How annoying!

I'll update my install of Xamarin and the fix the templates.  Then release the updated to the VS Gallery.

**Comment by bokmadsen** [comment]
Great thank. No hury - I dont need WP for now

**Comment by brianlagunas** [comment]
I fixed this with #453.  It should be available in the next update.  I am waiting on a reply for the Visual Studio team about a bug before pushing out an update, so it might be a few of days.
