### ISSUE TITLE
Question: Does navigation service support setting new Nav Page to Detail Page

### ISSUE THREAD

**Issue by dhaligas** [PrismLibrary/Prism#441]
Does navigation service support setting new Nav Page to Detail Page when tapping a menu item from the Master Page?  I haven't been able to figure this out except for resetting the MainPage using an Absolute Uri.

Ideally when tapping the menu item from the Master Page it would like to set a new Detail Page i.e 

Navigate("myNavPage/myNewDetailPage", newDetail : true)

**Comment by brianlagunas** [comment]
Not right now.  For now, it will reuse the current NavigationPage, pop all of it's children, and then push the new "detail page" onto the navigation stack.  This serves as a memory and performance improvement.  What is the benefit of creating a new NavigationPage on each request?

**Comment by dhaligas** [comment]
Simpler way to reset the stack and start with a new root essentially.  

I am all for memory and perf boost.  So how would I do this 

Navigate("myNavPage/myNewDetailPage") 
or
Navigate("myNewDetailPage")

**Comment by brianlagunas** [comment]
Well, if you want a new NavPage for every request, for now you would need to create a separate NavigationPage for each menu item.  Then navigate to it accordingly

```
Navigate("NavPage1/DetailPage");
Navigate("NavPage2/AnotherDetailPage");
Navigate("NavPage3/AnotherDetailPage");
```

I have been thinking of adding an attached property to control if the MasterPage should reuse the current Detail or to create a new instance.  Something like:

```
prism:NavigationOptions.MasterDetailPage.RecycleDetail="true"
```

I just can't think of a good name, or how common this need would be.

**Comment by dhaligas** [comment]
Thanks.  I don't want a new nav page for every menu item just want the menu item selected to be the root page of the nav page set to the detail page.

**Comment by brianlagunas** [comment]
Oh in that case, make sure that your links in your MasterDetail.Master always include the NavigationPage.

```
Navigate("NavPage1/DetailPage");
Navigate("NavPage1/AnotherDetailPage");
Navigate("NavPage1/SomeotherDetailPage");
```
Now, currently there is a bug in Xamarin.Forms that will not update the MasterDetailPage toolbar button back to the hamburger.   It is being tracked here:  https://bugzilla.xamarin.com/show_bug.cgi?id=38105

So in order to get your buttons to work properly, you will need to use a new navigatoinPage instance until they fix this bug.  It's a pain, but should be temporary.
