### ISSUE TITLE
Question: can you inject NavigationService into the BaseViewModel

### ISSUE THREAD

**Issue by dhaligas** [PrismLibrary/Prism#443]
Is there a way to always have the BaseViewModel inject the NavigationService?

I would like to wrap the functions esp to have a single place to handle double tapping / modals etc

**Comment by brianlagunas** [comment]
What BaseViewModel?  Prism doesn't have a BaseViewModel.  What platform are you using?

**Comment by dhaligas** [comment]
I am using 

BaseViewModel : BindableBase, INavigationAware 

I want to know if I can inject services into my BaseViewModel that every ViewModel inherits

I guess I could write an extension to the navigation service to handle the double tap

**Comment by brianlagunas** [comment]
You can, but you have to also inject them into your derived class and pass them to your base ctor.

Why would you modify the NavigationSevice to handle a double tap?  That should be handled by your UI, and you would call a navigation action on the double tap.

What platform?

**Comment by dhaligas** [comment]
I am handling the case where the command is invoked faster than it can complete the first tap.  

I have had issues in apps with the tap gesture and the ability to tap it fast and get multiple pages pushed to the stack

**Comment by brianlagunas** [comment]
What platform?

**Comment by dhaligas** [comment]
mostly on android but sometimes on iOS

**Comment by brianlagunas** [comment]
Okay, so you are using Xamarin.Forms.  Once again, this is not something you will handle in the navigation service.  The TabGestureRecognizer has a property that lets you define a double tab called NumberOfTaps required.  If you want to prevent a double tap, then you need to handle this logic in your ViewModel, not the navigation service.

**Comment by dhaligas** [comment]
ok makes sense like this question 
https://github.com/PrismLibrary/Prism/issues/442
