### ISSUE TITLE
Question: launch modal from master page

### ISSUE THREAD

**Issue by dhaligas** [PrismLibrary/Prism#451]
I am having trouble launching a modal from the master page in a MasterDetailPage.  

Is this possible or do I need to augment the NavigationService?

**Comment by brianlagunas** [comment]
What are you doing to navigate modally?  What ViewModel are you trying to navigate from?

**Comment by dhaligas** [comment]
I am trying to open the login page.  I am using the MasterDetailPageViewModel

The login action is on the Master Page.  Should the MasterPage have its own ViewModel?

**Comment by brianlagunas** [comment]
Yes, the MasterDetailPage needs to have it's own ViewModel.  Though currently, it doesn't not take into account the need to navigate modally from the MaserDetailPage directly.  It always assumes you are navigating to a Detail page.

I will have to think if navigating modally from a MasterDetailPage makes sense or not.  Is this something you should do, or should this action happen from the Detail as it currently does?  Not sure.

I could modify the logic for the MasterDetailPage logic to check to see if the useModalNavigation parameter is true, and if it is then navigate modally directly from there.  Let me think about this for a little bit.

As a work around, you can call navigate off of the Detail page instead.

**Comment by dhaligas** [comment]
@brianlagunas hmm I would like to be able to launch a modal from the MasterPage and control the IsPresented as well.  

For example slide up the login screen and if the user cancels the modal I want the side menu to still be presented.  

Can I extend the navigation service to accomplish this?

**Comment by brianlagunas** [comment]
You can extend the navigation service to do whatever you want.  You have access to the source code :)

**Comment by brianlagunas** [comment]
Just so you know, I just committed support for MasterDeatil modal navigation.  Now, if you are navigating from a MasterDetailPageand set the useModalNavigation = true, then the target page will be navigated to modally while not trying to change the Detail of the master detail.

**Comment by dhaligas** [comment]
Nice thanks

**Comment by dhaligas** [comment]
@brianlagunas where I can find this change?

**Comment by brianlagunas** [comment]
It's still in my local commit.  Working on other nav improvements.
