### ISSUE TITLE
Autowire a view which is derived from FrameworkContentElement instead of FrameworkElement 

### ISSUE THREAD

**Issue by HarmenGrosseDeters** [PrismLibrary/Prism#452]
I would like to use the `prism:ViewModelLocator.AutoWireViewModel="True"` in a view that is derived from FrameworkContentElement. Most views (like a Usercontrol) are derived from FrameworkElement, so usually the ViewmodelLocator just works.

Both FrameworkElement and FrameworkContentElement have a DataContext property, but the ViewmodelLocator cast the view to FrameworkElement in order to set the viewmodel as the DataContext. Given a view derived form FrameworkContentElement, the viewmodel is not set as the DataContext.

```
 static void Bind(object view, object viewModel)
 {
            FrameworkElement element = view as FrameworkElement;
            if (element != null)           
              element.DataContext = viewModel;          
 }
```
possible fix:

```
 static void Bind(object view, object viewModel)
 {
            FrameworkElement element = view as FrameworkElement;
            if (element != null)
            {
              element.DataContext = viewModel;
              return;
            } 
            FrameworkContentElement frameworkContentElement = view as FrameworkContentElement ;
            if (frameworkContentElement != null)
            {
               frameworkContentElement .DataContext = viewModel;
            }
 }
```

**Comment by brianlagunas** [comment]
What are you using as a View that is a FrameworkContentElement?  This class does not define its own rendering behavior, and is mainly used in the System.Windows.Documents.  None of which make a good view type.

**Comment by brianlagunas** [comment]
I'm closing this issue as this is not something I think we will be adding.  Feel free to continue the discussion if you want to try to convince us otherwise.

**Comment by HarmenGrosseDeters** [comment]
Well in my case, I was trying to 'autowire' viewmodels to NavBarGroups form devexpress.wpf, which are derived from FrameworkContentElement (for whatever reason). I inject those NavBarGroups vieww from different modules with a regionadapter into the navbarcontrol ( think some control like the navigation pane in Outlook at the left). Works as expected, if I have assign the viewmodel myself.
I was surprised the autowiring wasn't working, since I could see that a NavBarGroup has a DataContext. Being naive, I assumed there is just one class with DataContext.

I like the autowire viewmodel feature, so I am using it at every oppurtunity. Like with a view derived from Window, which I open modal. The Window class also has a DataContext Property, but it's not derived from FrameworkElement, so that is also not going well. (I guess an Interface for classes with a DataContext would have been nice.) 

I guess it's alright to just move on at this point, because it's only a minor glitch if 99% views are derived from FrameworkElement and I feel like wasting your time with something of no greater importance. I can always assign the viewmodel myself in those cases.

**Comment by brianlagunas** [comment]
Ahhh. DevExpress... yeah, they made some really bad choices with their WPF controls.

Actually, there used to be an interface call IView with the DataContext property, but as you started creating more and more views, it became a real pain in the ass to use, so we got rid of it.

**Comment by michelbieleveld** [comment]
I am having the same issue, also with a component from DevExpress (a RibbonPage). Is there a way to use the above suggested fix without needing to recompile the library? Sorry, not well enough versed in C# to find the solution.

**Comment by brianlagunas** [comment]
The only thing I can think of is to create your own attached property and change the behaviors of the Bind callback.  See this as an example:

https://github.com/PrismLibrary/Prism/blob/master/Source/Wpf/Prism.Wpf/Mvvm/ViewModelLocator.cs

**Comment by michelbieleveld** [comment]
Thanks Brian, easy solution, much easier than trying to override stuff than can't be overridden. It is working perfectly now.
