### ISSUE TITLE
PopupWindowAction without a host view

### ISSUE THREAD

**Issue by WillEllis** [PrismLibrary/Prism#454]
Hi,

I have the requirement to launch a popup window and elsewhere I have done this with a PopupWindowAction and that works great. (I actually extended this to allow me to support a custom window type and add other dependency properties to effect the window being created.)

This time however I need to launch a popup window but the module I am launching this from does not have a host view for the InteractionRequestTrigger. I want to use the PopupWindowAction as the behaviour I have added for the creation of the window/setting of window properties is still required for this popup. 

Whats the best way to do this? I've considered creating the window action in code and manually triggering it but that doesn't seem right, another thought was having a generic InteractionRequestTrigger in the main shell and then passing the view from the module in a INotification via the event aggregator.

Any suggestions would be great as I've struggled to find any guidence/examples on Popup Windows which don't have host views.

**Comment by brianlagunas** [comment]
If you need to show a dialog without it being associated with a view, then the best approach is to use a dialog service.  I show how to build a dialog service in my Pluralsight course "Prism Problems & Solutions Showing Multiple Shells"

https://www.pluralsight.com/courses/prism-showing-multiple-shells
