### ISSUE TITLE
RequestNavigate equivalent to RegisterTypeForNavigation

### ISSUE THREAD

**Issue by Haukinger** [PrismLibrary/Prism#456]
Can we get a `RequestNavigate` variant that can be passed the target's type, doing the same type-to-navigation target-resolution as `RegisterTypeForNavigation`?
That should remove a lot of magic strings for navigation targets, and while it is easy to add to my project independent of Prism, I guess every user would benefit form this.

I'm thinking along these lines:
```
void RequestNavigate<SourceType>(string regionName)
{
    RequestNavigate(regionName, typeof(SourceType).Name);
}
```

**Comment by brianlagunas** [comment]
Since WPF can handle both View first and ViewModel first, we left this extension out of the API.  Adding this will cause confusion and will open devs up to trying to pass View types into this method, which they should not be doing in a ViewModel.

**Comment by Haukinger** [comment]
Ok, no problem, but give me a hint - if we want to navigate to a view, why would it be better to pass the view's name by string as opposed to the view's type (if the type is accessible at all, i.e. if we navigate to a view in the same module)?

**Comment by brianlagunas** [comment]
This is discussed in the documentation:

https://github.com/PrismLibrary/Prism/blob/master/Documentation/WPF/60-Navigation.md#view-based-navigation

You never want to have a View type used or referenced in a ViewModel..
