### ISSUE TITLE
Implementation of NavigationParameters entries as Dictionary

### ISSUE THREAD

**Issue by lpsRobo** [PrismLibrary/Prism#458]
It is possible to use a Dictionary<string, object> for the entries-object of a NavigationParameters object instead of List<KeyValuePair<string, object>>? This would make it easier to determine whether the entries-object contains a particular parameter/key.

Or is there a reason why no dictionary is used?

**Comment by brianlagunas** [comment]
No, this is  major breaking change as it would break every single app that uses the NavigationParameters.  Checking for existence of a key is just as easy now compared to using a dictionary.

```
if (parameters["key"] != null)
...
```
