### ISSUE TITLE
[Win10 UAP] Bring IConfirmNavigation(Request) to UWP

### ISSUE THREAD

**Issue by bartlannoeye** [PrismLibrary/Prism#46]
I think this is an important navigation feature that is currently missing in the WinRT/Universal branch, certainly for the LOB apps (to be) created on UWP. The way current navigation for RT works and how Prism plugs in, brings some challenges to the table but it can be done.

**Comment by briannoyes** [comment]
Agreed.

**Comment by briannoyes** [comment]
Still want to do this, but too big of a change to get in first release. Since we want to look into bringing in regions and modularity, that would be the sensible time to address this.

**Comment by nabels-coolblue** [comment]
+1

**Comment by allanrsmith** [comment]
over a year ago... any thoughts to regions or multi-frame?

**Comment by bartlannoeye** [comment]
new issue for regions: #780

**Comment by brianlagunas** [comment]
Done
