### ISSUE TITLE
[XF] async/await with modal navigation - 6.1.0-pre3

### ISSUE THREAD

**Issue by CarMatt** [PrismLibrary/Prism#461]
Seems like async/await not plays with modal navigation in pre3.
This line runs directly `Debug.WriteLine("Back from PrismContentPage2...");`

```
        public PrismContentPage1ViewModel(INavigationService navigationService)
        {
            _navigationService = navigationService;
            ModalDelegateCommand = new DelegateCommand(async () => await NavigateModal());
        }
        private async Task NavigateModal()
        {
          
            NavigationParameters parameters = new NavigationParameters();
            parameters.Add("key1", "value1");
            await _navigationService.Navigate("PrismNavigationPage/PrismContentPage2", parameters, true);
            //the code is executed immediately, not waiting for ContentPage2 to Pop...
            Debug.WriteLine("Back from PrismContentPage2...");
  
        }
```

**Comment by brianlagunas** [comment]
I actually just discovered this today.  It seems I wasn't properly returning the result, instead I was actually awaiting the result in the service.  I am going to look into this.

**Comment by brianlagunas** [comment]
So looking into this, it seems that the Navigate methods don't need to return tasks at all, because all it does is await the Xamarin.Forms DoPush and DoPushModal methods.  Nothing is actually being returned from these methods.  I'll look into if I can make these an actual awaitable method or not.

**Comment by brianlagunas** [comment]
Oh, I remember why they have the Task return type, it's because the method await an async call.  Async/await guidelines state that a method that awaits an async operation should not have a void return type and instead should use Task.  So I'm not sure this is an issue or not.

https://msdn.microsoft.com/en-us/library/hh524395.aspx

I'm still looking into it though.

**Comment by brianlagunas** [comment]
I actually ran your test scenario and everything worked for me.  The next view was navigated to, the previous view navigated away from, and then the debug was written.  How are you verifying that the Debug.WriteLine is happening immediately and not waiting for navigation to complete?

**Comment by CarMatt** [comment]
Aha,
I thought in my haste I could just wait there for the Page2 to Pop and then continue. But as you describe it, await is just waiting for the navigation process(navigation to page2) is done.

**Comment by brianlagunas** [comment]
Correct.  The await is not awaiting for you to come back from Page2, it is awaiting the actual navigation to Page 2.
