### ISSUE TITLE
Can I change Prism Unity App created using Prism Template Pack to use it as start point of development Prism MEF App?

### ISSUE THREAD

**Issue by EugeneBuzin** [PrismLibrary/Prism#462]
Hi! First of all I bag your pardon for my poor English. I've read some answers in posts about Prism in Stackoverflow and these answers are asserting that Unity is more preferable than MEF in view-switching Prism application development if a developer himself develop all modules and doesn't use third-party modules. But why MEF is used in view-switching application example that is offered in (https://github.com/PrismLibrary/Prism-Samples-Wpf/tree/master/View-Switching%20Navigation_Desktop)? May be using navigation as part of an application built through modularity and user interface composition requires MEF only not Unity? And if I must develop similar application then I should use MEF instead of Unity? (I'm beginner in Prism but I must develop Prism WPF view-switching application involving approximately 20 modules - not less. And using of your MEF application mentioned above as manual for developing of mine would be very comfortable for me.) By the way, StockTraderRI_Desktop app and ViewSwitching_Desktop app (in Prism 5 Quik Start) were also created using MEF but not Unity. Why? So I have three questions:

1) Will it be dreadfully for Prism 6 WPF view-switching application with modularity and user interface composition where all modules I'll develop myself (without using use third-party modules) to develop it using MEF?

2) How can I change Prism Unity App created using Prism Template Pack to use it (if it is possible ofcourse) as start point of development Prism MEF App?

3) If it is impossible to change Prism Unity App (created using Prism Template Pack) to Prism MEF App then which steps I must do for creation of Prism 6 MEF App?

Your counsel or aid will be appreciated very highly.

Sincerely yours Eugene Buzin.

**Comment by brianlagunas** [comment]
You can build a view-switching, modular Prism application using MEF, or any DI container such as Unity.  The sample was one of the original samples written my the Microsoft Patterns and Practices team back in the early days.  It is just a sample on how to do it with MEF.

1. If you want to use MEF, then go for it.  There is nothing wrong with using MEF.
2. You have to remove the Unity references, add the MEF references, and update the bootstrapper, and attribute your views/ViewModels accordingly.
3. Of course it's possible.  You will need to read the docs and study the samples that we have available.

Now for my opinion.  I would not personally recommend using MEF as your "container".  MEF is not an IoC container.  My rule of thumb is to use a DI container for known dependencies, and MEF for unknown dependencies.  So unless you plan to open up your application to unknown third party's to extend your application, there is no real benefit to using MEF.

**Comment by EugeneBuzin** [comment]
Tank you very much!
