### ISSUE TITLE
Prism UWP - Cortana entry point

### ISSUE THREAD

**Issue by jockster1000** [PrismLibrary/Prism#463]
When a UWP application is not currently open and the app is opened via a Cortana command an error occurs. Looks like Container not setup etc.

**Comment by brianlagunas** [comment]
Can you provide the error, and possibly a sample?

**Comment by jockster1000** [comment]
` protected override void OnActivated(IActivatedEventArgs e)
        {
            try
            {
                if (e.Kind != ActivationKind.VoiceCommand)
                {
                    return;
                }

                if (NavigationService == null)
                {
                    ShowError("null");
                }

                var commandArgs = e as VoiceCommandActivatedEventArgs;
                var speechRecognitionResult = commandArgs.Result;
                var voiceCommandName = speechRecognitionResult.RulePath[0];
                var textSpoken = speechRecognitionResult.Text;

                if (voiceCommandName.Contains("addProperty"))
                {
                    NavigationService.Navigate("Property", textSpoken);
                }
            }
            catch (Exception ex)
            {
                //ShowError(ex.ToString());
                ShowError(ex.GetBaseException().ToString());
            }
        }`

**Comment by jockster1000** [comment]
![error](https://cloud.githubusercontent.com/assets/14966837/13121986/ab58b7a8-d5ac-11e5-85fa-2f5f45ad7d71.PNG)

**Comment by jockster1000** [comment]
Basically when the app is not open and you enter via cortana, the NavigationService throws a null exception. Maybe i'm doing something wrong. If you need any more details let me know. Regards

**Comment by brianlagunas** [comment]
Honestly, you are probably better off debugging this yourself, and reporting what you find.  Maybe even a PR with the fix.  I'm not going to be looking at this anytime soon.

**Comment by bartlannoeye** [comment]
I'm certainly willing to have a look at it if you can't find the problem @jockster1000, but it won't be for the next few days either. Currently swamped with work and we got a few other urgent UWP issues waiting as well. So keep us posted on your progress.

**Comment by jockster1000** [comment]
Thanks @bartlannoeye  I will have a look later today.

**Comment by LijiElizabeth** [comment]
@jockster1000 did you manage to resolve this issue? Im having the same problem of having to get Cortana work, if the app is not open. It works fine while the app is open

**Comment by brianlagunas** [comment]
Haven't even looked at it yet.

**Comment by allanrsmith** [comment]
I tested this out... Everything works fine in Prism.
Your sample shows that you are overriding `OnActivated` but you are not calling `base.OnActivated`.  `PrismApplication.OnActivated` sets up everything from the container, to sessionstate, devicegestureservice and .... navigationservice.

You should rather override:
```protected override Task OnActivateApplicationAsync(IActivatedEventArgs args)
        {
            NavigationService.Navigate("Main", null);
            return Task.CompletedTask;
        }```

@brianlagunas @bartlannoeye This can be closed in my opinion.

**Comment by bartlannoeye** [comment]
Thanks @allanrsmith. Could you add your code to the samples repository for future reference?
