### ISSUE TITLE
Two questins about Prism-Samples-WPF/Modularity/ModularityWithUnity/Moduletracking on GitHub.

### ISSUE THREAD

**Issue by EugeneBuzin** [PrismLibrary/Prism#464]
Hi guys! Let beginner in Prism ask you a question? Well. On GitHub in "ModularityWithUnity" solution in (_https://github.com/PrismLibrary/Prism-Samples-Wpf/tree/master/Modularity/ModularityWithUnity_) project "ModuleTraking" has place. 
1) What is the type of this project (the template in which it was created)?  Is it "Prism Module"? Or is it ClassLibrary application? Or is it any other type of project?
2) What is the destination of this project? It has IModuleTracker interface implemented in "ModularityWithUnity.Desktop" project and WellKnownModuleNames class. In my opinion, both of them could be located in "ModularityWithUnity.Desktop" project. So, what for "ModuleTracking" project was created?

Thank you very much in advance.

**Comment by bartlannoeye** [comment]
Please use [StackOverflow](http://stackoverflow.com/tags/prism) to ask regular questions and use GitHub for issues only. We watch the Prism tag on SO, and the rest of the community is at your help there to answer as well.

Adding to that, this is a question about the samples while this repository is for Prism itself.

**Comment by EugeneBuzin** [comment]
OK.

**Comment by brianlagunas** [comment]
Well, I am finding that the SO zealots don't like questions that are asking for "opinions" and wind up closing them.  I am getting a little tired of SO not wanting to actually help devs with questions.

**Comment by TaviTruman** [comment]
I hear you Brain - I stopped using SO last year.

**Comment by EugeneBuzin** [comment]
Brain, I'm consonant with you. But where will I (as beginner) get help for WPF Prism application development. Please tell me about it. Because now I till have a lot of problems and need help.

Eugene.

**Comment by brianlagunas** [comment]
Keep using SO until someone says your question isn't good enough for SO.  Then just come back here.  Also, be sure to watch our PluralSight courses to help you get started with Prism more quickly.

http://pluralsight.com/author/brian-lagunas

Start with the Intro to Prism course.  It's a little outdated, but all the concepts are the same.

**Comment by EugeneBuzin** [comment]
Now I can use free trial only because I'm (for the time being) unable to pay for courses unfortunately.
