### ISSUE TITLE
[XF] Navigation in the sandbox example don't actualize the page title for views B and C

### ISSUE THREAD

**Issue by lecniers** [PrismLibrary/Prism#465]
Using the Xamarin.Forms sandbox sample as a reference I created my MasterDeatail, my NavBar and ViewA, ViewB, ViewC.
Using the same code the Title in the NavBar always showing  the first View's title visited.

**Comment by brianlagunas** [comment]
Make sure you have set the title on your views.  In the sandbox they do not have titles.

**Comment by brianlagunas** [comment]
If that isn't it, you will have to provide a sample that demonstrates the issue.

**Comment by brianlagunas** [comment]
I'm assuming you figured this out, so I am closing this issue.
