### ISSUE TITLE
Prism in UWP and Multiple Instance Windows

### ISSUE THREAD

**Issue by premiaware** [PrismLibrary/Prism#467]
I have not much experience with Prism but I would like that my application would offer support to Multiple instance Windows as the sample:

https://msdn.microsoft.com/en-us/library/windows/apps/dn434070.aspx

My solution is to isolate the UnityContainer for each Main Window, but i have need the follow change in the prism source code.

in PrismApplication.cs file remove privare from
protected ISessionStateService SessionStateService { get; PRIVATE set; } to
protected ISessionStateService SessionStateService { get; set; }

protected INavigationService NavigationService { get; PRIVATE set; } to
protected INavigationService NavigationService { get; set; } to

in SessionStateService.cs file remove the static from
private STATIC DependencyProperty FrameSessionStateKeyProperty =               DependencyProperty.RegisterAttached("_FrameSessionStateKey", typeof(String), typeof(SessionStateService), null);

private STATIC DependencyProperty FrameSessionStateProperty =
            DependencyProperty.RegisterAttached("_FrameSessionState", typeof(Dictionary<String, Object>), typeof(SessionStateService), null);

private STATIC List<WeakReference<IFrameFacade>> _registeredFrames = new List<WeakReference<IFrameFacade>>();

Is possibile to have this changes in the next release of PRISM? or exist other mode to support Multiple instance Windows?

I include the HelloWorld Sample modification for support the multiple instance, start app and after right clic in the application bar icon to start new instance.
[HelloWorld.zip](https://github.com/PrismLibrary/Prism/files/140863/HelloWorld.zip)

**Comment by brianlagunas** [comment]
The up-coming rewrite of Prism for UWP will have support for multipl instances. We are merging with Template 10 which already has this solved.
