### ISSUE TITLE
How to share common resource that is in separate assembly amongst multiple Prism 6 Modules in solution?

### ISSUE THREAD

**Issue by EugeneBuzin** [PrismLibrary/Prism#471]
Gentlemen, excuse me for troubling please. I develop Prism 6 view-switching application. How to share ResourceDictionary (that is in separate assembly in the solution) amongst multiple Prism 6 Modules in the solution? Prism 6 Module doesn't have App.xaml file where I could write the following (assuming that I added reference to the assembly comprising the ResourceDictionary in Prism 6 Module references):

```
<Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <ResourceDictionary Source="pack://application:,,,/MyReferencedAssembly;component/MyResourceFile.xaml" />
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
    </Application.Resources>
```

And after (assuming that the ResourceDictionary is including 'MyRadioButtonStyle' style) in RadioButtonView XAML (that is in Views folder in Prism 6 Module) write:

`<RadioButton GroupName="MainNavigation" Style="{StaticResource MyRadioButtonStyle}" .....>`

But I can't do in this way because Prism 6 Module doesn't have App.xaml file. How to share common ResourceDictionary that is in separate assembly in the solution among multiple modules in this solution? I've fashed with this problem for two days. Please help me.

**Comment by brianlagunas** [comment]
If the resource dictionary is in a separate assembly and shared amongst your modules, then just add a references to your shell Project and merge it into the Application.Resources.

**Comment by EugeneBuzin** [comment]
Thanks! It works fine!

**Comment by loveprogrammin** [comment]
It works but it is still showing errors in the xaml "resource not found

**Comment by Coder-Nut** [comment]
How to Questions belong on StackOverflow.
________________________________
