### ISSUE TITLE
Deep linked navigation isn't working on Windows 8.1 and UWP

### ISSUE THREAD

**Issue by JasonBro** [PrismLibrary/Prism#476]
I have been using the latest build of Prism. In my app, Deep Linked Navigation in the form of a call in...

```
protected override void OnInitialized() 
{
    NavigationService.Navigate("/MainNavigationPage/MainPage/SubPage", animated: false);
}
```
...works fine for iOS, Android, and Windows Phone 8.0, but with Windows Phone 8.1 and UWP it seems to display two instances of MainPage rather than one of MainPage and one of SubPage.

When they are being created, the correct ViewModels seem to be created and the back button moves back from the second one to the first one, but the display is the incorrect page.

Let me know if you'd like a demo project to show this or any further information. Or if you can suggest where to look for the problem I'll gladly roll my sleeves up and try and find it.

I think you've done a cracking job with the rest of the framework. This is the only problem that I've come across.

Cheers

Jason

**Comment by brianlagunas** [comment]
I can't duplicate it on my end.  Make sure you aren't navigating to any views in the constructor of your MainNavigationPage.

**Comment by JasonBro** [comment]
Hi Brian,

Thanks for the prompt reply. I've created a test project to show the
problem. iOS works as expected. Android is nearly right, but the page title
still says *View 1* when it should be *View 2*. Windows 8.1 Phone and
Windows UWP (running on a Windows 10 Phone Emulator) have two pages, but
both are *View 1*, and the Windows 8.1 version (not a phone version) also
seems wrong.

Let me know if you have any problems with the project (it's a VS2015 one)
or would like any further information or help

Kind regards,

Jason


[image: Inline images 1]

**Comment by brianlagunas** [comment]
I think you forgot to provide a link to the project.

**Comment by JasonBro** [comment]
Ooops - I attached it to the email, but I think it must have been eaten by something on the way there. I'll have another go...
[NavTest.zip](https://github.com/PrismLibrary/Prism/files/150040/NavTest.zip)
![screenshot](https://cloud.githubusercontent.com/assets/1178225/13380859/ab24a90e-de44-11e5-97df-1e0c4f1f7238.jpg)

**Comment by brianlagunas** [comment]
Actually, I managed to reproduce this on my own using a very simple sample.  The sample I was originally working with had a ton of other stuff going on in it, so I stripped it down and started from scratch.  This is actually a bug in Xamarin.Forms.  This can easily be reproduced in a standard Xamarin.Foms application using this snippet:

```
            var navPage = new MainPageNavigationPage();
            var mainPage = new MainPage();
            var viewA = new ViewA();

            await mainPage.Navigation.PushAsync(viewA);
            await navPage.Navigation.PushAsync(mainPage);

            MainPage = navPage;
```

This essentially reproduces the steps the Prism navigation service takes when performing a deep link navigation.  As you can see, this is where the problem lies.  I will report this to Xamarin and hopefully they will get a fix out as soon as possible.

This is the second Xamarin.Forms navigation bug found by Prism users in about a week :)

**Comment by JasonBro** [comment]
Excellent! I'll carry on with my app assuming it'll be fixed by the Xamarin people before I release my app. Could you put the link to the Xamarin bug in here so that anyone else with this issue can find out what's happening then close this bug, please.

Thanks also for a very prompt reply: it gives me a lot of confidence in Prism and the work that you've done!

**Comment by brianlagunas** [comment]
I have reported ths bug to Xamarin.  You can follow the status here:

https://bugzilla.xamarin.com/show_bug.cgi?id=39187

**Comment by brianlagunas** [comment]
Xamarin has started working on this bug and it is "In Progress".  I will update this issue when it has been fixed.

**Comment by rmarinho** [comment]
This should be fixed in Xamarin.Forms 2.2 stable.

**Comment by brianlagunas** [comment]
It is partially fixed.  It is fixed in the specific test case I provided, but doesn't in other simple scenarios like:
```
        public App()
        {
            var mainPage = new MainPage();
            var viewA = new ViewA();

            mainPage.Navigation.PushModalAsync(viewA);            

            MainPage = mainPage;
        }
```
