### ISSUE TITLE
Logical and keyboard focus - Prism Region

### ISSUE THREAD

**Issue by rocky050371** [PrismLibrary/Prism#479]
I am having a problem where I can't set the focus to a textbox when I bring a region in. It shows logical focus but not keyboard

`<TextBox x:Name="Test" Width="400" FocusManager.FocusedElement="{Binding RelativeSource={RelativeSource Self}}" />`

Then in the code behind I have 

` Keyboard.Focus(Test);`

**Comment by brianlagunas** [comment]
Managing focus is not a Prism issue.  I recommend asking this question on StackOverflow.
