### ISSUE TITLE
Login Form

### ISSUE THREAD

**Issue by rocky050371** [PrismLibrary/Prism#483]
How would I show a login form prior to the Shell being shown, the Login form would need access to resolved services such as the repository.

**Comment by brianlagunas** [comment]
Watch this:

https://app.pluralsight.com/library/courses/prism-loading-modules-user-roles/table-of-contents

**Comment by rocky050371** [comment]
Hi Brian,

I had previously watched this and wasn't aware it actually showed a login prior to the shell loading?

**Comment by brianlagunas** [comment]
This question is discussed in Modules 2 clip 5 "Demo - Storing Roles"

**Comment by rocky050371** [comment]
Thanks Brian, would I simply capture the result from 

  dialog.ShowDialog();

and then call             

            //((RadWindow)Shell).Show();

**Comment by rocky050371** [comment]
Morning Brian,

I hope you can help, I have the following, after the login form closes the application just exits - am I missing something?

   protected override DependencyObject CreateShell()
        {
            return Container.Resolve<Shell>();
         
        }

        protected override void InitializeShell()
        {
            base.InitializeShell();

            Login login = new Login();
            login.Closed += (s, e) =>

            {
                // Check 
                ((RadWindow)Shell).Show();

       
            };
            
            login.Show();
       
        }

**Comment by rocky050371** [comment]
Thanks for your help Brian
