### ISSUE TITLE
Loosely coupled event generated with Prism EventAggregator is not received by its subscriber.

### ISSUE THREAD

**Issue by EugeneBuzin** [PrismLibrary/Prism#484]
Hi, guys. I'm damn embarrassing now that I trouble you but I puzzle over all day today with the following problem: _Loosely coupled event subscriber in one Prism module doesn't react to publishing of this event in the other Prism module_. Both of them - the publisher and the subscriber are ViewModel classes. Here is the reference to my post in SO about this problem: http://stackoverflow.com/questions/35840460/why-is-loosely-coupled-event-generated-with-prism-eventaggregator-not-received-b I think that it makes no sense to copy it here. In particularly, I've been changing call of Sibscribe method of event:
```
SubscriptionToken token = 
                this._eventAggregator.GetEvent<UserAuthorizationLevelDeterminedEvent>().Subscribe(this.setRadiobuttonVisualStatus, 
                ThreadOption.UIThread/*.PublisherThread*/ /*.BackgroundThread*/, true);
```
As you can see from code above, I changed ThreadOption value, set and removed 'true' value for 'keepSubscriberReferenceAlive' Boolean flag but nothing help me. Please, help me to move forward and solve the problem. I appreciate your time. Excuse me for troubling.

**Comment by brianlagunas** [comment]
This is being discussed on SO
