### ISSUE TITLE
From Eugene Buzin to Brian Lagunas. I put my application on GitHub.

### ISSUE THREAD

**Issue by EugeneBuzin** [PrismLibrary/Prism#487]
Hello, Brian. First of all - thank you very much for your help and support. I'm very grateful to you for it. With your permission, I put my application source code on GitHub in order to you can watch it. Here is reference to this source code: https://github.com/EugeneBuzin/FlowmeterConfigurator . Yesterday in SO you are allowed me to show my source code to you. As you know - my problem is that _loosely coupled event generated with Prism EventAggregator not received by its subscriber_. Thank you very much again.

Yours respectfully    Eugene Buzin  (in SO I have Dr.Doog nikname).

**Comment by brianlagunas** [comment]
I was hoping for a small repo, not the entire app :). Would be easier to debug without all the other noise.

**Comment by brianlagunas** [comment]
I see the problem.  You are using a Shared Project.  This will not work.  A SharedProject does not produce an assembly but rather acts as if the class is defined in the referenced assembly and is compiled within it.  You have to use a PCL.

**Comment by EugeneBuzin** [comment]
So great! You help and rescue me! The application I develop is very important for me. Thank you very much. Please forgive me for the trouble.
