### ISSUE TITLE
How to use the NavigationPage Soft-BackButton on Android with Prism GoBack()

### ISSUE THREAD

**Issue by JarJarBinkz** [PrismLibrary/Prism#488]
I want to use the NavigationService from Prism to navigate in my App. I use a NavigationPage with some ContentPages. The NavigationPage create on Android a Soft-BackButton in the NavigationMenu. When I press the Soft-BackButton the Prism NavigationService is not used. This is a Problem. How can override the Soft-BackButton to use the Prism NavigationService GoBack Method?

**Comment by brianlagunas** [comment]
You can't.  Xamarin has not exposed an API that allows you to hook into the software or Hardware buttons yet.  This is a known limitation and Xamarin will eventually be exposing an API.

Essentially, what you want Is for the INavigationAware methods to be invoked when using the soft/hardware button.  We have to wait on Xamarin before we can implement this.
