### ISSUE TITLE
[XF] Modal page navigation with Master Detail page problem

### ISSUE THREAD

**Issue by WarBorg** [PrismLibrary/Prism#489]
hello,

I am running into a small issue with navigation from a Master Detail page in Android (not tested in iOS or Windows) : 

- XAML looks like this

```XAML
<MasterDetailPage xmlns="http://xamarin.com/schemas/2014/forms"
                  xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
                  xmlns:prism="clr-namespace:Prism.Mvvm;assembly=Prism.Forms"
                  prism:ViewModelLocator.AutowireViewModel="True"
                  x:Class="..."
                  xmlns:local="clr-namespace:...;assembly=..."
                  Title="Title">
  <MasterDetailPage.Master>
    <ContentPage Title="Menu">
      ... Master page content here
    </ContentPage>
  </MasterDetailPage.Master>
  <MasterDetailPage.Detail>
    <NavigationPage>
      <x:Arguments>
      <ContentPage>
        ... Detail page content here
      </ContentPage>
      </x:Arguments>
    </NavigationPage>
  </MasterDetailPage.Detail>
</MasterDetailPage>
```

- in App class it is called like

```C#
protected override void OnInitialized()
        {
            InitializeComponent();

            NavigationService.Navigate("MyMasterDetailPage");
        }
```

- in the MasterDetailPage viewmodel I have this

```C#
public override void OnNavigatedTo(NavigationParameters parameters)
        {
            if (IsFromMainPage)
                return;

            if (IsUserLoggedIn)
            {
                _navigationService.Navigate("MainPage", null, true);
            }
            else
            {
                _navigationService.Navigate("LoginPage", null, true);
            }
        }
```

- in the LoginPage view model I have a button with the binded command 

```C#
public DelegateCommand LoginCommand
        {
            get
            {
                return new DelegateCommand(() =>
                {
                    IsUserLoggedIn = true;

                    _navigationService.GoBack(null, true);
                });
            }
        }
```

I was expecting the MasterDetailPage to get the OnNavigatedTo method hit and display the MainPage but when I use the GoBack method from the login page I get the error : 

Xamarin.Forms.InvalidNavigationException: Can't pop modal without any modals pushed

I tried replacing the master detail page with a content page and ran the same test and it works without an error...

is this because the navigation service is aware it is on a master detail page and somehow gets messed up with tring to navigate the detail page somehow and forgets that I pushed modal the login page ?

thank you in advance

**Comment by brianlagunas** [comment]
When navigating from a MasterDetailPage, the Detail will be set to the target page.  There is no Modal navigation happening here.  Basically the "isModal" is not being respected.  In the current code base this has been fixed so that the MasterDetailPage will respect the "isModal" parameter and properly navigate modally when set to true.  I am hoping to release Preview 4 with this fix in it soon.

In the mean time, a work around would be to navigate like this:

```
protected override void OnInitialized()
{
    InitializeComponent();
    NavigationService.Navigate("MyMasterDetailPage/MainPage");
}
```

Then in the MainPageViewModel OnNavigatedTo, navigate modally to your LoginPage.

**Comment by WarBorg** [comment]
yes that was also my conclusion, thank you for your answer

have one question, I tried your example and it is working fine but how do I get from the MainPage to MasterDetailPage ? I tried with GoBack() from the main page model, but I get a ArgumentOutOfRangeException

**Comment by brianlagunas** [comment]
That's not how MasterDetailPage works.  A MasterDetailPage is a single page that has another page as it's Detail.  It actually sets the MasterDetailPage.Detal property.  There is no going back from here.  If you swipe from the left edge your Master menu will slide out.  You could also wrap your detail in a navigation page to get the hamburger menu at the top.

**Comment by WarBorg** [comment]
yes, that is what I thought but that means your workaround does not satisfy my requirements:

when the app starts it should set the masterdetail page as root, then it will make a check on navigation to

if the user is logged in it shows the modal main page which has a button that should hide it (GoBack() ) and show the root masterdetail page which shows other data

if the user is not logged in then show login modal page, after login show modal main page with the behavior described above

**Comment by brianlagunas** [comment]
I'm not seeing how it won't.  The flow is the exact same.

App starts -> load MasterDetail/MainPage.  MainPage checks to see if you are logged in, and if you are then nothing happens.  Your MainPage is the Detail of the MasterDetail just as you expect.  If you are not logged in, then it will immediately navigate modally to your LoginPage.  There you can login and call GoBack when successful.

Another option is to change your process to check if the user is logged in first on App startup.  If they aren't navigate to the login screen.  Upon logging in, use an absolute URI to replace the navigation stack with your MasterDetailPage.

**Comment by WarBorg** [comment]
ok, I'm sorry I did not make myself clear, I don't want the main page to be part of the master detail page it is a separate entity and when the master detail finally appears I want it to display other detail pages with a nice hamburger menu
