### ISSUE TITLE
Detecting the Active View in a Prism

### ISSUE THREAD

**Issue by davidop** [PrismLibrary/Prism#490]
Hi, I have two views registered at the MainRegion and need to know which is active or has the focus, in order to send an event function of the active view. What can I do?

**Comment by brianlagunas** [comment]
Your ViewModel should implement IActiveAware.  That will tell you which View/VM is active.

**Comment by davidop** [comment]
Thanks. Do you have an example?

**Comment by brianlagunas** [comment]
Nope. Just implement the interface and you will be good.

**Comment by MikaelFerland** [comment]
@davidop If you really want a exemple. Feel free to watch "Prism Problems & Solutions: Mastering TabControl". @brianlagunas implement the interface in his demo if I remember it's the first module so you will be good with a trial of PluralSight.

**Comment by brianlagunas** [comment]
@MikaelFerland why didn't I think of that?  Thanks for the plug :)

**Comment by davidop** [comment]
Thanks @MikaelFerland
