### ISSUE TITLE
UWP: DataAnnotations Validation Localization via RESW resource file

### ISSUE THREAD

**Issue by chrisaswain** [PrismLibrary/Prism#493]
I am able to successfully implement ViewModel validation via ValidationAttributes (Required, Email, etc.), but I currently have to set the validation error message string in the attribute rather than being able to point it to a resource string inside a RESW file.  The usual way to do it would be to specify the ErrorMessageResourceType and ErrorMessageResourceName values for the attribute, but these don't seem to work right in Universal Windows Platform apps.  Is this a bug?  An unimplemented feature?  Or am I missing something?

**Comment by chrisaswain** [comment]
As a work-around, I was able to get it working by using the file generator tool at [http://reswcodegen.codeplex.com/](http://reswcodegen.codeplex.com/) to generate a resource file with the required static properties to access the strings in the RESW file.  Now I can use the following syntax:

`        
[Required(ErrorMessageResourceType = typeof(Resources.Strings), ErrorMessageResourceName = "EmailInvalidMessage")]
[EmailAddress(ErrorMessageResourceType = typeof(Resources.Strings), ErrorMessageResourceName = "EmailInvalidMessage")]
public string Username { ... }
`

I still think this is a bug and that there needs to be a way to use the RESW file as intended without requiring this Visual Studio plugin to generate a CS file.

**Comment by brianlagunas** [comment]
If this is indeed a bug, you would need to report this to Microsoft as Prism doesn't control how the attribute behaves.  All Prism does is call into the System.ComponentModel.DataAnnotations.Validator.TryValidateProperty and relies on the System.ComponentModel.DataAnnotations.ValidationResult.ErrorMessage property to get the message.
