### ISSUE TITLE
Forum/Chat Room ?

### ISSUE THREAD

**Issue by Michael-DST** [PrismLibrary/Prism#5]
GitHub isn't really good about this, but it would be cool to get a chat room to discuss items for this project.  That way, meanderings, musings, and other unofficial banter don't get created as issues (*halo*).  It is sort of confusing as "Issues" are really the only way to contact owners, and there really needs to be a forum/chat room for this.

I personally prefer forums, but it looks like chat rooms are the only offerings available right now.  Here is one that I know of: 

https://gitter.im

**Comment by brianlagunas** [comment]
True.  As soon as we can get a website created, we will added a forum to it.  This is something I have been wanting to do, but just haven't found the time.  We are also considering starting a monthly advisory board, or maybe an open meeting, to discuss the project and show off what we have been working on and gather feedback.

**Comment by Michael-DST** [comment]
Actually this might make a better substitute than #3 for general links/discussion/chat leading up to //build (until there is a chat room/forum).

Xamarin.Forms Windows Store Preview announced today: http://blog.xamarin.com/xamarin.forms-for-windows-store-preview-and-xamarin-for-oss/

**Comment by bartlannoeye** [comment]
Although it's nice to see the fast progress Xamarin.Forms is going through, it's still quite early to understand the effects these changes will have on creating LOB apps for WinRT as the support isn't for Universal projects yet.
I suppose we'll have to indeed wait until \\Build to find out which direction WinRT is going and which role Xamarin.Forms will play in Windows 10 LOB apps.

**Comment by brianlagunas** [comment]
Well said @bartlannoeye.  It is indeed a waiting game, and even the current work being done on prism for Xamarin.Forms is too volatile to rely on at this time.
