### ISSUE TITLE
Prism + Telerik Dark Theme

### ISSUE THREAD

**Issue by rocky050371** [PrismLibrary/Prism#500]
I am trying to use the Notification request within my app, the problem is only the title is shown on a blank white form, is this a theme or prism issue? 

```
  <i:Interaction.Triggers>
        <prism:InteractionRequestTrigger SourceObject="{Binding NotificationRequest}">
            <prism:PopupWindowAction IsModal="True" CenterOverAssociatedObject="True">
                <prism:PopupWindowAction.WindowContent>
                    <inf:NotificationView />
                </prism:PopupWindowAction.WindowContent>
            </prism:PopupWindowAction>
        </prism:InteractionRequestTrigger>
    </i:Interaction.Triggers>


<telerik:RadWindow x:Class="VTUK.Gemini.Infrastructure.PrismDialogs.NotificationView"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" 
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
             xmlns:telerik="http://schemas.telerik.com/2008/xaml/presentation"
             mc:Ignorable="d" 
             d:DesignHeight="150" d:DesignWidth="300" Width="800" Height="150" >
    <telerik:RadWindow.HeaderTemplate>
        <DataTemplate>
            <Grid Height="10" />
        </DataTemplate>
    </telerik:RadWindow.HeaderTemplate>
    <Grid Background="Black">
        <Grid.ColumnDefinitions>
            <ColumnDefinition />
            <ColumnDefinition />
        </Grid.ColumnDefinitions>
        <Grid.RowDefinitions>
            <RowDefinition Height="Auto" />
            <RowDefinition Height="Auto" />
            <RowDefinition Height="Auto" MinHeight="200"/>
        </Grid.RowDefinitions>
        <TextBlock Grid.Row="0" Text="{Binding Title}" />
        <TextBlock Grid.Row="2" Text="{Binding Content}" Margin="0,10,0,10" Grid.ColumnSpan="2" Grid.Column="0" Foreground="White" />
        <Button x:Name="Ok" Grid.Row="0" Grid.Column="1" Margin="0,10,0,0" Content="Ok" Width="50" HorizontalAlignment="Right" Click="Ok_Click" />
        <Border Grid.Row="1" Grid.ColumnSpan="2" Height="2" HorizontalAlignment="Stretch" Background="White" />
    </Grid>
</telerik:RadWindow>

```

**Comment by brianlagunas** [comment]
It's Telerik. Remove that and use a normal UserControl and it will work.

**Comment by rocky050371** [comment]
Hi Brian,

I switched it to a user control but no joy - the button shows and the title shows but not the Content (set       NotificationRequest.Raise(new Notification { Title = "Login Failed", Content = "Your password has not been recognised. Please try again." });)

<UserControl x:Class="VTUK.Gemini.Infrastructure.PrismDialogs.NotificationView"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" 
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
             mc:Ignorable="d" 
             d:DesignHeight="150" d:DesignWidth="300" Width="800" Height="150" >
    <Grid>
        <Grid.ColumnDefinitions>
            <ColumnDefinition />
            <ColumnDefinition />
        </Grid.ColumnDefinitions>
        <Grid.RowDefinitions>
            <RowDefinition Height="Auto" />
            <RowDefinition Height="Auto" />
            <RowDefinition Height="Auto" MinHeight="200"/>
        </Grid.RowDefinitions>
        <TextBlock Grid.Row="0" Text="{Binding Title}" />
        <TextBlock Grid.Row="2" Text="{Binding Content}" Grid.ColumnSpan="2" Grid.Column="0" />
        <Button x:Name="Ok" Grid.Row="0" Grid.Column="1" Margin="0,10,0,0" Content="Ok" Width="50" HorizontalAlignment="Right" Click="Ok_Click" />
        <Border Grid.Row="1" Grid.ColumnSpan="2" Height="2" HorizontalAlignment="Stretch" Background="White" />
    </Grid>
</UserControl>

**Comment by rocky050371** [comment]
Thanks Brian, is it possible when the interaction window is re-sized the user control to resize with it?

**Comment by brianlagunas** [comment]
Of course.  Just make sure your layout supports it.
