### ISSUE TITLE
Unhandled Exception: Page to remove must be contained on this Navigation Page

### ISSUE THREAD

**Issue by grzegorzbojar** [PrismLibrary/Prism#501]
I am using Prism for Xamarin 6.1.0-pre3. I have A MasterDetail Page with Navigation Page as a Detail + few Views I want to navigate between (in that Navigation Page). I navigate between them using Navigate Command in MasterDetail (Menu in Master Page) using e.g.
`_navigateService.Navigate("NavigationPage/ViewA")`

I have implemented some animations in code behind of xaml page in OnAppearing method like
```
protected override void OnAppearing()
        {
            base.OnAppearing();
            
            Device.BeginInvokeOnMainThread(async () => {
                headerLayout.FadeTo(1, 100, Easing.CubicInOut);
                await contentView.FadeTo(1, 250, Easing.CubicInOut);
            });
```

It looks like that, when I start to switch between these pages to fast (I want to navigate to new page before actual is loaded) I got Exception triggered by Navigation Service of PRISM:

> Unhandled Exception:
> System.ArgumentException: Page to remove must be contained on this Navigation Page
>   at Xamarin.Forms.NavigationPage.RemovePage (Xamarin.Forms.Page page) [0x0004b] in <filename unknown>:0 
>   at Xamarin.Forms.NavigationPage+NavigationImpl.OnRemovePage (Xamarin.Forms.Page page) [0x00006] in <filename unknown>:0 
>   at Xamarin.Forms.NavigationProxy.RemovePage (Xamarin.Forms.Page page) [0x00000] in <filename unknown>:0 
>   at Prism.Navigation.PageNavigationService+<>c__DisplayClass12_2+<<ProcessNavigationForNavigationPage>b__1>d.MoveNext () [0x000ad] in <filename unknown>:0 
> --- End of stack trace from previous location where exception was thrown ---
> [...]

Edit: I think this doesn't happen when using a simulator.

**Comment by brianlagunas** [comment]
Which platform?  The exception is coming from the Xamarin.Forms.NavigationPage.  Prism is simply calling Xamarin's INavigation methods. Which most likely means this is a bug in Xamarin.Forms.  Can you provide a sample that reproduces the problem?

**Comment by brianlagunas** [comment]
Also, if you were to remove your animation, does the issue still occur?

**Comment by grzegorzbojar** [comment]
I am using iOS 9.2 on iPad.

I deleted animations (commented out onAppearing/Disappearing methods) and the **problem still occurs**.
I will try to prepare a solution to reproduce a problem.

**Comment by grzegorzbojar** [comment]
Here is a solution:
https://onedrive.live.com/redir?resid=95445803EE63F494!3008&authkey=!AAd9ZQ9NZQQBpA0&ithint=file%2czip

When I start it in horizontal (so I see links in Master Page) and start switching between View1 and 2 the Exception occurs. I was not able to reproduce it in the simulator (or I am too slow using a mouse, or it is only a problem on the real device).

It only happens if transition animation of pages is enabled. **If navigation is used with animated: false the problem doesn't occur**

**Comment by brianlagunas** [comment]
Have you tried to remove Prism and use XF navigation calls to reproduce it?  All Prism does is call the XF navigation calls, so there isn't anything special going on under the covers.  I don't have an iPad so I will not be able to test your solution.  Chances are this is an XF issue.

**Comment by brianlagunas** [comment]
Try awaiting your navigation calls.

**Comment by grzegorzbojar** [comment]
I've tried awaiting commands - no change. The exception occurs. I will try to use XF without PRISM to reproduce it and let you know!

**Comment by brianlagunas** [comment]
Essentially, based on your description, you are navigating to another view before the other view has been place on the stack.  Hence the 
```
System.ArgumentException: Page to remove must be contained on this Navigation Page
 at Xamarin.Forms.NavigationPage.RemovePage (Xamarin.Forms.Page page) [0x0004b] in :0 
```
When you turn off animations, the view is placed on the stack immediately so you do not encounter this issue.  Why are you trying to navigate between the views so quickly?  So quickly in fact that you can't mouse click quick enough to reproduce on the emulator.

**Comment by brianlagunas** [comment]
This is one of those issues that will be very difficult to debug since you can't reproduce on an emulator.  Ideally, you would debug the source code and find the exact location of the exception.  It would be somewhere in this method

https://github.com/PrismLibrary/Prism/blob/master/Source/Xamarin/Prism.Forms/Navigation/PageNavigationService.cs#L157

If you need to prevent navigating so quickly between pages, then add a Property to your VM called IsNavigating and set that to true before any navigation action and back to false after the navigation has complete (await the navigation call), and then check that property value before allowing another navigation to occur.
