### ISSUE TITLE
Prism.Forms NavigationParameters on INavigationService.GoBack

### ISSUE THREAD

**Issue by tomaswinston** [PrismLibrary/Prism#503]
Hi,

I am using Prism.Forms in my Xamarin.Forms project. In the project I am using the INavigationService. I am using EventAggregator to pass parameters from a 'Navigated To' ViewModel back to the origin. However, looking at the INavigationService code for Prism.Forms [here](https://github.com/PrismLibrary/Prism/blob/master/Source/Xamarin/Prism.Forms/Navigation/INavigationService.cs) it looks as though I should be able to pass NavigationParameters back in the GoBack procedure. 
In my project I am using the latest version i.e. 6.1.0-pre3 but this functionality doesn't seem to be available. Is there a reason for this or what could I be doing wrong?

Cheers

**Comment by bartlannoeye** [comment]
@brianlagunas will be able to tell you more into detail how navigation on Xamarin Forms works for Android and iOS, but on Windows 10 UWP the navigation works by replaying the 'page-1' forward navigation, with the forward navigation parameters. So you'll never be able to pass 'back' parameters without manually tweaking the forward navigation string (which is very dirty).

Since XF + UWP is a possible combination, I don't think we'll add back parameters to navigation, so you'll have to continue using the EventAggregator or another dirty trick like a singleton 'godobject' tracking parameters.

**Comment by tomaswinston** [comment]
Cheers Bart!
I'll continue using, as you suggest, the EventAggregator. However, on further researching/reading of @brianlagunas blog [here](http://brianlagunas.com/prism-for-xamarin-forms-6-2-0-preview/) (correct me if I misunderstood Brian), it appears that passing parameters via the GoBack method call will be supported in Prism Forms 6.2.0  for Xamarin which is fantastic!
T

**Comment by brianlagunas** [comment]
Are you saying that the API isn't there, or that it doesn't work as expected?

**Comment by tomaswinston** [comment]
Hi Brian. Sorry if I wasn't clear. I think I was a little confused myself. I have Prism.Forms 6.1.0-pre3 in my project. When reading your blog I understood that the GoBack with parameters was going to be available in 6.2.0 (now understanding that 6.1.0-pre3 in part of that upcoming major release).

So to answer your question - the GoBack with navigation parameters doesn't appear to be there in 6.1.0-pre3. Also, I am using Xamarin Forms Version 2.1.0.6529


The following is the contents of the Assembly Browser for version info...
```
using System;
using System.Diagnostics;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.Versioning;

[assembly: AssemblyVersion ("6.0.0.0")]
[assembly: Debuggable (DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints)]
[assembly: AssemblyCompany ("")]
[assembly: AssemblyConfiguration ("")]
[assembly: AssemblyCopyright ("Copyright ©  2014")]
[assembly: AssemblyDescription ("")]
[assembly: AssemblyFileVersion ("6.0.1")]
[assembly: AssemblyInformationalVersion ("6.1")]
[assembly: AssemblyProduct ("Prism")]
[assembly: AssemblyTitle ("Prism.Forms")]
[assembly: AssemblyTrademark ("")]
[assembly: NeutralResourcesLanguage ("en")]
[assembly: CompilationRelaxations (8)]
[assembly: RuntimeCompatibility (WrapNonExceptionThrows = true)]
[assembly: TargetFramework (".NETPortable,Version=v4.5,Profile=Profile259", FrameworkDisplayName = ".NET Portable Subset")]
```

and the following is the INavigationService Interface...
```
namespace Prism.Navigation
{
	public interface INavigationService
	{
		//
		// Methods
		//
		void GoBack (bool useModalNavigation = true, bool animated = true);

		void Navigate<T> (NavigationParameters parameters = null, bool useModalNavigation = true, bool animated = true);

		void Navigate (string name, NavigationParameters parameters = null, bool useModalNavigation = true, bool animated = true);
	}
}

```

**Comment by brianlagunas** [comment]
Doesn't look like you are using Pre-3.  If you were, you would see
```
[assembly: AssemblyInformationalVersion("6.1.0-pre3")]
```
In the Prism.Forms assembly information.

**Comment by tomaswinston** [comment]
Ok. Solved. Although I had installed the latest 6.1.0-pre3 Prism.Forms package, the references in my Xamarin Studio Xamarin Forms project hadn't updated to reference the new package and were instead referencing the older package of 6.0.0.

Sorry for wasting ones time and thanks for guiding me to the solution.

T
