### ISSUE TITLE
UWP's EF7 with Sqlite have .net native compile bug in PrismLibrary

### ISSUE THREAD

**Issue by jingliancui** [PrismLibrary/Prism#504]
Hello, there is a serious bug in the prism library .
As the titile,UWP's EF7 with Sqlite have .net native compile bug in PrismLibrary.

I follow the doc here to use ef7 with SQLite:
https://docs.efproject.net/en/latest/platforms/uwp/getting-started.html

And I found it'll throw exception if I retrieve data from db and compile it with release mode(.net native compile ).
It's ok if I didn't use release mode.
After I new a project which is not use the prism. It's no problem with .net native compile.

The detail sample code you can download from my onedrive:
https://onedrive.live.com/redir?resid=C78B7E4A6377EC22!223289&authkey=!ABI9RTDOS1nEbPI&ithint=file%2crar

**Comment by bartlannoeye** [comment]
Hey @jingliancui we'll have to verify if this is a Prism or an EF7 issue. We'll look into this asap, but with //Build being around the corner, you should expect some delay in hearing from us.

**Comment by jingliancui** [comment]
That ok,I expect the //build too and I will wait for the solution by seeing this thread usually.

**Comment by jingliancui** [comment]
Hello @bartlannoeye ,That ok,I expect the //build too and I will wait for the solution by seeing this thread usually.

**Comment by jingliancui** [comment]
Hello@bartlannoeye  :) Have you checked the issue is Prism problem or the EF7 problem?

**Comment by brianlagunas** [comment]
Thanks to @jingliancui for getting a response from the EF team

https://github.com/aspnet/EntityFramework/issues/5517
