### ISSUE TITLE
Question on Navigation to NavigationPage in 6.1.0-pre3

### ISSUE THREAD

**Issue by polepage** [PrismLibrary/Prism#507]
I Navigate to a page using:

`_navigationService.Navigate(new Uri("MyNavigationPage/NewsPage");`

I have to issues when I do that:

1. After the navigation, the the NewsPage is displayed in a NavigationPage, however, there is no back button on the navigation bar.
2. If I navigate to another page from NewsPage using: `_navigationService.Navigate(new Uri("NewsPostPage");`, the NavigationBar simply disapear as I have navigated from a navigation page to a content page.

I guess I am doing something wrong. But I can't find what.
Thanks.

**Comment by brianlagunas** [comment]
1. There won't be a back button on the NavigationPage if there is only one Page on the navigation stack.
2. Set the useModalNavigation optional parameter to false.  In the next preview release this will not be necessary as the navigation service is more intelligent and will automatically handle this.

**Comment by polepage** [comment]
There is still no back button.

`_navigationService.Navigate(new Uri("http://www.mycompany.com/MyNavigationPage/NewsPage", UriKind.Absolute);`

The state of the app should now be a navigation page with my NewsPage as a root. There is a NavigationBar, but obviously no back button.

I navigate to another page from there, using `_navigationService.Navigate(new Uri("NewsPostPage"), useModalNavigation: false);` The state of the app should now be a NavigationPage with a NewsPage as a root and then a NewsPostPage on the stack. The NewsPostPage has a navigation bar as expected, however, there is still no back button.

In fact, I think I see the navigation bar flick (from no back button, to having a back button, to no back button).

Thanks.

**Comment by brianlagunas** [comment]
I am unable to reproduce the issue.  Please provide a sample that reproduces the issue.  Make sure you are navigating from NewsPageViewModel to "NewsPostPage".  Do not navigate from the MyNavigationPage.

Just so you know, you do not have to define a URI object.  You can simply `Navigate("NewsPostPage");`

Also, what platform?

**Comment by polepage** [comment]
I'll try to create a simple case where the issue is reproductible.

Platform is Android (API 25 I think)

Thanks for the rapid feedback :)

**Comment by polepage** [comment]
I extremely simplified the app and I can still reproduce it. Platform is Android (API 23).

Link to the simplified project: https://drive.google.com/file/d/0B769Pp5RdO60cmJ0RjNoc2c4SGc/view?usp=sharing

**Comment by brianlagunas** [comment]
Thanks for the sample, it explains everything.

This is because you have improperly overridden the ConfigureViewModelLocator method.  Navigation is page specific and you cannot simply use the PrismApplicationBase NavigationService.  You must create a navigation service for each page that has been resolved and pass that into your ViewModel ctor.  Otherwise you are always navigating from the App.MainPage.  Also, since you have decided not to use a container such as Prism.Unity.Forms, you have to register your types with the PageNavigationRegistry, or any deep linking will not work.

**Comment by polepage** [comment]
I actually use a container, I just simplified the sample as much as I can.

So it now works. Thanks for your support.
