### ISSUE TITLE
Xamarin Forms Visual Studio template: generic Navigate fails on UWP

### ISSUE THREAD

**Issue by FrancoisM** [PrismLibrary/Prism#508]
Hi,

Create a new Xamarin Forms app using the Prism template.
Change NavigationService.Navigate("MainPage?title=Hello%20from%20Xamarin.Forms"); with
1)  NavigationService.Navigate<MainPage>();
2)  NavigationService.Navigate("MainPage")

Then run on Windows.

2 works but 1 fails with an error about newRoot being null.

**Comment by brianlagunas** [comment]
`NavigationService.Navigate<MainPage>();` Is not supported.  You should never do this.  The generic Navigate method is meant to be used with other object types, most likely a ViewModel.  This also only works when registering your Page using the `RegisterTypeForNavigation<PageType, VIewModelType>();`
