### ISSUE TITLE
Session state service failed (Prism UWP)

### ISSUE THREAD

**Issue by mfe-** [PrismLibrary/Prism#509]
Hi, I got the following exception when the user closed the app 

> Type 'A' cannot be serialized. Consider marking it with the DataContractAttribute attribute, and marking all of its members you want serialized with the DataMemberAttribute attribute. Alternatively, you can ensure that the type is public and has a parameterless constructor - all public members of the type will then be serialized, and no attributes will be required.

So I added the DataContract to the class A and added to all properties the DataMember attribute. But now I get 

> Type 'A' cannot inherit from a type that is not marked with DataContractAttribute or SerializableAttribute.  Consider marking the base type 'Prism.Windows.Validation.ValidatableBindableBase' with DataContractAttribute or SerializableAttribute, or removing them from the derived type.

By the way my Model looks like the following:

```
[DataContract]
public class A : ValidatableBindableBase
{

    private String _Text;
    [DataMember]
    public String Text
    {
        get { return _Text; }
        set { SetProperty(ref _Text, value); }
    }
```

Can we add the DataContractAttribute to the ValidatableBindableBase?

**Comment by jpedretti** [comment]
I'm having the exactly same problem. I was going to report this, but I saw yours.
I analyzed the classes that would have to be modified and it is a little more complicated than simply add the DataContractAttribute .

I copied the code from github and made some nasty changes to make it work.
Added the DataContractAtributte to the BindableBase, PropertySupport and ValidatableBindableBase. So far so god.
Here came the nasty part.

1) At the ValidatableBindableBase, I removed the readonly modifier from the _bindableValidator field.
2) Removed the _bindableValidator  instantiation from the ctor
3) Changed the Errors property to:
```c#
public BindableValidator Errors
 {
    get
    {
        if(_bindableValidator == null)
        {
            _bindableValidator = new BindableValidator(this);
        }
        return _bindableValidator;
    }
}
```
4) Changed all references to _bindableValidator field to Errors property

I do not recommend those changes, but it is what i managed to make work, I think it is better than having an app that can't handle termination.

Please Prism guys, fix this for us.

**Comment by mfe-** [comment]
@jpedretti Thanks for looking into it. I'll try a fix with [IgnoreDataMember]. Anyway, it would be great if @brianlagunas could tell us, if such a workaround would be accepted as pull request.

**Comment by bartlannoeye** [comment]
I'm personally more looking into another approach to fix the session state issue, as it's giving us a lot of headaches with .net native as well. Hopefully I find the time in the upcoming weeks to test it out. If you got a repro on GitHub, feel free to share it, so I have different test cases to confirm my fix once it's implemented.

**Comment by bartlannoeye** [comment]
See #333, as both issues will be tackled together once I find the time.

**Comment by jpedretti** [comment]
I will create the repro and then I'll share it here. Thanks

**Comment by jpedretti** [comment]
Here it is. Hope it helps...
https://github.com/jpedretti/SerializationWorkaround

**Comment by brianlagunas** [comment]
Session state service is being removed from the rewrite of Prism for UWP.
