### ISSUE TITLE
[XF] Unit testing with a mock INavigationService error

### ISSUE THREAD

**Issue by WarBorg** [PrismLibrary/Prism#510]
hello,

I am having an issue with testing my Xamarin Forms project which uses Unity as IoC, I am using NUnit and Moq and everything works well until I hit the INavigationService:

viewmodel code : 

```C#

//code omitted for visibility 

public LoginPageViewModel(IAuthentificationService authentificationService, IConnectivityService connectivityService, IDataUpdateService dataUpdateService, IConfigurationService configurationService, INavigationService navigationService, ILocalRepository<BaseModel> localRepository)
        {
            _authentificationService = authentificationService;
            _connectivityService = connectivityService;
            _configurationService = configurationService;
            _dataUpdateService = dataUpdateService;
           _navigationService = navigationService;

            _localRepository = localRepository;
        }

// code omitted for visibility

private async void DoLoginCommand()
        {
            var navParams = new NavigationParameters();
            navParams.Add("pin", Pin);
            
            if (Pin == "00000000")
            {
                await _localRepository.DropAllTablesAsync();
            }

            await _navigationService.Navigate(nameof(TablePage), navParams);
        }
```

test code : 

```C#
[TestFixture]
    public class Login_View_Model_Fixture
    {
        [Test]
        public void pressing_ok_button_should_navigate_to_new_page()
        {
            //Arrange
            var authentificationServiceMock = new Mock<IAuthentificationService>();
            var connectivityServiceMock = new Mock<IConnectivityService>();
            var dataUpdateServiceMock = new Mock<IDataUpdateService>();
            var configurationServiceMock = new Mock<IConfigurationService>();
            var navigationServiceMock = new Mock<INavigationService>();
            var localRepositoryMock = new Mock<ILocalRepository<Models.BaseModel>>();

            var loginPageViewModel = new LoginPageViewModel(authentificationServiceMock.Object, connectivityServiceMock.Object, dataUpdateServiceMock.Object, configurationServiceMock.Object, navigationServiceMock.Object, localRepositoryMock.Object);
            loginPageViewModel.Pin = "1234";

            //Act
            loginPageViewModel.LoginCommand.Execute();

            //Assert
            navigationServiceMock.Verify(x => x.Navigate(It.IsAny<string>(), null, true, true), Times.Exactly(1));
        }
    }
```

I Mock the navigation service like any other service, but in my ViewModel Test when I hit the Act method to actually execute the login command it gives an error:

> Exception thrown: 'System.MissingMethodException' in mscorlib.dll

>Additional information: Method not found: 'System.Threading.Tasks.Task Prism.Navigation.INavigationService.Navigate(System.String, Prism.Navigation.NavigationParameters, System.Nullable`1<Boolean>, Boolean)'.

If I remove the Navigate method from the command and test for example:

`localRepositoryMock.Verify(x => x.DropAllTablesAsync(), Times.Exactly(1));`

test passes, after I set the Pin to 00000000

I have read a lot about how to do unit testing in general and in Xamarin but very few are about Xamarin Forms so I may be doing something wrong here, I am using a simple class library (not portable) to make my tests. Can you please guide me in how to properly mock the Prims INavigationService ? or tell me if I am doing anything wrong here.

thank you in advance

**Comment by brianlagunas** [comment]
I do not have any experience using Mock.  I would suggest posting this to either the Mock support forums or NUnit as it seems one of those is having a problem.  Have you tried creating your own mock INavigationService class and using that instead?

**Comment by bartlannoeye** [comment]
Navigate is an async method that returns a Task (should have been called NavigateAsync imho). Testing async methods isn't as straight-forward as regular methods, certainly not when starting to mock things as well.

I haven't tested it with NUnit myself, but please try following actions to fix your issue:

- Your test should be a Task, not void (in general, try to avoid async void as this is fire and forget)
- Your mock should be setup to return some Task, [mocking async methods](http://www.carlosble.com/2015/02/mocking-stubbing-async-calls-asyncawait/)

**Comment by brianlagunas** [comment]
Names can be changed :)

**Comment by bartlannoeye** [comment]
@brianlagunas it should ;) but then it's probably a 'breaking' change (which isn't much of an issue, since we're going to 6.2 anyway).

**Comment by WarBorg** [comment]
@bartlannoeye I have read the article but the thing with the Navigate method is that it returns void and in Moq I dont have access to a .Return method if the method I am using in the .Setup returns void

@brianlagunas I will try to implement my own Navigation service and let you know how it goes

thank you everyone

**Comment by bartlannoeye** [comment]
As far as I can see, it returns a [Task](https://github.com/PrismLibrary/Prism/blob/master/Source/Xamarin/Prism.Forms/Navigation/INavigationService.cs#L26).

**Comment by brianlagunas** [comment]
Yeah, I will get some feedback when I give my talk at Evolve.  If I am going to do it, I would need to do it with 6.2.

**Comment by WarBorg** [comment]
@bartlannoeye  hmm, yes you are right, still I don't have a .Return method on my .Setup, any idea why ? apparently the Moq framework shows that the Navigate method returns a null, and I tried implementing my own navigation service but still getting the exact same error when debuging the test

**Comment by WarBorg** [comment]
@brianlagunas @bartlannoeye ok I think I resolved it, the problem was that I was using a wrong version of Prism in my Test project, I just noticed that, I forgot that the latest prism is still in pre-release mode, thank you for all the help

**Comment by WarBorg** [comment]
ok, tests work now but I get a verification error on the Navigate method, I am using this setup:

`navigationServiceMock.Setup(x => x.Navigate(It.IsAny<string>(), null, true, true)).Returns(Task.CompletedTask);`

and the assert:

`navigationServiceMock.Verify(x => x.Navigate(It.IsAny<string>(), null, true, true), Times.Exactly(1));`

but it says test failed, Expected invocation on the mock exactly 1 times, but was 0 times, I went ahead and debuged the test and with a breakpoint it shows clearly that the method is hit

**Comment by jbachelor** [comment]
@WarBorg Did you (or anyone else on this thread) ever find a way to get around this issue? I'm facing the same problem right now... I know the navigationService is working just fine, but since I haven't been able to find a way to await the execution of the command. If there are any resources or samples you might be able to point me too, I would greatly appreciate it.

**Comment by WarBorg** [comment]
@jbachelor unfortunately no, I am still having this issue as well,  it is like the method is completely bypassed in the tests, although the app works fine in debug or release ...

**Comment by jbachelor** [comment]
@WarBorg - If your situation is like mine (and it sounds like it is), then it's probably not that the method is bypassed, but the test finishes before the asynchronous call to navigate is completed. Here's how I finally got around the issue:

Originally, I had a list of buttons on a page, each of which navigated to a different page via delegateCommands in the corresponding viewModel like this:

```
async void NavToRestaurantList()
{
	await _navigationService.NavigateAsync("RestaurantsPage");
}
```
That was changed to try to get us to a more easily awaitable call to test:

```
async void NavToRestaurantList()
{
	await NavigateToPage("RestaurantsPage");
}

public Task NavigateToPage(string targetPage)
{
	return _navigationService.NavigateAsync(targetPage, null, false, true);
}
```

Now, rather than trying to test each of 5 different navigation buttons, we're testing just that "NavigateToPage" method. Each of the DelegateCommands hooked up to the navigation buttons simply pass the desired page name to the NavigateToPage method:

```
[Test()]
public void TestNavigateToPageCallsNavigateAsyncOnce()
{
	Mock<INavigationService> navigationSvcMock;
	Mock<IPageDialogService> pageDialogSvcMock;
	Mock<EventAggregator> eventAggregatorMock;
	MainPageViewModel mainPageViewModel;

	navigationSvcMock = new Mock<INavigationService>();
	pageDialogSvcMock = new Mock<IPageDialogService>();
	eventAggregatorMock = new Mock<EventAggregator>();

	mainPageViewModel = new MainPageViewModel(pageDialogSvcMock.Object,
											  eventAggregatorMock.Object,
											  navigationSvcMock.Object);

	mainPageViewModel.NavigateToPage(string.Empty).Wait();
	navigationSvcMock.Verify(ns => ns.NavigateAsync(It.IsAny<string>(), null, false, true), Times.Once);
}
```


Hope this helps!

**Comment by WarBorg** [comment]
@jbachelor

hmm, ok I see what you did there, I will change my code to minick yours and report if it is working or not 

thx a lot!
