### ISSUE TITLE
ContentDialog and Prism Navigation blowing up my app

### ISSUE THREAD

**Issue by tjones0808** [PrismLibrary/Prism#512]
I am showing a content dialog on one of my sessionstateaware pages, I close the dialog fine and can reopen another on the same page as many times as I want. When I navigate away and come back and try to reopen my dialog, it blows up with this error:

WinRT information: Only a single ContentDialog can be open at any time.
Additional information: An async operation was not properly started.

I have tried numerous things, but it seems whenever I navigate away and come back, somehow the reference to the control is lost and another gets created? 

Here is a little snippet of the problem area:

 if(asyncCommand != null)
                asyncCommand.Cancel();

            var result = new ContentDialogResult();
            if (CanOpenNewDialog)
            {
                
                CanOpenNewDialog = false;
                MyContentDialog.Title = "Homebuyer Options - " + apt.Customer1FullName;
                asyncCommand = MyContentDialog.ShowAsync();

                result = await asyncCommand.AsTask();
            }

**Comment by brianlagunas** [comment]
Did you ever figure this out?

**Comment by tjones0808** [comment]
Yes, the problem was I was subscribing to an event that created the dialog. Whenever I left I wasn't unsubscribing from the event and when navigating back it subscribed again and was giving me the error.

**Comment by brianlagunas** [comment]
Glad you got it figured out
