### ISSUE TITLE
[XF] Rename INavigationService.Navigate to NavigateAsync

### ISSUE THREAD

**Issue by brianlagunas** [PrismLibrary/Prism#513]
Community, I need your input.  I am thinking of renaming the INavigationService.Navigate and GoBack methods to NavigateAsync and GoBackAsync.

This would be a breaking change in the 6.2 release.

Thoughts?

**Comment by bartlannoeye** [comment]
You know my opinion, any Async method must end with Async to make this clear.

**Comment by dansiegel** [comment]
I can get you a pull request for this later today.

**Comment by briannoyes** [comment]
I agree with Bart.

**Comment by brianlagunas** [comment]
Done
