### ISSUE TITLE
[XF] Add support DryIoc dependency injection

### ISSUE THREAD

**Issue by joacar** [PrismLibrary/Prism#517]
Hi all,

Just added DryIoc (Prism.DryIoc.Forms) and wonder if there is any special considerations for handling tests/samples beforing submitting a PR

Should I create sample/test project in the Xamarin solution?

**Comment by brianlagunas** [comment]
Yes, tests should accompany any new functionality like this.  We use xUnit.  Just add the Prism.DryIoc.Forms.Tests project to the current Tests folder.

**Comment by brianlagunas** [comment]
Whoops didn't mean to close.

**Comment by joacar** [comment]
To test the new `PrismApplicationBase` class in the PCL tests I needed to add a new build configuration Test and utialize compiler directives to remove the inheritance to `Xamarin.Forms.Application` to prevent exception "You MUST call Xamarin.Forms.Init()..." during creation of the `PrismApplication` class. Is there any thoughts about this if it should be done differently? The project Prism.Forms.Tests has not yet been updated with the `PrismApplication` so no guidance from that project.

**Comment by brianlagunas** [comment]
Honestly, since I haven't yet started adding tests for that, I haven't even looked into it.  I don't like the idea of adding compiler directives and new build configuration just to support testing.  I'll reach out to Xamarin and see if they have any guidance for testing custom application classes.

**Comment by brianlagunas** [comment]
So Xamarin basically agreed testing anything to do with Application is a pain in the ass.  Get it working, and I will check out the solution and determine if this is something we should adopt in order to test the other DI projects.

**Comment by joacar** [comment]
Thats too bad.. I'll finish up the work and submit the PR. 

Another question regarding testing: wouldn't it be nice to have a test class that could take an instance of PrismApplicationBase and run all tests defined in the Prism.Form.Tests project. That way when creating a Prism.Xyz.Forms project when would simply reference Prism.Forms.Tests and run the test suite for the Xyz.PrismApplication to ensure everything is properly configured regarding ViewModelLocator, INavigationService, IModuleInitializer and others that rely on the Di container that is implemented

**Comment by brianlagunas** [comment]
Done
