### ISSUE TITLE
WPF Prism Module Initialization

### ISSUE THREAD

**Issue by azzamsaziz** [PrismLibrary/Prism#520]
http://stackoverflow.com/questions/36254414/wpf-prism-module-initialization

**Comment by azzamsaziz** [comment]
Can I get an answer from you guys regarding this please? Or is my answer correct?

**Comment by azzamsaziz** [comment]
@brianlagunas .

**Comment by brianlagunas** [comment]
The best way to learn is to debug the source.  Let us know your findings.
