### ISSUE TITLE
x:Bind Data Validation

### ISSUE THREAD

**Issue by Telejka** [PrismLibrary/Prism#524]
I am learning "Universal Windows Platform" and I want to use **x:Bind** for data validation. Could you write somekind of tutorial? I wrote code similar to the "Xaml Brewer" application but I get error at this point:

Xaml Brewer: `<TextBlock Text="{Binding Errors[Location][0]}"`
My App:         `<TextBlock Text="{x:Bind Errors[Location][0]}"`

**Comment by bartlannoeye** [comment]
x:Bind with dictionaries is only available in the preview SDK of the "[Anniverary Update](https://blogs.windows.com/buildingapps/2016/03/30/windows-10-anniversary-sdk-is-bringing-exciting-opportunities-to-developers/)" (v 14295) which was just announced at Build 2016.

**Comment by Telejka** [comment]
Ok, I will use Binding and wait for further updates.
