### ISSUE TITLE
NavigationParameters and TabbedPage

### ISSUE THREAD

**Issue by polepage** [PrismLibrary/Prism#525]
I have a TabbedPage MyTabbedPage with children ViewA and ViewB. When the user navigates between ViewA and ViewB using the built in tabs, is it possible to pass parameters using NavigationParameters?

Thanks.

**Comment by brianlagunas** [comment]
That's not technically navigation, but rather tab changing.  You would have to handle the neccessary tab selection events and pass your parameters there.  You might be able to use a behavior instead to avoid the code behind.
