### ISSUE TITLE
PopupWindowAction throws intermittently

### ISSUE THREAD

**Issue by znakeeye** [PrismLibrary/Prism#526]
Also present in latest sources. Inside PopupWindowAction, the size handler of the associated view might be called before the view has been rendered. This causes PointToScreen to throw InvalidOperationException. Suggested solution below:

http://stackoverflow.com/questions/24802945/find-location-of-a-control-in-wpf-using-pointtoscreen

Loaded event is the key!

**Comment by brianlagunas** [comment]
Can you reproduce this consistently?

**Comment by brianlagunas** [comment]
I have not been able to reproduce this.  I am closing this for now until it is reported again.
