### ISSUE TITLE
Cannot resolve dependency to assembly System.ObjectModel

### ISSUE THREAD

**Issue by AlexPalacio** [PrismLibrary/Prism#527]
Please help me it's been a day now, still can't find any solution about my issue in System.ObjectModel

Error Message:Cannot resolve dependency to assembly 'System.ObjectModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' because it has not been preloaded. When using the ReflectionOnly APIs, dependent assemblies must be pre-loaded or loaded on demand through the ReflectionOnlyAssemblyResolve event.

I already used the System.Runtime, and AssemblyBinding in app.config, still no luck.
I'm using DynamicDirectoryModuleCatalog, every time I insert a new module in Modules folder that has a Prism reference the main application crashes. How to solve this? Thanks in advance.

My current Framework is .net 4.6.1 using Prism 6.1.0

**Comment by AlexPalacio** [comment]
I found the culprit, it's the BindableBase, but I don't have any idea to fix it.

**Comment by brianlagunas** [comment]
I'm not sure why BindableBase would be causing any issues at all.  It literalyl only has INPC in it.  Although this is not an issue with Prism, if you provide a sample I will take a look when I have time.
