### ISSUE TITLE
static ModuleCatalog.CreateFromXaml no longer exists and no substitute seems to exist

### ISSUE THREAD

**Issue by Shawn1874** [PrismLibrary/Prism#528]
```
protected override IModuleCatalog CreateModuleCatalog()
        {
            return ModuleCatalog.CreateFromXaml(new Uri("/PrismWpfApplTemplate;component/ModulesCatalog.xaml",
                                                        UriKind.Relative));
        }
```

In the past creating the ModuleCatalog from xaml was simple.  Now it can't be done because CreateFromXaml doesn't exist within the class that exists within the new namespace.    I see another issue about needing a website, which I can't really help with but I don't understand why this method of creating the module catalog was removed.  It would be better to have a forum to ask questions but I don't see such a thing in existence at this time.

**Comment by brianlagunas** [comment]
It has not been removed.

https://github.com/PrismLibrary/Prism/blob/master/Source/Wpf/Prism.Wpf/Modularity/ModuleCatalog.cs#L120

**Comment by Shawn1874** [comment]
I ran into this issue, which I forgot about.
http://stackoverflow.com/questions/11139166/prism4-creating-catalog-from-xaml-createfromxaml-doesnt-compile/36456808#36456808

**Comment by brianlagunas** [comment]
Thanks for sharing. Hopefully others will find this helpful.
