### ISSUE TITLE
[XF] Viewmodel not located

### ISSUE THREAD

**Issue by 1NESLEiN** [PrismLibrary/Prism#529]
Hi, 

I might be bad at searching or having trouble figuring out what my problem is, but here goes...

I have an application for Android, iOS, and Windows Phone. Currently debugging on Android. I have a "MainNavigationPage" which is just used to have my different views (ContentPages) hosted in here. When launching the app, the user gets prompted to log in, which is done in my "LoginPage", the viewmodel gets located just fine, and navigates me to the next view. Now here comes the problem I'm having! Whenever I get navigated to the next view from "LoginPage" my viewmodel for some reason does not get binded to this view, hence "Title" doesn't get binded and/or my commands are not working. I have the "AutowireViewModel="True"" on my second page.

I've tried creating a new project with the exact same structure (but no API service calls), and here, it works just fine. I just can't figure out what's causing this problem. My views are all registrered for navigation aswell. I would rather not have to create a whole new project...

Thank you.

**Comment by brianlagunas** [comment]
There isn't enough information here to help find the issue.  If it works in a brnad new project, but not your current one, this leads me to believe that you are not following the proper VIewModelLocator conventions.  Make sure your namesspaces are Namespace.Views.ViewName and Namespace.ViewModels.ViewNameViewModel.
