### ISSUE TITLE
MEFBootstrapper needs to handle/override ConfigureViewModelLocator()

### ISSUE THREAD

**Issue by karlfl** [PrismLibrary/Prism#53]
When using MEF the VML it is falling back to the default Reflection code in the ViewModelLocationProvider instead of using the MEF to instantiate the view model class.  To follow the pattern of the other DI bootstrappers, the MEFBootstrapper should override the ConfigureViewModelLocator() and also call this method in the MEFBootstrapper.Run() override.

**Comment by karlfl** [comment]
Closing issue.  I believe this is redundant based on a quick review of the code [Brian](https://github.com/brianlagunas) checked in for resolution of [Issue #51](https://github.com/PrismLibrary/Prism/issues/51).  Specifically the changes referenced by *"I want to use DI in my ViewModel constructors like I would for any other service."*

**Comment by brianlagunas** [comment]
What platform are you targeting?  If WPF, then #51 has nothing to do with your issue.  #51 was about the Xamarin.Forms support.  What version of the VML are you using?  In the current codebase, The base bootstrapper for WPF uses the ServiceLocator to resolve the VM so it won't matter if you are using Unity or MEF, it should work just fine.  If you are using the public NuGets packages for WPF, then this is not included in that version, and you will need to override the ViewModelLocationProvider yourself.

**Comment by karlfl** [comment]
Targeting WPF using MEF for DI.  I'm only experimenting with the Prism 6.0 base at this time.  I may be mistaken in the issue#, but there was code added (that I'd overlooked earlier) to the Prism.Bootstrapper main class to use ServiceLocator in the ConfigureViewModelLocator() method.  I suspect there still might be a tweak needed in the MefBootstrapper, but not sure exactly what yet.  My gut says that the MEFBootstrapper isn't using the ServiceLocator to resolve the ViewModels when using the VML. So it's defaulting back to using Reflection and causing exceptions with my test code.  I'll continue looking/testing and report back if I find anything concrete requiring a change.
