### ISSUE TITLE
Prism.Forms Preview 4 release notes missing

### ISSUE THREAD

**Issue by dansiegel** [PrismLibrary/Prism#531]
The link on the NuGet package for Prism.Forms pre4 points to:
https://github.com/PrismLibrary/Prism/wiki/Release-Notes--Jan-10,-2016

There is currently no update with the release notes for the pre4 release.

**Comment by brianlagunas** [comment]
Yeah, I just forgot.  I have so much going on right now :)

Just added nav improvements and these

* Modularity
* Launch Modal from MasterDetail

**Comment by brianlagunas** [comment]
Updated the link in the package

**Comment by WarBorg** [comment]
@brianlagunas so what does the InitializeModules() do ? cause I see I need to override it but no documentation on how to actually use it.

thank you in advance

**Comment by dansiegel** [comment]
@WarBorg have you checked out the [sample app](https://github.com/PrismLibrary/Prism/blob/master/Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld/App.cs)? The [solution](https://github.com/PrismLibrary/Prism/tree/master/Sandbox/Xamarin/HelloWorld) contains a module library, and the HelloWorld App shows how to use the override InitializeModules and how to call it from in your code. Hope that helps.

**Comment by WarBorg** [comment]
@dansiegel thank you,  but I don't need modularisation in my app at this time, from what I see on github the nuget packages for unity and ninject,  for that matter,  have not been updated, it is that or I am missing something again :) 

cheers

**Comment by brianlagunas** [comment]
There is a new package for Unity called Prism.Unity.Forms that will be used going forward.  Since XF added support for UWP, and we already had a different version of prism for UWP, we had to create a different package for XF Unity.  Right now it is preview, but after Evolve I will be publishing an official release.

**Comment by brianlagunas** [comment]
Also, if you don't need modularity, then you don't need to override InitializeModules.  Only override this method if you are going to use modules.

**Comment by dansiegel** [comment]
@brianlagunas InitializeModules is an abstract method in ApplicationBase, so it has to be overridden. Perhaps this could be made virtual so that it's only being overridden in projects that actually use Modules. Just a thought

**Comment by brianlagunas** [comment]
@dansiegel you should not be deriving from ApplicationBase unless you are creating your own Container project.  Your project should only use one o fthe PrismApplication classes from the unity or Ninject container projects.

**Comment by WarBorg** [comment]
@brianlagunas thank you, the new package was what I was looking for because it has the implementation for that abstract class which was laking from the former package, you should have mentioned it somewhere that a new package should be used :D

**Comment by brianlagunas** [comment]
Yeah, I'm traveling right now and was in a hurry to get the next preview out.  I'll be sure to fix all the docs and make sure the message is clearer after Xamarin Evolve at the end of this month.

**Comment by dansiegel** [comment]
@brianlagunas just to clarify, I'm not actually deriving from ApplicationBase that's just where it originates. It looks like maybe this has been fixed now, but when I updated from 3 to 4 and got the module support I had to provide an implementation for InitializeModules. Safe travels.

**Comment by WarBorg** [comment]
@dansiegel that was my issue as well but installing the new package Brian was talking about (https://www.nuget.org/packages/Prism.Unity.Forms/6.2.0-pre4) fixes the problem because it already implements that method so you don't have to :D
