### ISSUE TITLE
Prism.Wpf compatible with Visual Studio 15 Preview?

### ISSUE THREAD

**Issue by ryancole** [PrismLibrary/Prism#532]
I'm not extremely familiar with Nuget and everything, so this may not have anything to do with Visual Studio 15 Preview, and the latest version of Nuget.

I just installed the VS 15 Preview and am trying to install Prism.Wpf, via Nuget. I get an error saying that it cannot locate System.Windows.Interactivity in the GAC, and then fails to install.

Any ideas here?

Edit: I just wanted to mention that I'm pretty sure on Visual Studio 2015 Community Edition that the Prism.Wpf install seemed to work without issues.

**Comment by brianlagunas** [comment]
I haven't tested VS15 Preview, but the System.Windows.Interactivity is ships with the Blend SDK.  It could be that the Preview doesn't include this assembly yet.  For now, there is an unofficial NuGet package for it that you can use.  We will be updating the Prism.Wpf NuGet package to include the assembly soon.

**Comment by ryancole** [comment]
@brianlagunas sorry to bug, but do you know which package is the go-to package for that? I seem to see quite a bit of mentions of the lib, but not sure if there's a nuget pkg just for that lib? Thanks!

**Comment by ryancole** [comment]
Meh, I just went ahead and installed the whole Blend SDK. Covers that dependency.

**Comment by brianlagunas** [comment]
cool. The nugets should be updated after the Xamarin Evolve event.
