### ISSUE TITLE
Region.RequestNavigation using Ninject needs binding the view to 'object'

### ISSUE THREAD

**Issue by JorreHolland** [PrismLibrary/Prism#534]
I was having the darnest time getting regions and RequestNavigation working for Ninject, until I finally found out that the RegionNavigationContentLoader is trying to resolve for 'object' whereas I was registering my views with their type, eg. 

```
kernel.Bind<MyView>().ToSelf().Named(typeof(MyView).Name);  // fails using RequestNavigation
kernel.Bind<object>().To<MyView>().Named(typeof(MyView).Name); // works using RequestNavigation
```

Since there's not too much in the way of documentation about using Ninject with PRISM, and I'm kinda new to the whole MVVM/DI concept anyways, it took me a little while to figure it out. 
To make things easier, I've created these extensions that match the Unity/MEF way of doing it using Container.RegisterTypeForNavigation. 

```
public static class NinjectExtensions 
{ 
        public static void RegisterTypeForNavigation<T>(this NinjectModule ninjectModule)
        {
            ninjectModule.Bind<object>().To<T>().Named(typeof(T).Name);
        }
        public static void RegisterTypeForNavigation<T>(this IKernel kernel)
        {
            kernel.Bind<object>().To<T>().Named(typeof(T).Name);
        }
}
```
Feel free to use as you see fit without restrictions and/or include in your code as you like. .

**Comment by brianlagunas** [comment]
Just submit a PR :)
