### ISSUE TITLE
[XF] Master Detail page icons not working properly?

### ISSUE THREAD

**Issue by gviddy** [PrismLibrary/Prism#541]
Hi there,
I have followed your Master/Detail example. When i change pages I am getting some unexpected behavior.

For Example when the app loads I navigate with:
NavigationService.Navigate("MyMasterDetail/MyNavigationPage/MainPage", animated: false);

Then when I try to change the detail page I navigate with:
NavigationService.Navigate("MyNavigationPage/SettingsPage");

The detail page loads correctly however I am seeing the following on iOS and Android with respect to the navigation menu (hamburger/back button).

I am noticing that on iOS that the hamburger menu icon flashes and disappears. This results in being on a new details page and unable to navigate.

On Android it works but I always see a quick flash of the back button and then it changes to the hamburger icon.

When using Xamarin.Forms without PRISM these work as expected with no flashing or disappearing of the hamburger menus.

Am I changing pages correctly?

**Comment by gviddy** [comment]
I see the problem.

PageNavigationService.cs - ProcessNavigationForMasterDetailPage()

`var nextSegmentType = PageNavigationRegistry.GetPageType(UriParsingHelper.GetSegmentName(nextSegment));`
`if (detail.GetType() == nextSegmentType)`

The above is always true so you never set Detail to the new detail page. If I comment out this entire block of code then the following code block is used and is always ok. I am unsure what the above code is supposed to be doing. :)

I also tried your sandbox example and your master detail example is also broken on iOS.

**Comment by brianlagunas** [comment]
First off, what version of Prism are you using?  Also, are you using FormsAppCompatActivity for Android?

**Comment by brianlagunas** [comment]
Also, which ViewModel are you navigating from when you call "MyNavigationPage/SettingPage"?

**Comment by gviddy** [comment]
I am running the sandbox example you have for Xamarin Forms. I downloaded it from github about 5 days ago along with the full prism source. So the latest is what I am using. I also notice it in pre-3 and pre-4.

If you run your sandbox example on iOS and change views from the master menu then you lose your back/menu button and will be stuck on whichever view you change to.

it's a result of the code I posted above. I guess to understand it better what is the above code supposed to do? What does checking the segment type supposed to avoid?

**Comment by brianlagunas** [comment]
I see what you mean now about the arrow changing to an arrow and back to the hambuger menu quickly.  This didn't used to happen.  Something must have changed in Xaamrin.Forms.  I'll have to look into it.

The reason we check to see the next segment is because we want to see if the target page is the same as the current detail page.  If it is, there is no need in creating a new instance, instead we can improve performance and reuse the current detail page.  But, if that detail page is a NavigationPage, we have to first navigate to the next page and then remove the root, which is the actually cause of the arrow behavior.

I am on the road now and don't have access to an iOS device for testing, but it shouldn't be doing anything modally so you should still be able to show the hamburger menu and navigate normally on iOS.  If not, then Xamarin broke something with their latest update.

**Comment by gviddy** [comment]
Awesome. Thanks for looking into this for us.  :)

**Comment by brianlagunas** [comment]
Okay, so I have met with Xamarin on this issue, and they have a couple of ideas to fix this.  I will let you know what we come up with.  In the mean time, I can fix the part where the arrow shows up, but the hamburger menu still navigates the rotation.  Is this an acceptable compromise until the complete fix is in?

**Comment by gviddy** [comment]
Hey Brian,
Yes that sounds good. As long as that fixes the disappearing hamburger/menu item on iOS. Android still works OK however iOS loses the menu item up top so you can then never recall the master menu. So if that fixes that problem then we will be very happy indeed. :)

Easy test is to run your demo example on iOS (with latest stable XForms) and you can see you get locked onto a view with no way to change to another page.

Again thanks for looking into this.

**Comment by brianlagunas** [comment]
Here is the Xamarin bug to follow its status: https://bugzilla.xamarin.com/show_bug.cgi?id=41038

**Comment by dansiegel** [comment]
Looks like [PR #209 for Xamarin Forms](https://github.com/xamarin/Xamarin.Forms/pull/209) which was just merged should fix this.

**Comment by brianlagunas** [comment]
Sweet!
