### ISSUE TITLE
UWP apps fail Prelaunch WACK requirement

### ISSUE THREAD

**Issue by MartinZikmund** [PrismLibrary/Prism#542]
It seems there is an issue with Prism.Windows that causes apps using it fail UWP WACK Prelaunch test.

Steps to reproduce:
1) create a simple UWP app
2) add Prism.Unity
3) create a HomePage View
4) in OnLaunchApplicationAsync navigate to HomePage
5) run the app once
6) launch Windows App Cert Kit
7) run Prelaunch test from the Deployment and launch tests section

This will fail with no specific reason given. The same test passes when Prism is not present.

**Comment by mfe-** [comment]
You have to deal with this by yourself. 

Try the following:

```csharp
        protected override Task OnLaunchApplicationAsync(LaunchActivatedEventArgs args)
        {
            if (args.PrelaunchActivated == true)
            {
                //your preloading stuff
            }
            return base.OnInitializeAsync(args);
        }
```

https://msdn.microsoft.com/en-us/windows/uwp/launch-resume/handle-app-prelaunch

**Comment by NickDarvey** [comment]
That solution didn't work for me, @mfe-. I'm not returning OnInitializeAsync though, should I be? (The samples don't.)

````C#
protected override Task OnLaunchApplicationAsync(LaunchActivatedEventArgs args)
{
            if (args.PrelaunchActivated)
            {
                Debug.WriteLine("Prelaunching");
                return Task.FromResult<object>(null);
            }

            else
            {

                NavigationService.Navigate("Main", null);
                Window.Current.Activate();
                return Task.FromResult<object>(null);
            }
}
````

@MartinZikmund, did you find a solution?

**Comment by MartinZikmund** [comment]
@NickDarvey , are you running a Windows 10 Insider preview build? I have found out, that the failing prelaunch happened on the build I was running even for a completely blank app, so I guess it is an issue with the Preview.

**Comment by bkaankose** [comment]
Prelaunch test will always fail for Insider builds. Microsoft stated that. There's nothing wrong with your code or project. WACK will always fail on your Insider Build, but will be approved by the Store.

**Comment by brianlagunas** [comment]
Thanks for the information.  I will consider this resolved.
