### ISSUE TITLE
[XF+UWP]The binary Prism.Unity.Forms.dll is built in debug mode.

### ISSUE THREAD

**Issue by JGrzybowski** [PrismLibrary/Prism#543]
When submitting UWP application using Prism for Xamarin.Forms I get such error in certification verification:
`The binary Prism.Unity.Forms.dll is built in debug mode.`
Which prevents me from submitting app for the store. :/ 
Can you do something about it in next nuget release?

**Comment by brianlagunas** [comment]
Yeah, it's a preview so it wasn't built in release mode.  After Xamarin Evolve at the end of the month an RTM build will be pushed, and will be in release mode.

**Comment by brianlagunas** [comment]
I am going to be pushing another preview until XF 2.3 comes out of preview.  I will make sure to build it in Release mode this time.

**Comment by brianlagunas** [comment]
Just release the preview 5 update.  Everything was built in release mode :)

https://www.nuget.org/packages/Prism.Unity.Forms/6.2.0-pre5
