### ISSUE TITLE
[XF] Android, poping a ModalPage does not hit the OnNavigatedTo of the MasterDetail Page

### ISSUE THREAD

**Issue by WarBorg** [PrismLibrary/Prism#544]
hello,

so I have the following Android app, it starts with a Master/Detail page as root and I want to push a Modal Page as a Login screen if the user is not logged in, otherwise I want to push a different page, the Login page works but when I use the GoBack method from the modal Login page the  OnNavigatedTo method of the MasterDetail is not hit, I think I have read someting similar in #537 , is it connected ?

App
```C#
NavigationService.Navigate("MyMasterDetailPage");
```
MyMasterDetailPageViewModel
```C#
public override void OnNavigatedTo(NavigationParameters parameters)
{
    if (parameters.ContainsKey("isUserLoggedIn") && (bool)parameters["isUserLoggedIn"] == true)
    {
        _navigationService.Navigate("MainPage", null, true);
    }
    else
    {
        _navigationService.Navigate("LoginPage", null, true);
    }
}
```
LoginPageViewModel
```C#
var navParams = new NavigationParameters();
navParams.Add("isUserLoggedIn", true);

_navigationService.GoBack(navParams, true);
```

PS: Have not tested on iOS yet but I will ASAP

**Comment by brianlagunas** [comment]
I see you are not providing a detail page for your MasterDetail in your navigation link.  Is your Detail hardcoded in the initial MasterDetail?

**Comment by brianlagunas** [comment]
Yes, this is related to #537 and is a regression bug on Xamarin's part.  I have reported this to them, and I hope to have a fix soon.

**Comment by WarBorg** [comment]
@brianlagunas yes my details page is hardcoded, I see I hope it gets fixed soon, thank you

**Comment by brianlagunas** [comment]
Okay, I have spoken to Xamarin, and they changed the way the modal stack works.  They no longer include the Application.MainPage in the navigation stack.  I will have to handle this case manually in Prism now.

**Comment by WarBorg** [comment]
ok, so how will this change impact the modal navigation in Prism ?

**Comment by brianlagunas** [comment]
It won't change anything.  I just have to manually handle the case of navigating back from the root (MainPage) of the app.  It's a pain in the ass for sure.
