### ISSUE TITLE
How to remove parameters from NavigationContext.Parameters collection in Prism 6?

### ISSUE THREAD

**Issue by EugeneBuzin** [PrismLibrary/Prism#545]
How to remove all added parameters, or some added parameters, or one added parameter from NavigationContext.Parameters collection? It doesn't have method for removing parameter or parameters. How to do this deletion in WPF MVVM application in Prism 6? Is this operation possible at all?

**Comment by brianlagunas** [comment]
No, there is no API to remove parameters from NavigationParameters.  NavigationParameters is a temporary object meant pass state from one VM to another.
