### ISSUE TITLE
How to bind ItemTapped property of ListView in ViewModel for navigating detail page?

### ISSUE THREAD

**Issue by sasavranic** [PrismLibrary/Prism#546]
Hello,
Trying to figure out how to bind ItemTapped of ListView for navigating detail page with Prism.
I try with DelegateCommand but I have an error:

> Exception is: XamlParseException - Position 15:7. No Property of name ItemTapped found

**Comment by brianlagunas** [comment]
Please post these types of questions on StackOverflow using our "Prism" tag.

Also, there is not enough information in your question and doesn't really relate to Prism.  Be sure to include your platform, and include the code for your view and ViewModel when you post your question.

http://stackoverflow.com/questions/tagged/prism

**Comment by sasavranic** [comment]
Ok, opened: http://stackoverflow.com/questions/36600193/how-to-bind-itemtapped-property-of-listview-in-viewmodel-for-navigating-detail-p
