### ISSUE TITLE
Handle back button on windows phone 10

### ISSUE THREAD

**Issue by mun24** [PrismLibrary/Prism#547]
How to capture back button on UWP 10 .I tried but it is not  working.

Also If I navigate from one frame to second frame, how can we navigate from second frame to first frame via Back button.

Thanks

**Comment by boodoolak** [comment]
Add reference Windows Mobile Extensions for the UWP

**Comment by bkaankose** [comment]
You can check my answer in this issue.

https://github.com/PrismLibrary/Prism/issues/553

**Comment by brianlagunas** [comment]
Thanks @bkaankose
