### ISSUE TITLE
EventAggregator is not extensible

### ISSUE THREAD

**Issue by alsiola** [PrismLibrary/Prism#549]
The dictionary used to store events in EventAggregator (line 14) is marked as private, preventing easy extensibility of the class.  If it were changed to protected then we could inherit from EventAggregator and, for example, provide a different means of accessing events.

**Comment by bartlannoeye** [comment]
Nothing prevents you from using an own implementation of IEventAggregator. The EventAggregator is rather small and implemented to take care of locking and UI dispatching. If this doesn't fit your needs, chances are real you shouldn't be inheriting from it.
