### ISSUE TITLE
useModalNavigation parameter on INavigationService.Navigate() is always true

### ISSUE THREAD

**Issue by michaelnero** [PrismLibrary/Prism#55]
Hi I'm writing a mobile app on Xamarin, and I'm having trouble using `INavigationService`. It seems that no matter how I call `INavigationService.Navigate()`, the `useModalNavigation` parameter is true. For example, I'm currently calling it like this:
```csharp
this.navigationService.Navigate ("SignInPage", useModalNavigation: false);
```

But I've also tried:
```csharp
this.navigationService.Navigate ("SignInPage", null, false, true);
```

And:
```csharp
this.navigationService.Navigate ("SignInPage", parameters: null, useModalNavigation: false, animated: true);
```

Is anyone else having this issue? I'm not sure if this is something specific with Xamarin or if it's the way the interface is defined.

**Comment by brianlagunas** [comment]
Interesting... Are you sure it is still true event though you pass in false?  Are you getting an exception?  Is it not navigating?  Is your root page a NavigationPage?  Do you have a sample you can share?

**Comment by brianlagunas** [comment]
Also, are you using the latest 5.7.0-pre1 version that was just released?

**Comment by michaelnero** [comment]
Hi @brianlagunas, yes, I'm using 5.7.0-pre1. I'm 100% certain that the value is always true even if I pass false. The reason I'm getting an error is that I have a custom renderer that's trying to access the `PageRenderer.NavigationContoller` property, which is null when using `INavigation.PushModalAsync()`.

Interestingly, when I do this, it works like I expect it to:
```csharp
((Prism.Navigation.PageNavigationService)this.navigationService).Navigate ("SignInPage", useModalNavigation: false);
```

A co-worker mentioned this blog post to me. Think it'll help?
http://patrick.lioi.net/2012/08/29/a-c-feature-that-shocks-the-conscience/

**Comment by brianlagunas** [comment]
Interesting indeed!  I haven't run into this during testing.  I am going to see if I can reproduce this issue.  Dang, that would suck to have to drop the use of optional parameters.   Would you mind sharing your sample?  You can email it to me if you can share publically.

**Comment by brianlagunas** [comment]
I was able to duplicate it!  I duplicated it on a GoBack call.  Very freaking strange.  Looks like this is an issue with the language feature.  I will have to create overloads instead of use optional parameters.  I am going to run this pas the father of C# and see what he has to say.

**Comment by michaelnero** [comment]
I just got the note about sending my sample to you, but it looks like you don't need it. Thanks for taking a look at it!

**Comment by brianlagunas** [comment]
Actually I may nee it after all :)

**Comment by brianlagunas** [comment]
Okay, it seem I had another mismatch against the interface for Navigate as well.  Looks like when I did some refactoring, I got the "animated" and "useModalNavigation" parameter positions mixed up.  That may have cause the issue.

I thought interfaces were supposed to protect us from this stuff!  I guess not when using optional parameters.

**Comment by brianlagunas** [comment]
Okay, I think I got it fixed.  Go ahead and download the newest Nuget package Prism.Forms 5.7.0-Pre2.  It may take a moment for the package to show up in search results.

Let me know fi that fixes your issue.

**Comment by michaelnero** [comment]
That fixed it. Thanks again!

**Comment by brianlagunas** [comment]
Great!  Thanks for reporting it, and be sure to provide any feedback and feature requests as you see fit.

**Comment by Clement-Jean** [comment]
@brianlagunas I think I have this issue too, my _navigationService.GetNavigationUriPath(); always tell me: NavigationPage?useModalNavigation/MyPage , is that normal ? Because I'm having problem to go back to the previous view.

**Comment by brianlagunas** [comment]
@Clement-Jean if you only have one view on your NaviagtionPage then there is nothing to go back to, unless your NavPage is being shown modal, which means you'll have to force a modal GoBackAsync(useModalNavigation = true)

**Comment by Clement-Jean** [comment]
The is that my full path is

MasterDetail/navigationpage/dictiona

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by brianlagunas** [comment]
Then if you want to go back from PageB to PageA, you have to force a modal goback.

Honestly, not sure why you have your stack like that, why not just push PageB ontot eh root NavigationPage?

**Comment by Clement-Jean** [comment]
Ok I will try for the goback.

The point with the stack is doing something like:

- Click on list entry (I can see the master page)
- Showing a new page (I can't see the master page, just back button)
- Click back button (I can see the master page)

I'm totally new to prism navigation so I might do stupid stuff here 🤕

**Comment by brianlagunas** [comment]
You mean you're new to Xamarin.Forms navigation. Prism doesn't do anything special and uses the XF navigation API directly :)

Then it sounds like you might be adding another NavigationPage to your stack... something like calling "NavigationPage/PageB" from your PageA.  This is incorrect. You're already within a NavPage.  No need to add another.

**Comment by Clement-Jean** [comment]
Yes, I meant prism functions for navigation.

The thing is that I don't add it, the NavigateAsync does it by itself, I just do a ``` _navigationService.NavigateAsync("PageB");```

How can I solve this ?

**Comment by brianlagunas** [comment]
Either there is an issue with your code, or a bug in the GetNavigationUriPath logic.  Please submit a separate issue with an app the reproduces your issue.
