### ISSUE TITLE
finetuning Prism/Mvvm/ErrorsContainer.cs

### ISSUE THREAD

**Issue by lorenzo-a** [PrismLibrary/Prism#551]
I started studying & using the PRISM library for my current project.

One of the things I noticed was the following remark in the ErrorsContainer class (SetErrors method):

        // Remarks: 
        //     If a change is detected then the errors changed event is raised.

I looked at the implementation to see what exactly was meant with "a change is detected".

In the current implementation it seems like there are some cases where the event is raised when not necessary 

f.e.
- new validationresults available but they match the current ones
- no new validationresults available AND  no currentvalidationresults 

Would it be useful to fine-tune this code? In practice it will not make that much difference if the getErrors has no heavy load but the implementation could apply the concept " is changed " in a stricter/clearer way?

@briannoyes : I contacted Brian Lagunas and he told me to create an issue and tag you.

**Comment by dvorn** [comment]
- no new validationresults available AND no currentvalidationresults 

In this case event is not raised.

- new validationresults available but they match the current ones

This one is hard even to formulate what to expect: the new/old events are List<T>.  How to compare objects of type T?  Does the order of elements in the List matter?

**Comment by brianlagunas** [comment]
Thanks for the idea, but we aren't going to be doing this anytime soon.  This is related to #45
