### ISSUE TITLE
DelegateCommand isn't working with XF SearchBar

### ISSUE THREAD

**Issue by tmdaly** [PrismLibrary/Prism#559]
When I navigate to my ContentPage that has a DelegateCommand bound a Xamarin.Forms SearchBar's SearchCommand, it throws a "Specified cast is not valid"

<SearchBar Text="{Binding SearchText}" SearchCommand="{Binding SearchCommand}" />

public DelegateCommand SearchCommand { get; set; }

private void Search()
{
    //Execute search
}

But if I change it to an ICommand from a DelegateCommand it works.

**Comment by brianlagunas** [comment]
What platform and what version or Prism?  I am unable to duplicate this.  DelegateCommand is just an ICommand.  So there is no difference between declaring your command like this:

public ICommand SearchCommand ...

vs.

public DelegateCommand SerchCommand ...

**Comment by brianlagunas** [comment]
I'm going to assume you got this working.  If not be sure to let me know.

**Comment by tmdaly** [comment]
Sorry it's taken me so long to respond. A busy day at work and internet connection problems.
I see what you are saying but that is not what I'm experiencing. I went over my code again and didn't find the issue so I put together a test project. I'd appreciate it if you could take a look.
Visual Studio 2015Xamarin.Forms Shared appPrism.Forms v6.1.0-pre4Prism.Unity.Forms v6.2.0-pre4
And I'm testing it using the VS Emulator 5" Marshmallow (6.0.0) XXHDPI Phone (Android 6.0 - API 23)

**Comment by tmdaly** [comment]
This is the test project that I used  to reproduce the problem with navigating to a page that has a SearchBar bound to a delegatecommand.

[SearchTest.zip](https://github.com/PrismLibrary/Prism/files/248070/SearchTest.zip)

**Comment by brianlagunas** [comment]
This is really weird!  I see it happen in your app, and that it originates from the Xamarin.Forms.Core assembly.  I was testing off of the latest preview, so maybe they fixed a bug since this.  I am going to be publishing a new update soon, and hopefully this will fix it for you.
