### ISSUE TITLE
DelegateCommandBase.CanExecuteChanged EventHandler seems to get collected and so never fires on Xamarin

### ISSUE THREAD

**Issue by michaelnero** [PrismLibrary/Prism#56]
This is another odd behavior I'm afraid. What's happening is that when binding a `Button.Command` property to a `DelegateCommand`, the `EventHandler` reference that the `DelegateCommandBase` registers with the `WeakEventHandlerManager` gets collected. So, `DelegateCommandBase.RaiseCanExecuteChanged()` has no effect. Otherwise, I have no idea why it's being collected, but again, this maybe something off with Xamarin.Forms -- I wouldn't be surprised at this point.

Removing the usage of the `WeakEventHandlerManager` from `DelegateCommandBase` fixes the problem, but I'm not sure if that's what you're after. It maybe noteworthy that other libraries that provide an `ICommand` implementation don't use `WeakReference`s.

Consider the following ViewModel:

```csharp
public class SignInPageViewModel : BindableBase
{
	private readonly DelegateCommand signInCommand;

	private string email;
	private string password;

	public SignInPageViewModel ()
	{
		this.signInCommand = Workify.Commands.DelegateCommand.FromAsyncHandler (this.ExecuteSignIn, this.CanExecuteSignIn);
	}

	public DelegateCommand SignInCommand {
		get { return this.signInCommand; }
	}

	public string Email {
		get { return this.email; }
		set { this.SetProperty (ref this.email, value); }
	}

	public string Password {
		get { return this.password; }
		set { this.SetProperty (ref this.password, value); }
	}

	private async Task ExecuteSignIn ()
	{
		// Do something
	}

	private bool CanExecuteSignIn ()
	{
		return !string.IsNullOrWhiteSpace (this.Email) && !string.IsNullOrWhiteSpace (this.password);
	}

	protected override bool SetProperty<T> (ref T storage, T value, string propertyName = null)
	{
		if (base.SetProperty (ref storage, value, propertyName)) {
			this.signInCommand.RaiseCanExecuteChanged ();
			return true;
		} else {
			return false;
		}
	}
}
```

And the following ContentPage:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<ContentPage
	xmlns="http://xamarin.com/schemas/2014/forms"
	xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"

	xmlns:prism="clr-namespace:Prism.Mvvm;assembly=Prism.Forms"
	prism:ViewModelLocator.AutowireViewModel="True"

	x:Class="Views.SignInPage">

	<StackLayout>
		<Entry Text="{Binding Email, Mode=TwoWay}" />
		<Entry Text="{Binding Password, Mode=TwoWay}" />
		<Button Text="SIGN IN" Command="{Binding SignInCommand}" />
	</StackLayout>

</ContentPage>
```

What's supposed to happen is that the Sign In button is enabled as the Email and Password entries are filled out. But this doesn't happen.

**Comment by brianlagunas** [comment]
Interesting.  This must be something different with Xamarin.Forms memory management.  This DelegateCommand is used in all other XAML platforms, so I will have to be very careful with any changes made here.  Let me take a look.  First I will need to duplicate it.  I will take what you have and see if that is enough.

**Comment by michaelnero** [comment]
After thinking about it, you may be able to remove `DelegateCommand` altogether for Xamarin. Xamarin already provides an `ICommand` implementation `Xamarin.Forms.Command`. `DelegateCommand` does provide `FromAsyncHandler()` which I like, but there isn't another compelling reason to keep it around for that platform. Thoughts?

**Comment by brianlagunas** [comment]
It exists in the core PCL of Prism for all other platforms, and adds familiarity to current Prism users coming to Xamarin.Forms.  I will hunt down why it's being collection as soon as I duplicate it.

**Comment by brianlagunas** [comment]
This definitely is an issue.  It looks like Xamarin.Forms memory management is very aggressive.  This one will be a tough issue to solve.  Thanks for reporting this.

**Comment by brianlagunas** [comment]
Alright.  I made the fix and updated the Nuget package.  Go ahead and upgrade to Prism.Forms 5.7.0-Pre3.

Oh, and forgot to mention Prism also has a CompostieCommand and IActiveAware support, which are other compelling reasons to keep DelegateCommand around :0)

**Comment by michaelnero** [comment]
Ah, CompositeCommand. I hardly use it, but I'm glad it's there when I do need it!

Works like a charm. Thanks!

**Comment by Phmager** [comment]
I saw you removed the WeakEventHandlerManager from Prism, but won't this introduced a memory leak, why it was first introduced?
http://compositewpf.codeplex.com/workitem/4065?ProjectName=compositewpf

**Comment by brianlagunas** [comment]
No.  This was originally introduced because of a binding bug in WPF that would cause an ICommand to never be released.  Other platforms did not have this issue.   Instead, since the other platforms are much more aggressive with memory management, the weak references were being collected and breaking the bindings altogether.  So we had to remove it.

**Comment by Phmager** [comment]
But I exactly mean if someone is using prism in WPF. Is that no more possible?

**Comment by brianlagunas** [comment]
It's still possible in WPF, but it mainly happens when binding to command within DataTemplates on a touch device that creates automation peers.  As far as I know, this has not been fixed in WPF.
