### ISSUE TITLE
[XF] Tabbed page to tabbed page navigation issue

### ISSUE THREAD

**Issue by WarBorg** [PrismLibrary/Prism#560]
so, I have a tabbed page in witch I have three hardcoded children and I navigate to it like so :

```C#
            NavigationService.Navigate($"{nameof(NavPage)}/{nameof(TabbedPage1)}");
```

in one of the children of the tabbed page I have a button that navigates to a second tabbed page, witch has two hardcodded children, like so:

```C#
            _navigationService.Navigate(nameof(TabbedPage2));
```

the first tabbed page has a nice navigation bar with title and everything, but the second tabbed page not anymore, it's like the navigating to a modal page

PS tested only on Andorid 6.0 for the moment 

is this a known issue having some relations with the other navigation issues you are facing right now ?

thank you

**Comment by brianlagunas** [comment]
Remember, navigation is always relative to the page's VM you are calling navigate from.  This means you are calling navigate from some page inside a TabbedPage, not the actual TabbPageViewModel.   You should try setting the useModalNavigation parameter to false.

```
_navigationService.Navigate(nameof(TabbedPage2), useModeNavigation: false);
```
This will force a PushAsync

**Comment by WarBorg** [comment]
@brianlagunas yes I know, but the VM from where I am sending the command is set on the tabbed page not on the children page, I tried with the false param but still same issue

**Comment by brianlagunas** [comment]
Just so I am clear you... at app OnInitialized you are doing:

```
NavigationService.Navigate("MyNavPage/MyTabbePaged1");
```

Then on TabbedPage1ViewModel you are calling:

```
_navigationService.Navigate("TabbedPage2", useModeNavigation: false);
```

And it's not working?

**Comment by brianlagunas** [comment]
Also, how are you connecting the command from a Page in the TabbedPage.Children collection to the VM for the TabbedPage?  Also make sure you are setting the Title of your Pages.

**Comment by brianlagunas** [comment]
Actually, I found the issue:

https://github.com/PrismLibrary/Prism/blob/master/Source/Xamarin/Prism.Forms/Navigation/PageNavigationService.cs#L217

We are forcing all navigation from a TabbedPage to be modal.  I didn't see a scenario in which you would want to navigate directly from a TabbedPage within a NavigationPage.  I assumed all navigation would occur from a Page within the Children collection.  Let me think about this.

**Comment by WarBorg** [comment]
to the earlier posts you wrote the answer was yes

so if I used the navigation command from one of the children pages vm's that would work fine?  I see you have fixed it so I am waiting for a new preview release  :D

thank you

**Comment by guiwaltricke** [comment]
@brianlagunas Here we are looking for some feature too.

We have MasterDetailPage -> NavigationPage -> TabbedPage (With 3 Children).

When the ContentPage thats is a child of TabbedPage execute NavigateAsync to the next page thats need to open inside the navigation of the tab is opening like modal page.... the right way is open inside my tab navigation.

**Comment by brianlagunas** [comment]
The navigation service **does not** create tabs and/or add them to the TabbedPage.Children collection.  Adding tabs is not navigation.  If all you want is to navigate to the next page and have it be part of the NavigationPage navigation stack, then pass the useModalNavigation = false parameter in the NavigateAsync call.

**Comment by guiwaltricke** [comment]
@brianlagunas what we want is create a TabbedPage.Children with NavigationPage to navigate inside my tab... how we do this?

**Comment by brianlagunas** [comment]
Simple, just add a NavigationPage with a child ContentPage in your TabbedPage XAML or code-behind.  Then whenever you navigate from the ContentPage, it will automatically navigate within the NavigationPage

**Comment by guiwaltricke** [comment]
This happens: 
![589e13fa4e47480aaa808a419979ded7 1](https://cloud.githubusercontent.com/assets/7662711/18358369/1700bc94-75cb-11e6-99af-eaf8429ac026.png)

as you can see, appears 2 navigations

`<TabbedPage.Children>
    <NavigationPage Title="Entrada" Icon="{Binding Icone}" >
      <x:Arguments>
        <entrada:EntradaPage />
      </x:Arguments>
    </NavigationPage>
    
    <moduloMensagens:SaidaPage Title="Saída" Icon="{Binding Icone}"  />
    <moduloMensagens:HistoricoPage Title="Histórico" Icon="{Binding Icone}" />
    
  </TabbedPage.Children>`

**Comment by brianlagunas** [comment]
Yes, because you are using a navigation page to wrap your MasterDetailPage.Detail  TabbedPage, and you also have a NavigationPage nested inside a tabbed page.  So this is to be expected.  You just need to hide one of your navigation bars.

**Comment by guiwaltricke** [comment]
@brianlagunas we tried yesterday but this do not work like you can see:
```
<TabbedPage.Children>
    
    <NavigationPage Title="Entrada" Icon="{Binding Icone}" HasNavigationBar="False">
      <x:Arguments>
        <entrada:EntradaPage />
      </x:Arguments>
    </NavigationPage>

    <moduloMensagens:SaidaPage Title="Saída" Icon="{Binding Icone}"  />
    <moduloMensagens:HistoricoPage Title="Histórico" Icon="{Binding Icone}" />
    
  </TabbedPage.Children>
```

![Image](http://image.prntscr.com/image/05c1daa615794e71bbe25a3ad3dae5ab.png)

**Comment by brianlagunas** [comment]
You don't set the property on the NavigationPage.  You set it on the child page.  Since you have two navigation pages, you need to set the property on either the TabbedPage, which I would recommend, or on your EntradaPage.  I suggest reading up on the Xamarin.Forms docs to get a better understanding on how navigation works within XF.
