### ISSUE TITLE
ViewModels aren't bound to View if in different namespace

### ISSUE THREAD

**Issue by SmartyP** [PrismLibrary/Prism#564]
Took me a while to figure this one out.. Basically if you are on a MainPage, with an associated MainPageViewModel, and then try to navigate to a TestPage with an associated TestPageViewModel, it will fail to bind if the namespaces of the two view models are not the same.

Ex:
MainPageViewModel is defined in the MyApp.ViewModels namespace
TestPageViewModel is defined in the MyApp namespace

NavigationService.Navigate("TestPage") will navigate to the TestPage, but there will be no bound data context and bindings will not resolve. Changing the TestPageViewModel to be in the MyApp.ViewModels namespace instead will fix the issue. There aren't any resolve errors put into the application output.

**Comment by SmartyP** [comment]
I made a repro here:
https://www.dropbox.com/s/gsklahbxqalbvlc/PrismTestApp.zip?dl=0

If you run it after restoring packages you'll see a navigate button that takes you to a second page, and it only shows 1 label (because bindings are not resolving). If you change the namespace of the TestPageViewModel.cs to 'PrismTestApp' instead of 'PrismTestApp.ViewModels' and run again the bindings will resolve and you'll see 2 labels on the secondary page you nav to.

**Comment by brianlagunas** [comment]
Yes, there is a standard convention that is documented here:

https://github.com/PrismLibrary/Prism/blob/master/Documentation/WPF/40-ImplementingtheMVVMPattern.md#creating-the-view-model-using-a-view-model-locator

You can change these conventions if you need to.  Check out this blog post describing how to change them:

http://brianlagunas.com/getting-started-prisms-new-viewmodellocator/
