### ISSUE TITLE
[XF] TabbedPage Navigation events not fired 

### ISSUE THREAD

**Issue by adriangh83** [PrismLibrary/Prism#565]
Hi there,
I am trying to use a TabbedPage with Prism. When I navigate from tab to tab using tap gestures in android simulator there are no navigation events fired in children pages VMs. There is only the OnNavigatedTo event fired when I navigate from App.cs to a specific tab using a deeplink. 
I'm running the latest prism.forms version found in the Sandbox folder. I downloaded it from github today along with the full prism source
Thanks.

**Comment by brianlagunas** [comment]
Changing tabs in a TabbedPage is not a navigation function.  I would suggest creating a behavior that hooks into the selected tabbed changed event of the TabbedPage and invoke the methods from there.
