### ISSUE TITLE
Prism Forms - No Menu Icon after navigating to Master Detail Page

### ISSUE THREAD

**Issue by tomaswinston** [PrismLibrary/Prism#566]
Hi,

Not sure if it is related to this other issue [here](https://github.com/PrismLibrary/Prism/issues/541) but when I navigate to a page of my master detail page I no longer get the hamburger icon. e.g.

I am using:

- Xamarin.Forms 2.3.0.38-pre2 
- Prism for Xamarin.Forms 6.1.0-pre5.

This is how I navigate :

`_navigationService.NavigateAsync("MyMasterDetailPage/MyNavigationPage/MyMainPage", animated: true);`

Instead I just get the "Title" of the MasterDetailPage. Is it a known issue or should I revisit my code? 

Thanks

Tomás

**Comment by brianlagunas** [comment]
This is the same issue as #541.  This only happens on iOS right?

**Comment by tomaswinston** [comment]
Hi Brian. That's right. Or at least that is all I can attest to at the moment.

**Comment by brianlagunas** [comment]
Here is the Xamarin bug to follow its status:  https://bugzilla.xamarin.com/show_bug.cgi?id=41038

**Comment by dshchodro** [comment]
Hey Brian. I've faced the same issue and debugged Prism code to find an answer. Looks like the problem occurs only if you use NavigationPage for 2 or more children of MasterDetailsPage.  
For example,
if we navigate to "MyMasterDetailPage/MyNavigationPage/MyMainPage"
and then from master details menu we navigate to "MyNavigationPage/MyAnotherView"
then there's no hamburger icon (or a menu text) 
BUT if we use different navigation pages then everything OK.
For example,
if we navigate to "MyMasterDetailPage/MyNavigationPage/MyMainPage"
and then from master details menu we navigate to "MyDifferentNavigationPage/MyAnotherView"
Then everything works like a charm. Looks like navigation page is not removing from stack and Prism continuing to use the same and that's is why problem occurs. 
Hope it helped

**Comment by brianlagunas** [comment]
@dshchodro that is exactly the issue.  If you look at the bug linked above, you can see what it takes to reproduce this bug in Xamarin Forms.

**Comment by tomaswinston** [comment]
Hi,

I hope I am wrong but it seems that this is still not working or at least not working once again...

I am running Xamarin Forms 2.3.1.114 and Prism.Forms 6.2.0. 

I downloaded the HelloWorld demo from the sandbox and the Menu icon just appears as "Default" which is the Title of the ContentPage in the MyMasterDetail.xaml View.

Tomás

**Comment by brianlagunas** [comment]
Sadly, you're not wrong.  This is a confirmed bug in Xamarin.Forms:

https://bugzilla.xamarin.com/show_bug.cgi?id=42548

Waiting for them to fix this one again.

**Comment by tomaswinston** [comment]
Pity. Oh well. Waiting game again! 

Thanks Brian. Love Prism.Forms! 👍

**Comment by brianlagunas** [comment]
Well, now this only happens when using AppCompat mode.  If you don't use AppCompat it will work as expected.

**Comment by tomaswinston** [comment]
Does that mean it should work on iOS?
