### ISSUE TITLE
view state and viewmodel state gets null after page navigation

### ISSUE THREAD

**Issue by yeasin90** [PrismLibrary/Prism#567]
I am using Prism 6 with UWP. I have a button in MainPage.xaml that redirects to DashboardPage.xaml. Upon navigation to DashboardPage, I am saving the view state in DashboardPage.xaml.cs :
```
protected override void SaveState(Dictionary<string, object> pageState)
        {
            base.SaveState(pageState);

            pageState["viewState"] = 123;
        }
```
and saving view model state in DashboardPageViewModel.cs :
```
public override void OnNavigatingFrom(NavigatingFromEventArgs e, Dictionary<string, object> viewModelState, bool suspending)
        {
            base.OnNavigatingFrom(e, viewModelState, suspending);
        }

[RestorableState]
        public string Name
        {
            get { return _name; }
            set { SetProperty(ref _name, value); }
        }
```
From Dashboard, I went back to MainPage.xaml by pressing topbar back button. When I navigate back to DashboardPage.xaml from MainPage, all my saved sates gets null (view state and viewmode state). Which means, in the below code of DashboardPage.xaml.cs
```
protected override void LoadState(object navigationParameter, Dictionary<string, object> pageState)
        {
            if (pageState == null)
            {
                return;
            }

            base.LoadState(navigationParameter, pageState);

            if (pageState.ContainsKey("viewState"))
            {
                var data = pageState["viewState"].ToString();
            } 
        }
```
**pageState** is found null.

And, for view model state in DashboardPageViewModel.cs :
```
public async override void OnNavigatedTo(NavigatedToEventArgs e, Dictionary<string, object> viewModelState)
        {
            base.OnNavigatedTo(e, viewModelState);
        }
```
**viewModelState** is null

**Comment by bartlannoeye** [comment]
Closing as this got solved on [SO](http://stackoverflow.com/questions/37115091/pagestate-and-viewmodelstate-is-null-on-page-navigation-in-uwp).
