### ISSUE TITLE
Where are the docs?

### ISSUE THREAD

**Issue by rob8861** [PrismLibrary/Prism#568]
Does Prism have docs?
Can someone please share the link to the docs? I can only find release notes.

Thanks

**Comment by bartlannoeye** [comment]
The documents for WPF and Xamarin Forms are [part of the repository](https://github.com/PrismLibrary/Prism/tree/master/Documentation). For Windows 10, please look at those for [8.1](https://msdn.microsoft.com/en-us/library/windows/apps/xx130643.aspx), as we didn't have time yet to migrate those. They mostly apply to Windows 10 as well with some minor changes.

**Comment by rob8861** [comment]
Thank you very much. I missed that somehow.

cheers,
