### ISSUE TITLE
Workflows for OAuth2 authentication using Prism and Xamarin forms?

### ISSUE THREAD

**Issue by sstorie** [PrismLibrary/Prism#569]
I have started to experiment with Prism after seeing Brian's recent talk at Evolve (which was fantastic). I am trying to get a basic OAuth2 example working, and am struggling a little with whether that is supported out of the box with an app that derives from `PrismApplication`.

I was using Auth0's Xamarin library and I could get things working to the point where their library opened a WebView to authenticate my account, but when it attempted to pass control back to my app I started getting null reference errors and crashes. None of my app code seems to be called before the crash happens.

In previous attempts at this without using Prism my application's `OnResume` method would be called when the WebView closed, and I could go from there. With prism though I get this exception from the Auth0 library:

> {System.NullReferenceException: Object reference not set to an instance of an object
  at MyApp.Mobile.Droid.Services.Auth0LoginService+<LoginAsync>d__2.MoveNext () [0x000b6] in C:\MyApp\source\MyApp.Mobile\MyApp.Mobile.Droid\Services\Auth0LoginService.cs:32 }
    base: {System.SystemException}

...and `OnResume` is never called, so I don't know how to proceed, or if using Prism with a WebView is a supported workflow. My next attempt was to use OAuth2 with Azure Mobile Services to see if this is a WebView problem, or maybe something with how Auth0's component works.

Here's all I am doing within my Android project to trigger Auth0's component:

        public async Task<User> LoginAsync()
        {
            try
            {

                // 'this' could be a Context object (Android) or UIViewController, UIView, UIBarButtonItem (iOS)
                var auth0User = await _authClient.LoginAsync(Forms.Context);

                var user = new User
                {
                    Auth0Token = auth0User.Auth0AccessToken,
                    IdentityToken = auth0User.IdToken,
                    RefreshToken = auth0User.RefreshToken,
                    Sub = auth0User.Profile["sub"].ToString(),
                    Email = auth0User.Profile["email"].ToString(),
                    GivenName = auth0User.Profile["given_name"].ToString(),
                    FamilyName = auth0User.Profile["family_name"].ToString(),
                    Name = auth0User.Profile["name"].ToString(),
                    Locale = auth0User.Profile["locale"].ToString()
                };

                return user;
            }
            catch (Exception ex)
            {
                throw ex;
            }

Has anyone got OAuth2 working with Xamarin Forms and Prism?

**Comment by sstorie** [comment]
Interestingly, if I update my code to swallow the `NullReferenceException` specifically the code continues to run and works as expected. So I don't think this is any particular issue with Prism (not that I did initially), and with this work-around I can continue to investigate the library.

**Comment by brianlagunas** [comment]
As you probably guessed, Prism doesn't do anything special to the base Application class.  You still have access to OnResume, you just have to override it like you normally would.  For the most part, if you can get something working in a normal XF Application, it will work in a Prism application.

**Comment by sstorie** [comment]
Yep, I am seeing that now. I'm new to Xamarin and Xamarin Forms, but Prism seems to provide answers to many of the things I was finding frustrating (I've been doing client/server .NET and web development for 10+ years):

1. Easy ViewModel based navigation
2. Clean binding between the views and view models with IoC

I watched your Evolve talk last night and it was like a light bulb finally went off and I could see the way forward with many of these "issues". I finally feel like I can use the methods I'm used to, but can also focus on using standard Xamarin Forms stuff. Thanks for the response and especially for creating and talking about this library. I'm excited about using Xamarin again :)
