### ISSUE TITLE
[XF] How to control MasterDetailPage.IsPresented when navigating

### ISSUE THREAD

**Issue by brianlagunas** [PrismLibrary/Prism#570]
I need to think of a way to control the MasterDetailPage.IsPresented property when navigating within a MasterDeatilPage.

To add a little more context; right now the navigation service automatically sets the MasterDetailPage.IsPresented to false.  This makes sense 90% of the time.  Click to navigate, close the Matser.  Where this doesn't make sense is if you are on a tablet, and want the Master to always be open.  Essentially, you need to be able to make a check like this:

```
if (Device.Idiom == TargetIdiom.Tablet)
    //set IsPresented to true for navigation because we always want it open
```

Some ideas:
* A static property. Maybe something like NavigationOptions.MasterDetailPage.IsPresented. Set the value before calling NavigateAsync. Not sure I like this because of the static class. Does this impact testing?
* A special NavigationParameter. Maybe something like "MasterDetailPage.IsPresented=value" (name to be decided). Don't like that it's not very discoverable, but shouldn't impact testing and as long as we have docs should be okay.
* Use an interface.  Then have the PageNavigationService check the value of the IsPresented property value and use that. Maybe called IMasterDetailPage?
* other?

The approach must not add to the INavigationService.NavigateAsync API.

What is the community's thoughts? Ideas?

**Comment by jcaramello** [comment]
Hi, I'm trying to use the event aggregator in order to notify the change when I navigate to other page, I mean, when the master detail page is created I subscribe to an custom event for listen changes in the detail section, so, then when I navigate to other page, I trigger the event.

in my xaml I have:
...
  <MasterDetailPage.Master IsPresented="{Binding IsPresented}">
 ...
In the view model of my master page i have:
...
 public OtherViewViewModel(IEventAggregator eventAggregator)
        {
            _eventAggregator = eventAggregator;
            _eventAggregator.GetEvent<OtherViewDetailChangeEvent>().Subscribe(OnDetailChange, ThreadOption.UIThread, true);
        }

        private void OnDetailChange(string msg)
        {
            IsPresented = false;
           //OnPropertyChanged(nameof(IsPresented));
        }

And finally in the handler of the navigation command:

 private async void Navigate(string name)
        {          
            await _navigationService.NavigateAsync(name);
            _eventAggregator.GetEvent<OtherViewDetailChangeEvent>().Publish(name);
        }

but I can't make it works :(, for some reason the subscriber handler for the event it never execute.

**Comment by brianlagunas** [comment]
@jcaramello Could you please create a new issue and delete your comment as it doesn't pertain to the current topic.

**Comment by bkaankose** [comment]
Since it's not likely, maybe an optional parameter (false by default) can be the solution for it. Developers will not need to update their current code when updating Prism. It's kind of a discoverable comparing to the special NavigationParameter, but will change the NavigateAsync.

Using static won't be a bigger problem when testing but since it's static, we always hate it.

Maybe a method that sets IsPresented value based on latest navigated page key?

I will update the discussion when more ideas come up.

**Comment by brianlagunas** [comment]
I don't want to add an optional parameter to the NavigateAsyc method for a couple of reasons.  The biggest is that we are adding a parameter that only controls a very specific property of a very specific page type in a very specific scenario.

Another thing to think about it if this method should be application wide, or on a per method call basis.  In other words, should this be a global setting that if respected by all MasterDetailPages in the app, or should this be re-evaluated each time NavigateAsync is called from a MasterDetailPage?

**Comment by dansiegel** [comment]
I'm trying to think of a reason you would have more than one MasterDetailPage... I would love to hear the use case someone has where they need that. 

The more I think about this issue, the less I think it's as simple as just exposing that property. For example, maybe I'm on a phone and IsPresented can be false. But maybe I'm on a tablet in landscape and IsPresented can be true, but then the user goes and rotates the screen to portrait and suddenly I want to change IsPresented to false; Given that scenario I'm thinking you need something like:

```cs

public interface IMasterDetailPage
{
    bool IsPresented { get; set; }
}

public enum DeviceOrientation
{
    Landscape,
    Portrait
}

public interface IDeviceOrientationAware
{
    void OnDeviceRotation( DeviceOrientation deviceOrientation );
}

```

Which you could then implement like:

```cs

public class MyPageViewModel : IDeviceOrientationAware
{
    IMasterDetailPage _masterDetailPage { get; }

    public MyPageViewModel( IMasterDetailPage masterDetailPage )
    {
        _masterDetailPage = masterDetailPage;
    }

   public void OnDeviceRotation( DeviceOrientation deviceOrientation )
   {
       if( Device.Idiom == TargetIdiom.Tablet && 
           deviceOrientation == DeviceOrientation.Landscape ) 
       {
           _masterDetailPage.IsPresented = true;
       }
       else
       { 
           _masterDetailPage.IsPresented = false;
       }
   }
}

```

This assumes two things of course. First that OnDeviceRotation gets called anytime there is a rotation event, and second it should probably get called around the time we navigate. 

If we're talking about supporting the possibility of multiple MasterDetailPages then to be friendly I would say something like: 

```cs

public interface IMasterDetailPage
{
    string Name { get; set; }
    bool IsPresented { get; set; }
}

// Return a specific MasterDetailPage
[IMasterDetailPage( name = "SomePage" )]
public class MyPageViewModel
{
     public MyPageViewModel( IMasterDetailPage masterDetailPage ) { }
}

// Return the last MasterDetailPage on the navigation stack
public class MyPageViewModel
{
     public MyPageViewModel( IMasterDetailPage masterDetailPage ) { }
}

// Return any MasterDetailPages on the navigation stack
public class MyPageViewModel
{
     public MyPageViewModel( IEnumerable<IMasterDetailPage> masterDetailPages ) { }
}
```

**Comment by brianlagunas** [comment]
Great scenario!

This issue is that the solution must be implemented by the INavigationService.  So the approach must expose a hook of sorts to control what the INavigationService does in this scenario.  I guess the INavigationService could look for an interface and use the value off of that to determine if it should be presented or not.

So option number 3: Use an interface

**Comment by dansiegel** [comment]
If it has to be controllable from the INavigationService then I would expose it through a querystring parameter like "MyPage?IMasterDetailPage.IsPresented=true". The NavigationService could then just resolve the IMasterDetailPage and set the property.

**Comment by brianlagunas** [comment]
The INavigationService just has to read the value at the time of navigation, not set the property.  So we could just use the query string approach to send the value to the navigation service at the time of navigation, or we could use an interface that the navigation service can use to read the value when it's ready to navigate.

**Comment by bkaankose** [comment]
We must provide multiple MasterDetailPage support no matter what IMO. Using an interface seems pretty legit, I vote for that.

**Comment by brianlagunas** [comment]
If we use an interface, it needs to be used on both the MasterDetailPage or the ViewModel.  This means that given we have an interface defined like this:
```
public interface IMasterDetailPage
{
    bool IsPresented { get; }
}
```
Then the MasterDetailPage must implement this interface explicitly like this:
```
    public partial class MyMasterDetail : MasterDetailPage, IMasterDetailPage
    {
        public MyMasterDetail()
        {
            InitializeComponent();
        }

        bool IMasterDetailPage.IsPresented
        {
            get { return Device.Idiom != TargetIdiom.Phone; }
        }
    }
```
This is because the base MasterDetailPage already has a property called IsPresented.  Obviously we can't use that instance of the property because it is tied to the MasterDetailPage.Master behavior.  If you did not implement this interface explicitly then it would not work as expected and the result of the IsPresented property would always return **true**.

Does anyone think this would be an issue?

**Comment by powerdude** [comment]
I don't think i like the idea of having to provide an implementation of the page just to provide the interface.  Your example doesn't seem like it needs to be on the page class since it uses nothing from that class to provide the value.

**Comment by brianlagunas** [comment]
Well, you have to have an implementation of the page if you have a MasterDetailPage in your app.  This sample is simply showing how you would use this interface **if** you placed it on the MasterDetailPage instead of the ViewModel.

**Comment by brianlagunas** [comment]
I think we should name this interface something different.  Since this interface is only used for controlling the IsPresented during navigation, it probably shouldn't be called IMasterDetailPage.

What does everyone thing about:
```
public interface IMasterDetailPageNavigationOptions
{
    bool IsPresentedAfterNavigation { get; }
}
```

Any other name suggestions?

**Comment by bkaankose** [comment]
I think IMasterDetailPageOptions is more suitable for this. This interface has only 1 at the moment and it's about Navigation but we might use this interface for different future scenarios.

**Comment by brianlagunas** [comment]
I like that name.  How do you feel about me placing this in the Prism.Navigation namespace, or do you think this should go into a different namespace.  If so, what namespace makes sense to you?

**Comment by dansiegel** [comment]
I think that's a good name. Considering it's all about a navigation event, I would tend to think that the Prism.Navigation namespace makes a lot of sense. If we end up adding to it, to support some future scenario, we can always move it, should that make sense to do in the future.
