### ISSUE TITLE
[XF] I cannot resolve the navigationService unless if ViewModelLocator.AutowireViewModel="True"

### ISSUE THREAD

**Issue by tombby11** [PrismLibrary/Prism#571]
Have been stuck for days ...  and then I found what was the issue 

I have two pages one in case of tablet and the other in case of phone . Since they have different names then using ViewModelLocator.AutowireViewModel to share the same view model as a binding context does not work . So for this case I am using the classic binding context, as i did not want to create a viewmodel copy for each page. 
My problem was when I run it gives me an error saying **"no parameterless constructor defined for this object prism"**  The reason of this error is that the viewModel has a contructor that expects a navigationService. 
To solve this error i have to remove the navigation service as an argument , but then I need it so i can navigate with it .

**Comment by bartlannoeye** [comment]
Please ask these types of questions on StackOverflow, we'll answer them there.

**Comment by brianlagunas** [comment]
As discussed in this SO thread:  http://stackoverflow.com/questions/37239147/prism-for-xamarin-forms-i-cannot-resolve-the-navigationservice-unless-if-viewmo/37243428#37243428

Currently it is too cumbersome to provide a different VM that requires the INavigationSevice to the View using the ViewModelLocator.

**Scenario**
As a developer I want to use one ViewModel if I am on a phone than, and provide a different ViewModel if I am on a tablet and have the INavigationService injected properly

```
if (Device.Idiom == TargetIdiom.Tablet)
    //use TabletViewModel for MainPage
else
    //use PhoneViewModel for MainPage
```
Does this accurately represent your issue?

**Comment by tombby11** [comment]
I will rephrase the problem/s here 
**Use case:**
_As a developer I want to use one page if I am on a phone and a different page if I am on a tablet. In any case the same viewModel should be used ._ 

**Code Snippet** 
```
if (Device.Idiom == TargetIdiom.Tablet)
    //use MainPageViewModel for TabletMainPage
else
    //use MainPageViewModel for PhoneMainPage
```

**Details and Workaround:**
Since the ViewModelLocater uses NameConventions to locate the correct View model for the view, two views with different names cannot have the same ViewModel. 
 - TabletMainPage expects to have TabletMainPageViewModel 
 - PhoneMainPage expects to have PhoneMainPageViewModel 

However in my case both  TabletMainPage  &  PhoneMainPage   should get MainPageViewModel.

To overcome this problem, I could assign BindingContext of each page to an instance of MainPageViewModel, although this not so "Prismatic"  but it it kind of OK . 
The problem with this workaround occurs as the constructor of the MainPageViewModel expects a NavigationService interface 

```
public MainPageViewModel(INavigationService navigationService)
{
...
}

```

Having this constructor will blow an exception with a message: 

> "no parameterless constructor defined for this object prism"

This means the viewModel in my case should be instantiated using a parameterless contructor. But if so how would i pass the navigationService to it ?

**Comment by brianlagunas** [comment]
So right now how are you switching out your pages?  Can you provide a code snippet?

**Comment by dansiegel** [comment]
@tombby11 have you thought about implementing it something like: 

```cs
public abstract class MainPageViewModelBase
{
    // Some implementation
}

public class TabletMainPageViewModel : MainPageViewModelBase
{
    // Don't redo any code you don't need to...
}

public class PhoneMainPageViewModel : MainPageViewModelBase
{
   // Don't redo any code you don't need to...
}
```

**Comment by brianlagunas** [comment]
YOU can now do this:

```
if (Device.Idiom == TargetIdiom.Tablet)
{
    Container.RegisterTypeForNavigation<TabletMainPage>("MainPage");
    ViewModelLocationProvider.Register<TabletMainPage, MainPageViewModel>();
}
else
{
    Container.RegisterTypeForNavigation<PhoneMainPage>("MainPage");
    ViewModelLocationProvider.Register<PhoneMainPage, MainPageViewModel>();
}
```
