### ISSUE TITLE
Windows Projects reference wrong Publisher/Project for Xamarin Forms Project Template

### ISSUE THREAD

**Issue by dansiegel** [PrismLibrary/Prism#574]
Template Pack for Xamarin Forms, Windows Projects have publisher information as "joaqu" with a project name of "FPCL.{Platform}" in the Package.appxmanifest.

**Comment by brianlagunas** [comment]
Great catch!  Not sure what we should set the default to.  Let me look at the Visual Studio default templates and see what they are doing

**Comment by brianlagunas** [comment]
Fixed!
