### ISSUE TITLE
Add logging for Failed Navigation

### ISSUE THREAD

**Issue by dansiegel** [PrismLibrary/Prism#576]
Currently if the NavigationService fails to resolve a particular page for any reason, the page is silently ignored and the next page in the navigation path is resolved. This should be updated so that problems are logged and can more easily be found in the app's output. This would provide significant debugging enhancements.

**Comment by brianlagunas** [comment]
Well actually, if the page is not created, it should throw an exception.

https://github.com/PrismLibrary/Prism/blob/master/Source/Xamarin/Prism.Forms/Navigation/PageNavigationService.cs#L339

**Comment by dansiegel** [comment]
After a little more digging it looks like the root cause of this is a Microsoft.Practices.Unity.ResolutionFailedException. The exception is getting completely swallowed up on iOS making it extremely difficult to debug. Android does at least expose the exception so you can see both the exception and the type being resolved.

**Comment by brianlagunas** [comment]
That's weird.  So maybe we should add logging as well as throw the error?  Should we only log if in debug mode, or any more in the case in which someone has provided their own custom logger.

**Comment by dansiegel** [comment]
I would say probably the best bet would be to just log it. I can see some scenario where someone has some custom logger and may be streaming it to an analytic's service where they want the issue logged regardless of whether or not they're debugging.

**Comment by dansiegel** [comment]
Any thoughts about updating ILoggerFacade to add a new log function which can directly take an Exception?

I was thinking something like

```cs
void Log( Exception e, Priority priorty = Priority.High );
```

then update the PageNavigationService to wrap the navigation call like

```cs
try
{
    await NavigateAsync(typeof(T).FullName, parameters, useModalNavigation, animated);
}
catch(Exception e)
{
    _logger.Log( e );
    throw;
}
```

Output:

```
SomeException: This is a message from the exception. 
Priority: High
StackTrace: Some StackTrace
```

**Comment by brianlagunas** [comment]
No because this would be a breaking change to all existing WPF app.
