### ISSUE TITLE
[XF] Feature Request: Xamarin Form Project Templates in Xamarin Studio

### ISSUE THREAD

**Issue by dankraus** [PrismLibrary/Prism#577]
I brought this up to @brianlagunas at Evolve a few weeks ago but thought it'd be worthwhile to surface it here for tracking.

The Visual Studio templates for Xamarin Forms are a nice addition. It saves the step of needing to write what very minimal boilerplate is needed for Prism apps (hardly any boiler plate is what sold me on Prism). I'd love to see the templates in Xamarin Studio too.

@brianlagunas mentioned that it was something on the roadmap but the Xamarin Studio team was working on options to make project/file templates extensible for this kind of stuff. Is that accurate? If it's something the community can pitch in with, say the word!

Thanks!

**Comment by brianlagunas** [comment]
So Xamarin didn't make this any easier, but I took the time to create them anyways.  I got Item, Project, and Code templates for Xamarin Studio.  Now I just have to get them submitted to the gallery.  That should be fun.

**Comment by dankraus** [comment]
Awesome. Thanks @brianlagunas . Didn't realize there was a Xamarin Studio gallery. I'm having a hard time finding it though. Nothing we need to vote up or anything for visibility?

**Comment by brianlagunas** [comment]
In Xamarin Studio open up the Add-in Manager, and then select the Gallery tab.  The problem is that MonoDevelop builds it form source, and I'm having a hard tie getting it to work right now.
