### ISSUE TITLE
net native throw exception  with ef7 rc2

### ISSUE THREAD

**Issue by jingliancui** [PrismLibrary/Prism#582]
### Package info

- Platform:windows 10 pc and mobile
- Prism version:prism.core 6.1.0 , prism.unity 6.1.1 , prism.windows 6.0.1
- Xamarin version (if applicable):
- Windows 10 SDK version (if applicable):10586
- Other version info:
EF rc2

### Repro steps

Same problem, .net native throw exception
sample code at this link:
https://github.com/aspnet/EntityFramework/issues/5407

**Comment by brianlagunas** [comment]
Please do not post the same issue in two different project sites.  Since this is .NET Native related, you have already submitted this issue to the .NET Native project site.  If the answer comes back from the .NET Native team that it is Prism related, then feel free to open a issues here and provide all the information from the previous submitted issue.

Thanks,

**Comment by jingliancui** [comment]
Hello @bartlannoeye ,sorry to create new issue thread for you .
The thread you close is this problem your team not give me the answer:
#504 

Raw uwp frame work is no problem use ef7sqlite rc2 with release mode.
 But,If I use prism with these 2 think (ef7sqlite rc2 and release mode ),It crash.
 Same problem as #504 
 But now is the ef7 rc2 which updated at 2015/05/16.
 So can you check the thread #504 and the new sample code in my share onedrive?
https://onedrive.live.com/redir?resid=C78B7E4A6377EC22!249164&authkey=!AN8hVlZgjwIc5Bg&ithint=file%2crar

**Comment by bartlannoeye** [comment]
I'll do my best to have a look at it, but can't promise anything as my time behind the pc is very limited (broken arm). Sadly .net native issues aren't the easiest ones

**Comment by jingliancui** [comment]
Hello @bartlannoeye  @brianlagunas  Glad to hear that you can try it again.
If something I can help you ,please tell me , I will try my best for this library,because I love this prism framework.

**Comment by jingliancui** [comment]
@brianlagunas @bartlannoeye 
That's issue is throw from .net native . 
The ef team give me solution here:
https://github.com/aspnet/EntityFramework/issues/5407
