### ISSUE TITLE
That's an old issue with #504 you are not give me a reply

### ISSUE THREAD

**Issue by jingliancui** [PrismLibrary/Prism#583]
Hello @brianlagunas ,The thread you close is this problem your team not give me the answer:
https://github.com/PrismLibrary/Prism/issues/504#issuecomment-199318925

Raw uwp frame work is no problem use ef7sqlite rc2 with release mode.
But,If I use prism with these 2 think (ef7sqlite rc2 and release mode ),It crash.
Same problem as #504 
But now is the ef7 rc2 which updated at 2015/05/16.
So can you check the thread #504 and the new sample code in my share onedrive?
https://onedrive.live.com/redir?resid=C78B7E4A6377EC22!249164&authkey=!AN8hVlZgjwIc5Bg&ithint=file%2crar

**Comment by brianlagunas** [comment]
You don't have to create a new issue in order to reply to your other one.  Please continue the conversation on #582
