### ISSUE TITLE
Debug information for failed View - ViewModel connectivity.

### ISSUE THREAD

**Issue by bkaankose** [PrismLibrary/Prism#587]
There is no information given by the system if View doesn't find its ViewModel right now. NavigationService throwing an exception when it doesn't find the given page name though. I think we can improve the platform with such things to get more visibility and help new developers on this.

I don't think it's neccesary, but specially for XForms it can be frustrating sometimes. What do you think about it?

**Comment by brianlagunas** [comment]
We are a planning to add logging issues to the output window when debugging.  See #576
