### ISSUE TITLE
crash XAML intellisense

### ISSUE THREAD

**Issue by irschneider** [PrismLibrary/Prism#594]
Hello
I utilized the plugin "Enable XAML Language for Xamarin.Forms" (https://visualstudiogallery.msdn.microsoft.com/8195a8e2-a842-4389-a8cb-34e4672e2e13) to apply intellisense in XAML screens Xamarin.Forms
Apparently after installing Prism Template Pack, intellisense stopped working. Is there any reason?
Thank you!

**Comment by brianlagunas** [comment]
The Prism Template Pack has no impact or influence on intellisense.  It is just a set of Item and Project templates.  Nothing more.

**Comment by irschneider** [comment]
Sorry Brian , you're right. Prism Template does not influence the problem
