### ISSUE TITLE
[XF] Feature Request:  constrain INavigationService.NavigateAsync<T>()

### ISSUE THREAD

**Issue by MrXemiu** [PrismLibrary/Prism#595]
Since most (as far as I can tell) of the DI container extension methods for registering types for navigation, (RegisterTypeForNavigation&lt;T&gt;()), constrain T to be of type Page, it makes sense to similarly constrain INavigationService.NavigateAsync&lt;T&gt;().

**Comment by brianlagunas** [comment]
No, because you will never be calling `NavigateAsync<Page>()`.  `NavigateAsync<T>` is meant to be used with ViewModels.

Actually, you have given me the idea of doing a check of `<T>` to make sure it's not a Page type and if it is throw an exception :)
