### ISSUE TITLE
[Windows 10 UAP] Module/Region Management in UWP

### ISSUE THREAD

**Issue by ChSchmidt81** [PrismLibrary/Prism#60]
Will Prism for UWP support Module/Region Management?

**Comment by briannoyes** [comment]
It is on our roadmap to integrate modularity and regions into the UWP platform version of Prism. However, the first focus is on migrating the existing Prism for Windows Runtime functionality over to UWP and once that is all ready to go, that will be our first UWP release. Then we will focus on moving modularity and regions in and I would anticipate that being a second release somewhere down the road.

**Comment by ChSchmidt81** [comment]
Thanks for your quick answer.
I now it is always difficult to say but do you have a rough timeframe on the releases. 
Will the first release be ready for the start of Windows 10.

**Comment by briannoyes** [comment]
It is certainly our goal to get a first release of the UWP support ready so
that we can release shortly after Win 10 RTM's, but we will always need a
little time beyond that to test against the newly released bits, and we are
also already a little behind schedule on getting the PrismRT code migrated,
so a little hard to say for sure.

On Mon, Jun 15, 2015 at 4:22 AM, ChSchmidt81 <notifications@github.com>
wrote:

> Thanks for your quick answer.
> I now it is always difficult to say but do you have a rough timeframe on
> the releases.
> Will the first release be ready for the start of Windows 10.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PrismLibrary/Prism/issues/60#issuecomment-111975154>.
>



-- 
---------------------------------------------------------------------------
Brian Noyes
CTO and Co-founder, Solliance <http://solliance.net/> & Pluralsight Author
<http://www.pluralsight.com/author/brian-noyes>
Microsoft Regional Director / MVP
---------------------------------------------------------------------------

**Comment by MuralidharN** [comment]
Hi,
   Is there any reason why MEF container is not at present supported in UWP platform?
   Is this also there in your roadmap for UWP?
   I got to know that it is supported for Windows 8.1 apps? If so why it is dropped for UWP?

   Currently we were using the MEF extensively in our WPF  and are in a process of migrating to     UWP.

Thanks in Advance.

Regards,
Muralidhar

**Comment by peter-f-s** [comment]
In the meantime, is Region Management for UWP still on the agenda?
And if so, with which priority?

**Comment by brianlagunas** [comment]
It is, but we don't have the resources to work on UWP right now.  Prism for XF is my priority right now.  Which I am working on adding modularity to now.

**Comment by peter-f-s** [comment]
ok, thanks for your answer.

**Comment by ChSchmidt81** [comment]
Are Module/Region still on the Roadmap for UWP?

**Comment by brianlagunas** [comment]
It's on the road map, but it's really far down the road.

**Comment by Mayhem50** [comment]
Any news ?

**Comment by brianlagunas** [comment]
no news

**Comment by sathish8226** [comment]
I see this is added to 7.0 road map, when can we expect this to be released?

**Comment by brianlagunas** [comment]
No timeline. it gets done when we get to it.

**Comment by sathish8226** [comment]
Is there any workaround for now?

**Comment by brianlagunas** [comment]
create your own module management system
