### ISSUE TITLE
Add support for Xbox B/Back button to DeviceGestureService

### ISSUE THREAD

**Issue by briandunnington** [PrismLibrary/Prism#602]
Now that UWP apps are supported on Xbox (well, in preview), it would be great to add back navigation support for the B gamepad and Back Xbox remote buttons to make them work similar to how the hardware back buttons and other accelerator keys work.

https://msdn.microsoft.com/windows/uwp/input-and-devices/designing-for-tv#gamepad-and-remote-control

**Comment by allanrsmith** [comment]
I believe this should already work.  The provided link specifies that the developer must implement `ystemNavigationManager.GetForCurrentView().BackRequested +=
        SystemNavigationManager_BackRequested;` which is already done here: https://github.com/PrismLibrary/Prism/blob/master/Source/Windows10/Prism.Windows/AppModel/DeviceGestureService.cs#L50

Can you confirm that it does(not) work?

**Comment by brianlagunas** [comment]
Since there has been no response so I am assuming this works as expected.
