### ISSUE TITLE
IPageDialogService for UWP

### ISSUE THREAD

**Issue by bkaankose** [PrismLibrary/Prism#605]
It's very usefull in XForms, is there any reason we don't have it on UWP? Dealing with MessageDialog and it's commands is pretty boring and I usually write my own service for every UWP project. 

If there isn't any specific reason I'd like to add this feature to the current library, at least the basics like showing simple MessageDialog or comfirmation dialogs with 2 basic buttons. (it's a very common usage)

Even ContentDialogs can be managed under this service and we can prevent exceptions like 'only one content dialog is allowed'.

I might me missing some points in this situation (sorry if so), but I'd like to know what you guys think about it.

**Comment by brianlagunas** [comment]
The IPageDialogService in Xamarin Forms is built specifically to address the need of calling Page.DisplayALert and Page.DisplayActionSheet from within a ViewModel.  So we are simply abstracting away the Page reference need to call the platform's built-in API's.  UWP doesn't have such an API.  So this would not be needed for that abstraction.

**Comment by bkaankose** [comment]
In terms of abstraction, you're right. We don't need it. In the current Project I'm working on now, I seperated my views to another Universal Windows Project and my view models to a different PCL Project. I don't have any references for UWP in my view models right now and this service can be a solution for such thing. Not every developer places it's views and viewmodels to the same project or different projects with the same type. Does current Prism have solution for this kind of a situation?

And most importantly, Prism makes developers life much more easier than ever. Even though we're not solving any project related problems with this service, I'd love to see some kind of a helper service for dialogs in UAP, but you guys in charge of course :)

**Comment by brianlagunas** [comment]
The location of the ViewModels are irrelevant.  If you require this in your projects you would simply create your own interface and provide the UWP implementation of your required functionality.  Register that interface with your container, and anytime you ask for the interface, you'll get it.

**Comment by weitzhandler** [comment]
I'd love to see that service in UWP too.
I'm working with Uno platform, and if this interface is exposed by the system, it makes it more accessible to provide per-platform implementation.

**Comment by dansiegel** [comment]
@weitzhandler you may notice that we are not currently pursuing UWP as an independent platform at the moment.

**Comment by weitzhandler** [comment]
Yep. Saw that that :(

**Comment by weitzhandler** [comment]
I understand the UWP is out of scope for the Prism team. How about you just make those interfaces accessible in the core lib for others to implement them? Opened a new issue #1819.

Thank you!
