### ISSUE TITLE
How to create shared serial port access in Prism 6 multimodule WPF MVVM application?

### ISSUE THREAD

**Issue by EugeneBuzin** [PrismLibrary/Prism#606]
Hi, guys. I write C# WPF MVVM Prism 6 application consisting of:
1) Shell project,
1)  Multiple Prism modules projects,
2) ClassLibrary project with global access from all these Prism modules and from Shell. (This ClassLibrary is within my application solution as the modules and Shell are.)
I need a one (and only one!) SerialPort instance in my application. And I need multiple access to this SerialPort from all Prism modules in the application for communication with outer device (gas ultrasonic flowmeter).
What is the best approach to solve this problem about shared serial port?
If I create SerialPort as public static member and put it in one of the static class in the above mentioned ClassLibrary, will this way be the best one? Or put such SerialPort instance in shared service will be the best?
So please advice me how to define globally accessed shared SerialPort in multimodule Prism 6 WPF MVVM application?

Thanks in advance    Eugene.

**Comment by rohits79** [comment]
Please note Prism Issues page is only for feature request or bug reports. For suggestion and how-tos please ask question on stackoverflow with #prsim tag

**Comment by EugeneBuzin** [comment]
I know that you are busy people, but help me, please, I really need to solve the problem of shared access to the serial port from a number of Prism Modules.
