### ISSUE TITLE
Feature Request - Suggestion to have AddRange and RemoveRange extension method for ObservableCollection 

### ISSUE THREAD

**Issue by rohits79** [PrismLibrary/Prism#607]
If we recursively add multiple items to ObservableCollection one after the other (in a very short span), the performance degrades massively ([too many notification updates](http://stackoverflow.com/questions/11958375/how-to-add-thousands-of-items-to-a-binded-collection-without-locking-gui)), Instead it would be better to have something like an AddRange collection so we could add in bulk without incurring cost. I think almost all projects I've worked with need to implement this manually, it'd would be better if framework could support one out of the box.

See Calibun Micro's AddRange and RemoveRange for example https://github.com/Caliburn-Micro/Caliburn.Micro/blob/master/src/Caliburn.Micro/BindableCollection.cs#L155-192

**Comment by brianlagunas** [comment]
Thanks for the idea, but this is not something we feel Prism should be addressing at this time.
