### ISSUE TITLE
Command CanExecuteChanged handlers no longer run on the UI thread

### ISSUE THREAD

**Issue by tinyplasticgreyknight** [PrismLibrary/Prism#608]
This bug relates to a recent change in the threading behaviour of command `CanExecuteChanged` handlers.

Previously, event handlers were held weakly through a `WeakEventHandlerManager`; this class also used a `SynchronizationContext` to dispatch the handlers to the UI thread when they were being called.

In commit f44507fdcc38194d977971931bbfb693b3c5906f, the weak reference behaviour was removed to deal with some issues around handlers being collected too soon.

However, it is now also the case that the handlers are invoked directly instead of the UI thread.  This part seems to have been an accidental change.

(There is some related discussion from @federom towards the bottom of [issue 299](https://github.com/PrismLibrary/Prism/issues/299#issuecomment-182010024).)

**Comment by tinyplasticgreyknight** [comment]
The diff for f44507fdcc38194d977971931bbfb693b3c5906f shows `WeakEventHandlerManager` was using a `SynchronizationContext` right up until it was removed (unless there's something funky around the `syncContext` field that I've missed).

**Comment by brianlagunas** [comment]
Oh I see now! The WeakEventHandlerManager had the SynchronizationContext, not the DelegateCommand.  Good catch!  Well, issue #322 has been waiting for a PR to fix this for awhile now (hint hint)

**Comment by tinyplasticgreyknight** [comment]
I'll put something together this evening.

**Comment by brianlagunas** [comment]
Awesome!  Make sure to run the tests before submitting the PR

**Comment by brianlagunas** [comment]
This has been fixed
