### ISSUE TITLE
OnShareTargetActivated does not call OnInitializeAsync before 

### ISSUE THREAD

**Issue by Novan123** [PrismLibrary/Prism#61]
Hello,
we have written a universal app for windows store 8.1 and windows phone 8.1.
If the app is started as a share target the method OnShareTargetActivated is called in the app.xaml.cs
But before there is not called the OnInitializeAsync.

In the OnInitializeAsync we register the types for dependency injection and serialization. If we now try to process the share target request we need certain services which should be registered. But because the OnInitializeAsync method was not called nothing is registered and we get an exception. Also the NavigationService and SessionStateService of prism is not yet created. Navigation to a page is therefore not possible. 

See also:
https://prismwindowsruntime.codeplex.com/discussions/639901

**Comment by briannoyes** [comment]
Brian L, I discussed this with him on CodePlex - believe it was just an oversight in Prism for Windows Runtime because share contacts were not in scope for our releases. Should be easy to address and make sure we cover in Prism YEP release

**Comment by bartlannoeye** [comment]
Do we plan support for the Windows 8.1 / WP 8.1 code or do we only care about Win10 UWP? It's just that I got a few more issues/fixes on the Win8.1 that I could submit if we plan to keep that code alive. If only Win10, then there's no use in changing the 8.1 code base.

**Comment by Novan123** [comment]
Btw: This problem is also present, if the app is started with OnFileActivated.

**Comment by briannoyes** [comment]
@Novan123 OK, good to know. Not surprising since the only two launch scenarios we were specifically targeting and therefore testing were launch from a primary (start screen) and secondary (deep link) live tiles.

**Comment by briannoyes** [comment]
@bartlannoeye I'd say updates to the Win 8/8.1 code base are our lowest priority, and as you already know we are not progressing as fast on WPF/Xamarin/UWP support as we would like (unfortunately none of us get to work on this as part of our paid work). However that being said if there are some quick fix things we can do to that code base to get a new point release out there for it, we would be open to that, especially if someone else is willing to do the leg work and submit a pull request.

**Comment by bartlannoeye** [comment]
@Novan123 we currently use following code in the OnActivated (protocol activation) to work around this missing feature:

```csharp
if (args.PreviousExecutionState != ApplicationExecutionState.Running)
{
	await InitializeFrameAsync(args);
	RewireViewModelLocator(); // our logic to rewrite VML
}
```

@briannoyes I'll see what I can do. Currently I'm not longer doing full time Win8/Win10 dev either, so I feel your pain with timings.

**Comment by Novan123** [comment]
A short note how to resolve this problem:
Easily call the same methods which were called by MVVMBase at normal app launch.
The important part is the if clause plus the inner stuff.

protected async override void OnFileActivated(FileActivatedEventArgs args)
{
            if (args.PreviousExecutionState != ApplicationExecutionState.Running)
            {
                await InitializeFrameAsync(args);
                await OnLaunchApplicationAsync(null);
            }
            
            base.OnFileActivated(args);
            // Do your own stuff from here on.
        }

        protected override async void OnShareTargetActivated(ShareTargetActivatedEventArgs args)
        {
            if (args.PreviousExecutionState != ApplicationExecutionState.Running)
            {
                await InitializeFrameAsync(args);
                await OnLaunchApplicationAsync(null);
            }
            
            base.OnShareTargetActivated(args);
            // Do your own stuff from here on.
        }

With this code you can close this ticket in my optinion.
