### ISSUE TITLE
Unable to register multiple platform specific types or platform specific singletons

### ISSUE THREAD

**Issue by jtourlamain** [PrismLibrary/Prism#618]
### Package info

- Platform: Xamarin Forms
- Prism version: 6.1.0
- Xamarin version (if applicable): 6.1.0-pre5
- Other version info: Prism.Unity.Forms 6.2.0-pre5

### Repro steps

I want to register some services that are platform specific, so I can’t use the RegisterTypes method in the PCL. I know I can register my types via the Xamarin DependencyService (using the assembly attribute) and that Prism can auto inject them in my ViewModels.
Where can I register types directly on the container (so I can make them a singleton or register multiple types of IService)? If I register types after new App()  then the OnInitialized method is called which starts navigating before I can call appinstance.Container.

```C#
// AppDelegate.cs
public override bool FinishedLaunching(UIApplication app, NSDictionary options)
{
  global::Xamarin.Forms.Forms.Init();
  var formsApp = new App();
  // From here the OnInitialized is called in the formsApp that executes:
  // NavigationService.NavigateAsync("MainPage");
  // but I still need to register my platform specific services
  formsApp.Container.RegisterType<IService, HockeyAppLogger>(new ContainerControlledLifetimeManager());
  formsApp.Container.RegisterType<IService, AnotherService>();
  LoadApplication(formsApp);
  //...
```

**Comment by brianlagunas** [comment]
Thanks for bringing this scenario to my attention.  This is a great scenario, and I can imagine a very common one.

My first thought is to expose an event that you can hook into in order to register types in the platform project heads.  Maybe called "Initializing"?  Though, I'm not sure that will work because OnInitialized may still happen before you have finished handling the event.  I'll have to test that out.

Do you have any ideas of how you would like to see this implemented?

**Comment by joacar** [comment]
First idea that comes to my mind is to create an overload constructor with signature `public App(Action<IContainer> register)`.

Usage:

````c#
var formsApp = new App(container => 
{
   container.RegisterType<IService, HockeyAppLogger>();
});
...
LoadApplication(formsApp);
````

Then call the action before/after. This will affect how multiple registrations of the same interface will be handled by the container. For example in DryIoc you could specify that it should replace the previous or just append it (in which it will need service key by default).

So perhaps a more "sophistacted" approch will be needed. One of them could be to create an interface `IPlatformApp` (perhaps abstract class is more suitable) that could define various extension points and then it will be injected into the `App` constructor.

**Comment by brianlagunas** [comment]
I actually just coded up that approach!  In PrismApplicationBase I added this:

```
Action<IUnityContainer> _registerPlatformTypes;

public PrismApplication(Action<IUnityContainer> registerPlatformTypes = null)
{
    _registerPlatformTypes = registerPlatformTypes;
}
```
```
        public override void Initialize()
        {
            ...
            RegisterTypes();

            _registerPlatformTypes?.Invoke(Container);
            ...
        }
```

Then you just need to add a ctor to the App if you ant to use this extension point:
```
        public App(Action<IUnityContainer> registerPlatformTypes = null) : 
            base(registerPlatformTypes)
        {

        }
```

Next, in the Platform project provide your delegate:
```
    public class MainActivity : global::Xamarin.Forms.Platform.Android.FormsAppCompatActivity
    {
        protected override void OnCreate(Bundle bundle)
        {
            ...
            LoadApplication(new App(RegisterPlatformTypes));
        }

        void RegisterPlatformTypes(IUnityContainer container)
        {
            ...
        }
    }
```

**Comment by brianlagunas** [comment]
I also like the idea of accepting a class that implements an interface as well.  That leaves room for extension without modifying the App ctor again.

**Comment by jtourlamain** [comment]
My first thought was also, why not just use an overload in the constructor. But changing the constructor for each extension that is wanted, will make your constructors a bit messy.
Maybe it's a good idea to let Prism create the IoC container and then search for classes that implement an interface like IRegisterTypes. A container is build to do stuff like that. In that way your constructor stays clean.

**Comment by brianlagunas** [comment]
I like the idea, but we need to keep performance in mind, and searching for assemblies using reflection could be expensive.  Especially if there are a lot of modules in the app.

**Comment by joacar** [comment]
Now I'm just thinking out loud. What if there would exists something like ApplicationBuilder that allow a fluent-like registration model that later passed to the Application. The builder could perhaps utilize the Module architecture already at place and there could be something like `RegisterPlatformTypesModule` that does what we discuss here, i.e. has constructor expecting `IContainer` and a method `void ConfigureServices(IContainer container)`.

This could potentially be extended for registration of services in a more concise manner, something like 

````c#
var builder =  new ApplicationBuilder()
     .ConfigureSqLite()
     .ConfigureHockeyApp();
      ...
LoadApplication(new App(builder));
````

**Comment by totht91** [comment]
I had the same problem, and I added a parameter with a specific interface, to the `PrismApplication`'s ctor, and to the `PrismApplicationBase`.

@brianlagunas I think your solution is not enought because, the `Initialize` abstract method is called before the `PrismApplication`'s ctor (because it is called in the base ctor, and this is kind of antipattern). So the field initializer is not executed the action will be always null, you need to pass deeper the action/interface to the base.

**Comment by jtourlamain** [comment]
@brianlagunas you're right about performance. 
Wouldn't it be better to pass a PrismApplicationBuilder into your constructor (like @joacar suggested). Later on you can add more methods to that class that allow users to configure Prism without making breaking changes on the constructor. Something like:
```C#
public abstract class PrismApplicationBuilder
{
  public abstract void RegisterPlatformTypes(IUnityContainer container);
}
```
and
```C#
private readonly PrismApplicationBuilder _prismBuilder;

public PrismApplication(PrismApplicationBuilder prismBuilder = null)
{
    _prismBuilder = prismBuilder;
}
```
As far as I investigated the code so far, the code isn't using a lot of Action delegates. Maybe an abstract class that you can override is more in line with the existing code. Maybe PrismApplicationBuilder is not a good name but you get the point.

**Comment by brianlagunas** [comment]
I like the idea of passing an interface rather than an abstract class, since there will be no implementation provided.  Having said that, since each container project has it's own container type (IUnityContainer, IKernel, IContainer, etc) there is no standard interface I can use for registering types.

@totht91 how is it an anti pattern?  You might be thinking of calling virtual methods from within an abstract ctor, which is not happening here.

Either way, in order to support this, I am going to have to move the `InitializeInternal` method out of the base ctor in order for any platform specific methods to be respected during the initialization process.

**Comment by brianlagunas** [comment]
Alright, I think I have decieed to go with an interface approach.  I just need a good name for it.  I was thinking something like:
```
    public interface IPlatformConfiguration
    {
        void Configure(IUnityContainer container);
    }
```
This is pretty generic, but the only problem is if there is ever a need to add more methods that occur at different times during the initialization process.  So maybe  Something more specific like:
```
    public interface IPlatformConfiguration
    {
        void RegisterTypes(IUnityContainer container);
    }
```
Then we could add more methods/properties as necessary through the initialization process, but is that a real possibility or not?  Also, if we take this approach, I'm not sure I like the "Configuration" part of the name.  So maybe a better name?

Thoughts?

**Comment by brianlagunas** [comment]
How does 'IPlatformInitializer'?  That's essentially what it is going ot be used for.  Initializing the application with platform specifics.

**Comment by dansiegel** [comment]
If all we're doing is registering types how does having to implement a new interface work better than passing in an action which can simply be invoked before we register types in the shared code?

**Comment by brianlagunas** [comment]
Because this leaves us open for extension down the road if necessary.

**Comment by brianlagunas** [comment]
This has been implemented in #630

**Comment by amccorma** [comment]
Do you have an sample on how to use the IPlatformInitializer?  I try and the android app crashes when I try to inject it into the viewmodel.

**Comment by brianlagunas** [comment]
Check out the sandbox https://github.com/PrismLibrary/Prism/tree/master/Sandbox/Xamarin/HelloWorld

**Comment by amccorma** [comment]
Yes, that example the one I am using but it does not register anything.

 ```
 public class AndroidInitializer : IPlatformInitializer
    {
        public void RegisterTypes(IUnityContainer container)
        {
 // nothing is registered here?  
        }
    }
```

**Comment by brianlagunas** [comment]
Yes, but this is where you would register your types with the container

**Comment by joacar** [comment]
Example for Android. Below is using DryIoc but it works same way for any container (except that the signature reflects the container type)

````c#
public class DroidPlatformInitializer : IPlatformInitializer
    {
        public void RegisterTypes(IContainer container)
        {
            container.Register<ISqLiteContext, DroidSqLiteContext>();
        }
    }

public class MainActivity : FormsApplicationActivity
    {
        protected override void OnCreate(Bundle bundle)
        {
            base.OnCreate(bundle);          
            Forms.Init(this, bundle);
            LoadApplication(new App(new DroidPlatformInitializer()));
        }
    }

````

**Comment by amccorma** [comment]
interesting find.

if you do this works.

Forms.Init(this, bundle);
 LoadApplication(new App(new DroidPlatformInitializer()));

if you try this, exception.  creating the app variable throws an exception.  

Forms.Init(this, bundle);
var app = new App(new DroidPlatformInitializer());
LoadApplication(app);
