### ISSUE TITLE
[XF] Missing DependecyServiceKernel in Prism.Ninject.Forms

### ISSUE THREAD

**Issue by dansiegel** [PrismLibrary/Prism#621]
In Prism.Ninject.Forms the PrismApplication's CreateKernel method's docs tell you that you should override to return Prism.Ninject.Extensions.DependencyServiceKernel if you are using Xamarin.Forms.DependencyService. There is no DependencyServiceKernel.

**Comment by brianlagunas** [comment]
Not sure if those docs are accurate.  There is a DependencyServiceProvider that handles the XF DependencyService registrations.

**Comment by dansiegel** [comment]
Wasn't really sure whether the docs just need to be changed or a DependecyServiceKernel needs to be implemented.

**Comment by brianlagunas** [comment]
This was removed
