### ISSUE TITLE
PopUpWindowAction and Resizing

### ISSUE THREAD

**Issue by HartlD** [PrismLibrary/Prism#623]
I'm using a PopUpWindowAction in my MainVIew:
` <StackPanel Orientation="Horizontal">        
            <i:Interaction.Triggers>
                <prism:InteractionRequestTrigger SourceObject="{Binding SettingsRequest, Mode=OneWay}">
                    <local:CustomPopupWindowAction CenterOverAssociatedObject="True" IsModal="false" >
                        <local:CustomPopupWindowAction.WindowStyle>
                            <Style TargetType="Window">
                                <Setter Property="SizeToContent" Value="WidthAndHeight"/>
                            </Style>
                        </local:CustomPopupWindowAction.WindowStyle>
                        <local:CustomPopupWindowAction.WindowContent>
                            <local:CustomView />
                        </local:CustomPopupWindowAction.WindowContent>
                    </local:CustomPopupWindowAction>
                </prism:InteractionRequestTrigger>
            </i:Interaction.Triggers>
       <Button Content="Press" Width="50" Height="50" Command="{Binding ChangeCommand}">    </Button>
    </StackPanel>`

Window wiil get raised but the window will not resize after Template changes
CustomView:
`
<UserControl x:Class="UserControlResizeWindowTest.CustomView"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:UserControlResizeWindowTest"
        mc:Ignorable="d"
        Height="Auto" Width="Auto">
    <Control>
        <Control.Resources>
            <ControlTemplate x:Key="1" TargetType="Control">
                <StackPanel Background="Black" Width="300" Height="500">                  
                </StackPanel>
            </ControlTemplate>
            <ControlTemplate x:Key="2" TargetType="Control">
                <StackPanel Background="Red" Width="100" Height="100">                    
                </StackPanel>
            </ControlTemplate>
        </Control.Resources>
        <Control.Style>
            <Style TargetType="Control">
                <Setter Property="Template" Value="{StaticResource 1}"/>
                <Style.Triggers>
                    <DataTrigger Binding="{Binding Notification.Order}" Value="true">
                        <Setter Property="Template" Value="{StaticResource 2}"/>
                    </DataTrigger>
                </Style.Triggers>
            </Style>
        </Control.Style>
    </Control>
</UserControl>
`
Any Suggestion how to solve this Problem?

 Same Example(UserControl) without PopUpWindowAction works..

**Comment by brianlagunas** [comment]
I'm sorry, but what exactly is the issue?  You didn't provide any context to this issue.  If this is related to another issue then you shouldn continue the discussion there and not open a new issue.  Thanks.

**Comment by HartlD** [comment]
As I wrote before, the window will not resize, if the template changes...

**Comment by HartlD** [comment]
[UserControlResizeWindowTest.zip](https://github.com/PrismLibrary/Prism/files/300380/UserControlResizeWindowTest.zip)

As you can see in the example, the popup window size will not Change...

**Comment by brianlagunas** [comment]
This is because of how you are retemplating the control.  Fix your template and it will work.

**Comment by HartlD** [comment]
And what's wrong? :+1:

**Comment by brianlagunas** [comment]
I am out of country and on my phone so I'm not going to type the markup out. Delete your ControlTemplate and create a simple style to update the template property.
