### ISSUE TITLE
Navigating immediately within OnNavigatedTo fails [UWP]

### ISSUE THREAD

**Issue by mglodack** [PrismLibrary/Prism#624]
I'm using Prism for UWP and I'm hitting a road block with my understanding of `OnNavigatedTo` and the `FrameNavigationService`.

Currently I'm encountering an issue after attempting to navigate immediately to the another page using [this](https://github.com/PrismLibrary/Prism/blob/master/Source/Windows10/Prism.Windows/Navigation/FrameNavigationService.cs#L49) method in the `OnNavigatedTo` handler of my view model. Instead of navigating to the the next page, it returns false. I've been able to get around the issue by waiting half of a second, but that is certainly not a permanent solution. 

It seems like behind the scenes there `Frame` or some aspect of the Prism library is still doing work even though this event has been published.

These are some things that I've done to debug or have seen in the code base that might need further investigation.

0. This exception being swallowed up in the  [FrameFacade](https://github.com/PrismLibrary/Prism/blob/master/Source/Windows10/Prism.Windows/Navigation/FrameFacadeAdapter.cs#L97) could be something worth looking into.
0. I've attempted to subscribe to the original Frame's [NavigationFailed](https://msdn.microsoft.com/en-us/library/windows/apps/windows.ui.xaml.controls.frame.navigationfailed) event with no luck of that event firing.
0. I've double checked [these](https://github.com/PrismLibrary/Prism/blob/master/Source/Windows10/Prism.Windows/Navigation/FrameNavigationService.cs#L65) sessionState kvps and does not seem to be the issue.

Any ideas?

**Comment by bartlannoeye** [comment]
If you want to navigate away directly in the OnNavigatedTo method, use the Dispatcher to execute your call. This enables the first call to be fully completed before starting the second one.

**Comment by mglodack** [comment]
Thank you @bartlannoeye
