### ISSUE TITLE
Feature Request: Move ValidatableBindableBase to the Prism Project (PCL) 

### ISSUE THREAD

**Issue by mfe-** [PrismLibrary/Prism#625]
Since the introduction of Micrsofts application model, the useage of PCLs gained importance and popularity.

In new projects we want to move our model into a PCL. Therefore the models should be validatable. The necessary classes currently exist in [Prism/Source/Windows10/Prism.Windows/Validation/](https://github.com/PrismLibrary/Prism/tree/de7b03b5e015edcac595602512877b264a1345d1/Source/Windows10/Prism.Windows/Validation) . I would suggest to move these classes to the core Prism PCL.

There are only few adjustments to [ValidatableBindableBase.cs](https://github.com/PrismLibrary/Prism/blob/de7b03b5e015edcac595602512877b264a1345d1/Source/Windows10/Prism.Windows/Validation/ValidatableBindableBase.cs) requried.

This would require to upgrade the targets of the PCL from .NET Framework 4.5 to 4.6 because of the missing DataAnnotations reference.

**Comment by brianlagunas** [comment]
Upgrading the framework would be a breaking change and prevent a ton of current WPF Prism users from upgrading.  This would be the main reason why this probably won't happen anytime soon.

**Comment by mfe-** [comment]
We could use the https://www.nuget.org/packages/Portable.DataAnnotations/ and target the .NET Framework 4.5.
See also http://stackoverflow.com/a/20079103/740651

**Comment by brianlagunas** [comment]
First, we would have to research to make sure this class makes sense, and can be used, on all platforms before moving it into the PCL project.  Then decide if the hassle of using type forwarders is worth it for this one class.  Which I am going to assume it's not.  I also do not want the PCL project to take a dependency on another package (which isn't an official MS DataAnnotation package) just to support this single class.  Honestly, I really don't see this happening right now.

**Comment by mfe-** [comment]
Thanks for your Feedback @brianlagunas . I totally understand your concerns also your point regarding an unofficial dependency package sounds really reasonable.

> Honestly, I really don't see this happening right now.

I thought the best solution for this issue would be to create an independent prism extension / validation libary. 

With this [Prism.Extensions](https://github.com/mfe-/Prism.Extensions) you could share your PCL model with DataAnnotaion between wpf, xamarin and uwp.

I hope I can contribute to the prism libary this way.

**Comment by brianlagunas** [comment]
Good idea.  I think you might be better off and get more adoption if you make it more of a stand alone component without taking a dependency on Prism.Core.  It looks like you are only using BindableBase which is just INPC so it's not really needed.  Plus, I think Prism.Extensions is too generic of a name for this.  I would recommend something more inline with what this component actually does (validation).
