### ISSUE TITLE
NavigationPage back button disappearing from nav bar after page transition on iOS

### ISSUE THREAD

**Issue by tbaggett** [PrismLibrary/Prism#627]
### Package info

- Platform: Xamarin.Forms
- Prism version: Core: 6.1.0, Prism.Forms: 6.1.0-pre5, Prism.Unity.Forms: 6.2.0-pre5
- Xamarin version (if applicable): Xamarin.Forms: 2.3.0.38-pre2, Xamarin.iOS: 9.6.2.4

### Repro steps

Created a test app to try out Prism with Xamarin.Forms. App does NOT use a MasterDetail page, instead starts with a NavigationPage wrapping a ContentPage that contains buttons to fire commands that use INavigationService.NavigateAsync to go to desired pages.

When I click one of the buttons on the main menu screen, the view navigates to the requested page by sliding it into view from the right to the left as expected. During the animation of the transition, I see "< Golf App" text moving from the center title position to the left side of the navigation bar. This text then disappears as soon as the page transition animation is completed.

I've created a video recording of the issue at https://vimeo.com/169630885/42cda5a722. I enabled the iOS Simulator's "Slow Animation" option during the transition so it is very clear that the back button text doesn't disappear until the transition has completed.

I recreated the same structure in a regular Xamarin.Forms app and tested it using both the stable 2.2.0.45 release of Xamarin.Forms and the preview version 2.3.0.38-pre2 required by the latest Prism library. I couldn't reproduce the issue with either version when not using Prism.

**Comment by brianlagunas** [comment]
This may be related to #541 as it still relates to using the NavigationPage.  I am at NDC Olso right nojw, but when I return I will verify this issue.

**Comment by brianlagunas** [comment]
I assume you are calling NavigateAsync from your NavigationPageViewModel right?

**Comment by brianlagunas** [comment]
Can you provide more information such as how you navigating when the application initializes, as well as which ViewModels you are navigating from and to.  Please provide all necessary code

**Comment by tbaggett** [comment]
Hey Brian, sorry for the slow reply! I had already deleted my test app when you replied. I've been upgrading to a new system for the past couple of days but will reproduce the test app and provide it to you later today or over the weekend.

**Comment by tbaggett** [comment]
Is the Prism Template Pack available/compatible with the new Xamarin Studio v6.0? It isn't shown in the add-in manager when I search for "prism". I can create a test app without it, but will miss it. 😄

**Comment by tbaggett** [comment]
I built a new test app with all the new Xamarin stuff and things are working as expected this time. I'm not sure if I was doing something wrong (likely haha) or if all the shiny new stuff took care of the issue. Sorry for the false alarm!

**Comment by dansiegel** [comment]
Thanks for reporting the issue @tbaggett. I'm seeing the same issue. I'll coordinate with @brianlagunas, and hopefully we can get that taken care of as part of #612.
