### ISSUE TITLE
Page/ViewModel registration (possible) issue

### ISSUE THREAD

**Issue by micah8719** [PrismLibrary/Prism#628]
### Package info

- Platform: Xamarin.Forms
- Prism version: 6.1.0-pre5
- Xamarin version (if applicable): 2.3.0.34-pre1

### Repro steps

This was tested on Android emulator only. I know this is not best practice, but I tried breaking it to see if I could.

Assume you have 2 pages called Test and Test2 and two view-models, TestViewModel and Test2ViewModel. If you register the Test page to Test2ViewModel like so:

```
protected override void OnInitialized()
{
    NavigationService.NavigateAsync<Test2ViewModel>();
}

protected override void RegisterTypes()
{
    Container.RegisterTypeForNavigation<Test, Test2ViewModel>();
}
```

The Test page receives information from TestViewModel instead of Test2ViewModel. I think this may be an issue in ViewModelLocator when it's trying to auto wire-up the page.

Again, I know this is NOT best practice, but if you give the developer the option, it WILL happen eventually.

**Comment by dansiegel** [comment]
@micah8719 the ```RegisterTypeForNavigation<TView,TViewModel>()``` function does not do what you're thinking it does. It simply uses the full name (YourProject.ViewModels.Test2ViewModel) as the name to register your view with. It does not tell the ViewModelLocator to use a different ViewModel.

Additional functionality was introduced in PR #578 which will let you override the default behavior with the thought of being able to have a common ViewModel which may be shared across Views possibly for different platforms. See the [Xamarin Sandbox](https://github.com/PrismLibrary/Prism/blob/master/Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld/App.cs#L23) for an example of how to use it. This will be available in the next Prism.Forms release.
