### ISSUE TITLE
Prism - region.add and regionManager.AddToRegion works differently

### ISSUE THREAD

**Issue by rohits79** [PrismLibrary/Prism#633]
I was under the impression that the following two code statements are analagous

```
var region = regionManager.Region["SomeRegion"]
region.Add(container.Resolve<SomeView>());
```

and

`regionManager.AddToRegion("SomeRegion", container.Resolve<SomeView>());`

but as [shown in my project](https://github.com/rohits79/PrismRegionAmbiguity), they both yield different results - what surprises me is that with regionManager.AddToRegion do not need to use Scoped Regions, but with region.Add we need scoped regions.

Please [clone the repo](https://github.com/rohits79/PrismRegionAmbiguity.git), build and run the project, you should get an exception that ViewB is already registered. Now open TestModule.cs (see below) and comment "region.add" lines, and uncomment regionManager.AddToRegion, you will see the solution works perfectly.

I have gone through the docs and have seen projects intermittently using region.Add and regionManager.AddToRegion, but seems the API works differently.

https://github.com/rohits79/PrismRegionAmbiguity/blob/master/TestModule/TestModule.cs#L22-29

**Update**

Noticed that if i add three lines of AddToRegion then application blows up

`regionManager.AddToRegion("ViewA", unityContainer.Resolve<ViewA>());`

however it takes only two lines of region.Add

`region.Add(container.Resolve<ViewA>());`

Does this not look like an issue in Prism, Also wonder why AddToRegion works without creating scope?

**Comment by brianlagunas** [comment]
Closing this since you already asked this question on StackOverflow.  Please do not post in both locations.

**Comment by dvorn** [comment]
The configuration is incorrect: two instances of ViewA are created and each of them contains region "ViewB". This will not work anyway because region name must be unique (and you should have used scoped region managers for this scenario).

The configuration is incorrect: after

`regionManager.AddToRegion("ViewA", unityContainer.Resolve<ViewA>());` 
`regionManager.AddToRegion("ViewA", unityContainer.Resolve<ViewA>());`

add the following

`var region = regionManager.Regions["ViewA"];`

and it will crash.

Thus the difference is only in the stage at which the error is detected.  Actually, defining RegionName in ViewA.xaml as well as RegisterViewWithRegion do not create regions; the actual work is done on an event which is triggered when RegionManager.Regions is accessed.

**Comment by rohits79** [comment]
@dvorn

Sorry, i think you misread. I am aware of scoped regions and i know why we need scope regions.

The reason i call it is bug is because, writing two lines of AddToRegion works when it should be throwing exceptions.

regionManager.AddToRegion("ViewA", unityContainer.Resolve<ViewA>()); 
regionManager.AddToRegion("ViewA", unityContainer.Resolve<ViewA>());

However if we write three or more lines of AddToRegion, only then it throws exceptions

regionManager.AddToRegion("ViewA", unityContainer.Resolve<ViewA>()); 
regionManager.AddToRegion("ViewA", unityContainer.Resolve<ViewA>());
regionManager.AddToRegion("ViewA", unityContainer.Resolve<ViewA>()); 

First, the AddToRegion API behaves inconsistently and different from Region.Add. Region.Add fails on the second attempt we try to add a duplicate Region, but not AddToRegion (Please uncomment/comment the TestModule and see it for your self)

if Scope Region is required, why does it not crash when we add two views to the same region, but crashes when we add three views? If i understand Scope Region correctly, it should crash on the second attempt to register the same region. 

The reason i call it a bug is because the API does not behave consistently.

@brianlagunas - do you think we should open this as a bug?

**Comment by brianlagunas** [comment]
Nah, not really.  Honestly this is not an important issue and not worth the time to figure out.  This will be one of those "no going to fix" issues.  If you wanted to take a stab at it that would be cool, but I'm not going to spend any time on it.

**Comment by dvorn** [comment]
The explanation for this issue is here: [DelayedRegionCreationBehavior creates regions too early](http://compositewpf.codeplex.com/workitem/9157)

**Comment by brianlagunas** [comment]
Good find!

**Comment by rohits79** [comment]
So are we saying we can patch the suggested fix?

**Comment by brianlagunas** [comment]
Well I would be very hesitant. This is a very old part of the code base, and I am personally not familiar with it.  The side effects are unknown to me, hence why I'm not sure we should be touching this code.

**Comment by dvorn** [comment]
@rohits79 If you are using your own copy of Prism, you may try the patch.  Also, you may just remove the subscription for UpdatingRegions event from DelayedRegionCreationBehavior, leaving only the subscription to the Loaded event - that will work (I tried that).

However, I second @brianlagunas that we should not change the existing official implementation.  There are probably hundreds and more various region adapters, region behaviors a such wriiten for the current implementation.  Not all of this code was written correctly (e.g., the code may not check that whether the control is loaded).  Changes of this kind may easily break a lot of existing (maybe, incorrect) code - but the blame will be on Prism.
