### ISSUE TITLE
[XF] IConfirmNavigation vs Android device back button

### ISSUE THREAD

**Issue by tomcrusader** [PrismLibrary/Prism#634]
Please provide as much detail as possible (and feel free to remove unused properties):

### Package info

- Platform: Android 6.0 (API 23)
- Prism version: 6.1.0-pre5
- Xamarin version (if applicable): 2.3.0.46-pre3

### Repro steps

* Implement `IConfirmNavigation` on two two Prism viewmodels
* Navigate from one page to another using Prism.Forms
* Push **physical back** button on Android device

### Expected behavior
CanNavigate called in the active ViewModel

### Actual behavior
Xamarin/Prism navigates back without CanNavigate being called

**Comment by brianlagunas** [comment]
This is a known issue and a limitation of Xamarin.Forms. currently XF does not provide an API to respond to the hardware back button.   Even when they expose this API, there will most likely not be an ability to prevent the go back from occurring. I will leave this open until XF adds the ability.

**Comment by tomcrusader** [comment]
Actually they do. Turns out you can override OnBackButtonPressed in the Page. I tried this and it worked:)

Added in 1.3
https://developer.xamarin.com/api/member/Xamarin.Forms.Page.OnBackButtonPressed/

There's also one in navigation page
https://developer.xamarin.com/api/member/Xamarin.Forms.NavigationPage.OnBackButtonPressed()/

**Comment by brianlagunas** [comment]
That won't work. I have been working with Xamarin and they will be adding a proper API in a future release. When they do, then I'll implement this functionality.

**Comment by tomcrusader** [comment]
What about the Android top left "Back" arrow when navigating with Prism; does the same limitations apply? Here I'm physically clicking in the app, but `INavigationAware `seems unaware (no pun intended)?

**Comment by brianlagunas** [comment]
It's the same problem regardless of if it is the hardware back button or the software back button.

**Comment by tomcrusader** [comment]
So this is still an issue with 6.2.0 - have Xamarin not come up with a solution yet?

**Comment by brianlagunas** [comment]
Xamarin has a solution, they just haven't implemented it yet.  Still waiting

**Comment by adrianknight89** [comment]
I need this functionality as well. Hope they can release an API soon.

**Comment by izefler** [comment]
+1

**Comment by brianlagunas** [comment]
Turns out, there will be no way to support IConfirmNavigation in this scenario as there is no way to use an event to hook into the OnBackButtonPressed.  The only way to support this is to override the OnBackButtonPressed in your application on an "as-needed" basis.

Some good news, is that I think I have found a way to support calling the other INavigationAware methods when using the system/hardware buttons.

**Comment by brandondsz** [comment]
I'm facing a similar issue where I'm navigating back from one view to another using the device back button or the back button on the navigation bar(top left). I need to pass parameters when this navigation happens. I tried doing this by overriding the OnNavigatedFrom(NavigationParameters parameters) method in my VM and I'm looking for the parameters in the OnNavigatedTo(NavigationParameters parameters) method on the VM of the page I'm navigating back to. However neither of the mentioned methods are hit with a break point.
