### ISSUE TITLE
UWP: Navigating with Absolute Uri and back button remaining

### ISSUE THREAD

**Issue by FrancoisM** [PrismLibrary/Prism#637]
In UWP when I try to reset the NavigationStack navigating away from a NavigationPage using an absolute URI, the UWP app shows a back button. It is inactive but should not be there.

`_navigationService.Navigate(new Uri($"http://myapp.com/{nameof(MyPage)}", UriKind.Absolute), null, null, false)`

Note: on Android the back button exits the app as expected and on iOS there is no back button as expected as well.

**Comment by dansiegel** [comment]
@FrancoisM , this sounds related to #476 which is waiting for a fix from Xamarin. If not could you provide more details like what version of Prism/XF you're using?

**Comment by FrancoisM** [comment]
@dansiegel I don't think this the same problem.
When my app starts it does the follwing and there is no back button.

`_navigationService.Navigate(new Uri($"http://myapp.com/{nameof(MyPage)}", UriKind.Absolute), null, null, false)`

Then when I want to 'reset' the app (after a logout for example), I call the same code from a NavigationPage. However now the back button is there.

In the issue  #476 , they try to navigate to a navpage with an existing page stack. In my case, MyPage is not a navpage.

My config is:
Prism.Core 6.1.0
Prism.Forms 6.1.0-pre4
Prism.Unity.Forms 6.2.0-pre4
XF 2.2.0.45

**Comment by brianlagunas** [comment]
Once again, this is a bug in Xamarin.Forms.  Here is the code to duplicate it in XF without Prism:

```
    public partial class App : Application
    {
        public App()
        {
            MainPage = new MainPage();
        }
    }

    public class MainPage : ContentPage
    {
        public MainPage()
        {
            Title = "MainPage";

            Button btn = new Button() { Text = "Navigate from MainPage", HorizontalOptions = LayoutOptions.Center, VerticalOptions = LayoutOptions.Center };
            btn.Clicked += Btn_Clicked;

            Content = btn;
        }


        private void Btn_Clicked(object sender, System.EventArgs e)
        {
            Navigation.PushModalAsync(new NavigationPage(new ViewA()));
        }
    }

    public class ViewA : ContentPage
    {
        public ViewA()
        {
            Title = "View A";

            Button btn = new Button() { Text = "Navigate from View A", HorizontalOptions = LayoutOptions.Center, VerticalOptions = LayoutOptions.Center };
            btn.Clicked += Btn_Clicked;

            Content = btn;
        }

        private void Btn_Clicked(object sender, System.EventArgs e)
        {
            Navigation.PushAsync(new ViewB());
        }
    }

    public class ViewB : ContentPage
    {
        public ViewB()
        {
            Title = "View B";

            Button btn = new Button() { Text = "Navigate from View B", HorizontalOptions = LayoutOptions.Center, VerticalOptions = LayoutOptions.Center };
            btn.Clicked += Btn_Clicked;

            Content = btn;
        }

        private void Btn_Clicked(object sender, System.EventArgs e)
        {
            Application.Current.MainPage = new MainPage();
        }
    }
```

**Comment by FrancoisM** [comment]
Tks @brianlagunas. Will wait for a XF update then.

**Comment by brianlagunas** [comment]
Here is the XF bug: https://bugzilla.xamarin.com/show_bug.cgi?id=41854

**Comment by FrancoisM** [comment]
That's efficiency!
