### ISSUE TITLE
Create new Prism Extensibility Pack

### ISSUE THREAD

**Issue by brianlagunas** [PrismLibrary/Prism#638]
I want to create a new Prism Extensibility Pack to place all the VS extension into.  This will make it easier to maintain the Prism Template Pack, and allow for more flexibility when building VS extensions.

I will be moving the App.config Module Editor into the Prism Extensibility Pack as the first extension.

**Comment by vinidiktov** [comment]
Is there a precompiled add-in for Xamarin Studio 6.0? I can't seem to find one in the XS Add-in gallery.

**Comment by dansiegel** [comment]
@vinidiktov the template pack for Xamarin Studio is being updated to work in Xamarin Studio 6.0

**Comment by brianlagunas** [comment]
The Prism Template Pack fro  Xamarin Studio 6 has been published.

**Comment by vinidiktov** [comment]
@brianlagunas  Great!

**Comment by vinidiktov** [comment]
@brianlagunas I have successfully created a Prism Unity solution using a shared library but I can't create a Prism Unity solution using PCL in Xamarin Studio 6.0. 

I'm getting this error message at the last page of the solution creation wizard:
"The project could not be created. Unknown solution item type: PortableDotNet"

**Comment by thomasflad** [comment]
Same Problem here

**Comment by brianlagunas** [comment]
Yeah, looks like there was a breaking change with XS 6.0.  The Project type = ‘PortableDotNet’ should be set to Project type = ‘C#PortableLibrary’

**Comment by thomasflad** [comment]
👍

**Comment by thomasflad** [comment]
I'm getting with the latest Update of XS the error:

The following dependencies required by this add-in are not available:

MonoDevelop.Core v6.0, found v6.0.1
MonoDevelop.Ide v6.0, found v6.0.1

**Comment by dansiegel** [comment]
@thomasflad thanks for reporting the issue. I'll be looking into that today.
