### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by JohannStudanski** [PrismLibrary/Prism#639]
- Prism version: 6.1

See https://github.com/PrismLibrary/Prism/search?utf8=%E2%9C%93&q=+GetNotAllreadyLoadedModuleInfos
=> Shouldn't this read "Already"? Or even better "NotYet" instead of "NotAlready"?

Yeah, I'm nitpicking, I know, and this is certainly no Prio1 ticket...

Cheers,

Johann

**Comment by brianlagunas** [comment]
Yeah, this is not something we are conferenced about :)
