### ISSUE TITLE
AutowireWireViewModel - Data Context of child view is overriden by MainWindow's DataContext

### ISSUE THREAD

**Issue by polepage** [PrismLibrary/Prism#640]
### Package info

- Platform: Windows 10 (WPF)
- Prism version: 6.1
- Other version info: .NET 4.6.1, VS2015

### Repro steps

I have a MainWindow that contains controls. Each control has its own ViewModel.
When using ViewModelLocator.AutoWireViewModel, the DataContext of each child controls is overridden by the MainWindow's DataContext. The controls view models are created, but binding on the viewmodel's property fails because it try to bind on MainWindowViewModel properties.

**Comment by polepage** [comment]
Additionally. It is the MainWindowViewModel that causes issue, if I remove the ViewModelLocator.AutoWireViewModel = true from MainWindow xaml, it stops failing.

**Comment by brianlagunas** [comment]
I am closing this because this is not an issue with the VIewModelLocator, but rather WPF DataContext inheritance.  Having said that, if a controls DataContext is set, it should not be overridden by it's parent.  Can you provide a repo app that demonstrates the issue?
