### ISSUE TITLE
Problem accessing page twice

### ISSUE THREAD

**Issue by emilianomon** [PrismLibrary/Prism#645]
It may be a foolish problem, but I haven't found a way out of this and I've been searching about it for a long while. Calling NavigationService.NavigateAsync("MyPage") seems to work just once, since when I travel back to the first page and then back to "MyPage", the app crashes.

What made come here and ask for help was the following sentence:
"Calling NavigationService.GoBack and hitting the back button do the exact same thing. The only difference is, for the moment, the INavigationAware methods don't get called when using the back button. I hope to fix that soon."
* It was written by Brian Dec/2015.

I'm travelling back hitting the back button, and thought this sentence could be describing my problem. Is it? And if it is, is this problem fixed? What is the workaround for that?

I really feel like this is an easy situation to solve, and because of that, I'm really sorry for bodering you. But be aware that I spent a lot of time searching about the problem and couldn't find any.

Anyway, I'd be thankful for any enlightenment on the case.

**Comment by brianlagunas** [comment]
Could you please provide more detail around the issue?  What is the exception?  What does your ViewModels/Vews look like?  It would be best if you can provide a sample app the reproduces the issue.

**Comment by emilianomon** [comment]
Sorry about that. I took for granted that it was a well known issue.

The exception is this:

> System.ArgumentException: An item with the same key has already been added.

The Views and ViewModels are as common as possible. It's not even worth to paste them here. The only "special" thing worth pointing out is that I'm using a MasterDetailPage. But since this problem use to happen when the app had just two simple pages, I can't think in a reason for this to have anything to do with the MasterDetailPage implementation.

Anyway, I think it'd be helpful to post at least the navigation calls. Maybe I'm missing something I can't notice.

- App.cs
`NavigationService.NavigateAsync("iDOMasterDetailPage/iDONavigationPage/SelectRequestCategoryPage", p, animated: false);`

- SelectRequestCategoryPageViewModel.cs
`await NavigationService.NavigateAsync("CreateRequestFirstPage", _navigationParameters, animated: false); `

- CreateRequestFirstPageViewModel.cs
`await NavigationService.NavigateAsync("CreateRequestSecondPage", _navigationParameters);`

Sorry too for only posting the calls and not a sample app. I'm really in a hush right now, but if this post does not help enough, I'll make time to create the sample.

Just remembering that the problem occurs when I go back, for example, to the SelectRequestCategoryPage and then back to CreateRequestFirstPageViewModel.

Thanks for your time!

**Comment by brianlagunas** [comment]
Based on the exception, and I see you are passing NavigationParameters, you have logic that is adding the same parameter to the NavigationParameter twice.  NavigationParameters is a Dictionary, and can only have one unique key at a time.

**Comment by emilianomon** [comment]
Uhhhmm. Didn't know about it. Thanks again. As I predicted, It was a foolish problem, but I could not find anything related. Sorry for that!
