### ISSUE TITLE
[XF] Roadmap / stable deep linking for Xamarin.Forms?

### ISSUE THREAD

**Issue by tomcrusader** [PrismLibrary/Prism#652]
Evolve delivered some great features, and quite a few that Prism needed, since latest depend on 2.3.x pre.

XF 2.3.0 Stable was just released (jippie):
http://forums.xamarin.com/discussion/67709/xamarin-forms-2-3-0-stable/p1

So how are things looking, @brianlagunas , now that the cat's out of the bag? :)
What's the time line for a Stable Prism.Forms (with deep linking), i.e. "production ready".

**Comment by brianlagunas** [comment]
See issue #648

**Comment by tomcrusader** [comment]
Cool, so next stable which can't be that far off. Look forward to it
