### ISSUE TITLE
Behavior Attached To ListView In WindowContent Of PopupWindowAction Never Attaches

### ISSUE THREAD

**Issue by whandley** [PrismLibrary/Prism#653]
- Platform:  Windows 8.1
- Prism version: 6.1

Issue in detail:

The attached behavior is added to the ListView with the following:
                    <wi:Interaction.Behaviors>
                        <behaviors:ListViewSortBehavior 
                            DefaultSortColumn="{Binding Model.DefaultSortCol}" 
                            DefaultSortDirection="{Binding Model.DefaultSortDir}" />
                    </wi:Interaction.Behaviors>

Where wi: is clr-namespace:System.Windows.Interactivity;assembly=System.Windows.Interactivity
and i:: is http://schemas.microsoft.com/expression/2010/interactivity

I use this behavior without a problem on ListViews in several other UserControls (views) in the same project, however they are navigated to, thus they are housed within my Shell. This is the only case where I am using it in a UserControl that is displayed via an InteractionRequestTrigger, thus it is housed inside a PopupWindowAction window.

I have confirmed with a breakpoint that OnAttached never fires. As an additional test, I've placed this same UserControl in a standard WPF window in a new project outside of Prism, and OnAttached does fire.

I can only conclude that something inside PopupWindowAction is blocking attached behaviors.  If true, would appreciate a workaround, including as a temporary measure attaching the behavior programmatically in the codebehind of the UserControl.  My searches so far for a way to do this have turned up nothing that works.  The point I'm hung up on is how to set the bindings programmatically on the Behavior for several dependency properties.

**Comment by brianlagunas** [comment]
PopUpWindowAction does nothing in regards to blocking/controlling behaviors.  All it does is show a Window with the Content property set.  Please provide a sample app the reproduces this issue.  I would also suggest taking the PopupWindowAction code and brining it into your own application and using it so that you can debug the issue:

https://github.com/PrismLibrary/Prism/blob/master/Source/Wpf/Prism.Wpf/Interactivity/PopupWindowAction.cs
