### ISSUE TITLE
Inconsistent (and incorrect) error reporting in RegionManager.RequestNavigate

### ISSUE THREAD

**Issue by dvorn** [PrismLibrary/Prism#658]
### Package info

- Platform: WPF
- Prism version: 5.x and 6.x
- Other version info: not applicable to 4.x

### Repro steps
Method
`RegionManager.RequestNavigate(string regionName, Uri source, Action<NavigationResult> navigationCallback)`
when region `regionName` does not exist invokes the callback with `new NavigationResult(new NavigationContext(null, source), false)` as a parameter.  
(No navigation events are triggered because there is no navigation service on which to trigger an event.)

However,
`RegionManager.RequestNavigate(string regionName, Uri target, Action<NavigationResult> navigationCallback, NavigationParameters navigationParameters)`
when region `regionName` does not exist does nothing.

**Comment by dvorn** [comment]
Fix it?

**Comment by brianlagunas** [comment]
I haven't had time to verify it yet, but go ahead and get your PR together to fix it.

**Comment by dvorn** [comment]
Verification: https://github.com/PrismLibrary/Prism/blob/master/Source/Wpf/Prism.Wpf/Regions/RegionManager.cs#L379

**Comment by brianlagunas** [comment]
Well that makes it easy :)
