### ISSUE TITLE
[XF] Simplify Platform View Registration

### ISSUE THREAD

**Issue by dansiegel** [PrismLibrary/Prism#664]
Container Extensions should include an overload that handle OnPlatform needs with a shared ViewModel. This should be able to take a type for one or more platforms and a default similar to below. By convention if a name is not provided it take the Name of the ViewModel without the ViewModel part. This would simplify platform specific view implementations.

```cs
container.RegisterTypeForNavigationOnPlatform<MyViewViewModel>(
            iOSView: typeof( MyView_iOS )
            DefaultView: typeof( MyView ) );

NavigationService.NavigateAsync( "MyView" );
```

**Comment by joacar** [comment]
Good idea. I would also like to see something similar to handle different screen sizes so it is possible to load a different view e.g. on larger tablets.

**Comment by brianlagunas** [comment]
This can be done with the new IPlatformInitialzer.

**Comment by dansiegel** [comment]
Not really... it can certainly be done. The issue goes back to when the ViewModelLocator was extended. It would be an enhancement so that you don't need to do: 

```cs
 Device.OnPlatform(
    iOS: () =>
    {
        Container.RegisterTypeForNavigation<SomePage_iOS>();
        ViewModelLocationProvider.Register<SomePage_iOS>,SomePageViewModel>();
    },
    Default: () =>
    {
        Container.RegisterTypeForNavigation<SomePage>();
        ViewModelLocationProvider.Register<SomePage, SomePageViewModel>();
    } );
```

and instead could simply provide the platform View Type and shared ViewModel so that it can be done on one line.

**Comment by brianlagunas** [comment]
Why can't this be done using IPlatformInitializer?

**Comment by dansiegel** [comment]
the idea is to simplify it by allowing you to continue making the registrations in the shared code. Again the pieces are already there, it's just providing an new extension to make it cleaner when dealing with multiple views depending on the Target Platform or Idiom.

**Comment by brianlagunas** [comment]
Actually, I just thought about one scenario.  Modules.  If loading modules, these View resgitrations won't go through the IPlatformInitializer.

So, let's discuss the API, and what it should looks like/behave.

**Comment by brianlagunas** [comment]
The important thing is that we do not create confusion between this new method and the current extension methods for registering types for navigation.

**Comment by brianlagunas** [comment]
Here are some possible API's for this feature

A - the first TView is used as the default view
```
            container.RegisterTypeForNavigationOnPlatform<ViewA, ViewAViewModel>(
                iOSView: typeof(iOSView), 
                androidView: typeof(AndroidView));

            navigationService.NavigateAsync<ViewAViewModel>();

            container.RegisterTypeForNavigationOnPlatform<ViewA, ViewAViewModel>(
                name: "ViewA",
                iOSView: typeof(iOSView), 
                androidView: typeof(AndroidView));

            navigationService.NavigateAsync("ViewA");
```
B - a default view type must be provided as a param
```
            container.RegisterTypeForNavigationOnPlatform<ViewAViewModel>(
                defaultView: typeof(ViewA), //not optional
                iOSView: typeof(iOSView), 
                androidView: typeof(AndroidView));

            navigationService.NavigateAsync("ViewA");

            container.RegisterTypeForNavigationOnPlatform<ViewAViewModel>(
                name: "ViewA",
                defaultView: typeof(ViewA), // not optional
                iOSView: typeof(iOSView), 
                androidView: typeof(AndroidView));

            navigationService.NavigateAsync("ViewA");
```

I am worried that option A would cause a lot of confusion with the current RegisterTypeForNavigation<TVIew, TVIewModel> and when to use NavigationService.NavigateAsync("name") vs. NavigateAsync<TViewModel>.

Using option B though there is no way to use the NavigateAsync<TVIewModel> approach to navigation which a lot of devs like.

Thoughts/ideas?

**Comment by brianlagunas** [comment]
Also, what about those cases where each platform page uses a different ViewModel?

**Comment by brianlagunas** [comment]
The what about scenarios where one pages use one VM and another page uses a different VM?

**Comment by dansiegel** [comment]
Well crazy scenario's should probably still be the responsibility of the developer to implement something that fits their needs. But I think the common ones can be easily added to Prism, with those being Target Platform and Device Idiom. Either of these scenarios really revolve around you have a single ViewModel but a different View that needs to be used. 

If it helps perhaps we should remove or alter the existing ```RegisterTypeForNavigation<TView,TViewModel>( ... )```. Currently all it's really doing is allowing you to use a bad navigational pattern. I think in most developers minds when they see that signature they are thinking what I originally thought, which was that I can have ```MyPage``` for a View and ```SomeRandomViewModel``` which the ViewModelLocator will be able to properly resolve.

**Comment by brianlagunas** [comment]
@dansiegel I don't think we should remove it.  It is still a common way for devs to think about navigating.  Check out #666 .  This change will essentially do what you were first expecting.  It will register whatever ViewModel you specified as the one to use, and allow you to navigate to it using `NavigateAsync<SomeViewModel>()`

**Comment by joacar** [comment]
How should this be handled in `PageNavigationService` and `PageNavigationRegistry`? Something like

````c#
public static void Register(string name, Type pageType, Platform platform, Idiom idiom)
{
    ....
}
````
and then in `public static Type GetPageType(string name)` check the `Device.Platform` and find any appropriate overload other default to none? Or do we simply put this on the developer to handle in `CreatePage(string segmentName)` in `PageDialogService`?

**Comment by brianlagunas** [comment]
@joacar it's simpler than that.  We are creating a new extension methods with this signature:

```
RegisterTypeForNavigationOnPlatform<TView, TViewModel>(this IUnityContainer container, string name = null, Type AndroidView = null, Type iOSView = null, Type OtherView = null, Type WindowsView = null, Type WinPhoneView = null)
```
```
RegisterTypeForNavigationOnIdiom<TView, TViewModel>(this IUnityContainer container, string name = null, Type DesktopView = null, Type TabletView = null, Type PhoneView = null)
```

**Comment by powerdude** [comment]
any chance of renaming the parameters to camel case?

**Comment by brianlagunas** [comment]
yeah, I think the idea was to mimic the Device.OnPlatform. That can easily be changed though.

**Comment by dansiegel** [comment]
yeah the idea is to mimic ```Device.OnPlatform```. It does break the camel case convention, but I think given the scenario it's an acceptable break from convention.
