### ISSUE TITLE
[XF] Improve RegisterTypeForNavigation<TView, TViewModel>

### ISSUE THREAD

**Issue by brianlagunas** [PrismLibrary/Prism#666]
Currently, `RegisterTypeForNavigation<TView, TViewModel>` simply registers the TViewModel as the navigation key.  The ViewModelLocator still uses reflection to generate the ViewModel to create based on the convention.

Since the VM type is already being provided, I think it is safe to assume that this is the VM that the dev wants to use for the BindingContext.  So we can change this method to use this VM for the BindinContext instead of using the convention and improve performance.

So the method will now look like:

```
        public static IUnityContainer RegisterTypeForNavigation<TView, TViewModel>(this IUnityContainer container)
            where TView : Page
            where TViewModel : BindableBase
        {
            ViewModelLocationProvider.Register<TView,TViewModel>();
            return container.RegisterTypeForNavigation<TView>(typeof(TViewModel).FullName);            
        }
```
Keep in mind that devs can no longer use just any class for a strongly typed navigation, they must use the class they want to use as the BindingContext.  Though, I don't think this would be bad assumption.

Thoughts?

**Comment by dansiegel** [comment]
I think it's safe to say that if a dev is providing a View and ViewModel that's the ViewModel they want to use for that View and it should be registered. I just don't think that the name should be the FullName of the ViewModel. I think a common scenario here is like in #664 where you might have ```MyPage_iOS```, ```MyPage_Droid```, ```MyPage``` which all use the ```MyPageViewModel``` and what you would expect would be ```NavigationService.NavigateAsync( "MyPage" )``` and not ```NavigationService.NavigateAsync( "MyProject.ViewModels.MyPageViewModel" )```

**Comment by brianlagunas** [comment]
Then that would essentially render `NavigatAsync<TViewModel>` broken, which in turn will break a number of apps.  I know this is a common pattern for devs to navigate to ViewModels.  Removing it would standardize the navigation though.

If anything, maybe we provide a RegisterViewModelForNavigation extension methods which would support the `NavigateAsync<TVIewModel>`.  Does that make the intent of the method more clear?
