### ISSUE TITLE
PopUpWindowAction + MouseDoubleClick and Touchscreen

### ISSUE THREAD

**Issue by HartlD** [PrismLibrary/Prism#668]
Hello,
i have the following Problem, I've created an short example Project:
1. Works: If I make an mouse double click in retangle a PopUp will be shown and i can close it if i press one button with mouse(Test1|Test2|...).
2. Works: If I make an mouse double click in retangle a PopUp will be shown and i can close it if i press one button with touch(Test1|Test2|...).
3.Work don't work:
If I make a touch double click in retangle a PopUp will be shown and i can close it if i press TWICE on a button with touch(Test1|Test2|...).

[UserControlTouchWindowTest.zip](https://github.com/PrismLibrary/Prism/files/336910/UserControlTouchWindowTest.zip)

**Comment by dvorn** [comment]
The attached project uses **Custom**PopUpWindowAction.  This may not be a problem in Prism.

**Comment by brianlagunas** [comment]
This is not related to Prism but rather how WPF handles focus during touch on a double click (double touch).  The ListBox is keeping focus, so you have to give focus to the popup before you can close it with touch.  Change your event to MouseUp and it will work.
