### ISSUE TITLE
Exception when using AutoWireViewModel on Android

### ISSUE THREAD

**Issue by polepage** [PrismLibrary/Prism#671]
### Package info

- Platform: Android 6.0 (API 23)
- Prism version: 6.1.0 (Core) and 6.1.0-pre6 (Forms). I also tried 6.0.1 (Forms)
- Xamarin version (if applicable): 2.3.0.107
- Debug, Any CPU. On an actual device.
- Targets: .NET 4.5.1, Windows 8.1, Xamarin.Android, Xamarin.iOS, Xamarin.iOS (Classic)

### Repro steps

When using ViewModelLocator.AutoWireViewModel, I get a "System.IO.FileNotFoundException: Could not load file or assembly 'Prism.Forms' or one of its dependencies" exception. The Prism.Forms library cannot be found in code either.

Prism.Forms.dll was downloaded successfuly from nuget and copied in the bin dir. It is also correctly added as a Reference in the project.

Thank you.
Pierre

**Comment by brianlagunas** [comment]
Make sure you have added the correct references to all projects in your solution.  If one fails they all fail.
