### ISSUE TITLE
[XF] Improve MasterDetailPage with NavigationPage scenarios

### ISSUE THREAD

**Issue by brianlagunas** [PrismLibrary/Prism#675]
I have identified two main scenarios for navigating within a MasterDetailPage when dealing with a NavigationPage.

`_navigationService.NavigateAsync("MyNavigationPage/ViewA");`

1. The Detail is set to a new NavigationPage each time.

1. The Detail is already a NavigationPage and the next view is simply PushAsync onto the nav stack. This keeps an appearance of history within the MasterDetail and the back button will function as some apps require.

**Scenario 1**
Currently, the MasterDetaiPage navigation logic will always reuse the Detail if it is the same type.  In the case of a NavPage, we clear the NavigationStack of the NavPage and then PushAsync.  This has a side-effect of animating the icon which is an undesirable visual animation.  We can add an additional check to always create a new NavigationPage to fix this (this is the approach all Xamarin samples show).

**Scenario 2**
Currently, the NavPage navigation logic always clears the nave stack (PopToRoot) and then pushes the target page onto the nav stack.  Because of this, we can **never** achieve this scenario since we don't simply PushAsync to maintain a nav history.  This logic may be flawed.  The only time I can think of someone navigating from a NavPage directy, is in the MasterDetail scenario.  We can update the logic to always PushAsync and never clear the NavStack.  Is there any other scenario in which someone would navigate directly from a NavigatinPageViewModel?

Thoughts?

**Comment by totht91** [comment]
I also struggled with this problem. In my opinion the expected behavior is the Details reuse the NavigationPage and keep the nav history.

**Comment by brianlagunas** [comment]
The default behavior will always be a new NavPage (scenario 1), but I am trying to think of how to make scenario 2 more easily implemented.

**Comment by totht91** [comment]
It's a little bit hard to understand and follow the flows in the navigation service, but I don't know how to improve it.

**Comment by brianlagunas** [comment]
So I am thinking of adding an interface similar to:

```
    public interface INavigationPageOptions
    {
        bool ClearNavigationStackBeforeNavigation { get; }
    }
```
If the NavigationPage or it's ViewModel implement this interface, it can control the behavior of the navigation when navigating directly from the NavPage.

Thoughts?

**Comment by powerdude** [comment]
sorry for jumping in late here, but wouldn't it be better to add a property to NavigationParameters to control this.  It seems the caller should possibly have control, since it has the knowledge of choosing to go the page, to decide if the stack should be clear or not, just like it makes the decision to show a page as modal or not.  To have the view/viewModel make this choice would seem to limit the view/viewModel.

**Comment by brianlagunas** [comment]
No.  This is not discoverable and is very prone to bugs.  The behavior of a NavigationPage should not be dynamic or change.  It should be decided based on application flow during the design process.  This is a position I have taken as guidance.

**Comment by powerdude** [comment]
as far as discoverabilty, i wasn't suggesting adding the value as a string in the dictionary, but doing this:

```
public class NavigationParameters : IDictionary<string, object>
{
       public bool ClearStackBeforeNavigation { get;set;}
}

```

that makes it a bit more obvious, doesn't it.  

As far as your other statement is concerned, you're saying if I make a custom navigation page `MyNav1` that I can't decide to clear the stack in one instance but leave it alone in another.  That seems restrictive, and to be honest, i haven't run into a situation yet where i'd do this anyway, but it does just seem to tie my hands needlessly.

**Comment by brianlagunas** [comment]
This is not good either.  Now we are starting to break standard design principles.  The NavigationParameters has one job, and we do not want to start placing state that manages the behavior of the navigation service in a very specific scenario onto the NavParams class.  Also, this nav params class is going to be cross plat as soon as I can get into UWP.

> you're saying if I make a custom navigation page  MyNav1  that I can't decide to clear the stack in one instance but leave it alone in another

No, that's not what I'm saying.  That's why you use an interface.  You can provide logic to control the result of the ClearStackOnNavigation property.  Having said that, I personally would not do that as that could be a source of bugs in the app.  I would recommend having two diffferent navPages. One for each specific scenario and use the navPage you need when you need it.  If you needed it.  I haven't run into any apps that would require that behavior.
