### ISSUE TITLE
Navigation service for child frame

### ISSUE THREAD

**Issue by yeasin90** [PrismLibrary/Prism#680]
Hi,
(I am not sure if it's the good place for such post)

In my UWP app, I have MainPage.xaml which contains a Grid and inside this Grid, I have a Frame.
Now, prism navigation service will work for MainPage.xaml (as it's my initial landing page in current window)

Is it possible to get a Prism navigation service for Child Frame? I mean any navigation with Navigation service will occur for that child frame. Using NavigationService.Navigate() actually navigates the entire page rather than for a specific Frame control

**Comment by brianlagunas** [comment]
This currently not supported.
