### ISSUE TITLE
WPF Prism RegisterTypeForNavigation with viewmodel type

### ISSUE THREAD

**Issue by opcodewriter** [PrismLibrary/Prism#681]
In WPF + Prism, how can I navigate to a strongly type object using view-model type:

     _navigationService.NavigateAsync<MainPageviewModel>();

     Container.RegisterTypeForNavigation<MainPage, MainPageViewModel>();

I see Xamarin Forms has this, but not WPF!?

**Comment by brianlagunas** [comment]
Actually, in the latest Prism for Xamarin.Forms pre-7, this was removed.  But don't worry, it' just an extension method.  You can create your own extension methods to get this functionlaity.  You extension methods should use the ViewModel FullName as the resgitration key, and then use that same key to navigate to.  Use this as a guide, but modify it to work with WPF:

https://gist.github.com/brianlagunas/40b8a7d1e25ccc64623b19f11d758171
