### ISSUE TITLE
Splash screen

### ISSUE THREAD

**Issue by paulb2099** [PrismLibrary/Prism#685]
Hi,

Are there any plans to add a standard splash screen to the Prism library?
I know that UWP has the extended splash screen, but there doesn't seem to be anything like this for WPF.

I'm thinking it would be a module, but is displayed outside of the main shell.
It would just display a progress bar and text messages.

At startup, the main shell is hidden, whilst the splash screen is displayed.

As the bootstrapper loads modules, the modules would publish event aggregator events, that are received by the splash screen module (which would update the progress bar and/or display messages from the modules).

Once all modules are loaded, the splash screen exits, and the main shell is displayed.

**Comment by dansiegel** [comment]
A SplashScreen cannot be done from a PCL so the short answer is no. As for the templates, see #663, the Android project will be getting a basic Splash Screen that you can change as you see fit. The iOS project already has one. I honestly haven't spent the time to see what or if anything needs to be done for the WinPhone, Windows, & UWP projects.
