### ISSUE TITLE
Updating a property in ViewModel through DelegateCommand doesn't update the UI/View

### ISSUE THREAD

**Issue by deb1bhu** [PrismLibrary/Prism#686]
I have a code where i want to update the UI when some progress is going on in ViewModel. I set the property value to "Please wait" through some DelegateCommand. Although the value gets updated for the property but view doesn't get updated. If I change the property value through some method in ViewModel it updates the UI.

is this a known issue or bug in Prism 6?

Platform:
- Prism version: 6.
- Visual studio- 2015

code snippet
XAML:  TextBlock Text="{Binding UpdateValue, Mode=TwoWay}"

in ViewModel

private string _updateValue;
        public string UpdateValue
        {
            get
            {
                return this._updateValue;
            }
            set
            {
                this._updateValue = value;
                this.OnPropertyChanged("UpdateValue");
            }
        }

Constructor: 
ViewModel()
{
 ConnectCommand = new DelegateCommand<string>(ExecuteConnectionWindow);
...
}

private void ExecuteConnectionWindow(string obj)
{
            _updateValue = "Please wait...";
             ...
}

But it doesn't change the UI property.

**Comment by dvorn** [comment]
It should be 

this.UpdateValue = "Please wait...";

**Comment by deb1bhu** [comment]
I got the issue. I don't know if its a bug in prism 6 or it's the design of Prism. 
However let me point out the core issue.

I thought in Prism 6.0 there is no difference between OnPropertyChanged() method and Setproperty() method except using SetProperty<T> You can reduce the set method to just one line also ref parameter allows you to update its value.

But there is a difference between OnPropertyChanged() method and Setproperty() method. 
However there should not be as BindableBase is an abstract class implements INotifyPropertyChanged().

public abstract class BindableBase : INotifyPropertyChanged
{...}

If I have a property "UpdateValue" in MainViewModel with SetProperty() method.
And I want to update the value through some method in the ViewModel and also some "DelegateCommand". the value gets updated but it doesn't update the UI when I use "DelegateCommand" 

But for the same property value uses "OnPropertyChanged()" then the value gets updated in the UI through "DelegateCommand".

Can anyone explain this behaviour.

**Comment by dvorn** [comment]
There is no difference in behavior.  Provide the code that does not work for you.

**Comment by deb1bhu** [comment]
I have attached the code here. Sorry for the late reply as I have to create a new project and then share.
[PrismDummyApp.zip](https://github.com/PrismLibrary/Prism/files/375778/PrismDummyApp.zip)

Thanks

**Comment by dvorn** [comment]
@deb1bhu  You should not set the value of the underlying field before calling SetProperty.  SetProperty sees that the value did not changed and does nothing:

_updateValue1 = value;  // <<<< remove that
SetProperty(ref _updateValue1, value);

**Comment by deb1bhu** [comment]
Ohhh 
Thanks for the help. It really works.
