### ISSUE TITLE
DirectoryModuleCatalog Can't Load dlls in Subfloder

### ISSUE THREAD

**Issue by Iamcaibi** [PrismLibrary/Prism#687]
DirectoryModuleCatalog Can't Load dlls in Subfloder。
I want create Subfloder in DirectoryModuleCatalog's ModulePath,and take module dlls in it,but it not work.

**Comment by dvorn** [comment]
Why not set the subfolder as the ModulePath of the DirectoryModuleCatalog?

**Comment by brianlagunas** [comment]
The DirectoryModuleCataglog does not recursively search the directory tree.  You need to either specify which directory you want o search, or create a custom catalog that does what you want.
