### ISSUE TITLE
Can't load modules in subfloder 

### ISSUE THREAD

**Issue by Iamcaibi** [PrismLibrary/Prism#689]
why not search subfloder for modules,i want to take one module in a floder.

**Comment by dvorn** [comment]
With the current Prism version, you can have two DirectoryModuleCatalogs, one for directory and another for subdirectory, and combine them using https://github.com/PrismLibrary/Prism-Samples-Wpf/blob/master/Modularity/ModularityWithUnity/ModularityWithUnity.Desktop/AggregateModuleCatalog.cs
