### ISSUE TITLE
[WPF] DelegateCommand's CanExecute is not called first time when property changes when using ObserveProperty

### ISSUE THREAD

**Issue by opcodewriter** [PrismLibrary/Prism#690]
I have a ListView with `SelectedItem={Binding SelectedItem}` and `SelectionMode="Single"`.
First time I click on an item the `CanExecute` func of the command receives null.
After this, when selecting other items, `CanExecute` func receives non-null items.

```
public class ItemListViewModel : BindableBase
{
        private Item _selectedItem;
        public Item SelectedItem
        {
            get { return _selectedItem; }
            set
            {
                if (_selectedItem!= value)
                {
                    _selectedItem= value;
                    OnPropertyChanged(() => SelectedItem);
                }
            }
        }

        public ICommand RunItemCmd { get; private set; }

        public ItemListViewModel () 
        {
            RunItemCmd = new DelegateCommand<Item>(
                        (item) => {  }, 
                        (item) => item != null)
            .ObservesProperty(() => SelectedItem);
         }
}
```

**Comment by dvorn** [comment]
More likely is that CanExecute is called first time when the view is initially bound to view model.  At that time the selected item is uninitialized (null).

**Comment by opcodewriter** [comment]
No, I mentioned it's null on **first click**.

**Comment by dvorn** [comment]
I have similar setup in a _number_ of project and cannot confirm that.  Could you provide a project?

**Comment by dvorn** [comment]
@opcodewriter Note that the item is provided by the view as the parameter to the command.  Thus, it actually depends on your view and not view model.

**Comment by opcodewriter** [comment]
@dvorn Thank you for taking time to respond. 
I've been swamped, I plan to look again over this. 
It didn't look like a problem on my side.

**Comment by dvorn** [comment]
@opcodewriter 
```csharp
RunItemCmd = new DelegateCommand(
                        () => { ... SelectedItem ...  }, 
                        () => SelectedItem != null)
            .ObservesProperty(() => SelectedItem);
```

**Comment by opcodewriter** [comment]
Thanks. 
Actually sing `SelectedItem != null` in the "can execute" action is how I "fixed" it at that time.
My impression was that the parameter passed in "can execute" action is the value of `CommandParameter`, therefore I could check on it instead of using the property.
I was expecting that SelectedItem gets changed before the "can execute" action get called . After all, it's called because SelectedItem property get changed.
Isn't how things work?

**Comment by opcodewriter** [comment]
So the flow I was expecting is this:
1. I select an item in the ListView
2. SelectedItem property setter gets called. 
   **`_selectedItem` gets set to the item selected in the ListView.**
   Here, I also call `OnPropertyChanged` which raises the `INotifyPropertyChanged` event. Since `ObservesProperty` listens to this event too for the `SelectedItem` property, it calls `RaiseCanExecuteChanged` on the `RunItemCmd` command.
3. `RaiseCanExecuteChanged` on the `RunItemCmd` command calls my Action `(item) => item != null` passing the `CommandParameter` defined in the view, which resolves to calling the `SelectedItem` getter. 
4. The `SelectedItem` getter returns `_selectedItem` value which is not null.

**Comment by dvorn** [comment]
@opcodewriter Again, it depends on what is in your view.

SelectedItem is a dependency property of the ListView.  You click in the list and the value of SelectedItem is being modified.  During modification, it triggers a two-way binding (I suppose that is in your view) which modifies SelectedItem in view model which triggers RaiseCanExecuteChange of the command which triggers a request for CanExecute with a parameter.  But a parameter (I suppose that is in your view) is again that same SelectedItem property which is still being modified...

**Comment by opcodewriter** [comment]
See step 3 and 4. At the time when `CommandParameter` is resolved the `SelectItem` property returns the selected item

**Comment by dvorn** [comment]
@opcodewriter No.  The SelectedItem dependency property, for obtaining its value, does not query the SelectedItem in the view model.   It has its own value.  And the two-way binging attempts to synchronize the two.

**Comment by opcodewriter** [comment]
So the button in view looks like this:
```
<Button Content="Run"
             Command="{Binding RunItemCmd}"
             CommandParameter="{Binding SelectedItem}" />
```
I think I understand what's going. Please correct me:
When button is created, WPF "resolves" `CommandParameter` value. Obviously, at this point it's `null` because this is the default value of `SelectedItem` property of the view-model.

I was having the impression that at the moment when CanExecute action gets called, the `CommandParameter` is going to have the current value of the `SelectedItem` property in the view-model. 
I'm a bit confused now, I need a break, too much work.

**Comment by opcodewriter** [comment]
I think I got a bit confused :)

The commanding implementation so to speak, is not listening to the changes in binding I set to `CommandParameter`. Therefore, it cannot know about the change on `SelectedItem`.
It only reads the binding value once, at button creation item.
Which I think makes sense :) 
But it would have been nice if framework could read it again when calling the CanExecute action.

**Comment by brianlagunas** [comment]
You're expecting a parameter, but your aren't defining a command that takes a parameter.  You are using a simple DelegateCommand and not a `DelegateCommand<T>`  If you want to use your CommandParameter for the CanExecute logic, you need to be using `DelegateCommand<T>`

**Comment by dvorn** [comment]
@brianlagunas Actually he uses DelegateCommand<Item>

**Comment by opcodewriter** [comment]
I'm pretty sure I'm using `DelegeateCommand<T>`, otherwise I won't be able to use a lambda with input parameter for the "can execute" action, it wouldn't compile.

**Comment by dvorn** [comment]
What happens is this: DelegateCommand is subscribing to PropertyChanged(SelectedItem) event of view model in the constructor of view model.  Later, when the view is attached to the view model (DataContext assignment), CommandParameter is also subscribing to the same PropertyChanged event.  Event handlers are executed in the same order.  When CanExecute is evaluated for the first handler, the second has not be executed and hence CommandParameter has the old value.

@opcodewriter You may also bind CommandParameter to SelectedItem dependency property of your ListBox and not of view model.

**Comment by opcodewriter** [comment]
I think I see what you mean.
This issue shouldn't exist, it's too complex for such a simple purpose...
To me it looks like `ObservesProperty` adds some unexpected side effects. 
What am I doing wrong? Is everyone else using the view-model property in the lambda there and not the lambda parameter? It doesn't look OK to me, what's the point of having parameter passed to the can execute if I can't use it for some reason...

**Comment by brianlagunas** [comment]
@dvorn I was going off of this snippet that @opcodewriter provided:
```
RunItemCmd = new DelegateCommand(
                        () => { ... SelectedItem ...  }, 
                        () => SelectedItem != null)
            .ObservesProperty(() => SelectedItem);
```

@opcodewriter ObservesProperty behaves exactly as it should.  It simply calls DelegateCommand.RaiseCanExecuteChange when the INPC of the specific property is invoked.  That's it.  So when the SelectedItem property changes, RaiseCanEecuteChanged is called for the command, and no parameter will be passed because this was not raised from the UI.

My question to you is why are you using ObservesProperty in the first place if you are using the CommandParameter to pass your state to the CanExecute?  You should only be using ObsrvesProperty if you need to call RaiseCanExecuteChanged in response to the value of a VM property being changed.

**Comment by opcodewriter** [comment]
That's not my snippet, it's @dvorn's: https://github.com/PrismLibrary/Prism/issues/690#issuecomment-235671017

**Comment by opcodewriter** [comment]
> You should only be using ObsrvesProperty if you need to call RaiseCanExecuteChanged in response to the value of a VM property being changed

That's my scenario I think. 
My impression is that without `ObservesProperty`, I'd need to call `RunItemCmd.RaiseCanExecuteChanged()` in the `SelectedItem` property setter.

**View**:

```
<ListView SelectedItem="{Binding SelectedItem}" ItemsSource="{Binding Items}" />
<Button Content="Run"
             Command="{Binding RunItemCmd}"
             CommandParameter="{Binding SelectedItem}" />

```
**ViewModel**:

```
public class ItemListViewModel : BindableBase
{
        private Item _selectedItem;
        public Item SelectedItem
        {
            get { return _selectedItem; }
            set
            {
                if (_selectedItem!= value)
                {
                    _selectedItem= value;
                    OnPropertyChanged(() => SelectedItem);
                }
            }
        }

        public ICommand RunItemCmd { get; private set; }

        public ItemListViewModel () 
        {
            RunItemCmd = new DelegateCommand<Item>(
                        (item) => {  }, 
                        (item) => item != null)
            .ObservesProperty(() => SelectedItem);
         }
}
```

**Comment by opcodewriter** [comment]
I don't show `Items` property in the view-model, I don't think it matters.

**Comment by dvorn** [comment]
@opcodewriter `CommandParameter="{Binding SelectedItem}"` means "take the value from view model, pass it to view, use it as parameter to the command and execute that command in the view model.  No need pass the value back and forth between view and view model.  Use the command without parameter.

Commands with parameters were designed for the following:
```xaml
<ListView Name="LV" SelectedItem="{Binding SelectedItem}" ItemsSource="{Binding Items}" />
<Button Content="Run"
             Command="{Binding RunItemCmd}"
             CommandParameter="{Binding ElementName="LV" Path="SelectedItem}" />


```

**Comment by dvorn** [comment]
@opcodewriter 
> This issue shouldn't exist, things are too complex for such a simple purpose...

The problem is not in Prism implementation, it is in intrinsic to the command with parameter.  Google "commandparameter canexecute"

**Comment by opcodewriter** [comment]
Even with 
`<Button Content="Run"
             Command="{Binding RunItemCmd}"
             CommandParameter="{Binding ElementName=LV, Path=SelectedItem}" />`

When `SelectedItem` changes, the `ICommand.CanExecute` is not called.
I wish WPF did that.

**Comment by brianlagunas** [comment]
Yes it does.  Set a break point on CanExecute.  When you make a new selection in the LV, the SelectedItem is updated, and the CanExecute is called.

The code snippet you provided will absolutely no impact on whether CanExecute will be called or not. 
```
<ListView Name="LV" SelectedItem="{Binding SelectedItem}" ItemsSource="{Binding Items}" />
``` 
This is what causes it to get called.  When you make a new selection in the LV.

**Comment by opcodewriter** [comment]
When I select an item in the LV, `CanExecute` gets called only if in the `SelectedItem` property setter I call `RaiseCanExecuteChanged` on the command.

If I don't call `RaiseCanExecuteChanged`, the CanExecute is not called.

What I was saying was that I wish the `CommandParameter` property implementation called `CanExecute` when the `CommandParameter` binding changed. 
I can see that there's no 'property changed' callback:
http://referencesource.microsoft.com/#PresentationFramework/src/Framework/System/Windows/Controls/Primitives/ButtonBase.cs,202
When Command is changed, it does fire `CanExecute`:  http://referencesource.microsoft.com/#PresentationFramework/src/Framework/System/Windows/Controls/Primitives/ButtonBase.cs,288

While I realize calling `CanExecute` on the command when parameter has changed does not always make sense, I can see it useful in some very common scenarios. If framework could do this, I wouldn't have to implement a field for the Command and call RaiseCanExecuteChanged. 
Would nice if ButtonBase had a bool property like 'RaiseCanExecuteChangedOnParameterChange` or something.

**Comment by opcodewriter** [comment]
I updated my previous comment...

**Comment by brianlagunas** [comment]
Do you have a sample that demonstrates the issue?  It works perfectly for me.  When I make a new selection, SelectedItem is changes, INPC is invoked, and CanExecute is then called.

Obviously we can't control anything that ButtonBase does, and honestly, I don't think I agree with that behavior.  I don't think the CanExcute should be raised if the CommandParameter changes.

**Comment by opcodewriter** [comment]
I think it's getting confusing. In my last comment I wasn't talking about Prism or `ObserveProperty`.

I didn't expect you will agree that ButtonBase implementation should be changed :) I think it's been working like that for a decade or something. 
You're saying you don't agree with my suggested behavior, can I ask why?

**Comment by dvorn** [comment]
In my opinion, the real problem with those code snippets is the following:

When RaiseCanExecuteChanged is triggered by a change of view model's SelectedItem, CanExecute is invoked, but the argument provided to CanExecute by the view corresponds to the **previous value** of SelectedItem.

A workaround (already mentioned) is not to use the parameter but to use view model's SelectedItem in implementation of CanExecute.

Maybe it is possible to arrange the view differently so that CommandParameter passed to CanExecute reflected the new state of the view's SelectedItem, but it will be counterintuitive anyways.

**Comment by dvorn** [comment]
Another workaround might be the following:
```xaml
<ListView Name="LV" SelectedItem="{Binding SelectedItem, Delay=1}" ItemsSource="{Binding Items}" />
```
