### ISSUE TITLE
The name "InvokeCommandAction" does not exist in the namespace "http://prismlibrary.com/".	InteractivityQuickstart

### ISSUE THREAD

**Issue by nasheayahu** [PrismLibrary/Prism#692]
- Platform: WPF
- Prism version: 6.1

I just downloaded your latest code samples and I can't get InteractivityQuickstart to work because of the following error:

The name "InvokeCommandAction" does not exist in the namespace "http://prismlibrary.com/". InteractivityQuickstart

How do I fix this?

**Comment by dvorn** [comment]
Is automatic download of nugget packages enabled in VS?

**Comment by nasheayahu** [comment]
Yes, I recompiled it with and checked to make sure I had the latest Prism version, but still get the error message.

**Comment by dvorn** [comment]
Most likely it is a problem with System.Windows.Interactivity.dll.  It used to be included with Prism libraries, but now it is not.  Latest versions of VS include it.  But if you have previous versions of VS, try to download and install Expression Blend SDK.

**Comment by brianlagunas** [comment]
Well we know that it does exist:
https://github.com/PrismLibrary/Prism/blob/master/Source/Wpf/Prism.Wpf/Properties/AssemblyInfo.cs#L40

VS has always had issues with the interactivity stuff.  I am hoping ot ease this pain in the next Prism for WPF release next week.

**Comment by dvorn** [comment]
May be this is the same as #213
