### ISSUE TITLE
[WPF] Prism regions in templated controls do not work

### ISSUE THREAD

**Issue by dvorn** [PrismLibrary/Prism#694]
### Package info
- Platform: WPF
- Prism version: 2, 4, 5, 6

Actually this is an old well-known issue: [Region Registration Fails w/ Templated Controls](http://compositewpf.codeplex.com/workitem/3612)

The codeplex workitem above provides also a solution - a modification of RegionManagerRegistrationBehavior to account for templated controls.

While this can be achieved without modification of the Prism library by creating and registering a custom modified RegionManagerRegistrationBehavior, I suggest to include the fix into the library.

I do not expect that anybody's code may be broken by the fix.

**Comment by brianlagunas** [comment]
> I do not expect that anybody's code may be broken by the fix.

Obviously we can't rely on this :)

This is a scenario I'm not we want to support out of the box.  There should be very few scenarios when you would do this, and I have never had to do this personally.  I'll have to think about this.  This may just be a "how to" in the documentation.

**Comment by dvorn** [comment]
This is needed if you do View Model-first.

**Comment by brianlagunas** [comment]
Only if you are relying on implicit templates to represent your View which I would never recommend.  That's slow as hell and introduces a number of other development pains.

**Comment by dvorn** [comment]
> Only if you are relying on implicit templates to represent your View which I would never recommend.

But the documentation says [Navigation Using the Prism Library for WPF](https://github.com/PrismLibrary/Prism/blob/master/Documentation/WPF/60-Navigation.md)

> Note: The preceding description illustrates view-first navigation, where the URI refers to the name of the view type, as it is exported or registered with the container. With view-first navigation, the dependent view model is created as a dependency of the view. An alternative approach is to use view model–first navigation, where the navigation URI refers to the name of the view model type, as it is exported or registered with the container. View model–first navigation is useful when the view is defined as a data template, or when you want your navigation scheme to be defined independently of the views.

>  That's slow as hell 

Premature optimization, eeh?

>  introduces a number of other development pains.

It allows to run complete user scenarios with real view models in acceptance tests.

**Comment by brianlagunas** [comment]
Yeah.. the doc snippet you pasted doesn't point out anything ground breaking.  Using implicite data templates for your apps primary views is extremely slow in WPF.  I would never do this in any WPF app I build.  That's just my opinion.

> It allows to run complete user scenarios with real view models in acceptance tests
You can do this with view first or VM first.  The view approach should have no impact on testing your VMs.

**Comment by dvorn** [comment]
To summarize:

a) this change does not affect existing code and view-first scenarios.  

b) But it allows creation of regions in data templates which is useful in view model-first scenarios.  

What are the objections to that?

**Comment by brianlagunas** [comment]
> this change does not affect existing code and view-first scenarios. 

We need to verify this and cannot assume.  There are many scenarios around regions and scoped regions (View and VM first).  We also need to determine the performance impact we are introducing my complicating the logic.  This may seem like a simple change, but we must do a proper review before making this change as it touches a stable and very important aspect of the Prism code base.  This is a high risk change that I am not in a hurry to make.

**Comment by brianlagunas** [comment]
There are also a number of ways to solve this.  This is also another good approach http://southworks.com/blog/2011/11/10/regions-inside-datatemplates-in-prism-v4-using-a-region-behavior/

**Comment by brianlagunas** [comment]
This is not supported out of the box.
