### ISSUE TITLE
Feature Request: navigation with composable calls to the existing navigation views instead of strings

### ISSUE THREAD

**Issue by Emasoft** [PrismLibrary/Prism#696]
Currently in Prism we have this string based navigation system:

```C#
_navigationService.Navigate("ViewA/ViewB/ViewC/ViewD/ViewGallery", p);
```

It is cool and easy to write, but using strings is a very troublesome choice. Strings are not typed, errors are not caught at compile time, refactoring is impossible and debug is hell. We need to avoid this at all costs.

A solution would be implementing navigation with composable calls to the existing navigation views. Something similar to the LINQ syntax, that returns each time an IEnumerable and compose the query by chaining the method calls together:

```C#
_navigationService.Navigate (Navigation.Views.ViewA.ViewB.ViewC.ViewD.ViewGallery, p);
```

Or even better:

```C#
_navigationService.NavigateTo.Views.ViewA(p).ViewB(p).ViewC(p).ViewD(p).ViewGallery(p);
```

Could something like this be implemented in Prism?

**Comment by bartlannoeye** [comment]
You'll write the strings once and place them in a constants file. If you really want type checking, use typeof(ViewB).FullName or something similar, but then you'll loose the flexibility that we currently have in being able to rewrite the ViewModelLocator rules to fit _any_ implementation you want (one of my LOB applications had specific Uri's for deep linking mapped to views).

Also, your example isn't completely clear to me, you're trying to navigate to 4-5 views in a single call? Or is ViewA/ViewB/... a namespace?

I'll have to check with the rest of the team, but pretty sure this won't be implemented. However feel free to fork Prism and add it in your version.

**Comment by Emasoft** [comment]
@bartlannoeye I don't understand why you think that you'll loose the flexibility of being able to rewrite the ViewModelLocator rules. You can rewrite those rules in the same way you can rewrite Linq queries. Can you make an example of some rule that you think is going to be impossible to write?

**Comment by brianlagunas** [comment]
Thanks for the suggestion, but this is not going to happen.
