### ISSUE TITLE
Please provide signed version of Prism dlls

### ISSUE THREAD

**Issue by noufionline** [PrismLibrary/Prism#70]

**Comment by brianlagunas** [comment]
Thanks for the idea.  We will discuss it.

**Comment by cmjacobs** [comment]
any further development on this?

**Comment by llampret** [comment]
Would be great to have a signed version ye.

**Comment by Snickerboa** [comment]
This is a go or no-go issue for our use of Prism 6, we do not want to be forced to repack the nugets because we have to strong name the assemblies our selves.

**Comment by mkb137** [comment]
Agreed.

**Comment by brianlagunas** [comment]
We have started looking into this and have already found an issue.  We have some dependencies, such as StructureMap, that are not strongly named.  This means if we strongly named Prism, then we would no longer be able to use those dependencies.

**Comment by brianlagunas** [comment]
Actually seems SructureMap does have separate signed version.  We will have to check all of our other dependencies, and then find a way to create the different packages with little overhead.

**Comment by mlavigne1964** [comment]
Yes, this is a must. P5 was signed, all our projects are signed, we cannot use this if not signed. I'm so surprised and saw nothing about this breaking change in the release notes, you stopped our major update in its track because of that. Bob! Pull the backup, we're going back P5!
Strike 1 to the non-P&P team.

**Comment by brianlagunas** [comment]
We have a PR #178 in which we are testing signing Prism.  I am not 100% confident in our dependencies (Autofac, Unity, etc.) sinced I'm not sure they are signed or not.
