### ISSUE TITLE
NavigationService.NavigateAsync("MainPage") pushes page modally

### ISSUE THREAD

**Issue by adrianknight89** [PrismLibrary/Prism#700]
Hi Brian,

Thanks for putting up a presentation on Prism with Xamarin Forms. I just watched your video (https://www.youtube.com/watch?v=DYRLcqG2BAY&t=0s) and coded along the way.  I have Prism.Core 6.2.0-pre1, Prism.Forms 6.1.0-pre7, and Prism.Unity.Forms 6.2.0-pre7.  I followed the first project (MainPage, ViewA, and ViewB). The issue I'm having is all pages seem to be pushed modally. I don't see the navigation bar and page animations are that of modal pages. 

```
  protected override void OnInitialized()
  {
        NavigationService.NavigateAsync("MainPage");
  }
```

This seems to be pushing `MainPage` modally by default. I manually tried setting `useModalNavigation` to false, but it didn't work. Can you tell me what I'm doing wrong?

P.S. I'd love to see the source code for that presentation.

**Comment by brianlagunas** [comment]
You need to wrap your pages in a NavigationPage in order to get a navigation bar

**Comment by StefanOssendorf** [comment]
So this is the correct approach?
``` 
if(Device.OS == TargetPlatform.Android) {
    MainPage = new NavigationPage(new MainPage());
} else {
    NavigationService.NavigateAsync("MainPage");
}
```

**Comment by adrianknight89** [comment]
No. I figured it out. Make sure your first page is a NavigationPage. Have a look at MyNavigationPage here: https://github.com/PrismLibrary/Prism/tree/master/Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld/Views

In App.cs, you do `NavigationService.NavigateAsync("MyNavigationPage/FirstView")`

So you need to create MyNavigationPage and FirstView in order just to navigate to FirstView.

**Comment by StefanOssendorf** [comment]
Ah okay. Thank you very much :smiley:

**Comment by adrianknight89** [comment]
Welcome. :)

**Comment by StefanOssendorf** [comment]
@adrianknight89  Any way to get in touch with you? (Twitter, Mail or something else?)
