### ISSUE TITLE
NavigationAsync

### ISSUE THREAD

**Issue by los3rz** [PrismLibrary/Prism#701]
I have an issue with navigationAsync whereby after passing a parameter to the next view model, the view model will render the UI first then process the parameters in OnNavigateTo. In the OnNavigateTo, I will update my label with the binded title like so. 

```
public void OnNavigatedTo (NavigationParameters parameters) {
     if (parameters.ContainsKey ("id"))
        Title = (string)parameters ["id"];
} 
```

The problem here is that the label text change animation on viewB can be seen which I dont want it to happen.

**Comment by brianlagunas** [comment]
That's not possible.  The View and VM are created first, then navigated to which will then give you access to the parameters.  You cannot navigate to something that doesn't exist.

**Comment by los3rz** [comment]
So this means that it's not possible to load the state from the previous view model before the UI renders? If that's the case, then I would have to write my own transition animation and set the NavigateAsync animated parameter to false.

This is weird because on your Xamarin Evolve demo, when you're using Navigate instead of NavigateAsync, I can see that the label's text updates first before the UI renders.

**Comment by brianlagunas** [comment]
There is no Navigate anymore.  Essentially, you would have to prevent the view from rendering until your VM has been navigate to, which isn't something you can do off the top of my head.  My sample is so simple in the video, its possible it just happens so quickly you don't notice it.  You can't update a UI element from a binding unless the view has been created and initialized.

**Comment by los3rz** [comment]
The only way I could think of is to do a code behind navigation to its view
perhaps. Which would essentially break the true mvvm model. I remember
there's one mvvm video where u mention I wouldn't go to jail if I break the
pattern. Thanks!
