### ISSUE TITLE
[XF] InsertPageBefore and RemovePage methods

### ISSUE THREAD

**Issue by adrianknight89** [PrismLibrary/Prism#705]
Currently, the navigation service lacks these two methods. I need the ability to insert and remove pages on the navigation stack without actually pushing and popping them. Can these be added to INavigationService?

**Comment by dansiegel** [comment]
I would say that those would be a great add as would adding ```PopToRootAsync```. The biggest issue is that you need a way to determine what the name of a page is. I mean it's easy for apps following the convention. But if you use a custom name or use different Views depending on OS or Idiom all of that breaks. 

I think perhaps we could attach a BindableProperty to the pages as we create them and set it with the name that we used to resolve the page.

**Comment by brianlagunas** [comment]
I am hesitant to add these types of methods.  Besides being vey complex to implement, especially when you have multiple instances of the same view in your history, they add too much knowledge of the platform nav specifics and goes against the current goal of Prism navigation into a ViewModel.

I would need a lot of convincing before I even consider adding these methods.  For now, if you want to manipulate the navigation stack directly, I would recommend using code-behind for that.

**Comment by MaxFe** [comment]
I don't really undestand why Xamarin.Forms impl. the method "InsertPageBefore" but it's too complicated for Prism? Why can't their approach be used for Prism?   
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/navigation/hierarchical#manipulating-the-navigation-stack
