### ISSUE TITLE
`ConfigureModuleCatalog` executes before App constructor

### ISSUE THREAD

**Issue by toadzky** [PrismLibrary/Prism#707]
I think this is a problem for only Xamarin Forms. I have services that are defined as interfaces in my core project and implemented in my Android and iOS projects. I need to register the implementations based on the platform, so I created an `IModule` in each project to register all the types.

I want to be able to pass the module to the Application that gets instantiated in the AppDelegate/MainActivity class. Unfortunately, the parent constructor in `PrismApplication` executes, which creates the container, configures the module catalog, etc before my application constructor is run. My workaround is a static property I set before I create my Application. 

I'm not sure if something in the XF lifecycle prevents this or if there is another reason for doing everything in the parent constructor.

**Comment by joacar** [comment]
In version 6.2 the interface `IPlatformInitializer`Is added to address this issue. Pass an instance to Prism Application and IT Will call registertypes with the choser container

**Comment by toadzky** [comment]
@joacar awesome! thanks for letting me know.
