### ISSUE TITLE
[XF] System.TypeLoadException: Could not load type 'Prism.Unity.IPlatformInitializer' 

### ISSUE THREAD

**Issue by troyvnit** [PrismLibrary/Prism#708]
Hi guys, 
I just got an issue after upgrade to pre7. Please take a look the details below:

### Package info

- Platform: Android
- Prism version: "Prism.Core" version="6.2.0-pre1", "Prism.Forms" version="6.1.0-pre7", "Prism.Unity.Forms" version="6.2.0-pre7"
- Xamarin version (if applicable): "Xamarin.Forms" version="2.3.2.118-pre1"

### Repro steps

Upgrade Prism and Xamarin packages to above Package Info. 
Run Android project. 
Deploy successfully.
Got error message: 

> System.TypeLoadException: Could not load type 'Prism.Unity.IPlatformInitializer' from assembly 'Prism.Unity.Forms, Version=6.2.0.0, Culture=neutral, PublicKeyToken=null'.

 at `LoadApplication(new App());`

**Comment by troyvnit** [comment]
Sorry for my mistake. I just fixed this issue. So, I close it. Thanks!

**Comment by terudon** [comment]
Can you elaborate on how you fixed the issue?
