### ISSUE TITLE
Getting suspending error when click on DelegateCommand method on xamarin.forms

### ISSUE THREAD

**Issue by ShahriatHossain** [PrismLibrary/Prism#710]
*Use GitHub issues for __bugs in Prism and feature requests only__. If you have a question how to implement something using Prism or a bug in your app that might be related to Prism, please post your question on [StackOverflow](http://stackoverflow.com/tags/prism) (which we monitor as well).*

Please provide as much detail as possible (and feel free to remove unused properties):

### Package info

- Platform: Visual Studio 2015
- Prism version: 6.1.0
- Xamarin version (if applicable): 2.0
- Windows 10 SDK version (if applicable):
- Other version info:

### Repro steps

Please describe the issue/request in detail.

Hi,
I have prism view model page and content page related to it. Here is the xaml code

     <StackLayout VerticalOptions="Center" HorizontalOptions="Center">
         <Entry Text="{Binding Email}" Keyboard="Email" Placeholder="Email ID" Style="{StaticResource entryStyleBlack}" />
         <Entry Text="{Binding CountryCode}" Keyboard="Numeric" Placeholder="880" Style="{StaticResource entryStyleBlack}" />
         <Entry Text="{Binding MobileNo}" Keyboard="Numeric" Placeholder="1923508304" Style="{StaticResource entryStyleBlack}" />
         <Button Command="{Binding SaveCommand}" Text="Update" Style="{StaticResource buttonStyleRed}"/>
       </StackLayout>

 I am calling the deletegate like below:

 SaveCommand = new DelegateCommand(Save);

and the save method:

private async void Save(){}

and I am getting the error like:

08-08 11:05:33.997 F/ ( 3654): suspend_thread suspend took 201 ms, which is more than the allowed 200 ms
0x0 - starting (GOOD, unless the thread is running managed code)
0x1 - running (BAD, unless it's the gc thread)
0x2 - detached (GOOD, unless the thread is running managed code)
0x?03 - async suspended (GOOD)
0x?04 - self suspended (GOOD)
0x?05 - async suspend requested (BAD)
0x?06 - self suspend requested (BAD)
0x*07 - blocking (GOOD)
0x?08 - blocking with pending suspend (GOOD)
--thread 0xdac0d080 id 0xd93ff930 [0xe6c] state 1
--thread 0xeebe8200 id 0xd961e930 [0xe6b] state 1
--thread 0xdac0db00 id 0xd963f930 [0xe6a] state 1
--thread 0xeebe7600 id 0xd993f930 [0xe69] state 1
--thread 0xeebe7000 id 0xdc0fa930 [0xe60] state 1
--thread 0xf3fa6a80 id 0xdc1fb930 [0xe5f] state 105
--thread 0xf3fa6780 id 0xf76fbc00 [0xe46] state 1 GC INITIATOR
WAITING for 1 threads, got 0 suspended

Can you help me how to sort this out?

**Comment by brianlagunas** [comment]
Looks like your save code is taking to long to run.  Make sure you are running that on a separate thread to keep the app responsive.
