### ISSUE TITLE
[XF] Should the Project Templates change the directory tree?

### ISSUE THREAD

**Issue by dansiegel** [PrismLibrary/Prism#717]
Since the templates are being redone now seems like a great time to get feedback on how the community would like the base project setup. The current Directory Tree looks something like:
```
-- {Your Solution}
-- {Your Solution}.Droid
-- {Your Solution}.iOS
-- {Your Solution}.WinPhone
-- {Your Solution}.Windows
-- {Your Solution}.UWP
```

This could be updated to:
```
-- src
  -- Core
    -- {Your Solution} ?? {Your Solution}.Core
# The following could also be wrapped in a Platforms folder
  -- Droid
    -- {Your Solution}.Droid
  -- iOS
    -- {Your Solution}.iOS
# and so on...
-- tests
  -- {Your Solutions}.Tests
```

**Comment by joacar** [comment]
I agree with the src and tests folder. Usually I put all projects in the src folder.

````
-- src
  -- {Your Solution}
  -- {Your Solution}.Droid
  -- ....
````

I haven't (yet) come across the time where I've need another level.

**Comment by dansiegel** [comment]
I don't always find the need, but if you start dealing with app extensions and wearables it quickly becomes nice to collapse things down by platform.

**Comment by brianlagunas** [comment]
I do not want to complicate the structure of the project templates.  It is easy enough to rearrange projects in a solution to meet the developers desired layout.
