### ISSUE TITLE
InvokeCommandAction should not automatically set IsEnabled on associated control

### ISSUE THREAD

**Issue by JRRiley2001** [PrismLibrary/Prism#72]
The prism InvokeCommandAction added support for the CanExecute method of ICommand, so that it disables the associated control if the CanExecute returns false. That was great, however this behaviour is also used as the general mechanism by which Command actions are invoked from events. Whilst it makes sense to disable the control when connecting a command to, say, a button click event, there are many other examples where it doesn't make sense. 

For example, lets say I have a button that invokes an Edit command for a selected item in a data grid. The button will correctly (and automatically) enable and disable depending on my selection(s) in the datagrid.  If I then decide that I want that same command to execute when the user double clicks an item in the datagrid, in principle it should be straightforward; I just wire up the existing command to the datagrid MouseDoubleClick event:

        <DataGrid SelectedItem="{Binding SelectedItem}" ItemsSource="{Binding Path=DataItems}">
            <i:Interaction.Triggers>
                <i:EventTrigger EventName="MouseDoubleClick">
                    <prism:InvokeCommandAction Command="{Binding EditCommand}" />
                </i:EventTrigger>
            </i:Interaction.Triggers>
        </DataGrid>

The ViewModel executes simple code to ensure there is a valid SelectedItem.

        private bool CanExecuteEditCommand()
        {
            return (SelectedItem != null);
        }

And the setter for SelectedItem will cause the command to re-evaluate:

            set 
            {
                SetProperty(ref _selectedItem, value);
                EditCommand.RaiseCanExecuteChanged();
            }

However, if the user deselects all items in the datagrid, when the Command is re-evaluated, it determines that the command cannot execute, and will set IsEnabled on the TargetObject to false; for the button that is good, but for the DataGrid it isn't, the result is the datagrid itself becomes disabled!

ok, this is just one example, but I consistently have other similar situations and this clearly isn't right. Obviously I can see why having the IsEnabled property automatically updated make sense in some circumstances, but not all.

**Comment by brianlagunas** [comment]
Thanks for bringing this issue to our attention.  We will look at how we can improve this.  Maybe we can add a property called something like AllowDisable that you can use to turn this off for these scenarios.

**Comment by JRRiley2001** [comment]
Thanks Brian, yes that is exactly what I did locally, I added an "AutoEnable" dependency property (defaulting to true to maintain backwards compatibility) which is passed through to the CommandBehaviorBase class and checked in the UpdateEnabledState method.

**Comment by brianlagunas** [comment]
Great!  I haven't looked at the code yet, but could the AutoEnable property just be defined in the CommandBehaviorBase class instead of being passed to it?

**Comment by JRRiley2001** [comment]
Yes, that's just perhaps poor wording on my behalf. When I said "passed in", it wasn't through a method call, it was a property setter.

**Comment by brianlagunas** [comment]
This has been implemented
