### ISSUE TITLE
How to input validation in prism and xamarin forms?

### ISSUE THREAD

**Issue by ShahriatHossain** [PrismLibrary/Prism#722]
*Use GitHub issues for __bugs in Prism and feature requests only__. If you have a question how to implement something using Prism or a bug in your app that might be related to Prism, please post your question on [StackOverflow](http://stackoverflow.com/tags/prism) (which we monitor as well).*

Please provide as much detail as possible (and feel free to remove unused properties):

### Package info

- Platform:
- Prism version:
- Xamarin version (if applicable):
- Windows 10 SDK version (if applicable):
- Other version info:

### Repro steps

Please describe the issue/request in detail.

I am developing an app using xamarin.forms and prism, I need to validate some input data like email, mobile number, country code, otp code as a standard international validation. But I can't find any tutorial for it. Can anybody help me to find out a solution?

**Comment by joacar** [comment]
Hi,

There is the `ErrorsContainer` but currently that is only for WPF. I would use a behavior for this scenarios.

````c#

public class EmailValidationBehavior : Behavior<Entry>
{

tatic readonly BindablePropertyKey IsInvalidPropertyKey = BindableProperty.CreateReadOnly(nameof(IsInvalid), typeof(bool), typeof(EmailValidationBehavior ), false);
 
    public static readonly BindableProperty IsInvalidProperty = IsInvalidPropertyKey.BindableProperty;

public override void OnAttachedTo(Entry entry) 
{
 entry.TextChanged += OnTextChanged;
}

public override void OnDetachingFrom(Entry entry)
{
// Unsubscribe to prevent memory leaks
 entry.TextChanged -= OnTextChanged;
}

public void OnTextChanged(object sender, TextChangedEventArgs e)
{
    // Validate the email here using e.g. regular expression
   // sender is Entry so here you can apply a style in case it is invalid
}

}
````

And here is how you can use it
````c#
...
<Entry>
<Entry.Behaviors>
    <b:EmailValidationBehavior x:Name="emailValidator" />
</Entry.Behavoirs>
</Entry>
<Label Text="Email is invalid" Visible="{Binding Source={x:Reference emailValidator}, Path=IsInvalid}" />
````

Further this kind of questions should belong in Stackoverflow and tag them with Prism

**Comment by ShahriatHossain** [comment]
Hi, Thank you very much for your such a valuable response. I have tried to integrate your code on portable project but it is getting error like below:


08-11 18:22:54.668 E/mono    ( 5517): Unhandled Exception:
08-11 18:22:54.668 E/mono    ( 5517): System.NullReferenceException: Object reference not set to an instance of an object.
08-11 18:22:54.668 E/mono    ( 5517):   at (wrapper dynamic-method) System.Object:43344384-2b0a-48b6-91a1-2feb0c0ba139 (intptr,intptr,bool,int,int,int,int)
08-11 18:22:54.668 E/mono    ( 5517):   at (wrapper native-to-managed) System.Object:43344384-2b0a-48b6-91a1-2feb0c0ba139 (intptr,intptr,int,int,int,int,int)
08-11 18:22:54.668 E/mono-rt ( 5517): [ERROR] FATAL UNHANDLED EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object.
08-11 18:22:54.668 E/mono-rt ( 5517):   at (wrapper dynamic-method) System.Object:43344384-2b0a-48b6-91a1-2feb0c0ba139 (intptr,intptr,bool,int,int,int,int)
08-11 18:22:54.668 E/mono-rt ( 5517):   at (wrapper native-to-managed) System.Object:43344384-2b0a-48b6-91a1-2feb0c0ba139 (intptr,intptr,int,int,int,int,int)

**Comment by joacar** [comment]
Check this [source](https://blog.xamarin.com/behaviors-in-xamarin-forms/) as it is more complete

**Comment by ShahriatHossain** [comment]
Yes I have also implemented that blog but getting the same error but if I remove that xaml code from prism content page then error is not generating. So something configuration problem not sure though?

**Comment by joacar** [comment]
If you can create a stripped down project that reproduce your issue I can take a look. That strack trace doesn't make any sense to me. Are you using the latest 6.2?
