### ISSUE TITLE
[XF] Prism.Unity 6.2.0 does not target PCL Profile111?

### ISSUE THREAD

**Issue by tomcrusader** [PrismLibrary/Prism#723]
### Package info

- Platform: PCL
- Prism version: 6.2.0

### Repro steps

Create a XF PCL Project targetting Win 8.1 / iOS / Droid = PCL Profile 111.
Try to install Prism.Unity 6.2.0

### Actual Result ###
Fails with

> Could not install package 'Prism.Unity 6.2.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

Have this profile been removed? I'm OK with dropping 8.1 but it's a bit of work to re-target all PCLs.

**Comment by bartlannoeye** [comment]
For Xamarin Forms you should use [Prism.Unity.Forms](https://www.nuget.org/packages/Prism.Unity.Forms/) instead
