### ISSUE TITLE
[XF] NavigationService does not push pages on top of the stack when used within navigationpage

### ISSUE THREAD

**Issue by StefanOssendorf** [PrismLibrary/Prism#726]
Expected Behavior: NavPage/MainPage -> (VewModel-Command) -> SecondPage
Back functionality of NavPage should be usable, but SecondPage is set as RootPage not on top as NavPage/MainPage/SecondPage

The INavigationService does not push a contentpage on the stack when used from navigation page viewmodel ([Navigation from Navigationpage ViewModel](https://github.com/StefanOssendorf/XF.Prism.NavigationStackProblem/blob/master/XFPrismNavigationStackProblem/XFPrismNavigationStackProblem/ViewModels/NavPageViewModel.cs)). Inseadt the XF Navigation works as expected ([Navigation via click event and XF navigation](https://github.com/StefanOssendorf/XF.Prism.NavigationStackProblem/blob/master/XFPrismNavigationStackProblem/XFPrismNavigationStackProblem/Views/NavPage.xaml.cs)).

### Package info

- Platform: android / wp 
- Prism version: 6.2.0

### Repro steps
Repository with a [Sample Solution](https://github.com/StefanOssendorf/XF.Prism.NavigationStackProblem)

I hope I've provided any necessary information. if something is missing, just say it :smile:

**Comment by brianlagunas** [comment]
You can use the `INavigationPageOptions.ClearNavigationStackOnNavigation` to control how the NavigationPage pushes pages.  Implement this on the View or ViewModel.

**Comment by StefanOssendorf** [comment]
Works like a charm :) Tried `INavigationPageOptions` on "SecondPage" not the "NavPage".

Thanks!

**Comment by Willjobs94** [comment]
I want to do this, but I don't get it, how and where do I need to implement `INavigationPageOptions` ?

**Comment by brianlagunas** [comment]
You need your NavigationPage to implement this interface.
