### ISSUE TITLE
[XF] BindableBase vs Fody PropertyChanged

### ISSUE THREAD

**Issue by adrianknight89** [PrismLibrary/Prism#727]
Can you please tell me if it's safe to use BindableBase with Fody PropertyChanged (https://github.com/Fody/PropertyChanged)?

If I use Fody, should my ViewModel still derive from BindableBase? Is it safe to mix the two or should I stick to one?

**Comment by brianlagunas** [comment]
You don't need BindableBase if you are using Fody

**Comment by adrianknight89** [comment]
Thanks. That was quick. :)
