### ISSUE TITLE
BindableValidator vs ErrorsContainer

### ISSUE THREAD

**Issue by xied75** [PrismLibrary/Prism#728]
Dear all,

Currently we have:
Prism/Source/Prism/Mvvm/ErrorsContainer.cs
Prism/Source/Windows10/Prism.Windows/Validation/BindableValidator.cs

For a UWP I'm developing, I'm using the BindableValidator, and now I got confused:
This BindableValidator has a property "Errors", it does the validation and save all errors and do the notification. For my ViewModel properties, this works great to validate them. But what about errors that is not of validation? e.g. Runtime?

Say I have a textbox for URL input, I can put a validation rule on that, to check with regex, which is fine, but it only makes sure the pattern is correct, not the URL actually pointing to a live server; so later in the code, my httpclient makes connection to it, then it could be 404, 500, No Network, etc. And I would like to tell the user these "Errors", but I have no way to set the Errors within BindableValidator.

Then I saw the ErrorsContainer, I think it is correct to actually have this, it is better named "BindableErrors" in my mind. So I thought the BindableValidator probably should be separated into two parts: BindableErrors + Validator, and the Validator has access to set validation errors, but the BindableErrors would be public for me to set Runtime errors, so that my ViewModel can use a single Error setup for both kinds of errors.

I might have flaws in my thinking, anyone can shine some light regarding above? Thanks a lot!

**Comment by dvorn** [comment]
This seems to be a work in progress.  See #45

**Comment by xied75** [comment]
Thanks @dvorn I had a read on that issue, it seems very old and closed, so still a WIP?

**Comment by brianlagunas** [comment]
This is not something we are looking at anytime soon.  @briannoyes has a design in mind that we will get to one day. Closing this for now.

**Comment by xied75** [comment]
@brianlagunas understood. But is my thinking in the correct direction?

@briannoyes my world, you used to fly the Tomcat, got any photos with it? :)
