### ISSUE TITLE
How about adding ReadParameter Extention Method in Prism

### ISSUE THREAD

**Issue by noufionline** [PrismLibrary/Prism#729]
`        public static bool HasParameter(this NavigationContext item, string key) => item.Parameters.Any(i => i.Key == key);`
`

        public static T ReadParameter<T>(this NavigationContext item, string key)
        {
           
            if (!item.HasParameter(key)) return default(T);

            if(typeof(T).IsValueType)
                return (T)Convert.ChangeType(item.Parameters[key], typeof(T));
            return (T)item.Parameters[key];
        }`

**Comment by dvorn** [comment]
Extension methods of this kind can be easily added by a developer to his project.  IMHO, those particular extensions do not look universal enough to be included into the library:

Not everybody wants to have the default value for type when the parameter is missing; some will want to throw.

From performance point of view, this includes double scanning of the parameter list plus the LINQ overhead.   And if somebody writes `if (HasParameter) ReadParameter`, then three times scanning and twice the LINQ.

Also, not everybody will be happy with unconditional type conversion.  Some may prefer strict type checking.

**Comment by noufionline** [comment]
Sounds Logical to me. Thanks dvorn.
To avoid lines of code required every time when we read parameter value from parameter collection can you suggest a better way?

It will be really helpful!

**Comment by dvorn** [comment]
@noufionline It depends on what you need for your application.  If your extensions is what you need, just use them.
