### ISSUE TITLE
Decision on samples / dog fooding NuGet packages

### ISSUE THREAD

**Issue by bartlannoeye** [PrismLibrary/Prism#73]
How do we plan to go forward on providing samples for Prism? Do we create a new repository for every platform (XF, WPF, UWP) like @brianlagunas already die for XF? Or do we continue to post them in the samples folder on this repository. I see pros and cons for both scenarios with the major ones being:
- separate samples from framework source (split)
- keep issues in one single repository (don't split)

Related to this is the idea of dog fooding our own NuGet packages. While changing one of the existing samples, I noticed it had references to the debug output of Prism (and of course I was building Prism in release mode), which increases the chance of missing out on bugs.
One possible solution is to use MyGet to host our early pre-release packages that are also used in the samples for testing purposes before pushing it to NuGet.
The question there is how do we deal with local development and testing those changes (being a distributed team where everybody can pitch in). Unit tests are good, but being able to test a new feature in a real app is better.

**Comment by brianlagunas** [comment]
Well, we kind of have two scenarios.  We need samples to show off a feature or specific approach to a problem, and other samples that we use to actually test the functionality during development.  @briannoyes and I have discussed this briefly regarding if all the samples should just add the Prism projects in their solution to help enabled learning/debugging, or if the samples should just use the NuGet packages instead to keep the sample solution clean and focused as well as test the NuGet distribution.

I don't think we have come up with an answer yet, but this is definitely something we need to figure out before we start porting existing samples or creating new ones..

**Comment by brianlagunas** [comment]
We have decided that any sample that we create under the Prism-Samples-[Platform] repos will rely on the NuGet packages.  We will create new reference implementation apps that will be linked to the source code under the Prism repo at a later time.
