### ISSUE TITLE
InvalidOperationException thrown when upgrading to version 6.2

### ISSUE THREAD

**Issue by hpcsc** [PrismLibrary/Prism#730]
### Package info

- OS: Windows 10 Pro
- Platform: WPF
- Prism version: 6.2
- Previous Prism version: 6.1

### Description

In a view model we have following property:
```
private string _contact;
public string Contact
{
    get { return _contact; }
    set
    {
        _contact = value;
        OnPropertyChanged(() => Contact);
        VideoCallCommand?.RaiseCanExecuteChanged();
    }
}
```

`VideoCallCommand` is created in view model constructor as follow:

```
VideoCallCommand = new DelegateCommand(VideoCall, 
                            () => !string.IsNullOrWhiteSpace(Contact));
```

With version 6.1, eveything's working fine. Right after we upgrade it to version 6.2, the application throws the following exception when user's typing into the textbox that binded to Contact property in the UI (the exception is at the line `VideoCallCommand?.RaiseCanExecuteChanged();`)

```
System.InvalidOperationException was unhandled
Message: An unhandled exception of type 'System.InvalidOperationException' occurred in WindowsBase.dll
Additional information: The calling thread cannot access this object because a different thread owns it.
```

**Comment by dvorn** [comment]
This is a known issue.  They removed synchronization context from the DelegateCommand.  Now RaiseCanExecuteChanged should be invoked on the GUI thread.

**Comment by dvorn** [comment]
@brianlagunas This change creates a lot of pain for many developers.  If I understand correctly, WeakEventManager with its SynchronizationContext was removed because Xamarin was too aggressive, and SynchronizationContext was removed from DelegateCommand because in UWP there is no single context.  But all this has nothing to do with WPF.  Maybe we can have sync context back for WPF only?

**Comment by dvorn** [comment]
I'm sorry, I was wrong.  Sync context is in DelegateCommand.  But the behavior changed as compared to sync context in WeakEventManager.  Now sync context is captured in the constructor of the DelegateCommand, which typically means in the contractor of the view model.  Make sure the view model is created on the UI thread.

**Comment by brianlagunas** [comment]
Was your VM created on a separate thread?  I'm not sure why this would happen, and even then I don't know why this would work in 6.1 and not 6.2.  The only change made was to use the SyncContext in 6.2 so that you could raise CanExecute on a separate thread.  Can you provide a simple sample that can reproduce it?

**Comment by hpcsc** [comment]
It seems like something specifically in my current project that causes this issue with upgrading to 6.2. I cannot replicate it when creating a new project.
But it's obvious that it's the issue when upgrading Prism to 6.2 because when I downgrade it to 6.1, everything's working again.
For the view model, I setup AutofacBootstrapper to inject it into view code behind and code behind sets it to data context. I don't see anything really suspicious about that. Doing the same in a new project doesn't have any issue
I'm still trying to narrow down the issue, will update again when I have some progress

**Comment by dvorn** [comment]
@hpcsc You may try setting a breakpoint in the view model constructor and see on what thread it is executed.

**Comment by dvorn** [comment]
@hpcsc Also you may add the following lines to your constructor to examine the current sync context:
```csharp
SynchronizationContext context = SynchronizationContext.Current;
Type contextType = context.GetType();
```
The type should be DispatcherSynchronizationContext.
