### ISSUE TITLE
[XF] Async Friendly NavigationAware

### ISSUE THREAD

**Issue by dansiegel** [PrismLibrary/Prism#734]
Since ```async void``` can lead to a number of issues as it becomes fire and forget. Perhaps we should add a more Async friendly version of INavigationAware something like:

```cs
public interface INavigationAwareAsync
{
     Task OnNavigatedToAsync( NavigationParameters parameters );
     Task OnNavigatedFromAsync( NavigationParameters parameters );
}
```

**Comment by dvorn** [comment]
@dansiegel Cf. #704

**Comment by brianlagunas** [comment]
As @dvorn pointed out, this is probably something that should remain as-is.
