### ISSUE TITLE
Please add a helper method to Add Modules to ModuleCatelog

### ISSUE THREAD

**Issue by noufionline** [PrismLibrary/Prism#736]
Adding a Module to a catalog always requires to have additional coding which can be wrapped easily in a helper method like this.

`public void AddModule<TEntity>() where TEntity : class, IModule
        {
            var type = typeof (TEntity);
            ModuleCatalog.AddModule(new ModuleInfo
            {
                ModuleName = type.Name,
                ModuleType = type.AssemblyQualifiedName,
            });
        }
`

Please advice.

**Comment by dvorn** [comment]
You can use `ModuleCatalog.AddModule(typeof(MyModule));`

**Comment by noufionline** [comment]
I searched for this overload. But could not find. I can find only one overload which accepts ModuleInfo as a parameter. Am I missing something?

**Comment by dvorn** [comment]
https://github.com/PrismLibrary/Prism/blob/master/Source/Wpf/Prism.Wpf/Modularity/ModuleCatalog.cs#L239

**Comment by noufionline** [comment]
Hi dvorn,

Thanks so much.

But unfortunately I am not able to find it in prism 6.2 from Nuget.

Quite strange

**Comment by dvorn** [comment]
@noufionline WPF or Xamarin?

**Comment by brianlagunas** [comment]
The modularity is not fully baked.  I have more design work there before I can call it complete.
