### ISSUE TITLE
Prism Autofac Forms Error

### ISSUE THREAD

**Issue by muhammetsahin** [PrismLibrary/Prism#742]
Hi,

I use prism autofac forms but i've got an error below:

![image](https://cloud.githubusercontent.com/assets/2045788/17907237/a4b65296-6983-11e6-9064-d1ea786b2049.png)

Exception:

Application windows are expected to have a root view controller at the end of application launch

### Package info

- Platform: Xamarin Studio
- Prism version: 6.2.0
- Xamarin version (if applicable): 2.3.1.114

`using Prism.Autofac;
using Prism.Autofac.Forms;
using PrismSample.Views;

namespace PrismSample
{
	public partial class App : PrismApplication
	{
		public App(IPlatformInitializer initializer = null) : base(initializer) { }

		//public static IContainer Container;

		protected override void OnInitialized()
		{
			InitializeComponent();

			//Bootstrapper.Run();

			NavigationService.NavigateAsync("MainPage?title=Hello%20from%20Xamarin.Forms");
		}

		protected override void RegisterTypes()
		{

			//if (Container != null)
			//	return;

			//var builder = new ContainerBuilder();
			//builder.Register<IApp>(c => Application.Current as App).SingleInstance();

			//Register Services
			//builder.RegisterInstance(new CheckBatteryService()).As<ICheckBatteryService>().SingleInstance();

			//Container = builder.Build();

			Container.RegisterTypeForNavigation<MainPage>();
		}
	}
}
`

Can anybody help me?

**Comment by muhammetsahin** [comment]
I solved by myself.

I forgot register viewmodel

I added this code and work well:

`	var builder = new ContainerBuilder();

			builder.RegisterType<MainPageViewModel>();

			builder.Update(Container);`

**Comment by JeffB1** [comment]
@brianlagunas why does the Autofac container need to register the view model type but the Unity one does not? I've spent ages stuffing around with this. I was not registering the type as @muhammetsahin  did above. Didn't even think to do that. I removed the Autofac Prism libraries and used Unity Prism instead and my app started to work.

I'd like to use Autofac for familiarity reasons (from other projects) but having to register the VM types each time isn't as nice as using Unity and not needing to register the types.

**Comment by bartlannoeye** [comment]
The difference between Unity and Autofac is that Unity automatically tries to resolve types (even if not registered) and Autofac does not.

Autofac solves this by using
            // Make sure any not specifically registered concrete type can resolve.
            builder.RegisterSource(new AnyConcreteTypeNotAlreadyRegisteredSource());

See [the Windows 10 implementation]( https://github.com/PrismLibrary/Prism/blob/master/Source/Windows10/Prism.Autofac.Windows/PrismAutofacApplication.cs#L125). Looks like this wasn't done in XF.

**Comment by JeffB1** [comment]
Thanks @bartlannoeye , I will give that a go.

**Comment by bartlannoeye** [comment]
Good to hear, this will be done by Prism itself in the next release.
