### ISSUE TITLE
[XF] Setting ControlTemplate in code-behind gets rid of viewmodel

### ISSUE THREAD

**Issue by adrianknight89** [PrismLibrary/Prism#743]
I have a control template defined in App.xaml, but when I use it in a content page's XAML, the template is not rendered immediately especially on iOS (probably not with my repro down below but with my more complex actual template). The workaround seems to be setting it in code-behind.

Here's page content:

```
<ContentView x:Name="ContentView" ControlTemplate="{StaticResource Header}">
    <ListView ItemsSource="{Binding Items}"/>
</ContentView>
```

I removed `ControlTemplate="{StaticResource Header}"` and tried setting it in code-behind like so:

`ContentView.ControlTemplate = (ControlTemplate)App.Current.Resources["Header"];`

As I said, this works fine but listview data is gone. Please see repro.

https://drive.google.com/file/d/0BySiZTUVa9HPaWwzZUFRZGF2LUE/view?usp=sharing

I'm not sure if this is intended behavior or XF/Prism bug. What's the right way to set the control template in code-behind?

**Comment by dansiegel** [comment]
@adrianknight89 I'll try to take a look later but this shouldn't be a thing. I have a Prism app using Control Templates and they don't interfere with my ViewModels at all.

**Comment by adrianknight89** [comment]
@dansiegel OK. Remove control template from XAML markup and uncomment code behind in Page2. Let me know if listview data is rendered or not.

**Comment by brianlagunas** [comment]
Closing this as this is not a Prism issue.

**Comment by adrianknight89** [comment]
Filed a Xamarin bug report here: https://bugzilla.xamarin.com/show_bug.cgi?id=43706

**Comment by brianlagunas** [comment]
Thanks for the update.
