### ISSUE TITLE
How can i get navigation history from NavigationService?

### ISSUE THREAD

**Issue by boodoolak** [PrismLibrary/Prism#750]
I already asked this question on SO (https://github.com/Windows-XAML/Template10/issues/1197#issuecomment-243217347) but did not understand the answer. As in AppShellViewModel can I get a history of navigation? What should I embed in VM constructor or some other way? I need somehow to subscribe to the Navigated event, but where?

**Comment by brianlagunas** [comment]
I'm sorry, but this GitHub project is targeted for the Prism Library.  For Template 10 question or regular UWP platform questions you stick with SO, or other forums.

**Comment by boodoolak** [comment]
Oh, i'm post wrong link :-(
My app write with Prism and my original question here http://stackoverflow.com/questions/39139336/how-to-implement-the-bread-crumbs-in-the-uwp-application?noredirect=1#comment65638098_39139336
I'm sorry, please help me.

**Comment by brianlagunas** [comment]
I'm sorry, but please continue to use StackOverflow for questions like this and keep GitHub for Prism issues (bugs) and feature requests.
