### ISSUE TITLE
Unity multiple instances 

### ISSUE THREAD

**Issue by JamesPetras** [PrismLibrary/Prism#752]
Hi Guys,

not sure is this issue 100% related to Prism or to Microsoft Unity but I came across a very strange issue. 

My Service methods have been instanced in every single ViewModel instead to be a singleton.

On the following link you can find an example : [https://www.dropbox.com/s/yofe9wzqekz6y6m/Prism-master%202.zip?dl=0](url)

It is HelloWorld project with added ITestService interface and TestService class.

The interface is registered 

```
protected override void RegisterTypes()
		{

			Container.RegisterTypeForNavigation<MainPage, SomeOtherViewModel>(); //override viewmodel convention
			Container.RegisterTypeForNavigation<MyNavigationPage>();
			Container.RegisterTypeForNavigation<MyMasterDetail>();
			Container.RegisterType<ITestService, TestService>();
		}
```

and Injected to 

```
public MyMasterDetailViewModel(INavigationService navigationService, ITestService testService)
		{
			_navigationService = navigationService;
			NavigateCommand = new DelegateCommand<string>(Navigate);
			_testService = testService;
```

and 
```
	public SomeOtherViewModel(IPageDialogService dialogService, ITestService testService)
		{
			_dialogService = dialogService;
			LoadModuleACommand = new DelegateCommand(ShowDialog);
			_testService = testService;
```

If you put a breakpoint in TestService Constructor 

```
public class TestService : ITestService
	{
		public int Calls { get; set; }
		
		public TestService()
		{
			Calls = 0;
		}
```

And run the app you will see TestService constructor will be called twice instead of just once

I assume I'm doing something wrong here or?

**Comment by dvorn** [comment]
You should do `Container.RegisterType<ITestService, TestService>(new ContainerControlledLifetimeManager());`

**Comment by bartlannoeye** [comment]
Unity registers types as instance per request instead of singleton by default, @dvorn showed how to get a singleton. More info: https://msdn.microsoft.com/en-us/library/ff660872(v=pandp.20).aspx

Please use StackOverflow for questions like this and keep GitHub for Prism issues (bugs) and feature requests.
