### ISSUE TITLE
[UWP]Model Validation Exception

### ISSUE THREAD

**Issue by BekOV** [PrismLibrary/Prism#753]
### Package info
- Platform: UWP
- Prism version: Prism.Windows 6.2.0
- Windows 10 SDK version (if applicable): 14.393

### Issue
I have a model class Address: 
`public class Address : ValidatableBindableBase {
 [Required(ErrorMessageResourceType = typeof(ErrorMessagesHelper), 
  ErrorMessageResourceName      = "RequiredErrorMessage")]
        public string City
        {
            get { return _city; }
            set { SetProperty(ref _city, value); }
        }
 }
`So i use Attributes to specify validation rules.
Here is my `usings` : 
 `using System.ComponentModel.DataAnnotations;
  using Prism.Windows.Validation;`
When i am starting to input something in my City TextBox there is an exception: 
`An exception of type 'System.IO.FileLoadException' occurred in Prism.Windows.dll but was not handled in user code
Additional information: Could not load file or assembly 'System.ComponentModel.Annotations, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)`

**Comment by dvorn** [comment]
Seemingly you are using not Prism validation (UWP only) but the package Prism.Validation from Nuget which is a different beast.  Probably you should change `using Prism.Windows.Validation` to `using Prism.Validation`.
