### ISSUE TITLE
PubSubEvent without a payload - Virtual method-signature is missing

### ISSUE THREAD

**Issue by JarJarBinkz** [PrismLibrary/Prism#755]
We use the new feature "**PubSubEvent without a payload**" and found out that the new method 

> public SubscriptionToken Subscribe(Action action, ThreadOption threadOption, bool keepSubscriberReferenceAlive)

 in the "**PubSubEvent**"-Class is not virtual like in the old **"PubSubEvent\<TPayload\>**"-Class.

 Without virtual we can't fake(MS Fakes) the method inside a UnitTest.

Can you change the method-signature to virtual?

### Package info

- Platform: WPF
- Prism version: 6.2

**Comment by bartlannoeye** [comment]
@brianlagunas do we need a pre-release for this?

**Comment by brianlagunas** [comment]
I won't have time for a pre-release anytime soon.  This is not a blocking issue.

**Comment by bartlannoeye** [comment]
@JarJarBinkz how blocking is this on your end?

**Comment by JarJarBinkz** [comment]
@bartlannoeye 

It would be nice if a prerelease would be available in 3 months, because our software will be released early next year.

**Comment by dansiegel** [comment]
@JarJarBinkz remember this is open source.... Nothing stops you from either:
1) Cloning the Prism Library, building it, packing it with a hot fix you need, and pushing the package to your own feed or a local folder.
2) Including the Prism Library as a Git Submodule or Subtree, and referencing the projects you need so it can be compiled and included with your code.

**Comment by wakemaster39** [comment]
I ran into this problem as well and put in a work around, but a pre release to work around it is always appreciated.

**Comment by bartlannoeye** [comment]
@JarJarBinkz @wakemaster39 we got a prerelease up on [MyGet](https://www.myget.org/F/prism/api/v2). Feel free to test and give feedback.
