### ISSUE TITLE
[WPF] IRegionNavigationJournal CanGoBack property is true after second RequestNavigate

### ISSUE THREAD

**Issue by Bemjamin** [PrismLibrary/Prism#757]
### Package info
- Platform: WPF
- Prism version: 6.1

On my module initiation I am only registering my views with RegisterViewWithRegion method and the first view registered becomes the modules's default view. 

`_regionViewRegistry.RegisterViewWithRegion("ConfigurationRegion", typeof(View1));
            _regionViewRegistry.RegisterViewWithRegion("ConfigurationRegion", typeof(View2));`

Everything works fine. So in View1 I have a button that navigates to View2 and in this second view the Journal in the NavigationContext shows me that the property CanGoBack is aways false. 

On the View2 I have a back button that returns to the View1 using a RequestNavigate and on the View1 the CanGoBack property is true. 

What I realised is that the first time we navigate prism doesn't update the Journal and we can't GoBack . To fix this on my module Initialize() I made a RequestNavigate after the views registration.

`_regionViewRegistry.RegisterViewWithRegion("ConfigurationRegion", typeof(View1));
            _regionViewRegistry.RegisterViewWithRegion("ConfigurationRegion", typeof(View2));
            _regionManager.RequestNavigate("ConfigurationRegion", new Uri("View1", UriKind.Relative));`

So I was wondering if this is an expected behaviour. Considering that I don't really need to force a navigation after the registration.

**Comment by dvorn** [comment]
[Navigation Using the Prism Library for WPF](https://github.com/PrismLibrary/Prism/blob/master/Documentation/WPF/60-Navigation.md):

> **Note:** The navigation journal can only be used for region-based navigation operations that are coordinated by the region navigation service. If you use view discovery or view injection to implement navigation within a region, the navigation journal will not be updated during navigation and cannot be used to navigate forward or backward within that region.
