### ISSUE TITLE
Binding to Date/Time Picker in OnNavigatedTo

### ISSUE THREAD

**Issue by rhowes** [PrismLibrary/Prism#762]
In a ContentPage I have a Grid of 14 TimePickers defined in XAML. There are bound to properties in the associated ViewModel. If the values of these controls are set in the OnNavigatedTo method then firstly these controls are displayed with their default values (midnight) and then with those set in the OnNavigatedTo method, which looks pretty messy.

If the values are set in the constructor then the display is fine, however that defeats the purpose of sending parameters in as NavigationParameters. Making the TimeSpan's these controls are associated with nullable doesn't work either.

It is as if the OnNavigated to is happening too late.

**Comment by rhowes** [comment]
Or is this just a Xamarin problem of not having a nullable TimePicker?

**Comment by brianlagunas** [comment]
If you have a default value, then it will be displayed until the underlying data has been changed in the OnNavigatedTo.

**Comment by rhowes** [comment]
Ok - thanks for prompt response. What would be a really good solution would be to have access to the NavigationParameters in the constructor... I tried using the EventAggregation but settled for making my own controls that don't display anything for null/default values.
