### ISSUE TITLE
Async ViewModel Initiation

### ISSUE THREAD

**Issue by EuroEager2008** [PrismLibrary/Prism#764]
I want to initiate a ViewModel asynchronously, i.e. getting lots of file info perhaps over the network.
The View uses the ViewModelLocator.
The bootstrapper is a UnityBootstrapper.
As we know, we cannot use the await keyword in the constructor, but of course I can make a async Init method doing all this (which in turn updates a property used by the view by databinding).
Can this Init method be called by e.g. the Module.Initialize() ?
(Of course it can, but how to get access to the ViewModel ?)

**Comment by brianlagunas** [comment]
First, you should upgrade to Prism for Xamarin.Forms 6.2.  There is no longer a bootstrapper.  Better yet, just install the Prism Template Pack from the Visual Studio Gallery, and use it to create your project.

https://visualstudiogallery.msdn.microsoft.com/e7b6bde2-ba59-43dd-9d14-58409940ffa0

Why not just load your data in the INavigationAware.OnNavigtedTo method?  Also, you can still have async code run in the ctor, you just have to use a different approach that doesn't use async/await

**Comment by bartlannoeye** [comment]
Read [this article](http://blog.stephencleary.com/2013/01/async-oop-2-constructors.html) for async constructors. But I do not recommend async constructors, as Brian says load data in the OnNavigatedTo method.
