### ISSUE TITLE
[Xamarin Forms] OnNavigatedTo with TabbedPage

### ISSUE THREAD

**Issue by mrkhangtran** [PrismLibrary/Prism#767]
Hi Prism team,

I have the following issue in my app, maybe it could be an enhancement in future releases

### Package info

- Platform: Droid, not yet test on iOS
- Prism version: 6.2.0
- Xamarin version: 2.3.1.114

### Repro steps
**Pages structure**
NavigationPage - Wrapper page
-- Tabbed Page - Main page
---- Content Page - a tab in main page

**Steps**
1. In App - OnInitialized: navigate to a tab in main page
`NavigationService.NavigateAsync($"NavPage/MainTabPage/TabA");`

2. From within TabA, navigate to a completely different page PageB (this page will replace the TabPage)
`NavigationService.NavigateAsync($"PageB", null, false);`

3. From PageB, navigate back
`NavigationService.GoBackAsync();`

At this point, my code in OnNavigatedTo of **TabA** doesn't get called
I figured out that the OnNavigatedTo of **MainTabPage** is actually the one that gets called

Is this something to improve in future releases or it's just the way it works?

Thanks for the great work,

**Comment by brianlagunas** [comment]
Sorry for the late reply. I am traveling.  This is an interesting scenario.  Let me think about this.

**Comment by joacar** [comment]
Wrote a test and was able to reproduce the issue (if the test is correct that is :). 

Also found that pages that doesn't have `ViewModelLocator.SetAutowireViewModel(this, true)` in ctor will inherit the `BindingContext`, at least for childs to a `TabbedPage`

**Comment by joacar** [comment]
My test is not accurately reflecting the issue you are having. Will have to create a small test and run this in emulator to be sure, but I think now where the issue might be.

Will update as soon as I have time

**Comment by dansiegel** [comment]
Yes that's actually the way it's designed to work. Pages that are children of a MultiPage such as a Tab in a TabbedPage are not actually getting navigated to, but rather it is the MultiPage (TabbedPage) that is navigated to. TabA as the Current Page is simply displayed. The Navigation you see with Tabs is a sideways navigation different from the normal navigation pattern. 

I'll have to double check that exact scenario but I believe PR #712 should address the OnNavigatedTo issue you're concerned about.

**Comment by adrianknight89** [comment]
There were appearing / disappearing issues with XF TabbedPage which got fixed recently (post  2.3.1.114). Update to the latest pre-release and see if your scenario is the same.

Also, if I'm not mistaken, putting a tabbed page inside a navigation page is not recommended by Apple.

**Comment by brianlagunas** [comment]
Thank you everyone for helping with this.  It seems there has been no response from @mrkhangtran on the comments and questions from the community.  I am closing this, as I am assuming this is related to @dansiegel suggestion of #712.

**Comment by mrkhangtran** [comment]
Thank you everyone for your support. Sorry for cannot get back earlier.

@dansiegel, @brianlagunas Yes I believe this is related to #712 
@adrianknight89 I eventually changed my page structure to TabPage -> NavPage -> ContentPage and the OnNavigatedTo now works as expected

**Comment by Hedego** [comment]
I am working on a xamarin forms and mvvmcross project. I have a tabbed page which has two tabs. The first tab is expected to show a static list of activities which are defined in a service class that inherits the Iservice version of the class. I used <local:ActivitiesPage Title="Activities"/> in the first tab but I am not sure How I Can Show the data in the tab.

**Comment by brianlagunas** [comment]
@Hedego sorry, but this is the Prism GitHub, not MvvmCross.  You should probably ask the MvvmCross community for help.

**Comment by AbhijeetChowdhury** [comment]
@brianlagunas 
I am developing a Xamarin app using Prism Unity. I am facing problem on Refreshing the binding of view after my method is called OnNavigatedTo event in my ViewModel class. PFB the code snippet:

ViewModel:

private Load _load;
public Load load
        {
            get
            {
                return _load;
            }
            set
            {
                SetProperty(ref this._load, value,"load");
            }
        }
public async void OnNavigatedTo(NavigationParameters parameters)
        {
           load = await retrieveTrip();//this service takes much amount of time
           //load = Task.Run(async()=>await retrieveTrip()).Result; //if we do this it works fine but it lacks asynchronus way
        }

The View has binding of the Load object.

` 
<StackLayout Spacing="5" Padding="10">

                <Label Text="{Binding load.proNumber,Mode=TwoWay}"
                       Style="{StaticResource labelContentStyle}"></Label>

            </StackLayout>
`

If we call the service method async way the label text always comes blank. But on synchronus calling it works as expected.

Any help will be appreciated.
Thanks in advance!
