### ISSUE TITLE
NoResize Property in PopupWindowAction.WindowContent

### ISSUE THREAD

**Issue by umairfarooq** [PrismLibrary/Prism#768]
I am using prism library to convert my existing **WPF** project from code behind to **MVVM**. And I have learnt a lot and also prism helped me a lot in many scenarios. 

Recently I came across a requirement to make Custom Dialog because I need to have a confirmation Dialog. Prism provides a by default popup dialog as well but I needed to add an image for confirmation as well. So I developed one. 

But one thing I found out that **PopupWindowAction.WindowContent** does not have any **NoResize** property like the usual Window class have. 

I was using **MessageBox** in my code behind and now I need to implement a similar dialog that has fix width and that expands in height according to content. 

Is this behavior intentional or this library needs to have a property like discussed ?

**Comment by brianlagunas** [comment]
you need to set the WindowStyle property to a style that targets the Window type and set your properties accordingly.
