### ISSUE TITLE
[XF] FFImageLoading can't initialize with XF 2.3.3.152-pre2

### ISSUE THREAD

**Issue by adrianknight89** [PrismLibrary/Prism#770]
I have the following configuration:

```
<packages>
  <package id="CommonServiceLocator" version="1.3" targetFramework="portable45-net45+win8+wp8+wpa81" />
  <package id="Prism.Core" version="6.2.0" targetFramework="portable45-net45+win8+wp8+wpa81" />
  <package id="Prism.Forms" version="6.2.0" targetFramework="portable45-net45+win8+wp8+wpa81" />
  <package id="Prism.Unity.Forms" version="6.2.0" targetFramework="portable45-net45+win8+wp8+wpa81" />
  <package id="Unity" version="4.0.1" targetFramework="portable45-net45+win8+wp8+wpa81" />
  <package id="Xamarin.FFImageLoading" version="2.1.7" targetFramework="portable45-net45+win8+wp8+wpa81" />
  <package id="Xamarin.FFImageLoading.Forms" version="2.1.7" targetFramework="portable45-net45+win8+wp8+wpa81" />
  <package id="Xamarin.Forms" version="2.3.3.152-pre2" targetFramework="portable45-net45+win8+wp8+wpa81" />
</packages>
```

Prism Template Pack 1.6
Xamarin 4.2.0.680
Xamarin.Android 7.0.0.18

I cannot initialize FFImageLoading with this setup.

```
protected override void OnCreate(Bundle bundle)
{
     TabLayoutResource = Resource.Layout.tabs;
     ToolbarResource = Resource.Layout.toolbar;

     base.OnCreate(bundle);
     CachedImageRenderer.Init();
     global::Xamarin.Forms.Forms.Init(this, bundle);
     LoadApplication(new App(new AndroidInitializer()));
}
```
throws

`System.TypeLoadException: Could not load type 'FFImageLoading.Forms.Droid.CachedImageRenderer' from assembly 'FFImageLoading.Forms.Droid, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.`

@daniel-luberda @molinch I created a new solution **without Prism** (using XF 2.3.3.152-pre2). All seems fine, so I'm not sure where the issue originates from.

**Comment by leo-mck** [comment]
I can be wrong but this seems to be a problem with every library that implement a custom Renderer and not with Prism. The latest (2.3.3.152-pre2) XF exposes an `abstract CreateNativeControl` that needs to be implemented on the renderers and all previous UI libraries stopped working for me.

**Comment by brianlagunas** [comment]
Prism does nothing different than an plain XF app except abstract away the framework so it can be used within a VM.  I would tend to agree with @leo-mck .  I do not believe this is an issue with Prism.
