### ISSUE TITLE
Interaction request inside interaction request = error

### ISSUE THREAD

**Issue by znakeeye** [PrismLibrary/Prism#772]
Prism 6.2.0.

An unhandled exception of type 'System.InvalidOperationException' occurred in mscorlib.dll
Additional information: Cannot set Owner property to a Window that has not been shown previously.

I get this error when I press a button that has a PopupWindowAction set which yields a call that throws an exception - which is then handled by showing a new popup window with an error message.

It goes something like this. In my popup view I have this:

public INotification Notification
{
	get { return notification; }
	set
	{
		if (SetProperty(ref notification, value))
			CallMethodThatTriggersAnotherInteractionRequest();
	}
}

I really need to do stuff when the Notification property is set. But if it throws I want to show an error. I believe this window has not been shown yet. Thus the error. Ideally this would be handled in Prism. Suggested workaround?

**Comment by brianlagunas** [comment]
This is an unorthodox way of handling an exception from a Notification.  I have honestly never seen this approach before and would not recommend it.  This is not something Prism will support as it is not a recommended pattern to implement.
