### ISSUE TITLE
Prism Template Pack gets deactivated

### ISSUE THREAD

**Issue by digitalsigi** [PrismLibrary/Prism#773]
I love Prism 6, well done!
However there is one pitty I hope you can solve. I am using
Microsoft Visual Studio Professional 2015
Version 14.0.25422.01 Update 3
Microsoft .NET Framework
Version 4.6.01586
and use Prism Template Pack 1.6. 
Whenever I close VS 2015 and reopen it, the Prism Template Pack is disabled. I have to re-enable it and restart VS 2015 to use it again.
Any suggestions how to overcome this?
Josef

**Comment by brianlagunas** [comment]
I have no idea what could be causing that, and without the ability to repro the issue I am not sure what else I can do for you.  Try this post, maybe it will help.

https://blog.mastykarz.nl/installed-visual-studio-extension-doesnt-work/

**Comment by digitalsigi** [comment]
Unfortunately, this didn't help, as this was already checked.
After some thinking I started VS 2015 with /LOG option and found the reason:

> 2752 ERROR
> Extension will not be loaded because an extension with the same ID 'Prism.TemplatePack.138e3411-ac97-4c11-8016-c27a831cba2e' is already loaded at C:\USERS\......\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\14.0\EXTENSIONS\KU5LQPCG.M04\...
>           C:\USERS\.....APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\14.0\EXTENSIONS\41EPVU11.FAA\

Now, because of "Prism Templates" are disabled, I deinstalled extension and did a new install. Maybe something has not been cleaned up. Btw I observerd a similar issue with Prism Code Snippets, they seem to appear and disappear as they like.
May it helps to find the source of problem.
To continue my work I'll deinstall, delete the directories and reinstall. I hope it helps.

**Comment by digitalsigi** [comment]
Very special, first I renamed one of the directories in above error message, no change. Then I deinstalled extensions, both directories disapeared ..., next I did a fresh download an install, violá, it works.
I guess -> its VS 2015 issue.
Anyway, thanks for careing..
Josef

**Comment by brianlagunas** [comment]
Glad you go it figured out.  VS can be a pain sometimes.
