### ISSUE TITLE
CreateNavigationService accessibility incorrect

### ISSUE THREAD

**Issue by bartlannoeye** [PrismLibrary/Prism#781]
In [PrismApplication](https://github.com/PrismLibrary/Prism/blob/master/Source/Windows10/Prism.Windows/PrismApplication.cs) both [OnCreateNavigationService](https://github.com/PrismLibrary/Prism/blob/master/Source/Windows10/Prism.Windows/PrismApplication.cs#L438) and [CreateNavigationService](https://github.com/PrismLibrary/Prism/blob/master/Source/Windows10/Prism.Windows/PrismApplication.cs#L446) are virtual. If we keep this implementation in line with the other methods, the second one should be private right?

**Comment by bartlannoeye** [comment]
Digging deeper into this, it seems that CreateNavigationService is used in the IoC specific base classes to [register the instance in the container](https://github.com/PrismLibrary/Prism/blob/master/Source/Windows10/Prism.Autofac.Windows/PrismAutofacApplication.cs#L81-L86).

This is quite critical code and moving this to the OnCreateNavigationService might introduce bugs (calling a base class is easily forgotten). But keeping CreateNavigationService open for everyone to override is equally open for the same bugs.

Putting this method internal and using InternalsVisibleTo fixes the problem for us, but prevents anyone else from writing their own IoC implementation.

Any other suggestions? Or do we leave it as-is?

**Comment by briannoyes** [comment]
I don't like the idea of blocking people from creating their own IoC Prism extension, so I think the hazards of leaving as is is the better option.

**Comment by bartlannoeye** [comment]
Created #783 to provide some clarity for anyone trying to override either method.
I suppose that's the "best" fix for now.
