### ISSUE TITLE
Autofac and Single Instance() ViewModel with View and using RegisterViewWithRegion 

### ISSUE THREAD

**Issue by SyntaxThemes** [PrismLibrary/Prism#784]
Hi,

When you register a ViewModel to the container using SingleInstance() to create a singleton the view creates another ViewModel and does not use the single instance using Autofac.

For example:

`var containerBuilder = new ContainerBuilder();
containerBuilder.RegisterType<HeaderViewModel>().As<IHeaderViewModel>().SingleInstance();
containerBuilder.Update(_container);
_regionManager.RegisterViewWithRegion(RegionNames.HeaderRegion, typeof(HeaderView));`

Then when you get the instance of the ViewModel later it is not the one connected to the view.

`
  IHeaderViewModel headerViewModel = _container.Resolve<IHeaderViewModel>();
`

This code works ok but i would rather use AutoWireViewModel = True

`
HeaderView view = _container.Resolve<HeaderView>();
            view.DataContext = _container.Resolve<IHeaderViewModel>();
            _regionManager.AddToRegion(RegionNames.HeaderRegion, view);
`

When you use Unity this code works but I cannot replicate it in Autofac:

`
_container.RegisterType<IHeaderViewModel, HeaderViewModel>(new ContainerControlledLifetimeManager());
_regionManager.RegisterViewWithRegion(RegionNames.HeaderRegion, typeof(HeaderView));
`

When you resolve the IHeaderViewModel you will get a Singleton.

Does anybody know why this doesnt work with Autofac, or am I using SingleInstance() incorrectly.  I want to use Autofac so that I can load MEF plugins into my container.

Thank you

**Comment by brianlagunas** [comment]
I have no experience with Autofac, so I will not be able to help you.  Hopefully someone that does use autofac will step in.  Until they do, I suggest downloading the source code and stepping through the AutowireViewModel code and see if you can spot the issue.

It's also not clear from your code how you are storing/using the container. Is it possible you have created multiple containers?

You could also try to Autofac project site for help.

**Comment by Portikus** [comment]
Hi @SyntaxThemes, 
I know this issue is closed but I got the same wired behaviour with Autofac. 
The solution for this is to declare your ViewModel instance as the Interface type **and** as the ViewModel type like:
````csharp
builder.RegisterType<MenuViewModel>().SingleInstance().As<IMenuManager>().As<MenuViewModel>();
````

I write this for other developer who struggle with this.

**Comment by perssondan** [comment]
Thanks to @Portikus, this worked very well.
