### ISSUE TITLE
Update Xamarin Studio Template Pack  to use IPlatformInitializer

### ISSUE THREAD

**Issue by Willjobs94** [PrismLibrary/Prism#787]
### Package info
- Platform: Xamarin Studio
- Prism version: 6.2

I created a project in Visual Studio and Xamarin Studio and noticed that in the Visual Studio Template Pack the same UnityApp Project differ with the Xamarin Studio version. In Visual Studio the App class constructor has a parameter of type IPlatformInitializer while the Xamarin Studio version does not.

This Issue depends on #789

**Comment by Majirefy** [comment]
There is no new Prism Add-in for new Xamarin Studio 6.1 yet, so wait for an update.

**Comment by brianlagunas** [comment]
This has been fixed. Please test v1.4
