### ISSUE TITLE
[XF] Find a way to clean up Views/VMs when Popping off the Nav Stack

### ISSUE THREAD

**Issue by brianlagunas** [PrismLibrary/Prism#793]
We need to find an approach to provide developers a way to clean up a View and/or ViewModel when a page is removed from the navigation stack.  Possibly utilize the already existing IDisposable interface, or create a new interface (not sure if that's necessary).

**Comment by brianlagunas** [comment]
This will most likely be dependent on #634

**Comment by tboogh** [comment]
Possibly ```OnParentSet``` could be used as a mechanism for this. Only had time to run a test on a ```NavigationPage``` but the ```Parent``` property is set to null and the method called when the page is popped
