### ISSUE TITLE
[XF] Correct way to set new Application.MainPage?

### ISSUE THREAD

**Issue by tomcrusader** [PrismLibrary/Prism#794]
I couldn't find a clear answer to if and how to completely change the MainPage, i.e. a Xamarin.Forms.NavigationPage.

The scenario is that my login page (a TabbedPage with login / registration) is contained in one navigation page and the rest of the app in another. So once the user has registered / logged in I need to change the main navigation page.

Only way I've managed to do this is by resolving manually with the Prism container, but it's sub-optimal.

                // Set new base navigation page
                var navPage = this.Container.Resolve<NetNavigationPage>();
                var postsPage = this.Container.Resolve<PostListPage>();
                await navPage.PushAsync(postsPage);
                this.MainPage = navPage;

**Comment by joacar** [comment]
If you use absolute URI for navigation the navigation stack is cleared and the `MainPage`-property is set to the first page in the path. See [here](https://github.com/PrismLibrary/Prism/blob/master/Documentation/Xamarin.Forms/3-NavigationService.md#navigating)

````c#
Task SignIn()
{
     // Successfully signed in
    await navigationService.Navigate("app:///postListPage");
}
````
In the future ask these kind of questions on Stackoverflow and tag them with Prism/Prism.Forms :)
