### ISSUE TITLE
Windows 10 Resume from suspension

### ISSUE THREAD

**Issue by nolanblew** [PrismLibrary/Prism#795]
I have been having an issue in which resuming from suspension in a UWP app does not trigger `OnNavigatedTo` in the viewmodel, does not call `OnResumeApplicationAsync` in `PrismApplication`, and does not even call `OnActivated` (which holds the logic for calling further resume methods in Prism).

I believe all that has to be done is hook into the `Resuming` event in `PrismApplication.cs` (I have a working version on my fork). Thoughts?

**Comment by bartlannoeye** [comment]
Ah the beautiful application lifecycle. I'll have a look at your PR later tonight or tomorrow evening. Pretty sure this used to work. What version is your OS and your SDK?

**Comment by nolanblew** [comment]
Sure. I have Windows 10 1607 (OS Build 14393.222) anniversary update. SDK is 10.0.26624 and our target version is 10586... However my team has had this issue since May (it just hasn't been important to us until now)

**Comment by bartlannoeye** [comment]
@nolanblew can you check #801 please? I expanded your PR with OnResumeApplicationAsync and re-tested all activation paths.

**Comment by bartlannoeye** [comment]
Prerelease package up on https://www.myget.org/F/prismprerelease/api/v3/index.json
