### ISSUE TITLE
Rename PubSubEvents to PrismEvent?

### ISSUE THREAD

**Issue by brianlagunas** [PrismLibrary/Prism#8]
We need the community's input on this issue.  We are considering changing the name of the event aggregator's PubSubEvent to PrismEvent to better align with Prism as a product.  What are the community's thoughts on this?  Should we make the change?  Prism 6 for WPF will contain breaking changes in terms of namespaces.  So, since we are breaking apps, now would be the time to do it.

What are your thoughts?

**Comment by keozx** [comment]
I agree! :+1:

**Comment by llewelynrex** [comment]
Sure. Out with the old and in with the new!

**Comment by bartlannoeye** [comment]
Moving the namespace from _Microsoft.Practices.Prism.PubSubEvents_ to _Prism.Events_ certainly aligns it with the rest of (the new) Prism. That's a clear choice I'd say.

Changing the class name from _PubSubEvent_ to _PrismEvent_ is (in my opinion) a harder nut to crack. It would fit more in the branding of the Prism product. On the other hand the PubSubEvent class hints we're using a publisher-subscriber pattern, which is also clearly stated by the Publish and Subscribe methods. But then you could bring up as argument that nobody will use Prism without reading at least some documentation (which would state the publisher-subscriber pattern).

**Comment by ashokgelal** [comment]
I'm kind of torn on this. On one hand I personally don't like the name `PubSubEvent`but on the other hand I don't like the idea of tying it up too much with Prism. Prism is too close to be a pure Windows+WPF only library. Unless we plan to make Prism a true cross platform library, I don't want to give an impression that this awesome library has anything to do with Windows+WPF. As a matter of fact, we are using `PubSubEvents` package in our Xamarin.Mac apps.

**Comment by brianlagunas** [comment]
If you look at the new structure, Prism is now headed towards a true cross platform library.  Commanding, Logging, and Even Aggregation (PubSubEvents) have moved into a single PCL.  We also recently started adding support for Xamarin.Forms.  Soon we will be adding Windows 10 support.

**Comment by ashokgelal** [comment]
I noticed that and if that's where we are heading then I'm all up for it. Let's do it! I like the name way better then PubSubEvent anyway.

**Comment by akoken** [comment]
It would be great :+1:

**Comment by sgrassie** [comment]
:+1:

**Comment by Michael-DST** [comment]
Anything other than PubSubEvent would be an improvement in my book.  I like PrismEvent from a branding perspective.  Although, personally, I would try to get away with just Event<>, if possible (since Prism is already in the namespace), but PrismEvent is better than the previous version.  Prism is just a cool/good name. :+1:

**Comment by brianlagunas** [comment]
Well technically, the class doesn't really do anything special.  PubSubEvent is not the concern that is doing the publishing or subscribing.  The IEventAggregator is doing the pub/sub action.  So the PubSubEvent name doesn't fit well with the class.  The PubSubEvent is just an event used by the IEventAggregator.  The reason to prefix with "Prism" is to eliminate any collisions with the.NET Event class, since it is an event specifically for use in Prism with the event aggregator.

**Comment by powerdude** [comment]
EventAggregatorEvent?

**Comment by brianlagunas** [comment]
So I was looking into this some more and it appears that there is no Event class in .NET.  There is an "event" keyword, but no Event class.  So, what if we just called it Event?

public class SaveEvent : Event<string> {  }

Thoughts?

**Comment by Michael-DST** [comment]
:+1: :+1: :+1:

**Comment by brianlagunas** [comment]
It's been brought up that Event < string > may be too ambigious, and I tend to agree.

And, it turns out that I was wrong when I said the IEventAggregator does the pub/sub action.  It is actually the event.  I don't know what I was thinking!

Anyways, knowing that the event does actually perform the pub/sub actions, should we just keep it PubSubEvent?

I am leaning towards keeping it that way.
