### ISSUE TITLE
[Win10 UAP] VisualStateAwarePage

### ISSUE THREAD

**Issue by jorisdebock** [PrismLibrary/Prism#80]
I was wondering if there is still a need for the visual state switching in the VisualStateAwarePage, since with windows 10 universal app this now can be done in xaml

```
<VisualState.StateTriggers>
    <AdaptiveTrigger MinWindowWidth="720" />
</VisualState.StateTriggers>
```

**Comment by briannoyes** [comment]
Will be looking into it within the next couple weeks. If we can trim down or better yet elimination the need for a page base class, I would be all for that.

**Comment by tomzorz** [comment]
Lines 17-56 (except 43) and lines 141-251 are all for visual states, those could be removed. I don't see a way around the session state and navigation parts though.

**Comment by briannoyes** [comment]
hah, already have the work done, just need to check it in.

**Comment by briannoyes** [comment]
Changes are checked in with PR #164
