### ISSUE TITLE
[UWP] TabbedPage in MasterDetailPage won't change tabs (strange behavior)

### ISSUE THREAD

**Issue by Zure1** [PrismLibrary/Prism#805]
### Package info

- Platform: UWP
- Prism version: 6.2.0
- Xamarin version (if applicable): 2.3.2.127
- Windows 10 SDK version (if applicable): Windows 10 Anniversary Edition (10.0; Build 14393)

### Repro steps

TabbedPage Bug in UWP when using Prism

When using a TabbedPage inside a MasterDetailPage with Prism in UWP, it's not possible to change tabs if Prism is setting the Detail of MasterDetailPage.

Expected Behavior: I expect the TabbedPage to change the tabs and show "ContentPageRedView".

Actual Behavior: It doesn't show the other view. It doesn't matter which view is shown on the first tab. Whenever you click on another tab, nothing happens. When you click on the first tab (the one that's actually showing), the Master turns completely white.

For information on how to use the project, please read the README in the repo.

If anything is unclear, please ask. It's the first time I'm submitting a bug.

If you know any workarounds, it would be appreciated too.

Link to the repo: https://github.com/Zure1/TabbedPageSample

**Comment by brianlagunas** [comment]
Sorry for the late response.  I am traveling in Japan right now.  I am unable to reproduce the issue you are describing.  It works perfectly for me.  I am able to change tabs of the TabbedPage that is in the MasterDeatilPage.Master.  So, it works on my machine :)

![tabbedpage-as-master-works-for-me](https://cloud.githubusercontent.com/assets/835562/19373356/3ae0ca2e-91fe-11e6-8cae-24ac6b38b431.jpg)

To be safe, make sure you have declared the base class on your TabbedPage just so the Container doesn't have any issues registering it:  `public partial class TabbedPageView : TabbedPage`

Other than that, I have no idea why it's not working for you.
