### ISSUE TITLE
Gitter or Slack channel

### ISSUE THREAD

**Issue by smedegaard** [PrismLibrary/Prism#807]
May I suggest that you create a Gitter or Slack channel so the Prism users can discuss matters that are not quite worhty of a Github issue?

**Comment by bartlannoeye** [comment]
Do you mean minor questions? We have StackOverflow for that. Or do you have anything else in mind?

**Comment by brianlagunas** [comment]
I do have a slack channel, but never published it publically.  I don' have enough time to monitor too many communication methods.  So I would prefer to keep it to GitHub and SO.  Unless you expect the community to monitor it itself?

**Comment by smedegaard** [comment]
I didn't expect you to monitor it. Just to be a place where the community could communicate real time.

**Comment by brianlagunas** [comment]
The problem with slack is that an invitation must be sent out in order for people to join.  I couldn't find a way to let anyone just sign up.

**Comment by smedegaard** [comment]
Hi @brianlagunas, I played around with Gitter to make a room for Prism. I think I sent you an invite by accident. You can just ignore that

**Comment by smedegaard** [comment]
Hi again @bartlannoeye and @brianlagunas ,
So I created a Gitter channel (https://gitter.im/prism-mvvm) and invited you both. I hope would will consider linking it to the repo.
I find myself in situations where I'd like to ask ed community a question that does not belong on Stackoverflow or as an issue here on Github. 
I do not expect any of you guys to monitor this channel, but I feel it would be a great addition to the community with zero cost and minimal effort on your behalf. 

Thanks for considering this again ,and thanks for maintaing Prism.

Regards Anders Smedegaard

**Comment by brianlagunas** [comment]
Okay, I have created a new website to automate the process of signing up for the http://prismlibrary.slack.com/ channel.
You can use this website: https://prismslack.herokuapp.com/
Let me know if this works.

**Comment by smedegaard** [comment]
@brianlagunas , works like a charm! Thanks!

**Comment by iquijas** [comment]
I tried to access https://prismslack.herokuapp.com/ but I get an application error:

![image](https://cloud.githubusercontent.com/assets/10888177/25537760/768a7042-2c05-11e7-8047-a48eb8ff1e7a.png)

**Comment by brianlagunas** [comment]
This is because Herokuapp limits how many hits the site can have a month.  Just wait until the 1st and the limit resets :)
