### ISSUE TITLE
[XF] IDevice interface and implementation class

### ISSUE THREAD

**Issue by nuitsjp** [PrismLibrary/Prism#808]
When ViewModel and Model is to use the Device class of Xamarin.Forms, it will be difficult to unit test.
By using the IDevice like IDependencyService, I believe that it is possible to solve this problem.

Is this something that we would like in Prism or is this considered to be to application specific requirement?

Example
```cs
    public interface IDevice
    {
        TargetIdiom Idiom { get; }
        void BeginInvokeOnMainThread(Action action);
    }

    public class Device : IDevice
    {
        public TargetIdiom Idiom => Xamarin.Forms.Device.Idiom;
        public void BeginInvokeOnMainThread(Action action) 
            => Xamarin.Forms.Device.BeginInvokeOnMainThread(action);
    }
```

**Comment by brianlagunas** [comment]
I am not sure how common it is to need access to this information in a ViewModel.  Is this needed often across the majority of Xamarin.Forms applications, or is it needed in just a few special scenarios?  This would not be difficult to add.

**Comment by mikegottlieb** [comment]
I access the device OS or use OnPlatform in the view model a decent amount. Same with BeginInvokeOnMainThread. I've found that there are a lot of minor differences that I need to account for when trying to make sure iOS and Android both look and feel native and a convenient way to do it is in the logic of a bound property so they end up in my view model.

**Comment by nuitsjp** [comment]
If ViewModel, dispatch to the UI thread using BeginInvokeOnMainThread is probably the most common scenario. 
The others might not use very often. 
OpenUri is trouble where to use. ViewModel? Model? 
Model if StartTimer also available.

**Comment by brianlagunas** [comment]
I am implementing the following:
```
    public interface IDeviceService
    {
        TargetIdiom Idiom { get; }

        TargetPlatform Platform { get; }

        void BeginInvokeOnMainThread(Action action);

        void OnPlatform(Action iOS = null, Action Android = null, Action WinPhone = null, Action Default = null);

        void StartTimer(TimeSpan interval, Func<bool> callBack);
    }
```

Nothing else looked like it would make sense.  Thoughts?

**Comment by nuitsjp** [comment]
OpenUri and OnPlatform<T> is not required? 
Then, is it easier to those who Brian has implemented? 
If necessary, send PR. 
In that case, please tell me the name space

**Comment by brianlagunas** [comment]
OpenUri does not make sense because Prism has it's own INavigationService that you should use to open a URI.

OnPlatform is in the Interface I pasted above.

**Comment by brianlagunas** [comment]
You can review PR #809

**Comment by nuitsjp** [comment]
I'm sorry. Tag was removed.
Generics OnPlatform&lt;T&gt; is not required?
I saw PR. Everything else is perfect!

**Comment by brianlagunas** [comment]
Sorry, I missed that one.  Please check it again :)

**Comment by nuitsjp** [comment]
Great!
It's a big help. Thank you very much!

**Comment by amalmo** [comment]
@brianlagunas Shouldnt there be a stopTimer as well?

**Comment by nuitsjp** [comment]
DeviceService wraps the Xamarin.Forms.Device class.
If you return false with callback, the timer stops.

https://developer.xamarin.com/api/member/Xamarin.Forms.Device.StartTimer/p/System.TimeSpan/System.Func%7BSystem.Boolean%7D/
