### ISSUE TITLE
Modded server issue (wont rollback at all)

### ISSUE THREAD

**Issue by profjb** [PrismLibrary/Prism#81]
So their is a really strange issue on our server currently that has happened with both coreprotect and prism. When using /prism inspect it can tell exactly which blocks have been placed, removed etc... and by which person but when trying the command /prism rollback it wont rollback even the most basic of vanilla blocks, e.g. it wont rollback lava, explosions, placing or destroying of blocks. Just wondering what’s up. Theirs no error report and prism actually reports it's rolled back the greifing.
![2015-07-19_16 51 27](https://cloud.githubusercontent.com/assets/3171820/8766600/05af1ee0-2e37-11e5-89f9-69bff6c19b47.png)
![2015-07-19_16 50 54](https://cloud.githubusercontent.com/assets/3171820/8766599/05af01f8-2e37-11e5-9d6a-3feec5c9e58a.png)

**Comment by briannoyes** [comment]
@profjb Think you got the wrong Prism open source project - we are a framework for building XAML applications for desktop and mobile Windows. Nothing to do with Minecraft here, although my son is an addict. :)
