### ISSUE TITLE
DryIoc Container support for WPF and UWP

### ISSUE THREAD

**Issue by AlesDo** [PrismLibrary/Prism#811]
I have seen there is already support for the DryIoc container for Xamarin. Do you already have some plans to do it? If not I would like to contribute the support also for WPF and UWP so it can be used on all of the platforms.

**Comment by brianlagunas** [comment]
No one has asked for it for WPF or UWP yet.  I wouldn't do it for UWP because I am not sure what my plans are for it yet.

**Comment by AlesDo** [comment]
I see. I can then contribute the WPF support. And once you decide the about the UWP we will see if it will be needed. Are you thinking of supporting UWP only via the Xamarin implementation now that it supports also UWP?

**Comment by brianlagunas** [comment]
I haven't decided.  Actually I am working with Jerry to see if we can consolidate Prism and Template10.  So it really depends on a number of factors.

**Comment by brianlagunas** [comment]
Seems people are having issues with DryIoC in XF so I am holding off adding it to WPF or UWP.

**Comment by dansiegel** [comment]
@brianlagunas I'm not seeing any open issues for DryIoc XF... can you clarify what the "issues" are that people are having?

**Comment by brianlagunas** [comment]
I am getting emails and twitter questions.  Here is one app that someone is having trouble getting to work.  I haven't looked into it.

https://github.com/ederbond/Toro.App

**Comment by brianlagunas** [comment]
WPF now has DryIoc. I'm not touching UWP until my plan for the platform is finalized.
