### ISSUE TITLE
Stuck while using a prism template pack

### ISSUE THREAD

**Issue by msglight4874** [PrismLibrary/Prism#814]
- Platform: Mac Sierra
- Prism version: 1.4
- Xamarin version (if applicable): 6.1.1
- Windows 10 SDK version (if applicable): No
- Other version info:

Hi guys,

I'm new to Xamarin development.
When i creating a new xamarin form project with prism template pack,
the project status stuck at "Adding packages" and package show the message 『Attempting to gather dependency information for package 'Prism.Unity.Forms.6.2.0-pre5' with respect to project 'PrismPractices.iOS', targeting 'Xamarin.iOS,Version=v1.0'』.
Please help me solve this problem. Thanks

David

screenshot:
[http://imgur.com/a/c31VS](http://imgur.com/a/c31VS)

**Comment by brianlagunas** [comment]
The Prism Template Pack has no control over how Xamarin Studio performs while loading packages.  I did notice that I need to update the package versions to the latest, but other than that there is nothing I can do.  I suggest closing XS and restarting it.

**Comment by msglight4874** [comment]
Ok Thanks

**Comment by Eliasar** [comment]
I closed XS and restarted it, created a new project using the add-in pack, and got the same issue. Project creating hangs on "Attempting to gather dependency information for package 'Prism.Unity.Forms.6.2.0-pre5'".

**Comment by brianlagunas** [comment]
did you upgrade the add-in to 1.5?  Also, my Mac is down so I can't test this.  Can you download the source and debug this, then submit a PR to fix?

**Comment by Eliasar** [comment]
1.5 is missing from the Xamarin Studio Gallery, only version 1.4 is available. The page "exists" in Monodevelop's Repository at http://addins.monodevelop.com/Project/Index/226, but v1.5 404's when you click to download it.

**Comment by brianlagunas** [comment]
Does the template work now?

**Comment by Eliasar** [comment]
It works great. Thanks!
