### ISSUE TITLE
[Docs] Research Read The Docs for documentation hosting

### ISSUE THREAD

**Issue by brianlagunas** [PrismLibrary/Prism#815]
The title says it all.  I want to make the documentation easier to navigate and discover.  Are there any other doc systems the community would recommend?

**Comment by bartlannoeye** [comment]
[UWP Community Toolkit](https://github.com/Microsoft/UWPCommunityToolkit) moved to read the docs as well when they joined .NET Foundation.
I haven't digged into how it works, but seems to be based on Markdown, so we shouldn't have too much work migrating.

**Comment by brianlagunas** [comment]
Working on it, but can't seem to get it to work just yet:

http://prismlibrary.readthedocs.io

**Comment by brianlagunas** [comment]
got it working.  Now just need to improve some minor stuff and write more docs :)

**Comment by bartlannoeye** [comment]
We seem to have 2 doc folders in the repo now ?

**Comment by brianlagunas** [comment]
only until we get the RTD up and running.  Then I will remove the old docs repo.
