### ISSUE TITLE
OnPropertyChanged without a parameter name should fire the event with an empty string

### ISSUE THREAD

**Issue by hardcodet** [PrismLibrary/Prism#817]
### Package info

- Platform: Xamarin Forms -> Android
- Prism version: 6.2.0
- Xamarin version (if applicable): Latest

### Repro steps

I want to refresh all bindings on my view firing a single property change event. The VM base class gives me the OnPropertyChanged method with a default parameter (value == null) for that.

                Model = ride;
                TimeWindowModel = new TimeWindowModel(ride.DepartureTimeWindow);
                OnPropertyChanged();

This doesn't do anything though, because the property changed event seems to require an empty string. I can of course submit the string as a parameter. This works:

                Model = ride;
                TimeWindowModel = new TimeWindowModel(ride.DepartureTimeWindow);
                OnPropertyChanged(String.Empty);

However, R# (rightfully) complains here, because you attributed the property name parameter with the CallerMemberName attribute.

Suggested fix: Make the default parameter value to an empty string, or fire the event with an empty string if your receive a null parameter. Using null doesn't do anything.

**Comment by brianlagunas** [comment]
The OnPropertyChanged method will never get a null because it is using the CallerMemberNameAttribute.  It will always use the name of the Calling method, property, or event.  This means if you want to call OnPropertyChanged with an empty string, you have to pass it in, otherwise the calling method name will be used instead.  There are only a couple of scenarios where the default parameter of the method will actually get used:

https://msdn.microsoft.com/en-us/library/system.runtime.compilerservices.callermembernameattribute(v=vs.110).aspx

**Comment by hardcodet** [comment]
Well I ended up just subclassing the view model base class and supply that explicit empty string. It feels like a hack though, and I can't fire the event of the base class from a derived one. Maybe provide something explicity such a `FireAllPropertiesChanged`?

**Comment by brianlagunas** [comment]
Calling `OnPropertChanged(String.Empty)` is the best approach.  It's simple, clean, does not require creating a derived class, and does not require creating a dirty API in the Prism implementation.

**Comment by hardcodet** [comment]
I would agree if the attribute wasn't there - R# rightfully complains about the call with an explicit value.
Anyway, the issue will be a no-brainer for me once/if we get the new `OnNavigatingTo `API that allows me to set up my view models before any bindings take place.

Keep up the good work!

**Comment by brianlagunas** [comment]
> R# rightfully complains about the call with an explicit value

I disagree with this statement.  R# has this behavior completely wrong.  The reason a method has the CallerMemberNameAttribute is to pass default caller information and this signature requires an optional parameter.  This optional parameter allows you to override the caller information, which is to be an expected capability of a method with this attribute.
