### ISSUE TITLE
Allow initialization based on parameters before the view is rendered

### ISSUE THREAD

**Issue by hardcodet** [PrismLibrary/Prism#818]
- Platform: Xamarin Forms
- Prism version: 6.2.0
- Xamarin version (if applicable): Latest

I have to use the OnNavigatedTo method to initialize my view model based on the parameters submitted with the navigation request. However, setting them at this point causes the view to update itself while it's already visible, so the user sees the values changing on the view. I would much prefer to set stuff up before that happens, even before any bindings are being evaluated by the view (because otherwise, some property getters cause exceptions if the values aren't set yet). Hope that sounds like a reasonable request - keep up the good work :)

**Comment by csongysun** [comment]
[https://github.com/PrismLibrary/Prism/blob/master/Source/Xamarin/Prism.Forms/Navigation/PageNavigationService.cs#L346](url)
let OnNavigatedTo before navigationAction in PageNavigationService.cs, so init action can be invoked before the real navigate.

but i'm not sure that would not cause other problems or bad practice
e.g that would invoke init action before everytime navigate although vm has already inited (add a _inited field may solve this)
or init action may block navigating if init action need httprequest or something else.

so i prefer init the vm in its constructor and active a ActivityIndicator if it's a time-consuming action

**Comment by hardcodet** [comment]
Yeah, an *Init* call should happen after everything else has been setup, but before the view model is being connected to the view (by means of setting the BindingContext). This ensures proper behavior and makes initialization very clean - and it's quite a simple pattern.

I cannot init the VM in the constructor because I don't have the navigation parameters at this time. And the update of the bindings in OnNavigate is not time consuming (just setting a few properties), but still visible. Also, it requires me to fire a property changed event in order to refresh all bindings because I'm basically too late to the party ;)

**Comment by joacar** [comment]
This PR #796  might be worth checking out

**Comment by hardcodet** [comment]
That looks just perfect! Thanks for the pointer joacar :)
