### ISSUE TITLE
ReadTheDocs "On GitHub" links incorrect

### ISSUE THREAD

**Issue by bartlannoeye** [PrismLibrary/Prism#821]
Linking back from ReadTheDocs to GitHub is incorrect

eg.
https://github.com/PrismLibrary/Prism/blob/master/home/docs/checkouts/readthedocs.org/user_builds/prismlibrary/checkouts/latest/docs/Assembly-Versioning.md

**Comment by brianlagunas** [comment]
We have no control over that link.  This is a bug in RTD.
