### ISSUE TITLE
Inconsistent rendering of doc headers

### ISSUE THREAD

**Issue by bartlannoeye** [PrismLibrary/Prism#822]
On first sight the title in both markdown files are the same (# followed by spaced followed by title)
https://raw.githubusercontent.com/PrismLibrary/Prism/master/docs/WPF/04-Modules.md
https://raw.githubusercontent.com/PrismLibrary/Prism/master/docs/WPF/05-Implementing-MVVM.md

But rendering is different, 04 fails and 05 is correct.
http://prismlibrary.readthedocs.io/en/latest/WPF/04-Modules/
http://prismlibrary.readthedocs.io/en/latest/WPF/05-Implementing-MVVM/

Any specialists around who spot the issue?

**Comment by brianlagunas** [comment]
I noticed this too. Very weird.  Seems RTD has a couple of issues :)

**Comment by brianlagunas** [comment]
Looks like we have to get rid of the space between the # and the text.
