### ISSUE TITLE
navigation fails if source contains space or backslash

### ISSUE THREAD

**Issue by Haukinger** [PrismLibrary/Prism#827]
### Package info

- Platform: WPF
- Prism version: 6.2

### Repro steps

- Register a view with `RegisterTypeForNavigation` providing a name string parameter that contains either " " or "\"
- Navigate to the view with `RequestNavigate` by the same name string
- The view shows "System.Object" instead of the view

Change the name string to contain neither " " nor "\" and the view is shown as expected

**Comment by brianlagunas** [comment]
This is by design.  Navigation paths must be a valid relative, or absolute URIs.  Also, never register a type for navigation with a " " or "\" in it.

**Comment by Haukinger** [comment]
Ok, got it, but it comes a bit unexpected as there's no hint about these restrictions when registering the type and there are dedicated overloads of the navigation methods that take _not_ an uri but a string.

**Comment by brianlagunas** [comment]
Once you understand that navigation is always URI based, regardless of what overload you use, then it becomes clear.

**Comment by Haukinger** [comment]
Is that a legacy from silverlight? We have hierarchical navigation in prism forms, but what's the benefit of using uris on wpf?

**Comment by brianlagunas** [comment]
No, not legacy.  Navigation in Prism has always been URI based.  The benefit is clean, maintainable, testable, and extensible WPF applications.

**Comment by Haukinger** [comment]
I mean, _does prism for wpf make use of the path-like nature of uris and how?_

If I can only navigate to one region, I just need an unique identifier for the thing I want to show in the region, correct?

If I do not have to serialize my navigation parameters into that identifier, I could just use any string, no need to reuse the query-functionality of the uri. And if I can use any identifier, in what respect is "http://localhost/myview" more clean, maintainable, testable or extensible than "my view"?

It's even misleading, because it pretends to use http, and that's clearly not the case.

**Comment by brianlagunas** [comment]
It's not misleading at all, and it is very clear that it doesn't have to be an http, but can be any valid URI syntax.  There is a much bigger picture that you aren't seeing, especially considering the impacts on DI container registrations.  Unfortunately, these are concepts that cannot be explained in a GitHub thread.
