### ISSUE TITLE
Deep Linking Navigation (MyNavigationPage/ViewA/ViewB/ViewC) not working as expected. [XF]

### ISSUE THREAD

**Issue by diptesh-patil** [PrismLibrary/Prism#828]
I am downloaded and executed the HelloWorld sample as is.
From MasterDetailPage when you click on "ViewC" it is expected to load MyNavigationPage/ViewA/ViewB/ViewC, but looks like the stack is wrongly populated something like this ViewC/ViewB/ViewA.

Debugging it further it looks like in Navigation\PageNavigationService.cs functions ProcessNavigationForContentPage, ProcessNavigationForNavigationPage do the recursive call to ProcessNavigation(...) first and then calls DoNavigateAction(...) which will fill the stack in reverse order.
Changing this did fixed the issue.

Since this pattern is used throughout the code not sure if this would be a right fix. But would really like your help to get this fixed as I am stuck on this.

Attaching the modified file.
[PageNavigationService.cs.txt](https://github.com/PrismLibrary/Prism/files/562841/PageNavigationService.cs.txt)

### Package info

- Platform: Xamarin.Form (ALL)
- Prism version: 6.2.1
- Xamarin version (if applicable):
- Windows 10 SDK version (if applicable):
- Other version info:

### Repro steps

Please describe the issue/request in detail.

**Comment by brianlagunas** [comment]
Actually, I wrote this sample to reproduce a bug in Xamarin.Forms.  I had to reproduce it in order to submit it to Xamarin

https://bugzilla.xamarin.com/show_bug.cgi?id=45978

We cannot change the order in which we build the navigation stack.

**Comment by brianlagunas** [comment]
Luckily, this is not a very common navigation pattern. So it is not a big deal.
