### ISSUE TITLE
Prism.Core 6.2.1 incompatible with Prism.* 6.2.0

### ISSUE THREAD

**Issue by plamen-i** [PrismLibrary/Prism#830]
Just to note here problem, which another user (PloraX) submitted to your blog and which I'm also experiencing.

Long story short - Prism.dll v6.2.1 assembly has same version number, but (intentionally or not) different PublicKeyToken than Prism.dll v6.2.0 so other v6.2.0 assemblies do not recognize it.

Plamen

**Comment by brianlagunas** [comment]
Weird!  I didn't change anything.  Well... I did just get a new computer, so I bet when I built on this new machine, it changed the key.  Damn it!  I'll get this fixed ASAP!

**Comment by brianlagunas** [comment]
I just removed the Prism.Core 6.2.1 package from NuGet until I can get this fixed.  I really don't want to have to rebuild, and release everything just to make these compatible.

**Comment by brianlagunas** [comment]
Alright.  We figured out the issue.  After releasing 6.2, we removed the PFX and went with SNK.  This is what changed the key.  So we will be releasing a 6.3 preview this week instead.

**Comment by brianlagunas** [comment]
This has been fixed with the 6.3.0 preview.
