### ISSUE TITLE
Support for async subscribers in the EventAggregator.

### ISSUE THREAD

**Issue by ylatuya** [PrismLibrary/Prism#832]
Hi,

One of the main issues we found with the EventAggregator  implementation is that it does not supports async subscribers. We have added support for that so one can now do:

```
void Subscribe () {
  EventAggregator.GetEvent<PubSubEvent<SaveProjectEvent>> ().SubscribeAsync (HandleSave);
}

async Task HandleSave (SaveProjectEvent saveEvent){
  saveEvent.ReturnValue = await AsyncTask();
}

void Save () {
  var saveEvent = new SaveProjectEvent (project;
  await  EventAggregator.GetEvent<PubSubEvent<SaveProjectEvent>> ().Publish (saveEvent);
  if (saveEvent.ReturnValue) {
     InfoMessage ("Success");
  }
}

```

This changes slightly the API, with Publish returning a Task and adding a new SubscribeAsync function,  but I think the change makes the events aggregator much more useful.
Would you consider a change like that? In that case we can work on the PR.

**Comment by brianlagunas** [comment]
Thanks for the idea, but this is not something we will be adding to Prism.  The even aggregator is fire and forget.

**Comment by molinch** [comment]
@ylatuya would you mind sharing your implementation for PublishAsync?

**Comment by ylatuya** [comment]
You can find the implementation [here](https://github.com/fluendo/VAS/tree/master/VAS.Core/Prism) with the [commit ](https://github.com/fluendo/VAS/commit/2011d89130ce31e890294d66c4f1ec1eb99a506f#diff-63a6d189dba36c88de174742ded47af8) adding support for Async on top of Prism

**Comment by molinch** [comment]
Thanks ! I took a different approach in our project, which doesn't involve touching Prism classes, but being on top of them. If I find time I can try to share it.

**Comment by brinko99** [comment]
I too am interested in such functionality. @molinch, might you be able to share your solution?

I've successfully used the [Deferral ](http://blog.stephencleary.com/2013/02/async-oop-5-events.html) solution provided by Stephen Cleary. It requires adding a `Deferral` to the `PubSubEvent` payload that can be awaited on. It works great, but the syntax is clunky for users and implementers.
