### ISSUE TITLE
Nuget Symbols

### ISSUE THREAD

**Issue by pdinnissen** [PrismLibrary/Prism#833]
Would it be possible to get Nuget packages that are packed with symbols and hosted on SymbolsSource.org?

**Comment by brianlagunas** [comment]
This is not something that is high on my priority list.  I'm not sure how many more releases/websites/deployments that I want to add to my list of things to manage.  My first thought is that if you need to debug, download the source :)

**Comment by pdinnissen** [comment]
Completely understandable.  I've seen benefits for internal nuget packages, so I thought why not ask.  Downloading the source is always available.

**Comment by dvorn** [comment]
@brianlagunas @pdinnissen But probably you could just include pdbs and xmls with dlls, as, e.g., CommonServiceLocator does?  (See in your "packages\CommonServiceLocator.1.3\lib\portable-net4+sl5+netcore45+wpa81+wp8\").

**Comment by pdinnissen** [comment]
Or maybe just update the pack command with '-Symbols'? that way they would already by in the .nupkg.
