### ISSUE TITLE
[UWP] App written in VB crashes in Release mode only 

### ISSUE THREAD

**Issue by stonelyd** [PrismLibrary/Prism#834]
I am working on a UWP app written in VB. I am attempting to use prism for validation. 

As best I can tell, the code crashes when calling SetProperty override in Prism/Source/Windows10/Prism.Windows/Validation/ValidatableBindableBase.cs

Only crashes in Release build. 

Was not able to reproduce in C#.

### Package info

- Platform: Win 10 UWA
- Prism version: 6.2.0

### Repro steps

Simple App in C#, was not able to reproduce issue. 

https://github.com/stonelyd/PrismBindingIssue.git

The same App ported to VB, crashes in Release Build only. Debug build runs.

https://github.com/stonelyd/PrismBindingIssueVB.git

### VS info

Microsoft Visual Studio Community 2015
Version 14.0.25431.01 Update 3
Microsoft .NET Framework
Version 4.6.01586

Installed Version: Community

Visual Basic 2015   00322-20000-00000-AA277
Microsoft Visual Basic 2015

Visual C# 2015   00322-20000-00000-AA277
Microsoft Visual C# 2015

Visual C++ 2015   00322-20000-00000-AA277
Microsoft Visual C++ 2015

Windows Phone SDK 8.0 - ENU   00322-20000-00000-AA277
Windows Phone SDK 8.0 - ENU

Application Insights Tools for Visual Studio Package   7.10.01020.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2015.1 (Beta8)   14.1.11107.0
ASP.NET and Web Tools 2015.1 (Beta8)

ASP.NET Web Frameworks and Tools 2012.2   4.1.41102.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

ASP.NET Web Frameworks and Tools 2013   5.2.40314.0
For additional information, visit http://www.asp.net/

Common Azure Tools   1.8
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

GitHub.VisualStudio   1.0
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

Node.js Tools   1.2.40726.00
Adds support for developing and debugging Node.js apps in Visual Studio

Node.js Tools - Profiling   1.2.40726.00
Profiling support for Node.js projects.

NuGet Package Manager   3.4.4
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

Python Tools for Visual Studio   2.2.40825.00
Python Tools for Visual Studio provides IntelliSense, projects, templates, Interactive windows, and other support for Python developers.

Python Tools for Visual Studio - Django Integration   2.2.40825.00
Provides templates and integration for the Django web framework.

Python Tools for Visual Studio - Profiling Support   2.2.40825.00
Profiling support for Python projects.

SQL Server Data Tools   14.0.60519.0
Microsoft SQL Server Data Tools

TypeScript   1.8.36.0
TypeScript tools for Visual Studio

Visual Studio Tools for Apache Cordova   Update 10
Visual Studio Tools for Apache Cordova

Visual Studio Tools for Universal Windows Apps   14.0.25527.01
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

Web Essentials 2015.3   3.0.235
Adds many useful features to Visual Studio for web developers. Requires Visual Studio 2015

**Comment by NewBLife** [comment]
@stonelyd Maybe it is the metadata problem? You can try to add the Person type to the Default.rd.xml.

**Comment by stonelyd** [comment]
I unfortunately do not know much about the rd.xml file beyond what I can search and read about. 

Adding the line 

<Type Name="PrismBindingIssueVB.Models.Person" Dynamic="Required All"  />

does not seem help.

**Comment by brianlagunas** [comment]
Unfortunately VB is not in my language dictionary, and given this only happens in release mode I have a feeling its related to the .NET Native build chain.
