### ISSUE TITLE
Navigation problem after porting from 6.2.0 to 6.3.0 preview

### ISSUE THREAD

**Issue by ChristianRiedl** [PrismLibrary/Prism#838]
I use relative url navigation with Xamarin Forms 2.3.3.163 and I test with UWP Build 14393.

In build 6.2.0 I had problems only with hard key back navigation and solved it with a workarround handling the **NavigationPage.Popped** event. 

Now I navigate from main page A to subpage to B with relative url, then go back to A (with hard key or **GoBackAsync**).
When I try to navigate to B a second time it fails. I debugged through **NavigateAsync** and noticed that 
**GetCurrentPage**  delivers  page B (and not A). The reason is that the **PageNavigationService.Page** member is updated only during viewmodel autowire action when a page is loaded but not during _GoBack_. I think that **NavigateAsync** requires that current page is set properly.

After adding some lines of code to restore the current page during _GoBack_ everything worked fine for me.

In **PageNavigationService.GoBackAync** :  

```
                if (poppedPage != null)
                {
                    PageUtilities.OnNavigatedFrom(page, segmentParameters);
                    _page = previousPage;           // @@@
                    PageUtilities.OnNavigatedTo(previousPage, segmentParameters);
                    PageUtilities.DestroyPage(poppedPage);
                    return true;
                }

```

In **NavigationPageSystemGoBackBehavior**  :

```
       WeakReference <IPageAware> _pageAware;
        public NavigationPageSystemGoBackBehavior (IPageAware pageAware)
        {
            _pageAware = new WeakReference<IPageAware>(pageAware);
        }
       private void NavigationPage_Popped(object sender, NavigationEventArgs e)
        {
            if (PageNavigationService.NavigationSource == PageNavigationSource.Device)
            {
                var parameters = new NavigationParameters();
                PageUtilities.OnNavigatedFrom(e.Page, parameters);
                IPageAware pageAware;
                if (_pageAware.TryGetTarget(out pageAware))
                    pageAware.Page = AssociatedObject.CurrentPage;     // @@@
                PageUtilities.OnNavigatedTo(AssociatedObject.CurrentPage, parameters);
                PageUtilities.DestroyPage(e.Page);
            }            
        }

```

**Comment by brianlagunas** [comment]
Can you provide more information, maybe even a sample?  The changes you made will have no impact on the actual functionality because this is not a single instance navigation service;.  Each nav service is associated with a view.  So changing this will not behave the way you think it does.

**Comment by brianlagunas** [comment]
Also, the preview now handles the GoBack buttons, so you can remove the code in your work around.  That could be causing the issue.

**Comment by ChristianRiedl** [comment]
I already removed the work arround code and I solved the problem in the meanwhile. I am using **SimpleInjector** container, because I have good experience in high performance web apps. Result of this experience is that I always prefer singleton services and so I registered **PageNavigationService** as singleton. Together with my work arround it was working in previous version. It is also not very **Simple** to port Unity's  **ResolverOverride** to **SimpleInjector**, so I tried it as singleton. By the way in the MSDN docs **Unity's ResolveOverride**  functionality is termed "outdated" [(see MSDN doc)](https://msdn.microsoft.com/en-us/library/microsoft.practices.unity.resolveroverride(v=pandp.51).aspx).
Now I have a **SimpleInjector** solution using a custom scope associating the scope of **PageNavigationService** with the _current page_. It works when there is only one "_current page_" at any time.

**Comment by brianlagunas** [comment]
Ahh, that's the issue then.  Having a singleton instance will cause you problems even with your changes.  If you keep your navigation paths very simple it may work for your needs, but you are messing with fire.

Also, the MSDN cods say "outdated" because it is no longer maintained by MS, but instead it is now open source.  The MSDN docs say the same thing about Prism, yet here we are :)
