### ISSUE TITLE
Unable to navigate away from page.

### ISSUE THREAD

**Issue by GrigorescuNicolae** [PrismLibrary/Prism#842]
*Use GitHub issues for __bugs in Prism and feature requests only__. If you have a question how to implement something using Prism or a bug in your app that might be related to Prism, please post your question on [StackOverflow](http://stackoverflow.com/tags/prism) (which we monitor as well).*

Please provide as much detail as possible (and feel free to remove unused properties):

### Package info

- Platform:Visual Studio 2013 ,
- Prism version: 6.2.0
- Xamarin version (if applicable):Xamarin for Visual Studio 4.2
- Windows 10 SDK version (if applicable):
- Other version info: ZXing.Net.Mobile for Forms 2.1.12

### Repro steps

Please describe the issue/request in detail.

  Hi , I'm developing a pretty basic scanning up ( as a complete beginner  )and i'm using xamarin forms , ZXing.Net.Mobile for Forms and also Prism and the MVVM design pattern .  I've managed to navigate around using the Prism.NavigationService with 1 exception that i simply can not figure out .
  If i navigate from any page to my scanning page everything it's fine , but i can't navigate from my scanning page (AFTER I'M DONE SCANNING) to anywhere else using the  NavigateAsync. 
(The "after i'm done scanning" it's important because if i add a button to the scanning page and bind that button to the same command and press the button before letting it scan everyting works fine ). I can use the GoBackAsync() method to get to my last page but after i'm in my last page i can't use NavigateAsync at all . In debug mode i get something like "Unknown member: NavigateAsync"

to make it easier to understand : 
What i want to achive : PageA  ->ScanningPage (done scanning)  -> PageB 
My current situation  : ScanningPageViewModel : NavigateAsync("PageB ") ->Does Nothing ,GoBackAsync ->take's me to PageA but then NavigateAsync("PageB ") (from PageAViewModel)  still does nothing (again , "Unknown member: NavigateAsync") 

 Here's my code for the ScanningPage.

Scanning Page:
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:forms="clr-namespace:ZXing.Net.Mobile.Forms;assembly=ZXing.Net.Mobile.Forms"
             xmlns:prism="clr-namespace:Prism.Mvvm;assembly=Prism.Forms"
             prism:ViewModelLocator.AutowireViewModel="True"
             x:Class="ReleaseAppSofteh.Views.PrismScanningPage">

  <StackLayout>

     <forms:ZXingScannerView 

              IsScanning="{Binding IsScanning }"

              IsAnalyzing="{Binding IsAnalyzing}"

              ScanResultCommand="{Binding NavigateCommand}"

              Result="{Binding Result ,Mode=TwoWay}"

              >

    </forms:ZXingScannerView>

  </StackLayout>

</ContentPage>

ScanningPageViewModel: 

 public class ScanningPageViewModel: BindableBase

    {

        private INavigationService _navigationService;
        private bool _isAnalyzing = true;
        private bool _isScanning = true;
        public ZXing.Result Result { get; set; }
        
       public bool IsAnalyzing
        {
            get { return _isAnalyzing; }
            set
            {
                _isAnalyzing = value; 
                OnPropertyChanged();
            }
        }

        public bool IsScanning
        {
            get { return _isScanning; }
            set
            {
                _isScanning = value; 
                OnPropertyChanged();
            }
        }

        public DelegateCommand NavigateCommand { get; private set; }

        public ScanningPageViewModel(INavigationService navigationService)
        {
            _navigationService = navigationService;
            NavigateCommand = new DelegateCommand(Navigate, CanNavigate);
        }

        private void Navigate()
        {
            var a = Result.Text;       //testing
            IsAnalyzing = false;
            IsScanning = false;
            _navigationService.NavigateAsync("Page3");
           //if i use __navigationService.GoBackAsync() it takes me back to my Page1 but then the navigation
           //from page1 stops working 
        }

        private bool CanNavigate()
        {
            return true;
        }
    }

Page 1 and Page2 are pretty much blank pages with 1 button in them for navigation (for testing) .And i have nothing in the code behind  in any of them . 
If I take out the ZXingScannerView from  XAML and replace it with a button and bind the button to the same command everything it's fine again . 
Have i done something wrong?

**Comment by bartlannoeye** [comment]
Pleases ask general questions on [StackOverflow](http://stackoverflow.com/questions/tagged/prism). We will answer them there.

**Comment by brianlagunas** [comment]
If it works without your ZXing.Net.Mobile for Forms code, then your problem probably lies with code related to your canning feature.
