### ISSUE TITLE
Add Bindable Async Support

### ISSUE THREAD

**Issue by feinstein** [PrismLibrary/Prism#843]
This is a feature request, I am not a specialist on Prism and so far I can't see this functionality on the library, so forgive me if this is already there and I just couldn't find it.

I read some articles about MVVM and Async programming by Stephen Cleary, they are great, specially the two first ones on [Async Data Binding](https://msdn.microsoft.com/en-us/magazine/dn605875.aspx) and [Async Commands](https://msdn.microsoft.com/en-us/magazine/dn630647.aspx). He exposes patterns that work very nicely with MVVM and provide binding not only for the results of the Async calls, but also for errors, exceptions and etc.

I think his code needs just a bit of refinement before it's included here (a default value selectable by the user in a secondary constructor for the `NotifyTaskCompletion` and the `AsyncCommand.CanExecuteChanged ` uses a crude logic for change notification), but still those are great patterns and I believe his solution will be a great addition to the library.

**Comment by brianlagunas** [comment]
We will not be adding any type of async command support any time soon.

**Comment by feinstein** [comment]
Out of curiosity what are the motives behind this reason? Compatibility? Testability? Lack of time?

**Comment by brianlagunas** [comment]
ICommand is not async, and will not be called from the XAML platform as async.  This is overcomplicating the simple concept of commanding, as well as the Prism API.  There are many ways to do async, and many existied before the async/await keywords.  The concept of an async ICommand is misleading at best.

**Comment by feinstein** [comment]
I understand your point, but after reading Stephen's blog post I can't find it complicated at all, well probably I don't have the experience yet to see all the outcomes of his implementation, but thanks anyways for your views on the subject.

**Comment by dvorn** [comment]
@feinstein See discussion here: https://github.com/PrismLibrary/Prism/issues/785#issuecomment-257943922

**Comment by feinstein** [comment]
@dvorn interesting, I happened to think on this at the same moment there were one open discussion on the subject. I will share my opinion there, thank you.
