### ISSUE TITLE
Possible Memory Leak on DelegateCommand

### ISSUE THREAD

**Issue by feinstein** [PrismLibrary/Prism#844]
I started to read more about ICommand implementations and some questions about the way things are implemented raised in my head, I pointed them out here: http://stackoverflow.com/questions/40586345/why-people-use-commandmanager-invalidaterequerysuggested-on-icommands .

One issue I learned is the memory leak issue regarding holding references to UI items that would have to be collected. That's the reason ICommand implementations use the `CommandManager` to raise the `CanExecuteChanged` instead of holding a reference to the UI controls. WPF expects only weak references to be used so everything might be properly garbage collected.

Investigating the `DelegateCommand` code here I can't see the use of e nither the `CommandManager` or `WeakReference` but just a regular event, that AFAIK will hold a strong reference to all the UI controls subscribed and won't let them be garbage collected.

I am new to ICommand WPF architectures, so I might be missing something, if that's the case, I apologize in advance.

**Comment by brianlagunas** [comment]
Please verify memory leaks before submitting an issue on a memory leak :)

**Comment by feinstein** [comment]
I am sorry, I should have, this was more a technical question than an issue as a matter of fact.

**Comment by brianlagunas** [comment]
There has only been one verified instance where a memory leak could occur and that is when binding to a command with a command parameter in a DataTemplate, but that is a WPF issue with the automation peer holding references and not a Prism or any other framework issue.

**Comment by feinstein** [comment]
Interesting. Brian, could you explain how `DelegateCommand` avoids problems with strong references? The absence of leaks goes against all the text I can find on the web.

**Comment by dvorn** [comment]
@feinstein Thank you for raising this question.  I should admit it slightly disturbs me too.

FYI: Prism had WeakDelegateManager in DelegateCommands since v2.0, but later it was removed in v6 because of the aggressive GC in Xamarin.

@brianlagunas I suggest to re-open this issue and have an investigation on WPF case until we have some confidence in it.

**Comment by dvorn** [comment]
To start the discussion:  this is where it all begins: https://blogs.msdn.microsoft.com/nathannesbit/2009/05/29/wpf-icommandsource-implementations-leak-memory/

**Comment by brianlagunas** [comment]
Definitely something worth looking into.  I won't have time for awhile though.

**Comment by brianlagunas** [comment]
This may also only be an issue with WPF, and not other platforms.  For example; the native Xamarin.Forms command does not use any weak handlers:

https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Core/Command.cs

This is why I had to remove weak handlers from DelegateCommand because they were immediately getting GC'd in XF.

**Comment by dvorn** [comment]
@brianlagunas Yes, and this is a (potential) problem.  If WPF indeed has this problem, we will need different implementations for WPF and Xamarin.

**Comment by feinstein** [comment]
I would like to volunteer but I don't think I have the knowledge of the inner WPF engine to trigger this behavior.

Can't this be tagged with a low priority or something like "needs investigation" so at least we can have a answer of how this works differently than what's documented on the Internet?

**Comment by feinstein** [comment]
Investigating this issue a bit I found another possible problem (a little one though and easy to fix I guess), but I would like to comment it here before opening another formal issue.

AFAIK the `CommandManager.InvalidateRequerySuggested()` should trigger a `CanExecute` reevaluation of all the commands in the UI, and looking at the `DelegateCommand` code I couldn't see how this was done, and after a simple test I could confirm it's not being done. 

Thomas Levesque [gist code](https://gist.github.com/thomaslevesque/13c3e69f6c5ae219b945fc07b75843fc) in [my StackOverflow question](http://stackoverflow.com/questions/40586345/why-people-use-commandmanager-invalidaterequerysuggested-on-icommands). Shows a simple fix for this. I think it lacks an unregister from the event on destruction though.

**Comment by brianlagunas** [comment]
I took what little free time I had tonight to look at this.  As I thought, there is no issue.  The WPF framework uses a WeakEventManager to hook into the CanExecuteChange notifications.  I also could not create a leak in a sample that my profiler could detect.

DelegateCommand does not use the CommandManager.  Not only is this WPF specific and will not work in a PCL, but it also is bad practice to use it in a DelegateCommand.

**Comment by dvorn** [comment]
>  As I thought, there is no issue. The WPF framework uses a WeakEventManager to hook into the CanExecuteChange notifications.

I came to the same conclusion.  Some details:

The [WPF ICommandSource Implementations Leak Memory!](https://blogs.msdn.microsoft.com/nathannesbit/2009/05/29/wpf-icommandsource-implementations-leak-memory/) blog was written in 2009 at the time of WPF 3.5.  Here is how a ButtonBase was subscribing to events at that time:
```csharp
        private void UnhookCommand(ICommand command) 
        {
            EventHandler handler = CanExecuteChangedHandler.GetValue(this); 
            if (handler != null)
            {
                command.CanExecuteChanged -= handler;
                CanExecuteChangedHandler.ClearValue(this); 
            }
            UpdateCanExecute(); 
        } 

        private void HookCommand(ICommand command) 
        {
            EventHandler handler = new EventHandler(OnCanExecuteChanged);
            CanExecuteChangedHandler.SetValue(this, handler);
            command.CanExecuteChanged += handler; 
            UpdateCanExecute();
        } 
```
`CanExecuteChangedHandler` here is a "light-weight dependency property" `UncommonField<EventHandler>`.
This indeed will leak, and the solution in Prism 2.0 was valid.  But now the ButtonBase is implemented differently (https://referencesource.microsoft.com/#PresentationFramework/src/Framework/System/Windows/Controls/Primitives/ButtonBase.cs,300):
```csharp
        private void UnhookCommand(ICommand command)
        {
            CanExecuteChangedEventManager.RemoveHandler(command, OnCanExecuteChanged);
            UpdateCanExecute();
        }
 
        private void HookCommand(ICommand command)
        {
            CanExecuteChangedEventManager.AddHandler(command, OnCanExecuteChanged);
            UpdateCanExecute();
        }
```
and CanExecuteChangedEventManager is based on WeakEventManager along the lines of mentioned blog post.

Thus, it looks like the problem of memory leaking in commands was solved by Microsoft and now it is only a historical issue.

**Comment by briannoyes** [comment]
This was my understanding as well - that the extra ref to the command holder was taken care of in WPF 4 so that it should not be a problem anymore, making the original WeakEventManager handling by Prism redundant.
