### ISSUE TITLE
Prism Navigation doesn't work

### ISSUE THREAD

**Issue by ShahriatHossain** [PrismLibrary/Prism#845]
On my Xamarin android MainActivity class I am using this code to navigate to one of my forms page:

var nav = new NavigationPage(new MyPclFormPage());
now it is redirecting to MyPclFormPage page but I have also snippet of code inside the MyPclFormPage's constructor:
private readonly INavigationService _navigationService;
public MyPclFormPage(INavigationService navigationService)
{
_navigationService = navigationService;
this.NavigateToDetail();
}
private async void NavigateToDetail()
{
await _navigationService.Navigate("DetailPage", null, false);

}

Now it seems that DetailPage constructor is firing but page is not navigating. Can you help me what I have done wrong?

**Comment by brianlagunas** [comment]
The navigation service does work :)

First off, you should not be adding any code to your Android MainActivity releated to navigation.  In a Xamarin.Forms application you handle all navigation within the PCL.

Secondly, to wrap your pages in a navigation page you simple need to register the built-in NavigationPage, or a customer navigation page, for navigation and then simply prefix you navigation uri with the navigation page.

Container.RegisterTypeForNavigation<MyNavigationPage>();

NavigationService.NavigateAsync("NavigationPage/MainPage");

You will never navigate in the ctor of a ViewModel.

**Comment by ShahriatHossain** [comment]
Actually I am receiving message from push notification on gcm listener on
my android project and redirecting to my pcl project.

**Comment by brianlagunas** [comment]
I'm sorry, I do not understand your scenario.  I would like to mention that the Prism INavigationService is not available in a XAM Page code-behind, so if you are trying to use it there it will not work.

**Comment by ShahriatHossain** [comment]
I am not using prism navigation in my code-behind code. What I am doing I am navigating from android MainActivity using this code var nav = new NavigationPage(new MyPclFormPage()); to my  MyPclFormPage which is the page of my pcl project or viewmodel and in this viewmodel's constructor I am trying to redirecting to another view model but I can see that next viewmodel's constructor is being working but not page is moving from current MyPclFormPage viewmodel to next viewmodel and here I am using prism navigation service.

**Comment by ShahriatHossain** [comment]
Well, I have sorted out my problem. I am creating new instance instead using App.Current.MainPage=new NavigationPage(new MyPclFormPage()); and this is working like a charm :)

**Comment by Dresel** [comment]
I was looking for something similar, the use case I have to implement is the following: _User receives a notification and when clicked should be redirected to a specific view_

Since notifications are implemented in the platform specific project and within a service (`GcmListenerService`), I'm using a `PendingIntent` with extras and overriding `OnNewIntent` within the MainActivity. There I had to access the NavigationService, which I did via

    ((PrismApplicationBase)Xamarin.Forms.Application.Current).Container.Resolve<INavigationService>();

I know this is against

> First off, you should not be adding any code to your Android MainActivity releated to navigation. In a Xamarin.Forms application you handle all navigation within the PCL.

but it was the only solution I found after quite some research.

@brianlagunas If you have some advice how to do it better, I would be very grateful.

**Comment by ShahriatHossain** [comment]
You can resolve it using dependency injection.

**Comment by Dresel** [comment]
Where should I inject what and how does this avoid navigation related code in the Android MainActivity?

**Comment by ShahriatHossain** [comment]
You can use dependency service and you can follow this link to get idea:
https://developer.xamarin.com/guides/xamarin-forms/application-fundamentals/dependency-service/

**Comment by ShahriatHossain** [comment]
This also can be resolved using messaging center:
https://developer.xamarin.com/guides/xamarin-forms/application-fundamentals/messaging-center/
