### ISSUE TITLE
[XF] INavigationService is not singleton and related issues

### ISSUE THREAD

**Issue by MadMan79** [PrismLibrary/Prism#846]
### Package info

- Platform: Android
- Prism version: 6.2 and 6.3, Unity

### Repro steps

As INavigationService is not singleton these lines set current page on another instance of UnityPageNavigationService:
```
var navService = Container.Resolve<INavigationService>(_navigationServiceName);
 ((IPageAware)navService).Page = page;
```

Which causes issues during subsequent GoBackAsync as **page** below points to wrong page:
`Page previousPage = GetOnNavigatedToTarget(page, useModalForDoPop);`

Also neither GoBackAsync nor new NavigationPageSystemGoBackBehavior are updating IPageAware.Page, which causes further navigation issues.

I plan to create a PR with the fix later, but wondering why INavigationService is not singleton ...

Vitaly

**Comment by brianlagunas** [comment]
The navigation service cannot be a singleton.  Navigation in XF is page dependent, meaning that each page is responsible for its own navigation stacks (both modal and non-modal).  You cannot have a singleton nav service in XF.

As for your other issue of "subsequent GoBackAsync", could you please elaborate on the scenario?  The IPageAware.Page should not be updated as the service must know about its associated page object.  Could you help me understand why you feel the IPageAware.Page should be updated and in what scenario this is needed?  Maybe even provide a sample app the reproduces your scenario.

**Comment by MadMan79** [comment]
Thanks, need to think about it and review my solution. Most likely the problem is that I use INavigationService from a singleton Navigator(INavigationService) helper class. Probably in XF world it should not be singleton.

**Comment by brianlagunas** [comment]
No, it can never be a singleton.  This is the nature of navigation in XF.  The XF navigation is specific to a page and cannot be abstracted out into a singleton.  I will close this for now.  IF you find that you are still having the same issue with GoBack, then I will reopen.  Just let me know what you find.
