### ISSUE TITLE
Single Process Model initialization

### ISSUE THREAD

**Issue by senkia** [PrismLibrary/Prism#847]
Hi,

I'm using the Prism.Unity framework for UWP in an application that can do background activity according the new single process model described here: [link](https://blogs.windows.com/buildingapps/2016/06/07/background-activity-with-the-single-process-model/#JSgg6jFYw6PdTppD.97)

Obviously when the app is launched in the background (the OnBackgroundActivated method is launched), none of the Prism initialization has been called (like creating the IoC container, registering services, ect.) so I did that manually by calling the CreateAndConfigureContainer method. It works great but when my app completed the background activity, the Suspending event is published so the OnSuspending method is called in PrismApplication. This method tries to access the not instantiated Navigation and SessionState services so I get a NullReferenceException. [link](https://github.com/PrismLibrary/Prism/blob/master/Source/Windows10/Prism.Windows/PrismApplication.cs#L512)

So my question is that, what would be the best way to initialize my app and the Prism framework when it's launched in the background? 

Thanks

**Comment by briannoyes** [comment]
Hi @senkia , thanks for bringing this to our attention. We are aware there are a number of activation scenarios we are not covering completely for UWP at this point, and want to try to get those all covered cleanly. If you could put together a small sample repro of this problem and send me a link where I can get to it I'll try to get a fix in there to cover this scenario.

Thanks
Brian

**Comment by brianlagunas** [comment]
Closing as no sample provided when requested in 2016
