### ISSUE TITLE
[XF] Autofac should resolve non-registered types as well

### ISSUE THREAD

**Issue by bartlannoeye** [PrismLibrary/Prism#859]
- Platform: XF
- Prism version: all upto 6.3.0-pre1

See https://github.com/PrismLibrary/Prism/issues/742#issuecomment-263822188

**Comment by brianlagunas** [comment]
had to revert because the PR broke a test

**Comment by bartlannoeye** [comment]
One should not code in notepad++ :)
Weird Autofac behavior, new PR on the way
