### ISSUE TITLE
Prism.Windows - hardware back button press is not firing the BackRequested event first

### ISSUE THREAD

**Issue by rsvsakthi** [PrismLibrary/Prism#867]
I have two pages in my application PageA navigates to PageB. In PageB, I am handling the BackRequested event to dismiss a popup (shown as a control) and not going back to PageA. I have specified e.Handled = true.

When the user is in PageB and presses back button on device, onNavigatedTo in PageA is getting executed first then it comes to BackRequested event. So I am not able to prevent the user from going back to PageA. 

Can you please let me know how to handle this without going to previous pages OnNavigatedTo?

Thank you,
Sakthivel R

**Comment by briannoyes** [comment]
I think the only way currently you could address that is by disabling the back button in PageB until it is willing to allow the navigation to proceed. The docs show a similar approach here:
https://msdn.microsoft.com/en-us/library/windows/apps/mt465734.aspx

We have actually had a long standing issue to try to address this:
https://github.com/PrismLibrary/Prism/issues/46

Unfortunately none of us has had the time to dig into addressing that one, which I think would address your scenario as well. 

We always welcome community PRs with a solution!

**Comment by Mr1Penguin** [comment]
Short-term solution is use IDeviceGestureService.GoBackRequested instead of SystemNavigationManager.GetForCurrentView().BackRequested. But PrismApplication class does not check e.Handled inside its OnGoBackRequested. I can create PR for it.

**Comment by rsvsakthi** [comment]
@Mr1Penguin, Thanks a lot for your contribution. Have you created PreRelease already? if yes, can you provide me the details?

Thank you,
Sakthivel R

**Comment by Mr1Penguin** [comment]
@rsvsakthi 
PR = Pull Request. And it's already merged with main branch (#1019).

**Comment by brianlagunas** [comment]
Closing this since it was fixed in PR #1019
