### ISSUE TITLE
Upgrading to Forms 2.3.3 introduces issues in UWP with NavigationPage & Platform Specifics

### ISSUE THREAD

**Issue by mackayn** [PrismLibrary/Prism#868]
In Forms 2.3.3 they introduced Platform Specific. Now by default when you add toolbar items in UWP they go on a bottom toolbar. This isn't the desired behavior for a lot of people so the platform specific API allows you to override this default behavior of toolbars etc, surface native controls etc.

### Package info

- Platform: UWP
- Prism version: 6.3
- Xamarin version (if applicable): 4.2.1.64
- Windows 10 SDK version (if applicable): 10580
- Other version info: Forms 2.3.3.170, tested on Lumia 650 hardware handset

### Repro steps

In our existing apps this approach works fine in App.xaml.cs

```
    public App()
        {
            InitializeComponent();

            var startPage = new HomePage();
            NavigationPage.SetHasBackButton(startPage, false);
            MainPage = new CustomNavigationPage(startPage);
            MainPage.On<Windows>().SetToolbarPlacement(ToolbarPlacement.Top);

        }
```

You cannot call SetToolbarPlacement in the page constructor in UWP and it can only be called once apparently (Application wide).

I can't see how to do this in a Forms Prism app as the root page is not publicly available which is understandable but we need some kind hook into the root page to call platform specific code.

**Comment by dansiegel** [comment]
If it's something you are setting this once in the application there would be nothing to stop you from:

```cs
protected override void OnInitialized()
{
    InitializeComponent();
    NavigationService.NavigateAsync( "MainPage?title=Hello%20from%20Xamarin.Forms" );
    MainPage.On<Windows>().SetToolbarPlacement( ToolbarPlacement.Top );
}
```

**Comment by mackayn** [comment]
Hi Dan,

Wasn't aware you could do that. Tested and it works fine.

Thanks for your help.

**Comment by mackayn** [comment]
Hi,

Sorry to reopen this but found an unwanted side effect of this approach. While the code below works fine when starting up the app it doesn't work when you reset the navigation stack.

```
 protected override void OnInitialized()
        {
            InitializeComponent();

            var setting = Container.Resolve<ISettingService>();
            var user = setting.GetSetting(SettingConstants.SettingToken);
            if (!Equals(user, null))
            {
                var navigationPage = "app:///MainNavigationPage/HomePage";
                NavigationService.NavigateAsync($"{navigationPage}?startup=OnInitialized");
            }
            else
            {
                var navigationPage = "app:///MainNavigationPage/LoginPage";
                NavigationService.NavigateAsync(navigationPage);
            }

            // Force windows toolbar to top (default is bottom on Forms 2.3.3)
            MainPage.On<Windows>().SetToolbarPlacement(ToolbarPlacement.Top);
        }
```

The user can sign out of the app and authenticate using different credentials, what happens in this scenario is the navigation stack is reset to the login page.

In the login ViewModel when you successfully authenticate the user is redirected to the main dashbaord again.

```
                    var navigationPage = "app:///MainNavigationPage/HomePage";
                    await _navigationService.NavigateAsync($"{navigationPage}?startup=OnInitialized");
```

The issue if the viewmodel obviously doesn't reference the app context and there's no way to call SetToolbarPlacement, unfortunately when you reset the navigation stack this preference is not retained for toolbar placement, the toolbar goes to the bottom again. Setting it in the page doesn't work.

This may be a Forms bug or a feature of platform specifics (I would have though you'd set it once) but I thought I'd raise it here before maybe creating a bugzilla and raising a support ticket.

Thanks.

**Comment by brianlagunas** [comment]
Unfortunately, this is not a Prism related issue.  Prism has no control over toolbar placement or how Xamarin implements this feature.   I will say that according to their documentation, you can set it in XAML:
```
<TabbedPage ...
            xmlns:windows="clr-namespace:Xamarin.Forms.PlatformConfiguration.WindowsSpecific;assembly=Xamarin.Forms.Core"
            windows:Page.ToolbarPlacement="Bottom">
  ...
</TabbedPage>
```
https://developer.xamarin.com/guides/xamarin-forms/user-interface/platform-specifics/consuming/

If it doesn't work as documented, I would consider it an XF bug and submit I to Xamarin.

**Comment by mackayn** [comment]
Hi,

As Brian recommends, to resolve this issue you can simply set the platform specific setting for toolbar placement in the main navigation page, that way you can reset the navigation stack and the toolbar won't move back to the bottom in UWP apps.

```
<?xml version="1.0" encoding="utf-8" ?>
<NavigationPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="Foobar.Views.MainNavigationPage"
             xmlns:windows="clr-namespace:Xamarin.Forms.PlatformConfiguration.WindowsSpecific;assembly=Xamarin.Forms.Core"
             windows:Page.ToolbarPlacement="Top"
             Title="MainNavigationPage">
</NavigationPage>
```
