### ISSUE TITLE
Not working nonmodal navigation from MasterPage of MasterDetailPage

### ISSUE THREAD

**Issue by Konrad4** [PrismLibrary/Prism#869]
When performing nonmodal navigation from the Master page of the MasterDetailPage current page is set to MasterPage and this causes InvalidOperationException with the following information:

```
Exception thrown: 'System.InvalidOperationException' in Xamarin.Forms.Platform.WinRT.DLL
Additional information: PushAsync is not supported globally on Windows, please use a NavigationPage.
```

Nonmodal navigation is initiated from the ViewModel which is assigned to MasterPage of the MasterDetailPage:
`await _navigationService.NavigateAsync("NavigationPage/MyItemsList", null, false);`

Quite ugly workaround it to set Page of the Navigation to MasterDetailPage 
`((IPageAware)_navigationService).Page = _applicationProvider.MainPage;`

With this line of code before navigation it works as expected.

**Comment by brianlagunas** [comment]
You cannot navigate non-modal unless you are inside of a navigation page.  So wrap your MasterDetailPage in a navigation page, and then it will work.

**Comment by Konrad4** [comment]
Thank you for very fast reaction :) 

Yes, this solves the problem of the exception but because IPageAware.Page is still set to MasterPage and not to the MasterDetailPage every time when the nonmodal navigation is performed there is a new instance of MasterDetailPage created so I still need to set explicitly ((IPageAware)_navigationService).Page to prevent that.

But maybe there is still some other problem with my code, anyway thanks for help :)

**Comment by brianlagunas** [comment]
If you are trying to update the Detail of the MasterDetailPage, then you have to navigate from the MasterDetailPageViewModel.
