### ISSUE TITLE
[Win10 UAP] ExtendedSplashScreen is not visible

### ISSUE THREAD

**Issue by hva** [PrismLibrary/Prism#87]
Extended splash screen should be displayed during ````OnLaunchApplicationAsync```` execution.
But now, application logo is displayed instead of splash screen.
Possible reason is running ````Window.Current.Activate()```` after ````OnLaunchApplicationAsync```` in ````PrismApplication```` class.

**Comment by briannoyes** [comment]
Closing as dupe to #126
