### ISSUE TITLE
[WPF] Custom Window in Interactivity

### ISSUE THREAD

**Issue by ProH4Ck** [PrismLibrary/Prism#874]
For a new project actually in development I found a limitation of Prism's interactivty: it lacks a custom implementation of default Window. 
In my project I'd like to build myself a **DefaultConfirmationWindow**, **DefaultNotificationWindow** or **DefaultWindow** but this is not possible. I can provide a custom Style but for my scenario this is not enought.
I work with thirdy part components and I'd like to use other Window implementations (for example a Syncfusion chromeless Window) to mantain the same visual experience all over my application.

What do you think about?

**Comment by dvorn** [comment]
@ProH4Ck You can derive from PopupWindowAction to create your own.  It has 
`protected virtual Window CreateWindow()` method which you can override.

As a side note, interactivity has a lot of problems, see #864.

**Comment by ProH4Ck** [comment]
Didn't notice virtual keywork: I solved implementing my custom PopupWindowAction. Thanks! 
I saw #864 right now: after Interactivity rework I could integrate sample with this beahvior...
