### ISSUE TITLE
Prism.Forms.Autofac UWP - ComponentNotRegisteredException (INavigationService)

### ISSUE THREAD

**Issue by rmenezes** [PrismLibrary/Prism#875]
### Package info

- Platform: UWP / Xamarin Forms
- Prism version: ¨. 6.2
- Xamarin version (if applicable): 2.3.3.175
- Windows 10 SDK version (if applicable): 10393
- Other version info:

### Repro steps

Hi, I'm trying to create a Xamarin.Forms application with Prism.Forms and Prism.Forms.Autofac using NavigationService. When I'm trying to run it on windows I receive the following error:

![01](https://cloud.githubusercontent.com/assets/1154679/21210398/d41c2204-c261-11e6-9d9b-aa10b8b2863a.PNG)

![02](https://cloud.githubusercontent.com/assets/1154679/21210401/dcc4b2e0-c261-11e6-9a75-cb5054ea3ebd.PNG)

**Comment by bartlannoeye** [comment]
This is a known bug, for the workaround see https://github.com/PrismLibrary/Prism/issues/742#issuecomment-263822188.

This should be fixed in https://github.com/PrismLibrary/Prism/pull/863. I'll ask @brianlagunas to push a new pre-release asap, but he's on holiday.

**Comment by brianlagunas** [comment]
Closing as this has been fixed.   Will be releasing in the next preview.
