### ISSUE TITLE
No SetRegionManager for 6.x?

### ISSUE THREAD

**Issue by nasheayahu** [PrismLibrary/Prism#876]
Just wanted to know if SetRegionManager & SetRegionName is included in this version of Prism as it was in 5.x. to be able to create a region in code?  If so, where is it located?

**Comment by briannoyes** [comment]
They are still Attached Properties on the RegionManager class as they always have been.

**Comment by nasheayahu** [comment]
I need to know what I'm missing because its not there according to this coding example:
![screenshot 10 mod](https://cloud.githubusercontent.com/assets/5845052/21273163/911995ee-c37f-11e6-96f4-ffc910dff170.png)

here's my code:
![screenshot 9 mod](https://cloud.githubusercontent.com/assets/5845052/21273182/9e4c6174-c37f-11e6-8da8-e1943592579d.png)

Object Browser has it located here:
![screenshot 11 mod](https://cloud.githubusercontent.com/assets/5845052/21273205/b3f1df18-c37f-11e6-8a63-92d425b7a08c.png)

But, no reference here:
![screenshot 8 mod](https://cloud.githubusercontent.com/assets/5845052/21273216/be5fb9ac-c37f-11e6-9916-6adc392cd843.png)

**Comment by dvorn** [comment]
Questions of this kind should be asked on Stackoverflow.

You are missing the difference between instance methods regionManager.SetRegionManager and static methods RegionManager.SetRegionManager.

**Comment by nasheayahu** [comment]
That doesn't make since when there is no mention of this in the tutorial and the example make you assume you can obtain it from the _interface_.  If the example is incorrect, why is it being used?

**Comment by brianlagunas** [comment]
The example is correct, your understanding of static vs instance methods are incorrect.  If you were to copy and paste the sample code and replace the region names it would work perfectly.  The sample code in no way even hints that you can set the region name via the interface.  Even the documentation above the code snippet (the one you pasted) specifically states "using the RegionManager **static method** SetRegionName...".

**Comment by nasheayahu** [comment]
Oh okay. had to read it again slowly this time, my bad..., thanks for helping me see the light...  :)

**Comment by brianlagunas** [comment]
The method was **not** obtained by the interface. It is a **static** method off of the RegionManager class.  I do not know how to make it more clear.  Maybe it will help if you renamed the region manager instance to something lose to help you understand why you don't understand.
```
IRegionManager someOtherNameThatYouPick= ServiceLocator.Current.GetInstance<IRegionManager>();
RegionManager.SetRegionManager(this.ActionContent, someOtherNameThatYouPick);
RegionManager.SetRegionName(this.ActionContent, "ActionRegion");
```

**Comment by nasheayahu** [comment]
Oh just drop it, I need to see a full code example on how this is used in this way.  Thanks for your replies...
