### ISSUE TITLE
Difference between WindowStartupLocation="CenterOwner" and CenterOverAssociatedObject 

### ISSUE THREAD

**Issue by feinstein** [PrismLibrary/Prism#88]
Just more a question than an Issue...but why the trouble to code:
```C#
if (this.CenterOverAssociatedObject && this.AssociatedObject != null)
{
	// If we should center the popup over the parent window we subscribe to the SizeChanged event
	// so we can change its position after the dimensions are set.
	SizeChangedEventHandler sizeHandler = null;
	sizeHandler =
		(o, e) =>
		{
			wrapperWindow.SizeChanged -= sizeHandler;

			FrameworkElement view = this.AssociatedObject;
			Point position = view.PointToScreen(new Point(0, 0));

			wrapperWindow.Top = position.Y + ((view.ActualHeight - wrapperWindow.ActualHeight) / 2);
			wrapperWindow.Left = position.X + ((view.ActualWidth - wrapperWindow.ActualWidth) / 2);
		};
	wrapperWindow.SizeChanged += sizeHandler;
}
```
Instead of just setting the `WindowStartupLocation` to `CenterOwner` ?

I guess this will center in respect of the View that holds the PopupActionWindow, not necessarily the Window that has the View, since there might be several Views in the Window. If this is the case, shouldn't PopupActionWindow add the possibilty to Center over the Owner Window as well?

**Comment by brianlagunas** [comment]
Good question.  This code was written a very long time ago, so I am not sure why it is that way.  This wouldn't be the first time we found some over complicated code.  I haven't looked at that code, but feel free to try it out and see what happens.  Though, I am not sure what the benefit of making this change would be.  We could be introducing risk for scenarios we aren't thinking about, which may cause issues for someone.

**Comment by feinstein** [comment]
Yes, I agree, it's more a question for purposes of learning. I am testing both options now, and I am getting some interesting results, I will post the answer once I complete the tests.

**Comment by feinstein** [comment]
So, I made some tests and `CenterOverAssociatedObject` will indeed center over the view, not the Window, the Associated Object is into. 

And setting `WindowStartupLocation` to `CenterOwner` won't work because it depends on the Window's `Owner` property, which in our case is always going to be null or we will have to go and find the AssociatedObject's Window, and set is as the `Owner` of our new Window, which is going to be too much trouble I guess.

So there's the reason.
