### ISSUE TITLE
Deep Linking causes wrong Title in navigation header (XF Android)

### ISSUE THREAD

**Issue by hardcodet** [PrismLibrary/Prism#880]
I used a string such as this one to navigate from one page to another through INavigationService:
`/WrapperNavigationPage/HomePage/Page1`

This gets me correctly to Page1, and when pressing the back button, to my HomePage. However, the navigation header of Page1 shows the Title of the HomePage.

### Package info

- Platform: XF Andorid
- Prism version: Latest
- Xamarin version (if applicable): 2.3.3
- Windows 10 SDK version (if applicable):
- Other version info:

### Repro steps

I have three pages:

* An empty navigation page
* A ContentPage (HomePage) with Title "Home"
* Another ContentPage (Page1) with Title "Foo"

Both HomePage and Page1 have their Title property set in XAML.

When I navigate to  /WrapperNavigationPage/HomePage/Page1 from another location in the app, Page1 is displayed, but the Title in the navigation header says "Home" instead of "Foo".

**Comment by hardcodet** [comment]
Additional observation: If I then move from Page1 to Page2 (so my navigation stack would be `/WrapperNavigationPage/HomePage/Page1/Page2`) and then press the back button to get back to Page1, the Title is correct.

**Comment by brianlagunas** [comment]
This is a known bug in Xamarin.Forms and has already ben reported with #765. We are just waiting for Xamarin to fix it.
