### ISSUE TITLE
Slack...

### ISSUE THREAD

**Issue by smedegaard** [PrismLibrary/Prism#881]
Hi,
I'm duplicating [issue 807](https://github.com/PrismLibrary/Prism/issues/807) to be sure you get updates on this.

I really don't see why you would have a problem opening a Slack channel where people can talk about Prism. 

As stated in 807, you don't even have to be active in there. 

Do what Shayne Boyer did with the [.NET Core channel](http://tattoocoder.com/aspnet-slack-sign-up/) using [Slackin](http://rauchg.com/slackin/). That way people can request an invite for them selves in seconds and you don't even have to lift a finger.

I really like Prism, so I hope you will reconsider this once again to make the community more active.

Merry Christmas,
Anders Smedegaard Pedersen

**Comment by brianlagunas** [comment]
I have setup a slack account, but I don't have time right now to automate the sign up process.

http://prismlibrary.slack.com

**Comment by jacob-maristany** [comment]
https://gitter.im/ would be a good alternative as well.  Also, you could always through a #prism channel on xamarinchat.slack.com.  There's already #mvvmcross, #mmvmlight and #framework-authors channels on there and a lot of user base.

**Comment by brianlagunas** [comment]
Actually, that might be a better option! Thanks for the heads-up.

**Comment by brianlagunas** [comment]
Please test this auto invite system for the slack channel.  

https://prismchat.herokuapp.com/

**Comment by brianlagunas** [comment]
Okay, I have created a new website to automate the process of signing up for the http://prismlibrary.slack.com/ channel.

You can use this website:  https://prismslack.herokuapp.com/

Let me know if this works.

**Comment by listepo-alterpost** [comment]
@brianlagunas how to sign up in the http://prismlibrary.slack.com/ now?

**Comment by S1r-Lanzelot** [comment]
@listepo-alterpost - https://github.com/PrismLibrary/Prism/blob/master/README.md#help-support-prism for access to Slack

**Comment by listepo-alterpost** [comment]
@S1r-Lanzelot thank you, I just wanted to know when there will be a stable version, I do not think that for this I need support

**Comment by NguyenTam** [comment]
@S1r-Lanzelot : I registered half hour ago. Should I get invitation message to slack? Should I click something in Patreon? Or should I just wait?
