### ISSUE TITLE
Lifecycle Events NavigateTo/From

### ISSUE THREAD

**Issue by ChristianRiedl** [PrismLibrary/Prism#883]
In **Prism for UWP** it is very comfortable that **Suspend/Resume** calls the **NavigateFrom/To** function of the current view. I use this functions to initialize/end for example some server communication.
In **Prism for Xamarin Forms** the behavior is different. NavigateFrom/To is not called.
Can you imagine to add this functionality to Prism.Forms ? I think most developers would expect 
that NavigateFrom/NavigateTo is called when the app suspends/resumes.

**Comment by brianlagunas** [comment]
@ChristianRiedl MS got it wrong.  I do not believe suspending and resuming are navigation actions.  They are app lifecycle events.  Luckily, in the latest codebase I have added a new IApplicationLifecycle interface that will allow VM's to respond to OnSleep and OnResume app events.  I will be dropping another preview within the next few weeks.
