### ISSUE TITLE
Could not load file or assembly System.ComponentModel.Annotations

### ISSUE THREAD

**Issue by markti** [PrismLibrary/Prism#884]
I am receiving a runtime error when the ValidateProperties method is invoked on an instance of a class that inherits from ValidatableViewModelBase .

Please provide as much detail as possible (and feel free to remove unused properties):

### Package info

- Platform: Windows 10 x86
- Prism version:     "Prism.Core": "6.2.0", "Prism.Windows": "6.0.2",
- Xamarin version (if applicable):
- Windows 10 SDK version (if applicable): MIN: 10586, Target: 14393
- Other version info:

### Repro steps

An exception of type 'System.IO.FileLoadException' occurred in System.Linq.dll but was not handled in user code

Additional information: Could not load file or assembly 'System.ComponentModel.Annotations, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

**Comment by bartlannoeye** [comment]
Can you try to update:
- Prism packages to 6.3.0-pre1
- Microsoft.NETCore.UniversalWindowsPlatform to 5.2.2

and see if the problem still persists? It looks like 6.0.2 still depends on System.ComponentModel.Annotations 4.0.10 (probably UWP 5.1.0).

**Comment by brianlagunas** [comment]
@markti Can you please give us an update?

**Comment by brianlagunas** [comment]
I'm going to assume your issues is resolved.  If not, just let us know and we can reopen.

**Comment by rangav** [comment]
By Installing Nuget package System.ComponentModel.Annotations resolved the issue for me.
