### ISSUE TITLE
UWP documengtation or tutorials

### ISSUE THREAD

**Issue by mister-giga** [PrismLibrary/Prism#885]
All I can find is widnows 8.1 Universal or Xamarin's UWP(With ios and droid) tutorials and documentations.
I cant find any tutorials or documentations of how to use Prism specifically for UWP. Are there any resources at all?

**Comment by bartlannoeye** [comment]
Prism for UWP is a port from 8.1, so most docs are still relevant. We haven't found time to update/rewrite them yet. So except for a few blog posts (best series is the one from Matteo's [blog](http://blog.qmatteoq.com/prism-and-universal-windows-app-the-basic-concepts/)), you'll have to work with the 8.1 docs.
