### ISSUE TITLE
[XF] Prism Navigation when using SlideOverKit

### ISSUE THREAD

**Issue by DotSync** [PrismLibrary/Prism#886]
I have a working Xamarin.Forms Prism app. As soon as I integrate the SlideOverKit to use the right slide menu it breaks. When you run the app it executes NavigationService.NavigateAsync("MainPage"); but does not actually navigate there.

Steps to reproduce: Create Xamarin.Forms Prism App from Xamarin Prism Template pack and use the above code.

Attached is a basic sample project that has the issue.

Any Idea how to solve this or a work around?
[PrismTest.zip](https://github.com/PrismLibrary/Prism/files/681755/PrismTest.zip)

**Comment by brianlagunas** [comment]
This is not an issue with Prism.  This is an issue with SliderOverkit.  I would suggest contacting the SlidOverkit support.

**Comment by DotSync** [comment]
Thanks, I'll do that.
