### ISSUE TITLE
Determine navigation direction in VM

### ISSUE THREAD

**Issue by build-ninja** [PrismLibrary/Prism#887]
- Platform: Windows
- Prism version: 6.2

There is currently no means to determine what the direction of navigation is via either NavigationContext or NavigationParameters. RegionNavigationEventArgs class used in the Navigation events does not contain this information either. 

A parameter was added to the NavigationParameters for Xamarin. I am requesting similar support here for PRISM desktop.

**Comment by bartlannoeye** [comment]
Do you mean UWP or WPF ?

**Comment by brianlagunas** [comment]
Prism region navigation in WPF does not have the concept of a hardware/software back button.  Essentially, it is not possible for the system to navigate your app backwards without an explicit call to GoBack.  If you need a parameter for your app to know which direction you are going, you can manually add it to the NavigationParameters.
