### ISSUE TITLE
[XF] DryIoc not resolving concrete types

### ISSUE THREAD

**Issue by dansiegel** [PrismLibrary/Prism#889]
As the example provided by @brianlagunas in #811 shows, the ViewModel is not being resolved by the container and is thus never being set. 

Possible fixes:
1) update the ```DryIocExtensions``` so that we explicitly register the ViewModel
2) update the Rules so that in addition to resolving unknown types with the XF ```DependencyService``` we add automatic resolution for concrete types.

**Comment by brianlagunas** [comment]
Yeah, I just discovered this myself. I say we do the automatic resolution for concrete types just like we did for AutoFac. Do you know how to do this in DryIoC?

**Comment by dansiegel** [comment]
I'll try to get the PR in this afternoon

**Comment by brianlagunas** [comment]
let me ask you this... is there a performance benefit to manually registering the VM like we do with the View vs. automatically for all concrete types?

**Comment by dansiegel** [comment]
I'm can't really say with 100% certainty. I would say if we want the behavior to be have automatic concrete type resolution we fix that first and if there are issues later with performance we can look at adding explicity ViewModel registration.

**Comment by brianlagunas** [comment]
Agreed!

**Comment by AlesDo** [comment]
To do auto concrete type resolution in DryIoc you just add the rule when creating the container like this:
new Container(Rules.Default.WithAutoConcreteTypeResolution());

**Comment by dansiegel** [comment]
@AlesDo I'm aware of the rule. Unfortunately for XF we also have to try to fall back to the Xamarin Forms Dependency Service which breaks the built in ```WithAutoConcreteTypeResolution```.

**Comment by brianlagunas** [comment]
@dansiegel well, doesn't the XF DependencyService rely on an interface the lives in the PCL, and the interface is what is used to resolve the object?

**Comment by dansiegel** [comment]
@brianlagunas yes the Dependency Service is generally used to resolve the implementation for a specified interface, and while you would think simply adding Concrete Type Resolution wouldn't interfere there is something in the implementation that caused it not to work for some reason.

**Comment by brianlagunas** [comment]
Yeah, that's weird and a little annoying.

**Comment by dadhi** [comment]
By fallback to Dependency Service, do you mean if concrete type or any type could not be resolved, then DryIoc resolution should return null?

**Comment by brianlagunas** [comment]
There is a rule that says if DryIoC can't resolve the type then try using Xamarin.Forms DependencyService

https://github.com/PrismLibrary/Prism/blob/master/Source/Xamarin/Prism.DryIoc.Forms/Extensions/UnknownServiceResolverRule.cs

According to @dansiegel, by adding the WithAutoConcreteTypeResolution it breaks this behavior.  Even though the XF DependencyService relies only on an interface and not a concrete class to resolve.

**Comment by dansiegel** [comment]
@dadhi looking at the [DependencyServiceResolverRule](https://github.com/PrismLibrary/Prism/blob/master/Source/Xamarin/Prism.DryIoc.Forms/Extensions/UnknownServiceResolverRule.cs#L17) I had tried altering it as follows:

```cs
DependencyServiceResolverRule = Rules.Default.WithUnknownServiceResolvers(...).WithAutoConcreteTypeResolution();
```

and also

```cs
DependencyServiceResolverRule = Rules.Default.WithAutoConcrteTypeResolution().WithUnknownServiceResolvers(...);
```

either way resulted in exceptions being thrown.

**Comment by dadhi** [comment]
By quick look at source I guess that you may override `PrismApplication.CreateContainerRules()` and return 

    Default.Rules
        .WithAutoConcreteTypeResolution()
        .WithUnknownServiceResolvers(
             UnknownServiceResolverRule.DependencyServiceResolverRule.UnknownServiceResolvers);

Actually it would've been easy if `UnknownServiceResolverRule` provided just `UnknownServiceResolver` delegate, and not the fully constructed `Rules`, making it less composable.

Also impl may be simplified, but I need to check.

Btw. the fallback won't be possible if concrete type itself cannot be resolved, e.g. due missing dependency. I will play with it.. At the end `AutoConcrete...` rule is just a sugar. You may write your own.

**Comment by dadhi** [comment]
@dansiegel Missed your answer. 

What exceptions were thrown in the 2nd case? 1st is wrong.

**Comment by brianlagunas** [comment]
@dadhi DryIoc is completely broken for Xamarin.Forms.  It won't resolve concrete types using the WithAutoConcreteTypeResolution rule, you must register everything. If you register an XF navigationPage it completely crashes the app.  App won't even run.  I afraid I am going have to drop support for DryIoc if I can't get this to work.

**Comment by dadhi** [comment]
I would like to help, but I need to know the context more.
 
- What version of DryIoc is used, what platform is referenced?
- Any exceptions when it is crashing?
- Did you try source package to debug?
- Did you try to call `container.Validate` to check for possible errors?

**Comment by brianlagunas** [comment]
* Using v2.10.1. Tries upgrading, but still didn't work.
* Exception occurs when I try to resolve a concrete type no matter what rule I add to it.  If I simply try to register a NavigationPage the app never starts, it just shows a white screen and the MainPage is never created.
* No. I don't have time to debug source.
* No, I haven't tried that. I do not use DryIoc.  It was a contribution from the community. I am writing a VS Project Template for it to include in the Prism Template Pack, but when I create the project it won't work so I can't include it.

I have attached a bare bones file -> new
[PrismDryIocApp2.zip](https://github.com/PrismLibrary/Prism/files/869654/PrismDryIocApp2.zip)

**Comment by brianlagunas** [comment]
Okay, we have narrowed down the NavigationPage issue:

Unspecified how to select single constructor from type Xamarin.Forms.NavigationPage with multiple public constructors:
Void .ctor();
Void .ctor(Page)

Apparently the XF NavigationPage has two ctors.  How can I tell it that I want the default ctor?

The other issue with concrete types is not what it seems to be.  The person that implemented this code may have made a mistake.

What needs to happen is when a View is created a ViewModel is created automatically.  When the VM is created, we want to inject a precreated navigation service into the ctor, but only if it is being asked for.  Other wise create the ViewModel and inject anything that it is asking for, or use the dfeult ctor is it is not asking for anything.  I am not familiar with DryIoc maybe you can spot the issue here:  https://github.com/PrismLibrary/Prism/blob/master/Source/Xamarin/Prism.DryIoc.Forms/PrismApplication.cs#L117

**Comment by brianlagunas** [comment]
@dadhi Yes, this is definitely an implementation issue.  The author of this obviously didn't test this is a real app.

Use the sample app I provided and modify the MainPageViewModel by adding this to the ctor:
```
		public MainPageViewModel(INavigationService navigationService)
		{

		}
```

If you add this in the RegisteredTypes method, you will see that an instance of MainPageViewModel is not being created with an INavigationService parameter.  This is actually throwing an exception.

```
				var page = new MainPage() { Title = "Test" };
				var vmType = typeof(MainPageViewModel);

				var navigationService = CreateNavigationService(page);
				// Resolve type using the instance navigationService
				var resolver = Container.Resolve<Func<INavigationService, object>>(vmType);
				var result = resolver(navigationService);
```
How can we create an instance of the MainPageViewModel and inject the INavigationService instance, but only if the parameter exists.  If the param doesn't exsts it should just create the VM, resolve any other services if there are any, and return the new ViewModel class.

**Comment by dadhi** [comment]
Thank you, I have reread the whole thread and will try to adapt AutoConcreteTypeResolution for this case. Will use your attached project to check.

**Comment by dadhi** [comment]
Wow, thanks for more info, this is much easy now. I will check from here.

**Comment by dadhi** [comment]
The dumb solution may be something like this:

    var resolver = Container.Resolve<Func<INavigationService, object>>(vmType, ifUnresolved: IfUnresolved.ReturnDefault);
    if (resolver == null)
        Container.Resolve(vmType);
    ...

Hope this'll work, cause I could not test it at the moment. But more sophisticated way should exist,.. thinking.

**Comment by dadhi** [comment]
ViewModels have multiple ctors?

**Comment by dadhi** [comment]
Ok, ignore my prev suggestion with ReturnDefault. Here is how you can do it https://dotnetfiddle.net/9gIHH3

Sorry for formatting, written from phone.

- `B` is your INavigationService.
- `A` is view model
- replace B with C in A constructor, and container will select the default one, because C is not found.

For the moment forgot about `Container.WithDependencies` feature, did it to match Autofac functionality, where you may pass some args into Resolve.

**Comment by brianlagunas** [comment]
We cannot use that approach.  Each instance of a ViewModel needs to have a different instance of the INavigationService injected which must have other properties set at runtime.  So we cannot do this at the container level.  This injection really is ViewModel specific.

This is how Autofac does parameter injection:

https://github.com/PrismLibrary/Prism/blob/master/Source/Xamarin/Prism.Autofac.Forms/PrismApplication.cs#L53

This is how Unity does it:

https://github.com/PrismLibrary/Prism/blob/master/Source/Xamarin/Prism.Unity.Forms/PrismApplication.cs#L27

We need a way to pass the specific override at the time of resolve.  Unfortunately, if we can't achieve a dynamic override, then I have to drop support for DryIoc.

**Comment by brianlagunas** [comment]
This SO question is what we need to achieve.  It was marked as an answer, but it does not work:

http://stackoverflow.com/questions/37431451/override-certain-implementation-when-resolving-a-dependency

**Comment by dadhi** [comment]
As I said `WithDependencies` was made to cover for Autofac `Resolve(parameters)`:

ViewModelLocationProvider.SetDefaultViewModelFactory((view, type) =>
            {
                var page = view as Page;
                if (page != null)
                {
                    var navService = CreateNavigationService(page);
                    return Container.WithDependencies(
                        Parameter.Of.Type<INavigationService>(_ => navService))
                        .Resolve(type);
                }
                return Container.Resolve(type);
            });
        }

Mmm, regarding difference of nav services at runtime, what does it mean? how are they different. Cause I believe nav service should be just injected into vm. May be it should be registered with some condition based factory, method or with decorator..

**Comment by brianlagunas** [comment]
It seems that `Container.Resolve<Func<INavigationService, object>>(vmType);` doesn't like the `object` generic in the Func.  If I hard code it to the `MainPageViewModel` type it will work.  Unfortunately, we can't do this as we won't know the type until runtime.  So there is no way for use to pass the ViewModel type into the Func as a generic.

**Comment by dadhi** [comment]
Check my answer in prev comment. Seems like we typed in parallel.

**Comment by dadhi** [comment]
Regarding 
    var resolver = 
    Container.Resolve<Func<INavigationService, MainPageViewModel>>(vmType);

it is not clear why it works. It should not differ from object bazed, otherwise this is a bug.

Can you provide complete context, how many and what ctors VM has? I need a min repro sample.

**Comment by brianlagunas** [comment]
Just use the sample I provided already, and follow the instructions for adding the nav service to the MainPageViewModel ctor.

This is the same app I am using

**Comment by dadhi** [comment]
Reproduced! Will try to fix soon. 

Meanwhile you may try my suggestion with `WithDependencies` from couple of comments above, which is fully correspond to provided Autofac sample.

**Comment by brianlagunas** [comment]
@dadhi We are making progress.  We have a PR that seems to work so far.  Looks like the WithDependencies was what we needed.

https://github.com/PrismLibrary/Prism/pull/997

We just need a workaround for the NavigationPage object, and we are set.  I'll push an update to Prism.DryIoc and then publish my new DryIoC templates in the Prism Template Pack.

**Comment by dansiegel** [comment]
I threw in a fix for the NavigationPage issue as well in PR #997. It just needed a single line updated in the Registration extensions... This should also help any other cases we aren't currently aware of...

**Comment by dadhi** [comment]
Cool!

Btw, I have [project](https://bitbucket.org/dadhi/dryioc/src/20b6ed1354bf799f3fec1547b4f1741afbfdc722/Extensions/DryIoc.Syntax.Autofac/?at=default) in progress wich wraps DryIoc with Autofac API surface.. So may be, this one will rule them all.. future DryIoc integrations :-) kidding

**Comment by brianlagunas** [comment]
@dadhi thanks for the help! I was under pressure to ship this weekend. So we had to fix or drop :)

Looks like we fixed it with your help and guidance. I've heard good things about DryIoc, but I haven't had time to try it.  I am looking for a new "standard" to replace my favorite Unity container so I may give DryIoc a try.

**Comment by dadhi** [comment]
Hey, it is a bit late but here is released DryIoc 2.10.4 with fixes for original Func issue and more: https://www.nuget.org/packages/DryIoc.dll/2.10.4

**Comment by rasmuschristensen** [comment]
This might still be an issue in latest XFPrism. I'm getting this error 

DryIoc.ContainerException: Implementation type is not specified when using automatic constructor selection: Object {ServiceKey="RootPage=selectedTab=ProfilePage", ReturnDefault}

When navigating in OnInitialized using tabbedpages

dryIoc 2.12.5 and prism 7.0.0.269-pre in netstandard 2.0

**Comment by brianlagunas** [comment]
@rasmuschristensen This has already been fixed in the latest CI build on MyGet, and will be in the final release when we RTM next week.

**Comment by rasmuschristensen** [comment]
Sounds great. I think the issue actually was that I forgot the "?" after the tabbedpage in the path. Now everything seems to work perfectly! Looking forward to RTM it's a great fx
