### ISSUE TITLE
Calculated Property Dependencies

### ISSUE THREAD

**Issue by allanrsmith** [PrismLibrary/Prism#89]
I am not sure if this is the correct terminology but I am looking for a similar way to accomplish what is described in here: http://www.codeproject.com/Articles/375192/WPF-The-calculated-property-dependency-problem

I don't believe Prism has anything like this but would love to hear from the community if it is desired and/or a better implementation.

**Comment by brianlagunas** [comment]
This is not something Prism addresses, but something like Fody does.

https://github.com/Fody/PropertyChanged

**Comment by kobush** [comment]
My collegues Kevin Stumpf and Danny Warren developed PDFx framework to address this.
http://pdfx.codeplex.com/
http://blogs.interknowlogy.com/2013/05/17/pdfx-property-dependency-framework-part-i-introduction-2/
