### ISSUE TITLE
Need project template other than Unity

### ISSUE THREAD

**Issue by nuitsjp** [PrismLibrary/Prism#890]
Now, the Unity project seems to be not working.

[https://github.com/unitycontainer/unity](https://github.com/unitycontainer/unity)

- Latest version was released in October 2015  
- Latest commit is March 2016  
- No maintainer response to issue

For this reason, I think that it is better to prepare a project template other than Unity.

**Comment by nuitsjp** [comment]
Is this complete? PR is better to merge here?

**Comment by brianlagunas** [comment]
I will leave this open until I have merged the PR's.  I don't have time to review right now, but I will review as soon as I can.  Thanks for all your help!

**Comment by brianlagunas** [comment]
I merged the WPF templates. I should have time next week to review the Xamarin.Forms templates.

**Comment by nuitsjp** [comment]
Yes, Thank you for your hard work.

**Comment by davidtavarez** [comment]
Some documentation about Unity vs Ninject vs Drylok?

**Comment by brianlagunas** [comment]
We do not provide documentation for the DI container projects.

**Comment by dansiegel** [comment]
@davidtavarez Prism works effectively the same regardless of DI containers. Extensions provided by Prism for each DI container should generally have the same signatures so the only changes you would see would have to do with the actual DI container and how you might register your unique services. Your best bet for information on any DI container will always be the docs for the DI container you want to use.

**Comment by brianlagunas** [comment]
A big thank you to @nuitsjp for the great work on these templates.
