### ISSUE TITLE
Shell /Different Frame for Navigation UWP

### ISSUE THREAD

**Issue by JaggerJo** [PrismLibrary/Prism#894]
## Problem
I need to create a shell for my application that does not change which contains the frame that should be used to change the apps content. I tried this (code is below), but get a NullReferenceException because of the call order.

Is there an easy way to archive this ?
```
sealed partial class App : PrismUnityApplication
{
        protected override UIElement CreateShell(Frame rootFrame)
        {
            return new Views.ShellView();
        }

        protected override INavigationService CreateNavigationService(IFrameFacade rootFrame, ISessionStateService sessionStateService)
        {
            var frame = (Shell as Views.ShellView).ContentFrame;
            var adapter = new FrameFacadeAdapter(frame, EventAggregator);
            var navigationService = OnCreateNavigationService(adapter) ?? new FrameNavigationService(adapter, GetPageType, sessionStateService);
            return navigationService;
        }
        ....
}
```

**Comment by boodoolak** [comment]
Maybe this can help you

In App.xaml.cs
       
    protected override UIElement CreateShell(Frame rootFrame)
        {
            var shell = Container.Resolve<AppShell>();
            shell.SetContentFrame(rootFrame);
            return shell;
        }

In AppShel.xaml.cs

        public void SetContentFrame(Frame frame)
        {
            RootSplitView.Content = frame;
        }

In AppShell.xaml
            
    <SplitView x:Name="RootSplitView">
        <SplitView.Content>
            <Frame x:Name="ContentFrame" />
        </SplitView.Content>
    </SplitView>

**Comment by JaggerJo** [comment]
![image](https://cloud.githubusercontent.com/assets/13090415/21823722/af971210-d77c-11e6-817e-9b7a39fd565c.png)

works as described above. Thanks
