### ISSUE TITLE
Unable to go back during OnNavigatedTo

### ISSUE THREAD

**Issue by julciane** [PrismLibrary/Prism#905]
Hi all,
I'm using Prism Windows 10.
I'm facing this navigation scenario:
1-) Open my app
2-) Navigate to CategoriesPage (this page contains a list of categories)
3-) Select one category will trigger NavigateTo CategoryDetailPage
4-) CategoryDetailPage has some items
5-) Select one item will trigger ItemDetailPage
At this point we have a custom event that cause Item not to be available, so we have to go back in the navigation stack. We use goBack() method, so we are redirected to CategoryDetailPage.OnNavigatedTo method. 
My problem is that CategoryDetailPage will not be available if Category has only one item (that has been removed), so I want to go back to to CategoriesPage.

**Constraint:** we can access ItemDetailPage from many other flows, so we cannot redirect to CategoriesPage from ItemDetailPage.OnNavigatingFrom (){ navigationService.Navigate("CategoriesPage", null) }  because we don't know who is the previous page.

- I've tried to add a goback inside (**didn't work**)
 `CategoryDetailPage.OnNavigatedTo(){ if(!isCategoryAvailable) {goBack();}}`

- I've tried to navigate to CategoriesPage  (**didn't work**)
`CategoryDetailPage.OnNavigatedTo(){
    if(!isCategoryAvailable) {
       navigationService.Navigate("CategoriesPage", null);
    }}`

Is navigation (navigationService.goBack and navigationService.Navigate) supported during OnNavigatedTo and OnNavigatingFrom event?
Is there any way to access Prism backStack in order to know who is the previous page?

Best regards,
J.

**Comment by bartlannoeye** [comment]
This is a shortcoming in UWP instead of Prism. You can't navigate in the OnNavigatedTo eventhandler directly. You can however use the Dispatcher to work around this:

Frome code behind:

    Dispatcher.RunAsync(CoreDispatcherPriority.Low, () => Frame.GoBack();

From viewmodel (you might want to put the dispatcher access in a helper service):

        public override void OnNavigatedTo(NavigatedToEventArgs e, Dictionary<string, object> viewModelState)
        {
            base.OnNavigatedTo(e, viewModelState);
            Window.Current.CoreWindow.Dispatcher.RunAsync(CoreDispatcherPriority.Low, () => _navigationService.GoBack());
        }
