### ISSUE TITLE
Navigating from within OnNavigatingTo ends up with page I'm coming from

### ISSUE THREAD

**Issue by hardcodet** [PrismLibrary/Prism#906]
### Package info

- Platform: XF 2.3.3
- Prism version:  December 2016

### Repro steps

I'm seeing weird navigation behavior in `OnNavigatingTo`. Workflow:

* I start at **//HomePage**, navigating to **//HomePage/EditorPage**
* From **//HomePage/EditorPage**, I invoke GoBackAsync in order to pop **EditorPage**
* This invokes `OnNavigatingTo `in **HomePage**
* From there, I want to navigate immediately to page **DetailsPage** (without the user noticing):

```
        public override void OnNavigatingTo(NavigationParameters parameters)
        {
            var queryResults = parameters.TryGetParameter<RideQueryDto>();
            if (queryResults != null)
            {
                //immediately forward to the details page
                NavigationService.NavigateAsync(ViewId.DetailsPage, queryResults);
            }
        }
```

What I'm seeing now is that the desired **DetailsPage** (or at least its navigation header) quickly flashes up, and and is then replaced by the **EditorPage**. So I end up back on **//HomePage/EditorPage**, the page that I just popped.

If I trigger the same navigation code manually after the HomePage was loaded (e.g. through a button tap), everything works as expected and I end up at **//HomePage/DetailsPage**.

I can imagine that this form of navigation is not allowed. The outcome however is quite surprising ;)

Thanks for the clarification!

**Comment by brianlagunas** [comment]
This is expected.  OnNavigatingTo is execute prior to the navigation back to your HomePage.  When OnNavigatingTo is fired navigation has not started yet.  So before you navigate to the HomePage, you are navigating to DetailsPage, so this Page will now be navigated to first.  It a simple order of operations.  Do not navigate in the OnNavigatingTo.

Honestly, your navigation scheme doesn't make any sense to me.  If I'm a user and click a button that calls GoBackAsync, I would not expect to see a page that I never went to.  I would expect to see the previous HomePage.  If I click something on the EditorPage to show details, I would expect to navigate to another page and now have three pages in my navigation stack.

**Comment by hardcodet** [comment]
That was quick! Thanks for the clarification Brian.

As for the workflow: I simplified the example. The user doesn't click anything that says "back", but simply saves some edits, and I don't want the editor in the navigation stack after that. The editor page can be invoked from a number of places, so the simplest thing was to just pop it so far.

I can inject the desired navigation request (go back or go to //HomePage/DetailsPage) into the EditorPage though, that should be fine.

**Comment by brianlagunas** [comment]
You could also use an absolute URI to reset the navigation stack.  If I could understand the scenario better, I may be able to add a feature to support it.

**Comment by hardcodet** [comment]
Yes, absolute URIs is where I went to.

If I think of that in terms of a generic scenario: That would be like working with relative paths in order to not reset the stack parents. So instead of going to //ROOT/NEWTARGET, I would be going to ../NEWTARGET, which would basically pop the current view and attach NEWTARGET to wherever I am in the stack, but not touch the parent pages.

**Comment by brianlagunas** [comment]
Hmmm... that's an interesting idea.  I'm not sure how feasible that would be to actually implement, as it would be quite complex, but I will play around with it.
