### ISSUE TITLE
Unity container is null OnBackgroundActivated

### ISSUE THREAD

**Issue by eraser85** [PrismLibrary/Prism#907]
Hi,
I'm creating an UWP app using Prism 6.3.0-pre1 which implements the Repository pattern to retrieve some data from the internet, cache it locally and then update a live tile every hour.

Thing is, when the app is launched by the OS via OnBackgroundActivated, the Unity Container object is null so that trying to resolve repositories and services fails, crashing the app.

Things can be made to work by calling CreateAndConfigureContainer() and registering all the types like ones usually does in OnInitializeAsync() but seems pretty hack-ish to me. 

### Package info

- Platform: UWP
- Prism version: 6.3.0-pre1
- Windows 10 SDK version (if applicable): 14393

### Repro steps

Original discussion on StackOverflow: http://stackoverflow.com/questions/39923159/timetrigger-not-firing-in-single-process-uwp-scenario
Link to the repro: https://github.com/eraser85/LiveTileTestRepro

Run the "LiveTileTestSimple" and press the pin button on the bottom of the app: the live tile gets updated every 15 minutes.

Run the "LiveTileTestPrism" and press the pin button on the bottom of the app: the live tile doesn't get updated if the app is closed.

**Comment by bartlannoeye** [comment]
Thanks for the repro, we'll look into it asap.

**Comment by brianlagunas** [comment]
This should not be an issue now with the Template10 merge. If it is, let us know.
