### ISSUE TITLE
Destroy not invoked when resetting the stack with absolute navigation?

### ISSUE THREAD

**Issue by hardcodet** [PrismLibrary/Prism#909]
I implemented `IDestructible.Destroy ` in order to perform cleanup operations on my view models, most notably to unsubscribe my message listeners. This seems to work fine when popping my views off the navigation stack, but not if I reset navigation with an absolute URI (e.g. _//Root/Homepage_). Is this the intended behavior?

Thanks,
Philipp

**Comment by brianlagunas** [comment]
This is a known issues and I already captured this when I first wrote the feature as something I need to address.  See #862

**Comment by hardcodet** [comment]
I see. I don't know the prism internals, but I assume you don't have an abstraction of the current navigation stack? Otherwise, the fix might be easy and I could quickly do a PR if you point me in the right direction.
