### ISSUE TITLE
[PRISM] Retrieve data when tab page is active (tabbed page)

### ISSUE THREAD

**Issue by riandesign** [PrismLibrary/Prism#911]
Hi all.

Does anyone know how to detect when a tab page is active?
In my case, I need to update my ObservableCollection when user access the tab page.

I followed the example of the page below, but for some reason, it didn't work for me.
[https://github.com/qmatteoq/XamarinForms-Prism/blob/master/TabbedSample/TabbedSample/TabbedSample/ViewModels/ShowsListPageViewModel.cs](https://github.com/qmatteoq/XamarinForms-Prism/blob/master/TabbedSample/TabbedSample/TabbedSample/ViewModels/ShowsListPageViewModel.cs)

I also tried OnNavigateTo, but of course, it didn't work because it isn't even a navigation page.

Thank you all!

**Comment by brianlagunas** [comment]
Use the IActiveAware interface available in the latest preview.

**Comment by riandesign** [comment]
I already tried it, but it doesn't work for me.
My code:
https://codepaste.net/ejqwar

**Comment by brianlagunas** [comment]
you'll need to provide a sample repro app. It works fine for me.

**Comment by riandesign** [comment]
You mean attach all files of my project?
Well, basically, I have an App.xam.cs with types registered, for instance:

`Container.RegisterTypeForNavigation<MainTabbedPage>();
Container.RegisterTypeForNavigation<MainPage>();
Container.RegisterTypeForNavigation<UsersPage>();`

I also have the pages into a simple TabbedPage.
And in the UsersPage, I have the code I showed you:
https://codepaste.net/ejqwar

There is nothing wrong with the NuGets, the output doesn't show any error and everything works fine, except this issue.

**Comment by brianlagunas** [comment]
No, I mean provide a link to a full working application that reproduces the issue.

**Comment by riandesign** [comment]
Here it is:
[www.riandutra.com/downloads/xamarin/MessengerIntrasocial.php](www.riandutra.com/downloads/xamarin/MessengerIntrasocial.php)

**Comment by brianlagunas** [comment]
I would prefer a GitHub repo. Thanks

**Comment by riandesign** [comment]
Ok. I am uploading to link below. Please, check it:
https://github.com/riandesign/IActiveAware-project

**Comment by brianlagunas** [comment]
You're not using the right version.. You need to be using the 6.3 preview.

**Comment by riandesign** [comment]
But how do I install it? I couldn't find it through Visual Studio NuGets.

**Comment by brianlagunas** [comment]
You have to select the "Include Prerelease" checkbox

**Comment by riandesign** [comment]
@brianlagunas , thank you so much for your help!!

**Comment by brianlagunas** [comment]
I'm glad I could help :)

**Comment by riandesign** [comment]
Hi, Brian. Sorry for re open this issue, but I'm facing another problem. Now, related to navigation page inside tabbe page.

Before, I had these pages:
```
<views:MainPage />
<views:GroupsPage />
<views:UsersPage />
```

And, it works correctly after your help.
However, if I change UsersPage to a navigation page, it doesn't work properly:

```
<NavigationPage Title="Contatos">
    <x:Arguments>
      <views:UsersPage />
    </x:Arguments>
  </NavigationPage>
```

I tried both INavigationAware and IActiveAware, but they didn't work.
Any idea?

**Comment by vhugogarcia** [comment]
Hello @riandesign I am trying to implement the same feature you were trying, however, I'm stuck on it, due the IsActive is never changing.

Is there way you could share some insights or samples about how you solve it, please?

Thanks in advance
