### ISSUE TITLE
Exceptions thrown during Module initialization shouldn't effect other Modules from initializing

### ISSUE THREAD

**Issue by BrettJaner** [PrismLibrary/Prism#916]
### Package info

- Platform: Windows 7
- Prism version: 6.0.1

### Repro steps

I've defined a ModuleCatalog, that aggregates many modules together.  I've done my best to assure that their Initialize() methods do as little as possible, but there are some cases where the Initialize() methods could throw an exception that I can't anticipate for.  An exception thrown in an Initalize() method, stops further modules in my ModuleCatalog from attempting to initialize.  I believe the ModuleManager should more gracefully handle this by attempting to load all modules and throwing an aggregate exception of the all failures.  Modifying the following function in the ModuleManager like so is along the lines of what I was thinking:

        protected void LoadModulesThatAreReadyForLoad()
        {
            var initializationExceptions = new List<ModuleInitializeException>();
            bool keepLoading = true;
            while (keepLoading)
            {
                keepLoading = false;
                IEnumerable<ModuleInfo> availableModules = this.moduleCatalog.Modules.Where(m => m.State == ModuleState.ReadyForInitialization);

                foreach (ModuleInfo moduleInfo in availableModules)
                {
                    if ((moduleInfo.State != ModuleState.Initialized) && (this.AreDependenciesLoaded(moduleInfo)))
                    {
                        moduleInfo.State = ModuleState.Initializing;

                        try
                        {
                            this.InitializeModule(moduleInfo);
                        }
                        catch (ModuleInitializeException e)
                        {
                            initializationExceptions.Add(e);
                        }

                        keepLoading = true;
                        break;
                    }
                }
            }

            if (initializationExceptions.Any())
                throw new AggregateException(initializationExceptions);
        }

If you're interested, here's my implementation of the ModuleCatalog:

    public class TypeModuleCatalog : ModuleCatalog
    {
        public Type[] ModuleTypes { get; set; }

        protected override void InnerLoad()
        {
            if (ModuleTypes == null)
                throw new InvalidOperationException("ModuleTypes Cannot Be Null");

            var nonModuleType = ModuleTypes.FirstOrDefault(x => !typeof (IModule).IsAssignableFrom(x));

            if (nonModuleType != null)
                throw new InvalidOperationException(string.Format("{0} does not implement {1}", nonModuleType.FullName, typeof(IModule).FullName));

            Items.AddRange(ModuleTypes.Select(CreateModuleInfo));
        }

        private static ModuleInfo CreateModuleInfo(Type type)
        {
            var nestedType = typeof(DirectoryModuleCatalog).GetNestedType("InnerModuleInfoLoader", BindingFlags.NonPublic);

            if (nestedType == null)
                throw new InvalidOperationException("Could not find nested type \"private class InnerModuleInfoLoader\" in Prism.Modularity.DirectoryModuleCatalog.");

            var methodInfo = nestedType.GetMethod("CreateModuleInfo", BindingFlags.Static | BindingFlags.NonPublic);

            if (methodInfo == null)
                throw new InvalidOperationException("Could not find \"private static ModuleInfo CreateModuleInfo(Type type)\" in Prism.Modularity.DirectoryModuleCatalog+InnerModuleInfoLoader.");

            return (ModuleInfo)methodInfo.Invoke(null, new[] { type });
        }
    }

And then I configure it like this, where the Module type is a class that implements IModule:

            Kernel.Bind<IModuleCatalog>().ToMethod(context =>
                new TypeModuleCatalog
                {
                    ModuleTypes = new[]
                    {
                        typeof(TeamOne.Module),
                        typeof(TeamTwo.Module),
                        typeof(TeamThree.Module)
                    }
                })
                .InSingletonScope();

**Comment by brianlagunas** [comment]
So essentially you are asking to queue up all the exceptions and then throw an exception that contains all the other exceptions?  Hmm.. I'm not sure if this is a change we should make.  Given how old this code base is, there could be a number of apps that are expecting and handling known exceptions.  If we change this behavior it may break all those apps. @briannoyes what are your thoughts on this change?

**Comment by BrettJaner** [comment]
Hi @brianlagunas, I can see where you're coming from.  The more I think about the above proposed change the more I realize how much more dangerous it could be than I originally thought.  Still I'm trying not to copy and maintain a separate version of the ModuleManager.  What if we just made LoadModulesThatAreReadyForLoad() a virtual method?  With an understanding of when/where the ModuleInfos go through ModuleState changes.  I should be able to do the following in a subclass of ModuleManager:

        protected override void LoadModulesThatAreReadyForLoad()
        {
            var initializationExceptions = new List<ModuleInitializeException>();

            while (true)
            {
                try
                {
                    base.LoadModulesThatAreReadyForLoad();

                    break;
                }
                catch (ModuleInitializeException e)
                {
                    initializationExceptions.Add(e);
                }
            }

            if (initializationExceptions.Any())
                throw new AggregateException(initializationExceptions);
        }

Thoughts?

**Comment by brianlagunas** [comment]
I think that is a reasonable change.  I would recommend testing this first to make sure it works as you expect.  Once you have verified it will fit your needs, submit a PR with the change.

**Comment by BrettJaner** [comment]
Worked like a charm.  Pull Reqeust is open.

**Comment by brianlagunas** [comment]
Thanks for the PR
