### ISSUE TITLE
DependencyService error in navigation

### ISSUE THREAD

**Issue by riandesign** [PrismLibrary/Prism#917]
I created a DependencyService similar to this:
https://github.com/PrismLibrary/Prism/blob/master/docs/Xamarin-Forms/5-Dependency-Service.md

In my project, I have a tabbed page inside a navigation. In one of the tabs, I have a listview. Thus, when user clicks on an item, another page opens over tabbed page:
await _navigationService.NavigateAsync("DetailPage", param, false);

In this DetailPage, I have this:

```
private readonly ISocket _socketService;
public DetailPageViewModel(ISocket socketService) {
_socketService = socketService;
}
```

However, when I try to navigate to DetailPage, it crashes and I got this exception:

```
Microsoft.Practices.Unity.ResolutionFailedException: Resolution of the dependency failed, type = "System.Object", name = "DetailPage".
Exception occurred while: Calling constructor RianProject.Views.DetailPage().
Exception is: ResolutionFailedException - Resolution of the dependency failed, type = "RianProject.ViewModels.DetailPageViewModel", name = "(none)".
Exception occurred while: Calling constructor RianProject.ViewModels.DetailPageViewModel(RianProject.Services.ISocket socketService).
Exception is: NullReferenceException - Object reference not set to an instance of an object.
-----------------------------------------------
At the time of the exception, the container was:

  Resolving RianProject.ViewModels.DetailPageViewModel,(none)
  Calling constructor RianProject.ViewModels.DetailPageViewModel(RianProject.Services.ISocket socketService)
```

If I remove `ISocket socketService` from page's construct, and use `DependencyService.Get<ISocket>` it crashes the same way. But if I don't use any dependency, it works well.

Another details is that if I user the same DependencyService in tabs in tabbedpage, it works well too.
The only problem I think is related to navigation. Perhaps, I am forgetting to do something.

Note: if I use the normal XF way, like the code below, it works:
`DependencyService.Get<ISocket>().Connect();`

Any idea?

**Comment by riandesign** [comment]
Actually, the problem occurs only when I use some method of the DependencyService in page's constructor, for instance:

```
public DetailPageViewModel(ISocket socketService) {
            _socketService = socketService;

            string getNews = _socketService.SocketOn("get news").ToString();
        }
```

If I don't use `string getNews = _socketService.SocketOn("get news").ToString();` in the constructor, it works fine.
But it's needed to use that, in this case.

**Comment by brianlagunas** [comment]
The issue is not clear.  It is not possible to diagnose your issue without having an app the reproduces the problem.  There are too many moving pieces that could be causing our problem.

**Comment by riandesign** [comment]
The problem occurs when user navigate from UsersPage to ConversationPage.
Please, check the codes:
https://github.com/riandesign/Test

Note: I didn't push all files because there are too many, but the main files are there.

**Comment by brianlagunas** [comment]
The project is missing a solution file and does not build.  I need a compiling project to debug

**Comment by brianlagunas** [comment]
Also, the app should only contain the files with the problem. Do not include everything.  Only what the issue is.  We want to focus.

**Comment by riandesign** [comment]
Right! I just pushed the files:
https://github.com/riandesign/Test

**Comment by brianlagunas** [comment]
Please create a project that reproduces your issue without including all the other pages.  Only the pages that are causing the issue.  Plus, the page that is in the expectation you pasted (DetailsPage) doesn't even exist in the solution.

**Comment by riandesign** [comment]
Sorry my mistakes, @brianlagunas !
Here a new link with files:
https://github.com/riandesign/RianTest/

Note: I said DetailsPage, but actually the name is ConversationPage.

**Comment by riandesign** [comment]
The problem is in: https://github.com/riandesign/RianTest/blob/master/MessengerIntrasocial/MessengerIntrasocial/ViewModels/ConversationPageViewModel.cs (line 41)

```
public ConversationPageViewModel(ISocket socketService) {
            _socketService = socketService;
            string te = _socketService.SocketOn("get required messages").ToString();
}
```
If I don't use _socketService (DependencyService), it works.

**Comment by brianlagunas** [comment]
This is because you have an issue with your code.  The SocketOn method is returning null.  Then you call ToString() on it which will throw a null ref exception because you can't ToString a null object.  If you just remove the ToString() method call it will work. Now you know what your problem is, and it's not Prism :)
