### ISSUE TITLE
[Win10 UAP] Updating a value inside DelegateCommand does not update the Binding / UI

### ISSUE THREAD

**Issue by Rhywden** [PrismLibrary/Prism#92]
If I change a bound property inside a DelegateCommand, the UI does not get updated. Any changes outside the command get picked up, though. The command does fire and the properties get changed. But the same code inside and outside the command does result in different outcomes.

The code in the viewmodel basically looks like this:

    privat string _test;
    
    public TestViewModel() {
        Test = "foo";
        SelectItemCommand = new DelegateCommand( () =>
        {
            Test = "baz";
        });
    }
    public string Test { get { return _test; } set { SetProperty(ref _test, value); } }

     //Result: "foo"

Please note that using SetProperty() actually doesn't matter. I could also set `_test` directly - as long as it's outside the command, it will get picked up. Inside - nothing. The code fires, the values get changed, the UI doesn't pick up the changes.

**Comment by Rhywden** [comment]
Okay, found a workaround - basically, instead of binding, say, textboxes directly to a `public Property() {get;set;}` I instead wrap the textbox in a Grid or StackPanel, bind an instance of a class to it (which sports the property I want) and then change the property of the instance.

So, if we had 

    public class Foo {
      private string _baz;
      public string Baz { get { return _baz; } set { SetProperty(ref _baz, value); } }
    }

with the MVVM doing this:

    private Foo _foo;
    public Foo { get { return _foo } }
    public Baz {get { return _foo.Baz; } set { _foo.Baz = value; } }

and XAML like this:

    <Grid DataContext="{Binding Foo}">
      <TextBox Text="{Binding Baz, Mode=TwoWay}" />
    </Grid>
    <TextBox Text="{Binding Baz, Mode=TwoWay}" />

... then we will see that upon doing either `_foo.Baz = "Arf"` or `Foo.Baz = "Arf"` or `Baz = "Arf"` only the textbox inside the Grid will be updated.

**Comment by brianlagunas** [comment]
There is no need for that "workaround".  You don't change anything "in a DelegateCommand", you are changing it within the ViewModel itself through a delegate method in response to the invocation of the Execute event in the DelegateCommand.  The original issue exists in your bindings not in the DelegateCommand.  Creating a binding to sub properties doesn't change anything related to the DelegateCommand.  This tells me it was something wrong with your initial bindings in your UI.

Are you invoking the SelectItemCmmand with a button click or something?  Just declaring the command will not cause the code within the delegate to be executed.

**Comment by brianlagunas** [comment]
Also, in your second example, you are not calling PropertyChanged in the setter of Baz, so of course your UI will not update.

**Comment by Rhywden** [comment]
Erm, the Command _does_ execute.

**Comment by brianlagunas** [comment]
That's good, that means you have something in your UI which is data bound to the command which will invoke it, causing your code within the delegate to execute.  Now you have to make sure you are properly calling PropertyChanged in the setters of your property, or use SetProperty, and that the bindings are configured properly in your view.  You also have to make sure you DataCOntext of your View is set properly.

**Comment by Rhywden** [comment]
Well, that's the thing: If I change the properties I want anywhere _but_ in the command, the changes get picked up.

**Comment by brianlagunas** [comment]
Something is weird then, because it works fine for me.  Try declaring you command like:

SelectItemCommand = new DelegateCommand(Execute);

void Execute()
{
    Property = "new value";
}

Does that make a difference for you?

**Comment by Rhywden** [comment]
Seems to have done the trick. I'm not quite sure what is different this time around.

Then again, VS 2015 still needs some wrinkles to be ironed out - the designer view keeps crashing even when I didn't change anything and sometimes namespaces simply vanish according to VS, necessitating a restart.
