### ISSUE TITLE
NavigationService page popping question XF

### ISSUE THREAD

**Issue by snowppy** [PrismLibrary/Prism#920]
I have been looking and haven't found a example of how to handle popping though the navigation service.

In the app I have a list page that navigates to a creation page. I want to navigate to the a new page after creation, so I want to pop the current page and navigate to the new page. 

The only way I can do that with navigation service is to call .GoBackAsync(); with a navigation parameter to signal the list page that it should navigate immediately to the new page. This can't be the correct way of handle this. Can some one point me to an example of how this case is handled ?

**Comment by rmenezes** [comment]
I'm not quite sure if I understood correctly your question but try to use:

```
NavigationService.NavigateAsync(new Uri($"http://tempuri.org/{nameOfNewPage}", UriKind.Absolute));
```

This will clear all the stack navigation and the user will not go back to the creating page.

**Comment by snowppy** [comment]
This is how my navigation stack looks like before the create page:
LwdMasterDetailPage/LwdNavigationPage/ProjectsListPage
so I navigate one level down to : 
LwdMasterDetailPage/LwdNavigationPage/ProjectsListPage/CreateProjectPage
i want to navigate to when I am finished with the create page:
LwdMasterDetailPage/LwdNavigationPage/ProjectsListPage/SessionsListPage

Which is essentially pop the create page and move to the SessionsListPage with the right navigation parameter.
 In the suggestion above I will loose the first part of the path so any back action will not navigate correctly.

**Comment by brianlagunas** [comment]
@snowppy, @rmenezes was suggesting to use an absolute URI and provide the entire stack you wish to have which will reset the navigation stack and deep link you to exactly where you want to be.

`NavigationService.NavigateAsync(new Uri($"app:///LwdMasterDetailPage/LwdNavigationPage/ProjectsListPage/SessionsListPage", UriKind.Absolute));`

**Comment by snowppy** [comment]
Thanks I will try it out.  @ brianlagunas How is this handled internally, will the request for an absolute path remake all the pages or it will reuse the existing and just create the last page on the navigation?

**Comment by brianlagunas** [comment]
@snowppy I don't think using an absolute URI is the best solution.  I will see about adding the ability to remove a view based on name.

`INavigationService.Remove("Name")`

Though, this gets very tricky if you have more than one instance of the same page, so maybe you provide an index to remove instead?

`INavigationService.Remove(2)`

**Comment by brianlagunas** [comment]
@snowppy so answer your question, it recreates eveything

**Comment by snowppy** [comment]
@ brianlagunas Thank you for the explanation.  It would be nice to have the option as you suggest to be able to remove pages`INavigationService.Remove(2)`

**Comment by brianlagunas** [comment]
I think using the index based approach is safer and places the responsibility of knowing which page to remove on the developer, which I really like :)

**Comment by brianlagunas** [comment]
Let me know your thoughts on #921

**Comment by matrostik** [comment]
@brianlagunas 
>  to answer your question, it recreates eveything
So what the right way to load data? Right now i am using NavigatedTo method for that, but if my deep link too long it will load a lot of unnecessary data.

**Comment by brianlagunas** [comment]
You cache your data and load from the cache.  That way it is already in memory and very fast to load.
