### ISSUE TITLE
[XF] Add support for arrays in NavigationParameters *Breaking Change*

### ISSUE THREAD

**Issue by brianlagunas** [PrismLibrary/Prism#922]
Currently, the NavigationParameters for XF is a dictionary.  The problem is that because of this, we cannot pass an array as a URI query when navigating.

NavigateAsync("ViewA?car=dodge&car=ford&car=gmc");

We need to change the implementation of the NavigationParameters class to match the WPF implementation and fully support the URI query syntax for an array.

In order to minimize the API breaks, we will add the common Dictionary methods such as:
- ContainsKey
- TryGetValue

This will also allow us to move the WPF NavigationParameters class into the Prism.dll PCL to be shared across WPF, UWP, and Xamarin.Forms.

This will be a breaking change.  Thoughts?

**Comment by djcparker** [comment]
I haven't seem arrays url encoded like that for a while.  Most of the encoding I've seem recently are something like ViewA?car[]=dodge&car[]=ford&car[]=gmc

Not tried it recently though. 

I'm pretty sure jquery and  angular encode the same. 

Also, any impact on deep links?

In general, if it standardises all platforms then go for it.  As long as it is documented we can decide on taking the update and adjust our code.

**Comment by brianlagunas** [comment]
@djcparker both are valid URI's, and both would be supported.  This would no impact on deep linking.  It is solely to allow passing arrays via the URI query.

All breaking changes will be noted in the release notes, and blog post.  6.3 preview already contains some breaking changes as these types of issues are being discovered.

**Comment by djcparker** [comment]
@brianlagunas awesome! Sounds like a win all around.
