### ISSUE TITLE
Cannot create an instance of "WindowsPage"

### ISSUE THREAD

**Issue by weitzhandler** [PrismLibrary/Prism#923]
### Package info

- Platform: Windows 10 Home
- Prism version: Prism template pack: 1.8 - Libraries: 6.2.0
- Xamarin version (if applicable): 4.2.2.11
- Windows 10 SDK version (if applicable):  VS tools for UWP 14.0.25527.01
- Other version info: VS Community 2015 Update 3 (Ver. 14.0.25431.01)

### Repro steps

- Create a new Prism for Xamarin project and select all targets.
- Open MainPage.xaml file in one of the projects (designer not supported in the portable app at all).
- The following error shows up:
![](http://i.imgur.com/cVwMqvq.png)
- I'd like to mention that the project (tested the Windows one) builds and runs just fine. It's the designer that won't load.
And in text (outer to inner exception):

> **Exception: Cannot create an instance of "WindowsPage".**
>   at Microsoft.VisualStudio.DesignTools.Platform.InstanceBuilders.InstanceBuilderOperations.InstantiateType(Type type, Boolean supportInternal)
>    at Microsoft.VisualStudio.DesignTools.Platform.InstanceBuilders.ClrObjectInstanceBuilder.InstantiateTargetType(IInstanceBuilderContext context, ViewNode viewNode)
>    at Microsoft.VisualStudio.DesignTools.Platform.InstanceBuilders.ClrObjectInstanceBuilder.Instantiate(IInstanceBuilderContext context, ViewNode viewNode)
>    at Microsoft.VisualStudio.DesignTools.WindowsXamlDesigner.InstanceBuilders.FrameworkElementInstanceBuilder.Instantiate(IInstanceBuilderContext context, ViewNode viewNode)
>    at Microsoft.VisualStudio.DesignTools.WindowsXamlDesigner.InstanceBuilders.UserControlInstanceBuilder.Instantiate(IInstanceBuilderContext context, ViewNode viewNode)
>    at Microsoft.VisualStudio.DesignTools.Platform.InstanceBuilders.ViewNodeManager.CreateInstance(IInstanceBuilder builder, ViewNode viewNode)
> 
> **TargetInvocationException: Exception has been thrown by the target of an invocation.**
>   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
>    at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
>    at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
>    at System.Activator.CreateInstance(Type type, Boolean nonPublic)
> 
> **COMException: Error HRESULT E_FAIL has been returned from a call to a COM component.**
>    at Windows.UI.Xaml.Application.add_Suspending(SuspendingEventHandler value)
>    at System.Runtime.InteropServices.WindowsRuntime.WindowsRuntimeMarshal.NativeOrStaticEventRegistrationImpl.AddEventHandler[T](Func`2 addMethod, Action`1 removeMethod, T handler)
>    at System.Runtime.InteropServices.WindowsRuntime.WindowsRuntimeMarshal.AddEventHandler[T](Func`2 addMethod, Action`1 removeMethod, T handler)
>    at Xamarin.Forms.Platform.WinRT.WindowsBasePage..ctor()
>    at Xamarin.Forms.Platform.WinRT.WindowsPage..ctor()

**Comment by brianlagunas** [comment]
Prism has nothing to do with this.  We make no changes to the UWP MainPage.xaml or influence it in anyway.  The only change made to the platform projects is the addition of the platform initializer class.  other than that, Prism does not touch this.  The issues is something else.
