### ISSUE TITLE
Views without ViewModels are given parent ViewModel

### ISSUE THREAD

**Issue by wakemaster39** [PrismLibrary/Prism#924]
### Package info

- Platform: Windows 7 and 10
- Prism version: 6.2.0
- Other version info: Autofac 4.3.0, CommonServiceLocator 1.3.0

### Repro steps

As the title suggests, views that do not have a view model are being assigned a data context of the parent view. The issue is easily reproduced view navigation.  I have created an example project reproducing the problem [here ](https://github.com/wakemaster39/PrismNavigationAssigningParentViewModelExample)

Steps to run and illustrate the problem are in the readme of the repo. 

Here is a quick summary:
1. Have a View with a viewmodel,
2. Have a contentcontrol as a region in that view
3. Attempt to navigate to a view in that region that does not have a view model

In my example repo you will find that this problem exist for views created during the navigation process as well as views that are registered to a region during initialization. 

I tried to keep the example to as minimal code as possible, but in my additional testing I found that the viewmodel is given the DataContext at line https://github.com/PrismLibrary/Prism/blob/master/Source/Wpf/Prism.Wpf/Regions/Region.cs#L303.
Before this is executed, the DataContext is null, but afterwards it is set to the parents view model. Unfortunately, I have no idea where to go next to fix the problem from here. 

Any more details that are required I would be happy to supply. I have a work around for the problem, simply assigning DataContext=new object() on views that do not have view models works around the problem.

**Comment by bartlannoeye** [comment]
That's the default behavior of WPF (and any XAML language) that a control inherits the parent's DataContext if not explicitly set. What's the use of assigning DataContext=new object() ?

**Comment by wakemaster39** [comment]
@bartlannoeye, the second you mention this is the default behavior it all makes sense now about what was going on. Just looking over the basics. 

The point of assigning DataContext to new object was to not have the parents context assigned, thanks for helping me find the mistake.
