### ISSUE TITLE
Not able to catch exception thrown from DelegateCommand

### ISSUE THREAD

**Issue by eldhogeorge86** [PrismLibrary/Prism#927]
### Package info

- Platform: n.a
- Prism version: 6.2 for WPF
- Xamarin version (if applicable): n.a
- Windows 10 SDK version (if applicable): n.a
- Other version info:

### Repro steps

`ICommand cmd = new DelegateCommand(() => { throw new ArgumentException("test"); });`
`try`
`{`
`       cmd.Execute(null);`
`}`
`catch(Exception e)`
`{`
`}`

We are in the process of migrating our code from PRISM 4.1 to PRISM 6,2 when we realized the following problem:

With PRISM 4.1, in the above code snippet the catch block used to get executed. But with latest PRISM  the above catch block doesn't get executed. 

We feel the problem is due to the async/await pattern being used in DelegateCommandBase Execute method.

**Comment by dvorn** [comment]
@eldhogeorge86 This is fixed in 6.3.  See http://brianlagunas.com/prism-delegatecommand-fromasynchandler-is-obsolete/

**Comment by eldhogeorge86** [comment]
Thank you for the information. Could you let me know when PRISM 6.3 will be released?

**Comment by dvorn** [comment]
@eldhogeorge86 https://github.com/PrismLibrary/Prism/issues/650#issuecomment-274132112

**Comment by brianlagunas** [comment]
@eldhogeorge86 you can use the 6.3 preview that is on Nuget now.
