### ISSUE TITLE
Prism.Autofac -- Cannot Resolve INavigationService

### ISSUE THREAD

**Issue by adamcogx** [PrismLibrary/Prism#929]
I have seen this issue crop up in different places but none of the solutions work.

I have the following method in my App.cs class:

		protected override void RegisterTypes()
		{
			ContainerBuilder builder = new ContainerBuilder();

			var contentPageRoot = typeof(ContentPage).GetTypeInfo();
			var viewModelRoot = typeof(ViewModelBase).GetTypeInfo();
			var definedTypes = typeof(App).GetTypeInfo().Assembly.DefinedTypes;

			foreach (var page in definedTypes.Where(x => contentPageRoot.IsAssignableFrom(x))) {
				Container.RegisterTypeForNavigation(page.AsType(), page.Name);
			}

			builder.RegisterTypes(definedTypes.Where(x => viewModelRoot.IsAssignableFrom(x)).Select(x => x.AsType()).ToArray());

			builder.Update(Container);
		}

But when I run my application, I get:

An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = MainPage (ReflectionActivator), Services = [MainPage (Xamarin.Forms.Page)], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = OwnedByLifetimeScope ---> An exception was thrown while invoking the constructor 'Void .ctor()' on type 'MainPage'. ---> An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = MainPageViewModel (ReflectionActivator), Services = [Ditech.ViewModels.MainPageViewModel], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = OwnedByLifetimeScope ---> None of the constructors found with 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder' on type 'Ditech.ViewModels.MainPageViewModel' can be invoked with the available services and parameters:
Cannot resolve parameter 'Prism.Navigation.INavigationService navigation' of constructor 'Void .ctor(INavigationService)'. (See inner exception for details.) (See inner exception for details.) (See inner exception for details.)

I checked the Container in App, and the service is registered with Autofac, but is not visible during instantiation of the view model.

**Comment by brianlagunas** [comment]
I don't use Autofac, so I can't help you there. But, I noticed in the error message that you are asking for the INavigationService named "navigation" in a ctor of your VM.   This is not correct.  Is **must** be names navigationService (case sensitive) in order to work.

**Comment by adamcogx** [comment]
That is totally what the problem was!!  Is there any documentation anywhere that gives us these kinds of mappings (names -> type).

**Comment by brianlagunas** [comment]
Yes, this is documented here:  http://prismlibrary.readthedocs.io/en/latest/Xamarin-Forms/3-Navigation-Service/#getting-the-navigation-service

Luckily, this is the only service that has this limitation.  Everything else can be called whatever you want.

**Comment by devperson** [comment]
I had same issue. Thanks @brianlagunas

**Comment by KSemenenko** [comment]
@brianlagunas Pages from your link does not exist. And the problem is still there.

**Comment by dansiegel** [comment]
@kadamgreene the docs have been moved to the official Prism Library website... and the link is in the ReadMe... I also suggest you work with a better container as we are no longer supporting Autofac

**Comment by KSemenenko** [comment]
@dansiegel Thanks a lot.
