### ISSUE TITLE
[Prism.Forms] Does Prism.Forms Navigation work when navigating to a platform specific View?

### ISSUE THREAD

**Issue by PaybackMan** [PrismLibrary/Prism#93]
Hi guys, 

Trying to navigate from a XF ViewModel to another page which should render itself in a platform agnostic way.For now I have a PageRender inside of a Android class library. Library has a reference to my apps XF Core assembly. The ExportRenderer Attribute  in the Android assembly maps this to an Activity. When navigating nothing shows up in the Activity (no breakpoints hit in the PageRenderer either). Was thinking that INavigationService implementation in Prism.Forms doesn't use Xamarin Forms Navigation services...

Any idea here?
Thanks
  Travis

**Comment by brianlagunas** [comment]
The underlying Prism INavigationService does indeed use the XF navigation services.  Prism doesn't do anything different than if you weee to do it with XF, except it abstracts away the view stuff from your VM.

**Comment by PaybackMan** [comment]
Thanks Brian, I figured this out and it's nice to see that everything works.

Really looking forward to this api. Keep it up!
