### ISSUE TITLE
Already defines a member called InitializeComponent with the same parameter types

### ISSUE THREAD

**Issue by riandesign** [PrismLibrary/Prism#930]
I'm not sure if it's about PRISM, but I guess so.

I'm trying to create a custom cell, so a created a XAML, and in its code behind, I got the erro seen in the image I attached in this post.

Also, there are other errors:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0111	Type 'IncomingViewCell' already defines a member called 'InitializeComponent' with the same parameter types	RianProject	D:\_Projects\Rian\Dev\RianProject\RianProject\RianProject\obj\Debug\RianProject.CustomCells.OutgoingViewCell.xaml.g.cs	20	Active
```
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0121	The call is ambiguous between the following methods or properties: 'IncomingViewCell.InitializeComponent()' and 'IncomingViewCell.InitializeComponent()'	RianProject	D:\_Projects\Rian\Dev\RianProject\RianProject\RianProject\CustomCells\IncomingViewCell.xaml.cs	12	Active
```
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0103	The name 'InitializeComponent' does not exist in the current context	RianProject	D:\_Projects\Rian\Dev\RianProject\RianProject\RianProject\CustomCells\OutgoingViewCell.xaml.cs	12	Active
```

Any idea?

![pri](https://cloud.githubusercontent.com/assets/5668552/22480256/8c1b4f50-e7cf-11e6-9f95-afec4725e684.jpg)

**Comment by brianlagunas** [comment]
This has nothing to do with Prism.  This is a platform feature.  If you have a XAML file, then the code behind of that file requires a call to InitializeComponent.

You should check out this forum post that talks about creating ViewCells inXAML: https://forums.xamarin.com/discussion/20409/creating-a-custom-viewcell-in-xaml
