### ISSUE TITLE
[Xamarin.Forms Autofac] Register Prism services on CreateContainer method

### ISSUE THREAD

**Issue by akamud** [PrismLibrary/Prism#931]
According to [Autofac documentation](http://docs.autofac.org/en/latest/best-practices/#consider-a-container-as-immutable), it is recommended to register all services on Container's first build. I believe we could refactor Prism.Autofac.Forms to do that without any problem.

We should move [these](https://github.com/PrismLibrary/Prism/blob/master/Source/Xamarin/Prism.Autofac.Forms/PrismApplication.cs#L104-L118) lines to `CreateContainer`. 

If the user wishes to update the Container after the application Startup he could override `ConfigureContainer` with his registrations so Prism will add them after the initial setup. So this shouldn't be a breaking change for anyone.

What do you think? I could send a PR doing that if you believe this is correct.

**Comment by brianlagunas** [comment]
I have no knowledge of Autofac, so I leave it up to the community to support it.

**Comment by akamud** [comment]
From my understanding this refactor would be harmless to existing codebase and will then be following Autofac best practices.

I will write some tests and send a PR.

On a side note: I just cloned the repo and the XF.Autofac tests are broken because "Xamarin.Forms Init()" is not called. Do I have to do something else other than just cloning the repo?

**Comment by brianlagunas** [comment]
You can only run the XF tests using the "Test" build configuration

**Comment by akamud** [comment]
Is this documented somewhere that I missed? I think it is important to somehow document this for new contributors.

**Comment by akamud** [comment]
After taking a closer look at the code I saw that the `ConfigureContainer` is an abstract method, so we can't really make Autofac register everything at startup without calling this.

Prism would have to change this to make Autofac configuration work as suggested by the documentation. Now I'm not sure if this is really needed or worth the change... opinions?

**Comment by brianlagunas** [comment]
What's the benefit of doing this?  Do we gain anything?

**Comment by akamud** [comment]
I don't know :/
I'm not an Autofac expert either, so I'm not sure if this actually causes an unexpected behavior or if it is just a "best practice" to follow.

**Comment by brianlagunas** [comment]
Since we are unsure if the change will actually benefit us in any way, I am going to close this issue.  It can be reopened once someone can identify a technical reason why we should change it.  Thanks.
