### ISSUE TITLE
Xamarin forms, Master detail navigation problem

### ISSUE THREAD

**Issue by mister-giga** [PrismLibrary/Prism#934]
I have master-detal page named MsPage.  on initialized I navigate "NavigationPage/MsPage/DetailsListPage".
and now I have problem. on the item click in DetailsListPage I want to navigate whole page to a new page. I mean I want the navigation to happen from the very first NavigationPage. on the command I write "NavigationPage/ItemDetailPage", but it makes new navigation page inside MSPage's detail page
what am I doing wrong?

**Comment by brianlagunas** [comment]
Navigation is always relative by default, so by providing another navigationPage in your URI, you are creating a new nav page.  If you want o force a navigation from within the root NavigationPage, simply set the useModelNavigation parameter = fasle.
