### ISSUE TITLE
NavigateAsync doesn't navigate on xamarin forms ios project but work for android.

### ISSUE THREAD

**Issue by ShahriatHossain** [PrismLibrary/Prism#944]
I am having problem with NavigateAsync which stop to navigate to another page it doesn't move at all to next page on xamarin forms ios project but it is working good for android. It doesn't throw any exception so it is really strange to me. I have used 6.2.0 and even the latest but no effect. 
Here is my code example:

My Content Page:

`<Button Text="Search" Command="{Binding SearchCommand }" />`

My ViewModel:

public DelegateCommand SearchCommand { get; set; }

public MyViewModel(INavigationService navigationService)
{
_navigationService = navigationService;
SearchCommand = new DelegateCommand(NavigateToSearch);
}

private async void NavigateToSearch()
{
await _navigationService.NavigateAsync("SearchPage", null, false, false);
}

### Package info

- Platform:
- Prism version: latest
- Xamarin version (if applicable):
- Windows 10 SDK version (if applicable):
- Other version info:

### Repro steps

Please describe the issue/request in detail.

**Comment by brianlagunas** [comment]
I cannot reproduce this behavior.  Navigation works fine on iOS.  Can you please provide more detail?  What page are you navigating from?  What does the navigation stack look like?  I would start by removing all the content within the target page and see f it works.  Set a break point on the NavigateToSearch method and make sure it is being hit. check the result of the task to see if it was faulted.

**Comment by ShahriatHossain** [comment]
The problem I have found, I am calling a web api using await  and if api result success code 200 then navigateasync will be called like below:

JsonResponse result = await _apiService.MyMethod();
if(result != null)
{
  await _navigationService.NavigateAsync("SearchPage", null, false, false);
}
in this case, api  getting time to response and by this time SearchPageViewModel constructor is hitting but instead of moving to SearchPage it always stuck on the current page. 

can you suggest what should I do, because it seems on the latest version of prism synchronous method navigate is deprecated so I must use navigateasync method.

**Comment by brianlagunas** [comment]
Please do not double post.

https://forums.xamarin.com/discussion/comment/252643
