### ISSUE TITLE
Sorting pages within navigation journal? 

### ISSUE THREAD

**Issue by wowfood** [PrismLibrary/Prism#945]
Feature request for a way to either sort the navigation journal, or set some kind of priority pages. 

We potentially have a requirement where error pages will need to be displayed in the ui triggered by events.  Multiple errors could potentially appear at once so we need a way to sort the errors so the highest severity is displayed first.

Hence sorting the journal (so pages with higher priority can be brought to the top).  

If something like this already exists, or you have knowledge of a way I can already accomplish this in the existing structure please let me know, as I know this may be a bit of an edge case scenario.

**Comment by brianlagunas** [comment]
This is not something we will be adding to Prism.  The errors should simply track which page has the error and then you navigate to that page when you click on the error.
