### ISSUE TITLE
[XF] Support designating useModalNavigation for specific segments in Uri navigation

### ISSUE THREAD

**Issue by tossingc** [PrismLibrary/Prism#946]
Possibly use a reserved useModalNavigation query parameter to designate whether to use modal navigation or not - overrides value passed into NavigateAsync(..) method for a given segment.

This would be particularly useful when using UriKind.Absolute.  (deep linking to a modal data entry screen - e.g. "/NavigationPage/MainPage/ItemsPage/EditItemPage?id=5&useModalNavigation=true")

**Comment by brianlagunas** [comment]
Actually, this is being considered now.  If we did this, we would deprecate the NavigateAsync parameters in favor of using the uri query parameter.  This will also allow us to share the INavigationService across UWP making code sharing much easier.

**Comment by tossingc** [comment]
That's great news!  Any idea when that might be decided on and implemented?  I might have some bandwidth to help with the implementation.

**Comment by brianlagunas** [comment]
Feel free to take a stab at it.  I am in Japan for 2 weeks and will not have time to look at this anything soon.  It should be relatively simple.  I can't think of anything off the top of my head which would complicate it.  Of course, you won't know for sure until you start coding it and writing tests.

**Comment by brianlagunas** [comment]
Done
