### ISSUE TITLE
[XF] INavigationAware.OnNavigatedTo is silently hiding unhandled Exceptions

### ISSUE THREAD

**Issue by ederbond** [PrismLibrary/Prism#947]
Prism for Xamarin.Forms is silently hiding unhandled Exceptions that occurs on INavigationAware.OnNavigatedTo().

Note on the attached sample that the exception trown on Page2ViewModel.OnNagatedTo() doesn't shows anywhere on visual studio while debuging the app.

[PrismUnityApp1.zip](https://github.com/PrismLibrary/Prism/files/778068/PrismUnityApp1.zip)

**Comment by dvorn** [comment]
@ederbond My guess (without running your code):
```
        public DelegateCommand GoToPage2Command => new DelegateCommand(GoToPage2);

        private void GoToPage2()
        {
            navigationService.NavigateAsync("Page2");
        }
```
NavigateAsync returns a Task which may be faulted and may contain the exception.  You should observe the result of NavigateAsync (by awaiting on it).

**Comment by dvorn** [comment]
@ederbond Another potential problem is that you are using version 6.2 of Prism.  If the NavigateAsync method itself throws, the exception will be gobbled up by the DelegateCommand implementation.  You should upgrade to 6.3 where it was fixed.

**Comment by brianlagunas** [comment]
@dvorn is correct. You must await the task and the exception will then be thrown while debugging.

**Comment by ederbond** [comment]
@dvorn and @brianlagunas  do you have any idea of when Prism 6.3 will be lauched as stable on nuget.org ?  Currently my company's compliance avoids me to use non stable libraries.

**Comment by dvorn** [comment]
@ederbond Prism 6.3 is not strictly necessary to await ;-)
