### ISSUE TITLE
How to control the steps (Detail) of `ModuleManager` to Load modules  by myself?

### ISSUE THREAD

**Issue by huoxudong125** [PrismLibrary/Prism#949]
I want to override the `LoadModulesThatAreReadyForLoad` function in `Prism.Modularity.ModuleManager`  class for that:

I can control LoadModules orders by myself for Load `LoginModule`(**Which is my module for login,it will check the user is valid for the application,if the user is not valid, the application will  exit as soon as possible.and don't load other modules that login module is not depended**)

But the `InitializeModule` is private function.Is there a plan to allow user to  override the `LoadModulesThatAreReadyForLoad` function ?Or give a login module solution for prism application.

```
        /// <summary>
        /// Loads the modules that are not intialized and have their dependencies loaded.
        /// </summary>
        protected virtual void LoadModulesThatAreReadyForLoad()
        {
            bool keepLoading = true;
            while (keepLoading)
            {
                keepLoading = false;
                IEnumerable<ModuleInfo> availableModules = this.moduleCatalog.Modules.Where(m => m.State == ModuleState.ReadyForInitialization);

                foreach (ModuleInfo moduleInfo in availableModules)
                {
                    if ((moduleInfo.State != ModuleState.Initialized) && (this.AreDependenciesLoaded(moduleInfo)))
                    {
                        moduleInfo.State = ModuleState.Initializing;
                        this.InitializeModule(moduleInfo);
                        keepLoading = true;
                        break;
                    }
                }
            }
        }
```

In fact **,I want to use a login module to decide which module is loaded,and some module need the userinfo to initialize the module for load user's private data.**

Could you give a Idea? Many Thanks.

**Comment by brianlagunas** [comment]
If all you want to do is load modules based on a user roles, then this can be done without having to modify this code.  Just prompt for login when the app starts, get a list of the modules that they have rights to, and then add them to the module catalog and load them.

I'm not sure exactly why you are going through the trouble of creating a new ModuleManager class.  if anything, you would probably want to be looking at an IModuleInitializer instead.

**Comment by brianlagunas** [comment]
I would also like ot mention that these types of questions are better suited on our StackOverlow.

http://stackoverflow.com/questions/tagged/prism

**Comment by huoxudong125** [comment]
If the login is separate module `L` need a service in another module `A`, I want to load service module `A` first then load the  login module `L`. then load the other module such as module `B`,module ` C`.
```
             Yes            
A-->L-- ---->B->C
        | 
        |  'No'
        |----Exit

```
I need load the module `B`,'C'  in login module as dynamic load modules?

**Comment by brianlagunas** [comment]
This is a very custom scenario.  Luckily, you have all the source code available to you to use to meet your needs.  Unfortunately, this is not something I will be adding to the Prism framework.  Good luck.

**Comment by dvorn** [comment]
@huoxudong125 You can use module dependencies for that.  E.g., C depends on B; B depends on L; L depends on A.

**Comment by huoxudong125** [comment]
@dvorn I need to modify the `ModuleManager` to  procees modules load steps.Yes?

 How to gracefully exit form the progress of load modules, when invalid user login.I want to add a separate module for login and integrate the login module easily to Prism Application ,don't need to modify more code.

So I want to load login module first ,then check user is valid  or not when login module is loaded.if user is not valid ,exit application as soon as possible.

**Comment by dvorn** [comment]
@huoxudong125 Did you tried this: https://www.pluralsight.com/courses/prism-loading-modules-user-roles ?  I did not watched it myself yet, however I would assume that in the course all problems of this kind are discussed and resolved.

**Comment by huoxudong125** [comment]
@dvorn Thanks  for your replies
