### ISSUE TITLE
[UWP] AutoWireViewModel from another assembly using Unity?

### ISSUE THREAD

**Issue by veccie** [PrismLibrary/Prism#95]
Is it possible to use Unity to locate a viewmodel from another assembly when using AutoWireViewModel?

Right now the code below is used to locate a viewmodel, but this only works when the viewmodel is in the same assembly as the view/page.
```
static Func<Type, Type> _defaultViewTypeToViewModelTypeResolver =
    viewType =>
    {
        var viewName = viewType.FullName;
        viewName = viewName.Replace(".Views.", ".ViewModels.");
        var viewAssemblyName = viewType.GetTypeInfo().Assembly.FullName;
        var suffix = viewName.EndsWith("View") ? "Model" : "ViewModel";
        var viewModelName = String.Format(CultureInfo.InvariantCulture, "{0}{1}, {2}", viewName, suffix, viewAssemblyName);
        return Type.GetType(viewModelName);
    };
```
What can be added in PrismUnityApplication in order to change the default locator?

Is it even possible?

**Comment by briannoyes** [comment]
If you take a look at the ReferenceImplementation app (AdventureWorks Shopper) in the Prism for Windows Runtime releases (1.0, 1.1, and 2.0), the ViewModels and client services are in a separate UILogic library, and in OnInitialize in the app class, the type resolver is replaced with this:

            ViewModelLocator.SetDefaultViewTypeToViewModelTypeResolver((viewType) =>
                {
                    var viewModelTypeName = string.Format(CultureInfo.InvariantCulture, "AdventureWorks.UILogic.ViewModels.{0}ViewModel, AdventureWorks.UILogic, Version=1.0.0.0, Culture=neutral, PublicKeyToken=634ac3171ee5190a", viewType.Name);
                    var viewModelType = Type.GetType(viewModelTypeName);
                    return viewModelType;
                });

**Comment by veccie** [comment]
Ok, I'll try that. Thanks.
