### ISSUE TITLE
[WPF] Scoped regions inconsistent behavior

### ISSUE THREAD

**Issue by dvorn** [PrismLibrary/Prism#953]
### Package info

- Platform: WPF
- Prism version: All, starting from day one (1.0)

### Repro steps
```
region1.Add(view, null, true); // New RegionManager assigned to view
region1.Remove(view) // view's RegionManager remains assigned
then either
region2.Add(view)  // view's RegionManager replaced by region2's RegionManager
or
region2.Add(view, null, true) // view's RegionManager replaced by yet another new RegionManager.
region2 may be the same or another region
```

Note that if the view had been added to region1 as not scoped, removing it will clear the view's RegionManager.

So, what was the purpose of leaving the scoped RegionManager assigned to the view when the view was removed from region1?  That instance of RegionManager cannot be re-used.  It will be thrown away when the view is re-added to (another or the same) region.

The related test https://github.com/PrismLibrary/Prism/blob/master/Source/Wpf/Prism.Wpf.Tests/Regions/RegionFixture.cs#L565 is meaningless: it will succeed even when you remove the line
```
view.ClearValue(RegionManager.RegionManagerProperty);
```
What this test is trying to verify?  Shouldn't this test fail with this line removed? (Which is implied by the name of the test method.)

I would like to clarify whether this was an intentional behavior and if yes, what was the reason for it.
This is an undocumented behavior, and my question is shouldn't we change it and make explicit?

**Comment by brianlagunas** [comment]
This is code that was written by the MS P&P team a long time ago.  I have no knowledge of why it behaves the way it does.  I don't know if it was on purpose, or if it's a bug.  @briannoyes was around when this code was written, maybe he can shed some light on the issue.

**Comment by dvorn** [comment]
Some information is here: http://compositewpf.codeplex.com/workitem/7381

**Comment by dvorn** [comment]
To summarize what I found in workitem 7381:

1. Indeed, there was an intention to reuse the scoped region manager (DCherubini):

> Based on our understanding, we believe that the reason why the region manager is removed only if it’s the same that the hosting region (that is, the view being removed doesn’t have an scoped region manager) is that there might be an intention to support the scenario of being able to “move” an already created view, with its corresponding region manager, scoped regions and views, to a different region. 

2. The API does not allow to that anyway.

3. Moreover, attempting to reuse a view with scoped region manager leads to crash.  The root cause for the crash has not been determined, but the attached region manager is definitely participating, since removing it causes to crash to go away.

4. The aforementioned test, if it was trying to verify that reuse without the attached region manager works, is incorrect.  The crash happens when a) there are nested regions in the view and b) you add and remove the view twice.

**Comment by dvorn** [comment]
Update:

3.  There is a bug in RegionManagerRegistrationBehavior.  It is re-entrant and incorrect.  As a consequence, the following does not work:
```
region1.Add(view, null, true); 
region1.Remove(view); 
region2.Add(view, null, true)
```
However the view still may be reused as a workaround by
```
region1.Add(view, null, true); 
region1.Remove(view); 
view.ClearValue(RegionManager.RegionManagerProperty);
region2.Add(view, null, true)
```
This will result, however, in a new instance of scoped region manager attached to the view.  Fortunately, the popular RegionManagerAwareBehavior can handle this - IRegionManagerAware.RegionManager will be updated.

It is possible to fix RegionManagerRegistrationBehavior by either reordering the assignments in TryRegisterRegion method, or by using an "updating" flag to prevent reentrancy.

With the fixed behavior, the first scenario above will work without clearing the region manager property.

Also, the fixed behavior potentially allows to re-use the scoped manager instance, but the current IRegion does not have a method to do this.  Changing the IRegion would require a new release of Prism, this cannot be done via extensions.

Given that there are many third-party behaviors and a lot of existing program using Prism that may rely on the current, even if erroneous, behavior of RegionManagerRegistrationBehavior, it would be better to leave it as is.

**Comment by brianlagunas** [comment]
Yeah, unfortunately this is one of those high risk areas of the code.  Changing this will most certainly cause any number of production applications to break.  Hunting down the break will be very difficult for anyone as it will be so subtle and in a very complex portion of their app.  Thank you for documenting this as now we know of it's existence and work-around.

I think I will add a "known issues" section to the docs for things like this.
