### ISSUE TITLE
ObservePropertyChange does not work, when viewmodel raise PropertyChanged with String.Empty

### ISSUE THREAD

**Issue by johgoe** [PrismLibrary/Prism#963]
ObservePropertyChange does not work, when viewmodel raise PropertyChanged with String.Empty,

DelegateCommandBase.cs#L119  

> if (_propertiesToObserve.Contains(e.PropertyName))

 match only the property name but it should also raise L120  

> RaiseCanExecuteChanged();

 if (e.PropertyName == string.Empty) and _propertiesToObserve contains one or more entries.

### Repro steps

1) Create a view model implements INotifyPropertyChanged.
2) Observes a propery 
3) Raise PropertyChanged event in vm with string.Empty argument.

**Comment by brianlagunas** [comment]
How about a PR with tests?

**Comment by dvorn** [comment]
PR created: #964.

**Comment by brianlagunas** [comment]
Thanks for the PR @dvorn
