### ISSUE TITLE
XF NavigationParameters can't use new Dictionary initializer syntax anymore

### ISSUE THREAD

**Issue by jherby2k** [PrismLibrary/Prism#967]
### Package info

- Platform: XF
- Prism version: 6.3.0-pre2
- Xamarin version (if applicable): latest
- Windows 10 SDK version (if applicable):
- Other version info:

### Repro steps

With -pre1 I could do this:

new NavigationParameters { ["Id"] = "Test" })

but now it looks like the indexer isn't public, so I have to do this:

new NavigationParameters { { "Id", "Test"} })

Maybe there is a good reason, but I liked using the new syntax.

**Comment by brianlagunas** [comment]
If you read the release notes, this is noted as a breaking change because NavigationParameters is no longer a Dictionary.  It is now an IEnumerable.

https://github.com/PrismLibrary/Prism/wiki/Release-Notes-6.3.0-Pre2
