### ISSUE TITLE
Navigation in master detail cause reload of entire page on very navigation

### ISSUE THREAD

**Issue by v1rtu41m4n** [PrismLibrary/Prism#968]
When I navigate from my master to another detail view and y return to the original pages, this is loading everything like it was the first time, is this the expected behavior or what I am doing wrong?

this is what happening

1. from my login page y navigate to my master detail page with this:
 `
await _navigationService.NavigateAsync("/MainMasterDetailPage/NavigationPage/PageA");
`
2. then from my master page I navigate to another page detail with this:
`			await _navigationService.NavigateAsync(target);
`
where target equals `NavigationPage/PageB`
3. then I go back to my first detail pages with this:
`			await _navigationService.NavigateAsync(target);
`
where target equals `NavigationPage/PageA`

The problem is that the PageA is showed for the second time, it was executing everything like it was the first time (Constructor for example) and I am loosing the state of the page.

How could I prevent this? it is a bug or is there a work around

Any help should be appreciated.

**Comment by brianlagunas** [comment]
Please do not post the same question in multiple places.

This is the expected behavior.  Trying to keep pages in memory is a huge pain and has many unintended side effects, so it is best to recreate the page.  If you wish to have this behavior, you can manually control this with code-behind, or register your pages with the container as a singleton.

**Comment by v1rtu41m4n** [comment]
Thank you for your quick response!

I'll take your suggestion into account

How can I register my page in the container as singleton?

The method that I was using does not expose an argument for this `Container.RegisterTypeForNavigation<PageA>();`

If I register an instance of the page as this `var PageAInstance = new PageA();
			Container.RegisterInstance(PageAInstance);`

The the navigation occur it still creates a new instance, is there a way to register the pages keeping the navigation functionality? can you pleas give me an example?

**Comment by brianlagunas** [comment]
Your best bet would be to create your own extension method based off of the built-in functionality to add this.  https://github.com/PrismLibrary/Prism/blob/master/Source/Xamarin/Prism.Unity.Forms/UnityExtensions.cs#L17

Maybe something like:
```
public static IUnityContainer RegisterTypeForNavigationAsSingleton(this IUnityContainer container, Type viewType, string name)
{
    PageNavigationRegistry.Register(name, viewType);
    return container.RegisterType(typeof(object), viewType, name, new ContainerControlledLifetimeManager());
}
```

**Comment by v1rtu41m4n** [comment]
Thank you very much Brian, you save me a lot of researching time

**Comment by brianlagunas** [comment]
No problem.  This is my fault.  I haven't had time to write proper documentation on this feature yet.  You would have never found this on your own.  Glad I could help.

**Comment by v1rtu41m4n** [comment]
Hello Brian, me again.

I have a new problem with the working solution when I move to version 6.3.0-pre2, now when I come back to the page, it does not have a binding context it returns null. Is there something new that I have to consider to get this working again?

**Comment by brianlagunas** [comment]
Check your code. Prism doesn't null out any binding contexts when going back to a page.  The only pages that get a nulled binding context is the page that is being popped off the stack.

**Comment by brianlagunas** [comment]
Ahhhhh... You are using a singleton!  This is why.  Your pages remain in memory, except when they are popped off the stack, everything is cleaned up.  Once again, why using a singleton is problematic.

**Comment by v1rtu41m4n** [comment]
The scenario is:

I have a master detail showing a listivbiew with many items, like a fb timeline, the user interacts with it but it navigates to another page (from the master) to do anything else, when they return to this page, I want this pages in the same state that It was after I leave it. with the singleton, before I update to version 6.3 I was doing well, but after the update, when the page was loaded again it says that the binding context is null. I I don use a singleton, the the view model was recreated every time that I show this page it the described scenario.

**Comment by brianlagunas** [comment]
I under stand the scenario, but I can't think of a good solution right now.  Prism doesn't support singletons so I need to find a way to address this, but without impacting the current expected behavior.  The expectation is when a View is popped off the stack, its resources are cleaned up.  I might need to think of a way to override this to opt in to allowing the resources to remain in memory.

**Comment by dansiegel** [comment]
@v1rtu41m4n I get the scenario you have here. I still say a Singleton is a terrible idea for a View Or ViewModel and only leads to problems. You would be far better off serializing the data you need your ViewModel to have to recreate the state. There are a few options here:

1) You could store what you need in a SQLite table
2) You could save the data you need to the filesystem
3) (just thought of this one) we could add some new functionality to expose `Application.Properties` and `Application.SavePropertiesAsync()`

Unless I've missed something, I can't think of any reason you couldn't check for previous state and restore the state using `INavigatingAware`, `INavigatedAware` ( or the combination `INavigationAware`), or`IApplicationLifecycle`. Just as a verbose sample here:

```cs
public class MainPageViewModel : BindableBase, INavigationAware, IApplicationLifecycle
{
    private bool ShouldRestoreState = true;

    private void DoRestore()
    {
        // Implement your logic here
        ShouldRestoreState = false;
    }

    private void DoStateStore()
    {
        // Implement your logic here
        ShouldRestoreState = true;
    }

    #region INavigationAware

    public void OnNavigatingTo( NavigationParameters parameters )
    {
        DoRestore();
    }

    public void OnNavigatedTo( NavigationParameters parameters )
    {
        if( ShouldRestoreState )
            DoRestore();
    }

    public void OnNavigatedFrom( NavigationParameters parameters )
    {
        DoStateStore();
    }

    #endregion INavigationAware

    #region IApplicationLifecycle

    public void OnResume()
    {
        DoRestore();
    }

    public void OnSleep()
    {
        DoStateStore();
    }

    #endregion IApplicationLifecycle
}
```

If you're really stuck on the concept of using a SingletonPage adding the following would at least help ensure you have a ViewModel to attach, but it wouldn't really help you if you rely on parameters being passed in for `INavigationAware`

```cs
protected override void OnAppearing()
{
    base.OnAppearing();
    if( BindingContext == null )
    {
        Prism.Mvvm.ViewModelLocationProvider.AutoWireViewModelChanged( this, ( view, viewModel ) => BindingContext = viewModel );
    }
}
```
