### ISSUE TITLE
Get Stowed exception in UWP app - Dev Center reports

### ISSUE THREAD

**Issue by julciane** [PrismLibrary/Prism#971]
Hi all,
I have a UWP app published at Windows Store. This app uses Prism framework to control page navigation and events publish/subscription.
The reports from Microsoft Developer Center Health page shows me that more than 50% of reported crashes come from Prism. This is the failure name:
`STOWED_EXCEPTION_System.InvalidOperationException_80131509_MyAppName.dll!$58_Prism::Events::PubSubEvent$1_System::__Canon_.Subscribe`
Here is one of my subscription code:
`if (!eventAggregator.GetEvent<MySpecialEvent>).Contains(OnMySpecialEventActions))`           `{`
 `           eventAggregator.GetEvent<MySpecialEvent>().Subscribe(OnMySpecialEventActions, ThreadOption.UIThread);`
           ` }`
How can I avoid this crash?

**Comment by bartlannoeye** [comment]
Did you nail the exception down to this specific subscription? I haven't seen any reports on pubsub going wrong before, so we'll need all info available to dig into this as I can't point to a specific piece of code to pay attention to.

**Comment by dvorn** [comment]
@julciane InvalidOperationException is thrown in only one case - when you subscribe with ThreadOption.UIThread but the EventAggregator was not created on the UI thread.

**Comment by brianlagunas** [comment]
Unless you are doing something special, you should always use the default subscription thread which is the publisher thread.  Please update and let us now.  I am closing this unless you can repo the same behavior using the publisher thread.
