### ISSUE TITLE
Navigating from TabbedPage to other TabbedPage shows no ToolbarItems on navigated TabbedPage

### ISSUE THREAD

**Issue by KlockerTom** [PrismLibrary/Prism#976]
Hi @all!

I´m using the latest stable Prism Version 6.2 and the new Xamarin Forms 2.3.3.193. My MainPage is of type TabbedPage, and it shows 3 Content Pages as child and some ToolbarItems in it.
One ToolbarItem has a command which navigates (via the ViewModel) to a new TabbedPage. On this new TabbedPage there are also some ToolbarItems.
But these will not show.

When i downgrad to Xamarin Forms Version 2.3.3.180 it works, but with the new Xamarin.Forms Version it doesn´t.

Is there any solution to this or is it a XF Bug?

Thanks for any help
Greetings

Thomas

**Comment by KlockerTom** [comment]
Hi again,

now it´s getting more weird: i started the project with Xamarin Forms Version 2.3.3.180, and everything worked. Then i updated to 2.3.3.193, and it didn´t work anymore (no ToolbarItems visible on the TabbedPage to which i navigated).

Then i downgraded to Xamarin Forms 2.3.3.180 -> the ToolbarItems are still not visible! Once you updated to 2.3.3.193 you have the problem "in your project" and downgrading the Xamarin Forms version doesn´t help anymore.

That´s realy curious

**Comment by brianlagunas** [comment]
Hard to say without a repo.  The only way a toolbar shows up is if you are wrapped in a navigation page.  So as long as that exists it should work unless Xamarin broke something.  Prism does not control toolbars.

**Comment by KlockerTom** [comment]
Hi Brian,

here you will find the sample: https://github.com/KlockerTom/TestApp
As mentioned: this sample worked as expected, but after updating to Xamarin Forms 2.3.3.193 it didn´t work. Then i downgraded to 2.3.3.180, but it still doesn´t work.
Maybe you could have a look at it? It´s a very simple sample.

Thank you very much for your great work!!
Greetings

Thomas

**Comment by brianlagunas** [comment]
This happened because you are forcing a modal navigation which will replace the root of the application and you are no longer in the NavigationPage.  You need to change the useModalNavigation: true line and set it to false.

**Comment by KlockerTom** [comment]
Hi Brian,

 

thanks very much for your help. It works now (i´ve forgot to set a page title, that´s why the NavigationBar wasn´t showing).

But the problem is now that i have a „back“ button on the top left corner. When the user taps this button i need to call some

Async methods to save some stuff.

But i can´t trigger it when the user tapped this back button (except on UWP, there the OnBackButtonPressed event is invoked).

 

I´ve searched for two days now, but haven´t found any solution to solve this problem :(

Do you have any idea for this problem?

 

Thank you very much!

 

Greetings

Thomas

 

Von: Brian Lagunas [mailto:notifications@github.com] 
Gesendet: Montag, 13. März 2017 15:37
An: PrismLibrary/Prism <Prism@noreply.github.com>
Cc: KlockerTom <klocker.thomas@gmx.at>; Author <author@noreply.github.com>
Betreff: Re: [PrismLibrary/Prism] Navigating from TabbedPage to other TabbedPage shows no ToolbarItems on navigated TabbedPage (#976)

 

This happened because you are forcing a modal navigation which will replace the root of the application and you are no longer in the NavigationPage. You need to change the useModalNavigation: true line and set it to false.

**Comment by brianlagunas** [comment]
Prism 6.3.0-pre-2 has this built-in. Upgrade and the INavigationAware methods will be fired when you go back using the hardware/software buttons.
