### ISSUE TITLE
[XF]Apply EventToCommandBehavior to Element（Page and Cell）

### ISSUE THREAD

**Issue by nuitsjp** [PrismLibrary/Prism#978]
### Package info

- Prism version:6.3-pre2

### Repro steps
Now, the Generic Parameter of EventToCommandBehavir is View.
I want to change View to Element.
I also want to use it for events on Page and Cell.

Also, the test code will be green if the command is not executed.
I would like to add a test code.

![Element.Hierarchy](https://developer.xamarin.com/api/resource?id=source-id:10:Element.Hierarchy.png)

**Comment by dansiegel** [comment]
I feel like maybe I'm missing something here, but realistically only VisualElement's have Behaviors, not Elements. I totally understand if you wanted to attach this to a Page, and I think this was an oversight when it was originally added as it's not uncommon to want to attach to an event on the Page. But I would be curious as to your use of a Behavior on a Cell that doesn't have Behaviors.

That said if there is a reason to push it from VisualElement I would say we might as well push it to the root `BindableObject` like `BehaviorBase<T>`

**Comment by nuitsjp** [comment]
Sorry, it is my mistake. You are right.
Do not change to Element.

It is difficult to choose between BindableObject and VisualElement.
BindableObject does not have Behaviors. But Xamarin.Forms.Behavior <T> is BindableObject.

BindableObject seems good.
Just like Xamarin.Forms.Behavior <T>.

**Comment by nuitsjp** [comment]
#979 Completed.
Thank you review.

**Comment by brianlagunas** [comment]
Thanks for the fix!
