### ISSUE TITLE
Add PopupWindowActionRegionAdapter

### ISSUE THREAD

**Issue by ronin4net** [PrismLibrary/Prism#98]
Such an adapter would allow region specification directly on PopupWindowAction instead on embedded ContentControl/Presenter. This would slim-line the Xaml and support IInteractionRequestAware implementation by the DataContext - which does not work out of the box if the region is defined on an embedded content control.

A sample implementation can be found here: https://github.com/ronin4net/Plainion/blob/master/src/Foundation/Plainion.Prism/Interactivity/PopupWindowActionRegionAdapter.cs

I would like to contribute this to the library if interested.

**Comment by ronin4net** [comment]
I forgot to mention one drawback of the proposed solution. Pls refer to:
https://github.com/ronin4net/Plainion/blob/master/src/Foundation/Plainion.Prism/Interactivity/KeepAliveDelayedRegionCreationBehavior.cs

**Comment by brianlagunas** [comment]
After consideration, we have decided to not include this for now.  If enough people ask for it, we will revisit this decision.  I believe using a dialog service would be a better approach to this scenario.
