### ISSUE TITLE
Activation error occurred while trying to get instance of type DocumentRegionAdapter, key?...

### ISSUE THREAD

**Issue by nasheayahu** [PrismLibrary/Prism#987]
*Use GitHub issues for __bugs in Prism and feature requests only__. If you have a question how to implement something using Prism or a bug in your app that might be related to Prism, please post your question on [StackOverflow](http://stackoverflow.com/tags/prism) (which we monitor as well).*

Please provide as much detail as possible (and feel free to remove unused properties):

### Package info

- Platform: Windows 10 Pro
- Prism version: Prism.Mef.Wpf, 6.2.0.0

Hi,

I can't find how to create a RegionAdapter on the Prism Library doc's site, did a search using **RegionAdapterMappings** and when I click on the page hit I get, "SORRY This page doesn't exist yet."  Using the 5.0 doc's I get this exception asking for a key:

"**Activation error occurred while trying to get instance of type DocumentRegionAdapter, key**"

![screenshot 71](https://cloud.githubusercontent.com/assets/5845052/23928421/30e76434-08e5-11e7-9a61-a0109abc69c9.png)

I didn't need a key in 5.0 so how do I get this to work in 6.2?

**Here is my boot strapper code**:
![screenshot 70](https://cloud.githubusercontent.com/assets/5845052/23928462/88a7ae36-08e5-11e7-9bb1-2359adffd4c2.png)

**and here is my Region Adapter**:
![screenshot 69](https://cloud.githubusercontent.com/assets/5845052/23928486/a2c4f846-08e5-11e7-8d3a-07422ca3595a.png)

Can you link me to an updated doc on how to create an Adapter for 6.x?

Thanks!...

**Comment by brianlagunas** [comment]
You can find docs here: http://prismlibrary.readthedocs.io/en/latest/

Instead of using the ServiceLocator you could try using the Container.GetExportedValue method.  Other than that, I don't support MEF. Maybe you'll get lucky and have someone from the community help you out.

Don't use MEF, and everything will work.

**Comment by nasheayahu** [comment]
Thanks for the reply!

I so happen to have found the solution on the CodePlex site over looking [Prism Avalondock Extension](https://prismavalonextensions.codeplex.com/SourceControl/latest#Source/SampleApplication2/AppBootstrapper.cs) project AppBootstrapper.cs.  Even though it was using Unity as its container, but was using a different approach in initializing the Adapter which worked for me also.

`

            if (regionAdapterMappings != null)
            {
                IRegionBehaviorFactory factory = ServiceLocator.Current.GetInstance<IRegionBehaviorFactory>();
                regionAdapterMappings.RegisterMapping(typeof(LayoutDocument), new DocumentRegionAdapter(factory));
            }`
