### ISSUE TITLE
Navigation.RemovePage() for Login Pages

### ISSUE THREAD

**Issue by riandesign** [PrismLibrary/Prism#989]
In my app, I have a Login page.
After user login in the internal pages, if he uses the physical back button (Android), app backs to Login page.

How do I avoid that?

I tried `RemovePage()` but it seems Prism doesn't have this method, right?

Note:
I use a absolute URL to redirect user after login:
`await _navigationService.NavigateAsync("BaseNavigationPage/MainTabbedPage/MainPage");`

So, I initiate a new navigation an Login page is not part of it.

**Comment by brianlagunas** [comment]
You already have the solution.  You use an absolute path to reset the navigation stack.

**Comment by dansiegel** [comment]
@riandesign the URL you provided is a relative URL not absolute... to be absolute it would be `"/BaseNavigationPage/.."`

**Comment by riandesign** [comment]
Thank you all! @dansiegel it worked like a charm.
