### ISSUE TITLE
Add PopupFileDialogAction to support 100% MVVM file open/save dialog handling.

### ISSUE THREAD

**Issue by ronin4net** [PrismLibrary/Prism#99]
Pls have a look at:

https://github.com/ronin4net/Plainion/blob/master/src/Foundation/Plainion.Prism/Interactivity/PopupFileDialogAction.cs
https://github.com/ronin4net/Plainion/blob/master/src/Foundation/Plainion.Prism/Interactivity/InteractionRequest/OpenFileDialogNotification.cs
https://github.com/ronin4net/Plainion/blob/master/src/Foundation/Plainion.Prism/Interactivity/InteractionRequest/SaveFileDialogNotification.cs

It allows win32 FileOpen and FileSave dialog handling in a 100% mvvm style using interaction requests.

I would like to contribute this to Prism if interested.

**Comment by brianlagunas** [comment]
After consideration, we have decided to not include this for now.  If enough people ask for it, we will revisit this decision.
