### ISSUE TITLE
[XF] Tabbed page to content Page navigation hides tabs (useModalNavigation: false)

### ISSUE THREAD

**Issue by rupreetg** [PrismLibrary/Prism#991]
I've created a tabbed page like this  -
```
<TabbedPage xmlns="http://xamarin.com/schemas/2014/forms"
            xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
            xmlns:prism="clr-namespace:Prism.Mvvm;assembly=Prism.Forms"
            xmlns:pages="clr-namespace:Mobile.Views;assembly=Mobile"
            prism:ViewModelLocator.AutowireViewModel="True"
            x:Class="Mobile.Views.MainPage">

    <TabbedPage.Children>
        <pages:HomePage />
        <pages:FavoritesPage />
        <pages:NotificationsPage />
        <pages:SettingsPage />
    </TabbedPage.Children>

</TabbedPage>
```

I then initialize the app like this 
```
NavigationService.NavigateAsync("VLNavigationPage/MainPage/HomePage", animated: true);
```

In my HomeViewModel, I want to navigate to another content page which shows some result. I want to have  a back button which should bring me back to HomePage. I do -
```
  private async void ShowSearchResultPage()
        {
            if (!string.IsNullOrWhiteSpace(SearchText))
            {
                await navigationService.NavigateAsync($"SearchResultPage?searchKey={SearchText}", useModalNavigation: false);
            }
        }
```

When the SearchResultPage (it's a content page) opens, it opens as Modal Dialog and hides my tabs. Is this expected behavior when i specified userModalNavigation as false or am I missing something? I want to have my tabs visible and it should work as it's a child page of my first tab. 

I'm using Prism v6.2 and XF as v2.3.3.193

**Comment by brianlagunas** [comment]
If you want navigation to happen within a tab, you must wrap your tab in a NavigationPage.

**Comment by rupreetg** [comment]
Thanks Brian!

**Comment by espritm** [comment]
Any sample please ? I have same problem but I can't understand how to wrap my tab page in a navigation page.
If I do womething like :
```
NavigationService.NavigateAsync("VLNavigationPage/MainPage/HomePage", animated: true);
```
```

private async void ShowSearchResultPage()
        {
            if (!string.IsNullOrWhiteSpace(SearchText))
            {
                await navigationService.NavigateAsync($"NavigationPage/SearchResultPage?searchKey={SearchText}", useModalNavigation: false);
            }
        }


```
I have two title bars, one for MainPage and one for SearchResultPage, one below the other, and tabbar is still hidden

**Comment by brianlagunas** [comment]
It depends on what you are trying to do.  If you are navigating from within a Tab (which is actually a content page) then you need to wrap the actual tab item (the content page within the TabbedPage) in a NavigationPage.

Example:
```
<TabbedPage
    xmlns="http://xamarin.com/schemas/2014/forms"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:views="clr-namespace:MyApp.Forms.Views;assembly=MyApp.Forms"
    x:Class="MyApp.Forms.Views.MainTabbedPage">
	<TabbedPage.Children>
        <views:NavigationPage Title="Tab1">
            <x:Arguments>
                <views:Tab1Page />
            </x:Arguments>
        </views:NavigationPage>
	</views:TabbedPage.Children>    
</TabbedPage>
```

**Comment by espritm** [comment]
Thanks a lot for your answer Brian !
Ok I understand my mistake, I should do this : 
```
NavigationService.NavigateAsync("VLNavigationPage/MainPage/NavigationPage/HomePage", animated: true);
```
```
private async void ShowSearchResultPage()
        {
            if (!string.IsNullOrWhiteSpace(SearchText))
            {
                await navigationService.NavigateAsync($"SearchResultPage?searchKey={SearchText}", useModalNavigation: false);
            }
        }
```

And is it possible with the Query String ?
```
"MobileApp:///NavigationPage/TabbedPage?createTab=NavigationPage/Tab1&createTab=NavigationPage/Tab2"
```
I can't find a way to do it dynamically with Prism 7

**Comment by brianlagunas** [comment]
Please read the release notes, specifically the dynamic tab generation topic

https://github.com/PrismLibrary/Prism/releases/tag/7.0.0-Forms

You should be using a pipe not a slash.

**Comment by espritm** [comment]
> 
> Dynamic Tab Generation
> You can now dynamically create tabs when navigating to a TabbedPage by using the KnownNavigationParameters.CreateTab constant or by using the "createTab" parameter name.
> _navigationService.NavigateAsync("MyTabbedPage?createTab=ViewA&createTab=ViewB");
> This will create a TabbedPage and then create two tabs, ViewA and ViewB.
> To create a tab that wraps a page in a NavigationPage, simply denote this as a nested hierarchy using the | character.
> _navigationService.NavigateAsync("MyTabbedPage?createTab=NavigationPage|ViewA");
> 

Again thanks a lot for your help !!! That's what I missed ! 
This is exactly what I was looking for and it is working perfectly

So the correct query string is 
```
"MobileApp:///TabbedPage?createTab=NavigationPage|Tab1&createTab=NavigationPage|Tab2"
```
Cheers 👍
