### ISSUE TITLE
Dependency Injection failed

### ISSUE THREAD

**Issue by abdulraooof** [PrismLibrary/Prism#996]
I changed ViewmodelLocator & call login window before shell but when an error occurred type of interface can't be constructed. Here is code. when I do this then can't register services using RegisterType. Thanks in advance.

`base.OnStartup(e);
            DbInitializer.Initialize(new LogisticsContext());
            //Change ViewModel Locator Convention   
            ViewModelLocationProvider.SetDefaultViewTypeToViewModelTypeResolver(x =>
            {
                var viewName = x.FullName;
                viewName = viewName.Replace("Logistics.Services.Views.", "Logistics.Services.ViewModels.");
                var viewModelAssemblyName = "ViewModel";
                var suffix = viewName.EndsWith("View") ? "Model" : "ViewModel";
                var viewModelName = string.Format(CultureInfo.InvariantCulture, "{0}{1}, {2}", viewName, 
                    suffix, viewModelAssemblyName);
                return Type.GetType(viewModelName);
            });
            IUnityContainer container = new UnityContainer();
            ViewModelLocationProvider.SetDefaultViewModelFactory((type) =>
            {
                return container.Resolve(type);
            });

            //Open Login Window
            Current.ShutdownMode = ShutdownMode.OnExplicitShutdown;
            var logon = new LoginWindow();
            logon.ShowDialog();
            Current.MainWindow = null;
            Current.ShutdownMode = ShutdownMode.OnMainWindowClose;
            if ((bool)Current.Resources["IsAuthenticated"])
            {
                //Open Shell 
                var bootstrapper = new Bootstrapper();
                bootstrapper.Run();
            }
            else Current.Shutdown();`

**Comment by brianlagunas** [comment]
I'm sorry, but I do not understand what your issue is.  You changed the default implementation of ViewModelLocator, and it also looks like you are creating a new Unity container instance which is probably your issue.  I don't know what version of Prism or what platform you are targeting.  I would suggest backing out your changes until you find the error in your code.

**Comment by brianlagunas** [comment]
I also see that that you are trying to resolves things with your container instance with nothing registered and not in the bootstrapper.  Show the login in your bootstrapper before you show the Shell.

**Comment by abdulraooof** [comment]
When I call the login in bootstrapper it is always gives an error objectl reference not set to an instance of object exception.

`        protected override void InitializeShell()
        {
            //Open Login Window
            Application.Current.ShutdownMode = ShutdownMode.OnExplicitShutdown;
            var logon = new LoginWindow();
            logon.ShowDialog();
            Application.Current.MainWindow = null;
            Application.Current.ShutdownMode = ShutdownMode.OnMainWindowClose;
            if ((bool)Application.Current.Resources["IsAuthenticated"])
            {
                //Multiple ShellManager
                var regionManager = RegionManager.GetRegionManager((Shell));
                RegionManagerAware.SetRegionManagerAware(Shell, regionManager);
                //Open Bootstrapper Shell
                Application.Current.MainWindow.Show();
            }
        }`

**Comment by brianlagunas** [comment]
I don't know what any of the code means or its context.  You can't have a null MainWindow for an app.

**Comment by abdulraooof** [comment]
I am using prism 6.3 and I just want call login window before shell. Also my viewmodels are in a class library so that's why I changed the ViewModelLocator convention. As you said I have created another unity instance, Now I moved my code to bootstrapper but not as I told previously null reference exception. And I also implemented multiple shell strategy as you teach in PluralSight course. I hope now you would understand the exact problem. Here is my bootstrapper code.

`    public class Bootstrapper : UnityBootstrapper
    {
        public Bootstrapper()
        {
            //Change ViewModel Locator Convention   
            ViewModelLocationProvider.SetDefaultViewTypeToViewModelTypeResolver(x =>
            {
                var viewName = x.FullName;
                viewName = viewName.Replace("Logistics.Services.Views.", "Logistics.Services.ViewModels.");
                var viewModelAssemblyName = "ViewModel";
                var suffix = viewName.EndsWith("View") ? "Model" : "ViewModel";
                var viewModelName = string.Format(CultureInfo.InvariantCulture, "{0}{1}, {2}", viewName,
                    suffix, viewModelAssemblyName);
                return Type.GetType(viewModelName);
            });
        }
        protected override DependencyObject CreateShell()
        {
            return Container.Resolve<MainWindow>();
        }

        protected override void InitializeShell()
        {
            //Open Login Window
            Application.Current.ShutdownMode = ShutdownMode.OnExplicitShutdown;
            var logon = new LoginWindow();
            logon.ShowDialog();                   
            if ((bool)Application.Current.Resources["IsAuthenticated"])
            {
                Application.Current.ShutdownMode = ShutdownMode.OnMainWindowClose;
                //Multiple ShellManager
                var regionManager = RegionManager.GetRegionManager((Shell));
                RegionManagerAware.SetRegionManagerAware(Shell, regionManager);
                //Open Bootstrapper Shell
                Application.Current.MainWindow.Show();
            }
        }
        protected override void ConfigureContainer()
        {
            base.ConfigureContainer();
            ViewModelLocationProvider.SetDefaultViewModelFactory(type => Container.Resolve(type));
            //Register Services
            Container.RegisterType<IShellService, ShellService>(new ContainerControlledLifetimeManager());
            Container.RegisterType<IDialogService, DialogService>(new ContainerControlledLifetimeManager());
            Container.RegisterType<IUserRepo, UserRepo>(new ContainerControlledLifetimeManager());
            Container.RegisterType<IUserService, UserService>(new ContainerControlledLifetimeManager());
            //--Navigation--
            /*
             Some Navigation Registrations
*/
        }

        protected override IRegionBehaviorFactory ConfigureDefaultRegionBehaviors()
        {
            IRegionBehaviorFactory behaviors = base.ConfigureDefaultRegionBehaviors();
            behaviors.AddIfMissing(RegionManagerAwareBehavior.BehaviorKey, typeof(RegionManagerAwareBehavior));
            return behaviors;
        }

        protected override void ConfigureModuleCatalog()
        {
            base.ConfigureModuleCatalog();

            Type moduleViewsType = typeof(ViewsModule);
            ModuleCatalog.AddModule(new ModuleInfo()
            {
                ModuleName = moduleViewsType.Name,
                ModuleType = moduleViewsType.AssemblyQualifiedName,
                InitializationMode = InitializationMode.WhenAvailable
            });
        }
`

**Comment by brianlagunas** [comment]
You need to find out what is null.

**Comment by brianlagunas** [comment]
Also, if your not authenticated you are handing your app because you aren't closing it.
