### ISSUE TITLE
BindableBase.RaisePropertyChanged not virtual 

### ISSUE THREAD

**Issue by ChristianRiedl** [PrismLibrary/Prism#999]
Brian, in a lot of my sources I was overriding **OnPropertyChange** to inject additional functionality like "set dirty".
Unfortunatelly **RaisePropertyChanged** is not virtual. So I have got a problem now.
Can you imagine to change it to a virtual function ?

**Comment by brianlagunas** [comment]
No, you must now override the OnPropertyChanged(PropertyChangedEventArgs args) method.

**Comment by ChristianRiedl** [comment]
I was overriding the **virtual OnPropertyChanged (string propertyName).**
Exactly the function you renamed to **non virtual RaisePropertyChanged (string propertyName)**.
It was the easiest way to let SetProperty do what I want. 
I wonder why OnPropertyChanged(PropertyChangedEventArgs args) is still valid and virtual.

**Comment by brianlagunas** [comment]
They way it was done before was wrong.  OnPropertyChanged(PropertyChangedEventArgs args) was added to allow you to correctly override the behavior.

**Comment by ChristianRiedl** [comment]
OK. Thanks
